### ISSUE TITLE
能否同步到我的网站呢

### ISSUE THREAD

**Issue by magicdict** [521xueweihan/HelloGithub#1]
恭喜HelloGithub第一期发布。
能否同步到我的网站呢.不胜感激
http://codesnippet.info/

**Comment by magicdict** [comment]
https://github.com/magicdict/MongoCola
198个Star了，帮我完成200个Star吧，呵呵。

**Comment by 521xueweihan** [comment]
你好，magicdict：

《HelloGithub月刊》当然可以同步到你的网站。但是，我刚才尝试使用登录，无法登陆。没有任何错误提示。。。

**Comment by 521xueweihan** [comment]
@magicdict

**Comment by magicdict** [comment]
@521xueweihan 
不好意思，一直没有机会做测试，能再尝试一次吗？可能刚才Github服务不稳定，不好意思啊

**Comment by magicdict** [comment]
@521xueweihan 
there is a bug in login system, I am work with it.
i will fix the issue today,and could you kindly try again at tonight 21:00.
Thank you.

**Comment by 521xueweihan** [comment]
你好，我刚才我登录报错：

Error.  
An error occurred while processing your request.

**Comment by 521xueweihan** [comment]
@magicdict 好的 我晚上再试

**Comment by magicdict** [comment]
@521xueweihan 
已经修复登陆问题。
你登陆之后，我把你提升为特约作者，你有文章不用审核。
谢谢投稿。昨天由于我的问题，造成不便，不好意思。

**Comment by 521xueweihan** [comment]
@magicdict 
已经同步到http://codesnippet.info/，以后每个月的HelloGithub都会通过去。非常感谢🙏，给我特约作者的特权，望越做越好。
