### ISSUE TITLE
建议发布为 gitbook

### ISSUE THREAD

**Issue by hustcc** [521xueweihan/HelloGitHub#10]
只需要简单整理一下目录和首页即可。形成 GitBook 有利于大家阅读和分享。

**Comment by 521xueweihan** [comment]
感谢提供建设性意见，我会尽快整理出 GitBook 🙏

**Comment by 521xueweihan** [comment]
您好，非常感谢您的建议，GitBook地址：https://gitbook.hellogithub.com/

**Comment by 521xueweihan** [comment]
还有 HelloGitHub 所有的文章都是用了您的 `hint` 进行了样式的统一，改完后非常”清爽“

**Comment by TomShine** [comment]
GitBook看起开好多了
