### ISSUE TITLE
MVPArt 一个新的Android MVP 架构

### ISSUE THREAD

**Issue by JessYanCoding** [521xueweihan/HelloGitHub#100]
## 项目推荐
- 项目名称：MVPArt

- 项目地址：https://github.com/JessYanCoding/MVPArt

- 项目语言：java

- 项目描述：一个新的 MVP 架构,此框架旨在解决传统 MVP 类和接口太多,并且 Presenter 和 View 通过接口通信过于繁琐,重用 Presenter 代价太大等问题

- 截图：![overview](https://raw.githubusercontent.com/JessYanCoding/MVPArt/master/image/Architecture.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，已成功收录在 [HelloGitHub 第 19 期](https://hellogithub.com/volume/19/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，如果方便可以 Star ⭐️ 本项目，让更多人看到本项目。
