### ISSUE TITLE
YApi 是一个可本地部署的、打通前后端及 QA 的、可视化的接口管理平台

### ISSUE THREAD

**Issue by itgoyo** [521xueweihan/HelloGitHub#1002]
## 项目推荐
- 项目地址：https://github.com/YMFE/yapi

- 类别：JS

- 项目后续更新计划：

- 项目描述：
  - 必写：YApi 是一个可本地部署的、打通前后端及 QA 的、可视化的接口管理平台
 

- 推荐理由：用户不用特意到聚合数据网站上生成一堆无用的json数据，而是可以根据自己的需要生成数据然后返回数据，还可以本地部署。

- 示例代码：

```
npm install -g yapi-cli --registry https://registry.npm.taobao.org
yapi server 
```

- 截图：

![](https://raw.githubusercontent.com/itgoyo/PicGoRes/master/img/20191227112915.png)

**Comment by 521xueweihan** [comment]
类似项目推荐过很多次了，暂不收录啦～
