### ISSUE TITLE
Kitematic-可视化Docker容器管理

### ISSUE THREAD

**Issue by itgoyo** [521xueweihan/HelloGitHub#1003]
## 项目推荐
- 项目地址：https://github.com/docker/kitematic

- 类别：JS

- 项目描述：
  - 必写：可视Docker容器管理
 
- 推荐理由：
对于一些不是很熟悉Docker的用户，可以更简单快捷的启动容器还有实现端口的映射

- 截图：

![](https://raw.githubusercontent.com/itgoyo/PicGoRes/master/img/20191227113939.png)

**Comment by 521xueweihan** [comment]
描述可以再多一些～修改后@我
