### ISSUE TITLE
【自荐项目】flutter_easyloading UI 组件库

### ISSUE THREAD

**Issue by huangjianke** [521xueweihan/HelloGitHub#1008]
## 项目推荐
- 项目地址：https://github.com/huangjianke/flutter_easyloading

- 类别：其他(Flutter)

- 项目后续更新计划：会持续更新

- 项目描述：
  - 必写：flutter_easyloading 是Flutter平台的一个轻量级loading开源组件，适用于全局无context调用。

- 推荐理由：Flutter 目前生态还不够完善，很多组件需要自行封装，flutter_easyloading 简单易用，方便扩展，支持多种自定义样式，可以为Flutter开发者节省不少时间

- 截图：
<img src="https://raw.githubusercontent.com/huangjianke/flutter_easyloading/master/images/gif01.gif" width=250 height=535/> <img src="https://raw.githubusercontent.com/huangjianke/flutter_easyloading/master/images/gif02.gif" width=250 height=535/> <img src="https://raw.githubusercontent.com/huangjianke/flutter_easyloading/master/images/gif03.gif" width=250 height=535/>

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
