### ISSUE TITLE
一款可视化编辑手机H5页面的单页应用WebApp

### ISSUE THREAD

**Issue by answershuto** [521xueweihan/HelloGitHub#101]
## 项目推荐
- 项目名称：一款可视化编辑手机H5页面的单页应用WebApp

- 项目地址：https://github.com/answershuto/H5

- 项目语言：JavaScript

- 项目描述：

H5是一款可视化编辑手机H5页面的单页应用WebApp，可以根据用户的设计自动产生精美的H5界面。

类似市面上易企秀、简客这样的app。

这是我的个人项目，旨在学习Vue.js以及前后端开发流程。

- 推荐理由：有意思的项目

- 示例代码：

- 截图：
<img width="1280" alt="createnewwork" src="https://user-images.githubusercontent.com/17812136/29819941-5f777d26-8c88-11e7-9225-c8b9c4539c03.png">
<img width="1280" alt="design" src="https://user-images.githubusercontent.com/17812136/29819943-5f7ead08-8c88-11e7-99f2-1df394a7b94f.png">
<img width="1280" alt="login" src="https://user-images.githubusercontent.com/17812136/29819945-5f90bd40-8c88-11e7-8286-a0ea9d6fde75.png">
<img width="1280" alt="music" src="https://user-images.githubusercontent.com/17812136/29819942-5f79e124-8c88-11e7-96d6-38b3ea0fb2f5.png">
<img width="1280" alt="work" src="https://user-images.githubusercontent.com/17812136/29819944-5f8c18d0-8c88-11e7-88e6-1aef14a33a11.png">

<img width="1280" alt="login" src="https://user-images.githubusercontent.com/17812136/29819929-568fed9c-8c88-11e7-8b5a-fb3d51b6dcb8.png">

**Comment by 521xueweihan** [comment]
您推荐的项目，已成功收录在 [HelloGitHub 第 19 期](https://hellogithub.com/volume/19/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，如果方便可以 Star ⭐️ 本项目，让更多人看到本项目。
