### ISSUE TITLE
regexp-coder

### ISSUE THREAD

**Issue by snyang** [521xueweihan/HelloGitHub#1012]
## 项目推荐
regexp-coder
- 项目地址：
https://github.com/snyang/regexp-coder

- 类别：JS

- 项目后续更新计划：

- 项目描述：
帮助写JS/TS的正则表达式，写出来的效果，比较容易理解。
直接编写正则表达式的代码比较难于读懂。
这个工具提供了一个结构化，可以写出比较容易理解的正则表达式。

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？
帮助写JS/TS的正则表达式，写出来的效果，比较容易理解。

- 示例代码：（可选）长度：1-20 行
```typescript
import { RegExpCoder } from 'regexp-coder';

const subIP = /(\d|\d\d|1\d\d|2[0-4]\d|25[0-5])/;
const dot = /\./;
const ipv4Exp = RegExpCoder.new()
	.join(
		subIP,
		dot,
		subIP,
		dot,
		subIP,
		dot,
		subIP,
	)
	.enableMatchWhole()
	.toRegExp();

console.log(ipv4Exp.test('192.168.0.1')); // true
console.log(ipv4Exp.test('192-168-0-1')); // false
```

**Comment by fisker** [comment]
这例子...为什么我觉得`1?\d{1,2}`比`\d|\d\d|1\d\d`更好懂

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
