### ISSUE TITLE
PHP开源项目-cURL封装库

### ISSUE THREAD

**Issue by Linnzh** [521xueweihan/HelloGitHub#1013]
## 项目推荐
- 项目地址：[php-curl-class](https://github.com/php-curl-class/php-curl-class)

- 类别：PHP

- 项目后续更新计划：

- 项目描述：
  - 必写：该开源项目封装了PHP的cURL库，使得发送 HTTP 请求变得简单，并按标准格式返回响应数据
  - 可选：适用于需要PHP爬虫或者其他模拟访问的情况

- 推荐理由：减少了配置cURL时的繁琐

- 示例代码：

    ```php
    <?php
    // 获取豆瓣电影示例
    require '../vendor/autoload.php';
    
    use Curl\Curl;
    
    $curl = new Curl();
    $url = "https://movie.douban.com/j/search_subjects?type=movie&tag=%E8%B1%86%E7%93%A3%E9%AB%98%E5%88%86&sort=time&page_limit=20&page_start=1";
    $curl->get($url);
    $curl->setOpt(CURLOPT_SSL_VERIFYPEER, false);
    $curl->close();
    var_dump($curl->getResponse());exit;
    ```

- 截图：
    
    ![获取数据后存入数据库](https://user-images.githubusercontent.com/37938141/71565131-6f842f80-2ae6-11ea-88bf-95bcd749ed28.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 46 期](https://hellogithub.com/periodical/volume/46/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
