### ISSUE TITLE
PHP开源项目-Markdown文本解析库

### ISSUE THREAD

**Issue by Linnzh** [521xueweihan/HelloGitHub#1014]
## 项目推荐
- 项目地址：[parsedown](https://github.com/erusev/parsedown)

- 类别：PHP

- 项目后续更新计划：

- 项目描述：
  - 必写：该开源项目提供了标准Markdown文本解析为HTML字符串功能，一个小而美的解析器，并拥有良好的文档
  - 可选：适用于解析Markdown文本并输出为标准HTML的场景

- 推荐理由：
    1. 关于JavaScript解析Markdown文本的库有很多，但PHP在这方面就很少
    2. 该开源项目主文件只有一个，除了PHP版本限制必须高于 5.3 外几乎无依赖，可通过composer引入，也可以直接使用`Parsedown.php`文件
    3. 该项目中使用大量正则，也可作为学习正则表达式的项目
    4. 该项目使用了单元测试，想学习单元测试也可以看它

- 示例代码：

    ```php
    $Parsedown = new Parsedown();

    echo $Parsedown->text('Hello _Parsedown_!'); # prints: <p>Hello <em>Parsedown</em>!</p>
    ```

**Comment by 521xueweihan** [comment]
@Linnzh 您好，您推荐的两个 PHP 项目均已收录到 HelloGitHub 月刊中。这两个项目非常好，并且对新手十分友好。期待您后续推荐的项目，感谢！
