### ISSUE TITLE
【自荐】大前端面试宝典 - 图解前端

### ISSUE THREAD

**Issue by azl397985856** [521xueweihan/HelloGitHub#1015]
## 项目推荐
- 项目地址：https://github.com/azl397985856/fe-interview

- 类别：JS

- 项目后续更新计划：完善TODO，增加主题

- 项目描述：
  这是一份自己总结的关于准备前端面试的一个复习汇总项目，项目不定时更新。

  这不仅仅是一份用于求职面试的攻略，也是一份前端er用来检视自己，实现突破的宝典。 希望通过这个指南，大家可以打通自己的任督二脉，在前端的路上更进一步。

- 推荐理由：本仓库大量采用图的形式来传达知识，所谓一图胜千言，希望通过这种图文并茂的表达方式 让你更容易记住一些抽象，难以理解的概念，《图解前端》是我给它的副标题。

- 截图：

![logo](https://user-images.githubusercontent.com/12479470/61168590-1dc10a80-a583-11e9-9b1b-d08b0ddeec4d.jpg)
![SmartSelect_20190713-142136](https://user-images.githubusercontent.com/12479470/61168591-1dc10a80-a583-11e9-947e-3c9e4c71231a.jpg)
![SmartSelect_20190713-142204](https://user-images.githubusercontent.com/12479470/61168592-1e59a100-a583-11e9-99a7-deeb6f55aef5.jpg)

**Comment by 521xueweihan** [comment]
@azl397985856 您好，您推荐的项目将收录到本期月刊中。有以下几点个人建议：
1. 宇宙最强的前端面试指南（正在走向最强前端面试指南的项目）
2. 开源不易，坚持更难。请保持更新，完成 TODO 部分（加油！）
3. 每日一题的数据很有价值，可以数据持久化，便于管理和多平台同步

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 46 期](https://hellogithub.com/periodical/volume/46/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

**Comment by azl397985856** [comment]
@521xueweihan 感谢。 

1. 想改成“可能是西湖区最强的大前端面试宝典”
2. 尽量每个月至少更新一个TODO
3. 这个都是很好的资源，目前的想法是用github的功能。 之后会汇总整理，纳入专题等等。 

最后感谢你的认可和建议。
