### ISSUE TITLE
使用nodejs或者electron操纵小票打印机

### ISSUE THREAD

**Issue by boneVidy** [521xueweihan/HelloGitHub#1017]
## 项目推荐
- 项目地址：
https://github.com/boneVidy/node-escpos-addon
- 类别：请从中选择（JS）

- 项目后续更新计划：

- 项目描述：
  - 必写：nodejs和electron escpos binding,可以用来操纵小票打印机
  - 可选：收银机客户端
  - 描述长度（不包含示例代码）: nodejs和electron escpos binding,可以用来操纵小票打印机

- 推荐理由：比较适用与零售业客户端开发，让前端开发能借助这个库操纵小票打印机。

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
