### ISSUE TITLE
TinyIM

### ISSUE THREAD

**Issue by DennisThink** [521xueweihan/HelloGitHub#1018]
## 项目推荐
- 项目地址：https://github.com/DennisThink/TinyIM

- 类别：C++

- 项目后续更新计划：
  - 1. 完善项目的编译文档和使用文档。
  - 2. 增加使用UDP的P2P的方式传递文件。
  - 3. 增加Electron等跨平台的GUI,实现Windows、Linux、Mac系统通用(寻求合作者)。
  - 4. 增加IOS和Android的支持(寻求合作者)。
  - 5. 增加TinyIMBase版本,只有基础的消息架构,等待学习者填充业务逻辑的部分(业务逻辑稳定以后实现)。
  
- 项目描述：
  - 1. TinyIM是一个跨平台的IM项目,目前已经支持Windows和Linux,MacOS、IOS、Android需要寻求合作。
  - 2. TinyIM使用C++11进行开发,注释清晰详细,文档已经开始编写,以后会完善。
  - 3. TinyIM使用了Core和GUI分离开发架构,方便学习者使用不同的GUI栈进行开发。
  - 4. 支持开发IM的机器人,已经有简单的示例做演示。

- 推荐理由：跨平台、可选GUI实现、支持机器人开发。

- 截图：机器人和GUI聊天的一个示例
  ![机器人聊天演示](https://www.dennisthink.com/wp-content/uploads/2020/01/2019-12-31_183552.jpg)

**Comment by ChungZH** [comment]
请参考 #271 进行修改，现暂不收录。
