### ISSUE TITLE
入门C++数独项目

### ISSUE THREAD

**Issue by mayerui** [521xueweihan/HelloGitHub#1021]
## 项目推荐
- 项目地址：https://github.com/mayerui/sudoku

- 类别：C++
- 项目后续更新计划：加入保存进度功能等

- 项目描述：
C++实现的跨平台（linux、windows）数独游戏，可以在开发间隙用来放松身心。600余行代码，初学者也可以轻松掌握。

![image](https://user-images.githubusercontent.com/25812837/71639509-ec640480-2cb2-11ea-881d-8fd0c63ecc46.png)

**Comment by 521xueweihan** [comment]
有意思！建议修改项目 Readme 增加：
1. 项目运行步骤
2. 项目结构、文件说明

如果有详细讲解欢迎给我们投稿。

**Comment by mayerui** [comment]
感谢回复!@521xueweihan 
已完善Readme

**Comment by ChungZH** [comment]
@mayerui 再完善了一下，https://github.com/mayerui/sudoku/pull/2。

另：欢迎参与 https://github.com/HelloGitHub-Team/Article 项目，讲解一下您的项目！

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 46 期](https://hellogithub.com/periodical/volume/46/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
