### ISSUE TITLE
前后端分离的商城项目

### ISSUE THREAD

**Issue by liubin95** [521xueweihan/HelloGitHub#1022]
## 项目推荐
- 项目地址：https://github.com/liubin95/SanJuTou

- 类别：Java、JS、vue

- 项目后续更新计划：依赖mq的秒杀系统

- 项目描述：
  - 必写：springBoot+vue的项目。mybatis-plus的基本使用
  - 可选：适用于单体项目架构。学习基本的springBoot、vue和mybatis-plus
  - 描述长度（不包含示例代码）: 

- 推荐理由：自定义权限注解，参数统一校验，redis缓存，mq秒杀（开发中）

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
