### ISSUE TITLE
程序员必知必会的一款入门级的人脸、视频、文字检测以及识别的项目

### ISSUE THREAD

**Issue by GatesMa** [521xueweihan/HelloGitHub#1024]
## 项目推荐
- 项目地址：https://github.com/vipstone/faceai

- 类别：机器学习

- 项目后续更新计划：眼动追踪（待完善）、换脸（待完善）

- 项目描述：
FaceAI 是一款优秀入门级别的人脸、视频、文字：检测、识别的智能 AI 项目以及教程。他不仅包含最基本的人脸检测、识别（图片、视频）、轮廓标识、头像合成（给人戴帽子），还有表情识别（生气、厌恶、恐惧...）、视频对象提取、图片修复（可用于水印去除）、图片自动上色等等。

- 推荐理由：
推荐这个开源项目不是因为它的功能非常强大（现在的机器学习项目非常多），而是它的教程写的实在太好了，**真 · 入门级**，教你如何使用这个项目，做出上述功能来。在每篇功能文章的教程里，不仅仅写了每个功能的技术实现方案，还有具体重点关键代码的注释和解释以及具体实现，让你非常轻松的能够看懂，学习和使用。对于想要入门或者了解机器学习的初学者不能再友好了。

- 示例代码：
```python
# Tesseract Ocr文字识别
from PIL import Image
import pytesseract

path = "img\\text-img.png"

text = pytesseract.image_to_string(Image.open(path), lang='chi_sim')
print(text)

```

- 截图：
文字识别：
![image](https://user-images.githubusercontent.com/42234931/71704066-12a0b600-2e13-11ea-8962-20f2126e8d83.png)
表情识别：
![image](https://user-images.githubusercontent.com/42234931/71704092-3532cf00-2e13-11ea-92d9-f4682115b426.png)
性别识别：
![image](https://user-images.githubusercontent.com/42234931/71704111-50054380-2e13-11ea-903b-8cdd30ab8762.png)
人脸识别教程示意：
![image](https://user-images.githubusercontent.com/42234931/71704552-0a964580-2e16-11ea-94af-255d16f82466.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 46 期](https://hellogithub.com/periodical/volume/46/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
