### ISSUE TITLE
Transfer Learning

### ISSUE THREAD

**Issue by chsong513** [521xueweihan/HelloGitHub#1026]
## 项目推荐
- 项目地址：https://github.com/chsong513/TransferLearning

- 类别：请从中选择（Python、机器学习、迁移学习）

- 项目后续更新计划：

后面陆续集成其他的迁移学习方法。下一步计划：集成TCA
- 项目描述：
  - 必写：迁移学习算法集成包，集成了常见的经典的迁移学习等baseline方法，解决了寻找baseline源码困难，再现困难等问题。
  - 可选：适用于什么场景、能够让初学者学到什么
  - 描述长度（不包含示例代码）: 集成常见的经典的迁移学习

- 推荐理由：首个迁移学习算法集成包，解决了寻找baseline源码困难，再现困难等问题。

[introduce.txt](https://github.com/521xueweihan/HelloGitHub/files/4030153/introduce.txt)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
