### ISSUE TITLE
自荐项目：echat-plus

### ISSUE THREAD

**Issue by NemoHoHaloAi** [521xueweihan/HelloGitHub#1028]
## 项目推荐
- 项目地址：https://github.com/NemoHoHaloAi/wechat-plus

- 类别：Python

- 项目后续更新计划：
继续挖掘一些好玩的、有用的功能点，添加到项目中，让你的微信变得更有趣；

- 项目描述：
Python+网页版微信=更有趣的微信，借助Python的能力，利用微信打通手机和电脑，能够实现远程控制电脑、各种微信消息文件等的持久化存储、有趣的小功能触发，将你的微信打造成一个更强的随身工具箱。通过该项目对与Python初学者可以一个项目了解Python能做的很多很多事，只有想不到，没有做不到，同时因为结合微信，因此做出来的项目可以时时体验使用，具有很强的实用性；

- 推荐理由：
简单易上手，功能有趣，实用性强，例如微信消息文件音频视频等内容的持久化存储是很多同学都会遇到的问题，毕竟手机空间有限；

- 备注：之前该项目一直是private，因为里面有一些私人的信息，今天刚刚去除了个人信息，并重新开了个新仓；

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
