### ISSUE TITLE
cim

### ISSUE THREAD

**Issue by hellowHuaairen** [521xueweihan/HelloGitHub#1030]
## 项目推荐
- 项目地址：https://github.com/crossoverJie/cim

- 类别：Java
- 项目后续更新计划：持续更新中

- 项目描述：
  - 必写：一个不错即时通讯开源项目
  - 可选：可以满足基本的聊天功能
  - 描述长度（不包含示例代码）: CIM(CROSS-IM) 一款面向开发者的 IM(即时通讯)系统；同时提供了一些组件帮助开发者构建一款属于自己可水平扩展的 IM 。

- 推荐理由：基于Springboot的聊天系统，也超级实用的项目

- 示例代码：（可选）长度：1-20 行

部署 IM-server(cim-server)

```
cp /cim/cim-server/target/cim-server-1.0.0-SNAPSHOT.jar /xx/work/server0/
cd /xx/work/server0/
nohup java -jar  /root/work/server0/cim-server-1.0.0-SNAPSHOT.jar --cim.server.port=9000 --app.zk.addr=zk地址  > /root/work/server0/log.file 2>&1 &
```

部署路由服务器(cim-forward-route)
```
cp /cim/cim-server/cim-forward-route/target/cim-forward-route-1.0.0-SNAPSHOT.jar /xx/work/route0/
cd /xx/work/route0/
nohup java -jar  /root/work/route0/cim-forward-route-1.0.0-SNAPSHOT.jar --app.zk.addr=zk地址 --spring.redis.host=redis地址 --spring.redis.port=6379  > /root/work/route/log.file 2>&1 &
```

启动客户端
```
cp /cim/cim-client/target/cim-client-1.0.0-SNAPSHOT.jar /xx/work/route0/
cd /xx/work/route0/
java -jar cim-client-1.0.0-SNAPSHOT.jar --server.port=8084 --cim.user.id=唯一客户端ID --cim.user.userName=用户名 --cim.group.route.request.url=http://路由服务器:8083/groupRoute --cim.server.route.request.url=http://路由服务器:8083/login
```

- 截图：（可选）gif/png/jpg

![image](https://user-images.githubusercontent.com/19610305/71980337-b991b180-325a-11ea-9996-86434617e332.png)
![image](https://user-images.githubusercontent.com/19610305/71980371-ce6e4500-325a-11ea-8b9a-972cbe0e7ebe.png)
![image](https://user-images.githubusercontent.com/19610305/71980378-d62de980-325a-11ea-88ae-5e25dfc67794.png)

**Comment by 521xueweihan** [comment]
已推荐过
