### ISSUE TITLE
【自荐工具】showdoc，一个非常适合IT团队的在线API文档、技术文档工具

### ISSUE THREAD

**Issue by star7th** [521xueweihan/HelloGitHub#1031]
## 项目推荐
- 项目地址：

   https://github.com/star7th/showdoc

- 类别：PHP/JS

- 项目后续更新计划：

  完善网页交互体验
  完善移动端
  模板共享功能

- 项目描述：

  这是一个非常适合IT团队的在线API文档、技术文档工具。开发者可以用此来写出非常美观的API文档/数据字典和团队技术文档。同时其权限设置功能非常有助于团队协作。可以让初学者/老手均能释放自身生产力，用工具来解决自身在写文档的痛点。

- 推荐理由：写出非常美观的API文档/数据字典和团队技术文档。同时其权限设置功能非常有助于团队协作

- 截图
![image](https://user-images.githubusercontent.com/2200494/72030735-fdb99c00-32c4-11ea-8ce6-961f58ad652f.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 47 期](https://hellogithub.com/periodical/volume/47/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
