### ISSUE TITLE
基于t-io的即时消息通讯系统(包含android与web客户端)

### ISSUE THREAD

**Issue by comsince** [521xueweihan/HelloGitHub#1033]
## 项目推荐
* [即时通讯服务端](https://github.com/comsince/universe_push)
* [即时通讯web端](https://github.com/comsince/vue-chat)
* [即时通讯andorid端](https://github.com/comsince/android-chat)

- 类别：java, js

基于t-io的即时消息通讯系统，采用Dubbo，SpringBoot的分布式架构，可以衍生出推送，群组通讯的基础架构 ，支持docker,k8s快速部署。Android版本支持私聊，群聊，支持voip通话，支持语音，短视频，图片，位置发送。web客户端使用vue，基于websocket进行通讯

优势：基于自定义二进制协议，实现android端和web端消息互通
![image](https://github.com/comsince/universe_push/blob/master/attachment/vue-chat.png)

* [演示请点击](http://www.comsince.cn/chat)

**NOTE:** 由于服务器配置原因，目前没有对外注册，请使用下面的账号登录即可
```
帐号：13800000000, 13800000001, 13800000002
验证码：556677
```

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
