### ISSUE TITLE
『自推』前后端分离 CMS 系统，目前完成「博客」、「权限」、「代码段」功能

### ISSUE THREAD

**Issue by bihell** [521xueweihan/HelloGitHub#1039]
## 项目推荐
- 项目地址：

https://github.com/bihell/Dice

- 示例地址：

博客前端 http://bihell.com

管理前端 http://bihell.com/admin 账号：demo 密码：123456

- 类别：

Java、Js

- 项目后续更新计划：

后续主要完善一些细节代码，并把平时所学融合进去。近阶段会根据权限创建菜单，以及 opernresty 鉴权的优化。

- 项目描述：

* 基于`node` `java` `spring-boot` `vue` `nuxt` 开发的个人管理系统，目前已经实现「博客」、「权限管理」、「媒体库」、「代码段」功能
* 支持传统手动部署和`docker`部署
* 功能精简但齐全，界面简洁却美观，满足个人日常使用要求

- 推荐理由：

前后端分离、企业级鉴权系统，适合大家自己学习或进行企业应用开发。

- 截图：
![image](https://user-images.githubusercontent.com/19926035/72217199-35933e80-3566-11ea-96a5-0caf2f1b7dc0.png)
![image](https://user-images.githubusercontent.com/19926035/72217200-3d52e300-3566-11ea-8cf0-8e7c2d4db306.png)
![image](https://user-images.githubusercontent.com/19926035/72217203-4348c400-3566-11ea-8650-02b0142cfd3d.png)
![image](https://user-images.githubusercontent.com/19926035/72217206-4f348600-3566-11ea-90d0-439adbe341e1.png)
![image](https://user-images.githubusercontent.com/19926035/72217211-58255780-3566-11ea-8dd8-ff8892b49946.png)
![image](https://user-images.githubusercontent.com/19926035/72217222-72f7cc00-3566-11ea-948e-f8f4e9a3508c.png)
![image](https://user-images.githubusercontent.com/19926035/72217230-84d96f00-3566-11ea-9c8c-70df90349025.png)
![image](https://user-images.githubusercontent.com/19926035/72217232-8c007d00-3566-11ea-9c29-5d009e69ac76.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
