### ISSUE TITLE
Vue-3D-Model：一个展示三维模型的Vue组件

### ISSUE THREAD

**Issue by hujiulong** [521xueweihan/HelloGitHub#104]
## 项目推荐
- 项目名称：Vue-3D-Model

- 项目地址：https://github.com/hujiulong/vue-3d-model

- 项目语言：JavaScript

- 项目描述：一个展示三维模型的Vue组件

- 推荐理由：一个展示三维模型的 Vue 组件，支持模型操作和模型点击事件，能自动缩放模型到合适大小并校正偏移，目前支持 obj、stl、dae 和 json 格式的模型

- 示例代码：

```vue
<template>
    <model-obj src="example/models/obj/LeePerrySmith.obj"></model-obj>
</template>
<script>
    import { ModelObj } from 'vue-3d-model'

    export default {
        components: { ModelObj }
    }
</script>
```

- 截图：

![](https://github.com/hujiulong/vue-3d-model/blob/master/preview.gif?raw=true)

**Comment by 521xueweihan** [comment]
您推荐的项目，已成功收录在 [HelloGitHub 第 18 期](https://hellogithub.com/volume/18/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，如果方便可以 Star ⭐️ 本项目，让更多人看到本项目。

**非常酷的项目，感谢编写这么有意思的项目，赞 ！**
