### ISSUE TITLE
golang gorm 数据库映射工具

### ISSUE THREAD

**Issue by xxjwxc** [521xueweihan/HelloGitHub#1041]
项目推荐
项目地址：https://github.com/xxjwxc/gormt

类别：Go

项目后续更新计划：丰富函数。代码优化

项目描述：

必写：
一款 mysql 数据库转 golang struct 工具

- 一键生成golang结构,数据库操作函数
- 支持命令行及yml配置选项
- [自动生成快捷操作函数](https://github.com/xxjwxc/gormt/blob/master/data/view/genfunc/genfunc_test.go)
- [支持索引,外键](https://github.com/xxjwxc/gormt/tree/master/doc/export_cn.md)
- 带大驼峰命名规则
- 带json标签
- 支持界面操作

- 截图：（可选）gif/png/jpg

gui模式：
![ui_cn](https://user-images.githubusercontent.com/9114492/72814244-af7ea280-3c9f-11ea-9425-17e84a36cfff.gif)

命令行模式：
![out](https://user-images.githubusercontent.com/9114492/72814308-ce7d3480-3c9f-11ea-8f01-77566568de8c.gif)

**Comment by xxjwxc** [comment]
@521xueweihan  您好,我最近添加了界面交互。故做此更新

**Comment by 521xueweihan** [comment]
> @521xueweihan 您好,我最近添加了界面交互。故做此更新

棒，将在本期月刊中发布

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 46 期](https://hellogithub.com/periodical/volume/46/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
