### ISSUE TITLE
廖雪峰老师博客上的所有练习和作业都包含在该项目中

### ISSUE THREAD

**Issue by fanspaceshow** [521xueweihan/HelloGitHub#1042]
## 项目推荐
- 项目地址：https://github.com/seeways/PythonDemo

- 类别：请从中选择（Python）

- 项目后续更新计划：

- 项目描述：
  - 必写：廖雪峰老师博客上的所有练习和作业都包含在该项目中,另外有一些额外拓展的demo
  - 可选：
  - 描述长度（不包含示例代码）: 

- 推荐理由：让初学者可以参考的Demo

- 示例代码：

- 截图：

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
