### ISSUE TITLE
自荐项目 valval

### ISSUE THREAD

**Issue by taojy123** [521xueweihan/HelloGitHub#1043]
## 项目推荐
- 项目地址：https://github.com/taojy123/valval

- 类别：V（V语言）

- 项目后续更新计划：
   valval 会随着 V 语言同步更新，目标是打造 V 语言领域最好用的 web 框架

- 项目描述：
  valval 是一个基于 V 语言的 web 框架。V 语言是一门还在开发和完善过程中的语言，还不怎么成熟，但却十分适合用于 web 开发，不仅官方的标准库中提供了 vweb 以及 orm 的支持，不少开发者也都推出了各自的 web 开发框架，valval 就是其中之一。

- 推荐理由：
  valval 应该是目前众多框架（包括官方标准库 vweb）中最好用，功能最全的一个了。巧妙的利用 vue 实现了模板的功能，使用起来十分方便。

- 示例代码：

使用 docker 运行 V 语言环境 
```
$ docker run -it -p 8012:8012 --name vlang taojy123/vlang bash
```
安装 valval
```
$ git clone https://github.com/toajy123/valval
$ ln -s $(pwd)/valval ~/.vmodules/valval 
```
代码示例
```v
// demo.v
import valval

fn hello(req valval.Request) valval.Response {
    return valval.response_ok('hello world')
}

fn main() {
    mut app := valval.new_app(true)
    app.register('/', hello)
    valval.runserver(app, 8012)
}
```

运行服务
```
$ v run demo.v
ValvalApp running on http://0.0.0.0:8012 ...
working in: /root/valval_website
OS: linux, Debug: 1
Version: 0.1.0
```

- 项目官网: https://valval.cool

![](https://github.com/taojy123/valval_website/raw/master/static/valval_logo.png)

**Comment by 521xueweihan** [comment]
您好，因为月刊中支持的分类有限。将归到 其它 分类，进行推荐

**Comment by taojy123** [comment]
好的，新年好😄

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 46 期](https://hellogithub.com/periodical/volume/46/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
