### ISSUE TITLE
开源P2P互联网

### ISSUE THREAD

**Issue by tangdou1** [521xueweihan/HelloGitHub#1047]
## 项目推荐
- 项目地址：https://github.com/HelloZeroNet/ZeroNet

- 类别：Python

- 项目描述：
  - 这是一个使用 Bitcoin 加密和 BitTorrent 网络的去中心化网络，将传统巨头垄断的互联网变得平民化，人人可以轻松创建分布式博客、分布式论坛、分布式微博、分布式视频网站、分布式直播网站、分布式Github等等。
  - 能让初学者学习网站的建立过程和运行原理

- 推荐理由：不需要租用服务器不需要公网ip，人人可快速创建网站，促进学习互联网技术。

- 截图：
![68747470733a2f2f692e696d6775722e636f6d2f4836304f4148592e706e67](https://user-images.githubusercontent.com/35254744/72657508-1b32e800-39e0-11ea-978b-f2a5cfa23eb9.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 46 期](https://hellogithub.com/periodical/volume/46/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
