### ISSUE TITLE
开源资料管理

### ISSUE THREAD

**Issue by tangdou1** [521xueweihan/HelloGitHub#1048]
## 项目推荐
- 项目地址：https://github.com/zotero/zotero

- 类别：JS

- 项目描述：
  - 文献管理器
  - 学术研究，资源整理
  - zotero是开源的文献管理工具，可以方便的收集，组织，引用，和共享文献的工具。由安德鲁·w·梅隆基金会，斯隆基金会以及美国博物馆和图书馆服务协会资助开发。

- 推荐理由：极其好用

- 截图：
![screenshot-1 4](https://user-images.githubusercontent.com/35254744/53612758-bf684080-3c0e-11e9-83c4-91f609fbaecf.png)

**Comment by prateekrastogi** [comment]
LGTM
