### ISSUE TITLE
匀速贝塞尔曲线路径规划

### ISSUE THREAD

**Issue by csdjk** [521xueweihan/HelloGitHub#1049]
## 匀速贝塞尔曲线路径规划
- 项目地址：[https://github.com/csdjk/BezierCurvePathCreater](https://github.com/csdjk/BezierCurvePathCreater)

- 类别：JavaScript

- 项目后续更新计划：三阶贝塞尔曲线，界面优化，支持导出更多数据，切换分辨率等功能

- 项目描述：
  - 绘制贝塞尔曲线，常用于路径规划，支持匀速运动，可以导出路径数据用于项目中。
  - 适用于游戏开发者，前端，app等。

- 推荐理由：支持匀速贝塞尔曲线运动

- 截图：![在线绘制贝塞尔曲线](https://img-blog.csdnimg.cn/20200116192455200.gif)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
