### ISSUE TITLE
微信第三方客户端

### ISSUE THREAD

**Issue by trazyn** [521xueweihan/HelloGitHub#105]
## 项目推荐
- 项目名称：weweChat

- 项目地址：https://github.com/trazyn/weweChat

- 项目语言：JavaScript

- 项目描述：一个微信的第三方客户端

- 推荐理由：在完整实现 Web 微信功能的基础上，新增并优化部分功能，重设计整体UI，提供更好的体验。

- 示例代码：
`brew cask install wewechat`

- 截图：
![preview](https://raw.githubusercontent.com/trazyn/weweChat/master/screenshots/1.png)

**Comment by 521xueweihan** [comment]
@trazyn 请增加更详细的描述信息和推荐理由

**Comment by Xiaolang0** [comment]
我感觉这个项目挺好的啊，我已经用上了，界面清爽，还带有新的快捷键，防撤回等功能

**Comment by 521xueweihan** [comment]
@Xiaolang0 之前的推荐理由和描述信息，太简单了。

**Comment by 521xueweihan** [comment]
@trazyn 兄弟更新完信息怎么没 `at` 我一下。。。

**Comment by Xiaolang0** [comment]
@521xueweihan 他可能以为你知道 哈哈

**Comment by 521xueweihan** [comment]
@Xiaolang0 我的问题，我应该说明一下 😅

**Comment by trazyn** [comment]
在搬砖都没怎么看这些啊 😂

**Comment by Xiaolang0** [comment]
@521xueweihan 赞~

**Comment by qyuanmeng** [comment]
dalao有语言选项设置中文吗？

**Comment by trazyn** [comment]
目前主要改bug，没有做语言切换

**Comment by 521xueweihan** [comment]
您推荐的项目，已成功收录在 [HelloGitHub 第 18 期](https://hellogithub.com/volume/18/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，如果方便可以 Star ⭐️ 本项目，让更多人看到本项目。

**Comment by trazyn** [comment]
好的谢谢了

2017-09-29 0:08 GMT+08:00 削微寒 <notifications@github.com>:
