### ISSUE TITLE
推荐：p5.js http://p5js.org/

### ISSUE THREAD

**Issue by ZZY2357** [521xueweihan/HelloGitHub#1050]
## 项目推荐
- 项目地址：https://github.com/processing/p5.js

- 类别：JS

- 项目后续更新计划：

- 项目描述：
  - 必写：p5.js 是个 JavaScript 创意编程程式库，可以用来绘图，也提供了许多有用的函数。
  - 可选：适合JS新手，新手可以不管HTML和CSS，只写JS的代码
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：这是个创意编程的库，可以用它做出许多好玩的东西。文档齐全，官网有中文。还有专门的在线编辑器。有许多拓展库。

- 示例代码：
```js
function setup() {
  createCanvas(640, 480);
}

function draw() {
  if (mouseIsPressed) {
    fill(0);
  } else {
    fill(255);
  }
  ellipse(mouseX, mouseY, 80, 80);
}
```

- 截图：https://p5js.org/assets/img/get-started/first-sketch2.png

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 46 期](https://hellogithub.com/periodical/volume/46/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
