### ISSUE TITLE
自荐项目 Crawler-for-Github-Trending

### ISSUE THREAD

**Issue by ZY2071** [521xueweihan/HelloGitHub#1052]
## 项目推荐
- 项目地址：https://github.com/ZY2071/Crawler-for-Github-Trending

- 类别：JS

- 项目后续更新计划：根据 Github Trending 页面结构持续跟进更新

- 项目描述：一个简短的 node 爬虫项目，可以让对爬虫感兴趣的前端同学很简单的了解一下 node 爬虫相关模块以及流程

- 推荐理由：代码简单但五脏俱全，并且爬取的是 GitHub Trending，可以帮助自己更自定义的获取 GitHub Trending 上的信息。当然爬取其他网站想获取的数据也是类似的操作。

- 项目介绍：https://juejin.im/post/5cbab247e51d45789024d7cb
- 数据的展示：http://zy2071.com/Fun/todayGithub.html

**Comment by 521xueweihan** [comment]
HelloGitHub 后续会整合该功能，您的项目不能收录到月刊中。望理解

**Comment by ZY2071** [comment]
那请删除此 issue 吧

**Comment by ZY2071** [comment]
@521xueweihan

**Comment by ZY2071** [comment]
@521xueweihan

**Comment by jaywcjlove** [comment]
@521xueweihan 

每天自动更新了，利用 GitHub Actions Workflows 通过定时器，每天 00:00 (北京时间早上8:00) 触发 GitHub 的工作流，自动爬数据，将生成的 web 页面提交到 gh-pages 分支，并且自动发布 [`npm`](https://www.npmjs.com/package/@wcj/github-rank) 版本，每天的数据 在  [@wcj/github-rank/dist/](https://unpkg.com/browse/@wcj/github-rank/dist/) 目录中，方便你整合。

https://github.com/jaywcjlove/github-rank

**Comment by 521xueweihan** [comment]
> @521xueweihan
> 
> 每天自动更新了，利用 GitHub Actions Workflows 通过定时器，每天 00:00 (北京时间早上8:00) 触发 GitHub 的工作流，自动爬数据，将生成的 web 页面提交到 gh-pages 分支，并且自动发布 [`npm`](https://www.npmjs.com/package/@wcj/github-rank) 版本，每天的数据 在 [@wcj/github-rank/dist/](https://unpkg.com/browse/@wcj/github-rank/dist/) 目录中，方便你整合。
> 
> https://github.com/jaywcjlove/github-rank

收到！

**Comment by jaywcjlove** [comment]
@521xueweihan 你可以参考 [@jaywcjlove/github-rank](https://github.com/jaywcjlove/github-rank) 自己实现爬数据，利用 `GitHub Actions Workflows` 爬数据不会报错，目前没有一次失败过 :)
