### ISSUE TITLE
自荐项目-flask源码分析

### ISSUE THREAD

**Issue by Syncma** [521xueweihan/HelloGitHub#1053]
## 项目推荐

- 项目地址：
[Flask源码分析](https://github.com/Syncma/Learning-Note/tree/master/Flask%E6%BA%90%E7%A0%81%E5%88%86%E6%9E%90)

- 类别：Python

- 项目后续更新计划：  flask源码分析

- 项目描述：flask源码分析

  通过源码分析可以了解 [mitsuhiko 大神](https://github.com/mitsuhiko)的flask 思想
 

- 推荐理由： 深入flask 原理，想对WSGI原理有深入了解

- 目录展示

![bbe392a2-2b2b-43c7-8460-0eaf18c27877](https://user-images.githubusercontent.com/9897542/72780339-92bf7c00-3c59-11ea-98f4-77f493ced84f.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。（已发邮件联系您，期待您的回复。）

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
