### ISSUE TITLE
MusicLake

### ISSUE THREAD

**Issue by hellowHuaairen** [521xueweihan/HelloGitHub#1054]
## 项目推荐
- 项目地址：https://github.com/caiyonglong/MusicLake

- 类别：Java

- 项目后续更新计划：项目已完成。

- 项目描述：
  - 必写：音乐播放器，可播在线音乐，qq音乐，百度音乐，虾米音乐，网易云音乐，YouTuBe
  - 可选：安卓版仿网易云音乐
  - 描述长度（不包含示例代码）: 安卓版仿网易云音乐

- 推荐理由：持多平台音乐源，百度音乐，虾米音乐、网易云音乐、Youtube（需要翻墙），歌词播放、桌面歌词、桌面小控件等很多功能，是个不错的综合应用的项目。

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg
![image](https://user-images.githubusercontent.com/19610305/72956958-c37bee80-3ddc-11ea-8fb0-48cbb7e2b6b1.png)

![image](https://user-images.githubusercontent.com/19610305/72956970-d0004700-3ddc-11ea-9b00-c9cebf3c029c.png)
![image](https://user-images.githubusercontent.com/19610305/72957003-df7f9000-3ddc-11ea-9431-0e31aeeacabf.png)
![image](https://user-images.githubusercontent.com/19610305/72957009-e4dcda80-3ddc-11ea-9c62-57d6fbd3ea44.png)

**Comment by 521xueweihan** [comment]
因收到网易云音乐和QQ音乐的官方警告函，我们已关闭app的相关api服务,不再提供任何apk
