### ISSUE TITLE
indicators

### ISSUE THREAD

**Issue by ChungZH** [521xueweihan/HelloGitHub#1056]
## 项目推荐
- 项目地址：https://github.com/p-ranav/indicators

- 类别：C++

- 项目后续更新计划：

- 项目描述：这是一个使用 C++ 编写的进度条库，你可以用它在命令行中显示出美观的进度条。它提供了多种样式，还可以变成彩色。使用方便，线程安全。

- 推荐理由：使用方便，线程安全。

- 示例代码：（可选）长度：1-20 行

- 截图：![](https://github.com/p-ranav/indicators/raw/master/img/demo.gif)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
