### ISSUE TITLE
Django开发的Redis管理平台Repoll，旨在提高企业对redis实例平台化管理能力，助力运维转型。

### ISSUE THREAD

**Issue by NaNShaner** [521xueweihan/HelloGitHub#1058]
## 项目推荐
- 项目地址：https://github.com/NaNShaner/repoll

- 类别：python

- 项目后续更新计划：
- [x] 支持哨兵模式和集群模式
- [x] 监控独立展示，包括qps、内存使用率、客户端链接以及慢查询等
- [ ] 支持web console
- [x] 提供新建、下线、实例列表查询等API接口

- 项目描述：
  - 必写：该项目主要用于集中管理公司内部的redis集群，是一个redis的运维门户平台，包括标准化申请流程、统一redis配置及版本、统一监控并提供API接口用于打通公司内部的cmdb或现有告警上报功能等
  - 可选：项目用django，结合djangorestframework编写，对于运维上手很快。

- 推荐理由：Django开发的Redis管理平台，旨在提高企业对redis实例平台化管理助力运维转型，解放运维人员的痛苦，赋能开发

- 截图：
![image](https://github.com/NaNShaner/repoll/blob/master/images/login.png?raw=true)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 47 期](https://hellogithub.com/periodical/volume/47/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
