### ISSUE TITLE
python的paralell/pipeline库

### ISSUE THREAD

**Issue by franklingu** [521xueweihan/HelloGitHub#106]
## 项目推荐
- 项目名称：joblib

- 项目地址：https://github.com/joblib/joblib

- 项目语言：python

- 项目描述：
Joblib is a set of tools to provide lightweight pipelining in Python. In particular, joblib offers:

    transparent disk-caching of the output values and lazy re-evaluation (memoize pattern)
    easy simple parallel computing
    logging and tracing of the execution

Joblib is optimized to be fast and robust in particular on large data and has specific optimizations for numpy arrays. It is BSD-licensed.
- 推荐理由：简单的进行并行计算，disk caching

- 示例代码：

```
>>> from joblib import Memory
>>> mem = Memory(cachedir='/tmp/joblib')
>>> import numpy as np
>>> a = np.vander(np.arange(3)).astype(np.float)
>>> square = mem.cache(np.square)
>>> b = square(a)   
```

```
>>> from joblib import Parallel, delayed
>>> from math import sqrt
>>> Parallel(n_jobs=1)(delayed(sqrt)(i**2) for i in range(10))
```

- 截图：

**Comment by 521xueweihan** [comment]
老铁，我把你加到了核心贡献者中。期待分享更多好玩的项目 👍
