### ISSUE TITLE
【自荐】自己刚出炉的一个安卓平音视频应用

### ISSUE THREAD

**Issue by yishuinanfeng** [521xueweihan/HelloGitHub#1061]
## 项目推荐
- 项目地址：
https://github.com/yishuinanfeng/UnitedPlayer
- 类别：C++、Java、Kotlin

- 项目描述：
  -    一个支持录制和播放音频视频的应用，录制的视频将在播放列表中显示，点击列表项即可播放，并可以选择不同仿抖音滤镜特效。
  
  - 使用Camera+OpenGL ES实时预览画面，使用OpenSl ES录制音频，通过MediaCodec分别对音视频进行编码，并通过MediaMuxer将音视频封装为MP4格式。

  - 使用ffmpeg解复用、解码MP4文件，通过OpenGL ES渲染视频画面，OpenSl ES播放音频，并通过OpenGL片段着色器提供不同的视频仿抖音滤镜效果。

- 推荐理由：
1.目前安卓平台音视频录制、播放、编辑方向技术属于门槛较高的方向，可以为初学者提供一个学习的良好例子。
2.如果性能、功能和交互做得好的话，也考虑作为一个提供给生产环境开发者使用的开源框架。

- 项目后续更新计划：
1. 交互体验优化
2. 视频添加背景音乐
3. 音频变调
4. 视频断点续录
5. 视频裁剪拼接

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by yishuinanfeng** [comment]
> HelloGitHub

好的，非常感谢~

**Comment by yishuinanfeng** [comment]
> **您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
> 欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

你好，可了解下大概什么时候可以发布么~

**Comment by 521xueweihan** [comment]
> > **您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
> > 欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
> 
> 你好，可了解下大概什么时候可以发布么~

非常感谢您推荐项目。我重新看了下这个项目，还有很多地方需要优化和更新，暂不能收录到月刊中，可以在微信群里分享，找些小伙伴一起开发。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by yishuinanfeng** [comment]
> > > **您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
> > > 欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
> > 
> > 
> > 你好，可了解下大概什么时候可以发布么~
> 
> 非常感谢您推荐项目。我重新看了下这个项目，还有很多地方需要优化和更新，暂不能收录到月刊中，可以在微信群里分享，找些小伙伴一起开发。
> 
> **该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
> 期待持续完善该项目，后续推荐更多的项目。
> 
> 再次感谢您对 HelloGitHub 的支持 🙏

好的，那完善完之后还能再推荐该项目么？

**Comment by 521xueweihan** [comment]
> > > > **您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
> > > > 欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
> > > 
> > > 
> > > 你好，可了解下大概什么时候可以发布么~
> > 
> > 
> > 非常感谢您推荐项目。我重新看了下这个项目，还有很多地方需要优化和更新，暂不能收录到月刊中，可以在微信群里分享，找些小伙伴一起开发。
> > **该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
> > 期待持续完善该项目，后续推荐更多的项目。
> > 再次感谢您对 HelloGitHub 的支持 🙏
> 
> 好的，那完善完之后还能再推荐该项目么？

可以的，建议参考上述标准完善项目，不仅是利于收录，也可以让更多人了解、加入您的项目。谢谢您的支持和理解～
