### ISSUE TITLE
东北方言编程语言

### ISSUE THREAD

**Issue by ChungZH** [521xueweihan/HelloGitHub#1065]
## 项目推荐
- 项目地址：https://github.com/zhanyong-wan/dongbei

- 类别：Python

- 项目后续更新计划：

- 项目描述：还记得前不久火起来的那个「文言」语言吗？现在又来了一个东北语言！dongbei 是一门以东北方言词汇为基本关键字的编程语言，基于 Python 3 二次开发，所以支持 Py3 支持的所有平台。只要小学文化程度就能看懂它。~~不仅如此，dongbei 还采用了业界领先的 TDD（TreeNewBee-Driven Development）开发模式~~

- 推荐理由：简单啊！好读啊！开心啊！开源啊！

- 示例代码：
```
【阶乘】（几）咋整：  # 定义套路 阶乘，有一个参数 几。
  瞅瞅：几比一小吗？ # 需要自推吗？
  要行咧就 滚犊子吧 一。  # 不需要。
  要不行咧就 滚犊子吧 几乘整【阶乘】（几减一）。  # 需要。自推吧。
整完了。  # 定义结束。
```

- 截图：（可选）gif/png/jpg

**Comment by zhz1237ok** [comment]
草，人才啊

**Comment by kenlma** [comment]
木凳口袋

**Comment by kerrysun8** [comment]
厉害
