### ISSUE TITLE
个性化网络爬虫Timbr

### ISSUE THREAD

**Issue by lvyachao** [521xueweihan/HelloGitHub#107]
## 项目推荐
- 项目名称：Timbr

- 项目地址：https://github.com/lvyachao/Timbr_V1

- 项目语言：NodeJS

- 项目描述：Timbr is a web service/application that turns an arbitrary web page into structure JSON data, it provides a friendly interface allow users without programming experiences to let our application know which part of data you want with a few clicks.

- 推荐理由：For every users who want a "unique" web crawler and don't want to programming.

- 示例代码：

```
getHttpContent: (url, injectType, removeScript) =>
    check url, String
    res = HTTP.get url, {
      headers:
        'user-agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.10 Safari/537.36'
      timeout: 5000
    }
    content = res.content
    if injectType?
      inj = new InjectJs(injectType, url, content, removeScript)
      return inj.inject()
    else
      return content
```

- 截图：

**Comment by 521xueweihan** [comment]
@lvyachao 
1. Can you translate to chinese.
2. websit not found: http://timbr.me

**Comment by lvyachao** [comment]
@521xueweihan 
1. 不好意思，这本身起源是北美这边一个大学support的一个research project。也许我以后可以退出一个readme.cn
2. 网站和域名我到期了 。。。过两天有空了我给回复下，谢谢。。

**Comment by 521xueweihan** [comment]
@lvyachao 欢迎更新后，重新开启 issue
