### ISSUE TITLE
Let's Certbot : 一个自动获取、续期、部署 SSL 证书工具

### ISSUE THREAD

**Issue by jinhucheung** [521xueweihan/HelloGitHub#1070]
## 项目推荐
- 项目地址：https://github.com/jinhucheung/letscertbot / https://gitee.com/jimcheung/letscertbot

- 类别：Python

- 项目描述：Let's Certbot 是一个基于 Certbot 用于自动化获取、续期、部署 SSL 证书的工具，统一维护 SSL 证书生命周期，支持容器化执行，为运维人员解放生产力。 同时也有助于初学者了解 SSL 证书申请流程以及各 DNS 服务商 API 调用方法。现已支持国内主流云服务商，如阿里云、腾讯云、华为云等

- 推荐理由：与 acme.sh 相比，解决了部署在多部机器上的同一个 SSL 证书续期麻烦的问题

- 项目后续更新计划：
  - 完善部署脚本，支持执行用户自定义命令
  - 支持更多的 DNS 服务商

- 示例代码：`sudo python ./bin/obtain.py -d your.example.com *.your.example.com`

- 截图：

![example](https://user-images.githubusercontent.com/19590194/74020785-3f795780-49d5-11ea-9483-4b9a59d58c33.gif)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
