### ISSUE TITLE
自荐《C++那些事》项目

### ISSUE THREAD

**Issue by Light-City** [521xueweihan/HelloGitHub#1071]
## 项目推荐

- 项目地址：
  https://github.com/Light-City/CPlusPlusThings
- 类别：C++
- 项目后续更新计划：
  - 更新极客时间笔记
  - 设计模式
  - 并发及多线程多进程开发
  - boost库笔记
  - C++面经
  - C++2.0新特性
- 项目描述：
  - 必写：这是一个适合初学者从入门到进阶的仓库，解决了面试者想要深入C++及如何入坑C++的问题，除此之外，本仓库拓展了更加深入的原发分析，多线程并发等的知识，是一个比较全面的C++学习从入门到进阶提升的仓库。
  - 可选：适用于有C语言基础，想入坑及深入学习C++的学习者，可以为初学者提供一个学习路径及内容。
- 推荐理由：解决了面试者想深入学习C++，初学者想入坑及深入学习C++的问题。

**Comment by ChungZH** [comment]
@Light-City 老哥，解释下 C++2.0 是什么意思？

**Comment by yanlinlin82** [comment]
本以为这是C++20的笔误，看了内容发现他应该是想说morden C++或C++11/14/17/20。“C++2.0”这说法的确很清奇，哈哈哈

**Comment by ChungZH** [comment]
> 本以为这是C++20的笔误，看了内容发现他应该是想说morden C++或C++11/14/17/20。“C++2.0”这说法的确很清奇，哈哈哈

对...我刚开始也以为是笔误 :joy: 不过这种不流行的说法还是建议他要改改hhh

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 47 期](https://hellogithub.com/periodical/volume/47/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）

**Comment by Light-City** [comment]
> 么意思？

C++11/14/17/20等特性简称，因为后面会变短更新，所以就写成2.0，，而不是20,
