### ISSUE TITLE
AkShare 开源金融数据接口库, 超 13 万下载量

### ISSUE THREAD

**Issue by jindaxiang** [521xueweihan/HelloGitHub#1072]
## 项目推荐
- 项目地址：https://github.com/jindaxiang/akshare; docs: https://akshare.readthedocs.io/

- 类别：Python

- 项目后续更新计划：增加更多数据接口，目前本项目已经更新 0.3.88，每日都在维护

- 项目描述：
  - 必写：AkShare 是基于 Python 的开源金融数据接口库, 目的是实现对股票, 期货, 期权, 基金, 外汇, 债券, 指数, 数字货币等金融产品的基本面数据、实时和历史行情数据、衍生数据从数据采集, 数据清洗, 到数据落地的一套开源工具, 满足金融数据科学家, 数据科学爱好者在金融数据获取方面的需求.
  - 可选：可以便利解决数据获取问题，方便金融量化从业人员、科研人员。

- 推荐理由：开源项目; 利用一行代码获取数据，整合各大公开金融数据源。目前本项目已经收获 130+ star，下载量超过 13 万，微信公众号粉丝超过 1100 人，撰写超 100,000 字的文档；每个数据接口都有丰富的Python示例代码支持。

- 示例代码：
```
import akshare as ak
bond_df = ak.get_country_bond(country="中国", index_name="中国1年期国债", start_date='2000/01/01', end_date='2019/10/17')
print(bond_df)
```

- 截图：
![image](https://user-images.githubusercontent.com/18234520/74135886-0f75c280-4c28-11ea-94be-6ec3d917384d.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 47 期](https://hellogithub.com/periodical/volume/47/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
