### ISSUE TITLE
[自荐] 一款轻量且支持多彩模式的顶部进度条

### ISSUE THREAD

**Issue by vortesnail** [521xueweihan/HelloGitHub#1074]
## 项目推荐
- 项目地址：https://github.com/vortesnail/qier-progress

- 类别：TypeScript/JavaScript

- 项目后续更新计划：
  - 增加基于jest的单元测试，覆盖95%以上
  - 因为本项目比较轻量，不宜再增加更多功能，现在已经是比较成熟的一个插件了。

- 项目描述：
  - 必写：这是一个用于缓解用户焦虑，给予用户请求回馈的顶部进度条；在发送请求前后、文件夹在或上传、链接跳转等地方都能用到，比如你看github的点击某链接跳转时，顶部会有一个进度条；该项目使用 ts 重构了万星star的 nprogress，打包体积更小，且支持了多彩模式，自定义高度和颜色等，最重要的是有良好的类型注解。
  - 可选：除了应用在我们的开发中，该项目还能用来学习 typescript，结构简单，代码量也比较少，非常利于学习。

- 推荐理由：该项目使用 ts 重构了万星star的 nprogress，打包体积更小，且支持了多彩模式，自定义高度和颜色等，最重要的是有良好的类型注解。

- 示例代码：
```js
const qprogress = new QProgress()
qprogress.start()
qprogress.finish()
```
- 示例图片：
![](https://cdn.nlark.com/yuque/0/2020/gif/341314/1581514406350-f5ba82c9-4371-4e79-975e-5214e145e7ed.gif)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 47 期](https://hellogithub.com/periodical/volume/47/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
