### ISSUE TITLE
Retinanet-Pytorch

### ISSUE THREAD

**Issue by yatengLG** [521xueweihan/HelloGitHub#1076]
## 项目推荐
- 项目地址：https://github.com/yatengLG/Retinanet-Pytorch

- 类别：Python、机器学习

- 项目后续更新计划：后续添加训练过程实例。但是近期应该是顾不上。

- 项目描述：
 Retinanet-Pytorch是以Pytorch深度学习库实现的retinanet目标检测模型。项目拥有清晰的结构，完善的注释，以及详细的使用说明。适用于 有些许深度学习基础的初学者进行学习，或在实际的目标检测项目中使用。

- 推荐理由：完善的中文注释，简明的项目层次，清晰的模型结构 。如果你在目标检测任务时，为数据集类别不平衡而困扰。本项目将是你的不二之选。

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 47 期](https://hellogithub.com/periodical/volume/47/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
