### ISSUE TITLE
【自荐】✨强大、优雅的小程序异步库🚀 小程序promise

### ISSUE THREAD

**Issue by youngjuning** [521xueweihan/HelloGitHub#1081]
## 项目推荐
- 项目地址：https://github.com/youngjuning/wx-promise-pro

- 类别：JS

- 项目后续更新计划：添加自定义方法

- 项目描述：
  - 支持 finnaly、typescript 的微信小程序异步解决方案

- 推荐理由:
  - 方便集成：一处引用，处处使用
  - 把微信小程序所有异步 API promise 化并挂在到wx.pro 对象下
  - 支持 ES2018 finally 特性
  - 支持 TypeScript 开发

- 示例代码：

```js
import { promisifyAll, promisify } from 'wx-promise-pro'
// promisify all wx‘s api
promisifyAll()
// promisify single api
promisify(wx.getSystemInfo)().then(console.log)
```

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 47 期](https://hellogithub.com/periodical/volume/47/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）

**Comment by youngjuning** [comment]
感谢作者的肯定，我也关注你掘金了！
