### ISSUE TITLE
【自荐项目】Android UI 快速开发，专治原生控件各种不服

### ISSUE THREAD

**Issue by RuffianZhong** [521xueweihan/HelloGitHub#1088]
## 项目推荐
- 项目地址：[RWidgetHelper](https://github.com/RuffianZhong/RWidgetHelper)

- 类别：Java/Android

- 项目后续更新计划：
满足安卓UI开发的基本需求，最小代价实现你开启一个应用所能见到的所有UI

- 项目描述：
日常开发中，总有一些常见的UI效果，实现和修改费力不讨好，要么费事自定义，要么低声下气恳求美术切图，RWidgetHelper 的出现就是打破这种僵局，实现简单快速实现UI效果
现有解决方案痛点    ：代码冗余，复用性差，自由度低
RWidgetHelper 优点：优化代码，简化使用，快速开发，自定义程度高

- 推荐理由：程序从此翻身做主人
产品，美术你们随便设计，我一个 RWidgetHelper 搞定你所有！
工时多久？你效果图出来后就可以来找我看成品了！

- 示例代码：
[README](https://github.com/RuffianZhong/RWidgetHelper)

- 截图：
![预览](https://raw.githubusercontent.com/RuffianZhong/RWidgetHelper/master/picture/all.gif)
![水波纹](https://raw.githubusercontent.com/RuffianZhong/RWidgetHelper/master/picture/ripple.gif)
![阴影](https://raw.githubusercontent.com/RuffianZhong/RWidgetHelper/master/picture/shadow.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
