### ISSUE TITLE
SelectPage 多功能的分页选择器

### ISSUE THREAD

**Issue by TerryZ** [521xueweihan/HelloGitHub#109]
## 项目推荐
- 项目名称：SelectPage

- 项目地址：https://github.com/TerryZ/SelectPage

- 项目语言：javascript/jquery

- 项目描述：一个简洁优雅而功能强大的选择器；它包含了autocomplete、ajax数据源、多选择Tag、i18n国际化，结果列表分页展示，键盘快捷操作等

- 推荐理由：使用简单，适应各种UI环境，功能强大，丰富的参数和回调函数

- 示例代码：
```js
//defined a array, the data returned at the server side is also used that format：
//Array[{Object},{...}]
var data = [
    {id:1 ,name:'Chicago Bulls',desc:'芝加哥公牛'},
    {id:2 ,name:'Cleveland Cavaliers',desc:'克里夫兰骑士'},
    {id:3 ,name:'Detroit Pistons',desc:'底特律活塞'},
    {id:4 ,name:'Indiana Pacers',desc:'印第安纳步行者'}
];
//init SelectPage
$('#selectpage').selectPage({
    showField : 'desc',
    keyField : 'id',
    data : data
});
```

- 截图：

![selectpage](https://user-images.githubusercontent.com/854406/30259043-03b034a6-96f1-11e7-8931-5de623a93383.png)
![selectpage1](https://user-images.githubusercontent.com/854406/30259044-03b289fe-96f1-11e7-92c9-2593929d4f98.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，已成功收录在 [HelloGitHub 第 18 期](https://hellogithub.com/volume/18/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，如果方便可以 Star ⭐️ 本项目，让更多人看到本项目。
