### ISSUE TITLE
基于Go语言的开源论坛项目：bbs-go

### ISSUE THREAD

**Issue by alibabaaaaaa** [521xueweihan/HelloGitHub#1095]
## 项目推荐
- 项目地址：https://github.com/mlogclub/bbs-go

- 类别：Go

- 项目后续更新计划：积分商城、勋章系统

- 项目描述：bbs-go是一个使用Go语言搭建的开源社区系统，采用前后端分离技术，Go语言提供api进行数据支撑，用户界面使用Nuxt.js进行渲染，后台界面基于element-ui。如果你正在学习Go语言，或者考虑转Go语言的Phper/Javaer...那么该项目对你有的学习会有很大的帮助，欢迎一起来交流。

- 推荐理由：开源的基于Go语言最好的论坛系统。

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
