### ISSUE TITLE
【项目自荐】ext-collections - 优雅、高效地操作 PHP 数组

### ISSUE THREAD

**Issue by CismonX** [521xueweihan/HelloGitHub#1098]
## 项目自荐
- 项目地址：https://github.com/CismonX/ext-collections

- 类别：PHP

- 项目后续更新计划：
  * 紧跟 PHP 官方动向，及时适配最新版本的 PHP
  * 根据需要，实现更多的数组操作方法

- 项目描述：ext-collections 是一个 C 语言实现的 PHP 扩展库，提供了类似 JAVA stream API 和 kotlin.collections 的一系列库函数，方便开发者优雅、快速地操作 PHP 数组。

- 推荐理由：
  * 提供了丰富的 PHP 数组操作函数，有助于提高开发效率和代码的可读性
  * 使用 C 语言实现，比同类 PHP 实现性能更高
  * 初学者可以通过阅读此项目代码帮助自己入门 PHP 扩展开发

- 示例代码：
```PHP
$employees = [
    ['name' => 'Alice', 'sex' => 'female', 'age' => 35],
    ['name' => 'Bob', 'sex' => 'male', 'age' => 29],
    ['name' => 'David', 'sex' => 'male', 'age' => 40],
    ['name' => 'Benjamin', 'sex' => 'male', 'age' => 32]
];
// Trying to get an array of names of male employees,
// sorted by the descending order of their age.
$names = Collection::init($employees)
    ->filter(function ($value) {
        return $value['sex'] == 'male';
    })
    ->sortedByDescending(function ($value) {
        return $value['age'];
    })
    ->map(function ($value) {
        return $value['name'];
    })
    ->toArray();
// You got $names == ['David', 'Benjamin', 'Bob'].
```

**Comment by gowinder** [comment]
2020年2月25日 下午7:18，CismonX <notifications@github.com<mailto:notifications@github.com>> 写道：

项目自荐

  *   项目地址：https://github.com/CismonX/ext-collections<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCismonX%2Fext-collections&data=02%7C01%7C%7C494140fd675c4eb0ed2008d7b9e476e9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637182263201807139&sdata=Ml2ewemieQ6Tfin%2F6yJ%2FlXqM3D7pj3sgIPpm1wHes1s%3D&reserved=0>

  *   类别：PHP

  *   项目后续更新计划：

     *   紧跟 PHP 官方动向，及时适配最新版本的 PHP
     *   根据需要，实现更多的数组操作方法
  *   项目描述：ext-collections 是一个 C 语言实现的 PHP 扩展库，提供了类似 JAVA stream API 和 kotlin.collections 的一系列库函数，方便开发者优雅、快速地操作 PHP 数组。

  *   推荐理由：

     *   提供了丰富的 PHP 数组操作函数，有助于提高开发效率和代码的可读性
     *   使用 C 语言实现，比同类 PHP 实现性能更高
     *   初学者可以通过阅读此项目代码帮助自己入门 PHP 扩展开发
  *   示例代码：

$employees = [
    ['name' => 'Alice', 'sex' => 'female', 'age' => 35],
    ['name' => 'Bob', 'sex' => 'male', 'age' => 29],
    ['name' => 'David', 'sex' => 'male', 'age' => 40],
    ['name' => 'Benjamin', 'sex' => 'male', 'age' => 32]
];
// Trying to get an array of names of male employees,
// sorted by the descending order of their age.
$names = Collection::init($employees)
    ->filter(function ($value) {
        return $value['sex'] == 'male';
    })
    ->sortedByDescending(function ($value) {
        return $value['age'];
    })
    ->map(function ($value) {
        return $value['name'];
    })
    ->toArray();
// You got $names == ['David', 'Benjamin', 'Bob'].

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 47 期](https://hellogithub.com/periodical/volume/47/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
