### ISSUE TITLE
【自荐】jai - Just Assemble IT! - A LEGO-style & PyTorch-based Deep Learning Library

### ISSUE THREAD

**Issue by gengjia0214** [521xueweihan/HelloGitHub#1099]
## 项目推荐
- 项目地址：https://github.com/gengjia0214/jai.git | https://pypi.org/project/jai/

- 类别：Python, PyTorch
- 项目后续更新计划：目前项目处于初期，未来会持续更新更多的SOTA Technique，Deep Learning 模板等

- 项目描述：
  - 必写：jai 是一个基于 PyTorch library 即插即拔式的Deep Learnig框架，帮助你快速搭建Deep Learning的实验。 
  - 可选：利用jai的框架，尝试各种Deep learning的技巧，目前基础框架已经搭建完毕，非常欢迎Deep Learning有兴趣的同学contribute，提供建议
  - 描述长度（不包含示例代码）: 详情请见Readme
- 推荐理由：框架易于理解和上手，方便初学者修改，contribute，甚至创建自己的pipeline和插入一些自己写的SOTA Technique

- 示例代码：详情请见Readme

- 截图：详情请见Readme

**Comment by gengjia0214** [comment]
Just Assemble IT! - A LEGO-style & PyTorch-based Deep Learning Library

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
