### ISSUE TITLE
bDialog - 基于Bootstrap Modal功能加强扩展的多功能弹窗

### ISSUE THREAD

**Issue by TerryZ** [521xueweihan/HelloGitHub#110]
## 项目推荐
- 项目名称：bDialog

- 项目地址：https://github.com/TerryZ/bDialog

- 项目语言：javascript / jquery

- 项目描述：bDialog在原生Bootstral Modal功能基础上，增加多种功能设置，事件回调，参数传递等功能，并在展现形式上除原有的Modal模态窗口外，还增加了ALert消息通知对话框，包含了info、warning、error、success、confirm等类型对话框，增加了Mask遮罩层功能，Toast边角通知窗口模式，包含info、warning、error、success等模式，且有六个角落的显示位置，大大增强了Bootstrap Modal的功能和可用度

- 推荐理由：使用Bootstrap生态的项目可用bDialog解决所有弹窗的需求，且bDialog是不破坏Bootstrap Modal原生HTML代码结构的，可方便的进行主题更换

- 示例代码：
```js
//Modal
bDialog.open({
  url : 'http://some url'
});
bDialog.open({
  dom : $('#some element').html()
});

//Alert
bDialog.alert('your message');
bDialog.alert('your message',function(){
  //your callback
});

//Mask
bDialog.mask();

//Toast
bDialog.toast('your message');
bDialog.toast('your message',{
  //toast dialog type
  messageType : 'warning',
  //show dialog in topleft position
  position : 'topLeft',
  //don't show close button
  dialogCloseButton : false,
  //auto close dialog time(second),default 3s
  closeTime : 0
});
```
- 截图：
![bdialog](https://user-images.githubusercontent.com/854406/30259228-662c17de-96f2-11e7-99f7-0c4f2ea79afe.png)
![bdialogalert](https://user-images.githubusercontent.com/854406/30259229-662ce182-96f2-11e7-9edc-82ef2646d3f9.png)
![bdialogmask](https://user-images.githubusercontent.com/854406/30259230-66693a2e-96f2-11e7-92b0-d681f20afcdb.png)
![bdialogtoast](https://user-images.githubusercontent.com/854406/30632095-719a04ea-9e19-11e7-8722-03647f775092.png)

**Comment by 521xueweihan** [comment]
@TerryZ 您好，您的项目未能收录到月刊中。还望之后可以继续推荐有意思、有价值、可以让新手从中收益匪浅的项目。
