### ISSUE TITLE
【自荐】在线图片压缩工具[纯前端解决方案]

### ISSUE THREAD

**Issue by zerosoul** [521xueweihan/HelloGitHub#1101]
## 项目推荐
- 项目地址：https://github.com/zerosoul/image-compress-without-backend

- 类别：JS

- 项目后续更新计划：
  - 压缩参数自定义
  - 压缩前后对比图

- 项目描述：无他，又一个在线图片压缩小工具。只不过使用了纯前端解决方案，即，无需上传照片到服务器，一切都在浏览器端完成，快速而高效。非常适用于图片压缩后质量要求不是很高的场景，比如：移动端图片展示。

- 推荐理由：纯前端压缩图片，就是这么快！

- 截图：
![image](https://user-images.githubusercontent.com/2985895/75304943-97daa100-587f-11ea-8543-8f78fabc1a62.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
