### ISSUE TITLE
【自荐】静心呼吸调节器

### ISSUE THREAD

**Issue by zerosoul** [521xueweihan/HelloGitHub#1102]
## 项目推荐

- 项目地址：https://github.com/zerosoul/breathe-relaxer

- 类别：JS

- 项目描述：通过视觉反馈，可以在线调节呼吸节奏，进而达到放松身心的目的。

- 推荐理由：精美背景图+白噪音背景音乐，可全屏，让人仿佛置身于所视风景图中。调节呼吸，愉悦身心。

- 截图：
![image](https://user-images.githubusercontent.com/2985895/75305381-e3417f00-5880-11ea-8348-d4bd92f280a0.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 47 期](https://hellogithub.com/periodical/volume/47/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
