### ISSUE TITLE
一个Python+PyQt5实现的安卓手机投屏工具

### ISSUE THREAD

**Issue by littleningmeng** [521xueweihan/HelloGitHub#1105]
## 项目推荐
- 项目地址：https://github.com/littleningmeng/pyphone

- 类别：Python

- 项目后续更新计划：

- 项目描述：
  - 必写：Python实现的安卓手机投屏客户端，解决在家办公无聊时想用电脑刷抖音的痛点

- 推荐理由：学习minicap、minitouch的使用方式，顺便入门PyQt5

- 示例代码：（可选）长度：1-20 行

- 截图：[点我](https://github.com/littleningmeng/pyphone/blob/master/snapshots/demo.gif)

**Comment by 521xueweihan** [comment]
有意思的项目，有以下几个建议：
1. 执行步骤有些繁琐
2. 我看依赖 redis 服务，如果本机没有启动 redis 就瞎了
3. 既然是一个投屏工具，工具顾名思义拿来就能用
4. 动图录的不好看而且太大了，好的 Readme 是使用者的第一印象

**Comment by littleningmeng** [comment]
1&3. 嗯嗯，这个项目主要是用来练手PyQt5的，易用性上没考虑太多。
2. Redis的服务器需要用户自己搭，没有就用不了了~~
4. 录图有点随意了

**Comment by 521xueweihan** [comment]
> 1&3. 嗯嗯，这个项目主要是用来练手PyQt5的，易用性上没考虑太多。
> 2. Redis的服务器需要用户自己搭，没有就用不了了~~
> 4. 录图有点随意了

期待后续优化、完善后再来提交推荐，欢迎在微信群讨论、宣传贵项目，找到志同道合一起开发的小伙伴～我就先关闭了，再次谢谢您的支持～
