### ISSUE TITLE
【自荐】前端面试秘籍

### ISSUE THREAD

**Issue by qiilee** [521xueweihan/HelloGitHub#1106]
## 项目推荐
- 项目地址：https://github.com/yisainan/web-interview

- 类别：JS

- 项目后续更新计划：持续更新面试题目

- 项目描述：这是一个供web前端工程师们面试前复习使用的前端面试项目

- 推荐理由：收集整理全网面试题及面试技巧，旨在帮助前端工程师们找到一份好工作！

- 截图：
![1566544815(1)](https://user-images.githubusercontent.com/26279879/75520653-fef38380-5a40-11ea-8ccd-ea3900ebdca0.jpg)

**Comment by 521xueweihan** [comment]
已推荐过“全杭州最牛逼的前端面试项目”，所以您的项目暂不收录啦。
