### ISSUE TITLE
足球赔率数据爬虫分析一体化的项目

### ISSUE THREAD

**Issue by monomania** [521xueweihan/HelloGitHub#1109]
## 项目推荐
- 项目地址：https://github.com/monomania/foot

- 类别：Go

- 项目后续更新计划：
1..可能后期会部署于wondows 服务器上,开发一个舒服可控制的gui程序出来
2.优化分析算法,加入机器学习完成分析

- 项目描述：
foot是一个集足球数据采集器,简单分析,同步到微信及其他发布平台一体化的项目.
程序采用go语言开发,项目结构清晰完整,非常容易入手并进行二次开发分析.

- 推荐理由：
模块化的项目结构设计,go语言爬虫框架应用学习,便于实现自己对足球预测的分析逻辑

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
