### ISSUE TITLE
基于python的九型人格测试系统

### ISSUE THREAD

**Issue by crazyjums** [521xueweihan/HelloGitHub#1112]
## 项目推荐
- [项目地址](https://github.com/crazyjums/nine_char/)

- 类别：Python

- 项目后续更新计划：暂定无

- 项目描述：
  - 这是一个用python的tinker写的一个九型人格GUI测试系统（理论根据[海伦·帕尔默(Helen Palmer)](https://item.jd.com/12617848.html)的书籍编写）
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：
  - 可以测一测自己的人格类型，（测试结果仅供参考，切记不可根据测试结果妄自菲薄或骄傲自大。）
  - 可以通过该项目学习python中的GUI编程（基于tinker）
- 示例代码：（可选）长度：1-20 行

- 截图：
![](https://camo.githubusercontent.com/6eb8c62ea3a4c0fed814b27c31374180fe7ee6d1/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f6372617a796a756d732f4d61726b646f776e506963406d61737465722f6e696e65506572736f6e616c6974792f312e706e67)
![](https://camo.githubusercontent.com/7b6049622093f4c15a8954e350b703f7975c8908/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f6372617a796a756d732f4d61726b646f776e506963406d61737465722f6e696e65506572736f6e616c6974792f342e706e67)

**Comment by 521xueweihan** [comment]
有意思的项目，算是一个Python GUI 练手小demo，暂时不能收录到月刊中。

期待后续大作～
