### ISSUE TITLE
Python: 配置文件管理懒人脚本

### ISSUE THREAD

**Issue by tjysdsg** [521xueweihan/HelloGitHub#1113]
## 项目推荐
- 项目地址：https://github.com/tjysdsg/dot-easy

- 类别：Python

- 项目后续更新计划：

- 完善输出
- 添加更多配置选项
- 自动化push/pull

- 项目描述：
  - 必写：配置文件太多、太杂乱且不方便备份的解决方案
  - 可选：跨平台，代码简洁清晰，适合Python初学者
  - 描述长度（不包含示例代码）: 100行左右

- 推荐理由：自动化配置文件管理，谁不喜欢自动化的东西呢？

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
