### ISSUE TITLE
AntV/G2 4.0 released

### ISSUE THREAD

**Issue by hustcc** [521xueweihan/HelloGitHub#1116]
## 项目推荐
- 项目地址：https://github.com/antvis/G2

- 类别：JS

- 项目后续更新计划：https://www.yuque.com/antv/blog/g2-4.0-released

- 项目描述：
  - 必写：G2 一套面向常规统计图表，以数据驱动的高交互可视化图形语法，具有高度的易用性和扩展性。使用 G2，你可以无需关注图表各种繁琐的实现细节，一条语句即可使用 Canvas 或 SVG 构建出各种各样的可交互的统计图表。
  - 可选：G2 是整个蚂蚁金服 AntV 可视化解决方案中的一个环节，主要针对在高交互、高扩展的二维统计图表。
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？

G2 基于图形语法构建，可以幻化出千万种可视化图表（250+），在此基础上打磨交互语法，让可视化图表的交互开发变得容易。

G2 4.0 版本发布，诸多亮眼的更新特性见：https://www.yuque.com/antv/blog/g2-4.0-released

- 示例代码：（可选）长度：1-20 行

官网 [demo](https://g2.antv.vision/zh) 很多哦。

- 截图：（可选）gif/png/jpg

官网 demo 中挑选需要的图形截图吧。也可以从[发布文章](https://www.yuque.com/antv/blog/g2-4.0-released)中挑选一些动图，效果更加。

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 48 期](https://hellogithub.com/periodical/volume/48/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
