### ISSUE TITLE
【自荐】土味情话，在线生成

### ISSUE THREAD

**Issue by zerosoul** [521xueweihan/HelloGitHub#1117]
## 项目推荐

- 项目地址：https://github.com/zerosoul/honeyed-words-generator

- 类别：JS

- 项目描述：在线随机生成土味情话

- 推荐理由：生成图片，分享二维码，快快发给那个想表白的TA吧！

- 截图：
首页
![home image](https://github.com/zerosoul/honeyed-words-generator/raw/master/demo.home.png)
结果页
![image](https://user-images.githubusercontent.com/2985895/75674636-74b95280-5cc0-11ea-84a9-bd79138b1308.png)
生成的图片（附二维码）
![image card](https://github.com/zerosoul/honeyed-words-generator/raw/master/demo.download.png)
喜欢这句情话，可已生成对应的二维码，分享出去！
![qr image](https://github.com/zerosoul/honeyed-words-generator/raw/master/demo.share.qr.png)

**Comment by 521xueweihan** [comment]
撩到我了～

**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 48 期](https://hellogithub.com/periodical/volume/48/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
