### ISSUE TITLE
DungeonRush 自荐

### ISSUE THREAD

**Issue by Rapiz1** [521xueweihan/HelloGitHub#1118]
## 项目推荐
- 项目地址：https://github.com/Rapiz1/DungeonRush

- 类别：C

- 项目后续更新计划：
局域网或IP直连联机
代码重构

- 项目描述：
  - 这是个大一课设游戏，受到元气骑士的启发，基于贪吃蛇进行一些玩法创新。*你或许可以叫他 元 气 贪 吃 蛇。*
  - 适用于C语言初学者第一次尝试使用跨平台图形库，写出一个可玩性高的游戏，收获满满成就感。
- 推荐理由：把贪吃蛇课设做出花来。让C语言初学者摆脱命令行界面。用基本的知识，做一个好玩的游戏。

- 截图：（可选）gif/png/jpg
![banner](https://i.loli.net/2020/03/02/wd7DB1CUhsaPueZ.gif)
![preview](https://i.loli.net/2020/03/02/crM9x1jCYol7LzO.gif)

**Comment by 521xueweihan** [comment]
强。如补充：游戏说明，操作指南，可能会更受欢迎。

**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by yuemasked** [comment]
额，抱歉，我是打算收藏HelloGitHub这个项目的，用来学习使用，但可能用的不咋熟练、操作不当，对于GitHub的使用比较陌生，把以前的游戏项目推荐给了您，给您造成了困扰，对不起。还有，谢谢您的项目！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"削微寒"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 晚上9:30
收件人:&nbsp;"521xueweihan/HelloGitHub"<HelloGitHub@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [521xueweihan/HelloGitHub] DungeonRush 自荐 (#1118)





 
强。如补充：游戏说明，操作指南，可能会更受欢迎。
 
您推荐的项目已收录到专栏，后续有最新进展会在此 Issues 进行通知。
 欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
@yuemasked 我觉你的项目很有意思，将会被收录到月刊中。

一些个人建议：如果文档多些会对 C 新手有更多帮助。大家也能更快的理解你的项目，从而更容易找到一起开发维护的小伙伴。

**Comment by Rapiz1** [comment]
@yuemasked ???

**Comment by 521xueweihan** [comment]
> @yuemasked ???

我眼花了，回复错人了。那个朋友应该是还不是很熟悉 github 的通知。

**Comment by yuemasked** [comment]
额，确实 ，不是很熟悉GitHub，正在学习




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"削微寒"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 晚上9:47
收件人:&nbsp;"521xueweihan/HelloGitHub"<HelloGitHub@noreply.github.com&gt;;
抄送:&nbsp;"1140036127"<1140036127@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [521xueweihan/HelloGitHub] DungeonRush 自荐 (#1118)





  
@yuemasked ???
  
我眼花了，回复错人了。那个朋友应该是还不是很熟悉 github 的通知。

**Comment by Rapiz1** [comment]
一开始写的时候我其实没想到效果会这么好，也没想过把他发布出来，所以注释有些缺失。未来我会找时间重构并加入注释，提高代码的可维护性。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 48 期](https://hellogithub.com/periodical/volume/48/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
