### ISSUE TITLE
【自荐】通过字节码插桩帮助你自动获取http请求体（支持Okhttp）

### ISSUE THREAD

**Issue by kingwang666** [521xueweihan/HelloGitHub#1119]
## 项目推荐
- 项目地址：https://github.com/kingwang666/HttpParam

- 类别：Java、Kotlin

- 项目后续更新计划：
支持更多的请求体生成类型。
更多复杂参数的自我识别。
生成方法是否重写的逻辑判断修改

- 项目描述：
这是一个通过字节码插桩帮你自动构建请求体的 Gradle插件。此项目可以帮助开发者利用android studio的transform api来快速构建出想要的http请求，减少开发时间。适用于当一个http请求参数较长时，开发者也可通过代码学习字节码插桩技术。

- 推荐理由：通过字节码码插桩自动构建出http请求体。减少开发者开发时间。

- 示例代码：

	  @Params(
	          type = ParamsType.BODY
	  )
	  @Body
	  @Parts
	  public class FileReq extends BaseReq {
	
	      @NonNull
	      public String name = "wang";
	
	      @ParamName("fakeAge")
	      public Integer age = 18;
	
	      @PostFile
	      public File file = new File(Environment.getExternalStorageDirectory() + File.separator + "test.txt");
	    
	    
	  }

- 截图：（可选）gif/png/jpg

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
