### ISSUE TITLE
【自荐】一个学习Java的例子仓库！

### ISSUE THREAD

**Issue by JasonkayZK** [521xueweihan/HelloGitHub#1120]
## 项目推荐
- 项目地址：[https://github.com/JasonkayZK/Java_Samples](https://github.com/JasonkayZK/Java_Samples)

- 类别：Java

- 项目后续更新计划：添加更多的Java学习小例子(Spring源码功能实现等等)

- 项目描述：
  - Java_Samples是一个通过Java代码实现Java例子的仓库, 包括RPC, Reflection, Lambda, Annotation, Proxy, NIO, SSO, Spring-IoC等
  - 初学者可以通过代码学习到框架使用的例子, 或者源码底层是如何实现的, 从而扎实自己的基础, 并且逐步懂得和理解Java基础和热门框架的相关知识

- 推荐理由：仓库中每一个例子都在单独的一个分支, 所有例子都是本人在学习Java时的积累, 希望能够帮助到更多的人! 并且大多数例子都包括我博客内容的总结, 帮助初学者理解!

- 示例代码：

Demo | Url | Last Modified | Comment
-- | -- | -- | --
Java-Introspector | https://github.com/JasonkayZK/Java_Samples/tree/java-introspector | 2020-03-02 | 文章: [Java的内省技术](https://jasonkayzk.github.io/2020/03/02/Java%E7%9A%84%E5%86%85%E7%9C%81%E6%8A%80%E6%9C%AF/)
Redis-Session | https://github.com/JasonkayZK/Java_Samples/tree/redis-session | 2020-02-10 | 实现文章: [Redis实现分布式Session](https://jasonkayzk.github.io/2020/02/10/Redis%E5%AE%9E%E7%8E%B0%E5%88%86%E5%B8%83%E5%BC%8FSession/)
Redis-distribute-lock | https://github.com/JasonkayZK/Java_Samples/tree/redis-distribute-lock | 2020-02-09 | 文章: [Redis面试相关问题](https://jasonkayzk.github.io/2020/02/05/Redis%E9%9D%A2%E8%AF%95%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98/)
Redis-Pub/Sub | https://github.com/JasonkayZK/Java_Samples/tree/redis-pub/sub | 2020-02-09 | 文章: [Redis面试相关问题](https://jasonkayzk.github.io/2020/02/05/Redis%E9%9D%A2%E8%AF%95%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98/)
Mybatis-Generator | https://github.com/JasonkayZK/Java_Samples/tree/mybatis-generator | 2020-01-15 | 文章: [mybatis-generator逆向工程总结](https://jasonkayzk.github.io/2020/01/15/mybatis-generator%E9%80%86%E5%90%91%E5%B7%A5%E7%A8%8B%E6%80%BB%E7%BB%93/)
Swagger with Spring Boot | https://github.com/JasonkayZK/Java_Samples/tree/swagger | 2020-01-02 | 文章: [SpringBoot集成Swagger](https://jasonkayzk.github.io/2020/01/02/SpringBoot%E9%9B%86%E6%88%90Swagger/)
Proxy | https://github.com/JasonkayZK/Java_Samples/tree/java-proxy | 2019-09-18 | 包括: 静态/动态(JDK/CGLib)文章: [Java中的代理模式-静态代理与动态代理](https://jasonkayzk.github.io/2019/09/18/Java%E4%B8%AD%E7%9A%84%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F-%E9%9D%99%E6%80%81%E4%BB%A3%E7%90%86%E4%B8%8E%E5%8A%A8%E6%80%81%E4%BB%A3%E7%90%86/)
-- | -- | -- | --

**Comment by JasonkayZK** [comment]
上面是我本人学习Java时的一些代码总结和文章, 感觉能够帮助更多学习Java的人. 望通过, 谢谢~❤

**Comment by 521xueweihan** [comment]
> 上面是我本人学习Java时的一些代码总结和文章, 感觉能够帮助更多学习Java的人. 望通过, 谢谢~❤

感谢您的项目，期待持续更新。成大全后，可再次推荐，当前暂不能收录到月刊中，望理解。

**Comment by JasonkayZK** [comment]
好的, 可以理解! 以后还是会继续维护这个仓库的, 希望可以收录到月刊! : )
