### ISSUE TITLE
【自荐】一款 Ant Design 设计风格的 VuePress 主题

### ISSUE THREAD

**Issue by zpfz** [521xueweihan/HelloGitHub#1122]
## 项目推荐
- 项目地址：https://github.com/zpfz/vuepress-theme-antdocs
- 官方文档：http://antdocs.seeyoz.cn/

- 类别：JS

- 项目后续更新计划：发布正式版本并继续优化显示效果。

- 项目描述：
  - 这是一款具有 Ant Design 设计风格的 VuePress 主题，具有以下特点：
      - 搭载了开箱即用的高质量 Ant Design 组件，支持与 Markdown 语法混用。
      - 统一预处理器，使用 Ant Design 设计规范的 Less 样式。
      - 最大限度优化各种显示以及动画效果。
  - 为什么搞出这么一款主题？
    因为 React.js + GatsbyJs 已经有类似的主题方案，我觉得 Vue.js + VuePress 也不能输，而且官方文档模板也挺不错，所以熬了无数个日夜，魔改出这么一个主题。
  - 关于 AntDocs ： AntDocs of VuePress 是基于 VuePress 默认主题而修改的一款主题，部分样式借鉴了 Ant Design 设计规范，而其他较为复杂的模块则直接引用 Ant Design Vue 中的组件，尽量做到与 Ant Design 文档的设计风格一致，让大家享受 Ant Design 的优秀设计~
尽管如此，AntDocs of VuePress 的初衷并没有脱离轨道，秉承 VuePress 为文档而生 理念的同时，还致力于提供给开发者便捷的写作体验以及给读者带来更上一层的阅读体验。

- 推荐理由：搭载了开箱即用的高质量 Ant Design 组件，支持与 Markdown 语法混用，同时具有  Ant Design 风格界面。解决了 VuePress 没有 AntD 文档模板的痛点~

- 更新日志：
    - 0.1.0-beta
        - [新增] 搭载 Ant Design 组件，在 .md 中直接使用；
        - [新增] 添加底部栏，最大支持 4 个栏目数；
        - [优化] 统一预处理器，使用兼容 Ant Design 样式的 Less 语法；
        - [优化] 优化内置的提示、警告、危险块的显示效果；
        - [优化] 优化代码块、行内代码、Blockquote等显示效果；
        - [优化] 优化首页、导航菜单、Github徽标、侧边栏等显示效果；
        - [优化] 优化移动端显示以及动画效果；
        - [修复] 修复其他可能存在问题的BUG；

- 快速上手：
### 安装主题

使用 `yarn` 安装 `AntDocs` 主题：

```bash
yarn add vuepress-theme-antdocs
```

或者使用 `npm` 安装它：

```bash
npm i vuepress-theme-antdocs
```     

### 引用主题    

打开 `.vuepress/config.js` 文件，然后在合适位置引用它：

```js
module.exports = {
  ...
  theme: 'antdocs',
  ...
}
```
配置完毕后，你就可以直接 `yarn run docs:dev` 或 `npm run docs:dev` 查看效果。

- 截图：

![antdocs.png](https://s2.ax1x.com/2020/02/28/3B3lOf.png)

**Comment by 521xueweihan** [comment]
您好，月刊中暂不推荐类似某一个主题的项目。
