### ISSUE TITLE
【自荐】一个自己从零搭建的VUE UI组件库

### ISSUE THREAD

**Issue by Xutaotaotao** [521xueweihan/HelloGitHub#1125]
## 项目推荐
- 项目地址：https://github.com/ninecat-ui/ninecat-ui

- 类别：JS

- 项目后续更新计划：

1.集成codepen
2.颜色主题自定义
3.国际化多语言
4.JavaScript和typescript混合开发
5.很多组件

- 项目描述：
  - 必写：一个从零搭建的VUE UI组件，纯属兴趣。
  - 可选：学习一个组件库的搭建过程及工程化思路。

- 推荐理由：一个让自己成长的项目。

- 截图：（可选）gif/png/jpg
![](https://user-gold-cdn.xitu.io/2020/2/17/17051af5273452eb?w=2878&h=1612&f=png&s=260336)

**Comment by 521xueweihan** [comment]
鼓励你这种从零搭建的动手能力，但是目前有很多成熟的 UI 组建。期待持续维护，成为流行的UI组建库！等你呦～

非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
