### ISSUE TITLE
【自荐】程序员简历例句

### ISSUE THREAD

**Issue by Windsooon** [521xueweihan/HelloGitHub#1126]
## 项目推荐
- 项目地址：https://github.com/resumejob/awesome-resume

- 类别：其他

- 项目后续更新计划：定期更新简历示例

- 项目描述：
  - 必写：这个项目集合了简历常用例句，协助求职者从零开始写简历。
  - 可选：面试求职，可以学习如何组织语言以及表达自己的实际情况
  - 描述长度（不包含示例代码）:  程序员简历例句，程序员简历范例

- 推荐理由：很多求职者没有看过其他人的简历，无法从他人的简历中学习，这个项目从真实的简历中抽出一些比较通用的例子，求职者可以从中修改并在简历中使用。

**Comment by 521xueweihan** [comment]
这种项目是不能收录到月刊中的，如果需要推广合作可以给我发邮件。望您理解
