### ISSUE TITLE
【自荐】C语言多线程扫描IP段端口程序

### ISSUE THREAD

**Issue by kinglyl** [521xueweihan/HelloGitHub#1128]
## 项目推荐
- 项目地址：
https://github.com/nobackdoor/myscan
- 类别：
C
- 项目后续更新计划：
更加清晰的代码，更加详细的注释，支持Linux系统
- 项目描述：
C语言写的windows下多线程socket扫描ip端端口的程序。
可作为初学者参考的项目
- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？
至少在我写这个项目时，网上几乎没有这方面的示例代码和教程。并且目前windows下某些工具包里带的扫描工具基本报毒，网络上也很难找到这些工具的无毒版本。

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 48 期](https://hellogithub.com/periodical/volume/48/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
