### ISSUE TITLE
【自荐】File-Engine效率启动器

### ISSUE THREAD

**Issue by XUANXUQAQ** [521xueweihan/HelloGitHub#1129]
## 项目推荐
- 项目地址：https://github.com/XUANXUQAQ/File-Engine

- 类别：Java

- 项目后续更新计划：
支持动画效果，进一步提高索引速度，支持拼音搜索。
- 项目描述：
  - 这是一个便携绿色的快速Windows启动器，可以大大提高工作效率。对于一些不想在桌面 
放东西，但又需要快速找到并打开文件的人，就可以使用它进行搜索。而且不止可以搜 
索，还可以给任意文件（或文件夹）设置标识，只要输入设置好的标识，就可以迅速打开对 
应文件。

- 推荐理由：UI简单明了，响应速度快，相比同类软件去除了一些臃肿的功能，操作更加顺手。

- 更新日志：
 - V1.6
>添加多线程搜索，提高索引速度。
多线程显示搜索结果。
修复部分情况搜索框无法获取焦点的问题。

- 截图：
![8PPdxS.gif](https://s2.ax1x.com/2020/03/10/8PPdxS.gif)
![8PCAtP.png](https://s2.ax1x.com/2020/03/10/8PCAtP.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
