### ISSUE TITLE
:rocket: 一个查找获取 Emoji 表情的项目

### ISSUE THREAD

**Issue by gee1k** [521xueweihan/HelloGitHub#113]
## 项目推荐
- 项目名称：emoji

- 项目地址：[https://github.com/gee1k/emoji](https://github.com/gee1k/emoji)

- 项目语言：Javascript、Vue

- 项目描述：一个快速查找获取 Emoji 表情名称或者字体的项目

- 推荐理由：有了这个项目能更方便的写README 、ISSUE和commit message了

- 示例代码：:rocket: 

- 截图：![emoji gif](http://ody0ct4r0.bkt.clouddn.com/emoji.gif?new=2)

**Comment by 521xueweihan** [comment]
@gee1k 非常有趣的项目。

是否可以加上中文的支持？因为我当时也要做这么个网站，但是卡在了中文和emoji 的对应上。
是做翻译、自然语言、还是如何实现？

如果你有兴趣，可以做下中文 emoji 的支持。我觉得那就无敌了！

**Comment by gee1k** [comment]
@521xueweihan  我有考虑过加入中文搜索，不过我还没想好具体该如何做，如果手动每一个表情添加中文的话会是一个庞大的工作量，有一千多个emoji。所以接下来我考虑好采用什么方式并尽快完善它💯

**Comment by 521xueweihan** [comment]
@gee1k Cool，有什么新的进展欢迎告知，或者有什么需要帮忙的地方。😁

**Comment by gee1k** [comment]
@521xueweihan  OK，等我加上中文搜索支持，来这里告知你

**Comment by gee1k** [comment]
@521xueweihan 已经加上中文搜索支持 🇨🇳

**Comment by 521xueweihan** [comment]
@gee1k 收到，我刚才试了一下，老铁可以的💪

**Comment by 521xueweihan** [comment]
您推荐的项目，已成功收录在 [HelloGitHub 第 19 期](https://hellogithub.com/volume/19/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，如果方便可以 Star ⭐️ 本项目，让更多人看到本项目。
