### ISSUE TITLE
学习Git分支

### ISSUE THREAD

**Issue by pioneerAlone** [521xueweihan/HelloGitHub#1130]
## 项目推荐
- 项目地址：https://github.com/pcottle/learnGitBranching

- 类别：请从中选择（其它）

- 项目后续更新计划：

- 项目描述：
  - 必写：LearnGitBranching是一个git仓库可视化工具，沙箱，以及一系列教育教程和挑战。
  - 可选：其主要目的是帮助开发人员通过可视化功能（在命令行上工作时缺少的功能）理解git
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：生动形象的帮助初学者了解GIT工作原理以及学习git各种命令

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

## 提示（提交时请删除以下内容）
> 点击上方 “Preview” 更方便地阅读以下内容，

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 48 期](https://hellogithub.com/periodical/volume/48/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
