### ISSUE TITLE
【自荐】神策数据数据采集 SDK 

### ISSUE THREAD

**Issue by richardhxy** [521xueweihan/HelloGitHub#1134]
## 项目推荐
- 项目地址：https://github.com/sensorsdata/sa-sdk-android
https://github.com/sensorsdata/sa-sdk-ios
https://github.com/sensorsdata/sa-sdk-javascript

- 类别：Java、Objective-C、JS

- 项目后续更新计划：公司级别的开源项目，已经持续更新了 4 年时间，后续会一直更新下去

- 项目描述：
  - 必写：工具类项目，主要是数据采集和数据发送，特色功能全埋点（很少的代码自动采集用户行为，如页面浏览、控件点击，非用户隐私数据）
  - 可选：项目较大，内部细节丰富，对于 APP 端研发人员，会有一定的帮助。

- 推荐理由：SDK 有官网文档，文档持续更新维护；有开源社区，开源社区每周都会有原创博客，由浅入深介绍 SDK 内部的细节和实现原理（http://opensource.sensorsdata.cn/）；有开源社群，有 QQ 群、微信群，每日社群中都会有问题讨论。

- 理念：我们坚持推进开源项目，持续迭代数据采集与埋点技术；推广数据采集 SDK 的应用，推动大数据根基建设。

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
