### ISSUE TITLE
【自荐】基于Tp5和Vue的前后端分离商城(B2C)框架开源系统

### ISSUE THREAD

**Issue by dnyz520** [521xueweihan/HelloGitHub#1140]
## 项目推荐
- 项目地址：https://github.com/dnyz520/careyshop-admin

- 类别：JS、VUE

- 项目后续更新计划：

- 项目描述：
CareyShop 商城后台管理系统
CareyShop（简称 CS）是一套基于 ThinkPHP5 框架开发的高性能商城框架系统，秉承简洁、快速、极致的开发理念，框架内使用面向对象模块化调用，在多终端、跨平台时采用 REST API 架构来进行数据交互，可直接对接 PC、移动设备、小程序、云部署，构建 Android、IOS 的 APP。

设计理念
放眼移动热潮、新零售概念、各类终端的增多，服务端会与各类前端进行交互，和第三方相互协作也更加紧密、频繁。出于这样的整体环境，我们摒弃传统开发方向，直接以 REST 架构为基础，将各类业务处理层模块化。

框架所有的业务处理逻辑存放在公共模块目录中，对于框架内的其他模块可通过面向对象的方式调用公共模块，而外部则以 API 接口进行交互，如此真正做到业务处理层的入口路径统一。具体开发使用请参见「CareyShop 完全开发手册」

本项目说
CareyShop 整体的架构理念为前后端分离，这样更容易创建出私有云、微服务、分布式等。商城后台管理系统根据框架所提供的 API 接口而配套的后台管理系统，覆盖了所有管理需要用到的功能模块。

在您使用本项目前，请先安装好 node。项目技术栈基于 es2015+、vue、vuex、vue-router 、vue-cli4 、axios 和 element-ui，所有的请求数据都基于 rest 协议。

导航向导
预览地址 https://demo.careyshop.cn/admin
下载地址 https://github.com/dnyz520/careyshop-admin

文档中心
https://doc.careyshop.cn

- 推荐理由：基于Tp5和Vue的前后端分离商城(B2C)框架开源系统

- 截图：（可选）gif/png/jpg
![image](http://aliyun.oss.careyshop.cn/uploads/files/20200312/d827a47d-b33f-4bb7-8601-d1d78991ddc9.png?type=aliyun)

![image](http://aliyun.oss.careyshop.cn/uploads/files/20200312/66688697-16d5-4d69-8ae8-b12ac435f380.png?type=aliyun)

![image](http://aliyun.oss.careyshop.cn/uploads/files/20200312/b05b7e52-d899-4504-a9a1-3816a7d31f89.png?type=aliyun)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
