### ISSUE TITLE
推荐autokeras

### ISSUE THREAD

**Issue by kaixinbaba** [521xueweihan/HelloGitHub#1147]
## 项目推荐
- 项目地址：https://github.com/keras-team/autokeras

- 类别：请从中选择（机器学习）

- 项目后续更新计划：

- 项目描述：
  - 必写：autoML，自动化机器学习，傻瓜式API，非常简单
  - 可选：适用于什么场景、能够让初学者学到什么
  - 描述长度: keras官方出品，值得信赖，已有6000多的star，3行就能训练一个模型，目前支持的任务：图像分类，图像回归，文本分类，文本回归，结构化数据分类，结构化数据回归。官网地址 ： https://autokeras.com/

- 推荐理由：autoML未来的趋势，将人从手工选择超参数中解放出来，快速开发原型，官方口号“所有人都能使用机器学习”  CPU和GPU训练都能支持

- 示例代码：
安装
```bash
pip install autokeras
```
使用
```python
import autokeras as ak

clf = ak.ImageClassifier()
clf.fit(x_train, y_train)
results = clf.predict(x_test)
```
- 截图：（可选）gif/png/jpg
![image](https://user-images.githubusercontent.com/22809336/77333817-f1d76500-6d5e-11ea-92d6-0afaef61d542.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 48 期](https://hellogithub.com/periodical/volume/48/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
