### ISSUE TITLE
【自荐】B站av号和BV字符串之间的转换

### ISSUE THREAD

**Issue by MOHJ0558** [521xueweihan/HelloGitHub#1148]
## 项目推荐
- 项目地址：https://github.com/MOHJ0558/Bilibili_Conversion_between_av_and_BV

- 类别：C++
- 项目后续更新计划：偶尔更新

- 项目描述：这是个bilibili的av号和BV号之间的转换，**算法核心来源于知乎用户mcfx**，源代码是Python，没有交互界面，我把它人工转换成了C++，已经过本人同意。（更新）在第三版中增加了导出到文件，解决了在Windows系统下没有安装Python环境不能运行的痛点。

- 推荐理由：能在Windows/Linux/macOS下运行（只发布了Windows下的可执行文件），只有一个文件，可以很方便的编译，相对于Python增加了交互界面和导出到文件。

**Comment by 521xueweihan** [comment]
赞！解决痛点。但该项目暂未达到收录到月刊的标准望您理解。


非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
