### ISSUE TITLE
欠曝光照片的图像增强

### ISSUE THREAD

**Issue by aeinrw** [521xueweihan/HelloGitHub#1149]
## 项目推荐
- 项目地址：https://github.com/aeinrw/LIME

- 类别：Python

- 项目后续更新计划：利用深度学习使效果进行增强,对图像处理速度进行优化

- 项目描述：
  - 这是一个使用python写的对欠曝光照片进行增强的算法实现
  - 根据https://doi.org/10.1109/TIP.2016.2639450 论文所描述的算法进行的python实现,论文并没有给出代码实现,这个项目算是复现别人的工作

- 推荐理由：照片增强效果好,速度较快

- 截图：
![image](https://user-images.githubusercontent.com/44741763/77447926-329cb000-6e2b-11ea-8ce9-9ec789c723c5.png)
![image](https://user-images.githubusercontent.com/44741763/77447940-3597a080-6e2b-11ea-849d-5b2305ab98ec.png)

**Comment by MOHJ0558** [comment]
噪点有点明显，不过很不错！

**Comment by 521xueweihan** [comment]
请继续加油！

非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by wodeking** [comment]
mark
