### ISSUE TITLE
python的orm library，小巧灵活：orator

### ISSUE THREAD

**Issue by franklingu** [521xueweihan/HelloGitHub#115]
## 项目推荐
- 项目名称：
orator
- 项目地址：
https://github.com/sdispater/orator
- 项目语言：
python
- 项目描述：
The Orator ORM provides a simple yet beautiful ActiveRecord implementation. 
- 推荐理由：
The Orator ORM provides a simple yet beautiful ActiveRecord implementation.

It is inspired by the database part of the Laravel framework, but largely modified to be more pythonic.
- 示例代码：
```python
from orator import DatabaseManager, Model

config = {
    'mysql': {
        'driver': 'mysql',
        'host': 'localhost',
        'database': 'database',
        'user': 'root',
        'password': '',
        'prefix': ''
    }
}

db = DatabaseManager(config)
Model.set_connection_resolver(db)

class User(Model):
    pass

users = User.where('votes', '>', 100).take(10).get()

for user in users:
    print(user.name)
```

**Comment by 521xueweihan** [comment]
@franklingu 
How about this ORM?

https://github.com/coleifer/peewee

**Comment by franklingu** [comment]
sqlalchemy，django orm和peewee感觉都是很mature的，这个相比起来就新多了，而且它是lavarvel的rewrite的感觉

如果推荐mature的给新手当然好了，不过我个人就是说这个很好玩儿的啊

**Comment by anson2416** [comment]
ORM得意思是？

**Comment by franklingu** [comment]
object relational mapping
