### ISSUE TITLE
Cpp-Taskflow v2.4：CPU-GPU 異構計算 (Heterogeneous Computing) 新功能

### ISSUE THREAD

**Issue by tsung-wei-huang** [521xueweihan/HelloGitHub#1151]
## 项目推荐
- 项目地址：https://github.com/cpp-taskflow/cpp-taskflow

- 类别：C++, CUDA, GPU

- 项目后续更新计划：強化異構計算 (Heterogeneous Computing) 能力

- 项目描述：
  - 必写：一個輕便的函式庫幫助系統軟體開發者快速處理 CPU-GPU 運算
  - 可选：高效能計算，機器學習，GPU-CPU 平行加速
  - 描述长度（不包含示例代码）: Cpp-Taskflow v2.4 引入了兩個新功能，包含 conditional tasking 去處理迴圈以及 CPU-GPU 共同運算，大幅幫助了許多機器學習開發者需要運用到的運算功能

- 推荐理由：好寫，輕巧，高效能

- 示例代码：一個 CPU-GPU 共同計算範例

![image](https://user-images.githubusercontent.com/13237509/77572731-1c2b3e80-6e95-11ea-8b0b-b4d496d06cf1.png)

```cpp
tf::Taskflow taskflow;
tf::Executor executor;

const unsigned N = 1<<20;                               
std::vector<float> hx(N, 1.0f), hy(N, 2.0f);  // x and y vectors at host
float *dx{nullptr}, *dy{nullptr};  // x and y vectors at device

tf::Task allocate_x = taskflow.emplace([&](){ cudaMalloc(&dx, N*sizeof(float));});
tf::Task allocate_y = taskflow.emplace([&](){ cudaMalloc(&dy, N*sizeof(float));});
tf::Task cudaflow = taskflow.emplace([&](tf::cudaFlow& cf) {
  tf::cudaTask h2d_x = cf.copy(dx, hx.data(), N);    // host-to-device x data transfer
  tf::cudaTask h2d_y = cf.copy(dy, hy.data(), N);    // host-to-device y data transfer
  tf::cudaTask d2h_x = cf.copy(hx.data(), dx, N);    // device-to-host x data transfer
  tf::cudaTask d2h_y = cf.copy(hy.data(), dy, N);    // device-to-host y data transfer
  // launch saxpy<<<(N+255)/256, 256, 0>>>(N, 2.0f, dx, dy)
  tf::cudaTask kernel = cf.kernel((N+255)/256, 256, 0, saxpy, N, 2.0f, dx, dy);
  kernel.succeed(h2d_x, h2d_y)
        .precede(d2h_x, d2h_y);
});
cudaflow.succeed(allocate_x, allocate_y);            // overlap data allocations

executor.run(taskflow).wait();
```

saxpy CUDA kernel 如下：

```cpp
// saxpy (single-precision A·X Plus Y) kernel
__global__ void saxpy(int n, float a, float *x, float *y) {
  int i = blockIdx.x*blockDim.x + threadIdx.x;
  if (i < n)  y[i] = a*x[i] + y[i];
}
```

## 提示（提交时请删除以下内容）
> 点击上方 “Preview” 更方便地阅读以下内容，

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
老哥，咋又来推荐了一遍，推荐过的项目不会重复收录。。。就算是有革命性的更新。
