### ISSUE TITLE
Go图表可视化库—go-echarts

### ISSUE THREAD

**Issue by Yanwenjiepy** [521xueweihan/HelloGitHub#1152]
## 项目推荐
- 项目地址：https://github.com/go-echarts/go-echarts

- 类别：Go

- 项目后续更新计划：持续更新

- 项目描述：
  - 必写：go-echarts是一个优秀的数据图表可视化库，拥有丰富的图表和良好的交互性
  - 可选：适用于数据图表展示需求，使用Go就可以实现echarts的效果
  - 特性：
    - 简洁的 API 设计，使用如丝滑般流畅
    - 囊括了 25+ 种常见图表，应有尽有
    - 高度灵活的配置项，可轻松搭配出精美的图表
    - 详细的文档和示例，帮助开发者更快的上手项目
    - 多达 400+ 地图，为地理数据可视化提供强有力的支持

- 推荐理由：在 Golang 这门语言中，目前数据可视化的第三方库还是特别少，go-echarts 填补了这部分的空隙。

- 示例代码：
```package main
import (
	"log"
	"os"
	"github.com/chenjiandongx/go-echarts/charts"
)

func main() {
	nameItems := []string{"衬衫", "牛仔裤", "运动裤", "袜子", "冲锋衣", "羊毛衫"}
	bar := charts.NewBar()
	bar.SetGlobalOptions(charts.TitleOpts{Title: "Bar-示例"})
	bar.AddXAxis(nameItems).AddYAxis(
		"商家A", []int{20, 30, 40, 10, 24, 36},
		).AddYAxis(
			"商家B", []int{35, 14, 25, 54, 22, 15},
			)
	f, err := os.Create("bar.html")
	if err != nil {
		log.Fatal(err)
	}
	bar.Render(f)
}
```

- 截图：

![image](https://user-images.githubusercontent.com/32814388/77618459-4fdb9680-6f71-11ea-9f19-fb2ba0470544.png)

![image](https://user-images.githubusercontent.com/32814388/77618308-0b4ffb00-6f71-11ea-8d6b-de41e6d09e6e.png)

![image](https://user-images.githubusercontent.com/32814388/77618523-70a3ec00-6f71-11ea-99e3-69b982e53a20.png)

**Comment by 521xueweihan** [comment]
该项目已推荐过。
