### ISSUE TITLE
SweetMusicPlayer

### ISSUE THREAD

**Issue by hellowHuaairen** [521xueweihan/HelloGitHub#1153]
## 项目推荐
- 项目地址：https://github.com/WellerV/SweetMusicPlayer

- 类别：Java

- 项目后续更新计划：

- 项目描述：
  - 必写：安卓版的音乐播放器
  - 可选：后端调用百度音乐的api接口
  - 描述长度（不包含示例代码）: 功能挺完善的

- 推荐理由：SweetMusicPlayer是一款基于百度音乐API的在线音乐播放器。拥有播放本地、在线音乐以及mv等功能，采用 MVP + RxJava + Retrofit 架构的项目, 使用Java和Kotlin混合开发。

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

![](https://github.com/WellerV/SweetMusicPlayer/raw/master/screenshots/1_1.png)
![](https://github.com/WellerV/SweetMusicPlayer/raw/master/screenshots/1_2.png)
![](https://github.com/WellerV/SweetMusicPlayer/raw/master/screenshots/1_3.png)

**Comment by 521xueweihan** [comment]
此类项目容易受版权影响被迫删除。
