### ISSUE TITLE
logcat-swift

### ISSUE THREAD

**Issue by limall** [521xueweihan/HelloGitHub#1155]
## 项目推荐
- 项目地址：https://github.com/limall/logcat-swift

- 类别：JS、Swift

- 项目后续更新计划：添加功能将打印日志保存到本地数据库中

- 项目描述：一个apple平台打印日志的轻量级系统，能够有条理地打印日志，并且提供各种过滤日志的功能。打印端具有极高的复用性，使用electron开发，本身可以跨平台；通过Udp协议接收消息，为调试带来便利的同时，也提高了打印端应用于其它平台的可能性。目前代码只有五百多行。

- 推荐理由：轻量，跨平台

- 示例代码：（可选）长度：1-20 行

- 截图：![a.png](https://upload-images.jianshu.io/upload_images/11219572-090691f9d318fb4b.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
