### ISSUE TITLE
[自荐] SQL 语法增强工具 - sqlx

### ISSUE THREAD

**Issue by taojy123** [521xueweihan/HelloGitHub#1158]
## 项目推荐
- 项目地址：https://github.com/taojy123/sqlx

- 类别：其它（sql）

- 项目后续更新计划：
  目前语法还不支持 `if` 嵌套和 `for` 循环嵌套，后续会开发支持嵌套语法；另外目前 sqlx 已经做了 `Sublime Text` 插件，后续可能还会开发 `VS Code` 插件。

- 项目描述：
  强大的 SQL 语法拓展，目标是打造 "易读易写 方便维护" 的 sql 脚本，sqlx 意为 `SQL Extension`

- 推荐理由：
  适用于经常需要写复杂的 sql 查询做统计的同学，其实这也是本人在工作中的痛点，所以做了此工具，并希望同遇到相同困惑的同学分享。

- 插件支持：
  `sqlx` 已被 `Sublime Text` 官方收录，使用 `Sublime Text` 的同学可以直接搜索安装 `Sqlx Builder` 插件，并通过编辑器的 build 操作快捷的编译 `sqlx` 脚本。

![](https://raw.githubusercontent.com/taojy123/SublimeText-Sqlx/master/sqlx.png)

![](https://raw.githubusercontent.com/taojy123/SublimeText-Sqlx/master/sqlx2.png)

- 插件项目地址：https://github.com/taojy123/SublimeText-Sqlx

- 应用场景示例：

假设有一张商品价目表(product)，每天价格变动的商品都会更新报价。

例如，苹果的最新价格为 10 元, 因为苹果最新的一次报价是在 20191211, 当时价格为 10 元。

name(商品名称)|price(价格)|date(报价日期)
-|-|-
苹果|15|20191208
香蕉|18|20191208
橘子|12|20191208
香蕉|16|20191209
橘子|11|20191209
苹果|11|20191210
橘子|13|20191210
苹果|10|20191211
香蕉|22|20191211
橘子|14|20191212

现在要求通过 sql 统计出 `20191212 这天的平均价格 比 20191209 那天涨了多少` ?

正常情况下我们可能会写出这样的 sql
```sql
SELECT
    a1.avg_price AS `20191209 平均价格`,
    a2.avg_price AS `20191212 平均价格`,
    (a2.avg_price - a1.avg_price) AS `涨价金额`
FROM
    (
        -- 求出各类别 20191209 前最后一次报价的平均价格
        SELECT
            avg(product.price) AS avg_price
        FROM
            (
                -- 求出各商品在 20191209 前最后一次报价的日期
                SELECT
                    name,
                    max(date) AS max_date
                FROM
                    product
                WHERE
                    date <= '20191209'
                GROUP BY
                    name
            ) AS t1
        LEFT JOIN product
        ON t1.name = product.name AND t1.max_date = product.date
    ) AS a1
LEFT JOIN
    (
        -- 再求出各类别 20191212 前最后一次报价的平均价格
        SELECT
            avg(product.price) AS avg_price
        FROM
            (
                -- 先求出各商品在 20191212 前最后一次报价的日期
                SELECT
                    name,
                    max(date) AS max_date
                FROM
                    product
                WHERE
                    date <= '20191212'
                GROUP BY
                    name
            ) AS t2
        LEFT JOIN product
        ON t2.name = product.name AND t2.max_date = product.date
    ) AS a2
ON true
```

得到统计结果如下:

20191209 平均价格|20191212 平均价格|涨价金额
-|-|-
14.0000|15.3333|1.3333

传统做法虽然得到的结果是正确的，但同时暴露出以下问题:
1. 子查询多层嵌套，代码可读性极低
2. `t1` `t2` 两个子查询内容基本一致，也就说我们要维护两处相同的代码
3. `a1` `a2` 两个子查询也基本一致，并且其中相同的注释我们要写两遍，感觉太"蠢"了
4. 这只是个很简单的示例，在实际工作中，针对更复杂的统计需求，代码的复杂度将会以指数形式递增

下面看看如何使用 sqlx 来解决上述问题:
```sql
func product_max_date(day)
    -- 子查询: 统计出各个商品在 {day} 前最后一次报价的日期
    (
        SELECT
            name,
            max(date) AS max_date
        FROM
            product
        WHERE
            date <= '{day}'
        GROUP BY
            name
    )
end

func date_avg_price(day):
    -- 子查询: 统计出 {day} 这天各个类别的平均价格
    (
        SELECT
            avg(product.price) AS avg_price
        FROM
            {product_max_date($day)} AS t1
        LEFT JOIN product 
        ON t1.name = product.name AND t1.max_date = product.date
    )
end

SELECT
    a1.avg_price AS `20191209 平均价格`,
    a2.avg_price AS `20191212 平均价格`,
    (a2.avg_price - a1.avg_price) AS `涨价金额`
FROM
    {date_avg_price(20191209)} AS a1
LEFT JOIN 
    {date_avg_price(20191212)} AS a2
ON true
```

优势非常明显:
1. 核心代码是一段短小的 `SELECT`，外加加上两个子查询的定义就搞定了，代码逻辑清晰，可读性高
2. `a1` `a2` 使用类似 `函数` 的概念进行封装，通过传入不同的参数来生成不同的子查询内容
3. 相同逻辑的代码片段只需要写一遍，大大降低了代码维护的工作量
4. 使用 sqlx 提供的编译工具或插件，可快速编译成 sql 代码，在数据库中执行结果一致

**Comment by taojy123** [comment]
应用场景示例，之前的例子有点长，我改简化了一些

**Comment by bihell** [comment]
> 应用场景示例，之前的例子有点长，我改简化了一些

我经常要写复杂的Sql看了你的事例，我感觉意义不大，专门去学你这个成本太高了

**Comment by taojy123** [comment]
其实学习成本也不算高，常用的简单说就是 **将 sql 中重复的部分集中写到一个 func 定义中去**。

并且 sqlx 是完全兼容 sql 的。也就是说，刚开始可以直接在 sqlx 文件中写纯 sql，接下来可以用 func 语法去优化它。添砖加瓦的维护自己的代码。

但有一种场景确实不太适用。比如，写的 sql 虽然复杂，但只执行一次，不需要保存到本地文件，不需要考虑可读性，后期一般也不会修改和维护。这种场景下使用 sqlx 确实会将简单的问题变复杂。😄

**Comment by 521xueweihan** [comment]
@taojy123 我看了下项目，依赖 Python 解析。那么如果是数据处理的话，可以用 Python 的 pandas 库处理数据可能会更加灵活。

非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
