### ISSUE TITLE
livepython:Visually trace your Python code in real time.

### ISSUE THREAD

**Issue by franklingu** [521xueweihan/HelloGitHub#116]
## 项目推荐
- 项目名称：
livepython
- 项目地址：
https://github.com/agermanidis/livepython
- 项目语言：
python, javascript
- 项目描述：
Visually trace your Python code in real time.
- 推荐理由：
Watch your Python run like a movie.
- 示例代码：

- 截图：
![from official repo](https://camo.githubusercontent.com/263dfee8edae7df3cadf769435d39c878c1fc7d0/68747470733a2f2f692e696d6775722e636f6d2f54534e4a4a436d2e676966)

**Comment by 521xueweihan** [comment]
@JameJJ 老铁评估下这个项目
