### ISSUE TITLE
[自荐]轻量级CSS框架aqua.css

### ISSUE THREAD

**Issue by alphardex** [521xueweihan/HelloGitHub#1163]
## 项目推荐
- 项目地址：https://github.com/alphardex/aqua.css

- 类别：CSS

- 项目后续更新计划：持续更新

- 项目描述：一款轻量级的CSS框架，里面的UI组件都十分精美，而且还可以用CSS变量来自由定制外观。本项目还用到了很多有趣且实用的 CSS 技巧，非常适合学习。

- 推荐理由：
	- **UI精美**，高颜值网站的不二之选
	- **定制性强**，网站一键换肤不在话下
	- **有学习价值**，用到了很多实用的 CSS 技巧

- 截图：（可选）gif/png/jpg
![Dashboard](https://user-gold-cdn.xitu.io/2020/4/2/1713911e73046096?imageslim)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
