### ISSUE TITLE
[自荐]一种基于正则表达式的问题同义转换方法

### ISSUE THREAD

**Issue by TianhaoFu** [521xueweihan/HelloGitHub#1165]
## 项目推荐
- 项目地址：https://github.com/TianhaoFu/RegEx_based_convertor

- 类别：机器学习

- 项目后续更新计划：发展为一个Pytorch的函数或者是模块

- 项目描述：
句子的同义转换是一个很常见的NLP任务，现在很多人用机器学习的方法来做此任务。有时候结合其他方法来做同义转换能够帮助提高算法的performance，所以这里有一种将规则表示为正则表达式的形式来实现句子的同义转换的方法，来帮助你提高performace，从而或许会对你的论文或者是毕业有帮助。

- 推荐理由：能够提高NLP任务同义转换的performance，对做NLP任务的人无异于是一个福音

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
