### ISSUE TITLE
[自荐] A repository for studying WebSocket protocol and TCP programming

### ISSUE THREAD

**Issue by yeqown** [521xueweihan/HelloGitHub#1167]
## 项目推荐
- 项目地址：https://github.com/yeqown/websocket

- 类别：Go

- 项目后续更新计划：

目前已经实现了服务端和客户端的API，能够正确建立连接，完成握手，收发消息和关闭连接，支持处理Websocket分片。后续计划：

1. WebSocket protocol文档与代码实现结合解读
2. 打磨代码细节，优化阅读体验
3. 完善Conn的状态管理和切换
4. 增加单元测试覆盖率
5. 增加对TLS（即WSS）的支持，和示例代码

- 项目描述： 

 基于Go实现了Websocket协议，实现比较轻量易读，对正在学习和使用websocket的Go开发者有帮助。

- 推荐理由：

希望帮助到需要了解Go中TCP编程，Websocket编程以及想要熟悉websocket协议的开发者。

- 示例代码：（可选）长度：1-20 行
```go
// examples/use-as-client/main.go
conn, err = websocket.Dial("ws://localhost:8080/echo")
if err != nil {
    panic(err)
}
go func() {
    for {
        if err = conn.SendMessage("hello"); err != nil {
            fmt.Printf("send failed, err=%v\n", err)
        }
        time.Sleep(3 * time.Second)
    }
}()

for {
    mt, msg, err := conn.ReadMessage()
    if err != nil {
        if ce, ok := err.(*websocket.CloseError); ok {
            fmt.Printf("close err=%d, %s", ce.Code, ce.Text)
            break
        }
        fmt.Printf("recv failed, err=%v\n", err)
        time.Sleep(1 * time.Second)
    }
    fmt.Printf("messageType=%d, msg=%s\n", mt, msg)
}
```

- 截图：（可选）gif/png/jpg

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
