### ISSUE TITLE
[自荐]Flutter混合栈管理插件 thrio

### ISSUE THREAD

**Issue by foxsofter** [521xueweihan/HelloGitHub#1168]
## 项目推荐
- 项目地址：https://github.com/hellobike/thrio

- 类别：Objective-C、Flutter、Kotlin

- 项目后续更新计划：

- 项目描述：
  - 必写：提供Flutter嵌入iOS和Android App的相对完整的路由解决方案
  - 可选：需要在iOS和Android的App中引入Flutter时可考虑使用
  - 描述长度（不包含示例代码）: thrio提供三端统一的路由API，并遵循谷歌建议的Flutter嵌入原生App的最佳实践实现混合栈的管理，比目前主流的flutter_boost在内存开销上有比较明显的优势。

- 推荐理由：相对主流的混合栈管理框架，thrio提供开箱即用的路由API，并保持三端的一致性和互通性，同时在内存管理上有极大的优势。

- 示例代码：（可选）长度：

#### 页面的push

* dart 端打开页面

```dart
ThrioNavigator.push(url: 'flutter1');
// 传入参数
ThrioNavigator.push(url: 'native1', params: { '1': {'2': '3'}});
// 是否动画，目前在内嵌的dart页面中动画无法取消，原生iOS页面有效果
ThrioNavigator.push(url: 'native1', animated:true);
// 接收锁打开页面的关闭回调
ThrioNavigator.push(
    url: 'biz2/flutter2',
    params: {'1': {'2': '3'}},
    poppedResult: (params) => ThrioLogger.v('biz2/flutter2 popped: $params'),
);
```

* iOS 端打开页面

```objc
[ThrioNavigator pushUrl:@"flutter1"];
// 接收所打开页面的关闭回调
[ThrioNavigator pushUrl:@"biz2/flutter2" poppedResult:^(id _Nonnull params) {
    ThrioLogV(@"biz2/flutter2 popped: %@", params);
}];
```

* Android 端打开页面

```kotlin
ThrioNavigator.push(this, "biz1/flutter1",
        mapOf("k1" to 1),
        false,
        poppedResult = {
            Log.e("Thrio", "native1 popResult call params $it")
        }
)
```

- 截图：（可选）gif/png/jpg

![thrio](https://github.com/hellobike/thrio/blob/master/docs/imgs/thrio.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
