### ISSUE TITLE
fd: A simple, fast and user-friendly alternative to find. 

### ISSUE THREAD

**Issue by franklingu** [521xueweihan/HelloGitHub#117]
## 项目推荐
- 项目名称：
fd
- 项目地址：
https://github.com/sharkdp/fd
- 项目语言：
Rust
- 项目描述：
A simple, fast and user-friendly alternative to find. 
- 推荐理由：
fd is a simple, fast and user-friendly alternative to find.

While it does not seek to mirror all of find's powerful functionality, it provides sensible (opinionated) defaults for 80% of the use cases.
- 示例代码：

- 截图：
![demo from official repo](https://camo.githubusercontent.com/7f1a80fe54ca14295869160b6e81994ba7947c69/687474703a2f2f692e696d6775722e636f6d2f6b544d465356552e676966)

**Comment by JameJJ** [comment]
你好，能不能描述一下自己使用的体验，比如说中文支持度之类的，谢谢啦😂

**Comment by franklingu** [comment]
sorry，回复有点儿慢，我自己其实没怎么用太多，就是感觉还算挺快的而且比起find来说

**Comment by 521xueweihan** [comment]
@franklingu 
因为现在还没有推荐过 Rust 的项目，但是我也有一只关注过该语言动态，但不是很深入。
同时也在考虑是否新增 Rust 语言分类。但是精力有限，新增一个分类如果没有持续内容推荐，意义不大。

所以，朋友是否考虑加入 HelloGitHub 长期负责某一分类的项目推荐？

**Comment by franklingu** [comment]
我平时来说用python更多，就是觉得rust好玩儿啊！也是不太深入的其实

不过rust，go，scala都算是很promising，值得explore的语言诶

**Comment by 521xueweihan** [comment]
@franklingu 是的，我也是觉得 rust、go 前景光明
