### ISSUE TITLE
计算中间件开源项目Linkis推荐

### ISSUE THREAD

**Issue by peacewong** [521xueweihan/HelloGitHub#1170]
## 项目推荐
- 项目地址：
https://github.com/WeBankFinTech/Linkis
- 类别：请从中选择（C、C#、C++、CSS、Go、Java、JS、Kotlin、Objective-C、PHP、Python、Ruby、Swift、其它、书籍、机器学习）
Java/大数据
- 项目后续更新计划：
每个月会更新，现在有多家公司参与一起共建
- 项目描述：
Linkis是一个打通了多个计算存储引擎如：Spark、TiSpark、Hive、Python和HBase等，对外提供统一REST/WebSocket/JDBC接口，提交执行SQL、Pyspark、HiveQL、Scala等脚本的计算中间件。
Linkis基于微服务架构，提供了金融级多租户隔离、资源管控、权限隔离等企业级特性，支持统一变量、UDF、函数、用户资源文件管理，具备高并发、高性能、高可用的大数据作业/请求全生命周期管理能力

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？
解决复杂环境下各种类型的大量计算任务，都能更简洁、灵活、有序、可控的提交执行，和保障成功返回结果
- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg
![linkis](https://github.com/WeBankFinTech/Linkis/blob/master/images/linkis-intro-03.png?raw=true)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 49 期](https://hellogithub.com/periodical/volume/49/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）

**Comment by peacewong** [comment]
您好，感谢您的帮助，已经star和fork，我这边现在加您

**Comment by blank-1** [comment]
flink支持版本预计什么时候发布
