### ISSUE TITLE
代码生成工具

### ISSUE THREAD

**Issue by jackcooper2015** [521xueweihan/HelloGitHub#1172]
## 项目推荐
- 项目地址：https://github.com/jackcooper2015/mybatisplus-generator-web

- 类别：Java,代码生成工具

- 项目后续更新计划：

- 项目描述：
  - 名称：基于mybatis-plus的在代码生成工具
  - 可用于：基于mybatis-plus的任何web项目开发
  - 描述：节省70%的开发工作

- 推荐理由：
      1、节省70%的开发工作
      2、在线生成代码，包含Mapper,service,controller,element-ui的页面

- 截图：
![image](https://user-images.githubusercontent.com/10961327/78251685-49768d00-7524-11ea-9c9b-48bef20fea41.png)
![image](https://user-images.githubusercontent.com/10961327/78251529-116f4a00-7524-11ea-81a7-81e4e250f4c8.png)
![image](https://user-images.githubusercontent.com/10961327/78251607-2cda5500-7524-11ea-88ad-10c0091fb49b.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
