### ISSUE TITLE
[自荐]基于elementui的vue扩展组件库

### ISSUE THREAD

**Issue by chfree** [521xueweihan/HelloGitHub#1173]
## 项目推荐
- 项目地址：
[https://github.com/chfree/think-vuele](https://github.com/chfree/think-vuele)

- 类别：js

- 项目后续更新计划：
   持续加入新的控件和优化现有控件的不足

- 项目描述：
  - 基于Vue和ElementUI框架进行整合二次开发的一个框架.提供一些elementUI没有的或当时没有的控件.优化了或简化了便于2B软件开发的一些控件 框架结构按element源码结构进行改造

- 推荐理由：复杂的功能组件来帮你实现，你只管写业务代码。

- 示例代码：示例功能，可以参见[vuele.tennetcn.com](vuele.tennetcn.com)

- 截图：如下或示例功能，可以参见[vuele.tennetcn.com](vuele.tennetcn.com)

![block](https://user-images.githubusercontent.com/3860751/78317675-89c22380-7595-11ea-9f6f-39f51b364705.png)
![clamp](https://user-images.githubusercontent.com/3860751/78317682-8cbd1400-7595-11ea-80a5-43b0b4b9526f.png)
![codeDisplay](https://user-images.githubusercontent.com/3860751/78317683-8dee4100-7595-11ea-97d5-5941c197a059.png)
![dialog](https://user-images.githubusercontent.com/3860751/78317688-8fb80480-7595-11ea-90be-df125e617d49.png)
![edittable](https://user-images.githubusercontent.com/3860751/78317690-90509b00-7595-11ea-8776-89af1f721f8f.png)
![tag](https://user-images.githubusercontent.com/3860751/78317691-90e93180-7595-11ea-8fbf-67dcc958d76e.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
