### ISSUE TITLE
[自荐]ShortCommand（快捷命令）

### ISSUE THREAD

**Issue by Mengzuozhu** [521xueweihan/HelloGitHub#1177]
## 项目推荐
- 项目地址：https://github.com/Mengzuozhu/ShortCommand

- 类别：C#

- 项目后续更新计划：暂定

- 项目描述：
  - Windows桌面程序，使用自定义命令，快速打开文件、文件夹、应用和网页，以及唤起网络搜索引擎

- 推荐理由：
  - “一次配置，快捷使用”
  - 命令自动补全
  - 一个`自定义命令`，即可快速打开文件、文件夹、网页，以及当做轻量搜索引擎使用

- 截图：
![demo](https://user-images.githubusercontent.com/30893207/78366539-38488180-75f3-11ea-8887-06d1cfe41f0d.gif)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
