### ISSUE TITLE
[自荐]: 一份开源学习资料

### ISSUE THREAD

**Issue by guang19** [521xueweihan/HelloGitHub#1179]
## 项目推荐
- 项目地址：[framework-learning](https://github.com/guang19/framework-learning)

- 类别：书籍

- 项目后续更新计划：我会持续更新我学过的但还没有添加到项目的内容，包括以后我所学习知识也都会添加到项目中去。

- 项目描述：
  - 这是一份开源学习资料，以markdown形式编写，包含了许多Java开发者学习所需的内容，如:jvm,orm,spring,redis,mysql等等。

  - 项目暂时定位面向Java方向的的初学者。

  - 提供Gitbook网页阅读版，使得阅读体验大大提高。

- 推荐理由: "天下文章一大抄。" 这句话在我个人学习Jvm的时候感触最为深刻，网上各个社区充斥着重复，抄袭，质量参差不齐的文章(有很多文章还是非常好的)。当初学者想学习某个方面的知识的时候，他的途径不外乎: 官方文档，视频教程，靠搜索引擎搜索的文章，博客等等，而一些博客文章往往给初学者一些错误的引导，而我做这个项目的起因就是想初学者少走一些弯路，避免对网上的文章产生过度依赖。当然，以我目前的能力肯定无法做到我所理想的那个目标，但我会一直坚持下去。

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
