### ISSUE TITLE
Lilith - A terminal QR Code Generator.

### ISSUE THREAD

**Issue by RitterHou** [521xueweihan/HelloGitHub#118]
## 项目推荐
- 项目名称：Lilith

- 项目地址：https://github.com/RitterHou/Lilith

- 项目语言：Python

- 项目描述：一个命令行生成二维码的软件

- 推荐理由：可以在Linux或Mac下的终端上生成二维码，使用方便~~~

- 示例代码：```lilith https://github.com```

- 截图：[![asciicast](https://asciinema.org/a/bSI9XmBlvX1zsc99pkRQt6FIj.png)](https://asciinema.org/a/bSI9XmBlvX1zsc99pkRQt6FIj)

**Comment by 521xueweihan** [comment]
@RitterHou 
您好，我之前看到过类似的项目：https://github.com/mnooner256/pyqrcode，不仅支持 URL 转化二维码，还支持图片转化。

月刊中还推荐过：https://github.com/sylnsfar/qrcode。

所以，您的项目对比这两个项目有什么独特的地方？欢迎讨论。
