### ISSUE TITLE
octotree

### ISSUE THREAD

**Issue by ChungZH** [521xueweihan/HelloGitHub#1182]
## 项目推荐
- 项目地址：https://github.com/ovity/octotree

- 类别：JS

- 项目后续更新计划：

- 项目描述：octotree 是一款 GitHub 浏览器扩展，支持 Chrome(Chromium Edge)，Firefox，Opera 和 Safari。它可以在 GitHub Repo 的侧栏显示出这个项目的文件结构并查找其中的文件。

- 推荐理由：强大

- 示例代码：（可选）长度：1-20 行

- 截图：![image](https://github.com/ovity/octotree/raw/master/docs/demo.gif)

**Comment by 521xueweihan** [comment]
已推荐过。
