### ISSUE TITLE
[自荐]一个不需要会Canvas绘图就能在网页中插入仪表盘的小插件 Dashboard.js

### ISSUE THREAD

**Issue by zbLiuLiu** [521xueweihan/HelloGitHub#1185]
## 项目推荐
- 项目地址：https://github.com/zbLiuLiu/Dashboard.js

- 类别：HTML

- 项目后续更新计划：增加更多自定义属性，增加一个新标签&lt;dashboard>

- 项目描述：  一个Canvas仪表盘，直接增加、删除或修改canvas标签上相应的属性即可使用仪表盘来呈现自己的数据，可配合Vue.js等框架使用

- 推荐理由：使用方便。

- 示例代码：
```
<canvas id="canvas" width="300" height="300" data-score="50"></canvas>
<script src="Dashboard.js"></script>
<script>
	dashboard("canvas", 1000)
</script>
```

- 截图：由于懒得截图所以没有OwO...反正代码量也不多，你们自己试一下就好了嘛...

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
