### ISSUE TITLE
[自荐]高仿小米商城全栈项目（包含PC端Web、微信小程序、独立后端）

### ISSUE THREAD

**Issue by hai-27** [521xueweihan/HelloGitHub#1186]
## 项目推荐

- 项目地址：
  - 前端：https://github.com/hai-27/vue-store
  - 小程序：https://github.com/hai-27/store-miniprogram
  - 后端：https://github.com/hai-27/store-server
- 类别：JS
- 项目后续更新计划：
  - 继续完善该项目
  - 增加一个管理后台
- 项目描述：
  - 基于Vue+Vue-Router+Vuex+Element-ui+axios，参考小米商城，实现的电商PC端Web项目。
  - 基于原生微信小程序实现的仿小米商城微信小程序。
  - 基于node.js(Koa框架)+mysql实现独立后端。
  - 适合初学者，前端部分可以学到Vue全家桶、Element-ui、axios的基本使用；可以学到原生微信小程序的基本使用；后端部分可以学到，node.js(Koa框架)的基本使用。
- 推荐理由：高仿小米商城，全栈商城项目，微信小程序项目。
- 截图：

- PC端截图

**首页**

![](https://raw.githubusercontent.com/hai-27/vue-store/master/public/screenshots/home.png)

**全部商品**

![](https://raw.githubusercontent.com/hai-27/vue-store/master/public/screenshots/goods.png)

**购物车**

![](https://raw.githubusercontent.com/hai-27/vue-store/master/public/screenshots/shoppingCart.png)

**我的收藏**

![](https://raw.githubusercontent.com/hai-27/vue-store/master/public/screenshots/collect.png)

**我的订单**

![](https://raw.githubusercontent.com/hai-27/vue-store/master/public/screenshots/order.png)

  - 小程序截图

**首页**

![](https://raw.githubusercontent.com/hai-27/vue-store/master/public/screenshots/weChatMiniProgramScreenshots/home.png)

**发现（即全部商品）**

![](https://raw.githubusercontent.com/hai-27/vue-store/master/public/screenshots/weChatMiniProgramScreenshots/goods.png)

**商品详情页**

![](https://raw.githubusercontent.com/hai-27/vue-store/master/public/screenshots/weChatMiniProgramScreenshots/detail.png)

**我的购物车**

![](https://raw.githubusercontent.com/hai-27/vue-store/master/public/screenshots/weChatMiniProgramScreenshots/shoppingCart.png)

**订单结算**

![](https://raw.githubusercontent.com/hai-27/vue-store/master/public/screenshots/weChatMiniProgramScreenshots/confirmOrder.png)

**我的收藏**

![](https://raw.githubusercontent.com/hai-27/vue-store/master/public/screenshots/weChatMiniProgramScreenshots/collection.png)

**我的订单**

![](https://raw.githubusercontent.com/hai-27/vue-store/master/public/screenshots/weChatMiniProgramScreenshots/orders.png)

**我的**

![](https://raw.githubusercontent.com/hai-27/vue-store/master/public/screenshots/weChatMiniProgramScreenshots/mine.png)

**Comment by 521xueweihan** [comment]
完成后台部分再来推荐哦～
