### ISSUE TITLE
这是我发起的swift&Objective-C开源项目XICommand，请大家帮助它，向它输出代码。

### ISSUE THREAD

**Issue by Meterwhite** [521xueweihan/HelloGitHub#1187]
## 项目推荐
- 项目地址：https://github.com/Meterwhite/XICommand

- 类别：Objective-C、Swift

- 项目后续更新计划：该库集合开源的力量通过封装三方成为项目内的插件来实现无限扩展性，成为iOS&macOS平台上可视化编程的强力助手。

- 项目描述：
  - 必写：这是一个iOS&macOS可视化编程功能延伸的强力扩展、将IBOutlet作为一条命令行的形式来来拓展XIB和Storyboard的功能、把本应该在可视化界面编辑的内容都集中处理，让逻辑的部分更纯粹。
  - 可选：多适用于主要为XIB构建界面的项目、能够让初学者学到面向接口插件编程的思想
  - 描述长度（不包含示例代码）: Xcode interface command的核心功能是通过XIB文件适配夜间模式，用户在以指定格式命名IBOutlet属性时将触发特殊功能，这种格式类似于命令行。因为是面向接口的编程 ，所有开发人员都可以轻松添加插件以支持更多功能。支持iOS为主，macOS为辅。项目使用objective-c或者swift都是无恙的。本项目采用动态加载插件的方法，故不依赖任何三方。请使用cocoapods或其他方法导入三方以支持指定插件的功能。

- 推荐理由：我天马行空的想到将IBOutlet作为命令行。解决了Xcode内置可视化编程手段不够丰富的痛点。命令行是一种程序对应一种命令，下级有多种命令。XIC是一种插件对应一种命令，下级有多种命令。XIC的功能扩展性是无限制的。学习0成本，代码0行。

- 示例代码：
Objective-C
//Support for dark mode(DKNightVersion plug-ins).适配夜间模式。
● @property (weak, nonatomic) IBOutlet UILabel  *dkdo_bg_0XFFFFFF_0X000000;
//Set border color and border width.设置边框颜色和宽度。
● @property (weak, nonatomic) IBOutlet UIButton *sudo_border_0XCCCCCC_1p5;
swift
//Support for dark mode(DKNightVersion plug-ins).适配夜间模式。
● @IBOutlet weak var dkdo_bg_0XFFFFFF_0X000000: UILabel!
//Set border color and border width.设置边框颜色和宽度。
● @IBOutlet weak var sudo_border_0XCCCCCC_1p5: UIButton!

- 截图：

<img width="927" alt="XICEmp" src="https://user-images.githubusercontent.com/9498919/78912658-71cd3100-7aba-11ea-8810-10fb5a3218e1.png">

<img width="772" alt="XICEmp2" src="https://user-images.githubusercontent.com/9498919/78912846-aa6d0a80-7aba-11ea-819e-91de2a5a82d4.png">

<img width="735" alt="XICEmp3" src="https://user-images.githubusercontent.com/9498919/78912948-d7b9b880-7aba-11ea-83f0-641f525f97b3.png">

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
