### ISSUE TITLE
【自荐】hplayer：一个多画面播放器

### ISSUE THREAD

**Issue by ithewei** [521xueweihan/HelloGitHub#1189]
## 项目推荐
- 项目地址：https://github.com/ithewei/hplayer

- 类别：C++

- 项目后续更新计划：

添加显示器捕获源；
添加图片、文字、时间叠加功能；
添加多画面合成功能；
添加推流、录制功能；
添加人脸检测与识别功能；
添加美颜功能；

- 项目描述：
 一个类似VLC的播放器，能播放文件源、网络源、设备捕获源；
界面为多画面监控网格，可自由切换多画面风格，支持拖拽与合并；
技术点：
使用Qt实现界面；
使用FFmpeg获取帧，编解码，转码；
使用OpenCV处理图片；
使用OpenGL渲染视频帧；

- 推荐理由：
多画面播放器
适合音视频、播放器开发入门学习；

- 截图：
![hplayer](https://user-images.githubusercontent.com/26049660/78973500-a08eea00-7b42-11ea-8767-3805bbea7d53.png)
![hplayer4](https://user-images.githubusercontent.com/26049660/78973574-ca481100-7b42-11ea-8b82-5a09cb131a40.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 49 期](https://hellogithub.com/periodical/volume/49/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
