### ISSUE TITLE
SelectMenu - 简洁、易用、多样的菜单解决方案

### ISSUE THREAD

**Issue by TerryZ** [521xueweihan/HelloGitHub#119]
## 项目推荐
- 项目名称：SelectMenu

- 项目地址：https://github.com/TerryZ/SelectMenu

- 项目语言：javascript / jquery

- 项目描述：简洁、易用、多样的菜单解决方案。包含了常规菜单，高级菜单（autocomplete、多分组、自定义模板等）、右键呼出、嵌入网页、等多种菜单模式

- 推荐理由：简洁的样式可以适应大多数UI系统，多种多样的功能模式满足了各种业务场景的需求

- 示例代码：
```js
//defined data source
//data format：Array[{Object},{...}]
var data = [
    {id:1 ,name:'Chicago Bulls',desc:'芝加哥公牛'},
    {id:2 ,name:'Cleveland Cavaliers',desc:'克里夫兰骑士'},
    {id:3 ,name:'Detroit Pistons',desc:'底特律活塞'},
    {id:4 ,name:'Indiana Pacers',desc:'印第安纳步行者'}
];
//initialize selectmenu
$('#btnDemo').selectMenu({
    showField : 'desc',
    keyField : 'id',
    data : data
});
```

- 截图：

*Regular menu mode*

![SelectMenu1](https://terryz.github.io/image/SelectMenuBase.png)

*Advanced menu mode*

![SelectMenu2](https://terryz.github.io/image/SelectMenu.png)

*Advanced menu mode (multiple group data)*

![SelectMenu3](https://terryz.github.io/image/SelectMenuGroup.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，已成功收录在 [HelloGitHub 第 19 期](https://hellogithub.com/volume/19/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，如果方便可以 Star ⭐️ 本项目，让更多人看到本项目。
