### ISSUE TITLE
一叶（Same Page）聊天盒

### ISSUE THREAD

**Issue by Arch1tect** [521xueweihan/HelloGitHub#1192]
## 项目推荐
- 项目地址：
https://github.com/Same-Page/client
https://yiyechat.com/
- 类别：React.js, Python, websocket

- 项目后续更新计划：
完善中，已发布，尚未推广，现有4k活跃用户，累计约40k用户。

- 项目描述：
这是一个社交类产品，让用户可以在任意网页实时聊天。产品既可以打包成浏览器插件让普通用户安装，亦可以供网站所有者安装到自己的网站上面。
前端用的是React.js，后端则是Python。

- 推荐理由：在任意网页实时聊天非常好玩，项目难度适中，后端代码尤为简单易懂，前端代码需要React.js的基础知识，也不难上手。

- 截图：
![](https://yiyechat.com/images/sp-screenshots.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by 521xueweihan** [comment]
很有意思的项目。但我担心这种类型的网站的内容可能过于“自由”，所以HG暂不推荐您的项目了。
