### ISSUE TITLE
中文文本纠错工具

### ISSUE THREAD

**Issue by hungter007** [521xueweihan/HelloGitHub#1193]
## 项目推荐
- 项目地址：https://github.com/shibing624/pycorrector

- 类别：Python、机器学习

- 项目后续更新计划：

- 项目描述：
  - 必写：中文文本纠错工具
  - 可选：音似、形似错字（或变体字）纠正，可用于中文拼音、笔画输入法的错误纠正,pycorrector依据语言模型检测错别字位置，通过拼音音似特征、笔画五笔编辑距离特征及语言模型困惑度特征纠正错别字。

- 推荐理由：解决在文本识别模型处理后，对识别结果中个别词汇错误进行纠错

- 截图：![image](https://user-images.githubusercontent.com/32872324/79101381-fbbb1980-7d9a-11ea-81de-d4a7b9e70bee.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 49 期](https://hellogithub.com/periodical/volume/49/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
