### ISSUE TITLE
【自荐】快速克隆git仓库+生成、下载网站二维码+选中右击跳转百度的Chrome插件

### ISSUE THREAD

**Issue by Zenquan** [521xueweihan/HelloGitHub#1195]
## 项目推荐
- 项目地址：[https://github.com/Zenquan/quickgitclone](https://github.com/Zenquan/quickgitclone)

- 类别：JS(浏览器插件)

- 项目描述：
  这是一个帮助快速克隆git仓库+生成、下载网站二维码+选中右击跳转百度的Chrome插件，解决了国内git clone仓库慢的问题

- 推荐理由：1. 解决了国内git clone仓库慢的问题，2. 能生成、下载网站二维码，3.选中右击跳转百度的Chrome插件。实用性比较强。

- 截图：
![](https://camo.githubusercontent.com/b461ba416889be4d2aefc6c4b6e774a1097e5f85/68747470733a2f2f757365722d676f6c642d63646e2e786974752e696f2f323032302f342f322f313731333933376463303265653963303f773d38303526683d34303626663d706e6726733d39333135)

![](https://camo.githubusercontent.com/42dfc55c760a1e81c7509633d1cdf69ba7400d67/68747470733a2f2f757365722d676f6c642d63646e2e786974752e696f2f323032302f342f31322f313731366334653238623537373430623f773d36313226683d36303426663d706e6726733d3438353631)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
