### ISSUE TITLE
推荐百度 飞浆框架  【PaddlePaddle】

### ISSUE THREAD

**Issue by HalfLeaf** [521xueweihan/HelloGitHub#1196]
## 项目推荐
- 项目地址：https://github.com/PaddlePaddle

- 类别：Python， C++

- 项目后续更新计划：百度团队持续更新中

- 项目描述：
  - 必写：百度开源的深度学习框架，国内首家，目前也是最大的开源库
  - 可选：深度学习场景
  - 描述长度:『飞桨』核心框架，深度学习&机器学习高性能单机、分布式训练和跨平台部署

- 推荐理由：完善的中文文档，社区活跃，还可以可申请免费的算力，社区地址：http://ai.baidu.com/forum

**Comment by 521xueweihan** [comment]
感谢您的推荐，本项目不推荐该框架。谢谢您的理解和支持
