### ISSUE TITLE
定时检查MySQL的表锁 crontab-mysqlLock-go 

### ISSUE THREAD

**Issue by jasondayee** [521xueweihan/HelloGitHub#1198]
- 项目地址 
https://github.com/verytalk/crontab-mysqlLock-go

- 项目名称 crontab-mysqlLock-go

- 类别 GO

- 项目描述

```
定时检查MySQL的表锁
```

- 推荐理由

```
这个项目只需要简单地配置即可定时检查MySQL的表锁
可以帮助DBA分析是什么原因导致的表产生的事务锁
```

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
