### ISSUE TITLE
Istio Handbook——Istio 服务网格进阶实战

### ISSUE THREAD

**Issue by rootsongjc** [521xueweihan/HelloGitHub#1199]
## 项目推荐
- 项目地址：https://github.com/servicemesher/istio-handbook

- 类别：书籍
- 项目后续更新计划：

- 项目描述：Istio 是由 Google、IBM、Lyft 等共同开源的 Service Mesh（服务网格）框架，作为云原生时代下承 Kubernetes、上接 Serverless 架构的重要基础设施层，于 2017 年开始进入大众视野。2018 年由蚂蚁金服发起成立了 ServiceMesher 社区，作为中国最早的一批研究和推广 Service Mesh 技术的开源社区决定整合社区资源，合作撰写一本开源的 Service Mesh 电子书以飨读者。

- 推荐理由：国内第一本开源的 Istio 书籍，由 ServiceMesher 社区出品。

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）

![image](https://user-images.githubusercontent.com/3328185/79711970-05450400-82fc-11ea-8a09-afca1351db51.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 49 期](https://hellogithub.com/periodical/volume/49/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
