### ISSUE TITLE
[自荐] Python 开源 GitBook

### ISSUE THREAD

**Issue by ethan-funny** [521xueweihan/HelloGitHub#12]
explore-python: Python 之旅，总结了 Python 相关的知识点，力求深入浅出、条理清晰。
地址：https://github.com/ethan-funny/explore-python

**Comment by 521xueweihan** [comment]
您好，非常欣赏您的项目。

在11期中，收录了一部《Python 之旅》中文翻译版，地址如下：

https://spacewander.github.io/explore-flask-zh/index.html

这个是您的翻译版本吗？

**Comment by ethan-funny** [comment]
不是的，你说的这本书是 《Flask 之旅》，我的是 《Python 之旅》，是我个人独立创作。

**Comment by 521xueweihan** [comment]
不好意思，是我看错了，您的项目将被收录到《HelloGitHub》月刊 第 12 期，感谢支持🙏

**Comment by 521xueweihan** [comment]
您好，explore-python 项目已收录到 [12期](https://github.com/521xueweihan/HelloGitHub/blob/master/12/HelloGitHub12.md)，在此感谢您的支持，希望以后推荐更多好的项目。
