### ISSUE TITLE
[自荐]中文地址自动解析

### ISSUE THREAD

**Issue by jtyoui** [521xueweihan/HelloGitHub#1200]
## 项目推荐
- 项目地址：https://github.com/PyUnit/pyunit-address

- 类别：Python3

- 项目后续更新计划：基本上每1-2个月都会更新一次以上，每次更新都会向下兼容，不会担心出现兼容问题。

- 项目描述：
  - 必写：该项目是提取中文中的地址，对地址进行解析，对地址进行纠错和对地址进行补全。

  - 可选：使用场合特别多，主要用于实体提取中。

- 推荐理由：
            对地址进行补全，比如：输入：我家在遵义县。输出：[贵州省-遵义市-遵义县]
            对地址进行逻辑纠错：比如：输入：我家在贵州遵义花溪区，输出是：贵州省-贵阳市-花溪区（因为贵州下面的遵义没有花溪区。而贵州下面的贵阳有花溪区，明显对方把贵阳写成遵义了）
           对地址进行查找：输入：我家在红花岗，输出：红花岗
          对上万句地址操作。耗时不到0.1秒。

- 示例代码：（可选）长度：1-20 行
```python

def all_test():
    string_ = '我家在红花岗，你家在贵州贵阳花溪区，他家在贵州省遵义市花溪区'
    finds = find_address(address, string_)
    for find in finds:
        print()
        print('地址', find)
        print('补全地址', supplement_address(address, find))
        print('纠错地址', correct_address(address, find))
        print('--------------------------')

# 地址 红花岗
# 补全地址 ['贵州省-遵义市-红花岗区']
# 纠错地址 贵州省-遵义市-红花岗区
# --------------------------
# 
# 地址 贵州贵阳花溪区
# 补全地址 ['贵州省-贵阳市-花溪区']
# 纠错地址 贵州省-贵阳市-花溪区
# --------------------------
# 
# 地址 贵州省遵义市花溪区            注：这个地址是错误的
# 补全地址 []                      注：错误的地址无法补全
# 纠错地址 贵州省-贵阳市-花溪区      注：错误的地址被纠正为对的地址
# --------------------------

if __name__ == '__main__':
    start = time.time()
    all_test()
    print(time.time() - start)  # 0.0002001047134399414秒
```

- 截图：（可选）gif/png/jpg
![image](https://user-images.githubusercontent.com/28988355/79832167-6abbf200-83db-11ea-8cb7-3a76f604abf9.png)
![image](https://user-images.githubusercontent.com/28988355/79832176-714a6980-83db-11ea-97a1-9032c62a53e7.png)
![image](https://user-images.githubusercontent.com/28988355/79840024-e885fa80-83e7-11ea-9049-da707d3fa209.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
