### ISSUE TITLE
React Native 项目快速开发基础库

### ISSUE THREAD

**Issue by chende008** [521xueweihan/HelloGitHub#1203]
## 项目推荐（自荐）
- 项目地址：https://github.com/chende008/react-native-fast-app

- 类别：JS

- 项目描述：

  一个React Native项目辅助开发库，它可以协助开发者更方便快捷的访问本地、网络数据

  1. 解决了AsyncStorage繁琐的访问方式，能以同步访问内存对象（与之相关联）的形式来访问本地存储
  2. 封装了一个前后台交互的Http请求框架，开发者只需要设置涉及业务逻辑相关的入参及出解析方式，即可可方便的发关http请求

- 推荐理由：

   1. 还在直接访问AsyncStorage ？其实你只需要访问一个对象，对其属性取值、赋值即可。
   2. 还在手动封装fetch？其实你只需要做个填空题：告诉框架，你的入参及出参的解析方式即可。

- 示例代码：（可选）长度：1-20 行
```
import {RFStorage} from 'react-native-fast-app';

const initCallback = () => { // 您可以同步访问RNStorage中的任何属性

    console.log(RNStorage.isShow); // 等价于 [ console.log(await AsyncStorage.getItem('isShow')) ]

    RNStorage.token = 'TOKEN1343DN23IDD3PJ2DBF3=='; // 等价于 [ await AsyncStorage.setItem('token',TOKEN1343DN23IDD3PJ2DBF3==') ]

    RNStorage.userInfo = {name: 'rufeng', age: 30}; // 等价于 [ await AsyncStorage.setItem('userInfo',JSON.stringify({ name:'rufeng', age:30})) ]
};

RFStorage.initStorage(RNStorage, initCallback);
```

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
