### ISSUE TITLE
iOS 仿阿里巴巴/电商规格选择器 电商通用规格选择器

### ISSUE THREAD

**Issue by shabake** [521xueweihan/HelloGitHub#1208]
## 项目推荐
- 项目地址：https://github.com/shabake/GHAlibabaSpecificationSelectionDemo

- 类别：Objective-C

- 项目后续更新计划：增加动画

- 项目描述：
  - 封装仿阿里巴巴规格选择器，拿来即用

初始化确定按钮颜色置灰，不可点击。

当 spu 颜色数量大于1个时，显示颜色导航，底部列表可以滚动，反之隐藏，布局自适应。

如果有颜色导航，输入或点击 + - 按钮，颜色导航对应的颜色数字同步变化，如果数量大于99显示99+；如果数量小于1不显示。

点击> < 底部列表和颜色导航同步滚动。

输入或点击 + - 按钮，当按 + 到最大库存 + 置灰；当按 - 到0 - 置灰。

点击输入框。键盘弹出，规格选择器 上移；点击完成，键盘收回，规格选择器 回到原位。

点击颜色导航条的颜色标签，高亮被点击颜色标签并滚动到屏幕中心，底部列表滑动到对应位置，同时切换 sku 图片。

当输入或者点击数量大于1，确定按钮可点击，颜色高亮。

当库存不足的时候，输入框下显示库存不足标签。

输入框不可输入 0 ， . 等特殊符号。

列表行自适应高度，布局中心对齐。

点击背景遮罩或者 x ，收回弹窗。

动态输入监听，同步显示，根据输入判定确定按钮状态。

数据模型重新组装。

适配IPhoneX及以上系列。

增加加入到购物车抛物线动画，购物车同步用户选择 sku 数量。

![未标题-2.png](https://upload-images.jianshu.io/upload_images/1419035-5554f91741be4c55.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
