### ISSUE TITLE
一款小巧的基于Go的API开发框架snake，可以快速进行业务开发，遵循SOLID原则

### ISSUE THREAD

**Issue by qloog** [521xueweihan/HelloGitHub#1210]
## 项目推荐
- 项目地址：https://github.com/1024casts/snake

- 类别：Go

- 项目后续更新计划：
  - 加入更多的常用工具
  - 提高单元测试覆盖率
  - 完善用户模块，比如关注、粉丝等常用功能
  - 完善开发规约文档，而不是随便开发
  - ...

  
- 项目描述：
  - 一款适合于快速开发业务的Go框架，安装即用，非常方便简单
  - 非常适合开发API的项目，
  - 遵循 RESTful API 设计规范
  - 使用 make 来管理Go工程，自带进程管理，支持JWT，swagger文档，多环境配置等等

- 推荐理由：一款小巧的基于Go的API开发框架，可以快速进行业务开发

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
