### ISSUE TITLE
一个自动保存《极客时间》课程的轻型脚本（自荐）

### ISSUE THREAD

**Issue by zhengxiaotian** [521xueweihan/HelloGitHub#1212]
## 项目推荐
- 项目地址：https://github.com/zhengxiaotian/geek_crawler

- 类别：Python

- 项目后续更新计划：
  增加以下功能：
    - 抓取指定名称的课程；
    - 将每篇文章的评论与正文一起保存到本地；
    - 将视频拉取下来保存成 MP4 文件；

- 项目描述：
  - 极客时间课程抓取脚本，支持输入账号密码后自动将极客时间的专栏课程保存到本地

- 推荐理由：
  - 输入账号密码后自动将该账号下所有可以看到的专栏（图文+音频），保存到本地；
  - 可以支持选择保存成 Markdown 文档或者 HTML 文档；
  - 支持配置排除某些课程的拉取（比如已经有的课程不再下载）；

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 50 期](https://hellogithub.com/periodical/volume/50/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
