### ISSUE TITLE
一个基于依赖注入的Go API快速开发框架pick，聚焦于业务

### ISSUE THREAD

**Issue by liov** [521xueweihan/HelloGitHub#1213]
## 项目推荐
- 项目地址：https://github.com/liov/pick

- 类别：Go

- 项目后续更新计划：
  - 完善swagger文档生成
  - 完善单元测试
  - 清理代码结构及完善注释
  - 路由组部分考虑使用前缀树重构，将`/api/xxx/v1`的形式改为`/api/v1/xxx`

- 项目描述：
  - 基于依赖注入，像写java一样的写go，能够明晰业务的参数及返回
  - 旨在提供一种思路，适用于api的快速开发

- 推荐理由：
  - 摆脱路由注册
    >摆脱零散的各处的路由注册 `xxx.Handle("/"，func(){})`
  - 摆脱w,r,摆脱xxx.Context
    >不再编写这样`func(w http.ResponseWriter, r *http.Request)`或者`func(ctx xxx.Context){ctx.XXX()}`的业务代码
  - 专注于业务

- 示例代码：
```go
type UserService struct{}

func (*UserService) Service() (string, string, []http.HandlerFunc) {
	return "用户相关", "/api/user", []http.HandlerFunc{middleware.Log}
}

func (*UserService) AddV2(ctx *model.Claims, req *model.SignupReq) (*model.User, error) {
	//对于一个性能强迫症来说，我宁愿它不优雅一些也不能接受每次都调用
	pick.Api(func() interface{} {
		return pick.Method(http.MethodGet).
			Title("用户注册").
			CreateLog("1.0.0", "jyb", "2019/12/16", "创建").
			ChangeLog("1.0.1", "jyb", "2019/12/16", "修改测试")
	})

	return &model.User{Name: req.Name}, nil
}
func init() {
	pick.RegisterService(&service.UserService{})
}

func main() {
	router := pick.NewRouter(true)
	log.Fatal(http.ListenAndServe(":8080", router))
}
```
```shell
curl http://localhost:8080/api/user/v2/add?name=pick
```
```json
{"code":0,"message":"success","details":{"id":0,"name":"pick"}}
```

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
