### ISSUE TITLE
基于 Python 开发的在线文档系统，适合作为个人和小型团队文档、笔记、知识管理工具

### ISSUE THREAD

**Issue by zmister2016** [521xueweihan/HelloGitHub#1216]
## 项目推荐
- 项目地址：https://github.com/zmister2016/MrDoc

- 类别：Python

- 项目后续更新计划：打包docker镜像，方便安装使用；开发Chrome浏览器扩展；

- 项目描述：这是一个基于 Python 开发的在线文档系统，使用Markdown作为文档的书写语法，以文集进行分类，以文档作为最小单元，支持科学公式、流程图、序列图、思维导图等内容直接在文档内绘制，两栏式清爽的阅读界面，同时支持文集打包导出为md文件、EPUB文件、PDF文件。适合作为个人和小型团队的私有化文档部署方案。

- 推荐理由：Python中少有还在更新和完善的开源文档系统

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 50 期](https://hellogithub.com/periodical/volume/50/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
