### ISSUE TITLE
Go-sword 基于Go语言的可视化web管理后台生成工具

### ISSUE THREAD

**Issue by sunshinev** [521xueweihan/HelloGitHub#1217]
## 项目推荐
- 项目地址：https://github.com/sunshinev/go-sword

- 类别：Go

- 项目后续更新计划：

- 项目描述：
  - 必写：根据MySQL的表结构，创建完整的管理后台界面，开发者无需再重复手动的创建具有CRUD能力的页面 只需要点击按钮即可生成完整的管理后台
  - 可选：她能满足你哪些？
你有代码洁癖，不希望工具过多干扰你的业务逻辑
你希望生成的页面可以自定义修改，来实现更多的功能
你希望代码特别简单易读，且容易自定义
你希望能快速构建管理后台，哪怕仅仅是将数据库里的数据可视化
你希望一键生成CRUD，无需复杂操作
你希望使用 iView 的组件，快速构建页面
那么 go-sword 可以满足你

- 推荐理由：一键生成CRUD后台

- 截图：
![image](https://user-images.githubusercontent.com/8537718/81064418-42201600-8f0c-11ea-867e-4c7ff1451bda.png)

## 提示（提交时请删除以下内容）
> 点击上方 “Preview” 更方便地阅读以下内容，

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
