### ISSUE TITLE
自荐项目，Android基于RecyclerView实现WheelView

### ISSUE THREAD

**Issue by wongzy** [521xueweihan/HelloGitHub#1219]
## 项目推荐
- 项目地址：https://github.com/wongzy/RecyclerWheelView

- 类别：Kotlin

- 项目后续更新计划：
1. 增强兼容性，实现更多效果

- 项目描述：
这是一个Android库，基于RecyclerView实现，自定义item方法与RecyclerView使用接近，可快速上手使用，String Wheel View使用更加便捷，可几行代码实现滑动监听等。

- 推荐理由：
使用方法简便，可高度定制item，或实现字符串滚动字符大小，颜色，背景颜色等自定义。

- 示例代码：
stringRecyclerWheelView.setOnSelectedStringCallback(object :
            StringRecyclerWheelView.OnSelectedStringCallback {
            override fun onSelectedString(selectedString: String) {
                tvValue.text = "selected value : $selectedString"
            }
        })
stringRecyclerWheelView.setStringItemList(stringList)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
