### ISSUE TITLE
ClashR Pro

### ISSUE THREAD

**Issue by uiYzzi** [521xueweihan/HelloGitHub#1220]
## 项目推荐
- 项目地址：https://github.com/uiYzzi/ClashR-Pro

- 类别：Python

- 项目后续更新计划：完善功能

- 项目描述：
  - 适用于linux的ClashR Gui
  - 在linux上连接代理

- 推荐理由：Linux少有的程序

- 截图：![Image text](https://raw.githubusercontent.com/uiYzzi/ClashR-Pro/master/screenshot/1.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
