### ISSUE TITLE
【自荐】ViLikeJS 一款基于Bmob后端云轻量级的访问量&点赞插件

### ISSUE THREAD

**Issue by zpfz** [521xueweihan/HelloGitHub#1221]
## 项目推荐
- 项目地址：https://github.com/zpfz/ViLikeJS

- 类别：JS

- 项目后续更新计划：优化请求逻辑

- 项目描述：
  - 必写：ViLikeJS是一款基于Bmob后端云轻量级的访问量&点赞插件。ViLikeJS 的目标很明确，旨在解决那些静态服务器因各种原因未能实现需后端搭配的功能的痛处。目前主要实现的功能为站点访问量统计、文章页阅读量统计以及常用的点赞功能。
这是个什么项目、能用来干什么、有什么特点或解决了什么痛点
  - 可选： 当你想在你的博客显示访客统计时；当你想在你的文章页显示阅读量时；当你想给你的文章或者作品实现点赞功能时等等。
  - 描述长度（不包含示例代码）: 简单功能简单实现，封装十几行代码实现超轻量的JS插件。
无需在个人服务器上搭建后端系统，数据访问更加安全。
借助Bmob创建后端平台，创建、管理更加方便快捷。

- 推荐理由：解决那些静态服务器因各种原因未能实现需后端搭配的功能的痛处。特别适合那些需要访问量统计和点赞功能的站点。

- 示例代码：
获取访问量、点赞数、点赞状态
```js
ViLike.get('1192a75ccf48e109',(visit,like,islike)=>{
  // 依次显示 访问量、点赞数、点赞状态
  console.log(visit,like,islike)
});
```
点赞计数功能
```js
ViLike.like('1192a75ccf48e109',(like)=>{
  // 显示点赞后最新的点赞数
  console.log(like)
})
```

- 截图：无

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
