### ISSUE TITLE
Vue 表单生成组件 form-create

### ISSUE THREAD

**Issue by xaboy** [521xueweihan/HelloGitHub#1223]
## 项目推荐
- 项目地址：[https://github.com/xaboy/form-create](https://github.com/xaboy/form-create)

- 类别：JS

- 项目后续更新计划：
  - 功能优化
  - 基于 vue3.0 重构
- 项目描述：
form-create 是一个可以通过 JSON 生成具有动态渲染、数据收集、验证和提交功能的表单生成器。并且支持生成任何 Vue 组件。结合内置17种常用表单组件和自定义组件，再复杂的表单都可以轻松搞定。当前已支持 iview, element-ui, and-design-vue

- 推荐理由：帮开发者节省在表单的耗费的时间,有更多时间专注于业务功能开发

- 截图：
![https://raw.githubusercontent.com/xaboy/form-create/dev/images/demo-live3.gif](https://raw.githubusercontent.com/xaboy/form-create/dev/images/demo-live3.gif)

![https://raw.githubusercontent.com/xaboy/form-create/dev/images/demo-live2.gif](https://raw.githubusercontent.com/xaboy/form-create/dev/images/demo-live2.gif)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 50 期](https://hellogithub.com/periodical/volume/50/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）

**Comment by xaboy** [comment]
好的,感谢推荐
