### ISSUE TITLE
移动端研发助手DoKit

### ISSUE THREAD

**Issue by jtsky** [521xueweihan/HelloGitHub#1224]
## 项目推荐
- 项目地址：https://github.com/didi/DoraemonKit

- 类别：Java、Objective-C

- 项目后续更新计划：
增加www.dokit.cn平台端能力
- 项目描述：
DoraemonKit /'dɔ:ra:'emɔn/，简称DoKit，中文名 哆啦A梦，意味着能够像哆啦A梦一样提供给他的主人各种各样的工具。Just Do Kit

- 推荐理由：
每一个稍微有点规模的 App，总会自带一些线下的测试功能代码，比如环境切换功能、帧率查看功能等等，这些功能的切换入口往往放在各式各样的入口中，比如一些特殊的手势，双击 statusBar，双击某一个功能区块，或者新建一个 keyWindow 始终至于 App 最上方等等，而且每一个 App 里面的线下附带功能模块很多是相似的，比如帧率查看、内存和 CPU 监控等等，但是现在基本上都是每个 App 都是自己实现了一份，经历了以上的问题之后，DoraemonKit 就有了它存在的意义。

DoraemonKit 是一个功能平台，能够让每一个 App 快速接入一些常用的或者你没有实现的一些辅助开发工具、测试效率工具、视觉辅助工具，而且能够完美在 Doraemon 面板中接入你已经实现的与业务紧密耦合的一些非通有的辅助工具，并搭配我们的dokit平台，让功能得到延伸，接入方便，便于扩展。

简单总结

1、DoraemonKit 能够快速让你的业务测试代码能够在这里统一管理，统一收口；

2、DoraemonKit 内置很多常用的工具，避免重复实现，一次接入，你将会拥有强大的工具集合；

3、搭配dokit平台，方便你进行数据mock以及记录你的每一次健康体检用例。

- 截图：
![dokit](https://pt-starimg.didistatic.com/static/starimg/img/ea7H2QyOWF1589360724935.jpeg)

**Comment by 521xueweihan** [comment]
谢谢，已推荐过
