### ISSUE TITLE
ivideo

### ISSUE THREAD

**Issue by hellowHuaairen** [521xueweihan/HelloGitHub#1227]
## 项目推荐
- 项目地址：https://github.com/phobal/ivideo

- 类别：JS
- 项目后续更新计划：

- 项目描述：
  - 必写：一个可以观看国内主流视频平台所有视频的客户端（Mac、Windows、Linux）
  - 可选：学习娱乐两不误
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：于Electron 开发的跨平台客户端版本的视频播放器，该播放器包括国内主流视频平台视频资源，你不用去单独下载各个平台的客户端，只需要使用这一个客户端就能查看所有平台的视频，并且内置了各大视频网站 VIP 资源。

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

![](https://github.com/phobal/ivideo/raw/master/resources/showcase01.jpg)
![](https://github.com/phobal/ivideo/raw/master/resources/showcase03.jpg)
![](https://github.com/phobal/ivideo/raw/master/resources/showcase04.jpg)

**Comment by 521xueweihan** [comment]
这个项目非常好，我怕曝光度增加项目会被封，大家低调使用吧
