### ISSUE TITLE
开源图书《运维实践指南》

### ISSUE THREAD

**Issue by BillWang139967** [521xueweihan/HelloGitHub#123]
## 项目推荐
- 项目名称：op_practice_book

- 项目地址：https://github.com/BillWang139967/op_practice_book

- 项目语言：md

- 项目描述：记录运维的点滴，形成体系化内容

- 推荐理由：

- 示例代码：

[gitbooks](https://billwang139967.gitbooks.io/op_practice_book/content/)

- 截图：

![test](https://github.com/BillWang139967/op_practice_book/raw/master/images/ops.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，已成功收录在 [HelloGitHub 第 19 期](https://hellogithub.com/volume/19/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，如果方便可以 Star ⭐️ 本项目，让更多人看到本项目。
