### ISSUE TITLE
mir2x

### ISSUE THREAD

**Issue by etorth** [521xueweihan/HelloGitHub#1232]
## 项目推荐
- 项目地址：https://github.com/etorth/mir2x

- 类别：请从中选择（C、C#、C++、CSS、Go、Java、JS、Kotlin、Objective-C、PHP、Python、Ruby、Swift、其它、书籍、机器学习）
c++

- 项目后续更新计划：
完全复制传奇3

- 项目描述：
  - 必写：这是个什么项目、能用来干什么、有什么特点或解决了什么痛点
  - 可选：适用于什么场景、能够让初学者学到什么
  - 描述长度（不包含示例代码）: 10 - 256 个字符
练习C++最新标准。
第一个完全基于actor model的开源游戏。

**Comment by ChungZH** [comment]
您好，建议放几张截图上来，并按模板填写好推荐文案！谢谢！

```
## 项目推荐
- 项目地址：

- 类别：请从中选择（C、C#、C++、CSS、Go、Java、JS、Kotlin、Objective-C、PHP、Python、Ruby、Swift、其它、书籍、机器学习）

- 项目后续更新计划：

- 项目描述：
  - 必写：这是个什么项目、能用来干什么、有什么特点或解决了什么痛点
  - 可选：适用于什么场景、能够让初学者学到什么
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

```

**Comment by 521xueweihan** [comment]
未按照要求提交，所以本 issues 关闭
