### ISSUE TITLE
C++基本算法

### ISSUE THREAD

**Issue by DeusOfDeepThoughts** [521xueweihan/HelloGitHub#1235]
## 项目推荐
- 项目地址：https://github.com/DeusOfDeepThoughts/Devs?files=1

- 类别：
C++

- 项目后续更新计划：
将持续更新，并依照《剑指offer》中的题目，逐渐完善。

- 项目描述：
这个项目用来帮助C++向的求职学生，快速熟悉C++中的基本算法和数据结构。
其特点是基础，且很多都是通过题目、举例来说明算法的使用。

- 推荐理由：
可以帮助C++向的求职者从繁复的资料中解脱出来，通过学习，运行项目中的简单代码，就能快速地掌握基本算法。

**Comment by 521xueweihan** [comment]
连载完可以，重新推荐。
