### ISSUE TITLE
【自荐】一个将静态博客部署到云存储的工具，支持所有云平台。

### ISSUE THREAD

**Issue by saltbo** [521xueweihan/HelloGitHub#1237]
## 项目推荐
- 项目地址：https://github.com/saltbo/uptoc

- 类别：Go

- 项目后续更新计划：支持更多的云平台

- 项目描述：
  - 一个将静态博客部署到云存储的工具
  - 这个项目采用S8协议，可以对接所有平台的对象存储；另外我们实现了增量上传，每次只上传发生变化的文件。
  - 代码量小，适合开源项目初学者学习练手。

- 推荐理由：静态博客不论是部署在GitHubPages还是Netlify等平台都存在国内访问速度慢的问题，解决这个问题最好的办法就是部署在国内的云平台，如腾讯云COS，阿里云OSS，七牛云等。但是一般官方只提供一个全功能的命令行工具，一方面我们只能用到上传功能，另一方面每次都是全量上传。

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 50 期](https://hellogithub.com/periodical/volume/50/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
