### ISSUE TITLE
react-mobx-Cnode

### ISSUE THREAD

**Issue by Juliiii** [521xueweihan/HelloGitHub#124]
## 项目推荐
- 项目名称：
React-Cnode
- 项目地址：
https://github.com/Juliiii/React-Cnode
- 项目语言：
React + mobx + mobx-react + axios + react-router + antd-mobile
- 项目描述：
根据Cnode社区提供的API，完整实现了一个Cnode社区的webapp客户端，有两个版本，一个是当前master分支的react + mobx，另一个是old-version的react+redux+redux-saga。开发中对业务的分析和遇到的问题，可以前往[此处查看](http://www.jianshu.com/p/43c604177c08)
- 推荐理由：

1. 实现完整，正常使用

2. 使用了react全家桶，可以给刚入门react的同学一个学习和参考。也用了redux和mobx, 让大家可以比较这两种数据管理的方式。
3. 代码风格尽量遵循规范，文件架构合理

- 示例代码：
```
git clone git@github.com:Juliiii/React-Cnode.git
npm i
npm start
```
- 截图：
![images](https://user-images.githubusercontent.com/23744602/31574427-40b147f2-b102-11e7-8731-253ab286dc37.gif)

**Comment by JameJJ** [comment]
你好，因为我们每一期的篇幅有限，如果在这一期没有出现我们会在下一期考虑添加上的。还有就是能不能添加一个开发总结，比如新手使用react全家桶应该要注意哪些坑，开发过程中应该重点注意什么。谢谢

**Comment by Juliiii** [comment]
@JameJJ 额，已经按建议给出了修改

**Comment by 521xueweihan** [comment]
@Juliiii 您推荐的项目，已成功收录在 [HelloGitHub 第 20 期](https://hellogithub.com/volume/20/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)

最后，欢迎 Star ⭐️ 本项目，以便让更多人看到。
