### ISSUE TITLE
react-antd-admin-template

### ISSUE THREAD

**Issue by NLRX-WJC** [521xueweihan/HelloGitHub#1240]
## 项目推荐
- 项目地址：https://github.com/NLRX-WJC/react-antd-admin-template

- 类别：JavaScript，React

- 项目后续更新计划：

- 项目描述：
  - 必写：这是一个基于React+Antd的后台管理模版,它内置了动态路由，权限验证等典型的业务模型，可以帮助你快速搭建企业级中后台产品原型
  - 描述长度（不包含示例代码）: 使用react+antd+redux+react-router+react-redux+redux-thunk写了一个后台管理系统模板，它内置了动态路由，权限验证，富文本编辑器，表格，图表等典型的业务模型，可以帮助你快速搭建企业级中后台产品原型。
     
- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？
  本项目中内置了动态路由，权限验证，富文本编辑器，表格，图表等后台管理系统中常用的业务模型，可以帮助你快速搭建企业级中后台产品原型，在此基础上，进行二次开发可事半功倍
- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg
![guide](https://user-images.githubusercontent.com/58020593/82397431-06945880-9a83-11ea-880c-7437973f0f89.gif)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目，已推荐过类似项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
