### ISSUE TITLE
CMAKE-DEMO

### ISSUE THREAD

**Issue by gongluck** [521xueweihan/HelloGitHub#1248]
## 项目推荐
- 项目地址：https://github.com/gongluck/CMake-Demo.git

- 类别：C++、其它

- 项目后续更新计划：
CMake及其他组件的高级使用，跨平台编译例子。

- 项目描述：
  一个CMake入门项目，学习CMake的基本使用：创建工程、编译项目、测试代码、安装、打包。

- 推荐理由：
  由浅入深学习CMake。学习CMake最基础的命令。配套博客地址：https://gongluck.github.io/cmake/cmake-start/ 食用更佳！

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
