### ISSUE TITLE
【自荐】OI_Sharing：Algorithm-all-in-one

### ISSUE THREAD

**Issue by Xunzhuo** [521xueweihan/HelloGitHub#1249]
## 项目推荐
- 项目地址：https://github.com/Xunzhuo/OI_Sharing

- 类别：其它

- 项目后续更新计划：计划更新习题，扩充题解，并更新算法学习路线，从面向算法竞赛扩大到面向面试，有新的算法资料也会上传到项目中

- 项目描述：
  - 必写：算法资料汇总：算法竞赛、数据结构的课件、论文、书籍、OJ网站、习题
  - 可选：适用于进行算法竞赛、想自学算法、想准备算法面试的朋友，算法学习看这个就够了。
  - 描述长度（不包含示例代码）: 算法的学习是每个程序员必修的一部分，不管你是想准备面试突击算法、还是课外拓展、还是竞赛训练，这个仓库包含了所有你的所需

- 推荐理由：搜寻了GitHub上的算法资料分享的项目，没有一个有这个项目全面。Algorithm All in One，从语言、书籍、onlinejudge网站 到 算法基础套件（算法、数据结构、C++）、算法竞赛队课件 到题目 到 研究性论文。算法学习需要的都在这个repo里

- 截图：（可选）
仓库结构：
![](https://user-images.githubusercontent.com/48784001/82719623-df39c780-9cde-11ea-9ee8-6dc230fdfd0c.png)
仓库前言：
![](https://user-images.githubusercontent.com/48784001/82719625-e365e500-9cde-11ea-9104-bffb898781e2.png)
文件导图：
![](https://user-images.githubusercontent.com/48784001/82719627-e5c83f00-9cde-11ea-81e2-88df0e3948d5.png)
文件大纲目录：
![](https://user-images.githubusercontent.com/48784001/82719649-1c05be80-9cdf-11ea-8db4-d8106d55c130.png)
OnlineJudge汇总：
![](https://user-images.githubusercontent.com/48784001/82719666-3a6bba00-9cdf-11ea-8adf-fe2dfa13b65a.png)
完整文件树：
![](https://user-images.githubusercontent.com/48784001/82719676-48213f80-9cdf-11ea-82fb-aca3abdf7b32.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目，已推荐过类似项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
