### ISSUE TITLE
推荐一个我自己的项目

### ISSUE THREAD

**Issue by xiaorang** [521xueweihan/HelloGitHub#1250]
## 项目推荐
- 项目地址：https://github.com/xiaorang/videoMaker.git

- 类别：Python

- 项目后续更新计划：无明确计划，根据兴趣来

- 项目描述：
  - 必写：根据写好的剧本和素材，一键生成视频
  - 可选：可以用于制作各种小视频，能够学习到视频的各种操作
  - 描述长度（不包含示例代码）: 核心代码800行左右

- 推荐理由：一键生成视频

- 示例代码：（可选）长度：1-20 行
`makeNovel(base, pic, script)`

- 截图：（可选）gif/png/jpg
https://www.bilibili.com/video/BV1jf4y12767

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
