### ISSUE TITLE
在你的Github贡献板上进行任意的像素涂鸦（自荐项目）

### ISSUE THREAD

**Issue by qinshuang1998** [521xueweihan/HelloGitHub#1254]
## 项目推荐
- 项目地址：https://github.com/qinshuang1998/GithubPainter

- 类别：JS、Python

- 项目后续更新计划：此项目以娱乐为主，随缘更新。

- 项目描述：
  - 工作劳累？身体发虚？没时间提交代码？看着自己的Github主页中 0 contributions in the last year 是不是很丧气？不用担心，现在你不仅可以补上你那些空缺的时光，还可以在上面创建属于自己独一无二的像素涂鸦作品，画个爱心对TA表白，涂个蛋糕纪念生日，尽情发挥你的创造力。
  - 本项目仅供娱乐。
  - 仅仅300行不到的简单项目就能让你开心得像是200斤的胖子。

- 推荐理由：艺术无处不在，Github也不要放过噢。

- 截图：

![heatmap](https://inews.gtimg.com/newsapp_ls/0/11799836198/0)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
