### ISSUE TITLE
【scikit-opt】一个轻量部署的群体智能算法库

### ISSUE THREAD

**Issue by guofei9987** [521xueweihan/HelloGitHub#1255]
## 项目推荐
- 项目地址：https://github.com/guofei9987/scikit-opt

- 类别：Python

- 项目后续更新计划：近期将会持续更新到 v1.0.0

- 项目描述：纯Python群体智能算法库（差分进化算法、遗传算法、粒子群算法、模拟退火算法、蚁群算法、鱼群算法、免疫优化算法），特点是轻量部署，支持GPU运算。

- 推荐理由：包含主流群体智能算法，支持GPU运算，轻量部署。月下载量已经1.3k。

- 示例代码：
```python

from sko.GA import GA_TSP

ga_tsp = GA_TSP(func=cal_total_distance, n_dim=num_points, size_pop=50, max_iter=500, prob_mut=1)
best_points, best_distance = ga_tsp.run()

```

- 截图：

![sa](https://img1.github.io/heuristic_algorithm/sa_tsp1.gif)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 50 期](https://hellogithub.com/periodical/volume/50/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
