### ISSUE TITLE
Schedulis 打造灵活完善的金融级工作流调度方案

### ISSUE THREAD

**Issue by SelfImpr001** [521xueweihan/HelloGitHub#1257]
## 项目推荐
- 项目地址：https://github.com/WeBankFinTech/Schedulis

- 类别：Java

- 项目后续更新计划：
目前版本的Schedulis是基于Linkedin 开源的Azkaban开发，对Azkaban 做了多个金融级特性增强，已经在生产大规模使用。在Schedulis 2.0 版本中，我们将和开源社区开发者一起打造基于微服务架构的大数据平台调度系统，持续简化系统的使用难度，增加系统的稳定性，满足各种场景下的批量作业调度需求。

- 项目描述：
Schedulis 是一个基于 LinkedIn 的开源项目 Azkaban 开发的工作流任务调度系统。该调度系统具备高性能，高可用（去中心化多调度中心和多执行器）和多租户资源隔离等金融级特性；现已被集成到数据应用开发门户 DataSphere Studio。Schedulis 支持常规的 Command Shell 和Linkis（HadoopMR、 Hive、Spark、Sqoop、 Python）大数据任务；同时还支持特色的数据检查和工作流之间的依赖任务；支持完善的告警和工作流执行策略；提供多种类型的参数设置，动态全局变量和简单易用的 UI。

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？

模块 | 描述 | Schedulis | Azkaban | Dolphin | Airflow | Xxl-job
-- | -- | -- | -- | -- | -- | --
HA | 调度中心高可用 | 支持 | 不支持 | 支持 | 不支持 | 支持
资源管理 | 执行节点多租户 | 支持 | 不支持 | 支持 | 不支持 | 不支持
运行视图 | 工作流结构图（DAG） | 清晰显示任务状态，任务类型，工作流状态，重试次数等关键信息 | 只显示工作流和任务状态 | 清晰显示任务状态，类型，重试次数，任务运行机器等关键信息 | 只显示任务状态 | 只显示任务状态
WeDataSphere整合 | 对DataSphere Studio和Linkis的支持 | 与DSS和Linkis无缝对接 | 不支持 | 不支持 | 不支持 | 不支持
特色功能 | 循环执行 | 支持 | 不支持 | 不支持 | 不支持 | 不支持
  | 灵活的工作流参数 | 支持不同级别多种设置方式的工作流参数 | 不支持 | 不支持 | 不支持 | 不支持
  | hive表数据到达检查 | 支持 | 不支持 | 不支持 | 不支持 | 不支持
  | 工作流之间交互依赖 | 支持 | 不支持 | 不支持 | 不支持 | 不支持
  | 失败策略 | 支持任务失败暂停、跳过、重试、超时处理 | 不支持失败策略 | 支持任务超时处理 | 支持部分任务重跑策略 | 支持任务超时处理和失败重试
系统管理 | 用户管理 | 支持 | 不支持 | 支持 | 支持 | 不支持

- 截图：
![Schedulis 1.0架构](https://user-images.githubusercontent.com/11420267/82882641-efb6a000-9f73-11ea-8857-03a63c746b2b.png)

<center>Schedulis 1.0架构</center>

![Schedulis 2.0架构](https://user-images.githubusercontent.com/11420267/82882658-f513ea80-9f73-11ea-9b4b-0363a67406bc.png)

<center>Schedulis 2.0架构</center>

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 50 期](https://hellogithub.com/periodical/volume/50/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
