### ISSUE TITLE
C#项目推荐-ScheduleMaster

### ISSUE THREAD

**Issue by hey-hoho** [521xueweihan/HelloGitHub#1258]
## 项目推荐
- 项目地址：https://github.com/hey-hoho/ScheduleMasterCore

- 类别：C#

- 项目后续更新计划：资源监控、多数据库支持、精细化报表、计划拆分等。

- 项目描述：
  ScheduleMaster是一款基于.NET Core平台开发的分布式任务调度系统，专门为现代化部署而生，充分利用.NET Core的优势实现容器友好和云原生。它支持丰富的调度类型、灵活可控的系统参数、简易的UI操作、支持多节点高可用、业务API集成等等特性，同时支持多样化的部署方式，非常容易上手。

- 推荐理由：跨平台、分布式、容器支持

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 51 期](https://hellogithub.com/periodical/volume/51/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
