### ISSUE TITLE
基于Qt5开发的中国象棋网络对战平台[个人开源项目]

### ISSUE THREAD

**Issue by xmuli** [521xueweihan/HelloGitHub#1259]
## 项目推荐
**- 项目地址：**
[https://github.com/xmuli/chinessChess](https://github.com/xmuli/chinessChess)

**- 类别：**
  C++ / Qt

**- 项目后续更新计划：**
  后续互动和反馈活跃的话, 可能会完善人机 AI 算法; 和新增额外功能；当前只是修补一些小信息细节 

**- 项目描述：**
  - 必写：一款支持win/Mac/Linux 的网络对战象棋游戏
  - 可选：兴致休闲时候, 想玩传统益智游戏象棋; 个人学习 Qt 实战
  - 描述长度: 独立开发的话, 2周即可完成

**- 推荐理由：**
  即使处于局域网中, 也可以同时跨平台和好友进行游戏对战; 也可以选择人机对战等模式
   适合新人接学习QT, 迫切想要学习一代码量适中, 渴望能够独立开发一个游戏作品的人; 
   没有弹窗广告, 单纯的象棋三种模式游戏功能

**- 截图：**
<font color=#D0087E size=4 face="幼圆">**win10系统演示：**</font>

<img src="https://raw.githubusercontent.com/touwoyimuli/FigureBed/master/project_log/20190709004321.gif"  height="500" width="800">

<br>

<font color=#D0087E size=4 face="幼圆">**Linux系统演示：**</font>

<img src="https://raw.githubusercontent.com/touwoyimuli/FigureBed/master/project_log/20190709004216.gif"  height="500" width="800">

<br>

**<font color=#D0087E size=4 face="幼圆">MacOS系统演示：**</font>

<img src="https://raw.githubusercontent.com/touwoyimuli/FigureBed/master/project_log/20190709004745.gif"  height="500" width="800">

<br>

<font color=#70AD47 size=4 face="幼圆">**跨平台对战演示：**</font>   **MacOS 10.14  vs  Win10**

<img src="https://raw.githubusercontent.com/touwoyimuli/FigureBed/master/project_log/20190709004454.gif"  height="500" width="800">

<br>

**补充：**
暂时未被收录过 && 已经适当修改 README.md

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by zhengfy10** [comment]
#1259




| |
郑方圆
|
|
邮箱：zhengfangyuan10@163.com
|

签名由 网易邮箱大师 定制

在2020年06月27日 15:58，削微寒 写道：

Closed #1259.

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 51 期](https://hellogithub.com/periodical/volume/51/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
