### ISSUE TITLE
从Chrome中获取自动保存的用户名密码[自荐项目]

### ISSUE THREAD

**Issue by cckuailong** [521xueweihan/HelloGitHub#1261]
## 项目推荐
- 项目地址：
https://github.com/cckuailong/HackChrome

- 类别：
Go

- 项目后续更新计划：
Google Chrome会改变或加强算法，后续跟进进行新算法的解密

- 项目描述：
  从Chrome中获取自动保存的用户名密码，可获取当前全版本Windows Chrome中存储的密码

- 推荐理由：
如果刚刚升级Chrome到v80，之前保存的密码和之后保存的密码存储加密方式将会不同，所以HackChrome将两组结果 以某种算法聚合起来，得到最终的用户名密码数组

- 截图：
![demo](https://raw.githubusercontent.com/cckuailong/HackChrome/master/image/result.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 51 期](https://hellogithub.com/periodical/volume/51/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
