### ISSUE TITLE
跨平台python代码加密(加速)工具 [自荐项目]

### ISSUE THREAD

**Issue by cckuailong** [521xueweihan/HelloGitHub#1262]
## 项目推荐
- 项目地址：
https://github.com/cckuailong/py2sec

- 类别：
python

- 项目后续更新计划：
1. 增加新功能，如合并结果文件
2. 优化代码结构

- 项目描述：
py2sec 一款轻量的脚本工具，基于 Cython 将 .py 编译成 run-time libraries 文件：.so (Linux && Mac)，或 .pyd (Win)。一定程度上实现了“加密”保护源代码的需求。

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？
1. so / .pyd 文件可以像 .py 模块一样正常调用。例如：import 或 from module import * "
2. py2sec 可以指定编译单个 .py 文件，也可以指定一个 python 项目目录
3. py2sec 还可以提升代码运行速度，至多提升30倍
4. py2sec 自动识别项目中的 .py 文件，且只编译 .py 类型文件
5. 可以指定不需要编译的文件或子目录
6. py2sec 不影响源文件，加密后的文件或项目将被存放在 result 文件夹
7. 兼容多平台：macOS、Linux、Windows、
8. 兼容 Python 版本：python2 and python3, 可使用 -p(--py) 参数来指定版本

- 代码：
```
-v,  --version    显示 py2sec 版本
-h,  --help       显示帮助菜单
-p,  --pyth       Python的版本, 默认为 你的 "python" 命令绑定的python版本
                  例: -p 3  (比如你使用python3)
-d,  --directory  Python项目路径 (如果使用-d参数, 将编译整个Python项目)
-f,  --file       Python文件 (如果使用-f, 将编译单个Python文件)
-m,  --maintain   标记你不想编译的文件或文件夹路径
                  注意: 文件夹需要以路径分隔符号（`/`或`\\`，依据系统而定）结尾，并且需要和-d参数一起使用 
                  例: -m setup.py,mod/__init__.py,exclude_dir/
-x  --nthread     编译启用的线程数
-q  --quiet       静默模式，默认False
-r  --release     Release 模式，清除所有中间文件，只保留加密结果文件，默认False
python py2sec.py -f test.py
python py2sec.py -f example/test1.py -r
python py2sec.py -d example/ -m test1.py,bbb/
```

- 截图：
![demo](https://raw.githubusercontent.com/cckuailong/py2sec/master/img/2.png)

- 补充：
项目前身为py2so (<https://github.com/cckuailong/py2so>) ，之前的已停止维护，但是受到很多好评，简书上有几个人推荐了这个项目，之前的项目star fork较多，可以作为参考，本项目开放时间短，欢迎程度参考py2so

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
