### ISSUE TITLE
Spring Boot +Vue 技术栈开发的前后端分离商城项目

### ISSUE THREAD

**Issue by newbee-mall** [521xueweihan/HelloGitHub#1263]
## 项目推荐
- 项目地址：[https://github.com/newbee-ltd/newbee-mall-vue-app](https://github.com/newbee-ltd/newbee-mall-vue-app)

- 类别：JS

- 项目后续更新计划：继续完善功能，并对项目进行性能优化，Vue 3 版本稳定后再对项目进行整体的升级迭代。

- 项目描述：newbee-mall-vue-app 项目是一套移动端版本的电商系统，采用前后端分离模式进行开发和部署，技术栈为 Vue + Spring Boot，包含首页门户、商品分类、新品上线、首页轮播、商品推荐、商品搜索、商品展示、购物车、订单结算、订单流程、个人订单管理、会员中心、帮助中心等模块。

- 推荐理由：

  1. 项目采用前后端分离开发模式；
  2. 主要技术栈为 Spring Boot 技术栈 + Vue 技术栈；
  3. 代码开源且源码完善、功能完备、流程完整、页面交互美观；
  4. 技术栈新颖且知识点丰富，学习后可以提升大家对于知识的理解和掌握，可以进一步提升你的市场竞争力。

- 截图：

##### 接口文档

![](https://newbee-mall.oss-cn-beijing.aliyuncs.com/poster/vue/newbee-mall-api-swagger.png)

##### 页面展示

以下为新蜂商城 Vue 版本的页面预览：

- 登录页

![](https://newbee-mall.oss-cn-beijing.aliyuncs.com/poster/vue/登录.png)

- 首页

![](https://newbee-mall.oss-cn-beijing.aliyuncs.com/poster/vue/首页.png)

- 商品搜索

![](https://newbee-mall.oss-cn-beijing.aliyuncs.com/poster/vue/商品搜索.png)

- 商品详情页

![](https://newbee-mall.oss-cn-beijing.aliyuncs.com/poster/vue/详情页.png)

- 购物车

![](https://newbee-mall.oss-cn-beijing.aliyuncs.com/poster/vue/购物车.png)

- 生成订单

![](https://newbee-mall.oss-cn-beijing.aliyuncs.com/poster/vue/生成订单.png)

- 地址管理

![](https://newbee-mall.oss-cn-beijing.aliyuncs.com/poster/vue/地址管理.png)

- 订单列表

![](https://newbee-mall.oss-cn-beijing.aliyuncs.com/poster/vue/订单列表.png)

- 订单详情

![](https://newbee-mall.oss-cn-beijing.aliyuncs.com/poster/vue/订单详情.png)

**Comment by 521xueweihan** [comment]
已收录，月刊不再重复收录。
