### ISSUE TITLE
C++基本算法

### ISSUE THREAD

**Issue by DeusOfDeepThoughts** [521xueweihan/HelloGitHub#1265]
## 项目推荐
- 项目地址：https://github.com/DeusOfDeepThoughts/Devs

- 类别：C++

- 项目描述：
该项目实现了C++的基本算法。结合《剑指offer》和《数据结构》中的题目，总结了这些算法的应用场景，并对C++中的一些语法进行了归纳。
该项目旨在尽可能地运用简单易懂的代码，大量的注释，帮助初学者在代码中应用算法，学会算法。

- 推荐理由：
该项目能帮助研习算法的初学者从网络中大量散乱的资料中解脱出来，从头到尾，简简单单地读代码、用代码，最终将这些基本的算法纳为己有。

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
