### ISSUE TITLE
[自荐] DJL -- 一个 基于Java的深度学习框架

### ISSUE THREAD

**Issue by lanking520** [521xueweihan/HelloGitHub#1269]
## 项目推荐

- 项目地址：
https://djl.ai 
https://github.com/awslabs/djl

- 类别

Java 机器学习

- 项目后续更新计划：

AWS 开源项目组鼎力支持，会增添更多的功能以及深度学习引擎支持

- 项目描述：

Deep Java Library （简称DJL）是一个很新的项目，在2019年12月初的AWS  re: invent大会上才正式的发布出来。。简单来说，DJL是一个使用Java API简化模型训练、测试、部署和使用深度学习模型进行推理的开源库深度学习框架，开源的许可协议是Apache-2.0。对于Java开发者而言，可以在Java中开发及应用原生的机器学习和深度学习模型，同时简化了深度学习开发的难度。通过DJL提供的直观的、高级的API，Java开发人员可以训练自己的模型，或者利用数据科学家用Python预先训练好的模型来进行推理。如果您恰好是对学习深度学习感兴趣的Java开发者，那么DJL无疑将是开始深度学习应用的一个最好的起点。

DJL是在现有深度学习框架的基础上使用原生Java概念构建的的开发库。它为开发者提供了深度学习的最新创新和使用前沿硬件的能力，例如GPU、MKL等。简单的API抽象并简化了开发深度学习模型所涉及的复杂性，使得这个新的框架更易于学习和应用。有了model-zoo中绑定的预训练模型集，开发者可以立即开始将深度学习的SOTA成果集成到Java应用当中。总所周知，JAVA 的设计思想有这样的一句“Write once, run anywhere”（WORE）。同样， DJL 的设计目标也设定为不依赖于具体的引擎和深度学习框架，可以随时切换框架。原则上，基于DJL开发人员可以编写在任何引擎上运行的代码。DJL目前提供了Apache MXNet, TensorFlow 与PyTorch的实现。

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？

眼前一亮的点: 用起来很容易, [不到20行](https://github.com/awslabs/djl/blob/master/jupyter/load_pytorch_model.ipynb)就可以实现一个模型的读取到推理过程。提供了[安卓支持](https://github.com/aws-samples/djl-demo/tree/master/android)，轻松部署想要的模型。工业界的支持：DJL 现已运行在亚马逊数以百万的推理任务中。

解决的痛点：长久以来，Java用户一直没有一个很好使用的深度学习框架，使得在工业界的部署变得异常困难。DJL解决了这个问题，从依赖项管理，到最后部署代码，都达到了易用性和高维护性的特色，在服务器端，大数据平台 （Spark）都有很好的成绩。

- 示例代码：

https://github.com/aws-samples/djl-demo 这个repo包含了所有应用的示例代码。

在线运行平台: https://djl.ai/website/demo.html, 一键运行，部署你的深度学习模型。

- 截图：

安卓项目效果：

![image](https://github.com/aws-samples/djl-demo/raw/master/android/img/rabbit.gif)

项目 logo
![image](https://user-images.githubusercontent.com/11890922/83983064-2aa7c480-a8e0-11ea-832a-7aa3097fac52.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 51 期](https://hellogithub.com/periodical/volume/51/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
