### ISSUE TITLE
rust version的grep

### ISSUE THREAD

**Issue by franklingu** [521xueweihan/HelloGitHub#127]
## 项目推荐
- 项目名称：
ripgrep
- 项目地址：
https://github.com/BurntSushi/ripgrep
- 项目语言：
Rust
- 项目描述：
ripgrep combines the usability of The Silver Searcher with the raw speed of grep.
- 推荐理由：
ripgrep is a line oriented search tool that recursively searches your current directory for a regex pattern while respecting your gitignore rules. To a first approximation, ripgrep combines the usability of The Silver Searcher (similar to ack) with the raw speed of GNU grep. ripgrep has first class support on Windows, macOS and Linux, with binary downloads available for every release.
- 示例代码：

- 截图：
![use case from repo](https://camo.githubusercontent.com/a750be5009f196be6158976afd5bc53356f9273d/687474703a2f2f6275726e7473757368692e6e65742f73747566662f72697067726570312e706e67)

**Comment by franklingu** [comment]
1. unicode-8 support by default
2. 很快
不过
1. regex engine是finite automata，某些feature比如look around就没有了（个人还是觉得蛮有用的）
2. 不支持compressed（那就switch to zgrep喽或者直接unzip然后pipe一下喽）

**Comment by 521xueweihan** [comment]
@franklingu 老铁中文越来约好了

**Comment by franklingu** [comment]
哈哈哈哈，术语的话就喜欢用英文，下次再说吧

是支持utf8的，速度也很快，不过它的正则表达式某些高级功能没有，这个是rust的regex engine的问题，暂时不支持压缩的文件

**Comment by FrontMage** [comment]
要是有ruby的黑科技正则就爽了，看了下是有限状态机实现的正则，只有正则的基本功能
