### ISSUE TITLE
TypeScript 的小程序脚手架[自荐]

### ISSUE THREAD

**Issue by rottenpen** [521xueweihan/HelloGitHub#1272]
## 项目推荐
- 项目地址：[wx-typescript-cli](https://github.com/rottenpen/wx-typescript-cli)

- 类别：JS（TS）

- 项目后续更新计划：
  - 支持自动生成骨架屏

- 项目描述：
  - 这是一个基于 webpack 的 TS 编写小程序的脚手架。
  - 适合想要原生编写小程序的体验，又能写 TypeScript 的同学。
  - 为什么要基于 webpack？让项目可以使用 npm，能够通过命令行控制生产环境/开发环境的切换。
  - 内置了类 axios 的小程序请求库。axios 有的功能它都有，axios 没的功能它也有。可以告别 wx.request 糟糕的请求体验。
  - 支持 es-next，包括 es2020 的新语法。
  - 在 wxss 里面使用 less

- 推荐理由：
  - 现在市面上主流的一些小程序开发框架，都会在原生开发之上加上一些他们的规则，这样会造成开发流程的不透明，原生开发的 bug 已经够多了，再加一层框架会提高开发过程的难度。wx-typescript-cli 就是为了解决这个问题，被制造出来的。

**Comment by rottenpen** [comment]
骨架屏的功能也实现了

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
