### ISSUE TITLE
【pyprobar】一个简单优雅的进度条工具

### ISSUE THREAD

**Issue by beidongjiedeguang** [521xueweihan/HelloGitHub#1276]
## 项目推荐
- 项目地址：https://github.com/beidongjiedeguang/python-progress-bar

- 类别：Python

- 项目后续更新计划：近期会保持更新

- 项目描述：
  简单优雅的进度条工具

- 推荐理由：
    - 漂亮，漂亮，漂亮！
    - 高性能
    - 简单
    - 优雅

- 示例代码：
```python
from pyprobar import probar
for i in probar(range(20000000)):
    pass
```

- 截图：<img src="https://raw.githubusercontent.com/beidongjiedeguang/python-progress-bar/master/picture/color%3D1.gif" />

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
