### ISSUE TITLE
【TimeCat】一个神奇的Web录屏器

### ISSUE THREAD

**Issue by oct16** [521xueweihan/HelloGitHub#1278]
## 项目推荐
- 项目地址：https://github.com/oct16/TimeCat

- 类别：JS

- 项目后续更新计划：
  - 更多录制元素的支持
  - 算法与性能优化
  - 完整的生产环境解决方案

- 项目描述：
一个Web录屏器，参考了游戏录像的原理而实现的渲染引擎，生成的录像文件只有传统视频的百分之一！还可以在录制语音的同时自动生成字幕，导出的视频文件可以跨端播放，目前已经开发三个月时间，还处于WIP阶段，后续还将实现更多有意思的Feature

- 推荐理由：前端黑魔法

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 51 期](https://hellogithub.com/periodical/volume/51/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
