### ISSUE TITLE
【自荐】基于React的组件可视化拖拽，页面搭建，代码生成工具

### ISSUE THREAD

**Issue by anye931123** [521xueweihan/HelloGitHub#1281]
## 项目推荐
- 项目地址：https://github.com/brick-design/react-visual-editor
- 在线预览：https://anye931123.gitee.io/react-visual-editor

- 类别：JavaScript、Typescript、React、前端、其他

- 项目后续更新计划：
  - 新版将会以组件的形式调用通用简单
  - 新版会在保留老版本的基础上增加一些新的功能
     - 实时拖拽预览
     - 辅助线功能
     - 组件之间相对位置查看
     - hover直接操作组件
     - 等等····
  - 新的数据结构，更易操作，更易理解
  - 新版会比老版性能提升很多
  
- 项目描述：
  - 项目基于 React组件之间的原始约束设计，不会添加多余dom节点，以组件可视化拖拽，嵌套形式，完全还原真实开发中页面代码的实现过程，组件可以自由拖拽嵌套，配合dom树与设计面板的实时交互，实现组件实时追踪，使设计面板快速响应你对组件的操作，所见即所得，可以完美还原UI设计搞，并支持多款型号手机（可配置），和PC效果展示，模板功能可以使你分享你的页面或者页面中局部任何部分组件组合，减少相似页面的重复操作，可以选择以React源码生成的形式生成页面代码，也可以以JSON动态更新的形式实现noCode。
- 现有功能描述  
   - **任意拖拽嵌套**：通过组件预览面板拖拽组件，到设计面板实现任意嵌套，或者拖拽到DomTree中指定容器节点，DomTree与设计面板中的组件也可随意拖拽嵌套
   - **实时预览**：设计面板中会实时展示组件的属性效果和样式效果，并且与真实页面无异，所见即所得
   - **DomTree展示**：页面组件dom树的展示并实现组件dom实时追踪
   - **可视化属性配置**：结合React 特性和JS语法定制了可视化的组件属性配置，实现复杂数据结构的可视化配置
   - **可视化样式配置**：通过样式配置面板修改样式，实时在页面中显示样式效果
   - **模板功能**：可以选中局部或者整个页面做为可复用的模板，提高页面配置效率减少重复工作
   - **组件约束**：根据组件特性，可以配置组件的父组件约束与子组件约束，解决组件间的错误嵌套和报错
   - **预览与代码生成**：可随时预览页面的真实效果，和页面的jsx代码与样式代码
   - **多平台支持** ：支持PC与移动端多型号设配切换展示
   - **组件库替换**：通过简单的配置可以对接任何React组件库

- 推荐理由：基于react的组件之间原始约束，可视化拖拽、可完美还原UI设计稿、所见即所得，源码生成，多设备展示、实时预览。解决不会React技术栈的人员，使他们可以快速搭建React页面。项目适用于产品、设计、开发人员主要针对不会React技术栈的人员，使他们可以快速搭建React页面。

- 截图：
![brickd1](https://user-images.githubusercontent.com/15995127/85188005-7e4de100-b2d6-11ea-9441-2bd5570b14a9.gif)
![brickd2](https://user-images.githubusercontent.com/15995127/85187856-86595100-b2d5-11ea-883e-e45313797fb3.gif)
![brickd3](https://user-images.githubusercontent.com/15995127/85187862-92451300-b2d5-11ea-8394-a6c06b45de97.gif)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 51 期](https://hellogithub.com/periodical/volume/51/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
