### ISSUE TITLE
Mongood-MongoDB 图形化管理工具

### ISSUE THREAD

**Issue by RobiNexy** [521xueweihan/HelloGitHub#1282]
## 项目推荐
- 项目地址：https://github.com/RenzHoly/Mongood

- 类别：JS

- 项目后续更新计划：
  - geo search
  - role management
 
- 项目描述：
  - 必写：MongoDB 图形化的管理工具 
  - 可选：不只是简单的工具，在设计中包含了作者一些 MongoDB 的使用经验和深入理解
  - 描述长度（不包含示例代码）: 

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？

目前为止最好看的 MongoDB 图形化管理界面，基于微软 Fluent UI，支持自动黑暗模式；支持完整的 Mongo-shell 数据类型和查询语法，利用索引实现的自动查询和排序；支持 Json 数据库模式，既可用于 Server 也可用于 Client。

- 示例代码：（可选）长度：1-20 行
Run as client:
```
npm ci
npm run build
cd go
go build .
MONGO_URL="mongodb://localhost:27017" ./mongood
```

Run as server:
```
docker run -p 3000:3000 -e MONGO_URL="mongodb://localhost:27017" renzholy/mongood
```

Dev mode:
```
npm ci
npm run dev
cd go
go run main.go headless.go
```
- 截图：（可选）gif/png/jpg
![image](https://user-images.githubusercontent.com/44633884/84375931-d750b180-ac12-11ea-99ac-07bb21cef623.png)
![image](https://user-images.githubusercontent.com/44633884/84376011-f8190700-ac12-11ea-8d2c-cb82e5bf871b.png)
![image](https://user-images.githubusercontent.com/44633884/84376030-023b0580-ac13-11ea-997a-fcefa0f31d35.png)
![image](https://user-images.githubusercontent.com/44633884/84376105-24348800-ac13-11ea-974a-334a3979c1d1.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 51 期](https://hellogithub.com/periodical/volume/51/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
