### ISSUE TITLE
Gostream  类Java8的Stream API [自荐项目]

### ISSUE THREAD

**Issue by gaojunhuicavon** [521xueweihan/HelloGitHub#1286]
## 项目推荐
- 项目地址：https://github.com/gaojunhuicavon/gostream

- 类别：Go

- 项目后续更新计划：
  - 增加Int64Stream
  - 扩展Stream接口：foreach、count、anyMatch、allMatch

- 项目描述：
  - Gostream是一个类Java的Stream API，用于支持go中的函数式编程，例如mapreduce等操作。
  - 通过Gostream可以很方便地在Go上进行函数式编程，从而得到函数式编程带来的好处。函数式编程是面向数学的抽象，将计算描述为一种表达式求值，关心数据的映射。由于函数式编程是数据的映射，带来的好处是数据的不可变性，原始数据不会被直接修改，也即无副作用。而不可变性又使得多个线程不会发生资源争用，也就不会发生死锁，从而使得并发变成更为容易。

- 推荐理由：函数作为Go的一等公民，十分适合函数式编程，通过Gostream可以带来更好的函数式编程体验，获得其带来的好处，其中包括提高程序性能。

- 示例代码：
```Go
package main

import (
	"github.com/gaojunhuicavon/gostream"
	"log"
)

const (
	red color = iota
	green
	yellow
)

type color int

type widget struct {
	color  color
	weight int
}

func main() {
	widgets := []*widget{{red, 1}, {green, 2}, {yellow, 3}}
	max, err := gostream.NewSequentialStream(widgets).Filter(func(val interface{}) (match bool) {
		return val.(*widget).color == red
	}).MapToInt(func(src interface{}) (dest int) {
		return src.(*widget).weight
        }).Max()
	if err != nil {
		log.Printf("get an error: %s\n", err.Error())
		return
	}
	if max != nil {
		log.Printf("the max weight is %d\n", *max)
	}
}
```

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
