### ISSUE TITLE
无需额外注解的 SpringBoot API文档生成工具

### ISSUE THREAD

**Issue by YeDaxia** [521xueweihan/HelloGitHub#1288]
## 项目推荐

- 项目地址：https://github.com/YeDaxia/JApiDocs

- 类别：Java

- 项目后续更新计划：

这个工具的目标很明确，就是尽可能提升前后端沟通和开发效率。接下来的计划包括但不限于：

1. 支持更多导出文档格式；
2. 自动生成前端的接口代码，供App或网页前端开发同学直接使用；
3. 把发生变化的接口标识出来；
4. 对接一些开源mock平台等。

- 项目描述：

JApiDocs是一个无需额外注解、开箱即用的SpringBoot接口文档生成工具。

功能特性：

1、代码即文档

JApiDocs是通过直接解析SpringBoot的源码语法来工作的，所以只要Controller的语法符合一定的代码规范，有合理的注释，就可以直接导出文档。

2、支持导出HTML

便捷的导航和接口查看界面；可本地预览，或者部署到HTTP服务器。推荐部署到服务器，方便前后端展开协作。

3、同步导出客户端Model代码

支持导出Android端的 Java 和iOS端的 Object C Model代码，减少前端程序员的重复编码工作。

4、更多特性

支持接口搜索；支持不同版本和英文文档；自定义扩展等。

- 推荐理由：

相比Swagger要写一堆注解，Spring Rest Docs需要写测试用例，才能生成API文档，JApiDocs 具有无痛集成的特点。

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 51 期](https://hellogithub.com/periodical/volume/51/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）

**Comment by YeDaxia** [comment]
好的，谢谢！
