### ISSUE TITLE
 tool-tips Idea 中有哪些相见恨晚的技巧

### ISSUE THREAD

**Issue by xiaoxiunique** [521xueweihan/HelloGitHub#1289]
## 项目推荐
- 项目地址：
https://github.com/xiaoxiunique/tool-tips

- 类别：其他

- 项目描述：
  整理自 Idea 的操作技巧，快捷操作，多光标操作，并附带有 GIF 动图展示

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？
平时比较热爱探索 idea 的快捷之处。更多的喜欢用快捷键进行操作，所以做了很多笔记📚。个人认为对一个工具熟练之后, 你的编程效率, 和解决问题的效率都能得到大大的提升.
当时看到这个回答的时候只是非常随意的复制😬，没有想到的是大家的反响还是不错😊。我感觉大家好像对某些在我看来非常常用的操作还是很陌生的😅。于是我后续对他做了完善。便就有了这个项目😎。
现已累计 830 star

**Comment by 521xueweihan** [comment]
@xiaoxiunique 您好，该项目已推荐过。
