### ISSUE TITLE
pybigdata 使用 python 操作大数据的各种组件

### ISSUE THREAD

**Issue by TurboWay** [521xueweihan/HelloGitHub#1291]
## 项目推荐
- 项目地址：https://github.com/TurboWay/pybigdata

- 类别：Python

- 项目描述：
  - 使用 python 操作大数据的各种组件

- 推荐理由：

  汇总大数据各种常用组件的 python api 和 demo 示例，便于初学者以 python 进入大数据领域，而不必去学习 java

**Comment by 521xueweihan** [comment]
该项目很有价值，我浏览了下，目前是一些连接、基础 demo，可否再增加一些进阶的用法，参数的详解的和实际应用场景。让整项目更进一步，Python 支配大数据的领域的重任就交给你了！

期待你的后续更新和再次自荐！
