### ISSUE TITLE
A dead simple, fast SFTP file system 【自荐项目】

### ISSUE THREAD

**Issue by RainMark** [521xueweihan/HelloGitHub#1293]
## 项目推荐
- 项目地址：https://github.com/RainMark/oxfs

- 类别：Python

- 项目后续更新计划：
  - 文件属性 cache 持久化。
  - 引入 agent 工具，方便控制 cache 失效。
  - windows 平台支持。

- 项目描述：
  - 这是一个基于 sftp 协议的 fuse 网络文件系统。功能上类似于 sshfs 。
  - oxfs 相比 sshfs 而言更为高效，访问远端文件极快，尤其是网络条件较差时。
  - 在做远程开发没有 GUI 编辑代码时，使用 oxfs 能够挂载远程目录到本地，流畅使用
本地 IDE 开发项目，不会出现 sshfs 那种卡顿问题。
  - 各种各样的原因，我们需要更快的网络文件系统。

- 推荐理由：
  - oxfs 引入了异步并发读远端文件机制，提高了文件首次读速度。
  - 特别地降远端文件 cache，并持久化到本地磁盘，下次挂载时访问更加快速。
  - 文件的读写优先走 cache，异步任务负责同步文件，避免低速的网络读写阻塞上层应用。

- 示例代码：

```bash
$ oxfs -h
usage: oxfs [-h] [--host HOST] [--ssh-port SSH_PORT]
            [--apiserver-port APISERVER_PORT] [--mount-point MOUNT_POINT]
            [--remote-path REMOTE_PATH] [--cache-path CACHE_PATH]
            [--logging LOGGING] [--daemon] [-v]

optional arguments:
  -h, --help            show this help message and exit
  --host HOST           ssh host (example: root@127.0.0.1)
  --ssh-port SSH_PORT   ssh port (defaut: 22)
  --apiserver-port APISERVER_PORT
                        apiserver port (default: 10010)
  --mount-point MOUNT_POINT
                        mount point
  --remote-path REMOTE_PATH
                        remote path (default: /)
  --cache-path CACHE_PATH
                        cache path
  --logging LOGGING     logging file
  --daemon              daemon
  -v, --verbose         debug info

```

- 截图：

![](https://github.com/RainMark/oxfs/raw/master/files/mount.gif)
![](https://github.com/RainMark/oxfs/raw/master/files/operations.gif)
![](https://github.com/RainMark/oxfs/raw/master/files/umount.gif)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 51 期](https://hellogithub.com/periodical/volume/51/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
