### ISSUE TITLE
【PowerJob】强大的分布式任务调度与计算框架（自荐项目）

### ISSUE THREAD

**Issue by KFCFans** [521xueweihan/HelloGitHub#1294]
## 项目推荐
- 项目地址：https://github.com/KFCFans/PowerJob

- 类别：Java

- 项目后续更新计划：持续更新和维护

- 项目描述：
 PowerJob是基于Akka架构的新一代分布式任务调度与计算框架，支持CRON、API、固定频率、固定延迟等调度策略，支持单机、广播、MapReduce等多种执行模式，支持在线任务治理与运维，提供Shell、Python、Java等功能丰富的任务处理器，提供工作流来编排任务解决依赖关系，使用简单，功能强大，文档齐全！

- 推荐理由：当前市面上最强大的分布式任务调度与计算框架，代码质量高，文档齐全，功能强大，接入简单！附同类产品对比：

|                | QuartZ                   | xxl-job                                  | SchedulerX 2.0                                    | PowerJob                                                |
| -------------- | ------------------------ | ---------------------------------------- | ------------------------------------------------- | ------------------------------------------------------------ |
| 定时类型       | CRON                     | CRON                                     | CRON、固定频率、固定延迟、OpenAPI                 | **CRON、固定频率、固定延迟、OpenAPI**                        |
| 任务类型       | 内置Java                 | 内置Java、GLUE Java、Shell、Python等脚本 | 内置Java、外置Java（FatJar）、Shell、Python等脚本 | **内置Java、外置Java（容器）、Shell、Python等脚本**          |
| 分布式任务     | 无                       | 静态分片                                 | MapReduce动态分片                                 | **MapReduce动态分片**                                        |
| 在线任务治理   | 不支持                   | 支持                                     | 支持                                              | **支持**                                                     |
| 日志白屏化     | 不支持                   | 支持                                     | 不支持                                            | **支持**                                                     |
| 调度方式及性能 | 基于数据库锁，有性能瓶颈 | 基于数据库锁，有性能瓶颈                 | 不详                                              | **无锁化设计，性能强劲无上限**                               |
| 报警监控       | 无                       | 邮件                                     | 短信                                              | **邮件，提供接口允许开发者扩展**                             |
| 系统依赖       | MySQL                    | MySQL                                    | 人民币 | **任意Spring Data Jpa支持的关系型数据库（MySQL、Oracle...）** |
| DAG工作流      | 不支持                   | 不支持                                   | 支持                                              | **支持**                                   |

- 示例代码：
[代码示例](https://www.yuque.com/powerjob/guidence/hczm7m)
[在线试用](https://www.yuque.com/powerjob/guidence/hnbskn)

- 截图：
[系统截图](https://www.yuque.com/ohmyscheduler/guidence/ysug77)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by KFCFans** [comment]
> **您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
> 欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

好的，非常感谢！

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 51 期](https://hellogithub.com/periodical/volume/51/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
