### ISSUE TITLE
【自荐】简易Windows PE文件加壳器

### ISSUE THREAD

**Issue by czs108** [521xueweihan/HelloGitHub#1297]
## 项目推荐
- 项目地址：[PE-Packer](https://github.com/czs108/PE-Packer)

- 类别：C、80386汇编、逆向工程

- 项目后续更新计划：暂无

- 项目描述：

  ***PE-Packer***是一款针对**Windows PE**文件的简单加壳程序，加壳后的可执行文件可以对*逆向分析*过程造成干扰。

  对PE文件加壳时，程序会进行如下工作：

  - 转换导入表结构。
  - 加密节区数据。
  - 清除节区名称。
  - 安装*解密模块*。

  加壳后的文件启动时，*解密模块*会加载原始数据及代码：

  - 解密节区数据。
  - 初始化导入表。
  - 重定位。

  > 该项目目前仅用于初学者学习*Windows PE格式*和*汇编语言*，其仍存在兼容性问题及其他Bug，尚不能用于实际生产环境。

- 示例代码：

  80386汇编及C语言混合编程：
  
  ```assembly
  ; get the address of VirtualAlloc API
  lea     esi, [ebp + (dll_name - boot_seg_begin_lbl)]
  push    esi
  call    dword ptr [ebp + (second_thunk - boot_seg_begin_lbl)]
  lea     esi, [ebp + (virtual_alloc_name - boot_seg_begin_lbl)]
  push    esi
  push    eax
  call    dword ptr [ebp + (first_thunk - boot_seg_begin_lbl)]
  mov     dword ptr [ebp + (virtual_alloc_addr_boot - boot_seg_begin_lbl)], eax
  ```
  
  使用Doxygen文档规范：
   
  ```c
  /**
   * @brief Enumerate the import table.
   * 
   * @param image_info    The PE image.
   * @param callback
   * The `::LPFN_ENUM_IMP_CALLBACK` method,
   * it will be called on each `IMAGE_IMPORT_DESCRIPTOR` structure.
   * @param arg           The optional custom argument, it will be passed to `callback`.
   */
  static void EnumImpTable(
      const PE_IMAGE_INFO *const image_info,
      const LPFN_ENUM_IMP_CALLBACK callback,
      void *const arg);
  ```

- 截图：

  运行流程：

  ![screenshot](https://github.com/czs108/PE-Packer/blob/master/docs/screenshots/test-helloworld.png)

  加壳后的反汇编代码及导入表：

  ![packed-code](https://github.com/czs108/PE-Packer/blob/master/docs/screenshots/packed-code.png)

  ![packed-import-table](https://github.com/czs108/PE-Packer/blob/master/docs/screenshots/packed-import-table.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
