### ISSUE TITLE
【开源项目】HandyControl一款丰富、优美的WPF框架

### ISSUE THREAD

**Issue by JeremyWu917** [521xueweihan/HelloGitHub#1302]
## 项目推荐
- 项目地址：https://github.com/HandyOrg/HandyControl

- 类别：C#

- 项目后续更新计划：继续扩充自定义控件（附加属性）

- 项目描述：
  - HandyControl是一套WPF控件库，它几乎重写了所有原生样式，同时包含70余款自定义控件。支持跨平台，支持国际化
  - 适用于MVVM架构开发，扁平化设计，支持动态更换主题和背景色；丰富的自定义控件解决了VIEW设计的痛点，让程序员更加专注于业务逻辑的开发
  - HandyControl：Everything can be handy，致力于为用户提供最简单的API！

- 推荐理由：扁平化UI界面，动态主题/背景色，丰富的扩展控件和附加属性，极大地提升项目开发效率

- 示例代码：
```
<Application.Resources>
    <ResourceDictionary>
        <ResourceDictionary.MergedDictionaries>
            <ResourceDictionary Source="pack://application:,,,/HandyControl;component/Themes/SkinDefault.xaml"/>
            <ResourceDictionary Source="pack://application:,,,/HandyControl;component/Themes/Theme.xaml"/>
        </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
</Application.Resources>
```

- 截图：
![image](https://user-images.githubusercontent.com/54832272/85264863-eef62880-b4a3-11ea-8c98-10474f7bac66.png)
![HelloGitHub0](https://user-images.githubusercontent.com/54832272/85265542-01bd2d00-b4a5-11ea-9342-667fde2ccd5a.gif)
![HelloGitHub1](https://user-images.githubusercontent.com/54832272/85265868-83ad5600-b4a5-11ea-9871-3f5ca7b5c5b5.gif)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 51 期](https://hellogithub.com/periodical/volume/51/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
