### ISSUE TITLE
码小六 - GitHub 代码泄露监控系统（自荐项目）

### ISSUE THREAD

**Issue by code6er** [521xueweihan/HelloGitHub#1304]
## 项目推荐
- 项目地址：https://github.com/4x99/code6

- 类别：PHP

- 项目后续更新计划：
  - 移动端
  - 支持丰富的搜索语法
  - 消息报警通知

- 项目描述：
  - 全可视化界面，操作简单
  - 支持 GitHub 令牌管理及智能调度
  - 扫描结果信息丰富，支持批量操作
  - 任务配置灵活，可单独配置任务扫描参数
  - 支持白名单模式，主动忽略白名单仓库

- 推荐理由：快速部署，通过定期扫描 GitHub 发现代码泄露行为，为企业安全保驾护航！

- 截图：

![登录页面](https://raw.githubusercontent.com/4x99/snapshot/master/code6/login.png)

![应用概况](https://raw.githubusercontent.com/4x99/snapshot/master/code6/home.png)

![扫描结果](https://raw.githubusercontent.com/4x99/snapshot/master/code6/code-leak.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 51 期](https://hellogithub.com/periodical/volume/51/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
