### ISSUE TITLE
About Promise Priority Chain （优先级以及异步逻辑嵌套问题抽象解决方案）

### ISSUE THREAD

**Issue by RunsCode** [521xueweihan/HelloGitHub#1305]
## 项目推荐
- 项目地址：https://github.com/RunsCode/PromisePriorityChain

轻量级优先级处理类，采用单向链表设计， 自动内存管理无需外部强引用。
Lightweight priority processing class with LinkedList design that automates memory management without strong external references.
可以解决如下问题：

优先级逻辑处理
嵌套逻辑展开铺平
异步嵌套逻辑展开至同步的书写方式
检验逻辑抽象包装
轮询逻辑抽象包装
状态延迟抽象包装
The following issues can be resolved:

Priority logic processing
Nested logic spread
Asynchronous nesting logic expands to synchronous writing
Testing logic abstract packaging
Poll logic abstract wrapping

Transition delay abstract packaging提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://github.com/RunsCode/PromisePriorityChain

再次感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
