### ISSUE TITLE
【Javascript】会发声的 back to top 插件

### ISSUE THREAD

**Issue by QingZ11** [521xueweihan/HelloGitHub#1306]
## 项目推荐
- 项目地址：https://github.com/tholman/elevator.js

- 类别：JS

- 项目后续更新计划：暂无

- 项目描述：
  - 必写：叮~页面已到达顶部。elevator.js 是一个 back to top 返回顶部的插件，如他的名字所说，网页在返回顶部过程中像电梯向上运行，当页面返回到顶部时，会有电梯“到达”的提示音。
  - 使用场景：适用 Web 页面返回至顶部

- 推荐理由：插件的音效喜感

- 示例代码：（可选）长度：1-20 行

- 截图：
![elevator](https://user-images.githubusercontent.com/38887077/85844383-3bf43a80-b7d5-11ea-9269-21f8508a4867.gif)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 51 期](https://hellogithub.com/periodical/volume/51/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
