### ISSUE TITLE
wmathor - 营销号视频生成器（自荐项目）

### ISSUE THREAD

**Issue by wmathor** [521xueweihan/HelloGitHub#1307]
## 项目推荐
- 项目地址：https://github.com/wmathor/Rubbish-Video-Generator

- 类别：Python

- 项目后续更新计划：网页在线生成

- 项目描述：
  - 营销号视频自动生成
  - 只需简单准备视频、音频文件
  - 参数修改方便，操作简单
  - [B站讲解](https://www.bilibili.com/video/BV1Ap4y1y7o7)

- 推荐理由：营销号文本生成器很多，但是视频生成器（Python版）我是第一个。项目非常用于学习或者娱乐

- 截图：
![](https://camo.githubusercontent.com/458299eb72b29a5bc07ef01205df3b96f62ae4e3/68747470733a2f2f73312e617831782e636f6d2f323032302f30362f32372f4e633363744b2e706e6723736861646f77)

![](https://camo.githubusercontent.com/7315ff7b17a4d5134ea517ab7f2d6fed2848e3ea/68747470733a2f2f73312e617831782e636f6d2f323032302f30342f31392f4a754e4c5a442e706e67)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
