### ISSUE TITLE
html-plus-plus

### ISSUE THREAD

**Issue by ChungZH** [521xueweihan/HelloGitHub#1308]
## 项目推荐
- 项目地址：https://github.com/csb6/html-plus-plus

- 类别：C++

- 项目后续更新计划：

- 项目描述：这个库让你可以使用 C++ 模板编写 HTML。HTML 文档被表示为一个单一的、深层嵌套的类型。该库需要 C++20 编译。

- 推荐理由：有趣

- 示例代码：
```cpp
#include <iostream>
#include "html++.h"

int main()
{
  html<
    head<
      title<"Help Me.">
    >,
    body<
      h1<"The horror!">,
      p<"Someone has probably done this before, but I can see why it didn't catch on.">,
      a<"href=https://github.com/csb6/html-plus-plus", "For science">
    >
  > page;


  std::cout << page.content;

  return 0;
}
```

- 截图：（可选）gif/png/jpg

**Comment by CismonX** [comment]
This project is indeed a very interesting example of template metaprogramming in C++.

There's another interesting project using a similar paradigm, [Compile-Time RegEx](https://github.com/hanickadot/compile-time-regular-expressions), which may also interest you.

**Comment by 521xueweihan** [comment]
> This project is indeed a very interesting example of template metaprogramming in C++.
> 
> There's another interesting project using a similar paradigm, [Compile-Time RegEx](https://github.com/hanickadot/compile-time-regular-expressions), which may also interest you.

OK
