### ISSUE TITLE
链式事件流轻量级迷你 JS 库 - hubJS

### ISSUE THREAD

**Issue by lilijialiang** [521xueweihan/HelloGitHub#131]
## 项目推荐
- 项目名称：hubJS

- 项目地址：https://github.com/yyued/hub.js

- 项目语言：JavaScript

- 项目描述：仅6kb，通过简单的 API & 自由组合的链式写法，轻松订阅管理各类事件流

- 推荐理由：帮助开发者快捷地处理各类事件流

- 示例代码：
```js
import $hub from 'hub-js';

// 定义一个 “test” 监听器
$hub.listen('test', ( data ) => {
    console.log( 'test', data );
});

setInterval(( ) => {
    // 发出 “test” 事件
    $hub.emit('test', { code: 1 });
}, 1000);
```

- 截图：无

**Comment by 521xueweihan** [comment]
@JameJJ 老铁，这个项目我没看懂，交给你了。

**Comment by 521xueweihan** [comment]
您推荐的项目，已成功收录在 [HelloGitHub 第 20 期](https://hellogithub.com/volume/20/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)

最后，欢迎 Star ⭐️ 本项目，以便让更多人看到。
