### ISSUE TITLE
AR Copy Paste

### ISSUE THREAD

**Issue by africa1207** [521xueweihan/HelloGitHub#1311]
## 项目推荐
- 项目地址：https://github.com/cyrildiagne/ar-cutpaste

- 类别：Python

- 项目后续更新计划：支持更多软件

- 项目描述：
可以通过 iPhone 或者 Android 手机将真实物品从周围环境中抠出来，并粘贴到 Photoshop 中，未来还会支持其它软件。

- 推荐理由：AR抠图，自动粘贴到ps等软件中

- 截图：https://www.bilibili.com/video/BV1SK411n7rT

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 52 期](https://hellogithub.com/periodical/volume/52/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
