### ISSUE TITLE
推荐：开源屏幕阅读器 NVDA

### ISSUE THREAD

**Issue by dingpengyu** [521xueweihan/HelloGitHub#1312]
## 项目推荐
- 项目地址： [nvaccess/nvda: NVDA, the free and open source Screen Reader for Microsoft Windows](https://github.com/nvaccess/nvda)

- 类别：请从中选择（C++、Python）

- 项目后续更新计划：我主要是维护NVDA的简体中文翻译，跟随官方同步更新。有时候也会提交一些修复性质的 pull request。

- 项目描述：
  - NVDA是什么
无视觉桌面访问(NVDA)是一个免费且开放源码的微软 windows 操作系统的屏幕阅读器。 通过合成器语音或者盲文点字的反馈，方便盲人和低视力人群使用运行在 Windows 操作系统下运作的电脑。， NVDA 由 [NV Access](https://www.nvaccess.org)与社区内的其他开发者一起进行维护和开发。
主要特色包括：
支持包括 WEB 浏览器、电子邮件客户端、互联网聊天程序和 Office 套装在内的流行应用程序。
内建的语音合成气支持超过43种语言。
支持文档格式的朗读，如字体名称或大小、样式和拼写错误。
可自动朗读鼠标指向的文本，还包括用声音提示鼠标所在位置的选项。
支持许多点字显示器的实时刷新，支持带点字键盘的点字显示器的电脑盲文输入。
无需安装，可完全运行在U盘或者其他可携式媒体。
便于使用的语音安装程序。
已翻译为54种语言。
支持现代的Windows操作系统，包括32位和64位和其他衍生版本。
能够在 Windows 登录和其他安全界面运行
支持常见的辅助功能接口，如微软 Active Accessibility、Java Access Bridge、IAccessible2和UI automation(UI automation 仅支持 Windows 7和更高版本)
支持 Windows 命令提示符和控制台程序。 
  - NVDA能够用来干什么：
NVDA 可以协助盲人更好的浏览互联网，和使用office、chrome、firefox等程序……
  - 可选：可以让初学者了解微软的常见的辅助功能接口，如微软 Active Accessibility、Java Access Bridge、IAccessible2和UI automation
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：希望有更多的人了解无障碍

- 示例代码：（可选）长度：1-20 行
none
- 截图：（可选）gif/png/jpg

最后附上[NVDA中文站](https://www.nvdacn.com)地址。

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 52 期](https://hellogithub.com/periodical/volume/52/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
