### ISSUE TITLE
【Apache IoTDB】时序数据库——国产工业软件 (自荐项目)

### ISSUE THREAD

**Issue by qiaojialin** [521xueweihan/HelloGitHub#1313]
## 项目推荐

- 项目地址：
https://github.com/apache/incubator-iotdb
http://iotdb.apache.org/zh/

- 类别：

Java、数据库

- 项目后续更新计划：

主要由清华大学软件学院研究生同学维护，后续会完善单机版本，包括内存控制、多种数据合并策略、查询引擎优化、索引框架、触发器、连接池等。同时会继续开发分布式版本，包括读写路由、一致性协议、副本策略等。

- 项目描述：

Apache IoTDB（孵化中）是清华大学软件学院自主研发的时间序列数据管理引擎。IoTDB能够有效应对工业物联网领域时间序列数量多、写入频率高、数据乱序到达、秒级聚合等场景，采用查询分析一体化架构，支持 “云-端”一体化部署。读写性能超过国际主流时序数据库 InfluxDB、TimescaleDB、OpenTSDB、KairosDB等。2018年11月，经国际顶级开源基金会Apache评估和认可，IoTDB成功进入Apache孵化器，成为中国高校目前唯一主导的Apache项目。此外，IoTDB 与开源大数据软件广泛集成，如Hadoop、Spark、Flink、RocketMQ等。

官方网站有系统设计文档和使用手册，作为初学者，可以系统的学习数据库系统的完整设计和实现。在 IoTDB 社区可以与国内用户直接交流、收集需求、设计功能、性能优化，每个改进点都可以看到直接效果。还可以体验Apache开源软件的工作模式，与世界各地的开发者交流想法，也有机会成为Apache Committer、PMC等。

- 推荐理由：

亮点：不依赖外部系统、国内自主研发，支持乱序数据、重复数据写入，覆盖场景广，写入性能可达到国际开源时序数据库的十倍以上，上海地铁项目磁盘占用比原有系统提高15倍，节省硬件资源，为中国工业企业提供了一种更优的选择。

解决的痛点：现有关系数据库对表的列数有限制，不适用百万-千万级时间序列管理；key-value 数据库读写性能差；国际流行的时序数据库 InfluxDB 为集群监控设计，不适应长期历史数据管理，长期历史数据管理启动慢、聚合性能差。

- 示例代码

下载链接：http://iotdb.apache.org/zh/Download/
服务器启动方式：http://iotdb.apache.org/zh/UserGuide/V0.10.x/Server/Single%20Node%20Setup.html
客户端示例代码：https://github.com/apache/incubator-iotdb/tree/master/example

- 截图：

Cli 界面：
![image](https://user-images.githubusercontent.com/7240743/86740634-619d0180-c069-11ea-8627-56bd9a709ecd.png)

Logo：
![image](https://user-images.githubusercontent.com/7240743/86740414-374b4400-c069-11ea-8eb1-28da217f2b3f.png)

**Comment by 521xueweihan** [comment]
项目介绍写的非常好，由于月刊篇幅有限，只能节选了。棒棒哒～

**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 52 期](https://hellogithub.com/periodical/volume/52/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
