### ISSUE TITLE
MeterSphere 开源持续测试平台

### ISSUE THREAD

**Issue by KubeOperator** [521xueweihan/HelloGitHub#1316]
## 项目推荐
- 项目地址：https://github.com/metersphere/metersphere

- 类别：Java

- 项目后续更新计划：按月发布版本，具体请参考 https://github.com/metersphere/metersphere/blob/master/ROADMAP.md

- 项目描述：
  - 必写：MeterSphere 是一站式的开源企业级持续测试平台
  - 可选：MeterSphere 适应场景包括，测试跟踪、接口测试、性能测试等
  - 描述长度（不包含示例代码）: N/A

- 推荐理由：面向中国测试人员的开源项目少之又少，MeterSphere 希望能为中国测试人员必备的一款开源产品。

- 示例代码：N/A

- 截图：见下图

![image](https://user-images.githubusercontent.com/52770786/86995543-e90a8200-c1db-11ea-8ab2-614000005890.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 52 期](https://hellogithub.com/periodical/volume/52/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
