### ISSUE TITLE
[自荐项目]A search and replace chrome extension

### ISSUE THREAD

**Issue by Summer-andy** [521xueweihan/HelloGitHub#1319]
- 项目地址：https://github.com/Summer-andy/chrome-extensions-searchReplace
- 类别：javascript
- 项目后续更新计划：1.编写一套能够适配各种打包后页面的替换机制 2. 持续优化界面,提升用户体验
- 项目描述：在做产品ppt的时候,需要对某些个页面中的一些名词进行统一替换。在谷歌商店也找了一些插件,比如下载量高一点的两个插件: 1.search and replace 2. Find & Replace for Text Editing 。但是这两个插件都有问题, 第一个插件替换完文本后, 所有的按钮超链接都无法点击。第二个插件完全替换不了, 貌似也不维护了。因此我决定开发一个类似功能的插件。
- 推荐理由: 1. 上述两个插件中的问题, 此插件已全部fix, 最重要的是文本替换之后不会破坏DOM的事件绑定关系 2. 学习此项目可以快速上手一个谷歌浏览器插件的开发

![image](https://user-images.githubusercontent.com/30104912/87697347-8fe6b380-c7c4-11ea-8d9d-451088892a5c.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 52 期](https://hellogithub.com/periodical/volume/52/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
