### ISSUE TITLE
yddict - 命令行的单词查询工具

### ISSUE THREAD

**Issue by kenshinji** [521xueweihan/HelloGitHub#132]
## 项目推荐
- 项目名称： yddict

- 项目地址：https://github.com/kenshinji/yddict

- 项目语言：JavaScript

- 项目描述：一个命令行查单词的工具💻 📚

- 推荐理由：简洁，方便程序员们通过命令行查询单词，

- 示例代码：

- 截图：

![yddict](https://user-images.githubusercontent.com/1403893/32643995-d041639e-c619-11e7-8a03-ebd9a7208b97.png)

**Comment by 521xueweihan** [comment]
@kenshinji 因为时间问题没有看源码。我也做个类似的翻译工具，有几个问题欢迎讨论：
1. 使用的免费 api 还是？免费的key 有次数限制，所有用户使用一个key，还是用户自己申请？
2. 可以提供，结果目标语言的参数，以提高功能性。
3. 优化输出样式、颜色。

**Comment by kenshinji** [comment]
@521xueweihan 
1. **http get** 请求的 `dict.youdao.com`, 然后把需要的内容从返回的页面里面抓取出来，显示到console。
2. 参数，比如？ 欢迎提issue。
3. 已经有输出的颜色的选项了，还有啥更好的建议么？

**Comment by 521xueweihan** [comment]
@kenshinji 
1. 关于参数可以参考 YD  的api文档，单纯爬去网页提供的数据有限。例如：通过参数使用其他的翻译源、输出语言、发音播放？
2. 我建议的“输出样式和颜色优化”，不是单纯的字体颜色。

**Comment by iblis17** [comment]
Hi 我們有這個

https://github.com/zdict/zdict

**Comment by 521xueweihan** [comment]
@iblis17 这个很酷！

**Comment by iblis17** [comment]
@521xueweihan 多謝 :)

系列專案在這 https://github.com/zdict
