### ISSUE TITLE
【自荐】File-Engine 文件快速搜索引擎

### ISSUE THREAD

**Issue by XUANXUQAQ** [521xueweihan/HelloGitHub#1322]
## 项目推荐
- 项目地址：https://github.com/XUANXUQAQ/File-Engine

- 类别：C

- 项目后续更新计划：
进一步完善插件系统，提高搜索速度。

- 项目描述：
这是一个Windows文件搜索工具。可以快速搜索文件，定位文件位置和打开文件。速度与everything相差不大，大约是listary的两倍。   
该软件开放了插件API：https://github.com/XUANXUQAQ/File-Engine-Plugin-Template   　
API简单易懂，可以用于Java学习。

- 推荐理由：插件系统，可以解除像everything和listary那样仅支持NTFS磁盘的限制，并且速度极快。实测８０W文件只需要１５到２０秒。

- 示例代码：
```java
/**
     * When the search bar textChanged, this function will be called.
     * @param text
     * Example : When you input "&gt;examplePlugin TEST" to the search bar, the param will be "TEST"
     */
    @Override
    public void textChanged(String text) {

    }
```

- 截图：
![8PPdxS.gif](https://github.com/XUANXUQAQ/File-Engine/raw/master/%E6%BC%94%E7%A4%BA.gif)

![U8CIaQ.png](https://s1.ax1x.com/2020/07/12/U8CIaQ.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
