### ISSUE TITLE
【自荐】Java实现的Flappy Bird

### ISSUE THREAD

**Issue by kingyuluk** [521xueweihan/HelloGitHub#1323]
## 自荐项目
- 项目地址：https://github.com/kingyuluk/FlappyBird

- 类别：Java

- 项目后续更新计划：丰富玩法

- 项目描述：
  - 必写：用Java和JDK标准库实现的Flappy Bird，加入了水管类型的变化，优化了前期难度提高了后期难度
  - 可选：没有采用第三方库和游戏引擎，适合Java初学者入门编程
- 推荐理由：经典移植，完美还原，难度递增的实现

- 示例代码：

- 截图：

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 52 期](https://hellogithub.com/periodical/volume/52/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
