### ISSUE TITLE
【自荐】picbed - 简约不小气的自建图床程序

### ISSUE THREAD

**Issue by staugur** [521xueweihan/HelloGitHub#1324]
## 项目推荐

- 项目地址：https://github.com/staugur/picbed

- 文档地址：https://picbed.rtfd.vip

- 类别：Python

- 项目后续更新计划：多端聚合、分组限定、小程序等(https://github.com/users/staugur/projects/6)

- 项目描述：

  - 必写：使用Python开发的Web自建图床，轻量简洁不小气，可用于私有、公共图床，支持多存储后端、第三方扩展、多种图片上传方式。

  - 可选：

    - 作为Web图床适用于集中式图片存储展示，博客图片引用（rST、Markdown、HTML等）
	
    - 对于Flask爱好者，可以参考钩子管理器实现的可插拔扩展功能

- 推荐理由：

  - 给Python爱好者及需要图床的用户一个新选择。
  
  - 可插拔钩子扩展所需功能。程序没有？写一点代码集成吧！
  
  - 自由灵活的上传接口，多种上传方式（客户端、命令行、网页、用户脚本）

  - 用户可全网图片右键点击上传，第三方网站集成按钮一键上传等......
  
  - 丰富的全局选项以定制站点，用户级别个性设置

- 截图：

  - 首页上传
  
  ![](https://static.saintic.com/picbed/staugur/2020/07/17/1594964763285.png!small)

  - 我的图片
  
  ![](https://static.saintic.com/picbed/staugur/2020/07/17/1594964765628.png!small)

  - 后台-钩子管理
  
  ![](https://static.saintic.com/picbed/staugur/2020/07/17/1594964763129.png!small)

**Comment by 521xueweihan** [comment]
坚持做下去

非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
