### ISSUE TITLE
【自荐】✨ 高度还原微信UI的react-native 聊天组件

### ISSUE THREAD

**Issue by DaiYz** [521xueweihan/HelloGitHub#1325]
## 项目推荐
- 项目地址：
https://github.com/DaiYz/react-native-easy-chat-ui
- 类别：js

- 项目后续更新计划：添加拍一拍功能

- 项目描述：
  - react-native的聊天UI组件，UI风格类似微信，可自定义。

- 推荐理由：
     - 简单易用
     - 高度自定义
     - 支持多种消息类型
     - 样式美观

- 示例代码：
  
 ```jsx
import { ChatScreen } from 'react-native-easy-chat-ui'
class Example extends React.Component {
  state = {
     messages: []
     inverted: false,  // require   
  }

  sendMessage = (type, content, isInverted) => {
      console.log(type, content, isInverted, 'msg')
    }

  render() {
    return (
      <ChatScreen
        ref={(e) => this.chat = e}
        messageList={this.state.messages}
        androidHeaderHeight={androidHeaderHeight}
        sendMessage={this.sendMessage}
      />
    )
  }
}
```

- 截图：

<p>
<img alt="react-native-easy-chat-ui" src="https://raw.githubusercontent.com/DaiYz/react-native-easy-chat-ui/master/screenshots/1.png" width="207" height="448" />
<img alt="react-native-easy-chat-ui" src="https://raw.githubusercontent.com/DaiYz/react-native-easy-chat-ui/master/screenshots/2.png" width="207" height="448" />
<img alt="react-native-easy-chat-ui" src="https://raw.githubusercontent.com/DaiYz/react-native-easy-chat-ui/master/screenshots/3.png" width="207" height="448" />
<img alt="react-native-easy-chat-ui" src="https://raw.githubusercontent.com/DaiYz/react-native-easy-chat-ui/master/screenshots/4.png" width="207" height="448" />
<img alt="react-native-easy-chat-ui" src="https://raw.githubusercontent.com/DaiYz/react-native-easy-chat-ui/master/screenshots/5.png" width="207" height="448" />
<img alt="react-native-easy-chat-ui" src="https://raw.githubusercontent.com/DaiYz/react-native-easy-chat-ui/master/screenshots/6.png" width="207" height="448" /></p>

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
