### ISSUE TITLE
【自荐】Windows平台远程管理工具 PRemoteM

### ISSUE THREAD

**Issue by VShawn** [521xueweihan/HelloGitHub#1327]
## 项目推荐
- 项目地址：https://github.com/VShawn/PRemoteM/

- 类别：C#

- 项目后续更新计划：
   - 支持 VNC 
   - 支持FTP
   - 支持sFTP
   - ssh支持快捷指令（修改编译putty使其支持外部指令，不一定能够成功）
   - 操作逻辑优化如 ssh 启动后自动执行前置指令，ssh窗体与sFTP窗体关联，拖拽文件上传等

- 项目描述：
PRemoteM 是一款帮助你管理远程会话的小工具，它允许你进行多屏幕全屏RDP远程，也允许你在 Tab 窗体中管理、切换多个远程会话。它的快速启动器能帮助你在任何时候任何位置方便而快速地开启远程会话，省去查找服务器的烦恼。
尤其它可能是市面上唯一一款支持多显示全屏远程的 Windows 平台远程会话管理软件，其 Tab 页、远程别名、自定义图标等设计可以让用户轻松在多个远程会话间切换。开发契机是作者本人在疫情期间，需要在家用两台4k 200%缩放的显示器远程到工作站与多个服务器工作，迫于市面上没有找到一款支持多显示器全屏RDP远程的工具，于是编写了这个工具。
	- 其特性如下：
                - RDP 支持多屏幕全屏远程(测试于 **Win10 + 4k*2** 远程至 **Win2016**)
                - 基于 PuTTY 的 SSH Telnet 会话
                - Tab 页中管理远程会话
                - UI 颜色可自定义
                - 通过快捷键打开启动器，进而快速搜索查找开启会话
                - [可从 mRemoteNG 迁移会话](https://github.com/VShawn/PRemoteM#Migare-from-mRemoteNG)
                - [基于 RSA 的敏感数据保护](https://github.com/VShawn/PRemoteM#Encryption)

- 推荐理由：
1. 可能是目前唯一一款支持RDP的多屏幕全屏远程的远程管理工具；
2. 快速启动器超好用的，尤其是要经常开启关闭远程会话的时候；

<p align="center">
    <img src="https://github.com/VShawn/PRemoteM/raw/Doc/DocPic/quickstart.gif" width="300"/>
</p>

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
