### ISSUE TITLE
【自荐】程序语言与编译技术资源

### ISSUE THREAD

**Issue by shining1984** [521xueweihan/HelloGitHub#1329]
## 项目推荐
- 项目地址：https://github.com/shining1984/PL-Compiler-Resource

- 类别：其它

- 项目后续更新计划：会随着业界资料的更新，不断的更新最新的课程、书籍和内容。

- 项目描述：
 这是一个程序语言与编译技术的资料索引repo，汇总了目前世界各个大学的程序语言和编译技术的相关课程和教材，同时也收录了一些论文和比较活跃的博客。适用于所有对程序语言和编译技术感兴趣的新人，或者在这个领域工作研究的人员。

- 推荐理由：解决了很多学习程序语言和编译技术的人员不知道从哪里入手的问题，在细分领域做到了资料最全。

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
