### ISSUE TITLE
【自荐】全自动swagger转换jmx工具

### ISSUE THREAD

**Issue by Pactortester** [521xueweihan/HelloGitHub#1332]
## 项目推荐
- 项目地址：https://github.com/Pactortester/swaggerjmx

- 类别：Python

- 项目后续更新计划：
1. 根据参数规则自动生成请求参数，转换完成的jmx脚本可直接用于接口测试或者压测
2. 正在规划中...

- 项目描述：
  - swagger-ui接口文档一键生成jmx文件供jmeter使用
  - 由于接口测试脚本编写耗时，而且需要持续维护，耗时耗力，使用此工具可以一键生成接口测试脚本.

- 推荐理由：swagger-ui接口文档一键生成jmx文件供jmeter使用

- 示例代码_1：
- 可以直接访问 swagger_url (http://ip:port/v2/api-doc) 不需要登录的，使用Demo_1方式转换

```python
# -*- coding: utf-8 -*-

from swaggerjmx.convert import conversion
from swaggerjmx.settings import Settings as ST
#  swagger_url
ST.swagger_url = 'http://ip:port/v2/api-docs'
#  report_path
ST.report_path = 'jmx'
# 开始转换
conversion()

```

- 示例代码_2：
- 需要登录才能访问的，可以复制swagger_url页面上的json信息，保存json文件，使用Demo_2方式转换

```python
# -*- coding: utf-8 -*-

from swaggerjmx.convert import conversion
from swaggerjmx.settings import Settings as ST
#  swagger_url_json_path 
ST.swagger_url_json_path = 'test.json'
#  report_path
ST.report_path = 'jmx'
# 开始转换
conversion()

```

- 截图：

1. 传入红框中的swagger-ui 地址

![image](https://user-images.githubusercontent.com/29191106/88256748-a58d3900-ccee-11ea-8960-b16ed18c34c6.png)

2. 生成的jmx文件

![image](https://user-images.githubusercontent.com/29191106/88256097-de2c1300-ccec-11ea-80cb-4a2ed6e8c4e0.png)
3. jmeter中显示

![image](https://user-images.githubusercontent.com/29191106/88256407-d91b9380-cced-11ea-910b-cafaec9ae158.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
