### ISSUE TITLE
Live2D看板娘 for VSCode

### ISSUE THREAD

**Issue by RobiNexy** [521xueweihan/HelloGitHub#1334]
## 项目推荐
- 项目地址：https://github.com/iCharlesZ/vscode-live2d

- 类别：JS

- 项目后续更新计划：

- 项目描述：
  - 必写：一个简单的Live2D看板娘插件，会跟随你的鼠标动作变化，写代码累了可以逗逗她哦
  - 可选：VSCode 插件，初学者可以学到 VSCode 插件是如何开发的，以及 JS 的 Live2D 在项目中的运用
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？
一个简单的Live2D看板娘插件，会跟随你的鼠标动作变化，写代码累了可以逗逗她，功能类似程序员鼓励师；初学者可以学到 VSCode 插件是如何开发的，以及 JS 的 Live2D 在项目中的运用
- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg
![image](https://user-images.githubusercontent.com/44633884/88477781-6a506b80-cf75-11ea-8d9b-ec3b495361da.png)

**Comment by 521xueweihan** [comment]
有趣，希望持续更新迭代。

以后增加更多有趣的功能，可重新推荐。
