### ISSUE TITLE
ppshop,一个完全开源的微信小程序商城

### ISSUE THREAD

**Issue by peizhou** [521xueweihan/HelloGitHub#1335]
## 项目推荐
- 项目地址：https://github.com/peizhou/ppshop-miniprogram

- 类别：JS

- 项目后续更新计划：
采用flutter增加移动端app适配

- 项目描述：
  - 必写：这是一个基于NideShop的完整的开源微信小程序商城，重构了GUI和效率问题。完整包含了服务端，管理后台，微信小程序。
  - 可选：只需几步稍微配置下，即可完成一个小程序商城的搭建。

- 推荐理由：商城源码完全开源，部署简单，功能强大。非开发人员亦可快速搭建商城。

- 截图：商城demo二维码

![mini_qr](https://user-images.githubusercontent.com/2238176/88508888-763e3b00-d012-11ea-9996-4384204883d1.jpg)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
