### ISSUE TITLE
大屏数据展示组件库

### ISSUE THREAD

**Issue by jiaming743** [521xueweihan/HelloGitHub#1337]
## 项目推荐
- 项目地址：
大屏数据展示组件库 Vue版 http://datav.jiaminghi.com/
大屏数据展示组件库 React版 http://datav-react.jiaminghi.com/
为组件库提供图表支持的插件 http://charts.jiaminghi.com/
为Charts图表组件及组件库提供Canvas矢量图形渲染的插件 http://crender.jiaminghi.com/

- 类别：请从中选择 JavaScript

- 项目后续更新计划：

- 项目描述：
  - 必写：快速制作数据展示大屏，提供了一些常用的具有炫酷视觉效果的组件，有Vue和React两个版本
  - 可选：可以学习到如何开发一个组件库；组件库涉及SVG、Canvas及动效相关知识，炫酷又好玩

- 推荐理由：很少有专门做SVG矢量边框、装饰的库，视觉效果炫酷，文档齐全，长期维护

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
