### ISSUE TITLE
酷炫的星空聊天室

### ISSUE THREAD

**Issue by genaller** [521xueweihan/HelloGitHub#1338]
## 项目推荐
- 项目地址：https://github.com/genaller/genal-chat 

- 类别：typescript/javascript

- 项目后续更新计划：
  1. 加入用户标签
  2. 加入更多在线互动功能
  3. 适配手机端

- 项目描述：
  - 必写：聊天室项目,用来在线聊天,通过酷炫的界面和友好的交互提高用户聊天体验
  - 可选：初学者能够学到vue结合typescript的写法,nestjs的socket用法
  - 描述长度（不包含示例代码）:  本聊天室有着酷炫的界面和良好的代码规范,聊天室刷新数据持久化,1.5s内能拿到所有数据和初始化socket成功,即时改名和改头像.

- 推荐理由：代码良好,界面有趣, 有利于新人学习,系统可扩展性良好

- 截图：（可选）gif/png/jpg
![genalChat](https://user-images.githubusercontent.com/46491653/88530760-72bbab80-d034-11ea-8b1f-97e6db352829.gif)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 53 期](https://hellogithub.com/periodical/volume/53/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
