### ISSUE TITLE
[自荐] 禁漫天堂第三方, 让你轻松看本子, 你懂的~

### ISSUE THREAD

**Issue by d1y** [521xueweihan/HelloGitHub#1339]
## 项目推荐
- 项目地址：https://github.com/waifu-project/18comic

- 类别：ts

- 项目描述：
  - 必写：让你轻松看本子, 你懂的~
  - 描述长度: 基于 `uniapp` + `typescript` 开发的一个看本子的漫画 `app`

- 推荐理由：`bika` 哔咔漫画的替代品, 爱我你怕了吗~

- 截图：（可选）gif/png/jpg

|    |            |   |
|:----------:|:-------------:|:------:|
| ![](https://cdn.jsdelivr.net/gh/waifu-project/18comic-live/previews/首页.png) 首页 |  ![](https://cdn.jsdelivr.net/gh/waifu-project/18comic-live/previews/主题.png) 主题 |  ![](https://cdn.jsdelivr.net/gh/waifu-project/18comic-live/previews/我的.png) 我的 |
| ![](https://cdn.jsdelivr.net/gh/waifu-project/18comic-live/previews/漫画详情.png) 详情 |  ![](https://cdn.jsdelivr.net/gh/waifu-project/18comic-live/previews/阅读器.png) 阅读器 |  ![](https://cdn.jsdelivr.net/gh/waifu-project/18comic-live/previews/分流切换.png) 分流切换 |
| ![](https://cdn.jsdelivr.net/gh/waifu-project/18comic-live/previews/搜索.png) 搜索 |  ![](https://cdn.jsdelivr.net/gh/waifu-project/18comic-live/previews/留言区.png) 留言区 |  ![](https://cdn.jsdelivr.net/gh/waifu-project/18comic-live/previews/设置.png) 设置 |

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by NieRAutomata-cell** [comment]
漫画存在多张合一起的情况，不能观看
