### ISSUE TITLE
基于Java8的高性能Web框架

### ISSUE THREAD

**Issue by biezhi** [521xueweihan/HelloGitHub#134]
## 项目推荐

- 项目名称：Blade

- 项目地址：https://github.com/biezhi/blade

- 项目语言：Java

- 项目描述：一款简洁优雅、高性能的Web框架

- 推荐理由：代码量小，高性能，1小时上手，基于Java8

- 示例代码：

```java
public static void main(String[] args) {
    Blade.me().get("/", (req, res) -> {
        res.text("Hello Blade");
    }).start();
}
```
- 截图：

![image](https://user-images.githubusercontent.com/3849072/32689613-f5d67432-c722-11e7-943c-d95ff676efa0.png)

**Comment by 521xueweihan** [comment]
@biezhi 您推荐的项目，已成功收录在 [HelloGitHub 第 21 期](https://hellogithub.com/volume/21/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，欢迎 Star ⭐️ 本项目，以便让更多人看到。
