### ISSUE TITLE
【自荐】深度学习卷积交互工具: cnn-convoluter

### ISSUE THREAD

**Issue by pwwang** [521xueweihan/HelloGitHub#1340]
## 项目推荐
- 项目地址：https://github.com/pwwang/cnn-convoluter

- 类别：JS、机器学习

- 项目后续更新计划：
  - Probable optimizations for React usage
  - 3D visualization support (need to find a good but simple 3D engine)
  - Transposed convolution?
  - Pooling layers/Activation?
  - Loading data?

- 项目描述：
  - 一个卷积交互工具，帮助理解深度学习中卷积是如何完成的。

- 推荐理由：交互。很多工具或者动画没有交互功能

- 截图：（可选）gif/png/jpg
![cnn-convoluter](https://github.com/pwwang/cnn-convoluter/raw/master/cnn-convoluter.gif)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 53 期](https://hellogithub.com/periodical/volume/53/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
