### ISSUE TITLE
【自荐】seaweedfs 文件浏览器(seaweedfs-explorer)

### ISSUE THREAD

**Issue by sukaiyi** [521xueweihan/HelloGitHub#1346]
## 项目推荐

- 项目地址：https://github.com/sukaiyi/seaweedfs-explorer

- 类别：Java

- 项目后续更新计划：

  - 文件搜索
  - 文件预览和提取
  - 统计图表（文件大小分布，文件类型分布等）

- 项目描述：

  [Seaweedfs](https://github.com/chrislusf/seaweedfs) 是一个优秀的分布式文件存储服务程序，使用 fileId 唯一标志一个文件，这也是外部访问文件的唯一方法，但有时候文件上传之后 fileId 丢失了，而 Seaweedfs 出于安全考虑，并不支持查找 fileId ，这时便再也无法访问该文件，也无法释放该文件占用的磁盘空间，这对服务器磁盘空间造成了永久性的浪费。

  Seaweedfs Explorer 为解决这个问题而生，通过解析 Seaweedfs  的数据文件（\*.dat/\*.idx）生成已上传的文件列表

  初学者通过这个项目可以了解 Seaweedfs 文件存储的底层原理，另外项目中对于文件流的解析过程也值得借鉴。

- 推荐理由：实现了 Seaweedfs 中已上传文件的浏览

- 示例代码：

```bash
git clone git@github.com:sukaiyi/seaweedfs-explorer.git
cd seaweedfs-explorer
mvn clean package -DskipTests

# 启动 方法一
cd target
java -jar seaweedfs-explorer-1.0-SNAPSHOT-shaded.jar <seaweedfs data dir>
# 方法二 将jar包拷贝到 seaweedfs 数据目录下（dat/idx 同级目录），可省略启动参数
cd <seaweedfs data dir>
java -jar seaweedfs-explorer-1.0-SNAPSHOT-shaded.jar

# 浏览器打开 http://127.0.0.1:35672/index.html
```

- 截图：

![image-20200731230815159](https://github.com/sukaiyi/seaweedfs-explorer/raw/master/README.assets/image-20200731230815159.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
