### ISSUE TITLE
【自荐】 Java-Student-Roadmap

### ISSUE THREAD

**Issue by Xunzhuo** [521xueweihan/HelloGitHub#1349]
## 项目推荐
- 项目地址：https://github.com/Xunzhuo/Java-Student-Roadmap

- 类别：其他

- 项目后续更新计划：持续丰富和扩大项目，更加精细化。

- 项目描述：
  - 必写：大多GitHub上的路线图是针对社招而制定，为在校学生制定的Roadmap少之又少，此仓库制定针对于校招的Java应聘者的学习路线。
  - 可选：Java学习路线、Java岗位应聘
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：为在校学生制定的Roadmap少，具有针对性；针对于大的学习路线，本仓库对学生更有可学性、可操作性

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

![road1](https://user-images.githubusercontent.com/48784001/89117666-307de880-d4d2-11ea-84ce-66aed3471295.png)
![road2](https://user-images.githubusercontent.com/48784001/89117668-32e04280-d4d2-11ea-8ae6-83ae58aa91d4.png)

## 提示（提交时请删除以下内容）
> 点击上方 “Preview” 更方便地阅读以下内容，

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
