### ISSUE TITLE
NBA比赛查询终端工具

### ISSUE THREAD

**Issue by xcyf008** [521xueweihan/HelloGitHub#135]
## 项目推荐
- 项目名称：NBA Go

- 项目地址：https://github.com/xxhomey19/nba-go

- 项目语言：JavaScript

- 项目描述：可以用命令终端查看NBA比赛，包括时间表和比分情况

- 推荐理由：感觉很有意思

- 示例代码：

> 安装：npm install -g nba-go

> 查看当天：nba-go game -t

- 截图：

**Comment by JameJJ** [comment]
哈哈，这个项目确实感觉很有意思的，终端看NBA还是很潮的😂

**Comment by 521xueweihan** [comment]
@xcyf008 请根据提示删除提示信息。做一个中文版的岂不更酷？（还可以附上全场回顾的录像连接）

**Comment by xcyf008** [comment]
@521xueweihan 已删除

**Comment by 521xueweihan** [comment]
@xcyf008 您推荐的项目，已成功收录在 [HelloGitHub 第 20 期](https://hellogithub.com/volume/20/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，欢迎 Star ⭐️ 本项目，以便让更多人看到。

**Comment by xcyf008** [comment]
谢谢收藏
