### ISSUE TITLE
marktext-- 一款简单优雅的、专注于速度和可用性的开源Markdown编辑器(Linux, macOS, Windows)

### ISSUE THREAD

**Issue by corgile** [521xueweihan/HelloGitHub#1350]
## 项目推荐
- 项目地址：https://github.com/marktext/marktext

- 官网：https://marktext.app/

- 类别：其他

- 项目后续更新计划：

- 项目描述：
  - 必写：编辑markdown，融合了所有可能使用得到的语法，如常规markdown，vega图表，Latex公式等等

- 推荐理由：外观好看，功能齐全，简单易用(更多描述自己去看 README吧~)

- 示例代码：（可选）长度：1-20 行

- 截图：

![image](https://user-images.githubusercontent.com/48396880/89234083-b65a7a80-d61d-11ea-8be8-6ac1671eec78.png)

![image](https://user-images.githubusercontent.com/48396880/89234161-e9047300-d61d-11ea-8b9a-022b99edbbea.png)

**Comment by ChungZH** [comment]
#774
已推荐过，感谢。
