### ISSUE TITLE
【自荐】OpenVINO-YOLOV4系列的实现

### ISSUE THREAD

**Issue by TNTWEN** [521xueweihan/HelloGitHub#1352]
## 项目推荐
- 项目地址：https://github.com/TNTWEN/OpenVINO-YOLOV4

- 类别：机器学习

- 项目后续更新计划：OpenVINO-YOLOV3/4 速度更快，检测更稳定的优化策略，解决YOLOV3/V4在intel设备运行慢，tiny版本目标检测不稳定的痛点，让YOLO系列能在intel设备上真正落地实现，满足各类场景需求

- 项目描述：
  - OpenVINO官方暂未实现YOLOV4的支持，本项目全网率先实现对OpenVINO-YOLOV4,YOLOV4-TINY,YOLOV4-RELU的支持，可在intel CPU ,GPU,NCS2等设备运行YOLOV4

- 推荐理由：全网首发，让OpenVINO爱好者能提前体验与使用YOLOV4系列。模型转换精度与darknet下接近，甚至许多场景优于darknet，本项目获得了V4作者和Intel OpenVINO工程师的认可和关注

- 截图：
本项目OpenVINO-YOLOV4效果
![yolov4-416](https://user-images.githubusercontent.com/49018311/89701186-111a0c00-d967-11ea-97d6-4b0892dbf8ce.png)
与darknet-YOLOV4对比
![darknet-v4-416](https://user-images.githubusercontent.com/49018311/89701191-18d9b080-d967-11ea-97b9-66123953b61b.jpg)

**Comment by 521xueweihan** [comment]
感觉过于专业了，读者可能看不懂。
