### ISSUE TITLE
一个基于 Spring Boot、Shiro、 JWT、Mybatis Plus、Vue、Ant-Design-Vue 的前后端分离的插件式快速开发框架

### ISSUE THREAD

**Issue by fengbindev** [521xueweihan/HelloGitHub#1353]
# 介绍

<center><h1>EightRoes插件式开发框架</h1></center>
<center><p>一个基于 Spring Boot、Shiro、 JWT、Mybatis Plus、Vue、Ant-Design-Vue 的前后端分离的插件式快速开发框架</p></center>
<center>

</center>

::: tip

EightRoes 的开发机制是基于插件的可插拔的松耦合体系。在软件行业中普遍存在一种现象：软件企业特别是产品型的软件企业往往倾向于劝说客户去适应产品的现有功能，而比较抗拒对产品中的功能做客户化修改。这种现象的出现并不全部是修改本身的工作量的原因（大部分情况下修改的工作量实际上非常小），而在于这种修改要求软件企业为每一客户保有一个产品的版本库分支，将来对此客户的任何响应都要基于此一分支，此一分支也不便于和主版本同步演进，这就会带来比较大的管理成本。特别是熟悉此一分支的骨干人员离职之后，对于客户的服务水平将会急剧下降。

针对此一问题，EightRoes 构建了一套插件体系，并为此体系提供了基于 IDEA 的开发插件，使得客户的个性化需求通过可插拔的插件来实现。特别地，EightRoes 允许通过在插件中声明扩展点和扩展项来覆盖和扩展产品中原有的功能，但又不影响产品本身的升级。通过这种方式，每个项目只需要维护该项目特有的一个或几个插件的代码即可，项目版本库中的代码量急剧减少，代码的可读性、可维护性大增，又因为没有修改产品的核心代码，因此只需要着重测试项目相关的插件即可，测试的工作量也随之大减，从而较好地兼顾了个性化实施和管理成本两个方面。
:::

### 在线体验

**开发文档：**  [http://doc.ssrsdev.top/](http://doc.ssrsdev.top/)  **(有问题先看文档，看文档，看文档)**

预览地址：[http://www.ssrsdev.top/eightroesadmin](http://www.ssrsdev.top/eightroesadmin)

账号密码：admin / admin

### 项目源码

码云作为国内同步仓库，可解决 Github 克隆缓慢的问题，两个平台的代码都是同步更新的，按需选择

|        | 后端源码                                                                     | 前端源码                                                                                   |
| ------ | ---------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------ |
| Gitee  | [https://gitee.com/quella01/EightRoes](https://gitee.com/quella01/EightRoes) | [https://gitee.com/quella01/EightRoes-Client](https://gitee.com/quella01/EightRoes-Client) |
| Github  | [https://github.com/fengbindev/EightRoes](https://github.com/fengbindev/EightRoes) | [https://github.com/fengbindev/EightRoes-Client](https://github.com/fengbindev/EightRoes-Client) |
### 反馈交流

使用中遇到问题或者 Bug 可以在 Gitee 上提 [Issues](https://gitee.com/quella01/EightRoes/issues)

项目反馈交流群：893689646

### 加群问题

Ios 和 Mac 可能会存在加不了群的情况，请更换成 Android 或者 window 系统加入

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
