### ISSUE TITLE
【推荐】Algorithms-in-4-Steps

### ISSUE THREAD

**Issue by Xunzhuo** [521xueweihan/HelloGitHub#1355]
## 项目推荐
- 项目地址：https://github.com/Xunzhuo/Algorithms-in-4-Steps

- 类别：其他（C、C#、C++、CSS、Go、Java、JS、Kotlin、Objective-C、PHP、Python、Ruby、Swift、其它、书籍、机器学习）

- 项目后续更新计划：细化、提高学习粒度

- 项目描述：
  - 必写：Algorithms-in-4-Steps，用4步，系统性的学习算法与数据结构
  - 可选：系统性的学习算法与数据结构，无论是小白还是大佬，都有适合的内容
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？

系统性、全面性，包括算法、数据结构 大部分 知识

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

<img width="886" alt="截屏2020-08-09 下午5 32 18" src="https://user-images.githubusercontent.com/48784001/89729257-66891280-da66-11ea-98a9-7ae4c3455f3c.png">

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 53 期](https://hellogithub.com/periodical/volume/53/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
