### ISSUE TITLE
【自荐】一款在线展示个人Github 信息的单页应用: gitfolio-online

### ISSUE THREAD

**Issue by WangNingkai** [521xueweihan/HelloGitHub#1358]
## 项目推荐
- 项目地址：https://github.com/WangNingkai/gitfolio-online

- 类别：JS

- 项目后续更新计划：

  - 多主题
  - 定制化

- 项目描述：

  -  通过提供的 API 配合适当的参数，大家可以将自己的 GitHub 项目（名称、介绍、语言类型、Star / Fork 数）展示在 Web 上，界面简洁美观

- 推荐理由：适合于每个 Github 用户展示个人主页

- 截图：

![](https://cdn.jsdelivr.net/gh/wangningkai/wangningkai/assets/20200726173312.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by 521xueweihan** [comment]
一句话突出特点描述你的项目：

xxx GitHub 卡片。修改后可重复提交，下期可考虑收录
