### ISSUE TITLE
一个基于Beego开发的，能快速创建个人博客，cms 的系统

### ISSUE THREAD

**Issue by 1920853199** [521xueweihan/HelloGitHub#1359]
## 项目推荐
- 项目地址：https://github.com/1920853199/go-blog

- 类别：Go
- 项目后续更新计划：博客文章一键同步多平台

- 项目描述：
  - 必写：能快速创建个人博客，cms 的系统
  - 可选：适用于创建个人博客，cms 的系统，学习Beego框架
  - 描述长度（不包含示例代码）: 一个基于Beego开发的，能快速创建个人博客，cms 的系统

- 推荐理由：快速，简洁，门槛低

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
