### ISSUE TITLE
Java 实现的面向对象软件设计模式

### ISSUE THREAD

**Issue by JamesZBL** [521xueweihan/HelloGitHub#136]
## 项目推荐
- 项目名称：java_design_patterns

- 项目地址：https://github.com/JamesZBL/java_design_patterns

- 项目语言：Java

- 项目描述：Java 实现的面向对象软件设计模式，包括创建型模式、结构型模式和行为性模式

- 推荐理由：学习设计模式已经成为 Java 架构师的必经之路

- 示例代码：

- 截图：

**Comment by 521xueweihan** [comment]
@JamesZBL 您好，您的项目未能收录到月刊中。还望之后可以继续推荐有意思、有价值、可以让新手从中收益匪浅的项目。
