### ISSUE TITLE
Flutter Create Framework

### ISSUE THREAD

**Issue by 1467602180** [521xueweihan/HelloGitHub#1363]
## 项目推荐
- 项目地址：https://github.com/1467602180/flutter-create-framework

- 类别：其他

- 项目后续更新计划：嵌套路由，动画路由，发布-订阅模式

- 项目描述：
  - 必写：本项目是一个Flutter应用的快速搭建框架，旨在为开发者提供一个高效，方便的开发环境
  - 可选：通过flutter cli初始化的项目是个空白模板，每次新建项目的前期准备工作都让人厌烦，故写了这个框架，按照前端的开发习惯进行了规范化，且集成了很多开发必备的工具集，开发文档也完善。
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：内置了mock服务，可以撇开后端，先行开发，以及状态管理，发布订阅模式等

- 示例代码：
```dart
// Mock示例
import 'package:faker/faker.dart';

List UserInfoRole(){
  return [
    {
      "path":'/userinfo',
      "method":"GET",
      "response":{
        "status":0,
        "data":{
          "username":faker.internet.userName(),
          "email":faker.internet.email(),
          "address":faker.address.city()
        }
      }
    }
  ];
}
```

- 截图：

![image](https://user-images.githubusercontent.com/46753332/90211768-381f8480-de24-11ea-9a68-eb6e87677b89.png)

![image](https://user-images.githubusercontent.com/46753332/90211793-49689100-de24-11ea-89d8-de93cf976779.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
