### ISSUE TITLE
一本关于 LeetCode 题解的开源书

### ISSUE THREAD

**Issue by halfrost** [521xueweihan/HelloGitHub#1365]
## 项目推荐
- 项目地址：
https://github.com/halfrost/LeetCode-Go

- 类别：
Go

- 项目后续更新计划：
继续更新更多题解

- 项目描述：
这个项目是用来帮助各位开发者在 LeetCode 上做题提供解题思路和代码的。目前已经收录了 520 道题目的题解和代码，代码都已经 runtime beats 100% 了。代码全部都是用 Go 语言实现。书籍在线阅读地址 https://books.halfrost.com/leetcode

- 推荐理由：
与开发者分享 LeetCode 解题思路

- 截图：
![book](https://books.halfrost.com/leetcode/logo.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by halfrost** [comment]
@521xueweihan 可以放到“开源书籍”分类中。

谢谢大佬~

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 53 期](https://hellogithub.com/periodical/volume/53/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）

**Comment by halfrost** [comment]
谢谢大佬，微信已经加过你啦~
