### ISSUE TITLE
【自荐】第一本分享 Python 黑魔法玩法的电子文档

### ISSUE THREAD

**Issue by iswbm** [521xueweihan/HelloGitHub#1367]
## 项目推荐
- 项目地址：https://github.com/iswbm/magic-python

- 类别：Python

- 项目后续更新计划：持续更新中

- 项目描述：
  - 必写：本书是一本专门介绍 Python 黑魔法玩法的电子书。其中包括少有人知的一些 Python 冷门知识，Python Shell 的多样玩法，各种令人疯狂的 Python 炫技操作，Python 的超详细进阶知识解读，还有不断扩充完善适合所有 Python 开发者的开发技巧等等。

- 推荐理由：本书旨在向 Pythonista 介绍一个不一样的 Python，应该是市面上第一本集中介绍 Python 另类玩法的电子文档。

- 截图：
![](http://image.iswbm.com/20200816092506.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
