### ISSUE TITLE
Laravel 风格，优雅且轻量级的 Node 框架

### ISSUE THREAD

**Issue by dmpty** [521xueweihan/HelloGitHub#137]
## 项目推荐
- 项目名称：varal

- 项目地址：https://github.com/dmpty/varal

- 项目语言：JavaScript(Node)

- 项目描述：Laravel 风格，优雅且轻量级的 Node 框架

- 推荐理由：我是该项目的作者，该框架还在不断地完善中，几乎每个工作日都有 `commit` ，希望有志同道合的小伙伴一起参与进来，也欢迎大家参考学习或是给出意见反馈。

- 示例代码：

- 截图：

**Comment by 521xueweihan** [comment]
@dmpty 您好，该项目不能收录到月刊中，希望可以持续维护、迭代，让项目更具有特色。再次感谢您所推荐的项目。
