### ISSUE TITLE
【自荐】企业开发工具集，数据可视化，代码生成

### ISSUE THREAD

**Issue by sanri1993** [521xueweihan/HelloGitHub#1373]
## 项目推荐
- 项目地址：

https://gitee.com/sanri/sanri-tools-maven/

- 类别：请从中选择（C、C#、C++、CSS、Go、Java、JS、Kotlin、Objective-C、PHP、Python、Ruby、Swift、其它、书籍、机器学习）

Java

- 项目后续更新计划：

* 更多实用工具
* Vue 前端

- 项目描述：
这是一个用于企业应用开发中，像 redis , kafka 的数据无法实时查看的问题 ， 市面上大部分工具没有相应序列化工具导致查到的数据基本都是乱码，目前已经有的功能有这些

1. tools-core
   * 类加载管理 上传类 zip , class, java 文件到类加载器
   * 连接管理 创建 zookeeper, redis , database 等连接
   * 文件管理 系统的临时文件和配置文件的管理,提供临时文件下载功能 
   * 插件管理 插件注册,提供给前端可访问的插件,做了一个监控指标,根据插件点击次数和最后访问时间来排序插件
   * 数据管理 可以给 class 随机生成数据,使用正则表达式生成数据,和爬网站数据功能
2. tools-serializable
   * 提供序列化,反序列化等基础功能 
3. tools-zookeeper
   * zookeeper 连接的子节点,acl权限,节点数据,节点元数据,删除节点,写入数据
   * 路径收藏功能,方便下次直接查找
4. tools-redis
   * 集群节点展示,显示节点主机,端口,角色,父节点
   * key 列表查询,可以查询集群所有节点,hashKey 列表查询,key 的长度,ttl , type 展示
   * 查询某个 key 的数据,可以根据序列化和类加载器来直接展示成数据明文
5. tools-kafka
   * 消费组列表,删除消费组,消费组消费的主题列表,消费组消费主题某分区消费数据情况,消费组消费主题某分区附近的数据
   * 主题列表,主题尾部数据,创建主题,删除主题,模拟数据发送
   * 主题数据实时监控,brokers 列表
   * 所有的数据消费或监控都可以使用序列化配合类加载器来展示数据明文
6. tools-database
   * 数据库元数据 catalog,schema,表,列,索引,主键 查询和搜索
   * 扩展元数据 表类型(字典表,配置表,业务表),表关联关系设置,展示和搜索
   * 数据库文档生成和下载
   * 使用模板生成代码,组合模板成方案生成代码
   * 使用 sql 预览数据库数据和 excel 导出,导入 excel 数据 ,表随机数据生成 
   * nacos,diamond 等依赖于数据库的配置数据可以直接展示 
7. tools-mybatis
   * 上传 mapper 文件,配合类加载器,可以找到所有的 mapper 文件中的所有 statementId
   * 根据 statementId 可以知道当前 statementId 所必传的参数
   * 传入必传参数,和数据库连接,可以直接调用 statementId, 得到 sql 语句 ,这里的数据库连接引用数据库模块的连接名
8. tools-swagger-doc
   * 将 swagger 的文档生成更美观的文档并提供下载文档
9. tools-dubbo
   * 依赖于 zookeeper 模块,得到 dubbo 的提供者,获取提供的方法,并可以执行调用
10. tools-name
    * 想要给某个方法取名,但一下子想不到合适的名字,可以用这个工具帮你取名
    * 支持设置业务词,ik 分词,英语翻译
11. tools-soap
    * 支持 soap 调用
12. tools-websocket
    * 主要是给其它模块提供前端推送数据功能 

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？
数据可以视化，不乱码

- 相关使用截图

![首页](https://images.gitee.com/uploads/images/2020/0802/183913_ed63c782_409739.png)

![数据表工具](https://images.gitee.com/uploads/images/2020/0802/183913_5f3e433b_409739.png)

![模板代码生成](https://images.gitee.com/uploads/images/2020/0802/183913_9575d5bb_409739.png)

![kafka 消费组列表](https://images.gitee.com/uploads/images/2020/0802/183913_1531ca2e_409739.png)

![kafka 消息组消费的主题](https://images.gitee.com/uploads/images/2020/0802/183913_8b5a412e_409739.png)

![kafka 消费组消费主题分区监控](https://images.gitee.com/uploads/images/2020/0802/183914_246662b6_409739.png)

![kafka 主题管理](https://images.gitee.com/uploads/images/2020/0802/183914_2ab7e87d_409739.png)

![kafka 分区数据查看](https://images.gitee.com/uploads/images/2020/0802/183914_1154146f_409739.png)

![kafka json 数据查看](https://images.gitee.com/uploads/images/2020/0802/183914_a8ed0d1e_409739.png)

![kafka 模拟数据发送](https://images.gitee.com/uploads/images/2020/0802/183914_9d3fa961_409739.png)

![redis 数据监控](https://images.gitee.com/uploads/images/2020/0802/183914_80e3418a_409739.png)

![响应数据模拟](https://images.gitee.com/uploads/images/2020/0802/183914_6917a898_409739.png)

**Comment by 521xueweihan** [comment]
目前仅收录 GitHub 上的项目。
