### ISSUE TITLE
项目推荐 hexo-submit-urls-to-search-engine

### ISSUE THREAD

**Issue by cjh0613** [521xueweihan/HelloGitHub#1377]
## 项目推荐
- 项目地址：hexo-submit-urls-to-search-engine

- 类别：JS

- 项目后续更新计划：https://github.com/cjh0613/hexo-submit-urls-to-search-engine/projects/1

- 项目描述：

 Hexo 博客插件：主动推送Hexo博客新链接至谷歌必应百度搜索引擎，提升网站收录质量和速度。

- 推荐理由：简单易学

**Comment by 521xueweihan** [comment]
如果可以后面可以做成提高 SEO 的插件，可以再来推荐一次～
