### ISSUE TITLE
自荐项目：Sharingan

### ISSUE THREAD

**Issue by aoii103** [521xueweihan/HelloGitHub#1379]
## 项目推荐
- 项目地址：https://github.com/aoii103/Sharingan

- 类别：Python

- 项目后续更新计划：持续更新所支持站点

- 项目描述：这是一款社工工具，目前还在成长期。可根据所听提供的用户名在几百个站点中搜索其社交足迹，已经复刻了[`sherlock`](https://github.com/sherlock-project/sherlock) 的功能。本项目诣在更好的服务社工人员进行信息搜集

- 推荐理由：更好的提供社工查询能力 且 `pip install sharingan` 一键安装，`python -m sharingan XXX` 一键使用，使用快速；站点添加使用快速

- 截图：
![image](https://user-images.githubusercontent.com/22721729/90874192-f49fba00-e3d1-11ea-8883-8b46a9cb8630.png)

**Comment by 521xueweihan** [comment]
我记得我们推荐过：https://github.com/sherlock-project/sherlock 这个项目，所以您的就不推荐了。

**Comment by aoii103** [comment]
不是这个项目额




| |
oi
邮箱：aoii103@126.com
|

Signature is customized by Netease Mail Master

在2020年08月24日 20:59，削微寒 写道：

Closed #1379.

**Comment by aoii103** [comment]
老哥
Sherlock 相当于是Ping
Sharingan相当于telnet 两个不一样的呢




| |
oi
邮箱：aoii103@126.com
|

Signature is customized by Netease Mail Master

在2020年08月24日 21:01，S045pd 写道：
不是这个项目额




| |
oi
邮箱：aoii103@126.com
|

Signature is customized by Netease Mail Master

在2020年08月24日 20:59，削微寒 写道：

Closed #1379.
