### ISSUE TITLE
grainRPC

### ISSUE THREAD

**Issue by dianbaer** [521xueweihan/HelloGitHub#138]
## 项目推荐
- 项目名称：grain

- 项目地址：https://github.com/dianbaer/grain

- 项目语言：java

- 项目描述：grain是一个极简的、组件式的RPC框架，灵活且适合渐进学习，可与任何框架整合。同时包含系统通用多线程模型与消息通讯、多对多关系的分布式锁、基于Servlet的HTTP框架、基于系统通用多线程模型的Websocket框架、支持行级锁的多线程锁等组件，按需选择组件，不绑架开发者。

- 推荐理由：1、渐进的学习使用曲线。2、学会了可以超神，做网站、做游戏、做什么都行

- 示例代码：
```java
//RPC
//创建消息包
RPCTestC.Builder builder = RPCTestC.newBuilder();
builder.setName("RPC服务器你好啊");
TcpPacket pt = new TcpPacket("TEST_RPC_C", builder.build());
//RPC远程调用，返回结果
TcpPacket ptReturn = WaitLockManager.lock(session, pt);
```
```java
//分布式锁
// 获取类型为user，键值为111的锁
int lockId = DistributedLockClient.getLock("111", "user");
if (lockId == 0) {
	return;
}
/***********执行分布式锁业务逻辑开始*********/
/***********执行分布式锁业务逻辑结束*********/
// 释放类型为user，键值为111的锁
DistributedLockClient.unLock("111", "user", lockId);
```
- 截图：
项目库架构图（从线程设计->线程消息设计->TCP设计->RPC设计，不断扩展）：
![grain-framework.png](https://raw.githubusercontent.com/dianbaer/grain/master/grain-framework.png)
RPC示意图：
![rpc.jpg](https://raw.githubusercontent.com/dianbaer/grain/master/rpc.jpg)
RPC客户端流程图：
![grain-framework.png](https://raw.githubusercontent.com/dianbaer/grain/master/grain-rpc/rpc-client.png)
RPC服务器流程图：
![grain-framework.png](https://raw.githubusercontent.com/dianbaer/grain/master/grain-rpc/rpc-server.png)
分布式锁客户端流程图：
![grain-framework.png](https://raw.githubusercontent.com/dianbaer/grain/master/grain-distributedlock/distributedlock-client.png)
分布式锁服务器流程图：
![grain-framework.png](https://raw.githubusercontent.com/dianbaer/grain/master/grain-distributedlock/distributedlock-server.png)
![grain-framework.png](https://raw.githubusercontent.com/dianbaer/grain/master/thread.png)

**Comment by 521xueweihan** [comment]
@dianbaer 图画的不是很优雅 😅

**Comment by dianbaer** [comment]
上面那个图，我感觉解释的，没我画的图清晰。我的图还有线程、阻塞这些

**Comment by 521xueweihan** [comment]
@dianbaer 是的，你画的架构图是很细。

我的理解 RPC 框架是 C／S 模型，架构图以C／S模型表示可能更方便理解。第一张图可能更偏向于‘类图’

以上仅为个人建议。

**Comment by dianbaer** [comment]
我明白了，是解释问题 我改改
