### ISSUE TITLE
[飞书 Golang sdk] A fast feishu development sdk written in Golang

### ISSUE THREAD

**Issue by Ceelog** [521xueweihan/HelloGitHub#1380]
## 项目推荐
- 项目地址：https://github.com/fastwego/feishu

- 类别：Go

- 项目后续更新计划：近期刚发布，持续优化中 & 和官方接口保持同步更新

- 项目描述：
  - 飞书 Golang sdk
  - 用于快速开发飞书平台上的企业应用

- 推荐理由：
    - 快速开发，5分钟就可以搭建一套飞书应用
    - 架构简洁，和官方目录保持一致

- 示例代码：
```go
// 创建应用
App = feishu.NewApp(feishu.AppConfig{
    AppId:             "APPID",
    AppSecret:         "SECRET",
})

// 调用 api 接口
params = url.Values{}
params.Add("calendarId", "10086")
resp, err := calendar.GetCalendarById(App, params)
fmt.Println(string(resp), err)
```

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
