### ISSUE TITLE
自荐项目：leek-fund 韭菜盒子，VSCode 里也可以看股票 & 基金实时数据，做最好用的养基插件

### ISSUE THREAD

**Issue by giscafer** [521xueweihan/HelloGitHub#1381]
## 项目推荐

- 项目地址：https://github.com/giscafer/leek-fund

- 类别：TypeScript 、VSCode 插件开发

- 项目后续更新计划：v2.0.0

- 项目描述：
  - 必写：VSCode 里也可以看股票 & 基金实时数据，做最好用的养基插件。
  - 可选：VSCode 开发者，玩基金和股票的人都适用

- 推荐理由：

```

本插件具有以下特点：
- 基金涨跌（因接口原因基金数据延迟 `2 分钟` 左右）
- 股票涨跌，支持 A 股、港股、美股（实时数据）
- 左侧菜单面板
- 底部状态栏信息
- 手动刷新
- 自动刷新（每天 9~15 点之间轮询刷新数据）
- 支持升序/降序排序
- 基金实时走势图和历史走势图
- 基金排行榜
- 基金持仓信息
- 股市资金流向（沪深港通资金流向、北向资金、南向资金）
- 支持 GUI 操作新增&删除 基金 和 股票
- 通过 GUI 添加基金和股票时，支持模糊搜索匹配
- 支持 GUI 设置涨跌颜色、状态栏股票自定义等
```

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

![概览](https://raw.staticdn.net/giscafer/leek-fund/master/screenshot/overview.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 53 期](https://hellogithub.com/periodical/volume/53/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
