### ISSUE TITLE
【自荐】简化 UITableView 及 UICollectionView 使用的库：YLExtensions

### ISSUE THREAD

**Issue by YuLeiFuYun** [521xueweihan/HelloGitHub#1382]
## 项目推荐
- 项目地址：https://github.com/YuLeiFuYun/YLExtensions

- 类别：Swift

- 项目后续更新计划：

- 项目描述：通过添加扩展简化了 UITableView 及 UICollectionView 的注册及创建和配置过程。

- 推荐理由：它解决了 UITableView 及 UICollectionView 注册和配置过程不得不写很多重复代码的问题。

- 截图：
![图像2020-8-23 18.23.JPEG](https://i.loli.net/2020/08/23/1syQMD9jYJ7BrUW.jpg)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 53 期](https://hellogithub.com/periodical/volume/53/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
