### ISSUE TITLE
【自荐项目】IDEA自动生成代码插件

### ISSUE THREAD

**Issue by caofanCPU** [521xueweihan/HelloGitHub#1384]
## 项目推荐
- 项目地址：
[源码地址](https://github.com/caofanCPU/D8gerAutoCode)  
[插件地址](https://plugins.jetbrains.com/plugin/13576-d8gerautocode)

- 类别：Java

- 项目后续更新计划：
    - 自动生成代码方面, 考虑支持更多的数据库, 如MongoDB, PostgreSQL, Apache Hive
    - 工具集方面, 考虑增加Python、Shell脚本的支持, 用以完成在IDEA界面里一键测试RestAPI
    - 代码模板方面, 考虑使用Intellij代码提示功能, 支持例如Java集合的流式操作, Redis常用操作等
    - 其他, 将更多常见的重复工作剥离开来, 继续削减重复, 一键搞定

- 项目描述：
    - 基本信息: 该项目是一个[代码生成工具插件项目](https://plugins.jetbrains.com/plugin/13576-d8gerautocode), **保留小白开发专属插件的痕迹**   
    - 主体功能: 针对Java Web开发一键生成_单表_的从接口到数据库**增删改查(带分页)**代码  
    - 附加功能: **命名驼峰下划线转换,  JSON格式化,  SQL美化,  多行字符串批处理,  正则表达式功能**集结, 常用高频操作, 不用再到网站或者其他软件上, 就在你的IDEA里一键搞定  

- 推荐理由：
    - **所见即所得**
    - 主要特性: 现有Java代码生成插件是从SQL出发，反向生成数据模型对象(Mo), 在设计之初，字段难免考虑不周，命名或增减字段改动是比较频繁的, 那这就得频繁改SQL。我的观点是SQL是数据库层面的，且SQL定义会随着数据库的不同而有所差别，但是从Mo角度来看，是可确定的，于是，应该以Mo触发，生成SQL及其他代码，把关注焦点放在Mo本身。  
    - 解决痛点:  一些常用高频操作(例如字符串处理)有对应插件,  但是它们由不同开发者各自实现, 导致要安装多款插件,  因而我进行了**整合工作(思路与代码上都是独立实现)**,  以**所见即所得**为基线, 实现工具集功能 

- 截图: 
    - [使用教程](http://www.debuggerpowerzcy.top/home/2020/03/14/D8gerAutoCode%E6%8F%92%E4%BB%B6%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/)
    - [插件设计架构](https://www.processon.com/view/5e93cf41e0b34d6feaa6c483)

    ![](http://file.debuggerpowerzcy.top/power/D8King.jpg)

**Comment by caofanCPU** [comment]
@521xueweihan 
老铁觉得这插件咋样？

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 53 期](https://hellogithub.com/periodical/volume/53/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
