### ISSUE TITLE
gin框架rpc插件

### ISSUE THREAD

**Issue by xxjwxc** [521xueweihan/HelloGitHub#1388]
## 项目推荐
- 项目地址：https://github.com/xxjwxc/ginrpc

- 类别：Go

- 项目描述：
go-gin 自动参数绑定插件，简化go-gin框架注册路由方式，自动生成swagger/markdown文档。

支持对象自动注册及注解路由
自带请求参数过滤及绑定实现 binding:"required" validator
支持swagger/markdown文档导出
支持grpc/restful 访问方式

- 推荐理由：web/ rpc 框架，解放重复繁杂路由绑定工作。文档自动导出

- 示例代码：（可选）
```
type ReqTest struct {
	UserName    string `json:"user_name" binding:"required"` // 带校验方式
}

type Hello struct {
}

// Hello [grpc-go](https://github.com/grpc/grpc-go) 模式
// @Router /hello_ruter [post,get]
func (s *Hello) Hello(c *gin.Context, req ReqTest) (*ReqTest, error) {
	fmt.Println(req)
	return &req,nil
}

func main() {
	base := ginrpc.New(ginrpc.WithGroup("xxjwxc"))
	router := gin.Default()
	base.Register(router, new(Hello)) // 对象注册 like(go-micro)
	router.Run(":8080")
}
```

- 截图：

![11](https://user-images.githubusercontent.com/9114492/76700375-bc44d300-66f1-11ea-97e2-34d7669fd80a.gif)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 53 期](https://hellogithub.com/periodical/volume/53/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
