### ISSUE TITLE
【自荐】一个优质的中文博客

### ISSUE THREAD

**Issue by halfrost** [521xueweihan/HelloGitHub#1390]
## 项目推荐
- 项目地址：
https://github.com/halfrost/Halfrost-Field

- 类别：其他

- 项目后续更新计划：
分享技术文章

- 项目描述：
这是一个中文博客，分享前端和后端的技术。每篇文章内容都是干货，配图很用心。作者是前阿里巴巴资深后端工程师，日常工作语言是 Go。在进入阿里巴巴之前，做了几年前端工作。目前博客里面的所有文章总阅读量 PV 已经达到 317 W。总阅读人数 UV 81 W。文章累积总字数 57.8 W。

- 推荐理由：
技术干货分享

- 截图：

![](https://user-images.githubusercontent.com/10825609/91529921-bc9df700-e93c-11ea-90b2-302c4dd65a84.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 54 期](https://hellogithub.com/periodical/volume/54/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
