### ISSUE TITLE
【开源项目】libevent 跨平台事件驱动库

### ISSUE THREAD

**Issue by tangkai-prc** [521xueweihan/HelloGitHub#1392]
## 项目推荐
- 项目地址：github.com/libevent/libevent

- 类别：C 

- 项目后续更新计划：支持HTTP的SSL，DNS等

- 项目描述：基于事件驱动，高性能，轻量级的开源高性能事件通知库；事件驱动，高性能；轻量级，专注于网络；跨平台，支持 Windows、Linux、Mac Os等；支持多种 I/O多路复用技术， epoll、poll、dev/poll、select 和kqueue 等；支持 I/O，定时器和信号等事件；
 
- 推荐理由：基本的socket变成是阻塞/同步的，每个操作除非已经完成，出错，或者超时才会返回，这样对于每一个请求，要使用一个线程或者单独的进程去处理，系统资源没有办法支撑大量的请求。posix定义了可以使用异步的select系统调用，但是因为它采用了轮询的方式来判断某个fd是否变成active，效率不高。于是各系统就分别提出了基于异步的系统调用，例如Linux的epoll，由于在内核层面做了支持，所以可以用O(1)的效率查找到active的fd。基本上，libevent就是对这些高效IO的封装，提供统一的API，简化开发。

**Comment by ChungZH** [comment]
不要删改模板，如有无必要写的项留空即可。类别只需要写语言名字。

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 54 期](https://hellogithub.com/periodical/volume/54/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
