### ISSUE TITLE
【开源项目】大数据实践项目 - nginx 日志分析可视化

### ISSUE THREAD

**Issue by TurboWay** [521xueweihan/HelloGitHub#1393]
#  项目推荐
- 项目地址：[https://github.com/TurboWay/bigdata_practice](https://github.com/TurboWay/bigdata_practice)

- 类别：Python

- 项目描述：
  - 通过 hive 分析 nginx 日志，将分析结果通过 flask + echarts 进行可视化展示。

- 推荐理由：
   - 一个完整的大数据实践项目，希望对想入门大数据的同学可以有所帮助

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by 521xueweihan** [comment]
为什么把 hive 和 web 分开了？
是否可以考虑 hive 的查询做成任务形式（T+1），web 直接读结果而不是到处 xls，再通过 web 查看。

**Comment by TurboWay** [comment]
> 为什么把 hive 和 web 分开了？
> 是否可以考虑 hive 的查询做成任务形式（T+1），web 直接读结果而不是到处 xls，再通过 web 查看。

直接读 hive 延迟很大。如果是做成离线分析，就需要 flume + hive + mysql ，同时还要引入调度，夜间执行 hive 将分析结果存到另外的表，再导入mysql里面；如果是做成实时分析的话，还要引入 kafka +spark/flink 。这样会变得复杂化，这样一来就背离了我的初衷。因为我的本意只是想作为一个完整的数据分析项目，便于初学者仿造实践。
