### ISSUE TITLE
阿里开源中后台 ui 框架

### ISSUE THREAD

**Issue by xyyVee** [521xueweihan/HelloGitHub#1394]
## 项目推荐
- 项目地址：https://github.com/alibaba-fusion/next

- 类别：JavaScript

- 项目描述：
  - 必写：一套企业级中后台 UI 的解决方案，致力于解决设计师与前端在工作协同、产品体验一致性、开发效率方面的问题

  - 描述长度（不包含示例代码）: 你可以通过一站式协作平台灵活地定制自己的 DesignSystem，生成设计物料与代码分片到设计师的工具端 FusionCool 及开发者的工具端 Iceworks，同时保证代码和视觉稿之间的一致性。

- 推荐理由：@alifd/next 配合 Fusion Design 解决在页面开发时设计师和前端协同的问题。通过这套体系设计师可以自由的定制组件的 UI 并产出一个 npm 主题包，前端可以直接使用这个主题包不需要关注组件的还原度问题。省去了和设计师反复的去做还原度 Review 的工作量，大幅度的提高了开发效率。

- 截图：[截图](https://img.alicdn.com/tfs/TB1dF3BH4TpK1RjSZFMXXbG_VXa-1280-720.gif)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 54 期](https://hellogithub.com/periodical/volume/54/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
