### ISSUE TITLE
【自荐】YLRefreshKit：有了它，你可以删除你的刷新代码了

### ISSUE THREAD

**Issue by YuLeiFuYun** [521xueweihan/HelloGitHub#1397]
## 项目推荐

- 项目地址：https://github.com/YuLeiFuYun/YLRefreshKit

- 类别：Swift

- 项目后续更新计划：

- 项目描述：一个实现了刷新操作自动化的 Swift 库。

- 推荐理由：它实现了刷新操作的自动化，有了它，你不必再一遍遍的重复刷新代码，YLRefreshKit 会进行自动处理。

- 截图：

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
