### ISSUE TITLE
css-diner CSS选择器学习网站

### ISSUE THREAD

**Issue by kaixinbaba** [521xueweihan/HelloGitHub#1398]
## 项目推荐
- 项目地址：
git地址 ：      https://github.com/flukeout/css-diner
练习网站：    https://flukeout.github.io

- 类别：CSS

- 项目后续更新计划：

- 项目描述：
  - 必写：用来学习CSS选择器
  - 可选：通过简单的动画界面，让初学者学习CSS选择器不同的语法是如何筛选到页面的元素的
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：非常通俗，虽然右边的说明是英文的，但是这个英文 小学水平就能看懂了

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg
![image](https://user-images.githubusercontent.com/22809336/92094584-33d4fe80-ee07-11ea-9813-901d8337ebb5.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
