### ISSUE TITLE
分享自己写的一个LOL掌上助手（vue2.0版本）

### ISSUE THREAD

**Issue by arronf2e** [521xueweihan/HelloGitHub#14]
[https://github.com/arronf2e/Vue2.0LOL](https://github.com/arronf2e/Vue2.0LOL)

正在更新第二版中，希望楼主能推荐一波，开源的动力

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目 🙏。

如您推荐的项目在《HelloGithub》月刊中推荐，则会注明推荐人。**同时在此 issues 中通知您**。

再次感谢您对《HelloGithub》项目的支持！💪

**Comment by 521xueweihan** [comment]
🎉🎉🎉 
您好，Vue2.0LOL 项目已收录到 [13期](https://github.com/521xueweihan/HelloGitHub/blob/master/13/HelloGitHub13.md)，再次感谢您的支持，希望以后推荐更多好的项目。

建议：下次推荐信息更加详细些
