### ISSUE TITLE
学习flex布局小游戏网站-FLEXBOX FROGGY

### ISSUE THREAD

**Issue by kaixinbaba** [521xueweihan/HelloGitHub#1400]
## 项目推荐
- 项目地址：
github地址： https://github.com/thomaspark/flexboxfroggy
网站地址： https://flexboxfroggy.com

- 类别：CSS

- 项目后续更新计划：

- 项目描述：
  - 必写：通过让青蛙回家的小游戏让初学者知道flex布局中几个重要的属性究竟有什么用
  - 可选：CSS苦手的新手或者后端开发
  - 描述长度（不包含示例代码）: 
一共24关小游戏，通过设置flex css的属性让小青蛙回家，过程中学习

- 推荐理由：通过动画非常通俗的就能了解到flex布局的几个重要的属性，并且可以在settings中选择简体中文

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg
![image](https://user-images.githubusercontent.com/22809336/92098273-9c25df00-ee0b-11ea-9769-0fc1e3bd364c.png)

**Comment by 521xueweihan** [comment]
这个留在下期了！

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 55 期](https://hellogithub.com/periodical/volume/55/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
