### ISSUE TITLE
【自荐】mmdetection tensorrt 转换工具

### ISSUE THREAD

**Issue by grimoire** [521xueweihan/HelloGitHub#1401]
## 项目推荐
- 项目地址：https://github.com/grimoire/mmdetection-to-tensorrt

- 类别：机器学习

- 项目后续更新计划：
更多对mmdetection模型的支持，更快速度，更小显存占用

- 项目描述：
  - 必写：将mmdetection的目标检测模型转换成tensorRT推理引擎可用的格式
  - 可选：适用于对目标检测模型部署有速度需求，希望将最新的目标检测成果部署到实际项目中的人
  - 描述长度（不包含示例代码）: mmdetection是目前最好用的目标检测框架之一。但是它对于实际项目的部署依然存在一些缺陷。TensorRT是nvidia提供的深度学习推理框架，可以在gpu，jetson等nvidia推荐的计算平台上实现高速的网络推理。TensorRT自带的模型转换方法并不适用于mmdetection的目标检测模型。本项目则提供了mmdetection到TensorRT的桥梁。让各种目标检测算法也能享受到TensorRT带来的速度提升

- 推荐理由：易于使用，支持fp16/int8等多种转换形式，支持以batched input的形式输入数据，支持动态的图片输入尺寸。可以自由组合已支持的组件。可以被部署在nvidia jetson系列的开发板上，用于机器人、无人机平台的目标检测。

- 示例代码：
```python
opt_shape_param=[
    [
        [1,3,320,320],      # min shape
        [1,3,800,1344],     # optimize shape
        [1,3,1344,1344],    # max shape
    ]
]
max_workspace_size=1<<30    # some module and tactic need large workspace.
trt_model = mmdet2trt(cfg_path, weight_path, opt_shape_param=opt_shape_param, fp16_mode=True, max_workspace_size=max_workspace_size)
torch.save(trt_model.state_dict(), save_path)
```

```python
trt_model = init_detector(save_path)
num_detections, trt_bbox, trt_score, trt_cls = inference_detector(trt_model, image_path, cfg_path, "cuda:0")
```

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
