### ISSUE TITLE
【自荐】字节跳动开源图标库IconPark

### ISSUE THREAD

**Issue by AppleMonkey2019** [521xueweihan/HelloGitHub#1405]
## 项目推荐
- 项目地址：
https://github.com/bytedance/IconPark
- 类别：JS
- 项目后续更新计划：
官方图标库开源，图标数量种类持续丰富，图标库增加项目管理。进行中
- 项目描述：
  经过一年打磨，公司内NPM下载量数十万次，赋能设计师和开发者，助力业务项目效率提升的IconPark开源啦 ~~~
 IconPark提供了超过1200个高质量图标，支持在线化配置图标风格。与使用各种SVG源文件来达到换肤效果的方案不同的是，我们支持通过改变一个SVG文件的属性来变换出多种主题。并且支持跨平台导出多种图标代码库，方便您在代码中以组件的形式按需引用。
优势：
1.高质量：提供近1300图标，免费使用
2.多主题：主题任你切换，线框、填充、双色、多色（仅使用了一个SVG源文件哦）
3.跨平台：支持导出不同代码库，满足React/Vue/移动端小程序等多场景使用
4.定制化：在线定制图标样式，可以更改颜色、大小等属性进行批量换肤
5.高效率：丰富的可视化交互，方便你快速操作图标，直接拿去Sketch、PPT 中使用，复制组件代码在React/Vue/小程序等项目中去使用

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？
支持SVG属性配置，根据单一SVG源文件生成多套主题，赋能设计师和开发者，助力业务项目效率提升。在公司内得到大量使用，现在开源，希望能帮助到更多同学

- 示例代码：（可选）长度：1-20 行

| React icons | Preview | Theme |
| ---- | --- | --- |
| ```<Camera theme="outline" size="32" fill="#000000"/>``` | <img src="https://sf1-dycdn-tos.pstatp.com/obj/eden-cn/lswwheh7nupwnuhog/icons/camera_outline.png" width="100"></img> | Outline theme |
| ```<Camera theme="filled" size="32" fill="#333"/>``` | <img src="https://sf1-dycdn-tos.pstatp.com/obj/eden-cn/lswwheh7nupwnuhog/icons/camera_filled.png" width="100"></img> | Filled theme |
| ```<Camera theme="two-tone" size="32" fill={['#333' ,'#2F88FF']}/>``` | <img src="https://sf1-dycdn-tos.pstatp.com/obj/eden-cn/lswwheh7nupwnuhog/icons/camera_two-tone.png" width="100"></img> | Two-tone theme |
| ```<Camera theme="multi-color" size="32" fill={['#333' ,'#2F88FF' ,'#FFF' ,'#43CCF8']}/>``` | <img src="https://sf1-dycdn-tos.pstatp.com/obj/eden-cn/lswwheh7nupwnuhog/icons/camera_multi-color.png" width="100"></img> | Multi-color theme |
    
- 截图：
<img src="https://sf1-dycdn-tos.pstatp.com/obj/eden-cn/lswwheh7nupwnuhog/icons/icon-dance.gif"></img>

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 54 期](https://hellogithub.com/periodical/volume/54/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
