### ISSUE TITLE
【自荐】一款高自定义化照片选择框架

### ISSUE THREAD

**Issue by longitachi** [521xueweihan/HelloGitHub#1406]
## 项目推荐
- 项目地址：https://github.com/longitachi/ZLPhotoBrowser

- 类别：Swift

- 项目后续更新计划：根据issue需求，丰富更多功能

- 项目描述：高自定义化轻量级照片选择框架，支持预览/相册内拍照及录视频、拖拽/滑动选择，编辑裁剪图片/视频，支持多语言国际化等功能; 

- 推荐理由：可解决日常开发中对照片选择功能的需求

- 示例代码：
`ZLPhotoConfiguration` 该类为框架自定义配置参数类，`ZLPhotoThemeColorDeploy`该类为框架各部位颜色自定义类
```
// 使用起来非常简单
let ac = ZLPhotoPreviewSheet()
ac.selectImageBlock = { [weak self] (images, assets, isOriginal) in
    // your code
}
// 快速选择方法
ac.showPreview(animate: true, sender: self)
// 进入相册选择方法
ac.showPhotoLibrary(sender: self)
```

- 截图：部分界面效果图如下
![preview](https://user-images.githubusercontent.com/11711768/92675235-78a1ed80-f351-11ea-8a3e-43e80152baa3.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 54 期](https://hellogithub.com/periodical/volume/54/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
