### ISSUE TITLE
【自荐】微信电脑版隐身模式

### ISSUE THREAD

**Issue by tpchris1** [521xueweihan/HelloGitHub#1408]
## 项目推荐
- 项目地址：https://github.com/tpchris1/WeChat_PC_open_as_private

- 类别：其它

- 项目后续更新计划：变成一个GUI界面，模拟WeChat开启

- 项目描述：
  - 这是一个Batch file，用来将微信电脑版开启时，能够不记住上一个用户，每次都出现二维码。能够让多用户每次开启微信的时候就相当于开启了隐身模式。也不用担心自己的电脑会被别人看到你的当前账户。比起网页版，更适合多微信账户的用户使用，增加微信电脑版的隐私程度。
  - Batch File入门码，10分钟以内理解code，对于刚学batch的同学很轻松

- 推荐理由：我有多账户，不想要每次打开微信电脑版的时候，都会记住上次登录的账号，但是想要不记住账号的话，又想要使用微信PC版的功能，就要用到该插件

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
