### ISSUE TITLE
【开源项目】一个网络直播聚合平台，支持视频直播、高清电视和广播电台等观看或收听

### ISSUE THREAD

**Issue by parzulpan** [521xueweihan/HelloGitHub#1409]
- 项目地址：https://github.com/parzulpan/real-live

- Star数：300+

- 分类：Python

- 项目后续更新计划：完善后端，开发移动端和 Web 端

- 项目描述：一个网络直播聚合平台，支持视频直播、高清电视和广播电台等观看或收听。包括 Linux、MacOS、Windows 等桌面端，Android、iOS 等移动端，Web 端，后端等。采用 Qt、Vue、Flutter 等主流前端技术栈，MySQL、Redis、Kafka/RabbitMQ、Elasticsearch 等主流后端技术栈。

- 推荐理由：目前支持 36 个视频直播、59 个高清电视频道和 74 个广播电台在线观看或收听，同时也是一个比较全面前后端学习项目。

- 截图：
![视频直播](https://github.com/parzulpan/real-live/raw/dev/assets/img/%E7%9B%B4%E6%92%AD%E6%90%9C%E7%B4%A2.png)
![视频直播](https://github.com/parzulpan/real-live/raw/dev/assets/img/%E7%9B%B4%E6%92%AD%E6%90%9C%E7%B4%A2-%E6%AC%A3%E8%B5%8F.png)
![高清电视](https://github.com/parzulpan/real-live/raw/dev/assets/img/%E9%AB%98%E6%B8%85%E7%94%B5%E8%A7%86.png)
![高清电视](https://github.com/parzulpan/real-live/raw/dev/assets/img/%E9%AB%98%E6%B8%85%E7%94%B5%E8%A7%86-%E6%AC%A3%E8%B5%8F.png)
![视频直播](https://github.com/parzulpan/real-live/raw/dev/assets/img/%E5%B9%BF%E6%92%AD%E7%94%B5%E5%8F%B0.png)
![广播电台](https://github.com/parzulpan/real-live/raw/dev/assets/img/%E5%B9%BF%E6%92%AD%E7%94%B5%E5%8F%B0-%E6%AC%A3%E8%B5%8F.png)

**Comment by hapiman** [comment]
视频流来自哪里呢

**Comment by parzulpan** [comment]
> 视频流来自哪里呢

分析爬的

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 54 期](https://hellogithub.com/periodical/volume/54/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
