### ISSUE TITLE
[开源项目] Taichi - 高性能图形学编程框架

### ISSUE THREAD

**Issue by archibate** [521xueweihan/HelloGitHub#1414]
## 项目推荐
- 项目地址：https://github.com/taichi-dev/taichi

- 类别：Python

- 项目后续更新计划：添加 OpenCL 后端；合并 `@ti.kernel` 和 `@ti.func`，从而提供递归函数支持。

- 项目描述：Taichi 是一个高性能图形学编程框架，它可以将你编写的 Python 代码转换成高效的汇编代码，在多 CPU 和 GPU 上运行，相当于是在用 Python 的语法写着色器。使用 `@ti.kernel` 装饰的函数将被 Taichi 编译，在 GPU 上能够实现实时计算大规模粒子特效并渲染，解决了 Python 本身性能差，不适合图形学任务的问题。Taichi 具有多个后端，包括 CUDA, OpenGL, Metal, LLVM CPU, C CPU等，但前端却是统一的 Python，因此一个人编写的程序能和大家分享，不需要辛苦的配环境，Taichi 能自动选择当前平台支持的后端，从而在不同的电脑上都能运行同一份程序。有了它，你可以在 [88 行内实现 MLS-MPM 算法](https://github.com/taichi-dev/taichi/blob/master/examples/mpm88.py)，[99 行实现有限元弹性模拟](https://github.com/taichi-dev/taichi/blob/master/examples/fem99.py)。

- 推荐理由：解决了图形学配环境难，代码移植性差等问题，只需 `pip install taichi` 即可安装，编写的程序在Windows，Linux，OS X均可运行，降低了新手学习图形学的门槛。

- 示例代码：（可选）长度：1-20 行
```py
import taichi as ti

ti.init(arch=ti.gpu)  # 指定编译后的函数在 GPU 上执行

n = 320
pixels = ti.field(dtype=float, shape=(n * 2, n))  # 提前声明数组存储类型，大小


@ti.func  # 该函数将是被调用的过程函数
def complex_sqr(z):
    return ti.Vector([z[0]**2 - z[1]**2, z[1] * z[0] * 2])


@ti.kernel  # 该函数将被 Taichi 编译
def paint(t: float):
    for i, j in pixels:  # 最外层循环会自动并行化
        c = ti.Vector([-0.8, ti.cos(t) * 0.2])
        z = ti.Vector([i / n - 1, j / n - 0.5]) * 2
        iterations = 0
        while z.norm() < 20 and iterations < 50:  # 其他语法和原生 Python 基本一致
            z = complex_sqr(z) + c
            iterations += 1
        pixels[i, j] = 1 - iterations * 0.02


gui = ti.GUI("Julia Set", res=(n * 2, n))

for i in range(1000000):
    paint(i * 0.03)
    gui.set_image(pixels)
    gui.show()
```
更多示例：https://github.com/taichi-dev/taichi/tree/master/examples
浏览器在线运行部分示例（使用我们的 JS/WASM 后端）：https://taichi-dev.github.io/taichi.js

- 截图：（可选）gif/png/jpg
![image](https://raw.githubusercontent.com/taichi-dev/public_files/master/taichi/fractal_small.gif)

## 提示

注意：目前只支持 Python 3.6+。

> 文档

英文文档：https://taichi.readthedocs.io/en/stable
中文文档：https://taichi.readthedocs.io/zh_CN/latest

> ChangeLog (自荐项目可选，开源项目必须)

你可以在 https://github.com/taichi-dev/taichi/releases 看到我们的 Changelog

> 版权/协议 (必须)

我们使用 MIT License。

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 54 期](https://hellogithub.com/periodical/volume/54/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
