### ISSUE TITLE
[自荐] 一个旨在帮助非专业人士的运行在浏览器中的OpenPGP加密程序 

### ISSUE THREAD

**Issue by chenlhlinux** [521xueweihan/HelloGitHub#1415]
## 项目推荐
- 项目地址：
https://github.com/chenlhlinux/OpenPGP-Web
- 类别：
纯HTML + Javascript

- 项目后续更新计划：
完善文档，添加对文件和子密钥的支持

- 项目描述：
  -  帮助非专业人士使用OpenPGP加解密和签名

- 推荐理由：
现有的OpenPGP加解密对与非专业人士来说使用可能过于复杂，本程序能够更加方便非专业人士使用OpenPGP进行加解密。

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
