### ISSUE TITLE
[Open-source project] CSS Contest 

### ISSUE THREAD

**Issue by vicnicius** [521xueweihan/HelloGitHub#1416]
## 项目推荐
- 项目地址：CSS Contest

- 类别：CSS

- 项目后续更新计划：I have multiple ideas of new features like a history of winners, a page for all participants, and so on, but I'd like people interested in the project to contribute with ideas too.

- 项目描述：
  CSS is a group of open-source projects that enable a [website](https://csscontest.com) and a [repository](https://github.com/bitsofart/contest) to host a weekly CSS contest totally driven by the community. The objective of the contest is to create the piece of CSS that makes a given piece of HTML look amazing. Every week anyone with a GitHub account can participate and vote on their preferred entry.

- 推荐理由：It is a valuable tool for beginners as they can see others code and learn how to interact with open-source projects in a fun context.

**Comment by vicnicius** [comment]
Sorry for the entry in English, I hope I'm not intruding too much. Let me know if I missed something and I can edit it. I'm sure Google Translate is not that reliable. Still, I was able to grasp a good part of the project, and I want to congratulate everyone involved!

**Comment by 521xueweihan** [comment]
> Sorry for the entry in English, I hope I'm not intruding too much. Let me know if I missed something and I can edit it. I'm sure Google Translate is not that reliable. Still, I was able to grasp a good part of the project, and I want to congratulate everyone involved!

OK. I will reply as soon as possible.

**Comment by 521xueweihan** [comment]
@vicnicius 
Sorry. your project can't included in HelloGitHub.

And website: https://csscontest.com/  I can't open
