### ISSUE TITLE
【自荐】Kotlin Android  日期时间选择器，支持100%自定义UI

### ISSUE THREAD

**Issue by loperSeven** [521xueweihan/HelloGitHub#1418]
## 项目推荐
- 项目地址：https://github.com/loperSeven/DateTimePicker

- 类别：Kotlin

- 项目后续更新计划：1.即将新增常用场景时间日期选择模式；2.处理issues中即将提出的好建议及优化

- 项目描述：DateTimePicker 一个简约、漂亮的日期时间选择器，支持100%自定义UI，内置日期时间选择弹窗，基于 Google BottomSheetDialog，足够轻量。

- 推荐理由： 一个简约、漂亮的日期时间选择器，支持100%自定义UI，内置日期时间选择弹窗，基于 Google BottomSheetDialog，足够轻量。

- 示例代码：
```kotlin
 CardDatePickerDialog.builder(context)
                .setTitle("CARD DATE PICKER DIALOG")
                .setDisplayType(displayList)
                .setBackGroundModel(model)
                .showBackNow(true)
                .setDefaultTime(defaultDate)
                .setMaxTime(maxDate)
                .setMinTime(minDate)
                .setThemeColor(color)
                .showDateLabel(true)
                .showFocusDateInfo(true)
                .setLabelText("年","月","日","时","分")
                .setOnChoose("选择"){millisecond->}
                .setOnCancel("关闭") {}
                .build().show()
```

- 截图：https://github.com/loperSeven/DateTimePicker/blob/master/images/card.gif
https://github.com/loperSeven/DateTimePicker/blob/master/images/cube.gif
(https://github.com/loperSeven/DateTimePicker/blob/master/images/sta.gif
(https://github.com/loperSeven/DateTimePicker/blob/master/images/custom.gif
https://github.com/loperSeven/DateTimePicker/blob/master/images/main.gif

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 54 期](https://hellogithub.com/periodical/volume/54/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
