### ISSUE TITLE
rustlings 初学者练习rust的小项目

### ISSUE THREAD

**Issue by kaixinbaba** [521xueweihan/HelloGitHub#1419]
## 项目推荐
- 项目地址：https://github.com/rust-lang/rustlings

- 类别：Rust

- 项目后续更新计划：

- 项目描述：
  - 必写：通过一个个简单练习小demo，让初学者慢慢学习rust的语法以及一些特性
  - 可选：
  - 描述长度（不包含示例代码）: 通过简单的命令即可安装本项目，在通过自己喜欢的编辑器去修改一个个小练习，达到编译通过或者输出目标，从而学习rust

- 推荐理由：一个个小关非常简单，有种打游戏闯关的感觉和成就感

- 示例代码：
安装非常简单
```bash
git clone https://github.com/rust-lang/rustlings
cd rustlings
git checkout tags/4.0.0 # or whatever the latest version is (find out at https://github.com/rust-lang/rustlings/releases/latest)
cargo install --force --path .
```
安装完后就可以通过该命令开始练习了
```bash
rustlings watch
```

- 截图：
![image](https://user-images.githubusercontent.com/22809336/94093890-defa3600-fe50-11ea-9b49-ea98a0aa3c3d.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 54 期](https://hellogithub.com/periodical/volume/54/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
