### ISSUE TITLE
anychat

### ISSUE THREAD

**Issue by dianbaer** [521xueweihan/HelloGitHub#142]
项目推荐
- 项目名称：anychat

- 项目地址：https://github.com/dianbaer/anychat

- 体验地址：https://www.threecss.com/AnyChatClient/third-embed-demo.html

- 项目语言：java

- 项目描述：anychat是一个极简纯净的websocket聊天插件，支持对接任何身份系统，嵌入方只需提供三个API即可进行实时通讯。支持个人聊天、群聊天、上下线、查看聊天记录、离线消息推送等，服务器绝对控制权的推送机制，合理的线程设计，支持mongodb存储聊天记录，天生的嵌入式支持。

- 推荐理由：

1、合理的线程归属设计，登录、离线、断线归属线程1，其他业务归属随机线程。

2、服务器掌握绝对的控制权，消息首先推送至每个人的消费队列，每个线程再进行轮训推送消息。

3、第三方身份系统只需提供身份验证、好友列表或组织成员列表、获取组信息三个api即可完成对接，进行聊天。

4、支持嵌入式，通过iframe即可进行嵌入

5、支持聊天记录存入MongoDB，提高性能。

- 示例代码：

```javascript
<iframe src="https://ip:port/AnyChatClient/index.html?token=5ffdefd0e1104ebdbc49cc6de538b669"></iframe>
```

- 截图：
![anychat.png](https://raw.githubusercontent.com/dianbaer/anychat/master/anychat.png)
![anychat.png](https://raw.githubusercontent.com/dianbaer/anychat/master/anychatphoto.png)
![anychat.png](https://raw.githubusercontent.com/dianbaer/anychat/master/anychatflow.png)

**Comment by dianbaer** [comment]
我想知道，怎么嵌入图片呢

**Comment by 521xueweihan** [comment]
@dianbaer 
```
![GitHub Logo](/images/logo.png)
Format: ![Alt Text](url)
```
[GitHub Master markdown](https://guides.github.com/features/mastering-markdown/)

**Comment by 521xueweihan** [comment]
@dianbaer 这期 Java 项目有点多，该项目留到下期发布
