### ISSUE TITLE
[开源项目] LGBT-CN

### ISSUE THREAD

**Issue by KevinZonda** [521xueweihan/HelloGitHub#1422]
## 项目推荐

- 项目地址：<https://github.com/LGBT-CN/LGBTQIA-in-China>

- 类别：其它

- 项目后续更新计划：
  - 完善并维护
  - 推广以让更多程序员参与

- 项目描述：
  - 这是一个与 LGBT 相关的项目。虽然 LGBT 在中国是一个非常敏感的话题，但是 LGBT-CN 依旧希望借助此项目能够唤起程序员群体中对自由平等的追求。LGBT-CN 期待有更多人能够抛弃对 LGBT 本身的歧视观念，拥抱平等。

**Comment by 521xueweihan** [comment]
您好，您的项目暂时不能收录。HelloGitHub 月刊中的项目希望读者可以从中学习到技术的相关知识。再次感谢您

非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
