### ISSUE TITLE
【自荐】众安科技开源移动端 UI 组件库 Zarm

### ISSUE THREAD

**Issue by whatwewant** [521xueweihan/HelloGitHub#1423]
## 项目推荐
- 项目地址：https://github.com/ZhongAnTech/zarm

- 类别：JS

- 项目后续更新计划：
  - 业务长期应用，持续维护中；
  - 未来会考虑开源 Vue 版本，并支持小程序；

- 项目描述：
  - 众安科技基于 React、React-Native 研发的一款适用于企业级的移动端UI组件库。
  - Zarm 的命名，灵感来源于众安保险秉承的理念：做有温度的保险。
  - Zarm = za + warm，za代表“众安”，warm有“温暖”的含义，以重合的a字母为中心，各取左右两部分。
  - 追求极致的用户体验，致力于做有温度的组件库也是zarm项目发起的初衷。
  - [点击访问官网](https://zarm.design)

- 推荐理由：
  - 在众多的 React 移动端 UI 组件库中，长期维护，在众安保险业务中长期使用，积累足够业务经验；
  - 相关资源齐全，面向设计师的 Sketch 资源，面向产品的 Axure 资源；

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg
![image](https://user-images.githubusercontent.com/7463687/94402708-f4e45f80-019e-11eb-879c-7336381497a3.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by whatwewant** [comment]
@521xueweihan 违法了哪条标准？麻烦告知，感谢

**Comment by 521xueweihan** [comment]
@whatwewant 相比之下推荐了同类型另外一个项目：https://github.com/521xueweihan/HelloGitHub/issues/1445
