### ISSUE TITLE
自荐 ToolGood.Words

### ISSUE THREAD

**Issue by toolgood** [521xueweihan/HelloGitHub#1425]
## 项目推荐
- 项目地址：https://github.com/toolgood/ToolGood.Words

- 类别：C#、Java、Python、JS、Go
 
- 项目后续更新计划：优化Go语言的过滤算法

- 项目描述：
一款高性能非法词(敏感词)检测组件，附带繁体简体互换，支持全角半角互换，获取拼音首字母，获取拼音字母，拼音模糊搜索等功能

- 推荐理由： 
1）敏感词过滤速度快：
C#测试中，StringSearchEx2.ContainsAny是Regex.IsMatch效率的8.8万倍多。
使用StringSearchEx2.Replace过滤，在48k敏感词库上的过滤速度超过3亿字符每秒。（cpu i7 8750h）
2）拼音全面，包含声调
unicode范围 0x3400-0x9FD5，（C#支持部分0x20000以上的拼音）

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 55 期](https://hellogithub.com/periodical/volume/55/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
