### ISSUE TITLE
【自荐】灵活方便、易于管理的开源工单系统

### ISSUE THREAD

**Issue by lanyulei** [521xueweihan/HelloGitHub#1428]
## 项目推荐
- 项目地址：https://github.com/lanyulei/ferry

- 类别：Go

- 项目后续更新计划：

```
支持自定义用户组及部门审批。
持续优化表单和流程设计器。
增加项目的可扩展性，方便接入内部的各种系统，包括LDAP管理、人力系统、财务系统、运维系统等等。
```

- 项目描述：

```
本系统是集工单统计、任务钩子、权限管理、灵活配置流程与模版等等于一身的开源工单系统，当然也可以称之为工作流引擎。 致力于减少跨部门之间的沟通，自动任务的执行，提升工作效率与工作质量，减少不必要的工作量与人为出错率。
```

- 推荐理由：灵活的流程及模版设计，可以让工单的管理更加方便。

- 截图：

![image](https://user-images.githubusercontent.com/20027531/94657543-2e9a9f00-0334-11eb-9905-0d9150750ec6.png)

![image](https://user-images.githubusercontent.com/20027531/94657591-3eb27e80-0334-11eb-8c01-096f5c52e7c1.png)

![image](https://user-images.githubusercontent.com/20027531/94657627-496d1380-0334-11eb-8d45-1c2bee60e759.png)

![image](https://user-images.githubusercontent.com/20027531/94657748-80432980-0334-11eb-9047-a27bb55a825d.png)

![image](https://user-images.githubusercontent.com/20027531/94657770-8a652800-0334-11eb-901b-4a347c30a134.png)

![image](https://user-images.githubusercontent.com/20027531/94657653-5427a880-0334-11eb-8447-5400f4c37e78.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 55 期](https://hellogithub.com/periodical/volume/55/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
