### ISSUE TITLE
The fuck

### ISSUE THREAD

**Issue by wynter-wang** [521xueweihan/HelloGitHub#143]
## 项目推荐
- 项目名称：
thefuck
- 项目地址：
https://github.com/nvbn/thefuck
- 项目语言：
python
- 项目描述：
在Linux命令行中，当你输入的命令有错误后，直接输入fuck就可以自动执行修复后的命令
- 推荐理由：
功能强大，名称好记
- 示例代码：
无
- 截图：
![image](https://user-images.githubusercontent.com/19240391/32992446-da38d1c0-cd85-11e7-8bd1-727e61a7c05b.png)

**Comment by JameJJ** [comment]
感觉可以用一用

**Comment by franklingu** [comment]
这个的确挺好玩儿的

**Comment by 521xueweihan** [comment]
@wynter-wang  您推荐的项目，已成功收录在 [HelloGitHub 第 21 期](https://hellogithub.com/volume/21/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，欢迎 Star ⭐️ 本项目，以便让更多人看到。
