### ISSUE TITLE
【自荐】纯文本缩进式笔记插件

### ISSUE THREAD

**Issue by zwx2238** [521xueweihan/HelloGitHub#1430]
## 项目推荐
- 项目地址：https://github.com/zwx2238/TXTMindMap

- 类别：python

- 项目后续更新计划：改进UI设计

- 项目描述：
  纯文本缩进式笔记插件。在sublime修改，浏览器中查看。支持搜索和跳转。

- 推荐理由：节点上限远超传统思维导图，同时支持搜索和跳转。

- 截图：

![image](https://user-images.githubusercontent.com/61327648/94993279-5e5ed680-05c2-11eb-9553-5e181ec2939a.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
