### ISSUE TITLE
jaina

### ISSUE THREAD

**Issue by kaixinbaba** [521xueweihan/HelloGitHub#1431]
## 项目推荐
- 项目地址： https://github.com/kaixinbaba/jaina

- 类别：Python

- 项目后续更新计划：主要是bug修复及UI的改进

- 项目描述：
  - 必写：这是一个纯python编写的轻量级的zookeeper命令行交互客户端
  - 可选：在命令行下只要安装了python都可以通过一句命令进行安装，大部分情况下完爆 官方的 zkCli客户端
  - 描述长度（不包含示例代码）: 10 - 256 个字符
Jaina是一个简单好用又强大的 Zookeeper 客户端命令行工具，拥有彩色输出，自动提示，以及和类unix一样的体验.

- 推荐理由：工具最重要的就是好用，当需要从命令行去查看zk节点数据并进行增删改或者设置权限等操作时，使用jaina都非常的方便，支持的命令非常直观，基本见明知义，实在不行使用`help <command>`或者`<command> --help`都能回答如何使用。

- 示例代码：
安装
```bash
$ pip install jaina
```
使用
```bash
$ jaina -h 127.0.0.1:2181
```
文档地址 [jaina](https://jaina.readthedocs.io/zh_CN/latest/)

- 截图：（可选）gif/png/jpg
![image](https://user-images.githubusercontent.com/22809336/94993269-50a95100-05c2-11eb-83c6-b0ead21645f6.png)
![image](https://user-images.githubusercontent.com/22809336/94993289-7a627800-05c2-11eb-9b24-ae778cb48f27.png)
自动提示（粉色部分），并且针对命令历史给出提示（灰色部分）
![image](https://user-images.githubusercontent.com/22809336/94993307-98c87380-05c2-11eb-95e9-2501cbcbc70c.png)

如果你想找的是zkCli的替换品，快来试试吧

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
