### ISSUE TITLE
vue3.0-antdv项目推荐

### ISSUE THREAD

**Issue by chuzhixin** [521xueweihan/HelloGitHub#1432]
## 项目推荐
- 项目地址：https://github.com/chuzhixin/vue-admin-beautiful/tree/vue3.0-antdv

- 类别：JS

- 项目后续更新计划：
  继续推进vue3.0演化，基于ant-design-vue重新起航

- 项目描述：
  - 必写：master分支为vue2.x版本基于vue+element-ui的一套入门级vue admin框架，vue3.0-antdv分支为vue3.x版本基于vue+antdv的一套入门级vue admin框架,它同时支持电脑，手机，平板,他同时是拥有100+页面的大型vue前端单页应用,长期更新维护
  - 可选：适用于新手搭建完整的admin项目，并快速掌握vue基础知识、和组件的开发运用，保留MIT协议即可免费商用

- 推荐理由：一套代码，多端适配，同时支持电脑，手机，平板，始终基于最新依赖开发编写

- 示例代码：（可选）长度：1-20 行

```js
import Vue from "vue";
import Vuex from "vuex";

Vue.use(Vuex);
const files = require.context("./modules", false, /\.js$/);
const modules = {};

files.keys().forEach((key) => {
  modules[key.replace(/(\.\/|\.js)/g, "")] = files(key).default;
});
Object.keys(modules).forEach((key) => {
  modules[key]["namespaced"] = true;
});
const store = new Vuex.Store({
  modules,
});
export default store;

```

- 截图：（可选）gif/png/jpg

![image](https://gitee.com/chu1204505056/image/raw/master/h2.png)
![image](https://gitee.com/chu1204505056/image/raw/master/h3.png)
![image](https://gitee.com/chu1204505056/image/raw/master/h4.png)
![image](https://gitee.com/chu1204505056/image/raw/master/h5.png)
![image](https://gitee.com/chu1204505056/image/raw/master/h6.png)
![image](https://gitee.com/chu1204505056/image/raw/master/h7.png)
![image](https://gitee.com/chu1204505056/image/raw/master/h8.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
