### ISSUE TITLE
Makefile models

### ISSUE THREAD

**Issue by fanchenxinok** [521xueweihan/HelloGitHub#1434]
## 项目推荐
- 项目地址：https://github.com/fanchenxinok/Makefile_models

- 类别：C++

- 项目后续更新计划：持续维护

- 项目描述：
本项目是本人学习Makefile编写过程中总结的各种模型，Makefile可以说是嵌入式软件工程师必备的一项技能，写好Makefile将会使你的工作效率大大提升。本仓库的工程模型是一个消息传递模型，学习该工程模型在不同目录结构下的makefile的编写方法。

- 推荐理由：嵌入式开发工程师学习我的Makefile框架，里面的案例可以直接套用，提高工作效率。本人目前也一直用我的这套Makefile框架去编译自己构建的工程项目，很方便。

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
