### ISSUE TITLE
rocket-api 自荐项目

### ISSUE THREAD

**Issue by alenfive** [521xueweihan/HelloGitHub#1435]
## 项目推荐
- 项目地址：https://github.com/alenfive/rocket-api

- 类别：Java

- 项目后续更新计划：
1. 更多数据源的支持，hbase,redis等其他非关系性数据库
2.更多语言支持，比如 python,javascript,go,object-c

- 项目描述：
1. 用于快速开发API接口。不再定义`Controller`,`Service`,`Dao`,`Mybatis`,`xml`,`Entity`,`VO`等对象和方法.
2. 可视化界面，将入参自动封装到可执行的脚本上，支持所有关系性数据库SQL执行语句，非关系型`MONGODB`查询语句.
3. 完全基于springboot2.x 作为springboot项目的stater方式集成,无侵入性，新老项目都能快速集成
4. 只需编写一行代码即可完成大部分的业务需求开发，使用难度级别（测试 or 运维）也可参与开发
5. 在线动态编译，无需重启，即时生效，多数据源操作
6. 版本控制,历史记录比对，回滚等功能
7. 远程一键发布到线上环境
8. 线上POSTMAN调试,保存POSTMAN信息或三方文档的自动生成，历史调用记录存储，回塑
9. 代码提示，SQL提示，语法提示
10. 用户管理控制，安全性控制，以及历史行为记录

- 推荐理由：拒绝CRUD。用尽可能简单的方式，完成尽可能多的需求。通过约定的方式 实现统一的标准。告别加班，拒绝重复劳动，远离搬砖

- 示例代码：（可选）长度：1-20 行
```
sql = """
select * from user where id = #{id}
"""
db.pager(sql)
```

- 截图：（可选）gif/png/jpg
![image](https://user-images.githubusercontent.com/9295325/95548911-ace3f900-0a38-11eb-9d61-4cfba143e863.png)
![image](https://user-images.githubusercontent.com/9295325/95548919-b1a8ad00-0a38-11eb-8d84-96fc2cfabac4.png)

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by alenfive** [comment]
很高兴收到你的回信，
我希望知道审核标准中的具体哪一项不满足要求，这样我就能针对性的完善

1. 是否有完善的文档       ：这个是满足的 https://alenfive.gitbook.io/rocket-api/
2. Star  :   这个确实比较少，这也是我希望被HelloGitHub收录的原因，让更多的人知道
3. Insights : 目前该项目应用于8个生产环境，在我的团队中研发效率确实提升了3倍以上，项目在持续不断的优化改进 
4. Issues :  没有怎么做推广，所以知道的人少

因为项目自己做推广还是比较麻烦，希望得到回得，让我针对性的完善它



kobe96688@126.com
 
发件人： 削微寒
发送时间： 2020-10-27 17:04
收件人： 521xueweihan/HelloGitHub
抄送： monk; Author
主题： Re: [521xueweihan/HelloGitHub] rocket-api 自荐项目 (#1435)
非常感谢您推荐项目。
该项目暂不能收录到 HelloGitHub 月刊中，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。
再次感谢您对 HelloGitHub 的支持
