### ISSUE TITLE
tldr: simplified man page

### ISSUE THREAD

**Issue by franklingu** [521xueweihan/HelloGitHub#144]
## 项目推荐
- 项目名称：
tldr
- 项目地址：
https://github.com/tldr-pages/tldr
https://github.com/tldr-pages/tldr-python-client
- 项目语言：
Python
- 项目描述：
tldr是一个试图简化man page的工程，基础项目是community做的对于各种常用项目的man的简化，client有很多个，可以是python的
- 推荐理由：
man一般太长了，很多时候我们就想用一些比较常用的东西不过我们却记不起来了，这个时候如果不google，不如tldr，一般就可以发现自己想要的命令了
- 示例代码：

- 截图：
![official repo image](https://github.com/tldr-pages/tldr/raw/master/screenshot.png)

**Comment by 521xueweihan** [comment]
@franklingu 这段描述，满分💯 😄

**Comment by 521xueweihan** [comment]
[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)

**Comment by franklingu** [comment]
哈哈哈哈哈
