### ISSUE TITLE
【自荐】 fishpond 基于NLP情感分析的微信养鱼插件

### ISSUE THREAD

**Issue by FrontMage** [521xueweihan/HelloGitHub#1440]
## 项目推荐
- 项目地址：[fishpond](https://github.com/FrontMage/fishpond)

- 类别：Python、Javascript、机器学习

- 项目后续更新计划：
鱼塘看板，统计和分析鱼的情况，鱼塘报警，设置报警阈值通过邮件或者bark通知

- 项目描述：
  - 必写：用NLP分析每一条微信聊天消息，查看消息对应的情感分值
  - 可选：梗，NLP用法，微信插件写法
  - 描述长度（不包含示例代码）: 
通过tempermonkey加载js代码，在网页微信中实现监听每一条消息并给每个消息打个情感分，可以用于养鱼，也可以用于反养鱼，看到小姐姐或者小哥哥情感较低的时候可以选择对应应对策略。
- 推荐理由：NLP的实际应用

- 示例代码：

- 截图：
![image](https://user-images.githubusercontent.com/17007026/95761332-bee6c580-0cde-11eb-9ec0-771c3f3e0372.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

感谢让我发现了 snownlp，这个项目
