### ISSUE TITLE
retrofit-spring-boot-starter开源项目推荐

### ISSUE THREAD

**Issue by chentianming11** [521xueweihan/HelloGitHub#1441]
## 项目推荐
- 项目地址：https://github.com/LianjiaTech/retrofit-spring-boot-starter

- 类别：Java

- 项目后续更新计划：目前项目已经进入稳定期，后续主要会关注挖掘更多新功能的支持，持续进行迭代。

- 项目描述：
这是一个适用于Spring-boot项目的轻量级HTTP应用框架。支持接口化的方式发送HTTP请求，使用简单方便。底层使用`Retrofit`实现，并支持了诸多功能特性增强，极大简化开发。

- 推荐理由：适用于Spring-boot项目的轻量级HTTP应用框架，简单好用！让我们忘掉`RestTemplate`，一起来尝试一下！

- 示例代码：
```java
/**
* 定义接口
**/
@RetrofitClient(baseUrl = "${test.baseUrl}")
public interface HttpApi {

    @GET("person")
    Result<Person> getPerson(@Query("id") Long id);
}

/**
* 注入使用
**/
@Service
public class TestService {
    @Autowired
    private HttpApi httpApi;

    public void test() {
        // 通过httpApi发起http请求
    }
}
```

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 55 期](https://hellogithub.com/periodical/volume/55/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

**Comment by chentianming11** [comment]
感谢~



---原始邮件---
发件人: "削微寒"<notifications@github.com&gt;
发送时间: 2020年10月28日(周三) 上午10:43
收件人: "521xueweihan/HelloGitHub"<HelloGitHub@noreply.github.com&gt;;
抄送: "伍六七"<chentianming11@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [521xueweihan/HelloGitHub] retrofit-spring-boot-starter开源项目推荐 (#1441)




 
您推荐的项目，已成功发布在 HelloGitHub 第 55 期，并把您添加到了贡献者列表中。
 
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
