### ISSUE TITLE
一个基于JS的跨平台Redis图形化客户端

### ISSUE THREAD

**Issue by SekiBetu** [521xueweihan/HelloGitHub#1444]
## 项目推荐
- 项目地址：https://github.com/qishibo/AnotherRedisDesktopManager

- 类别：JS

- 项目描述：Another Redis DeskTop Manager是一款多语言多平台的redis桌面连接工具；他比起收费的RDM具有更加丰富完善的功能，且当加载大量的key时不会发生奔溃现象，以下是其功能更新日志：
2020-09-04: SSH集群支持 && 扩展指令支持
2020-06-18: SSL/TLS支持
2020-04-28：大的键支持浏览，页面缩放，自动化json
2020-04-18: 键值格式化支持
2020-04-04：集群支持！
2020-03-13：暗模式支持!!! && JsonView在其他地方
2020-02-16：SSH私钥支持
2020-02-13：在选项卡中打开Cli控制台
2019-06-14：自定义字体家族支持
2019-05-28：密钥列表可调整大小
2019-05-09：哈希列表集Zset中的搜索支持
2019-04-26：自动更新
2019-04-09：SSH隧道连接支持
2019-04-01：提取搜索支持
2019-02-22：单连接支持
2019-01-08：项目开始

- 推荐理由：比起市面上用得最多且收费的Redis DeskTop Manager，此项目的功能更加完善，界面更加美观，也不会出现RDM中的某些显示异常，且当加载大量的key时不会发生奔溃现象，适合初学者尝试使用

- 截图：
![image](https://user-images.githubusercontent.com/38283893/96224553-5407e980-0f7f-11eb-844e-d909289f75d4.png)
![image](https://user-images.githubusercontent.com/38283893/96224564-58340700-0f7f-11eb-9874-0d417e0682a8.png)
![image](https://user-images.githubusercontent.com/38283893/96224583-5f5b1500-0f7f-11eb-8d73-b2d438edad2d.png)
![image](https://user-images.githubusercontent.com/38283893/96224592-61bd6f00-0f7f-11eb-81f3-d9899b1f2c1a.png)
![image](https://user-images.githubusercontent.com/38283893/96224603-641fc900-0f7f-11eb-8e91-f48952637a79.png)
![image](https://user-images.githubusercontent.com/38283893/96224616-66822300-0f7f-11eb-8b0d-ba5289cac0ee.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 55 期](https://hellogithub.com/periodical/volume/55/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
