### ISSUE TITLE
[自荐] 小说在线转码工具

### ISSUE THREAD

**Issue by lionet1224** [521xueweihan/HelloGitHub#1446]
## 项目推荐
- 项目地址：https://github.com/lionet1224/novel-online

- 类别：Javascript

- 项目后续更新计划：使用脚手架重构，实现书城功能，优化阅读器。

- 项目描述：
  - 这是一个看小说的WebApp、可以同时获取多个不同来源的书籍数据，实现了一个简单的前端阅读器，其中实现了滚动自动加载下一章的功能，手机端左右分页的效果。
  - 没事在电脑上划水时，可以直接通过[在线体验](http://book.lionet.top)网址进行阅读。
  - 可以学习到Promise在爬虫中的应用，避免回调地狱。
  - 实现一个DOM数据处理器，通过对象配置简单快捷的获取到相对应并且处理过的数据。
  - 同时使用了redis、socket等技术，可以学习到这两项技术的简单使用。

- 截图: 

![image.png](http://blog.lionet.top:3000/images/2020_10_22/1603336840601.png)
![image.png](http://blog.lionet.top:3000/images/2020_10_22/1603336886172.png)
![image.png](http://blog.lionet.top:3000/images/2020_10_22/1603336958426.png)
![image.png](http://blog.lionet.top:3000/images/2020_10_22/1603337008622.png)
![image.png](http://blog.lionet.top:3000/images/2020_10_22/1603337029640.png)
![image.png](http://blog.lionet.top:3000/images/2020_10_22/1603337044417.png)
![image.png](http://blog.lionet.top:3000/images/2020_10_22/1603337058329.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by 521xueweihan** [comment]
注意版权问题
