### ISSUE TITLE
【自荐】懒人部署k8s集群工具 - kainstall

### ISSUE THREAD

**Issue by lework** [521xueweihan/HelloGitHub#1447]
## 项目推荐
- 项目地址：https://github.com/lework/kainstall

- 类别：其它

- 项目描述：
  快速部署一个分布式的 Kubernetes HA 集群， 使用 shell 脚本可以不借助外力直接在服务器上运行，省时省力。 并且 shell 脚本只有一个文件，文件大小不到 100 KB，非常小巧，可以实现一条命令安装集群的超快体验，而且配合离线安装包，可以在不联网的环境下安装集群，这体验真的非常爽啊。

- 推荐理由：
 一键部署集群，省时省力。文件大小不到 100 KB，非常小巧。

- 截图：
![image](https://user-images.githubusercontent.com/17396943/96405222-5b452680-120f-11eb-9d4e-afae792afca2.png)

![image](https://user-images.githubusercontent.com/17396943/96405058-fbe71680-120e-11eb-8f11-22f36f12beef.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
