### ISSUE TITLE
利用actions自动完成B站每日任务助手

### ISSUE THREAD

**Issue by srcrs** [521xueweihan/HelloGitHub#1448]
## 项目推荐
- 项目地址：https://github.com/srcrs/BilibiliTask

- 类别：Java

- 项目后续更新计划：看用户需求增加

- 项目描述：
  - 哔哩哔哩(B站)自动完成每日任务，投币，点赞，直播签到，自动兑换银瓜子为硬币，自动送出即将过期礼物，漫画App签到。
  - 用户不必要自己每天自己去完成哔哩哔哩每日任务，每天自动获得65点经验，快速升级到Lv6。

- 推荐理由：自动完成每日任务，投币，点赞，直播签到，自动兑换银瓜子为硬币，自动送出即将过期礼物，漫画App签到。
- 项目协议：Apache-2.0

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 55 期](https://hellogithub.com/periodical/volume/55/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
