### ISSUE TITLE
Provide Email Subscribe

### ISSUE THREAD

**Issue by tigercosmos** [521xueweihan/HelloGitHub#145]
This project is awesome.
Hope this weekly news can be subscribed.

**Comment by franklingu** [comment]
刚刚在码天狗周刊上读到类似的想法，有subscription是很好的提议啊

I just read from [codetengu](https://weekly.codetengu.com/issues/107#start) and a similar suggestion is made there -- a subscription would much user-friendly to keep track of updates I guess

**Comment by 521xueweihan** [comment]
好的，已增添到 TODO 列表。
