### ISSUE TITLE
[自荐]bwb

### ISSUE THREAD

**Issue by qbsz** [521xueweihan/HelloGitHub#1451]
## 项目推荐
- 项目地址：https://github.com/crqblog/bwb

- 类别：css,js

- 项目后续更新计划：添加更多好看的css设计

- 项目描述：
  - 必写：类似bootstrap，可以通过简短的代码构建网页。
  - 可选：可用于非商业化的网页开发。初学者可以学习css的结构与实例。

- `推荐理由：可以通过简短的代码构建网页。

- 示例代码：

```html
<link href="https://cdn.jsdelivr.net/gh/crqblog/bwb.js@v.1.2.x/css/style.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/gh/crqblog/bwb.js@v.1.2.x/js/plugins.js"></script>
```

```html
<div class="bar bar-warning">
...
</div>
```
### 附
更新比较频繁，需要经常更新版本

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
