### ISSUE TITLE
[自荐] Socialify 一键生成专业 GitHub 仓库头图

### ISSUE THREAD

**Issue by wei** [521xueweihan/HelloGitHub#1452]
## 项目推荐
- 项目地址：https://github.com/wei/socialify

- 类别：其他

- 项目后续更新计划：添加字体选项、背景选项

- 项目描述：
  - 必写：一键生成 GitHub 仓库头图 可用在 README、social preview image、网站等
  - 可选：很多小伙伴喜欢写 GitHub 开源项目。但是对于不会/懒的用 Photoshop 的小伙伴来说，项目推广图的设计真是很头疼。使用 Socialify 可以让你不再需要烦恼，更专注写你喜欢的代码。
  - 描述长度（不包含示例代码）: 

      > **功能：**
      > - 无需 Photoshop 设计功底即可一键自动生成 GitHub 项目推广图
      > - 直接复制 Markdown/img 代码
      > - 支持下载 png/jpg/webp 图片
      > - 可用于项目 README 和 Social Preview Image 增加被 GitHub 推广的几率
      > - 可放进项目网站的 open graph tag 内让分享项目的小伙伴可以看到你的推广图
      > - 可放进同名 README 项目并在主页展示
      > - 任何其他推广项目的使用场景
      > - 支持 Dark Theme

- 推荐理由：很多小伙伴喜欢写 GitHub 开源项目。但是对于不会/懒的用 Photoshop 的小伙伴来说，项目图的设计真是很头疼。使用 Socialify 可以让你不再需要烦恼，更专注写你喜欢的代码。

- 示例代码：前往 https://socialify.git.ci 即可

- 截图：**（ℹ️ 点击可编辑）**

[![socialify](https://user-images.githubusercontent.com/5880908/97212747-30bb1680-1797-11eb-877b-240abcb33ea3.png)](https://socialify.git.ci/wei/socialify?description=1&font=Raleway&issues=1&language=1&pattern=Charlie%20Brown&pulls=1&stargazers=1&theme=Light)

[![examples](https://user-images.githubusercontent.com/5880908/97212918-6102b500-1797-11eb-8f63-5b2900d31e05.png)](https://github.com/wei/socialify#examples)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 x 期](https://hellogithub.com/periodical/volume/55/，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
