### ISSUE TITLE
[自荐] Zealot - 移动应用上传下载竟然如此简单、移动 App 应用分发系统 

### ISSUE THREAD

**Issue by icyleaf** [521xueweihan/HelloGitHub#1454]
## 项目推荐

- 项目地址：https://github.com/getzealot/zealot

- 类别：Ruby on Rails

- 项目后续更新计划：根据公司项目和 Issues 持续维护更新

- 项目描述：

移动应用上传竟然如此简单、解放开发打包的烦恼，轻松放权给测试、产品、运营等使用 App 的人员，提供丰富组件库，打包流程一键上传，iOS 和 Android 轻松接入，深度与 Jenkins 和 Gitlab 集成，更多查看文档：https://zealot.ews.im

- 推荐理由：

 支持 iOS 和 Android 应用的上传和下载
 支持应用创建各种类型（Debug、AdHoc、Enterprise、Release）和渠道（小米、华为、Oppp、Vivo、应用宝等）
 支持 iOS dSYM 和 Android Progruard 文件的备份管理和解析
 支持单次上传解析 iOS、Android 包甚至是 mobileprovision 文件的信息
 支持自定义网络钩子（WebHooks）发送给通知各种服务（钉钉、企业微信、Slack 等）
 支持获取 iOS 设备 UDID 及显示支持安装的应用
 支持 OAuth 认证登录（目前以接入 Google，LDAP）
 提供检查新版本和安装服务的 iOS 和 Android 组件
 提供 fastlane 插件 zealot 提供上传应用和调试文件服务
 可接入 Gitlab 服务直接挂钩源码管理
 支持丰富的 REST APIs
 支持 Docker 一键部署

- 截图：

![main](https://zealot.ews.im/_media/screenshot/product-1.png)

![app](https://zealot.ews.im/_media/screenshot/product-3.png)

![debug file](https://zealot.ews.im/_media/screenshot/product-4.png)

![teardown](https://zealot.ews.im/_media/screenshot/product-5.png)

![udid](https://zealot.ews.im/_media/screenshot/product-6.png)

**Comment by 521xueweihan** [comment]
“移动应用上传竟然如此简单、解放开发打包的烦恼，轻松放权给测试、产品、运营等使用 App 的人员，提供丰富组件库，打包流程一键上传，iOS 和 Android 轻松接入，深度与 Jenkins 和 Gitlab 集成，更多查看文档：https://zealot.ews.im”

这是它的功能和亮点。请补充描述这是个什么东西。

**Comment by icyleaf** [comment]
抱歉，我重新编辑了下项目描述。请重新 review，感谢
