### ISSUE TITLE
自荐-利用github actions的贴吧自动签到小工具

### ISSUE THREAD

**Issue by srcrs** [521xueweihan/HelloGitHub#1459]
## 项目推荐
- 项目地址：https://github.com/srcrs/TiebaSignIn

- 类别：Java

- 项目后续更新计划：看用户的需求

- 项目描述：每日自动进行贴吧签到的小工具，用的是手机端的接口，获得的经验更多

- 推荐理由：每日自动进行贴吧签到的小工具，解放双手，支持运行结果推送至微信（通过server酱）

![](https://github.com/srcrs/TiebaSignIn/blob/master/assets/%E8%BF%90%E8%A1%8C%E7%BB%93%E6%9E%9C.gif?raw=true)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
