### ISSUE TITLE
中文繁简转换库 PHP 

### ISSUE THREAD

**Issue by wizarot** [521xueweihan/HelloGitHub#146]
## 项目推荐
- 项目名称：中文繁简转换库 zh_gb_convert 

- 项目地址：https://github.com/wizarot/zh_gb_convert

- 项目语言：PHP

- 项目描述：一个简单的繁体简体中文互相转换库.没什么技术难度.但是长处在于方便. 不需要额外安装任何其它东西,也无法完成分词之类复杂转换. 但是应付一下简单需求也够了啊! 之前在github上没找到类似的,所以自己写了一个.简单到一目了然. 实在不会看下readme.md 或者示例代码都可以.

- 推荐理由：简单方便.

- 示例代码：
```
<?php
$s2t_dict = json_decode( file_get_contents('s2t.json') , true);
$t2s_dict = json_decode( file_get_contents('t2s.json') , true);
$str = '测试简体中文转换为繁体';
echo str_replace( array_keys($s2t_dict), array_values($s2t_dict), $str);
$str = '繁體中文轉化為簡體中文,測試';
echo str_replace( array_keys($t2s_dict), array_values($t2s_dict), $str);
```

**Comment by 521xueweihan** [comment]
您好，您的项目未能收录到月刊中。还望之后可以继续推荐有意思、有价值、可以让新手从中收益匪浅的项目。
