### ISSUE TITLE
[开源项目] vue-luck-draw 基于 vue2 / vue3 的大转盘 / 九宫格抽奖插件

### ISSUE THREAD

**Issue by buuing** [521xueweihan/HelloGitHub#1460]
## 项目推荐

- 项目地址：https://github.com/LuckDraw/vue-luck-draw

- 类别：JS

- 项目后续更新计划：

  - 使用 ts 抽离逻辑代码扩展 `原生js / react` 插件
  - 增加更多抽奖类型, 如老虎机抽奖等...
  - 增加更多可配置属性, 以及更多缓动函数...

- 项目描述：

  - 描述：目前是一个支持 `vue2.x / vue3.x` 的 `大转盘 / 九宫格` 抽奖插件（**后续会扩展其他框架：react / angular**）
  - 特点： `奖品 / 文字 / 图片 / 颜色 / 按钮` 均可自由配置，支持 `同步 / 异步` 抽奖，中奖概率 `前 / 后端` 可控，可自动根据 `dpr` 调整清晰度并搭配 `rem` 属性适配移动端

- 推荐理由：

  - 通常在公司里大部分类似的抽奖需求都要的很急，但是现在又没有一个`功能完善且靠谱`的抽奖插件来帮助我们，所以我开发了这款基于`canvas`的抽奖插件，可以仅通过简单的配置`快速实现`产品需求

- 示例代码：

**浏览器在线Demo：https://100px.net/demo/wheel/ymc.html**

```vue
<template>
  <LuckyWheel
    style="width: 310px; height: 310px"
    ref="LuckyWheel"
    :prizes="prizes"
    :default-style="defaultStyle"
    :blocks="blocks"
    :buttons="buttons"
    @start="startCallBack"
    @end="endCallBack"
  />
</template>

<script>
export default {
  data () {
    return {
      prizes: [],
      defaultStyle: {
        fontColor: '#d64737',
        fontSize: '16px'
      },
      blocks: [
        { padding: '13px', background: '#d64737' }
      ],
      buttons: [
        { radius: '50px', background: '#d64737' },
        { radius: '45px', background: '#fff' },
        { radius: '41px', background: '#f6c66f', pointer: true },
        {
          radius: '35px', background: '#ffdea0',
          fonts: [{ text: '开始\n抽奖', fontSize: '20px', top: '-20px' }]
        }
      ],
    }
  },
  mounted () {
    this.getPrizesList()
  },
  methods: {
    getPrizesList () {
      this.prizes = []
      let data = ['1元红包', '100元红包', '0.5元红包', '2元红包', '10元红包', '50元红包', '0.3元红包', '5元红包']
      data.forEach((item, index) => {
        this.prizes.push({
          title: item,
          background: index % 2 ? '#f9e3bb' : '#f8d384',
          fonts: [{ text: item, top: '20%' }],
        })
      })
    },
    startCallBack () {
      this.$refs.LuckyWheel.play()
      setTimeout(() => {
        this.$refs.LuckyWheel.stop(Math.random() * 8 >> 0)
      }, 3000)
    },
    endCallBack (prize) {
      alert(`恭喜你获得${prize.title}`)
    },
  }
}
</script>
```

## 提示

> 文档

- https://100px.net

> ChangeLog

- https://github.com/LuckDraw/vue-luck-draw/releases

> 版权/协议 (必须)

- BSD-3-Clause License

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 56 期](https://hellogithub.com/periodical/volume/56/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
