### ISSUE TITLE
freenom域名自动续期

### ISSUE THREAD

**Issue by lxyok** [521xueweihan/HelloGitHub#1461]
## 项目推荐
- 项目地址：https://github.com/luolongfei/freenom

- 类别：PHP

- 项目后续更新计划：遇到任何问题或 Bug 欢迎提 issues （请按模板格式提issues，以便作者更快复现你的问题）， 如果Freenom改变算法导致此项目失效，请提 issues 告知，我会及时修复，本项目长期维护。 欢迎star~

- 项目描述：
  - 必写：白piao了freenom的免费域名，有时候忘记续期，这个自动续期项目解决烦恼。支持Github Actions部署（又是白piao）

- 推荐理由：freenom提供免费顶级域名，不过需要每年续期，每次续期最多一年。如果申请了多个然后时间又不相同续期就比较麻烦。而这个项目部署一次后等你的免费域名快到期的时候就会自动帮你续期。

- 截图：![](https://camo.githubusercontent.com/cd7ceb6359fc7c375c132a243424fbc8d56aebf1/68747470733a2f2f73322e617831782e636f6d2f323032302f30312f33312f3133395272642e706e67)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by luolongfei** [comment]
旧版仓库因为前期的github actions事件被封锁，新项目已经迁移到 https://github.com/luolongfei/next-freenom

依然长期维护。
