### ISSUE TITLE
网易云音乐升级全家桶netease-cloud

### ISSUE THREAD

**Issue by lxyok** [521xueweihan/HelloGitHub#1462]
## 项目推荐
- 项目地址：https://github.com/ZainCheung/netease-cloud

- 类别：Python

- 项目后续更新计划：

- 项目描述：
  - 必写：网易云音乐升级，自动签到听歌每天自动升级

- 推荐理由：每天自动升级，任务进度推送到微信，自定义网易云日推风格，支持云函数。

- 截图：![](https://gitee.com/ligedone/pic/raw/ov/img/20201103151144.png)

- 项目协议：MIT License

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
