### ISSUE TITLE
Game of Life

### ISSUE THREAD

**Issue by Futrime** [521xueweihan/HelloGitHub#1466]
## 项目推荐
- 项目地址：
https://github.com/Futrime/Game-of-Life
https://gitee.com/futrime/Game-of-Life

- 类别：请从中选择（C、C#、C++、CSS、Go、Java、JS、Kotlin、Objective-C、PHP、Python、Ruby、Swift、其它、书籍、机器学习）
JS

- 项目后续更新计划：
还没想到，希望能有人提提issue

- 项目描述：
  - 必写：这是个什么项目、能用来干什么、有什么特点或解决了什么痛点
  - 可选：适用于什么场景、能够让初学者学到什么
  - 描述长度（不包含示例代码）: 10 - 256 个字符
超有趣的康威生命游戏(Game of Life)实现，聚合了官网wiki所有的样式，调节控制方便，应该还没找到完善程度相当的其它web实现。可以成为初学者接触Web Canvas开发的敲门砖。

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？

可以调节地图大小、演算速度等，并且避免了大部分类似repo偏向于演示的问题。

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

## 提示（提交时请删除以下内容）
> 点击上方 “Preview” 更方便地阅读以下内容，

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
@Futrime 请按照要求提交描述，并删除无用信息。修改后可以@我
