### ISSUE TITLE
TerminalMenus.jl

### ISSUE THREAD

**Issue by iblis17** [521xueweihan/HelloGitHub#147]
- Project： TerminalMenus.jl 

- Project URL: https://github.com/nick-paul/TerminalMenus.jl

- Language：Julia

- Description："TerminalMenus.jl enables small, low-profile interactive menus in the terminal."

- Reason: 這是個簡單而且精巧的 interactive menu，而且 Pkg3.jl 將會使用這個套件。 作者同時也有在 README 底下有列了一些 TODO。

- Sample Code: (from README)
```julia
using TerminalMenus

options = ["apple", "orange", "grape", "strawberry",
            "blueberry", "peach", "lemon", "lime"]
menu = RadioMenu(options, pagesize=4)
choice = request("Choose your favorite fruit:", menu)
```
-  Snapshot: from README
![](https://camo.githubusercontent.com/9e41018ea28088020229b8e9b48fcaf15ff8c416/687474703a2f2f6e7061756c2e636f2f66696c65732f5465726d696e616c4d656e75732d64656d6f2e676966)

**Comment by 521xueweihan** [comment]
@iblis17 请根据模板填写并提供更多信息。

**Comment by iblis17** [comment]
這樣可以嗎？

**Comment by 521xueweihan** [comment]
@iblis17 可以

**Comment by 521xueweihan** [comment]
@iblis17 您好，由于推荐的 Julia 语言项目过少，该项目暂时不能收入到月刊中，如后续推荐的项目足够出刊，会再考虑。再次感谢推荐项目 😁
