### ISSUE TITLE
[自荐]srpc--搜狗自研RPC系统

### ISSUE THREAD

**Issue by holmes1412** [521xueweihan/HelloGitHub#1470]
## 项目推荐
- 项目地址：https://github.com/sogou/srpc

- 类别：C++

- 项目后续更新计划：搜狗公司自研RPC系统，内部版与开源版持续同步更新

- 项目描述：
``srpc``是搜狗基于C++ Workflow的自研RPC系统，与thrift/brpc是协议与IDL均互通的，且完美兼容workflow其他功能。``srpc``除了自带的sogou-std协议以外，还实现了baidu-std协议和thrift framed协议，因此``srpc``可以与thrift或brpc（连接池模式）互通。另外，接口描述文件支持protobuf和thrift，这意味着用户不仅可以一键迁移基于protobuf或thrift作为IDL的项目，还可以用``srpc``作为一个性能更优的thrift框架或者brpc框架，是一个既可以用于实际生产环境，又适合学习RPC原理的C++ RPC核心系统。

- 推荐理由：
  1. 高性能、低门槛，可使用HTTP+JSON跨语言；
  2. 与thrift/brpc协议兼容；
  3. protobuf/thrift IDL一键迁移；
  4. 自解析thrift和protobuf service部分的IDL，进行代码生成；
  5. 与workflow互通、可使用workflow的其他功能包括服务治理、计算调度、异步文件IO等；
  6. 内部架构精巧，协议、数据布局、IDL序列化、压缩等各层解耦，整体核心代码量仅1w行。

- 示例代码：
```cpp
class ExampleServiceImpl : public Example::Service
{
public:
    void Echo(EchoRequest *request, EchoResponse *response, RPCContext *ctx) override
    {
        response->set_message("Hi, " + request->name());
    }
};

int main()
{
    SRPCHttpServer server;
    ExampleServiceImpl impl;
    server.add_service(&impl);
    server.start(1412);
    pause();
    server.stop();
    return 0;
}
```
可使用HTTP+JSON访问：
```cpp
curl 127.0.0.1:1412/Example/Echo -H 'Content-Type: application/json' -d '{message:"from curl",name:"CURL"}'
```

- 截图：
<img width="609" alt="image" src="https://user-images.githubusercontent.com/1880011/98439273-c0fc4280-212b-11eb-90ab-9d6496264058.png">

<img width="892" alt="image" src="https://user-images.githubusercontent.com/1880011/98439241-7b3f7a00-212b-11eb-9546-2262efc1f285.png">

- 其他参考：https://www.infoq.cn/article/F3ziH6mIqfUHm9K7xvz9

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 56 期](https://hellogithub.com/periodical/volume/56/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
