### ISSUE TITLE
自荐 - 内建完整微服务治理能力的web & rpc微服务框架 go-zero

### ISSUE THREAD

**Issue by kevwan** [521xueweihan/HelloGitHub#1471]
## 项目推荐
- 项目地址：https://github.com/tal-tech/go-zero

- 类别：Go

- 项目后续更新计划：内外同源，积极更新

- 项目描述：
  - 集成了各种工程实践的 web 和 rpc 框架。通过弹性设计保障了大并发服务端的稳定性，经受了充分的实战检验。
  - 包含极简的 API 定义和生成工具 goctl，可以根据定义的 api 文件一键生成 Go, iOS, Android, Kotlin, Dart, TypeScript, JavaScript 代码，并可直接运行。
  - 可以让Go新手也可以快速编写高性能可扩展的微服务。

- 推荐理由：
  - 强大的工具支持，尽可能少的代码编写
  - 极简的接口
  - 完全兼容 net/http
  - 支持中间件，方便扩展
  - 高性能
  - 面向故障编程，弹性设计
  - 内建服务发现、负载均衡
  - 内建限流、熔断、降载，且自动触发，自动恢复
  - API 参数自动校验
  - 超时级联控制
  - 自动缓存控制
  - 链路跟踪、统计报警等
  - 高并发支撑，稳定保障流量洪峰

- 示例代码：
  ```go
  func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)

	ctx := svc.NewServiceContext(c)
	server := rest.MustNewServer(c.RestConf)
	defer server.Stop()

	handler.RegisterHandlers(server, ctx)

	server.Start()
  }
  ```

- 截图：
![image](https://user-images.githubusercontent.com/1918356/98439572-b17df900-212d-11eb-8cca-a2575fb385b4.png)
![image](https://user-images.githubusercontent.com/1918356/98439577-bd69bb00-212d-11eb-9ea5-af8ae5d0222f.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 56 期](https://hellogithub.com/periodical/volume/56/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

**Comment by kevwan** [comment]
> 您推荐的项目，**已成功发布**在 [HelloGitHub 第 56 期](https://hellogithub.com/periodical/volume/56/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
> 
> 欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

感谢！已star，如果可以，有劳 star 一下 [go-zero](https://github.com/tal-tech/go-zero) 谢谢 🙏
