### ISSUE TITLE
微信/QQ/TIM防撤回补丁

### ISSUE THREAD

**Issue by lxyok** [521xueweihan/HelloGitHub#1473]
## 项目推荐
- 项目地址：https://github.com/huiyadanli/RevokeMsgPatcher

- 类别：C#

- 项目后续更新计划：

- 项目描述：
  - 必写：Windows 下 PC 版微信/QQ/TIM的防撤回补丁阻止对方撤回信息 

- 推荐理由：有时候朋友发信息来了等我去看的时候就是已撤回，就感觉错过了啥好玩的。有了这个，直接就说撤回也没用，我已经截图了^_^

- 截图：
![Screenshot](https://raw.githubusercontent.com/huiyadanli/RevokeMsgPatcher/master/Images/screenshot.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 56 期](https://hellogithub.com/periodical/volume/56/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
