### ISSUE TITLE
MMORPG

### ISSUE THREAD

**Issue by dianbaer** [521xueweihan/HelloGitHub#148]
## 项目推荐
- 项目名称：MMORPG

- 项目地址：https://github.com/dianbaer/MMORPG

- 项目语言：Java+Actionscript3

- 项目描述：MMORPG是一个可以用来学习ARPG核心战斗的项目

- 推荐理由：
    1. 含有mmorpg所有战斗、场景、技能、ai、广播等核心代码。
    2. 服务器有很高的稳定性、安全性、效率、承载量，借鉴了天龙服务器的技术架构。魔兽世界的体验和交互设计思路，服务器拥有完整的客户端逻辑，对网络延迟处理的非常优秀，在外网服务器运行半年多的时间。
    3. 客户端有很高的渲染效率，经过2次深度优化，在网页上可以跑满60帧，手机上跑40-60帧。
    4. 客户端与服务器的交互品质达到一个业界很高的水准，在100毫秒以内，每秒20个心跳。战斗与交互体验非常优秀，可以达到国内较高的水准。
    5. 服务器与客户端交互，技能连技能，技能取消技能，都使用了一种可以叫做“弱同步”的机制，这是为了交互设计体验而设计的一种机制。

- 示例代码：

- 截图：
视频地址：
http://v.youku.com/v_show/id_XOTE5NDg1MTg0.html?firsttime=0

**Comment by 521xueweihan** [comment]
@dianbaer 期待推荐更多项目，老铁被你刷屏了。。。

**Comment by dianbaer** [comment]
被刷屏是嘛意思？

**Comment by 521xueweihan** [comment]
@dianbaer 觉得你很 NB 的意思

**Comment by dianbaer** [comment]
多谢，期望都能上推荐，哈哈。

**Comment by 521xueweihan** [comment]
@dianbaer 期待您持续推荐项目，早日加入到 核心贡献者行列 😁
