### ISSUE TITLE
【自荐】SZT-bigdata 深圳地铁大数据客流分析系统

### ISSUE THREAD

**Issue by geekyouth** [521xueweihan/HelloGitHub#1483]
## 项目推荐
- 项目地址：<https://github.com/geekyouth/SZT-bigdata>

- 类别：JAVA+Scala

- 项目后续更新计划：完善二期架构

- 项目描述：

该项目主要分析深圳通刷卡数据，通过大数据技术角度来研究深圳地铁客运能力，探索深圳地铁优化服务的方向；
✨ 强调学以致用，本项目的原则是尽可能使用较多的常用技术框架，加深对各技术栈的理解和运用，在使用过程中体验各框架的差异和优劣，为以后的项目开发技术选型做基础；
👑 解决同一个问题，可能有多种技术实现，实际的企业开发应当遵守最佳实践原则；
🎉 学习过程优先选择较新的软件版本，因为新版踩坑一定比老版更多，坑踩的多了，技能也就提高了，遇到新问题可以见招拆招、对症下药。

- 截图：
![](https://github.com/geekyouth/SZT-bigdata/raw/master/.file/.doc/full-logo.png)
![](https://github.com/geekyouth/SZT-bigdata/raw/master/.file/.doc/stack2.jpg)
![](https://github.com/geekyouth/SZT-bigdata/raw/master/.file/.doc/SZT-bigdata-2+.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
