### ISSUE TITLE
小说漫画采集阅读弹幕网站

### ISSUE THREAD

**Issue by 201206030** [521xueweihan/HelloGitHub#1485]
## 项目推荐
- 项目地址：https://github.com/201206030/fiction_house

- 类别：Java

- 项目后续更新计划：业余时间更新。

- 项目描述：
小说精品屋是一个多平台（web、安卓app、微信小程序）、功能完善的屏幕自适应小说漫画阅读弹幕网站，包含精品小说专区、轻小说专区和漫画专区。包括小说/漫画分类、小说/漫画搜索、小说/漫画排行、完本小说/漫画、小说/漫画评分、小说/漫画在线阅读、小说/漫画书架、小说/漫画阅读记录、小说TXT下载、小说弹幕、小说/漫画自动采集/更新/纠错。

- 推荐理由：搭建个人网站，采集小说漫画到本地阅读，发送弹幕和书友交流，免除互联网广告骚扰和网络限制。

- 示例代码：

```
          
                //解析第一页小说的数据
                //小说页URI正则匹配
                Pattern bookUriPatten = compile(getBookUrlPattern());
                Matcher bookUriMatcher = bookUriPatten.matcher(bookListHtml);
                boolean bookUriFind = bookUriMatcher.find();

                //小说评分正则匹配
                Pattern scorePatten = compile(getScorePattern());
                Matcher scoreMatch = scorePatten.matcher(bookListHtml);
                boolean scoreFind = scoreMatch.find();

                //小说名正则匹配
                Pattern bookNamePatten = compile(getBookNamePattern());
                Matcher bookNameMatch = bookNamePatten.matcher(bookListHtml);
                boolean bookNameFind = bookNameMatch.find();

                while (bookUriFind && scoreFind && bookNameFind) {
                    try {
                        //小说基础信息能够匹配到
                        Float score = Float.parseFloat(scoreMatch.group(1));
                        if (score < getLowestScore()) {
                            //只采集指定评分以上的小说
                            continue;
                        }

                        //获取小说基础信息，生成采集日志
                        String bookUri = bookUriMatcher.group(1);
                        String bookUrl = getIndexUrl() + "/" + bookUri + "/";
                        String bookName = bookNameMatch.group(1);
                        bookService.addBookParseLog(bookUrl, bookName, score, (byte) 10);

                    } catch (Exception e) {
                        //小说解析出现异常，不做处理，继续下一本小说的解析
                        log.error(e.getMessage(), e);
                    } finally {
                        //跳到下一本小说的解析
                        bookUriMatcher.find();
                        bookUriFind = bookUriMatcher.find();
                        scoreFind = scoreMatch.find();
                        bookNameFind = bookNameMatch.find();
                    }
                }
           
```

- 截图：
![QQ20200520-215756](https://image.uc.cn/o/wemedia/s/upload/2020/12edb2bea62b63091d20fc86b460c7d2.png)
![QQ20200520-215756](https://image.uc.cn/o/wemedia/s/upload/2020/db193765211903bfba8e531d00c089df.jpg)
![QQ20200520-215756](https://image.uc.cn/o/wemedia/s/upload/2020/70e7eb9d354f393256cee1c7c56706de.png)
![QQ20200520-215756](https://image.uc.cn/o/wemedia/s/upload/2020/0890d39b660665ba485ba93fae1bb9c3.png)
![QQ20200520-215756](https://image.uc.cn/o/wemedia/s/upload/2020/cb8749f1373610ab0d6326d2267c8476.png)
![QQ20200520-215756](https://image.uc.cn/o/wemedia/s/upload/2020/7e86c6e043088aec2625c21fed788663.png)
![QQ20200520-215756](https://image.uc.cn/o/wemedia/s/upload/2020/5e1de92410c93741e6b194f08112b598.png)
![QQ20200520-215756](https://static.oschina.net/uploads/img/201911/06101250_8V4S.png)
![QQ20200520-215756](https://image.uc.cn/o/wemedia/s/upload/2020/201f43f07c34d1495f54ffe1883c58d1.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 56 期](https://hellogithub.com/periodical/volume/56/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）

**Comment by 201206030** [comment]
Thanks!,已Star！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "521xueweihan/HelloGitHub"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月27日(星期五) 上午9:10
收件人:&nbsp;"521xueweihan/HelloGitHub"<HelloGitHub@noreply.github.com&gt;;
抄送:&nbsp;"离开天空的云"<1179705413@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [521xueweihan/HelloGitHub] 小说漫画采集阅读弹幕网站 (#1485)





 
您推荐的项目，已成功发布在 HelloGitHub 第 56 期，并把您添加到了贡献者列表中。
 
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
 
HG 发起了《讲解开源项目》系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
