### ISSUE TITLE
【自荐】命令行鼠标交互式的方式去管理 K8s - lazykube

### ISSUE THREAD

**Issue by elfgzp** [521xueweihan/HelloGitHub#1486]
## 项目推荐
- 项目地址：[https://github.com/TNK-Studio/lazykube](https://github.com/TNK-Studio/lazykube)

- 类别：Go 、工具

- 项目后续更新计划：

- [ ] 增加日志过滤功能
- [ ] 增加 deployment rollout restart 功能
- [ ] 增加资源编辑功能 (kubectl edit)
- [ ] ...

- 项目描述：
  - 必写：命令行鼠标交互式的方式去管理 K8s，对比 [k9s](https://github.com/derailed/k9s) 命令行工具，可以不用去记那么多快捷键，直接用鼠标交互操作。主要解决公司不使用 rancher 和 dashboard 管理 K8s，只能通过堡垒机访问，这样操作方式只有终端，节约敲命令的时间。

- 推荐理由：命令行鼠标交互式的方式去管理 K8s

- 截图：![gif](https://github.com/TNK-Studio/lazykube/raw/main/docs/lazykube.gif)

**Comment by elfgzp** [comment]
[v0.2.2](https://github.com/TNK-Studio/lazykube/releases/tag/v0.2.2) 版本增加了过滤功能，快捷键 F4
![gif1](https://tva1.sinaimg.cn/large/0081Kckwgy1gkth4dsyeqg30ul0kxhdw.gif)

**Comment by 521xueweihan** [comment]
持续搞下去

**Comment by elfgzp** [comment]
增加项目首页
https://lazykube.tnk-studio.org

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 56 期](https://hellogithub.com/periodical/volume/56/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）

**Comment by elfgzp** [comment]
感谢推荐，很早就 star 了～👍
