### ISSUE TITLE
【自荐】vscode-texinfo：在 Visual Studio Code 中编辑 Texinfo 文档

### ISSUE THREAD

**Issue by CismonX** [521xueweihan/HelloGitHub#1487]
### 项目地址

[texinfo-lang/vscode-texinfo](https://github.com/texinfo-lang/vscode-texinfo)

### 类别

其他（领域：开发工具/VSCode；语言：TypeScript）

### 项目描述

vscode-texinfo 是一个 Visual Studio Code 插件，它提供了在 Visual Studio Code 中编辑 Texinfo 文档的基本功能，包括：
* 语法高亮
* 代码补全
* HTML 预览
* 章节、块的折叠和[面包屑导航](https://en.wikipedia.org/wiki/Breadcrumb_navigation)

### 推荐理由

作为一个专门为撰写技术文档而生的排版语言，Texinfo 比 Markdown 功能丰富，同时又比 LaTeX 简单易上手。但是，虽然 Texinfo 历史悠久且一直持续迭代，由于在主流代码编辑器中的支持匮乏（目前已知只有 Emacs 的 texinfo-mode），它逐渐地淡出了开发者的视线。

本项目将 Texinfo 带进了流行的代码编辑器 Visual Studio Code，主要目的就是希望更多的开发者能够了解 Texinfo，并能够舒适地使用它编写文档。最终写出更加优秀的技术文档。

### 项目后续更新计划

实现 Texinfo 的 Language Server，从而解决该插件目前存在的一些问题。

### 截图：

![preview](https://user-images.githubusercontent.com/19173506/98842831-15355880-2485-11eb-9a12-a709d930ac05.png)

![completion](https://user-images.githubusercontent.com/19173506/98842873-254d3800-2485-11eb-8cef-78a534b08b84.png)

![navigation](https://user-images.githubusercontent.com/19173506/98842850-1ebec080-2485-11eb-8da7-2d167ea86ccf.png)

![folding](https://user-images.githubusercontent.com/19173506/98842863-21b9b100-2485-11eb-85f9-d6c9d317d307.png)

![diagnostics](https://user-images.githubusercontent.com/19173506/98842883-28482880-2485-11eb-9399-6046e8873014.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
