### ISSUE TITLE
【自荐】用键盘8个键演奏一首钢琴曲送给她

### ISSUE THREAD

**Issue by Wscats** [521xueweihan/HelloGitHub#1489]
## 项目推荐

- 项目地址：https://github.com/Wscats/piano

- 体验地址：https://wscats.github.io/piano/build

- 类别：其他 - 音乐

- 项目描述：

![image](https://user-images.githubusercontent.com/17243165/99625794-f2e6a080-2a6b-11eb-9f4f-3bafeb074435.png)

用键盘8个键演奏一首蒲公英的约定送给996的自己或者一首月亮代表我的心给七夕的她，非常简单~ 这个项目仅仅用了几个简单的前端技术实现，献给每一位挚爱音乐的代码家🎹

- 推荐理由：

不需要懂乐理知识，仅用键盘即可弹奏简单而熟悉的音乐，也借此项目感谢音乐和编程的陪伴！也致敬各位奋斗于996的代码家和打工人，欢迎分享，音乐不曾辜负任何人，正如 Leehom Wang 歌曲中唱到：

> 如果世界太危险，只有音乐最安全，带着我进梦里面，让歌词都实现！ —— 《我们的歌》

- 项目后续更新计划：

项目中没有使用市面主流的框架（React，Vue 和 Angular ）和热门的技术，而用的是腾讯 Omi 框架（JSX+WebComponents），还有 Omil 的单文件组件 SFCs 加载器，组件通讯基于Proxy特性，并结合了 VScode 的插件 Omi-Snippets基于 AST 和正则实时编译 .eno 或 .omi 后缀组件减轻部分的 Webpack 的局部编译压力，后续会完善 Omi 的解析器，和增加示例音乐，并升级音乐的引擎。

- 示例代码：

```js
playSong(song) {
  this.setSong([...song])
  let offset = 0
  let time = 0
  let playSong = async () => {
    // 右边是从外部来中断递归
    if (offset < song.length && this.store.data.song.length > 0) {
      switch (typeof song[offset]) {
        // 简谱2演奏方法 根据 ++12345--6. 简单旋律情况
        case 'string':
          let letters = song[offset].match(/[0-9]/g)
          switch (letters.length) {
            case 1:
              time = this.handleString(song, offset)
              break
            default:
              time = this.handleStrings(song, offset)
              break
          }
          break
        // 简谱1演奏方法 根据 CDEFGAB，复杂旋律情况，比如有和弦
        case 'object':
          console.log(song[offset]['note'])
          time = song[offset]['time'];
          this.playNote(song[offset]['note'])
          break;
        case 'number':
          // 休止符
          switch (song[offset]) {
            case 0:
              time = 1000
              break
          }
          break
      }
      await new Promise((resolve) => {
        let timer = setTimeout(() => {
          clearInterval(timer)
          resolve()
        }, time)
      })
      offset++
      // 自定义事件，跟下面底部的音符自动跳动结合
      this.add()
      playSong()
    } else {
      // 暂停播放
      clearTimeout(this.timer)
      this.store.data.song = []
      this.store.data.count = 0
      return
    }
  }
  playSong()
}
```

- 截图：

![piano](https://user-images.githubusercontent.com/17243165/99626385-0c3c1c80-2a6d-11eb-8f41-87d589fa5ebb.gif)

![image](https://user-images.githubusercontent.com/17243165/99626511-4e655e00-2a6d-11eb-9634-1f4fb65f721f.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 56 期](https://hellogithub.com/periodical/volume/56/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
