### ISSUE TITLE
【自荐】Markdown-Toolbox

### ISSUE THREAD

**Issue by HaujetZhao** [521xueweihan/HelloGitHub#1490]
## 项目推荐

- 项目地址：https://github.com/HaujetZhao/Markdown-Toolbox

- 类别：Python

- 项目后续更新计划：目前图片离线化还是单线程一张一张下载，等有时间了学下多线程，加快下载速度。

- 项目描述：
  Markdown 工具箱，是我为 Markdown 笔记管理做的一个工具集。目前有以下几个功能：

  - 复制
    批量将 md 笔记（连带它的相对路径引用的图片、附件）复制或移动到另一指定的文件夹
  - 离线化
    批量将 md 笔记中的在线图片、附件、绝对路径引用的文件下载或移动到笔记的相对路径文件夹中，并将原始笔记中原来的绝对路径改为相对路径
  - 清理
    批量清理 Markdown 相对路径索引的文件夹中已不再被引用的图片

- 推荐理由：我不信任任何图床，但是 TextBundle 还没有普及，所以目前我在做 Markdown 笔记的时候，会把图片都放到 md 文档同目录下的 assets 文件夹，用相对路径引用图片。
  
  但这就带来一个问题：一个目录下所有笔记的图片都在同一个 assets 目录下，如果我想要整理下笔记，将其中几份笔记移动到另一个文件夹，因为所有图片使用的是相对路径，我就需要将所有引用到的图片都一并复制过去。
  
  而如果要从存有上百张、上千张图片的 assets 文件夹中找到要移动的文档所引用的所有图片，是非常困难的；而如果一股脑将整个 assets 文件夹复制过去，必然会造成磁盘空间浪费。

  这就是 Markdown 的通病：

  - 图片用图床吧，网络会影响体验，图床也难保几十年地靠谱
  - 图片用本地绝对路径吧，分享文档到其它设备，就看不了图了
  - 图片用本地相对路径吧，多个文档共用一个图片目录的话，后期整理和分享也都不方便
  
  不过我还是坚持 md 笔记使用本地相对路径的图片，为了方便整理文档，就写了这个工具，第一个功能是 复制，用于移动文档的同时自动移动文档中索引的相对路径的图片、附件。

**Comment by 521xueweihan** [comment]
有想法切动手实现工具，非常好。但是这个工具使用场景不多，适用人群不广。

非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
