### ISSUE TITLE
【自荐】本机状态监控（Python+Flask插件）

### ISSUE THREAD

**Issue by aaronxiongli** [521xueweihan/HelloGitHub#1491]
## 项目推荐
- 项目地址：https://github.com/yoobool/flask-state

- 类别：Python

- 项目后续更新计划：
  - 添加更多的可扩展服务监控
  - 记录频率参数支持 Cron 表达式
  - 优化Flask-State手机端显示

- 项目描述：
  - Flask-State是一款轻便的、图表化插件；
  - 可扩展：除记录本机状态外，还包括丰富的扩展功能选择。其中有Redis监控、用户验证、自定义logging和i18n等。
  - 稳定：轻量级的依赖关系，同时解决了多进程并发问题。

- 推荐理由：一款轻便的、图表化插件；

- 示例代码：
```import flask_state
flask_state.init_app(app)
// npm
import 'echarts';
import 'flask-state/flask-state.min.css';
import {init} from 'flask-state';
// Create a DOM node with ID 'test'. After init() binds the node, click to open the listening window
init({dom:document.getElementById('test')});
```
- 截图：
![状态监控截图](https://camo.githubusercontent.com/1018d2a3c46158506c52361767f60831e62fc5f14b2b2df7836c639b6ff5c922/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f796f6f626f6f6c2f666c61736b2d737461746540312e302e342f6578616d706c65732f7374617469632f666c61736b5f73746174652e706e67)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 56 期](https://hellogithub.com/periodical/volume/56/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
