### ISSUE TITLE
GOPUP 数据接口

### ISSUE THREAD

**Issue by justinzm** [521xueweihan/HelloGitHub#1493]
## 项目推荐
- 项目地址：https://github.com/justinzm/gopup

- 类别：python

- 项目后续更新计划：

- 项目描述：
  - 旨在使获取数据尽可能方便，主要用于学术研究目的。
  - 数据接口：百度、谷歌、头条、微博指数,宏观数据，利率数据，货币汇率，千里马、独角兽公司，新闻联播文字稿，影视票房数据，高校名单，疫情数据…

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

## 提示（提交时请删除以下内容）
> 点击上方 “Preview” 更方便地阅读以下内容，

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
@justinzm  修改建议：

1. 请整理下自己的提交信息，删除多余的内容（请阅读提示）
2. 清理项目中的 .DS_Store 文件，加到 gitignore 中
3. 挑一个快速开始放到 REAMDE 展示
