### ISSUE TITLE
【自荐】程序员励志语录

### ISSUE THREAD

**Issue by StepfenShawn** [521xueweihan/HelloGitHub#1494]
## 项目推荐
- 项目地址：
https://github.com/StepfenShawn/Motivational-Quotes
- 类别: HTML

- 项目后续更新计划：
* 收集更多的语录
* 添加英文版
* 更加简洁的css
* 带包成h5 App, 支持离线访问
- 项目描述：
  - 必写：程序run不起来想放弃? 程序员励志语录帮你重拾信心
网站地址: http://lower_jade.gitee.io/motivational-qutes/

- 推荐理由：人嘛遇到困难肯定有想放弃的时候，这时候一个简洁优雅的小页面可能会帮助你重拾希望!

- 截图：（可选）gif/png/jpg
![image](https://user-images.githubusercontent.com/44727245/99892128-9a521600-2cac-11eb-9a6e-565cc3d1971a.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
