### ISSUE TITLE
【自荐】打造个人跑步主页（Python+React）

### ISSUE THREAD

**Issue by yihong0618** [521xueweihan/HelloGitHub#1496]
## 项目推荐
- 项目地址：https://github.com/yihong0618/running_page

- 类别：Python

- 项目后续更新计划：
  - 更多跑步 APP 支持
  - 多语言支持
  - 支持多主题

- 项目描述：
  1. GitHub Actions 管理自动同步跑步进程及自动生成新的页面
  2. Gatsby 生成的静态网页，速度快
  3. 支持 Vercel(推荐) 自动部署
  4. React Hooks
  5. Mapbox 进行地图展示
  6. Nike 及 Runtastic(Adidas Run) 以及佳明（佳明中国）及 Keep, 自动备份 gpx 数据，方便备份及上传到其它软件

- 推荐理由：自己的跑步数据自己做主，GitHub Actions 自动化，激励自己跑下去。和同样爱好跑步的程序员分享自己的主页。

- 截图：
![running_page](https://user-images.githubusercontent.com/15976103/98808834-c02f1d80-2457-11eb-9a7c-70e91faa5e30.gif)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 56 期](https://hellogithub.com/periodical/volume/56/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）

**Comment by yihong0618** [comment]
谢谢。
