### ISSUE TITLE
推荐https://github.com/fastgh/fgit

### ISSUE THREAD

**Issue by fastgh** [521xueweihan/HelloGitHub#1497]
## 项目推荐
- 项目地址：https://github.com/fastgh/fgit

- 类别：Go

- 项目后续更新计划：目前是1.0，2.0计划增加支持SSH代理，支持git的sub module等

- 项目描述：
  - 必写：为clone github加速
  - 可选：是个工具，帮助大家clone大的github项目
  - 描述长度: 

- 推荐理由：fgit是一个可以无缝替换git命令行的工具，使用优化线路为使用github.com加速。目前实测git clone速度超过15MB/S

- 截图：
<img src="https://control.fastgithub.com:10443/static/how_fast-annotated.png" alt="image"/>

**Comment by 521xueweihan** [comment]
实用的项目。

建议项目 README 认真修改下：
1. 简介突出使用和效果
2. 对比和原理往下放或者给链接。

可以提个 PR 到下面这个项目，月刊就不收录了。

https://github.com/521xueweihan/GitHub520
