### ISSUE TITLE
GOPUP 数据接口

### ISSUE THREAD

**Issue by justinzm** [521xueweihan/HelloGitHub#1498]
## 项目推荐
- 项目地址：https://github.com/justinzm/gopup

- 类别：Python

- 项目后续更新计划： 后续会基于金融、生活等方面来添加更多数据接口, 敬请关注.

- 项目描述：
  - 本项目提供的数据接口及相关数据仅用于学术研究，旨在使获取数据尽可能方便。
  - 数据接口：百度、谷歌、头条、微博指数,宏观数据，利率数据，货币汇率，千里马、独角兽公司，新闻联播文字稿，影视票房数据，高校名单，疫情数据… 

- 推荐理由：获取的是相对权威的数据网站公布的原始数据, 通过利用原始数据进行各数据源之间的交叉验证, 进而再加工。

- 示例代码：

`import gopup as gp  

df = gp.weibo_index(word="疫情", time_type="1hour")  
print(df)`

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 56 期](https://hellogithub.com/periodical/volume/56/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
