### ISSUE TITLE
RoundShadowImageView - 圆形图片的阴影,自由定制!

### ISSUE THREAD

**Issue by HuanHaiLiuXin** [521xueweihan/HelloGitHub#1499]
## 项目推荐
- 项目地址：https://github.com/HuanHaiLiuXin/RoundShadowImageView

- 类别：Java

- 项目后续更新计划：
  - 添加对非圆形ImageView的支持
  - 添加对TextView,Button的支持

- 项目描述：
  - RoundShadowImageView 是1个为圆形图片的ImageView添加阴影的自定义控件.
  - 可以自由设置:
    1. 阴影的颜色
    2. 阴影初始透明度
    3. 阴影位置
    4. 阴影相对中心点角度
    5. 阴影的显示尺寸比例
  - 描述长度（不包含示例代码）: 圆形图片的阴影,自由定制!

- 推荐理由：不增加布局层级,性能更好! 阴影相关属性自由设置,定制型更强!

- 示例代码：
```java
RoundShadowImageView shadowImageView = findViewById(R.id.shadowImageView);
ObjectAnimator animator = ObjectAnimator.ofFloat(shadowImageView,"shadowCircleAngle",0F,360F);
animator.start();
```

- 截图：
![RoundShadowImageView.gif](https://github.com/HuanHaiLiuXin/RoundShadowImageView/blob/main/RoundShadowImageView.gif)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
