### ISSUE TITLE
Mac中漂亮的代码行计算工具(已开源)--PPRows

### ISSUE THREAD

**Issue by jkpang** [521xueweihan/HelloGitHub#15]
PPRows -- 在Mac上计算你写了多少行代码 
开源地址:  https://github.com/jkpang/PPRows
1. 支持检测参与计算的代码文件夹数量以及代码行数;
2. 支持同时检测多文件/多文件夹代码;
3. 支持自定义检测的文件类型,例如:c,swift,oc, java....类型的代码文件;
4. 支持自定义需要忽略检测的文件夹, 例如: iOS工程中的Pods文件夹;
5. 支持中文与英文,跟随系统语言变化 
6. 支持忽略代码中的空行, 代码行数计算更精确.
![gif1](https://cloud.githubusercontent.com/assets/17583451/24388127/3b7edcee-13ab-11e7-90f9-c2193a574897.gif)
![gif2](https://cloud.githubusercontent.com/assets/17583451/24388137/41b36242-13ab-11e7-94ae-38cfc8c079a5.gif)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目 🙏。

如您推荐的项目在《HelloGithub》月刊中推荐，则会注明推荐人。**同时在此 issues 中通知您**。

再次感谢您对《HelloGithub》项目的支持！💪

**Comment by 521xueweihan** [comment]
🎉🎉🎉 
您好，PPRows 项目已收录到 [13期](https://github.com/521xueweihan/HelloGitHub/blob/master/13/HelloGitHub13.md)，再次感谢您的支持，希望以后推荐更多好的项目。
