### ISSUE TITLE
推荐：webpack-component-loader

### ISSUE THREAD

**Issue by nicholaslee119** [521xueweihan/HelloGitHub#150]
## 项目推荐
- 项目名称：webpack-component-loader

- 项目地址：https://github.com/nicholaslee119/webpack-component-loader

- 项目语言：JavaScript

- 项目描述：在没有前端框架的情况下实现组件化

- 推荐理由：https://juejin.im/post/59df7e76f265da431e15c4fe  详细介绍了项目的方向

- 示例代码：

- 截图：

**Comment by 521xueweihan** [comment]
@nicholaslee119   您推荐的项目，已成功收录在 [HelloGitHub 第 22 期](https://hellogithub.com/volume/22/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，欢迎 Star ⭐️ 本项目，以便让更多人看到。
