### ISSUE TITLE
gping

### ISSUE THREAD

**Issue by MikeDGitHub** [521xueweihan/HelloGitHub#1500]
## 项目推荐
- 项目地址：https://github.com/orf/gping

- 类别：其它

- 项目后续更新计划：

- 项目描述：
  - 必写：ping 命令的替代品，带有图形界面
  - 可选：适用于什么场景、能够让初学者学到什么
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：ping 命令的替代品，带有图形界面

- 示例代码：gping --help

- 截图：（可选）gif/png/jpg
![image](https://github.com/orf/gping/raw/master/images/readme-example.gif)

## 提示（提交时请删除以下内容）
> 点击上方 “Preview” 更方便地阅读以下内容，

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
@MikeDGitHub 请按照要求从提交项目信息。完成后可以 @我
