### ISSUE TITLE
pyShortLink-短链接服务

### ISSUE THREAD

**Issue by smallevil** [521xueweihan/HelloGitHub#1502]
## 项目推荐
- 项目地址：https://github.com/smallevil/pyShortLink

- 类别：Python、JS、HTML

- 项目后续更新计划：增加短链超时功能、完善提示、增加多用户管理

- 项目描述：
  简单的短链服务,公司可以通过这个项目管理自己的推广链接.支持Mysql和sqlite3.支持Python2和Python3

- 推荐理由：短链现在公开平台不好找了.各大平台开始收费.小平台不稳定.此项目可以自建短链平台,开箱即用.一套程序即可跑起来

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。[加入我们](https://mp.weixin.qq.com/s/9FUQ2i0HbemwfIj9sa1p0A)

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
