### ISSUE TITLE
项目推荐 - TechNewsletter

### ISSUE THREAD

**Issue by thyrlian** [521xueweihan/HelloGitHub#1503]
## 项目推荐
- 项目地址：https://github.com/thyrlian/TechNewsletter

- 类别：其它

- 项目后续更新计划：更新UI，增加支持的邮件客户端，添加后台管理系统，全文索引。

- 项目描述：
  - 必写：通过使用项目自定义的轻量化标记语言（类Markdown），创建小巧易读便维护的周报文件，最终自动生成高度响应式网页（大部分客户端支持），从而给订阅者发送漂亮的周报邮件。

- 推荐理由：普通的邮件生成工具或者服务需要大量的鼠标拖拽，并且内容和最终生成的网页代码高度混合，不利于维护管理。而本工具通过程序员的方式，彻底改变了传统工具的弊病，可以达到完全的GitOps.

- 截图：
<img src="https://github.com/thyrlian/TechNewsletter/blob/master/assets/images/Intro.png?raw=true" width="800">

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
