### ISSUE TITLE
【自荐】基于Auto.js的蚂蚁森林能量智能收取脚本

### ISSUE THREAD

**Issue by SuperMonster003** [521xueweihan/HelloGitHub#1504]
## 项目推荐
- 项目地址：[Ant_Forest](https://github.com/SuperMonster003/Auto.js_Projects/tree/Ant_Forest)

- 类别：JavaScript

- 项目后续更新计划：长期维护

- 项目描述：蚂蚁森林能量智能收取脚本 (基于[`Auto.js`](https://github.com/hyb1996/Auto.js))

- 推荐理由：
1. 智能化 自动化 无人值守 高[鲁棒性](https://baike.baidu.com/item/%E9%B2%81%E6%A3%92%E6%80%A7/832302)
2. 基于 `Auto.js UI` 的项目参数配置 (友好的交互界面)
3. `JavaScript` 语法 / 针对 `Auto.js` + `ES5` + `部分ES6` 的诸多扩展模块
4. 扩展模块 (如 `自动解锁` 模块) 可轻易适用于其他 `Auto.js` 项目

- 难点解决：
1. 能量球识别无法使用控件信息 (使用基于霍夫变换的图像识别)
2. 脚本执行逻辑易被打断 (使用事件监听及扩展模块增强鲁棒性)
3. 每次只能运行一次 (完善的复查及定时循环功能)
4. 不同设备分辨率及屏幕比例不同 (使用等比缩放/定宽缩放等进行适配)

- 示例代码：
```js
$$init.check().global().queue().delay().monitor().unlock().prompt().command();
$$af.launch().collect().timers().epilogue();
```

- 截图：
![Screenshot_20201128-145730](https://user-images.githubusercontent.com/30370009/100497063-ecef6e80-3193-11eb-8162-7409d383abd3.png)
![Screenshot_20201128_145941](https://user-images.githubusercontent.com/30370009/100497109-39d34500-3194-11eb-949d-49619de7225c.png)

**Comment by 521xueweihan** [comment]
恭喜您！

您推荐的项目，**已成功发布**在 [HelloGitHub 第 57 期](https://hellogithub.com/periodical/volume/57/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎参与。如需帮助，可以加我的微信：xueweihan（备注您的项目名称）
