### ISSUE TITLE
开源项目 - InfoSpider爬虫工具箱

### ISSUE THREAD

**Issue by kangvcar** [521xueweihan/HelloGitHub#1505]
## 项目推荐
- 项目地址：https://github.com/kangvcar/InfoSpider

- 类别：Python

- 项目后续更新计划：计划在v2.0版本对项目进行重构，提供web端操作与数据可视化，以适配多平台。提供更丰富的数据分析功能和人物画像分析系统。

- 项目描述：INFO-SPIDER 是一个集众多数据源于一身的爬虫工具箱🧰，旨在安全快捷的帮助用户拿回自己的数据，工具代码开源，流程透明。支持数据源包括GitHub、QQ邮箱、网易邮箱、阿里邮箱、新浪邮箱、Hotmail邮箱、Outlook邮箱、京东、淘宝、支付宝、中国移动、中国联通、中国电信、知乎、哔哩哔哩、网易云音乐、QQ好友、QQ群、生成朋友圈相册、浏览器浏览历史、12306、博客园、CSDN博客、开源中国博客、简书。
该项目解决了个人数据分散在各种各样的公司之间，经常形成数据孤岛，多维数据无法融合的痛点。

- 推荐理由：本项目目前支持多达24+个数据源，持续更新。所有数据源相互独立，可移植性高，所有爬虫脚本在项目的 Spiders 文件下。

- 截图：
![image](https://user-images.githubusercontent.com/20273349/100537364-ed0a6f80-3262-11eb-8f34-669811d5a0f7.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
