### ISSUE TITLE
完整实现前后端的数据可视化平台

### ISSUE THREAD

**Issue by JohnYan2017** [521xueweihan/HelloGitHub#1511]
## 项目推荐
- 项目地址：
https://github.com/JohnYan2017/Echarts-Django
https://gitee.com/smartchart/django_smartchart
- 类别：Python

- 项目后续更新计划：
持续维护, 建立图形生态

- 项目描述：
  - 必写：完整实现前后端的可视化开发平台,内置Echarts,极低门槛,拿来即用,比拖拽更方便
  - 可选：可做为项目插件或独立平台应用的可视化平台
  - 描述长度（不包含示例代码）: 完整实现前后端的可视化开发平台,内置Echarts,极低门槛,拿来即用,比拖拽更方便,可做为项目插件或独立平台应用,让你项目页面图形,大屏可视化非常方便, 简单, 敏捷, 高效, 通用化, 高度可定制化,为你完全打通前后端, 图形数据联动, 筛选开发毫无压力, 数据缓存处理机制让查询无压力

- 推荐理由：数据可视化拿来即用, 比拖拽更方便且不失其定制化能力, 简单, 敏捷, 高效, 通用化, 高度可定制化, 让你的项目瞬间档次提升

- 示例代码:
pip install smartchart

- 截图：
![](http://smartchart.cn/media/editor/WX20201128-075135@2x_20201128075202927382.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by JohnYan2017** [comment]
兄弟, 帮忙提点下, 那一条需要改进呗
