### ISSUE TITLE
自荐项目 - WarOfResistanceLive(抗战直播)

### ISSUE THREAD

**Issue by kokohuang** [521xueweihan/HelloGitHub#1512]
## 项目推荐
- 项目地址：https://github.com/kokohuang/WarOfResistanceLive

- 类别：其它

- 项目后续更新计划：持续更新

- 项目描述：
  - 必写：这是一个记录14年(1931-1945)抗战历史的博客，通过这种方式，让我们与抗战中的国人一起经历每一个日日夜夜，感受他们曾经的屈辱与绝望，感受他们的光荣与梦想。

- 推荐理由：铭记历史，相关介绍文章：https://juejin.cn/post/6903332404694515726

- 示例代码：（可选）长度：1-20 行

- 截图：

<img width="2139" alt="image" src="https://user-images.githubusercontent.com/8692455/101304942-6cf49300-387c-11eb-88cf-616014442b2c.png">

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
