### ISSUE TITLE
SpringBoot2集成Activiti7、Swagger、Druid

### ISSUE THREAD

**Issue by xugj-gits** [521xueweihan/HelloGitHub#1517]
## 项目推荐
- 项目地址：https://github.com/xugj-gits/SpringBoot2_Activiti7

- 类别：Java

- 项目后续更新计划：

- 项目描述：
  - 必写：SpringBoot2集成Activiti7、Swagger、Druid
  - 可选：适用于什么场景、能够让初学者学到什么
  - 描述长度（不包含示例代码）: 10 - 256 个字符

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
