### ISSUE TITLE
python脚本生成exe批量检测网站TDK

### ISSUE THREAD

**Issue by xugj-gits** [521xueweihan/HelloGitHub#1518]
## 项目推荐
- 项目地址：https://github.com/xugj-gits/BulkURLDetection

- 类别：Python

- 项目后续更新计划：

- 项目描述：
  - 必写：网站频繁、大量被黑、挂马；替换被挂马文件后需要检查是否再次被挂马，由于网站比较多，所以用这个检测网站是否再次被黑，省去每次打开网站F12检测TDK的工作量

- 推荐理由：网站频繁、大量被黑、挂马；替换被挂马文件后需要检查是否再次被挂马，由于网站比较多，所以用这个检测网站是否再次被黑，省去每次打开网站F12检测TDK的工作量

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
