### ISSUE TITLE
H5数字键盘

### ISSUE THREAD

**Issue by viclm** [521xueweihan/HelloGitHub#152]
## 项目推荐
- 项目名称：手机数字键盘

- 项目地址：https://github.com/viclm/numeric-keyboard

- 项目语言：javascript

- 项目描述：手机数字键盘，包含一个纯键盘ui和输入框套件，有纯js,react,vue三个版本，后续会支持更多框架
- 推荐理由：简单易用，支持多种框架，兼容性强大，扩展容易

[点击观看演示视频](https://fast.wistia.net/embed/iframe/f40gilnlxp)

**Comment by 521xueweihan** [comment]
@viclm 您推荐的项目，已成功收录在 [HelloGitHub 第 21 期](https://hellogithub.com/volume/21/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，欢迎 Star ⭐️ 本项目，以便让更多人看到。
