### ISSUE TITLE
【自荐】Electron桌面端所见即所得

### ISSUE THREAD

**Issue by Gstring-w** [521xueweihan/HelloGitHub#1521]
## 项目推荐
- 项目地址：https://github.com/tal-tech/electron-playground

- 类别：JS

- 项目后续更新计划：electron 开发一整个流程

- 项目描述：

1. 带有gif示例和可操作的demo的教程文章。
2. 系统性的整理了Electron相关的api和功能。
3. 搭配演练场，自己动手尝试electron的各种特性。

- 推荐理由：electron客户端、代码可以编辑，即所见即所得

- 截图：
![12](https://user-images.githubusercontent.com/37607986/101755255-9f69ee80-3b0f-11eb-8721-6dae9dc7ff16.png)

**Comment by sz-p** [comment]
第一行链接多了中文分号导致404

**Comment by Gstring-w** [comment]
> 第一行链接多了中文分号导致404

已修正

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
