### ISSUE TITLE
bat — 搭配语法高亮和Git集成的cat

### ISSUE THREAD

**Issue by Yanwenjiepy** [521xueweihan/HelloGitHub#1522]
## 项目推荐
- 项目地址：https://github.com/sharkdp/bat

- 类别：Rust

- 项目后续更新计划：维护中

- 项目描述：
  - 搭配语法高亮和Git集成的cat替代品，可以灵活配置主题、字体、颜色
  - 在终端使用bat查看代码，配合语法高亮和Git集成，非常方便
  - 可以像在vim里一样查询关键字
  

- 推荐理由：
 - 支持大量编程和markdown语言的语法高亮显示
 - bat与git集成,显示代码修改信息
 - 文件过大时，会自动分页
 - 读取文件时可以指定语言
 - 可以自定义主题
 - 可以自己添加新的语言支持

- 截图：
  - 语法高亮：
![image](https://camo.githubusercontent.com/7b7c397acc5b91b4c4cf7756015185fe3c5f700f70d256a212de51294a0cf673/68747470733a2f2f696d6775722e636f6d2f724773646e44652e706e67)

   - 与Git集成：
![image](https://camo.githubusercontent.com/c436c206f2c86605ab2f9fb632dd485afc05fccbf14af472770b0c59d876c9cc/68747470733a2f2f692e696d6775722e636f6d2f326c53573452452e706e67)

**Comment by 521xueweihan** [comment]
恭喜您！

您推荐的项目，**已成功发布**在 [HelloGitHub 第 57 期](https://hellogithub.com/periodical/volume/57/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
