### ISSUE TITLE
[自荐] UNO

### ISSUE THREAD

**Issue by Gusabary** [521xueweihan/HelloGitHub#1523]
## 项目推荐
- 项目地址：https://github.com/Gusabary/UNO

- 类别：C++

- 项目后续更新计划：见项目 [Wiki](https://github.com/Gusabary/UNO/wiki/%E5%BE%85%E5%AE%9E%E7%8E%B0%E5%8A%9F%E8%83%BD%E7%9A%84%E8%AF%A6%E7%BB%86%E9%9C%80%E6%B1%82)

- 项目描述：

  这是一个使用 C++ 编写的命令行版纸牌游戏 UNO，项目包括服务端，客户端以及 bot 的代码。

- 推荐理由：

  + 操作方便，一个 shell，一个 binary 就可以玩 UNO，纯命令行操作的游戏体验。
  + 可以联网（目前支持 2 ~ 4 人），和朋友一起玩。开始一场对局需要启动一个游戏服务，可以由玩家自己启动，也可以使用我们[预启动的游戏服务](https://github.com/Gusabary/UNO/wiki/%E9%A2%84%E5%90%AF%E5%8A%A8%E7%9A%84%E6%B8%B8%E6%88%8F%E6%9C%8D%E5%8A%A1)。
  + 支持人机对战，实现了一个简单的 bot。
  + 跨平台，适配 linux，windows 以及 mac 终端。
  + 基于 Asio 网络库和现代 C++ 开发，也有对 C++17 的尝试
  

- 示例代码：

- 截图：![](https://raw.githubusercontent.com/Gusabary/UNO/master/asset/demo.gif)

**Comment by 521xueweihan** [comment]
恭喜您！

您推荐的项目，**已成功发布**在 [HelloGitHub 第 57 期](https://hellogithub.com/periodical/volume/57/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎参与。如需帮助，可以加我的微信：xueweihan（备注您的项目名称）
