### ISSUE TITLE
入门项目推荐:beginners-intro-javascript-node

### ISSUE THREAD

**Issue by sz-p** [521xueweihan/HelloGitHub#1524]
## 项目推荐
- 项目地址：[beginners-intro-javascript-node](https://github.com/microsoft/beginners-intro-javascript-node)

- 类别：javascript

- 项目后续更新计划：维护中。

- 项目描述：
  -  javascript-node.js 开发的入门教程。
  - 微软出品，有相对较为全面和权威的教程。
- 推荐理由：权威、全面的`node.js`入门教程。

> ps: 搭配[Web-Dev-For-Beginners](https://github.com/microsoft/Web-Dev-For-Beginners/)食用更佳。

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
