### ISSUE TITLE
入门项目推荐:Web-Dev-For-Beginners

### ISSUE THREAD

**Issue by sz-p** [521xueweihan/HelloGitHub#1525]
## 项目推荐
- 项目地址：[Web-Dev-For-Beginners](https://github.com/microsoft/Web-Dev-For-Beginners/)

- 类别：javascript

- 项目后续更新计划：维护中。

- 项目描述：
  -  `WEB开发`的入门教程。
  -  微软出品，有相对较为全面和权威的教程。
- 推荐理由：权威、全面的`WEB开发`入门教程。

> ps: 搭配[beginners-intro-javascript-node](https://github.com/microsoft/beginners-intro-javascript-node)食用更佳。

**Comment by 521xueweihan** [comment]
恭喜您！

您推荐的项目，**已成功发布**在 [HelloGitHub 第 57 期](https://hellogithub.com/periodical/volume/57/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
