### ISSUE TITLE
[自荐]LnskyDB 于Dapper的Lambda扩展

### ISSUE THREAD

**Issue by liningit** [521xueweihan/HelloGitHub#1526]
## 项目推荐
- 项目地址：https://github.com/liningit/LnskyDB

- 类别：C#

 
- 项目描述：
  LnskyDB是基于Dapper的Lambda扩展,支持按时间分库分表,也可以自定义分库分表方法.而且可以T4生成实体类免去手写实体类的烦恼.

文档地址: https://liningit.github.io/LnskyDB/

开源地址: https://github.com/liningit/LnskyDB

nuget地址: https://www.nuget.org/packages/LnskyDB/

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
