### ISSUE TITLE
去除字符马赛克的算法Depix

### ISSUE THREAD

**Issue by SekiBetu** [521xueweihan/HelloGitHub#1528]
## 项目推荐
- 项目地址：
https://github.com/beurtschipper/Depix

- 类别：
Python

- 项目后续更新计划：
算法较完善，后续更新未知

- 项目描述：
这个项目可以通过算法最大程度地去除被轻度打码的字符的马赛克

- 推荐理由：
去码效果显著

- 截图：
![image](https://user-images.githubusercontent.com/38283893/101875518-aaaa3200-3b82-11eb-8167-5ac36e26a19d.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
