### ISSUE TITLE
去除人脸马赛克的算法pulse

### ISSUE THREAD

**Issue by SekiBetu** [521xueweihan/HelloGitHub#1529]
## 项目推荐
- 项目地址：
https://github.com/adamian98/pulse

- 类别：
Python

- 项目后续更新计划：
算法较完善，关键在于训练模型，后续更新未知

- 项目描述：
这个项目可以通过算法最大程度地去除被轻度打码的人脸的马赛克

- 推荐理由：
去码效果显著，但是由于训练模型的不同，去码后的人脸更像是“新长出来的”

- 截图：
![image](https://user-images.githubusercontent.com/38283893/101875638-df1dee00-3b82-11eb-9c57-474074164ef3.png)

**Comment by 521xueweihan** [comment]
恭喜您！

您推荐的项目，**已成功发布**在 [HelloGitHub 第 57 期](https://hellogithub.com/periodical/volume/57/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
