### ISSUE TITLE
P2P数据分析

### ISSUE THREAD

**Issue by zgbgx** [521xueweihan/HelloGitHub#153]
## 项目推荐
- 项目名称：P2PDA

- 项目地址：https://github.com/zgbgx/P2PDA

- 项目语言：python

- 项目描述：使用从第三方数据网站爬取的数据分析中国P2P行业现状

- 推荐理由：包含爬虫和数据分析两个大的部分，适合爬虫和数据分析以及python 初学者和初级开发者

**Comment by JameJJ** [comment]
你好，在推荐完项目时请将提示信息删除，蟹蟹
