### ISSUE TITLE
Diagram of Python Import System

### ISSUE THREAD

**Issue by pwwang** [521xueweihan/HelloGitHub#1530]
## 项目推荐
- 项目地址：https://github.com/pwwang/python-import-system

- 类别：Python

- 项目后续更新计划：增加更多的代码例子

- 项目描述：
  - 必写：python import机制的图解和实验代码
  - 可选：能让初学者快速了解python import的工作机制
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：

python的import可以让人快速方便的加载模块，但是这背后的机制却没有一个简单易懂的文档。官方文档冗长且对初学者不友好。该项目解构了python import的官方文档，提取关键信息绘制import机制的流程图，可以让初学者快速了解该机制。

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

![image](https://user-images.githubusercontent.com/1188067/101967122-ab20e800-3bd7-11eb-9cb4-a2e0d8c1b1d7.png)

**Comment by 521xueweihan** [comment]
我觉得这个可以写成一篇文章投稿到 HelloGitHub，如果有意加我的微信：xueweihan（备注：python import）
