### ISSUE TITLE
Erupt Framework 通用数据管理框架，零前端代码，仅需简单Java注解即可快速开发后台管理系统 

### ISSUE THREAD

**Issue by erupts** [521xueweihan/HelloGitHub#1531]
## 项目推荐
- 项目地址：https://github.com/erupts/erupt

- 类别：Java

- 项目后续更新计划：
1. 完善模板功能
2. 持续增加更多组件
3. 提供自定义组件功能

- 项目描述：Erupt 可快速的构建管理页面，零前端代码、零CURD、自动建表，仅需单个类文件 + 简洁的注解配置，即可快速开发企业级Admin管理后台！后台管理系统非常重要，但开发存在一定的痛点，如：开发效率低、界面不美观、交互不理想、工作量重复、存在安全漏洞、后端研发被迫写前端代码等。
Erupt提供企业级中后台管理系统的全栈解决方案，提供超多业务组件，简洁美观的后台页面，支持23类数据组件，多种数据源支持，严密的安全策略，压缩研发周期，降低研发成本。
注：我不是代码生成器，代码生成器并非后台开发的最优解。代码生成器的本质还是生成繁琐的后台代码，一旦修改后期生成的代码很难合并，虽然减轻了一部分工作，可解决方式并非最佳。

- 推荐理由：前端零代码，一个Java文件就可快速创建后台管理页面，解决了后台管理系统开发慢周期长等问题。

- 示例代码：
```java
@Erupt(name = "简单的例子")
@Table(name = "t_xxxxxx") //数据库表名
@Entity
public class Simple extends BaseModel {

    @EruptField(
            views = @View(title = "文本"),
            edit = @Edit(title = "文本")
    )
    private String input;
    
    @EruptField(
            views = @View(title = "数值"),
            edit = @Edit(title = "数值")
    )
    private Integer number;

    @EruptField(
            views = @View(title = "布尔"),
            edit = @Edit(title = "布尔")
    )
    private Boolean bool;

    @EruptField(
            views = @View(title = "时间"),
            edit = @Edit(title = "时间")
    )
    private Date date;

}
```

- 截图：
<img width="1544" alt="WechatIMG7" src="https://user-images.githubusercontent.com/20358088/101981133-aa568780-3ca5-11eb-960a-52144d810c33.png">

项目首页：
https://www.erupt.xyz

使用文档：
https://www.yuque.com/yuepeng/erupt

演示地址：
https://www.erupt.xyz/demo （自适应布局支持手机端访问）

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。我决定推荐另外一个类似的项目  el-admin

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
