### ISSUE TITLE
phpbrew

### ISSUE THREAD

**Issue by tyl569** [521xueweihan/HelloGitHub#1532]
## 项目推荐

- 项目地址：

https://github.com/phpbrew/phpbrew

- 类别：PHP

- 项目后续更新计划：

- 项目描述：
  - 必写：Mac上面安装PHP，方便了开发者安装各个版本的PHP以及对应的扩展，快捷的在多个版本之间进行切换
  - 可选：
  - 描述长度（不包含示例代码）: 

首先，phpbrew可以让开发者很容易的找到对应的PHP版本，不用再安装各种brew源，其次，可以安装多个版本的PHP，而且可以通过简单的命令进行版本之间的切换，此外针对对应版本PHP的拓展，安装也非常容易。

- 推荐理由：方便、实用，提高开发效率。多版本PHP共存。

- 示例代码：（可选）

- 截图：（可选）

**Comment by 521xueweihan** [comment]
恭喜您！

您推荐的项目，**已成功发布**在 [HelloGitHub 第 57 期](https://hellogithub.com/periodical/volume/57/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
