### ISSUE TITLE
自荐项目 - ngx_waf 一个 nginx 防火墙模块 | 增加性能测试

### ISSUE THREAD

**Issue by ADD-SP** [521xueweihan/HelloGitHub#1535]
## 项目推荐
- 项目地址：https://github.com/ADD-SP/ngx_waf

- 类别：C

- 项目后续更新计划：暂无，因为基本功能已经完成，后续的主要工作应该是修修补补。

- 项目描述：一个 nginx 防火墙模块，支持 CC 防护、IP 黑白名单（支持拉黑网段）、URL 黑白名单（支持正则）、POST 内容黑名单（支持正则）、Referer 黑白名单（支持正则）、UserAgent 黑名单（支持正则）、GET 参数黑名单（支持正则）和 Cookie 黑名单（支持正则）。最新的测试版已经支持了 IPV6。

- 推荐理由：使用简单，性能有保证，没有复杂的配置，功能比较完整。作为功能同样比较完整且使用比较简单的的 [ngx_lua_waf](https://github.com/loveshell/ngx_lua_waf) 看来已经不更新了，本项目可以看作它的继承和发展。

- 性能测试：

    **测试机器**

    CPU：I5-7300HQ
    内存：8GB
    HostOS：Windows10 x64 2004
    WSL2：Linux DESKTOP-xxxxx 4.19.128-microsoft-standard  SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

    > 使用 WSL2 测试。

    ***

    **版本信息**

    - nginx：1.18.0
    - ngx_waf: v3.0.0-beta-1

    ***

    **配置文件**

    nginx.conf
    ```
    server {
    listen 80;
    server_name  localhost;

    root /path/to/root;
    index index.html;

    waf on;
    waf_mult_mount on;
    waf_mode GET IP;
    waf_rule_path /usr/local/src/ngx_waf/rules/;;
    ```

    ***

    **测试脚本**

    ```shell
    #!/bin/bash

    i=0

    while [ $i -lt 3 ] ; do
        ab -c 100 -n 100000 http://localhost/ >> out.txt
        ((i++))
    done
    ```

    ***

    **防火墙配置**
    
    仅开启 GET 检查和 IP 检查。其中 IPV4 黑名单有约 21W 个 IP 地址块，且没有重叠的地址块。

    ***

    **测试结果概述**

    使用 ab 命令，100 并发，每轮测试请求 10w 次，重复三轮，取平均值。
    - 平均每 10w 次请求所用时间（未开启防火墙）：23.482 s。
    - 平均吞吐率（未开启防火墙）：4,292.98 req/s。
    
    - 平均每 10w 次请求所用时间（开启防火墙）：23.116 s。
    - 平均吞吐率（开启防火墙）：4,326.173 req/s。

    可以看出开启防火墙前后性能没有数量级上的变化。

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by 521xueweihan** [comment]
恭喜您！

您推荐的项目，**已成功发布**在 [HelloGitHub 第 57 期](https://hellogithub.com/periodical/volume/57/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎参与。如需帮助，可以加我的微信：xueweihan（备注您的项目名称）
