### ISSUE TITLE
webster-web抓取框架

### ISSUE THREAD

**Issue by zhuyingda** [521xueweihan/HelloGitHub#154]
## 项目推荐
- 项目名称：webster

- 项目地址：https://github.com/zhuyingda/webster

- 项目语言：javascript

- 项目描述：一个可以抓取网页中ajax异步内容的分布式抓取框架

- 推荐理由：自荐，具备大多数crawl framework不具备的抓取网页中异步数据的能力，基于redis实现了任务队列，支持横向纵向扩展，支持docker一键部署。

- 示例代码：[直接看文档中的Example](http://webster.zhuyingda.com/#Example)

**Comment by 521xueweihan** [comment]
@zhuyingda 您推荐的项目，已成功收录在 [HelloGitHub 第 21 期](https://hellogithub.com/volume/21/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，欢迎 Star ⭐️ 本项目，以便让更多人看到。
