### ISSUE TITLE
自荐项目 - rtty - 在任何地方通过Web访问您的设备的终端

### ISSUE THREAD

**Issue by zhaojh329** [521xueweihan/HelloGitHub#1540]
## 项目推荐
- 项目地址：https://github.com/zhaojh329/rtty

- 类别：C

- 项目后续更新计划：暂无

- 项目描述：
  - 通过 rtty，您可以在任何地方通过 Web 访问您的设备的终端。通过设备 ID 来区分您的不同的设备。它由客户端和服务端组成。客户端采用纯 C 实现（适合嵌入式 Linux 设备）。服务端采用 GO 语言实现，前端界面采用 vue 实现。

- 推荐理由：
  - rtty 非常适合远程维护您的或者您的公司的部署在全球各地的成千上万的 Linux 设备。
  - 客户端采用 C 语言实现，加上依赖库不到 100KB，适合嵌入式 Linux 设备。
  - 支持远程传输文件。

- 截图：
![screen](https://raw.githubusercontent.com/zhaojh329/rtty/doc/screen.gif)
![file](https://raw.githubusercontent.com/zhaojh329/rtty/doc/file.gif)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
