### ISSUE TITLE
《后端架构师技术图谱》

### ISSUE THREAD

**Issue by xyyVee** [521xueweihan/HelloGitHub#1541]
## 项目推荐
- 项目地址：https://github.com/xingshaocheng/architect-awesome

- 类别：Java、开源书籍

- 项目描述：
  - 必写：这是一个后端架构师技术图谱，从基础的数据结构到常用算法，还有后续的并发、操作系统、设计模式、运维、中间件、网络、数据库、性能、安全等等都有很详细介绍和具体的类目拆分。
 
  - 可选：适合从初级到中级到高级的持续学习，包含了架构师需要的所有知识点
 
  - 描述长度（不包含示例代码）: 这是一个后端架构师技术图谱，从基础的数据结构到常用算法，还有后续的并发、操作系统、设计模式、运维、中间件、网络、数据库、性能、安全等等都有很详细介绍和具体的类目拆分。
 

- 推荐理由：信息很全面，虽然都是链接，但是可以看到后端架构师的成长路线

**Comment by 521xueweihan** [comment]
已推荐过
