### ISSUE TITLE
项目自荐 - H5-Dooring | 开源H5页面制作/可视化解决方案

### ISSUE THREAD

**Issue by MrXujiang** [521xueweihan/HelloGitHub#1543]
## 项目推荐 - H5-Dooring | 开源H5页面制作/可视化解决方案
- 项目地址：https://github.com/MrXujiang/h5-Dooring

- 类别:（javascript, nodejs）

- 项目后续更新计划：
  - 添加地图组件
  - 添加悬浮组件
  - 添加二维码生成组件
  - 优化渲染器, 做npm包管理

- 项目描述：
  (H5编辑器)H5-Dooring是一款功能强大，开源免费的H5可视化页面配置解决方案，致力于提供一套简单方便、专业可靠、无限可能的H5落地页最佳实践。技术栈以react为主， 后台采用nodejs开发.

- 推荐理由：
目前一直在维护和更新, github上已有2000+star, 从企业实际角度出发, 做更好用的H5所见即所得的编辑器产品.

- 截图：
![](http://49.234.61.19/uploads/dooring-sdk_1763cbe7028.png)

**Comment by 521xueweihan** [comment]
恭喜您！

您推荐的项目，**已成功发布**在 [HelloGitHub 第 57 期](https://hellogithub.com/periodical/volume/57/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎参与。如需帮助，可以加我的微信：xueweihan（备注您的项目名称）
