### ISSUE TITLE
【项目自荐】Baby-BlockChain 从0搭建区块链教程

### ISSUE THREAD

**Issue by Xunzhuo** [521xueweihan/HelloGitHub#1545]
## 项目推荐
- 项目地址：https://github.com/Xunzhuo/Baby-BlockChain

- 类别：区块链（C、C#、C++、CSS、Go、Java、JS、Kotlin、Objective-C、PHP、Python、Ruby、Swift、其它、书籍、机器学习）

- 项目后续更新计划：
- 深入分析blockchain技术
- 实践部分再扩展

- 项目描述：
  - 必写：从0用Java学习和搭建区块链
  - 可选：区块链入门教程
  - 描述长度（不包含示例代码）: 区块链入门：从0用Java学习和搭建区块链。包括理论和实践两部分，理论部分由快速理解和深入技术两部分，实践部分用Java实现简单区块链。

- 推荐理由：简单易懂学习入门区块链技术

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

![image](https://user-images.githubusercontent.com/48784001/102502734-ee88c400-40b9-11eb-9669-32e96f6560df.png)

## 提示（提交时请删除以下内容）
> 点击上方 “Preview” 更方便地阅读以下内容，

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
我认为这只是一篇文章，不能作为项目推荐。如果有兴趣额可以投稿到 HelloGitHub 我的微信：xueweihan（备注：Java 区块链）
