### ISSUE TITLE
【项目推荐】Swift 项目 | 专为Swift开发人员构建的静态网站生成器

### ISSUE THREAD

**Issue by liumenghua** [521xueweihan/HelloGitHub#1546]
## 项目推荐
- 项目地址：https://github.com/JohnSundell/Publish

- 类别：Swift

- 项目后续更新计划：swiftbysundell.com 全部由Publish生成，作者热爱开源，持续维护更新中。

- 项目描述：

    专为Swift开发人员构建的静态网站生成器。让使整个网站都可以使用Swift构建，并且支持主题，插件和大量其他强大的自定义选项。

- 推荐理由：JohnSundell 大神作品，3k star，Swift 构建网站不是梦

- 示例代码：当使用Publish时，每个网站都被定义为一个Swift包，它充当如何生成和部署网站的配置-所有这些都使用本机的type-safeSwift代码。例如，以下是食品配方网站的配置：

```swift
struct DeliciousRecipes: Website{
    enum SectionID: String, WebsiteSectionID{
        case recipes
        case links
        case about
    }

    struct ItemMetadata: WebsiteItemMetadata{
        var ingredients: [String]
        var preparationTime: TimeInterval
    }

    var url = URL(string: "https://cooking-with-john.com")!
    var name = "Delicious Recipes"
    var description = "Many very delicious recipes."
    var language: Language { .english }
    var imagePath: Path? { "images/logo.png" }
}
```

**Comment by 521xueweihan** [comment]
恭喜您！

您推荐的项目，**已成功发布**在 [HelloGitHub 第 57 期](https://hellogithub.com/periodical/volume/57/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
