### ISSUE TITLE
【项目自荐】StaticScript: 类TypeScript的静态编译型语言

### ISSUE THREAD

**Issue by ApsarasX** [521xueweihan/HelloGitHub#1548]
## 项目推荐
- 项目地址： https://github.com/StaticScript/StaticScript

- 类别：C++

- 项目后续更新计划：StaticScript后续将支持更多TypeScript的高级特性

- 项目描述：TypeScript是JavaScript的超集，提供了更强大的静态类型检查功能，但TypeScript没有自己的运行时，只能编译到JavaScript再执行，而StaticScript是一门类TypeScript的静态编译型语言，可以编译为可执行文件执行。StaticScript的语法99%兼容TypeScript, 可以认为StaticScript是TypeScript的一种真子集。

- 推荐理由：
    - StaticScript通常编译为二进制可执行文件进行执行，对于大多数计算密集型的任务，使用StaticScript编写出来的程序通常要比使用TypeScript/JavaScript编写出来的程序性能好很多
    - StaticScript的源码结构清晰明了，对初学者友好，阅读StaticScript的源码可以使得有一定基础的初学者也能够自制编程语言
  
- 示例代码：

```ts
// 斐波那契额列函数
function fibonacci(n: number): number {
    if(n <= 1) {
        return 1;
    }
    return fibonacci(n - 1) + fibonacci(n - 2);
}

ss_println_integer(fibonacci(20));
```

- 截图
![tquxh-zi0bj](https://user-images.githubusercontent.com/24390069/102704517-72f46600-42b7-11eb-8356-2c31baf01bd4.gif)

**Comment by linvs** [comment]
厉害了~~~~学习一下

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by ApsarasX** [comment]
> 非常感谢您推荐项目。
> 
> **该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
> 期待持续完善该项目，后续推荐更多的项目。
> 
> 再次感谢您对 HelloGitHub 的支持 🙏


该项目文档他已包含项目介绍 (必须)、特性 (必须)、快速开始 (必须)，star 200+

请问是哪项不符合审核标准呢，我以后完善一下
