### ISSUE TITLE
自荐项目 | 工业表面缺陷检测数据集及论文集SurfaceDD

### ISSUE THREAD

**Issue by Charmve** [521xueweihan/HelloGitHub#1549]
## 项目自荐
- 项目地址：https://github.com/Charmve/Surface-Defect-Detection

- 类别：机器学习、计算机视觉

- 项目后续更新计划：
  - 继续跟进表面缺陷检测论文方法；
  - 收集更多工业场景下表面缺陷检测数据集；

- 项目描述：
  - 必写：机器学习的应用很难落地的原因，很大一部分在于没有/训练测试样本——``数据集``。尤其是在计算机视觉的不断发展，其在工业应用场景下发挥着巨大的影响，现已成为计算机视觉领域的研究热点。但数据集的缺失，给算法研发、场景落地带来致命影响。项目开源者长期关注表面缺陷检测方向，收集整理了目前开放的数据集，挑选出在学界和业界认可较高的数据集。在此基础上，专门整理了自2019年7月以来最新的顶会论文和作者解读。
  - 可选：适用于表面缺陷检测领域的从业者、研究者、学习者。

- 推荐理由：<strong>目前可以说是最全的开源表面缺陷检测数据集</strong>
  - 完整详细的README；
  - 拥有DeepPCB实训参考项目，开源详细源代码；
  - 读者反馈较好
     - CSDN: <img src="https://img.shields.io/badge/访问-5k+-green" alt="visit-5k+"> &nbsp;<img src="https://img.shields.io/badge/收藏-93-blue" alt="收藏-93">
  - 编写中英文文档，方便读者阅读

- 截图：（可选）gif/png/jpg

<div align=center><img src="https://github.com/Charmve/Surface-Defect-Detection/raw/master/metal_surface.png"></div>
<p align=center>Figure 1. Metal Surface: KolektorSDD</p>
<br>
<br>

<div align=center><img src="https://github.com/tangsanli5201/DeepPCB/raw/master/fig/test.jpg" width="375" style="margin:20">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<img src="https://github.com/tangsanli5201/DeepPCB/raw/master/fig/template.jpg" width="375" style="margin:20"> 
 </div>
<div align=center>
 an example of the tested image 
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
 the corresponding template image
 </div>

<p align=center>Figure 2. PCB Inspection Dataset.</p>
<br>

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by 521xueweihan** [comment]
恭喜您！

您推荐的项目，**已成功发布**在 [HelloGitHub 第 57 期](https://hellogithub.com/periodical/volume/57/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎参与。如需帮助，可以加我的微信：xueweihan（备注您的项目名称）
