### ISSUE TITLE
Hello Comic

### ISSUE THREAD

**Issue by pipiliang** [521xueweihan/HelloGitHub#155]
## 项目推荐
- 项目名称：hello comic

- 项目地址：https://github.com/pipiliang/hello-comic

- 项目语言：markdown

- 项目描述：收集和程序员有关的漫画（还在不断收集中）。

- 推荐理由：让苦逼的程序员在繁忙之中也可以乐一乐。

- 截图：
# Hello Comic
A comic book for cute programmers，收集和程序员有关的漫画。

![](http://www.jeffpalm.com/fox/fox.jpg)

- 国内
  - 程序员幽默漫画
  - 极客漫画
  - 神秘的程序员们
  - 架构师成长之路
  - Lae程序员小漫画
  - 数码战争
  - 程序员人生
  - ...

- 国外
  - Dan Williams
  - ...

**Comment by 521xueweihan** [comment]
@pipiliang 很有意思的项目，坚持维护下去。希望有更多人可以加入到你的项目，加油！

**Comment by 521xueweihan** [comment]
@pipiliang  您推荐的项目，已成功收录在 [HelloGitHub 第 21 期](https://hellogithub.com/volume/21/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，欢迎 Star ⭐️ 本项目，以便让更多人看到。
