### ISSUE TITLE
自荐项目 - 「PrettyZoo」 最美 Zookeeper 桌面客户端

### ISSUE THREAD

**Issue by vran-dev** [521xueweihan/HelloGitHub#1551]
## 项目推荐
- 项目地址：https://github.com/vran-dev/PrettyZoo

- 类别：Java、Zookeeper

- 项目后续更新计划：支持命令行操作

- 项目描述：

 PrettyZoo 是一个基于 Apache Curator 和 JavaFX 实现的高颜值 Zookeeper 图形化管理客户端。
使用了 Java 的模块化（Jigsaw）技术，并基于 JPackage 打包了多平台的安装包（支持 windows、Linux、MAC）。

如果你在学习 Dubbo、Elastic-Job 等源码， 那 PrettyZoo 绝对可以为你事半功倍，它能更直观的为你展示这些框架是如何使用 Zookeeper 的。

- 推荐理由：

    -  zookeeper 集群管理，节点增删该查这都是基本功能
    - 生产环境不能直连？prettyZoo 支持 SSH Tunnel ，为君解忧
    - 谁说程序员就没有审美了？prettyZoo 的根基就是**颜值**
    - 既然是面向极客的，命令行操作也得有（正在研发中......）

- 截图：

![main](https://user-images.githubusercontent.com/12870335/102896472-67fd2980-44a1-11eb-9fe3-9dcc8b073155.png)

![server](https://user-images.githubusercontent.com/12870335/102896484-6e8ba100-44a1-11eb-9f3f-69436eafadcf.png)

![node-list](https://user-images.githubusercontent.com/12870335/102896502-75b2af00-44a1-11eb-9dd3-36c3dd92b121.png)

![node-search](https://user-images.githubusercontent.com/12870335/102896523-7ba89000-44a1-11eb-8acc-89e08b4ec4c3.png)

![node-add](https://user-images.githubusercontent.com/12870335/102896527-7ea38080-44a1-11eb-897e-aed0be885e4c.png)

**Comment by 521xueweihan** [comment]
恭喜您！

您推荐的项目，**已成功发布**在 [HelloGitHub 第 57 期](https://hellogithub.com/periodical/volume/57/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

最后，HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎参与。如需帮助，可以加我的微信：xueweihan（备注您的项目名称）
