### ISSUE TITLE
自荐项目 - 「Keras4Torch」 开箱即用的pytorch模型训练高级API

### ISSUE THREAD

**Issue by blueloveTH** [521xueweihan/HelloGitHub#1552]
## 项目推荐
- 项目地址：https://github.com/blueloveTH/keras4torch

- 类别：Python、机器学习

- 项目后续更新计划：不断完善对原生keras的兼容性，长期维护

- 项目描述：
`keras4torch`是一个开箱即用的pytorch模型训练高级API。它提供了以pytorch为后端的keras实现。`keras4torch`提供了两种工作流，NumPy工作流的接口与原生keras最大程度兼容，DataLoader工作流则提供强大的灵活性。基于此框架，训练模型的过程可以被大大简化。

- 推荐理由：据我们了解，`keras4torch`是目前唯一的兼容性keras实现，这意味着keras的训练代码能够几乎不加修改的运用于`keras4torch`。该项目旨在帮助具有keras使用经验的pytorch初学者，降低工程迁移（从keras迁移到torch）的成本。此外，keras用户也可以使用`keras4torch`来测试torch模型。

- 示例代码：
```python
import torchvision
import torch.nn as nn
import keras4torch as k4t

# 加载原生torch模型
model = torchvision.models.resnet50(num_classes=10)

# 封装为keras模型并集成训练组件
model = k4t.Model(model)

# 配置优化器和损失函数
model.compile(optimizer='adam', loss=nn.CrossEntropyLoss(), metrics=['acc'])

# 训练模型
history = model.fit(x_train, y_train,
                	epochs=30,
                	batch_size=512,
                	validation_split=0.2,
                	)

# 评估模型
model.evaluate(x_test, y_test)
```

**Comment by 521xueweihan** [comment]
您话，这个项目不能收录到月刊中。

“一个开箱即用的pytorch模型训练高级API。它提供了以pytorch为后端的keras实现。”  

这就话我没读懂，

Keras4Torch provides a high-level API to train PyTorch models compatible with Keras. 

你把文档的这段话写成中文它不香吗
