### ISSUE TITLE
项目推荐-DeepMoji

### ISSUE THREAD

**Issue by sz-p** [521xueweihan/HelloGitHub#1555]
## 项目推荐
- 项目地址：[DeepMoji](https://github.com/bfelbo/DeepMoji)

- 预览地址：[deepmoji.mit.edu](https://deepmoji.mit.edu/)

- 类别：请从中选择（Python、机器学习）

- 项目后续更新计划：最后更新于2018年11月10日

- 项目描述：
  一个根据包含emoji推文训练的模型。以了解语言是如何用于表达情感的，一段文本最可能对应的emoji。

- 推荐理由：项目有趣、内容充足、易于学习。 包含一个机器学习项目应有的所有内容，示例、模型、数据、测试。源码等。

- 截图：
![image](https://user-images.githubusercontent.com/14040327/103185626-25e84380-48f8-11eb-8751-d78fc00307bb.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 58 期](https://hellogithub.com/periodical/volume/58/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
