### ISSUE TITLE
项目自荐 | PaperWeeklyAI - 迈微AI顶会论文研读

### ISSUE THREAD

**Issue by Charmve** [521xueweihan/HelloGitHub#1557]
## 项目推荐
- 项目地址：https://github.com/Charmve/PaperWeeklyAI

- 类别：书籍、机器学习、计算机视觉

- 项目后续更新计划：
  - 缩小关注点，持续关注计算机视觉领域CVPR、ECCV顶会论文分析；
  - 发布最新AI动向，打通学习与求职、科研之间的桥梁；
  - 完善每篇研读论文的推荐理由；
  - 简历电子化在线阅读网页，方便中国大陆区读者访问；

- 项目描述：
  - 必写：每周研读机器学习、计算机视觉、深度学习、NLP、AI前沿技术动态的相关论文，总结作者学习过程中踩过的坑，分享机器学习免费电子书。现已发布论文研读文章200+，还会持续更新。
  - 可选：适合有一定机器学习、数学专业基础的研究生及相关学习研究人员。
  - 描述长度（不包含示例代码）: 迈微AI研习社精选论文研读文章，快速掌握最新前言研究方法及动向。

- 推荐理由：
  - 解决入门者对论文研究动态把握不到位、会议论文、电子书难求的棘手问题；
  - 每篇解读论文都包含论文arXiv论文下载、github源代码，部分研读文章有项目主页、视频介绍；
  - 总结了图像分割、目标检测的必读论文 30 篇，LeNet、FCNN、U-Net等，并给出PyTorch实现源代码。

- 示例代码：

### 本项目包括

<table>
  <thead>
    <tr>
      <th style="text-align: left">👀 <a href="https://github.com/ChromeWei/PaperWeeklyAI">迈微论文研读</a></th>
      <th style="text-align: left">🐒 <a href="https://github.com/ChromeWei/PaperWeeklyAI/tree/master/00_GuideBooksPDF(English%2BChinese)">AI进阶指南</a></th>
      <th style="text-align: left">📚 <a href="https://github.com/ChromeWei/hello-algorithm/tree/master/%E6%B8%85%E6%99%B0%E7%89%88%E7%94%B5%E5%AD%90%E4%B9%A61000%E6%9C%AC">超清电子书10000本</a></th>
      <th style="text-align: left">🐒 <a href="https://github.com/ChromeWei/hello-algorithm/tree/master/%E4%B8%93%E6%A0%8F">计算机IT必备</a></th>
      <th style="text-align: left" colspan="2">🚀 <a href="https://github.com/ChromeWei/hello-algorithm/tree/master/%E5%A4%A7%E5%8E%82%E9%9D%A2%E7%BB%8F%E6%B1%87%E6%80%BB100%E7%AF%87">大厂面经汇总指南</a></th>
      
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align: left">🍄 <a href="https://github.com/Charmve/PaperWeeklyAI/tree/master/03_Maiwei%20AI%20PaperWeekly/01_NLP%E8%AE%BA%E6%96%87%E7%A0%94%E8%AF%BB">NLP论文研读</a></td>
      <td style="text-align: left">🌽 <a href="https://github.com/Charmve/PaperWeeklyAI/tree/master/00_GuideBooksPDF(English%2BChinese)">机器学习/深度学习理论篇</a></td>
      <td style="text-align: left">🐒 <a href="https://github.com/Charmve/hello-algorithm/tree/master/%E8%B6%85%E6%B8%85%E6%80%9D%E7%BB%B4%E5%AF%BC%E5%9B%BE100%E5%BC%A0">超清思维导图集锦</a></td>
      <td style="text-align: left">👺 <a href="https://github.com/Charmve/hello-algorithm/tree/master/%E4%B8%93%E6%A0%8F/%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F">专栏：学习os</a></td>
      <td style="text-align: left">🍏 <a href="https://github.com/Charmve/hello-algorithm/tree/master/%E5%A4%A7%E5%8E%82%E9%9D%A2%E7%BB%8F%E6%B1%87%E6%80%BB100%E7%AF%87/C%26C%2B%2B">面试：C&amp;C++</a></td>
      <td>🍇 <a href="https://github.com/ChromeWei/hello-algorithm/tree/master/%E5%A4%A7%E5%8E%82%E9%9D%A2%E7%BB%8F%E6%B1%87%E6%80%BB100%E7%AF%87/Java">面试：Java</a></td>
    </tr>
    <tr>
      <td style="text-align: left">🍐 <a href="https://github.com/Charmve/PaperWeeklyAI/tree/master/03_Maiwei%20AI%20PaperWeekly/02_%E8%AE%A1%E7%AE%97%E6%9C%BA%E8%A7%86%E8%A7%89%E8%AE%BA%E6%96%87">CV顶会</a></td>
      <td style="text-align: left">🍉 <a href="https://github.com/Charmve/PaperWeeklyAI/tree/master/04_AppliedML">机器学习实战篇</a></td>
      <td style="text-align: left">👺 <a href="https://github.com/Charmve/PaperWeeklyAI/tree/master/00_GuideBooksPDF(English%2BChinese)">电子书：机器学习&amp;深度学习</a></td>
      <td style="text-align: left">📡 <a href="https://github.com/Charmve/hello-algorithm/tree/master/%E4%B8%93%E6%A0%8F/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C">专栏：学习网络</a></td>
      <td style="text-align: left">🍖 <a href="https://github.com/Charmve/hello-algorithm/tree/master/%E5%A4%A7%E5%8E%82%E9%9D%A2%E7%BB%8F%E6%B1%87%E6%80%BB100%E7%AF%87/%E6%9E%B6%E6%9E%84%E5%B8%88">面试：架构师</a></td>
      <td>🍅 <a href="https://github.com/Charmve/hello-algorithm/tree/master/%E5%A4%A7%E5%8E%82%E9%9D%A2%E7%BB%8F%E6%B1%87%E6%80%BB100%E7%AF%87/%E5%89%8D%E7%AB%AF">面试：前端</a></td>
    </tr>
    <tr>
      <td style="text-align: left">📡 <a href="https://github.com/Charmve/PaperWeeklyAI/tree/master/00_GuideBooksPDF(English%2BChinese)/05_AI%E8%AE%BA%E6%96%87%E5%BF%85%E8%AF%BB%E7%AF%87%E7%9B%AE10%E7%AF%87">AI论文必读篇目10篇</a></td>
      <td style="text-align: left">📚 <a href="https://github.com/ChromeWei/PaperWeeklyAI/tree/master/00_GuideBooksPDF(English%2BChinese)">机器学习/Linux电子书</a></td>
      <td style="text-align: left">📝 <a href="https://github.com/Charmve/PaperWeeklyAI/tree/master/00_GuideBooksPDF(English%2BChinese)">电子书：编程与算法</a></td>
      <td style="text-align: left">📺 <a href="https://github.com/ChromeWei/hello-algorithm/tree/master/%E4%B8%93%E6%A0%8F/Linux">专栏：学习linux</a></td>
      <td style="text-align: left">🚀 <a href="https://github.com/ChromeWei/hello-algorithm/tree/master/%E5%A4%A7%E5%8E%82%E9%9D%A2%E7%BB%8F%E6%B1%87%E6%80%BB100%E7%AF%87/Python">面试：Python</a></td>
      <td style="text-align: left">✏️ <a href="https://github.com/Charmve/LeetCode4FLAG">刷题：LeetCode4FLAG</a></td>
    </tr>
    <tr>
      <td style="text-align: left">🎅 <a href="https://github.com/Charmve/PaperWeeklyAI/tree/master/00_GuideBooksPDF(English%2BChinese)/06_CVPR2020%E8%AE%BA%E6%96%8730%E7%AF%87">CVPR2020论文30篇</a></td>
      <td style="text-align: left">🍏 <a href="https://github.com/Charmve/ML-Basics">ML-Basics</a></td>
      <td style="text-align: left">📚 <a href="https://github.com/Charmve/PaperWeeklyAI/tree/master/00_GuideBooksPDF(English%2BChinese)">电子书：网络编程</a></td>
      <td style="text-align: left">🎅 <a href="https://github.com/Charmve/hello-algorithm/tree/master/%E4%B8%93%E6%A0%8F/Mysql">专栏：学习mysql</a></td>
      <td style="text-align: left">🍄 <a href="https://github.com/Charmve/hello-algorithm/tree/master/%E5%A4%A7%E5%8E%82%E9%9D%A2%E7%BB%8F%E6%B1%87%E6%80%BB100%E7%AF%87/Mysql">面试：Mysql</a></td>
      <td> </td>
    </tr>
    <tr>
      <td style="text-align: left">🌽 <a href="https://github.com/Charmve/PaperWeeklyAI/tree/master/04_AppliedML">AppliedML</a></td>
      <td style="text-align: left">🍑 <a href="https://github.com/Charmve/PaperWeeklyAI/tree/master/06_ML-Surveys">ML-Surveys</a></td>
      <td style="text-align: left"> </td>
      <td style="text-align: left">🆎 <a href="https://github.com/Charmve/hello-algorithm/tree/master/%E4%B8%93%E6%A0%8F/%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F">专栏：学习设计模式</a></td>
      <td style="text-align: left">📝 <a href="https://github.com/Charmve/hello-algorithm/tree/master/%E4%B8%93%E6%A0%8F/%E5%89%91%E6%8C%87offer">面试：剑指offer</a></td>
      <td> </td>
    </tr>
  </tbody>
</table>

- 截图：

![image](https://user-images.githubusercontent.com/29084184/103194153-a0758b00-4919-11eb-8f06-e8a86d6ceca7.png)

## applied-ml
Curated papers, articles, and blogs on **data science & machine learning in production**. ⚙️

📚 Papers by organizations sharing their work on applied data science & machine learning.

[![contributions welcome](https://img.shields.io/badge/contributions-welcome-brightgreen.svg?style=flat)](./CONTRIBUTING.md) [![Summaries](https://img.shields.io/badge/summaries-in%20tweets-%2300acee.svg?style=flat)](https://twitter.com/eugeneyan/status/1288236455228137473) ![HitCount](http://hits.dwyl.com/eugeneyan/applied-ml.svg)

Figuring out how to implement your ML project? Learn how other organizations did it:

- **How** the problem is framed 🔎(e.g., personalization as recsys vs. search vs. sequences)
- **What** machine learning techniques worked ✅ (and sometimes, what didn't ❌)
- **Why** it works, the science behind it with research, literature, and references 📂
- **What** real-world results were achieved (so you can better assess ROI ⏰💰📈)

P.S., Want a summary of ML advancements? 👉[`ml-surveys`](https://github.com/Charmve/PaperWeeklyAI/tree/master/06_ML-Surveys)

<br>

<a href="https://github.com/Charmve/PaperWeeklyAI">More Details --> </a>

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
