### ISSUE TITLE
【自荐】Algorithm-Guide：算法和数据结构系统教程（目前Stars>1000）

### ISSUE THREAD

**Issue by Xunzhuo** [521xueweihan/HelloGitHub#1558]
## 项目推荐
- 项目地址：https://github.com/Xunzhuo/Algorithm-Guide

- 类别：算法&数据结构

- 项目后续更新计划：算法部分基本完成，数据结构还有有一些未完成部分，空闲时会加快完善！同时后续会推出算法题解，让Repo涵盖算法和数据结构所需的所有因素。

- 项目描述：
【算法和数据结构教程】带你系统掌握核心知识，轻松解决面试算法难题。
本仓库主要有两个分支：
master分支：最近的新分支，也是以后日常维护的主分支😀，内容为算法和数据结构的教程。
Collections 分支：以前的主分支，详细整理了算法和数据结构的资料，现作为辅助分支。

- 推荐理由：不仅有系统的算法&数据结构教程，还有刷题攻略教你如何刷题，同时在辅助分支还有系统学习算法的资料总结。掌握算法和数据结构，这个仓库基本涵盖大部分内容。

- 截图：

![截屏2020-12-28 下午2 37 46](https://user-images.githubusercontent.com/48784001/103194632-32ca5e80-491b-11eb-97a8-8e4c8f0b3987.png)
![截屏2020-12-28 下午2 38 52](https://user-images.githubusercontent.com/48784001/103194639-39f16c80-491b-11eb-8606-4b57f03f49c4.png)
![截屏2020-12-28 下午2 38 57](https://user-images.githubusercontent.com/48784001/103194641-3bbb3000-491b-11eb-9e8f-3bea52098fd2.png)

**Comment by 521xueweihan** [comment]
加油，完成 上图中的 TODO 后再来推荐吧

**Comment by Xunzhuo** [comment]
欧克





削微寒 <notifications@github.com> 于2021年1月25日周一 下午4:20写道：
