### ISSUE TITLE
【开源项目推荐】Nonstop：外链自动跳转插件

### ISSUE THREAD

**Issue by Yuxiaoy1** [521xueweihan/HelloGitHub#1560]
## 项目推荐
- 项目地址：https://github.com/yuxiaoy1/nonstop

- 类别：JS

- 项目后续更新计划：增加支持更多无法直接跳转到外链的网站

- 项目描述：Nonstop 是一个浏览器扩展，可以规避知乎、微博、简书，QQ 邮箱上面的外部链接跳转的确认页面，自动跳转到外部网址。

- 推荐理由：知乎，微博，简书，QQ 邮箱等网站的外链均需要手动复制再打开，影响浏览体验，使用此扩展可以实现自动跳转，无缝连接到外部网址，提升用户浏览体验。

- 截图：

![Nonstop](https://cdn.jsdelivr.net/gh/yuxiaoy1/nonstop/nonstop.gif)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
