### ISSUE TITLE
【自荐】生成国产达梦数据库表结构文档

### ISSUE THREAD

**Issue by ZoolYe** [521xueweihan/HelloGitHub#1566]
## 项目推荐
- 项目地址：https://github.com/ZoolYe/dmdb-document

- 类别：Java

- 项目后续更新计划：增加数据库配置页面，提供动态配置数据源

- 项目描述：
  > dmdb-document是一个生成达梦数据库表结构文档Java项目
  > 解决目前市面上还没有达蒙数据库生成表结构文档的相关工具

- 推荐理由：简单好用，支持达梦8、达梦7数据库

- 截图：![文档样式](https://github.com/ZoolYe/dmdb-document/blob/master/start/src/main/resources/static/dm.png?raw=true)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
