### ISSUE TITLE
【开源项目】lastversion：轻松获取项目的最新版本（避开风格杂乱的版本号）

### ISSUE THREAD

**Issue by ADD-SP** [521xueweihan/HelloGitHub#1569]
## 项目推荐
- 项目地址：https://github.com/dvershinin/lastversion

- 类别：Python

- 项目后续更新计划：支持解析 `.spec` 文件（**本人并非项目作者，是根据项目的 issue 发现的**）。

- 项目描述：包含命令行工具和 `Python` 库，它可以**避开不同项目作者使用的不同风格的版本号**，获取一个项目的最新版本号，下载或安装它们。本项目主要用于 `build system`，比如自动更新脚本。支持从下面这些网站搜索：
  * GitHub
  * GitLab
  * PyPI
  * BitBucket
  * Mercurial
  * SourceForge
  * 任何以 RSS/ATOM 订阅方式发布软件网站。

- 推荐理由：虽然是老外的项目，但是有中文文档。下面的这些做法都会给我寻找最新版本造成困难，如果你需要处理这些麻烦（比如编写自动更新脚本），你可以使用 lastversion，它可以让你获取一个项目的格式良好的版本号，或者源代码和随新版本发布的其它资源（如 `.exe`）。
  * 许多开源项目所使用的版本标签格式并不一致，有的可能是 `release-2.1.3`，有的可能是 `name-2.1.3-2019`，即包含一些带有作者个性的文本；
  * 有时会在发布候选版本的时候没有将其标记为预发布版，而是作为正式版发布，典型情况就是版本标签为 `v2.1.3-rc1`，但是发布时并未标记为预发布版；
  * 版本标签可能有的带有 `v` 前缀如 `v2.1.3`， 有的不带如 `2.1.3`，甚至同一个项目也会今天带，明天不带；
  * 发布者可能会更改版本标签的格式。

- 示例代码：
  * 获取某个项目的最新版本号（两行命令等价）
     ```bash
     lastversion https://github.com/gperftools/gperftools
     # 作者的版本标签：gperftools-2.8.1
     # 本项目提供的版本标签：2.8.1

     lastversion gperftools/gperftools
     # 作者的版本标签：gperftools-2.8.1
     # 本项目提供的版本标签：2.8.1
    ```
  * 获取最新的 Linux 版本号和最新的 Wordpress 版本号
    ```bash
    lastversion linux
    # 作者的版本标签：v5.10
    # 本项目提供的版本标签：5.10
    lastversion wordpress
    # 作者的版本标签：5.6
    # 本项目提供的版本标签：5.6
    ```
  * 获取 PowerToys 发布的可执行文件的下载链接
    ```bash
    lastversion --assets --filter exe powertoys
    #> https://github.com/microsoft/PowerToys/releases/download/v0.29.3/PowerToysSetup-0.29.3-x64.exe
    ```
  * 下载某个项目的最新版本
    ```bash
    lastversion mautic/mautic --download 
    ```
  * 使用 Python 代码检查 `mautic` 是否有比 `1.2.3` 更加新的版本。
    ```python
    from lastversion import lastversion
    latest_version = lastversion.has_update(repo="mautic/mautic", current_version='1.2.3')
    if latest_version:
        print('mautic 有新版本：{}'.format(str(latest_version)))
    else:
        print('mautic 暂无新版本')
    ```

- 截图：![](https://camo.githubusercontent.com/eb129e84cf3490362c699ffa2afa12031479734c06ab20d233a6a6696378c907/68747470733a2f2f7777772e6765747061676573706565642e636f6d2f696d672f6c61737476657273696f6e2e676966)

**Comment by 521xueweihan** [comment]
满分项目描述，推！

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 58 期](https://hellogithub.com/periodical/volume/58/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
