### ISSUE TITLE
shadowsocks 账号批量下载

### ISSUE THREAD

**Issue by phobal** [521xueweihan/HelloGitHub#157]
## 项目推荐
- 项目名称：
shadowsocks-free-account
- 项目地址：
https://github.com/phobal/shadowsocks-free-account
- 项目语言：
JavaScript
- 项目描述：
利用 Nodejs 爬取一个免费提供 ss 账号的网站，并提供一个网页来支持批量下载爬取的账号，能一键导入到 ss 客户端
- 推荐理由：
支持账号批量下载，不用手动输入，减少操作以及错误率，多终端支持，高速、稳定，关键还免费😝
- 示例代码：

- 截图：

### 编辑完推荐项目的信息，下述提示信息**请删除**
非常感谢推荐这么好的项目

如您推荐的项目收录到《HelloGitHub》月刊，您的GitHub帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/contributors.md)，**同时会在此 issues 中通知您**。

再次感谢您对《HelloGitHub》项目的支持！

HelloGitHub 网站：https://hellogithub.com

**Comment by 521xueweihan** [comment]
@phobal 为保证本项目的“长治久安”，暂不推荐此类项目，望理解。😅

**Comment by jp1017** [comment]
Anyway, Got it. @521xueweihan 太坏了,收了人家东西,嘴上说不要,, :100:

**Comment by phobal** [comment]
没事儿，理解，有需要的朋友肯定能找到的
