### ISSUE TITLE
【自荐】ZFILE：支持挂载各种存储源并列表展示，在线预览，下载

### ISSUE THREAD

**Issue by zhaojun1998** [521xueweihan/HelloGitHub#1571]
## 项目推荐
- 项目地址：https://github.com/zhaojun1998/zfile

- 类别：Java

- 项目后续更新计划：
    - 支持 SharePoint 国际版/世纪互联版
    - 支持自定义文件预览格式
    - 支持内置短链功能
    - 支持图片画廊模式
    - 支持视频播放列表功能
    - 支持自定义 API clientId clientSecret 等信息
    - 支持在线日志诊断功能

- 项目描述：
  - 主要用途：挂载存储在各种位置的文件，用于展示下载或分享给朋友，但定位是个人公开使用的列目录程序，故不支持多用户，多权限等功能。
  - 使用场景：如将常用的安装包，或公司/部门内部常用的资料挂载以用于访问

- 推荐理由：个人网盘，页面进阶美观，安装便捷

- 截图：
![前台首页](https://cdn.jun6.net/2020/04/19/d590d2bde13bb.png)
![后台设置-驱动器设置](https://cdn.jun6.net/2020/04/19/d58fc2debcce8.png)
![后台设置-驱动器设置](https://cdn.jun6.net/2020/04/19/0f321e47fc18c.png)
![后台设置-显示设置](https://cdn.jun6.net/2020/04/19/6d7c300b89671.png)

**Comment by 521xueweihan** [comment]
推过了：https://hellogithub.com/periodical/search/?q=https://github.com/zhaojun1998/zfile#zfile
