### ISSUE TITLE
【自荐】PHPEnum：和Java枚举一样好用的枚举类库

### ISSUE THREAD

**Issue by yinfuyuan** [521xueweihan/HelloGitHub#1573]
## 项目推荐

- 项目地址：https://github.com/yinfuyuan/php-enum

- 类别：PHP

- 项目后续更新计划：
    - 增加PHP7和PHP8的支持
    - 增加严格类型校验

- 项目描述：
    - 项目用途：这个项目使PHP可以像使用Java枚举一样使用枚举类
    - 使用场景：Api返回统一格式错误码以及其他表示各种状态的任意可以使用枚举的地方
    
- 推荐理由：真正解决了在PHP中枚举也可以像Java那样使用属性值

- 示例代码：
    
```
class Color extends \PhpEnum\Enum
{
    const RED = ["FF0000"];
    const GREEN = ["00FF00"];
    const BLUE = ["0000FF"];

    private string $hexadecimal;

    protected function construct(string $hexadecimal)
    {
        $this->hexadecimal = $hexadecimal;
    }

    public function getHexadecimal(): string
    {
        return $this->hexadecimal;
    }
}
```

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
