### ISSUE TITLE
【项目推荐】containers-the-hard-way：用go实现docker的精简版

### ISSUE THREAD

**Issue by sandaawa** [521xueweihan/HelloGitHub#1576]
## 项目推荐
- 项目地址：https://github.com/shuveb/containers-the-hard-way

- 类别：Go

- 项目后续更新计划：

- 项目描述：用简短的代码实现docker的核心功能，使容器初学者了解容器在linux系统级别是如何调度的

- 推荐理由：为想要了解docker实现的同学提供一个思路

- 示例代码：

- 截图：![png](https://camo.githubusercontent.com/f9bcce9bbd567468fc468cda6307aeec6f76979cd9be83c85d897028d11c1355/68747470733a2f2f756e697869736d2e6e65742f77702d636f6e74656e742f75706c6f6164732f323032302f30362f476f636b65722e706e67)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 58 期](https://hellogithub.com/periodical/volume/58/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
