### ISSUE TITLE
【自荐】基于 Vue 3.x 及相关全家桶技术栈的电商网站

### ISSUE THREAD

**Issue by Nick930826** [521xueweihan/HelloGitHub#1577]
## 项目推荐
- 项目地址：https://github.com/newbee-ltd/newbee-mall-vue3-app

- 类别：JS、Vue

- 项目后续更新计划：后期除了完善流程之外，还会继续拓展出 TS 版本、小程序版本、以及原生 app。

- 项目描述：
这是一个电商类的 C 端 H5 网页项目，使用以 Vue 3.x 为核心，以及周边的最新插件如 Vue-Router 4.x、Vuex 4.x、Flexible.js、Vant 4.x 等等。项目分几个模块，首页、类型分类、搜索、购物车、订单列表、个人中心、地址管理、登录注册。麻雀虽小五脏俱全，该有的基本上都有涉及到。

- 推荐理由：
1、项目对新手十分友好，只要有一点 Vue 的知识基础，分分钟启动项目学习。
2、本项目采用的是 Vue 3.x 最新的技术栈。Vue 3.x 是 9 月 18 号出的，而截止目前，项目已经积累 700+ star，好评率可见一斑。
3、项目采用的 Vant 3.x 最新的移动端组件框架，并且在项目设计上也比较讲究细节，尽可能做到美观简洁。
4、对于 Vue 2.x 迁移 Vue 3.x 的朋友帮助也很大，项目内涵盖许多 Vue 2.x -> Vue 3.x 的语法。

- 截图

![](https://s.yezgea02.com/1610000502017/WeChat39fc1d5209dcfc84ece8f50cb706a41e.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 58 期](https://hellogithub.com/periodical/volume/58/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者加入进来，让更多人知道您的项目。阅读完我们的往期文章，有兴趣的话可以加我的微信：xueweihan（备注您发起的项目名称）
