### ISSUE TITLE
【自荐】Android Gralde Plugin 字节码操作Demo

### ISSUE THREAD

**Issue by Leifzhang** [521xueweihan/HelloGitHub#1579]
## 项目推荐
- 项目地址：https://github.com/Leifzhang/AndroidAutoTrack

- 类别：Java,Kotlin,Gradle

- 项目后续更新计划： 后续打算持续演进Gradle  Plugin的开发方式，以及更简单的接入成本

- 项目描述：
     本项目主要就是给大家一个参考学习的demo而已，主要是打算简化学习gradle插件的成本，以及对于android transform的一次抽象，将Transform的增量编译以及多线程优化等进行一次抽象，以方便大家学习开发。
     通过字节码替换的形式提供安卓双击优化，自动化埋点的demo以及threadpool更换，新手可以学会更简单方便的gradle 插件开发模式。
  （不包含示例代码）通过项目组合编译的方式重构，同样不需要本地推aar，保留了上述所有的优点的同时，由于buildSrc是一个优先编译的工程，所以无法使用项目内的build.gradle,而ComposeBuild则由于是一个独立Project，所以可以使用当前下面的所有共用属性。

- 推荐理由：其中的双击保护的字节码插桩已经是在项目中进行运用，多线程Hook优化也可以解决项目内的多线程FD异常。

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
