### ISSUE TITLE
扩展性极强的B端表格操作工具: handsontable

### ISSUE THREAD

**Issue by mapletower** [521xueweihan/HelloGitHub#158]
## 项目推荐
- 项目名称：handsontable

- 项目地址：https://github.com/handsontable/handsontable

- 项目语言：JavaScript

- 项目描述：`handsontable` 是一个非常强大的开源HTML5表格处理工具。它很容易与任何数据源集成，并附有非常丰富的操作，如数据绑定、验证、排序及强大的上下文菜单。同时提供商业版[handsontable-pro](https://github.com/handsontable/handsontable-pro)。

- 推荐理由：api友善，扩展性可操作性极强，与execl等表格处理程序兼容很好。

- 示例代码：
```
var data = [
  ["", "Tesla", "Volvo", "Toyota", "Honda"],
  ["2017", 10, 11, 12, 13],
  ["2018", 20, 11, 14, 13],
  ["2019", 30, 15, 12, 13]
];

var container = document.getElementById('example');
var hot = new Handsontable(container, {
  data: data,
  rowHeaders: true,
  colHeaders: true,
  filters: true,
  dropdownMenu: true
});
```

- 截图：

**Comment by 521xueweihan** [comment]
@mapletower   您推荐的项目，已成功收录在 [HelloGitHub 第 22 期](https://hellogithub.com/volume/22/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，欢迎 Star ⭐️ 本项目，以便让更多人看到。
