### ISSUE TITLE
【自荐】Flutter+GRPC+Go 开发的 IOS App(已上线 App store)

### ISSUE THREAD

**Issue by DuanJiaNing** [521xueweihan/HelloGitHub#1580]
## 项目推荐
- 项目地址：https://github.com/DuanJiaNing/makeaplan_public

- 类别：Go

- 项目后续更新计划：开发新功能

- 项目描述：使用 Flutter 和 Go 开发的目标规划 App，帮助用户记录和追踪自己的计划，辅助用户完成自己的目标。手机端用的是 Flutter，后端用的是 Go，手机端和 Go 服务通过 ProtoBuffer+GRPC 进行通信。

- 推荐理由：1）不使用 RESTful，而是通过 RPC 进行通信，可以大大提高开发效率；2）Flutter 新手可以进行参考。

- 截图：
<img  src="https://raw.githubusercontent.com/DuanJiaNing/makeaplan_public/main/preview.png"/>

**Comment by 521xueweihan** [comment]
这个集合项目，我要把它放在那个分类呢

**Comment by DuanJiaNing** [comment]
我没在可选类别（C、C#、C++、CSS、Go、Java、JS、Kotlin、Objective-C、PHP、Python、Ruby、Swift、其它、书籍、机器学习）里看到 Flutter、或和手机 App 相关的，所以就选了 Go。如果没有其它类别的话，看样子只有**其它**和**Go**是比较符合的，我更偏向放在**其它**类别。

**Comment by 521xueweihan** [comment]
**好的**

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 58 期](https://hellogithub.com/periodical/volume/58/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者加入进来，让更多人知道您的项目。阅读完我们的往期文章，有兴趣的话可以加我的微信：xueweihan（备注您发起的项目名称）
