### ISSUE TITLE
【自荐】基于VuePress的 知识管理&博客 主题-vdoing

### ISSUE THREAD

**Issue by xugaoyi** [521xueweihan/HelloGitHub#1581]
## 项目推荐
- 项目地址：https://github.com/xugaoyi/vuepress-theme-vdoing

- 类别：Vue

- 项目后续更新计划：随vuepress2.0版本的正式发布而升级

- 项目描述：
  - 这是一个基于vuepress的主题项目，用于构建知识库网站或博客，具有轻松和高效地构建结构化知识库的特点。

- 推荐理由：
  - 包含三种典型的知识管理形态：结构化、碎片化、体系化。
  - 自动生成侧边栏、目录页、索引页、面包屑等，以更少的配置完成更多的事。

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
