### ISSUE TITLE
【自荐】自动生成Java DTO对象（当然也可以用于别的用途，总之就是基于原类生成新类）

### ISSUE THREAD

**Issue by vipcxj** [521xueweihan/HelloGitHub#1582]
## 项目推荐
- 项目地址：https://github.com/vipcxj/beanknife

- 类别：Java

- 项目后续更新计划：目前更新非常频繁，这里列出的计划可能明天就能实现
  1.  支持为新类定义新方法
  2.  ~~支持反向转换，即新类转回原类，但这个功能需要斟酌，由上诉业务情况1可知，很多时候DTO是原对象的自己，反向转换并不靠谱。~~
  3.  ~~兼容lomok，我没用过lomok，我也不清楚现在是否兼容。或许通过调整annotation processor的顺序可以兼容也说不定。如果不行我也有思路强行兼容了。~~
  4. 配置新类实现特定接口。这个功能如果只是要能用，可以说毫无难度，但我考虑的是要不要检查其合法性，不然随便乱配，生成的代码也是编译不了的。另一方面是否需要检查最终类哪些方法可以加上`@Override` 注解，当然这个其实不加也不影响最终类的功能，但我就是有强迫症，希望生成的代码非常漂亮。
  5. ~~转换函数支持自定义外部参数。目前转换方法只支持使用原类和生成类为参数，当然因为方法声明再配置类里，配置类的状态也是可以使用的。配合上面提到的配置类spring托管功能，这已经满足绝大多数情况了。但极少的情况下可能还不够，所以这个功能就是可能的解决办法。~~
  6. 完善文档，增加中文文档。感觉写文档比写代码还难~

- 项目描述：
  - 这个项目可以用于基于原类，自动化生成一个新类，最容易想到的一个用处就是生成DTO，功能设计也是主要围绕这个来的。基于我个人的主观认识，DTO主要用于以下两种场景。
    i. 有一个非常大的对象，内部属性繁多，根据业务需要向客户端返回这个对象的部分信息。如果直接返回原对象，就会浪费很多带宽。这时建一个新类，映射其中需要的属性，即DTO。这个任务虽然简单，但重复又繁琐，还维护困难。非常适合自动化。
    ii. 同样是希望返回数据给客户端的场景。即使需要的是原对象所有或几乎全部的信息，但若其中有循环引用，这种对象序列化起来就会很麻烦。虽然各个主流JSON库都有一些配置来解决循环引用的问题，但往往效果都不是很好。举个例子，类A有属性List<B\> bList，类B有属性A a，这里可能产生两种业务需求。1. 以A为主，剔除bList中的B对象的a属性；2. 以B为主，剔除a的bList属性，或者保留a，但需要剔除a的bList中的B对象的a属性。这些个需求只能靠DTO，靠配置JSON是很难实现的。
  - 这个项目使用了jdk的annotation processor技术，这方面的资料很少，可以作为新手的一个良好范例。
  - 该工具能基于原类，生成新类。基于注解配置。注解可以配置在原类上，也可以配置在一个单独的配置类上。推荐后者，因为后者无侵入性，并且后者支持配置继承。使用者可以控制新类继承哪些属性，修改已有的属性（除了名字，什么都能改），增加新的属性。通过配置，可以控制新类是否继承注解，这对使用一些json框架进行序列化非常有帮助。提供了一个SPI，来自定义配置类的实例化。本库基于这个机制提供了一个spring boot插件，使得配置类可以是spring bean。新类有多个read方法，用于转换原类，原类的List，原类的Set，原类的Map，总之就是让你转换无忧。

- 推荐理由：
  1. 目前市面上我没找到一样功能的java库。有不少类似的，主要是用于对象间映射，比如ModelMapper，MapStruct。看似相似，但还是有本质不同。因为它们的DTO还是要自己手写的。事实上它们是可以和我的库一起使用，互相补足。
  2. 我的这个库的杀手级特性是自动对属性做DTO映射，下面的示例代码会展示出它的强大之处。这个特性也是我敲代码时的一大难点。没有这个特性，这个库我估计几天就搞定了，为了实现这个特性，结果1个月才搞完。这个特性的难点在于，DTO版本也就是新类是需要生成的，也就是说目前还不存在，如果将其声明在配置类中，IDE会认为是语法错误。当然这不是编码的难点。编码的难点在于执行我的代码生成程序时，JDK收集不到这些“未来类”的信息，我的解决办法时使用ast，来猜测这些未知类的构造。总之就是最后解决了，如果你使用我这个库，配置的过程中，可以直接使用这些不存在的类，执行编译并不会报错，而且编译完成后，IDE也不会再显示错误了。
  3. 目前这个库无人知晓，但我还是天天再更新，迭代非常快，几乎一天一版本。比如今天强化了配置继承。这意味者只要所有配置类都有同一个基类，绝大多数配置都能直接继承下来，懒人狂喜。
  4. 众所周知 java9 的模块化是个天坑，导致了兼容性上的一大断层，我这项目深受其害，但我还是排除万难，使其同时兼容 java8 和 java9+。这里面最大的坑在于我的库使用了tools.jar，这东西在java 9+被移入了其他地方，理论上用起来更方便了，模块描述里声明下依赖就行。问题是这和 java8 是完全不兼容的。这让编译工作变得极度困难~ 但最后还是搞定了。
- 示例代码：
```
@Entity
class Pojo1 {
   private int a;
   @OneToMany(mappedBy="b")
   private List<Pojo2> b;
}

@Entity
class Pojo2 {
   private String a;
   @ManyToOne()
   private Pojo1 b;
}

// 这就是配置基类，这上面的注解都会被继承
// 默认情况下，新类不继承任何属性，这主要是为了满足上面提到的第一种业务需求，
// 使用了这个注解后，新类会继承所有属性
@PropertiesIncludePattern(".*")
// 默认情况下，新类的名字是原类加上View，比如Bean变成BeanView
// 使用这个注解后，Bean变成BeanDto
@ViewGenNameMapper("${name}Dto")
abstract class BaseConfiguration {
}

// 生成 Pojo1Dto, b属性由 List<Pojo2>转为List<Pojo2Info>，这里 Pojo2Info 由下面的配置生成
@ViewOf(value = Pojo1.class)
class Pojo1DtoConfiguration extends BaseConfiguration {
    private List<Pojo2Info> b;
}

// 生成 Pojo1Info, 去掉 b 属性
@ViewOf(value = Pojo1.class, genName="Pojo1Info", excludes = "b")
class Pojo1InfoConfiguration extends BaseConfiguration {}

// 生成 Pojo2Dto, b 属性由 Pojo1 转为 Pojo1Info，这里 Pojo1Info 由上面面的配置生成
@ViewOf(value = Pojo2.class)
class Pojo2DtoConfiguration extends BaseConfiguration {
    private Pojo1Info b;
}

// 生成 Pojo2Info, 去掉 b 属性
@ViewOf(value = Pojo2.class, genName="Pojo2Info", excludes = "b")
class Pojo2InfoConfiguration extends BaseConfiguration {}
```
以上配置将生成 （实际类对象会更复杂，保护getter，setter，转换方法）
```java
class Pojo1Dto {
   private int a;
   private List<Pojo2Info> b;
}

class Pojo1Info {
   private int a;
}

class Pojo2Dto {
   private String a;
   private Pojo1Info b;
}

class Pojo2Info {
   private String a;
}
```
这样使用生成的新类
```java
Pojo1 pojo1 = ...
Pojo1Dto pojo1Dto = Pojo1Dto.read(pojo1);
Pojo2 pojo2 = ...
Pojo2Dto pojo2Dto = Pojo2Dto.read(pojo2);
```

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
