### ISSUE TITLE
【自荐】各大名校EECS公开课程资源集合以及自己的作业代码

### ISSUE THREAD

**Issue by PKUFlyingPig** [521xueweihan/HelloGitHub#1583]
## 项目推荐
- 项目地址：https://github.com/PKUFlyingPig/Self-learning-Computer-Science

- 类别：C、C++、Go、Java、Python

- 项目后续更新计划：根据自己的自学进度不断更新

- 项目描述：
  - 我是北京大学计算机系的一名学生，这是我从大二开始自学的MIT、UC berkeley、Stanford、Harvard 等名校的所有公开课程资源的集合（包括课程网站链接、课程资料链接以及我个人对所有作业、lab、project的实现）
  - 是对国内枯燥、实践性不强的大学计算机课程的有效替代，也是想要跨专业转计算机的学生的资料库。

- 推荐理由：如果你觉得计算机学起来很痛苦，大学的课堂很无聊，很大程度上不是你的原因，作为top1高校的一员，我觉得完全的自学是效率最高且最快乐的！

**Comment by 521xueweihan** [comment]
你是个狠人，但是你这个项目是个索引页，而且索引页的内容很多人看不懂呀。

如果你有兴趣搞成被大众接受的项目的话，我可以帮你，我的微信：xueweihan（备注你的昵称）
