### ISSUE TITLE
【自荐项目】Electronjs - 炉石传说酒馆战棋插件

### ISSUE THREAD

**Issue by chenyueban** [521xueweihan/HelloGitHub#1588]
## 项目推荐
- 项目地址：https://github.com/hbt-org/hearthstone-battlegrounds-tools

- 类别：JS

- 项目后续更新计划：
	- 增加战绩同步功能
	- 利用 C++ addon 实现对炉石的内存读取，获取更多实用信息
	- 实现用户战绩统计分析

- 项目描述：
这是一个炉石传说酒馆战棋的记牌插件。通过 [electron](https://github.com/electron/electron) 实现了对 Windows 以及 MacOS 双平台的支持。除了最基本的记牌功能，她还具有以下特性：
	- 🌴 当天战绩统计
	- 📦 历史战绩查询
	- 🎉 数据分析，统计你所使用过的英雄，自动计算每个英雄的平均排名、选择率
	- 🙈 选择英雄时展示可选英雄的大数据选择率、平均排名等
	- 🃏 对局信息记录，记录对局过的对手阵容
	- ✈️ 一键拔线
	- 🚄 连接 OBS 自动同步当天战绩到 OBS
	- 🚀 战力计算 原创战力系统，根据阵容计算敌我双方的战力值
	- 😻 阵容模拟 模拟酒馆中的随从买卖，创造阵容，并且计算模拟阵容的战力值

- 推荐理由：
对普通用户而言它打开即用，提供了对局记录、战力计算、一键拔线等实用功能。
对开发者而言，它实现了一整套比较完整的 Electronjs 开发流程，从多个渲染进程的管理、不同平台的差异化处理、版本的控制与发布等方面都做了细致的封装。

- 截图：
![preview](https://user-images.githubusercontent.com/27852165/104311893-d2d5d980-5510-11eb-816b-983414ba20ac.png)
![preview2](https://user-images.githubusercontent.com/27852165/104311905-d5383380-5510-11eb-9ad6-f640fa042f0a.jpg)
<img width="1024" alt="QQ20210112-200651@2x" src="https://user-images.githubusercontent.com/27852165/104312569-c00fd480-5511-11eb-9ceb-e85aeb20ebf6.png">

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 58 期](https://hellogithub.com/periodical/volume/58/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者加入进来，让更多人知道您的项目。阅读完我们的往期文章，有兴趣的话可以加我的微信：xueweihan（备注您发起的项目名称）
