### ISSUE TITLE
【自荐】面单设计系统

### ISSUE THREAD

**Issue by SXX19950910** [521xueweihan/HelloGitHub#1592]
## 项目推荐
- 项目地址：https://github.com/SXX19950910/manifest-design

- 类别：JS

- 项目后续更新计划： 添加更多打印元素，例如图片等。

- 项目描述：
  这是一个基于VUE开发的模板设计项目，可以用来设计打印面单，例如商品标签，物流标签等等。
  适用于商家的商品标签设计或者物流标签设计等等。

- 推荐理由：操作简单，功能强大，集预览于打印于一身的面单设计系统。

- 截图：![image](https://github.com/SXX19950910/manifest-design/blob/master/demo.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
