### ISSUE TITLE
【开源项目】SimpleDocker

### ISSUE THREAD

**Issue by taoes** [521xueweihan/HelloGitHub#1597]
## 项目推荐
- 项目地址： https://gitee.com/taoes_admin/SimpleDocker

- 类别：
  - 后端：Go 
  - 前端: Vue

- 项目后续更新计划：
  - 操作流程优化
  - 容器文件下载与上传(计划中)
  - 私有仓库的镜像拉取(计划中)
  - DockerCompose 镜像编排管理(计划中)
  - DockerSwarm 集群管理(计划中)

- 项目描述：
  - 必写：SimpleDocker 是一个简单的Docker控制面板，致力于可以让你更方便，更无障碍的使用Docker,其界面简洁，操作便捷，免除了登录服务器以及Docker复杂命令的困扰
  - 可选：适用于开发者管理服务端Docker服务以及本地Docker运行管理
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：更好地管理Docker资源，特色功能 在线容器终端访问 & 远程在线容器文件浏览及下载 & 远程容器性能监控

- 截图：
  + 终端命令执行
![终端管理](https://user-images.githubusercontent.com/22141049/104830427-02daff00-58ba-11eb-945d-8a864aad5b32.png)

  + 文件管理
![文件管理](https://user-images.githubusercontent.com/22141049/104830429-066e8600-58ba-11eb-8f75-dcc8c0520d8b.png)

  + 性能监控
![性能监控](https://user-images.githubusercontent.com/22141049/104830419-f5be1000-58b9-11eb-918d-72edb0e31144.png)

**Comment by taoes** [comment]
烦死了，总是被自动关闭，凸(艹皿艹 )，不提交了，溜了溜了

**Comment by qiutian00** [comment]
@taoes  休息休息， 后面接着干
