### ISSUE TITLE
Geisha - Tiny Java MVC Framework

### ISSUE THREAD

**Issue by RitterHou** [521xueweihan/HelloGitHub#160]
## 项目推荐
- 项目名称：Geisha

- 项目地址：https://github.com/RitterHou/Geisha

- 项目语言：Java

- 项目描述：用 Java 语言写的 web MVC 框架，包含诸多语言特性并且实现了 IOC 以及通过注解设置 url 映射的功能。

- 推荐理由：入门实践项目，适合新手熟悉 Java 语法和了解 web 框架的实现

- 示例代码：
```java
@Component
@RequestMapping("/person")
public class Hello {

    @RequestMapping("/info")
    public String hello(@Param("name") String name, @Param("age") String age) {
        return "hello " + name + ", your age is " + Integer.valueOf(age);
    }

}
```
```java
public class Application {

    public static void main(String[] args) {
        Geisha.run();
    }

}
```

**Comment by 521xueweihan** [comment]
@RitterHou  您推荐的项目，已成功收录在 [HelloGitHub 第 23 期](https://hellogithub.com/volume/23/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，欢迎 Star ⭐️ 本项目，以便让更多人看到。
