### ISSUE TITLE
【开源项目推荐】Xonsh 允许python代码和bash指令混用

### ISSUE THREAD

**Issue by xuzirui20080129** [521xueweihan/HelloGitHub#1601]
## 项目推荐
- 项目地址：https://github.com/xonsh/xonsh
          https://xon.sh

- 类别：Python

- 项目后续更新计划：包含更多的python和控制台指令

- 项目描述：
  - **xonsh**是一个 Python 驱动的跨平台，Unix- gazing shell 语言和命令提示符。
  - 可以在python语言中使用shell，可以在shell中使用python
  - Xonsh 支持使用 [Prompt Toolkit](https://python-prompt-toolkit.readthedocs.io/en/master/)补全 shell 命令和 Python 表达式。补全有可视化提示，会显示可能的补全并有下拉列表。
- 漂亮的终端输出，类似ipython的补全
  
- 推荐理由：可以让python和bash混用，比bash有更强大的可读性，比python更方便地操作文件。

- 示例代码：

     ```python
     $ for i in range(3):
     .     echo "hello world"
     .
     hello world
     hello world
     hello world
     ```

     

- 截图：![img](https://xon.sh/_static/windows_terminal.png)![img](https://xon.sh/_static/xonsh-docker-example.jpg)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 58 期](https://hellogithub.com/periodical/volume/58/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
