### ISSUE TITLE
【自荐】nuco-docsify

### ISSUE THREAD

**Issue by HerbertHe** [521xueweihan/HelloGitHub#1602]
## 项目推荐
- 项目地址：

`https://github.com/NucoTech/nuco-docsify`

- 类别：请从中选择 **其它**

- 项目后续更新计划：

将伴随着[docsify](https://docsify.js.org/)项目、[NucoTech](https://github.com/NucoTech)项目涉及文档部分和使用的插件持续更新

- 项目描述：

这是一个团队内部文档规范化项目, 本身是一个基于docsify项目的文档模板, 实现了常用插件测试、插件冲突调整、命令行工具集成、脱离nodejs环境等开发过程中普遍存在的问题。

- 推荐理由：

1. 利用了docsify项目本身可插拔的特性, 实现了一些常用的功能
2. 测试了所有使用到的插件, 并参与了其中部分插件的编写
3. 脱离了所需要依赖的nodejs环境, 移除了开发中增加的不必要环境, eg. 后端组使用golang开发
4. 为一项目模板, 可以根据自己的喜好更改, 又不需要重复配置文档项目
5. 与NucoTech另一开源工具[nbc](https://nucotech.github.io/nuco-backend-cli)很好的结合, 可以实现`nbc docs`直接模板初始化, `nbc serve`启动静态预览

- 仓库文档预览：

[nuco-docsify](https://nucotech.github.io/nuco-docsify)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
