### ISSUE TITLE
【开源项目】Antv 旗下 X6

### ISSUE THREAD

**Issue by NewByVector** [521xueweihan/HelloGitHub#1603]
## 项目推荐
- 项目地址：https://github.com/antvis/X6

- 类别：JS

- 项目后续更新计划：

X6 在内部和外部的很多业务中落地，后面会持续维护，V2.0 版本准备中

- 项目描述：
 
  X6 是 AntV 旗下的图编辑引擎，提供了一系列开箱即用的交互组件和简单易用的节点定制能力，方便我们快速搭建 DAG 图、ER 图、流程图等应用,[官网地址](https://x6.antv.vision/zh)

- 推荐理由：快速搭建图编辑应用
- 示例代码：（可选）长度：1-20 行
```ts
import { Graph } from '@antv/x6';

const graph = new Graph({
  container: document.getElementById('container'),
  width: 800,
  height: 600,
  background: {
    color: '#fffbe6', // 设置画布背景颜色
  },
  grid: {
    size: 10,      // 网格大小 10px
    visible: true, // 渲染网格背景
  },
});
```
- 截图：（可选）gif/png/jpg
![image](https://user-images.githubusercontent.com/20186737/105031566-6fa7f200-5a90-11eb-9e7f-4adb18603943.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 58 期](https://hellogithub.com/periodical/volume/58/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者加入进来，让更多人知道您的项目。阅读完我们的往期文章，有兴趣的话可以加我的微信：xueweihan（备注您发起的项目名称）
