### ISSUE TITLE
Python 中的可视化库 —— PyG2Plot

### ISSUE THREAD

**Issue by hustcc** [521xueweihan/HelloGitHub#1604]
## 项目推荐

- 项目地址：https://github.com/hustcc/PyG2Plot

- 类别：Python

- 项目后续更新计划：主要是让其使用起来更加方便

1. 按照图表类型导出 API
2. 新增事件等顶层 API 设计

- 项目描述：
  - 必写：基于 G2Plot 封装的，用于 Python3 环境下的可视化库，完全底层的全部能力
  - 可选：Python Web 开发中图表渲染，Jupyter Notebook 中图表渲染
  - 描述长度（不包含示例代码）: G2Plot 是蚂蚁集团开源的一个基于图表分类学的可视分析图表库，内置 25+ 常见图表类型，体验良好，开箱即用。PyG2Plot 是基于 G2Plot 封装的，用于 Python3 环境的可视化库，同时也支持在 Jupyter Notebook 中渲染预览，支持 G2Plot 内置的所有图表能力。

- 推荐理由：目前 JavaScript 环境的图表库很多，但是在 Python 环境中选择并不多，G2Plot 是蚂蚁集团开源的一个基于图表分类学的可视分析图表库，使用起来简单，内置的 25+ 常用图表可以满足大部分的场景，所以基于 G2Plot 封装的 PyG2Plot 使用上也会非常轻便。

- 示例代码：（可选）长度：1-20 行

```py
from pyg2plot import Plot

line = Plot("Line")

line.set_options({
  "height": 400, # set a default height in jupyter preview
  "data": [
    { "year": "1991", "value": 3 },
    { "year": "1992", "value": 4 },
    { "year": "1993", "value": 3.5 },
    { "year": "1994", "value": 5 },
    { "year": "1995", "value": 4.9 },
    { "year": "1996", "value": 6 },
    { "year": "1997", "value": 7 },
    { "year": "1998", "value": 9 },
    { "year": "1999", "value": 13 },
  ],
  "xField": "year",
  "yField": "value",
})

line.render_notebook()
```

- 截图：（可选）gif/png/jpg

![image](https://user-images.githubusercontent.com/7856674/105114613-30b28480-5b02-11eb-9edc-833afeb89aa0.png)

**Comment by 521xueweihan** [comment]
我看了下要写的还有点多，再迭代下再来推吧

**Comment by hustcc** [comment]
> 我看了下要写的还有点多，再迭代下再来推吧

你说的是文档的两个部分吗？

**Comment by 521xueweihan** [comment]
@hustcc 好的，我其实比较感兴趣 TODO 里的这个功能：“按照图表类型导出 API”


顺便可以聊一下，对比起这个库：https://github.com/pyecharts/pyecharts

比起来有什么亮点或者特别的地方吗

**Comment by hustcc** [comment]
> @hustcc 好的，我其实比较感兴趣 TODO 里的这个功能：“按照图表类型导出 API”
> 
> 顺便可以聊一下，对比起这个库：https://github.com/pyecharts/pyecharts
> 
> 比起来有什么亮点或者特别的地方吗

“按照图表类型导出 API” 其实是语法糖而已，不是必须：

```py
from pyg2plot import Plot, Line

line = Plot('Line')

# 这里就是包了上面一层语法糖而已，本质非常简单
line = Line()
```

和 pyecharts 同类产品，它封装的是 echarts，这个封装的是 G2Plot，他们之间的优劣就是在于底层优劣了。（这就是各靠各吹了，echarts 用户量必然是国内图表库 number 1，毋庸置疑）

**Comment by 521xueweihan** [comment]
下期月刊，安排上！

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 59 期](https://hellogithub.com/periodical/volume/59/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
