### ISSUE TITLE
awesome-seo

### ISSUE THREAD

**Issue by madawei2699** [521xueweihan/HelloGitHub#1607]
## 项目推荐
- 项目地址：
https://github.com/madawei2699/awesome-seo
- 类别：请从中选择（C、C#、C++、CSS、Go、Java、JS、Kotlin、Objective-C、PHP、Python、Ruby、Swift、其它、书籍、机器学习）
其它

- 项目后续更新计划：
不定期更新内容，或者新增章节内容

- 项目描述：
有关Google SEO及流量变现的项目，介绍我学习SEO收藏的资源清单以及研究流量变现渠道。

- 推荐理由：
介绍了SEO学习中的痛点，包括权威资料的推荐。因为网上关于SEO的粗糙文章太多，导致学习的过程很难找到高质量的资料，所以我整理了我认为高质量的文章和资料。

- 示例代码：
无

- 截图：
无

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 58 期](https://hellogithub.com/periodical/volume/58/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者加入进来，让更多人知道您的项目。阅读完我们的往期文章，有兴趣的话可以加我的微信：xueweihan（备注您发起的项目名称）

**Comment by madawei2699** [comment]
谢谢！

削微寒 <notifications@github.com>于2021年1月28日 周四上午8:42写道：
