### ISSUE TITLE
用于爬取图片的小东西

### ISSUE THREAD

**Issue by code-aifarmer** [521xueweihan/HelloGitHub#1608]
## 项目推荐
- [项目地址：]https://github.com/code-aifarmer/Image-crawling-program-developed-based-on-PyQt5

- 类别：Python

- 项目后续更新计划：
- 改善GUI，提升使用者的使用体验，增加更多的功能，进一步完善程序。

- 项目描述：
  这个是用来爬取图片的小程序，可以从本地上传文件进行关键字读取，也可以手动输入单关键字或者多关键字进行爬取图片，可以选择从百度或者bing爬取图片，可以自定义设置线程，爬取数量以及保存地址。适用于批量特定图片的下载和爬取，能够让想学习爬虫和python相关知识的初学者们学习到相关的知识以及爬虫搭建的基本思路和PyQt5的使用。

- 推荐理由：爬取的速度很快，采用多线程，提升了效率，下载的图片自动分类保存在对应的文件夹中。提供不同搜索引擎的选择，后续还将进一步完善，操作简单易于上手。

- 截图：（可选）gif/png/jpg
![g](https://user-images.githubusercontent.com/73326606/105569127-1551ae80-5d7a-11eb-9f91-708f04ba1b2a.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by code-aifarmer** [comment]
你好，我很喜欢你们的这个公众号，我认真的看了每一期，发现也有不少关于爬虫的小项目，想知道为什么我的项目不能被通过，希望您给出宝贵的意见，我会进一步做出完善和改正，谢谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "521xueweihan/HelloGitHub"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月25日(星期一) 下午4:00
收件人:&nbsp;"521xueweihan/HelloGitHub"<HelloGitHub@noreply.github.com&gt;;
抄送:&nbsp;"自#由@飞翔"<1223419806@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [521xueweihan/HelloGitHub] 用于爬取图片的小东西 (#1608)





 
非常感谢您推荐项目。
 
该项目暂不能收录到 HelloGitHub 月刊中，HelloGitHub 推荐项目审核标准 #271。
 期待持续完善该项目，后续推荐更多的项目。
 
再次感谢您对 HelloGitHub 的支持 🙏

**Comment by 521xueweihan** [comment]
@code-aifarmer 感谢您的支持，我这几天要出月刊比较忙。等我出完月刊再聊，可以叫我微信：xueweihan
