### ISSUE TITLE
【项目自荐】腾讯开源项目 CloudBase Framework

### ISSUE THREAD

**Issue by binggg** [521xueweihan/HelloGitHub#1609]
## 项目推荐
- 项目地址：https://github.com/Tencent/cloudbase-framework

- 类别：JS

- 项目后续更新计划：公司级开源项目，持续维护

- 项目描述：

腾讯开源的云原生一体化部署工具，一键将项目部署上云，不限制框架和语言

无需改动代码，前后端一键托管部署，基于Serverless架构，加速访问，弹性免运维。

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？

使用简单，支持本地 CLI 和云端一键部署

- 示例代码：（可选）长度：1-20 行

```bash
npm i @cloudbase/cli@latest -g 

tcb 
```

- 截图：（可选）gif/png/jpg

云端一键安装

![image (2)](https://user-images.githubusercontent.com/7686861/105573649-0e3a9880-5d9a-11eb-8037-9f5c741fa80a.png)

应用中心

![image (4)](https://user-images.githubusercontent.com/7686861/105573720-7db08800-5d9a-11eb-9957-0e1033f4a6cd.png)

本地一键部署
![image (3)](https://user-images.githubusercontent.com/7686861/105573667-2f02ee00-5d9a-11eb-9afb-6680ad262e55.png)

![68747470733a2f2f6d61696e2e71636c6f7564696d672e636f6d2f7261772f64306634663863663033643132363763333936656234636633353730303331622e706e67 (1)](https://user-images.githubusercontent.com/7686861/105573703-5ce83280-5d9a-11eb-9957-ac031840e533.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 58 期](https://hellogithub.com/periodical/volume/58/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者加入进来，让更多人知道您的项目。阅读完我们的往期文章，有兴趣的话可以加我的微信：xueweihan（备注您发起的项目名称）

**Comment by binggg** [comment]
多谢多谢
