### ISSUE TITLE
amazing-books

### ISSUE THREAD

**Issue by cunyu1943** [521xueweihan/HelloGitHub#1612]
## 项目推荐
- 项目地址：https://github.com/cunyu1943/amazing-books

- 类别：书籍
- 项目后续更新计划：长期更新，收集到新的电子书后就会更新

- 项目描述：
  - 必写：编程电子书下载，方便大家下载，解决大家花费大量时间去找电子书
- 推荐理由：方便大家下载电子书，节约更多时间
- 截图：
![](https://user-images.githubusercontent.com/22308895/105964839-b4014680-60bd-11eb-9617-5d2715f40b3a.png)
![](https://user-images.githubusercontent.com/22308895/105964864-bcf21800-60bd-11eb-9fee-071a37881595.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。有很多都是违反版权的

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
