### ISSUE TITLE
Java 开发的图形验证码项目

### ISSUE THREAD

**Issue by stone365** [521xueweihan/HelloGitHub#1615]
## 项目推荐
- 项目地址：https://github.com/stone365/captcha

- 类别：Java

- 项目后续更新计划：支持算数类型的验证码

- 项目描述：
  - 必写：用 Java 实现的图形验证码，接口防刷，防范部分爬虫
  - 可选：Java Graphics2D 绘制

- 推荐理由：在实际项目中，有效拦截自动化脚本

- 示例代码：
// 生成包含大小写字母的 png 图形验证码：
CaptchaConfig captchaConfig = new CaptchaConfig(200, 60, 4);
Captcha captcha = new LetterCaptcha(captchaConfig, CaptchaEnum.CaptchaType.MIX_LETTER);
CaptchaPrinter printer = new PngPrinter(captcha);
File file = new File("your destination/example.png");
FileOutputStream outputStream = new FileOutputStream(file);
printer.print(outputStream);
outputStream.close();

- 截图：（可选）gif/png/jpg
https://github.com/stone365/captcha/blob/main/src/main/resources/png/Blox2.png

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
