### ISSUE TITLE
自荐项目 - AndroidSDK Docker image

### ISSUE THREAD

**Issue by thyrlian** [521xueweihan/HelloGitHub#1617]
## 项目推荐
- 项目地址：https://github.com/thyrlian/AndroidSDK

- 类别：请从中选择（其它）

- 项目后续更新计划：
  - 更新依赖
  - 完全剥离 Android SDK 包 (合法化)
  - 添加新功能，新应用子镜像

- 项目描述：
  - 该容器镜像包含了一个完整的 Android SDK 运行环境，适用于各种 Android 持续集成场景，甚至包括模拟器运行应用，界面自动化测试，也可以连接云端(比如Google Firebase Test Lab)进行自动化测试。
  - 该方案可用于个人小型项目，和 CircleCI 之类集成使用
  - 该方案亦可用于企业大型项目，搭建分布式环境。其中的挂载 Android SDK 镜像(NFS)，自建 Gradle 服务器，都可助力企业快速构建。
  - 最重要的是，通过挂载而非自包含 Android SDK，解决了几个相当棘手问题
    - Google 的许可协议不允许第三方再分发 Android SDK
    - 和 Android SDK 解藕，就无需维护大量不同版本的镜像，不需要浪费时间更新
  - 该项目属于非常早的关于 Android 构建的容器镜像解决方案之一(也是目前唯一一个不违法许可协议的方案)，并且在 Docker 官方的 DockerCon EU 2017 进行过宣讲报告

**Comment by 521xueweihan** [comment]
@thyrlian 您好，配图我就用：

您在 Docker 官方的 DockerCon EU 2017 进行过宣讲报告的视频截图了

**Comment by thyrlian** [comment]
谢谢@521xueweihan

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 59 期](https://hellogithub.com/periodical/volume/59/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
