### ISSUE TITLE
cc-admin企业级快速开发平台-可视化数据展示系统

### ISSUE THREAD

**Issue by zhy6599** [521xueweihan/HelloGitHub#1619]
## 项目推荐
- 项目地址：https://github.com/zhy6599/cc-admin-web

- 类别：Java、JS

- 项目后续更新计划：持续完善，数据可视化部分。补充可视化数据分析建模功能。

- 项目描述：
  - 必写：
  一个基于 Spring Boot 2.1.3 、 Mybatis plus、 JWT、Shiro、Redis、Vue、Quasar的前后端分离的后台管理系统。
  可以通过配置，一键生成前后端代码，监控服务器性能，做数据可视化展示。
  - 可选：可以直接拿来做企业应用开发。数据可视化展示。
- 推荐理由：炫酷的数据可视化展示模块。可以无代码做数据可视化。支持手机端和PC端访问。基于wrapper的打包方式，方便进行部署。

- 截图：

  - 演示地址：http://www.cc-admin.top/

（可选）gif/png/jpg
  - https://github.com/zhy6599/preview
  - http://forum.quasarchs.com/article/1608993799842
  - https://blog.csdn.net/zwhfyy/article/details/113450546
  - https://blog.csdn.net/zwhfyy/article/details/113062895

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
