### ISSUE TITLE
有没有一个central的记录已经推荐过的项目的地方--以防重复推荐的？

### ISSUE THREAD

**Issue by franklingu** [521xueweihan/HelloGitHub#162]
比如一个search page，这个page可以按语言（按期数已经有了），按名字，这样以后便于user查找，同时以后可以尽量防止重复

推荐的项目最好是不是也加上meta tag，按功能的？

**Comment by 521xueweihan** [comment]
@franklingu 现在后台有根据 project url search 的功能（project url 唯一），面向用户的搜索功能暂时没有。由于项目信息、描述的维度太少，多元搜索开发有难度。

所以，暂时只能开发 项目名模糊搜索、project url 精确搜索。

**Comment by jp1017** [comment]
可能有些处女座朋友会修改用户名,造成url更改,,,

**Comment by 521xueweihan** [comment]
@jp1017 修改用户名不会造成 `https://github.com/xxxx/HelloGitHub` 的改变，但是修改项目名会。。。

**Comment by 521xueweihan** [comment]
@franklingu 新增了搜索功能，支持项目名和地址搜索

https://hellogithub.com/
