### ISSUE TITLE
自荐开源项目：GitHub 组织成员墙

### ISSUE THREAD

**Issue by Suvern** [521xueweihan/HelloGitHub#1628]
## 项目推荐
- 项目地址：[https://github.com/Suvern/github-org-users-wall](https://github.com/Suvern/github-org-users-wall)

- 类别：JS

- 项目后续更新计划：增加模板功能，丰富自定义配置项等

- 项目描述：
  很多GitHub组织都有自己的Profile仓库，因此需要展示所有人的头像。本项目基于GitHub API获取组织内所有成员，并按Team分组生成Markdown形式的头像墙，可用于组织介绍仓库的README.md
  使用NodeJS + Babel开发，使用`async`、`await`进行异步调用，可作为新手学习Node编程和项目配置的案例。

- 推荐理由：代码不到200行，简单易读，快速可生成直观的“成员墙”。

- 截图：[![效果图](https://s3.ax1x.com/2021/02/12/yD6P56.jpg)](https://imgchr.com/i/yD6P56)
   使用案例：[https://github.com/cumtonline](https://github.com/cumtonline)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
