### ISSUE TITLE
install-docker 一键安装 docker 二进制文件

### ISSUE THREAD

**Issue by dyrnq** [521xueweihan/HelloGitHub#1630]
## 项目推荐
- 项目地址：https://github.com/dyrnq/install-docker

- 类别：请从中选择（C、C#、C++、CSS、Go、Java、JS、Kotlin、Objective-C、PHP、Python、Ruby、Swift、其它、书籍、机器学习）
其它（bash语言）
- 项目后续更新计划：
支持更多的os安装方式，对mirror进行测速
- 项目描述：
  - 必写：这是个什么项目、能用来干什么、有什么特点或解决了什么痛点
  - 可选：适用于什么场景、能够让初学者学到什么
  - 描述长度（不包含示例代码）: 10 - 256 个字符
一键安装docker二进制和docker-compose，支持主流的linux系统：centos7、centos8、debian10、ubuntu18.04、ubuntu20.04，**支持各种国内mirror**，Tuna、aliyun等
- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？
一键安装docker二进制，解决在各种操作系统**先换docker-ce源再安装的麻烦**，直接采用curl从国内源拉取static二进制文件。**使用相同的二进制方式在不同的linux系统上安装docker**，**自用脚本，使用很久**
- 示例代码：（可选）长度：1-20 行

```bash
curl -fsSL https://cdn.jsdelivr.net/gh/dyrnq/install-docker@main/install-docker.sh | bash -s docker --mirror Tuna --version 20.10.3 --with-compose --compose-version 1.28.2 --compose-mirror daocloud
```
| Name                  | Description                                   | Default                                   |
| ----------            | ----------------                              | ----------------------                    |
| --mirror              | mirror of docker binary download url          |                                           |
| --prefix              | docker binary installation directory          | /usr/local/bin                            |
| --version             | docker binary version                         | 20.10.2                                   |
| --with-compose        | install docker-compose                        |                                           |
| --compose-prefix      | docker-compose installation directory         | /usr/local/bin                            |
| --compose-version     | docker-compose version                        | 1.28.2                                    |
| --compose-mirror      | mirror of docker-compose download url         |                                           |
| --systemd-mirror      | mirror of dockerd`s systemd unit files        | jsdelivr                                  |
| --no-systemd          | do not install dockerd`s systemd unit files   |                                           |
| --daemon-json         | daemon.json path or url                       |                                           |
| --no-daemon-json      | do not install daemon.json                    |                                           |
| --daemon-json-prefix  | daemon.json path                              | /etc/docker                               |
| --dry-run             | dry run                                       |                                           |

- 截图：（可选）gif/png/jpg

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
