### ISSUE TITLE
【自荐】16岁高中生开发的粤语编程语言

### ISSUE THREAD

**Issue by StepfenShawn** [521xueweihan/HelloGitHub#1632]
## 项目推荐
- 项目地址：https://github.com/StepfenShawn/Cantonese

- 类别：Python

- 项目后续更新计划：
     * 编写编辑器插件
- 项目描述：
  粤语编程语言是一门用粤语来操作(虐待)计算机的编程语言 
  功能: 图灵完备，支持栈，list，异常处理，面向对象，机器学习,  海龟绘图，网页开发等操作

- 推荐理由: 
 * 自从 github 上出现了东北，上海，四川等方言编程语言，作为一个广东仔，没理由不开发一个粤语编程语言!
 * 粤语本身声调丰富、具有乐感，又是一种优美的语言，与代码相结合，可以让人感受到代码与方言相结合的魅力
 * 好玩有趣，符合本repo的描述: " 分享 GitHub 上有趣、入门级的开源项目 "
 * 保护粤语文化，粤语是中国多种方言中流传得最广最远的, 保护和传承好这门古老的方言就是我大湾区人的责任
 * 有热度:
 [16 岁高中生开发的粤语编程语言在 github 上开源](https://v2ex.com/t/752132)
 [开源中国软件推荐](https://www.oschina.net/p/cantonese)
 [厉害了，粤语也能编程!](https://weibo.com/1400220917/K0okUoNIs?from=page_1006061400220917_profile&wvr=6&mod=weibotime&type=comment)

- 示例代码：
  实现KNN分类算法:
```
使下 math
|[5, 1], [4, 0], [1, 3], [0, 4]| 拍住上 -> |数据|
|'动作片', '动作片', '科幻片', '科幻片'| 拍住上 -> |标签|
讲嘢: |K| 系 3
嗌|KNN|过嚟估下 -> |[3, 0]|
```
 运行结果:
```
动作片
```

这个项目花费了我很多的心思和时间，在此希望能被`HelloGithub`录取，谢谢!

**Comment by 521xueweihan** [comment]
感谢推荐项目，很有意思。考虑到月刊的受众，就不收录到月刊了。标题确实有热度，但我还是希望读者可以从中学到东西，尽管只是哈哈一笑后，我已 Star 期待后续佳作。
