### ISSUE TITLE
仅需在你的应用中添加几行代码的性能分析平台

### ISSUE THREAD

**Issue by Yanwenjiepy** [521xueweihan/HelloGitHub#1633]
## 项目推荐
- 项目地址：https://github.com/pyroscope-io/pyroscope

- 类别：Go

- 项目后续更新计划：持续更新中

- 项目描述：
  Pyroscope是一个开源的连续分析平台。它将帮助您：
    - 在代码中查找性能问题
    - 解决CPU使用率高的问题
    - 了解您的应用程序的调用树
    - 跟踪随着时间的变化

- 推荐理由：
  - 仅需要在你的代码里添加几行代码，就可以对你的代码进行性能分析，丰富图表助你代码如飞
  - 可以在mac、linux直接部署服务，也可以通过docker部署
  - 目前支持Go、Python、Ruby，后续计划支持Node和Linux eBPF

- 截图：
![image](https://user-images.githubusercontent.com/32814388/108592412-c31ba180-73a8-11eb-9a76-1675de0f339f.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 59 期](https://hellogithub.com/periodical/volume/59/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
