### ISSUE TITLE
自荐项目 - 利用现代浏览器的强大API在浏览器中录制任意界面并实现导出、保存与管理

### ISSUE THREAD

**Issue by asdjgfr** [521xueweihan/HelloGitHub#1634]
## 项目推荐
- 项目地址：[https://github.com/asdjgfr/operationRecord](https://github.com/asdjgfr/operationRecord)

- 类别：JS
- 项目后续更新计划：
  - 适配`Electron`
  - 自定义上传接口
  - 格式转换

- 项目描述：
  - 利用现代浏览器的强大API在浏览器中录制任意界面并实现导出、保存与管理

- 推荐理由：包含后台管理也可单独使用的基于浏览器的全局屏幕录制。

- 示例代码：
  ```html
      <script type="text/javascript" src="op-rec.js"></script>
      <body>
        <video controls autoplay></video>
      </body>
      <script>
        const video = document.querySelector("video");
        const or = new OpRec();
        or.on("startREC", function (stream) {
          video.srcObject = stream;
        });
      </script>
  ```

- 说明文章：[掘金](https://juejin.cn/post/6931885040750051342)

**Comment by 521xueweihan** [comment]
很棒的项目，我已 star。月刊中已经推荐过类似的项目，暂不能收录到月刊。望见谅
