### ISSUE TITLE
c++ deep segmentation models

### ISSUE THREAD

**Issue by AllentDan** [521xueweihan/HelloGitHub#1635]
## 项目推荐
- 项目地址：https://github.com/AllentDan/SegmentationCpp

- 类别：C++

- 项目后续更新计划：增加resnest和其他architectures.

- 项目描述：
  - 必写：这是个C++的语义分割开源项目、能用C++训练语义分割网络、有易用性强，封装性好的特点，解决了部分深度学习开发者需要C++部署的痛点
  - 可选：适用于语义分割场景
  - 描述长度（不包含示例代码）: 一行代码生成网络，7个不同的骨干网络，4个不同的分割框架。

- 推荐理由：C++版本的分割网络库，内容丰富

- 示例代码：（可选）长度：
```cpp
#include "Segmentor.h"
auto model = UNet(1, //num of classes
                  "resnet34", //encoder name, could be resnet50 or others
                  "path to resnet34.pt"//weight path pretrained on ImageNet, it is produced by torchscript
                  );
```

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
