### ISSUE TITLE
性能超高简单易用的微服务聚合网关

### ISSUE THREAD

**Issue by linwaiwai** [521xueweihan/HelloGitHub#1636]
## 项目推荐
- 项目地址：https://github.com/wehotel/fizz-gateway-community

- 类别：Java

- 项目后续更新计划：
  - Fizz 现阶段的已经支持的产品特性：
	- 集群管理：Fizz网关节点是无状态的，配置信息自动同步，支持节点水平拓展和多集群部署。
	- 服务编排：支持热服务编排能力，支持前后端编码，随时随地更新API。
	- 负载均衡：支持round-robin负载均衡。
	- 服务发现：支持从Eureka、Nacos注册中心发现后端服务器。
	- 配置中心：支持接入apollo配置中心。
	- HTTP反向代理：隐藏真实后端服务，支持 Rest API反向代理。
	- 访问策略：支持不同策略访问不同的API、配置不同的鉴权等。
	- IP黑白名单：支持配置IP黑白名单。
	- 自定义插件：强大的插件机制支持自由扩展。
	- 可扩展：简单易用的插件机制方便扩展功能。
	- 高性能：性能在众多网关之中表现优异。
	- 版本控制：支持操作的发布和多次回滚。
	- 管理后台：通过管理后台界面对网关集群进行各项配置。
  - Fizz 未来的更新计划如下：
  
      ![更新计划](https://oscimg.oschina.net/oscnet/up-c02766e33e4109fa94a94324cdcf1feb22d.png)

- 项目描述：
  A Managerment API Gateway in Java . Fizz Gateway 是一个基于 Java开发的微服务网关，能够实现热服务编排、自动授权选择、线上服务脚本编码、在线测试、高性能路由、API审核管理等目的，拥有强大的自定义插件系统可以自行扩展，并且提供友好的图形化配置界面，能够快速帮助企业进行API服务治理、减少中间层胶水代码以及降低编码投入、提高 API 服务的稳定性和安全性。

- 推荐理由：
  Fizz 是现阶段性能最高的Java网关之一，经历春晚流量验证，功能强大，也是唯一一款支持高性能聚合服务的网关，能够适配小中大型企业成长需要。

- 截图：

![](https://user-images.githubusercontent.com/6129661/104895987-84618880-59b1-11eb-9a73-a8569a7e6a69.png)

![](https://user-images.githubusercontent.com/184315/97131368-f5ace900-177e-11eb-9e00-24e73d4e24f5.png)

![](https://user-images.githubusercontent.com/184315/97131376-f9407000-177e-11eb-8c17-4922b3df5d48.png)

![](https://user-images.githubusercontent.com/184315/97131378-f9d90680-177e-11eb-92b4-6fc67550daca.png)

![](https://user-images.githubusercontent.com/184315/97131381-fba2ca00-177e-11eb-9e59-688dafa76aea.png)

![](https://user-images.githubusercontent.com/6129661/104897563-7ca2e380-59b3-11eb-8288-39a2b181183d.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 59 期](https://hellogithub.com/periodical/volume/59/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
