### ISSUE TITLE
自荐：简单通用的单表增删改查

### ISSUE THREAD

**Issue by loyayz** [521xueweihan/HelloGitHub#1637]
## 项目推荐
- 项目地址：https://github.com/loyayz/simple-crud

- 类别：Java

- 项目后续更新计划：目前通过mybatis支持rdbms的单表操作，后续将支持 mongodb、redis、es

- 项目描述：
简单通用的单表增删改查，无需任何配置，无需继承基类 Mapper，只需要定义数据库表对应的实体类即可获得通用方法。

- 推荐理由：简单使用方便，增加开发效率

- 示例代码：假设有一个表 user，只需要定义对应的实体类，即可使用 BaseMapper<User>
```java
// 定义实体类
@Table
public class User {
    String id;
    String name;
    //省略set和get方法
}

// 使用
@Autowired
BaseMapper<User> userMapper;

public void test() {
    User user = new User();
    user.setName("测试");
    userMapper.insert(user);
}
```

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
