### ISSUE TITLE
项目推荐-Swift项目

### ISSUE THREAD

**Issue by liumenghua** [521xueweihan/HelloGitHub#1638]
## 项目推荐
- 项目地址：https://github.com/stephencelis/SQLite.swift

- 类别：Swift

- 项目后续更新计划：7K+ star，业界使用广泛，贡献者活跃，持续维护中

- 项目描述：纯Swift实现的轻量级Sqlite3数据库框架

- 推荐理由：采用链式编程的写法，让数据库的管理变得优雅，可读性也很强, 即使你不会SQL语句，也可以使用数据库。

- 示例代码：

```swift
import SQLite

let db = try Connection("path/to/db.sqlite3")

let users = Table("users")
let id = Expression<Int64>("id")
let name = Expression<String?>("name")
let email = Expression<String>("email")

try db.run(users.create { t in
    t.column(id, primaryKey: true)
    t.column(name)
    t.column(email, unique: true)
})

// CREATE TABLE "users" (
//     "id" INTEGER PRIMARY KEY NOT NULL,
//     "name" TEXT,
//     "email" TEXT NOT NULL UNIQUE
// )
```

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 59 期](https://hellogithub.com/periodical/volume/59/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
