### ISSUE TITLE
推荐项目-NASA"机智号"火星无人机飞行软件框架

### ISSUE THREAD

**Issue by jasonli50358** [521xueweihan/HelloGitHub#1639]
## 项目推荐
- 项目地址：
https://github.com/nasa/fprime

- 类别：C，Python
- 
- 项目描述：该项目是一个组件驱动的框架，能够快速开发和部署太空飞行和其他嵌入式软件应用程序。项目最初是在喷气推进实验室开发的，已经成功地部署在多个空间应用上。它是量身定做的，但不限于小型的航天系统，如CubeSats、SmallSats和instruments。

- 推荐理由：NASA“机智号”火星无人机“同款”代码，你也可以用在自己的飞行器上。

- 截图：
![image](https://user-images.githubusercontent.com/12906777/109090938-ce772000-774e-11eb-9d06-bcfa3de91dfd.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。这玩意有点不实用，咱不收录啦。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
