### ISSUE TITLE
pydu：Python常用数据结构和工具库

### ISSUE THREAD

**Issue by Prodesire** [521xueweihan/HelloGitHub#164]
## 项目推荐
- 项目名称：
pydu

- 项目地址：
https://github.com/Prodesire/pydu

- 项目语言：
Python

- 项目描述：
pydu （python data structures and utils —— python 数据结构和工具）是一个面向Python 2和3的库。它收集自开源项目，也由贡献者创建。

- 推荐理由：
将平时常用的数据结构和工具都收录其中，可供日常开发使用，也可供学习借鉴。相比于GitHub上现存的pyutils等项目，其优势是积极维护，并有丰富文档。

- 示例代码：
英文版：http://pydu.readthedocs.io/en/latest/
中文版：http://pydu.readthedocs.io/zh/latest/

**Comment by 521xueweihan** [comment]
@Prodesire 您推荐的项目，已成功收录在 [HelloGitHub 第 21 期](https://hellogithub.com/volume/21/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，欢迎 Star ⭐️ 本项目，以便让更多人看到。
