### ISSUE TITLE
一个go用来生成随机单词的库.

### ISSUE THREAD

**Issue by ser163** [521xueweihan/HelloGitHub#1641]
## 项目推荐
- 项目地址：https://github.com/ser163/WordBot

- 类别：Go

- 项目后续更新计划：

- 项目描述：
  - 必写：WordBot是一个Go语言项目,是为了解决日常随机单词生成的库.日常开发中可以直接调用来生成随机的单词.
  - 可选：测试,随机单词起名
  - 描述长度（不包含示例代码）: 有了它可以随机生成单词字符串.可以定义位数1-19位. 可以设置大小写模式.基本满足日程生成随机字符,有此项目诸君不用重复造轮子。

- 推荐理由：简单易用,不用费神费力

- 示例代码：
```go
package main

import (
	"fmt"
	"github.com/ser163/WordBot/generate"
)

func main() {
	for i := 0; i < 5; i++ {
		w, err := generate.GenRandomWorld(0, "none")
		if err != nil {
			fmt.Println(err)
			break
		}
		fmt.Println(w.Chance, w.Word)
	}
}
```

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
