### ISSUE TITLE
【blind-watermark】Python图片盲水印算法库

### ISSUE THREAD

**Issue by guofei9987** [521xueweihan/HelloGitHub#1642]
## 项目推荐
- 项目地址：https://github.com/guofei9987/blind_watermark

- 英文文档：https://blindwatermark.github.io/blind_watermark/#/en/
- 中文文档：https://blindwatermark.github.io/blind_watermark/#/zh/
- 类别：Python

- 项目后续更新计划：1）改进数学基础，以增强算法鲁棒性。2）更高的并行化性能

- 项目描述：
  - 算法的功能：1）给图片打上盲水印，同时保证人眼感知不到图片有变化；2）给定一张已经打上盲水印的图片，提取出其中的盲水印。
  - 应用场景：数据泄漏溯源、版权保护等

- 推荐理由：与现有能找到的其它开源的算法相比，有以下亮点：1）解析隐水印时无需原图；2）支持密码加密； 3）极高的鲁棒性，对打上盲水印的图做任意旋转、裁剪、不规则挖空，都不会破坏其中的盲水印；4）作者来自阿里巴巴安全算法团队。

- 示例代码1：嵌入水印
```
from blind_watermark import WaterMark

bwm1 = WaterMark(password_wm=1, password_img=1)
# 读取原图
bwm1.read_img('pic/ori_img.jpg')
# 读取水印
bwm1.read_wm('pic/watermark.png')
# 打上盲水印
bwm1.embed('output/打上水印的图.png')
```
- 示例代码2：提取水印
```
bwm1 = WaterMark(password_wm=1, password_img=1)
# 注意需要设定水印的长宽wm_shape
bwm1.extract(filename='output/打上水印的图.png', wm_shape=(128, 128), out_wm_name='output/解出的水印.png', )
```
- 效果一览：
![image](https://user-images.githubusercontent.com/19920283/109295746-38381c80-786a-11eb-8939-984e3f9045c4.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 59 期](https://hellogithub.com/periodical/volume/59/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

**Comment by guofei9987** [comment]
> 您推荐的项目，**已成功发布**在 [HelloGitHub 第 59 期](https://hellogithub.com/periodical/volume/59/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

hello，我看到 59 期文档，我这边跑出来的效果是这样的：

原图：
![hellogithub图](https://user-images.githubusercontent.com/19920283/109446104-08606300-7a7c-11eb-8ef4-ae201144cc50.png)

logo：
![hellogithub的logo](https://user-images.githubusercontent.com/19920283/109446118-0dbdad80-7a7c-11eb-8b85-d8e514cfd487.png)

打上logo的图
![embedded](https://user-images.githubusercontent.com/19920283/109446137-1615e880-7a7c-11eb-80b3-f2a9e3f7b8d0.png)

解出的水印

![wm_extracted](https://user-images.githubusercontent.com/19920283/109446156-1c0bc980-7a7c-11eb-90b7-6d559d6ccffe.png)

代码如下：

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from blind_watermark import WaterMark

bwm1 = WaterMark(password_wm=1, password_img=1)
# 读取原图
bwm1.read_img('hellogithub/hellogithub图.png')
# 读取水印
bwm1.read_wm('hellogithub/hellogithub的logo.png')
# 打上盲水印
bwm1.embed('hellogithub/embedded.png')

# %% 解水印


bwm1 = WaterMark(password_wm=1, password_img=1)
# 注意需要设定水印的长宽wm_shape
bwm1.extract(filename='hellogithub/embedded.png', wm_shape=(122, 122), out_wm_name='hellogithub/wm_extracted.png', )
```

**Comment by 521xueweihan** [comment]
感谢，已修改为您的示例图

![](https://raw.githubusercontent.com/521xueweihan/img2/master/hellogithub/59/img/blind_watermark.png)
