### ISSUE TITLE
Avatarify 视频会议实时换脸工具

### ISSUE THREAD

**Issue by SekiBetu** [521xueweihan/HelloGitHub#1643]
## 项目推荐
- 项目地址：https://github.com/alievk/avatarify

- 类别：Python

- 项目后续更新计划：训练模型是成熟的，维护的是软件本身的运行BUG等

- 项目描述：利用机器学习训练的模型，通过捕捉人脸动作并与图片相结合进行实时渲染的方式，达到实时换脸的效果

- 推荐理由：最近比较热门的IOS上的换脸应用Avatarify的原项目，可以用于OBS、Zoom、Skype、Teams、Slack等直播、会议软件上，实时进行渲染换脸，且支持跨平台安装使用

- 截图：
![image](https://raw.githubusercontent.com/alievk/avatarify/master/docs/mona.gif)

**Comment by 521xueweihan** [comment]
很及时啊，本期刚好没有机器学习的项目！

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 59 期](https://hellogithub.com/periodical/volume/59/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
