### ISSUE TITLE
微前端解决方案 m-app

### ISSUE THREAD

**Issue by ambit-tsai** [521xueweihan/HelloGitHub#1646]
## 项目推荐
- 项目地址：https://github.com/ambit-tsai/m-app

- 类别：JS

- 项目后续更新计划：1) 支持微应用预加载 2) 支持微应用嵌套

- 项目描述：新一代微前端解决方案，可替代 iframe 作为微应用的接入容器，实现对 DOM、CSS、JS 的硬隔离，做到真正的技术栈无关，并且运行时集成，微应用可独立开发、部署、升级。使用如 iframe 般简便，却超脱 iframe 的局限，你值得一试！

- 推荐理由：实现对 DOM、CSS、JS 的硬隔离，做到真正的技术栈无关，并且运行时集成，微应用可独立开发、部署、升级。

- 示例代码：
```html
<m-app entry="http://example.com/path/to/entry.html"></m-app>
```

- 截图：（可选）gif/png/jpg
![m-app](https://user-images.githubusercontent.com/42671189/109739858-3ae99780-7c05-11eb-893f-7e6cb78fd469.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
