### ISSUE TITLE
Kdiff3

### ISSUE THREAD

**Issue by assange0** [521xueweihan/HelloGitHub#1647]
## 项目推荐
- 项目地址：https://github.com/KDE/kdiff3

- 类别：C++

- 项目后续更新计划：此项目随着KDE框架版本更新进行迭代，以及日常bug修复。

- 项目描述：
  - 必写：KDE项目里的一个代码比较/合并工具

- 推荐理由：Kdiff3历史悠久，早期是Qt4开发的工具，已经停止维护。现在新的Kdiff3主要由KDE官方开发者维护，已经更新到Qt5版本，代码简洁。工具本身使用体验也不错，除了自带的配色方案比较有槽点，适合新手学习Qt5/C++小工具的开发。目前代码维护在KDE官方的[Gitlab](https://invent.kde.org/sdk/kdiff3)里，镜像到[Github](https://github.com/KDE/kdiff3)上，二进制发布地址是[KDE Download](https://download.kde.org/stable/kdiff3/)。

- 截图：
![kdiff3](https://user-images.githubusercontent.com/8962458/109785390-0e566f80-7c47-11eb-8741-28c0efa92439.png)

**Comment by 521xueweihan** [comment]
您好，已收录类似项目，您的项目暂不收录。
