### ISSUE TITLE
【项目自荐】fun-comment：一款可以将图片转化成 ascii 字符添加到注释里的 VSCode 插件

### ISSUE THREAD

**Issue by 5A59** [521xueweihan/HelloGitHub#1648]
## 项目推荐
- 项目地址：
https://github.com/5A59/fun-comment

- 类别：TS

- 项目描述：
Fun-Comment 提供了在注释中插入 ascii 图片或文字的功能，可以让代码注释变得花里胡哨起来。     
具体功能如下，在编辑区点右键，有两个选项：    
  - "Fun-comment Add Image Comment"：选择这个，会弹出图片选择器，选择一个图片后会插入图片的 ascii 样式
  - "Fun-comment Add Text Comment"：选择这个，会将已经选择的文字替换成 ascii 样式，前提需要先选中一段文字

- 推荐理由：一款可以将图片转化成 ascii 字符添加到注释里的 VSCode 插件

- 安装：
  VSCode extensions 搜索 “fun-comment” 即可下载体验

- 截图：
![gif](https://zylab.oss-cn-beijing.aliyuncs.com/fun-comment/Fun-Comment.gif)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
