### ISSUE TITLE
项目推荐-npkill

### ISSUE THREAD

**Issue by sz-p** [521xueweihan/HelloGitHub#1649]
## 项目推荐
- 项目地址：[npkill](https://github.com/voidcosmos/npkill)

- 官网：[npkill官网](https://npkill.js.org/)

- 类别：nodejs、工具

- 项目后续更新计划：最后更新于2021年2月

- 项目描述：

一个快速定位，删除`node_modules`库的工具。

- 推荐语：

还在因`node_modules`过重而烦恼吗？还在手动找不再开发的临时工程吗？快来试试[npkill](https://npkill.js.org/)。轻松解决`node_modules`，释放磁盘空间。

背景：

![image](https://user-images.githubusercontent.com/14040327/109897760-258c7000-7cce-11eb-8ab8-f0ceb1843e82.png)

**Comment by 521xueweihan** [comment]
如果方便请优化下项目描述和推荐语，可参考往期月刊的推荐语。

修改后可以通过@告知我，该项目会在下期收录。

**Comment by sz-p** [comment]
@521xueweihan

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 61 期](https://hellogithub.com/periodical/volume/61/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
