### ISSUE TITLE
一个开源服务器框架——jwEngine，适用于小游戏服务器开发

### ISSUE THREAD

**Issue by jwcpp** [521xueweihan/HelloGitHub#1651]
## 项目推荐
- 项目地址：https://github.com/jwcpp/jwEngine

- 类别：C++、lua、游戏服务器

- 项目后续更新计划：修正反馈的bug

- 项目描述：
          一个跨平台的c++<->lua服务器快速解决方案，该框架即可快速响应服务器开发工作，设计思想：“让事情变得更简单”。
          网络底层采用libuv（node.js底层库），异步io助力使单线程也能释放澎湃动力，跨平台支持epoll、iocp、ipv6。框架支持tcp、udp/kcp、websocket、http，并保证了接口的一致性，使用了sol2将所有接口都导出到lua，可以选择用lua开发逻辑。
          使用modern c++开发，尽可能的使用std::move、std::string_view减少内存复制。
          该框架使用异步事件，不建议使用多线程，避免多线程上下文切换开销和破坏代码美感，网络部分和逻辑部分使用一个主事件循环驱动。建议的方案是多进程单线程的横向扩展，按照业务控制各个进程的粒度，当然mysql和redis可以加入到线程池中。

- 推荐理由：支持tcp、kcp、websocket、http、protobuf、mysql、redis。lua作为逻辑开发，使用简单，能够快速搭建小游戏服务器

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 60 期](https://hellogithub.com/periodical/volume/60/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
