### ISSUE TITLE
rtty - 在任何地方通过Web访问您的设备的终端 

### ISSUE THREAD

**Issue by zhaojh329** [521xueweihan/HelloGitHub#1652]
## 项目推荐
- 项目地址：https://github.com/zhaojh329/rtty

- 类别：C

- 项目后续更新计划：服务端新增用户注册，设备管理

- 项目描述：
  - 通过 rtty，您可以在任何地方通过 Web 访问您的设备的终端。通过设备 ID 来区分您的不同的设备。它由客户端和服务端组成。客户端采用纯 C 实现（适合嵌入式 Linux 设备）。服务端采用 GO 语言实现，前端界面采用 vue 实现。

- 推荐理由：
  - rtty 非常适合远程维护部署在全球各地的成千上万的 Linux 设备。
  - 客户端采用 C 语言实现，加上依赖库不到 100KB，适合嵌入式 Linux 设备。
  - 支持远程传输文件。
  - 支持远程访问设备的 Web 界面。

- 截图：
![diagram](https://raw.githubusercontent.com/zhaojh329/rtty/doc/diagram.png)
![terminal](https://raw.githubusercontent.com/zhaojh329/rtty/doc/terminal.gif)
![file](https://raw.githubusercontent.com/zhaojh329/rtty/doc/file.gif)
![web](https://raw.githubusercontent.com/zhaojh329/rtty/doc/web.gif)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 60 期](https://hellogithub.com/periodical/volume/60/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
