### ISSUE TITLE
项目推荐-MZC8051 c语言单片机编译器

### ISSUE THREAD

**Issue by Jiangshan00001** [521xueweihan/HelloGitHub#1655]
## 项目推荐
- 项目地址：https://github.com/Jiangshan00001/MZC8051

- 类别：C++

- 项目后续更新计划：
- 完善一个编译器
- 实现单片机的编译总流程
- 稳定，性能好

- 项目描述：
  - 必写：编译器开发项目。一个单片机的c语言编译器。用于各种单片机。希望开发一个国内的开源的编译器基础项目。
  - 可选：有仿真的单片机例程适合于单片机学习者。代码本身是一个编译器的实现，可用于学习编译器实现。可以在此代码基础上添加代码优化，或者添加前端后端代码。

- 推荐理由：国内唯一的一个开源单片机c语言编译器，全球也仅有sdcc是类似的项目。

- 示例代码：
 void main()
{
int a=4;
}

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
