### ISSUE TITLE
一个能让你的网站自如切换 🌜/🌞 (黑夜/白天)模式的 React Hook

### ISSUE THREAD

**Issue by Turkyden** [521xueweihan/HelloGitHub#1659]
## 项目推荐
- 项目地址：https://react-darkreader.vercel.app/

- 类别：JS

- 项目后续更新计划：支持 localStorage 浏览器记录主题模式，支持主题随着系统主题而变化

- 项目描述：
  - 一个能让你的网站自如切换 🌜/🌞 (黑夜/白天)模式的 React Hook！无需编写 ~~CSS~~，多种 Switch 组件任你选择。

- 推荐理由：想让自己的博客和 Github 一样，生动起来，自如切换 🌜/🌞 (黑夜/白天)模式，而又不想写任何 CSS，或对网站进行样式重构，那么 [react-darkreader](https://react-darkreader.vercel.app/) 一定适合你。

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

![wwdd](https://user-images.githubusercontent.com/24560160/110283222-ae7f1080-801a-11eb-8cb8-4878f6598ce2.gif)

![image](https://user-images.githubusercontent.com/24560160/110282993-5e07b300-801a-11eb-823f-e4456cd717af.png)

![image](https://user-images.githubusercontent.com/24560160/110282960-534d1e00-801a-11eb-92d7-03a1488dd366.png)

**Comment by Turkyden** [comment]
太水了，这个校验机制，我填了 10 次，都通不过，没发推荐。

**Comment by 521xueweihan** [comment]
@Turkyden  那你为什么不反思下自己填写的内容？并且bot已经提示联系我，你一句：“太水了”，谁欠你的吗？

**Comment by Turkyden** [comment]
> @Turkyden
> 
> 你知道我们为什么叫 HelloGitHub 还有什么叫项目地址吗？
> 
> 你为什么不反思下自己填写的内容？并且bot已经提示联系我，你一句：“太水了”，谁欠你的吗？

不好意思博主，我不是说你，我是说这个 Action 校验。对不起博主，误会了误会了。
