### ISSUE TITLE
FloatWindow-Andorid 任意界面悬浮窗

### ISSUE THREAD

**Issue by yhaolpz** [521xueweihan/HelloGitHub#166]
## 项目推荐
- 项目名称：
FloatWindow

- 项目地址：
https://github.com/yhaolpz/FloatWindow

- 项目语言：
Java

- 项目描述：
Andorid 任意界面悬浮窗，实现悬浮窗如此简单

- 推荐理由：
功能全面，链式调用，简洁清爽

- 示例代码：
https://github.com/yhaolpz/FloatWindow/blob/master/sample/src/main/java/com/example/yhao/floatwindow/BaseApplication.java

**Comment by 521xueweihan** [comment]
@yhaolpz   您推荐的项目，已成功收录在 [HelloGitHub 第 22 期](https://hellogithub.com/volume/22/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，欢迎 Star ⭐️ 本项目，以便让更多人看到。
