### ISSUE TITLE
ChatUI - 服务于对话领域的设计和开发体系，助力智能对话机器人的搭建

### ISSUE THREAD

**Issue by akai** [521xueweihan/HelloGitHub#1666]
## 项目推荐
- 项目地址：https://github.com/alibaba/ChatUI

- 类别：JS

- 项目后续更新计划：丰富组件，完善功能

- 项目描述：ChatUI 是服务于智能对话领域的设计和开发体系，由阿里云达摩院阿里小蜜团队基于阿里小蜜业务孵化而来，目前已经支持了阿里经济体80多个事业部，数千个 Chatbot (对话式机器人)。ChatUI 可以帮助用户快速搭建体验友好的机器人对话界面，部分独立软件开发商已经投入使用，开发周期从平均14天缩短到2天。

- 推荐理由：
  - 可以帮助用户快速搭建体验友好的机器人对话界面
  - 最佳实践：基于阿里小蜜业务积累和打磨的对话式交互最佳实践
  - TypeScript：使用 TypeScript 开发，提供完整的类型定义文件
  - 响应式：响应式布局，在无线和 PC 端都可以友好展现
  - 无障碍：支持无障碍，已通过深圳市无障碍研究会的认证
  - 主题：支持灵活的样式定制，以满足业务和品牌上多样化的视觉需求
  - 国际化：支持多语言和本土化特性

- 示例代码：

```js
import Chat, { Bubble, useMessages } from '@chatui/core';
import '@chatui/core/dist/index.css';

const App = () => {
  const { messages, appendMsg, setTyping } = useMessages([]);

  function handleSend(type, val) {
    if (type === 'text' && val.trim()) {
      appendMsg({
        type: 'text',
        content: { text: val },
        position: 'right',
      });

      setTyping(true);

      setTimeout(() => {
        appendMsg({
          type: 'text',
          content: { text: 'Bala bala' },
        });
      }, 1000);
    }
  }

  function renderMessageContent(msg) {
    const { content } = msg;
    return <Bubble content={content.text} />;
  }

  return (
    <Chat
      navbar={{ title: '智能助理' }}
      messages={messages}
      renderMessageContent={renderMessageContent}
      onSend={handleSend}
    />
  );
};
```

- 截图：![](https://gw.alicdn.com/tfs/TB1NVmpU7L0gK0jSZFtXXXQCXXa-1992-1462.jpg) ![](https://img.alicdn.com/imgextra/i1/O1CN01dAYCc61jWEk9pO1O7_!!6000000004555-2-tps-750-1334.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 60 期](https://hellogithub.com/periodical/volume/60/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
