### ISSUE TITLE
项目自荐 | TRPG Engine - 专注于TRPG的IM应用

### ISSUE THREAD

**Issue by moonrailgun** [521xueweihan/HelloGitHub#1667]
## 项目推荐
- 项目地址：https://github.com/TRPGEngine/Client

- 类别：JS

- 项目后续更新计划：
  - 增加网格地图
  - 增加语音会议录音
  - 重写移动端App

- 项目描述：
`TRPG Engine` 是一款帮助用户更加方便跑团的即时通信软件。正如名字所言，本项目的定位是作为一个引擎的存在，用于帮助用户更快很好的进行沟通与交互，让主持人将精力专注于剧情、场景上。

  互联网的发展，让人与人之间线下沟通的机会变少了，却让线上交流的机会变多了。通过网络，可以让五湖四海的人聚在一起。面团的机会让人羡慕却很少能够实现，网团将会成为跑团未来发展的趋势。而这就是我为什么要开发这款应用的原因，希望能让更多的人来体会跑团的魅力，而不是被一些琐碎的事情打败。

  - 因为字数限制更多见: [TRPG Engine 介绍](https://trpgdoc.moonrailgun.com/docs/introduce)
  - 关于跑团: 
    - [桌上角色扮演游戏(Wiki)](https://zh.wikipedia.org/wiki/%E6%A1%8C%E4%B8%8A%E8%A7%92%E8%89%B2%E6%89%AE%E6%BC%94%E9%81%8A%E6%88%B2)
    - [桌上角色扮演游戏(百度百科)](https://baike.baidu.com/item/%E6%A1%8C%E4%B8%8A%E8%A7%92%E8%89%B2%E6%89%AE%E6%BC%94%E6%B8%B8%E6%88%8F/7357787)

- 推荐理由：
正如`slack`解决工作的交流, `discord`专注于游戏, `TRPG Engine`就是类似的专注于跑团这个领域的即时通讯应用。它通过各种开放的定制化的配置使开放的、沙盒式的跑团游戏能有定制化与自由的可能。

- 截图：

![image](https://user-images.githubusercontent.com/6964737/110915889-2cad2100-8353-11eb-9cee-7d0f523483b1.png)

![image](https://user-images.githubusercontent.com/6964737/110915942-3b93d380-8353-11eb-88f5-6c8c11fa4cd8.png)

![image](https://user-images.githubusercontent.com/6964737/110915983-464e6880-8353-11eb-923a-4b24e928dddb.png)

![image](https://user-images.githubusercontent.com/6964737/110916039-549c8480-8353-11eb-8ee0-deeba7483fe4.png)

![image](https://user-images.githubusercontent.com/6964737/110916097-6716be00-8353-11eb-9669-54fbaee0e3ba.png)

**Comment by 521xueweihan** [comment]
@moonrailgun 请问什么是 跑团？

**Comment by moonrailgun** [comment]
> @moonrailgun 请问什么是 跑团？

@521xueweihan 感谢您的回复

跑团是进行TRPG游戏的过程行为的代称

![image](https://user-images.githubusercontent.com/6964737/112315188-d772f700-8ce4-11eb-987d-ddab1d66c9ed.png)

具体可以参考[wiki](https://zh.wikipedia.org/wiki/%E6%A1%8C%E4%B8%8A%E8%A7%92%E8%89%B2%E6%89%AE%E6%BC%94%E9%81%8A%E6%88%B2)

**Comment by 521xueweihan** [comment]
等开发完语音功能再来推荐吧！

**Comment by moonrailgun** [comment]
> 等开发完语音功能再来推荐吧！

@521xueweihan  你好，语音功能已经开发完了。支持多人语音通话

可以创建一个语音频道随时体验。

**Comment by moonrailgun** [comment]
@521xueweihan Hi, 你好, 距离上次的交流已经 12 天过去了。

请问有任何的更新么? 或者为了推动这个项目的自荐有什么需要我来配合的么？

希望能够告知。感谢您的 review

**Comment by 521xueweihan** [comment]
我没有看到你的介绍中支持多人语音通话，而且我们已经推荐过难过 JS 写的在线聊天室项目了。

所以您的项目暂不收录了

**Comment by moonrailgun** [comment]
@521xueweihan 感谢您的回复

关于多人语音在这里有介绍:
![image](https://user-images.githubusercontent.com/6964737/114138405-2b661880-9940-11eb-80d5-3130964cc2ff.png)

关于您对于多人聊天项目的说法我不敢苟同。
就好像您推荐了钉钉，就不推荐slack了？这两者都是为了工作而存在但并不是同样方向的东西，也完全不能说谁能替代谁。

同时不同的项目深度也是不同的。`TRPG Engine`持续迭代了3年以上, 累计提交4500+commit, 并专注于跑团这一小众领域。并不是一个简单的即时通讯软件。他的定位和`discord`, `slack`, `gitter`一样。都是专注于某个特定领域而存在的软件。如果仅仅仅限于看到他的即时通讯部分那么只能说没有关注到它更加有价值的部分 —— 即时通讯部分仅仅是一切的基础而不是所有。

她具有一个企业级项目应有的一切配置: 多配置，自定义，分布式部署。完善的文档, 完善的错误收集, 用户行为分析, 接口metrics分析, 日志汇总, 配套的rn移动端应用(包括codepush的热更新, 国内特色的多平台消息推送)。OAuth第三方登录, 接口熔断限流, 第三方机器人集成，基于BBCode二次实现的消息解释器，自部署的语音会议室系统以及一套功能完备的DSL语言与其运行时以帮助用户自定义他们自己的人物卡模板, 等等其他的功能。

坦白的讲我不认为国内的开源项目中有很多在技术深度上和`TRPG Engine`一样的在线聊天室项目 —— 因为它们往往都商业化了。而我期望能在您的平台上寻找志同道合的, 纯粹热爱技术热爱开源的伙伴一起继续完善下去。

总之感谢您的回复与时间, 如果您执意不愿意收录`TRPG Engine`, 那么也没有关系。我们下次还有合作的机会，但我个人很希望您能看到`TRPG Engine`的价值, 并给予她一个机会。谢谢
