### ISSUE TITLE
项目Illumine推荐（PythonWEB框架）

### ISSUE THREAD

**Issue by streetartist** [521xueweihan/HelloGitHub#1669]
## 项目推荐
- 项目地址：https://github.com/streetartist/Illumine

- 类别：Python

- 项目后续更新计划：大约每周更新一次（因为是初中生）
- 项目描述：
  - 必写：Python的一个网页框架，支持像Wordpress那样的扩展
  - 可选：网站编写
  - 描述长度（不包含示例代码）: 目标是让用户在不修改内核代码的情况下，通过编写插件电池主题，来编写网站

- 推荐理由：
1.电池是事先编写好的网页框架（框架中的框架），加快编写速度
2.支持多个框架：Flask、Fastapi

- 示例代码：
```python
# from battery.blog.admin import isadmin
from battery.blog.db import Post

class Main:
    def __init__(self, render):
        self.render = render
        self.name ="new"
    def main(self,session,request=None,arg=None,plugin=None):
        # @isadmin(session)
        def this():
            if request == None:
                return self.render("new.html",welcome = True,post=Post.select())
            else:
                title = request.form.get("title")
                text = request.form.get("text")
                time = request.form.get("time")
                author = request.form.get("author")
                tag = request.form.get("tag")

                p = Post(tag=tag, time=time, author = author, content = text,title = title)
                p.save()
                return "创建成功！"
        
        return this()
```
- 截图：
![image](https://user-images.githubusercontent.com/60282562/111028280-9d763b00-8430-11eb-9098-b10fadbed0c5.png)
![image](https://user-images.githubusercontent.com/60282562/111028290-ae26b100-8430-11eb-87f3-cec120888304.png)
![image](https://user-images.githubusercontent.com/60282562/111028298-b7b01900-8430-11eb-80d1-048ccfdde1b3.png)
![image](https://user-images.githubusercontent.com/60282562/111028317-d0203380-8430-11eb-8432-7f729fe9c173.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
