### ISSUE TITLE
simple-railway-captcha-solver : 实作基于CNN的订票验证码辨识以及验证性高的训练集产生器

### ISSUE THREAD

**Issue by JasonLiTW** [521xueweihan/HelloGitHub#167]
## 项目推荐
- 项目名称：simple-railway-captcha-solver

- 项目地址：https://github.com/JasonLiTW/simple-railway-captcha-solver

- 项目语言：Python

- 项目描述：实作基于CNN的订票验证码辨识以及验证性高的训练集产生器

- 推荐理由：写了详细的教程，有兴趣不妨来看看吧〜

- 示例代码：https://github.com/JasonLiTW/simple-railway-captcha-solver/blob/master/train_cnn.py
https://github.com/JasonLiTW/simple-railway-captcha-solver/blob/master/captcha_gen.py

**Comment by JasonLiTW** [comment]
不好意思，刚刚没编辑到内容就按到Enter送出了，已编辑好。

**Comment by 521xueweihan** [comment]
@JasonLiTW 收到，期待之后推荐更多项目 😊

**Comment by 521xueweihan** [comment]
@JasonLiTW 你好，本期决定推荐这个基于机器学习的验证码破解项目：https://github.com/ypwhs/captcha_break

由于篇幅和内容关系，不能收录你的项目，望海涵，继续推荐更加有意义、价值、有意思的项目

**Comment by NickYi1990** [comment]
> @JasonLiTW 你好，本期决定推荐这个基于机器学习的验证码破解项目：https://github.com/ypwhs/captcha_break
> 
> 由于篇幅和内容关系，不能收录你的项目，望海涵，继续推荐更加有意义、价值、有意思的项目

@JasonLiTW 在我看来更加有实际意义
