### ISSUE TITLE
应该是node.js生态中最好的后台权限管理系统框架

### ISSUE THREAD

**Issue by cool-team-official** [521xueweihan/HelloGitHub#1671]
## 项目推荐
- 项目地址：https://github.com/cool-team-official/cool-admin-midway

- 类别：node.js

- 项目后续更新计划：
   更多的插件、更多的通用模块

- 项目描述：
  cool-admin(midway版)一个很酷的后台权限管理框架，模块化、插件化、CRUD极速开发，永久开源免费，基于midway.js 2.0、typeorm、mysql、jwt、element-ui等构建。也跟紧了云开发时代，支持打包发布到阿里与腾讯serverless，也支持普通ecs服务器部署，docker部署。

- 推荐理由：node.js的后台管理系统框架很少，这应该是node.js生态最好的的后台权限管理系统，该系统受阿里midwayjs文档推荐，受github精选公众号推荐，永久开源免费可商用

- 截图：![](https://admin.cool-js.com/admin-home.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 60 期](https://hellogithub.com/periodical/volume/60/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
