### ISSUE TITLE
【项目推荐】Swift项目-简洁易用的着色工具Hue

### ISSUE THREAD

**Issue by liumenghua** [521xueweihan/HelloGitHub#1673]
## 项目推荐
- 项目地址：https://github.com/zenangst/Hue

- 类别：Swift

- 项目后续更新计划：该项目API稳定，使用较多，适配最新版本Swift

- 项目描述：Hue是一个集合多个功能于一体的着色工具，在iOS开发中非常好用，可以快速简单的进行UI的颜色设置、透明度修改、设置渐变颜色、修改图片的颜色等。

- 推荐理由：相比于使用Swift原生繁重复杂的RGBA颜色API，Hue仅需要一行代码，简洁易用。

- 示例代码：

```swift
// 设置16进制颜色
let white = UIColor(hex: "#ffffff")
let black = UIColor(hex: "#000000")

// 设置alpha
let colorWithAlpha = myColor.alpha(0.75)

// 设置渐变
let gradient = [UIColor.blackColor(), UIColor.orangeColor()].gradient()

let secondGradient = [UIColor.blackColor(), UIColor.orangeColor()].gradient { gradient in
  gradient.locations = [0.25, 1.0]
  return gradient
}
```

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 60 期](https://hellogithub.com/periodical/volume/60/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
