### ISSUE TITLE
【项目推荐】kotlin项目 Android 极简跳转页面工具

### ISSUE THREAD

**Issue by smartbackme** [521xueweihan/HelloGitHub#1674]
项目地址：https://github.com/smartbackme/AutoPage

类别：kotlin

项目后续更新计划：目前稳定版，后续根据Android api考虑扩展

项目描述：Android通过一行代码就可快速跳转其他ui页面

推荐理由：原有Android跳转复杂而又麻烦，如果参数极多的情况下，更是难以维护。这个工具，能提升项目可维护度和简洁

示例代码：

// 简单的跳转并且带参数
class MainActivity2 : AppCompatActivity() {

    @AutoPage
    @JvmField
    var message:String? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main2)
        AutoJ.inject(this)
        findViewById<TextView>(R.id.text).text = message
    }

ApMainActivity2.getInstance().setMessage("123").start(this)

// 跳转带有result
@AutoPage
class SimpleJumpResultActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_simple_jump_result)
    }

    override fun onBackPressed() {
        var intent = Intent()
        intent.putExtra("message","123")
        setResult(RESULT_OK,intent)
        super.onBackPressed()
    }
}

ApSimpleJumpResultActivity.getInstance().requestCode(1).start(this)

// 简单的跳转
@AutoPage
class SimpleJump1Activity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_simple_jump1)
    }
}

ApSimpleJump1Activity.getInstance().start(this)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
