### ISSUE TITLE
项目推荐 | fawkes 修改照片欺骗面部识别系统

### ISSUE THREAD

**Issue by SekiBetu** [521xueweihan/HelloGitHub#1675]
## 项目推荐
- 项目地址：https://github.com/Shawn-Shan/fawkes

- 类别：机器学习

- 项目后续更新计划：不清楚

- 项目描述：芝加哥大学 Sand Lab 团队创建的 Fawkes 技术。主要通过 AI 技术，对像素进行一些微调，普通人很难看出两者的区别，但对于人脸识别系统来说，这就是天壤之别。

- 推荐理由：315刚报道了人脸识别技术的滥用，这个项目能帮到喜欢在社交平台发布自己照片而又怕照片被拿去滥用的人

- 截图：
![image](https://user-images.githubusercontent.com/38283893/111585972-18f23680-87fb-11eb-856f-e38c4ba56dce.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 60 期](https://hellogithub.com/periodical/volume/60/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
