### ISSUE TITLE
Linux效率神器Albert

### ISSUE THREAD

**Issue by itgoyo** [521xueweihan/HelloGitHub#168]
## 项目推荐
- 项目名称：Albert

- 项目地址：https://github.com/albertlauncher/albert

- 项目语言：C++

- 项目描述：Albert是在Linux下面的类似于Mac Alfred效率神器,比Bash更快方便快捷,可开机自启动还有自定义快捷键

- 推荐理由：提高Linux用户使用软件的效率

- 截图：

![](http://omvbl46i3.bkt.clouddn.com/7dec8698e7747cefa6d1621523382ea4.png)

![](http://omvbl46i3.bkt.clouddn.com/898b669a326feca856f9acf1b8877eaa.png)

![](http://omvbl46i3.bkt.clouddn.com/7b44b72216d1021a72ca14e7b35acd67.png)

**Comment by 521xueweihan** [comment]
@itgoyo   您推荐的项目，已成功收录在 [HelloGitHub 第 22 期](https://hellogithub.com/volume/22/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，欢迎 Star ⭐️ 本项目，以便让更多人看到。
