### ISSUE TITLE
[项目自荐] pyworkflow

### ISSUE THREAD

**Issue by kedixa** [521xueweihan/HelloGitHub#1681]
## 项目推荐
- 项目地址：https://github.com/sogou/pyworkflow

- 类别：Python

- 项目后续更新计划：
  本项目已经完整实现了Workflow中的大部分任务，近期正在开发MySQL任务和Kafka任务，后续会跟随C++ Workflow同步更新。
- 项目描述：
  [C++ Workflow](https://github.com/sogou/workflow)是一个高性能的异步引擎，PyWorkflow基于C++ Workflow和Pybind11，实现一套Python语言的接口，将Workflow的理念引入到Python语言当中，让Python用户也能享受Workflow带来的绝佳体验。

- 推荐理由：
  - 将Workflow新颖的任务流结构引入Python语言
  - 支持Http、Redis协议，即将支持MySQL、Kafka协议

- 示例代码：

```python
# 依次发起两个Http请求，且中间暂停一秒
import pywf as wf

def series_callback(s):
    print("All task in this series is done")

def http_callback(http_task):
    state = http_task.get_state()
    error = http_task.get_error()
    if state == wf.WFT_STATE_SUCCESS:
        req = http_task.get_req()
        resp = http_task.get_resp()
        print("uri:{} status:{}".format(
            req.get_request_uri(),
            resp.get_status_code()))
    else:
        print(wf.get_error_string(state, error))

def create_http_task(url):
    return wf.create_http_task(url, 4, 2, http_callback)

first_task = create_http_task("http://www.sogou.com")
series = wf.create_series_work(first_task, series_callback)
series.push_back(wf.create_timer_task(1000 * 1000, None))
series.push_back(create_http_task("https://www.zhihu.com/people/kedixa"))
series.start()
wf.wait_finish()
```

**Comment by 521xueweihan** [comment]
已推荐过：Workflow，所以您的项目暂不能收录到月刊。

**Comment by Barenboim** [comment]
你好。其实我们的pyworkflow和C++ Workflow项目还是很不一样的，主要目的是为了让python用户也可以使用到workflow的高性能，任务流，以及多种client的实现。目前我们也已经完成了MySQL客户端的Python接口。
我们先继续改进，等功能上更完善一些了再麻烦你看一看。非常感谢之前推荐workflow和srpc：）
