### ISSUE TITLE
【项目自荐】brick design全场景可视化拖拽低代码编辑器

### ISSUE THREAD

**Issue by anye931123** [521xueweihan/HelloGitHub#1682]
## 项目推荐
- 项目地址：[https://github.com/brick-design/brick-design](https://github.com/brick-design/brick-design)
- 在线预览：[https://brick-design.github.io/brick-design/](https://brick-design.github.io/brick-design/)

- 类别：js

- 项目后续更新计划：持续更新功能，专注全场景低代码实现。

- 项目描述：
  - 必写：这是一个适用于全场景的可视化低代码编辑器
  - 可选：适用于全场景
  - 描述长度（不包含示例代码）: brick design实现 1、组件自由拖拽嵌套 2、组件逻辑渲染 3、组件列表渲染 4、组件方法渲染 5、组件map渲染 6、组件可以拖拽到任何位置，不仅限于子节点，包括属性节点 7、自定义方法 8、状态域管理，子页面自成一域 9、实时参考线辅助还原 10、丝滑拖拽更改大小  11、实时交互编辑展示  12、所见即所得 

- 推荐理由：1、全场景支持  2、所见即所得  3、自由拖拽，自由嵌套组合  4、实时交互展示  5、所见即所得 

- 截图：（可选）gif/png/jpg

https://user-images.githubusercontent.com/15995127/111975099-28df8280-8b3b-11eb-8fcc-5dd9a286414c.mp4

![brickd1](https://user-images.githubusercontent.com/15995127/85188005-7e4de100-b2d6-11ea-9441-2bd5570b14a9.gif)
![brickd2](https://user-images.githubusercontent.com/15995127/85187856-86595100-b2d5-11ea-883e-e45313797fb3.gif)
![brickd3](https://user-images.githubusercontent.com/15995127/85187862-92451300-b2d5-11ea-8394-a6c06b45de97.gif)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。这期的 JS 项目太多了，您的项目不能收录了。望见谅

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
