### ISSUE TITLE
项目推荐 - CabloyJS

### ISSUE THREAD

**Issue by zhennann** [521xueweihan/HelloGitHub#1685]
## 项目推荐

- 项目地址：https://github.com/zhennann/cabloy

- 类别：node.js

- 项目后续更新计划：

1. 在现有前后端分离架构的基础上，支持所有类型数据的静态渲染机制（从而支持SEO）
2. 实现工作流的可视化编辑

- 项目描述：

CabloyJS 是一款 NodeJS 开源全栈框架，通过前后端分离、模块化的架构设计，可以快速开发全场景业务。内置 NodeJS 工作流引擎、业务数据实现`草稿->正式->历史`全生命周期管理、角色授权、数据授权、Bean 容器、明细表、消息推送，等一系列核心功能

CabloyJS支持各类跨平台、跨端开发，诸如：后台管理系统、微信公众号、企业微信、钉钉、博客、社区、论坛、技术文档站点，等等

- 推荐理由：自带NodeJS工作流引擎，显著扩展了NodeJS的开发适应场景

- 示例代码：

``` javascript
    async startByKey({ flowDefKey, flowAtomId, flowVars, flowUserId, startEventId }) {
      // fullKey
      const { fullKey } = ctx.bean.flowDef._combineFullKey({ flowDefKey });
      // get flow def
      const flowDef = await ctx.bean.flowDef.getByKey({ flowDefKey });
      if (!flowDef) ctx.throw.module(moduleInfo.relativeName, 1001, fullKey);
      if (flowDef.atomDisabled === 1) ctx.throw.module(moduleInfo.relativeName, 1002, fullKey);
      return await this._start({ flowDef, flowAtomId, flowVars, flowUserId, startEventId });
    }

    async startById({ flowDefId, flowAtomId, flowVars, flowUserId, startEventId }) {
      // get flow def
      const flowDef = await ctx.bean.flowDef.getById({ flowDefId });
      if (!flowDef) ctx.throw.module(moduleInfo.relativeName, 1001, flowDefId);
      if (flowDef.atomDisabled === 1) ctx.throw.module(moduleInfo.relativeName, 1002, flowDef.atomStaticKey);
      return await this._start({ flowDef, flowAtomId, flowVars, flowUserId, startEventId });
    }

    evaluateExpression({ expression, globals }) {
      return vm.runInContext(expression, vm.createContext(globals || {}));
    }
```

- 截图：

<img width="1206" alt="theme-light" src="https://user-images.githubusercontent.com/24246985/112776994-9a578d80-9073-11eb-8cdc-4d4645e5fe69.png">

<img width="1209" alt="theme-dark" src="https://user-images.githubusercontent.com/24246985/112777049-bfe49700-9073-11eb-83b6-e11a897d0ab2.png">

<img width="1208" alt="theme-hyacinth" src="https://user-images.githubusercontent.com/24246985/112777060-c96dff00-9073-11eb-84c0-10210a77d681.png">

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
