### ISSUE TITLE
项目自荐 | 高性能轻量级的captive portal项目apfree-wifidog

### ISSUE THREAD

**Issue by liudf0716** [521xueweihan/HelloGitHub#1688]
## 项目推荐
- 项目地址：https://github.com/liudf0716/apfree_wifidog

- 类别：c

- 项目后续更新计划：

1. 根据用户反馈修复相应bug
2. 扩展wifidog协议，提升协议效率，减轻wifidog协议带给服务器端的压力

- 项目描述：
  apfree-wifidog是高性能轻量级的captive portal项目，其主要用于基于openwrt的无线路由器上，也有少数项目运行在大型x86设备上，结合服务器端通过wifidog协议给用户提供认证上网的服务，其主要用于商业公共场所为商家提供各种商业营销手段。

- 推荐理由：
  apfree-wifidog可能是目前国内应用最为广泛的商业wifi固件端解决方案；相比原有的开源wifidog解决方案，apfree-wifidog提供了更稳定的功能、性能更加优越、功能更加完善，其为首个支持https captive portal功能的开源项目，具体内容可参考apfree-wifidog开源项目里的具体描述。

- 示例代码：（可选）长度：1-20 行

- 截图：

<img src="https://raw.githubusercontent.com/wificoin-project/wwas/master/portal.jpg" width="365" height="619"/>

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
