### ISSUE TITLE
项目推荐 swift项目 iOS抓包工具

### ISSUE THREAD

**Issue by Lojii** [521xueweihan/HelloGitHub#1689]
## 项目推荐
- 项目地址：https://github.com/Lojii/Knot

- 类别：Swift

- 项目描述：
  - 一款iOS端抓包工具（没有其他的科学转发功能，单纯的抓包工具），包含所有完整代码(Network+UI)，使用MITM(中间人攻击)技术，用swift编写，目前实现了http(s)解析，可扩展其他任何协议，核心代码使用SwiftNIO实现
  - 可选：适用于什么场景、能够让初学者学到什么
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：手机端抓包，网络分析

- 截图：
 ![截图](https://s2.ax1x.com/2020/02/11/1ovHtf.png) | ![截图](https://s2.ax1x.com/2020/02/11/1ovo7t.png) | ![截图](https://s2.ax1x.com/2020/02/11/1ovW1e.png) 
![截图](https://s2.ax1x.com/2020/02/11/1ov7AP.png) | ![截图](https://s2.ax1x.com/2020/02/11/1ov5nA.png) | ![截图](https://s2.ax1x.com/2020/02/11/1ovbh8.png)
![截图](https://s2.ax1x.com/2020/02/11/1ovL9S.png) | ![截图](https://s2.ax1x.com/2020/02/11/1ovO1g.png) | ![截图](https://s2.ax1x.com/2020/02/11/1ovXcQ.png)
![截图](https://s2.ax1x.com/2020/02/11/1ovxns.png) | ![截图](https://s2.ax1x.com/2020/02/11/1oxS7q.png) | ![截图](https://s2.ax1x.com/2020/02/11/1ox9A0.png)
![截图](https://s2.ax1x.com/2020/02/11/1oxCNV.png) | ![截图](https://s2.ax1x.com/2020/02/11/1oxPhT.png) |

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 61 期](https://hellogithub.com/periodical/volume/61/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
