### ISSUE TITLE
CC:简单但功能强大的android组件化框架

### ISSUE THREAD

**Issue by luckybilly** [521xueweihan/HelloGitHub#169]
## 项目推荐
- 项目名称：CC

- 项目地址：https://github.com/luckybilly/CC

- 项目语言：Java(Android)

- 项目描述：简单但功能强大的android组件化框架

- 推荐理由：

使用简单，功能丰富，适用于几乎所有的组件化开发需求，可进行组件层面的AOP编程

功能列表：

        1. 支持组件间相互调用（不只是Activity跳转，支持任意指令的调用/回调）
        2. 支持组件调用与Activity、Fragment的生命周期关联
        3. 支持app间跨进程的组件调用(组件开发/调试时可单独作为app运行)
        4. 支持app间调用的开关及权限设置（满足不同级别的安全需求，默认打开状态且不需要权限）
        5. 支持同步/异步方式调用
        6. 支持同步/异步方式实现组件
        7. 调用方式不受实现方式的限制（例如:可以同步调用另一个组件的异步实现功能。注：不要在主线程同步调用耗时操作）
        8. 支持添加自定义拦截器（按添加的先后顺序执行）
        9. 支持超时设置
        10. 支持手动取消
        11. 编译时自动注册组件(IComponent)，无需手动维护组件注册表(使用ASM修改字节码的方式实现)
        12. 支持动态注册/反注册组件(IDynamicComponent)
        13. 支持组件间传递Fragment、自定义View等（组件在同一个app内时支持、跨app传递非基础类型的对象暂不支持）
            13.1 不仅仅是获取Fragment、自定义View的对象，并支持后续的通信。
        14. 尽可能的解决了使用姿势不正确导致的crash，降低产品线上crash率： 
            14.1 组件调用处、回调处、组件实现处的crash全部在框架内部catch住
            14.2 同步返回或异步回调的CCResult对象一定不为null，避免空指针

传送门：

[CC框架使用文档](https://github.com/luckybilly/CC/blob/master/README-zh-CN.md)

[CC框架技术原理](https://juejin.im/post/5a2b92e4f265da430d57f047)

[CC框架实践(1)：实现登录成功再进入目标界面功能](https://juejin.im/post/5a30d5f151882534af25f1c2)

[CC框架实践(2)：Fragment和View的组件化](https://juejin.im/post/5a3e48f26fb9a045132ae7ff)

[CC框架实践(3): 让jsBridge更优雅](https://juejin.im/post/5a3fa7fe6fb9a045204c702f)

- 示例代码：

```java
//同步调用，直接返回结果
CCResult result = CC.obtainBuilder("ComponentName").build().call();
//异步调用，不需要回调结果
String callId = CC.obtainBuilder("ComponentName").build().callAsync();
//异步调用，在子线程执行回调
String callId = CC.obtainBuilder("ComponentName").build().callAsync(new IComponentCallback(){
        @Override
        public void onResult(CC cc, CCResult result) {
            showResult(cc, result);
        }
    };
//异步调用，在主线程执行回调
String callId = CC.obtainBuilder("ComponentName").build().callAsyncCallbackOnMainThread(new IComponentCallback(){
        @Override
        public void onResult(CC cc, CCResult result) {
            showResult(cc, result);
        }
    };
//参数传递
String callId = CC.obtainBuilder("ComponentName")
               .addParam("name", "billy")
               .addParam("id", 12345)
               .setTimeout(5000) //5秒后超时
               .build()
               .callAsync();
//取消任务
cc.cancel(); //取消此CC对象的调用
CC.cancel(callId); //根据callId调用静态方法取消对应的CC调用

//获取fragment对象
Fragment fragment = CC.obtainBuilder("ComponentName").build().call().getDataItem("key");
//生命周期关联(Activity/Fragment onDestroy时自动执行cancel)
CC.obtainBuilder("ComponentName").cancelOnDestroyWith(activity).build().callAsync();
CC.obtainBuilder("ComponentName").cancelOnDestroyWith(fragment).build().callAsync();
```
- 截图：

![image](https://raw.githubusercontent.com/luckybilly/CC/master/image/CC.gif)

**Comment by 521xueweihan** [comment]
@luckybilly    您推荐的项目，已成功收录在 [HelloGitHub 第 23 期](https://hellogithub.com/volume/23/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，欢迎 Star ⭐️ 本项目，以便让更多人看到。
