### ISSUE TITLE
项目推荐- FaceBook高性能高压缩比例压缩算法

### ISSUE THREAD

**Issue by tianwailaike61** [521xueweihan/HelloGitHub#1692]
## 项目推荐
- 项目地址：https://github.com/facebook/zstd

- 类别：C

- 项目后续更新计划：不清楚

- 项目描述：
 1、全平台压缩算法，并且已经内置进入Linux。
 2、支持训练字典，并根据字典进行压缩。

- 推荐理由：
 1、高压缩率高性能
 2、流式压缩，降低CPU峰值

- 示例代码：
```
static void compress_orDie(const char* fname, const char* oname)
{
    size_t fSize;
    void* const fBuff = mallocAndLoadFile_orDie(fname, &fSize);
    size_t const cBuffSize = ZSTD_compressBound(fSize);
    void* const cBuff = malloc_orDie(cBuffSize);

    /* Compress.
     * If you are doing many compressions, you may want to reuse the context.
     * See the multiple_simple_compression.c example.
     */
    size_t const cSize = ZSTD_compress(cBuff, cBuffSize, fBuff, fSize, 1);
    CHECK_ZSTD(cSize);

    saveFile_orDie(oname, cBuff, cSize);

    /* success */
    printf("%25s : %6u -> %7u - %s \n", fname, (unsigned)fSize, (unsigned)cSize, oname);

    free(fBuff);
    free(cBuff);
}
```

- 截图：
![image](https://engineering.fb.com/wp-content/uploads/2016/08/GKlK2ADEDDFOVM8DAAOq-EYAAAAAbj0JAAAB.jpg)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 61 期](https://hellogithub.com/periodical/volume/61/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
