### ISSUE TITLE
自荐项目 - 基于 Vue、JSON Schema的动态表单

### ISSUE THREAD

**Issue by lljj-x** [521xueweihan/HelloGitHub#1693]
## 项目推荐
- 项目地址：https://github.com/lljj-x/vue-json-schema-form

- 类别：JS

- 项目后续更新计划：
提供更多业务类型组件，形成业务类组件库

- 项目描述：
基于Vue/Vue3，Json Schema 和 ElementUi/antd/iview3 等生成 HTML Form 表单，用于活动编辑器、CMS数据配置等场景，遵循JSON Schema 规范可以很方便的做到跨端校验；支持自定义任意节点组件和ui配置，以及完善的表单验证。

- 推荐理由：基于Vue且能够支持JSON Schema大部分配置的库基本没有，此外能够同时支持vue2、vue3，多ui框架以及快速接入现有的组件库。

- 截图：
![68747470733a2f2f6c6c6a6a2d787878782e6f73732d636e2d686f6e676b6f6e672e616c6979756e63732e636f6d2f7675652d6a736f6e2d736368656d612d666f726d2e676966](https://user-images.githubusercontent.com/6283929/113666133-57379300-96e1-11eb-8e9e-935e67bb4266.gif)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
