### ISSUE TITLE
项目自荐 | Chanify简单的消息推送工具

### ISSUE THREAD

**Issue by wizjin** [521xueweihan/HelloGitHub#1695]
## 项目推荐
- 项目地址：https://github.com/chanify/chanify

- 类别：Go

- 项目后续更新计划：添加文件消息推送等多种通知类型

- 项目描述：
这个项目可以用来给自己的iPhone推送消息APP的服务端，按去中性化的模式设计的系统，解决了用户对于隐私安全的顾虑。支持文本、图片、链接等多种消息类型，可以使用Docker部署自建服务器，利用公私钥生成用户账号，数据通过AES-GCM加密传输。

- 推荐理由：本项目功能简单，有完整的单元测试和较高的代码覆盖率，使用Github的action来进行版本发布，Docker自动打包上传，对初学者有一定的借鉴价值。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 61 期](https://hellogithub.com/periodical/volume/61/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
