### ISSUE TITLE
Legado 一款可以自定义来源阅读网络内容的工具

### ISSUE THREAD

**Issue by SekiBetu** [521xueweihan/HelloGitHub#1697]
## 项目推荐
- 项目地址：https://github.com/gedoor/legado

- 类别：Kotlin

- 项目后续更新计划：不清楚

- 项目描述：Legado(阅读3.0)是一款可以自定义来源阅读网络内容的工具，为广大网络文学爱好者提供一种方便、快捷舒适的试读体验。

- 推荐理由：与以往的一些书籍阅读器不同，这款阅读器提供了一个「平台」，可以自定义书源，而不依靠软件中自带的书源，同时开发较活跃，功能也比较齐全，值得一试

- 截图：
![image](https://user-images.githubusercontent.com/38283893/113707614-be217000-9712-11eb-98ba-b53dad6c0f5d.png)
![image](https://user-images.githubusercontent.com/38283893/113707628-c37eba80-9712-11eb-949d-d94b4e8c7955.png)
![image](https://user-images.githubusercontent.com/38283893/113707641-c7aad800-9712-11eb-9173-2df9cc8603ef.png)
![image](https://user-images.githubusercontent.com/38283893/113707650-caa5c880-9712-11eb-85d5-a21b74aab81d.png)
![image](https://user-images.githubusercontent.com/38283893/113707655-cd082280-9712-11eb-8d86-211669f69f36.png)
![image](https://user-images.githubusercontent.com/38283893/113707663-d0031300-9712-11eb-9173-db78ee5f3a95.png)

**Comment by 521xueweihan** [comment]
https://hellogithub.com/periodical/search/?q=https://github.com/gedoor/MyBookshelf

我们推荐过 Java 版本了，这个项目就不再推荐了
