### ISSUE TITLE
Vue可视化表单设计器组件

### ISSUE THREAD

**Issue by xaboy** [521xueweihan/HelloGitHub#1698]
## 项目推荐

- 项目地址：https://github.com/xaboy/form-create-designer

- 类别：JS

- 项目后续更新计划：
    功能完善优化
    丰富表单组件

- 项目描述：form-create-designer 是基于 Vue 和 ElementUI 实现的可视化表单设计器组件。可以通过拖拽的方式快速创建表单，提高开发者对表单的开发效率，节省开发者的时间。

- 推荐理由：帮开发者节省在表单的耗费的时间，有更多时间专注于业务功能开发。

- 截图：

![demo1](http://form-create.com/img/designer-review.png)

![designer-demo2](https://user-images.githubusercontent.com/21242408/113984095-4b80d380-987d-11eb-9ea3-19de715a73e8.gif)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
