### ISSUE TITLE
iOS项目推荐：IPAPatch——免越狱给iOS程序打补丁

### ISSUE THREAD

**Issue by CloudnuY** [521xueweihan/HelloGitHub#17]
[Naituw/IPAPatch](https://github.com/Naituw/IPAPatch)

![IPAPatch](https://camo.githubusercontent.com/056caee2fa3016443320c1ff73306ff04ff7aadb/687474703a2f2f7778312e73696e61696d672e636e2f6c617267652f62656265646262356c79316664726767307631686a6a323065323035716467692e6a7067)

## 包含一个Xcode工程，提供以下Features

* **向第三方ipa文件注入代码**
* **使用lldb单步调试**
* **链接外部Framework，如Reveal**

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目 🙏。

如您推荐的项目在《HelloGithub》月刊中推荐，则会注明推荐人。**同时在此 issues 中通知您**。

再次感谢您对《HelloGithub》项目的支持！💪

**Comment by 521xueweihan** [comment]
不好意思，请重新[创建 issues](https://github.com/521xueweihan/HelloGitHub/issues/new)，根据推荐项目的模版，规范推荐项目格式、完善信息。
