### ISSUE TITLE
drawio 一款简洁强大的绘图工具

### ISSUE THREAD

**Issue by SekiBetu** [521xueweihan/HelloGitHub#1700]
## 项目推荐
- 项目地址：https://github.com/jgraph/drawio

- 类别：JS

- 项目后续更新计划：不清楚

- 项目描述：一款简洁强大的绘图工具，可以创建流程图、序列图、网络拓扑图、甘特图、思维导图、模型图、文氏图等，也能导出各类图片格式(比如 png、jpg、svg)和PDF，同时也能导出HTML格式和VSDX格式(Microsoft Visio 图形格式)

- 推荐理由：免费开源，功能上直逼Microsoft Visio，并且仅仅依靠网页端即可运行，可Fork原仓库后直接部署为github pages，同时也有基于electron的桌面版和vscode的插件版

- 截图：

![image](https://user-images.githubusercontent.com/38283893/114064353-2071a080-98cc-11eb-813f-53eee98a2ed8.png)
![image](https://user-images.githubusercontent.com/38283893/114064754-84946480-98cc-11eb-90cc-47aabf9e562a.png)
![image](https://user-images.githubusercontent.com/38283893/114065118-e523a180-98cc-11eb-8546-2db20da83edc.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 61 期](https://hellogithub.com/periodical/volume/61/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
