### ISSUE TITLE
【自荐开源项目】corpwechat-bot：快速高效的企业微信消息推送接口

### ISSUE THREAD

**Issue by GentleCP** [521xueweihan/HelloGitHub#1701]
## 项目推荐
- 项目地址：https://github.com/GentleCP/corpwechat-bot

- 类别：python

- 项目后续更新计划：
目前已更新至版本`v0.2.0`，已更新和待更新的内容：

- [x] `docs`：readme和usage更新
- [x] `fix`：token存储位置修改，初始设置保存到本地`site-packages`（后期将其移到`site-packages/corpwechatbot`目录下，方便统一）
- [ ] `feat`：更智能的调用接口（如所有发送用同一接口`send`，根据传入参数的不同自动选择）
- [x] `feat`：终端快捷使用，一行命令式消息发送，现支持`cwb -t='hello world'` 直接在终端发送消息
- [ ] `refactor`：核心代码优化与重构
- [x] `docs` : 添加`QuickStart` 
- [ ] `feat`：添加对应用消息发送到企业微信群聊的支持
- [ ] `feat`：添加应用消息任务卡片消息推送的功能（小程序消息暂不考虑）
- [x] `feat`：允许将企业微信配置信息存储到本地文件读取

- 项目描述：
  - 必写：`corpwechat-bot`是一个python封装的企业机器人&应用消息推送库，通过企业微信提供的api实现。利用本库，你可以轻松地实现从服务器端发送一条文本、图片、视频、markdown等等消息到你的微信手机端，而不依赖于其他的第三方应用，如`ServerChan` 
  - 可选：本项目适合应用到所有需要接收服务器推送消息到手机的场景，并且是基于企业微信，因此开发者无需安装其他app，可直接在微信中收到相应的推送消息，或将消息推送给自己企业微信中的其他人。

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？
以往在服务器端程序运行结束后要通知本人，通常的解决方案是`ServerChan`(需安装公众号，且21年4月底下线)，或者`bark`，或者邮件，但个人最常用的还是微信消息，通过该项目，可以轻松实现服务器端到微信的消息推送，并包含许多特性。
- 示例代码：（可选）长度：1-20 行
```python
# 发送应用消息
from corpwechatbot.app import AppMsgSender

app = AppMsgSender(corpid='',  # 你的企业id
                   corpsecret='',  # 你的应用凭证密钥
                   agentid='')   # 你的应用id
app.send_text(content="如果我是DJ，你会爱我吗？")

# 发送群聊机器人消息
from corpwechatbot.chatbot import CorpWechatBot

bot = CorpWechatBot(key='')  # 你的机器人key，通过群聊添加机器人获取

bot.send_text(content='Hello World')
```
```python
# 终端一条命令式发送消息
$ cwb -t='hello world'
```
- 截图：（可选）gif/png/jpg
    - 应用消息
![image](https://user-images.githubusercontent.com/38175267/114138672-8d268280-9940-11eb-9cbe-2f41d7a11045.png)
    - 群聊机器人消息
![image](https://user-images.githubusercontent.com/38175267/115169427-8f32d300-a0f0-11eb-80c5-9336334400e6.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
