### ISSUE TITLE
自荐开源项目：sureness - 面向restful api的高性能认证鉴权框架

### ISSUE THREAD

**Issue by tomsun28** [521xueweihan/HelloGitHub#1702]
## 项目推荐
- 项目地址：https://github.com/usthe/sureness

- 类别：java

- 项目后续更新计划：支持LDAP认证

- 项目描述：
  - sureness是一个开箱即用的高效认证鉴权框架，基于 rbac主要关注于对 restful api 的安全保护，无特定框架依赖(已有springboot,quarkus,javalin,ktor等demo)，支持动态修改权限配置，支持主流http容器 servlet 和 jax-rs，支持多种认证策略, jwt, basic auth,digest auth ... 可扩展自定义支持的认证方式，基于改进的字典匹配树拥有的高性能，提高良好的扩展接口，demo和文档。sureness的低配置，易扩展，不耦合其他框架，能使开发者对自己的项目多场景快速安全的进行保护。

- 推荐理由：无web框架依赖，使用优化的匹配树拥有高性能，基准性能测试比shiro spring security快几倍。目前已经历几家公司生产环境考验。

- 示例代码：

````
<dependency>
    <groupId>com.usthe.sureness</groupId>
    <artifactId>sureness-core</artifactId>
    <version>1.0.2</version>
</dependency>
````

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
