### ISSUE TITLE
kodbox 一款强大易用的私有云网盘程序

### ISSUE THREAD

**Issue by kalcaddle** [521xueweihan/HelloGitHub#1704]
## 项目推荐
- 项目地址：https://github.com/kalcaddle/kodbox
   >  项目前身:   https://github.com/kalcaddle/KodExplorer   kodbox为kodexplorer全面重构产品,更强大易用.

- 类别：PHP
- 项目后续更新计划：全文搜索,支持office,pdf等文件内容搜索;  二级回收站等.

- 项目描述：
  - 轻松自建私有云网盘, 自己的数据自己掌控!
  - 可用于个人,也可以公司及团队使用. 支持组织架构, 完善的权限体系.
  - 特色: 高效，流畅,云端存储&协同办公新体验. 如Windows体验的私有云盘/企业网盘,完全支持私有化部署，存储安全可控
数百种文件格式在线预览、编辑和播放;轻松分享，高效协作，细粒度权限管控.

- 推荐理由：界面及用户体验很强大;  全平台客户端及APP，随时随地访问;同时支持webdav挂载,轻松打通多个应用
- 示例代码(快速安装)：
  ```
  git clone https://github.com/kalcaddle/kodbox.git
  chmod -Rf 777 ./kodbox/*
  ```
- 使用截图：
![](https://raw.githubusercontent.com/kalcaddle/static/master/images/kod/common2.png)
![](https://raw.githubusercontent.com/kalcaddle/static/master/images/kod/common3.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
