### ISSUE TITLE
vscode-qq

### ISSUE THREAD

**Issue by takayama-lily** [521xueweihan/HelloGitHub#1706]
## 项目推荐
- 项目地址：https://github.com/takayama-lily/vscode-qq

- 类别：TS/JS

- 项目后续更新计划：

> 根据需求添加功能
> 完善UI界面

- 项目描述：

> 以vscode编辑器插件的形式嵌入了轻量级QQ聊天客户端  
> 工作聊天两不误

- 推荐理由：

> 之前看到有网易云等各种奇奇怪怪的vscode插件，正好手头有QQ协议于是突发奇想制作了这个。

**Comment by 521xueweihan** [comment]
要不要给我们投稿一篇文章，正好我们在做 HelloVSCode 系列？

我的微信：xueweihan
