### ISSUE TITLE
[wp2vite]一个让webpack项目支持vite的命令行工具

### ISSUE THREAD

**Issue by dravenww** [521xueweihan/HelloGitHub#1708]
## 项目推荐
- 项目地址：https://github.com/tnfe/wp2vite

- 类别：JS

- 项目后续更新计划：

- 项目描述：
  - 必写：一个前端项目转换工具，可以让webpack项目支持vite
  - 可选：适用于webpack项目，能够快速体验vite带来的红利
  - 描述长度（不包含示例代码）: 
    - wp2vite 不会删除你的项目的webpack的配置文件，但是会在你的项目中插入vite的配置文件；
    - 相较于webpack，vite开发环境构建速度可以提升80%左右，构建生产环境能够提升50%左右

- 推荐理由：解决掉对vite不熟悉的开发者可以一键让webpack项目支持vite，更快的开发项目。

- 示例代码：（可选）长度：
 ```
  cd yourwork/your_project // go to your project catalog
  wp2vite 
  or 
  wp2vite init
  
  npm install // install dependencies
  
  npm run dev // start server
  or
  npm run vite-start // start server
 ```

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
