### ISSUE TITLE
【项目自荐】NPlayer 可定制的弹幕视频播放器

### ISSUE THREAD

**Issue by woopen** [521xueweihan/HelloGitHub#1711]
## 项目推荐
- 项目地址：[https://github.com/woopen/nplayer](https://github.com/woopen/nplayer)

- 类别：JS

- 项目后续更新计划：
  - 移动端兼容模式
  - 支持解析任何格式的字幕插件
  - 支持 360 度全景视频
  - 增加 ffmpeg，让 web 播放器也具备本地播放器功能

- 项目描述：NPlayer 是由 Typescript 加 Sass 编写，无任何第三方运行时依赖，兼容 IE11，支持 SSR。该播放器高度可定制，提供了 内置组件 方便二次开发。并且有用插件系统，其 弹幕功能 就是使用插件形式提供。该播放器可以接入任何 流媒体，如 hls、dash 和 flv 等。在线体验 & 官网 [https://nplayer.js.org](https://nplayer.js.org)。

- 推荐理由：
  - 播放器所有图标、主题色、加载元素等都可以被修改。拥有内置组件方便二次开发。
  - 非常轻松就可以配置的控制条、右键菜单和设置菜单。
  - 和 B 站一样体验的弹幕系统，支持非常多的配置项且大量弹幕不会卡顿。

- 示例代码：

```js
import Player from 'nplayer'
import Danmaku from '@nplayer/danmaku'

const player = new Player({
  plugins: [new Danmaku({ // 弹幕配置 })],
  contextMenus: ['loop', 'pip', { html: '我的右键菜单', click() { console.log('被点击了') } }],
  videoAttrs: { src: 'video.mp4' }
})

console.log(player.danmaku)
player.mount(document.body)
```

- 截图：
![image](https://user-images.githubusercontent.com/25923128/115490091-fa66db80-a28f-11eb-86a9-5c6a0a517a20.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
