### ISSUE TITLE
项目推荐｜Swift项目-awesome-ios

### ISSUE THREAD

**Issue by liumenghua** [521xueweihan/HelloGitHub#1714]
## 项目推荐
- 项目地址：https://github.com/vsouza/awesome-ios

- 类别：Swift

- 项目后续更新计划：37k+ star，iOS/Swift业界使用广泛，持续维护中

- 项目描述：一个iOS开源项目的集合，包含Objc和Swift项目，非常全面

- 推荐理由：在这里可以找到iOS开发中所有类型的项目，网络、UI、Json、数据库、音视频... 初学者查找开源项目学习的好地方

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 61 期](https://hellogithub.com/periodical/volume/61/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
