### ISSUE TITLE
AlbumCameraRecorder

### ISSUE THREAD

**Issue by zhongjhATC** [521xueweihan/HelloGitHub#1717]
## 项目推荐
- 项目地址：https://github.com/zhongjhATC/AlbumCameraRecorder

- 类别：Java

- 项目后续更新计划：实时更新兼容最新Android版本，完善相册、视频、图片各种编辑，分开多库灵活搭配

- 项目描述：
  - 必写：这是集合相册、视频、图片三合一的库，目的是让开发者无需自定义多媒体操作，方便使用
  - 可选：能够让初学者了解并学习相册、视频、图片等多媒体操作，代码按照阿里规范而写
  - 描述: 
  - 支持自定义样式.支持更换里面的相关按钮.
  - 支持相册、录制、录音等三合一功能（类似抖音等），并且也可以通过配置只独立出其中一个功能.
  - 虽然功能很多，但是可以按照所需功能来引入某些库
  - 丰富的回调接口和调试信息,可利用现有API实现丰富的效果.
  - 兼容性强，不管是低版本的4.1还是目前最新版本的Android 11,都进行了相关兼容处理
  - 支持所有图片读取处理自定义，例如可自定义glide、Fresco等等都可以
  - 支持从相册选择图片
  - 支持相册按照手机文件区分不同的文件夹选择
  - 自定义性强，支持各种自定义最多选多少张图片、视频等等，也支持只显示自定义文件大小
  - 支持自定义相册的样式，颜色，大小等等
  - 录制拍照时支持闪光灯、前后摄像头切换
  - 录制拍照时支持双指触摸放大缩小，支持单指上下滑动控制亮度
  - 录制拍照长按按钮等所有UI可自定义，全是svg图片可以很好的处理动画细节
  - 录制支持分段录制，以后还会加入视频编辑
  - 图片编辑支持颜色涂鸦、输入文字、马赛克处理、旋转、裁剪等处理
  - 支持录音处理
  - 所有录制拍照都经过了压缩处理
  - 1.0.19X以后的版本兼容Android Q版本,如果打算保留自己项目sdk28的，可以只保留1.0.18X

- 推荐理由：三合一多媒体操作，也可支持只使用某库，实时更新

- 示例代码：

    // 拍摄有关设置
    CameraSetting cameraSetting = new CameraSetting();
    cameraSetting.mimeTypeSet(MimeType.ofAll());// 支持的类型：图片，视频

    // 相册
    AlbumSetting albumSetting = new AlbumSetting(true)
            .mimeTypeSet(MimeType.ofAll())// 支持的类型：图片，视频
            .countable(true)// 是否显示多选图片的数字
            .addFilter(new GifSizeFilter(320, 320, 5 * Filter.K * Filter.K))// 自定义过滤器
            .originalEnable(true)// 开启原图
            .maxOriginalSize(10); // 最大原图size,仅当originalEnable为true的时候才有效

    // 录音机
    RecorderSetting recorderSetting = new RecorderSetting();

    // 全局
    GlobalSetting globalSetting = MultiMediaSetting.from(MainSimpleActivity.this).choose(MimeType.ofAll());

    if (mBinding.cbAlbum.isChecked())
        // 开启相册功能
        globalSetting.albumSetting(albumSetting);
    if (mBinding.cbCamera.isChecked())
        // 开启拍摄功能
        globalSetting.cameraSetting(cameraSetting);
    if (mBinding.cbRecorder.isChecked())
        // 开启录音功能
        globalSetting.recorderSetting(recorderSetting);

    globalSetting
            .setOnMainListener(errorMessage -> Toast.makeText(MainSimpleActivity.this.getApplicationContext(), "自定义失败信息：录音已经达到上限", Toast.LENGTH_LONG).show())
            .allStrategy(new SaveStrategy(true, "com.zhongjh.cameraapp.fileprovider", "AA/test"))// 设置路径和7.0保护路径等等
            .imageEngine(new Glide4Engine())    // for glide-V4
            .maxSelectablePerMediaType(5 - alreadyImageCount, 1 - alreadyVideoCount, 1 - alreadyAudioCount)// 最大10张图片或者最大1个视频
            .forResult(REQUEST_CODE_CHOOSE);

- 截图：
## 快照
![](https://github.com/zhongjhATC/AlbumCameraRecorder/blob/master/Demonstration.gif)
![](https://github.com/zhongjhATC/AlbumCameraRecorder/blob/master/DemonstrationShowImg.png)

## 市场上常用手机兼容测试
100%通过[兼容测试报告](https://github.com/zhongjhATC/AlbumCameraRecorder/blob/master/WeTest.md).
![](https://raw.githubusercontent.com/zhongjhATC/AlbumCameraRecorder/master/wetest/5.jpg)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
