### ISSUE TITLE
add rosedb

### ISSUE THREAD

**Issue by roseduan** [521xueweihan/HelloGitHub#1718]
## 项目推荐
- 项目地址：https://github.com/roseduan/rosedb

- 类别：Go

- 项目后续更新计划：
  目前项目中的 TODO，后续可能会适当性的调整：
   1、支持事务，ACID 特性
   2、文件数据压缩存储（snappy、zstd、zlib）
   3、缓存淘汰策略（LRU、LFU、Random）
   4、支持更多的命令操作（type，keys，mset，mget，zcount，etc...）
   5、完善相关文档

- 项目描述：

    rosedb 是一个简单、内嵌的 k-v 数据库，使用 Golang 实现，支持多种数据结构，包含 String、List、Hash、Set、Sorted Set， 
   接口名称风格和 Redis 类似。

    这个项目也是学习并巩固 Go 相关知识的不错的素材，通过实践这个项目，至少可以学到：
        1、Golang 大多数基础语法，以及一些高级特性比如 goroutine、chan、mutex
        2、数据结构及算法相关知识，链表，哈希表，跳表等
        3、操作系统的一些知识，特别是对文件系统，内存映射相关

- 推荐理由：新手友好，代码简洁，注释清晰，项目已经在 awesome-go 以及 awesome-go-cn 等知名项目中被收录，学习 Go 语言的绝佳项目。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 62 期](https://hellogithub.com/periodical/volume/62/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
