### ISSUE TITLE
一个 Go 语言的 TAB 缩进替换成 Space 缩进的小工具

### ISSUE THREAD

**Issue by bingxio** [521xueweihan/HelloGitHub#1719]
## 项目自荐
- 项目地址：https://github.com/bingxio/gft

- 类别：Go

- 项目描述：
1. 20 kb 的小工具
2. 100 行的 C++ 代码编写
3. 支持自定义缩进大小
4. 支持指定单个 .go 文件或文件夹

- 推荐理由：
编写代码时，使用官方好用的格式化工具，但都是 TAB 缩进。提交代码时，使用 gft 一键格式化，使 GitHub，CodeReview 代码观感更好。

- 示例代码：（可选）长度：1-20 行
```go
// Before
func foo() {
        for i := 0; i < 100; i++ {
                println(i)
        }
}
// After
func foo() {
    for i := 0; i < 100; i++ {
        println(i)
    }
}

```

- 截图：（可选）gif/png/jpg

**Comment by appleboy** [comment]
Go 標準用的是 tab

**Comment by bingxio** [comment]
> Go 標準用的是 tab

**Comment by bingxio** [comment]
> Go 標準用的是 tab

**Comment by bingxio** [comment]
> Go 標準用的是 tab

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
