### ISSUE TITLE
你好，我正在完成我的学期CMS项目,我想将你的HelloGithub项目的编程语言月报链接放到我的CMS项目的轮播图中，可以吗？

### ISSUE THREAD

**Issue by Dev-Breezer** [521xueweihan/HelloGitHub#1721]
你好，我正在完成我的博客，我想将你的HelloGithub项目的编程语言月报链接放到我的博客中，可以吗？

**Comment by 521xueweihan** [comment]
@Dev-Breezer 可以，搞起！

完成后如果是上线的话，把上线后的地址发到本 issues 我给你留着，展示你的成果～

**Comment by Dev-Breezer** [comment]
好的😊谢谢你



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月29日(周四) 下午4:38
收件人: ***@***.***&gt;;
抄送: "The ***@***.******@***.***&gt;;
主题: Re: [521xueweihan/HelloGitHub] 你好，我正在完成我的学期CMS项目,我想将你的HelloGithub项目的编程语言月报链接放到我的CMS项目的轮播图中，可以吗？ (#1721)




 
@Dev-Breezer 可以，搞起！
 
完成后如果是上线的话，把上线后的地址发到本 issues 我给你留着，展示你的成果～

**Comment by 2926295173** [comment]
我想专门在我的博客写一篇文章介绍您的项目，不知道是否可行

**Comment by Dev-Breezer** [comment]
可以的，不过我的项目过于简陋，前端使用了layui，后端使用了mysql+php,没有依靠任何的框架，是一个很简单的项目，我担心会耽误您的时间,消耗您的精力










------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月29日(星期四) 下午5:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [521xueweihan/HelloGitHub] 你好，我正在完成我的学期CMS项目,我想将你的HelloGithub项目的编程语言月报链接放到我的CMS项目的轮播图中，可以吗？ (#1721)



我想专门在我的博客写一篇文章介绍您的项目，不知道是否可行

**Comment by 521xueweihan** [comment]
@2926295173 搞

**Comment by Dev-Breezer** [comment]
让哪位朋友介绍吗？😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月29日(周四) 下午5:39
收件人: ***@***.***&gt;;
抄送: "The ***@***.******@***.***&gt;;
主题: Re: [521xueweihan/HelloGitHub] 你好，我正在完成我的学期CMS项目,我想将你的HelloGithub项目的编程语言月报链接放到我的CMS项目的轮播图中，可以吗？ (#1721)




 
@2926295173 搞

**Comment by Dev-Breezer** [comment]
不知道您是否有收到我的回复，如果可以，我将会在之后使用python+django重构我们CMS项目，那时，我将会主动联系您介绍我的项目，这样既可以提升您博客的文章质量，也能将干货分享给别人。您看可以吗







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "521xueweihan/HelloGitHub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月29日(星期四) 下午5:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [521xueweihan/HelloGitHub] 你好，我正在完成我的学期CMS项目,我想将你的HelloGithub项目的编程语言月报链接放到我的CMS项目的轮播图中，可以吗？ (#1721)



 我想专门在我的博客写一篇文章介绍您的项目，不知道是否可行
