### ISSUE TITLE
自荐 react-native-easy-chat-ui

### ISSUE THREAD

**Issue by DaiYz** [521xueweihan/HelloGitHub#1723]
## 项目推荐
- 项目地址：
https://github.com/DaiYz/react-native-easy-chat-ui
- 类别：js

- 项目描述：
  - react-native的聊天UI组件，UI风格类似微信，可自定义。

- 推荐理由：
     - 简单易用
     - 高度自定义
     - 支持多种消息类型
     - 样式美观

- 示例代码：
  
 ```jsx
import { ChatScreen } from 'react-native-easy-chat-ui'
class Example extends React.Component {
  state = {
     messages: []
     inverted: false,  // require   
  }

  sendMessage = (type, content, isInverted) => {
      console.log(type, content, isInverted, 'msg')
    }

  render() {
    return (
      <ChatScreen
        ref={(e) => this.chat = e}
        messageList={this.state.messages}
        androidHeaderHeight={androidHeaderHeight}
        sendMessage={this.sendMessage}
      />
    )
  }
}
```

- 截图：

<p>
<img alt="react-native-easy-chat-ui" src="https://raw.githubusercontent.com/DaiYz/react-native-easy-chat-ui/master/screenshots/1.png" width="207" height="448" />
<img alt="react-native-easy-chat-ui" src="https://raw.githubusercontent.com/DaiYz/react-native-easy-chat-ui/master/screenshots/2.png" width="207" height="448" />
<img alt="react-native-easy-chat-ui" src="https://raw.githubusercontent.com/DaiYz/react-native-easy-chat-ui/master/screenshots/3.png" width="207" height="448" />
<img alt="react-native-easy-chat-ui" src="https://raw.githubusercontent.com/DaiYz/react-native-easy-chat-ui/master/screenshots/4.png" width="207" height="448" />
<img alt="react-native-easy-chat-ui" src="https://raw.githubusercontent.com/DaiYz/react-native-easy-chat-ui/master/screenshots/5.png" width="207" height="448" />
<img alt="react-native-easy-chat-ui" src="https://raw.githubusercontent.com/DaiYz/react-native-easy-chat-ui/master/screenshots/6.png" width="207" height="448" /></p>

**Comment by 521xueweihan** [comment]
您好，已推荐过类似的项目。所以您的项目暂不收录到月刊中。
