### ISSUE TITLE
Vulhub，一个面向大众的开源漏洞环境集合

### ISSUE THREAD

**Issue by phith0n** [521xueweihan/HelloGitHub#1724]
## 项目推荐

- 项目地址：https://github.com/vulhub/vulhub
- 类别：其它
- 项目后续更新计划：持续更新
- 项目描述：Vulhub是一个面向大众的开源漏洞环境集合，无需docker知识，简单执行一条命令即可编译、运行一个完整且存在某个漏洞的应用。
- 推荐理由

对于大多数安全研究人员来说，为了复现与研究某一个漏洞，有以下一些痛点：

第一，本地复现漏洞，通常需要先运行起一套完整的软件环境。对于安全研究人员来说，他们可能并不熟悉某某语言的开发环境与流程，编译运行这个软件的过程会有大量学习成本。
第二，即使某个应用的搭建运行并不复杂，但通常只限于最新版本，而寻找漏洞影响的旧版本应用也会浪费大量时间。结果就是，时间越久的漏洞，学习成本越高。
第三，某个漏洞突然爆出时，企业安全运营人员需要快速得到检测与修复方法并进行验证，以前是没有这样完整的解决方案的
第四，在深入学习某个漏洞时，我们通常需要了解应用是怎么运行的，依赖了哪些服务与组件，这个过程比较冗杂

Vulhub中已经包含了180余个漏洞与其相应的环境，可以通过docker-compose命令一键启动与管理，不同漏洞时间跨度超过10年，解决了前两个痛点；同时，Vulhub由一线安全从业人员与社区维护，在漏洞爆发的第一时间能够快速上线对应的环境，且所有环境都有漏洞介绍和复现方法，帮助使用者快速学习了解漏洞，解决了第三个痛点；最后，如果你想深入学习某个漏洞，Vulhub所有漏洞环境均有对应的Dockerfile，环境编译、部署、运行，漏洞复现完全开源，可以让使用者快速完成对一个漏洞原理的学习，解决第四个痛点。

与DVWA等漏洞靶场的不同是：DVWA（等）是自己编写的一款存在漏洞的应用，是仅存在于测试环境的一个漏洞演示demo；Vulhub是一些历史上出现过的真实漏洞，我们运行了这个漏洞所对应的软件版本。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 62 期](https://hellogithub.com/periodical/volume/62/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
