### ISSUE TITLE
simplepy

### ISSUE THREAD

**Issue by cnzbpy** [521xueweihan/HelloGitHub#1725]
## 项目推荐
- 项目地址：https://github.com/cnzbpy/simplepy

- 类别：Python

- 项目描述：
  - 必写：这是一些简单的程序，能够加深初学者对Python的理解
  - 可选：例如基于Python-Vlc写个全能媒体播放器、爬取热榜、用爬虫的方式多个翻译、查当前ip等

- 推荐理由：部分人学完Python没有合适的地方练手，这可能是个好的方式

- 示例代码：
import requests
string=input('输入字符串：')
data={'doctype':'json','i':string}
resp=requests.post('http://fanyi.youdao.com/translate',data=data)
result=resp.json()['translateResult'][0][0]['tgt']
print(result)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
