### ISSUE TITLE
【项目自荐】Go 语言实现的 Redis 服务器

### ISSUE THREAD

**Issue by HDT3213** [521xueweihan/HelloGitHub#1727]
## 项目自荐

- 项目地址: https://github.com/HDT3213/godis

- 类别：Go

- 项目后续更新计划：
  
  - 支持单机/分布式事务
  - 支持使用 info 命令查看系统状态
  - 支持主从同步及哨兵机制
  - 添加一个类似 Disque 的分布式队列

- 项目描述：Godis 是一个用 Go 语言实现的 Redis 服务器。它完全兼容 Redis 通信协议并支持大多数常用命令，包括Redis的5种数据结构、TTL、发布订阅、地理位置以及 AOF 持久化等。Godis 支持对客户端透明的集群模式，只要连接上集群中任意一个节点就可以访问集群中所有数据。初学者可以通过此项目学习如何使用 Go 语言开发高性能的Web中间件。

- 截图：
![](https://i.loli.net/2021/05/02/q8uyglk7w9aIer4.png)

- 推荐理由：Godis 功能完善、代码简洁，且拥有[系列中文博客](https://www.cnblogs.com/Finley/category/1598973.html)详细介绍设计思路和实现要点，非常适合初学者参与和学习

**Comment by 521xueweihan** [comment]
@HDT3213 由于每期篇幅有限，所以这期暂时不收录您的项目了。

预计下期（63）可以收录，我看有系列的文章。如果有有兴趣连载到 HelloGitHub 公众号的话，可以加我微信：xueweihan 进行进一步的沟通。

**Comment by HDT3213** [comment]
非常感谢！最近对代码进行了较大规模的优化和重构，系列文章中有些内容已经过时。在文章更新后我再与您联系。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 63 期](https://hellogithub.com/periodical/volume/63/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
