### ISSUE TITLE
项目自荐: vscode-dependencyGraph

### ISSUE THREAD

**Issue by sz-p** [521xueweihan/HelloGitHub#1728]
## 项目推荐
- 项目地址：[vscode-dependencyGraph](https://github.com/sz-p/vscode-dependencyGraph)

- 类别：JS，工具，VsCode插件

- 项目描述：一个用来查看项目文件依赖关系的VsCode插件。

- 推荐理由：这款插件可以帮助开发者查看和分析js项目的`文件依赖`和`模块关系`。从模块的角度阐述项目架构，核心功能和耦合关系。

- 项目后续更新计划：最终视图形成类似于`visual studio class view`的分析页面,帮助开发者查看和分析`文件依赖`和`模块关系`。

![visual-studio-class-view](https://github.com/sz-p/vscode-dependencyGraph/raw/HEAD/doc/visual-studio-class-view.png)

- 截图：

![DependencyGraph-screenshot](https://github.com/sz-p/vscode-dependencyGraph/raw/HEAD/doc/dependencyGraph.gif)

**Comment by 521xueweihan** [comment]
建议推荐给 awsome vscode 项目，

由于每期收录的项目优先，我们的月刊暂不收录了哈
