### ISSUE TITLE
自荐：vscode-texinfo

### ISSUE THREAD

**Issue by CismonX** [521xueweihan/HelloGitHub#1729]
## 项目自荐

* 项目地址：https://github.com/texinfo-lang/vscode-texinfo

* 类别：JS

* 项目描述：vscode-texinfo 是 Visual Studio Code 的一款插件，为编辑器提供了 Texinfo 格式支持，包括语法高亮、代码补全、 HTML 预览等功能。方便用户在 VSCode 上编写、阅读 Texinfo 格式的技术文档。

* 项目后续更新计划：
  * 持续跟进 VSCode 版本，确保兼容性
  * 持续跟进用户反馈，修复bug，实现新功能
  * 开发 Texinfo 的 Language Server，借此解决该项目现有的局限性问题，进一步提升使用体验

* 推荐理由：
  * 能帮助更多人发现 Texinfo 这个优秀的排版语言，并用它编写技术文档
  * 能帮助新手入门 VSCode 插件开发
  * 相比于上次推荐被拒，这段时间项目的主要改进：
    * 进行了重构，提高了代码的可读性和可维护性
    * 优化了部分功能，实现了显著的性能提升
    * 精简依赖，打包后的程序体积减少了近 50%
    * 编写了完整的[用户手册](https://nongnu.org/vscode-texinfo/manual)

* 截图：
![Screenshot from 2021-05-05 21-21-39](https://user-images.githubusercontent.com/19173506/117344153-adae1200-aed7-11eb-8507-1cd45bcf0297.png)

**Comment by 521xueweihan** [comment]
建议推荐给 awesome vscode 项目，

由于每期收录的项目有限，我们的月刊暂不收录了哈
