### ISSUE TITLE
推荐使用 LSAnimator 实现 iOS 日常开发中的动画需求

### ISSUE THREAD

**Issue by Lision** [521xueweihan/HelloGitHub#173]
## 项目推荐
- 项目名称：
LSAnimator

- 项目地址：
https://github.com/Lision/LSAnimator

- 项目语言：
Swift 3.2-4.0, Objective-C

- 项目描述：
Easy to Read and Write Multi-chain Animations Kit in Objective-C and Swift.

- 推荐理由：
通过使用 LSAnimator（Objective-C）或者 CoreAnimator（Swift）可以用少量的代码实现复杂而又易于维护的动画。并且弥补了 JHChainableAnimations 的致命缺陷，详见 [LSAnimator](https://github.com/Lision/LSAnimator/blob/master/README_ZH-CN.md)。

- 示例代码：

``` obj-c
LSAnimator *animator = [LSAnimator animatorWithView:self.myView];
animator.moveX(100).spring.thenAfter(2).increWidth(30).easeIn.animate(2);
```

- 截图：

![](https://github.com/Lision/LSAnimator/blob/master/Rources/LSAnimatorDemo.gif)

**Comment by 521xueweihan** [comment]
@Lision 您推荐的项目，已成功收录在 [HelloGitHub 第 24 期](https://hellogithub.com/volume/24/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
