### ISSUE TITLE
Caiss：一套简单好用的ANN组件

### ISSUE THREAD

**Issue by ChunelFeng** [521xueweihan/HelloGitHub#1730]
## [自荐项目]
- 项目地址：https://github.com/ChunelFeng/caiss

- 类别：C++，Python，机器学习

- 项目后续更新计划：搜索流程图化，算法流程优化，提供高可用服务

- 项目描述：
Caiss是一个为了解决相似向量（ANN）问题而制作的算法SDK组件，内置了多种优化后的ANN算法，实现了模型自优化、实时增删改查等功能。可以同时进行 vec2vec 或者 label2label 级别的查询，同时也提供了并发、缓存机制。

- 推荐理由：
1，为智能搜索领域提供了一套通用的解决方案
2，使用简单，仅需要集成几个接口，就可以完成训练、查询等功能
3，支持多语言版本，包括C++，Python，Java和C#
4，提供docker版本和web版本示例，方便上手

- 示例代码：
请参见github链接

- 截图：
![image](https://user-images.githubusercontent.com/37905059/117400238-cb5d9480-af34-11eb-9b1a-d5fce9f9933a.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。


**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。

期待持续完善该项目，后续推荐更多的项目。


再次感谢您对 HelloGitHub 的支持 🙏
