### ISSUE TITLE
项目自荐 | GoGoCode，简单易上手的 JS 代码 AST 转换工具

### ISSUE THREAD

**Issue by bigfengyu** [521xueweihan/HelloGitHub#1732]
## 项目推荐

- 项目地址：https://github.com/thx/gogocode
- 官网：https://gogocode.io Playground：https://play.gogocode.io

- 类别：JavaScript,AST

- 项目后续更新计划：支持更多的语法格式，提供更便利的代码修改能力

- 项目描述 & 推荐理由：以往的AST处理工具对代码的操作纷繁复杂，GoGoCode 利用类似 jQuery 的语法和字符串构建替换AST的形式大大简化了CodeMod的编写工作，像字符串替换一样直觉和方便，却更精准和格式无关。[介绍文章](https://juejin.cn/post/6938601548192677918)

- 示例代码：

下面这段 demo 的效果是把代码中 text 属性更名为 name，把 value 属性更名为 id

如果用正则很难精确匹配容易误伤，操作AST树还有些麻烦，用 GoGoCode 只需要这么替换一下就行了：

```typescript
const $ = require('gogocode')

const input = `

const list = [
  {
    text: "A策略",
    value: 1,
    tips: "Atip",
  },
  {
    text: "B策略",
    value: 2,
    tips: "Btip",
  },
  {
    text: "C策略",
    value: 3,
    tips: "Ctip",
  },
];

// ts的类型标记，这种正则替换会被错误替换的，在 gogocode 里就不会
const text: string = ''
// 这一段因为没有 value 就不会被选择器匹配到，也不会被错误替换
const cfg = {
  text: ''
}

`
  
const output = $(input2).replace(
  '{ text: $_$1, value: $_$2, $$$ }',
  '{ name: $_$1, id: $_$2, $$$ }'
).generate();

```

- 截图：
![image](https://user-images.githubusercontent.com/9885968/117531910-75ade880-b017-11eb-96c7-43fa9cd44b9e.png)

**Comment by 521xueweihan** [comment]
这个功能，IDE 不支持吗

**Comment by bigfengyu** [comment]
> @bigfengyu 这个功能，IDE 不是支持吗。搞这个项目的目的是啥？

不是一回事，它类似于更易用的 jscodeshift，是基于ast做代码转换的，很多人有些 codemod的需求，但是完全按照ast树遍历修改的方式是非常痛苦的，这个项目能让你用一种类似于ide正则替换的方式来做ast级别的代码转换，这样就不受代码风格、空格、换行的制约，还能随时到树里面进行结构性替换。
