### ISSUE TITLE
项目自荐 | Varlet，基于Vue3的Material风格移动端组件库

### ISSUE THREAD

**Issue by haoziqaq** [521xueweihan/HelloGitHub#1733]
## 项目推荐
- 项目地址：https://github.com/haoziqaq/varlet

- 类别：Javascript Vue

- 项目后续更新计划：完善组件单元测试，兼容Vue2.7

- 项目描述：
基于Vue3的Material风格移动端组件库
1.提供40多个高质量通用组件
2.组件十分轻量
3.由国人开发，完善的中英文文档和后勤保障
4.支持按需引入
5.支持主题定制
6.支持国际化
7.支持webstorm，vscode组件属性高亮
8.支持SSR
9.支持Typescript

- 推荐理由：轻简实用的api设计，完善的中英文文档，完善的模板，ts, tsx类型提示，以及填补了vue3生态初期移动端组件库多样性空白。

- 截图：
![image](https://user-images.githubusercontent.com/24223652/117568799-09091b80-b0f5-11eb-993f-6f8f8b37dc43.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by haoziqaq** [comment]
> 非常感谢您推荐项目。
> 
> **该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
> 期待持续完善该项目，后续推荐更多的项目。
> 
> 再次感谢您对 HelloGitHub 的支持 🙏

能询问一下是哪个部分未符合审核标准么？

**Comment by haoziqaq** [comment]
> 非常感谢您推荐项目。
> 
> **该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
> 期待持续完善该项目，后续推荐更多的项目。
> 
> 再次感谢您对 HelloGitHub 的支持 🙏

个人感觉可能是因为没有附上文档地址 我会重新开一个issue
