### ISSUE TITLE
项目自荐 | ncgen，一个令人愉悦的代码生成器

### ISSUE THREAD

**Issue by daniel-dx** [521xueweihan/HelloGitHub#1734]
## 项目推荐
- 项目地址：https://github.com/daniel-dx/ncgen

- 类别：JS

- 项目后续更新计划：

- 项目描述：
  ncgen，一个令人愉悦的代码生成器。
  你只需简单按照指南提供一份描述了代码生成器逻辑的配置，即可开发出一个功能强大的代码生成器

- 推荐理由：
  - 配置开发：仅仅开发一份简单的配置文件，即可拥有一个比“复制粘贴修改”好用得多的代码生成器
  - 不止脚手架：开发的代码生成器不止是一次性的脚手架工具，增量为项目生成代码才是它的拿手好戏
  - 项目即模板：任意的项目都可不作一点改造就直接作为项目模板，项目模板本身就是一个可运行的项目

- 示例代码：（可选）长度：1-20 行

```sh
# 安装
$ npm i ncgen -g # yarn global add ncgen

# 生成配置
$ ncgen genConf

# 运行主命令生成项目脚手架
$ ncgen ncgen-config.js

# 查看所有子命令
$ ncgen ncgen-config.js::help

# 运行子命令在生成的项目中新增组件
$ ncgen ncgen-config.js::add-component
```

- 截图：（可选）gif/png/jpg
![ncgen-home.png](https://p9-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/1ff00763d86f4710a0aae8f241f50107~tplv-k3u1fbpfcp-watermark.image)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by daniel-dx** [comment]
看了审核标准，难道是觉得README没啥内容，然后误以为文档不全吗？

**Comment by daniel-dx** [comment]
你好，看了审核标准，没明白ncgen的项目不满足的点在哪，难道是因为README内容较少让你误以为没文档吗？

项目的中文文档是：[https://daniel-dx.github.io/ncgen/zh/](https://daniel-dx.github.io/ncgen/zh/)，我是觉得该文档算是诚意满满了，从项目github首页是可以直接链接过去的

现在一些热门的开源项目也是这种形式，如https://github.com/vuejs/vuepress，它的github READMEP写得很简洁，文档是在另外的地方维护的
