### ISSUE TITLE
项目自荐 | yoz-comment 开源评论系统

### ISSUE THREAD

**Issue by kwokronny** [521xueweihan/HelloGitHub#1735]
## 项目推荐
- 项目地址：https://github.com/kwokronny/yoz-comment

- 类别：Go

- 项目后续更新计划：
  - [ ] 支持sqlite
  - [ ] 增加样式主题
  - [ ] 后台导出功能

- 项目描述：
  - 必写：gin + typescript 开发的评论系统，单文件编译，方便部署，可视化配置，为网站提供评论功能
  - ### 特点
    * 多级评论
    * 部署简单，可视化配置
    * 支持MySQL、PostgreSQL
    * 支持响应式
    * 支持 明/暗 主题
    * 接入 Gravatar 头像显示
    * 支持敏感词识别
    * 支持邮件通知自己 及 SendCloud平台 发信通知留言者有回复

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？

- 示例代码：（可选）长度：1-20 行

- 截图：
- ![](https://cdn.jsdelivr.net/gh/kwokronny/kwokronny.github.io@latest/202105/yoz-comment/preview.jpg)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
