### ISSUE TITLE
项目推荐 | Playground macOS - 伪装成 fake macOS Big Sur 系统的个人简介页

### ISSUE THREAD

**Issue by SekiBetu** [521xueweihan/HelloGitHub#1738]
## 项目推荐
- 项目地址：https://github.com/Renovamen/playground-macos

- 类别：JS

- 项目后续更新计划：不清楚

- 项目描述：
    - 通过 Lanchpad 展示多个个人开源项目
    - 内置简易 Bear，通过文字介绍自己和开源项目
    - 内置简易 Safari，可作为浏览器使用，首页书签列举个人相关网站
    - 通过开源项目 GitHub1s 制作简易在线 VSCode
    - 内置简易终端

- 推荐理由：创意很不错的个人简介展示网页

- 截图：
![image](https://user-images.githubusercontent.com/38283893/118094593-825c8300-b401-11eb-960c-3264327f1933.png)
![image](https://user-images.githubusercontent.com/38283893/118094609-89839100-b401-11eb-99e4-e49e02f255fa.png)

**Comment by SekiBetu** [comment]
类似的项目还有
https://github.com/PuruVJ/macos-web
https://github.com/vivek9patel/vivek9patel.github.io
https://github.com/GoodManWEN/GoodManWEN.github.io

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 62 期](https://hellogithub.com/periodical/volume/62/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
