### ISSUE TITLE
项目推荐 | Github1s - 快速使用在线 VS Code 阅读 GitHub 上的代码

### ISSUE THREAD

**Issue by SekiBetu** [521xueweihan/HelloGitHub#1739]
## 项目推荐
- 项目地址：https://github.com/conwnet/github1s

- 类别：JS

- 项目后续更新计划：不清楚

- 项目描述：只需要把网址中的 github.com 改为 github1s.com(或者是自己部署的服务器域名) 就可以使用 VS Code 进行在线代码浏览。

- 推荐理由：以在线 VS Code 的样式阅读 github 仓库的代码，不需要 clone 到本地再使用 VS Code 打开，且可以多开，方便阅读多个仓库的代码

- 截图：
![GitHub1sDemo1](https://user-images.githubusercontent.com/38283893/118096837-7a521280-b404-11eb-855a-f2229b1c7171.gif)
![image](https://user-images.githubusercontent.com/38283893/118096847-7d4d0300-b404-11eb-842b-124e7b33b726.png)

**Comment by 521xueweihan** [comment]
感谢推荐，之前推荐过啦。
