### ISSUE TITLE
PHP-ML机器学习库推荐

### ISSUE THREAD

**Issue by Neroxiezi** [521xueweihan/HelloGitHub#174]
## 项目推荐
- 项目名称：
   php-ml-study
- 项目地址：
 [](https://github.com/Neroxiezi/PHP-ML-study.git)
- 项目语言：
php
- 项目描述：
基于php-ml的机器学习中文实例
- 推荐理由：
GitHub 上PHP-ML 机器学习库 实例缺少,并且官方文档实例不够，而推荐的这个是让更多的人学习PHP也可以做机器学学习

- 示例代码：
   https://github.com/Neroxiezi/PHP-ML-study/blob/master/README.md
- 截图：
![image](https://user-images.githubusercontent.com/11400329/34475059-a749704e-efc2-11e7-9c6b-b251aba15683.png)

**Comment by 521xueweihan** [comment]
机器学习还是主要以 python 为主。

由于篇幅和内容关系，不能收录你的项目，望海涵。希望继续推荐更加有意义、价值、有意思的项目
