### ISSUE TITLE
自荐项目 | kvrocks - 基于 RockDB 实现 Redis 协议兼容的 NoSQL 数据库

### ISSUE THREAD

**Issue by git-hulk** [521xueweihan/HelloGitHub#1741]
## 项目推荐
- 项目地址：https://github.com/bitleak/kvrocks

- 类别：C++
- 项目后续更新计划：https://github.com/bitleak/kvrocks/projects/1
   - 支持集群模式
   - 支持半同步语义

- 项目描述：磁盘类型的 Redis 存储，旨在降低 Redis 内存成本以及提高单机存储容量
     - 兼容 Redis 协议
     - 支持主从同步
     - 通过 Namespace 做业务数据隔离
     - 高可用，可通过 redis sentinel 来进行 failover

- 推荐理由：兼容 Redis 命令的高性能 NoSQL 数据库，相比 Redis 来说，存储成本可以降到 Redis 的 1/3 以上，同时容量可以提高一个量级。目前已经在美图、携程、白山云以及百度等公司线上使用。

![performance](https://raw.githubusercontent.com/bitleak/kvrocks/master/docs/images/chart-commands.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 62 期](https://hellogithub.com/periodical/volume/62/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
