### ISSUE TITLE
【项目自荐】NPlayer  支持移动端、高度可定制的弹幕视频播放器

### ISSUE THREAD

**Issue by woopen** [521xueweihan/HelloGitHub#1743]
## 项目推荐

- 项目地址：[https://github.com/woopen/nplayer](https://github.com/woopen/nplayer)

- 官网地址：[https://nplayer.js.org](https://nplayer.js.org)

- 类别：JS

- 项目后续更新计划：
  - 字幕插件及字幕实时翻译
  - 支持全景视频

- 项目描述：NPlayer 是由 Typescript 加 Sass 编写，无任何第三方运行时依赖，兼容 IE11，支持移动端、支持 SSR、支持直播。高度可定制，所有图标、主题色等都可以替换，并且提供了内置组件方便二次开发。你可以自定义任意多个断点，不仅仅是兼容移动端，只要愿意，你可以非常轻松的兼容手机竖屏、手机横屏、平板等设备。它还拥有插件系统，弹幕功能就是使用插件形式提供，使用时按需引入即可。该播放器还可以接入任何流媒体，如 hls、dash 和 flv 等。

- 推荐理由：目前大部分播放器都只支持桌面端，NPlayer 可以自定义任意多的断点，两套交互方案（触屏交互和键鼠交互），手机、平板、桌面设备全支持。NPlayer 高度可定制，可以轻松的更换主题。同时也拥有高性能的弹幕系统。

- 示例代码：

```js
import Player from "nplayer";

/**
 * Danmaku DEMO:
 *    https://codesandbox.io/s/nplayer-demo-ujtms?file=/src/index.js
 * React DEMO:
 *    https://codesandbox.io/s/nplayer-react-demo-p558g?file=/src/App.js
 * Vue2 DEMO:
 *    https://codesandbox.io/s/nplayer-vue2-demo-9lps9?file=/src/main.js
 * Vue3 DEMO:
 *    https://codesandbox.io/s/nplayer-vue3-demo-mt8s4?file=/src/main.js
 */
const player = new Player({
  src: "https://v-cdn.zjol.com.cn/280443.mp4"
});

player.mount(document.body);
```

- 截图：

![preview](https://user-images.githubusercontent.com/25923128/118581816-d5995180-b7c4-11eb-95aa-69365a8d688b.jpeg)

**Comment by 521xueweihan** [comment]
已推荐过类似项目 DPlayer，您的项目咱不收录到月刊中。

我看您写的文章不错，可以给 HelloGitHub [投稿](https://www.yuque.com/docs/share/bf781d29-cc94-44dd-b226-9d70fa38fa1c)。

**Comment by woopen** [comment]
好的
