### ISSUE TITLE
Midway.js 最佳实践，可能是东半球最好的 Node.js 实践项目

### ISSUE THREAD

**Issue by tkvern** [521xueweihan/HelloGitHub#1746]
## 项目推荐
- 项目地址：https://github.com/fsd-nodejs/service-mw2

- 类别：Node.js

- 项目后续更新计划：

- 项目描述：
  在这个项目中，你会看到以下基于 Midway 的实践案例 (上层使用 egg.js )
  **所有代码均已经过工程师的测试请放心使用!!!**

| 能力栏目                 | 名称                                   | 进度 |
| :------------------------------------- | ---- | :--: |
| **概述** |      |      |
|                        | 控制器(Controller) | ✅ |
|                        | 服务和注入 | ✅ |
|                        | 请求、响应和应用 | ✅ |
|                        | Web 中间件 | ✅ |
|                        | 启动和部署 | ✅ |
| **基础能力** |  | |
|                        | 依赖注入 | ✅ |
|                        | 运行环境 | ✅ |
|                        | 多环境配置 | ✅ |
|                        | 参数校验和转换 | ✅ |
|                        | 生命周期 | ✅ |
|                        | 使用组件 | ✅ |
|                        | 日志 | ✅ |
|                        | 本地调试 | ✅ |
|                        | 测试 | ✅ |
| **增强** |  | |
|                        | 代码流程控制 | |
|                        | 方法拦截器（切面） | |
|                        | 缓存（Cache）(目前直接使用 Redis) | ✅ |
|                        | Database（TypeORM) | ✅ |
|                        | MongoDB | |
|                        | Swagger | ✅ |
| **一体化研发** |  | |
|                        | 开发一体化项目 | |
|                        | 非 Serverless 环境使用一体化 | |
| **Web技术** |  | |
|                        | Cookies | |
|                        | Session | |
|                        | 跨域 CORS | ✅ |
| **微服务** |  | |
|                        | gRPC | |
|                        | RabbitMQ | |
|                        | Consul | |
| **WebSocket** |  | |
|                        | SocketIO | |
| **常用能力** |  | |
|                        | Admin 登录 | ✅ |
|                        | 普通用户登录-账户密码 | |
|                        | OAuth 2.0 | |
|                        | 日志监控 | |
|                        | 本地上传文件服务 | |
|                        | 鉴权中间件 | ✅ |
|                        | 接口响应统计中间件 | ✅ |
|                        | 统一错误处理 | ✅ |
|                        | SnowFlake 雪花算法生成分布式ID | ✅ |
|                        | Jaeger 链路追踪 | ✅ |
| **业务能力** |                                        |      |
|                | 权限管理                                 |  ✅   |
|                | 角色管理                                 |  ✅   |
|                | 管理员管理                               |  ✅   |
|                | 菜单管理                                 |  ✅   |
|                | 日志(操作日志，记录管理用户的实际操作) | ✅ |

  
- 推荐理由：帮你扫清学习障碍，让你用起 Midway 来更加得心应手，提升能效，找回编码的乐趣。

- 截图：
![image](https://user-images.githubusercontent.com/10667077/118634217-e073d680-b804-11eb-80c2-824f93046d5a.png)

**Comment by 521xueweihan** [comment]
已推荐过类似的项目：https://github.com/cool-team-official/cool-admin-midway

所以您的项目暂不收录到月刊。
