### ISSUE TITLE
项目推荐- Swift项目

### ISSUE THREAD

**Issue by liumenghua** [521xueweihan/HelloGitHub#1748]
## 项目推荐
- 项目地址：https://github.com/Instagram/IGListKit

- 类别：Swift

- 项目后续更新计划：12K star 更新频繁

- 项目描述：IGListKit 是 Instagram 推出的一套数据驱动的 UICollectionView 框架，用来创建快速灵活的列表界面

- 推荐理由：提供了更简单的使用 UICollectionView 方式，并且支持对自己的数据模型进行自定义 diff 操作，提供更好的架构以复用 Cell 和组件，不再需要调用 performBatchUpdates(_:, completion:) 或者 reloadData()

- 示例代码：[参考文档](https://www.raywenderlich.com/9106-iglistkit-tutorial-better-uicollectionviews)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 62 期](https://hellogithub.com/periodical/volume/62/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
