### ISSUE TITLE
项目自荐 | 《计算机视觉实战演练：算法与应用》免费在线电子书+源码

### ISSUE THREAD

**Issue by Charmve** [521xueweihan/HelloGitHub#1749]
## 项目推荐
动手学 ！！！
![image](https://user-images.githubusercontent.com/29084184/119107865-3be6d400-ba52-11eb-84ba-633abc4ba9ea.png)

- 项目地址：https://github.com/Charmve/computer-vision-in-action

- 类别：书籍、计算机视觉

- **项目背景描述**
  
  计算机视觉主要研究如何使机器能对环境和其中的刺激进行可视化分析，通常涉及对图像或视频的评估，属于较前沿的学科分支。随着人工智能热潮的来临，大批学生、从业者开始学习或者从事计算机视觉相关工作，但因其涉及较为深奥的数学理论和复杂的软件实现，“行百里者半九十”。

  只是看理论，却总也学不会？看不懂，又总没有进度？动手实践了，又因为网络资源质量的参差不齐，总是碰到棘手的bug。如果你也有这类问题，那你来看看这本书。作者以实际项目为导向，带领读者亲自动手实践，从简单的手写字识别、人脸检测、图像分类开始，逐渐学习掌握实例分割、目标检测、车道线检测等进阶技能。学习有回馈、有成就感，你才能继续下去。

- **项目描述**：

  本书分为基础篇、理论篇、实战篇和进阶篇，从计算机视觉涉及到的基础理论讲起，用简单通俗的语言讲解模型的基本原理，给出模型的代码实现，最后每个模型用一个完整的实际项目带领读者亲自编程、debug、运行。当每条代码运行通过后，给出漂亮的结果，每个读者都会充满信心，并在不断的正向反馈中学习到实际的计算机视觉项目技能。

  在实战篇，文中分析重要的神经网络模型，阐述其优缺点和适用条件，并给出完整的模型训练过程，带领读者学习如何搭建、训练、调参、交叉验证、模型优化，对项目实战能力有较高的提升。而在进阶篇，作者将分享最新的计算机视觉模型，学习注意力模型、BERT、知识蒸馏、迁移学习在计算机视觉中的应用，保持行业动态的敏感度，扩充自身的项目前瞻能力。

- 本书主要适合于以下读者：

1. 掌握基本的数学基础和编程能力的初学者；
2. 对计算机视觉领域感兴趣的软件开发人员；
3. 图像处理、图形学、模式识别等方向的学生和从业者；
4. 互联网技术程序员；
5. 喜欢动手实践的软件开发者；

- **特色**
1. 将深奥的深度学习、机器学习理论拆解，分为小模块进行分析，抓住算法原理和模型的搭建、优化方法即可，降低读者的学习负担。
2. 每个章节都有作者精心编排的小练习和实战项目，快速体验和掌握理论方法。
3. 可跨平台的在线资料，搭载Colab减少因软件环境差异带来的不必要麻烦；同时，给出requirement.txt 为这本书的软件环境做一个同意的配置，每个章节代码均可独立运行。
4. 本书分为基础篇、理论篇和实战篇、进阶篇，自顶向下、模块化组织本书内容，既可按书目先后顺序阅读，也可独立阅读各章节。
6. 特别地，本书给出了进阶篇目，解读最新的计算机视觉模型和方法，紧跟前言模型，提高专业能力。学完本书，将达到一名计算机视觉算法工程师基本从业技能要求。

- 项目后续更新计划：
继续跟新相关章节，按照目前的框架进行编写，提供每章节对应的源代码和notebook。

- **样章或代码**：

![image](https://user-images.githubusercontent.com/29084184/119107925-486b2c80-ba52-11eb-8d6e-f040e4375584.png)

![image](https://user-images.githubusercontent.com/29084184/119107953-4f923a80-ba52-11eb-90fb-edd56062e207.png)

![image](https://user-images.githubusercontent.com/29084184/119108157-7b152500-ba52-11eb-8212-b3e69de82604.png)

<br>
<br>
感谢HelloGithub，之前发布的项目得到推荐！

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by Charmve** [comment]
> 非常感谢您推荐项目。
> 
> **该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
> 期待持续完善该项目，后续推荐更多的项目。
> 
> 再次感谢您对 HelloGitHub 的支持 🙏

再次推荐！

[GitHub重磅开源！《计算机视觉实战演练：算法与应用》代码、数据集、在线学习](https://zhuanlan.zhihu.com/p/377866938)
