### ISSUE TITLE
项目自荐 | Varlet，基于Vue3的Material风格移动端组件库

### ISSUE THREAD

**Issue by haoziqaq** [521xueweihan/HelloGitHub#1750]
## 项目推荐
- 项目地址:  https://github.com/haoziqaq/varlet

- 文档站点:  https://varlet.gitee.io/varlet-ui

- 类别：Javascript Vue

- 项目后续更新计划：完善组件单元测试，兼容Vue2.7

- 项目描述：
基于Vue3的Material风格移动端组件库
1.提供40多个高质量通用组件
2.组件十分轻量
3.由国人开发，完善的中英文文档和后勤保障
4.支持按需引入
5.支持主题定制
6.支持国际化
7.支持webstorm，vscode组件属性高亮
8.支持SSR
9.支持Typescript

- 推荐理由：轻简实用的api设计，完善的中英文文档，完善的模板，ts, tsx类型提示，以及填补了vue3生态初期移动端组件库多样性空白。

- 截图：
![image](https://user-images.githubusercontent.com/24223652/117568799-09091b80-b0f5-11eb-993f-6f8f8b37dc43.png)

**Comment by 521xueweihan** [comment]
@haoziqaq 您好，我并非专业的前端。所以不是很懂和已推荐过的 vant 区别在哪里

您能否简述下和有赞的 vant 项目对比异同和优势

**Comment by haoziqaq** [comment]
> @haoziqaq 您好，我并非专业的前端。所以不是很懂和已推荐过的 vant 区别在哪里
> 
> 您能否简述下和有赞的 vant 项目对比异同和优势

1.首先是UI的整体风格是基于谷歌的Material Design设计规范，追求的是材料的质感和动画效果，vant则是国内电商一贯扁平风格。
2.随着移动设备性能越来越好，在手机上一些动画的表现力更强了，以往的ui库设计风格都比较保守，为了在性能和效果上平衡实际上损失了一些表现力，我们就没有这样的包袱，在一些非电商的场景下varlet可能更适合。
3.vue3的生态属于基础建设时期，市面上vue3的移动端仓库十分少见，这也是我们的优势。不过vant也很快的推出了vue3版本。

**Comment by 521xueweihan** [comment]
好的，我看完决定暂不收录您的项目了。
