### ISSUE TITLE
项目自荐|消息Plus-富文本消息钉钉小程序

### ISSUE THREAD

**Issue by KangSpace** [521xueweihan/HelloGitHub#1753]
## 项目推荐
- 项目地址：https://github.com/KangSpace/message_plus

- 类别：JS

- 应用类型：钉钉小程序

- 项目描述：
  - 消息Plus项目通过集成钉钉小程序普通消息API，扩展个人的会话消息发送类型，可以发送多种类型的富文本消息。
  - 可使用消息Plus小程序直接发送OA消息，Markdown，卡片等类型的消息。
 
- 截图：
![image](https://user-images.githubusercontent.com/26271023/119849871-96df6600-bf3f-11eb-968a-d9f1aa81ddcb.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
