### ISSUE TITLE
Web多人协同富文本编辑器

### ISSUE THREAD

**Issue by BennettChina** [521xueweihan/HelloGitHub#1754]
## 项目推荐

- 项目地址：https://github.com/itellyou-com/am-editor

- 类别：JS
- 项目后续更新计划：非本人开发，仅作为发现者，不知道后续计划。

- 项目描述：
  am-editor，一个基于ShareDB 的 Web 多人协同富文本编辑器，适用于React、Vue框架，与主流的现代浏览器兼容。使用浏览器提供的`contenteditable`属性让一个 DOM 节点具有可编辑能力。

众所周知`contenteditable`属性，在不同的浏览器厂商中实现会有不同的差异，并且其默认行为具有不可预测性，因此我们封装了一个具有一定可控性的编辑能力引擎库`@aomao/engine`，在默认行为和期望行为之间进行平衡取舍。

引擎库使用javascript编写，我们对 DOM 节点插入、删除、替换等一系列操作、包括光标、事件进行了封装并派生接口。因此，在引擎中我们的所有操作都将直接编辑复杂的 DOM 树，在数据结构中我们也将以 DOM 树结构呈现。不过在实际应用中，我们非常有必要对复杂的 DOM 树结构进行约束，以免出现不可预期的行为，并且在当前流行使用React Vue等前端框架来渲染 UI 的情况下，让我们再使用javascript定制 UI 是一件非常痛苦的事情。所以我们把 DOM 节点按功能和特性分为以下几类：mark inline block card 并且通过 schema 来约束他们特定的行为和一些特质属性，在 card 组件中我们还可以结合前端框架来完成复杂的 UI 渲染和编辑嵌套。

在现代化企业中，协同办公已是高效的代名词。在即时通讯、视频会议之后让文档也协同起来，已是大势所趋。在引擎库中，我们基于ShareDB提供协同编辑能力，把复杂的 DOM 结构转换为JSON0协议的数据结构后，提交给sharedb处理协同编辑的交互。
📦 开箱即用，提供几十种丰富的插件来满足大部分需求
🏷 高扩展性，除了mark inline block基础插件外，我们还提供card组件结合React Vue等前端框架渲染插件 UI
📋 丰富的多媒体支持，不仅支持图片和音视频，更支持插入嵌入式多媒体内容
🐠 不依赖前端框架，复杂架构轻松应对
📡 内置协同编辑方案，轻量配置即可使用

- 推荐理由：目前比较好用的语雀、石墨等未开源，难以集成到项目中，此项目好用程度堪比语雀、石墨，又是开源项目可集成到项目中，非常适合需要集成文档编辑器到项目。

- 截图：

![image](https://user-images.githubusercontent.com/48208644/119958312-811c8000-bfd5-11eb-8dcb-eb8ca9080148.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by 521xueweihan** [comment]
但我觉得 ShareDB 这个项目很有意思
