### ISSUE TITLE
GBA模拟器

### ISSUE THREAD

**Issue by Ayerss** [521xueweihan/HelloGitHub#1756]
## 项目推荐
- 项目地址：https://github.com/mgba-emu/mgba

- 类别：C

- 项目后续更新计划：非本人开发，仅作为发现者，不知道后续计划

- 项目描述：
mGBA是运行Game Boy Advance游戏的模拟器。它旨在比许多现有的Game Boy Advance模拟器更快、更准确，并添加其他模拟器所缺乏的功能。它还支持Game Boy和Game Boy Color游戏。

- 推荐理由：支持全平台的GBA模拟器

- 截图：
![GBA](https://user-images.githubusercontent.com/39729707/119961660-e45be180-bfd8-11eb-9f27-ebda8b570be3.jpg)
![口袋妖怪](https://user-images.githubusercontent.com/39729707/119961669-e625a500-bfd8-11eb-9cd2-54b9d483e914.jpg)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 63 期](https://hellogithub.com/periodical/volume/63/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
