### ISSUE TITLE
EasyHttp

### ISSUE THREAD

**Issue by vizaizai** [521xueweihan/HelloGitHub#1763]
## 自荐项目
- 项目地址：https://github.com/vizaizai/easy-http
- 类别：Java

- 项目后续更新计划：
1. 移除多余的三方依赖
2. 拆分底层客户端实现，根据用户引入的依赖替换底层实现
3. 增加更多的客户端实现-Java11、okHttp等
4. 优化实现逻辑，采用更多的设计模式
5. 增加新的代理方式

- 项目描述：
  - 必写：easy-http是一个完全基于注解和接口的http客户端，为简化开发、提高效率而生。
  - 可选：让Http请求更容易，新手可以学习到Java反射应用，加深对http理解，jdk动态代理、springBoot的Bean扫描注入过程等
  - 描述长度（不包含示例代码）: 
              easy-http是一个完全基于注解和接口的http客户端，为简化开发、提高效率而生。

- 推荐理由：基于接口的http请求客户端，为简化开发、提高效率而生，并提供spring-boot-starter版本，自动扫描注入到Ioc。

- 示例代码：（可选）长度：1-20 行
``` 
    // 设置了-parameters
@Get("/books")
ApiResult<List<Book>> listBooksByAuthor2(@Param String author);

@Get("/books")
ApiResult<List<Book>> listBooksByAuthor(@Param Map<String, String> params);

@Get("/books")
ApiResult<List<Book>> listBooksByAuthor(Map<String, String> params);

@Get("/books")
ApiResult<List<Book>> listBooksByIds(@Param("ids") List<String> ids);
```

**Comment by 521xueweihan** [comment]
建议：
1. for human 的 Java HTTP 客户端
2. 思考下这个库的独特亮点和在那里些场景下独树一帜
3. 保持更新，多和 Java 程序员交流

本 issues 将在保留一个月，期待有让人眼前一亮的改变。

**Comment by vizaizai** [comment]
好的，谢谢，最近也构思一些新东西。后续我会把starter版本也提上来，starter版本更能体现它的简化性和扩展性。

**Comment by vizaizai** [comment]
暂时关闭，最近工作比较忙，之后再开启
