### ISSUE TITLE
SimpleDocker

### ISSUE THREAD

**Issue by taoes** [521xueweihan/HelloGitHub#1764]
## 项目推荐
- 项目地址：https://github.com/taoes/SimpleDocker

- 类别：Go

- 项目后续更新计划：
  计划支持DockerSwarm集群管理以及docker-compose实现镜像编排
- 项目描述：
   SimpleDocker是一个简单好用的Docker控制面板，能够非常轻松地管理Docker，其具有简单，直接的特点，为不熟悉Docker同学提供了非常快的使用途径。SimpleDocker一般部署在远程服务上，通过WEB界面的方式进行管理，初学者可以通过学习Go的开发经验，以及DockerSDK的使用。

- 推荐理由：简单，简洁，上手快

- 示例代码：
```go
    func initContent() error {
        var err error
            Ctx = context.Background()
        Cli, err = client.NewClientWithOpts(client.FromEnv, client.WithAPIVersionNegotiation())
        _ = http.Client{
            Transport: &http.Transport{
                DialContext: func(_ context.Context, _, _ string) (net.Conn, error) {
                    if runtime.GOOS == "darwin" || runtime.GOOS == "linux" {
                        return net.Dial("unix", "/var/run/docker.sock")
                    } else {
                        return net.Dial("unix", "/var/run/docker.sock")
                    }
                },
            },
        }
        return err
    }
```

- 截图：

![image](https://user-images.githubusercontent.com/22141049/120593624-58cbd000-c472-11eb-89e1-1bf776d090ed.png)

**Comment by HuberWong** [comment]
unsubscribe



在 2021-06-03 13:49:52，"Zhoutao" ***@***.***> 写道：

项目推荐

项目地址：https://github.com/taoes/SimpleDocker

类别：Go

项目后续更新计划：
计划支持DockerSwarm集群管理以及docker-compose实现镜像编排

项目描述：
SimpleDocker是一个简单好用的Docker控制面板，能够非常轻松地管理Docker，其具有简单，直接的特点，为不熟悉Docker同学提供了非常快的使用途径。SimpleDocker一般部署在远程服务上，通过WEB界面的方式进行管理，初学者可以通过学习Go的开发经验，以及DockerSDK的使用。

推荐理由：简单，简洁，上手快

示例代码：

funcinitContent() error {

        varerrerrorCtx=context.Background()

        Cli, err=client.NewClientWithOpts(client.FromEnv, client.WithAPIVersionNegotiation())

        _= http.Client{

            Transport: &http.Transport{

                DialContext: func(_ context.Context, _, _string) (net.Conn, error) {

                    ifruntime.GOOS=="darwin"||runtime.GOOS=="linux" {

                        returnnet.Dial("unix", "/var/run/docker.sock")

                    } else {

                        returnnet.Dial("unix", "/var/run/docker.sock")

                    }

                },

            },

        }

        returnerr

    }
截图：

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by 521xueweihan** [comment]
@HuberWong 点右上角的 Unwatch 选择通知模式即可，我这边是没法操作的
