### ISSUE TITLE
项目推荐-JS项目

### ISSUE THREAD

**Issue by liumenghua** [521xueweihan/HelloGitHub#1765]
## 项目推荐
- 项目地址：https://github.com/banga/git-split-diffs

- 类别：JS

- 项目后续更新计划：项目更新频繁，贡献者多

- 项目描述：一个可以将代码 diff 显示为类似 GitHub 风格的命令行工具

- 推荐理由：在终端上使用git diff查看修改时，系统默认的效果并不直观，该项目以将代码 diff 显示为类似 GitHub 风格，方便查看，并且支持多种主题以及配置。

- 截图：

![](https://github.com/banga/git-split-diffs/blob/main/screenshots/dark.png?raw=true)

**Comment by 521xueweihan** [comment]
本期篇幅有限，这个项目下期收录

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 64 期](https://hellogithub.com/periodical/volume/64/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目
