### ISSUE TITLE
高性能的javascript拼音匹配库

### ISSUE THREAD

**Issue by xmflswood** [521xueweihan/HelloGitHub#1767]
## 项目推荐
- 项目地址：https://github.com/xmflswood/pinyin-match

- 类别：JS

- 项目描述：
  - 必写：小而快的JS拼音匹配方法，参考微信通讯录匹配规则。
  - 可选：支持多音字、繁体字、拼音首字母匹配,具备分词功能，在长多音字串下依然有高性能。

- 截图：
![GIF 2021-6-7 13-34-24](https://user-images.githubusercontent.com/13427833/120963975-1a495480-c795-11eb-9ba3-f844820bc5a2.gif)

**Comment by 521xueweihan** [comment]
我看了你的项目和文章，我觉得这个项目写成一篇文章，应该会比收录到月刊中给读者来带的知识多。相应的也对你的项目有更多的曝光。

可以先考虑下，决定后加我的微信：xueweihan（备注你的项目名）
