### ISSUE TITLE
项目自荐 | m2obj - 在Go中处理动态JSON数据

### ISSUE THREAD

**Issue by RickoNoNo3** [521xueweihan/HelloGitHub#1769]
## 项目推荐

-   项目地址：[RickoNoNo3/m2obj](https://github.com/RickoNoNo3/m2obj)

-    类别：Go

-    项目后续更新计划：见[README:TODO](https://github.com/RickoNoNo3/m2obj/blob/master/README_CN.md#todo)

-----

-    项目描述：

一个类JSON的、动态的、可持久化的 Golang 【对象结构】, 可用于管理配置项、缓存、模板引擎数据, 也可以单纯用来存储动态JSON格式对象.

项目在[gopkg](https://pkg.go.dev/github.com/rickonono3/m2obj)有完整文档, 有[中文README](https://github.com/RickoNoNo3/m2obj/blob/master/README_CN.md).

-----

-    推荐理由：

> 以下内容摘抄自[README:为何使用 M2Obj](https://github.com/RickoNoNo3/m2obj/blob/master/README_CN.md#%E4%B8%BA%E4%BD%95%E4%BD%BF%E7%94%A8-m2obj)
> - Go 原生的处理树形动态数据的方式需要频繁地对每层数据进行类型断言, 代码过长. 而 M2Obj 只需在定位数据后使用已封装好的取值方法即可.
> - Go 原生的对 JSON 结构数据的支持有所欠缺. M2Obj 进行了大量封装和改善, 并且专为 JSON / 类 JSON 格式做了适配性开发.
> - M2Obj 拥有高效、并发的 Goroutine 文件同步器, 在内存数据和文件间进行自动同步

对学习者来讲, 该项目有如下帮助:
- 深入了解 `slice` / `map` / 指针 / `error` / `panic` 等基础知识及其运用
- 控制及探测 `interface{}`的实际类型, 并适当利用反射机制进行动态类型操作
- 在Go中实现树形数据结构算法 (如 深度优先搜索 / 事件冒泡 / 节点添加、删除及合并 ), 在含有`map`和`slice`的特殊节点结构下维护树上父子关系
- 学习Go中的"接口"技术在多态实现上的作用
- 学习Goroutine多线程编程, 熟悉Mutex并发控制的使用方法(当然学习这个主要还是要靠学校教的OS)
- 在关键位置编写大段注释, 完成了覆盖率100%的单元测试, 保持良好编码习惯

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
