### ISSUE TITLE
PreLoader: android页面启动速度优化利器（在页面打开之前进行预加载）

### ISSUE THREAD

**Issue by luckybilly** [521xueweihan/HelloGitHub#177]
## 项目推荐
- 项目名称： PreLoader

- 项目地址：https://github.com/luckybilly/PreLoader

- 项目语言：Java(android)

- 项目描述：

一般android页面在打开后需要在UI初始化完成后才能发起网络请求，以免网络请求返回后展示到UI时出现错误。但这种串行的做法导致页面的整个初始化时间变长。

使用本工具可以在打开页面之前预加载数据，然后在页面UI初始化完成后提取预加载好的数据进行展示，数据加载可先于UI初始化进行，从而缩短页面初始化时间。

使用状态机模式解决提取数据时数据是否已经加载完成的不同处理：已加载完则直接展示数据；未加载完则等待数据加载结束后再执行数据展示

- 推荐理由： 缩短android app的用户等待时间，提升用户体验

- 示例代码：

1. 开启预加载任务（如：在startActivity之前开启，或者更早）
```java
int preLoaderId = PreLoader.preLoad(new Loader());
Intent intent = new Intent(this, PreLoadBeforeLaunchActivity.class);
intent.putExtra("preLoaderId", preLoaderId);
startActivity(intent);

//预加载任务：模拟网络接口请求获取数据
class Loader implements DataLoader<String> {
    @Override
    public String loadData() {
        //此方法在线程池中运行，无需再开子线程去加载数据
        try {
            Thread.sleep(600);
        } catch (InterruptedException ignored) {
        }
        return "data from network server";
    }
}
```
2. 在Activity(或Fragment)中UI初始化完成后开始监听预加载数据
```java
PreLoader.listenData(preLoaderId, new Listener());

//数据加载完成后，会调用DataListener.onDataArrived(...)来处理加载后的数据
class Listener implements DataListener<String> {
    @Override
    public void onDataArrived(String data) {
        //此方法在主线程中运行，无需使用Handler切换线程运行
        Toast.makeText(activity, data, Toast.LENGTH_SHORT).show();
    }
}
```

- 截图：
<img src="https://github.com/luckybilly/PreLoader/raw/master/image/cn_inside_page.png" height="400" /> <img src="https://github.com/luckybilly/PreLoader/raw/master/image/cn_before_start_activity_1.png" height="400" /> <img src="https://github.com/luckybilly/PreLoader/raw/master/image/cn_before_start_activity_2.png" height="400" />

**Comment by 521xueweihan** [comment]
@luckybilly 您推荐的项目，已成功收录在 [HelloGitHub 第 24 期](https://hellogithub.com/volume/24/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
