### ISSUE TITLE
自荐 | 《凤凰架构：构建可靠的大型分布式系统》

### ISSUE THREAD

**Issue by fenixsoft** [521xueweihan/HelloGitHub#1770]
## 项目推荐
- 项目地址：https://github.com/fenixsoft/awesome-fenix

- 类别：开源书籍

- 项目后续更新计划：
  - 建设开源电子书及演示工程站点：https://icyfenix.cn
  - 出版音频课程。已由极客时间合作配音，提供公益性质的[音频公开课程](https://time.geekbang.org/opencourse/intro/100064201)
  - 出版纸质书。已由机械工业出版社合作出版，目前在印刷阶段，预计2021年6月末发售。

- 项目描述：
  - 必写：一部以“如何构建一套可靠的分布式大型软件系统”为叙事主线的开源文档
  - 可选：
    - **演进中的架构**：该模块会借着讨论历史之名，从全局性的视角，帮你梳理微服务发展历程中出现的大量技术名词、概念，让你了解这些技术的时代背景和探索过程，帮你在后续的课程讲解中，更容易去深入理解软件架构设计的本质。
架构师的视角：该模块不会局限在某种架构的通用技巧，而是会带你系统性地了解在做架构设计的时候，架构师都应该思考哪些问题、可以选择哪些主流的解决方案和行业标准做法，以及这些主流方案都有什么优缺点、会给架构设计带来什么影响，等等。这样一来，我们才可以把“架构设计”这样比较抽象的工作具体化、具象化。
    - **分布式的基石**：该模块会聚焦在分布式架构，和你探讨分布式带来的问题与应对策略。带你剖析分布式架构中出现的一系列问题，比如服务的注册发现、跟踪治理、负载均衡、故障隔离、认证授权、伸缩扩展、传输通讯、事务处理等，有哪些解决思路、方法和常见工具。
    - **不可变基础设施**：该模块会按照云原生时代“基础设施即代码”的新思路，带你深入理解基础设施不变性的目的、原理与实现途径，和你一起去体会用代码和用基础设施，来解决分布式问题的差异，让你能够理解不可变基础设施的内涵，便于在实际工作中做运维、程序升级和部署等工作。
    - **技术方法论**：这部文档的主体内容是务实的，多谈具体技术，少谈方向理论。只在这部分中会集中讨论几点与分布式、微服务、架构等相关的相对务虚的话题。
    - **探索与实践**：该模块会带你一起开发不同架构的Fenix’s Bookstore，并看看在不同环境下都应该怎么部署。这个模块的定位是“实战”，为了保证学习效果，特意没有安排音频，所以建议你一定要自己动手去实操。

- 推荐理由：
  - 全局视角理解微服务发展历程
  - 构建一个可靠的分布式系统
  - 实战开发不同风格的架构项目
  - 资深架构师解决问题的独到思路

- 截图：（可选）gif/png/jpg
![book 85229ff1](https://user-images.githubusercontent.com/5801867/121619956-09058e00-ca9c-11eb-8d10-2ddb082e1c33.png)

**Comment by newbee-mall** [comment]
支持！
