### ISSUE TITLE
CMS-Blog项目申请收录

### ISSUE THREAD

**Issue by Dev-Breezer** [521xueweihan/HelloGitHub#1771]
## 项目推荐
- 项目地址：https://github.com/Dev-Breezer/CMS-Blog

- 类别：PHP

- 项目后续更新计划：无

- 项目描述：
  - 必写：个人博客管理系统
  - 可选：适用于Web开发，可以让初学者了解PHP+Mysql操作、Layui组件库的使用，markdown解析过程
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：无

- 示例代码：
```php
$username = $_POST['username'];
$password = $_POST['password'];
$identity = $_POST['identity'];

$sql = "insert into users(user_name,password,identity)values('$username',$password,'$identity')";

// 验证图片数据的有效性
if($image['name']){
	//上传文件TODO: 
	
	$ext = strrchr($image['name'],'.');	//step 1.获取文件扩展名
	$filename = $username.rand(100,999).$ext;	//step 2.生成文件名
	//step 3.判断是否允许上传
	$exts = ['.jpg', '.png','.jpeg', '.webp', '.tiff'];
	//step 4.从临时文件夹上传到服务器
	if(!in_array($ext,$exts)){
		echo '文件类型不允许上传';
	}
	move_uploaded_file($image['tmp_name'],'../admin/head-image'.$filename);
	
}else{
	$filename = '';
	
}

```

- 截图：

![image](https://user-images.githubusercontent.com/81347398/121770756-d479fb00-cb9d-11eb-9eb9-2284058c871b.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
