### ISSUE TITLE
Vue中台项目

### ISSUE THREAD

**Issue by Indomite** [521xueweihan/HelloGitHub#1779]
## 项目推荐
- 项目地址：https://github.com/Indomite/BlogAdmin

- 类别：JavaScript

- 项目后续更新计划：

- 项目描述：
  - 必写：Vue的中台管理系统
  - 可选：适用于初学者完成基本的项目
  - 描述长度（不包含示例代码）: 

- 推荐理由：项目代码明了，简洁易懂，适合初学者学习，学习完了对基本的开发掌握没有问题

- 示例代码：建议运行查看

- 截图：建议运行查看

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
