### ISSUE TITLE
项目自荐 | A lightweight, high performance, open source, application layer log service framework.

### ISSUE THREAD

**Issue by jdklog** [521xueweihan/HelloGitHub#1780]
## 项目自荐
- 项目地址：https://github.com/jdkstack/jdklog

- 类别：java

- 项目后续更新计划：https://github.com/orgs/jdkstack/projects/8, Online document: https://www.jdklog.org(demo)

- 项目描述：
  - A lightweight, high performance, open source, application layer log service framework.
  - A lightweight, high performance, open source, application layer log service framework.
Although the performance is lower than log4j2(It didn't use lock-free queue,such as ring buffer), but the advantage is  no dependency lib, only need openjdk.After jmh benchmark,the performance of log4j2 is higher than that of jdklog, but less than an order of magnitude(Even lower).
Log4j2 performance is poor when output location information, the jdklog has no performance loss.
  - A lightweight, high performance, open source, application layer log service framework.
Although the performance is lower than log4j2(It didn't use lock-free queue,such as ring buffer), but the advantage is  no dependency lib, only need openjdk. 
After jmh benchmark,the performance of log4j2 is higher than that of jdklog, but less than an order of magnitude(Even lower).
Log4j2 performance is poor when output location information, the jdklog has no performance loss.

- 推荐理由：
  - High annotation rate.
  - Interface(api) and Iimplementation(core).
  - CheckStyle and CodeStyle.
  - Code specification and Light weight.
  - A lot of features need to be optimized.
  - Amateur projects,LTS(Long term support).

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by jdklog** [comment]
你好,我看过 推荐项目审核标准 #271。
但是没有发现哪里不符合.

是在线文档问题吗?
Online document: https://www.jdklog.org
麻烦给一些提示哦,非常感谢.
