### ISSUE TITLE
C++结构体与json/xml/bson互转

### ISSUE THREAD

**Issue by xyz347** [521xueweihan/HelloGitHub#1781]
## 项目推荐
- 项目地址：https://github.com/xyz347/xpack

- 类别：C++

- 项目后续更新计划：相对比较完备了，会根据大家的issue进行更新支持

- 项目描述：
  - 用来将C++结构体和json/xml/bson互转
  - 适用于需要使用json/xml的C++代码，初学者可以学到一些比较高阶的宏技巧和C++一些初级的SFINAE写法
  - 使用简单，在结构体里面包含一个宏即可

- 推荐理由：可能是目前最好用的C++结构体和json/xml互转库，且json/xml只有头文件，include即可，无需编译

- 示例代码：
``` C++
#include <iostream>
#include "xpack/json.h" // 包含该头文件

struct User {
    int id;
    std::string name;
    XPACK(O(id, name)); // 添加宏定义XPACK在结构体定义结尾
};

int main(int argc, char *argv[]) {
    User u;
    string data = "{\"id\":12345, \"name\":\"xpack\"}";

    xpack::json::decode(data, u);          // json转结构体
    cout<<u.id<<';'<<u.name<<endl;

    string json = xpack::json::encode(u);  // 结构体转json
    cout<<json<<endl;
    return 0;
}
```

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 64 期](https://hellogithub.com/periodical/volume/64/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
