### ISSUE TITLE
项目推荐：Flutter流畅度优化项目 keframe

### ISSUE THREAD

**Issue by Nayuta403** [521xueweihan/HelloGitHub#1784]
## 项目推荐
- 项目地址：https://github.com/LianjiaTech/keframe

- 类别：Flutter （移动端）

- 项目后续更新计划：目前功能层面已完善，后续做维护和升级优化

- 项目描述：
一个Flutter流畅度优化项目，能**快速且通用**的解决 Flutter 中存在卡顿问题。适用于 复杂列表或者页面切换场景。如果在Flutter开发中遇到了流畅度问题，使用本项目只需简单的对卡顿的页面嵌套优化组件即可解决，在快速滚动场景下或者页面切换的场景下，能到达流畅度翻倍。

- 推荐理由：流畅度是移动端性能中最直观的指标，页面卡顿往往让用户感到不愉快。对于 Flutter 而言，同样存在复杂页面中的卡顿问题。不同场景下有不同的优化方式，但本项目提供一种通用的方案解决流畅度问题。

- 截图：
- 
| 优化前 |  优化后 |
| --- | --- |
| <img src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/4233166557ec4b4da0133fe8a9b17325~tplv-k3u1fbpfcp-watermark.image" alt="优化前" style="zoom:50%;" /> | <img src="https://p9-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/6db4a156eaa14bb8b6acb27549788b63~tplv-k3u1fbpfcp-watermark.image" alt="优化后" style="zoom:50%;" /> |

|                            | 优化前  | 优化后 |
| -------------------------- | ------- | ------ |
| 平均多少帧出现一帧卡顿     | 33.3    | 200    |
| 平均多少帧出现一帧轻微卡顿 | 8.6     | 66.7   |
| 最大耗时                   | 188.0ms | 90.0ms |
| 平均耗时                   | 27.0ms  | 19.4ms |
| 流畅帧占比                 | 40%     | 64.5%  |

**Comment by Nayuta403** [comment]
项目收到的开发者 反馈：https://juejin.cn/post/6984606303641403406

**Comment by 521xueweihan** [comment]
@Nayuta403 我们现在没有移动端和 Flutter 这两个分类，🤔 不知道放到那个分类～

**Comment by Nayuta403** [comment]
￣□￣｜｜ 额 ，那只有其他分类了
