### ISSUE TITLE
项目推荐 | DataEase 开源数据可视化分析工具

### ISSUE THREAD

**Issue by maninhill** [521xueweihan/HelloGitHub#1785]
## 项目推荐
- 项目地址：https://github.com/dataease/dataease

- 类别：Java

- 项目后续更新计划：按月发布版本

- 项目描述：DataEase 是开源的数据可视化分析工具，支持丰富的数据源连接，能够通过拖拉拽方式快速制作图表，并可以方便的与他人分享。

- 推荐理由：DataEase 帮助用户快速分析数据、理解数据并洞察业务趋势；打造类似 Tableau 的免费开源产品。

- 截图：

![image](https://user-images.githubusercontent.com/41712985/124047330-922e3600-da46-11eb-9e53-af21662aa8ea.png)
![image](https://user-images.githubusercontent.com/41712985/124047339-98241700-da46-11eb-8154-6c15aec851bb.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 64 期](https://hellogithub.com/periodical/volume/64/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
