### ISSUE TITLE
自荐项目 - Reate

### ISSUE THREAD

**Issue by mintsweet** [521xueweihan/HelloGitHub#1786]
## 项目推荐
- 项目地址：https://github.com/mintsweet/reate

- 类别：JavaScript

- 项目后续更新计划：
  - 完善中文文档
  - 完善测试用例

- 项目描述：
  - 必写: 一个轻量级的`React`状态管理库
  - 可选: 代码简单易用, 非常适合理解全局状态

- 推荐理由：
  - 解决为了管理一个全局登录用户信息引入大量库的问题
  - 同时也解决 Redux 等状态管理学习曲线陡峭
  - 简单易用, 只有三个API, 只有 4kb 的大小, 支持 TS 静态检查, 没有任何依赖

**Comment by 521xueweihan** [comment]
专注于一个问题的项目，我觉得挺好的。

但可能月刊的读者没有感受过你的项目解决的痛点，所以暂不收录到月刊中。
