### ISSUE TITLE
项目自荐：EasySharpFrame

### ISSUE THREAD

**Issue by suxf** [521xueweihan/HelloGitHub#1788]
## 项目自荐
- 项目地址：https://github.com/suxf/EasySharpFrame

- 类别：C#

- 项目后续更新计划：
主要更新优化已经结束，接下来以维护为主，新功能开发为辅。

- 项目描述：
用于快速搭建一个基于.Net平台的服务端，提供HTTP、Websocket、Socket等高级封装网络模块
同时对Sqlserver数据库也有支持，服务器可以在运行中进行热更逻辑等功能。

- 推荐理由：
快速搭建可热更的服务端程序，使用简洁的代码实现更多功能，框架注释很完善，基本上每个函数都会有注释，复杂的函数体内也会有注释解释这样写的意图和逻辑。（自己从来没在任何地方推荐过自己的框架，现如今发现还是要推广一下，第一是为了更好的帮助框架进步，第二是也能给他人学习使用提供微小的帮助^_^）

- 示例代码：
工程主页有详细的主要功能代码示例。

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
