### ISSUE TITLE
项目自荐！ HelloGitHub最帅！

### ISSUE THREAD

**Issue by shaoxiongdu** [521xueweihan/HelloGitHub#1789]
## 项目推荐
- 项目地址：https://github.com/shaoxiongdu/JVMStudy
- 类别：Java

- 项目后续更新计划：持续更新

- 项目描述：
  -JVM底层原理解析及面试知识整理
  - 学到JVM底层的运行知识，包括类加载系统，运行时数据区，垃圾回收机制，执行引擎等知识。
 
- 推荐理由：详细的图示，完整的Readme文件 

- 截图：![](https://gitee.com/ShaoxiongDu/imageBed/raw/master/20210705111505.png)
- ![](https://gitee.com/ShaoxiongDu/imageBed/raw/master/20210705111528.png)
- 
![image](https://user-images.githubusercontent.com/73691342/124413039-68487c80-dd82-11eb-9513-7011b731eff7.png)

**Comment by 521xueweihan** [comment]
感谢您的喜爱和支持。

月刊已推荐过类似的项目，所以您的项目不能收录到月刊中，望理解～

**Comment by shaoxiongdu** [comment]
好的 感谢
