### ISSUE TITLE
X-BUILD

### ISSUE THREAD

**Issue by codexu** [521xueweihan/HelloGitHub#1791]
## 项目推荐
- 项目地址：https://github.com/code-device/x-build
- 文档地址：https://code-device.github.io/x-build/

- 类别：JS / TS

- 项目后续更新计划：
曾经在HelloGitHub发布过 5.x 版本，此次推荐 6.x 版本，最大的变化是基于 vue3 开发，目前处于 Beta 状态，持续测试，完善并修复 bug。

- 项目描述：
X-BUILD 是一个基于 vue3 + typescript 搭建的前端脚手架，不同于众多的中后台解决方案（ant-design-pro、vue-element-admin、d2-admin 等）。它的宗旨是快速创建一套纯净却具备强大基础功能的模板，协助开发者自由发挥快速搭建任何类型的项目。

- 推荐理由：基于 vue3 + typescript 的前端脚手架

**Comment by 521xueweihan** [comment]
已收录过的项目，不做重复收录哈
