### ISSUE TITLE
自荐项目 - password-converter

### ISSUE THREAD

**Issue by Longhao-Chen** [521xueweihan/HelloGitHub#1793]
## 项目推荐
- 项目地址：https://github.com/Longhao-Chen/password-converter

- 类别：JavaScript

- 项目后续更新计划：改进界面，进一步提高使用舒适度。

- 项目描述：通过散列算法来解决密码记忆和安全性之间的矛盾 ，缓解因密码过多记不住密码和无法安全设置密码的问题。

- 推荐理由：很多网站或程序都需要一个账号，而每一个账号都需要一个密码。如果保持所有账号的密码都一致或使用同一种模式，那么只需要有一个账号的密码发生泄漏就会影响的所有账号的安全；如果每个账号都使用不同密码，这样就会造成记忆的困难。于是就出现了一些密码管理程序，这些程序的核心就是将你的密码保存下来，需要时再显示。但这也会出现一些问题，例如：如果我想在公共计算机上登录我的帐号，这就很不方便了。
这个程序通过散列函数，让我们能够安全的使用有便于记忆的密码来设置不同账号的密码。产生密码所需的信息完全可以记在大脑里，这样就可以很方便的在任意的设备上登录你的帐号而不用担心密码泄露的问题。

- 示例代码：https://longhao-chen.github.io/password-converter/

**Comment by 521xueweihan** [comment]
暂不能收到月刊
