### ISSUE TITLE
自荐项目: grape-layout

### ISSUE THREAD

**Issue by cqh963852** [521xueweihan/HelloGitHub#1794]
## 项目推荐
- 项目地址：https://github.com/idealjs/layout-manager
- 在线demo: https://codesandbox.io/s/grape-layout-example-z9ktt
- 类别：JS React 组件

- 项目后续更新计划：添加开发者自定义样式接口。

- 项目描述：
  这是一个单页面的模拟多窗口组件，可以将弹出窗口，或者返回。
  适用于基于网页的编辑器开发，或者有多窗口需求的场景。
  初学者可以学到如何在组件间通信（弹出，返回需要通信）。

- 推荐理由：一个有意思的多窗口解决方案。

- 示例代码：
```
function App() {
    return (
        <div className="App" style={{ height: "100vh", width: "100vw" }}>
            <GrapeLayout factory={factory} layout={ROOT} />
        </div>
    );
}
```

- 截图：![image](https://user-images.githubusercontent.com/17702287/124540699-90071580-de52-11eb-9bf7-63a97d9b10b5.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
