### ISSUE TITLE
项目自荐 | 一款入门级的人脸识别、视频人脸识别、图片分类, 性别检测, 年龄检测, 照片特效处理实战项目

### ISSUE THREAD

**Issue by ZhangLe1993** [521xueweihan/HelloGitHub#1795]
## 项目推荐
- 项目地址：https://github.com/ZhangLe1993/face-ai

- 类别：Java

- 项目后续更新计划：后续将视情况更新一些新的滤镜或者特效

- 项目描述： 一款入门级的人脸识别、视频人脸识别、图片分类, 性别检测, 年龄检测, 照片特效处理实战项目

- 推荐理由：JAVA 相关的音视频与图像处理教程相对于python与C++来说很少, 或者没有系列教程整理, 初学者或者Java 爱好者可以通过本教程掌握基本的图像处理, 并在学习的过程中掌握一些常用的概念.

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
