### ISSUE TITLE
自荐项目 | Rubick-媲美utools的开源工具箱，自由集成丰富插件，utools生态插件微改动即可无差异化使用。

### ISSUE THREAD

**Issue by muwoo** [521xueweihan/HelloGitHub#1796]
## 项目推荐
- 项目地址：https://github.com/clouDr-f2e/rubick

- 类别：JS

- 项目后续更新计划：https://github.com/clouDr-f2e/rubick/projects/1?add_cards_query=is%3Aopen
  - 支持 window、Linux
  - server端部署，支持云端插件发布和下载

- 项目描述：基于 `electron`  开发的媲美 `utools` 的开源插件化工具箱，已实现 `utools` 大部分的 `API` 能力，所以可以做到无缝适配 `utools` 开源的插件。 之所以做这个工具箱一方面是 `utools` 本身并未开源，但是公司内部的工具库又无法发布到 `utools` 插件中，所以为了既要享受 `utools` 生态又要有定制化需求，我们自己参考 `utools` 设计，做了 Rubick

- 推荐理由：github上有很多基于 electron 的桌面端应用，但是都是一些小的工具。 uTools 很强大，可以插件化支持所有工具，用完即走，扩展性、功能性、易用性极强，但是本身并未开源。Rubick 便是媲美 uTools 的开源版。

- 截图：

![example](https://user-images.githubusercontent.com/21073039/124551459-b930a180-de64-11eb-83af-c630008643f5.gif)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 64 期](https://hellogithub.com/periodical/volume/64/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
