### ISSUE TITLE
项目推荐 | DTM 解决微服务架构下分布式事务的中间件

### ISSUE THREAD

**Issue by yedf2** [521xueweihan/HelloGitHub#1797]
## 项目推荐
- 项目地址：https://github.com/yedf/dtm

- 类别：GO

- 项目后续更新计划：
	client支持更多语言，如nodejs、python、PHP
	逐步添加更细的文档与更多的示例

- 项目描述：
  - 解决微服务架构下事务拆分的中间件。首个可用于生产环境的GO语言分布式事务解决方案。初学者可以通过该项目，学习分布式事务的理论知识，并动手实践。

- 推荐理由：开发者不再担心悬挂、空补偿、幂等各类问题，框架层代为处理
	适用于多语言的微服务架构体系

- 示例代码：
```
  // 具体业务微服务地址
  const qsBusi = "http://localhost:8081/api/busi_saga"
	req := &gin.H{"amount": 30} // 微服务的载荷
	// DtmServer为DTM服务的地址，是一个url
	saga := dtmcli.NewSaga("http://localhost:8080/api/dtmsvr").
		// 添加一个TransOut的子事务，正向操作为url: qsBusi+"/TransOut"， 补偿操作为url: qsBusi+"/TransOutCompensate"
		Add(qsBusi+"/TransOut", qsBusi+"/TransOutCompensate", req).
		// 添加一个TransIn的子事务，正向操作为url: qsBusi+"/TransOut"， 补偿操作为url: qsBusi+"/TransInCompensate"
		Add(qsBusi+"/TransIn", qsBusi+"/TransInCompensate", req)
	// 提交saga事务，dtm会完成所有的子事务/回滚所有的子事务
  err := saga.Submit()
```

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 64 期](https://hellogithub.com/periodical/volume/64/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
