### ISSUE TITLE
62期推荐了一个不太合适的项目

### ISSUE THREAD

**Issue by zhang-anzhi** [521xueweihan/HelloGitHub#1799]
62期的 [JavaScript 项目](https://github.com/521xueweihan/HelloGitHub/blob/master/content/62/HelloGitHub62.md#javascript-%E9%A1%B9%E7%9B%AE) 中有一个项目 [Ink-wash-docs](https://github.com/huangwei9527/Ink-wash-docs) 有一些问题，现将有关原因和证据梳理如下：

## 项目参考/模仿/抄袭其他项目

被模仿项目：[石墨文档](https://shimo.im/welcome)

### 项目名称

水墨文档与石墨文档`

### 界面风格

![](https://raw.githubusercontent.com/521xueweihan/img2/master/hellogithub/62/img/Ink-wash-docs.png)
![image](https://user-images.githubusercontent.com/37402126/124635931-9335ec00-deba-11eb-8485-6f22daddf5db.png)

### 功能

两个项目功能基本相同，如在线文档、协作编辑、团队空间等

## 非原创未说明且误导原创

huangwei9527/Ink-wash-docs#7 中有一些详细说明

![image](https://user-images.githubusercontent.com/37402126/124636361-09d2e980-debb-11eb-855f-3675772e42b0.png)
这句话的意思是作者并不知道有石墨文档这个项目，有类似需求且自己写了一个，强调了**不知晓类似项目**、**原创**两个重点

![image](https://user-images.githubusercontent.com/37402126/124636513-34bd3d80-debb-11eb-8a4c-51fb09892a22.png)
这句话的意思是作者参考别的系统自己实现的，强调了**参考其他项目**

且联系两个项目名称、界面风格和功能，可以判断作者了解 `石墨文档` 项目且参考开发了 `水墨文档`，但是在项目中没有提到任何有关石墨文档项目的的内容和解释

## 我认为该作者参考了其他项目、只字未提参考项目、缺乏作为开发者的良心与底线，这样的项目一点也不有趣，并不适合HelloGithub介绍

**Comment by zhang-anzhi** [comment]
还有一个重要原因是如果有人因为 HelloGithub 的介绍商业部署使用了水墨文档，将会与石墨文档产生纠纷，虽然 HelloGithub 不一定需要承担责任，但是至少会影响口碑

**Comment by Funny-dot** [comment]
> 还有一个重要原因是如果有人因为 HelloGithub 的介绍商业部署使用了水墨文档，将会与石墨文档产生纠纷，虽然 HelloGithub 不一定需要承担责任，但是至少会影响口碑

我觉得你有病

**Comment by darrenliuwei** [comment]
> 还有一个重要原因是如果有人因为 HelloGithub 的介绍商业部署使用了水墨文档，将会与石墨文档产生纠纷，虽然 HelloGithub 不一定需要承担责任，但是至少会影响口碑

石墨文档是开源项目？？？

石墨文档的开源代码在哪里？？？

别告诉我你不知道石墨文档的开源代码在哪里

**Comment by zhang-anzhi** [comment]
> > 还有一个重要原因是如果有人因为 HelloGithub 的介绍商业部署使用了水墨文档，将会与石墨文档产生纠纷，虽然 HelloGithub 不一定需要承担责任，但是至少会影响口碑
> 
> 石墨文档是开源项目？？？
> 
> 石墨文档的开源代码在哪里？？？
> 
> 别告诉我你不知道石墨文档的开源代码在哪里

讨论问题就好好讨论，你的问题是什么意思？石墨文档不是开源项目，是一个彻彻底底商业的软件

**Comment by darrenliuwei** [comment]
> > > 还有一个重要原因是如果有人因为 HelloGithub 的介绍商业部署使用了水墨文档，将会与石墨文档产生纠纷，虽然 HelloGithub 不一定需要承担责任，但是至少会影响口碑
> > 
> > 
> > 石墨文档是开源项目？？？
> > 石墨文档的开源代码在哪里？？？
> > 别告诉我你不知道石墨文档的开源代码在哪里
> 
> 讨论问题就好好讨论，你的问题是什么意思？石墨文档不是开源项目，是一个彻彻底底商业的软件

这里是讨论开源项目！！！

**Comment by zhang-anzhi** [comment]
> > > > 还有一个重要原因是如果有人因为 HelloGithub 的介绍商业部署使用了水墨文档，将会与石墨文档产生纠纷，虽然 HelloGithub 不一定需要承担责任，但是至少会影响口碑
> > > 
> > > 
> > > 石墨文档是开源项目？？？
> > > 石墨文档的开源代码在哪里？？？
> > > 别告诉我你不知道石墨文档的开源代码在哪里
> > 
> > 
> > 讨论问题就好好讨论，你的问题是什么意思？石墨文档不是开源项目，是一个彻彻底底商业的软件
> 
> 这里是讨论开源项目！！！

开源项目也不能侵权其他项目

**Comment by 521xueweihan** [comment]
@darrenliuwei 我把他 ban 掉了，大周末的开开心心的。这事儿不聊了

**Comment by puzzle9** [comment]
`issue` 格式不错 主次分明

**Comment by maxxiewang** [comment]
上面那老哥太逗了，我还想抄Google Docs呢，弄好了我就不用去搬砖了。
