### ISSUE TITLE
推荐一个自己参与的C#开源播放器项目：Dopamine

### ISSUE THREAD

**Issue by PeoLeser** [521xueweihan/HelloGitHub#18]
- Github地址：
[https://github.com/digimezzo/Dopamine](https://github.com/digimezzo/Dopamine)
 - 推荐理由：
基于WPF编写的现代扁平风格轻量级播放器
 - 截图：
![bb98b8368061537e413e6781eb37251b](https://cloud.githubusercontent.com/assets/11793304/24559064/4bdcd530-1678-11e7-8955-97828ef15085.jpg)
![untitled](https://cloud.githubusercontent.com/assets/11793304/24559128/8288521c-1678-11e7-9705-8feab58a49ee.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目 🙏。

如您推荐的项目在《HelloGithub》月刊中推荐，则会注明推荐人。**同时在此 issues 中通知您**。

再次感谢您对《HelloGithub》项目的支持！💪

**Comment by 521xueweihan** [comment]
您好，Dopamine 项目已收录到 [13期](https://github.com/521xueweihan/HelloGitHub/blob/master/13/HelloGitHub13.md#c-项目-1)，再次感谢您的支持，希望以后推荐更多好的项目。
