### ISSUE TITLE
八卦博客

### ISSUE THREAD

**Issue by 8gua-men** [521xueweihan/HelloGitHub#180]
## 项目推荐
- 项目名称：八卦博客

- 项目地址：https://github.com/8gua-blog

- 项目语言：coffeescript

- 项目描述：

八卦博客，是静态博客，也是动态博客。

支持部署到 码云页面 、GITHUB PAGE 、BITBUCKET PAGE 。

与 Jekyll 这类纯静态博客相比，
八卦博客，能直接在浏览器中写作，后台将自动地生成页面、部署，
这极大地方便了日常使用。

- 推荐理由：

界面简洁优雅，写作体验很好。

- 示例代码：

[官网  8GUA.BLOG](https://8gua.blog)
[码云镜像 i8gua.gitee.io](https://8gua.blog)
[GITHUB i8gua.github.io](https://8gua.blog)
[BITBUCKET 8gua.bitbucket.io](https://8gua.bitbucket.io)

- 截图：
![image](https://user-images.githubusercontent.com/35199489/35200967-7fa1d790-ff51-11e7-807d-470abba3ebb3.png)

**Comment by JameJJ** [comment]
感觉可以介绍一下一些技术实现细节

**Comment by 8gua-men** [comment]
@JameJJ https://8gua.blog/-/help/tech
补充了一些技术细节

**Comment by JameJJ** [comment]
@8gua-men 额，我能说链接404了吗
