### ISSUE TITLE
自荐项目 | Milkdown

### ISSUE THREAD

**Issue by Saul-Mirone** [521xueweihan/HelloGitHub#1803]
## 项目推荐
- 项目地址：https://github.com/Saul-Mirone/milkdown

- 类别：JS, TS

- 项目后续更新计划：https://github.com/Saul-Mirone/milkdown/projects/1

- 项目描述：
  - 必写：Milkdown是一个所见即所得的Markdown编辑器，基于prosemirror和remark构建，完全开源，可以运行在浏览器和electron中。类似开源可自由扩展的Typora。
  - 可选：适用于需要混合富文本和Markdown的使用场景，例如需要使用markdown作为存储但需兼顾不熟悉markdown的用户。或喜欢所见即所得的编辑模式的用户。入门开发者可以学习到如何使用prosemirror来开发富文本编辑器，以及如何设计一个针对编辑器的插件系统。

- 推荐理由：不同于其它Markdown编辑器，Milkdown是插件驱动的，因此用户可以根据自己的需要定制编辑器的能力，例如扩展特有的markdown语法，渲染特殊节点，定制主题。

- 示例代码：
```typescript
import { Editor } from '@milkdown/core';
import { commonmark } from '@milkdown/preset-commonmark';

import { history } from '@milkdown/plugin-history';

// import theme
import '@milkdown/theme-nord/lib/theme.css';

new Editor()
  .use(commonmark)
  .use(history)
  .create();
```

- 截图：

官网：
![image](https://user-images.githubusercontent.com/10047788/125184948-5d935900-e254-11eb-9195-a0ac6dacd847.png)

编辑器：
![image](https://user-images.githubusercontent.com/10047788/126858854-290a1711-3603-45e6-a0a2-cd33cd44a9ab.png)

![image](https://user-images.githubusercontent.com/10047788/126858848-36ca3ce8-df1a-4d79-a07e-6b45eb81af8a.png)

**Comment by 521xueweihan** [comment]
您好，由于月刊的篇幅有限，您的项目将于下期发布。

**Comment by Saul-Mirone** [comment]
> 
> 
> 您好，由于月刊的篇幅有限，您的项目将于下期发布。

更新提示一下，现在有中文文档了，您也可以直接放中文文档的链接:

https://saul-mirone.github.io/milkdown/#/zh-hans
