### ISSUE TITLE
自荐项目 | ToastFish

### ISSUE THREAD

**Issue by Uahh** [521xueweihan/HelloGitHub#1804]
## 项目推荐
- 项目地址：https://github.com/Uahh/ToastFish

- 类别：C#

- 项目后续更新计划：即将更新复习功能。

- 项目描述：
    这是一个利用Windows通知栏背单词的软件。可以让你在上班、上课等恶劣环境下安全隐蔽的背单词。曾在6月3日冲上微博热搜前十。

- 推荐理由：适用人群明确——工作不是很忙，但上班又不能明显地干其他事情，于是可以背背单词，提高自己。

- 截图：
![word](https://user-images.githubusercontent.com/40496762/125207138-26a55d80-e2bd-11eb-9ea0-e7fc0ba68835.gif)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 64 期](https://hellogithub.com/periodical/volume/64/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
