### ISSUE TITLE
项目推荐 | 現代化網路應用程序的安全最佳實踐的備忘錄

### ISSUE THREAD

**Issue by mao-shonen** [521xueweihan/HelloGitHub#1805]
## 项目推荐
- 项目地址：https://github.com/OWASP/CheatSheetSeries

- 类别：书籍

- 项目后续更新计划：來自OWASP社群或github上不定期更新

- 项目描述：
這是一個現代化網路應用程序的安全最佳實踐的備忘錄。

- 推荐理由：
比起其他網路上找的答案或github上其他的個人項目更來的完整且容易閱讀，並且許多問題都會詳細的說明問題的成因、解決或緩解方法，甚至提供常見的程式語言範例。
你我的一分一秒都不值得浪費，我認為在資料足夠完整有可靠來源的前提下，可以快速找到你需要的參考資料非常重要，故此推薦。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 64 期](https://hellogithub.com/periodical/volume/64/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
