### ISSUE TITLE
项目推荐 | 网页设计50天50个小项目

### ISSUE THREAD

**Issue by mefengl** [521xueweihan/HelloGitHub#1807]
## 项目推荐
- 项目地址：https://github.com/bradtraversy/50projects50days

- 类别：JS

- 项目描述：
  - 必写：这是个前端入门项目、能用来养成基本的网页设计知识，特点是很有趣。

- 推荐理由：每个小模块都很有新意，比如根据密码强度改变网页背景之类的，可以开拓眼界。

- 截图：
![image](https://user-images.githubusercontent.com/71683364/126036297-dbf39723-6582-4258-9733-f153c066820d.png)
![image](https://user-images.githubusercontent.com/71683364/126036299-cbab66c9-6f0b-4126-9f59-2147cbbda981.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 64 期](https://hellogithub.com/periodical/volume/64/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
