### ISSUE TITLE
自荐项目 | 植物大战僵尸 局域网对战【逆向工程 | 代码注入】

### ISSUE THREAD

**Issue by czs108** [521xueweihan/HelloGitHub#1808]
## 植物大战僵尸局域网对战

- 项目地址：https://github.com/czs108/Plants-vs.-Zombies-Online-Battle

- 类别：C++

- 项目后续更新计划：BUG修复

- 项目描述：

  通过逆向工程和代码注入，在没有游戏源代码的前提下，使用C++和内联汇编为植物大战僵尸添加局域网对战模式
  
  Mod成功加载后，解密模式的最后一关会变为网络对战关卡，其中一个玩家放置植物进行防御，另一玩家放置僵尸进攻。

- 推荐理由：

  - 同时结合逆向工程、C++和汇编相关技术，在无源代码的前提下为游戏增加功能
  - 使用最新C++20语法
  - 使用面向对象设计，代码注释完整
  - 基本没有同类项目

- 示例代码：

  ```c++
  __declspec(naked) void CreateZombie(const std::int32_t pos_x,
                                      const std::int32_t pos_y,
                                      const std::int32_t id) noexcept {
      __asm {
          pushad
  
          mov     ebx, dword ptr ds : [BASE_ADDR]
          test    ebx, ebx
          jz      _end
          mov     ebx, dword ptr ds : [ebx + 0x768]
          test    ebx, ebx
          jz      _end
  
          mov     ecx, dword ptr ds : [ebx + 0x160]
  
          mov     edx, [esp + 32 + 4]
          push    edx
  
          mov     eax, [esp + 32 + 16]
          push    eax
  
          mov     eax, [esp + 32 + 16]
  
          mov     edx, FUNC_CREATE_ZOMBIE_ADDR
          call    edx
  
      _end:
          popad
          ret
      }
  }
  ```

- 截图：

  ![online-battle](https://github.com/czs108/Plants-vs.-Zombies-Online-Battle/raw/main/docs/images/online-battle.gif)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 64 期](https://hellogithub.com/periodical/volume/64/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
