### ISSUE TITLE
项目自荐| Go 实现的延时和优先级队列服务

### ISSUE THREAD

**Issue by git-hulk** [521xueweihan/HelloGitHub#1809]
## 项目推荐
- 项目地址：https://github.com/bitleak/lmstfy

- 类别：Go

- 项目后续更新计划：
   -  支持除 Redis  之外的存储引擎
   - 支持 Web UI 管理队列和任务

- 项目描述：
  - 必写：Go 基于 Redis 实现的延时和优先级队列服务，目前在美图、AfterShip 等多个公司线上使用。
  - 可选：需要处理延时或者优先级任务的场景，纯 Go  实现，设计和实现都很简洁
  
- 推荐理由：纯 Go 实现，支持队列级别的容量横向扩展，设计和实现都很简洁

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
