### ISSUE TITLE
DouZero_For_Happy_DouDiZhu: 将DouZero用于欢乐斗地主实战

### ISSUE THREAD

**Issue by Chasing66** [521xueweihan/HelloGitHub#1810]
## 项目推荐
- 项目地址：https://github.com/tianqiraf/DouZero_For_HappyDouDiZhu

- 类别：Python、机器学习

- 项目后续更新计划：

- 项目描述：
  - 必写：基于快手开发的斗地主AI实现快乐斗地主
  - 可选：python，机器学习
  - 描述长度（不包含示例代码）: DouZero是一个为斗地主设计的强化学习框架。斗地主十分具有挑战性。它包含合作、竞争、非完全信息、庞大的状态空间。斗地主也有非常大的动作空间，并且每一步合法的牌型会非常不一样

- 推荐理由：是一个小白也能上手体验的AI项目

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

## 提示（提交时请删除以下内容）
> 点击上方 “Preview” 更方便地阅读以下内容，

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！

**Comment by Chasing66** [comment]
Try AI closely from DouZero

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 64 期](https://hellogithub.com/periodical/volume/64/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
