### ISSUE TITLE
项目自荐：基于 Rust + Vite 构建 WebAssembly 应用

### ISSUE THREAD

**Issue by lencx** [521xueweihan/HelloGitHub#1811]
## 项目推荐

- 项目地址：https://github.com/lencx/vite-plugin-rsw

- 类别：JavaScript, Rust, WebAssembly

- 项目描述：
  - 必写：一个 Vite 插件，可以使初学者快速上手 web 中的 webAssembly 开发
  - 描述：🦀 wasm-pack plugin for Vite

- 推荐理由：使用 rust 开发 webAssembly，需要借助 wasm-pack 来进行构建生成 npm 包，然后手动进行依赖。如果 rust 代码变更，每次都需要重复以上步骤，插件解决了构建以及依赖安装的问题，支持热更新并且有友好的错误提示。 

- 示例代码：

```js
// vite.config.ts
import { defineConfig } from 'vite';
import ViteRsw from 'vite-plugin-rsw';

export default defineConfig({
  plugins: [
    ViteRsw({
      crates: [
        '@rsw/hey', // npm package (org)
        'rsw-test', // npm package
      ],
    }),
  ],
});
```

- 截图：

![image](https://user-images.githubusercontent.com/16164244/126252896-a20bf20b-1926-46a1-a222-2117ec05c4c8.png)

![image](https://user-images.githubusercontent.com/16164244/126253005-1463440f-c88d-4979-a365-c1823eb796e9.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
