### ISSUE TITLE
👋开源项目：Agora Flat 开源教室

### ISSUE THREAD

**Issue by Leooeloel** [521xueweihan/HelloGitHub#1815]
**项目地址**

- [Flat 官网](https://flat.whiteboard.agora.io/) 
- [GitHub 前端](https://github.com/netless-io/flat)
- [GitHub 后端](https://github.com/netless-io/flat-server)
- [快速体验 Flat Web](https://flat-web.whiteboard.agora.io)

**技术栈**

- 前端：TypeScript、React、Mobx、[Storybook](https://netless-io.github.io/flat/storybook)、Electron、yarn workspace
- 后端：TypeScript、Fastify、TypeORM、MySQL、Redis

**后续更新计划**

- [Flat 公开 Roadmap](https://github.com/netless-io/flat/projects/1) 
- 另外，我们有一个**插件计划**正在进行中，围绕使用场景来开发或集成一些实用的白板插件，比如 VS Code 代码编辑器（在线代码面试）、钢琴插件（在线学钢琴）、五子棋等趣味小游戏（在线娱乐）......这样的话开发者可以更方便的参与我们的项目，同时 Flat 也会更加实用和有趣。

**项目描述**

Flat 项目是一个前后端代码完全开源的在线互动教室。未来的目标是成为在线教育领域的 Wordpress，有点像**开源的在线教室生成器**。

**解决痛点**

- 在线互动教室是一个通用性比较强、标准化的产品，然而每个在线教育公司都想拥有一款自己的在线教室用来开展业务，**由于公司间存在信息壁垒，无法在工程上进行经验复用，导致重复造轮子，为此通常需要经过较长的研发周期、踩到各种各样的坑**；有了 Flat，他们就不需要投入过多的时间去搭建在线教室基础框架，只需要在 Flat 开源代码的基础上修改主题、logo 等简单的配置来生成符合自己要求的在线教室。能够大大节省公司的研发成本与时间成本，提高在线教育整个行业的研发效率。

- 个人教师通常需要一款产品来给自己所带的三五个学生进行在线辅导或授课，但是他们不像在线教育公司的老师有现成的工具，通常会去用一些免费的会议型产品，比如腾讯会议、ZOOM，但是**这类产品无法很好的满足教育场景的需求，比如对多人白板互动的需求、录制回放的需求、趣味课堂游戏的需求等等**。而 Flat 天生就是为在线教育而生，在这方面可以很好的满足需求。Flat 针对个人用户提供可以直接使用的 APP，支持 Web 端、桌面端、移动端。考虑到 iPad 是个人用户重度使用场所，未来还会支持 iPad。

**适用于什么场景、可以帮助到哪些人**
 
- **企业用户**可以参考或基于我们的代码快速生成自己的在线教室；
- **个人用户**，比如个人教师可以直接免费使用我们打包好的产品给自己的学生在线讲课和辅导；
- 有意愿接触或学习 Web RTC音视频技术、互动白板原理、实时消息通信技术的**个人开发者**也可以参考学习我们的代码。

**效果图**

![效果图](https://user-images.githubusercontent.com/29906716/126454829-a28ee85e-6880-46a9-a756-489b4fc4d9e0.png)

![效果图](https://user-images.githubusercontent.com/29906716/126454547-32b5be27-8226-4fe2-8fe6-dd161fa6f022.png)

![效果图](https://user-images.githubusercontent.com/29906716/126449093-90261977-ea66-4eab-8bc2-3a91f2a64656.png)

**Comment by 521xueweihan** [comment]
由于月刊的篇幅问题，收录项目有限。您的项目将于下期推荐

**Comment by Leooeloel** [comment]
> 由于月刊的篇幅问题，收录项目有限。您的项目将于下期推荐

好的
