### ISSUE TITLE
项目自荐 | GoGoCode，JS 代码 AST 转换工具，已经支持 vue2 转换成 vue3

### ISSUE THREAD

**Issue by bigfengyu** [521xueweihan/HelloGitHub#1816]
## 项目推荐

- 项目地址：https://github.com/thx/gogocode
- 官网：https://gogocode.io Playground：https://play.gogocode.io 当前 1600+ star

- 类别：JavaScript,AST

- 项目描述 & 推荐理由：这是一款简化 JavaScript AST 处理的工具，使用了类似 jQuery 的预发和字符串构建 AST 的思想大大简化了学习成本、降低了开发复杂度，官方团队在此基础上开发了 vue2 转 vue3 的插件 https://gogocode.io/zh/docs/vue/vue2-to-vue3 和 vscode 转换插件

- 示例：

Vue2 转 Vue3：

![image](https://user-images.githubusercontent.com/9885968/126728751-1486ce14-87b0-4d4a-94c9-ee968303da19.png)

VSCode 插件：

![image](https://user-images.githubusercontent.com/9885968/126728699-228fdc3f-6974-4d63-9a49-879991f614e1.png)

官网：

![image](https://user-images.githubusercontent.com/9885968/117531910-75ade880-b017-11eb-96c7-43fa9cd44b9e.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 64 期](https://hellogithub.com/periodical/volume/64/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
