### ISSUE TITLE
项目推荐 | 开源GPS自行车码表 X-TRACK

### ISSUE THREAD

**Issue by SekiBetu** [521xueweihan/HelloGitHub#1817]
## 项目推荐
- 项目地址：https://github.com/FASTSHIFT/X-TRACK

- 类别：C

- 项目后续更新计划：不清楚

- 项目描述：
  - 拥有可显示实时位置的离线地图。

  - 支持记录和显示实时轨迹以及导出标准GPX格式的轨迹文件。

  - 全新设计的"页面生命周期管理"和"消息订阅发布框架"。

- 推荐理由：开源GPS自行车码表，功能繁多，UI完善美观，达到公司产品级别的难以置信

- 截图：
![image](https://user-images.githubusercontent.com/38283893/126784526-ca40d1f1-5a3f-4440-b2d8-0dbc6af63ff4.png)

- 演示视频：
https://www.bilibili.com/video/BV1GB4y1K7VV

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 64 期](https://hellogithub.com/periodical/volume/64/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
