### ISSUE TITLE
libuhttpd - 一个非常灵活的,轻量的,全异步的HTTP服务器C库

### ISSUE THREAD

**Issue by zhaojh329** [521xueweihan/HelloGitHub#1819]
[libev]: http://software.schmorp.de/pkg/libev.html
[http-parser]: https://github.com/nodejs/http-parser
## 项目推荐
- 项目地址：https://github.com/zhaojh329/libuhttpd

- 类别：C

- 项目后续更新计划：绑定 Lua 语言

- 项目描述：
  - 一个非常灵活的,轻量的,全异步的HTTP服务器C库，基于[libev]和[http-parser]实现，主要用于嵌入式Linux。

- 推荐理由：
  - 轻量、全异步
  - 使用[libev]作为其事件后端
  - 支持HTTPS - OpenSSL, mbedtls 和 CyaSSl(wolfssl)
  - 支持 HTTP 流水线
  - 支持 IPv6
  - 支持插件
  - 支持上传大文件
  - 支持 HTTP 范围请求
  - 支持多进程模型 - 和 Nginx 一样的多进程模型
  - 可伸缩 - 你可以非常方便的扩展你的应用程序，使之具备HTTP/HTTPS服务
  - 代码结构简洁通俗易懂，亦适合学习

### Nginx

	$ wrk -t4 -c400 -d10s http://localhost:80/test.html
	Running 10s test @ http://localhost:80/test.html
	4 threads and 400 connections
	Thread Stats   Avg      Stdev     Max   +/- Stdev
		Latency     3.54ms    7.32ms 224.58ms   93.30%
		Req/Sec    40.63k    12.49k   96.29k    74.50%
	1622012 requests in 10.05s, 385.09MB read
	Requests/sec: 161390.39
	Transfer/sec:     38.32MB

### libuhttpd

	$ wrk -t4 -c400 -d10s http://localhost:8080/test.html
	Running 10s test @ http://localhost:8080/test.html
	4 threads and 400 connections
	Thread Stats   Avg      Stdev     Max   +/- Stdev
		Latency     2.12ms    3.01ms  31.30ms   89.26%
		Req/Sec    70.87k    12.53k  142.54k    79.75%
	2826394 requests in 10.05s, 547.18MB read
	Requests/sec: 281328.83
	Transfer/sec:     54.46MB

**Comment by 521xueweihan** [comment]
由于月刊篇幅问题，您的项目暂不收录了。

但您可以给 HelloGitHub 投稿单篇的文章。但如果感兴趣的话，可以通过文章做一篇 C 语言实现异步 HTTP 服务的文章。

注意：文章需要原创、未发布、不可大段复制文档，仅支持 Markdown 排版用心
