### ISSUE TITLE
自荐项目 | silky

### ISSUE THREAD

**Issue by liuhll** [521xueweihan/HelloGitHub#1820]
## 项目推荐
- 项目地址：https://github.com/liuhll/silky

- 类别：C#

- 项目后续更新计划：
   * 优化分布式事务,通过定时作业和undolog检查事务完整性
   * 新增身份认证与授权中间件
   * 新增服务管理端(Dashboard)
   * 新增模板项目和CLI命令行行工具
   * 完善示例
   

- 项目描述：
  * 通过.net框架的通用主机构建业务微服务应用,内部通过dotnetty/SpanNetty实现的rpc进行通信,在消息传递过程中,通过rpcToken保证消息在同一个集群内部进行通信，而且rpc通信支持ssl加密。使用Zookeeper作为服务注册中心。
  * 通过.net的web主机构建对外提供访问入口的服务主机(网关)，在http请求或是ws会话请求到达该主机时,通过内置的中间件解析到服务集群的路由条目,并指定rpcToken,通过内置的负载均衡算法和路由寻址与集群内部的主机进行rpc通信。
 * Silky在通信过程中,使用基于拦截器实现了TCC分布式事务。

- 推荐理由：Silky是一个旨在帮助开发者在.net平台下,通过简单代码和配置快速构建一个微服务开发框架。具有安全、稳定、高性能、易扩展、使用方便的特点。

- 示例代码：
```csharp
   public class Program
    {
        public static async Task Main(string[] args)
        {
            await CreateHostBuilder(args).Build().RunAsync();
        }

        private static IHostBuilder CreateHostBuilder(string[] args)
        {
            return Host.CreateDefaultBuilder(args)
                    .RegisterSilkyServices<NormHostDemoModule>()
                ;
        }
    }

/// NormHostDemoModule

[DependsOn(typeof(MessagePackModule), typeof(SilkySkyApmAgentModule))]
    public class NormHostDemoModule : GeneralHostModule
    {
        public override void ConfigureServices(IServiceCollection services, IConfiguration configuration)
        {
            services.AddDatabaseAccessor(options => { options.AddDbPool<DemoDbContext>(); }, "NormHostDemo");
        }
    }
```

- 截图：
  * swagger 文档
   ![image](https://user-images.githubusercontent.com/16488441/126922549-8bb17f3a-8367-43ce-90dd-8eb3cf77a240.png)

  * 请求网络拓扑图
    ![image](https://user-images.githubusercontent.com/16488441/127141356-4fd9ffa3-8e6b-451d-840c-aad506b3926e.png)

  * 链路跟踪
   ![image](https://user-images.githubusercontent.com/16488441/126922830-fcc2ba5c-9821-418d-a44a-58ee3267fee2.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
