### ISSUE TITLE
JMS - .net core集成分布式事务的微服务开发框架

### ISSUE THREAD

**Issue by simpleway2016** [521xueweihan/HelloGitHub#1822]
## 项目推荐
- 项目地址：https://github.com/simpleway2016/JMS

- 类别：C#

- 项目后续更新计划：

- 项目描述：
分布式事务的控制一直是微服务写起来比较麻烦的地方，JMS微服务开发框架实现了0代码支持分布式事务。
视频教程：https://www.bilibili.com/video/BV1zU4y1578Y/

- 推荐理由：
1、支持分布式事务控制（强一致性和非强一致性）；
2、支持分布式事务锁；
3、网关支持双机热备；
4、支持配置文件统一在网关部署、更新；
5、支持SSL双向校验；
6、可自定义定时任务；
7、负载均衡根据微服务的CPU使用率和当前请求数进行平均分配，也可自己编写负载均衡规则；

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
