### ISSUE TITLE
Python client for Baidu Yun (Personal Cloud Storage) 百度云/百度网盘Python客户端

### ISSUE THREAD

**Issue by Chasing66** [521xueweihan/HelloGitHub#1824]
## 项目推荐
- 项目地址：https://github.com/houtianze/bypy

- 类别：python

- 项目描述：
百度网盘 Python 客户端 是一款使用百度网盘官方 API，可以在 Python 环境下实现上传、下载、同步等操作，非破解非魔改，主要用途是在 Linux 环境下使用百度网盘，比如 Raspberry Pi 树莓派，仅可读取 /apps/bypy 路径下的文件。

- 推荐理由：Linux 端的基于百度网盘官方API的客户端

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

## 提示（提交时请删除以下内容）
> 点击上方 “Preview” 更方便地阅读以下内容，

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
因篇幅有限，该项目暂不收录到月刊中。
