### ISSUE TITLE
推荐项目-filament

### ISSUE THREAD

**Issue by kirinzer** [521xueweihan/HelloGitHub#1826]
## 项目推荐
- 项目地址：https://github.com/google/filament

- 类别：C++

- 项目后续更新计划：

- 项目描述：

  - 是什么？
 这是一个实时物理渲染引擎，能够用来作为一个游戏的渲染引擎，或者音视频编辑工程的渲染引擎。

  - 适用于什么场景？
当你需要处理3d渲染效果，而又不想引入庞大的游戏引擎时，可以考虑使用它。

  - 可能的收货？
另一方面，如果你想要自己开发一个渲染引擎，那么参考借鉴 filament 的渲染处理过程也是很有必要的。
它的跨平台实现，也许可以提供给你提供一些参考，如果你正在考虑迁移自己的渲染框架覆盖全平台。

- 推荐理由：
  - 优点： 
足够轻量的，基于先进的ECS架构。（Unity 也使用了 ECS 架构）
横向对比 OGRE，filament 没有额外的游戏相关逻辑，只专注于3d物理效果渲染。
虽然不是 google 官方支持的产品，但是项目的讨论区非常活跃，维护人员会非常及时的联系你来解决你的困惑，注意时区差异。
  - 缺点：
相对来说，文档的完善度比较欠缺，或许是最初的定位是 Android 平台，因此 Android 的示例会比 iOS 更丰富。
有些接口的调用及说明，要在 Android 的示例源码中才能看到（iOS 平台相关的也在这里！！）。
比较完善的文档，是在介绍如何它是如何进行光照，材质处理的。

- 示例代码：

创建 engine，render，nativeWindow。此时已经准备好了基本的渲染环境。
再添加上默认的 scene，view。以及想要渲染的 material 就可以输出渲染效果了！！
```
Engine* engine = Engine::create();
SwapChain* swapChain = engine->createSwapChain(nativeWindow);
Renderer* renderer = engine->createRenderer();
```

**Comment by ChungZH** [comment]
以后类别要写括号里的语言...注意一下

**Comment by kirinzer** [comment]
> 以后类别要写括号里的语言...注意一下

这 C++ 类别是在模板里有的呀？

**Comment by ChungZH** [comment]
> > 以后类别要写括号里的语言...注意一下
> 
> 这 C++ 类别是在模板里有的呀？

![image](https://user-images.githubusercontent.com/42088872/128680012-8d14a318-9b31-4f37-b863-3956ad7c20ac.png)

**Comment by kirinzer** [comment]
> > > 以后类别要写括号里的语言...注意一下
> > 
> > 
> > 这 C++ 类别是在模板里有的呀？
> 
> ![image](https://user-images.githubusercontent.com/42088872/128680012-8d14a318-9b31-4f37-b863-3956ad7c20ac.png)

我就是从这里选取的，复制粘贴出来的，刚刚用字符串比较工具看了一下，是一致的。所以你这里说的要注意的点是什么？

**Comment by ChungZH** [comment]
![image](https://user-images.githubusercontent.com/42088872/128684658-25fad004-8d9d-4048-9517-1448a2fb3f06.png)

我帮你改过了，谢谢

**Comment by ChungZH** [comment]
你这个复制粘贴还挺牛的（

**Comment by kirinzer** [comment]
> ![image](https://user-images.githubusercontent.com/42088872/128684658-25fad004-8d9d-4048-9517-1448a2fb3f06.png)
> 
> 我帮你改过了，谢谢

啊不好意思，时间有点久了。但是这个作为一个跨端项目，其实代码本身是包含有多种语言的，因此使用 C++ 可能也不是特别准确呢（还包含 java，oc 等端侧语言），所以才会有这个“自定分类”出现。

**Comment by ChungZH** [comment]
我们发的时候是按这些分类来的，如果新加的话会混乱。而且 C++ 在这个项目里面是毫无疑问的主要语言。
