### ISSUE TITLE
English-Grammar-Basic

### ISSUE THREAD

**Issue by PageSecOnd** [521xueweihan/HelloGitHub#1829]
## 项目推荐
- 项目地址：https://github.com/PageSecOnd/English-Grammar-Basic

- 类别：书籍

- 项目后续更新计划：添加中级和高级教材

- 项目描述：
  - 必写：这是一个英语语法学习项目，在更新中，可以轻松地学习英语语法知识
  - 可选：适用于英语初学者学习基础语法

- 推荐理由：包含初级，中级，高级语法教材    解决了英语初学者的语法学习问题

- 截图：![image](https://img.ams1.imgbed.xyz/2021/08/05/2sQ6p.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
