### ISSUE TITLE
python实现苏州公交实时查询

### ISSUE THREAD

**Issue by duhaipeng** [521xueweihan/HelloGitHub#183]
## 项目推荐
- 项目名称：python实现苏州公交实时查询

- 项目地址：https://github.com/duhaipeng/python/tree/master/suzhou_bus   

- 项目语言：python

- 项目描述：实时查询苏州近4000辆公交的到站信息，显示车牌信息，具体时间，表格化输出

- 推荐理由：看到前几期有个类似的北京公交查询，哈哈，真的是想到一块去了，其实还能添加更多有趣好用的功能

- 示例代码：
def get_html2(url,urllist):
    line=raw_input('输入车次序号查看实时车辆：'.decode("utf-8").encode("gb2312")).decode(sys.stdin.encoding )
    req = urllib2.Request(url=url,headers={'Accept-Encoding': 'gzip, deflate',})
    if int(line)<len(urllist):
        req = urllib2.Request(url=url,data = urllist[int(line)],headers={'Accept-Encoding': 'gzip, deflate',})
        res = urllib2.urlopen(req)
        html = res.read()
        if res.info().get('Content-Encoding') == 'gzip':
            buf = StringIO(html)
            f = gzip.GzipFile(fileobj=buf)
            html = f.read().decode('utf-8')
            html = html[1:]
            data = json.loads(html)
            return data['data']

- 截图：
http://p2v7iejhm.bkt.clouddn.com/%E6%8D%95%E8%8E%B71.PNG
http://p2v7iejhm.bkt.clouddn.com/%E6%8D%95%E8%8E%B7.PNG

**Comment by 521xueweihan** [comment]
@duhaipeng 建议提交PR到 [beijing_bus](https://github.com/wong2/beijing_bus)，或者做一个全国公交查询 SDK 👍
