### ISSUE TITLE
推荐一个 awesome-nodejs

### ISSUE THREAD

**Issue by huaize2020** [521xueweihan/HelloGitHub#1830]
## 项目推荐
- 项目地址：https://github.com/huaize2020/awesome-nodejs

- 类别：请从中选择（JS、NodeJS）

- 项目描述：
  - 必写：这是个什么项目、能用来干什么、有什么特点或解决了什么痛点
        之前对Node.js进阶路径很迷茫，熟悉了koa/express/egg/nest这些web框架是不是就可以了，熟悉了构建工具链是不是就可以了，还需要熟悉什么？没有项目没法成长怎么办？

       这些疑问一直伴随学习的过程中，后面我发现了一个技巧，就是把node资源进行分类体系化整理，只需要短短几个月，每天几个库每天几个库，就能收集一个基础的体系。最后成就了这个仓库。
     
       当前端/NodeJS工程师需要一个类别库的时候，可以在这个库中去索引，通过类型扩展思维 以及 各种库对比 快速找到自己想要的库。且该库已经在aweome-nodejs中文中排到前列。

- 项目后续更新计划：
   - 短期内：持续的更新，平均每天至少更新一个库
   - 随着时间的增长，库的增长会越来越难发现。我会针对每个类别，整理互联网上优质的库对比的文章，以供更好的参考 

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？
   - 第一中文版awesome-nodejs
   - 选库神器

**Comment by huaize2020** [comment]
圈内的朋友写的推文
《这些node开源工具你值得拥有(上) 》https://juejin.cn/post/6972124481053523999
《这些node开源工具你值得拥有(下) 》https://juejin.cn/post/6981249055070355492

**Comment by 521xueweihan** [comment]
您好，首先您做的事情是很有意义的。但同样作为开源项目集合的 HG 不适合推荐 awesome 系列，可以拆分出来适合 HG 的开源项目单独推荐：有趣、入门级。

最后，再次感谢您的项目，以及为开源社区作出的贡献。
