### ISSUE TITLE
推荐 ｜ Astral 管理你的GitHub Stars

### ISSUE THREAD

**Issue by mefengl** [521xueweihan/HelloGitHub#1834]
## 项目推荐
- 项目地址：https://github.com/astralapp/astral

- 类别：其它

- 项目描述：
  - 必写：一图胜千言
  
![image](https://user-images.githubusercontent.com/71683364/128638203-b151a3cf-ff62-4393-8994-b3af8fe13aba.png)

- 推荐理由：

1. 按语言分类功能
2. 标签功能
3. 笔记功能
3. 好看的界面
4. 和GitHub无缝衔接的使用体验

**Comment by ChungZH** [comment]
写一下描述吧，我们不可能只发一张图的
