### ISSUE TITLE
自荐项目|flask-openapi3

### ISSUE THREAD

**Issue by luolingchun** [521xueweihan/HelloGitHub#1835]
## 项目推荐
- 项目地址：https://github.com/luolingchun/flask-openapi3

- 类别：Python

- 项目后续更新计划：添加导出Markdown接口文档功能

- 项目描述：
  flask-openapi3是一个基于Flask的WEB API框架，设计灵感来自于FastAPI，使用pydantic验证数据，自动生成Swagger UI和Redoc两种在线API文档。

- 推荐理由：
  - 更优雅的编写REST API
  - 更简洁的代码
  - Swagger在线文档
  - Redoc在线文档

- 示例代码：
  ```python
  from pydantic import BaseModel

  from flask_openapi3 import OpenAPI
  from flask_openapi3.models import Info, Tag
  
  info = Info(title='book API', version='1.0.0')
  app = OpenAPI(__name__, info=info)
  
  book_tag = Tag(name='book', description='Book')
  
  
  class BookData(BaseModel):
      age: int
      author: str
  
  
  @app.get('/book', tags=[book_tag])
  def get_book(query: BookData):
      """get books
      get all books
      """
      return {
          "code": 0,
          "message": "ok",
          "data": [
              {"bid": 1, "age": query.age, "author": query.author},
              {"bid": 2, "age": query.age, "author": query.author}
          ]
      }


  if __name__ == '__main__':
      app.run(debug=True)

  ```

- 截图
  ![swagger](https://github.com/luolingchun/flask-openapi3/raw/master/docs/images/openapi-swagger.png)
  ![redoc](https://github.com/luolingchun/flask-openapi3/raw/master/docs/images/openapi-redoc.png)

**Comment by 521xueweihan** [comment]
非常好的项目，但使用受众有些局限，所以暂不能收录到月刊中。

感谢您的项目，以及为开源社区做的贡献。
