### ISSUE TITLE
项目推荐 ：micro-app 微前端框架

### ISSUE THREAD

**Issue by bailicangdu** [521xueweihan/HelloGitHub#1836]
## 项目推荐
- 项目地址：https://github.com/micro-zoe/micro-app

- 类别：JavaScript

- 官网：https://zeroing.jd.com/micro-app

- 项目描述：
micro-app是京东零售推出的一款微前端框架，它基于类WebComponent进行渲染，从组件化的思维实现微前端，旨在降低上手难度、提升工作效率。它是目前接入微前端成本最低的框架，并且提供了JS沙箱、样式隔离、元素隔离、预加载、资源地址补全、插件系统、数据通信等一系列完善的功能。

- 推荐理由：
micro-app摒弃了以拦截路由进行微前端渲染的主流方式，从WebComponent的思想渲染微前端，从而简化渲染步骤，降低上手难度，是目前实现微前端最简单的框架。

- 示例代码：
```html
<template>
  <div>
    <h1>子应用</h1>
    <!-- name为应用名称，全局唯一，url为html地址 -->
    <micro-app name='app1' url='http://localhost:3000/' baseurl='/my-page'></micro-app>
  </div>
</template>
```

- 效果截图：
![image](https://img12.360buyimg.com/imagetools/jfs/t1/196940/34/1541/38365/610a14fcE46c21374/c321b9f8fa50a8fc.png)

- 官网：
[![](https://img13.360buyimg.com/imagetools/jfs/t1/195690/22/17587/232997/61126492E9d2de3fb/6954b83ba068a756.png)](https://zeroing.jd.com/micro-app)

**Comment by 521xueweihan** [comment]
@bailicangdu  您好，由于篇幅有限，您推荐的项目暂不能收录到月刊中。
