### ISSUE TITLE
Go Blog 一个基于Beego开发的社交商城博客系统

### ISSUE THREAD

**Issue by 1920853199** [521xueweihan/HelloGitHub#1837]
## 项目推荐
- 项目地址：https://github.com/1920853199/go-blog

- 类别：Go

- 项目后续更新计划：
![image](https://user-images.githubusercontent.com/28426364/129146766-e0e3659d-34c6-4750-a164-a9a6d454076e.png)

- 项目描述：
  - 必写：能快速搭建个人博客，cms或者社区,持续更新商城部分内容
  - 
- 推荐理由：学习Golang语言一个比较好的选择，没有花里胡哨的前端技术门槛，搭建个人博客兴趣平台简单快速方便

- 截图：（可选）gif/png/jpg
![image](https://user-images.githubusercontent.com/28426364/129147102-00a1cec4-06a6-4899-8b19-85e562b731ee.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
