### ISSUE TITLE
novel-plus

### ISSUE THREAD

**Issue by BenWyy** [521xueweihan/HelloGitHub#1838]
## 项目推荐
- 项目地址：https://github.com/201206030/novel-plus

- 类别：Java、其它

- 项目后续更新计划：

- 项目描述：
  - 必写：小说精品屋-plus是在小说精品屋的基础上，去除了漫画和弹幕模块，专注于小说，是一个多端（PC、WAP）阅读、功能完善的原创文学CMS系统，由前台门户系统、作家后台管理系统、平台后台管理系统、爬虫管理系统等多个子系统构成，支持会员充值、订阅模式、新闻发布和实时统计报表等功能。
  - 可选：提供给初学者学习，同时支持 Web、安卓、微信小程序多平台。
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：一个基于 SpringBoot 实现的小说和漫画在线阅读网站。网站功能齐全、资源丰富，同时支持 Web、安卓、微信小程序多平台。服务端分为网站和管理后台，采用 SpringBoot、MyBatis、MySQL、Redis 等技术实现，可当作 Java 新手实战项目学习

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg
![微信截图_20210812154711](https://user-images.githubusercontent.com/31247377/129158538-36cad5dd-9b49-4639-b190-4aabf636e4a9.png)

**Comment by 521xueweihan** [comment]
推荐过之前的版本了，这个就不收录了。
