### ISSUE TITLE
aLive2D! 一个萌萌哒 Live2D API o(*≧▽≦)ツ 快来向web页面添加可爱的看板娘吧～

### ISSUE THREAD

**Issue by xiarimangguo** [521xueweihan/HelloGitHub#1839]
## 项目推荐
- 项目地址：[aLive2D! 一个萌萌哒 Live2D API o(*≧▽≦)ツ 快来向web页面添加可爱的看板娘吧～](https://github.com/xiarimangguo/aLive2D)

- 类别：js

- 项目后续更新计划：
进一步支持点击按钮切换模型功能

- 项目描述：
  - aLive2D! 一个萌萌哒 Live2D API o(*≧▽≦)ツ 快来向web页面添加可爱的看板娘吧～
  - 如果你想为你的网页添加一只萌萌哒Live2D的话，快来使用这款萌萌哒Live2D API吧

- 推荐理由：这个项目可以向web页面添加萌萌哒Live2D看板娘，可以用两句代码轻松为网页引入Live2D模型，并且整理了70+开箱即用的Live2D模型，解决了到处找模型的苦恼
    * 实现 **全自动** 加载模型
    * **无须** 手动引入一连串的js文件
    * **无须** 手动添加canvas标签
    * **无须** 自己编写css样式
    * **解决了** 到处寻找Live2D模型的苦恼
    * **可以** 调整模型在网页上的位置及长宽

- 示例代码：
```
<script src="https://91.90.194.171/api/Live2D"></script>
<script>aLive2D('#02007','240px','400px','Rb','10%','0%',false)</script>
```

- 截图：点我查看效果吧～
[![demo-1](https://user-images.githubusercontent.com/38160007/129200638-4e83d9f9-369c-4e7d-8dac-afa34de2a9a3.png)](https://91.90.194.171/api/Live2D/start/demo.gif)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
