### ISSUE TITLE
💅用Javascript刷Leetcode

### ISSUE THREAD

**Issue by tangweikun** [521xueweihan/HelloGitHub#184]
## 项目推荐
- 项目名称：leetcode

- 项目地址：https://github.com/tangweikun/leetcode

- 项目语言：Javascript【Typescript】

- 项目描述：用Javascript来刷Leetcode

- 推荐理由：
1.使用TDD的方式来解题，让代码更可靠
2.使用Codeclimate来检测代码异味，确保代码质量
3.代码简单，可读性强
4.每道题都有完整的README和Test Case
5.从Easy到Hard，帮助初学者循序渐进练习

- 示例代码：
```javascript
// Time Complexity O(n) [Only a single pass is needed.]
// Space Complexity O(1)  [Only two variables are used.]

export function maxProfit(prices: number[]) {
  let min = Infinity
  let result = 0
  prices.forEach(n => {
    if (n < min) min = n
    else result = Math.max(result, n - min)
  })

  return result
}

```
- 截图：
![jietu20180307-131507 2x](https://user-images.githubusercontent.com/13361639/37074832-a145f8ba-2209-11e8-941b-ce1c20eb4036.jpg)

![image](https://user-images.githubusercontent.com/13361639/35496800-824f19ec-0502-11e8-959a-2b075a572d74.png)

**Comment by 521xueweihan** [comment]
@tangweikun 仅保留父级 awsome leetcode 项目
