### ISSUE TITLE
Changeable-基于pytorch的目标检测数据增强工具包

### ISSUE THREAD

**Issue by yatengLG** [521xueweihan/HelloGitHub#1840]
## 项目推荐
- 项目地址：https://github.com/yatengLG/Changeable

- 类别：Python、机器学习

- 项目后续更新计划：
  后续会持续添加一些其他的数据增强方式。

- 项目描述：
  基于pytorch的目标检测数据增强工具包。用于在深度学习目标检测训练时，对训练数据进行增强，提高模型鲁棒性。
  实现了 **VOC格式数据集** -> **单图数据增强** -> **mosaic图片合成** -> **anchors匹配** -> **训练数据** 的完整数据处理流程。
  * 单图数据增强部分。对图像、标注框、标签同时进行变换，保证了标注框与图片的严格对齐。
  * 数据加载器部分。集成了无限加载、mosaic图片合成、anchors对齐等功能。
  * mosaic图片合成部分。先裁剪后合并的方式，提供了更多的组合可能。（此处mosaic与yolov4 mosaic实现方式有所不同，yolov4采用图片相互覆盖的方式实现mosaic；本项目先随机mosaic中心，然后以一定尺寸裁剪图片，然后组合的方式合成mosaic）
  * anchors分配部分。将anchors通过iou或宽高比的方式，分配给各标注框。实现了不同数量标注框和目标标签的统一，便于后续进行批次训练。
  * 该数据增强工具包，可灵活应用于各类目标检测模型的训练过程。

- 截图：
  |![mosaic4](https://user-images.githubusercontent.com/31759824/129314534-fad796e9-ce14-450d-866d-3d5c98100bbd.png)|![mosaic_with_transform4](https://user-images.githubusercontent.com/31759824/129314741-eed798f3-cd88-4fae-b73b-4470902435a4.png)|
  |----|----|

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
