### ISSUE TITLE
自荐项目: RSA CLI - 基于 Node.js 的命令行非对称加密解密工具

### ISSUE THREAD

**Issue by MrWillCom** [521xueweihan/HelloGitHub#1842]
## 项目推荐
- 项目地址：[MrWillCom/rsa-cli](https://github.com/MrWillCom/rsa-cli)

- 类别：JS

- 项目后续更新计划：完善 API，并且完善配套的 [RSA GUI](https://github.com/MrWillCom/rsa-gui)。

- 项目描述：在命令行用 RSA 算法非对称加密解密的工具。功能齐全，输出简洁，操作简单，上手容易。另外可以作为 Node.js 模块在其它项目中调用。

- 推荐理由：
  - 支持 npm 或 Yarn 安装。
  - Release 中的可执行文件就是完整的程序。
  - 输出简洁，没有废话。
  - 支持导入公/私钥。
  - 生成密钥时，支持自定义密钥长度。
  - 支持 API 调用。
  - 支持密码保护私钥 (算法: AES)

- 示例代码：

```sh
$ rsa generate test
Generated a new key pair: 'test'

$ rsa encrypt test 'Hello, World!'
Encrypted 'Hello, World!' with key 'test':
siuTym3xP/0u0yQHZ+oNBSFC7ha1JxUzjdrfZ7azpOHsLiQpenyPkoney/LF4hiKrrAKVf6PSIubBgD0s4pluRVoN1m/no8QvB55TV64sreVxLIgbZkUPMWrJFHBMjZbtf3Bnl+Araynq0Dk4OM5vjFwdnzsdzOwEDtAkujBFPjMSGD3k69eW9gaoEjlZCybzKVjqkVzULRp6XbtjmrBLMA5ryKV5Fx92ZIvIRQzmeCcBC1isdMDMxT2qe+TaspUU6Xdlos5oGMkpGRo/iMM6MzoNi1SKihTuod9UpXFbpnHOepW5HJkhECMNBhpoPMglXC/vhvvR3SABnpJMtjk5A==

$ rsa decrypt test 'siuTym3xP/0u0yQHZ+oNBSFC7ha1JxUzjdrfZ7azpOHsLiQpenyPkoney/LF4hiKrrAKVf6PSIubBgD0s4pluRVoN1m/no8QvB55TV64sreVxLIgbZkUPMWrJFHBMjZbtf3Bnl+Araynq0Dk4OM5vjFwdnzsdzOwEDtAkujBFPjMSGD3k69eW9gaoEjlZCybzKVjqkVzULRp6XbtjmrBLMA5ryKV5Fx92ZIvIRQzmeCcBC1isdMDMxT2qe+TaspUU6Xdlos5oGMkpGRo/iMM6MzoNi1SKihTuod9UpXFbpnHOepW5HJkhECMNBhpoPMglXC/vhvvR3SABnpJMtjk5A=='
Decrypted 'siuTym3xP/0u...BnpJMtjk5A==' with key 'test':
Hello, World!
```

- 截图：![截图](https://user-images.githubusercontent.com/47271684/129440187-f4bf35e7-32af-46ee-92e2-f33d341da43b.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by MrWillCom** [comment]
你好 @521xueweihan ，非常感谢您审核我的项目。

再次查阅 #271 后，我还是没能了解我项目的问题在哪里，所以您能否给我一些改进建议，这会对我产生很大的帮助，谢谢🙏
