### ISSUE TITLE
自荐项目：纯前端复刻游戏 baba is you

### ISSUE THREAD

**Issue by FlyingFatPenguin** [521xueweihan/HelloGitHub#1846]
## 项目推荐
- 项目地址：https://github.com/FlyingFatPenguin/baba-is-you
- 类别：JS

- 项目描述：
  这是一个复刻经典游戏 baba-is-you 的纯前端项目，里面包含了十个关卡和一个实验性质的地图编辑器。项目使用 TypeScript 和 React 编写。没有额外的库，学习理解的门槛极低。
初学者可以从中学到，一些程序设计思想、TS 对数据类型的精细管理、移动端手势支持以及“简单的技术也可以给我们带来快乐”的理念。当你想做游戏时，随时可以出发。[在线试玩](http://flyingfatpenguin.gitee.io/baba-is-you/)。

- 推荐理由：简单的技术，不简单的规则

- 截图：
![图片](https://user-images.githubusercontent.com/37020201/130364361-9ea3b83f-58ba-4f20-8e12-d47b0c6beda3.png)

**Comment by 521xueweihan** [comment]
@FlyingFatPenguin 
如果感兴趣的话，可以给 HelloGitHub 投稿一篇你用 JS 复刻游戏的心路历程和技术实战。

注意：文章需要原创、未发布、不可大段复制文档，仅支持 Markdown 排版用心
