### ISSUE TITLE
Android 组件化项目 Component

### ISSUE THREAD

**Issue by xiaojinzi123** [521xueweihan/HelloGitHub#1858]
## 项目推荐
- 项目地址：https://github.com/xiaojinzi123/Component

- 类别：Kotlin Java

- 项目后续更新计划：
目前处于稳定版本中. 并且紧跟 Android 最新 Api 的变动

- 项目描述：
  -  Component 是 Android 的一个组件化项目, 帮助开发者在实现项目组件化. 它的强大在于, 现在市面上所有相关的项目. 这个功能是最全的, 并且更新及时. 并且紧跟时代潮流, 支持 RxJava、协程 等

- 推荐理由：功能最全, 对新技术的支持更新最及时. 维护时间超三年

- 截图：
![image](https://user-images.githubusercontent.com/12975743/131220543-802ac28d-70b6-412d-b581-2f7d8bd769ed.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 66 期](https://hellogithub.com/periodical/volume/66/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
