### ISSUE TITLE
DeepLeague:用ml，cv，dl分析LOL

### ISSUE THREAD

**Issue by franklingu** [521xueweihan/HelloGitHub#187]
## 项目推荐
- 项目名称：
DeepLeague
- 项目地址：
https://github.com/farzaa/DeepLeague
- 项目语言：
python
- 项目描述：
DeepLeague - leveraging computer vision and deep learning on the League of Legends mini map + a dataset of over 100,000 labeled images to further A.I research within esports.
- 推荐理由：
1 规模不大
2 研究的是游戏
3 适合读code研究一些cv和ml的算法应用
- 示例代码：

- 截图：
![sample image](https://camo.githubusercontent.com/b7f69981f780205cebd531ca1f192caa33f77780/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f336f68633050565673677435373875426b412f67697068792e676966)

**Comment by franklingu** [comment]
分析一下王者也行吧

**Comment by 521xueweihan** [comment]
您推荐的项目，已成功收录在 [HelloGitHub 第 24 期](https://hellogithub.com/volume/24/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
