### ISSUE TITLE
add excel-to-pdf

### ISSUE THREAD

**Issue by zhangchunsheng** [521xueweihan/HelloGitHub#1872]
## 项目推荐
- 项目地址：https://github.com/devops-utils/excel-to-pdf

- 类别：Java

- 项目描述：
  - An easy way to convert Excel 2003 and Excel 2007 to PDF by Java code based on Apache POI and itext7

- 推荐理由：
  - Support Excel 2003 and Excel 2007
  - Support wrap text

- 示例代码：
```java
IExcel2PDF excel2PdfTool = EPFactory.getEP("case6.xlsx", "output1.pdf", System.getProperty("user.dir") + "/doc/font/SimHei.TTF");
if(excel2PdfTool != null) {
    excel2PdfTool.convert();
}
```

- 截图：
![image](https://user-images.githubusercontent.com/831839/131781166-bf5d7413-04b2-4219-8e22-9022119bd75d.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
