### ISSUE TITLE
chinese-poetry

### ISSUE THREAD

**Issue by franklingu** [521xueweihan/HelloGitHub#188]
## 项目推荐
- 项目名称：
chinese-poetry
- 项目地址：
https://github.com/chinese-poetry/chinese-poetry
- 项目语言：
python
- 项目描述：
最全的中华古典文集数据库, 包含5.5万首唐诗、26万首宋诗和2.1万首宋词. 唐宋两朝近1.4万古诗人, 和两宋时期1.5K词人. 数据来源于互联网.

为什么要做这个仓库? 古诗是中华民族乃至全世界的瑰宝, 我们应该传承下去, 虽然有古典文集, 但大多数人并没有拥有这些书籍. 从某种意义上来说, 这些庞大的文集离我们是有一定距离的。而电子版方便拷贝, 所以此开源数据库诞生了. 你可以用此数据做任何有益的事情， 甚至我也可以帮助你.

古诗采集没有记录过程， 因为古诗数据庞大，目标网站有限制, 采集过程经常中断超过了一个星期.
- 推荐理由：

- 示例代码：

- 截图：
![sample](https://raw.githubusercontent.com/chinese-poetry/chinese-poetry/master/images/ci_rhythmic_topK.png)

**Comment by 521xueweihan** [comment]
已推荐过——[19 期](https://hellogithub.com/volume/19/)
