### ISSUE TITLE
项目推荐 | Hamibot - 安卓平台JS自动化工具

### ISSUE THREAD

**Issue by SekiBetu** [521xueweihan/HelloGitHub#1889]
## 项目推荐
- 项目地址：https://github.com/hamibot/hamibot

- 类别：JS

- 项目后续更新计划：不清楚

- 项目描述：Hamibot 是一款 Android 平台基于Auto.js开发的 JavaScript 自动化工具，无需 root，无需编程基础，在脚本市场内安装脚本即可运行。

- 推荐理由：Auto.js社区关闭之后，安卓平台上的自动化APP进入了沉默期，然后Hamibot出现了，虽然现在还在成长期，但是很有潜力，其自带的开发文档也算全面

- 截图：
![image](https://user-images.githubusercontent.com/38283893/132951905-772d1102-d4a6-4226-9674-9e786e8cf798.png)

**Comment by 521xueweihan** [comment]
先放放，看看这个项目能活多久
