### ISSUE TITLE
自荐项目 | Mokia

### ISSUE THREAD

**Issue by varHarrie** [521xueweihan/HelloGitHub#1894]
## 项目推荐
- 项目地址：https://github.com/varHarrie/mokia

- 类别：JS

- 项目后续更新计划：v0.5刚发布，短期以bugfix为主，长期进行功能迭代，直到v1.0

- 项目描述：
  - 必写：一个开箱即用的API模拟服务器，帮助快速创建后端原型和数据模拟。
  - 可选：适合任何需要快速创建一个API服务器的场景，例如前端开发中，在只有接口文档的情况下，通过mokia可以快速搭建一个接口高度自定义的服务器，配合进行联调测试。同时可以利用代理模式，模拟个别接口，其余接口依旧指向真实的服务器。

- 推荐理由：开发者可以忽略服务器框架原理、API和搭建过程，一行命令、零依赖便可以启动一个mock服务器，同时只需专注于编写接口函数便可以实现模拟接口。鉴于mokia本身就提供了大量mock方法，以及基于TS开发，结合IDE的智能提醒，编写过程会变得更加简单。

- 示例代码：

创建入口文件（index.js）：

```js
module.exports = {
  port: 3000,
  'GET /users'() {
    return this.list(() => ({ id: this.uuid(), name: this.fullName() }));
  },
  'GET /users/:id'(req) {
    return { id: req.params.id, name: this.fullName() };
  },
};
```

启动服务器：

```bash
npx mokia index.js
```

浏览器打开[http://localhost:3000/users](http://localhost:3000/users)，可以得到响应结果

**Comment by 521xueweihan** [comment]
开源的 mock server 太多了，需要在突出下亮点。
Mokia 才刚刚开源，走的再久一些，再来推荐吧。
希望届时 HG 可以帮你一把。
