### ISSUE TITLE
JkdYaf 一个简单、高性能常驻内存的PHP框架

### ISSUE THREAD

**Issue by crytjy** [521xueweihan/HelloGitHub#1896]
## 项目推荐
- 项目地址：https://github.com/crytjy/JkdYaf

- 类别：PHP

- 项目后续更新计划：后期讲话加上队列与rpc

- 项目描述：
  - 必写：JkdYaf 一个简单、高性能常驻内存的PHP框架。
  - 可选：适用于什么场景、能够让初学者学到什么
  - 描述长度（不包含示例代码）: 基于Yaf与Swoole开发，性能较传统基于 PHP-FPM 的框架有质的提升。一款专为Api开发的轻量级框架。一款面向中小型企业级项目的高可用、低门槛PHP开源框架。

- 推荐理由：简单、高性能常驻内存的PHP框架

- 示例代码：（可选）长度：1-20 行

- 截图：![jkdyaf](https://user-images.githubusercontent.com/38123501/133660980-d8240fea-7598-4bca-b425-52896746eefd.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
