### ISSUE TITLE
推荐一个自己写的微信小程序内容滑动插件：we-swiper

### ISSUE THREAD

**Issue by dlhandsome** [521xueweihan/HelloGitHub#19]
#### 项目描述：
这是一款应用为微信小程序打造的内容滑动解决方案，对比官方swiper组件的优势：
- 丰富的事件回调
- 丰富的属性
- 支持横、纵向滑动
- 强拓展（可在原插件基础上二次开发）

#### ScreenShots
- 横向滚动
![Alt text](https://github.com/dlhandsome/we-swiper/blob/master/screenshots/Gif_20170401_013729.gif?raw=true)
-  纵向滚动
![Alt text](https://github.com/dlhandsome/we-swiper/blob/master/screenshots/Gif_20170401_013701.gif?raw=true)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目 🙏。

如您推荐的项目在《HelloGithub》月刊中推荐，则会注明推荐人。同时在此 issues 中通知您。

再次感谢您对《HelloGithub》项目的支持！💪

**Comment by 521xueweihan** [comment]
@dlhandsome 您好，因为我个人感觉可能这个项目受众较小，不能收录进 HelloGitHub，其它推荐受众更广的项目 ❤️

欢迎讨论 😁
