### ISSUE TITLE
【项目自荐】Go语言实现的IM整体解决方案OpenIM 包括服务端和客户端SDK

### ISSUE THREAD

**Issue by skiffer-git** [521xueweihan/HelloGitHub#1900]
## 项目推荐
- 项目地址：https://github.com/OpenIMSDK/Open-IM-Server

- 类别：Go

- 项目后续更新计划：
   支持基于sfu的音视频通话；
   高频消息操作用mongodb替换；
   支持上万人大群；

- 项目描述：
Open-IM：由前微信技术专家打造的基于 Go 实现的即时通讯（IM）项目，从服务端到客户端SDK开源即时通讯（IM）整体解决方案。开发文档完善，代码100%开源，支持Andorid、iOS原生开发，支持Flutter、uni-app跨端开发，支持小程序、React等所有主流web前端技术框架， PC支持Electron，可以轻松替代第三方IM云服务。

- 推荐理由：IM云服务价格高企，且无法支持私有化部署。 OpenIM 100%开源，私有化部署，一切皆可控。
OpenIM SDK提供IM全平台支持，支持Andorid、iOS原生开发，支持Flutter、uni-app跨端开发，支持小程序、React等所有主流web前端技术框架， PC支持Electron，Flutter、iOS、uni-app已有成熟demo可以体验。
部署方便，开发文档齐全 ：https://doc.rentsoft.cn/demo/server_deploy/docker_singe.html

- 截图：
![image](https://user-images.githubusercontent.com/72860476/134342040-bf41b062-a1a5-43d4-88c3-c8f27978e13e.png)

![e3aa60a775a6d1906e784455831c356](https://user-images.githubusercontent.com/72860476/134343084-da3204da-13af-4c5e-8857-794ef410f96f.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 66 期](https://hellogithub.com/periodical/volume/66/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
