### ISSUE TITLE
mypy

### ISSUE THREAD

**Issue by colinshin** [521xueweihan/HelloGitHub#1902]
## 项目推荐
- 项目地址：https://github.com/python/mypy

- 类别：Python

- 项目后续更新计划：

- 项目描述：
  - 必写：mypy是一款针对python的静态类型检查程序
  - 可选：python是一门动态类型的语言，既然是动态类型的语言，python的类型检查还有啥意义呢？静态类型语言在程序运行之前通过对源代码的分析进行类型检查，并在运行前检测应用程序中代码可能的错误，就是mypy(python应用程序的静态类型检查)的价值所在
  - 描述长度（不包含示例代码）: 50

- 推荐理由：mypy 是python应用程序的静态类型检查工具，及早发现问题

- 示例代码：  test.py
`
class People:
    def __init__(self, name, age):
        self.name = name
        self.age = age

def info(peoples_list):
    for people in peoples_list:
        if people.age < 18:
            print(f'{people.name}是小孩子')

p1 = People('python', 10)
p2 = People('java', 20)

info([p1, p2])
info(p1)
`

mypy test.py

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 66 期](https://hellogithub.com/periodical/volume/66/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
