### ISSUE TITLE
项目推荐 | btop++ 一款非常不错的类似 top 的资源监视工具

### ISSUE THREAD

**Issue by SekiBetu** [521xueweihan/HelloGitHub#1907]
## 项目推荐
- 项目地址：https://github.com/aristocratos/btop

- 类别：C++

- 项目后续更新计划：不清楚

- 项目描述：一款展示包括处理器、内存、磁盘、网络、进程等信息的资源监视工具

- 推荐理由：UI美观、功能全面、完全支持鼠标、快速响应、可过滤进程、树状图等等的实用功能集于一身，可替代系统自带的 top 工具，同时作者还用 bash ([bashtop](https://github.com/aristocratos/bashtop)) 和 python ([bpytop](https://github.com/aristocratos/bpytop)) 分别实现了本工具

- 截图：
![image](https://user-images.githubusercontent.com/38283893/134847947-8348eb70-449f-4254-80c0-8d603618ae95.png)
![image](https://user-images.githubusercontent.com/38283893/134847952-1248e838-e991-4a38-b70d-cb4a4f9d5aae.png)

**Comment by 521xueweihan** [comment]
感谢推荐，这个 66 期刚推荐过了～
