### ISSUE TITLE
wiki.js

### ISSUE THREAD

**Issue by franklingu** [521xueweihan/HelloGitHub#192]
## 项目推荐
- 项目名称：
Wiki.js
- 项目地址：
https://github.com/Requarks/wiki
- 项目语言：
JavaScript
- 项目描述：
An open source, modern and powerful wiki app built on Node.js, Git and Markdown.
- 推荐理由：
看起来很不错wiki repo，现在只支持git的backend，不过也不错了
- 示例代码：

- 截图：

**Comment by 521xueweihan** [comment]
@franklingu   您推荐的项目，已成功收录在 [HelloGitHub 第 23 期](https://hellogithub.com/volume/23/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
