### ISSUE TITLE
项目自荐 | awesome-flutter-plugins

### ISSUE THREAD

**Issue by jahnli** [521xueweihan/HelloGitHub#1931]
## 项目推荐
- 项目地址：仅收录 GitHub 的开源项目，请填写 GitHub 的项目地址

- 类别：Flutter

- 项目后续更新计划：新增类别、持续更新

- 项目描述：
  - 必写：尽可能收集好用的Flutter插件以便更效率的开发
  - 描述长度（不包含示例代码）:Flutter 、dart、flutter桌面化插件

- 推荐理由：轻松找到你想要的Flutter插件、满足大多基本需求

- 截图：
![QQ截图20211018090208](https://user-images.githubusercontent.com/20943608/137652197-ae7c7862-2655-416a-a9f6-080890886827.png)

**Comment by smart2pet** [comment]
@521xueweihan This isn't a spam/bad issue. Please come and review it. Thanks a lot.

**Comment by 521xueweihan** [comment]
此项目非恶意 issue。
但除特别突出的 awesome 的集合，本月不收录集合类项目

**Comment by smart2pet** [comment]
Ok. Ok.
