### ISSUE TITLE
Rust 并行迭代器 Rayon

### ISSUE THREAD

**Issue by M-Adoo** [521xueweihan/HelloGitHub#194]
## 项目推荐
- 项目名称：Rayon

- 项目地址：https://github.com/rayon-rs/rayon

- 项目语言：Rust

- 项目描述：rayon 是一个易用、无数据竞争的将顺序迭代器妆化成并行迭代器。很容易就可以将自己的单线程程序并行化。

- 推荐理由: 易用、无数据竞争、不破坏逻辑

- 示例代码：

```rust
// just change your foo.iter() call into foo.par_iter()
use rayon::prelude::*;
fn sum_of_squares(input: &[i32]) -> i32 {
    input.par_iter() // <-- just change that!
         .map(|&i| i * i)
         .sum()
}
```
- 截图：

**Comment by JameJJ** [comment]
感觉可以在写写描述，比如使用场景之类的

**Comment by FrontMage** [comment]
简单说就是原本你的数组只能一个一个地遍历，这个可以并发同时从几个index开始遍历，同时也能遍历map等类似的数据结构
@JameJJ

**Comment by 521xueweihan** [comment]
@FrontMage 赞

**Comment by M-Adoo** [comment]
@FrontMage  通俗易懂。

**Comment by 521xueweihan** [comment]
@M-Adoo   您推荐的项目，已成功收录在 [HelloGitHub 第 26 期](https://hellogithub.com/periodical/volume/26/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
