### ISSUE TITLE
Electron 融合Nestjs 的桌面应用开发框架

### ISSUE THREAD

**Issue by ArcherGu** [521xueweihan/HelloGitHub#1942]
## 项目推荐
- 项目地址：https://github.com/ArcherGu/fast-vite-nestjs-electron

- 类别：JS/TS

- 项目后续更新计划：长期维护，文档，博客更新。

- 项目描述：
  - 一个Electron的构建框架，融合了nest.js，可以方便的在未来从C/S 切换到 B/S，前端由vite构建，主进程由esbuild构建，开发启动速度非常快，开发者体验拉满。
  - 适用于常规的桌面项目，特别适合未来有C/S转B/S需求的渐进式项目。
  - 本项目完全由 Typescript 开发。

- 推荐理由：将桌面框架 electron 和 node.js 后端框架 nestjs 融合，并通过当下流行的 vite 和 esbuild 进行快速启动和构建。

![封面](https://github.com/ArcherGu/fast-vite-nestjs-electron/raw/main/logo.png)

**Comment by 521xueweihan** [comment]
@ArcherGu  非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
