### ISSUE TITLE
WindTerm - 替换Xshell的终端工具

### ISSUE THREAD

**Issue by leioulin** [521xueweihan/HelloGitHub#1946]
## 项目推荐
- 项目地址：https://github.com/kingToolbox/WindTerm

- 类别：C++ 
- 项目后续更新计划：

- 项目描述：
  - 必写：一个用于 DevOps 的更快更好的 SSH/Telnet/Serial/Shell/Sftp 客户端，用以替代Xshell、Finalshell
  - 可选：
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：
- 实施了 SSH v2、Telnet、Raw Tcp、串行、Shell 协议。介绍视频
  会话认证时支持 SSH 自动执行。
  支持 SSH ProxyCommand 或 ProxyJump。介绍视频
  支持SSH代理转发。介绍视频
  支持使用密码、公钥、键盘交互、gssapi-with-mic 的 SSH 自动登录。介绍视频
  支持X11转发。介绍视频
  支持直接/本地端口转发、反向/远程端口转发和动态端口转发。介绍视频
  支持 XModem、YModem 和 ZModem。介绍视频
  集成sftp、scp客户端，支持下载、上传、删除、重命名、新建文件/目录等。介绍视频
  集成本地文件管理器，支持移动到、复制到、复制自、删除、重命名、新建文件/目录等。
  支持 Windows Cmd、PowerShell 和 Cmd、PowerShell 作为管理员。
  支持Linux bash、zsh、powershell core等。
  支持 MacOS bash、zsh、powershell core 等。

- 示例代码：（可选）长度：1-20 行

- 截图：
![WindTerm](https://user-images.githubusercontent.com/26403440/139399300-c97f1042-6ba6-4417-abf9-7bc39ec52a37.png)

**Comment by SekiBetu** [comment]
@521xueweihan 这是个半开源的项目，因为涉及到用户连接服务器的过程，可能有些人不想用半开源的，可以最后发表的时候说明一下

**Comment by 521xueweihan** [comment]
@SekiBetu 好的

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 68 期](https://hellogithub.com/periodical/volume/68/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
