### ISSUE TITLE
项目自荐 | Vue Color Avatar 一个纯前端实现的头像生成网站 🧑‍🦱

### ISSUE THREAD

**Issue by Codennnn** [521xueweihan/HelloGitHub#1950]
## 项目推荐
- 项目地址：[https://github.com/Codennnn/vue-color-avatar](https://github.com/Codennnn/vue-color-avatar)

- 类别：JS

- 项目后续更新计划：丰富头像素材，并且可以自定义素材的颜色

- 项目描述：
  - 一个纯前端实现的矢量风格**头像生成**网站，可以搭配不同的素材组件，生成自己的个性化头像

- 推荐理由：使用 Vite + Vue3 开发，帮助前端初学者学习 Vue3 的语法以及掌握项目搭建

- 截图：

![image](https://user-images.githubusercontent.com/47730755/139567336-8990ebee-1e6e-421c-a343-9bcf8b646e5c.png)

![image](https://user-images.githubusercontent.com/47730755/139567345-a40df90f-8b80-4a78-ad03-0c5e4458a6f5.png)

![image](https://user-images.githubusercontent.com/47730755/139567352-3ea85503-1957-4cd6-9b02-a03935a012a2.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 68 期](https://hellogithub.com/periodical/volume/68/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
