### ISSUE TITLE
项目自荐 | Python的终极API开发框架JSONClasses

### ISSUE THREAD

**Issue by victorteokw** [521xueweihan/HelloGitHub#1951]
## 项目自荐
- 项目地址：https://github.com/fillmula/jsonclasses

- 类别：Python

- 项目后续更新计划：
- 持续维护和增加对于快速开发API服务器有用的功能。
- 持续维护和增加单页面低代码API服务器的功能。

- 项目描述：
  - JSONClasses是快速开发API服务器的利器，将数据验证、数据转换、数据呈现、序列存储和ORM、服务器进行有机的声明化结合。代码易于分离、维护，编写高效，易于阅读，大大缩短了API服务器的开发时间。
  - 适用于需要使用Python编程语言开发API服务器的用户。

- 推荐理由：极低代码的声明式变成，后端界的React.js。

- 示例代码：
```python
from __future__ import annotations
from datetime import datetime
from jsonclasses import jsonclass, types
from jsonclasses_pymongo import pymongo
from jsonclasses_server import api, create_flask_server


@api
@pymongo
@jsonclass
class Article:
    id: str = types.readonly.str.primary.mongoid.required
    title: str
    content: str
    words: int = types.int.getter(types.this.fval('content').split(" ").len)
    published: bool = False
    created_at: datetime = types.readonly.datetime.tscreated.required
    updated_at: datetime = types.readonly.datetime.tsupdated.required
    
    
app = create_flask_server()    
```

- 其他：
- 官方网站：https://www.jsonclasses.com
- 官方文档：https://docs.jsonclasses.com
- Medium文章：https://medium.com/@victor.teo/python-web-api-development-with-jsonclasses-67f618eaedc6

**Comment by 521xueweihan** [comment]
@victorteokw 感谢您推荐的项目，但该项目暂时不能收录到月刊中。

我认为 fastAPI 适用的场景已涵盖贵项目支持的所有场景，虽然低代码方面 jsonclasses 较强但也相对局限。如果让我选择的话，我更愿意投入时间学习 fastAPI 或者说把它用的更加顺手。
