### ISSUE TITLE
PyWebIO - Build web apps with only Python

### ISSUE THREAD

**Issue by Chasing66** [521xueweihan/HelloGitHub#1956]
## 项目推荐
- 项目地址：https://github.com/pywebio/PyWebIO

- 类别：python

- 项目后续更新计划：持续更新

- 项目描述：
  - PyWebIO提供了一系列命令式的交互函数来在浏览器上获取用户输入和进行输出，将浏览器变成了一个“富文本终端”，可以用于构建简单的Web应用或基于浏览器的GUI应用。 PyWebIO还可以方便地整合进现有的Web服务，让你不需要编写HTML和JS代码，就可以构建出具有良好可用性的应用。

- 推荐理由：不需要编写HTML和JS代码，就可以构建出具有良好可用性的应用

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

## 提示（提交时请删除以下内容）
> 点击上方 “Preview” 更方便地阅读以下内容，

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 68 期](https://hellogithub.com/periodical/volume/68/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
