### ISSUE TITLE
React hooks 实用收录集锦

### ISSUE THREAD

**Issue by baiziyu-fe** [521xueweihan/HelloGitHub#1958]
## 项目推荐
- 项目地址：[use-Hooks](https://github.com/baiziyu-fe/use-hooks)

- 类别：JS、React

- 项目后续更新计划：

- 项目描述：
  - 必写：用来收集实现目前好用的hooks并手写，提供可引入的方式和本地启动
  - 可选：适用于使用React-Hooks开发的项目，提供多种不同场景下的hooks支持和使用，并且包含一些hooks的讲解
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：为业务代码提供更多可用的hook和方案

- 示例代码：
```TS
//懒加载图片
import useElementInView from './useElementInView';

const lazyLoadImg = (el: any) => {
  const { target } = el;
  target.src = target.dataset.src;
}

const useLazyLoadImg = (imgElList: HTMLImageElement[]) => {
  useElementInView(imgElList, lazyLoadImg, {
    threshold: [1]
  })
};

export default useLazyLoadImg;

```
- 详见[Readme](https://github.com/baiziyu-fe/use-hooks#readme)

**Comment by 521xueweihan** [comment]
@baiziyu-fe 非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
