### ISSUE TITLE
[项目自荐] ColorFu：一个用文字，颜色，纹理和图片生成有感情的美丽壁纸的工具

### ISSUE THREAD

**Issue by pearmini** [521xueweihan/HelloGitHub#1965]
## 项目推荐
- 项目地址：https://github.com/pearmini/colorfu

- 类别：JS

- 项目后续更新计划：添加更多颜色，案例，支持生成移动端的壁纸。

- 项目描述：
  - 必写：快速生成 “文字 + 颜色/纹理/图片“ 这种美丽且有意义的壁纸。
  - 可选：壁纸的编辑界面有配置面板，这个配置面板是直接根据一套 JSON schema 渲染而成的，非常的方便。
  - 描述长度（不包含示例代码）: 福字（Fu）是中国的传统习俗，大家会在红纸上写一个个大大的“福”字来表达对来年的美好期望，这就是一个用**颜色**和**文字**来表达情感的很好的例子。如果有工具能让你用更加丰富和复杂的颜色，更多的文字去表达更多的情感和想法呢？ColorFu 就是这样的工具：让你的壁纸不再冰冷而有意义。

- 推荐理由：简洁的界面，丰富且有意义的颜色，支持颜文字和 emoji，让你的壁纸美丽且有意义。

- 截图：
<img width="1679" alt="截屏2021-11-10 下午10 14 19" src="https://user-images.githubusercontent.com/49330279/141133855-9fc1d1af-3d81-43b3-b5e6-ccc9522fddf7.png">
<img width="1679" alt="截屏2021-11-10 下午10 13 16" src="https://user-images.githubusercontent.com/49330279/141133865-bd622a2f-604e-48a1-8b7a-4eb0d37c9f1b.png">

<img width="956" alt="截屏2021-11-08 上午1 54 03" src="https://user-images.githubusercontent.com/49330279/141134087-5644d8e9-c92a-4892-a665-b51a9fe63e29.png">

![wallpaper (7)](https://user-images.githubusercontent.com/49330279/141134200-06aac256-925b-408e-8cf4-3cb1ee3118a4.png)

**Comment by 521xueweihan** [comment]
@pearmini

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 68 期](https://hellogithub.com/periodical/volume/68/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
