### ISSUE TITLE
MapTileGenerator

### ISSUE THREAD

**Issue by michael-laoyu** [521xueweihan/HelloGitHub#1966]
## 项目推荐
- 项目地址：[GitHub 的项目地址](https://github.com/michael-laoyu/MapTileGenerator)

- 类别：请从中选择（C#）

- 项目后续更新计划：

- 项目描述：
  - 必写：第三方地图瓦片下载工具。支持TMS、WMTS标准瓦片下载，支持百度地图瓦片、高德地图瓦片、腾讯地图瓦片、天地图、ArcServer Rest瓦片、ArcServer本地缓存切片、geoserver WMS等瓦片下载。默认以png文件方式保存瓦片，也支持以sqlite（mbtiles格式）保存瓦片，支持瓦片base64编码后以sqlite保存（用于android端离线地图）。
  
  - 可选：适用于什么场景、能够让初学者学到什么
  适用于GIS领域，能让初学者熟悉了解地图瓦片的相关算法。
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？
项目中使用的工具，已应用多年，运行稳定可靠。

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
