### ISSUE TITLE
项目自荐 | 自动化host碰撞工具（hostscan）

### ISSUE THREAD

**Issue by cckuailong** [521xueweihan/HelloGitHub#1967]
项目地址：https://github.com/cckuailong/hostscan
类型：golang
项目描述：
自动化Host碰撞工具，帮助红队快速扩展网络边界，获取更多目标点
使用背景：
很多时候，访问目标网站时，使用其真实IP无法访问，只有域名才能访问到后端业务服务。这是因为反代服务器（如nginx）配置了禁止直接IP访问。

nginx后面的业务有时是隐藏的：

不开放到外网的业务，如测试业务

原来DNS解析到外网，但是后来删除了A记录（nginx后的业务没删除，转移到了内网访问）

怎么访问这些隐藏的业务呢？这就需要今天的主角登场了--Host碰撞技术

其他参加github中的readme

p.s. 想问下大佬，要不要开hellogithub的专项，比如说安全工具专项，感觉细分领域可能受众指向性更强

**Comment by 521xueweihan** [comment]
@cckuailong 不好意思，暂时没有安全工具类别。
我正在开发标签功能，以及除了月刊的展示途径。但是开发进度有些慢。。。还得在耐心等待一段时间😅。

您的项目为解决痛点而生，非常酷。但正如您所说，针对的受众较为局限，所以暂时不能收录到月刊中。等我后面支持了标签，欢迎再来推荐。
