### ISSUE TITLE
自荐项目 | Fantastic-admin - 一款开箱即用的 Vue 中后台管理系统框架

### ISSUE THREAD

**Issue by hooray** [521xueweihan/HelloGitHub#1968]
## 项目推荐
- 项目地址：https://github.com/hooray/fantastic-admin

- 类别：JS

- 项目后续更新计划：持续产出业务相关静态页面和 Vue3 版本视频教程

- 项目描述：
  - 丰富的布局模式，覆盖市面上各种中后台布局，兼容PC、平板和移动端
  - 提供主题配置文件，轻松实现个性化定制
  - 精心设计的动效，让每一处的动画都干净利落
  - 根据路由配置自动生成导航栏
  - 支持全方位权限验证
  - 集成多级路由缓存方案

- 推荐理由：不管是前端还是后端开发者，都可以快速上手

- 截图：
![](https://camo.githubusercontent.com/dec3d229265ec0011d84255bb1bfc4755dcc386c2ae00c1df137b8983dc5fb98/68747470733a2f2f686f6f7261792e67697465652e696f2f66616e7461737469632d61646d696e2f70726576696577322e706e67)
![](https://camo.githubusercontent.com/bbb0a5457e4e6425ccae6fefe5fbf83eb7bc27273bba07c780a8ba04469a1304/68747470733a2f2f686f6f7261792e67697465652e696f2f66616e7461737469632d61646d696e2f70726576696577342e706e67)
![](https://camo.githubusercontent.com/4c0ac3433f523832ec5768648361004b9d15ed742d473b2cf6223f66d94ac589/68747470733a2f2f686f6f7261792e67697465652e696f2f66616e7461737469632d61646d696e2f70726576696577332e706e67)

**Comment by 521xueweihan** [comment]
您好，月刊已收录过类似开源项目，所以贵项目暂不能收录到月刊中。
