### ISSUE TITLE
项目自荐 | 字节跳动企业级设计系统 Arco Design

### ISSUE THREAD

**Issue by PengJiyuan** [521xueweihan/HelloGitHub#1972]
![middle_img_v2_d851b9a2-4ef6-4ab1-8fe7-3095e3bf6a3g](https://user-images.githubusercontent.com/19399269/141933465-3996ff30-71c4-4029-bf81-2a984b840681.png)

## 项目推荐
- 项目地址：[https://github.com/arco-design/arco-design](https://github.com/arco-design/arco-design)

- 类别：JS

- 项目后续更新计划：由字节跳动官方团队维护，每周五发版。

- 项目描述：

  **ArcoDesign 是由字节跳动 GIP UED 团队和架构前端团队联合推出的企业级设计系统，是内部使用量最大的设计系统。** 在打磨了近 3 年之后，通过字节内部大量业务沉淀和验证，我们开源了 ArcoDesign 设计系统。旨在让社区听见更多的声音，为更多中小型企业及个人设计师和开发者提效，创造更多高效美观的“最佳实践”。

  ArcoDesign 拥有系统的设计规范和资源，依据此规范提供了覆盖 React、Vue、Mobile 的原子组件。同时基于丰富的原子组件，Arco 提供了丰富的定制化平台，包括风格配置平台、物料平台等。也提供了丰富的资源平台，包括图标平台、品牌库、Arco Pro 最佳实践等。

  正如 「Arco」 这个名字一样，遵循【Agreement / 一致】、【Rhythm / 韵律】、【Clear / 清晰】、【Open / 开放】的理念，Arco 希望能帮助更多的用户提升工作效率和愉悦程度，打造更好的产品。

  https://user-images.githubusercontent.com/19399269/141435899-e453cf75-d50f-4549-b8d0-37daebe46c36.mp4

- 推荐理由：

  **完善的基础组件**

  基于 ArcoDesign 设计规范，Arco 提供了 67 个基础组件，这些基础组件足以支撑绝大多数的业务需求。同时，Arco 在这些基础组件的设计上，也开放了细粒度的配置，方便后续拓展。
  
  ![arco-components](https://user-images.githubusercontent.com/19399269/141931983-8bef0516-70a2-49c2-ab13-4766e4b0f5ce.png)

  **React 和 Vue 同步支持**

  基于 ArcoDesign 设计规范，Arco 同时提供了 React 和 Vue 两套 UI 组件库。Vue 组件库基于 Vue 3.0 开发，提供了面向未来开发的能力，且与 React 组件库底层能力互通，均可完美利用 Arco 生态体系的各项能力。

  **科学的暗黑模式**

  Arco 支持一键开启暗黑模式，无缝切换，流畅体验。
暗黑模式会让使用者更加专注自己的操作任务，同时避免在黑暗环境中长时间注视高亮光源导致的视觉刺激。
Arco 在底层设计上，结合了 Less 和 CSS 变量各自的优势。Less 变量负责编译时的色彩计算，基于主色计算亮 / 暗两套梯度色板，CSS 变量负责页面渲染时的最终引用，从而实现了无缝切换亮 / 暗色风格。用户既能享受 CSS 变量带来的丝滑切换体验，又能享受 Less 变量带来配置单个主色即可生成整套色板的便捷，兼顾优雅与易用。

  **开箱即用的体验**

  为了帮助用户更快速地从 0 到 1 搭建项目，Arco 提供了最佳实践 Arco Pro，整理了常见的页面场景，帮助用户快速初始化项目和使用页面模板。
在中后台项目中，页面设计模式较为单一，Arco 提取了典型的业务场景，并将其抽离为页面模板，使用户通过简单的复制和修改就能快速搭建页面。

  **极致的个性化定制能力**

  从底层组件到上层平台，Arco 提供了极致的定制能力。

  在底层组件上，Arco 提供了细致的样式定制和默认行为定制。
样式方面，Arco 从设计之初就通过细致的拆分，将影响组件视觉的样式都抽离为上千个独立的 token 变量，并基于这些变量完成了从全局样式到组件样式的全面配置。

  ![arco-token](https://user-images.githubusercontent.com/19399269/141932411-89c60885-9615-4c53-a76a-8cdd7c083fc1.gif)

  在默认行为方面，Arco 支持 60+ 组件默认行为的全局配置，以极大的灵活性，减小维护成本、提升开发体验。用户只需要维护一份全局配置，就能定制每一个组件的默认交互。

  在底层能力的加持下，Arco 的上层平台再次将定制能力无限放大。
Arco 提供了样式可视化编辑的「风格配置平台」。基于风格配置平台所见即所得的组件配置能力，用户可以对全局样式和组件样式做细粒度的调整，实现「ArcoDesign to Any Design」。在配置完成之后，用户可一键发布主题到主题市场，提供优秀的主题风格给社区。在主题市场上，用户可以浏览所有主题，自由地进行选用。

  ![arco-designlab](https://user-images.githubusercontent.com/19399269/141932739-cccfed06-cc80-412d-acea-5681717029dd.gif)

  **全流程完善的生态体系**

  Arco 希望通过完善的生态体系，提升设计、开发全流程工作体验。

  在生态平台上，Arco 提供了个性化定制平台包括风格配置平台、物料平台等，资源平台包括图表平台 IconBox、中后台最佳实践ArcoPro 等。 
  在开发工具上，Arco 提供了 Webpack 插件、ArcoCli 脚手架工具、VSCode 插件、Figma 插件等。

- 示例代码：

  ```js
  import React from 'react';
  import ReactDOM from 'react-dom';
  import { Button } from '@arco-design/web-react';
  import '@arco-design/web-react/dist/css/arco.css';
  
  function App() {
    return (
      <Button type='secondary'>
        Hello World
      </Button>
    );
  }
  
  ReactDOM.render(<App />, document.getElementById('app'));
  ```

- 截图：

  ![1](https://user-images.githubusercontent.com/19399269/141933780-5acfd3e6-ab83-4ec4-abba-32965fe67afd.png)
  ![2](https://user-images.githubusercontent.com/19399269/141933803-1c4769d3-b21f-458c-af29-0b16697e017c.png)
  ![3](https://user-images.githubusercontent.com/19399269/141933802-0386061c-2490-4263-88d2-dea58bc81be9.png)
  ![4](https://user-images.githubusercontent.com/19399269/141933800-e6e1628f-c165-4d4e-8c04-9a9752d44e80.png)

**Comment by 521xueweihan** [comment]
@PengJiyuan 请勿大段复制内容，用于填充推荐理由和项目描述。

请修改后 @我，否则将不收录到月刊。

**Comment by PengJiyuan** [comment]
> @PengJiyuan 请勿大段复制内容，用于填充推荐理由和项目描述。
> 
> 请修改后 @我，否则将不收录到月刊。

这个原版的内容也是我写的，如果是多的话我删减一些。

**Comment by PengJiyuan** [comment]
@521xueweihan Hi，我修改删减了一版，麻烦看下可以不～

**Comment by 521xueweihan** [comment]
@PengJiyuan 您辛苦了。由于本期月刊时间点有些特殊，所以明天就会发布。

很抱歉，目前月刊已经合刊，所以贵项目只能下期安排收录和发布了。

最后，关于项目描述和推荐理由，月刊每个项目描述的因篇幅有限（不易超过 256 字），所以没有办法面面俱到，只能提炼出关键字眼。下面是我写的欢迎讨论和修改。
```
基于 ArcoDesign 的 React UI 组件库，可用于快速构建企业级管理后台。包含 60 多个开箱即用的高质量组件，还提供了可视化的样式配置平台
```

**Comment by PengJiyuan** [comment]
> 

好的，您辛苦，我再修改一下哈，争取下次能收录

**Comment by PengJiyuan** [comment]
@521xueweihan 我之前写的时候太考虑排版了，写的有点多，抱歉。我已经改完了，现在推荐理由在 200 字以下了，这次无法收录的话麻烦下次收录一下，非常感谢～

**Comment by 521xueweihan** [comment]
@PengJiyuan 收到，没问题。ArcoDesign 将收录在下一期月刊发布。👍

**Comment by 521xueweihan** [comment]
@PengJiyuan 您推荐的项目，**已成功发布**在 [HelloGitHub 第 69 期](https://hellogithub.com/periodical/volume/69/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
