### ISSUE TITLE
分享Android蓝牙开源作品-HBluetooth

### ISSUE THREAD

**Issue by g-HJY** [521xueweihan/HelloGitHub#1974]
## 项目推荐
- 项目地址：https://github.com/g-HJY/HBluetooth

- 类别：Java

- 项目后续更新计划：持续维护

- 项目描述：
- 封装了支持Android蓝牙（经典蓝牙或低功耗蓝牙）扫描，连接，以及通信的库。附带使用例子。
- 为更多的学习者或Android初学者提供一个学习入口，帮助他们更好更快速的理解掌握安卓蓝牙开发方面知识
- 源码封装尽量简单，层级少，适合学习，减少时间成本。兼容经典蓝牙和低功耗蓝牙，一次理解透彻，无需分头零散积累学习。

- 推荐理由：简单，简单，简单。并且同时支持经典蓝牙和低功耗蓝牙。

- 示例代码：HBluetooth.getInstance().scan()

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
