### ISSUE TITLE
基于搜狗微信搜索的微信公众号爬虫接口

### ISSUE THREAD

**Issue by Chyroc** [521xueweihan/HelloGitHub#198]
## 项目推荐
- 项目名称：
WechatSogou

- 项目地址：
https://github.com/Chyroc/WechatSogou

- 项目语言：
Python

- 项目描述：
基于搜狗微信搜索的微信公众号爬虫接口

- 推荐理由：
非常简单易用的爬取微信公众号的接口

- 示例代码：
```python
import wechatsogou

ws_api = wechatsogou.WechatSogouAPI()
ws_api.get_gzh_info('微信名称')
```
- 截图：

![](https://raw.githubusercontent.com/chyroc/wechatsogou/master/screenshot/get_gzh_info.png)

**Comment by 521xueweihan** [comment]
@Chyroc  您推荐的项目，已成功收录在 [HelloGitHub 第 24 期](https://hellogithub.com/volume/24/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
