### ISSUE TITLE
项目推荐 | sniffer 现代化的网络流量嗅探工具

### ISSUE THREAD

**Issue by chenjiandongx** [521xueweihan/HelloGitHub#1982]
## 项目推荐
- 项目地址：https://github.com/chenjiandongx/sniffer

- 类别：Go

- 项目后续更新计划：
  - 支持 pcap 数据文件保存。
  - 支持时序数据点持久化 支持 replay。

- 项目描述：
  - sniffer 是一个基于 BPF 实现的网络流量嗅探工具，可以按不同视角来查看主机流量情况，包括进程维度，socket 维度以及 remote address 维度。
  - sniffer 支持两种视图模式 Table View 以及 Plot View。

- 推荐理由：
  - 项目参考了 [nethogs](https://github.com/raboof/nethogs) 以及 [bandwhich](https://github.com/imsnif/bandwhich)，前者使用 Rust 编写，后者使用 C++ 编写。
  -  bandwhich 界面精巧并且支持以多种视角查看流量数据，像 Socket 连接、进程以及远程端点，但不支持传入 BPF 过滤条件，比如只想查看某个端口的流量数据或者过滤某个 IP 的数据。而 nethlogs 支持 BPF 过滤条件但只能以进程维度查看数据。
  - `sniffer` 在融合了两者有点的同时新增了一种新的图线数据展示模式，用于查看数据趋势。
  - `sniffer` 已收录在 https://github.com/raboof/nethogs 文档中，作为网络嗅探工具推荐。

- 用法说明
```shell
❯ sniffer -h
# A modern alternative network traffic sniffer.

Usage:
  sniffer [flags]

Examples:
  # processes mode for pid 1024,2048 in MB unit
  $ sniffer -p 1024 -p 2048 -m 2 -u MB

  # only capture the TCP protocol packets with lo,eth prefixed devices
  $ sniffer -b tcp -d lo -d eth

Flags:
  -b, --bpf string                   specify string pcap filter with the BPF syntax (default "tcp or udp")
  -d, --devices-prefix stringArray   prefixed devices to monitor (default [en,lo,eth,em,bond])
  -h, --help                         help for sniffer
  -i, --interval int                 interval for refresh rate in seconds (default 1)
  -l, --list                         list all devices name
  -m, --mode int                     view mode of sniffer (0: bytes 1: packets 2: processes)
  -n, --no-dns-resolve               disable the DNS resolution
  -p, --pids int32Slice              pids to watch, empty stands for all pids (default [])
  -u, --unit string                  unit of traffic stats, optional: B, Kb, KB, Mb, MB, Gb, GB (default "KB")
  -v, --version                      version for sniffer

```

- 截图示例

![](https://user-images.githubusercontent.com/19553554/142900814-5a0d5e01-43b8-4980-85fa-e78f4a554bc6.jpg)
![](https://user-images.githubusercontent.com/19553554/142900831-d7a025ad-4275-4c5f-a904-f66e329bffe7.jpg)
![](https://user-images.githubusercontent.com/19553554/142900845-50657ee0-7df6-4cca-99e8-c0fe05487b08.jpg)

-  演示视频

https://user-images.githubusercontent.com/19553554/142890205-62980e37-5861-4161-9669-737317573aa1.mov

**Comment by 521xueweihan** [comment]
@chenjiandongx 由于月刊的篇幅问题，您的项目将于下一期推荐。

**Comment by 521xueweihan** [comment]
@chenjiandongx 您推荐的项目，**已成功发布**在 [HelloGitHub 第 69 期](https://hellogithub.com/periodical/volume/69/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
