### ISSUE TITLE
无需安装任何软件，纯脚本 Mac OS 自动换超高清 bing(必应)壁纸

### ISSUE THREAD

**Issue by xiqishow** [521xueweihan/HelloGitHub#1984]
## 项目推荐
- 项目地址：https://github.com/xiqishow/bing_wallpaper

- 类别：其它

- 项目描述：
bing_wallpaper 为 Mac OS 随机定时设定 Bing 超高清壁纸（ UHD 质量） 纯脚本实现，无需安装任何软件 使用 Bing 壁纸定时随机选择一张图片设定系统壁纸（默认 5 分钟更换） 支持多屏幕同时更换壁纸
- 推荐理由：无需安装任何软件 即可将bing的超高清图片设置为Mac桌面壁纸

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
