### ISSUE TITLE
第 68 期  27. waka-readme-stats  有谁部署成功了吗？

### ISSUE THREAD

**Issue by sanbeichahegongheguo** [521xueweihan/HelloGitHub#1985]
我死活成功不了。

**Comment by sanbeichahegongheguo** [comment]
好的。谢谢。

**Comment by puzzle9** [comment]
提问 你好歹把错误截图放上来啊

把 那个项目的 `readme.md` 翻译成中文大概就成了

**Comment by sanbeichahegongheguo** [comment]
> 
> 提问 你好歹把错误截图放上来啊
> 
> 把 那个项目的 `readme.md` 翻译成中文大概就成了

谢谢指教。我已经部署成功了。我本来只是问问有谁部署成功了之后再交流的。另外并不是把 那个项目的 readme.md 翻译成中文大概就成了，还涉及到挺多问题。不过我都解决了。
