### ISSUE TITLE
80份程序员技术点，思维导图

### ISSUE THREAD

**Issue by wenchao1024** [521xueweihan/HelloGitHub#1986]
## 2021年【思维导图】盒子，C/C++，Golang，Linux，云原生，数据库，DPDK，音视频开发，TCP/IP，数据结构，计算机原理等
- 项目地址：https://github.com/0voice/learning_mind_map
- 类别：请从中选择（C++、Go）

- 项目后续更新计划：

- 项目描述：
  - 这是为涉及C/C++语言的技术点，整理收纳网络中大家归纳总结的【思维导图】，帮助大家更好地学习以及掌握知识重点。

- 推荐理由：整理清洁，分类明确。为不少程序员学习指明学习的方向

- 截图：

![image](https://user-images.githubusercontent.com/87457873/143672384-bd3f839f-90dc-49a9-9931-c24fc65d0cc1.png)

**Comment by puzzle9** [comment]
啊 还有哪里有

<https://github.com/ruanyf/weekly/issues/2091>

**Comment by wenchao1024** [comment]
@puzzle9 不能重提交吗？

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
