### ISSUE TITLE
自荐项目 | Context Note - 带上下文的网页笔记插件

### ISSUE THREAD

**Issue by betterRunner** [521xueweihan/HelloGitHub#1988]
## 项目推荐
- 项目地址：https://github.com/betterRunner/context-note

- 类别：JS

- 项目后续更新计划：持续更新维护

- 项目描述：
  - 生产力工具，基于vue3&vite2开发的一款网页笔记插件
  - 记录笔记的上下文信息，一键跳转，方便回顾与溯源
  - 便捷标签系统和完善的搜索，快速找到任一条笔记
 
- 推荐理由：
  - 较为创新地实现了一种记录上下文的网页笔记记录方式，**提高网页笔记的管理和回顾质量**
  - 在producthunt投票活动获得当日第六名，https://www.producthunt.com/posts/context-note

- 截图：

https://user-images.githubusercontent.com/7123136/138256405-f86d1e4e-3990-4a22-bac2-4e22e33b0245.mov

**Comment by 521xueweihan** [comment]
@betterRunner 您推荐的项目，**已成功发布**在 [HelloGitHub 第 69 期](https://hellogithub.com/periodical/volume/69/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

**Comment by betterRunner** [comment]
@betterRunner 感谢博主提供这么好的平台！已star项目并告知小伙伴前来围观。
另外有个小请求就是[目前期刊展示的gif图](https://raw.githubusercontent.com/521xueweihan/img2/master/hellogithub/69/img/context-note.gif)分辨率有点模糊（主要是我的原mp4文件夹比较大），请问能否替换成我现在的[这一个](https://user-images.githubusercontent.com/7123136/147523960-66b8645e-d385-43b2-805b-78b58285ae21.gif)清晰一点的？非常感谢！
