### ISSUE TITLE
项目自荐 | TG Catbox Uploader Bot

### ISSUE THREAD

**Issue by AnotiaWang** [521xueweihan/HelloGitHub#1989]
## 项目推荐
- 项目地址：https://github.com/AnotiaWang/TG_Catbox_Uploader

- 类别：JavaScript

- 项目后续更新计划：支持转换 ..tgs 文件为 gif；解决多下载任务冲突的问题

- 项目描述：

  这是我学习 Node.js 过程中的一个练手小作品。

  - 可将 Telegram 的文件上传到 <a href="https://catbox.moe">Catbox.moe</a> 或 <a href="https://litterbox.catbox.moe">Litterbox</a>。

  - 支持多语言，可以在 `strings.json` 中自行修改或添加新语言；

  - 支持私聊 / 群组调用；

  - 支持自定义一些参数，如 Litterbox 的文件过期时限、用户语言、WebHook 等。配置文件借助 cron 定期保存。

- 推荐理由：

  1. 易于部署；

  2. 可以用来快速下载贴纸和 GIF；

  3. 可以在群组中快速下载文件。

- 截图：
![anj5bk](https://user-images.githubusercontent.com/62269186/143809858-d06ca0a6-9f01-4662-b8cf-d348830c97da.gif)

**Comment by 521xueweihan** [comment]
@AnotiaWang 不好意思，为了本项目的长治久安 TG 相关的项目，无法收录。
