### ISSUE TITLE
MovieHeavens

### ISSUE THREAD

**Issue by lt94** [521xueweihan/HelloGitHub#199]
## 项目推荐
- 项目名称：MovieHeavens

- 项目地址：https://github.com/lt94/MovieHeavens

- 项目语言：Python2

- 项目描述：为了避免找电影期间的各种广告,以及各种页面跳转

- 推荐理由：实用性

- 示例代码：

- 截图：

![](http://ww2.sinaimg.cn/large/d9e82fa4jw1f7nembhbr1g20dq09nna1.gif)

**Comment by 521xueweihan** [comment]
@lt94  您推荐的项目，已成功收录在 [HelloGitHub 第 24 期](https://hellogithub.com/volume/24/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
