### ISSUE TITLE
自荐项目 | Addax - 开源的通用数据采集工具

### ISSUE THREAD

**Issue by wgzhao** [521xueweihan/HelloGitHub#1990]
## 项目推荐
- 项目地址：https://github.com/wgzhao/addax

- 类别：Java

- 项目后续更新计划：

- 项目描述：
  - 必写：Addax 是一个异构数据源离线同步工具(ETL)，最初来源于阿里的 DataX ，致力于实现包括关系型数据库(MySQL、PostgreSQL、Oracle 等)、NoSQL(Redis，MongoDB， HBase 等)，分布式数据库(Hive, Cassandra, InfluxDB 等)，分布式文件系统以及其他主流 异构数据源之间稳定高效的数据同步功能。相比原来的的版本，修复了大量的bug并新增了大量的读取插件和写入插件，[这里详细描述了两者的区别](https://github.com/wgzhao/Addax/blob/master/difference.md)
  - 可选：主要用户数据中心离线采集各类数据到数据仓库或者大数据平台
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：采集速度快；支持的数据源丰富，几乎支持市面上主流的所有关系型和非关系型数据库；更新频繁，每三周发布一个版本；有详细的中文文档(https://wgzhao.github.io/Addax/develop/)
以下是当前支持的数据库：
![img](https://github.com/wgzhao/Addax/raw/master/docs/images/supported_databases.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 69 期](https://hellogithub.com/periodical/volume/69/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
