### ISSUE TITLE
自动删除 PC 端微信缓存数据 CleanMyWechat

### ISSUE THREAD

**Issue by blackboxo** [521xueweihan/HelloGitHub#1992]
## 项目推荐
- 项目地址：仅收录 GitHub 的开源项目，请填写 GitHub 的项目地址
https://github.com/blackboxo/CleanMyWechat
- 类别：请从中选择（C、C#、C++、CSS、Go、Java、JS、Kotlin、Objective-C、PHP、Python、Ruby、Swift、其它、书籍、机器学习）
Python
- 项目后续更新计划：
支持 Mac 版本，支持企业微信，支持后台常驻
- 项目描述：
  - 必写：这是个什么项目、能用来干什么、有什么特点或解决了什么痛点
  - 可选：适用于什么场景、能够让初学者学到什么
  - 描述长度（不包含示例代码）: 10 - 256 个字符
自动删除 PC 端微信缓存数据，包括从所有聊天中自动下载的大量文件、视频、图片等数据内容，解放一年几十 G 的空间占用。
适用于 Python 初学者练手，学习文件操作，多线程等知识。
- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？
最近发现微信占用电脑很多空间的人越来越多，该工具能够方便用户清理微信缓存，特别地，针对客服类、有多个微信、离职等人员适用。
- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg
![image](https://user-images.githubusercontent.com/18532207/144226996-a23d45f3-7413-486f-aa74-cb9a4bf90bef.png)

## 提示（提交时请删除以下内容）
> 点击上方 “Preview” 更方便地阅读以下内容，

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
