### ISSUE TITLE
vue-admin-box

### ISSUE THREAD

**Issue by cmdparkour** [521xueweihan/HelloGitHub#1993]
## 项目推荐
- 项目地址：https://github.com/cmdparkour/vue-admin-box
- 预览地址：http://vue-admin-box.51weblove.com

- 类别：JS/TS/VUE3

- 项目后续更新计划：核心目标，打造一个上手快、源码简洁易读的vue3中后台开源项目，解决之前的社区未解决的问题

- 项目描述：
vue-admin-box是一个免费并且开源的中后台管理系统模板。使用最新版本的vue3+vite+element-plus开发而成，目的是为了解决通用型的业务中后台系统复杂的配置。

- 推荐理由：从易读性来说，大部分代码都没有设计得很复杂，大部分JS用户均能快速理解其中的逻辑，而且有大量的手写功能供大家参考使用。从功能上来说，国际化、多模板（4套基础模板）、多主题（主题可自行扩展）、keep-alive不需要写name值（之前社区中后台的都需要写）。

- 截图：
<p align="center">
    <img src="http://blog.51weblove.com/wp-content/uploads/2021/08/QQ截图20210810174824.png">
    <img src="http://blog.51weblove.com/wp-content/uploads/2021/08/QQ截图20210810174848.png">
    <img src="http://blog.51weblove.com/wp-content/uploads/2021/08/QQ截图20210810174923.png">
    <img src="http://blog.51weblove.com/wp-content/uploads/2021/08/QQ截图20210810174940.png">
    <img src="http://blog.51weblove.com/wp-content/uploads/2021/08/QQ截图20210810175009.png">
</p>

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
