### ISSUE TITLE
tabby: A terminal for a more modern age

### ISSUE THREAD

**Issue by buppter** [521xueweihan/HelloGitHub#1995]
## 项目推荐
- 项目地址：https://github.com/Eugeny/tabby

- 类别：TypeScript

- 项目描述：
  - 必写：Tabby is an infinitely customizable cross-platform terminal app for local shells, serial, SSH and Telnet connections.

- 推荐理由：极简的UI风格，有多种主题可以供选择。支持SSH, SFTP, Telnet，serial。并且有插件系统，能实现更强大的功能，跨平台支持

- 截图：
![image](https://user-images.githubusercontent.com/43202996/144579118-88eea2c2-15a5-46a8-b115-a4259f9df6cc.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 69 期](https://hellogithub.com/periodical/volume/69/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
