### ISSUE TITLE
https://github.com/Rajaniraiyn/windows11

### ISSUE THREAD

**Issue by iamzhz** [521xueweihan/HelloGitHub#1998]
## 项目推荐
- 项目地址：仅收录 GitHub 的开源项目，请填写 GitHub 的项目地址

- 类别：请从中选择（C、C#、C++、CSS、Go、Java、JS、Kotlin、Objective-C、PHP、Python、Ruby、Swift、其它、书籍、机器学习）

- 项目后续更新计划：

- 项目描述：
  - 必写：这是个什么项目、能用来干什么、有什么特点或解决了什么痛点
  - 可选：适用于什么场景、能够让初学者学到什么
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

## 提示（提交时请删除以下内容）
> 点击上方 “Preview” 更方便地阅读以下内容，

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！

**Comment by iamzhz** [comment]
@521xueweihan 您好，

我是iamzhz，之前提交了#1998号issue。我注意到我的issue被标记为“恶意issue”并已经关闭。在此，我想解释一下当时的情况，并请求您重新考虑这个标签。

当我提交这个issue时，我的本意是想分享标题所指的项目。由于我当时对GitHub的使用不太熟悉，可能没有遵循正确的格式或提交流程。我没有意识到这可能会给项目带来不便，对此我深表歉意。

我理解每个项目都有自己的规则和标准，我完全尊重这些规则。如果可能的话，我恳请项目维护者考虑移除这个标签，因为它可能没有准确地反映我的意图或行为。

如果需要我提供更多信息或采取其他行动，请随时告知。我非常愿意配合，以确保我的参与符合项目的要求。

感谢您的时间和考虑。

此致，
iamzhz

**Comment by 521xueweihan** [comment]
@iamzhz 我已收到您的反馈，“恶意issue”标签已移除，您遇到的问题将在网站完成国际化后解决。
