### ISSUE TITLE
很激动能遇到想法一致的人！！

### ISSUE THREAD

**Issue by bawangxx** [521xueweihan/HelloGitHub#20]
我做了一个网站，目前正在完善中。网址：http://www.haocode123.com
和一个app：https://itunes.apple.com/us/app/%E5%A5%BD%E6%BA%90%E7%A0%81/id1220481838?l=zh&ls=1&mt=8

希望有机会我们可以合作，一起搞大我的QQ：525713029
微信：xiaozhi19921222

**Comment by alihanniba** [comment]
PHP写的？

**Comment by arronf2e** [comment]
@bawangxx 不错不错，晚上加你交个朋友

**Comment by bawangxx** [comment]
@alihanniba 后台接口用php写得

**Comment by alihanniba** [comment]
@bawangxx 可以可以，缺人手 不

**Comment by bawangxx** [comment]
@alihanniba 缺啊，欢迎加入，哈哈

**Comment by 521xueweihan** [comment]
@bawangxx 你好，我尝试加你的微信，提示微信号错误。

**Comment by bawangxx** [comment]
@521xueweihan QQ号应该可以搜到，或者17600201035，或者我加你哦
