### ISSUE TITLE
dynamo.cli 用SQL操作aws dynamoDB

### ISSUE THREAD

**Issue by FrontMage** [521xueweihan/HelloGitHub#200]
## 项目推荐
- 项目名称：dynamo.cli

- 项目地址：https://github.com/FrontMage/dynamo.cli

- 项目语言：golang

- 项目描述：用SQL操作aws dynamoDB

- 推荐理由：如果大家用dynamoDB又记不住那个蹩脚的aws cli，可以试试这个

- 示例代码：这是一个prompt，并不能当lib用

- 截图：![Screenshot](https://github.com/FrontMage/dynamo.cli/blob/master/screenshots/screenshot.gif?raw=true)

**Comment by 521xueweihan** [comment]
@FrontMage  您推荐的项目，已成功收录在 [HelloGitHub 第 25 期](https://hellogithub.com/volume/25/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
