### ISSUE TITLE
英语小助手机器人

### ISSUE THREAD

**Issue by hdcola** [521xueweihan/HelloGitHub#2002]
## 项目推荐
- 项目地址：https://github.com/HDCodePractice/EnglishHelper

- 类别：Python

- 项目后续更新计划：

- 项目描述：
  - 使用一个Telegram bot帮助记忆单词、查字典、发音、语法，是一位ESL学习者开发的学习工具
  - 可选：学习英语、telegram bot开发
  - 描述长度（不包含示例代码）: 

- 推荐理由：运用了国外ESL学校的学习方法，广泛利用了诸多互联网资源

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

## 提示（提交时请删除以下内容）
> 点击上方 “Preview” 更方便地阅读以下内容，

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
