### ISSUE TITLE
『自荐』中文播客和newsletter

### ISSUE THREAD

**Issue by alaskasquirrel** [521xueweihan/HelloGitHub#2004]
[Chinese-Podcasts](https://github.com/alaskasquirrel/Chinese-Podcasts)&[Email-newsletter-RSS](https://github.com/alaskasquirrel/Email-newsletter-RSS)
虽说通过阮一峰科技爱好者周报的介绍，获得了不少关注，但参与分享者屈指可数，日常都是本人在更新。希望HelloGitHub能够呼吁一下。

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
