### ISSUE TITLE
Traffic Monitor是一款用于Windows平台的网速监控悬浮窗软件

### ISSUE THREAD

**Issue by leioulin** [521xueweihan/HelloGitHub#2005]
## 项目推荐
- 项目地址：仅收录 GitHub 的开源项目，请填写 GitHub 的项目地址

- 类别：请从中选择（C#）

- 项目后续更新计划：

- 项目描述：
  - 必写：Traffic Monitor是一款用于Windows平台的网速监控悬浮窗软件，可以显示当前网速、CPU及内存利用率，支持嵌入到任务栏显示，支持更换皮肤、历史流量统计等功能。
  - 可选：适用于什么场景、能够让初学者学到什么
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：
- 显示当前实现网络传输速率、CPU和内存占用率
如果电脑有多个网卡，支持自动和手动选择网络连接
查看网络详细信息
支持嵌入到任务栏显示
支持更换皮肤和自定义皮肤
历史流量统计

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

**Comment by lingr7** [comment]
虽然这个推荐被关闭了。
但是，这个项目确实还是不错的，目前有21k以上的star了。
https://github.com/zhongyang219/TrafficMonitor

**Comment by 521xueweihan** [comment]
@lingr7 感谢推荐，该项目月刊收录过了。
