### ISSUE TITLE
Traffic Monitor是一款用于Windows平台的网速监控悬浮窗软件

### ISSUE THREAD

**Issue by leioulin** [521xueweihan/HelloGitHub#2006]
## 项目推荐
- 项目地址：https://github.com/zhongyang219/TrafficMonitor

- 类别：C#

- 项目后续更新计划：

- 项目描述：
  - 必写：Traffic Monitor是一款用于Windows平台的网速监控悬浮窗软件，可以显示当前网速、CPU及内存利用率，支持嵌入到任务栏显示，支持更换皮肤、历史流量统计等功能。
  - 可选：适用于什么场景、能够让初学者学到什么
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：显示当前实现网络传输速率、CPU和内存占用率
如果电脑有多个网卡，支持自动和手动选择网络连接
查看网络详细信息
支持嵌入到任务栏显示
支持更换皮肤和自定义皮肤
历史流量统计

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

**Comment by 521xueweihan** [comment]
感谢您的推荐该项目已经推荐过：https://hellogithub.com/periodical/search/?q=https://github.com/zhongyang219/TrafficMonitor
