### ISSUE TITLE
使用具有良好声明性 API 的 JS/TS 轻松生成 .docx 文件。适用于 Node 和浏览器。

### ISSUE THREAD

**Issue by Julycc41** [521xueweihan/HelloGitHub#2008]
项目地址：
https://github.com/dolanmiu/docx

类别：react  Angular vue html

项目描述：一个基于Flutter的开源在线笔记工具

推荐理由：使用具有良好声明性 API 的 JS/TS 轻松生成 .docx 文件。适用于 Node 和浏览器

演示项目 
https://github.com/dolanmiu/docx/tree/master/demo

api：https://docx.js.org/#/

截图
![1639108797(1)](https://user-images.githubusercontent.com/80231740/145515070-a819fcc8-ad35-4b7b-8700-f34122e06412.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
