### ISSUE TITLE
开源android投屏tool

### ISSUE THREAD

**Issue by maceaykk** [521xueweihan/HelloGitHub#2009]
## 项目推荐
- 项目地址：https://github.com/Genymobile/scrcpy

- 类别：C、java

- 项目后续更新计划：

- 项目描述：
  - 必写：Display and control your Android device 
  - 可选：适用于什么场景、能够让初学者学到什么
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：开源的android手投屏工具
- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

**Comment by 521xueweihan** [comment]
感谢您的推荐，该项目已经推荐过了。
