### ISSUE TITLE
申请收录开源项目 swiftadmin极速后台开发框架

### ISSUE THREAD

**Issue by meystack** [521xueweihan/HelloGitHub#2013]
## 项目推荐
- 项目地址：https://github.com/meystack/swiftadmin

- 类别：php

- 项目后续更新计划：每月迭代更新

- 项目描述：
  - 必写：基于THINKPHP6 layui2.6的极速后台开发框架
  - 可选：适合后台的快速开发，基于ant design设计，封装大量特性，
  - 描述长度（不包含示例代码）: 基于ThinkPHP Layui 完美契合，在开发上采用最精简最高效的做法去完成业务系统的需求，是一款优秀的中后台极速开发解决方案。

- 推荐理由：界面设计合理，封装大量特性，支持细粒度权限

- 示例代码：（可选）长度：；；；这写不写的，UP主自己看下抄录下您喜欢的就行

- 截图：（可选）

## 提示（提交时请删除以下内容）
> 点击上方 “Preview” 更方便地阅读以下内容，

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
