### ISSUE TITLE
项目推荐 | Antv/S2 基于Canvas的高性能多维分析表格

### ISSUE THREAD

**Issue by wjgogogo** [521xueweihan/HelloGitHub#2019]
## 项目推荐
- 项目地址：https://github.com/antvis/S2
- 官网地址：https://github.com/antvis/S2

- 类别: TS

- 项目后续更新计划：
`1.0`正式版已发布，更多分析组件和功能正在持续完善中。

- 项目描述：
  Antv/S2 是基于 canvas 开发的高性能多维交叉分析表格工具（表格是 BI 领域中重要的数据分析工具，几乎是中国式报表中必定会使用到的工具之一）

- 推荐理由：
   - S2 是多维交叉分析领域的表格解决方案，数据驱动视图，提供底层核心库、基础组件库、业务场景库，具备自由扩展的能力，让开发者既能开箱即用，也能基于自身场景自由发挥
   - S2 官网提供了详细的使用文档，丰富的使用示例以及在线 playground，极大降低了开发者的使用门槛和上手难度
   - S2 通过按需渲染、虚拟滚动等方式，保证了在百万级数据量下秒级渲染和滚动不卡顿的流畅体验，极限测试下 100w 的数据也能正常渲染

- 示例代码：
```js
import { PivotSheet } from "@antv/s2";

const container = document.getElementById("container");

const s2DataCfg = {
  describe: "标准交叉表数据。",
  fields: {
    rows: ["province", "city"],
    columns: ["type", "sub_type"],
    values: ["number"],
    valueInCols: true,
  },
  meta: [
    {
      field: "number",
      name: "数量",
    },
    {
      field: "province",
      name: "省份",
    },
    {
      field: "city",
      name: "城市",
    },
    {
      field: "type",
      name: "类别",
    },
    {
      field: "sub_type",
      name: "子类别",
    },
  ],
  data: [
    {
      number: 7789,
      province: "浙江省",
      city: "杭州市",
      type: "家具",
      sub_type: "桌子",
    },
    {
      number: 2367,
      province: "浙江省",
      city: "绍兴市",
      type: "家具",
      sub_type: "桌子",
    },
    {
      number: 3877,
      province: "浙江省",
      city: "宁波市",
      type: "家具",
      sub_type: "桌子",
    },
    {
      number: 4342,
      province: "浙江省",
      city: "舟山市",
      type: "家具",
      sub_type: "桌子",
    }
  ],
};

const s2Options = {
  width: 600,
  height: 480,
};
const s2 = new PivotSheet(container, s2DataCfg, s2Options);

s2.render();

```

- 截图：
  - 表格：
![screely-1639639053480](https://user-images.githubusercontent.com/17964556/146325451-b8bdefa5-28b2-4428-b64d-dfe328e53719.png)
![screely-1639639120680](https://user-images.githubusercontent.com/17964556/146325573-b51c3d61-af93-4a87-9f40-1d9fc11f6c6f.png)
![screely-1639639202551](https://user-images.githubusercontent.com/17964556/146325773-e72ca235-e514-48b7-8e64-f0442bb4b317.png)
 - 性能表现：
![performace](https://user-images.githubusercontent.com/17964556/146324527-fd9ad7e6-0569-45d5-9171-62669551687a.gif)

  - 官网：
![screely-1639639333963](https://user-images.githubusercontent.com/17964556/146326060-05423e45-9aa3-44ba-a716-d8413ab293a0.png)

  - 在线示例：
![screely-1639639292977](https://user-images.githubusercontent.com/17964556/146325998-b5acfa1e-365f-4346-a7c2-7a8139efa2c0.png)

**Comment by hustcc** [comment]
- 中英文空格
- 不是领域中的人，get 不到表格重要，介绍中可以加一小段文字介绍背景（比如：国内特色的数据报表中表格的占比 xx%）
- 性能对比数据精炼一下，可以贴一下

**Comment by xingwanying** [comment]
* 官网截图用下https://www.screely.com/ 可以稍微精致些 0, 0
* 可以贴下性能demo的效果截图

**Comment by 521xueweihan** [comment]
@wjgogogo 您推荐的项目，**已成功发布**在 [HelloGitHub 第 69 期](https://hellogithub.com/periodical/volume/69/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
