### ISSUE TITLE
基于Scrapy+Redis实现的高可用分布式IP代理池

### ISSUE THREAD

**Issue by ResolveWang** [521xueweihan/HelloGitHub#202]
## 项目推荐
- 项目名称：HAipproxy

- 项目地址：https://github.com/SpiderClub/haipproxy

- 项目语言：Python

- 项目描述：使用Scrapy＋Redis实现的高可用分布式IP代理池，为大型分布式爬虫提供高可用低延迟的代理IP资源

- 推荐理由：（１）和同类项目相比，HAipproxy实现得更加优雅，且天然支持高可用部署，支持任务路由（２）免费代理IP质量往往不好，但是本项目根据特定的算法策略从高度不可用的资源中提取出高可用的代理IP，这也是本项目和其它同类项目相比的核心竞争力。使用它可以在单机的情况下达到每小时一万以上的请求量，这种速度是很多收费的代理提供商也没做到的（３）文档丰富，写了若干开发者文档以帮助用户更好地使用它

- 示例代码：examples见[examples/zhihu](https://github.com/SpiderClub/haipproxy/tree/master/examples/zhihu)

- 截图：
以知乎为目标抓取网站，该代理IP池的实际性能测试结果如下

![benchmark_result](https://user-images.githubusercontent.com/8018776/36945033-c9a2b812-1fe2-11e8-95eb-1d7418f1371f.png)

**Comment by 521xueweihan** [comment]
@ResolveWang 您推荐的项目，已成功收录在 [HelloGitHub 第 24 期](https://hellogithub.com/volume/24/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
