### ISSUE TITLE
[自荐项目] 可定制化的二维码生成工具

### ISSUE THREAD

**Issue by yeqown** [521xueweihan/HelloGitHub#2020]
## 项目推荐
- 项目地址：https://github.com/yeqown/go-qrcode

- 类别：Go

- 项目后续更新计划：
   - 调研WASM支持的可行性；
   - 日常维护；

- 项目描述：

这是一个用于生成二维码的工具库，支持输出到 Stream / File / Terminal, 还可以定制化。

- 推荐理由：支持高度定制化输出，目前 standard Writer 实现了常用的对于输出图片的可选参数，并持续补充当中；如果有特殊的需求，完全可以自己实现 Writer 控制二维码图片的输出。

- 示例代码：

```go
package main

import (
	"github.com/yeqown/go-qrcode/v2"
	"github.com/yeqown/go-qrcode/writer/standard"
)

func main() {
	qrc, err := qrcode.New("https://github.com/yeqown/go-qrcode")
	if err != nil {
		fmt.Printf("could not generate QRCode: %v", err)
		return
	}
	
	w, err := standard.New("../assets/repo-qrcode.jpeg")
	if err != nil {
		fmt.Printf("standard.New failed: %v", err)
		return
	}
	
	// save file
	if err = qrc.Save(w); err != nil {
		fmt.Printf("could not save image: %v", err)
	}
}
```

- 截图：

![image](https://user-images.githubusercontent.com/27146233/146316617-8b2e5da8-76eb-42e2-861e-53fb3300369e.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
