### ISSUE TITLE
【项目推荐】一个轻量的 Web IDE UI 框架 - Molecule

### ISSUE THREAD

**Issue by wewoor** [521xueweihan/HelloGitHub#2029]
<div align="center">
 <img src="https://user-images.githubusercontent.com/2766811/146497934-b619b3a0-dec9-44ef-805b-f69883107caf.png" width="20%" height="20%" alt="watchman-logo" />
 <h1>Molecule</h1>
 <h3>A lightweight Web IDE UI Framework</h3>

[![CI][ci-image]][ci-url] [![Codecov][codecov-image]][codecov-url] [![NPM downloads][download-img]][download-url] [![NPM version][npm-version]][npm-version-url]
</div>

[ci-image]: https://github.com/DTStack/molecule/actions/workflows/main.yml/badge.svg
[ci-url]: https://github.com/DTStack/molecule/actions/workflows/main.yml
[codecov-image]: https://codecov.io/gh/DTStack/molecule/branch/main/graph/badge.svg?token=PDjbCBo6qz
[codecov-url]: https://codecov.io/gh/DTStack/molecule
[download-img]: https://img.shields.io/npm/dm/@dtinsight/molecule.svg?style=flat
[download-url]: https://www.npmjs.com/package/@dtinsight/molecule
[npm-version]: https://img.shields.io/npm/v/@dtinsight/molecule.svg?style=flat-square
[npm-version-url]: https://www.npmjs.com/package/@dtinsight/molecule

## 项目推荐 - Molecule
- 项目地址：https://github.com/DTStack/molecule

- 类别：`JS`

- 项目后续更新计划：

添加 Jupyter 扩展、更丰富的布局、更简单的自定义方式

- 项目描述：
  - 必写：一个轻量的 Web IDE UI 框架
  - 可选：搭建 Web IDE , 或者 类 IDE 交互场景的 Web  应用，例如**数据库管理客户端**等等
  - 描述长度（不包含示例代码）: Molecule 是一款受 VSCode 启发，使用 React.js 构建的 Web IDE UI 框架。我们设计了类似 VSCode 的扩展（Extension)机制，可以帮助我们使用 React 组件快速完成对 Workbench 的自定义。Molecule 与 React 项目集成非常方便，我们已经在 DTStack 多个产品、项目中使用。

- 推荐理由: 轻松实现 VS Code IDE UI 交互，兼容上千种主题；React.js 无缝接入；自由扩展

- 示例代码：（可选）长度：
```ts
import React from 'react';
import ReactDOM from 'react-dom';
import { MoleculeProvider, Workbench } from '@dtinsight/molecule';
import '@dtinsight/molecule/esm/style/mo.css';

const App = () => (
    <MoleculeProvider extensions={[]}>
        <Workbench />
    </MoleculeProvider>
);

ReactDOM.render(<App />, document.getElementById('root'));
```

- 截图

![image](https://user-images.githubusercontent.com/2766811/146787833-9aa5bc7e-dcf9-4736-85a8-cb569dbc5793.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
