### ISSUE TITLE
基于TensorFlow/Pytorch/Theano的AlphaZero算法（应用于五子棋）

### ISSUE THREAD

**Issue by junxiaosong** [521xueweihan/HelloGitHub#203]
## 项目推荐
- 项目名称：
AlphaZero_Gomoku

- 项目地址：
https://github.com/junxiaosong/AlphaZero_Gomoku

- 项目语言：
Python

- 项目描述：
An implementation of the AlphaZero algorithm for Gomoku (also called Gobang or Five in a Row)

- 推荐理由：
使用TensorFlow/Pytorch/Theano实现AlphaZero算法，通过自我对弈从零训练五子棋AI。实现简单清晰，适合学习了解AlphaGo Zero背后的关键思想和技术细节。

- 示例代码：
python human_play.py 
python train.py

- 截图：
![playout400](https://raw.githubusercontent.com/junxiaosong/AlphaZero_Gomoku/master/playout400.gif)

**Comment by 521xueweihan** [comment]
@junxiaosong   您推荐的项目，已成功收录在 [HelloGitHub 第 26 期](https://hellogithub.com/periodical/volume/26/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
