### ISSUE TITLE
【项目自荐】vue3-win10   web的win10模拟框架

### ISSUE THREAD

**Issue by royalknight56** [521xueweihan/HelloGitHub#2033]
## 项目推荐
- 项目地址：[https://github.com/royalknight56/vue3-win10](https://github.com/royalknight56/vue3-win10)

- 类别：JS

- 项目后续更新计划：更加完善的功能，更加新颖的应用示例

- 项目描述：
  - 必写：一个在web端运行的win10UI框架，使用vite+vue3构建
  - 可选：适用于新形式的UI界面，管理系统等。
  - 描述长度（不包含示例代码）: 已经部署到npm，npm install vue3-win10 --save安装

- 推荐理由：本框架可以让你的页面像win10视窗系统一样，变为一个网页上的win10系统。项目采用目前前端最新的vue3，typescript开发。还在积极迭代中

- 示例代码：
```js
let window = new DragWindow({
      title: '浏览器',
      icon: brow,
      width: 600,
      height: 500,
      x:0,
      y:0,
      content: Test3
    })
window.show()
```

- 截图：
- 
![IMAGE](https://raw.githubusercontent.com/royalknight56/vue3-win10/master/rdmassert/open.gif)
![IMAGE](https://raw.githubusercontent.com/royalknight56/vue3-win10/master/rdmassert/wintmp.gif)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
