### ISSUE TITLE
把验证码做成射击游戏，这还是第一个

### ISSUE THREAD

**Issue by xujanus** [521xueweihan/HelloGitHub#2036]
## 项目推荐
- 项目地址：https://github.com/vivirenremoto/doomcaptcha

- 类别：JS+HTML

- 项目描述：
  - 必写：这块一款用游戏的方式做的一款验证码
  - 描述长度（不包含示例代码）: 可能是第一款使用射击游戏的形式来实现验证码功能的项目，这是demo:地址https://vivirenremoto.github.io/doomcaptcha/

- 推荐理由：
你见过哪些验证码？数字？图像？算数？拼图？

这些都太普通了！能不能用游戏的方式做一款验证码呢？

今天就给大家推荐一个开源项目：doomcaptcha

doom，可能年轻点的小伙伴不清楚，但是在我小时候，doom及其制作小组都是神一样的存在，doom是当时最最流行的第一人称射击游戏，doom之父就是那位搞出快速平方根算法的约翰·卡马克。

想必作者采用doom作为验证码的原型，也是一种致敬！

项目非常有创意的将验证码和初代doom游戏结合在了一起，如果要完成验证，就需要在页面上使用当年doom的那把手枪干掉四个随机出现的doom小怪物就行了。

不过如果你打的太慢，可是要不合格的哟，因为作者还加入了倒计时模式，要在规定的时间里打完四个小怪物哟！

并且每一次出现的怪物和场景都是随机的，让你每一次输入验证码都是不一样的感受，真是让人欲罢不能！
- 截图：
https://blog.didispace.com/images/pasted-782.png
https://blog.didispace.com/images/pasted-783.png

PS.以上部分图文转自：https://blog.didispace.com/tj-opensource-doomcaptcha/

**Comment by 521xueweihan** [comment]
@xujanus 您推荐的项目，**已成功发布**在 [HelloGitHub 第 69 期](https://hellogithub.com/periodical/volume/69/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
