### ISSUE TITLE
【开源自荐】一个自己开发的鸭子操作系统YiYiYa

### ISSUE THREAD

**Issue by evilbinary** [521xueweihan/HelloGitHub#2037]
## 项目推荐
- 项目地址：https://github.com/evilbinary/YiYiYa

- 类别：C

- 项目后续更新计划：
 
1、移植新架构，支持riscv、esp32板子等；
2、添加新的stm32 驱动，如lcd驱动、gpio驱动等。
3、添加新的app应用示例。

- 项目描述：
  - 必写：这是一个自己开发的鸭子操作系统YiYiYa
  - 可选：主要用于操作系统学习（x86、arm、xtensa等）
  - 描述长度（不包含示例代码）:  支持qemu和实际开发板子运行

- 推荐理由：从0开始写操作系统，包括桌面gui、文件系统fs、内存管理mm、进程调度process、驱动开发、elf加载运行等等。代码简洁，适合新手学习和理解，尽量使用最少的汇编，增加阅读的可理解性。

- 示例代码：（可选）长度：1-20 行

```c
int kmain(int argc, char* argv[]) {
  kernel_init();
  kprintf("module regist\n");
  module_regist(&serial_module);
  module_regist(&i2c_module);
  module_regist(&gpio_module);
  module_regist(&spi_module);
  module_regist(&gpu_module);
  module_regist(&mouse_module);
  module_regist(&sdhci_module);
  module_regist(&devfs_module);
  module_regist(&fat_module);

  thread_t* t0 = thread_create_name("serial",(u32*)&do_serial_thread,NULL);
  thread_t* t1 = thread_create_name("shell",(u32*)&do_shell_thread,NULL);

  kprintf("thread run\n");
  thread_run(t0);
  thread_run(t1);
  kprintf("kernel run\n");
  kernel_run();

  return 0;
}
```

- 截图：

<img src="https://github.com/evilbinary/YiYiYa/blob/main/docs/demo/etk-gui.jpeg?raw=true" width="800px" />

https://user-images.githubusercontent.com/5143386/133922735-972ddceb-eab6-4102-b9a2-2e14e7d86397.mp4

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
