### ISSUE TITLE
【开源自荐】一个对标 C++ STL 库的 javascript 数据结构库

### ISSUE THREAD

**Issue by ZLY201** [521xueweihan/HelloGitHub#2047]
## 项目推荐

- 项目地址：https://github.com/ZLY201/js-sdsl

- 类别：JS

- 项目后续更新计划

  - 持续进行优化，包括但不限于语法优化以及算法优化，预期某些容器比目前提升 5 个百分点
  - 对各个容器进行抽象，使其更加符合社区规范
  - 增加更加健壮的性能测试，对各个浏览器进行兼容性测试

- 项目描述

  - 一个对标 C++ STL 库的 javascript 数据结构库
  - 适用于各种需要用到高级数据结构的场景，支持大多数浏览器，包括 IE8+

- 推荐理由

  - 我们对各个容器进行了严格的单元测试，运行正确性和时间复杂度有严格保证
  - 使用闭包的形式在 es5 中实现了对象 的 private 属性
  - [目前该项目在 npm 上正式版本（2.0.0）已发布](https://www.npmjs.com/package/js-sdsl)，下载量已达到 10000+

- 示例代码

  ```html
  <!-- you can download the file locally and import it or import it dynamically by using url. -->
  <script src="https://zly201.github.io/js-sdsl/js-sdsl.min.js"></script>
  <script>
      const { Vector } = sdsl;
      const myVector = new Vector();
      // you code here...
  </script>
  ```

**Comment by 521xueweihan** [comment]
@ZLY201 
https://github.com/tinyplex/tinybase

能否对比下这个项目的差别和优势

**Comment by ZLY201** [comment]
> @ZLY201 https://github.com/tinyplex/tinybase
> 
> 能否对比下这个项目的差别和优势

我跟这个好像目标不太一样，这是一个状态管理库，用于构建程序状态，js-sdsl 是从底层对高级数据结构的实现

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 70 期](https://hellogithub.com/periodical/volume/70/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
