### ISSUE TITLE
img-previewer 动画丝滑的js图片预览插件

### ISSUE THREAD

**Issue by yue1123** [521xueweihan/HelloGitHub#2048]
## 项目推荐
- 项目地址：https://github.com/yue1123/img-previewer
- 预览地址: https://yue1123.github.io/img-previewer/demo/index.es.html
- 类别：Typescript, Scss, Javascript

- 项目后续更新计划：

- 项目描述：
轻量且强大的 javascript 图片预览插件,丝滑的动画让你可以优雅的预览你的网站中的图片。开箱即用,你无需多余的配置(默认情况下)或改变页面 html 代码结构,即可在任何类型的网站中轻松启用该插件,升级你的用户体验

- 推荐理由：丝滑的动画(最高可达120fps), 使用简单且无需改变任何代码结构, 多语言支持

- 截图：（可选）gif/png/jpg
![image](https://user-images.githubusercontent.com/61490799/147458624-f870973f-8a7d-46a9-921e-be7b835a4e58.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
