### ISSUE TITLE
启发式 Python 自动化办公

### ISSUE THREAD

**Issue by PY-GZKY** [521xueweihan/HelloGitHub#2049]
## 项目推荐
- 项目地址：[启发式 Python 自动化办公](https://github.com/PY-GZKY/python-automation-docs)

- 类别：Python、自动化办公

- 项目后续更新计划：持续更新和完善

- 项目描述：Python 自动化办公 最佳实践、Automation、Office、Pandas、SQL、Selenium、Puppeteer、Crawl、NLP

- 推荐理由：《 启发式 Python 自动化办公 》本文档是作者从事 Python 以来的学习历程， 重点是 Python 在自动化方面的一些主要的应用场景。希望能给予读者一份比较全面的自动化文档、一个比较舒适的阅读环境。 如果本文档对你有所帮助，请给予支持！

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
