### ISSUE TITLE
RDM - 自由更改屏幕分辨率

### ISSUE THREAD

**Issue by doyoyob** [521xueweihan/HelloGitHub#205]
## 项目推荐
- 项目名称：RDM

- 项目地址：https://github.com/avibrazil/RDM

- 项目语言：英语

- 项目描述：更改MacBook Retina的分辨率，提供更多的选择。

- 推荐理由：突破系统限定的分辨率，想怎么任性就怎么任性。

- 示例代码：brew cask install avibrazil-rdm

- 截图：
![255a7d74-dff0-11e4-9bf9-16e726336e29](https://user-images.githubusercontent.com/25147482/37217675-7e2e9856-2401-11e8-91b6-9fb55814fd98.png)

**Comment by 521xueweihan** [comment]
@doyoyob 您推荐的项目，已成功收录在 [HelloGitHub 第 25 期](https://hellogithub.com/volume/25/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
