### ISSUE TITLE
【开源自荐】Stay² -  iOS上的Safari插件脚本管理器

### ISSUE THREAD

**Issue by shenruisi** [521xueweihan/HelloGitHub#2051]
## 项目推荐
- 项目地址：https://github.com/shenruisi/Stay

- 类别：Objective-C

- 项目后续更新计划：
Stay²将会成为iOS上为数不多的脚本管理器，除了支持油猴脚本，Stay²也会自建API让用户可以开发更为强大的脚本应用。

- 项目描述：
  - 必写：Stay² 是一个Safari的插件脚本管理器，并且自带内置脚本库，支持App防跳转，恶心广告拦截，自动展开文本等功能。
  - 可选：Stay² 同时也是一个Safari插件开发的样例，包括了主应用开发，插件脚本以及脚本与应用间通信等等技巧。
  - 描述长度（不包含示例代码）:  Stay²是一个开源的iOS本地脚本管理器。

- 推荐理由：
做为AppStore的应用，Stay² 提供了丰富的脚本管理能力，并且实现了在iOS上运行油猴脚本，已被[Airport推荐](https://app.airport.community)
做为插件开发的示例应用Stay²囊括了几乎所有Safari extension开发的技术点。已被[open-source-ios-apps收录](https://github.com/dkhamsing/open-source-ios-apps#safari-extension)

- 截图：
 <img width="310px" src="https://dl.airtable.com/.attachmentThumbnails/3910382dff85b683caa8d34be5b8bde6/a6e5049e"  />

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 70 期](https://hellogithub.com/periodical/volume/70/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

**Comment by shenruisi** [comment]
> 您推荐的项目，**已成功发布**在 [HelloGitHub 第 70 期](https://hellogithub.com/periodical/volume/70/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
> 
> 欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

感谢收录，已赞😄
