### ISSUE TITLE
【开源自荐】🧾 Resume Generator: 在线简历生成器，只需要一份简历数据，即可在线预览、编辑和下载

### ISSUE THREAD

**Issue by visiky** [521xueweihan/HelloGitHub#2053]
## 项目推荐
- 项目地址： https://github.com/visiky/resume

- 类别：JS

- 项目后续更新计划：见 https://github.com/visiky/resume/issues

- 项目描述：一款在线简历生成器，轻松实现在线简历以及下载（支持 PC 端和移动端）。
- 推荐理由：

    无须 fork 仓库，即可在线预览、编辑和下载 PDF 简历.
    
    - 内置三套模板，可以自定义主题颜色、自定义模块；[简历模板1](https://visiky.github.io/resume/?user=visiky)，[简历模板2](https://visiky.github.io/resume/?template=template2&user=visiky)，[简历模板3](https://visiky.github.io/resume/?template=template3&user=visiky)。
    - 支持国际化
    - 支持在线预览，方便随时分享在线简历（简历信息存储在个人仓库）
    - 支持在线编辑简历信息，可导入、导出以及下载 PDF

- 截图：

![image](https://user-images.githubusercontent.com/15646325/147800052-dbbac1ba-8404-4550-92a6-ba39fe5fa718.png)

**Comment by 521xueweihan** [comment]
@visiky 您好，该项目将收到最新一期月刊中，月刊将于本月 28 号发布。

另外，我发现 [Demo 简历](https://visiky.github.io/resume/?user=visiky)上有手机号。我不清楚是不是真实的联系方式，如果是的话建议修改防止给您造成不必要的困扰。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 70 期](https://hellogithub.com/periodical/volume/70/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
