### ISSUE TITLE
【开源自荐】F6 - 移动端图可视化引擎

### ISSUE THREAD

**Issue by openwayne** [521xueweihan/HelloGitHub#2056]
## 项目推荐
- 项目地址：https://github.com/antvis/f6

- 类别：JS

- 项目后续更新计划：提供更多的分析能力及图可视化动画能力

- 项目描述：
  F6 是一款可以快速、流畅运行于移动设备中的图可视化引擎，通过丰富的布局、组件及分析能力，帮助用户落地跨平台的图可视化应用解决方案。在 H5、小程序等移动端平台上，对包体积、性能有更高的要求，也需要定义一套合适的交互模式。针对以上问题，我们在 G6 的基础上重新设计并构建了 F6。F6 不仅具有基础的关联图绘制、事件、动画，同时内置了常用的移动端交互模式、丰富的布局和分析组件，通过简单的配置即可使用。

- 推荐理由：可以方便用户在移动端创建图可视化应用

- 示例代码：https://github.com/antvis/F6/tree/master/packages/examples-alipay

- 截图：
![](https://raw.githubusercontent.com/antvis/F6/master/examples.gif)

**Comment by 521xueweihan** [comment]
@openwayne 篇幅有限，因已收录过 G6 项目，F6 暂不收录。
