### ISSUE TITLE
【开源自荐】mometa: 面向研发的代码可视编码，辅助开发工具

### ISSUE THREAD

**Issue by imcuttle** [521xueweihan/HelloGitHub#2059]
## 项目推荐
- 项目地址：https://github.com/imcuttle/mometa

- 类别：JS

- 项目后续更新计划：
    1. 物料生态支持，开源物料中心化服务
    2. 物料属性解析，可视化编辑器对接
    3. 组件动态化预览支持

- 项目描述：
面向研发的低代码元编程，代码可视编辑，辅助编码工具；适合于所有前端开发场景；
用于研发提效，使用可视化编辑进一步提升研发效率；更好的搭建团队内的物料生态系统；

- 使用场景
1. 新开发一个页面
    - 使用团队开发指令，新增一个空的占位路由 & 页面
    - 进入 mometa，查看本地物料，和远端物料市场，选中自己需要的物料，直接拖拽，基本成型的页面布局完成
    - 进入 ide，完成数据联调，数据传递等，源码开发
2. 已有历史项目，需要迭代功能，只在某一小块 ui 模块内
    - 进入 mometa，物料操作插入
    - 反向定位直接进入 ide 源码开发

- 推荐理由：
🛠 面向研发的代码可视化编辑，直接作用于源码（支持移动端布局，路由模拟）
🍒 开放物料生态，可定制团队内物料库
💎 多语言、多生态支持
🔥 接入友好，Webpack>=4 插件化接入
🌟 无缝兼容接入，不破坏已有项目开发模式

- 截图：
反向定位 (支持从视图定位代码位置)
![](https://github.com/imcuttle/mometa/raw/master/images/mometa-locate.gif)

插入物料
![](https://github.com/imcuttle/mometa/raw/master/images/mometa-insert-material.gif)

删除视图
![](https://github.com/imcuttle/mometa/raw/master/images/mometa-delete.gif)

移动视图
![](https://github.com/imcuttle/mometa/raw/master/images/mometa-move.gif)

编辑代码
![](https://github.com/imcuttle/mometa/raw/master/images/mometa-code-edit.gif)

预览 (路由跳转进行拦截控制，其他和正常预览一致)
![](https://github.com/imcuttle/mometa/raw/master/images/mometa-preview-url.gif)

响应式布局
![](https://github.com/imcuttle/mometa/raw/master/images/mometa-preview-responsive.gif)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 x 期](https://hellogithub.com/periodical/volume/70/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
