### ISSUE TITLE
iina - 媒体播放器

### ISSUE THREAD

**Issue by doyoyob** [521xueweihan/HelloGitHub#206]
## 项目推荐
- 项目名称：iina - 媒体播放器

- 项目地址：https://github.com/lhc70000/iina

- 项目语言：英语，App多国语言

- 项目描述：颜值很高

- 推荐理由：支持很多媒体格式

- 示例代码：brew cask install iina

- 截图：
![256-1](https://user-images.githubusercontent.com/25147482/37217865-175ac946-2402-11e8-8ce9-337d9e3bfa2a.png)

**Comment by 521xueweihan** [comment]
@doyoyob 您推荐的项目，已成功收录在 [HelloGitHub 第 24 期](https://hellogithub.com/volume/24/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
