### ISSUE TITLE
【开源自荐】scihub-cn 基于scihub的中文可用论文下载工具

### ISSUE THREAD

**Issue by Ckend** [521xueweihan/HelloGitHub#2061]
## 项目推荐
- 项目地址：https://github.com/Ckend/scihub-cn

- 类别：Python

- 项目后续更新计划：
- 1.高级搜索
- 2.支持更多的数据源

- 项目描述：
  - 必写：基于Scihub+(百度学术、谷歌学术、publons、science_direct)使用doi，论文标题、bibtex文件或者关键词批量下载论文。
  - 可选：用于无学术资源的大学生做研究、学习。
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：无学术资源的大学生可以用此模块轻松下载论文。

- 示例代码：（可选）长度：1-20 行
```
    def search(self, search_engine, query, limit=10, cookie=''):
        """选择一个搜索引擎搜索内容"""
        if search_engine == SearchEngine.google_scholar:
            return self.search_by_google_scholar(query, limit)
        elif search_engine == SearchEngine.baidu_xueshu:
            return self.search_by_baidu(query, limit)
        elif search_engine == SearchEngine.science_direct:
            return self.search_by_science_direct(query, cookie, limit)
        else:
            return self.search_by_publons(query, limit)
```
- 截图：
![2022010110324742](https://user-images.githubusercontent.com/22796589/148505724-ed9556d4-528c-42c7-9c9c-7ea085a0c9ea.gif)

**Comment by 521xueweihan** [comment]
这个下载器需要挂代理吧

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
