### ISSUE TITLE
Scrcpy-GUI

### ISSUE THREAD

**Issue by zhongweisheng1** [521xueweihan/HelloGitHub#2064]
## 项目推荐
- 项目地址：仅收录 GitHub 的开源项目，请填写 GitHub 的项目地址
https://github.com/zhongweisheng1/Scrcpy-GUI
- 类别：请从中选择（C、C#、C++、CSS、Go、Java、JS、Kotlin、Objective-C、PHP、Python、Ruby、Swift、其它、书籍、机器学习）
Python
- 项目后续更新计划：
有空才更新（节假日、寒暑假、周末）。
- 项目描述：
  - 必写：这是个什么项目、能用来干什么、有什么特点或解决了什么痛点
  - 可选：适用于什么场景、能够让初学者学到什么
  - 描述长度（不包含示例代码）: 10 - 256 个字符
一个 GUI 版的 Scrcpy，解放双手。
- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？
再也不用天天对着终端了。
- 示例代码：（可选）长度：1-20 行
```
start = time.time()
        while Flag:
            QtWidgets.QApplication.processEvents()
            end = time.time()
            if end - start >= 2:
                for index in range(self.A_Devices.rowCount()):
                    self.A_Devices.removeRow(0)
                popen = os.popen(os.path.join(self.ScrcpyPath + "adb.exe") + " devices")
                devices = popen.readlines()
                i = 0
                for line in devices:
                    if line == "List of devices attached\n":
                        break
                    i += 1
                devices = devices[i+1:-1]
                out = []
                for line in devices:
                    out.append(line.strip("\n").split("\t"))

                i = 0
                for Name, State in out:
```
- 截图：（可选）gif/png/jpg

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
