### ISSUE TITLE
line-io

### ISSUE THREAD

**Issue by wolray** [521xueweihan/HelloGitHub#2068]
## 项目推荐
- 项目地址：[line-io](https://github.com/wolray/line-io)

- 类别：Java
- 项目后续更新计划：更丰富友好的文档

- 项目描述：
  - 必写：一个融合了CSV读写和stream增强的Java库，让io操作丝滑无比，堪比Python里的pandas甚至更强
  - 可选：用于实际生产的Java工程，初学者通过阅读源码了解java的反射怎么玩得有趣又实用
  - 详见项目首页中文说明

- 推荐理由：目前Java生态里最好用的csv阅读器，没有之一。性能可能不是最好但仅略逊于univocity。

- 示例代码：详见项目首页中文说明

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
