### ISSUE TITLE
youtube-dl 网络视频下载神器

### ISSUE THREAD

**Issue by doyoyob** [521xueweihan/HelloGitHub#207]
## 项目推荐
- 项目名称：youtube-dl

- 项目地址：https://rg3.github.io/youtube-dl/

- 项目语言：英语

- 项目描述：自由下载各大网站的视频，非常逆天，支持的网站也超多。

- 推荐理由：不需要在缓冲，直接下载最清晰的版本。字幕也可以下载。命令行版本动作很快，如有需要可以另行下载GUI。戳这里 https://github.com/MrS0m30n3/youtube-dl-gui

- 示例代码：brew install youtube-dl

- 截图：
<img width="702" alt="2018-03-10 1 34 44" src="https://user-images.githubusercontent.com/25147482/37218498-f21b1d3c-2403-11e8-8548-7da9131f698f.png">

**Comment by 521xueweihan** [comment]
@doyoyob 该项目已推荐过。[21 期](https://hellogithub.com/volume/21/)
