### ISSUE TITLE
【开源自荐】PHP项目：基于Canal实现ES文档增量更新的高性能轻量框架

### ISSUE THREAD

**Issue by WGrape** [521xueweihan/HelloGitHub#2071]
## 项目推荐
- 项目地址：https://github.com/WGrape/esupdater

- 类别：PHP

- 项目后续更新计划：项目日常维护、提供开箱即用的Canal服务和ES服务，实现完全的极速上手使用

- 项目描述：
  - 简介：esupdater是一个基于Canal实现ES文档增量更新的高性能轻量框架，易上手和接入业务，可以优雅的实现业务需求
  - 场景 ：常适用于搜索业务，比如当需要把MySQL增量数据实时更新到ES中时，就可以使用esupdater

- 推荐理由 ：高性能、容器化、轻量化、事件驱动、易扩展、文档齐全

- 截图 ：
![image](https://user-images.githubusercontent.com/35942268/148946323-682cee90-6046-4e37-a0c4-8f7846b5eac3.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 x 期](https://hellogithub.com/periodical/volume/70/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

**Comment by WGrape** [comment]
感谢收录 ~
