### ISSUE TITLE
【开源自荐】ActionServerless：在 GitHub 中运行 Serverless 异步服务

### ISSUE THREAD

**Issue by gingerhot** [521xueweihan/HelloGitHub#2073]
## 项目推荐
- 项目地址：https://github.com/gitx-io/ActionServerless

- 类别：Python

- 项目后续更新计划：更好地支持现有语言的功能，以及支持更多常用的语言

- 项目描述：
  - 通过 GitHub actions 运行一个 Serverless 异步服务

- 推荐理由：通过已有的 template 可以零配置运行应用代码

- 示例代码：https://github.com/gitx-io/GitFx/blob/master/test/func_examples/function.py

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
