### ISSUE TITLE
井字棋

### ISSUE THREAD

**Issue by BackMountainDevil** [521xueweihan/HelloGitHub#2075]
## 项目推荐
- 项目地址：[井字棋](https://github.com/BackMountainDevil/TicTacToe)

- 类别：C++

- 项目后续更新计划：结束不更

- 项目描述：
  - 必写：一个可进行人机对战、局域网对战的井字棋
  - 可选：局域网通信、游戏NPC

- 推荐理由：色彩鲜明

再次感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
