### ISSUE TITLE
【开源自荐】类似 rz / sz，支持 tmux 的文件传输工具 trzsz ( trz / tsz )

### ISSUE THREAD

**Issue by lonnywong** [521xueweihan/HelloGitHub#2078]
## 项目推荐
- 项目地址：https://github.com/trzsz/trzsz

- 类别：Python

- 项目后续更新计划：
  * 支持 mac 以外的其他平台（例如 windows），要 SecureCRT、Xshell 等像 iTerm2 一样支持 [coprocesses](https://iterm2.com/documentation-coprocesses.html) 才能搞。
  * 将进度条改成模态框，防止在文件传输过程中误触键盘导致传输失败，需要 iTerm2 支持显示 [mac 进度条](https://developer.apple.com/library/archive/documentation/LanguagesUtilities/Conceptual/MacAutomationScriptingGuide/DisplayProgress.html) 才能搞。
  * 使用 tmux 控制模式时，支持二进制上传和下载，需要 tmux 和 iTerm2 支持一些 future 才好搞。
  * 使用 tmux 普通模式时，现已支持二进制下载，支持二进制上传需要 tmux 支持输入设置成 latin1 字符集，或者找到个稳定可靠的办法，将被 tmux 转成 UTF-8 的数据转换回原始的二进制数据。

- 项目描述：
[trzsz](https://trzsz.github.io/) 是一个简单的文件传输工具，和 lrzsz ( rz / sz ) 类似但支持 tmux，和 iTerm2 一起使用，并且有一个不错的进度条。

- 推荐理由：
  * 登录远程电脑时用 tmux 保持会话，但 tmux 不支持用 rz / sz 上传和下载文件，这就很不方便了。
  * 既然 tmux 不愿意支持 rz / sz ，那我们就设计一个新的 trz / tsz ( [trzsz](https://github.com/trzsz/trzsz) )  去支持 tmux 。
  * 不管经过多少跳才登录到远程服务器，都可以方便地上传和下载文件，没有 scp 需要中转的麻烦。
  * 原来 rz / sz 的实现比较简陋，连个进度条都没有，上传和下载文件不知道还要多久才能完成，又或者卡住了也不知道。
  * trzsz ( trz / tsz ) 有一个不错的进度条，虽然现在还不是模态框，但也能清楚地看到上传和下载的进度。

- 截图：
  * 上传文件示例 ![上传文件示例](https://user-images.githubusercontent.com/20320324/149653033-988d4c54-3787-4530-b02b-f3008f99dd9a.gif)
  * 下载文件示例 ![下载文件示例](https://user-images.githubusercontent.com/20320324/149653078-bdbe3ccc-4ac5-49bc-b2df-205cf184edbb.gif)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 x 期](https://hellogithub.com/periodical/volume/70/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
