### ISSUE TITLE
Chrome 音乐实验室 - 在线谱曲

### ISSUE THREAD

**Issue by zeed-w-beez** [521xueweihan/HelloGitHub#208]
## 项目推荐
- 项目名称：Chrome 音乐实验室

- 项目地址：https://github.com/googlecreativelab/chrome-music-lab
  在线谱曲地址： https://musiclab.chromeexperiments.com/Song-Maker/

- 项目语言：Javascript

- 项目描述：
Chrome音乐实验室是一个网站，通过有趣的实验性实验让学习音乐变得更加易于使用。

- 推荐理由：
1. 完全基于Web端，国内可直接访问。
1. 老少皆宜。支持多种乐器，圆你一个音乐梦。

- 截图：
![songmaker](https://user-images.githubusercontent.com/20834022/37239603-fa6fa270-2479-11e8-9f68-863ad3f93ca6.jpg)

**Comment by 521xueweihan** [comment]
@zeed-w-beez 您推荐的项目，已成功收录在 [HelloGitHub 第 24 期](https://hellogithub.com/volume/24/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
