### ISSUE TITLE
【开源自荐】一款简单好用的DAG调度框架

### ISSUE THREAD

**Issue by ChunelFeng** [521xueweihan/HelloGitHub#2080]
- 项目地址：https://github.com/ChunelFeng/CGraph

- 类别：C++

- 项目后续更新计划：
    提供跨进程通信机制，提供常用相似搜索算法算子

- 项目描述：
    一款基于C++17的跨平台DAG调度框架。用户可以通过自定义节点（node）和组（group），来实现任意类型的图调度功能。

- 推荐理由：
    实现了一个基于标准C++17版本实现的跨平台的DAG流图框架，无任何第三方依赖，简单好上手。通过流水线编排，实现了依赖节点依次执行、无依赖节点并发执行的逻辑。此外，还提供了循环执行、条件判断、参数传递、切面编程、自定义分区、函数注入、流图自动优化等功能。同时，项目内部抽象出了一些简单的通用功能算子（如高性能线程池、通用单例类等），可供直接使用。

    代码风格高度统一，便于阅读和Review，提供了10+个适用于各种不同场景的Demo、详细的文档说明和变更记录。普遍适用于算法调度、引擎开发、并发编程、抽象业务通用逻辑等场景。初学者可以通过此项目，学到新C++的一些实用功能、图调度方式、模块开发、模板编程、多线程编程、设计模式和一些通用算法知识。

- 示例代码：

```cpp

#include "../src/CGraph.h"
using namespace CGraph;

class MyNode1 : public GNode {
public:
    CStatus run () override {
        CStatus status;
        CGRAPH_ECHO("[%s], enter MyNode1 run function. Sleep for 1 second ... ", this->getName().c_str());
        CGRAPH_SLEEP_SECOND(1)
        return status;
    }
};

class MyNode2 : public GNode {
public:
    CStatus run () override {
        CStatus status;
        CGRAPH_ECHO("[%s], enter MyNode2 run function. Sleep for 2 second ... ", this->getName().c_str());
        CGRAPH_SLEEP_SECOND(2)
        return status;
    }
};

void tutorial_simple() {
    /* 创建一个流水线，用于设定和执行流图信息 */
    GPipelinePtr pipeline = GPipelineFactory::create();
    GElementPtr a, b, c, d = nullptr;

    /**
     * 其中，MyNode1算子的执行内容为sleep(1s)
     * MyNode2算子的执行内容为sleep(2s)
     * 以下几行代码，相当于是设定了一个[b/c]依赖[a]，[d]依赖[b/c]的dag流图
     */
    pipeline->registerGElement<MyNode1>(&a, {}, "nodeA");
    pipeline->registerGElement<MyNode2>(&b, {a}, "nodeB");
    pipeline->registerGElement<MyNode1>(&c, {a}, "nodeC");
    pipeline->registerGElement<MyNode2>(&d, {b, c}, "nodeD");

    /* 执行流图框架 */
    pipeline->process();
    GPipelineFactory::destroy(pipeline);
}
```

- 截图：

![image](https://user-images.githubusercontent.com/37905059/149786031-37ad9611-4b0e-4fb0-9eb2-192093558829.png)

**Comment by ChunelFeng** [comment]
很开心项目能被hellogithub项目选中，算是这一年结束的时候一个重要的里程碑。

最近对项目做了一点改进，同时也对之前留言的时候贴的图片做了略微的修改。

希望大佬在发表的时候，用最新的图片（左下方的 function condition标签，是绿色的）。

再次感谢hellogithub项目组，为大家提供了一个这么好的展示和交流平台

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 x 期](https://hellogithub.com/periodical/volume/70/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
