### ISSUE TITLE
【开源自荐】Android 编译加速黑科技- RocketX 

### ISSUE THREAD

**Issue by trycatchx** [521xueweihan/HelloGitHub#2084]
## 项目推荐
- 项目地址：仅收录 GitHub 的开源项目，请填写 GitHub 的项目地址

- 类别：Kotlin  gradle

- 项目名称：RocketX

- 项目地址：源码： https://github.com/trycatchx/RocketXPlugin ，插件：https://plugins.jetbrains.com/plugin/18001-rocketx

- 项目后续更新计划：
    dexbuilder 优化

- 项目描述：
  - 必写: Android 编译 apk 加速
  - 可选：适用于编译 apk 需要漫长的等待，提高效率，让工作不再 996 。初学者能初窥编译器源码
  - 描述长度（不包含示例代码）: 本插件自动识别未改动 module 并在编译流程中替换为 aar ，只编译改动模块，加速 Android apk 的编译速度。让你体验到所有模块都是 aar 的速度，又能保留所有的 module 便于修改，完美！

- 推荐理由：hook 编译器编译流程，解决了打包苦苦等待的几分钟的无奈

- 示例代码：（可选）长度：

```
// app module 的 build.gradle 加入
apply plugin: 'com.rocketx'

// 在根目录的 build.gradle 加入
buildscript {
    dependencies {
        classpath 'io.github.trycatchx:rocketx:1.0.17'
    }
}
依赖 AS 插件 android studio setting->plugins-> marketplace 搜索 RocketX 安装
```

- 截图：

![image](https://user-images.githubusercontent.com/6050250/150731926-ec1b4c63-a944-45da-8f64-fde432b752bb.png)

![image](https://user-images.githubusercontent.com/6050250/150731838-fb39253b-caa8-4183-b154-73fb7406d77e.png)

![image](https://user-images.githubusercontent.com/6050250/150734013-35625e30-f748-48dd-b472-34d5fddf6317.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 71 期](https://hellogithub.com/periodical/volume/71/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
