### ISSUE TITLE
[开源自荐]vscode 扩展 Css Code Block 常用css代码段大全

### ISSUE THREAD

**Issue by 347830076** [521xueweihan/HelloGitHub#2088]
## 项目推荐
- 项目地址：[github地址](https://github.com/347830076/vscode-plugin-css-class) [vscode插件地址](https://marketplace.visualstudio.com/items?itemName=aliwang.css-code-block)

- 类别：CSS ，vscode-plugin

- 项目后续更新计划：

- 项目描述：
  - 一个vscode 扩展，收集常用的css代码块，快捷键自动输入css代码块

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？

开发中，我们一直写很多重复的css样式，想着要是有个vscode插件能收集常用的css样式大全，直接选择样式，就出现在vscode编辑器文件上面了，这样就可以大大提高我们的工作效率。

如果所有的前端开发者都来共享常用的css样式，那么这个样式表将会越来越全，写css各种样式就会很轻松了。

所以这个项目开源，欢迎大家参与交流，为常用css贡献一份力，让我们前端人css开发效率高起来。

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
