### ISSUE TITLE
开源项目 | 开放源码的无 App 推送服务pushdeer

### ISSUE THREAD

**Issue by itgoyo** [521xueweihan/HelloGitHub#2089]
## 项目推荐
- 项目地址：https://github.com/easychen/pushdeer

- 类别：其它

- 项目后续更新计划：
PushDeer 开源版，可以自行架设的无 APP 推送服务（WIP，API、iOS 和 Mac 第一版本完成，Android 即将完成，其他部分正在施工🚧）

- 项目描述：方便的消息推送，支持IOS，Android端

- 推荐理由：
1.Self-hosted：让有能力和精力的用户可以自行架设，避免因为在线服务下线导致的接口更换风险。
2.非商用免费：不用 PushDeer 挣钱，就无需支付费用
3.不依赖微信消息接口：不像 Server 酱那样受腾讯政策影响  

- 示例代码：
```
通过访问后边的 URL 即可推送内容：https://api2.pushdeer.com/message/push?pushkey=key&text = 要发送的内容
```
- 截图：
- 
![image](https://user-images.githubusercontent.com/23348551/151472513-14e21731-565d-4a32-8131-3dfdb1213cd4.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 71 期](https://hellogithub.com/periodical/volume/71/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
