### ISSUE TITLE
mpvue 用 vue 开发小程序

### ISSUE THREAD

**Issue by aOrz** [521xueweihan/HelloGitHub#209]
## 项目推荐
- 项目名称：
  mpvue
- 项目地址：
https://github.com/Meituan-Dianping/mpvue
- 项目语言：
JavaScript
- 项目描述：
mpvue 是一个使用 Vue.js 开发小程序的前端框架。框架基于 Vue.js 核心，mpvue 修改了 Vue.js 的 runtime 和 compiler 实现，使其可以运行在小程序环境中，从而为小程序开发引入了整套 Vue.js 开发体验。
- 推荐理由：
使用 mpvue 开发小程序，你将在小程序技术体系的基础上获取到这样一些能力：

  - 彻底的组件化开发能力：提高代码复用性
  - 完整的 Vue.js 开发体验
  - 方便的 Vuex 数据管理方案：方便构建复杂应用
  - 快捷的 webpack 构建机制：自定义构建策略、开发阶段 hotReload
  - 支持使用 npm 外部依赖
  - 使用 Vue.js 命令行工具 vue-cli 快速初始化项目
  - H5 代码转换编译成小程序目标代码的能力

- 示例代码：
[五分钟上手教程](http://mpvue.com/mpvue/quickstart/)

**Comment by 521xueweihan** [comment]
@aOrz 您推荐的项目，已成功收录在 [HelloGitHub 第 24 期](https://hellogithub.com/volume/24/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
