### ISSUE TITLE
github.com/matsuwin/proctop

### ISSUE THREAD

**Issue by matsuwin** [521xueweihan/HelloGitHub#2093]
## 项目推荐

- 项目地址：https://github.com/matsuwin/proctop

- 类别：Go

- 项目后续更新计划：持续完善

- 项目描述：适用于 Linux 的性能分析工具，实时显示进程的资源占用状态，类似于 TOP。支持 Java 同名进程拆分。*同样适用于 Raspberry Pi (树莓派)。
- 单核 CPU 使用率 TOP 进程列表，自动刷新 2s/次。
- 分等级的彩色页面渲染：红 > 黄 > 青 > 蓝。
- 同名进程自动合并，资源利用累加。
- 主机信息和处理器型号抬头展示。
- 处理器温度实时预览。
- 一键安装。

- 推荐理由：ProcTop 提供了好看直观的 TOP 视图，是 top 命令的增强。除此之外还提供了丰富的机器信息枚举，CPU型号、温度、whoami、IP 等。

<img src="https://raw.githubusercontent.com/matsuwin/proctop/main/demo.png">

**Comment by 521xueweihan** [comment]
@matsuwin 
非常感谢您推荐项目，往期月刊已推荐过类似的项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
