### ISSUE TITLE
asmoboot项目推荐

### ISSUE THREAD

**Issue by asmoyou** [521xueweihan/HelloGitHub#2095]
## 项目推荐
- 项目地址：https://github.com/RotaNova  项目网站：http://asmoboot.com
其中asmoboot为java后端、 asmoboot-web为Vue开发的Web端、 asmoboot-app为Uni-app开发的移动端

- 类别：Java、Vue、Uni-app

- 项目后续更新计划：
  ① 完善开放数据中台功能
  ② 开放基于物模型的物联网平台
  ③ 不断完善开发文档

- 项目描述：
  ​ 在开发了一些实际工程项目后，发现一些常见的权限、对接、消息通知等等问题。由于每次定制化项目都要进行一些开发，不利于项目长期维护。参考若依、JEECGBOOT以及一些低代码开发框架的启发，我们设计了一套自己的快速开发框架。具备行级权限管理，安全登录防护以及轻量级的数据中台功能。除此之外，还支持集成了Amis等低代码开发框架，更多内容请自行探索。
   此外，在项目实施中，我们还额外基于zlmediakit开发了视频监控平台，支持GB28181、RTSP等协议，并具备完整的级联平台以及PTZ控制；由于项目以物联网性质为主，所以还参考阿里云物联网平台开发了基于物模型管理的设备管理模块；此外，还有诸如工地实名制平台对接、智慧停车场、智慧用电等等平台模块，提供有偿服务。

- 推荐理由：
    可以应用在任何J2EE项目的开发中，适用SAAS项目、企业信息管理系统（MIS）、内部办公系统（OA）、企业资源计划系统（ERP）、客户关系管理系统（CRM）等，现成的管理框架体系，可以显著提高开发效率，降低开发成本。
    相比于若依框架，多了更多的物联网行业元素，以及集成了大量物联网项目所需的基础能力。项目安全防护可帮助用户快速适配三级等保测评要求。

- 截图：截图请看说明https://github.com/RotaNova/asmoboot

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目，企业级项目建议先在项目中注明开源协议。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
