### ISSUE TITLE
【开源自荐】Nyquisis - 一键删除 PDF 中的重复页面

### ISSUE THREAD

**Issue by Enoch2090** [521xueweihan/HelloGitHub#2096]
## 项目推荐
- 项目地址：[https://github.com/Enoch2090/Nyquisis](https://github.com/Enoch2090/Nyquisis)
- 类别：Python
- 项目后续更新计划：增加鲁棒性代码
- 项目描述：
  命令行工具，利用图像哈希算法删除用于 PPT 演示的 PDF 文件中的重复页，方便阅读。一键操作，无需任何手动设置。

- 推荐理由：附实现细节 - [https://www.enoch2090.me/nyquisis-pdfdropduplicate-remastered](https://www.enoch2090.me/nyquisis-pdfdropduplicate-remastered)
- 示例代码：
```shell
nyquisis ./my-file.pdf
```
- 截图：处理前后对比（左-处理前；右-处理后）：
![处理前后对比](https://user-images.githubusercontent.com/47914326/153133308-1a20b24b-4046-4620-871c-9f568cabe41f.JPEG)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目，但项目使用场景过于单一。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
