### ISSUE TITLE
【开源自荐】Yank Note - 一款面向程序员的 Markdown 笔记应用

### ISSUE THREAD

**Issue by purocean** [521xueweihan/HelloGitHub#2098]
## 项目推荐
- 项目地址：https://github.com/purocean/yn

- 类别：JS

- 项目后续更新计划：
  - 增加插件中心：将一些功能做成插件发布，也方便用户共享插件
  - 增加反向索引：将文档信息结构化，便于搜索，也便于程序使用
  - 增强文档关联：能查看文档引用和被引用情况

- 项目描述：
  
  Yank Note 是一款面向程序员的本地 Markdown 笔记应用。支持在文档中嵌入可运行的代码块、思维导图以及各种图形 (Drawio、Mermaid、Plantuml)，支持插件拓展、文档历史版本回溯。

- 推荐理由：

Yank Note 非常适合程序员群体，针对下面的场景具有和其他笔记工具不一样的体验：

1. 做技术笔记：可直接在文档中运行代码块（天然支持 JS 代码，其他语言需配置环境），让笔记生动起来。
2. 编写辅助工具：可在文档中嵌入 HTML 组件来制作一些辅助工具，甚至你可以使用 [Markdown 遥控无人机](https://github.com/purocean/yn/issues/65#issuecomment-962472316) :)
3. 写技术方案和文章：支持嵌入多种图形（思维导图、Plantunl、Drawio、Mermaid 、ECharts ），写文档画图形一气呵成。
4. 记录工作日志：支持任务代办列表，使用“宏替换”功能可以方便生成日报周报。

- 截图：
 ![image](https://user-images.githubusercontent.com/7115690/153351642-243bf320-fd79-4f9c-bc91-25adeb3b0be0.png)

**Comment by 521xueweihan** [comment]
@purocean 可以着重介绍下 面向“程序员”的功能

**Comment by purocean** [comment]
@521xueweihan 改了一下推荐理由部分

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 71 期](https://hellogithub.com/periodical/volume/71/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
