### ISSUE TITLE
【开源自荐】基于Gin框架的自动化绑定中间件

### ISSUE THREAD

**Issue by jtyoui** [521xueweihan/HelloGitHub#2099]
## 项目推荐
- 项目地址：https://github.com/jtyoui/ginRoute

- 类别：Go

- 项目后续更新计划：
   一直更新   

- 项目描述：
   ginRoute框架是gin框架对web的二次封装，意在减轻对路由和DAO的操作是一个自动化、简洁化的过程，它仅仅是一个小的尝试，辅助gin更加变得使用简单一些。

- 推荐理由：解决Gin自动绑定的痛点，让程序员只专注逻辑层的开发。简单、几分钟便能灵活使用。

```go
package main

import (
	"github.com/gin-gonic/gin"
	"github.com/jtyoui/ginRoute/router"
)

type User struct {
}

func (*User) GetId(name string) string {
	return name
}

func main() {
	r := gin.Default()
	rg := router.GinRouter{Router: r.Group("")}
	rg.AutoRouter(&User{})
	r.Run(":8080")
}
```
![image](https://user-images.githubusercontent.com/28988355/153705278-9d3b6e71-853a-4048-a3e3-cd4cc9e7abb6.png)

## 文档
👉 点击查看使用[文档](https://www.wolai.com/iDARnRwqR3Pb94uDrhD3xw)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
