### ISSUE TITLE
Android 开源代码大全

### ISSUE THREAD

**Issue by jp1017** [521xueweihan/HelloGitHub#21]
全部看完了12期， 收藏了一些python的库，很有趣，感谢，推荐一个安卓的：

https://github.com/XXApple/AndroidLibs

**Comment by 521xueweihan** [comment]
@jp1017 感谢支持与推荐的项目。

我看您的项目是Android项目的集合，然后我想邀请您加入到本项目一期维护，您来负责Android部分的项目推荐。

如有意欢迎保持联系，继续交流

**Comment by jp1017** [comment]
@521xueweihan 可以的, 最近开始学习 `python`, 有好东西, 一起分享 :smile: :+1:
