### ISSUE TITLE
【开源自荐】基于G6和Vue的可视化图形编辑器

### ISSUE THREAD

**Issue by OXOYO** [521xueweihan/HelloGitHub#2101]
## 项目推荐
- 项目地址：[https://github.com/OXOYO/X-Flowchart-Vue](https://github.com/OXOYO/X-Flowchart-Vue)
- 在线地址：[https://oxoyo.co/X-Flowchart-Vue/](https://oxoyo.co/X-Flowchart-Vue/)

- 类别：JS

- 项目后续更新计划：[https://github.com/OXOYO/X-Flowchart-Vue/issues](https://github.com/OXOYO/X-Flowchart-Vue/issues)

- 项目描述：基于 G6 和 Vue 的可视化图形编辑器

- 推荐理由：Antv G6 流程图编辑器最佳实践

- 截图：
![image](https://user-images.githubusercontent.com/5074207/153713380-5538e467-7fc0-486f-9f49-8517b885c695.png)

**Comment by 521xueweihan** [comment]
@OXOYO  1095 请注意身体。
无后续维护计划的项目，月刊暂不收录了。
