### ISSUE TITLE
【开源自荐】ONLYOFFICE办公套件

### ISSUE THREAD

**Issue by linakudryash** [521xueweihan/HelloGitHub#2109]
## 项目推荐
**项目地址**：https://github.com/ONLYOFFICE

**类别**：C#、Java、其它

**项目后续更新计划**：[点击这里](https://github.com/ONLYOFFICE/DocumentServer/blob/master/ROADMAP.md)，查看该项目的后续更新计划。

**项目描述**：
- [ONLYOFFICE文档](https://www.onlyoffice.com/zh/developer-edition.aspx)是可集成到你平台中的开源办公套件。该套件除了3个主要微软Office的替代品（Word、Excel、PowerPoint）以外，还提供可填写的表单编辑器。
- 允许多人实时在线协作编辑文件，并使用一套协作工具：两种共同编辑模式、评论、文档比较、内容控制、内置聊天，跟踪变化及版本历史。
- 表单编辑器允许从头开始创建并填写表单，也可以使用现有的DOCX文件并插入各种类型的字段，并另存为PDF。也有免费的[表单模板库](https://oforms.onlyoffice.com/zh/)。

**推荐理由**：
- 使用OOXML作为本地格式，提供更好的微软Office兼容性。
- 无论使用云端或本地部署模式，您都可以将ONLYOFFICE文档集成到任何Web解决方案。
- ONLYOFFICE文档可进行伸缩以为任意数量的用户提供服务。

**示例代码**：[点击这里](https://api.onlyoffice.com/editors/demopreview)，查看该项目的示例代码。

**Comment by 521xueweihan** [comment]
项目拆的太散了，月刊不收录组织只收录项目。
