### ISSUE TITLE
仿今日头条点赞动画

### ISSUE THREAD

**Issue by Qiu800820** [521xueweihan/HelloGitHub#211]
## 项目推荐
- 项目名称：
SuperLike
- 项目地址：
https://github.com/Qiu800820/SuperLike
- 项目语言：
Java
- 项目描述：
仿今日头条点赞动画
- 推荐理由：
便捷又炫酷的UI库
- 示例代码：
```javascript
compile 'com.sum.slike:library:0.2.0'
```

```java
    BitmapProvider.Provider provider = new BitmapProvider.Builder(this).build();
    superLikeLayout.setProvider(provider);
    superLikeLayout.launch(x, y);
```
- 截图：

![image](https://raw.githubusercontent.com/Qiu800820/SuperLike/master/img/Animation.gif)

**Comment by 521xueweihan** [comment]
@Qiu800820 您推荐的项目，已成功收录在 [HelloGitHub 第 24 期](https://hellogithub.com/volume/24/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
