### ISSUE TITLE
【开源自荐】Databasir 数据库模型文档自动化管理中心

### ISSUE THREAD

**Issue by vran-dev** [521xueweihan/HelloGitHub#2110]
## 项目推荐

- 项目地址：https://github.com/vran-dev/databasir

- 类别：Java

- 项目后续更新计划：

  - 支持任意数据库类型扩展
  - 支持更多文档导出格式，如 Excel、PDF 等
  - 支持将文档转为 DDL

- 项目描述：

  **Databasir** 是一款集中式的数据库模型文档管理工具，提供了自动化、版本化、扁平化的数据库模型文档管理能力，目前支持 Mysql、Postgresql，后续会支持更多数据库类型。

  项目采用了 Spring MVC、Spring Security、Quartz、Vue、Element-Plus 等知名开源框架构建，由开源项目 [PrettyZoo](https://github.com/vran-dev/PrettyZoo) 作者设计研发。

  

- 推荐理由：

  - 自动生成数据库文档，支持手动、定时同步更新
  - 历史版本轻松查看，轻松了解模型迭代历史
  - 简单而完善的团队管理模式，为团队协作项目赋能
  - markdown、excel （扩展中）文档导出格式一应俱全

- 截图

项目同步

![project-sync](https://user-images.githubusercontent.com/12870335/154959694-b4772e05-a5e2-4303-9bcd-632be8c01810.gif)

成员管理

![group-member](https://user-images.githubusercontent.com/12870335/154959715-8b001ac7-053e-4edc-a779-f26c29f1232c.gif)

用户详情

![user-detail](https://user-images.githubusercontent.com/12870335/154959747-f62bd347-76cc-42f8-8a65-be8f39a34114.gif)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
