### ISSUE TITLE
程序员在家做饭指南

### ISSUE THREAD

**Issue by gdcplasf** [521xueweihan/HelloGitHub#2113]
## 项目推荐
- 项目地址：[仅收录 GitHub 的开源项目，请填写 GitHub 的项目地址](https://github.com/Anduin2017/HowToCook.git)

- 类别：其它

- 项目后续更新计划：

- 项目描述：
  - 必写：这是个教程序员如何做饭的开源项目
  - 可选：适用于程序员讨好GF和丈母娘

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 71 期](https://hellogithub.com/periodical/volume/71/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
