### ISSUE TITLE
simplepy

### ISSUE THREAD

**Issue by cnzbpy** [521xueweihan/HelloGitHub#2114]
## 项目推荐
- 项目地址：https://github.com/cnzbpy/simplepy

- 类别：Python

- 推荐理由：这些是用Python编写的一些简单的项目，通过一些方便使用的小工具来学习Python

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

可以考虑为 OneFile 项目提交 PR：https://github.com/521xueweihan/OneFile
