### ISSUE TITLE
【开源自荐】awesome-cybersecurity -- 爬取github上所有关于网络安全资料收集的项目，并进行分类和精选

### ISSUE THREAD

**Issue by liyansong2018** [521xueweihan/HelloGitHub#2116]
## 项目推荐
- 项目地址：https://github.com/liyansong2018/awesome-cybersecurity
- 类别：Python、其它、书籍

- 项目后续更新计划：继续爬虫和选取有价值的网络安全相关资料

- 项目描述：
  - 这是一个通过python爬虫爬取github上所有关于网络安全资料的项目
  - 自动爬取相应项目，并统计历年更新的项目数以及相应的star排名
  - 手动精选安全项目

- 推荐理由：
  - 通过统计分类，精选相应的awesome-security存储库，网络安全从业人员可快速找到自己想要学习的方向和资料 

- 示例代码：（可选）长度：
```python
for i in range(20):
        url = 'https://github.com/search?p={}&q=awesome-security&type=Repositories'.format(i + 1)
        # github-error-rate-limit-exceeded
        response = requests.get(url=url, headers=headers, verify=False)
        soup = BeautifulSoup(response.text, 'lxml')
        date = soup.findAll('relative-time')
```

- 截图：
![top_repositories](https://user-images.githubusercontent.com/25031216/156148690-cf738b51-4294-4500-a854-b36733cce295.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
