### ISSUE TITLE
Jina 项目推荐

### ISSUE THREAD

**Issue by antonia0912** [521xueweihan/HelloGitHub#2117]
## 项目推荐
- 项目地址：[Jina GitHub 项目地址](https://github.com/jina-ai/jina)

- 类别：**Python、机器学习**

- 项目后续更新计划：

- 项目描述：
  - 🚀 神经搜索 (Neural Search) 是指用非结构化数据，搜索非结构化数据。**深度学习模型和向量索引是神经搜索的重要组成部分。** 由于神经搜索是一个全新的领域，缺少系统搭建的统一工具，开发者通常需要同时了解包括分布式系统、深度学习框架以及网络服务方面的知识，为此我们设计了 Jina。
  - 💥 **Jina 是一款主打易用性及云原生的神经搜索框架，** 它将整个流程封装成一个完整系统，提供统一的接口，这极大降低了神经搜索系统的开发成本。2020 年 4 月 Jina 在 GitHub 开源，截至目前已收获 13.8k Star。
  - 📝 利用 Jina，**开发者可搭建以图搜图、以文字搜图、Question-Answering（问答机器人）、照片去重、海量标签分类等多种应用。**
   
  - **Jina 具有以下优势：**
    - ⏱ 省时省力：将神经搜索系统搭建的整个流程，封装成一个完整系统，支持快速建立索引、查询、理解多/跨模态数据的解决方案；
    - 🌩️ 本地和云端友好：分布式架构，支持可扩展和云原生，可以在本地、Docker Compose、Kubernetes 上部署 Jina；
    - 🚀 服务、扩展及共享：通过 HTTP、WebSockets 或 gRPC 端点，几分钟之内即可服务本地项目；扩展神经搜索应用，满足用户对可用性和吞吐量的不同要求；通过 Jina Hub，开发者可以轻松分享和复用 Executor；
    - 🍱  拥有自己的堆栈：对解决方案保有端到端的堆栈所有权，支持与神经搜索生态系统 (DocArray, Hub 及 Finetuner) 的整合。

  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？
  - 极大简化了神经搜索系统的搭建流程
  - 方便本地调试，也可以快速地以服务形式进行部署
  - Jina 原生提供 Swagger-UI，方便代码调试
  - 几行代码即可将 Jina 部署到 Kubernetes 系统中

- 示例代码：（可选）长度：1-20 行
```
from docarray import Document, DocumentArray
from jina import Executor, Flow, requests
```
```
class PreprocImg(Executor):
    @requests
    async def foo(self, docs: DocumentArray, **kwargs):
        for d in docs:
            (
                d.load_uri_to_image_tensor(200, 200)  # load
                .set_image_tensor_normalization()  # normalize color
                .set_image_tensor_channel_axis(
                    -1, 0
                )  # switch color axis for the PyTorch model later
            )
```

- 截图：
![](https://tva1.sinaimg.cn/large/e6c9d24egy1gzvlhqv9nlj21ql0u0jwk.jpg)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 72 期](https://hellogithub.com/periodical/volume/72/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
