### ISSUE TITLE
项目推荐 | 程序员做饭指南 HowToCook

### ISSUE THREAD

**Issue by SekiBetu** [521xueweihan/HelloGitHub#2119]
## 项目推荐
- 项目地址：https://github.com/Anduin2017/HowToCook

- 类别：其它、书籍

- 项目后续更新计划：社区驱动

- 项目描述：网上的菜谱往往写法千奇百怪，经常中间莫名出来一些材料。对于习惯了形式语言的程序员来说极其不友好，于是此项目诞生了

- 推荐理由：项目仓库中的每一个菜谱都结合了实际做菜的经验，用更清晰精准的描述来整理常见菜的做法，以方便程序员在家做饭

**Comment by 521xueweihan** [comment]
@SekiBetu 已推荐过
