### ISSUE TITLE
【开源自荐】OnlySwitch

### ISSUE THREAD

**Issue by jacklandrin** [521xueweihan/HelloGitHub#2122]
## 项目推荐
- 项目地址：https://github.com/jacklandrin/OnlySwitch

- 类别：Swift

- 项目后续更新计划：
   会继续开发更多开关与快捷指令

- 项目描述：
  采用SwiftUI开发的macOS一键设置app。可以轻松对很多系统功能进行设置，如隐藏桌面图标，清理Xcode缓存，一键隐藏新MacBook刘海儿，进入夜览模式等数十种功能，OnlySwitch内置了一个网络电台，用户可以自定义配置喜欢的电台链接。此外OnlySwitch还支持Monterey中全新的快捷指令，甚至可以为开关和快捷指令设置键盘热键进行操作。

- 推荐理由：对于macOS新手来说，系统设置变得轻松易用。应用完全开源免费，支持多种语言

- 截图：
<p align="center">
<img alt="Sits in the status bar" src="https://www.jacklandrin.com/wp-content/uploads/2022/01/onlySwitch_19.png" width="60%" align="center" />
</p>

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 72 期](https://hellogithub.com/periodical/volume/72/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
