### ISSUE TITLE
复活版黑盒BlackBox，一款虚拟引擎，可以在Android上克隆、运行虚拟应用

### ISSUE THREAD

**Issue by crazyn2** [521xueweihan/HelloGitHub#2124]
## 项目推荐
- 项目地址：[https://github.com/FBlackBox/BlackBox](https://github.com/FBlackBox/BlackBox)

- 类别：Java

- 项目后续更新计划：

- 项目描述：
  - 必写：该项目是原BlackBox ( 简称BB ) 的复活版本，重写了VirtualApp的那部分代码，主要功能和原项目一样，是一款虚拟引擎，可以在Android上克隆、运行虚拟应用，拥有免安装运行能力。
  - 可选：插件化、双开、多开技术实现
  - 描述长度（不包含示例代码）: 黑盒BlackBox，是一款虚拟引擎，支持5.0～11.0，可以在Android上克隆、运行虚拟应用，拥有免安装运行能力。黑盒可以掌控被运行的虚拟应用，做任何想做的事情。

- 推荐理由：可以在Android上克隆、运行虚拟应用，拥有免安装运行能力，遵循Apache2.0开源协议。

**Comment by 521xueweihan** [comment]
@crazyn2 您好，我记得 VirtualAPP 这个项目由有几起，侵权案例：https://new.qq.com/omn/20220227/20220227A03X4E00.html

您可以看看

**Comment by crazyn2** [comment]
代码是全部重写过的

**Comment by 521xueweihan** [comment]
@crazyn2 低调使用或许可以让这个项目活得更久

**Comment by crazyn2** [comment]
没用的，罗盒已经知道了
