### ISSUE TITLE
开源软件 lol上等马分析程序 golang

### ISSUE THREAD

**Issue by buffge** [521xueweihan/HelloGitHub#2126]
## 项目推荐
- 项目地址：[lol对局先知](https://github.com/real-web-world/hh-lol-prophet)

- 类别：Go

- 项目后续更新计划：
 1. 使用c#重写界面
 2. 优化算法
- 项目描述：
  - 必写：lol自动接受对局,自动ban,pick,自动获取队友马匹信息. 开局前就知道这局大概能不能赢
  - 可选：golang demo项目
  - 描述长度（不包含示例代码）:  -

- 推荐理由：好用

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg
![Dingtalk_20220315105000](https://user-images.githubusercontent.com/24917906/158296566-a13e616d-a30e-478e-a84d-f8f593f75d98.jpg)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 72 期](https://hellogithub.com/periodical/volume/72/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
