### ISSUE TITLE
【开源自荐】类似 rz / sz，兼容 tmux 的 trzsz ( trz / tsz ) 通过 js 组件支持更多的终端

### ISSUE THREAD

**Issue by lonnywong** [521xueweihan/HelloGitHub#2127]
## 项目推荐
- 项目地址：https://github.com/trzsz/trzsz.js

- 类别：JS

- 项目后续更新计划：
  * 支持更多的终端，如 tabby 等
  * 使用 JS 实现服务端的 trz / tsz 命令工具
  * 集成 rz / sz ，同时支持 ( trz / tsz ) 和 ( rz / sz )

- 项目描述：
  * [trzsz](https://github.com/trzsz/trzsz) ( trz / tsz ) 是类似 lrzsz ( rz / sz ) 的文件传输工具，兼容 tmux，有进度条。
  * [trzsz.js](https://github.com/trzsz/trzsz.js) 是 JS 版本的实现，用于支持 electron 实现的跨平台的终端、支持运行在浏览器的 webshell 集成 trzsz ( trz / tsz )。
  * 现在 [electerm](https://github.com/electerm/electerm) v1.19.0 已通过 [trzsz.js](https://github.com/trzsz/trzsz.js)  实现了支持 trzsz ( trz / tsz )。

- 推荐理由：
  * 在浏览器中实现类似 rz / sz 上传和下载的功能。
  * 兼容 tmux ，解决了 rz / sz 不兼容 tmux 的问题。
  * trzsz ( trz / tsz ) 上传和下载时有很不错的进度条。

- 示例代码：
  * 在浏览器 webshell 的使用示例：https://github.com/trzsz/trzsz.js/blob/main/examples/browser
  * 在 electron 应用中的使用示例：https://github.com/trzsz/trzsz.js/blob/main/examples/electron
  * 使用 `TrzszAddon` 接入更简单：https://github.com/trzsz/trzsz.js/blob/main/examples/addon

- 截图：
  * 在浏览器 webshell 的截图：

  ![](https://trzsz.github.io/images/browser.gif)

  * 在 electron 应用中的截图：

  ![](https://trzsz.github.io/images/electron.gif)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
