### ISSUE TITLE
【开源自荐】ASP.NET Core 轻量级插件框架

### ISSUE THREAD

**Issue by yiyungent** [521xueweihan/HelloGitHub#2128]
## 项目推荐
- 项目地址：仅收录 GitHub 的开源项目，请填写 GitHub 的项目地址

> https://github.com/yiyungent/PluginCore

- 类别：请从中选择（C、C#、C++、CSS、Go、Java、JS、Kotlin、Objective-C、PHP、Python、Ruby、Swift、其它、书籍、机器学习）

> C#

- 项目后续更新计划：

> 1. 分出 PluginCore, PluginCore.AspNetCore, 对 WPF, MAUI 等非 Web 项目做出更好支持
> 2.  依赖注入提供更多接口，可替换更多内部实现
> 3. PluginCore 后端 多语言支持

- 项目描述：
  - 必写：这是个什么项目、能用来干什么、有什么特点或解决了什么痛点

> 1. 适用于 ASP.NET Core 的轻量级插件框架，开箱即用，自带 插件管理 WebUI
> 2. 插件能为我们的软件系统提供了丰富的拓展能力，也在某些场景下将系统功能拆分为松耦合的子模块分而治之
> 3. 需求不断变更，导致代码越来越臃肿，有许多为了特定需求开发的定制化功能
> 4. 主程序不能开源，但需要社区/第三方 开发辅助功能

  - 可选：适用于什么场景、能够让初学者学到什么
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？

> 1. 开箱即用，接入式：不同于其他框架，本框架自身以一个类库存在，无需引入源代码，只需引入包，再添加两行代码即可集成，nopCommerce, OrchardCore, ABP 等自带插件系统，但只能通过修改源代码方式在其上构建，而 .NET 其它开源插件方案均未针对 ASP.NET Core，需要昂长的代码自己集成并实现插件管理界面，而 PluginCore 将插件管理  WebUI 一起嵌入到了 dll 中，插件管理自动集成，在 PHP 中类比 [Laravel Plugin](http://docs.you-tang.com/) ，Java 也有很多开源方案，而 .NET 针对 ASP.NET Core 的独立插件方案极少，自带插件管理界面的更少（我就没看到）
> 2. 首创 通用 PluginCore JavaScript SDK：在 PHP 中，由于可与 HTML 混写，所以很容易实现前端插件扩展，而 ASP.NET Core 中，若想实现 则 寄托于 Razor，Blazor等，但现在前后端分离, Vue.js 等兴起，因此能不能有一种通用方案，同时适用于这些，而 `PluginCore JavaScript SDK` 则可通过插件轻松在任意前端页面（需事先埋点）注入/修改页面，后端配置CORS, 甚至前端在与后端不同源时，仍然可以通过插件扩展
> 3. 插件前后端分离 - 可在插件 `wwwroot` 文件夹下放置前端文件 (index.html,...), 然后访问 `/plugins/pluginId/index.html`
> 4. 依赖注入 - 可在 实现 `IPlugin` 的插件类的构造方法上申请依赖注入项, 当然 `Controller` 构造方法上也可依赖注入

- 示例代码：（可选）长度：1-20 行

```csharp
public void ConfigureServices(IServiceCollection services)
{
    // ...
    // 1. Add PluginCore
    services.AddPluginCore();
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    // ...
    // 2. Use PluginCore
    app.UsePluginCore();
}
```

- 截图：（可选）gif/png/jpg

![Snipaste_2022-03-16_19-01-27](https://user-images.githubusercontent.com/16939388/158737669-ccfcc2ce-4ac3-472f-9972-55de85d8597a.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 72 期](https://hellogithub.com/periodical/volume/72/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
