### ISSUE TITLE
【开源自荐】一款可以从各类源码管理网站（github，自定义等）任意前端项目作为项目模板，克隆下来并进行项目开发的前端cli

### ISSUE THREAD

**Issue by xhl592576605** [521xueweihan/HelloGitHub#2130]
## 项目推荐
- 项目地址：https://github.com/xhl592576605/front-engine-cli
- 类别：js

- 项目后续更新计划：
 - 支持更多的命令，如像pnpm，yarn 等运行项目的命令
 -  支持用户自定义插件，并集成在项目中，方便创建组件等业务性，重复性的工作

- 项目描述：
  - front-emgine-cli 支持从github，gitlab，gitee，自定义（direct）中，将项目作为项目模板克隆到本地，作为自己的项目，进行开发
  - 开发者可以从中学习到最简单并最完全的前端cli的工具写法

- 推荐理由
 - 作为企业级的开发，每次开发都有类似的功能，这些功能都算是基础模板，但并未集成作为项目模板，每次创建项目都可能做重复操作，浪费时间， front-emgine-cli很好的结局啦这一点

- 截图
![front-emgine-cli ](https://raw.githubusercontent.com/xhl592576605/front-engine-cli/main/docs/fengine.gif)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
