### ISSUE TITLE
开源自荐：可以自建的酷炫网络攻击地图

### ISSUE THREAD

**Issue by luckykeeper** [521xueweihan/HelloGitHub#2134]
## 项目自荐
- 项目地址：https://github.com/luckykeeper/attackMap

- 类别：Python

- 项目后续更新计划：目前已经基本完工，有源码部署和 Docker 部署两种方式，建立了文档站，后续可能会针对 Docker 部署作进一步测试

- 项目描述：
  - 我们看过很多的网络攻击地图，但是却没有什么可以自建的前后端解决方案， attackMap 可以让你在自己的网络环境搭建一套只属于你的网络攻击地图，将网络攻击行为可视化
  - 项目建立了[文档站](https://luckykeeper.github.io/attackMap/)，包括架构介绍、部署、二次开发，提供了 Docker 快速部署的视频，即使是初学者也能快速上手

- 推荐理由：完全自建，适应自己的私有网络场景，二次开发简单

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，期待后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
