### ISSUE TITLE
项目推荐 | LSPlant 一款安卓运行时 hook 框架

### ISSUE THREAD

**Issue by SekiBetu** [521xueweihan/HelloGitHub#2137]
## 项目推荐
- 项目地址：https://github.com/LSPosed/LSPlant

- 类别：C++

- 项目后续更新计划：与 [LSPosed](https://github.com/LSPosed/LSPosed) 项目同步更新

- 项目描述：一款安卓运行时 hook 框架，提供 Java 方法的 hook 和 unhook，以及内联优化

- 推荐理由：支持 Android 5.0至13，支持armeabi-v7a, arm64-v8a, x86, x86-64等基础架构，支持自定义 inline hook 和 ART symbol resolver，Xposed 社区比较火热的 [LSPosed](https://github.com/LSPosed/LSPosed) 项目的 [最新版](https://github.com/LSPosed/LSPosed/releases/tag/v1.8.0) 就是基于此项目开发，开发者比较用心

**Comment by 521xueweihan** [comment]
@SekiBetu 我还是推荐 https://github.com/LSPosed/LSPosed 吧，这个太低层了。而且我们也缺 Java 类别的项目😢
