### ISSUE TITLE
【开源自荐】music-dl - 音乐搜索下载器

### ISSUE THREAD

**Issue by guanguans** [521xueweihan/HelloGitHub#2142]
## 项目推荐
- 项目地址：[https://github.com/guanguans/music-dl](https://github.com/guanguans/music-dl)

- 类别：PHP

- 项目后续更新计划：

- 项目描述：
  - 命令行音乐搜索下载器。
  - 支持 QQ 音乐、网易云音乐、酷狗音乐。

- 推荐理由：支持多个平台(QQ 音乐、网易云音乐、酷狗音乐)的音乐搜索下载。

- 示例代码：无

- 截图：

![usage](https://user-images.githubusercontent.com/22309277/160237106-4993ce87-ba91-433e-8fc2-5e82dccb8094.gif)

**Comment by 521xueweihan** [comment]
已推荐过类似的项目
