### ISSUE TITLE
【开源自荐】hertzbeat - 监控告警项目

### ISSUE THREAD

**Issue by tomsun28** [521xueweihan/HelloGitHub#2143]
## 项目推荐
- 项目地址：https://github.com/dromara/hertzbeat

- 类别：Java 

- 项目后续更新计划：监控支持更多应用服务，云原生，开源中间件等监控类型，自定义监控支持更多协议(snmp,jmx)，告警功能增强

- 项目描述：
  - HertzBeat是全职开源的一个支持网站，API，PING，端口，数据库，操作系统等监控类型，拥有易用友好的可视化操作界面的开源监控告警项目。
  - 适用于应用服务，数据库，网站，API，操作系统等监控的场景，提供[云环境](https://console.tancloud.cn/)，希望能帮助开发者和中小团队快速搭建自有监控系统。

- 推荐理由：拥有自定义监控功能，简单易上手，全职维护

- 截图： 演示视频 - https://www.bilibili.com/video/BV1DY4y1i7ts
![输入图片说明](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/9535fcdbdbeb4ed6b4a5bbea51e7744a~tplv-k3u1fbpfcp-zoom-1.image)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 74 期](https://hellogithub.com/periodical/volume/74/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
