### ISSUE TITLE
【自荐】fuck_school: 伟大的用途-锁定电脑屏幕显示倒计时

### ISSUE THREAD

**Issue by 123ABCDF11345** [521xueweihan/HelloGitHub#2144]
## 项目推荐
- 项目地址：[fuck school](https://github.com/123ABCDF11345/fuck_school)

- 类别：Python

- 项目描述：
  - 本项目的初衷是我亲爱的各科老师总是喜欢拖堂，为此，我设计了一款全屏倒计时应用，在下课后自动锁定电脑，并通过一些手段禁止老师关闭此窗口，达到阻止老师拖堂的目的，顺便还能提醒同学们已经下课多久了，何乐而不为呢
  - 适用于各类剥削场景

- 推荐理由：伟大的学生斗争精神，胶水语言快速写GUI的特点

- 截图：
![image](https://user-images.githubusercontent.com/50321657/160276820-e68dc34e-8709-44fa-ae9c-c1b5b2f2b9e7.png)

**Comment by xiao-jay** [comment]
真离谱，哈哈哈哈

**Comment by 521xueweihan** [comment]
@123ABCDF11345 强啊，我的月刊收不下啊
