### ISSUE TITLE
可以 RSS 订阅吗？期待可以订阅

### ISSUE THREAD

**Issue by nanxiaobei** [521xueweihan/HelloGitHub#2145]
现在每次都到这个网页才能看，一下就忘了看了。

希望可以 RSS 订阅。

**Comment by 521xueweihan** [comment]
https://hellogithub.com/rss

**Comment by Miroxyz** [comment]
@521xueweihan 这个 RSS 订阅会有个问题，图片资源会因为防盗链的原因无法正常加载
![image](https://github.com/user-attachments/assets/fe912152-5372-4384-b6a7-c95f4f9082bf)

**Comment by 521xueweihan** [comment]
@Miroxyz 控制图床成本，设置的防盗链
