### ISSUE TITLE
【开源自荐】 lal - Golang流媒体服务器

### ISSUE THREAD

**Issue by q191201771** [521xueweihan/HelloGitHub#2146]
## 项目推荐

- 项目地址： https://github.com/q191201771/lal

- 类别： Go

- 项目后续更新计划：

  - 支持插件化，支持业务方注册自定义协议
  - 支持国标GB28181协议

- 项目描述：

  - 纯Golang开发的流媒体（直播音视频网络传输）服务器。目前已支持RTMP, RTSP(RTP/RTCP), HLS, HTTP[S]/WebSocket[S]-FLV/TS协议。
  - 官方文档： https://pengrl.com/lal

- 推荐理由： 跨平台。高性能。支持多种流媒体协议。

- 截图：

![lal_feature](https://user-images.githubusercontent.com/6093955/160361760-c30cefc9-d4c6-4f04-9081-0bd4f37b4d23.jpeg)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 73 期](https://hellogithub.com/periodical/volume/73/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
