### ISSUE TITLE
【开源自荐】 基于 Python 的内存数据库 CyberDB

### ISSUE THREAD

**Issue by Cyberbolt** [521xueweihan/HelloGitHub#2151]
## 项目推荐
- 项目地址：[CyberDB](https://github.com/Cyberbolt/CyberDB)

- 类别：Python

- 项目后续更新计划：暂定长期更新

- 项目描述：
CyberDB 是一个轻量级的 Python 内存数据库。它旨在利用 Python 内置数据结构 Dictionaries、Lists 作数据存储，通过 Socket TCP 高效通信，并提供数据持久化。该模块可用于 Gunicorn 进程间通信、分布式计算 等领域。高并发场景下，传统数据库的性能瓶颈主要在硬盘 I/O，即便 CyberDB 基于动态语言 Python 开发，速度仍然远快于硬盘数据库(如 MySQL)，CyberDB 可以作为它的缓存。

- 推荐理由：
最为一个内存数据库，CyberDB 的核心在于使用 Pythonic 的方式编程，你可以像使用 Dictionaries 和 Lists 一样使用 CyberDB。

**Comment by MustNull** [comment]
能对接peewee吗

**Comment by Cyberbolt** [comment]
> 能约会peewee吗
CyberDB 属于 NoSQL，原生基于 Python 的，所以不需要 ORM。

**Comment by Cyberbolt** [comment]
> 能对接peewee吗

CyberDB 属于 NoSQL，原生基于 Python 的，所以不需要 ORM。

**Comment by 521xueweihan** [comment]
@Cyberbolt 请问发起这个项目的初衷是什么？

是为了解决某些 redis 无法解决的场景，还是实践用 Python 从头实现 NoSQL 内存数据库。

如果是后者可以加我微信：xueweihan（备注：CyberDB）投稿我们的讲解开源项目系列。
