### ISSUE TITLE
【开源自荐】利用 GitHub Action 自动更新赞助者列表

### ISSUE THREAD

**Issue by yiyungent** [521xueweihan/HelloGitHub#2155]
## 项目推荐
- 项目地址：仅收录 GitHub 的开源项目，请填写 GitHub 的项目地址

> <https://github.com/yiyungent/afdian-action>

- 类别：请从中选择（C、C#、C++、CSS、Go、Java、JS、Kotlin、Objective-C、PHP、Python、Ruby、Swift、其它、书籍、机器学习）

> C#

- 项目后续更新计划：

> - Added: 常用工具类

- 项目描述：
  - 必写：这是个什么项目、能用来干什么、有什么特点或解决了什么痛点
  - 可选：适用于什么场景、能够让初学者学到什么
  - 描述长度（不包含示例代码）: 10 - 256 个字符

> 利用 `GitHub Action` 自动更新来自 `爱发电` 的赞助者列表, 免去人为手动更新赞助列表的烦恼，支持自定义风格及内容

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？

> - 很多开源项目使用了 `爱发电` 作为赞助渠道，同时提供在 `README.md` 的赞助者显示，但人为手动更新赞助者列表较为麻烦，本项目基于 `GitHub Action`  自动更新赞助者列表
> - 支持自定义模板文件，通过模板文件，来自定义风格及内容
> - 由于是 `GitHub Action` 中的一个步骤，也可用于 `Hexo`, `Hugo` 等静态网页生成中添加 赞助页面

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

![image](https://user-images.githubusercontent.com/16939388/162293044-eb59f061-b9d9-4b1c-9e4f-eb650a133492.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
