### ISSUE TITLE
【开源自荐】一个轻量级跨平台交互式Shell工具

### ISSUE THREAD

**Issue by alittlekami** [521xueweihan/HelloGitHub#2156]
## 项目推荐
- 项目地址：https://github.com/b23r0/cliws
- 类别：Rust

- 项目后续更新计划：
- 1. 支持多种通信协议。
- 2. 提供接口库供其他项目调用。

- 项目描述：
  - 必写：项目是一个Rust实现的跨平台的轻量级的交互式PTY Shell。
  - 描述长度（不包含示例代码）: Cliws是一个用Rust开发的轻量级交互式Shell，跨平台，支持正向和反弹连接，通过WebSocket通信，可以帮助运维和渗透测试人员在不需要安装任何依赖环境的情况下（SSH也不需要），快速建立一个远程的Shell，并且支持Vim，Readline，SSH，Ctrl+X等交互式的工具和操作，以及自动设置会话窗口大小。同时支持Windows和Linux，Windows下可以建立一个交互式的Cmd或者Powershell，可以通过Linux连接到Windows的Powershell，或通过Windows连接到Linux的Bash。

- 推荐理由：采用Rust编写，安全稳定可靠。支持Windows和Linux跨平台交互。

- 截图：（可选）gif/png/jpg

![cliws-windows](https://user-images.githubusercontent.com/103354603/162607975-e2e80062-5395-4f6d-8c8d-c83f907c458e.gif)

![cliws-vim](https://user-images.githubusercontent.com/103354603/162607998-3a9f9263-e4ff-478a-aaeb-2379271260d8.gif)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。我认为您的项目适用场景有些局限，可以考虑整合功能、得带成跨平台终端传输、通信工具。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by 521xueweihan** [comment]
做成产品级项目
