### ISSUE TITLE
【开源自荐】Go语言实现的推荐系统引擎

### ISSUE THREAD

**Issue by zhenghaoz** [521xueweihan/HelloGitHub#2158]
## 项目推荐
- 项目地址：https://github.com/gorse-io/gorse

- 类别：Go

- 项目后续更新计划：
  - 支持Kubernetes部署
  - 完善Prometheus监控接口
  - 支持深度学习推荐算法
  - 支持分布式模型训练

- 项目描述：
  - Gorse是一个由Go语言实现的推荐系统引擎。开发者只需要将用户信息、物料信息和用户和物料之间的交互信息（例如点赞、收藏等）写入到Gorse中，Gorse即可使用多种推荐算法为自动为每个用户生成物料推荐。
  - Gorse适用于电商、社交等多种推荐场景。尤其对于没有自研能力的创业团队，Gorse可以解决推荐系统从无到有的问题。

- 推荐理由：无需推荐系统背景知识也能搭建推荐系统

- 示例代码：[快速上手教程](https://docs.gorse.io/chapter_1.html)

- 截图：![](https://raw.githubusercontent.com/gorse-io/gorse/master/assets/dashboard.jpeg)

**Comment by 521xueweihan** [comment]
建议 README 中增加，该系统所需的最低配置和推荐配置

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 73 期](https://hellogithub.com/periodical/volume/73/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
