### ISSUE TITLE
【开源自荐】辅助提醒读README的vscode插件

### ISSUE THREAD

**Issue by ooyyloo** [521xueweihan/HelloGitHub#2159]
## 项目推荐
- 项目地址：[https://github.com/digshare/rtf-readme](https://github.com/digshare/rtf-readme)

- 类别：JS

- 项目后续更新计划：

- 项目描述：
  - 写了个提示读 README 的辅助软件。主要功能是提示程序员去读某个 README ，以及在 CI 中输出哪些人没读哪些 README 。

  - 主要场景是，当修改了一个 README 后，其他人不知道这个 README 被修改过，而其他人改代码之前又应该去读这个 README ，这时候就可以用这个项目提供的插件去提醒修改代码的人去读 README 。

- 推荐理由：当项目中 README 较多时，这个插件就非常好用了～～

- 示例代码：[参考项目README](https://github.com/digshare/rtf-readme/blob/main/README.md)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。使用场景较为固定，而且月刊较少收录 VSCode 插件类型项目

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
