### ISSUE TITLE
开源低时延流式边缘计算框架-YoMo

### ISSUE THREAD

**Issue by Yoname** [521xueweihan/HelloGitHub#2161]
## 项目推荐
- 项目地址：[YoMo](https://github.com/yomorun/yomo)

- 类别：Go

- 项目描述：
  - 介绍：低时延流式边缘计算框架，帮助开发者快速开发“实时交互”应用
  - 应用场景：在应用构建实时数据同步体系，打造实时互动体验的过程中，YoMo 为应用开发提供极简易用的最佳实践，适用于在线协作SaaS、元宇宙（Metaverse）、AR / VR、云游戏、物联网 IoT 等领域。YoMo 以 QUIC 协议为基础，从网络协议、数据编解码等方面优化数据传输速率和稳定性，以保证复杂网络环境下，数据依然可以超低时延传输及处理。YoMo 原生支持多地域分布式的部署模式(Geo-distributed System)，基于 YoMo 的应用可快速在全球不同地域不同公有云的节点中完成部署，助力应用快速迁移至分布式架构（Geo-distributed Architecture），节点间数据可通过 YoMo 低时延传递和同步，使得终端用户可就近访问节点，实时与其他用户或服务交互。

- 推荐理由：The fastest method to deliver realtime functionality.  Speed up the development of metaverse, multiplayer games, collaboration tools

- 截图：
![YoMo: low-latency geo-distributed system](https://user-images.githubusercontent.com/65603/162367572-5a0417fa-e2b2-4d35-8c92-2c95d461706d.png)
![Realtime revolution: components based on yomo](https://ph-files.imgix.net/f805aa36-f584-43df-8533-3485e3446e66.png)
![Realtime cursor chat like figma](https://raw.githubusercontent.com/yomorun/react-cursor-chat/main/show.gif)

**Comment by deathkel** [comment]
请问最后一个T-shirt的例子 在哪可以找到

**Comment by Yoname** [comment]
> 

https://github.com/yomorun/react-cursor-chat
https://github.com/yomorun/presencejs
两个相关repo在这里
Blog：https://dev.to/sayanta66/cursor-chat-integration-with-presencejs-3ejc

**Comment by Yoname** [comment]
> 请问最后一个T-shirt的例子 在哪可以找到

两个相关repo在这里
https://github.com/yomorun/react-cursor-chat
https://github.com/yomorun/presencejs
Blog：https://dev.to/sayanta66/cursor-chat-integration-with-presencejs-3ejc

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 73 期](https://hellogithub.com/periodical/volume/73/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
