### ISSUE TITLE
【开源】HTTP(HTTP/1,HTTP/2)压测工具，支持单机和分布式

### ISSUE THREAD

**Issue by linkxzhou** [521xueweihan/HelloGitHub#2164]
## 项目推荐
- 项目地址：https://github.com/linkxzhou/http_bench

- 类别：Go

- 项目后续更新计划：每周更新

- 项目描述：
  - 小巧的HTTP(HTTP/1,HTTP/2)压测工具，支持单机和分布式
  - 类似wrk的压测，但是该项目支持分布式压测和http2协议，后续会支持http3的压测
  - 近期的版本支持jmeter的标准函数

- 推荐理由：完整的文档样例，小巧，只有700行左右的代码

- 示例代码：[README.md](https://github.com/linkxzhou/http_bench/blob/master/README.md)

**Comment by 521xueweihan** [comment]
@linkxzhou 贵项目将不收录到月刊，可以整理下代码看是否符合 OneFile 项目的要求，可以尝试提交项目：https://github.com/521xueweihan/OneFile
