### ISSUE TITLE
【开源自荐】StreamX ─ Flink极速开发框架,一站式流数据处理平台

### ISSUE THREAD

**Issue by wolfboys** [521xueweihan/HelloGitHub#2166]
## 项目推荐
- 项目地址：https://github.com/streamxhub/streamx
- 类别：Java/Scala/大数据
- 项目后续更新计划：
  - 元数据管理
  - 流逝数仓支持 
  - JAR, UDF等资源统一管理

- 项目描述：
  - 必写：让流处理更简单, Flink & Spark极速开发框架,流批一体一站式大数据平台
  - 描述长度:  项目的初衷是 —— 让流处理更简单, 使用 `StreamX` 开发, 可以极大降低学习成本和开发门槛, 让开发者只用关心最核心的业务, `StreamX` 规范了项目的配置, 鼓励函数式编程, 定义了最佳的编程方式, 提供了一系列开箱即用的 `Connectors`, 标准化了配置、开发、测试、部署、监控、运维的整个过程, 提供了 Scala/Java 两套 api, 其最终目的是打造一个一站式大数据平台, 流批一体,湖仓一体的解决方案

- 推荐理由：批流一体一站式数据平台, Spark & Flink 任务从开发到上线,运维全链路的支持,多家企业生产实践, 简单易用,高效稳定

- 截图：

![](https://user-images.githubusercontent.com/13284744/142746863-856ef1cd-fa0e-4010-b359-c16ca2ad2fb7.png)

![](https://user-images.githubusercontent.com/13284744/142746864-d807d728-423f-41c3-b90d-45ce2c21936b.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 73 期](https://hellogithub.com/periodical/volume/73/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
