### ISSUE TITLE
【开源自荐】Databasir 专注于数据库模型文档的管理平台

### ISSUE THREAD

**Issue by vran-dev** [521xueweihan/HelloGitHub#2167]
## 项目推荐

- 项目地址：https://github.com/vran-dev/databasir

- 类别：Java

- 备注：该项目于 #2110 自荐过一次，经过两个月的迭代对功能、文档都做了更多的完善，故再次自荐。（由于无法 reopen issue，所以额外单开了一个 issue，在此感谢项目发起人提供的机会）

- 项目后续更新计划：

  - 支持 PDF、Word 文档导出
  - 支持 UML 关系保存

- 项目描述：

  **Databasir** 是一款集中式的数据库模型文档管理平台，旨在通过**自动化的方式解决数据模型文档管理过程中维护成本高、内容更新不及时以及团队协作复杂等问题**。

  - 自动化功能：支持自动或手动同步数据库元数据并生成文档
  - 个性化功能：理论上支持所有拥有 JDBC 驱动的数据库、提供了文档模板自定义功能、支持 UML、Markdown 等文档导出
  - 团队化功能：扁平化的角色管理、支持 gitlab / github  OAuth 登录、文档内容变更自动通知等高效协作功能
  - 版本化功能：支持文档版本记录，可以进行版本差异对比，一键查看字段、表、索引等变更详情

  

- 推荐理由：

  在软件行业，API 文档的自动化有着非常广泛而成熟的方案，但数据库模型文档的自动化却还是一片蓝海，我曾在网上搜寻良久，但并没有找到一款能同时满足我以下需求点的产品

  1. **自动化**：基于数据库自动生成文档
  2. **版本化**：文档历史版本回溯，版本差异对比
  3. **团队化**：适应不同团队结构，多样性功能为跨团队协作赋能
  4. **个性化**：给予使用者一定的文档定制能力

  鉴于此，我利用业余的时间开发并开源了 Databasir  这个项目，它的定位就是专注于数据库模型文档的管理。

体验地址：https://demo.databasir.com/

文档地址：https://doc.databasir.com/

项目地址：https://github.com/vran-dev/databasir

- 截图

文档同步

![sync](https://user-images.githubusercontent.com/12870335/163915286-5123a3c5-dfc2-4d6e-8eb2-3c3cd99e9e71.gif)

版本差异对比

![diff](https://user-images.githubusercontent.com/12870335/163915296-63962527-96a3-48cb-936e-38f8e3b7b27a.gif)

自定义文档表头

![template](https://user-images.githubusercontent.com/12870335/163915304-494f5da9-cff7-4f24-b8f6-c4cab1b941d6.gif)

UML 图片导出

![uml-export](https://user-images.githubusercontent.com/12870335/163915311-8846878c-c7a4-4c03-93c2-3a0ed13ba8f6.gif)

导出 Markdown 展示

![markdown-exported](https://user-images.githubusercontent.com/12870335/163915323-ff0d7398-ba38-439b-94c1-37788e17d17c.gif)

**Comment by 521xueweihan** [comment]
开源就是不停迭代，从一个想法变成受“万千宠爱”的产品。

一点小建议：把 README 中的二维码隐去，换成“点击联系”（链接放个人微信号或者公众号二维码），这样有利于项目的推广。

我看到了 Databasir 的变化，按照上述建议修改后将收录到月刊。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 73 期](https://hellogithub.com/periodical/volume/73/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

**Comment by 510457577** [comment]
非常棒！
