### ISSUE TITLE
新推广: 梦胜交易系统(Oybab Trading System)

### ISSUE THREAD

**Issue by padixa** [521xueweihan/HelloGitHub#2169]
## 项目推荐
- 项目地址：https://github.com/oybab/TradingSystem

- 类别：C#

- 项目后续更新计划：增加更多语言

- 项目描述：
  - 必写：一个多语言跨平台开源交易系统. 
  - 可选：支持个人交易管理, 餐厅, 小店, 超市 酒店....等各个领域, 也可以支持二次开发并配合你目前的生意的管理, 统计报表.

- 推荐理由：多语言, 适合结合当前的功能再二次开发自己的项目.

- 截图：
![banner](https://user-images.githubusercontent.com/103999705/163993934-a9ceeac3-4a79-428f-a4c2-fd6e32c59761.jpg)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 73 期](https://hellogithub.com/periodical/volume/73/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
