### ISSUE TITLE
【开源自荐】commitizen适配器 cz-git

### ISSUE THREAD

**Issue by Zhengqbbb** [521xueweihan/HelloGitHub#2170]
## 项目推荐
- 项目地址：仅收录 GitHub 的开源项目，请填写 GitHub 的项目地址
Github: https://github.com/Zhengqbbb/cz-git
文档介绍：https://cz-git.qbenben.com/zh/

- 类别：请从中选择（JS）

- 项目描述：
  - 名称：cz-git
  - 描述：一款工程性更强，高度自定义，标准输出格式的 commitizen 适配器

> 曾被阮一峰周刊推荐 [issue-203-工具-9](https://github.com/ruanyf/weekly/blob/master/docs/issue-203.md#%E5%B7%A5%E5%85%B7)

- 推荐理由：
  - 友好型命令行工具，支持搜索和选择，减少重复性输入，让输出标准化 git commit message 变得简单
  - 高度自定义，让工具的使用更贴合你或团队的习惯
  - 与 commitlint 配合紧密，给予命令行提示信息 | 让 commit 与 issue 关联更简单，特别在 gitee 当中 | 支持emoji

- 截图：
![demo](https://user-images.githubusercontent.com/40693636/154906217-e0b1c5d0-9294-4072-8082-c0cdd9392023.gif)
![logo](https://user-images.githubusercontent.com/40693636/154064210-964aeaa0-d9dc-4cea-9e52-2ffc3789611b.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
