### ISSUE TITLE
【开源自荐】SmartIDE - 云原生时代的集成开发环境(IDE)

### ISSUE THREAD

**Issue by zlweicoder** [521xueweihan/HelloGitHub#2171]
## 项目推荐
- 项目地址：https://github.com/SmartIDE/SmartIDE
- 组织地址：https://github.com/SmartIDE
- 站点地址：https://smartide.cn
- 快速开始：https://www.bilibili.com/video/av336989627?zw

- 类别：JavaScript, Go, NodeJS, DockerFile, Shell Script 等

- 项目后续更新计划：
持续迭代中，目前处于Sprint 17，最新进展：SmartIDE Server版本内测已发布：https://www.bilibili.com/video/BV1bi4y1S71J

- 项目描述：
SmartIDE:
 SmartIDE可以帮助你完成开发环境的一键搭建，你只需要学会一个命令 (smartide start) 就可以在自己所需要的环境中，使用自己喜欢的开发工具进行编码和开发调试了，不再需要安装任何工具，SDK，调试器，编译器，环境变量等繁琐的操作。如果我们把Vscode和JetBrain这些IDE称为传统IDE的话，这些传统IDE最大的问题是：他们虽然在 I (Integration) 和 D (Development) 上面都做的非常不错，但是都没有解决 E (Environment) 的问题。

SmartIDE Server:
SmartIDE Server 为开发团队提供对开发环境的统一在线管理和访问能力，企业管理者可以通过SmartIDE Server为开发团队提供统一的一致的开发环境，大幅降低开发者花费在搭建环境上的时间消耗，让开发者可以将更多的精力投入到业务需求开发和技术方案改进上。更为重要的是，SmartIDE Server提供了完全受控的开发测试环境，管理者可以通过工作区策略对开发环境进行管理，比如：

端到端的代码安全：通过策略配置实现开发者只能通过浏览器修改和发布代码，完全避免开发者将代码下载到个人开发机上；
质量左移：通过指定制定策略在开发者提交代码之前就进行质量门禁的验证，从而彻底杜绝有问题的代码进入代码仓库；
优化DevOps流水线：通过提供与生产环境一致的开发测试环境部署方式，大幅降低DevOps流水线的复杂度，并通过将更多的串行的流水线环节集成到开发编码过程中，大幅缩短流水线运行时间并提高部署成功率。
SmartIDE Server 使用容器和云原生技术，可以部署在任何标准的虚拟化或者k8s平台上，企业云管理员可以自行完成SmartIDE Server的私有部署，并将企业内部开发团队的开发测试环境纳入企业云的管理之中。开发测试环境一旦纳入云平台的管理可以有效降低企业内部开发测试环境的管理复杂度，提高资源利用率；容器化开发测试环境可以根据开发者的需要动态的创建或者销毁环境，为开发测试环境提供弹性伸缩能力。与当前企业中大量使用的基于VDI的开发测试环境管理模式相比，基于容器的开发测试环境将大幅提高资源利用率，同时大幅降低成本。

对于开发者而言，使用SmartIDE Server可以完全消除开发者搭建环境的技能要求，避免因为环境不一致或者工具/SDK版本，安装配置问题所造成的时间浪费，让开发者将更多的精力投入到更有价值的应用开发中去。对于团队而言，当一个团队成员开始使用SmartIDE以后，其他开发者就可以完全重用这个环境，而不必重新配置；如果一名成员变更了环境配置，其他的成员也可以通过一个简单的git pull就可以获取到这个变更后的开发环境。

- 推荐理由：SmartIDE的重点就是要解决 Environment 的问题。

- 截图：
SmartIDE支持模式图
![image](https://user-images.githubusercontent.com/13825714/164130674-3c3bc971-77bd-40a1-99ac-e37d39e651a9.png)
![image](https://user-images.githubusercontent.com/13825714/164131097-72c82969-fcc7-4ba2-b0a4-86abe8ffc638.png)

SmartIDE效果图
![image](https://user-images.githubusercontent.com/13825714/164130725-b3296e22-6e03-4ea6-90dc-a5d89c7ac6a1.png)

SmartIDE Server: http://dev.smartide.cn/
[快速开始](https://smartide.cn/zh/docs/quickstart/server)
![image](https://user-images.githubusercontent.com/13825714/164130823-6918fcab-03e4-4aad-8ab7-86a15b93a9ff.png)

-  视频列表：
[SmartIDE 开发从未如此简单](https://www.bilibili.com/video/BV1pR4y147wn)
[开发从未如此简单 - 谁说vue.js和大型微服务Java Spring项目不能在WebIDE中运行，谁说不能一键部署WebIDE到远程主机](https://www.bilibili.com/video/BV1zb4y1i7B1)
[SmartIDE 产品发布会](https://www.bilibili.com/video/BV1xR4y1s7sx)
[云端开发利器：SmartIDE Server版介绍及操作指南](https://www.bilibili.com/video/BV1bi4y1S71J)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 73 期](https://hellogithub.com/periodical/volume/73/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
