### ISSUE TITLE
项目推荐 | Guice 基于Java的开源依赖注入框架

### ISSUE THREAD

**Issue by SekiBetu** [521xueweihan/HelloGitHub#2172]
## 项目推荐
- 项目地址：https://github.com/google/guice

- 类别：Java

- 项目后续更新计划：谷歌公司推进

- 项目描述：轻量级依赖注入框架，类似于Spring

- 推荐理由：Guice减轻了对factories的需求以及在你的Java代码中对new的使用，你的代码将更容易修改、单元测试和在其他情况下重用，Guice的目标是使开发和调试更容易、更快速，适合个人开发者在小项目中使用，起手快，但可能会有一些问题

**Comment by hklisuper** [comment]
您的邮件我已收到！
