### ISSUE TITLE
Java 程序员进阶之路

### ISSUE THREAD

**Issue by itwanger** [521xueweihan/HelloGitHub#2176]
## 项目推荐

- 项目地址：https://github.com/itwanger/toBeBetterJavaer

- 类别：Java

- 项目后续更新计划：JavaSE 部分基本已经完善，下个阶段打算把 Java 企业级开发内容（Spring Boot 方面完善）

- 项目描述：

  - 必写：一份通俗易懂、风趣幽默的Java学习指南，内容涵盖Java基础、Java并发编程、Java虚拟机、Java企业级开发、Java面试等核心知识点。学Java，就认准Java 程序员进阶之路😄
  - 可选：适用于 Java 初学者，Java 中级开发者
  - 描述长度（不包含示例代码）: 里面大部分是我自己原创的 Java 文章，按照体系化整理了出来，同时配套了在线学习网站，努力打造成一个 Java 一站式学习基地。

- 推荐理由：目前 GitHub 已经星标 2k+，体系已经非常完善，内容也非常丰富。

- 截图：![](https://img-blog.csdnimg.cn/7fa7cbd99d6449288f4e75cb7d771ec4.png)

![](https://cdn.jsdelivr.net/gh/itwanger/toBeBetterJavaer/images/xuexiluxian/java/yitiaolong-a5436c4a-6464-4065-ae0d-50755c4184df.png)

**Comment by 521xueweihan** [comment]
@itwanger 感谢二叔推荐项目！月刊已收录过同类的 Java 学习指南，所以您的项目**暂不收录到月刊**了。
