### ISSUE TITLE
【项目自荐】JamTools

### ISSUE THREAD

**Issue by fandesfyf** [521xueweihan/HelloGitHub#2177]
## 项目推荐
- 项目地址：https://github.com/fandesfyf/JamTools

- 类别：Python

- 项目后续更新计划：一直更新

- 项目描述：
  - 必写：JamTools是一个跨平台的小工具集类软件，支持Windows7/8/10/11、Macos、ubuntu系统(其他系统可以直接从源码编译打包)。包含了(滚动/区域)截屏、录屏、文字识别、多种语言互译、多媒体格式转换、鼠标键盘动作录制播放、局域网文件传输、聊天机器人等功能，完全开源!
  - 可选：各个功能分模块封装，可以单独运行测试，界面采用QT库，新人入门也不难，算是一个比较成熟的软件吧。
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：内置截屏功能，包含滚动截屏、区域截屏、画笔、自动框选目标等等，可以实现微信qq截屏的所有功能(甚至做的比他们还好)；录屏(包含gif等格式录制，可调码率)、音视频格式转换(基于ffmpeg库)、各种多媒体的格式处理、文件批处理功能；鼠标键盘动作录制和重放(可调速度和次数)；局域网(校园网)文件传输，可以进行点对点收发文件或者基于网页端共享文件；还有比较好用的文字识别和翻译集成于各处(比如剪切板翻译--复制英文后按一下shift键马上翻译、右键划过屏幕提取文字等等一些比较方便的功能)；更具体的描述可以看项目主页。项目release里面可以下载各个系统下的安装文件。

- 截图：
- ![!image](https://github.com/fandesfyf/JamTools/raw/main/image/ui.jpg)
- ![!image](https://github.com/fandesfyf/Jamscreenshot/raw/master/image/0180a5748681abe7254ce6734aa64de.png)
- ![!image](https://github.com/fandesfyf/JamTools/raw/main/image/62.png)

**Comment by 521xueweihan** [comment]
我观察了一段时间，感觉该项目更新不积极，暂不收录到月刊中。
