### ISSUE TITLE
请问下该月刊的RSS订阅方法

### ISSUE THREAD

**Issue by AngusWG** [521xueweihan/HelloGitHub#2179]
在官网和github页面都没有找到 RSS的订阅方式，
请问是否有rss的订阅方式

微信公众号(已关注)基本不咋看。。。因为商家的一些推荐活动啥的，信息太多了。

**Comment by 521xueweihan** [comment]
@AngusWG 如果可以的话，可以把我们的公众号标星，这样就会第一时间收到推送。

rss：https://hellogithub.com/rss

**Comment by AngusWG** [comment]
> @AngusWG 如果可以的话，可以把我们的公众号标星，这样就会第一时间收到推送。
> 
> rss：https://hellogithub.com/rss

感谢~ 其实rss放到readme.md里也挺好的   😊
