### ISSUE TITLE
python自动化测试--Android

### ISSUE THREAD

**Issue by Gaoyongxian666** [521xueweihan/HelloGitHub#218]
## 项目推荐
- 项目名称：uiautomater2

- 项目地址：https://github.com/openatx/uiautomator2

- 项目语言：python

- 项目描述：python自动化测试--Android

- 推荐理由：基于wifi

- 示例代码：
`import uiautomator2 as u2
d = u2.connect('10.0.0.1') # alias for u2.connect_wifi('10.0.0.1')
print(d.info)`

- 小例子：https://testerhome.com/topics/11034

**Comment by 521xueweihan** [comment]
@Gaoyongxian666 请填写更多项目描述和推荐理由
