### ISSUE TITLE
项目推荐 Apache ShardingSphere

### ISSUE THREAD

**Issue by terrymanu** [521xueweihan/HelloGitHub#2181]
## 项目推荐

- 项目地址：https://github.com/apache/shardingsphere

- 类别：Java

- 项目后续更新计划：

- 项目描述：
一套开源的分布式数据库增强计算引擎，其通过可插拔架构构建基于数据库之上的生态系统，实现包括数据分片、弹性伸缩、加密脱敏等功能为代表的增强能力。

- 推荐理由：Apache 基金会顶级项目。数据库碎片化下的解决方案，解决了数据分片、数据加密、异构数据查询等痛点。

- 示例代码：

```java
DataSource dataSource = ShardingSphereDataSourceFactory.createDataSource(schemaName, modeConfig, dataSourceMap, ruleConfigs, props);
```

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 74 期](https://hellogithub.com/periodical/volume/74/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
