### ISSUE TITLE
【开源自荐】xfrpc -- FRP(fast reverse proxy)项目的c语言客户端

### ISSUE THREAD

**Issue by liudf0716** [521xueweihan/HelloGitHub#2182]
## 项目推荐
- 项目地址：[xfrpc](https://github.com/liudf0716/xfrpc)

- 类别：c

- 项目后续更新计划：兼容frp项目的服务端frps，持续更新

- 项目描述：
  xfrpc是frp项目的c语言客户端；frp 是一个专注于内网穿透的高性能的反向代理应用，支持 TCP、UDP、HTTP、HTTPS 等多种协议。可以将内网服务以安全、便捷的方式通过具有公网 IP 节点的中转暴露到公网。
  

- 推荐理由：

  由于frp是用golang实现，因此其最终生成的可执行文件超过10M；而在一般基于openwrt的wifi路由器上，flash存储空间较小（8-16M），cpu的性能也较低，很多常用的型号由于存储空间的限制，frp客户端无法安装；而xfrpc由于是基于c语言实现，其无论是对硬件的性能和存储要求都非常低（最终可执行文件大小100k不到），因此可以安装到绝大部分的基于openwrt的wifi路由器上。
  
  xfrpc项目已经被openwrt官方社区收录 ： https://github.com/openwrt/packages/tree/master/net/xfrpc

**Comment by 521xueweihan** [comment]
感谢您的项目。一个很好的项目，解决了某个场景下的痛点。

但因为 openwrt 相关话题会涉及翻墙技术，为了本项目的长治久安您的项目暂不收录


非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
