### ISSUE TITLE
ssh-tools在线ssh系统

### ISSUE THREAD

**Issue by ChoviWu** [521xueweihan/HelloGitHub#2186]
## 项目推荐
- 项目地址：[SSH-tools](https://github.com/planetRun/ssh-tools)
基于WebSSH fork而来，扩展了多个功能
- 类别：Java Javascript

- 项目后续更新计划：

- 项目描述：
  -  在线ssh操作的微系统，无xshell也可以登录服务器，目前支持拖拽上传（上传文件限制需用户定义）
  -  目前支持拖拽上传，后续考虑支持 文件下载，以及ssh私钥登录，免密登录，适配手机等功能
- 推荐理由：摒弃xshell传统的客户端
 

- 截图： 
- 
![image](https://user-images.githubusercontent.com/19967338/165880122-e84409eb-72a4-45c1-a3a6-c1a3f6f8b676.png) 
![image](https://user-images.githubusercontent.com/19967338/165880275-61555768-6f0b-464c-89cf-8b5df6c35d45.png)
![image](https://user-images.githubusercontent.com/19967338/165880324-4734e65a-ff16-421e-82ab-58b46265d437.png)

演示： http://ssh.choviwu.top/

感谢平台

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
