### ISSUE TITLE
微信聊天记录年度报告

### ISSUE THREAD

**Issue by myth984** [521xueweihan/HelloGitHub#2187]
## 项目推荐
- 项目地址：https://github.com/myth984/wechat-report

- 类别：JS

- 项目后续更新计划：

- 项目描述：
  - 必写：和女朋友微信聊天记录统计年度报告
  - 描述长度（不包含示例代码）: 一步一步的教你生成和女朋友的微信聊天记录年度报告

- 推荐理由：各个APP都有年度报告 给女朋友也出一个报告吧

- 截图：
![image](https://user-images.githubusercontent.com/43159834/165904532-48a8948b-e02a-4c5f-8f59-58e3aa89e3e9.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 74 期](https://hellogithub.com/periodical/volume/74/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
