### ISSUE TITLE
【自荐项目】Eoapi： 一个轻量、可拓展的 API 工具

### ISSUE THREAD

**Issue by scarqin** [521xueweihan/HelloGitHub#2188]
## 项目推荐
- 项目地址：[Eoapi](https://github.com/eolinker/eoapi)

- 类别：Javascript、其他

- 项目后续更新计划：
  1. 加入 Mock、协作功能
  2. 插件支持定义 UI
  3. 支持多协议（Websocket、GraphQL 等）API 文档管理以及调试
  4. 丰富插件生态
  
![](https://user-images.githubusercontent.com/15225835/166083471-aebbbb6c-8116-4ef8-a16d-98fc64e87fab.png)

  
- 项目描述：
  - 一个轻量、可拓展的 API 工具
  - 除了提供和 API 有关的核心功能，还可以通过插件市场帮助你将 API 发布到各个应用平台，比如发布到网关上完成 API 上线，或者和低代码平台结合，将 API 快速变成低代码平台中可使用的组件等。

- 推荐理由：

在社区中时常会出现“抱怨某商业产品越来越臃肿”的声音，API 工具也是如此。从最早期只做 API 调试的工具，到经过多年的演进后集成全面功能的“庞然大物”，它越来越成熟了，也越来越不适合最初的那批用户了。我们并不需要用到所有的功能，自然也会觉得自己用不上的功能是“多余”的。

我们希望个性和共性能够共存，因此，我们决定发布这款极其轻量的 API 工具，基础功能仅包括 API 文档和测试，满足开发者最核心的需求。同时：

我们选择支持插件：让每个功能满足所有人的需求是不可能的，通过不断地加功能满足需求只会让产品越做越重。插件系统则不一样，一个插件一个功能，你可以像组装乐高一样组装你想要的功能。

我们选择拥抱开源：我们希望将自己的技术沉淀、解决方案做成开源项目回馈给开源社区，也希望通过开源吸收社区中最棒的想法和实践，联合开发者、企业积极地共创插件生态。

- 截图：
![](https://user-images.githubusercontent.com/15225835/166083651-c718905d-0f30-497d-a35e-f1feb370cd02.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by 521xueweihan** [comment]
此类项目已经推荐很多次了，所以贵项目暂不收录到月刊了。

非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by scarqin** [comment]
@521xueweihan 感谢回复，我可以理解为后续也无法过来提交推荐吗？
