### ISSUE TITLE
自荐项目Contractual

### ISSUE THREAD

**Issue by yankun-song** [521xueweihan/HelloGitHub#2189]
## 项目推荐
- 项目地址：[Contractual](https://github.com/oslabs-beta/contractual)

- 类别：JS

- 项目后续更新计划：
1. 增加web版本；
2. 允许用户设定array中的元素类型和array长度

- 项目描述：
1. Contractual是一款desktop app，允许用户自定义或导入他人定义的API。在此基础上，提供mock request/ response，并进行类型检查，实现前后端的测试分离。
2. 主要使用Typescript， React, Redux和Express，提供了练习机会

- 推荐理由：
Contractual是Typescript和Postman的结合。既可以进行类型检查，也可以发送mock request/ response。

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
