### ISSUE TITLE
自荐项目: Output-Line  在nodejs终端中显示打印语句的文件路径以及行号

### ISSUE THREAD

**Issue by Lete114** [521xueweihan/HelloGitHub#2191]
## 项目推荐
- 项目地址：[Lete114/Output-Line](https://github.com/Lete114/Output-Line)

- 类别：JavaScript

- 项目描述：
  - 必写：在nodejs终端中显示打印语句的文件路径以及行号
  - 可选：适用于代码调试，快速移除遗漏的console.log语句
  - 描述长度: 
     当你写的项目文件过多时，可能有30以上的js文件时，有一个bug需要解决，于是你打了好几个console.log语句用于查看内容输出，当问题解决后你需要将这些输出语句删除，可文件太多，不方便查找，这时你可能会想到使用IDE的全局文件搜索，但是在项目中有些地方也是用了输出语句的，例如`try-catch`输出异常错误等，这时`Output-Line`就派上用场了，它会直接在终端直接显示输出语句的文件夹，可以直接从终端`ctrl+鼠标左键`直接找到输出语句

- 推荐理由：方便调试，也可追踪报错信息由哪一个文件输出，还能追踪到第三方库的输出信息

- 示例代码：
```js
/*
┌────────────┬────────────┬────────────┐
│  property  │  default   │    type    │
├────────────┼────────────┼────────────┤
│   methods  │  Console   │   Array    │
│   prefix   │   '🐞'     │   String   │
│ isRelative │   false    │   Boolean  │
└────────────┴────────────┴────────────┘
*/

// 使用默认参数
// require('output-line')()

// 自定义参数
const options = {
  methods: ['debug', 'log', 'warn', 'error'],
  prefix: '🐸',
  isRelative: true
}
require('output-line')(options)

console.log('%s %d', 'age', 18)

console.log({ f: 'foo', b: 'bar' })
```

- 截图：
![image](https://user-images.githubusercontent.com/48512251/166434885-a8f1a312-2c4c-4537-9ac8-8b29d06a8a5c.png)
![image](https://user-images.githubusercontent.com/48512251/166435154-87031b08-1792-4d76-9924-7c1f6a57ba86.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
