### ISSUE TITLE
项目推荐 mdBook

### ISSUE THREAD

**Issue by AmazonPython** [521xueweihan/HelloGitHub#2194]
## 项目推荐
- 项目地址：[mdBook](https://github.com/rust-lang/mdBook)

- 类别：Rust

- 项目后续更新计划：

- 项目描述：
  - 必写：markdown 构建工具，用 markdown 文件创建书籍。与 Gitbook 类似，使用 Rust 实现。
  - 可选：它非常适合创建产品或 API 文档、教程、课程材料或任何需要简洁、易于导航和可定制的演示文稿。
  - 描述长度（不包含示例代码）: 轻量级 Markdown 语法可帮助您更专注于您的内容。集成搜索支持。许多不同语言的代码块的颜色语法突出显示。为了速度、安全和简单而用 Rust 编写。Rust 代码示例的自动化测试。

- 推荐理由：开源电子书构建工具，简单易用，用于替代 Gitbook 。

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 74 期](https://hellogithub.com/periodical/volume/74/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
