### ISSUE TITLE
自荐项目：Thanks-Mirror

### ISSUE THREAD

**Issue by eryajf** [521xueweihan/HelloGitHub#2196]
- 项目地址：[https://github.com/eryajf/Thanks-Mirror](https://github.com/eryajf/Thanks-Mirror)
- 类别：其它
- 项目后续更新计划：继续补充一下常用软件及其他需要镜像的内容
- 项目描述：这是一个归纳梳理类的项目，整理了常见的包管理工具，软件，系统的国内镜像，以助力运维同学自建企业私服，开发同学直接上手使用。
- 推荐理由：由于国内网络原因，下载依赖包或者软件，对于不少互联网从业者来说，都有不小的挑战，时间浪费在这上边，实在可惜。这个项目介绍了常见依赖，软件的国内镜像，助力大家畅爽编码。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 74 期](https://hellogithub.com/periodical/volume/74/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
