### ISSUE TITLE
自荐项目VisualMaker

### ISSUE THREAD

**Issue by luoyangC** [521xueweihan/HelloGitHub#2197]
## 项目推荐
- 项目地址：https://github.com/luoyangC/visual-maker

- 类别：JS

- 项目后续更新计划：自定义工具和插件能力

- 项目描述：
  - 这是一个低代码平台搭建的项目，可以通过一些简单的拖拽和配置生成页面
  - 使用 Vue 3 Composition API 和 TypeScript，样式基于 Element-plus

- 截图：![Snipaste_2022-04-05_16-51-11](https://user-images.githubusercontent.com/37894210/167620898-0614c884-bb65-460d-8096-a81292525e12.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
