### ISSUE TITLE
自荐项目： 给Mysql 保留字段添加一个别名

### ISSUE THREAD

**Issue by shencangsheng** [521xueweihan/HelloGitHub#2198]
## 项目推荐
- 项目地址：[Mysql-System-Lex-Alias](https://github.com/shencangsheng/Mysql-System-Lex-Alias)

- 类别：其它

- 项目后续更新计划：
  - 支持更多的版本
  - 更好的编译策略
  - 支持更多的函数 

- 项目描述：
  - 给你的 Mysql 系统保留字段添加一个别名，如果你也被各种自己防火墙拦截SQL注入导致业务接口无法正常使用，那么就给你的Mysql数据库系统关键词添加一个别名吧。
  - 防火墙拦截SQL注入导致业务接口无法正常使用
  - `REGEXP` 被拦截，那么我们就换一个名字。

- 推荐理由：轻松的给你的MySQL添加一个系统关键词的别名，无需了解MYSQL源码即可完成，只需要一个Docker，无需环境依赖。

- 示例代码：

下载 MYSQL 源码

```bash
wget https://codeload.github.com/mysql/mysql-server/zip/refs/heads/5.7
unzip mysql-server-5.7.zip
```

添加一个系统关键词别名

```bash
docker run --rm -v $(pwd)/mysql-server-5.7:/mysql-server-5.7 shencangsheng/mysql-system-lex-alias add-lex-alias -f /mysql-server-5.7 -c REGEXP -v REGEXP_ALIAS
```

  编译源代码

    基于多层构建编译，性能极佳 **[推荐]**

```bash
docker build --target compile --target compile-builder -t ${username}/mysql:latest .
```

- 截图： 
![image](https://user-images.githubusercontent.com/67856731/167760187-1569d6ee-7cd4-4fdd-bca8-60deebd32357.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
