### ISSUE TITLE
有趣的项目推荐

### ISSUE THREAD

**Issue by erguotou520** [521xueweihan/HelloGitHub#22]
- [中国程序员容易发音错误的单词](https://github.com/shimohq/chinese-programmer-wrong-pronunciation)
- [前后端分离+服务端渲染的博客系统. 基于Vue2, Koa2, MongoDB, Redis](https://github.com/Smallpath/Blog)  博客地址[https://smallpath.me/](https://smallpath.me/)，相应速度超快

**Comment by 521xueweihan** [comment]
@erguotou520 感谢推荐项目，第一个项目已经有了。

后面如果第二个项目收进 HelloGitHub 我会在本 issue 中回复您；

**Comment by erguotou520** [comment]
咦~ 我过了一遍所有的月刊，似乎没发现，可能是一行文字的我都一眼扫过去了吧 😸

**Comment by 521xueweihan** [comment]
@erguotou520 [11 期](https://github.com/521xueweihan/HelloGitHub/blob/master/11/HelloGitHub11.md#其它)

是的，我也发现这个问题了，随着项目的增多，我自己在收集项目的时候也会出现重复。😅

所以，我写了一个脚本把月刊的数据放到数据库，方便后面的更多的延伸。

**Comment by 521xueweihan** [comment]
不好意思，请重新[创建 issues](https://github.com/521xueweihan/HelloGitHub/issues/new)，根据推荐项目的模版，规范推荐项目格式、完善信息。
