### ISSUE TITLE
DzzOffice 类似Google企业套件，Office365开源方案 

### ISSUE THREAD

**Issue by fhxsnabi** [521xueweihan/HelloGitHub#220]
## 项目推荐
- 项目名称：DzzOffice

- 项目地址：https://github.com/zyx0814/dzzoffice

- 演示地址：http://demo.dzzoffice.com/

- 项目语言：PHP

- 项目描述：Dzzoffice是一套开源办公套件，适用于企业、团队搭建自己的 类似“Google企业应用套件”、“微软Office365”的企业协同办公平台。

- 推荐理由：一套功能完善的开源私有化办公解决方案。

- 截图：![](http://lebook.me/index.php?mod=io&op=thumbnail&width=0&height=0&original=1&path=aG9GZEV2LzNYc1ZjOVVoTDlvYzRCamdsMkQxZS9JK2k0NzFmUFUycmNqTjBaKzdzMnlWZEhXVQ==)

**Comment by JameJJ** [comment]
你好，我看了一下这应该是你的个人项目吧，能否方便介绍一下产品的使用和推广情况吗

**Comment by 521xueweihan** [comment]
@fhxsnabi 您推荐的项目，已成功收录在 [HelloGitHub 第 24 期](https://hellogithub.com/volume/24/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
