### ISSUE TITLE
【自荐】ACNumpad，为主键盘区添加数字小键盘

### ISSUE THREAD

**Issue by AstronChen** [521xueweihan/HelloGitHub#2200]
## 项目推荐
- 项目地址：[ACNumpad](https://github.com/AstronChen/ACNumpad)

- 类别：AutoHotkey

- 平台
Windows

- 项目后续更新计划：
  - 增加自定义键位映射功能。
  - 保持软件简洁。

- 项目描述：
  - 运行于后台，在主键盘区增加可随时开关的数字小键盘。
  - 绿色，免费，简单，高效。
  - 相对于其他同类软件，切换方式更顺手，快捷键冲突少。

  - 解决以下问题：
    ①快速输入数字。
    ②使用小键盘快捷键可大幅提升效率的应用。如几个著名的音视频制作软件。

## 1. 安装
a、 解压缩到任何地方。运行。
b、 （可选）向Startup文件夹发送快捷方式。

为当前用户安装：
```
%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
```
为所有本地用户安装：
```
%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup
```

c、 （可选）进入设置-个性化设置-任务栏-其他系统托盘图标。切换以持续显示ACNumpad。

## 2. 使用

ACNumpad静默运行于后台。会显示一个托盘图标，帮助您确定是否开启了数字小键盘。

ACNumpad刚启动时，默认挂起。托盘图标为红色，不会对键盘进行任何更改。

当你按下右侧Alt+，（逗号）或点击任务栏图标右键菜单中的“Toggle Suspend”时，Numpad激活。托盘图标变为绿色。

按键变更如下：

![image](https://user-images.githubusercontent.com/54497232/167413009-dc0d30ec-b7c3-4919-85da-c5b8b00b6fba.png)

## 3. 卸载

退出ACNumpad并删除目录文件。

# 截图

![image](https://user-images.githubusercontent.com/54497232/167413255-97e595f9-1737-4eb3-9895-1504a766f3a2.png)

![image](https://user-images.githubusercontent.com/54497232/167415198-5a6bb9a2-6332-4c58-a2e6-04ca28a98848.png)

# 相关工具

AutoHotkey: https://www.autohotkey.com/

Ahk2Exe: https://github.com/AutoHotkey/Ahk2Exe

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
