### ISSUE TITLE
[自荐] toml-bench: which toml package to use in python?

### ISSUE THREAD

**Issue by pwwang** [521xueweihan/HelloGitHub#2202]
## 项目推荐
- 项目地址：https://github.com/pwwang/toml-bench

- 类别：python

- 项目后续更新计划：
  - 增加更多的测试
  - 持续更新当不同的toml包发布新版本时
  - 持续更新速度测试当benchmark data更新或者有不同的benchmark data发布时

- 项目描述：
  这个项目对python中不同toml包进行了测试，让人更全面的了解不同的toml包的优缺点。让人很容易选择适当自己项目的toml包。也让toml包开发者有了一套基准测试，让他们对自己的包的优缺点了如指掌并在后续进行针对性改进。

- 推荐理由：
  在开发python项目涉及使用toml配置文件的时候总是不知道该使用哪个toml包。这个项目从各个方面对python中的toml包进行了测试，让人更容易做出选择。

- 示例代码：

- 截图：

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
