### ISSUE TITLE
【开源自荐】一个可以用纯粹的Flutter来开发Android浮动窗口的插件。

### ISSUE THREAD

**Issue by jiusanzhou** [521xueweihan/HelloGitHub#2205]
## 项目推荐

- 项目地址：https://github.com/jiusanzhou/flutter_floatwing

- 类别：其它

- 项目后续更新计划：
  - Features: 支持位置移动的动画
  - Features: 支持拖拽锚点设置
  - Improve: 增加事件订阅优化性能

- 项目描述：该Flutter插件可以让开发者完全使用Flutter来开发Android的浮动窗口。

- 推荐理由：一个可以用纯粹的Flutter来开发Android浮动窗口的插件。目前社区内没有一款好用的插件来支持该功能，该插件能够让Flutter开发者完全使用Flutter来完成浮动窗口的功能开发，同时无需任何原生Android开发背景。

- 示例代码：
  ```dart
    @override
    Widget build(BuildContext context) {
      return MaterialApp(
        debugShowCheckedModeBanner: false,
        initialRoute: "/",
        routes: {
            "/": (_) => HomePage(),
            // add a route as entrypoint for your overlay window.
            "/my-overlay-window": ((_) => MyOverlayWindow()).floatwing(),
        },
      );
    }
  
    void _startWindow() {
          // define window config and start the window from config.
          WindowConfig(route: "/my-overlay-window") 
              .to() // create a window object
              .create(start: true); // create the window and start the overlay window.
      }
  ```

- 截图：
  |Night mode|Simpe example|Assistive touch mock|
  |:-:|:-:|:-:|
  |![](https://github.com/jiusanzhou/flutter_floatwing/raw/main/assets/flutter-floatwing-example-1.gif)|![](https://github.com/jiusanzhou/flutter_floatwing/raw/main/assets/flutter-floatwing-example-2.gif)|![](https://github.com/jiusanzhou/flutter_floatwing/raw/main/assets/flutter-floatwing-example-3.gif)|

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 74 期](https://hellogithub.com/periodical/volume/74/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
