### ISSUE TITLE
【开源自荐】一款支持多人协同的React表格组件

### ISSUE THREAD

**Issue by zyc9012** [521xueweihan/HelloGitHub#2207]
## 项目推荐
- 项目地址：https://github.com/ruilisi/fortune-sheet

- 类别：JS

- 项目后续更新计划：
  - 支持Excel导入导出
  - 支持Vue
  - 支持筛选、条件格式、图表等高级功能

- 项目描述：
  
  FortuneSheet是一款开箱即用的类似Excel和Google Sheets的javascript表格组件。
  本项目源于Luckysheet，将代码用Typescript + React重写，并优化和解决了原项目设计层面的问题。
  
  优化点包括：
  - 可以用 `import` / `require` 导入本库了。
  - 同页面支持多个实例。
  - 去掉了 `jQuery` 的依赖, 用原生 `React` + `immer` 来管理Dom和状态。
  - 用一个forked [handsontable/formula-parser](https://github.com/handsontable/formula-parser) 来处理公式计算。
  - 去除了强制使用websocket和内置格式做后台数据更新，仅产生数据更新回调，使更新方式更灵活
  - 用SVG代替`iconfont`的图标，因为`iconfont`的图标对其他开发者而言很不方便改动。
  - ……见github页

- 推荐理由：
  - 开箱即用，无需繁琐配置
  - 内置多种Excel常用功能
  - 支持在线协同，在远程办公和在线文档编辑越发重要的当下，帮助开发者快速构建在线Excel表格

- 示例代码：

```js
import React from 'react';
import ReactDOM from 'react-dom';
import { Workbook } from "@fortune-sheet/react";
import "@fortune-sheet/react/dist/index.css"

ReactDOM.render(
  <Workbook data={[{ name: "Sheet1" }]} />,
  document.getElementById('root')
);
```

- 截图：

![Large GIF (620x816)](https://user-images.githubusercontent.com/3034310/168759011-13b4e43f-578c-4018-803b-4633fe573e9d.gif)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 74 期](https://hellogithub.com/periodical/volume/74/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
