### ISSUE TITLE
Linux下使用触控板手势切换工作区

### ISSUE THREAD

**Issue by CuberL** [521xueweihan/HelloGitHub#221]
## 项目推荐
- 项目名称：swipe-workspace

- 项目地址：https://github.com/CuberL/swipe-workspace

- 项目语言：C

- 项目描述：一个C编写的，基于libinput的程序，可以使用二指在触控板滑动来切换工作区

- 推荐理由：提高使用触控板时的工作效率

- 示例代码：

- 截图: 
![](http://7tebhf.com1.z0.glb.clouddn.com/output1.gif)

**Comment by 521xueweihan** [comment]
@CuberL 功能虽然简单，且无跨平台。但是十分推荐这种通过自己的代码实现一个实用的功能，Nice

**Comment by 521xueweihan** [comment]
@CuberL  您推荐的项目，已成功收录在 [HelloGitHub 第 25 期](https://hellogithub.com/volume/25/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
