### ISSUE TITLE
【工具自荐】一款将链接转化为精美分享图的小工具

### ISSUE THREAD

**Issue by xiaoluoboding** [521xueweihan/HelloGitHub#2211]
## 项目推荐

- 项目地址：https://github.com/one-tab-group/bookmark.style

- 类别：Vue

- 项目描述：

    最近将一直自用的一款将任意链接转换生成分享图的工具 [bookmark.style](https://bookmark.style/) 发布到了 [ProductHunt](https://www.producthunt.com/posts/bookmark-style)

- 推荐理由：bookmark.style 适用于开发者、创作者、公众号写手，它可以美化你的链接，让你的链接“开口说话”

- 截图:

![image](https://user-images.githubusercontent.com/6118824/165920506-bf01e5e0-fd7b-4996-9b30-eb17fd1092f6.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
