### ISSUE TITLE
【工具自荐】一键将标签页转化为精美分享图的 Chrome 插件

### ISSUE THREAD

**Issue by xiaoluoboding** [521xueweihan/HelloGitHub#2212]
## 项目推荐

- 项目地址：https://github.com/one-tab-group/chrome-web-bookmark

- 类别：Vue

- 项目描述:

  一键将标签页转化为精美分享图的 Chrome 插件

  🔗 插件链接：https://chrome.google.com/webstore/detail/web-visual-bookmark/jcfidgjldodhkpiebmemhnhgpgdakham/

- 推荐理由：分享图适用于开发者、创作者、公众号写手

- 截图:

![CleanShot 2022-05-16 at 11 04 32@2x](https://user-images.githubusercontent.com/6118824/168513138-eb394234-de07-4081-9b0c-1991f309d2c1.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
