### ISSUE TITLE
【开源自荐】极易扩展的无代码开发平台 NocoBase

### ISSUE THREAD

**Issue by zhouyanliang** [521xueweihan/HelloGitHub#2217]
## 项目推荐
- 项目地址：https://github.com/nocobase/nocobase

- 类别：JS

- 项目后续更新计划：一方面持续完善核心架构；另一方面持续开发更多插件。接下来几个月的 Roadmap：https://docs.nocobase.com/roadmap

- 项目描述：
  - NocoBase 是一个极易扩展的开源无代码开发平台。 无需编程，使用 NocoBase 搭建自己的协作平台、管理系统，只需要几分钟时间。
  - 如果你有以下需求，NocoBase 就是为你设计的：
    - 开发组织内部管理系统
    - 通过无代码开发，满足大部分业务需求
    - 通过扩展开发，满足个性化业务需求
    - 系统功能需要频繁变动
    - 开源免费，私有部署，掌控全部代码和数据

- 推荐理由：NocoBase 最重要的特点是便于扩展开发。无代码可以节省大量的成本，但无法满足所有业务需求，NocoBase 通过无代码搭建满足大部分业务场景，剩余的个性化需求可以很方便的通过扩展开发来实现。

- 截图：

![](https://www.nocobase.com/images/demo/11.png)

![](https://www.nocobase.com/images/feature/blocks.gif)

**Comment by zhouyanliang** [comment]
> @zhouyanliang “在线尝试”建议：取消收集用户信息和建议的表单。

感谢建议。

目前表单里需要的用户准确信息只有邮箱，之所以需要邮箱是因为我们每个 demo 都是创建一个独立的应用，每个独立应用都会绑定一个随机生成的域名。将域名发送给用户，用户可以长时间体验；如果不发送的话，用户记不住这个域名，会找不到自己的应用（我们有不少体验用户是直接在 demo 里花比较长的时间搭一个自己的系统）。

邮箱以外的几个字段算是简单的调研，有部分用户会随便填几个字母，不会影响开通 demo。最近我们发布新版本并更新 demo，到时候会根据你的建议调整这几个字段。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 77 期](https://hellogithub.com/periodical/volume/77/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
