### ISSUE TITLE
项目推荐   https://github.com/debezium/debezium

### ISSUE THREAD

**Issue by flyingfz** [521xueweihan/HelloGitHub#2218]
## 项目推荐
- 项目地址：[debezium](https://github.com/debezium/debezium)

- 类别：Java

- 项目后续更新计划：

- 项目描述：
 Debezium是一个开源项目，为捕获数据更改(change data capture,CDC)提供了一个低延迟的流式处理平台。你可以安装并且配置Debezium去监控你的数据库，然后你的应用就可以消费对数据库的每一个行级别(row-level)的更改。只有已提交的更改才是可见的，所以你的应用不用担心事务(transaction)或者更改被回滚(roll back)。Debezium为所有的数据库更改事件提供了一个统一的模型，所以你的应用不用担心每一种数据库管理系统的错综复杂性。另外，由于Debezium用持久化的、有副本备份的日志来记录数据库数据变化的历史，因此，你的应用可以随时停止再重启，而不会错过它停止运行时发生的事件，保证了所有的事件都能被正确地、完全地处理掉。

- Debezium有很多非常有价值的使用场景，我们在这儿仅仅列出几个更常见的使用场景：

  - 缓存失效(Cache invalidation)
  - 简化单体应用(Simplifying monolithic applications)
  - 共享数据库(Sharing databases)
  - 命令查询职责分离(CQRS)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 74 期](https://hellogithub.com/periodical/volume/74/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
