### ISSUE TITLE
marshmallow: 轻量级的serialization library

### ISSUE THREAD

**Issue by franklingu** [521xueweihan/HelloGitHub#222]
## 项目推荐
- 项目名称：
marshmallow
- 项目地址：
https://github.com/marshmallow-code/marshmallow
- 项目语言：
python
- 项目描述：
marshmallow is an ORM/ODM/framework-agnostic library for converting complex datatypes, such as objects, to and from native Python datatypes.
- 推荐理由：
https://news.ycombinator.com/item?id=10788814
- 示例代码：
```python
from datetime import date
from marshmallow import Schema, fields, pprint

class ArtistSchema(Schema):
    name = fields.Str()

class AlbumSchema(Schema):
    title = fields.Str()
    release_date = fields.Date()
    artist = fields.Nested(ArtistSchema())

bowie = dict(name='David Bowie')
album = dict(artist=bowie, title='Hunky Dory', release_date=date(1971, 12, 17))

schema = AlbumSchema()
result = schema.dump(album)
pprint(result, indent=2)
# { 'artist': {'name': 'David Bowie'},
#   'release_date': '1971-12-17',
#   'title': 'Hunky Dory'}
```

**Comment by 521xueweihan** [comment]
@franklingu 请增加更多的中文描述，从初学者、上手方面、应用场景方面介绍推荐的项目

**Comment by franklingu** [comment]
可以validate input数据，序列化和反序列化

1. 这个library没有对数据层有限制，可以是django，flask，或者其他比如sqlalchemy
2. syntax和django orm或者django rest之类的很相似，可以很快上手
3. 非常的flexible：比如partial serialization，nested schema之类的

**Comment by 521xueweihan** [comment]
@franklingu   您推荐的项目，已成功收录在 [HelloGitHub 第 26 期](https://hellogithub.com/periodical/volume/26/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
