### ISSUE TITLE
【开源自荐】code996 - 分析 Git 项目的编码工作强度

### ISSUE THREAD

**Issue by hellodigua** [521xueweihan/HelloGitHub#2221]
## 项目推荐

- 项目地址：https://github.com/hellodigua/code996

- 类别：JS

- 项目后续更新计划：

  - 国际化、本地部署服务等功能性优化
  - 推导结果的算法优化

- 项目描述：

  - code996 是一个分析工具，它可以统计 Git 项目的 commit 时间分布，进而推导出这个项目的编码工作强度。

  - 预览地址：https://hellodigua.github.io/code996/#/

- 用途：

  - 分析 Git 项目的 commit 提交时间数据
  - 入职新公司后了解项目是否存在 996 现象
  - 在上班的摸鱼时光找点乐子

- 推荐理由：

  - 工具分为shell端和web端，代码易于理解，方便根据自己需求扩展。

  - 解决的痛点：在对加班情况标准化之后，我们可以方便的对跨团队、跨公司项目的工作强度进行对比。

- 示例代码：

  - Mac 或 Linux 用户，在 Git 项目的根目录，执行以下命令：

    ```
    /bin/bash -c "$(curl -fsSL https://fastly.jsdelivr.net/gh/hellodigua/code996/bin/code996.sh)"
    ```

  - Windows 用户，下载该脚本 `https://fastly.jsdelivr.net/gh/hellodigua/code996/bin/code996.sh`，然后将该脚本移至要分析的 Git 项目目录，并执行以下命令：

    `sh code996.sh`

- 截图：

分析项目的基本情况：

![](https://fastly.jsdelivr.net/gh/hellodigua/code996@master/public/preview/1.png)

通过图表查看 commit 提交分布：

![](https://fastly.jsdelivr.net/gh/hellodigua/code996@master/public/preview/2.png)

对比项目工作时间类型：

![](https://fastly.jsdelivr.net/gh/hellodigua/code996@master/public/preview/3.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 74 期](https://hellogithub.com/periodical/volume/74/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
