### ISSUE TITLE
基于netty的websocket springboot starter

### ISSUE THREAD

**Issue by fzdwx** [521xueweihan/HelloGitHub#2222]
## 项目推荐
- 项目地址：https://github.com/fzdwx/sky

- 类别：Java

- 项目后续更新计划：
1.  完善和spring boot web的适配度（当然还可以脱离spring环境运行）
2. 寻找替代filter的方法（因为没对servlet这一块的适配有点问题，最近在想解决方案。）
3. ...

- 项目描述：
>  ⚡ 快速基于Netty创建出你自己的服务（HTTP，Weboscket，TCP...） quickly create an http service or websocket service.(lightweight high-performance maybe?)
 
- 适用于什么场景、能够让初学者学到什么?
>  使用更底层的api来进行websocket开发。

- 推荐理由：既可以同时提供http服务也可以提供websocket服务。

- 示例代码:
![image](https://user-images.githubusercontent.com/65269574/170430948-2489040a-f01f-49d6-a5ea-647045d538b1.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
