### ISSUE TITLE
项目推荐｜思源笔记

### ISSUE THREAD

**Issue by heheda123123** [521xueweihan/HelloGitHub#2223]
## 项目推荐
- 项目地址：https://github.com/siyuan-note/siyuan

- 类别：JS、Go

- 项目后续更新计划：持续更新

- 项目描述：
  - 思源笔记是一款本地优先的个人知识管理系统， 支持细粒度块级引用和 Markdown 所见即所得。

- 推荐理由：完全开源，支持端到端加密，作者更新反馈快

- 截图：
![image](https://user-images.githubusercontent.com/97490782/170444658-72e03cf3-9518-4b51-b6de-fa3fe8523625.png)

**Comment by 521xueweihan** [comment]
@heheda123123 月刊已收录过类似功能的项目
