### ISSUE TITLE
2048-Vue

### ISSUE THREAD

**Issue by 321paranoiawhy** [521xueweihan/HelloGitHub#2224]
## 项目推荐 2048-Vue

- 项目地址：https://github.com/321paranoiawhy/2048

- 类别：JavaScript Vue

- 项目后续更新计划：基本功能已开发完毕, 后续如有需求可继续更新

- 项目描述：

这是用 Vue 写的 2048，可深度定制网格大小、初始数字个数、初始数字概率、新增数字个数和新增数字概率等，详见https://not-just-2048-vue.netlify.app/

- 推荐理由：可深度定制，10x10，20x20 甚至无限大网格(或许可以哦)都可以

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
