### ISSUE TITLE
【开源自荐】基于golang开发的一款开箱即用的跨平台文件同步工具

### ISSUE THREAD

**Issue by mstmdev** [521xueweihan/HelloGitHub#2225]
## 项目推荐
- 项目地址：[https://github.com/no-src/gofs](https://github.com/no-src/gofs)

- 类别：Go

- 项目后续更新计划：
  - 支持FTP、SFTP以及第三方云存储
  - 内置中继模式支持
  - 支持版本控制
  - 支持自定义文件变更通知回调
  - 新增Web管理以及监控平台

- 项目描述：
  - gofs是基于golang开发的一款开箱即用的跨平台文件同步工具，支持在本地磁盘之间同步、从远程服务器同步变更到本地、将本地文件变更推送到远程服务器三种场景模式
  - 通过第三方内网穿透工具进行中继，可以实现两台不同局域网的电脑之间的文件同步

- 推荐理由：跨平台，开箱即用，适用不同场景的同步需求，支持实时同步以及定时同步，支持大文件上传，增量同步

**Comment by 521xueweihan** [comment]
您的项目暂不能收录，已推荐过两个类似功能的项目。

![image](https://user-images.githubusercontent.com/8255800/174922190-c7eb84ab-ff18-4757-848f-2e5a08579c53.png)
