### ISSUE TITLE
LeetCode-C++

### ISSUE THREAD

**Issue by shijianzugouniai** [521xueweihan/HelloGitHub#2228]
## 推荐项目

- 项目地址：https://github.com/wisdompeak/LeetCode

- 类别：C++

- 项目标题： 包含LeetCode上算法问题的解决方案和解释。仅包括中等或以上。所有这些都是用C++ / Python编写的。多次尝试的问题都标有超链接。

- 项目描述：提高程序员的数据结构与算法知识，这个博主将LeetCode里面类似的题目整理在一起了，因此推荐在几天之内做一道题之后就把同类型全部做完，完全掌握这个知识点，这比今天做了一道，仿佛明白了但又不熟，然后明天又做了个别的题更有效。算法就是让你think as a computer，经验可以通过长期的工作积累得到，思维却是无法这样得到的。 

- 亮点：采用C++编写程序，题目难度在medium和hard范围内，算法是程序的灵魂，思维则是算法的灵魂，这就是我们选择写算法题的重要原因，锻炼思维。  
- 示例代码：（可选）

- 截图：（可选）gif/png/jpg
- 
![image](https://user-images.githubusercontent.com/86582822/170812666-bba2a057-9c0d-424e-bd8e-fed37774fe13.png)

- 后续更新计划：

**Comment by 521xueweihan** [comment]
月刊在尽量克制收录算法题解的理解，感谢理解
