### ISSUE TITLE
【自荐项目】KCL：一个Rust开发的面向云原生的配置策略语言

### ISSUE THREAD

**Issue by chai2010** [521xueweihan/HelloGitHub#2231]
## 推荐项目

- 项目地址：https://github.com/KusionStack/KCLVM

- 类别：Rust

- 项目标题：KCL 配置策略语言

- 项目描述：面向云原生领域，基于 Rust 实现的 配置策略语言，特点 [简单、稳定、协同配置、工程化、高性能](https://kusionstack.io/docs/user_docs/concepts/kcl-lang)

- 亮点：https://kusionstack.io/docs/user_docs/concepts/kcl-lang

- 示例代码：（可选）

- 截图：![](https://kusionstack.io/assets/images/hello-86644801c77c9a1ca5662da7e16dd1de.gif)

- 后续更新计划：https://kusionstack.io/docs/governance/intro/roadmap

![](https://raw.githubusercontent.com/KusionStack/community/main/logo/kusionstack-color2.png)

**Comment by 521xueweihan** [comment]
@chai2010  该项目暂时不能收录，已推过类似的配置语言 toml
