### ISSUE TITLE
推荐个最好的Vue方向table库 VXE-table,甚至不止于table

### ISSUE THREAD

**Issue by adoin** [521xueweihan/HelloGitHub#2234]
## 推荐项目

- 项目地址：https://github.com/x-extends/vxe-table

- 类别：JS

- 项目标题：
Vue生态内最好的表格和表单组件

- 项目描述：
无限长能渲染大数据的虚拟滚动表格（包括树形和行扩展）。大数据懒加载的树形表格。配置式书写表单表格等。全局任意组件封装渲染器，以声明使用在表单表格内。

- 亮点：除了UI组件没有，差不多你能想到的需求都能实现，比起Element和antdv的表格高出好几个大气层

- 示例代码：（可选）
-- DOM：
<vxe-grid v-bind="gridSettings" class="mg-top-md" @cell-dblClick="editRow"></vxe-grid>
-- JS：
computed:{
gridSettings () {
      return {
        ref: 'mainGrid',
        data: this.shiftData,
        height: 600,
        border: 'full',
        align: 'center',
        columns: [
          { field: 'shiftName', title: '班次名称', width: 180 },
          { field: 'dept', title: '班次部门', minWidth: 180 },
          { field: 'isFixed', title: '考勤分类', width: 100, formatter: ({ cellValue }) => cellValue ? '固定班次' : '其他班次' },
          {
            field: 'startAt', title: '上班时间', width: 100,
            formatter: ({ cellValue, row }) => this.getFixedTime(cellValue, row.flexMinutes)
          },
          {
            field: 'endAt', title: '下班时间', width: 100,
            formatter: ({ cellValue, row }) => this.getFixedTime(cellValue, row.flexMinutes)
          },
          { field: 'breakFrom', title: '间休开始时间', width: 120, formatter: ({ cellValue }) => this.formatTime(cellValue) },
          { field: 'breakTo', title: '间休结束时间', width: 120, formatter: ({ cellValue }) => this.formatTime(cellValue) },
          {
            field: 'weekendType',
            title: '休息日',
            width: 260,
            formatter: ({ cellValue }) => cellValue ? this.weekendTypeOptions.find(f => f.value === cellValue).label : '周末双休'
          },
          {
            field: 'operation',
            title: '操作',
            width: 220,
            fixed: 'right',
            cellRender: {
              name: '$buttons',
              children: [
                {
                  props: { content: '分配部门', status: 'primary', icon: 'fa fa-wrench' },
                  events: { click: this.startDistribution }
                },
                {
                  props: { content: '删除', status: 'danger', icon: 'fa fa-trash' },
                  events: { click: this.deleteShift }
                }
              ]
            }
          }
        ]
      }
    },

}
- 截图：（可选）gif/png/jpg

- 后续更新计划：

**Comment by 521xueweihan** [comment]
@adoin 您推荐的项目，**已成功发布**在 [HelloGitHub 第 76 期](https://mp.weixin.qq.com/s/L3GP5DcTJb-3Z6kbB-OK7w)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
