### ISSUE TITLE
【推荐项目】仿生英文阅读

### ISSUE THREAD

**Issue by JaneDoe2233** [521xueweihan/HelloGitHub#2236]
## 推荐项目

- 项目地址：https://github.com/ansh/jiffyreader.com

- 类别：JS

- 项目标题：仿生英文阅读（Bionic Reading）浏览器插件

- 项目描述：通过加粗单词的部分字母，让人更方便快速的阅读英文文章、书籍等。

- 亮点：加速阅读

- 示例代码：（可选）

- 截图：（可选）gif/png/jpg
![1fce3edaa97eaab0859b0c7d4e60634](https://user-images.githubusercontent.com/76079648/171568051-0f87421c-388a-4561-8553-436ae65a2971.jpg)

- 后续更新计划：未知

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 75 期](https://hellogithub.com/periodical/volume/75/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
