### ISSUE TITLE
【开源自荐】hot-chocolate 前端浏览器上的微前端沙箱

### ISSUE THREAD

**Issue by huey-LS** [521xueweihan/HelloGitHub#2237]
## 推荐项目

- 项目地址：https://github.com/NeteaseLofter/hot-chocolate

- 类别：JS

- 项目标题：
hot-chocolate 是浏览器端运行的沙箱框架。

- 项目描述：
hot-chocolate 可以广泛的运用于微前端系统中，帮助大家在一些巨石的项目中完成新老版本切换和共存。
其目标是零修改即可运行现有代码，目前已经正常的运行react、vue等多种不同框架的项目，其是对原生js上的修改，对框架本身并无要求。
基于Proxy + Shadow Dom 实现。实现了较好的隔离效果，理论上能同时支持多个应用同时运行。

- 亮点：
1. 无生命周期：应用代码无生命周期，不需要设置挂载、卸载操作，让hot-chocolate帮你完成。
2. 打包配置无修改：可以直接用create-react-app、vue-cli生成项目，也可以自定义webpack配置。也支持非webpack项目，只要你生产的html和js、css 是正确的、可访问的。当然使用umi也可以，且无需额外修改配置，我们现在不少也是用umi的开发的后台。
3. 支持动态引入js、css，你的webpack可以按需拆分模块了，动态创建的script、style、link标签都将被正确的使用，同时支持使用icon-font等css字体图标。
4. 推荐使用`htmlRemote: 'http://abc.com/index.html`的方式，直接设置html的地址，剩下的交给hot-chocolate。
5. 易于扩展的插件体系
hot-chocolate 提供了一套插件体系。其开发目的是为了使用者可以对沙箱中运行环境进行自定义。使用插件可以实现对沙箱内的进行ajax、localStorage等行为，进行监控、代理、重写等操作。也可以基于插件完成跨沙箱间通信。
开发自定义插件可以看[这里](https://github.com/NeteaseLofter/hot-chocolate/tree/master/packages/hot-chocolate#%E5%BC%80%E5%8F%91%E8%87%AA%E5%B7%B1%E7%9A%84%E6%8F%92%E4%BB%B6)。目前已提供了沙箱从启动到运行到销毁，各个阶段多个事件，基本可以满足大部分自定义需求。如果有想法可以提issue，我们进行补充。

- 截图：
![demo](https://user-images.githubusercontent.com/5868138/173765208-40fb4c48-1d4c-4c6d-9b06-84683ec970ae.gif)
更多demo: https://github.com/NeteaseLofter/hot-chocolate/tree/master/examples

- 后续更新计划：
  - 可能会实现更兼容性的版本，但同时会牺牲一些隔离效果。如果使用兼容性版本，这会需要使用者对项目有更好了解和规范。
  - 更多插件的支持，比如单页面history的适配，其他如果有想法可以提issue，我们进行补充。
  - 沙箱的上层封装 -- 完整的微前端。hot-chocolate专注于沙箱。微前端的功能，包括路由切换、应用资源自动发放，我们考虑在上层提供全新的包去完整。这样hot-chocolate可以有更好的使用空间。

- 补充说明
  hot-chocolate 在我们自己的后台项目中正在使用中。作为微前端设计中的一部分，它的沙箱隔离效果和可扩展的插件，让它在不同的项目中都有不错的表现。
  同时作者感觉，微前端是个比较复杂的设计，我们使用需要对当前项目有充分的评估。如果你需要整合技术栈，可以使用。如果没有明确的需求，则可以了解但放缓。

**Comment by 521xueweihan** [comment]
@huey-LS 非常感谢您推荐项目。后续更新不积极

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
