### ISSUE TITLE
【开源自荐】notification-gateway-lite 一个零成本可自建的多渠道通知推送网关

### ISSUE THREAD

**Issue by LeslieLeung** [521xueweihan/HelloGitHub#2239]
## 推荐项目

- 项目地址：https://github.com/LeslieLeung/notification-gateway-lite

- 类别：Python

- 项目标题：轻量的通知网关

- 项目描述：notification-gateway-lite 是一个非常轻量的通知网关，可以聚合各种推送渠道，使用 Serverless 部署，几乎零成本运行。是著名推送项目 Server酱 的开源可自建替代，能让初学者学习Serverless有关知识。

- 亮点：
  - 等同于免费、开源、可自建的 [新版Server酱](https://sct.ftqq.com/)，没有任何限制，痛快推送
  - 支持各种常见的推送渠道，如Bark、企业微信等
  - 支持部署成腾讯云/阿里云 Serverless，几乎零成本运行
  - 解决因为群晖DSM奇怪的webhook设置方式而无法接入一些推送渠道的问题

- 后续更新计划：
  - 支持更多的通知渠道
  - 支持更多 Serverless 部署方法

**Comment by 521xueweihan** [comment]
@LeslieLeung 
新版 Server 酱支持多种消息推送：
- 企业微信应用消息：无需安装企业微信客户端，可在微信中直接收到消息，内容显全文
- 手机客户端：Andorid有官方测试版，iOS 可用 Bark 通道
- 群机器人：企业微信、钉钉、飞书群
- 微信服务号和测试号：依赖模板消息接口（微信可能会在某天下线该接口，建议配置多个通道随时切换）
- 邮件和短信原生不支持，但可以通过自定义通道调用其他云服务来实现

而且有手机端之类的，可以说是推送的解决方案。贵项目相较于它通知渠道较少，但部分方式简单切免费，我个人非常认可。

最后，建议如果可以的话，可以一同构建 server 酱，开源不易相互理解，谢谢。
