### ISSUE TITLE
开源推荐 | checkchan-dist用来监测网页数据变动，然后通过微信通知

### ISSUE THREAD

**Issue by itgoyo** [521xueweihan/HelloGitHub#2241]
## 推荐项目

- 项目地址：https://github.com/easychen/checkchan-dist

- 类别：JS

- 项目标题：[checkchan-dist](https://github.com/easychen/checkchan-dist)

- 项目描述：Check 酱是一个通用网页内容监控工具，可以监测网页内容变化，并发送异动到微信

- 亮点：

Check 酱是方糖气球出品的网页内容监测工具，它包含一个 Edge/Chrome 浏览器插件和可以自行架设的云端。

基于浏览器插件，它通过可视化选择器 理论上可以监控网页上的任意内容（文本）、除了浏览器通知，还可以配合 [Server 酱](https://sct.ftqq.com/)将异动推送到微信或手机。

用来监听服务器变化，或者是追番剧，或者是小说非常有用

- 示例代码：（可选）

- 截图：（可选）gif/png/jpg
![image](https://user-images.githubusercontent.com/23348551/172316102-9ce07fa4-8969-46d8-acf8-7c9205cc9725.png)

- 后续更新计划：

## 提高项目收录的方法（提交时请删除下方内容）

1. **请勿使用复制的内容**作为项目描述提交！

2. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目**是否被推荐过**。

3. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

最后，感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 75 期](https://hellogithub.com/periodical/volume/75/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
