### ISSUE TITLE
【开源自荐】在原生终端实现类似 rz / sz 的上传和下载文件，支持拖文件上传，支持多种平台。

### ISSUE THREAD

**Issue by lonnywong** [521xueweihan/HelloGitHub#2244]
## 推荐项目

- 项目地址：https://github.com/trzsz/trzsz-go

- 类别：Go

- 项目标题：在原生终端实现类似 rz / sz 的上传和下载文件，支持拖文件上传，支持多种平台。

- 项目描述：
  1、在本地终端运行 `trzsz ssh x.x.x.x` 登录服务器。
  2、在服务器上运行 `trz` 即可选择文件上传到服务器。
  3、在服务器上运行 `tsz file_name` 即可以从服务器下载指定文件到本地。
  4、在本地终端运行 `trzsz -d ssh x.x.x.x` 登录服务器，那么只要拖文件到终端，就会自动上传到远程服务器。
  5、关于 `trz` 和 `tsz` 的更多用法，可以参考 Python 版的网站：https://trzsz.github.io/

- 亮点：
  1、支持多种平台，包括 macOS、Linux 和 Windows 等。
  2、支持各平台的原生终端，例如 cmd、PowerShell、Windows Terminal 以及 macOS 和 Linux 的原生终端等。
  3、支持拖文件上传，在某些场景下非常的方便。
  4、进度条很帅，还有传输速度和剩余时间等。
  5、支持 tmux ，解决了 rz / sz 之类工具的硬伤。

- 截图：
  * Windows 的 cmd 通过 `trzsz ssh` 登录到 Linux，选文件上传和下载：
  ![windows trzsz ssh](https://trzsz.github.io/images/cmd_trzsz.gif)

  * Ubuntu 的原生终端通过 `trzsz ssh` 登录到 Linux，选文件上传和下载：
  ![ubuntu trzsz ssh](https://trzsz.github.io/images/ubuntu_trzsz.gif)

  * macOS 的原生终端通过 `trzsz -d ssh` 登录到 Linux，拖文件上传：
  ![drag files ssh](https://trzsz.github.io/images/drag_files.gif)

- 后续更新计划：
  1、正在实现文件夹的上传和下载。
  2、尽可能发布到各大软件分发平台，方便用户安装。

**Comment by 521xueweihan** [comment]
已推荐过类似功能的项目。

**Comment by lonnywong** [comment]
之前那个是 Python 写的，在客户端只支持 iTerm2 的。

现在这个是 Go 写的，支持 windows 、mac 和 linux 的原生终端，用法也不同，支持拖文件上传。

**Comment by 521xueweihan** [comment]
@lonnywong 好的，我再看下。

**Comment by lonnywong** [comment]
@521xueweihan 感谢 🤝

**Comment by 521xueweihan** [comment]
@lonnywong 该项目不能收录到月刊中。

因为同类型的项目，不收录不同语言的版本。

已收录：https://github.com/trzsz/trzsz

而且两个项目属于同一个组织，同一位开发者。
