### ISSUE TITLE
【开源自荐】轻量级Java日志框架

### ISSUE THREAD

**Issue by OptiJava** [521xueweihan/HelloGitHub#2249]
## 推荐项目

- 项目地址：https://github.com/OptiJava/Optilog-Client

- 类别：Java

- 项目标题：轻量级Java日志框架

- 项目描述：相比Slf4j和Log4j更加方便、更适合初学者的轻量级Java日志框架

- 亮点：初学者易上手，支持多种配置文件等（详见[Optilog的优势](https://github.com/OptiJava/Optilog-Client#optilog%E7%9A%84%E4%BC%98%E5%8A%BF)）

- 截图：
![170864247-7da18dd5-f5b9-4e5c-aee7-4174d29a8969](https://user-images.githubusercontent.com/106148777/173598488-0dd687db-bc8f-4304-9b2f-05a769cbd4ac.png)

- 后续更新计划：
-   1.加入远程日志功能
-   2.支持多个文件名设置
-   3.支持运行期修改输出路径设置

**Comment by 521xueweihan** [comment]
@OptiJava 非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
