### ISSUE TITLE
JsPlayer

### ISSUE THREAD

**Issue by shuaijia** [521xueweihan/HelloGitHub#225]
## 项目推荐
- 项目名称：
### JsPlayer
- 项目地址：
[https://github.com/shuaijia/JsPlayer](https://github.com/shuaijia/JsPlayer)
- 项目语言：
java、Android
- 项目描述：
使用Android原生提供的MediaPlayer+SurfaceView实现视频播放器与弹幕。
- 推荐理由：
原生封装，不用考虑兼容性问题；
使用简单，容易拓展。
- 示例代码：
### 布局中引用
```
<com.jia.jsplayer.video.JsPlayer
    android:id="@+id/player"
    android:layout_width="match_parent"
    android:layout_height="260dp" />
```
### 设置视频信息
```
player.setPath(new VideoInfo("艺术人生", path));
```
其中VideoInfo集成IVideoInfo，需重写getVideoTitle和getVideoPath方法，返回视频标题和路径，当然，**路径可以是本地路径，也可以是在线视频地址**。
### 实现播放处理回调
```
player.setOnVideoControlListener(new OnVideoControlListener() {
    @Override
    public void onStartPlay() {
        player.startPlay();
    }

    @Override
    public void onBack() {

    }

    @Override
    public void onFullScreen() {
        DisplayUtils.toggleScreenOrientation(MainActivity.this);
    }

    @Override
    public void onRetry(int errorStatus) {

    }
});
```
- 截图：

![image](https://raw.githubusercontent.com/shuaijia/JsPlayer/master/img/aa.png)
![image](https://raw.githubusercontent.com/shuaijia/JsPlayer/master/img/bb.png)
![image](https://raw.githubusercontent.com/shuaijia/JsPlayer/master/img/cc.png)
![image](https://raw.githubusercontent.com/shuaijia/JsPlayer/master/img/dd.png)
![image](https://raw.githubusercontent.com/shuaijia/JsPlayer/master/img/ee.png)
![image](https://raw.githubusercontent.com/shuaijia/JsPlayer/master/img/ff.png)

**Comment by 521xueweihan** [comment]
@shuaijia 请问该项目还在持续更新吗？
