### ISSUE TITLE
妙言 - 轻灵的 Markdown 笔记本伴你写出妙言 

### ISSUE THREAD

**Issue by tw93** [521xueweihan/HelloGitHub#2250]
## 推荐项目

- 项目地址：https://github.com/tw93/MiaoYan

- 类别：Swift

- 项目标题：妙言

- 项目描述：轻灵的 Markdown 笔记本伴你写出妙言 

- 亮点：一个非常简洁好看的[开源的]( https://github.com/tw93/MiaoYan) Mac 端的 Markdown 编辑器。没有任何多余的功能，纯本地使用、安全、语法高亮、黑暗模式、源文件保存。使用 Swift5 原生开发，相比 Web 套壳方式性能体验好。

- 截图：
![image](https://user-images.githubusercontent.com/8736212/173721107-4e254576-6eef-4ca8-88b7-74a15e7273e2.png)

**Comment by 521xueweihan** [comment]
@tw93 您推荐的项目，**已成功发布**在 [HelloGitHub 第 76 期](https://mp.weixin.qq.com/s/L3GP5DcTJb-3Z6kbB-OK7w)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
