### ISSUE TITLE
【自荐项目】go-ldap-admin ：基于Go+Vue实现的openLDAP后台管理项目

### ISSUE THREAD

**Issue by eryajf** [521xueweihan/HelloGitHub#2251]
## 推荐项目

- 项目地址：https://github.com/eryajf/go-ldap-admin

- 类别：Go

- 项目标题：🌉 基于Go+Vue实现的openLDAP后台管理项目

- 项目描述：go-ldap-admin旨在为openLDAP服务端提供一个简单易用，清晰美观的现代化管理后台。

- 亮点：现代化openLDAP管理后台，设计简洁，交互简单，助力运维人员快速简单地应用并管理openLDAP。支持钉钉，企业微信，飞书的组织架构，以及员工信息自动同步到平台，一座打通IM与常见支持ldap认证的应用的桥梁。

- 截图：

![](https://github.com/eryajf/tu/raw/main/img/image_20220607_174313.png)

- 后续更新计划：当前已支持钉钉架构与员工同步，下一步支持企业微信与飞书

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by eryajf** [comment]
@521xueweihan 是否方便了解下，是哪块儿的条款不符合吗？

**Comment by 521xueweihan** [comment]
@521xueweihan 已推荐过类似的 go-admin 项目：

https://github.com/flipped-aurora/gin-vue-admin

**Comment by eryajf** [comment]
项目名字叫go-ldap-admin，事实上侧重词在于ldap，而非 go 或者 admin，因此根本上来说，这个项目与gin-vue-admin并不是一个性质的项目。

这是一个旨在简化 openLDAP 管理的一个后台项目。
