### ISSUE TITLE
【自荐项目】基于 Rust 实现的 Node.js-addon nanoid —— 相比原版 nanoid.js 性能提升 40+%

### ISSUE THREAD

**Issue by meloalright** [521xueweihan/HelloGitHub#2253]
## 推荐项目

- 项目地址：[https://github.com/rustq/napi-nanoid](https://github.com/rustq/napi-nanoid)

- 类别：Rust

- 项目标题：基于 Rust 实现的 Node.js-addon nanoid

- 项目描述：基于 Rust 实现的 Node.js-addon nanoid —— 相比原版 nanoid.js 性能提升 40+%

- 亮点：
  - 包括 secure + non-secure api 相比原版 nanoid.js 性能均提升 40+% [(runs: 6842925183)](https://github.com/rustq/napi-nanoid/runs/6842925183)

- 示例代码：

```js
const { nanoid } = require('napi-nanoid');

nanoid() // => AeogKAGjUMX6mqB4sMzWe
```

- 后续更新计划：

  - 完善 custom size
  
  - 完善 custom alphabets

**Comment by 521xueweihan** [comment]
由于月刊篇幅有限，同一种库的不同实现仅收录一种哈
