### ISSUE TITLE
【自荐项目】超简单的文件数据库

### ISSUE THREAD

**Issue by LiuYuguang** [521xueweihan/HelloGitHub#2254]
## 推荐项目

- 项目地址：https://github.com/LiuYuguang/supersimplefiledatabase

- 类别：C

- 项目标题：超简单的文件数据库

- 项目描述：基于B-tree实现的Key–value文件数据库，接口简单易调用，核心代码简明易读，适合初学者学习。

- 亮点：
  - 接口简单，一共六个接口，创建数据库、打开数据库、关闭数据库、插入操作、查询操作、删除操作。  
  - 创建文件数据库时，可指定key为string、bytes、int32、int64之一。  
  - 只有一个数据库文件，并且实现了文件块的分配与回收，删除操作将文件块标记为空闲，插入操作优先分配空闲文件块。  

- 示例代码：（可选）
```c
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include "db.h"

#define COUNT 100000L
#define PATH "./db_test"

int main(){
    db_t* db;
    int i,rc;
    char value[128];

    // 创建数据库
    unlink(PATH);
    db_create(PATH,DB_INT32KEY,sizeof(int));

    // 打开数据库
    db_open(&db,PATH);

    // 插入操作
    for(i=0;i<COUNT;i++){
        sprintf(value,"%d",i);
        db_insert(db,&i,value,strlen(value));
    }

    //查询操作
    i = 0;
    bzero(value,sizeof(value));
    rc = db_search(db,&i,value,sizeof(value));
    printf("search key: %d value: %.*s\n",i,rc,value);

    // 关闭数据库
    db_close(db);

    return 0;
}
```

- 截图：（可选）gif/png/jpg

- 后续更新计划：
  - 不再添加新功能，完善代码备注。
  - 在README中，添加个人思考。

**Comment by 521xueweihan** [comment]
@LiuYuguang 太酷了，感觉 OneFile 更适合贵项目，可以整理下代码实现“一个文件” 的效果，进一步提高运行和下载的简易程度。

OneFile 参与方式：https://github.com/521xueweihan/OneFile/blob/main/doc/join.md
