### ISSUE TITLE
【自荐项目】RepoChart 可视化展示Github项目

### ISSUE THREAD

**Issue by Uahh** [521xueweihan/HelloGitHub#2256]
## RepoChart

- 项目地址：https://github.com/Uahh/RepoChart  

- 类别：Python + JavaScript

- 项目标题：RepoChart  
- 项目描述：
  可视化展示Github项目，快速了解一个储存库的历史，近期发展情况，储存库中的重要文件，获得Star的历史等信息。
  已将本项目发布到网页：https://uahh.site/repochart
  (因为是国内的服务器，clone速度可能会比较慢，如果是大型项目建议clone项目自己生成图表。)
  项目前端使用Vue + Echarts，后端使用Python Flask
  
- 截图：
    
  每个圆圈代表一个文件，圆圈越大，代表文件在repo中的重要性越高。  
  
  <img src="https://github.com/Uahh/Repochart/blob/main/data/circle_chart_line.png?raw=true" width="75%" height="75%">  
    
  展示中repo文件大小。  
  
  <img src="https://github.com/Uahh/Repochart/blob/main/data/square_chart.png?raw=true" width="75%" height="75%">  
    
  展示repo所使用语言占比。  
    
  <img src="https://github.com/Uahh/Repochart/blob/main/data/ring_chart.png?raw=true" width="75%" height="75%">  
    
  展示repo的commit每种文件的变化历史，比如可以看出，在第5次commit里，项目中js代码从html文件中独立出来了，第12次commit中，将js代码独立成vue文件。  
  
  <img src="https://github.com/Uahh/Repochart/blob/main/data/commit_line_chart.png?raw=true" width="75%" height="75%">  
    
  展示代码行数。  
  
  <img src="https://github.com/Uahh/Repochart/blob/main/data/lines_of_code_chart.png?raw=true" width="75%" height="75%">  

- 后续更新计划：
  增加项目中开发者相关图标，开发占比，活跃时间，次数等图表。

**Comment by 521xueweihan** [comment]
@Uahh 已推荐过类似的项目，不再重复推荐同类项目。
