### ISSUE TITLE
【开源自荐】fetch-github-hosts：一款专向 github hosts 同步工具，支持多平台多模式

### ISSUE THREAD

**Issue by Licoy** [521xueweihan/HelloGitHub#2259]
## 推荐项目

- 项目地址：https://github.com/Licoy/fetch-github-hosts

- 类别：Go

- 项目标题：同步github的hosts工具，支持多平台的图形化和命令行，内置客户端和服务端两种模式~

- 项目描述：可视化同步github的hosts工具，同时也支持命令行的模式，解决因网络DNS污染导致或其他原因导致的Github访问不稳定，傻瓜式操作，下载下来只需要点击两步即可同步github hosts，已经内置github520和fetch-github-hosts提供的hosts源。

- 亮点：可视化，对小白更友好，方便，多平台支持。

- 截图：

![](https://github.com/Licoy/fetch-github-hosts/raw/main/docs/client.png)
![](https://github.com/Licoy/fetch-github-hosts/raw/main/docs/client-select.png)
![](https://github.com/Licoy/fetch-github-hosts/raw/main/docs/client-custom.png)
![](https://github.com/Licoy/fetch-github-hosts/raw/main/docs/server.png)

- 后续更新计划：引入hosts清除模式及其他网友反馈的建议。

**Comment by 521xueweihan** [comment]
@Licoy 非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
