### ISSUE TITLE
Avalon：🤖 A scalable multi-function group robot for QQ and Discord. 多功能、可扩展的群机器人，支持QQ和Discord。

### ISSUE THREAD

**Issue by Ray-Eldath** [521xueweihan/HelloGitHub#226]
## 项目推荐
- 项目名称：Avalon

- 项目地址：[Ray-Eldath/Avalon](https://github.com/Ray-Eldath/Avalon)

- 项目语言： Kotlin：67.7%； Java：31.8%

- 项目描述：🤖 A scalable multi-function group robot for QQ and Discord. 多功能、可扩展的群机器人，支持QQ和Discord。

- 示例代码：
![img](https://raw.githubusercontent.com/Ray-Eldath/Avalon/master/img/console.png)

- 截图：
![ae463418-15b3-443e-b807-a518a22464f8](https://user-images.githubusercontent.com/7938763/38162001-b518911c-350b-11e8-9613-d02d1353909d.jpg)

**Comment by 521xueweihan** [comment]
@Ray-Eldath 以后请不要用截图敷衍了事

**Comment by 521xueweihan** [comment]
@Ray-Eldath 欢迎修改后通知我重新打开
