### ISSUE TITLE
【开源自荐】Stroke：一款基于 Rust 实现的 Mac 命令行一笔画绘线工具

### ISSUE THREAD

**Issue by meloalright** [521xueweihan/HelloGitHub#2261]
## 推荐项目

- 项目地址：[https://github.com/meloalright/stroke](https://github.com/meloalright/stroke)

- 类别：Rust

- 项目标题：Stroke: 一款基于 Rust 实现的 Mac 命令行一笔画绘线工具

- 项目描述：
一款基于 Rust 实现的 Mac 命令行一笔画绘线工具
项目基于 Skia Backend
支持自定义绘制路径 + 自定义连线颜色

- 亮点：
  - 可一行代码生成自由绘线图形

- 示例代码：

```shell
$ stroke 0 40 120 40 20 120 60 0 100 120 0 40 60 0 120 40 100 120 20 120 0 40 --view
```

- 后续更新计划：

  - 增加 curveTo 能力

  - 增加 fill 能力

**Comment by 521xueweihan** [comment]
@meloalright 非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
