### ISSUE TITLE
项目推荐 | Whoogle Search

### ISSUE THREAD

**Issue by RiverOnVenus** [521xueweihan/HelloGitHub#2262]
## 推荐项目

- 项目地址：[https://github.com/benbusby/whoogle-search](https://github.com/benbusby/whoogle-search)

- 类别：Python

- 项目标题：Whoogle Search 是一个开源的、自我托管的、无广告的、尊重隐私的元搜索引擎。

- 项目描述：这是一个元搜索引擎，获取Google搜索结果，但过滤了其中的广告，没有cookies，不追踪ip等，并考虑到了更多的隐私问题，适用于注重隐私的用户。

- 亮点：注重隐私，可以用docker快速部署，作为桌面和移动端的主要搜索引擎替代品，实施起来既快速又简单。

- 截图：
桌面端
![image](https://user-images.githubusercontent.com/79885139/176082627-498264d0-03b8-466a-8339-229da16d2aa6.png)
移动端
![image](https://user-images.githubusercontent.com/79885139/176083299-ca9632f5-e846-4224-84fd-0a8196ac41db.png)

- 后续更新计划：

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 77 期](https://hellogithub.com/periodical/volume/77/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
