### ISSUE TITLE
【开源自荐】ptg: 用 Go 写的 GUI gRPC 客户端。

### ISSUE THREAD

**Issue by crossoverJie** [521xueweihan/HelloGitHub#2263]
## 推荐项目

- 项目地址：https://github.com/crossoverJie/ptg

- 类别：Go

- 项目标题：用 Go 写的 GUI `gRPC` 客户端，主要是为了解决 BloomRPC 对 int64 精度溢出的问题。

- 项目描述：类似于 `postman`，可视化调用 `gRPC` 接口，同时也支持对 `gRPC/HTTP` 接口进行压测。

- 亮点：支持 `gRPC` 的客户端工具不多，当需要 int64 时这能解决你的痛点，同时还配套了压测功能。

- 截图：

![image](https://github.com/crossoverJie/ptg/raw/main/pic/ptg.gif)
![](https://github.com/crossoverJie/ptg/raw/main/pic/search.gif)
![](https://github.com/crossoverJie/ptg/raw/main/pic/show.gif)

**Comment by 521xueweihan** [comment]
@crossoverJie 您推荐的项目，**已成功发布**在 [HelloGitHub 第 76 期](https://mp.weixin.qq.com/s/L3GP5DcTJb-3Z6kbB-OK7w)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
