### ISSUE TITLE
【开源自荐】从零实现的软件渲染器 foolrenderer

### ISSUE THREAD

**Issue by cadenji** [521xueweihan/HelloGitHub#2265]
## 推荐项目

- 项目地址：https://github.com/cadenji/foolrenderer

- 类别：C

- 项目标题：一个不使用图形API，从零实现的轻量软件渲染器，用于学习GPU的基本工作原理。

- 项目描述：
foolrenderer是一个从零实现的，纯C语言的，软件渲染器项目。用于演示封装在GPU内部的光栅化算法，实现了一套类似OpenGL的基本图形功能。在这个基础上还实现了一些应用于游戏工业的实时渲染技术，如阴影、切线空间法线映射、基于物理的材质系统等。
foolrenderer主要作为游戏开发者和图形学爱好者用于学习基础渲染知识和着色器原理的演示项目。foolrenderer的着色器用C编写，运行在CPU所以便于调试，可以作为实验性shaders的测试工具。

- 亮点：
  - **精简**，只有几千行代码，没有复杂依赖。
  - **可读**，代码四分之一以上是注释，在各算法处有参考文献链接，数学计算有公式推导过程的说明。
  - **可编程渲染管线**，实现了可编程渲染管线，可以用C编写类似glsl风格的着色器代码。
  - foolrenderer逐步添加功能，从实现数学库开始，到光栅化一个三角形、绘制3D模型，便于初学者的渐进学习。相比同类面向初学者的软渲染器项目，foolrenderer还引入阴影，PBR等高级概念。项目readme页面包含从入门到进阶的自学材料清单。

- 截图：
![cut_fish-animation](https://user-images.githubusercontent.com/10301447/176867561-0f08d1dd-3e45-4835-a4c4-bcca23987ec5.gif)
![foolrenderer_features](https://user-images.githubusercontent.com/10301447/176867515-4a21f5d8-5aca-4e6d-ba46-ed8bc1031f64.jpg)

- 后续更新计划：
  - 屏幕外多边形的齐次裁剪
  - 立方体贴图采样
  - HDR支持
  - Image based lighting (IBL)
  - 微表面模型的能量守恒

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 77 期](https://hellogithub.com/periodical/volume/77/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
