### ISSUE TITLE
【开源自荐】Windows 系统自动安装应答文件生成工具

### ISSUE THREAD

**Issue by dsx42** [521xueweihan/HelloGitHub#2267]
## 推荐项目

- 项目地址：https://github.com/dsx42/UnattendTool

- 类别：其它

- 项目标题：生成 Windows 系统自动安装应答文件 Unattend.xml

- 项目描述：

    * 生成 Windows 系统自动安装应答文件 Unattend.xml
    * 支持 Ventoy
    * 只支持 Windows 10 或 Windows 11

- 亮点：

    * 无需安装 ADK
    * 可个性化定制应答文件，中文交互，定制过程易于理解
    * 可以和 Ventoy 集成，简化 Windows 系统安装
    * 纯 PowerShell 实现

- 后续更新计划：

    * 支持更多系统安装语言
    * 紧跟 Windows 版本变化情况，支持最新的 Windows 版本

**Comment by 521xueweihan** [comment]
@dsx42  非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
