### ISSUE TITLE
【开源自荐】Solon ，轻量级应用开发框架

### ISSUE THREAD

**Issue by noear** [521xueweihan/HelloGitHub#2272]
## 推荐项目

- 项目地址：https://github.com/noear/solon

- 类别：Java

- 项目标题：一个生态型的轻量级应用开发框架。更快、更小、更少、更自由！

- 项目描述：
支持jdk8+；主框架0.1mb；组合不同的插件应对不同需求；方便定制；快速开发。

1. 克制、简洁、开放、生态。
2. Http、WebSocket、Socket 三种信号统一的开发体验（俗称：三源合一）。
3. 支持注解与手动两种模式，按需自由操控。
4. Not Servlet，可以适配任何基础通讯框架（所以：最小0.2m运行rpc架构）。
5. 自建 IOC & AOP容器，支持 Web、Data、Job、Remoting、Cloud 等任何开发场景。
6. 集合 Handler + Context 和 Listener + Message 两种架构模式；强调插件式扩展；适应不同的应用场景。
7. 插件可扩展可切换：启动插件，扩展插件，序列化插件，数据插件，会话状态插件，视图插件(可共存) 等...。
8. 支持 GraalVm Native 打包。

- 亮点：启动快 5 ～ 10 倍；qps 高 2～ 3 倍；运行时内存节省 1/3 ~ 1/2；打包可以缩到 1/2 ~ 1/10（相对于 Spring 生态）

- 示例代码：

```java
@Controller
public class App {
    public static void main(String[] args) {
        Solon.start(App.class, args, app -> {
            //手写模式
            app.get("/hello1", ctx -> ctx.output("Hello world!"));
        });
    }

    //注解模式
    @Get
    @Socket
    @Mapping("/hello2")
    public String hello2(@Param(defaultValue = "world") String name) {
        return String.format("Hello %s!", name);
    }
}
```

- 后续更新计划：不断完善生态体系

**Comment by 521xueweihan** [comment]
@noear 我建议可以多用“微”这个字眼，突出“更小、更自由”的特点，类比 Python 的 Flask 可以有效地提高传播度。月刊描述如下：

一款微型 Java Web 框架。更小、更自由的 Java Web 框架，类似 Python Flask 的微型框架，提倡自由地按需组合插件。

**Comment by noear** [comment]
@521xueweihan 从理解的角度：Solon 是一个应用开发框架，类似 Spring 这种生态型的。。。并不是一个 Web 开发框架

**Comment by 521xueweihan** [comment]
@noear 我理解有误，本期暂停收录该项目，下期重新审核。

**Comment by noear** [comment]
好的，谢谢

发自我的iPhone

在 2022年7月27日，18:20，削微寒 ***@***.***> 写道：

﻿

@noear<https://github.com/noear> 我理解有误，本期暂停收录该项目，下期重新审核。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 x 期](https://hellogithub.com/periodical/volume/78/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

**Comment by noear** [comment]
谢谢

**Comment by noear** [comment]
有没有机会，添加到：编程挑战 那里啊？

**Comment by noear** [comment]
再来鉴到一下：）
