### ISSUE TITLE
【开源自荐】Paper2GUI 一款面向普通人的 AI 桌面 APP 工具箱，免安装即开即用。

### ISSUE THREAD

**Issue by Baiyuetribe** [521xueweihan/HelloGitHub#2274]
## 推荐项目

- 项目地址：https://github.com/Baiyuetribe/paper2gui

- 类别：机器学习

- 项目标题：一款面向普通人的 AI 桌面APP工具箱

- 项目描述：Paper2GUI: 一款面向普通人的AI桌面APP工具箱，免安装即开即用，已支持20+AI模型，内容涵盖语音合成、视频补帧、视频超分、目标检测、图片风格化、OCR识别等领域。

- 亮点：支持Windows、Linux、Mac，操作简单，免安装即开即用，基于`ncnn-vulkan`，支持任意常见显卡。让普通人也能无门槛使用前沿人工智能技术。

- 示例代码：（可选）

- 截图：（可选）gif/png/jpg
![](https://cdn.jsdelivr.net/gh/Baiyuetribe/paper2gui@main/docs/images/huoshan_tts.png)
![](https://cdn.jsdelivr.net/gh/Baiyuetribe/paper2gui@main/docs/images/microsoft_tts.gif)
![](https://cdn.jsdelivr.net/gh/Baiyuetribe/paper2gui@main/docs/images/modnet_gui.png)
![](https://github.com/Baiyuetribe/paper2gui/raw/main/docs/images/realESRGAN_RAM.png)

- 后续更新计划：

1.  基于ncnn-wasm开发在线体验网站，让AI使用更加便捷
2.  整合优质AI为一个应用，促进实际工业，诞生真正意义上有创造力的工具

**Comment by 521xueweihan** [comment]
@Baiyuetribe 您推荐的项目，**已成功发布**在 [HelloGitHub 第 76 期](https://mp.weixin.qq.com/s/L3GP5DcTJb-3Z6kbB-OK7w)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
