### ISSUE TITLE
【开源自荐】Forest，高层的、极简的声明式HTTP客户端框架

### ISSUE THREAD

**Issue by mySingleLive** [521xueweihan/HelloGitHub#2275]
## 推荐项目

- 项目地址：https://github.com/dromara/forest

- 类别：Java

- 项目标题：一个高层的、极简的声明式HTTP客户端框架

- 项目描述：
  Forest 是一个开源的 Java HTTP 客户端框架，它能够将 HTTP 的所有请求信息（包括 URL、Header 以及 Body 等信息）绑定到您自定义的 Interface 方法上，能够通过调用本地接口方法的方式发送 HTTP 请求。

- 亮点：
   采用声明式的开发方式，10分钟即可完成请求的定义、发送、接收、解析、错误处理、日志打印等过程，此外还有直观的API和详尽的中文文档
   
- 示例代码：

第一步. 创建接口
```java
public interface AmapClient {
    /**
     * 聪明的你一定看出来了@Get注解代表该方法专做GET请求
     * 在url中的{0}代表引用第一个参数，{1}引用第二个参数
     */
    @Get("http://ditu.amap.com/service/regeo?longitude={0}&latitude={1}")
    Map getLocation(String longitude, String latitude);
}
```

第二步. 调用接口

```java
// 注入接口实例
@Autowired
private AmapClient amapClient;
...
// 调用接口
Map result = amapClient.getLocation("121.475078", "31.223577");
System.out.println(result);
```

- 后续更新计划：

1. 支持请求模型的开发模式（让Java的HTTP客户端开发更便捷）
2. 支持HTTP 2.0

**Comment by 521xueweihan** [comment]
@mySingleLive 您推荐的项目，**已成功发布**在 [HelloGitHub 第 76 期](https://mp.weixin.qq.com/s/L3GP5DcTJb-3Z6kbB-OK7w)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
