### ISSUE TITLE
【开源自荐】LiteFlow，灵动且强大的编排式规则引擎

### ISSUE THREAD

**Issue by bryan31** [521xueweihan/HelloGitHub#2276]
## 推荐项目

- 项目地址：https://github.com/dromara/liteflow

- 类别：Java

- 项目标题：轻量，快速，稳定可编排的组件式规则引擎

- 项目描述：

LiteFlow是一个轻量且强大的规则引擎，独有的DSL规则语法能让你的系统变的更加解耦，更加灵活。改变规则即改变业务，平滑热刷新，让你的业务更改无需重启。是一个能让你的系统变的更加灵活，复用程度高的神器。

- 亮点：

规则语法简单，不到10个的语法关键字，能完成超复杂的编排场景
平滑热刷新，让你无需重启应用，即可完成刷新规则
强大的脚本支持能力，支持qlExpress和groovy两种脚本语言，可以和java混合编排
声明式组件，侵入性更加低
上下文对象体系，传递参数更加优雅
文档非常友好，一步步引导式的文档架构。官网阅读体验已经被多位业内人士称赞

- 示例代码：

规则写法：

THEN表示串行，WHEN表示并行，SWITCH表示条件选择
```xml
<chain name="chain1">
    THEN(
        a,
        WHEN(
            b,
            SWITCH(c).to(d,e)
        ),
        f
    )
</chain>
```

执行代码
```java
@Component
public class YourClass{
    
    @Resource
    private FlowExecutor flowExecutor;
    
    public void testConfig(){
        LiteflowResponse response = flowExecutor.execute2Resp("chain1", "arg");
    }
}
```

- 截图：
<img width="1557" alt="image" src="https://user-images.githubusercontent.com/924838/177946731-25f6d1b9-abd0-4f9f-bae8-18674b668433.png">

- 后续更新计划：
1.和bpm协议接轨，可以和liteflow的规则进行互转
2.推出IDEA语法插件，语法高亮，格式化，语法提示，语法预检查。
3.推出UI编排功能，组件监控可视化等生态

**Comment by 521xueweihan** [comment]
@bryan31 您推荐的项目，**已成功发布**在 [HelloGitHub 第 76 期](https://mp.weixin.qq.com/s/L3GP5DcTJb-3Z6kbB-OK7w)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
