### ISSUE TITLE
【开源自荐】Typing Learner 可以用 MKV 视频生成词库（单词本），让每个单词都有具体的语境。

### ISSUE THREAD

**Issue by tangshimin** [521xueweihan/HelloGitHub#2286]
## 开源自荐

- 项目地址：https://github.com/tangshimin/typing-learner

- 类别：Kotlin

- 项目标题：可以用 MKV 视频生成词库（单词本），让每个单词都有具体的语境。然后通过语境记忆单词，句子，字幕。 

- 项目描述：
    1. [可以用MKV 视频生成词库(单词本)](https://github.com/tangshimin/typing-learner/wiki/%E4%BB%8E-MKV-%E8%A7%86%E9%A2%91%E7%94%9F%E6%88%90%E8%AF%8D%E5%BA%93)，让每个单词都有具体的语境。
    2. 记忆单词，记忆单词的时候，会自动播放单词的读音，然后用键盘打字练习拼写，每个单词都可以输入多次，直到记住为止。从 MKV 生成的词库(单词本)，可以播放单词对应的视频片段。每个单元有 20 个单词，记完一个单元还有听写测试，检查记忆效果。
    
        https://user-images.githubusercontent.com/16540656/163662386-e82dc534-7a5a-4566-8449-fc71db51f960.mp4

    3. 抄写字幕，可以抄写你感兴趣的电影、电视剧、纪录片、TED演讲、歌词。可以抄写多种语言的字幕。
    4. 抄写字幕界面也可用来练习听力，可用重复的播放一句字幕，直到听懂为止。切换到下一条字幕用 Enter 或 ↓键。

       https://user-images.githubusercontent.com/16540656/174944474-e5947df9-c8ed-4546-9c67-057fe52c2d51.mp4

- 亮点：
    1. 通过语境记忆单词
    2. 记忆单词的时候可以预览对应的视频片段
    3. 可以练习听力，在抄写字幕界面，可以一句一句的播放视频。
    4. 可以自由的使用字幕或文档生成词库

- 截图：
记忆单词界面截图：

    ![Demo-Word-Dark](https://user-images.githubusercontent.com/16540656/179658965-e1c7447a-07ce-410b-9501-c9b6f5871410.png)

抄写字幕界面截图:

   ![Demo-Subtitles-Dark](https://user-images.githubusercontent.com/16540656/179658956-b7ae8741-ad2a-40d0-8dec-aef8d312ee33.png)

抄写文本界面截图：

   ![Demo-Text-Light](https://user-images.githubusercontent.com/16540656/179658962-281f2515-cfd2-472b-b171-c7c2433c1214.png)

**Comment by 521xueweihan** [comment]
@tangshimin 您推荐的项目，**已成功发布**在 [HelloGitHub 第 76 期](https://mp.weixin.qq.com/s/L3GP5DcTJb-3Z6kbB-OK7w)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
