### ISSUE TITLE
【开源自荐】regex-vis 可视化正则编辑器

### ISSUE THREAD

**Issue by Bowen7** [521xueweihan/HelloGitHub#2292]
## 推荐项目

- 项目地址：https://github.com/Bowen7/regex-vis

- 类别：JS

- 项目标题：regex-vis 可视化正则编辑器

- 项目描述：输入一条正则表达式后，会生成它的可视化图形；然后可以选择图形中某些节点进行二次编辑；最后可以对当前正则表达式进行测试。

- 亮点：
   - 将输入的正则表达式转化为可视化图形
   - 支持字面量和字符串形式，字符串形式下支持包括转义 `\` 符号
   - 选中图形，告知图形对应子表达式
   - 二次编辑图形，反向生成正则表达式
   - 对最终的正则表达式进行测试，并且可以生成带有测试用例的分享链接

- 截图：

![regex-vis](https://user-images.githubusercontent.com/27432981/180222745-da4671c6-8e0e-44f2-818f-25d5fa237956.gif)

- 后续更新计划：
   - 对输入框的正则表达式进行高亮处理
   - e2e 测试
   - 更多语言支持（i18n）

**Comment by 521xueweihan** [comment]
@Bowen7 
您推荐的项目，**已成功发布**在 [HelloGitHub 第 76 期](https://mp.weixin.qq.com/s/L3GP5DcTJb-3Z6kbB-OK7w)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
