### ISSUE TITLE
【开源自荐】Firezone - open-source remote access

### ISSUE THREAD

**Issue by gongjason** [521xueweihan/HelloGitHub#2295]
## 推荐项目

- 项目地址：https://github.com/firezone/firezone or https://www.firezone.dev/

- 类别：Elixir, Ruby, Rust

- 项目标题：Open-source VPN and Firewall server built on WireGuard. 

- 项目描述：

Firezone是一款新型虚拟组网产品。不同于传统vpn发布和管理难的问题，Firezone基于Wirecard之上，运行速度更高，安全性也更可靠。 初学者可以通过使用Firezone更好地学习安全，网络，及如何在Linux环境下self-host等知识。

Firezone offers an alternative to legacy VPNs, which are difficult to deploy and manage. It's also built on WireGuard, a new VPN protocol that's faster and more reliable than existing options. Beginners can set up Firezone to learn about security, networking, and self-hosting on Linux. 

- 亮点：

- 示例代码：（可选）

- 截图：（可选）gif/png/jpg
![firezone-usage](https://user-images.githubusercontent.com/52545545/147392573-fe4cb936-a0a8-436f-a69b-c0a9587de58b.gif)

- 后续更新计划：Client Apps, Multi-Sites, and user-scoped access rules.

**Comment by 521xueweihan** [comment]
@gongjason 不好意思，月刊不能收录 VPN 相关话题的项目。
