### ISSUE TITLE
【开源自荐】File-Engine文件高速搜索引擎

### ISSUE THREAD

**Issue by XUANXUQAQ** [521xueweihan/HelloGitHub#2297]
## 推荐项目

- 项目地址：https://github.com/XUANXUQAQ/File-Engine

- 类别：C、Java

- 项目标题：File-Engine文件高速搜索引擎

- 项目描述：这是一个本地文件搜索工具，他可以高速搜索本地文件，打开应用程序，提高工作效率。 这是一个绿色软件，不必安装，随时使用。File-Engine还拥有一个插件系统，可以自定义插件，拥有很高的自定义空间。

- 亮点：
    - 绿色便携软件，所有配置文件均在自身目录。   
    - 拥有插件系统，可以自己制作插件，实现不同的功能。   
    - 支持指定优先搜索文件夹，常用文件无需等待，立即打开。   
    - 自适应分辨率显示。
    - 多语言支持。

- 截图：
![](https://i.bmp.ovh/imgs/2022/07/22/88e418adc7b0d968.png)

![](https://i.bmp.ovh/imgs/2022/07/22/06ccdd2e3776926e.png)

- 后续更新计划：
    - 继续提高性能
    - 尝试使用graalvm的native-image编译成本地程序
    - 优化插件API，完善文档

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
