### ISSUE TITLE
【自荐项目】React 18 + TS + Vite + Nest.js 开发一个文件压缩服务

### ISSUE THREAD

**Issue by qufei1993** [521xueweihan/HelloGitHub#2299]
## 推荐项目

- 项目地址：https://github.com/qufei1993/compressor

- 类别：Node.js、JS

- 项目标题：React 18 + TS + Vite + Nest.js 开发一个文件压缩服务

- 项目描述：一款免费开源的文件压缩工具，Compressor 让您的文件体积更小！以 Web 形式实现，支持在本地运行，没有最大压缩限制。项目前后端整体以 TypeScript 编程语言为主，对于想学习 Node.js、React、TS 的朋友也是一个学习的机会，可以参考该项目，如果有帮助欢迎给个 Star 给予支持。

- 亮点：目前支持图像（PNG、Jpeg、Gif、转位 Webp）压缩，以页面交互方式来调整压缩配置，来达到满意的压缩效果。

- 截图：

![image](https://user-images.githubusercontent.com/17956058/180693721-bff41f06-8bac-457c-a10e-47b8b0e746d6.png)

- 后续更新计划：持续更新，后期会加上视频压缩、文档压缩

**Comment by 521xueweihan** [comment]
@qufei1993 
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
