### ISSUE TITLE
996.icu

### ISSUE THREAD

**Issue by daniuEvan** [521xueweihan/HelloGitHub#2300]
## 推荐项目

- 项目地址：https://github.com/996icu/996.ICU

- 类别：其他

- 项目标题：呼吁每个人都坚定维护劳动法

- 项目描述：。需要提前声明这个项目和政治没有关系这个项目不是一个政治运动，而是工薪阶级内心的呼喊。996.ICU 是指“工作 996， 生病 ICU” ，所以这个项目的主题是呼吁每个人都坚定维护劳动法，呼吁雇主也要尊重雇员的合法权益。996.ICU 项目是中国众多的 IT 从业者发起的一项倡议

- 亮点：996.icu项目的开源真是程序员内卷届甚至整个工薪阶级的一大步。

- 示例代码：（可选）

- 截图：（可选）gif/png/jpg

- 后续更新计划：

**Comment by 521xueweihan** [comment]
@daniuEvan 这个项目性质特殊无法收录，而且已经很流行了无需再收录到月刊了。
