### ISSUE TITLE
【开源自荐】在浏览器和nodeJS中优雅地发送 fetch 请求

### ISSUE THREAD

**Issue by fanhaoyuan** [521xueweihan/HelloGitHub#2302]
## 推荐项目

- 项目地址：[https://github.com/fatcherjs/fatcher](https://github.com/fatcherjs/fatcher)

- 类别：JS

- 项目标题：在浏览器和nodeJS中优雅地发送 fetch 请求

- 项目描述：fatcher 是一个轻量的 HTTP 请求库, 它基于 fetch，它允许我们在浏览器与 NodeJS 环境中使用原生的fetch来进行网络请求。目的是在于拥抱标准库的 fetch 的同时，提供 fetch 中一些没有提供的功能，以及让功能更好的拓展与复用。

- 亮点：
1. TypeScript 支持
2. 基于 Fetch API
3. 插拔式中间件
4. 体积最小化
5. 不可变上下文
6. Web Streams API 支持
7. NodeJS 与 浏览器行为一致
8. 简单易用的拦截器

- 示例代码：
```ts
import { fatcher, isFatcherError } from 'fatcher';

fatcher({
    url: '/',
})
    .then(result => {
        // 响应结果
        const { data, status } = result;
    })
    .catch(err => {
        // 捕捉错误
        if (isFatcherError(err)) {
            // 这里是发送请求成功，但是 status 值不是2xx的错误
            console.error(err.toJSON());
            return;
        }

        // 这里是其他错误
    });
```

- 截图：

<img width="1594" alt="fatcher" src="https://user-images.githubusercontent.com/35361626/180908106-3fa6a79b-1485-4166-b27f-ebf52aa464de.png">

- 后续更新计划：

1. 请求重试
2. 轮询请求
3. Service Worker 请求 Mock
4. Swagger JSON 生成 Mock 请求
5. 请求管道
6. 未完待续（详情查看 [Project](https://github.com/fatcherjs/fatcher/projects/2)）

**Comment by 521xueweihan** [comment]
@fanhaoyuan 月刊收录的项目，需要有让人有眼前一亮的感觉，建议持续迭代成为解决某个痛点、拥有某种亮点的项目。
