### ISSUE TITLE
【开源自荐】go-cryptobin 是 go 常用的加密解密库

### ISSUE THREAD

**Issue by deatil** [521xueweihan/HelloGitHub#2303]
## 推荐项目

- 项目地址：
https://github.com/deatil/go-cryptobin

- 类别：
Go

- 项目标题：
go-cryptobin 是 go 常用的加密解密库

- 项目描述：
go-cryptobin 是 go 的常用加密解密库
完整的包含了常用的对称加密和非对称加密类型
对称加密解密（Aes/Des/TriDes/SM4/Tea/Twofish）
对称加密解密模式（ECB/CBC/CFB/OFB/CTR/GCM）
对称加密解密补码（NoPadding/ZeroPadding/PKCS5Padding/PKCS7Padding/X923Padding/ISO10126Padding/ISO7816_4Padding/TBCPadding/PKCS1Padding）
 非对称加密解密（RSA/SM2）
 非对称签名验证（RSA/DSA/PSS/Ecdsa/EdDSA/SM2）
 默认 `Aes`, `ECB`, `NoPadding`

- 亮点：
解决了每次使用加密都需要去找的问题
几行代码即可完成加密解密及证书生成

- 示例代码：（可选）
~~~go
// 加密
    cypt := cryptobin.
        FromString("useData").
        SetKey("dfertf12dfertf12").
        Aes().
        ECB().
        PKCS5Padding().
        Encrypt().
        ToBase64String()
    cyptde := cryptobin.
        FromBase64String("i3FhtTp5v6aPJx0wTbarwg==").
        SetKey("dfertf12dfertf12").
        Aes().
        ECB().
        PKCS5Paddin().
        Decrypt().
        ToString()

    // i3FhtTp5v6aPJx0wTbarwg==
    fmt.Println("加密结果：", cypt)
    fmt.Println("解密结果：", cyptde)
~~~

- 截图：（可选）gif/png/jpg

- 后续更新计划：
继续完善使用逻辑，减低使用门槛，完善文档

**Comment by 521xueweihan** [comment]
@deatil 
非常感谢您推荐项目。API 不够优雅

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by deatil** [comment]
能确认下你们这边的api优雅是哪种吗？
每个项目的api都会根据作者的风格来确认api的风格，api的优雅不能去限定作者写api的风格吧
