### ISSUE TITLE
【开源自荐】酷瓜云课堂（腾讯云版）在线教育解决方案

### ISSUE THREAD

**Issue by xiaochong0302** [521xueweihan/HelloGitHub#2304]
- 项目地址：https://github.com/xiaochong0302/course-tencent-cloud

- 项目类别：PHP

- 项目标题：酷瓜云课堂（腾讯云版），在线教育解决方案

- 项目描述：酷瓜云课堂，依托腾讯云基础服务架构，采用C扩展框架Phalcon开发，GPL-2.0开源协议，实现了点播、直播、专栏、面授、问答、会员、群组、微聊、积分、秒杀等功能。docker容器化部署，极速搭建专属课程点播，课程直播学习平台。

- 项目亮点：国内的同类＂开源＂要么阉割严重，要么刷排名推广，要么纯粹挂羊头卖狗肉引流，要么搞一些和开源协议相悖的条款。酷瓜云课堂（腾讯云版）GPL2.0协议，走正道，正本清源，良币驱逐劣币。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 76 期](https://mp.weixin.qq.com/s/L3GP5DcTJb-3Z6kbB-OK7w)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
