### ISSUE TITLE
在家看片利器，有Android App以及桌面应用。

### ISSUE THREAD

**Issue by Kerr1Gan** [521xueweihan/HelloGitHub#231]
## 项目推荐
- 项目名称：ShareBox

- 项目地址：[Kerr1Gan/ShareBox](https://github.com/Kerr1Gan/ShareBox)

- 项目语言：Kotlin,Java

- 项目描述：家庭看片神器，可以用手机播放电脑里的视频，也可以用电脑播放手机里的视频，使用简单，能稳定运行在后台，目前支持的设备有Windows，Mac，Android。

- 推荐理由：支持多平台设备，随心所欲看片,随时随地看片，不再受限于数据线。

- 截图：
![phone](https://kerr1gan.github.io/sharebox/mobile.png)

![desktop](https://kerr1gan.github.io/sharebox/desktop.png)

**Comment by 521xueweihan** [comment]
@Kerr1Gan 非常鼓励这种自己开发工具的行为，但是该项目暂不能收录到月刊中。期待继续推荐有趣、入门级的开源项目。
