### ISSUE TITLE
[开源自推] 为静态资源创建 hash 以中断http缓存

### ISSUE THREAD

**Issue by Lete114** [521xueweihan/HelloGitHub#2315]
## 推荐项目

- 项目地址：https://github.com/Lete114/cache-hash

- 类别：JavaScript

- 项目标题：为静态资源创建 hash 以中断http缓存

- 项目描述：众所周知，http缓存分为两种缓存，**协商缓存**和**强制缓存**，他们都有各自的优缺点(自行上网查阅)，该项目就是为了解决**强制缓存**的短板，能够及时更新本地缓存

- 亮点：它采用 AST(Abstract Syntax Tree) 对html，css，js代码进行分析，为所有引用的资源生成hash，在目前看来并没有任何项目使用 AST 处理，大多都是使用正则表达式匹配，这可能会导致匹配错误

- 后续更新计划：
1. 新增对指定资源的过滤
2. 只对指定目录下的资源生成hash等

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
