### ISSUE TITLE
【开源自荐】Linux下简单好用的多功能壁纸软件

### ISSUE THREAD

**Issue by ambition-echo** [521xueweihan/HelloGitHub#2316]
## 推荐项目

- 项目地址：https://github.com/ambition-echo/earth_wallpaper

- 类别：Python

- 项目标题：Linux下简单好用的多功能壁纸软件

- 项目描述：该项目可以用来在Linux下管理桌面壁纸，解决了Linux下没有简单好用的壁纸管理工具的问题。可以从各自api下载高质量壁纸，主界面使用Qt搭建，核心功能使用Python实现，核心逻辑与界面分离之后可以很容易的使用Python进行扩展，目前可以实现实时地球壁纸，随机必应壁纸，每日必应壁纸，24h壁纸，本地壁纸循环等功能

- 亮点：
    - 专为Linux打造，兼容各个发行版，兼容主流桌面环境。使用Python非常易于扩展。
    - 实时地球壁纸可以调节地球显示比例，可根据个人喜好自由调整
    - 使用24h壁纸时可以自动获取ip并根据ip获取到地理位置，再根据地理位置计算出当地日出日落时间自动调整壁纸切换时间，相比于其他同类软件的手动设置，更加方便与人性化

- 截图：
<table>
<tr>
	<td> <img src=https://user-images.githubusercontent.com/59004461/183230829-a14af362-cd38-417e-88a2-a95f19d4ec98.png>
	<td> <img src=https://user-images.githubusercontent.com/59004461/183230903-935b4726-27cb-41b9-90d8-e3bc74da090f.png>
</table>
<table>
<tr>
	<td> <img src=https://user-images.githubusercontent.com/59004461/183231074-7e6bd286-d29e-4644-ab21-ffb1b0cd75ca.png>
</table>

- 后续更新计划：
    - 扩展api支持范围
    - 兼容更多Linux发行版与桌面环境
    - 使用PySide重构为纯Python项目

**Comment by 521xueweihan** [comment]
@ambition-echo 你的项目很好，但月刊已推荐过类似的项目，所以不能收录。
