### ISSUE TITLE
【开源自荐】一款方便、快捷的数据库文档查询、导出工具

### ISSUE THREAD

**Issue by TeslaFly01** [521xueweihan/HelloGitHub#2319]
## 推荐项目

- 项目地址：https://github.com/TeslaFly01/SmartSqlT

- 类别：C#

- 项目标题：SmartSQL - 一款方便、快捷的数据库文档查询、导出工具

- 项目描述：SmartSQL 是一款方便、快捷的数据库文档查询、导出工具！该工具从最初支持CHM文档格式开始，通过不断地探索开发、集思广益和不断改进，又陆续支持Word、Excel、PDF、Html、Xml、Json、MarkDown等文档格式的导出。同时支持SqlServer、MySql、PostgreSQL、SQLite等多种数据库的文档查询和导出功能。

- 亮点：可以方便、快捷的实现数据库文档查询、导出，支持SqlServer、MySql、PostgreSQL、SQLite等多种数据库及Word、Excel、PDF、Html、Xml、Json、MarkDown等多种文档格式导出。

- 示例代码：（可选）

- 截图：
![](https://camo.githubusercontent.com/e28e69ea8711d3d7c746f29b2a6bfea5556479fb08e4670f21f6cbe397ffd595/68747470733a2f2f67697465652e636f6d2f697a68616f66752f536d61727453514c2f7261772f6d61737465722f496d672f42616e6e65722e706e67)
![](https://camo.githubusercontent.com/c7fc259619a1567e5297d3dd303804d5e14df4046c4c84ed4303ff97f6bf8c3b/68747470733a2f2f67697465652e636f6d2f697a68616f66752f536d61727453514c2f7261772f6d61737465722f496d672f7373686f742d436f6e6e656374547970652e706e67)
![](https://camo.githubusercontent.com/2bc3e545613c918fed1237942e3abaef6ee352ace589d6e0998978b8f875874e/68747470733a2f2f67697465652e636f6d2f697a68616f66752f536d61727453514c2f7261772f6d61737465722f496d672f7373686f742d4578706f72742e706e67)

- 后续更新计划：
>  ⏳ 计划中：Oracle、DB2、达梦等数据库支持
>  ⏳ 计划中：对象结构对比功能
>  ⏳ 计划中：表、视图、存储过程同步功能

**Comment by 521xueweihan** [comment]
已推荐过类似项目。

非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
