### ISSUE TITLE
请问能否开放 API 我想寻求一些合作~

### ISSUE THREAD

**Issue by Desgard** [521xueweihan/HelloGitHub#232]
Hello 我是 GitHub 三方客户端 [Sepicat](https://itunes.apple.com/us/app/sepicat-for-github/id1355383210?mt=8) 的作者。

看到你的这个项目觉得很有趣，想将其内容加入到我的 App 中。我想做一个 Explorer 模块，用来为用户增加可定制的项目订阅功能，恰好你的网站实现了这一功能的数据源。

我目前的策略是通过抓包 hack 了掘金的接口（因为他们仅仅用了 base64 转码对用户进行了加密），但是他们推荐的质量并不如 HelloGitHub 的高。🤣

**Comment by 521xueweihan** [comment]
@Desgard 我觉得这是个好主意，还有你另外一个项目说到的 “Octodex 章鱼猫作品展” ，正好我最近写了个脚本，都给 down 下来了。唯一的阻碍就是我最近的工作上的任务很多，咱们微信交流一下。我的微信：eHVld2VpaGFu
