### ISSUE TITLE
【开源自荐】quic-tun 构建快速且安全的 TCP 传输隧道

### ISSUE THREAD

**Issue by jeffyjf** [521xueweihan/HelloGitHub#2320]
## 推荐项目

- 项目地址：https://github.com/kungze/quic-tun

- 类别：Go

- 项目标题：一个快速且安全的 TCP 隧道工具，能加速弱网环境下（网络有丢包）TCP 的转发性能。

- 项目描述：QUIC 是 google 指定的一个新型的可靠的传输层网络协议，相较于传统的 TCP 其在传输性能和安全方面有非常突出的表现，HTTP3 就是就要 QUIC 协议指定的，那么除了 HTTP3 这种新型应用，有没有方案能使传统的 TCP 应用也搭上 QUIC 的便车呢？答案当然是肯定的，quic-tun 就提供了这样的一套解决方案。

- 亮点：成倍的提升网络传输性能；安全的传输隧道；一个 UDP 端口构建多条隧道

- 后续更新计划：
  支持查看每个隧道的状态：流量和类型
  支持 UDP 打洞
  对接 prometheus 监控

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
