### ISSUE TITLE
开源项目：video.js

### ISSUE THREAD

**Issue by XYZscratcher** [521xueweihan/HelloGitHub#2322]
## 推荐项目

- 项目地址：https://github.com/videojs/video.js

- 类别：JS

- 项目标题：开源的HTML5视频播放器，支持HTML5视频和其他播放技术

- 项目描述：Video.js是一款从头开始构建的Web视频播放器。它支持HTML5视频和媒体源扩展，以及其他播放技术，如YouTube和Vimeo（通过[插件](https://videojs.com/plugins/)）。它支持在台式机和移动设备上播放视频。

- 亮点：
  - 能播放任何内容
  - 易于设计

- 示例代码：（可选）

- 截图：（可选）gif/png/jpg

- 后续更新计划：无

**Comment by 521xueweihan** [comment]
@XYZscratcher 该项目已推荐过：https://hellogithub.com/periodical/search/?q=https://github.com/videojs/video.js

**Comment by XYZscratcher** [comment]
@521xueweihan 但搜索结果中的项目并不是我推荐的项目
我推荐的是 https://github.com/videojs/video.js
搜索结果中的是 https://github.com/pinry/pinry

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 77 期](https://hellogithub.com/periodical/volume/77/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
