### ISSUE TITLE
【自荐项目】基于自然语言的，跨端跨框架 BDD UI 自动化测试方案 Flybirds

### ISSUE THREAD

**Issue by clgwlg** [521xueweihan/HelloGitHub#2328]
## 推荐项目

- 项目地址：https://github.com/ctripcorp/flybirds

- 类别：Python

- 项目标题：基于自然语言的，跨端跨框架 BDD UI 自动化测试方案 Flybirds

- 项目描述：一套基于BDD模式的前端UI自动化测试框架，提供了一系列开箱即用的工具和完善的文档。使用Flybirds你能够完成大部分的手机端自动化操作，以下是一些帮助入门的特性描述：

   - 基于BDD模式，类自然语言语法
   - 支持自动化操作、表单提交、UI元素校验、键盘输入、Deeplink跳转等
   - 支持 Android、iOS、React Native、Flutter、Web
   - 多端脚本复用
   - 支持多浏览器渲染引擎：Chromium、WebKit 和 Firefox
   - 支持多浏览器并发模式下的兼容性测试
   - 默认支持英文、中文两种语言，支持更多语言扩展
   - 插件式设计，支持用户自定义自动化扩展
   - 提供cli脚手架，快速搭建项目
   - 提供html报告

- 亮点：
   多端研发对于当今时代的前端开发来说是个绕不过去的话题，为了解决这些问题，行业内推出了很多开发方案，但是跨端 UI 自动化测试的解决方案并不多。

   Flybirds从2022年初开源至今，通过与社区内活跃用户的交流和反馈，推出了v0.4 版本的跨端跨框架测试方案，一套脚本多端运行，插件化的架构设计，也方便社区开发者自由加入扩展，一起共建成长。

   我们到底需要一个怎样的多端测试方案呢？从 Flybirds 的视角来说，我们希望多端测试不会成为研发流程中的障碍，特别是多端. 生态整体呈现欣欣向荣之时，自动化测试方案应和开发方案共同成长。

   不论是 Web 、React Native 端，Flutter端、还是Native端，理想的方案应该进行多端适配，保留良好扩展，兼顾更多框架，由. 社区共同建设，促进整体生态繁荣，因此就有了Flybirds 向社区提供的跨端跨框架测试方案。

- 插件化架构
插件化架构帮助我们将每一个端的能力拆分开, 插件提供运行时所需的组件、API 和配置，Flybirds 将它们分别注入对应的生命周期。

![Arc](https://flybirds.readthedocs.io/zh_CN/latest/_images/flybirds.png)

* 基于Behave，实现BDD中“自然语言测试用例文档”和“自动化测试代码”关联所需要用到的支持BDD工具。
* 基于Airtest，实现BDD中“测试用例能在自动化测试平台上执行”所需要用到的UI自动化测试框架。
* 基于Playwright, 实现BDD中“测试用例能在自动化测试平台上执行”需要用到Web端UI自动化测试框架。
* 基于PaddleOCR和OpenCV, 实现BDD中“测试用例能在自动化测试平台上执行”需要用到的OCR和图像识别能力。
* 基于Multiple-cucumber-html-reporter，实现可视化的测试报告

- 文件结构

```bash
 																
├─ cli	                        脚手架
├─ core
|   ├─ config_manage.py         配置管理
|   ├─ dsl
|   │    ├─ globalization       国际化处理
|   │    └─ step                Step 列表
|   ├─ global_resource.py       全局配置
|   ├─ launch_cycle             生命周期管理
|   └─ plugin
|        ├─ event               事件管理
|        ├─ plugin_manager.py   插件管理
|        └─ plugins					
|             ├─ android        Andriod 相关处理
|             ├─ ios            iOS 相关处理
|             └─ web            Web 相关处理
├─ report                       报告
├─ template                     模板处理
└─ utils								

```

- 示例代码
```Gherkin
# language: zh-CN
功能: flybirds功能测试-android ocr
  
   场景: 验证扫描文字
     当   启动APP[ctrip.android.view]
     那么 页面扫描完成出现文字[机票]
     那么 扫描存在[酒店]的文案
     那么 扫描存在[旅游]的文案
     那么 扫描不存在[机票机票]的文案

   场景: 验证点击扫描文字
     当   启动APP[ctrip.android.view]
     那么 页面扫描完成出现文字[机票]
     那么 点击扫描文案[机票]
     而且 等待[1]秒
     那么 页面扫描完成出现文字[阿克苏]
     那么 点击扫描文案[阿克苏]
     而且 等待[1]秒
     而且 全屏向上滑动[300]
     那么 页面扫描完成出现文字[阿克苏]
     那么 点击扫描文案[阿克苏]
     那么 全屏截图

   场景: 验证输入
     当   启动APP[ctrip.android.view]
     那么 页面扫描完成出现文字[目的地/酒店/景点/关键字/航班号]
     那么 在扫描文字[目的地/酒店/景点/关键字/航班号]中输入[上海]
     那么 全屏截图
```

- 截图：使用脚手架创建项目
![image](https://user-images.githubusercontent.com/30871402/185143833-bb702483-29eb-4ea0-a0fd-b9ac25518041.png)

- 文档：
   - [环境准备](https://flybirds.readthedocs.io/zh_CN/latest/BDD-UI-Testing-Flybirds.html#id6)
   - [运行前检查](https://flybirds.readthedocs.io/zh_CN/latest/BDD-UI-Testing-Flybirds.html#id8)
   - [运行](https://flybirds.readthedocs.io/zh_CN/latest/BDD-UI-Testing-Flybirds.html#id10)
   - [项目细节](https://flybirds.readthedocs.io/zh_CN/latest/BDD-UI-Testing-Flybirds.html#id13)
   - [DSL step](https://flybirds.readthedocs.io/zh_CN/latest/BDD-UI-Testing-Flybirds.html#id18)
   - [Android端例子](https://flybirds.readthedocs.io/zh_CN/latest/BDD-UI-Testing-Flybirds.html#android)
   - [iOS端例子](https://flybirds.readthedocs.io/zh_CN/latest/BDD-UI-Testing-Flybirds.html#ios)
   - [OCR&OpenCV使用例子](https://flybirds.readthedocs.io/zh_CN/latest/BDD-UI-Testing-Flybirds.html#ocr-opencv)
   - [Web端例子](https://flybirds.readthedocs.io/zh_CN/latest/BDD-UI-Testing-Flybirds.html#id69)
   - [多端应用例子](https://flybirds.readthedocs.io/zh_CN/latest/BDD-UI-Testing-Flybirds.html#id80)
   - [数据驱动参数化](https://flybirds.readthedocs.io/zh_CN/latest/BDD-UI-Testing-Flybirds.html#id83)
   - [多浏览器并发](https://flybirds.readthedocs.io/zh_CN/latest/BDD-UI-Testing-Flybirds.html#id84)
   - [自定义框架扩展](https://flybirds.readthedocs.io/zh_CN/latest/BDD-UI-Testing-Flybirds.html#id87)
   - [多语言](https://flybirds.readthedocs.io/zh_CN/latest/BDD-UI-Testing-Flybirds.html#id88)
   - [持续集成](https://flybirds.readthedocs.io/zh_CN/latest/BDD-UI-Testing-Flybirds.html#id89)
   - [更多细节](https://flybirds.readthedocs.io/zh_CN/latest/BDD-UI-Testing-Flybirds.html#)

- 后续更新计划：我们将按照 SemVer 版本控制规范进行发版。逐步新增功能和代码优化，非常欢迎您加入到我们的共建计划中，在 GitHub 上提出您的宝贵建议，以及在使用时遇到的一切问题，我们也会对此每周进行一次小版本的迭代。

   非常感谢！

**Comment by 521xueweihan** [comment]
请勿大段复制 README 内容，作为推荐理解理由和项目描述。
