### ISSUE TITLE
CocoaDebug

### ISSUE THREAD

**Issue by CocoaDebug** [521xueweihan/HelloGitHub#233]
## 项目推荐
- 项目名称：
CocoaDebug
- 项目地址：
https://github.com/CocoaDebug/CocoaDebug
- 项目语言：
![Languages](https://img.shields.io/badge/languages-Swift%20%7C%20ObjC-orange.svg)
- 项目描述：
iOS Debugging Tool (APP网络日志调试)
- 推荐理由：
APP内置网络日志调试工具，强大到没朋友，就怕你不用。
log日志，网络抓包，沙盒查看.....更多功能等你发现。
一行代码实现安装，代码零入侵。
- 示例代码：

      //Step 1.
      #if DEBUG
          import CocoaDebug
      #endif

      //Step 2.
      #if DEBUG
          CocoaDebug.enable()
      #endif

      //Step 3.
        public func print<T>(file: String = #file, function: String = #function, line: Int = #line, _ message: T, _ color: UIColor? = nil) {
          #if DEBUG
              swiftLog(file, function, line, message, color)
          #endif
      }

- 截图：
![example](https://raw.githubusercontent.com/CocoaDebug/CocoaDebug/master/pic/example.gif)

**Comment by 521xueweihan** [comment]
@DotzuX   您推荐的项目，已成功收录在 [HelloGitHub 第 26 期](https://hellogithub.com/periodical/volume/26/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by CocoaDebug** [comment]
小编你好！目前此开源项目已经正式更名为 [CocoaDebug](https://github.com/CocoaDebug/CocoaDebug)，目的为了更加直观方便的表达此开源项目的目的，从名字就能很好的理解它的作用。并且增加了不少实用的新功能，详见[README](https://github.com/CocoaDebug/CocoaDebug#introduction)

希望小编可以及时更新一下 [HelloGitHub 第 26 期](https://hellogithub.com/periodical/volume/26/)，打扰之处，敬请谅解！🙏

Thank you
Best Regard

**Comment by CocoaDebug** [comment]
@521xueweihan

**Comment by 521xueweihan** [comment]
@CocoaDebug 收到，更新后会在本issues中给予回复，再次感谢对本项目的支持。

**Comment by 521xueweihan** [comment]
@CocoaDebug 项目名称和代码已更新。[第 26 期](https://hellogithub.com/periodical/volume/26/#CocoaDebug)，再次感谢您对 HelloGitHub 的支持
