### ISSUE TITLE
[开源项目] fauxpilot 可本地运行的 GitHub Copilot

### ISSUE THREAD

**Issue by Chasing66** [521xueweihan/HelloGitHub#2330]
## 推荐项目

- 项目地址：https://github.com/moyix/fauxpilot

- 类别：机器学习

- 项目标题：可本地运行的 GitHub Copilot 服务

- 项目描述：使用 NVIDIA Triton Inference Server 里的 Salesforce 的 CodeGen 模型 自建本地的Copilot 服务

- 亮点：使用GPU资源即可搭建，并且可以使用多块GPU共同协作，运行在自己本地，无需担心隐私和License问题，可以训练自己的AI 模型， 以辅助代码开发

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 77 期](https://hellogithub.com/periodical/volume/77/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
