### ISSUE TITLE
开源项目： VanBlog

### ISSUE THREAD

**Issue by Mereithhh** [521xueweihan/HelloGitHub#2331]
## 推荐项目

- 项目地址：https://github.com/mereithhh/van-blog

- 类别：JS

- 项目标题：VanBlog —— 简洁风但功能齐全的个人博客解决方案

- 项目描述：一款简洁优雅的博客系统。前后台均为响应式布局且支持夜间模式、支持多种图床一键上传、后台功能全面、前台为静态页面，支持增量渲染，每次更改按需构建更新页面。拒绝花里胡哨，追求极致响应速度和博客体验，专注于个人博客场景。

- 亮点：前后台均为响应式且支持带自动切换的暗色模式、简洁美观的 UI、极致的相应速度、功能齐全的个人博客场景覆盖、支持多种图床一键上传、前台为静态页面并支持增量渲染，每次更改按需构建更新页面、docker 一键部署、全自动 HTTPS、完善的日志记录、开箱即用的访客统计与评论系统。

- 截图：https://pic.mereith.com/img/d2afe59eb3c561fd325e2123ea5b1401.%E5%89%8D%E5%8F%B0-%E7%99%BD%E8%89%B2.png   https://pic.mereith.com/img/1efc08838877ed216e927e9da1cc039e.%E5%89%8D%E5%8F%B0-%E9%BB%91%E8%89%B2.png https://pic.mereith.com/img/f0c0fd8334341fa28cdac55016458d7b.%E5%90%8E%E5%8F%B0-%E7%99%BD%E8%89%B2.png https://pic.mereith.com/img/f12a1345ed18286a1833b6b50070bb87.%E5%90%8E%E5%8F%B0-%E9%BB%91%E8%89%B2.png

- 后续更新计划：`自定义 CSS`、`RSS 订阅`、`迁移助手`...

**Comment by 521xueweihan** [comment]
@Mereithhh 加油！

**Comment by Mereithhh** [comment]
> @Mereithhh 加油！

🥰谢谢

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 x 期](https://hellogithub.com/periodical/volume/77/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
