### ISSUE TITLE
【开源自荐】SVNAdmin - 好用的服务器端SVN管理系统

### ISSUE THREAD

**Issue by witersen** [521xueweihan/HelloGitHub#2333]
## 推荐项目

- 项目地址：https://github.com/witersen/SvnAdminV2.0

- 类别：PHP

- 项目标题：SVNAdmin - 好用的服务器端 SVN 管理系统

- 项目描述：该系统为基于web的Subversion（SVN）服务器端管理工具。在线可视化配置功能强大，基本满足常见的SVN管理需求，可为管理运维人员省去繁琐的SVN部署和配置流程

- 亮点：支持自由配置 SVN 版本，支持在线目录浏览，支持人员权限配置文件级授权，服务器状态实时监测等，UI风格清新柔和

- 后续更新计划：

  - 支持对接 LDAP 等权限系统
  - 支持 http/https 协议
  - 拓展计划任务、双备份等功能
  - 拓展人员权限管理机制，更符合企业管理与 SVN 结合需求
  - 支持 webhooks 等机制，向便捷化对接 devops 靠近

- 截图：

  - 登录界面可分角色登录，配合后端实现的登录验证码更安全（验证码可后台手动关闭开启）

    <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/01.jpg" alt="" width="100%" height="100%" />

  - 服务器状态监控和信息统计，对当前服务器状态和SVN仓库信息更加了解

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/02.jpg" alt="" width="100%" height="100%" />
    
  - SVN仓库概览，提供了多种高级功能，还可根据仓库名、版本数、体积等一键排序

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/03.jpg" alt="" width="100%" height="100%" />
    
  - 新建SVN仓库提供两种模式 随意选择

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/04.jpg" alt="" width="100%" height="100%" />
    
  - 在线目录浏览更加方便 逐层加载，服务资源占用更低

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/05.jpg" alt="" width="100%" height="100%" />
    
  - 通过目录面包屑可以随时回到某级目录 可以看到目录的作者、版本、提交日期、提交日志等，还可一键复制检出地址

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/06.jpg" alt="" width="100%" height="100%" />
    
  - 仓库授权精确到文件级别，可对用户和用户组快速授权和更改权限

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/07.jpg" alt="" width="100%" height="100%" />
    
  - 支持在线dump方式备份，备份文件可随时下载或删除

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/08.jpg" alt="" width="100%" height="100%" />
    
  - 支持对SVN仓库钩子的管理

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/09.jpg" alt="" width="100%" height="100%" />
    
  - 提供了常用钩子，也可以将自己的常用钩子放在这里 

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/10.jpg" alt="" width="100%" height="100%" />
    
  - 可以查看每个仓库的详细信息，一键复制详细信息更加方便

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/11.jpg" alt="" width="100%" height="100%" />
    
  - 可以将通过dump方式备份的文件再导入仓库 实现SVN仓库的迁移

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/12.jpg" alt="" width="100%" height="100%" />
    
  -  仓库导入过程中如果抛出了错误信息会被收集被显示 方便管理人员更好的定位问题 

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/13.jpg" alt="" width="100%" height="100%" />
    
  - 可以很方便的修改仓库名称，这会自动同步配置文件，所以无需担心

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/14.jpg" alt="" width="100%" height="100%" />
    
  - 删除仓库也会有风险提示  

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/15.jpg" alt="" width="100%" height="100%" />
    
  - SVN用户管理支持启用、禁用、添加备注信息，管理用户更加方便

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/16.jpg" alt="" width="100%" height="100%" />
    
  - SVN分组支持显示其包含的用户和分组数量 同时支持修改备注信息 

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/17.jpg" alt="" width="100%" height="100%" />
    
  - 可以对分组进行用户成员编辑，系统会贴心的提示用户是否处于禁用状态 

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/18.jpg" alt="" width="100%" height="100%" />
    
  - 用户管理支持组嵌套，同时如果你不小心搞了一个循环嵌套，系统会提示你 

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/19.jpg" alt="" width="100%" height="100%" />
    
  - 分组名支持修改，系统会帮你修改配置文件的一切，无需担心 

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/20.jpg" alt="" width="100%" height="100%" />
    
  - 系统提供了日志功能，可以对系统的运转情况做个记录啦 

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/21.jpg" alt="" width="100%" height="100%" />
    
  - 管理人员可以修改自己的账号和密码，更加安全 

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/22.jpg" alt="" width="100%" height="100%" />
    
  - 系统提供了svnserve主机和端口绑定功能 而且开启了svnserve的运行日志 为你多一层运维保障 

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/23.jpg" alt="" width="100%" height="100%" />
    
  - 看看你的数据都在哪里存储呢

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/24.jpg" alt="" width="100%" height="100%" />
    
  - 配置邮件通知服务吧

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/25.jpg" alt="" width="100%" height="100%" />
    
  - 风险操作可以来个提示

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/26.jpg" alt="" width="100%" height="100%" />
    
  - 看看有没有新版本吧

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/27.jpg" alt="" width="100%" height="100%" />
    
  - SVN用户个人的界面 只可看到被授权的仓库路径

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/28.jpg" alt="" width="100%" height="100%" />
    
  - SVN用户可自己修改密码 无需联系管理人员了

     <img src="https://download.witersen.com/images/svnadmin-2.3.2/01.demo/29.jpg" alt="" width="100%" height="100%" />

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
