### ISSUE TITLE
【自荐项目】Start — 基于pip和venv的包管理工具

### ISSUE THREAD

**Issue by Dragon-GCS** [521xueweihan/HelloGitHub#2335]
## 推荐项目

- 项目地址：https://github.com/dragon-gcs/start

- 类别：Python

- 项目标题：Start — 基于pip和venv的轻量级项目管理工具

- 项目描述：一个基于`pip`的包管理工具。
  - 使用`pyproject.toml`作为配置文件，使用`venv`创建虚拟环境，可以自动在当前目录以及最多两层的目录内寻找虚拟环境。
  - 受`npm`和`poetry`的启发，可以将包分为`dependencies`和`dev-dependencies`进行管理，也可以使用`start install`一键安装项目所需的扩展包。
  - 受`cargo`的启发，可以使用`start init`和`start new`自动生成新的虚拟环境以及对应的模板文件

- 亮点：
  - 更加好看的命令行输出
  - 一键安装所需依赖项
  - 分析安装包之间的依赖关系并以树形图进行展示
  - 生成基于模板的新项目

- 示例代码：（可选）

- 截图：（可选）gif/png/jpg

![image](https://user-images.githubusercontent.com/54531807/185796717-74ddc11a-455d-466a-a968-28db2648d109.png)
![image](https://user-images.githubusercontent.com/54531807/185796792-beaf3d9d-4c6a-4a52-a769-f664de9dc49d.png)

- 后续更新计划：
  - 可自定义新项目模板

如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

最后，感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
已推荐过类似项目。

**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
