### ISSUE TITLE
【开源自荐】Apache Doris - 高性能、支持实时的 OLAP 数据库

### ISSUE THREAD

**Issue by jialiangCHOU** [521xueweihan/HelloGitHub#2337]
## 推荐项目

- 项目地址：[https://github.com/apache/doris](https://github.com/apache/doris)

- 类别：C++、Java

- 项目标题：基于 MPP 架构的高性能、支持实时的 OLAP 数据库

- 项目描述：

Apache Doris 是一个基于 MPP 架构的高性能、实时的分析型数据库，以极速易用的特点被人们所熟知，仅需亚秒级响应时间即可返回海量数据下的查询结果，不仅可以支持高并发的点查询场景，也能支持高吞吐的复杂分析场景。基于此，Apache Doris 能够较好的满足报表分析、即席查询、统一数仓构建、数据湖联邦查询加速等使用场景，用户可以在此之上构建用户行为分析、AB 实验平台、日志检索分析、用户画像分析、订单分析等应用。

截止目前， Apache Doris 已经在全球超过 500 家企业的生产环境中得到应用，在中国市值或估值排行前 50 的互联网公司中，有超过 80% 长期使用 Apache Doris，包括百度、美团、小米、京东、字节跳动、腾讯、快手、网易、微博、新浪、360 等知名公司。同时在一些传统行业如金融、能源、制造、电信等领域也有着丰富的应用。

2022 年 6月，Apache Doris 正式从 Apache 孵化器毕业，成为 Apache 顶级项目。

- 亮点：

**性能优异**：自带高效的列式存储引擎，减少数据扫描量的同时还实现了超高的数据压缩比。同时 Doris 还提供了丰富的索引结构来加速数据读取与过滤，利用分区分桶裁剪功能，Doris 可以支持在线服务业务的超高并发，单节点最高可支持上千 QPS。更进一步，Apache Doris 结合了向量化执行引擎来充分发挥现代化 CPU 并行计算能力，辅以智能物化视图技术实现预聚合加速，并可以通过查询优化器同时进行基于规划和基于代价的查询优化。通过上述多种方式，实现了极致的查询性能。

**简单易用**：支持标准 ANSI SQL 语法，包括单表聚合、排序、过滤和多表 Join、子查询等，还支持窗口函数、Grouping Set 等复杂 SQL 语法，同时用户可以通过 UDF 和 UDAF 等自定义函数来拓展系统功能。除此以外，Apache Doris 还实现了 MySQL 协议兼容，用户可以通过各类客户端工具来访问 Doris，并支持与 BI 工具的无缝对接。

**架构精简**：系统只有两个 Frontend（FE）和 Backend（BE）两个模块，其中 FE 节点负责用户请求的接入、查询计划的解析、元数据存储及集群管理等工作，BE 节点负责数据存储和查询计划的执行，自身就是一个完备的分布式数据库管理系统，用户无需安装任何第三方管控组件即可运行起 Apache Doris 集群，并且部署和升级过程都非常简易。同时，任一模块都可以支持横向拓展，集群最高可以拓展到数百个节点，支持存储超过 10PB 的超大规模数据。

**稳定可靠**：支持数据多副本存储，集群具备自愈功能，自身的分布式管理框架可以自动管理数据副本的分布、修复和均衡，副本损坏时系统可以自动感知并进行修复。节点扩容时，仅需一条 SQL 命令即可完成，数据分片会自动在节点间均衡，无需人工干预或操作。无论是扩容、缩容、单节点故障还是在升级过程中，系统都无需停止运行，可正常提供稳定可靠的在线服务。

**生态丰富**：提供丰富的数据同步方式，支持快速加载来自本地、Hadoop、Flink、Spark、Kafka、SeaTunnel 等系统中的数据，也可以直接访问 MySQL、PostgreSQL、Oracle、S3、Hive、Iceberg、Elasticsearch 等系统中的数据而无需数据复制。同时存储在 Doris 中的数据也可以被 Spark、Flink 读取，并且可以输出给上游数据应用进行展示分析。

- 示例代码：

下载地址：[https://doris.apache.org/zh-CN/download](https://doris.apache.org/zh-CN/download)
安装部署：[https://doris.apache.org/zh-CN/docs/install/install-deploy](https://doris.apache.org/zh-CN/docs/install/install-deploy)

- 系统架构图：

![](https://doris.apache.org/zh-CN/assets/images/what-is-doris-2ed5ac7fffa3799871d5d33993b1de09.png)

- 后续更新计划：
    - 冷热数据分离：能够将访问频次较少的冷数据沉降到云对象存储或者HDFS等冷存储，从而降低存储成本。
    - 支持 Array, Map, Jsonb 等复合数据类型来增强半结构化数据的分析能力
    - 新一代的基于cascades模型的CBO优化器，整体设计更加模块化，更加方便统计信息、代价模型和优化规则的迭代
    - 优化对 DBT，Airbyte，Metabase 等工具的支持。
    - 完善对数据湖外表联邦查询的支持，已经支持 Hive 和 Iceberg，对 Apache Hudi 即将在新版本发布

**Comment by ssusieee** [comment]
👍

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 x 期](https://hellogithub.com/periodical/volume/77/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
