### ISSUE TITLE
【开源自荐】RxImg——图像处理深度学习领域的拖拖乐。

### ISSUE THREAD

**Issue by rximg** [521xueweihan/HelloGitHub#2338]
## 推荐项目

- 项目地址：https://github.com/rximg/rximg

- 类别：Python

- 项目标题：RxImg——图像处理深度学习领域的拖拖乐。

- 项目描述：

  一句话描述就是，这是图像处理深度学习领域的拖拖乐。具体来说就是，以响应式的数据流，可视化的搭建图像处理流程。

  **安装步骤**
  安装python > 3.9

  ```
  pip install rximg
  python -m rximg.app
  ```
  浏览器中打开 127.0.0.1:5000

  **响应式数据流概念介绍**
  以观察者模式抽象图像处理步骤，这样数据源和图像处理函数就可以表达成一个有向图。只要数据源有更新，有向图中剩下的节点 
  就会响应式的执行。
  [Rxjs](http://link.zhihu.com/?target=https%3A//rxjs.dev/guide/overview)是JavaScript领域的一个函数式库，RxPY是Rxjs的python实 
  现。通过引入这一框架，将图像处理流程抽象成观察者模式，就可以将图像处理步骤变成响应式的。

  **多播数据流demo**
  这是一个支持多播的数据流，具体功能是将图片分别做不同核大小的高斯滤波后相减。
![highpass3217](https://user-images.githubusercontent.com/103294298/185937670-f2d56cb4-4ba0-4f76-a5c7-2b49e03433fd.png)

- 亮点：

1. 图像处理流程可视化。
2. 按DAG方式响应式的执行数据,支持更复杂的图像数据流，比如多分枝的，循环的，带条件的。
3. 可以便捷的利用python生态中的各种图像处理，深度学习资源。

- 示例代码：（可选）

- 截图：（可选）gif/png/jpg
![image](https://github.com/rximg/rximgimagebed/blob/master/firstdemo.gif?raw=true)
- 后续更新计划：

持续更新

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
