### ISSUE TITLE
【自荐项目】CMinor-Verifier：清华大学《软件分析与验证》课程实验平台

### ISSUE THREAD

**Issue by namasikanam** [521xueweihan/HelloGitHub#2339]
## 推荐项目

- 项目地址：https://github.com/thufv/CMinor-Verifier

- 类别：其它

- 项目标题：【CMinor-Verifier】清华大学《软件分析与验证》课程实验平台

- 项目描述：这是一个课程实验平台（就是个“大作业”框架），可供对自动化软件验证（一种可以验证程序的正确性&安全性的重量级技术）感兴趣的诸君，于其中上手实践来体验和学习软件验证算法。

- 亮点：自动化软件验证是一个门槛较高的领域，国内尚无可供上手实践学习软件验证的环境，所以我们便搞了这样一个框架以期能为国内的计算机行业普及软件验证的基础知识。

- 截图：
![image](https://user-images.githubusercontent.com/22532925/186426414-1b282c82-2d30-4ebd-8ff8-ded37f0c3702.png)

- 后续更新计划：此后会每年随课程迭代更新。

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
