### ISSUE TITLE
使用 Django+Bootstrap4 搭建的个人博客

### ISSUE THREAD

**Issue by Hopetree** [521xueweihan/HelloGitHub#234]
## 项目推荐
- 项目名称：Django+Bootstrap4 Blog

- 项目地址：https://github.com/Hopetree/izone

- 项目语言：Python

- 项目描述：Django+Bootstrap4 搭建的个人博客，博客的内容很丰富，功能实现比较多

- 推荐理由：Django 练手项目

- 示例代码：

- 截图：
![image](https://user-images.githubusercontent.com/30201215/39033141-376fd084-44a3-11e8-8bd2-957af22609dc.png)

**Comment by 521xueweihan** [comment]
@Hopetree 已推荐过类似项目。
