### ISSUE TITLE
【开源自荐】凹语言 - 专注于 WASM 平台的通用语言

### ISSUE THREAD

**Issue by chai2010** [521xueweihan/HelloGitHub#2343]
## 推荐项目

- 项目地址：https://github.com/wa-lang/wa

- 类别：Go

- 项目标题：凹语言

- 项目描述：专注于 WASM 平台的通用语言

- 亮点：国产，支持中文编程

- 示例代码：（可选）

```
# 版权 @2019 凹语言 作者。保留所有权利。

fn main() {
	println(40+2)
}
```

- 截图：（可选）gif/png/jpg

![](https://wa-lang.org/theme/favicon.svg)

- 后续更新计划：https://wa-lang.org/smalltalk/st0002.html

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
