### ISSUE TITLE
PythonOOP

### ISSUE THREAD

**Issue by adeywyt** [521xueweihan/HelloGitHub#2345]
## 推荐项目

- 项目地址：https://github.com/adeywyt/PythonOOP

- 类别：Python

- 项目标题：Python面向对象入门

- 项目描述：零基础Python面向对象入门到实践

- 亮点：Python面向对象讲的很清晰

- 截图：
![Snipaste_2022-08-30_21-25-34](https://user-images.githubusercontent.com/108849049/187448998-78f1059b-f9c1-46ad-aac6-6930f95a65d8.png)

- 后续更新计划：更新Python面向对象的高级使用方法

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
