### ISSUE TITLE
一个轻量级的 eventBus 实现

### ISSUE THREAD

**Issue by wangzianan** [521xueweihan/HelloGitHub#235]
## 项目推荐
- 项目名称：一个轻量级的 eventBus 实现

- 项目地址：https://github.com/wangzianan/EventEmitter

- 项目语言：JavaScript

- 项目描述：这个工具是发布订阅设计模式的实现，用来在模块间进行消息传递。在很多代码库中都会用到，非常常见。这个工具可以实现消息的订阅，取消订阅，消息的广播三种功能。

- 推荐理由：轻量并且功能完善，非常适合入门级选手

- 示例代码：eventEmitter.addListener(name, listener)

- 截图：
![image](https://user-images.githubusercontent.com/13514472/39058443-68287e6a-44ee-11e8-9e3b-d99b12449175.png)
![image](https://user-images.githubusercontent.com/13514472/39058457-7497c4a8-44ee-11e8-877a-a30426422ac8.png)

**Comment by 521xueweihan** [comment]
@wangzianan 已推荐过类似项目
