### ISSUE TITLE
【开源自荐】stevedore：基于数据包内容转发的四层负载均衡

### ISSUE THREAD

**Issue by near-notfaraway** [521xueweihan/HelloGitHub#2353]
## 推荐项目

- 项目地址：https://github.com/near-notfaraway/stevedore

- 类别：Go

- 项目标题：基于数据包内容转发的四层负载均衡

- 项目描述：一个可以基于数据包内容进行转发的四层负载均衡。基本只有七层负载均衡才对内容进行解析和转发，对于某些四层封装协议 KCP、QUIC、TFTP  或者私有协议来说，希望能够根据特点协议 field 做转发处理，则通过该项目能够支持

- 亮点：
  Stevedore 实现了一个四层负载均衡，并且可根据四层数据包的字节内容进行灵活地转发，其主要特点有：
  - 四层协议目前支持 UDP，也可应用于 KCP、QUIC、TFTP 协议，或基于 UDP 的一些私有协议
  - 数据包的上游选择，支持基于字节进行匹配，甚至基于比特来进行匹配
  - 数据包的负载均衡，支持指定的字节作为 hash key
  - 通过 epoll 搭配 recvmmsg 对转发效率进行优化，仅用于 linux 系统
  - 具有健康检查功能，当节点均不可用时，支持启用某个指定为备用的节点

- 示例代码：（可选）

- 截图：（可选）gif/png/jpg

- 后续更新计划：支持更多类型的内容判断逻辑，支持 TCP 协议，提高转发性能

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
