### ISSUE TITLE
【开源自荐】HummerRisk 开源的云原生安全检测平台

### ISSUE THREAD

**Issue by colinn66** [521xueweihan/HelloGitHub#2357]
## 推荐项目

项目地址：https://github.com/HummerRisk/HummerRisk

类别：Java

项目名称：HummerRisk

项目介绍：HummerRisk 是开源的云原生安全平台，以非侵入的方式对云原生环境进行全面安全合规检测，以混合云的安全合规为重点，同时延伸覆盖K8S容器云安全。

亮点：将混合云环境中的复杂安全合规问题简单化，构建便捷的云原生安全检测能力

后续更新计划：每月更新版本

参考文档：https://docs.hummerrisk.com/
截图：
![截图1](https://docs.hummerrisk.com/img/user/dashboard.png)
![截图2](https://docs.hummerrisk.com/img/user/account_system.png)
![截图3](https://docs.hummerrisk.com/img/user/resource_in.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 82 期](https://hellogithub.com/periodical/volume/82)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

更多详情尽在：https://hellogithub.com/repository/133f754e87ff4b879d65178765a5fcc2

最后，欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
