### ISSUE TITLE
开源项目：JSON Crack

### ISSUE THREAD

**Issue by XYZscratcher** [521xueweihan/HelloGitHub#2358]
## 推荐项目

- 项目地址：https://github.com/AykutSarac/jsoncrack.com

- 类别：js

- 项目标题：适用于您的数据的简单 JSON 可视化工具

- 项目描述：JSON Crack 是一种从 JSON 对象生成图的工具。这些图表比文本格式更容易导航，并且为了使其更加方便，该工具还允许您搜索节点。

- 亮点：
  - 搜索节点
  - 共享链接 & 创建嵌入小部件
  - 下载/剪贴板作为图像
  - 在本地上传 JSON 或从网址提取

  - 出色的用户界面/用户体验

  - 亮/暗模式

  - 高级错误消息

- 示例代码：（可选）

- 截图：（可选）gif/png/jpg

- 后续更新计划：

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 x 期](https://hellogithub.com/periodical/volume/78/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
