### ISSUE TITLE
【开源自荐】命令行可视化文件管理工具：Lin 

### ISSUE THREAD

**Issue by Mrwu87** [521xueweihan/HelloGitHub#2369]
项目地址：https://github.com/Mrwu87/Lin
类别：python3
项目标题：TUI方式可视化管理文件
项目描述：离线文件管理工具运行在云服务器可代替桌面管理文件
亮点：
方便使用，扩展性高；
命令行可视化轻松管理文件，让不懂linux的程序员也能玩转文件系统，让懂linux的程序员提升管理系统的运维或者开发效率；
该工具也能够轻松使用命令行模式进行配置不需要退出；
可使用鼠标点击进行文件操作；
远程轻松拷贝文件；
一键复制内容；

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
