### ISSUE TITLE
DocArray 为机器学习而生的数据结构

### ISSUE THREAD

**Issue by Nick17t** [521xueweihan/HelloGitHub#2370]
## 推荐项目

- 项目地址：[DocArray](https://github.com/jina-ai/DocArray)

- 类别：Python

- 项目标题：[DocArray](https://github.com/jina-ai/docarray)  为机器学习而生的数据结构

- 项目描述：[DocArray](https://github.com/jina-ai/DocArray) 是由 Jina AI 开发的，一种用来存储非结构化数据的数据结构，目前已经支持 Redis，Elasticsearch，Qdrant 等存储后台。基于强大的数据建模能力，DocArray 可以用于表示一些非常复杂的数据结构，并且能直观地表示多模态数据。

- 亮点一：分层存储
当你用 DocArray 表示电影，你可以在第一层存储整部视频，第二层存储每一个镜头的画面，第三层存储台词文本 ... 基于或结合不同的模态进行搜索。
- 亮点二： 可交互的可视化
![embedding-projector](https://user-images.githubusercontent.com/55871322/191454467-46b0cf33-9452-4b3a-a42c-3f2ff050fec7.gif)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
