### ISSUE TITLE
【开源自荐】利用Python自动生成小学生加减乘除口算考试题卷

### ISSUE THREAD

**Issue by bosichong** [521xueweihan/HelloGitHub#2375]
## 推荐项目

- 项目地址：https://github.com/bosichong/PrimarySchoolMathematics

- 类别：Python

- 项目标题：利用Python自动生成小学生加减乘除口算考试题卷

- 项目描述：孩子上小学一年级了，加减乘除的口算就要开始练习了，估计老师肯定会让家长出题，所以提前准备一下，利用Python开发了一套自动生成小学生口算题的小应用。

- 亮点：可以设置各算数项和结果的取值范围及多步算数符号的选择，可以生成求结果、求算数项、带括号的算式，最多支持3步算式题,可以简单设置文档标题，小标题。设置生成的口算题文档个数.最后打开文件可以直接连接打印机打印出来.

- 示例代码：（可选）

- 截图：
![](https://raw.githubusercontent.com/bosichong/PrimarySchoolMathematics/flask-PSM/jt.png)

程序成生的口算题截图：

![输入图片说明](https://images.gitee.com/uploads/images/2018/1119/214154_bb529734_125848.png "001.png")

![输入图片说明](https://images.gitee.com/uploads/images/2018/1119/214206_a3081f2e_125848.png "002.png")

![输入图片说明](https://images.gitee.com/uploads/images/2018/1119/214230_b9c6e3ef_125848.png "003.png")

![输入图片说明](https://images.gitee.com/uploads/images/2018/1119/214240_e946434d_125848.png "004.png")

- 后续更新计划：

添加更为方便的口算题生成方式,以年级为分类,快速生成对应年级的相关口算题卷子.

**Comment by 521xueweihan** [comment]
@bosichong 月刊已收录类似的开源项目，贵项目暂不收录到月刊。
