### ISSUE TITLE
【开源自荐】Simple Admin 分布式后台管理系统

### ISSUE THREAD

**Issue by suyuan32** [521xueweihan/HelloGitHub#2378]
## 推荐项目

- 项目地址：https://github.com/suyuan32/simple-admin-core

- 类别：Go

- 项目标题：Simple Admin 分布式后台管理系统

- 项目描述： 该项目主要解决目前go语言的后台框架虽然多例如gin, beego, go-zero等，但是基于rpc和微服务构建的后台管理系统还比较少，simple admin主要提供了一个快速开发容器化微服务后台管理系统的基本框架，使用者可以根据自己的需求添加微服务，使用的工具可以直接生成服务注册发现的代码。这也是一个初学者学习容器化开发的良好学习示例，项目未来会有docker部署和k8s部署的教程和文档，适合golang新手开发者学习。

- 亮点：
- goctl 一键生成支持 consul 服务注册发现以及配置文件的微服务。
- 区别于go-zero官方的swagger集成方案，simple admin直接支持go-swagger所有注解，只需在api文件编写声明即可生成详细的swagger文档
- 原生支持 validator ， 在声明文件声明 validate 即可实现数据校验
- 国际化处理，项目默认支持中英双语，完善的国际化方案。
- 微服务易于拆分添加，减少项目冲突。
- 完善的中英文文档和视频教程。

- 示例代码：（可选）

- 截图：（可选）
- ![Simple Admin](https://s1.imagehub.cc/images/2022/09/25/-2022-09-25-16-38-15.png)
- ![SimpleAdmin](https://s1.imagehub.cc/images/2022/09/25/authority_zh_cn.png)

- 后续更新计划：
- 消息中心服务： 提供短信发送和邮箱发送以及内部IM等功能
- 支付中心： 集成微信，支付宝，paypal 等支付接口
- 论坛服务:  提供论坛接口，前端暂时考虑使用flutter方便跨平台

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
