### ISSUE TITLE
地理坐标转换工具gcoord

### ISSUE THREAD

**Issue by hujiulong** [521xueweihan/HelloGitHub#238]
## 项目推荐
- 项目名称：gcoord

- 项目地址：https://github.com/hujiulong/gcoord

- 项目语言：javascript

- 项目描述：一个处理地理坐标的轻型js库

- 推荐理由：由于国内对于地理坐标有特殊的政策，导致从API得到的地理坐标放在百度地图或高德地图上会有数百米的偏移，gcoord可以将坐标在不同坐标系下转换，修正偏移。

- 示例代码：
从API得到的地理坐标转换为百度地图坐标系
```js
var result = gcoord.transform(
    [ 116.403988, 39.914266 ],    // 经纬度坐标
    gcoord.WGS84,                 // 当前坐标系
    gcoord.BD09                   // 目标坐标系
);

console.log( result );  // [ 116.41661560068297, 39.92196580126834 ]
```

- 截图：

**Comment by 521xueweihan** [comment]
@hujiulong 您推荐的项目，已成功收录在 [HelloGitHub 第 25 期](https://hellogithub.com/volume/25/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
