### ISSUE TITLE
开源自荐 ｜ redis-shake：用于 Redis 实例间数据迁移与清洗，支持自定义过滤函数

### ISSUE THREAD

**Issue by suxb201** [521xueweihan/HelloGitHub#2381]
## 推荐项目

- 项目地址：https://github.com/alibaba/RedisShake

- 类别：Go

- 项目标题：用于 Redis 实例间数据迁移与清洗，支持自定义过滤函数

- 项目描述：
    - 用于 Redis 实例间数据迁移与清洗
    - 支持使用 Lua 语言自定义过滤函数
    - 代码清晰，适合学习 Redis 数据存储结构
    - 中文文档：https://github.com/alibaba/RedisShake/wiki
    - 👏 欢迎蹭 PR

- 亮点：过滤项灵活、代码清晰、监控项完整可观测性好

- 截图

![image](https://user-images.githubusercontent.com/16659368/192509767-208318c5-9563-4c23-aa9c-0986fd28dc8f.png)

<img width="1597" alt="image" src="https://user-images.githubusercontent.com/16659368/192509722-f7bc9f8f-0108-458c-9a74-3f0c90dd25f2.png">

**Comment by 521xueweihan** [comment]
@suxb201 该项目已收录在第 43 期
