### ISSUE TITLE
开源项目 | C#.NET Redis 客户端组件 FreeRedis

### ISSUE THREAD

**Issue by 2881099** [521xueweihan/HelloGitHub#2382]
## 推荐项目

- 项目地址：https://github.com/2881099/FreeRedis

- 类别：C#

- 项目标题：C#.NET Redis Client 客户端 FreeRedis

- 项目描述：基于 .NET 的 Redis 客户端，支持 .NET Core 2.1+、.NET Framework 4.0+ 以及 Xamarin。

- 亮点：

  - 🌈 所有方法名与 redis-cli 保持一致
  - 🌌 支持 Redis 集群（服务端要求 3.2 及以上版本）
  - ⛳ 支持 Redis 哨兵模式
  - 🎣 支持主从分离（Master-Slave）
  - 📡 支持发布订阅（Pub-Sub）
  - 📃 支持 Redis Lua 脚本
  - 💻 支持管道（Pipeline）
  - 📰 支持事务
  - 🌴 支持 GEO 命令（服务端要求 3.2 及以上版本）
   - 🌲 支持 STREAM 类型命令（服务端要求 5.0 及以上版本）
  - ⚡ 支持本地缓存（Client-side-cahing，服务端要求 6.0 及以上版本）
  - 🌳 支持 Redis 6 的 RESP3 协议

- 示例代码：（可选）

```csharp
public static RedisClient cli = new RedisClient("127.0.0.1:6379,password=123,defaultDatabase=13");
//cli.Serialize = obj => JsonConvert.SerializeObject(obj);
//cli.Deserialize = (json, type) => JsonConvert.DeserializeObject(json, type);
cli.Notice += (s, e) => Console.WriteLine(e.Log); //打印命令日志

cli.Set("key1", "value1");
cli.MSet("key1", "value1", "key2", "value2");

string value1 = cli.Get("key1");
string[] vals = cli.MGet("key1", "key2");
```

- 截图：（可选）gif/png/jpg

- 后续更新计划：

作者拥有 csredis 经验重构 FreeRedis 开源项目，经历了两年生产验证，功能完整程度高，之后会跟随 Redis-server 新版本发布更新对应的功能。

**Comment by 521xueweihan** [comment]
@2881099 该项目将在网站进行收录和展示，Issues 就直接关闭了。
