### ISSUE TITLE
开源自荐 ｜OneAPI ：一个用于替代 Swagger/SpringFox 的 API 工具，既不需要修改后端代码，也不需要启动应用

### ISSUE THREAD

**Issue by tudou527** [521xueweihan/HelloGitHub#2385]
## 推荐项目

- 项目地址：https://github.com/tudou527/OneAPI

- 类别：JS

- 项目标题：OneAPI

- 项目描述：一个根据 Java 代码生成 API 的工具，不需要后端改代码，也不需要启动后端应用

- 亮点：
    - 专注 API 生产。于 Apifox/YApi 等工具相比，OneAPI 专注于 API 生产，支持导出 OpenAPI 3.0 协议文件到业界其它工具消费
    - 后端 0 成本。不需要修改后端代码，也不需要启动应用
    - 可扩展。可支持企业内部各种 RPC 协议
    - API 自动化。提供 CLI 工具可以于 git/svn 等结合实现 API 生产自动化

- 示例代码：（可选）

- 截图：（可选）gif/png/jpg
<img width="600" alt="image" src="https://user-images.githubusercontent.com/1134658/194768226-ebed6546-e951-4cfb-a3c3-2bc69b7d7ebe.png">

<img width="600" alt="image" src="https://user-images.githubusercontent.com/1134658/193092688-46b2b156-619d-4e0e-bb6b-c9258ee35d0d.png">

- 后续更新计划：
     - 完善后端代码解析能力

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
