### ISSUE TITLE
iOS Shadowrocket砸壳到重签

### ISSUE THREAD

**Issue by we11cheng** [521xueweihan/HelloGitHub#239]
## 项目推荐
- 项目名称：iOS Shadowrocket砸壳到重签

- 项目地址：https://github.com/we11cheng/WCShadowrocket

- 项目语言：objective-c

- 项目描述：iOS Shadowrocket 完美重签（原生砸壳，源码运行即可），无须越狱。

- 推荐理由：简单易用。

- 示例代码：

- 截图：
![image](https://user-images.githubusercontent.com/13333981/39390648-244cf96e-4aca-11e8-802d-6c28ea500503.png)

**Comment by 521xueweihan** [comment]
@we11cheng 考虑到项目的长治久安，暂不推荐任何vpn、凸墙、有关政治的项目。
