### ISSUE TITLE
推荐项目：Howdz Dashboard

### ISSUE THREAD

**Issue by XYZscratcher** [521xueweihan/HelloGitHub#2390]
## 推荐项目

- 项目地址：https://github.com/leon-kfd/Dashboard

- 类别：其他

- 项目标题：Howdz Dashboard

- 项目描述：基于Vue3, Typescript, Vite的一个完全自定义配置的浏览器起始页

- 亮点：
  - 💫 提供基于`文档流`的响应布局或`Fixed模式`固定任意位置的两种布局模式
  - ✨`响应式设计`，编辑模式下拖拽组件更改其大小和位置
  - 🍭 组件可自由添加或删除，并且组件的`样式`和`功能`都是可配置的
  - 🍌 数据可使用`密钥`或`JSON文件`导出以实现`同步`功能
  - 🎉 预设多种`主题`，初始进入可任意选择
  - 🌟 可配置`动态壁纸`背景，选用官方提供或自行添加网络视频路径即可
  - 📋 可配置`多标签页`模式，允许添加切换多个隔离的页面
  - 🍦 可配置组件`交互`行为，设置点击组件弹出另一个组件等交互操作
  - 🚀 资源使用`Service worker`缓存加快页面加载速度.
  - 🌐 支持语言切换，当前支持`简体中文`与`英文`
  - 🌈 提供浏览器插件模式[Chrome extension](https://chrome.google.com/webstore/detail/howdz%E8%B5%B7%E5%A7%8B%E9%A1%B5/ggglfehkglgpenacfalffmiojghklamm/related)
  - 🎲 提供基于 Electron 的桌面应用[Desktop Application](https://github.com/leon-kfd/Dashboard/releases/tag/)

- 示例代码：（可选）

- 截图：（可选）gif/png/jpg

- 后续更新计划：

**Comment by SparkHan** [comment]
我现在不在，如果有事请用QQ找我。
