### ISSUE TITLE
【开源自荐】CThreadPool : 一款简单高效、功能强大、跨平台的C++线程池

### ISSUE THREAD

**Issue by ChunelFeng** [521xueweihan/HelloGitHub#2391]
## 推荐项目

- 项目地址：https://github.com/ChunelFeng/CThreadPool

- 类别：`C++`

- 项目标题：`CThreadPool`

- 项目描述：
 
**本项目是一个跨平台、高性能、无任何三方依赖、功能强大的C++线程池**。原本是 [CGraph 项目](https://github.com/ChunelFeng/CGraph) 中的线程调度模块，因为咨询和想要单独使用的人较多，所以专门抽出来，方便大家使用。

- 亮点：

C++标准库中没有线程池功能，但线程池又是非常常用和重要的基础组件。相比github上目前star数最多的threadpool，本库**调度性能提升近4倍**。

除此之外，还增加了很多实用功能，提供了多个功能配置参数。支持 **主辅线程机制、多任务队列机制、任务偷盗、线程数自动调节、超时机制、任务组机制、优先级机制** 等功能。同时，也开放了调度机制接口，可以供使用者继承，并根据实际情况做优化。

本仓库工程结构精简统一、上手简单、文档信息齐全，且属于C++体系中，比较重要的基础组件，可复用性高。希望在此推荐给大家，以便于今后相互学习和交流。

- 示例代码：
```cpp
#include "src/CThreadPool.h"

using namespace CTP;

float add_by_5(float i) {
    return i + 5.0f;
}

void tutorial() {
    UThreadPool tp;
    int i = 6, j = 3;
    auto r1 = tp.commit([i, j] { return i - j; });
    std::future<float> r2 = tp.commit(std::bind(add_by_5, 8.5f));

    std::cout << r1.get() << std::endl;
    std::cout << r2.get() << std::endl;
}
```

- 后续更新计划：

兼容协程调度机制。优化超时退出机制。引入环形队列机制。

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。已推荐过类似项目

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
