### ISSUE TITLE
推荐项目：action

### ISSUE THREAD

**Issue by zk4** [521xueweihan/HelloGitHub#2392]
## 推荐项目

- 项目地址：https://github.com/zk4/action
- 类别： bash

- 项目标题：管理命令行的命令，支持自动搜索，占位输入，任意语言
- 项目描述：用来省掉繁杂命令的记忆成本，基于 fzf。将命令做统一管理与复用。非常适合命令行重度用户。
- 亮点：不需要重新学任何东西。相对 navi， 等一些类似项目。极轻量。学习成本几乎为 0。极易扩展，只要你会写任意语言的脚本，bash，js，python，甚至 java。
- 示例代码：
创建 action 
``` bash
#!/bin/bash
source "$(dirname "$0")/../util/base.sh"
# -------------------------------------------
directory=$(input2 "文件夹位置: ")
du -h -d 2 $directory | gsort -h
```
![2022-10-07 12.01.35](https://zk4bucket.oss-cn-beijing.aliyuncs.com/uPic/2022-10-07%2012.01.35.gif)

- 后续更新计划：
- 整合 tldr 以及一些好用的命令行快速输入源。
- 扩展更多实用的 action 集合

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
