### ISSUE TITLE
github加速仓库在哪里

### ISSUE THREAD

**Issue by biange200** [521xueweihan/HelloGitHub#2398]
你好 请问一下你github hosts加速仓库在哪里 我没找到
我想收藏你的加速仓库

**Comment by czw-fs** [comment]
你是不是发错人了,我好像不认识你




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "521xueweihan/HelloGitHub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月12日(星期三) 上午10:04
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[521xueweihan/HelloGitHub] github加速仓库在哪里 (Issue #2398)





 
你好 请问一下你github hosts加速仓库在哪里 我没找到
 我想收藏你的加速仓库

**Comment by biange200** [comment]
https://raw.hellogithub.com/hosts这个不是你的？获取Outlook for Android

**Comment by czw-fs** [comment]
这个链接我打开是404

**Comment by czw-fs** [comment]
[521xueweihan](https://github.com/521xueweihan)

**Comment by biange200** [comment]
不是你的？

**Comment by czw-fs** [comment]
肯定是弄错了

**Comment by biange200** [comment]
哦 sorry获取Outlook for Android

**Comment by 521xueweihan** [comment]
@biange200 就是这个：https://raw.hellogithub.com

**Comment by biange200** [comment]
哦 sorry获取Outlook for Android发件人: ***@***.*** ***@***.***> 代表 czw-fs ***@***.***>发送时间: 2022年10月12日星期三 11:10收件人: 521xueweihan/HelloGitHub ***@***.***>抄送: biange200 ***@***.***>; Author ***@***.***>主题: Re: [521xueweihan/HelloGitHub] github加速仓库在哪里 (Issue #2398)肯定是弄错了—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
