### ISSUE TITLE
[项目推荐]一款功能强大的安卓软件

### ISSUE THREAD

**Issue by xp12047** [521xueweihan/HelloGitHub#2399]
## 推荐项目

- 项目地址：
https://github.com/ic005k/Knot

- 类别：
C++

- 项目标题：集待办，薄记，计步器，markdown备忘单等于一体的安卓app

- 项目描述：

     
- 簿记(导出为图片)
- 计数器  
- 待办事项清单
- 计步器  
- 统计图表  
- 统计报告 
- 阅读器(txt.epub)  
- 笔记(markdown支持)   
- 备注(markdown支持)
- 数据导出导入  
- 数据备份onedrive      

- 示例代码：（可选）

- 截图：（可选）gif/png/jpg

![Screenshot_20221019_120724_com x](https://user-images.githubusercontent.com/56335408/196595543-829e1a66-b90a-4f11-82c1-377354379cb9.jpg)
![Screenshot_20221019_120707_com x](https://user-images.githubusercontent.com/56335408/196595544-7db859a0-f444-4b54-a462-495d8e784800.jpg)
![Screenshot_20221019_120732_com x](https://user-images.githubusercontent.com/56335408/196595549-f8036065-4239-4e3c-9c0e-8d47371eebcb.jpg)
![Screenshot_20221019_120654_com x](https://user-images.githubusercontent.com/56335408/196595554-e0bc78cf-4814-4af6-84c3-87759aa24b8e.jpg)  
![Screenshot_20221019_120804_com x](https://user-images.githubusercontent.com/56335408/196595530-a93ef4a5-1486-43d0-a9ae-46478c763e84.jpg)
![Screenshot_20221019_120720_com x](https://user-images.githubusercontent.com/56335408/196595538-f2f24e96-d3ad-4ae7-b2b4-8327872f7504.jpg)

- 后续更新计划：

## 提高项目收录的方法（提交时请删除下方内容）

1. **请勿使用复制的内容**作为项目描述提交！

2. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目**是否被推荐过**。

3. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

最后，感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
