### ISSUE TITLE
推荐项目：satori

### ISSUE THREAD

**Issue by XYZscratcher** [521xueweihan/HelloGitHub#2401]
## 推荐项目

- 项目地址：https://github.com/vercel/satori

- 类别：JS

- 项目标题：satori：将 HTML 和 CSS 转换为 SVG 的库。

- 项目描述：一个能将 HTML 和 CSS 转换为 SVG 的库，支持 JSX 语法。

- 亮点：
  - 支持 JSX 语法，这使得它非常易于使用

- 示例代码：（可选）
```js
// api.jsx
import satori from 'satori'

const svg = await satori(
  <div style={{ color: 'black' }}>hello, world</div>,
  {
    width: 600,
    height: 400,
    fonts: [
      {
        name: 'Roboto',
        data: robotoArrayBuffer,
        weight: 400,
        style: 'normal',
      },
    ],
  },
)
```

- 截图：（可选）gif/png/jpg

- 后续更新计划：

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 82 期](https://hellogithub.com/periodical/volume/82)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
