### ISSUE TITLE
【开源自荐】LoopAuth : 同时支持RBAC、ABAC双模式的JavaWeb鉴权框架

### ISSUE THREAD

**Issue by ChangZou** [521xueweihan/HelloGitHub#2403]
## 推荐项目

- 项目地址：https://github.com/ChangZou/LoopAuth

- 类别：Java

- 项目标题：同时支持RBAC、ABAC双模式的JavaWeb鉴权框架

- 项目描述：[LoopAuth](https://github.com/ChangZou/LoopAuth) 是一款JavaWeb鉴权框架，同时支持RBAC (角色鉴权校验)、ABAC (规则流引擎鉴权)，并还提供会话管理等功能。在使用时可根据需求自行选择RBAC、ABAC、Session等功能包使用，即使你的项目已经完成登录Or角色鉴权等功能，你依然可以只依赖ABAC模块进行规则流引擎鉴权。

- 亮点：支持ABAC鉴权模式，鉴权粒度更细。对于项目更低的侵入，可根据需求自行选择需要使用的功能包。

- 后续更新计划：微服务的支持包：更快捷的整合进微服务项目、账户风险监控：Session模块对于用户的异地登录、风险操作进行监控及动态锁定账户、对更多Java框架的支持：例如Spring Flux的快速接入。

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。已推荐过类似项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
