### ISSUE TITLE
【开源自荐】redis可视化工具

### ISSUE THREAD

**Issue by gphper** [521xueweihan/HelloGitHub#2404]
## 推荐项目

- 项目地址：https://github.com/gphper/grm

- 类别：其他（go+vue）

- 项目标题：web端redis可视化工具

- 项目描述：基于go+vue的web版redis管理工具

- 亮点：web端、部署方便简单支持命令行、lua、监控等

- 示例代码：（可选）

- 截图：（可选）gif/png/jpg
![all](https://user-images.githubusercontent.com/18718299/197769599-cb607038-03bf-4e2d-8934-00a4da95cd3d.gif)

- 后续更新计划：

1. 支持docker部署
2. 用户及权限管理

**Comment by 521xueweihan** [comment]
已推荐过类似的工具

**Comment by gphper** [comment]
确实redis管理类工具有不少，提个建议有没有可能单独一个模块或某种方式用来整理功能类似的这种工具，这样的话大家找工具的时候也会有更多种选择，每个工具还是有细微的不一样的地方的，例如我知道的类似的redis工具要么是桌面版的，要么是依赖开发环境或者是前端单独部署的，我这是直接二进制进行部署的，当然不排除还有很多没接触到过的~~
