### ISSUE TITLE
【开源自荐】gohtml - Gin框架中间件：快速自动代理前端页面

### ISSUE THREAD

**Issue by jtyoui** [521xueweihan/HelloGitHub#2411]
## 推荐项目

- 项目地址：https://github.com/gounits/gohtml

- 类别：Go

- 项目标题：gohtml - 一种静态页面代理技术、自动绑定Gin框架

- 项目描述：
   [GoHTML](https://github.com/gounits/gohtml) 是一个快速、安全的静态页面代理技术。自动绑定Gin框架、自动寻找路由。无须使用Nginx反向代理。支持Go1.18并且支持路径绑定和Embed嵌入打包。部署简单。

- 亮点：

1. 使用简单
2. 绑定Gin框架
3. 使用Embed绑定、部署简单
4. 自动寻找路由
5. 满足接口设计、可自定义代理方法

- 示例代码

1. 使用embed嵌入页面打包到二进制代码

```go
package main

import (
	"embed"
	"github.com/gin-gonic/gin"
	"github.com/gounits/gohtml"
)

//go:embed 前端页面的路径
var efs embed.FS

func main() {
	r := gin.Default()
	r.Use(gohtml.NewFs(efs))
	if err := r.Run(":8080"); err != nil {
		panic(err)
	}
}

```

2. 使用路径代码

```go
package main

import (
	"github.com/gin-gonic/gin"
	"github.com/gounits/gohtml"
)

func main() {
	r := gin.Default()
	r.Use(gohtml.New("前端页面路径"))
	if err := r.Run(":8080"); err != nil {
		panic(err)
	}
}

```

- 截图

![image](https://user-images.githubusercontent.com/28988355/199414188-c12a23f5-0887-4dbd-8d1b-5b7401611778.png)

![image](https://user-images.githubusercontent.com/28988355/199414206-15327647-9182-4e6b-a91e-b21195f90cde.png)

![image](https://user-images.githubusercontent.com/28988355/199414246-0ccf3f4a-4c91-42de-ac22-00e8ddc52cbe.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
