### ISSUE TITLE
【开源自荐】k8s原生的IoT平台——Shifu

### ISSUE THREAD

**Issue by saiyan86** [521xueweihan/HelloGitHub#2412]
## 推荐项目

- 项目地址：https://github.com/edgenesis/shifu

- 类别：Go

- 项目标题：k8s原生的IoT平台——Shifu

- 项目描述：Shifu是一个k8s原生的、生产级别的物联网平台。通过把IoT设备封装成k8s的pod，Shifu将设备的能力与数据以API的形式开放出来，让开发一个IoT应用都像开发一个APP一样简单。

- 亮点：Shifu已经应用在要求极高的航海、航天以及众多工业场景中，将软硬件彻底解耦，帮助IoT应用开发团队10倍提升开发效率。

- 示例代码：（可选）
- 安装（已有k8s/k3s/KubeEdge/openYurt的情况下）
`kubectl apply -f https://raw.githubusercontent.com/Edgenesis/shifu/v0.4.1/pkg/k8s/crd/install/shifu_install.yml`

- 截图：（可选）gif/png/jpg
Shifu于北京中关村的首次线下Meetup：
<img width="382" alt="image" src="https://user-images.githubusercontent.com/6934678/199454684-068707ba-469d-4c07-9348-9a98a0855313.png">

- 后续更新计划：
长期保持两周一个release，直到让开发一个IoT应用都像开发一个APP一样简单的愿景实现！

**Comment by 521xueweihan** [comment]
@saiyan86 您推荐的项目，**已成功发布**在 [HelloGitHub 第 82 期](https://hellogithub.com/periodical/volume/82)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

更多详情尽在：https://hellogithub.com/repository/c257b5be90204bf580c77de23297a7c8

最后，欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
