### ISSUE TITLE
【自荐项目】Golang 编写的配置中心

### ISSUE THREAD

**Issue by HYY-yu** [521xueweihan/HelloGitHub#2422]
## 推荐项目

- 项目地址：https://github.com/HYY-yu/Sail

- 类别：Go

- 项目标题：一款设计简单且功能齐全的配置中心。

- 项目描述：企业级配置中心，拥有配置管理、权限管控、热更新、发布管理、命名空间等强大功能。为 go 语言带来一款新的配置中心，通过源码可学习：go 模板编程、ETCD 的使用等。

- 亮点：
- - go 世界缺乏一款类似 apollo、nacos 的配置中心
- - 单二进制文件即可运行部署，依赖极少

- 后续更新计划：
- - 实现发布管理，配置灰度发布
- - 接入 Prometheus 和 Jaeger

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
