### ISSUE TITLE
【开源自荐】一个使用WinUI3开发的提取图片关键像素点生成字符艺术图像的App

### ISSUE THREAD

**Issue by ewoifuoi** [521xueweihan/HelloGitHub#2425]
## 推荐项目

- 项目地址：https://github.com/ewoifuoi/Image2ASCIIEditor

- 类别：C#

- 项目标题：一个使用WinUI3开发的提取图片关键像素点生成字符艺术图像的App

- 项目描述：
    - 终端工具开发者常常会碰到一个痛点，那就是在终端中使用字符绘制一个具有表现力的图像是一件较为困难的事情，无论是使用代码生成还是直接输入字符，都避免不了 编写代码-输出看结果-再修改 的过程， 
    - 该项目通过让用户编辑图片后**直接识别图片关键像素点**并进行**k-means聚类**，识别图片的关键结构部分，允许用户使用终端支持的字符和前景色进行替换，导入编辑界面微调后，**直接导出一段c/Shell字符图像生成代码**，或文本文件

- 亮点：
    - 使用 WinUI 3开发，主题风格现代化，内存占用小，性能大幅提升
    - 支持 Windows 原生亚克力主题背景
    - 支持用户对不满意的聚类结果在编辑界面微调，为用户快速编辑提供多种工具（如一键填充，直线工具，选择工具）
    - 支持用户改变导入图像分辨率

- 截图：

![](https://foruda.gitee.com/images/1668233043324304288/960f85e8_10544622.png "3.png")
![输入图片说明](https://foruda.gitee.com/images/1668234875507260805/256a236b_10544622.png "1.png")
![输入图片说明](https://foruda.gitee.com/images/1668234934135262955/7a0873b9_10544622.png "5.png")
![输入图片说明](https://foruda.gitee.com/images/1668235215559265312/b91c6037_10544622.png "4.png")

- 后续更新计划：
    - 支持在编辑界面设置图层,并设置图层显示优先级,允许用户创建更加复杂的场景图像
    - 支持识别视频并提取关键帧生成图像,生成代码或允许用户使用文件读写的方式创建终端字符动画
    - 增加支持显示的字符
    -支持识别关键像素点组所成图形,使用神经网络推荐当前点的最佳代替字符

**Comment by 521xueweihan** [comment]
@ewoifuoi 该项目将在网站进行收录，希望后续可以持续迭代。

Issues 就直接关闭了。

**Comment by 521xueweihan** [comment]
@ewoifuoi 您的项目已成功展示在 HelloGitHub 网站。

如果您是项目的维护者，同时项目还没有制作官网/落地页的话，可以考虑增添 HelloGitHub 项目详情页作为官网，这里汇集了项目的源码、文档、演示、下载地址等项目相关信息：
https://hellogithub.com/repository/ead6a822bd02407fa31ecf001ae3e5dd

最后，如果方便的话欢迎在项目 README 增添「HelloGitHub 徽章」展示项目获取的点赞数和评论入口，同时这也是支持 HelloGitHub 的善举。

<a href="https://hellogithub.com/repository/ead6a822bd02407fa31ecf001ae3e5dd" target="_blank"><img src="https://api.hellogithub.com/v1/widgets/featured.svg?rid=ead6a822bd02407fa31ecf001ae3e5dd" alt="Featured｜HelloGitHub" style="width: 250px; height: 54px;" width="250" height="54" /></a>
