### ISSUE TITLE
【开源自荐】 watching-you - 让你的 DOM 能够像眼睛一样关注东西的 JS 动画库

### ISSUE THREAD

**Issue by jj811208** [521xueweihan/HelloGitHub#2427]
## 推荐项目

- 项目地址：https://github.com/jj811208/watching-you

- 类别：JS

- 项目标题：让你的 DOM 能够像眼睛一样关注东西的 JS 动画库

- 项目描述：watching-you 是一个基于 DOM + JS 的简易动画库，主要用于计算一个 DOM 与 `观察目标`（滑鼠、DOM、输入框值）之间的位置资讯，从而做出一些有趣的动画，比方说让它变成跟眼睛一样👀

- 亮点：
  - 它能够观察鼠标或另一个 DOM，甚至是输入框里面的值，观察任何你想要的东西!
  - 因为它是基于 DOM，所以它很容易支持 RWD，而且上手成本很低
  - 支持多种框架
    - vanilla.js
    - react
    - vue
  - 没有任何依赖套件（每个框架都是！）。
  - 使用 TypeScript 编写
  - 核心代码的大小在 gzip 压缩后仅为 3kb
  - 如果元素不在屏幕上时，它将自动停止运行，节省资源的浪费

- 示例代码：
https://github.com/jj811208/watching-you/tree/main/packages/website

- 截图：
[登入表单](https://jj811208.github.io/watching-you/#/example/login)
![login](https://user-images.githubusercontent.com/25342059/200180898-a6b783ef-ad07-4cb8-ab07-027a1abffa7d.gif)
[John Cena 在看你](https://jj811208.github.io/watching-you/#/example/cena)
![cena](https://user-images.githubusercontent.com/25342059/200180927-829059ca-686a-4c52-8e74-99b4f7a6ae1a.gif)
[观看 SVG 元素](https://jj811208.github.io/watching-you/#/example/svg-path)
![SVG Watcher](https://user-images.githubusercontent.com/25342059/201524690-aeaaa806-24f5-49dd-baf7-89d7759f5f9b.gif)

- 后续更新计划：
1. 扩充更多可观察的 `观察目标`
因为我把 `观察目标` 设计成插件（[这部分的源代码](https://github.com/jj811208/watching-you/tree/main/packages/core/src/targetPlugin)），所以这相当容易扩充，我希望未来能让它观察网页上的一切（比方说 scroll-bar），未来也可能会把这部分 API 开放出来让使用者自己写插件（不确定有没有这个必要，可能根据后续回馈决定来做不做🤔）

2. 支持更多的框架
它负责渲染（修改 HTML）的 method 被设计成[可以客制](https://github.com/jj811208/watching-you/blob/main/packages/core/src/index.ts#L190-L199)，所以它相当容易整合其他框架（目前仅有 vue 和 react）

3. 撰写更多的范例及文档
虽然 `watching-you` 的宣传语是 `让 DOM 像眼睛一样关注任何事物`，但实际上它能做的不只如此，因为它给你两个点之间的位置和角度资讯，实际上要怎么处理它开发者可以自己决定（但这是高级用法，通常不需要额外处理这个），所以像是[这种效果](https://creepyface.io/)也相当容易做到，但它目前只有基本的文档，需要有更多的范例及文档告诉大家该如何使用它

**Comment by 521xueweihan** [comment]
@jj811208 
您推荐的项目，**已成功发布**在 [HelloGitHub 第 81 期](https://hellogithub.com/periodical/volume/81)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
