### ISSUE TITLE
Halo-可能是最好的Java博客系统😉

### ISSUE THREAD

**Issue by ruibaby** [521xueweihan/HelloGitHub#243]
## 项目推荐
- 项目名称：Halo

- 项目地址：https://github.com/ruibaby/halo

- 项目语言：Java

- 项目描述：Halo可能是最好的Java博客系统😉

- 推荐理由：易用，部署方便，功能强大，不臃肿，单纯的博客系统，非cms

- 示例代码：SpringApplication.run(Application.class, args);

- 截图：https://github.com/ruibaby/halo/blob/master/PREVIEW.md

**Comment by 521xueweihan** [comment]
@ruibaby 已推荐过类似项目，期待推荐其他更多有意思的项目
