### ISSUE TITLE
推荐项目：Layui

### ISSUE THREAD

**Issue by XYZscratcher** [521xueweihan/HelloGitHub#2431]
## 推荐项目

- 项目地址：https://github.com/layui/layui

- 类别：CSS/JS

- 项目标题：一套遵循原生态开发模式的 Web UI 组件库

- 项目描述：一套遵循原生态开发模式的 Web UI 组件库，采用自身轻量级模块化规范，易上手，可以更简单快速地构建网页界面。

- 亮点：
  - 风格简约
  - 兼容性强
  - 文档齐全

- 示例代码：（可选）
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>开始使用 Layui</title>
    <link href="./layui/css/layui.css" rel="stylesheet">
  </head>
  <body>
    <!-- HTML -->
     
    <script src="./layui/layui.js"></script>
    <script>
    // 使用组件
    layui.use(['layer', 'form'], function(){
      var layer = layui.layer;
      var form = layui.form;
      
      // 欢迎语
      layer.msg('Hello World');
    });
    </script> 
  </body>
</html>
```
- 截图：（可选）gif/png/jpg

- 后续更新计划：

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 88 期](https://hellogithub.com/periodical/volume/88)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

最后，欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
