### ISSUE TITLE
【开源自荐】 用于抵御 DDOS 攻击的 Linux 防火墙 CFW

### ISSUE THREAD

**Issue by Cyberbolt** [521xueweihan/HelloGitHub#2433]
项目地址：https://github.com/Cyberbolt/cfw

类别：Python

项目描述：

CFW (Cyber Firewall) 是一个人性化的 Linux 防火墙。它旨在协助阻止拒绝服务攻击 (DDOS)，同时能控制 Linux 系统端口的开关。由于基于 Linux 原生运行，CFW 拥有良好的软件兼容性。
该软件基于 iptables 和 ipset，使用 Python 开发，使用时建议关闭发行版自带的防火墙 (如 firewalld、ufw) 避免冲突。

亮点：

- 通过自定义的规则自动封禁互联网中的恶意 ip，以防止拒绝服务攻击

- 保护 Linux 的所有端口遭受 DDOS 攻击，而不仅仅是 Web 应用

- 获得良好的软件兼容性，原生支持 Nginx、Caddy 等服务器

- 支持配合 CDN 使用，使用 CDN 时请将 CDN 的 ip 段设置为 CFW 白名单

- 控制开启或关闭 Linux 系统的 TCP/UDP 端口

- 获得友好的命令行交互式体验

后续更新计划：长期更新

背景：

Web 应用程序运行在复杂的互联网中，随时可能面临恶意攻击，导致拒绝服务现象。封禁这些不友好的 ip，CFW 正是为此而诞生。

CFW 的灵感最初来自宝塔面板的 Nginx 防火墙。然而，使用 Nginx 防火墙的过程中遇到诸多不顺。该防火墙仅针对 Web 应用 (通常是 80 和 443 端口) 防御 CC 攻击，无法保护 Linux 服务器的其他端口。同时，该防火墙需要按月付费，并始终捆绑宝塔生态 (最新的宝塔面板甚至需要登录绑定手机实名制的账号)，从而限制了软件自由度。我们想在纯净的 Linux 中运行防火墙，并对所有端口生效，于是自己开发了一个。

由于 CFW 基于 iptables 和 ipset，不免会与发行版自带的防火墙 (如 firewalld、ufw) 冲突，我们增加了 CFW 对端口开关的控制。

**Comment by 521xueweihan** [comment]
请按照要求提交项目信息。
