### ISSUE TITLE
【开源自荐】xfrpc -- FRP(fast reverse proxy)项目的c语言客户端

### ISSUE THREAD

**Issue by liudf0716** [521xueweihan/HelloGitHub#2435]
## 项目推荐
- 项目地址：[xfrpc](https://github.com/liudf0716/xfrpc)

- 类别：c

- 项目后续更新计划：兼容frp项目的服务端frps，持续更新

- 项目描述：
  当我们想通过公网访问自己局域网内的服务时，通常可通过如下方式来实现：
  + 通过防火墙或者路由器提供的端口映射的功能，将局域网内部服务映射出去，如果要提供公网访问的能力，需要防火墙或者路由器的wan口有公网IP；
  + 使用花生壳类似的收费服务，通过第3方提供的中转服务，将局域网内部服务映射到公网访问；
  + 使用开源代码如frp搭建自己的中转服务，将局域网内部服务映射到公网访问；
  
  frp 是一个专注于内网穿透的高性能的反向代理应用，其支持TCP、UDP、HTTP、HTTPS 等多种协议，理论上可以开放任何想要的端口。frp可以将内部局域网服务以安全、便捷的方式通过具有公网 IP 节点的中转暴露到公网上让用户访问。frp由golang语言实现，其由服务器端的frps及客户端frpc组成，其中frps部署到具有公网IP的服务器上，一般部署在云端的vps上；客户端frpc部署到内网的网关设备上或者内部能PC上，该PC只要能访问需要暴露出去的内部局域网服务即可；xfrpc是frp项目的c语言实现客户端，其能完美兼容frp的服务端应用，在特殊场景下能起到代替frpc的作用。

**Comment by 521xueweihan** [comment]
请按照要求提交项目信息。
