### ISSUE TITLE
【开源自荐】文本盲水印：把一段隐密信息嵌入到文本中

### ISSUE THREAD

**Issue by guofei9987** [521xueweihan/HelloGitHub#2437]
## 推荐项目

- 项目地址：https://github.com/guofei9987/text_blind_watermark

- 类别：Python

- 项目标题：文本盲水印，把一段隐密信息嵌入到文本中

- 项目描述：此项目用来把一段信息嵌入到一段明文中，使信息隐密不可见，并且旁人无法察觉到嵌入后明文的变化。
    - 使用场景：版权保护、数据安全、数据泄漏溯源、信息隐秘传输
    - 经测试，在很多场景下运行良好：1）MacBook 的 Chrome 浏览器，包括知乎网页版、微博网页版等大多数网站。2）微信、钉钉的MacBook/iPhone 版本。 3）更多场景，详见文档

- 亮点：同类别开源/闭源算法主要两类，1）用微小的格式（如字体、字间距、行间距）变化来嵌入信息，缺点是复制黏贴、或者全选更改格式后，盲水印消失。2）更改词语风格以嵌入二进制信息，缺点是要求明文是一段较长并有语义的文章，并且嵌入盲水印后明文显著变化。本项目克服了以上缺点，可以抵抗任何格式攻击，并且明文在嵌入前后不会改变。

- 示例代码：（可选）

如何嵌入水印：
```python
from text_blind_watermark import TextBlindWatermarkThin

password = '20190808'
watermark = 'github.com/guofei9987'
text_blind_wm = TextBlindWatermarkThin(password=password)

wm = text_blind_wm.embed(watermark=watermark)
text_embed = '这句话中有盲' + wm + '水印，你能提取出来吗？'
print(text_embed)
```

如何提取水印
```python
text_blind_wm_new = TextBlindWatermarkThin(password=password)
wm_extract = text_blind_wm_new.extract(text_embed)
print('提取内容：', wm_extract)
```

- 截图：（可选）gif/png/jpg

运行结果：
<img width="279" alt="image" src="https://user-images.githubusercontent.com/19920283/203133578-56037153-aab9-4581-8399-09092658ea54.png">

额外有个 html 版可供在线/离线使用 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/19920283/203135557-8da0a15f-977f-4e57-9448-6b00f7287ef9.png">

介绍视频：https://www.bilibili.com/video/BV1m3411s7kT/

- 后续更新计划：此项目在某些软件上还不能很有效的隐藏，例如知乎app（但app上的回复可以）、GitHub的md文件（但是GitHub的代码文件和文本文件是可以的），后续更新中，会追求在更多软件上能够完美的隐藏信息。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 94 期](https://hellogithub.com/periodical/volume/94)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
