### ISSUE TITLE
用于抵御 DDOS 攻击的 Linux 防火墙 CFW

### ISSUE THREAD

**Issue by Potato-OvO** [521xueweihan/HelloGitHub#2439]
## 自荐项目

- 项目地址：https://github.com/Cyberbolt/cfw

- 类别：Python

- 项目标题：用于抵御 DDOS 攻击的 Linux 防火墙 CFW

- 项目描述：CFW (Cyber Firewall) 是一个人性化的 Linux 防火墙。它旨在协助阻止拒绝服务攻击 (DDOS)，同时能控制 Linux 系统端口的开关。由于基于 Linux 原生运行，CFW 拥有良好的软件兼容性。该软件基于 iptables 和 ipset，使用 Python 开发，使用时建议关闭发行版自带的防火墙 (如 firewalld、ufw) 避免冲突。

- 亮点：
  
  - 通过自定义的规则自动封禁互联网中的恶意 ip，以防止拒绝服务攻击

  - 保护 Linux 的所有端口遭受 DDOS 攻击，而不仅仅是 Web 应用

  - 获得良好的软件兼容性，原生支持 Nginx、Caddy 等服务器

  - 支持配合 CDN 使用，使用 CDN 时请将 CDN 的 ip 段设置为 CFW 白名单

  - 控制开启或关闭 Linux 系统的 TCP/UDP 端口

  - 获得友好的命令行交互式体验

- 后续更新计划：长期更新

**Comment by 521xueweihan** [comment]
@Potato-OvO 您好，月刊已收录类似的开源项目，贵项目暂不收录到月刊。
