### ISSUE TITLE
Day.js

### ISSUE THREAD

**Issue by zazzaz** [521xueweihan/HelloGitHub#244]
最近社区很火的小而美的库，Day.js 国人出品2KB时间日期库，10000+star，Moment.js 的轻量化方案，拥有同样强大的 API 
## 项目推荐
- 项目名称：Day.js

- 项目地址：https://github.com/xx45/dayjs

- 项目语言：Javascript

- 项目描述：Day.js 是一个轻量的 JavaScript 时间日期处理库，和 Moment.js 的 API 设计保持完全一样. 如果你曾经用过 Moment.js, 那么你已经知道如何使用 Day.js

- 推荐理由：2KB大小，和Moment.js 相同的 API 和用法， Immutable， Chainable；

- 示例代码：`dayjs().startOf('month').add(1, 'day').set('year', 2018).format('YYYY-MM-DD HH:mm:ss');`

- 截图：https://user-images.githubusercontent.com/17680888/39081119-3057bbe2-456e-11e8-862c-646133ad4b43.png

**Comment by 521xueweihan** [comment]
@zazzaz   您推荐的项目，已成功收录在 [HelloGitHub 第 26 期](https://hellogithub.com/periodical/volume/26/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
