### ISSUE TITLE
Heimdall - 一款Go开发的命令行下 MySQL 数据库导入导出工具

### ISSUE THREAD

**Issue by mylxsw** [521xueweihan/HelloGitHub#2440]
## 推荐项目

- 项目地址：https://github.com/mylxsw/heimdall

- 类别：Go

- 项目标题：Heimdall - 一款命令行下的 MySQL 数据库导入导出工具

- 项目描述：[Heimdall](https://github.com/mylxsw/heimdall) 是一款专门为 MySQL 设计的命令行导入导出工具，使用它，你可以通过写 SQL 的方式，将查询结果直接导出 xlsx、csv、markdown、html、json、yaml、xml、sql 等格式的文件，也可以将 xlsx 和 csv 格式的文件导入到数据库表中。

- 亮点：将 SQL 执行结果直接输出为 xlsx、csv、markdown、html、json、yaml、xml、sql  等格式的文件或者到标准输出。

- 示例代码：

```bash
heimdall export --database example --host 127.0.0.1 --user root --password root \
      --sql "SELECT id, name AS '企业名称', address AS '企业地址', city_name AS '城市', district_name AS '区县', DATE_FORMAT(created_at, '%Y-%m-%d %H:%i:%s') AS '创建时间' FROM enterprise WHERE created_at > DATE_SUB(NOW(), INTERVAL 30 DAY) ORDER BY id DESC" \
      --streaming \
      --format xlsx \
      --output 最近30天新增企业列表.xlsx
```

- 后续更新计划：12月将会增加对 Binlog 订阅的支持，实现数据库之间的实时同步。

**Comment by 521xueweihan** [comment]
看到项目已停更，issues 将被关闭。
