### ISSUE TITLE
【开源书籍】The Art of Linear Algebra 线性代数的艺术 最新中文版

### ISSUE THREAD

**Issue by kf-liu** [521xueweihan/HelloGitHub#2444]
## 推荐项目

- 项目地址：https://github.com/kf-liu/The-Art-of-Linear-Algebra-zh-CN

- 类别：书籍

- 项目标题：The Art of Linear Algebra 线性代数的艺术 最新中文版

- 项目描述：最新翻译的3k+Star的开源书籍The Art of Linear Algebra，用可视化的、图形化的方式理解和学习线性代数。

- 亮点：图形化理解矩阵！一张图概括线代！MIT教授作的序！

- 示例代码：（可选）一篇超短的[推荐文章](https://github.com/kf-liu/frontend/blob/master/books/The-Art-of-Linear-Algebra.md)可供参考

- 截图：（可选）gif/png/jpg

- 后续更新计划：跟随原著更新

**Comment by 521xueweihan** [comment]
已推荐过原项目，翻译的项目不做重复推荐了。

**Comment by kf-liu** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的邮件我已收到，谢谢！

**Comment by kf-liu** [comment]
好的，谢谢
