### ISSUE TITLE
开源自荐：SmartPET-Feeder

### ISSUE THREAD

**Issue by smart2pet** [521xueweihan/HelloGitHub#2447]
## 推荐项目

- 项目地址：https://github.com/smart2pet/SmartPET-Feeder

- 类别：Python和Arduino C

- 项目标题：SmartPET 自动喂食机

- 项目描述：可以自动喂食，解决了宠物喂食问题

- 亮点：准确，精度高于市面普通自动喂食机(Precise)、操作简单(Easy)、准时（Time-based）；离线可出粮；
普通自动喂食机利用重量传感器，会造成约±5g偏差。但此项目使用回归算法，实际测试证明算法使偏差普遍低于±2g。
- 示例代码：（可选）

- 截图：（可选）gif/png/jpg

- 后续更新计划：提供major、minor、patch更新，提供新功能。

- 注：未尽事宜，参见项目README。

**Comment by smart2pet** [comment]
项目已重构，请查看。

**Comment by smart2pet** [comment]
包含C语言

**Comment by smart2pet** [comment]
@521xueweihan 项目已重构，请查看。包含Arduino C 语言。

**Comment by smart2pet** [comment]
@521xueweihan Are you still looking at this project?

**Comment by smart2pet** [comment]
@521xueweihan Come here please.

**Comment by smart2pet** [comment]
@521xueweihan Please look at this project. Thanks.

**Comment by smart2pet** [comment]
Please, look at this project. @521xueweihan

**Comment by smart2pet** [comment]
@521xueweihan

**Comment by 521xueweihan** [comment]
@smart2pet 项目描述还需要优化，建议按照下面的方向进行优化：
1. 丰富项目描述
2. 添加效果图、实物图
3. 如何证明：准确，精度高于市面普通自动喂食机
