### ISSUE TITLE
C++项目：MyTinySTL

### ISSUE THREAD

**Issue by Alinshans** [521xueweihan/HelloGitHub#245]
## 项目推荐
- 项目名称：MyTinySTL

- 项目地址：https://github.com/Alinshans/MyTinySTL

- 项目语言：C++

- 项目描述：用C++11实现自己的小型STL（容器库+算法库）

- 推荐理由：代码结构清晰规范，中文文档与注释，并且自带一个简单的测试框架，适合新手学习与参考

- 示例代码：
```c++
// 在尾部插入元素
template <class T>
void vector<T>::push_back(const value_type& value)
{
  if (end_ != cap_)
  {
    data_allocator::construct(mystl::address_of(*end_), value);
    ++end_;
  }
  else
  {
    reallocate_insert(end_, value);
  }
}
```

**Comment by 521xueweihan** [comment]
@Alinshans 您推荐的项目，已成功收录在 [HelloGitHub 第 27 期](https://hellogithub.com/periodical/volume/27/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
