### ISSUE TITLE
【开源自荐】FileCodeBox：匿名口令分享文本，文件

### ISSUE THREAD

**Issue by vastsa** [521xueweihan/HelloGitHub#2450]
## 推荐项目

- 项目地址：https://github.com/vastsa/FileCodeBox

- 类别：Python

- 项目标题：文件快递柜-匿名口令分享文本，文件，像拿快递一样取文件

- 项目描述：很多时候，我们都想将一些文件或文本传送给别人，或者跨端传递一些信息，但是我们又不想为了分享，而去下载一些七里八里端软件，这时候，我们就可以使用口令传送箱。

- 亮点：
- [x] 轻量简洁，Fastapi+sqlite3
- [x] 拖拽，复制粘贴上传
- [x] 文件口令传输，生成二维码
- [x] 分享文件：多种上传方式供你选择
- [x] 分享文本：直接复制粘贴直接上传
- [x] 防爆破：错误五次拉黑十分钟
- [x] 完全匿名：不记录任何信息
- [x] 无需注册：无需注册，无需登录
- [x] Sqlite3数据库：无需安装数据库
- [x] 可以加get参数code，这样打开就会读取取件码如：http://xxx.com?code=12345
- [x] 管理面板：简单列表页删除违规文件
- [x] 口令使用次数，口令有效期，二维码分享

- 截图：

1.  取件

![取件](https://raw.githubusercontent.com/vastsa/FileCodeBox/master/images/img.png)
![取件](https://raw.githubusercontent.com/vastsa/FileCodeBox/master/images/img_1.png)

2. 寄件

![取件](https://raw.githubusercontent.com/vastsa/FileCodeBox/master/images/img_2.png)
![取件](https://raw.githubusercontent.com/vastsa/FileCodeBox/master/images/img_3.png)

3. 管理面板

![取件](https://raw.githubusercontent.com/vastsa/FileCodeBox/master/images/img_4.png)
![取件](https://raw.githubusercontent.com/vastsa/FileCodeBox/master/images/img_5.png)

- 后续更新计划：
- [ ] 接入其他存储

- 部署文档：
https://www.yuque.com/lxyo/work/zd0kvzy7fofx6w7v

**Comment by 521xueweihan** [comment]
@vastsa 
您推荐的项目，**已成功发布**在 [HelloGitHub 第 81 期](https://hellogithub.com/periodical/volume/81)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
