### ISSUE TITLE
【开源推荐】Golang 语言的行为式验证码

### ISSUE THREAD

**Issue by wenlng** [521xueweihan/HelloGitHub#2456]
## 推荐项目

- 项目地址：https://github.com/wenlng/go-captcha

- 类别：Go

- 项目标题：Golang 语言的行为式验证码

- 项目描述：go-captcha, 一个简洁易用、交互友好、高安全性的"行为式验证码" Go库 ，采用 “验证码展示-采集用户行为-验证行为数据” 为流程，用户无需键盘手动输入，极大优化传统验证码用户体验不佳的问题，支持PC端及移动端，支持前端Vue、React...等项目。

- 亮点：行为式验证码、点选式验证码、高安全性、防机器破解

- 示例代码：
## 安装模块
```shell
$ go get -u github.com/wenlng/go-captcha/captcha
```

## 引入模块
```go
package main

import "github.com/wenlng/go-captcha/captcha"

func main(){
   // ....
}
```

## 快速使用
```go
package main
import (
    "fmt"
    "github.com/wenlng/go-captcha/captcha"
)

func main(){
    // Captcha Single Instances
    capt := captcha.GetCaptcha()

    // 生成验证码
    dots, b64, tb64, key, err := capt.Generate()
    if err != nil {
        panic(err)
        return
    }
    
    // 主图base64
    fmt.Println(len(b64))
    
    // 缩略图base64
    fmt.Println(len(tb64))
    
    // 唯一key
    fmt.Println(key)
    
    // 文本位置验证数据
    fmt.Println(dots)
}

```

- 截图：
<img src="http://47.104.180.148/go-captcha/go-captcha.jpg?v=9"/>

- 后续更新计划：
计划加入滑动式验证、旋转式验证、图标式点选验证、预置 Androind、IOS、Uniapp、小程序、Flutter 等前端或客户端实例

**Comment by 521xueweihan** [comment]
@wenlng  您推荐的项目，**已成功发布**在 [HelloGitHub 第 85 期](https://hellogithub.com/periodical/volume/85)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
