### ISSUE TITLE
【开源自荐】 🐇年春节全屏动画效果

### ISSUE THREAD

**Issue by xiaoli1999** [521xueweihan/HelloGitHub#2465]
## 推荐项目

- 项目地址：[🐇年春节全屏动画效果](https://github.com/xiaoli1999/fullScreen-animation)

- 类别：css、js

- 项目标题：🐇兔年春节全屏动画效果，css、js动画。

- 项目描述：这是一个全屏动画效果，可以应用到任何网站。用户上手快，可实现快速集成全屏动画，用于新年、春节、圣诞节等场景。

- 亮点：轻量、灵活、高定制化的全屏动画效果。

- 截图：
![效果](https://github.com/xiaoli1999/fullScreen-animation/raw/master/img/effect.gif)

![效果](https://github.com/xiaoli1999/fullScreen-animation/raw/master/img/effect.png)

后续更新计划：
- 修复项目问题
- 根据用户意见、建议优化完善项目

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
