### ISSUE TITLE
【开源自荐】影视自动更新及在线观看

### ISSUE THREAD

**Issue by Bssn520** [521xueweihan/HelloGitHub#2467]
## 推荐项目

- 项目地址：https://github.com/Bssn520/AnimationAutoUpdate

- 类别：其它

- 项目标题：影视自动更新及在线观看

- 项目描述：基于Alist项目和影视更新文档，通过阿里云盘官方接口实现动漫、电视剧、电影等的自动更新及在线观看。

- 亮点：
1. 不占用本地带宽，播放非常流畅。
2. 清晰度非常高，且网页端支持原画质播放。
3. 支持Webdav挂载，配合Infuse等软件使用，体验非常好。
4. ......

- 截图：
![image](https://cdn.staticaly.com/gh/Bssn520/Images@master/Test/image.2ly5mw6wm460.webp)

- 后续更新计划：
![image](https://cdn.staticaly.com/gh/Bssn520/Images@master/Test/image.4d3vxzp1us80.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
