### ISSUE TITLE
【自荐项目】 - Smalltalk

### ISSUE THREAD

**Issue by m0ver** [521xueweihan/HelloGitHub#2468]
## 推荐项目

- 项目地址：
https://github.com/tinystruct/smalltalk

- 类别：
Java

- 项目标题：
Smalltalk

- 项目描述：
smalltalk是基于@tinystruct框架的一个示例项目，它支持C/S应用程序和B/S Web应用程序的开发。它允许您通过命令行界面（CLI）或Web界面与OpenAI开发的ChatGPT语言模型进行交互。

- 亮点：
它允许您通过命令行界面（CLI）或Web界面与OpenAI开发的ChatGPT语言模型进行交互。
- 示例代码：（可选）

- 截图：（可选）gif/png/jpg
<img src="https://raw.githubusercontent.com/tinystruct/smalltalk/master/screenshot.png" />
- 后续更新计划：
持续更新...

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
