### ISSUE TITLE
text2art:生成可控终端艺术字体

### ISSUE THREAD

**Issue by Fenghuapiao** [521xueweihan/HelloGitHub#247]
## 项目推荐
- 项目名称：text2art

- 项目地址：https://github.com/Fenghuapiao/text2art

- 项目语言：python

- 项目描述：在终端生成特定效果的艺术字体。

- 推荐理由：直接pip install text2art即可使用。

- 示例代码：无

- 截图：
![1](https://user-images.githubusercontent.com/17211003/39526247-cc87f014-4e50-11e8-99b7-89c9bf38e890.png)
![2](https://user-images.githubusercontent.com/17211003/39526392-3204bf80-4e51-11e8-88d2-6d4ba67fb20d.png)

**Comment by 521xueweihan** [comment]
@Fenghuapiao 未能收录到 HelloGitHub 月刊中，期待持续优化或推荐更多有意思的项目
