### ISSUE TITLE
【开源自荐】 mongo-plus

### ISSUE THREAD

**Issue by here-Leslie-Lau** [521xueweihan/HelloGitHub#2472]
## 推荐项目

- 项目地址：
[mongo-plus](https://github.com/here-Leslie-Lau/mongo-plus)

- 类别：
Go

- 项目标题：
mongo-plus

- 项目描述：
基于mongo go官方驱动的二次封装，以调用链的形式操作mongodb，屏蔽了mongodb的一些复杂性，达到开箱即用。

- 亮点：
简单的方法调用
常见方法都经过benchmark测试，性能与官方相同
以调用链的形式操作mongodb，屏蔽了mongodb的一些复杂性，达到开箱即用
等等

- 示例代码：（可选）
https://github.com/here-Leslie-Lau/mongo-plus/blob/master/test/chain_test.go

- 截图：（可选）gif/png/jpg
![image](https://user-images.githubusercontent.com/32758741/212810091-e845550b-746f-4f08-ad0c-8506c74de9d7.png)

- 后续更新计划：
持续更新ing，[版本管理计划here](https://github.com/here-Leslie-Lau/mongo-plus#%E7%89%88%E6%9C%AC%E7%AE%A1%E7%90%86)

**Comment by 521xueweihan** [comment]
@here-Leslie-Lau 非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
