### ISSUE TITLE
【开源项目推荐】| Antlr4 使用Java编写的语法分析库

### ISSUE THREAD

**Issue by XZirui** [521xueweihan/HelloGitHub#2484]
## 推荐项目

- 项目地址：https://github.com/antlr/antlr4 （官网 http://antlr.org/）

- 类别：Java

- 项目标题：Antlr是一个强大的语法分析器生成工具，可以通过特定的语法分析文本（或者做编译器前端） 

- 项目描述：可以通过简洁的antlr语法构造一个词法分析器和语法分析器，通过访问者模式和监听者模式实现了逻辑代码和匹配语法分离（可以生成10种目标语言 Java/C++/Python等等） 适用于各种字符串、文本解析, 如配置文件读取器、遗留代码转换器、json解析器、编译器前端语法树生成等 

- 亮点：可以直接处理语法文件的左递归，无需为了工具而改变语法。将内嵌语义动作和语法文件分离（一份文件可以生成多种语言目标 无需更改内嵌动作） 拥有出色的错误回溯和错误报告

- 示例代码：
```antlr
grammar Expr;
prog:   (expr NEWLINE)* ;
expr:   expr ('*'|'/') expr
    |   expr ('+'|'-') expr
    |   INT
    |   '(' expr ')'
    ;
NEWLINE : [\r\n]+ ;
INT     : [0-9]+ ;
```

- 截图：![image](https://user-images.githubusercontent.com/48241049/216214058-09dc9f16-59f5-4866-8087-d4eb2905eac6.png)

- 后续更新计划：(作者应该不会弃坑）

**Comment by XZirui** [comment]
PS：贡献者xuzirui20080129应更新为XZirui

**Comment by XZirui** [comment]
![image](https://user-images.githubusercontent.com/48241049/216214779-9840ddb1-0531-49bd-98cc-3521b76449b1.png)

**Comment by XZirui** [comment]
点错了 抱歉 下面是更新贡献者的证明![image](https://user-images.githubusercontent.com/48241049/216214909-8ab42c37-3c06-47d6-8172-c523b9e3c719.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 88 期](https://hellogithub.com/periodical/volume/88)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

最后，欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
