### ISSUE TITLE
【开源项目推荐】KDE Connect：所有设备间互联

### ISSUE THREAD

**Issue by lihz1990** [521xueweihan/HelloGitHub#2485]
## 推荐项目
 
- 项目地址：https://github.com/KDE/kdeconnect-kde

- 类别：其它

- 项目标题：支持所有平台间的文件、信息、通知等功能

- 项目描述：

实现局域网内全平台PC（Linux、Windows、macOS）、移动（安卓、iOS）设备间的通信和远程控制。功能包括：

    - 文件、链接和剪贴板共享
    - 通知提醒
    - 多媒体和PPT播放控制
    - 手机来电通知
    - 短信收发
    - 查找手机
    - 远程键盘
    - 手机文件系统挂载
    - 自定义命令执行

- 亮点：
  - 实现多设备互联
  - 全平台支持
  - 功能丰富，可以满足日常多样化需求

- 截图：
![image](https://user-images.githubusercontent.com/5841740/216228420-e0341b20-b2d8-4ee5-b375-4d15b326e439.png)
![1675317273240](https://user-images.githubusercontent.com/5841740/216243495-1902efbc-bc4e-4c8f-947b-eb9d0db32567.jpg)

- 后续更新计划：

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 86 期](https://hellogithub.com/periodical/volume/86)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
