### ISSUE TITLE
【开源自荐】PocketPy：C++17实现的轻量级Python解释器

### ISSUE THREAD

**Issue by blueloveTH** [521xueweihan/HelloGitHub#2486]
## 推荐项目

- 项目地址：https://github.com/blueloveTH/pocketpy

- 类别：C++、Python

- 项目标题：PocketPy：C++17实现的轻量级Python解释器

- 项目描述：PocketPy是一个轻量级的Python解释器，为嵌入至游戏引擎而设计。它包含一个编译器和基于字节码的虚拟机，以及交互式命令窗的实现。所有功能均集成在单个头文件`pocketpy.h`中，不包含外部依赖项，能很方便地嵌入至你的应用。此外，它还提供了Unity引擎插件和Flutter插件。

- 亮点：PocketPy是**单个头文件**的库，体积小巧，方便嵌入至应用。

#### C
```c
#include "pocketpy.h"

int main(){
    // 创建一个虚拟机
    VM* vm = pkpy_new_vm(true);
    
    // Hello world!
    pkpy_vm_exec(vm, "print('Hello world!')");

    // 构建一个列表
    pkpy_vm_exec(vm, "a = [1, 2, 3]");

    // 对列表进行求和
    char* result = pkpy_vm_eval(vm, "sum(a)");
    printf("%s", result);   // 6

    // 释放资源
    pkpy_delete(result);
    pkpy_delete(vm);
    return 0;
}
```

#### C++
```cpp
#include "pocketpy.h"

int main(){
    auto vm = pkpy::make_shared<VM>(true);
    vm->exec("print('Hello world!')", "main.py", EXEC_MODE);
    vm->exec("a = [1, 2, 3]", "main.py", EXEC_MODE);
    PyVar result = vm->exec("sum(a)", "<eval>", EVAL_MODE);
    std::cout << vm->PyInt_AS_C(result);   // 6
    return 0;
}
```

## 支持的语法特性

| 特性         | 示例                            | 支持 |
| ------------ | ------------------------------- | ---- |
| 分支         | `if..else..elif`                | YES  |
| 循环         | `for/while/break/continue`      | YES  |
| 函数         | `def f(x,*args,y=1):`           | YES  |
| 类与继承     | `class A(B):`                   | YES  |
| 列表         | `[1, 2, 'a']`                   | YES  |
| 列表生成式   | `[i for i in range(5)]`         | YES  |
| 切片         | `a[1:2], a[:2], a[1:]`          | YES  |
| 元组         | `(1, 2, 'a')`                   | YES  |
| 字典         | `{'a': 1, 'b': 2}`              | YES  |
| 格式化字符串 | `f'value is {x}'`               | YES  |
| 序列解包     | `a, b = 1, 2`                   | YES  |
| 异常         | `raise/try..catch`              | YES  |
| 动态分发     | `eval()/exec()`                 | YES  |
| 反射         | `hasattr()/getattr()/setattr()` | YES  |
| 导入模块     | `import/from..import`           | YES  |
| 上下文管理器 | `with <expr> as <id>:`          | YES  |
| 类型标注     | `def  f(a: int, b : float = 1)` | YES  |

- 后续更新计划：计划实现asyncio模块，提供协程支持。计划实现闭包/装饰器。完善C++ APIs文档。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 83 期](https://hellogithub.com/periodical/volume/83)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

最后，欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

**Comment by blueloveTH** [comment]
感谢~
