### ISSUE TITLE
以最简洁的 Api 让 Retrofit 同时支持多个 BaseUrl 以及动态改变 BaseUrl.

### ISSUE THREAD

**Issue by JessYanCoding** [521xueweihan/HelloGitHub#249]
## 项目推荐
- 项目名称：RetrofitUrlManager 

- 项目地址：https://github.com/JessYanCoding/RetrofitUrlManager

- 项目语言：java

- 项目描述：以最简洁的 Api 让 Retrofit 同时支持多个 BaseUrl 以及动态改变 BaseUrl.

- 推荐理由:  市面上较完善的一个解决方案，曾被 Gank，Android 开发技术周报推荐

## 项目一览：
![](https://raw.githubusercontent.com/JessYanCoding/RetrofitUrlManager/master/art/overview.gif)

**Comment by 521xueweihan** [comment]
@JessYanCoding 您推荐的项目，已成功收录在 [HelloGitHub 第 27 期](https://hellogithub.com/periodical/volume/27/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
