### ISSUE TITLE
能否把项目按照语言归类？

### ISSUE THREAD

**Issue by medmin** [521xueweihan/HelloGitHub#25]
主要是便于查找

语言的排序可以按照字母表顺序
比如C语言放在最前面，然后是D语言，然后是Erlang，然后是F#，然后是Go，然后是。。。。。。

我就是举个例子，
如果某语言这一期没有好项目，那就略过。

**Comment by jp1017** [comment]
@521xueweihan 感觉就是把 https://github.com/521xueweihan/HelloGitHub/tree/dev 这个分支填满，是这样吗？ @medmin

**Comment by medmin** [comment]
我是说，这不是已经12期了么，每一期的项目，排列顺序似乎是无序的，我建议按照语言的顺序来排序。That's all.

**Comment by medmin** [comment]
比如，第12期，项目1是Python项目，项目9 是C#项目，项目10是Android项目，项目11是C语言项目，所以，我建议，能否把这个项目10放在第1位，然后是项目11，因为这是C项目。

排列有序一点，好找一些。

仅此而已。

**Comment by 521xueweihan** [comment]
@medmin 
感谢提供建设性意见。

我认为这个建议的目的是为了：通过分类名有序性，提高阅读月刊的效率。

@jp1017 
关于提高月刊的阅读效率，我提供了两种思路：
1. 目录
2. 折叠 #11 

我不是很提倡 排序性和提高阅读效率，出于以下几点：
1. 分类名排序是根据：字母、语言流行度、本期内容该分类丰富程度，那种排序方式，我还没有想好（欢迎提供建议）。
2. 通篇的阅读，也有助于开阔视野，更好的拓展兴趣，发现更多有意思的领域。

以上为本人个人观点，欢迎讨论。

**Comment by clayclayclay** [comment]
可以把每个项目归纳到相应的语言标签下，这样看起来会比较有条例，而且对于有些人来说，他并不想通篇全读，只想找一下自己感兴趣的语言项目。

**Comment by medmin** [comment]
对啊，比如我只想看PHP和Python的项目，然后我还要一个个项目找下来才可以发现哪些是PHP和Python的，为何不按照语言排序，然后我就直接忽略其他项目了呢。

只是把项目按照语言首字母顺序排序而已，捎带手的事而已。

这么简单的一个事还要投票。。。。

**Comment by jp1017** [comment]
@medmin 你说的是每期还是这个库？每期就是按照语言来的

**Comment by jp1017** [comment]
@521xueweihan 新建个qq群吧 :smile:

**Comment by medmin** [comment]
我说的是每一期，就是排列的时候，按照字母顺序排列，不要再这样杂乱无章。仅此而已。

**Comment by jp1017** [comment]
> 我说的是每一期，就是排列的时候，按照字母顺序排列

这个蛮好的 :smile: :+1:

**Comment by clayclayclay** [comment]
坐等 @521xueweihan 回复~_

**Comment by 521xueweihan** [comment]
@jp1017 
@medmin 
@clayclayclay 

按字母排序、折叠，将会在最近（3 天内）完成，更新完成会在本 issue 中告知，💪 😃 ✌️

**Comment by 521xueweihan** [comment]
@jp1017 
@medmin 
@clayclayclay 

a7b7d7cede97a5616ef630d6be088f4c85e6f334

本次更新，完成了：
1. 按照分类折叠
2. 分类以首字母顺序排序

**Comment by jp1017** [comment]
效率好高 :+1: @521xueweihan

**Comment by yu-liang-zheng** [comment]
嗯嗯，作者效率很高。可是折叠之后，浏览起来不方便啊。能不能默认不折叠，每种语言都点一下，烦死了。
