### ISSUE TITLE
【开源自荐】轻快图床：基于Koa2 + Vue3.x + Vite3.x + typescript开发的轻量级快捷图片管理系统、图床系统

### ISSUE THREAD

**Issue by it-chenliang** [521xueweihan/HelloGitHub#2504]
- 项目名称：轻快图床
基于Koa2 + Vue3.x + Vite3.x + typescript开发的轻量级快捷图片管理系统、图床系统

如果大家觉得本项目不错的话，**还望点个star**，让我们共同进步！！！！
- 项目地址：
  - 仓库地址
    - github仓库地址：https://github.com/ischenliang/quickly-picture-bed
    - gitee仓库地址：https://gitee.com/itchenliang/quickly-picture-bed
  - 演示地址：[http://picture.itchenliang.club/#/](http://picture.itchenliang.club/#/)
  账号：guest@163.com
  密码：000000

- 项目简介 (**100** 字以内)：
程序员日常就是写博客，当然写博客时就会涉及到在博文中插入图片，所以往往会使用图床来进行图片资源管理，市面上较流行的图床系统是`PicGo`，是使用`electron-vue`开发的桌面应用程序，每次换电脑或者重装系统后都需要重新下载安装并配置图床，比较麻烦。所以开发了这款**轻快图片管理系统**，是基于vue3.x + typescript + vite + koa + mysql开发的前后端分离图床系统，使用该系统可以不需要每次都配置图床。

- 项目截图 (**6**张以内)：
  - 上传区
  ![202211101718307.png](https://imgs.itchenliang.club/img/202211101718307.png)
  - 图片管理
  ![202211101719274.png](https://imgs.itchenliang.club/img/202211101719274.png)
  - 存储桶管理
  ![202211101719413.png](https://imgs.itchenliang.club/img/202211101719413.png)
  - 字典管理
  ![202211101725334.png](https://imgs.itchenliang.club/img/202211101725334.png)
  - 相册管理
  ![202211101720094.png](https://imgs.itchenliang.club/img/202211101720094.png)
  - 存储桶插件开发
  ![202302201023375.png](https://imgs.itchenliang.club/img/202302201023375.png)

**Comment by xsxz01** [comment]
标明非开源项目
