### ISSUE TITLE
【开源自荐】G2 5.0：从可视化语言到思维

### ISSUE THREAD

**Issue by hustcc** [521xueweihan/HelloGitHub#2524]
## 推荐项目

- 项目地址：https://github.com/antvis/G2

- 类别：JS

- 项目标题：G2 是一个基于图形语法的可视化图表库

- 项目描述：AntV G2 是一套用于报表搭建、数据探索和可视化叙事的简洁的渐进式可视化语法。

- 亮点：
  - 渐进式语法：结合工业和学术实践，实现图形语法、动画语法和交互语法。
  - 丰富的标记：内置 10+ 基础标记，8+ 高阶标记。
  - 高可扩展性：提供统一机制扩展所有可视化组件。
  - 个性化风格：支持手绘、圆角、纹理等风格。
  - 多环境渲染：支持 Canvas、SVG 以及 WebGL，和 Node.js 服务端渲染。

- 示例代码：（可选）

```ts
import { Chart } from '@antv/g2';

// 准备数据
const data = [
  { genre: 'Sports', sold: 275 },
  { genre: 'Strategy', sold: 115 },
  { genre: 'Action', sold: 120 },
  { genre: 'Shooter', sold: 350 },
  { genre: 'Other', sold: 150 },
];

// 初始化图表实例
const chart = new Chart({
  container: 'container',
  theme: 'classic',
});

// 声明可视化
chart
  .interval() // 创建一个 Interval 标记
  .data(data) // 绑定数据
  .encode('x', 'genre') // 编码 x 通道
  .encode('y', 'sold'); // 编码 y 通道

// 渲染可视化
chart.render();
```

- 截图：（可选）gif/png/jpg

这篇发布稿《[G2 5.0 来啦，伴着春天的脚步，从语言到思维](https://www.yuque.com/antv/blog/zgtv9ezu83r8nusr)》有很多图。

- 后续更新计划：看这里[后续的规划](https://www.yuque.com/antv/g2-docs/biptmogeqdepgbow#SRuYT)。

**Comment by 521xueweihan** [comment]
@hustcc 该项目已推荐过
