### ISSUE TITLE
【项目自荐】无 dockerd 运行 container，为完全离线安装环境提供安装运行环境

### ISSUE THREAD

**Issue by exfly** [521xueweihan/HelloGitHub#2525]
## 推荐项目

- 项目地址：https://github.com/exfly/bmc

- 类别：Go

- 项目标题：无 dockerd 运行 tar 格式的 docker image，让搭建离线安装环境为所欲为

- 项目描述：

[bmc](https://github.com/exfly/bmc) 是基于 runc 的轻量级容器运行时环境。它允许您在不使用 dockerd 的情况下运行 tar 格式的 Docker 镜像。该项目的主要目标是为离线软件安装和运行提供便利，满足开发和运维的需求。

- 亮点：

1. 无 dockerd 或任何容器运行时运行 docker save 出的 docker image
2. 支持 amd64 及 arm64，理论上支持 golang 支持的所有架构

**Comment by 521xueweihan** [comment]
这边看到项目，已处于停更状态，所以关闭此 issues。
