### ISSUE TITLE
【开源自荐】PTPT - 一个用 ChatGPT 处理纯文本的工具

### ISSUE THREAD

**Issue by LeslieLeung** [521xueweihan/HelloGitHub#2531]
## 推荐项目

- 项目地址：https://github.com/LeslieLeung/PTPT
- 类别：Go
- 项目标题：PTPT - 一个用 ChatGPT 处理纯文本的工具
- 项目描述：PTPT 是一个命令行工具，旨在为你提供一个简单的方式，让 ChatGPT 处理纯文本文件。 PTPT 提供了多种预定义 prompt，以及方便分享和扩展的 prompt 格式。 通过订阅，你可以获得更多有趣的 prompt！
> 主要功能
> - 🌟ChatGPT Lint!
> - 预定义 prompt （目前已有 16 种 prompt）
> - 方便分享和扩展的 prompt 格式
> - 🌟通过订阅获得更多 prompt
> - 🌟开发更多有用有趣的 prompt，并通过 PTPT 管理你的 prompt
> - 通过代理使用

- 亮点：ChatGPT Lint，使用 ChatGPT 对代码进行检查。

- 截图：![](https://github.com/LeslieLeung/PTPT/raw/main/example/lint_example.png)

- 后续更新计划：
  - 优化使用体验
  - 支持ChatGPT参数配置
  - PromptHub - 通过 yaml 文件分享 prompt
  - 支持更多的 prompt
  - 支持超长文本

**Comment by 521xueweihan** [comment]
期待后续更新，月刊暂不收录哈
