### ISSUE TITLE
javatuples - Java 中的类型安全的元组

### ISSUE THREAD

**Issue by iamjohnnyzhuang** [521xueweihan/HelloGitHub#254]
## 项目推荐
- 项目名称：
javatuples

- 项目地址：
https://github.com/javatuples/javatuples

- 项目语言：
Java

- 项目描述：
提供了多个方便易用的元组类，极大的提升了开发的效率。

- Unit<A> (1 element)
- Pair<A,B> (2 elements)
- Triplet<A,B,C> (3 elements)
- Quartet<A,B,C,D> (4 elements)
- Quintet<A,B,C,D,E> (5 elements)
- Sextet<A,B,C,D,E,F> (6 elements)
- Septet<A,B,C,D,E,F,G> (7 elements)
- Octet<A,B,C,D,E,F,G,H> (8 elements)
- Ennead<A,B,C,D,E,F,G,H,I> (9 elements)
- Decade<A,B,C,D,E,F,G,H,I,J> (10 elements)

- 推荐理由：
写Java代码经常会有需要使用元组的场景，我们经常会用Array或者List来代替这种实现。
但是这不仅不够优雅，并且不够安全（你要放弃泛型来达到可以存放不同类型的数据）。
而javatuples提供了多个类型安全的、优雅的实现类，大大提升了我们开发的效率以及便捷性。

- 示例代码：
``` java
   ...
    String str = ...;
    Integer integ = ...;
    Double[] doubleArray = ...;
    ...
   
    // create a tuple
    Triplet<String,Integer,Double[]> triplet = Triplet.with(str, integ, doubleArray); 

   // fetch data
    ...
    String myStr = triplet.getValue0();
    Integer myInteg = triplet.getValue1();
    Double[] myDoubleArray = triplet.getValue2();
    ...
```

- 截图：
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/12725777/39966060-ded32baa-56d7-11e8-9a81-ea1f58022bd0.png">

**Comment by 521xueweihan** [comment]
@iamjohnnyzhuang  您推荐的项目，已成功收录在 [HelloGitHub 第 26 期](https://hellogithub.com/periodical/volume/26/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
