### ISSUE TITLE
【开源自荐】AudioFlux：一个高性能的音频分析、特征提取库

### ISSUE THREAD

**Issue by liufeigit** [521xueweihan/HelloGitHub#2541]
## 推荐项目

- 项目地址：
https://github.com/libAudioFlux/audioFlux

- 类别：
C、Python

- 项目标题：
A library for audio and music analysis, feature extraction.

- 项目描述：
一个用于音频和音乐分析、特征提取的深度学习工具库，支持数十种时频分析变换方法和数百种对应的时域、频域特征组合，它可以提供给深度学习网络进行训练，用于研究音频领域的各种任务，如分类、分离、音乐信息检索 (MIR) 和 ASR 等。

- 亮点：
> 1.  系统、多维度的提取特征和组合，可以灵活的用于各种任务研究分析。
> 2.  性能高效，核心大部分C实现，支持MKL、OpenBLAS等，方便大规模数据特征提取。
> 3.  适用移动端，支持移动端音频流实时计算。

- 截图

![flow](https://user-images.githubusercontent.com/6100752/236469379-a5bc7e74-d9d2-4d5b-aa27-a7858994a2d0.png)
![](https://cdn.codenews.cc/blog/1a4492d54225cbb747445cb112110226.png)
![mac_x86_1](https://user-images.githubusercontent.com/6100752/236459298-8e87cdfe-4775-44c5-af34-b25d9509fd5d.png)

- 示例代码：[官方文档](https://audioflux.top/)
 
- 后续更新计划：
> 1. 浏览器wasm支持，支持javascript前端web audio。
> 2. C# Unity，Unity相应插件。
> 3. C命令行工具，方便shell处理。

**Comment by 521xueweihan** [comment]
@liufeigit 该项目将收录进网站并展示，Issues 就先直接关闭了。

**Comment by 521xueweihan** [comment]
@liufeigit 您的项目已成功展示在 HelloGitHub 网站。

如果您是项目的维护者，同时项目还没有制作官网/落地页的话，可以考虑增添 HelloGitHub 项目详情页作为官网：
https://hellogithub.com/repository/645150edb7ae4d96956a5c786d0fe13e

最后，如果方便的话欢迎在项目 README 增添「HelloGitHub 徽章」展示项目获取的点赞数和评论入口，同时这也是支持 HelloGitHub 的善举。

<a href="https://hellogithub.com/repository/645150edb7ae4d96956a5c786d0fe13e" target="_blank"><img src="https://api.hellogithub.com/v1/widgets/featured.svg?rid=645150edb7ae4d96956a5c786d0fe13e" alt="Featured｜HelloGitHub" style="width: 250px; height: 54px;" width="250" height="54" /></a>
