### ISSUE TITLE
【开源自荐】交互式配置 tsconfig.json

### ISSUE THREAD

**Issue by yue1123** [521xueweihan/HelloGitHub#2543]
## 推荐项目

- 项目地址：https://github.com/yue1123/ts-config-helper

- 类别：JS、TS、Vue

- 项目标题：交互式配置 `tsconfig.json`

- 项目描述：Ts Config Helper 是一个功能强大、易用性高的 TypeScript 配置工具，提供可视化配置、详细 Ts 官网文档查阅、预设配置列表和分类过滤等多种功能，帮助你更快速、准确地完成 tsconfig.json 的配置。

- 亮点：
`交互式可视化配置界面`、`文档查阅`、`预设配置`、`分类过滤`、`双向解析`

- 截图：（可选）gif/png/jpg
![image](https://user-images.githubusercontent.com/61490799/236690176-eac241c6-8c2b-43a7-b36c-e8d89b82cb6d.png)

**Comment by 521xueweihan** [comment]
@yue1123 您好，该项目已收到月刊[第 86 期](https://hellogithub.com/periodical/volume/86)，但昨天晚上体验时“预设配置”功能提示未知错误，望悉知。

另外，您可以考虑在贵项目中引入 HelloGitHub 社区地址，用户可以在对应页面下发表对贵项目的使用体验和点赞。

- HelloGitHub 徽章：https://hellogithub.com/repository/6726c0923d8d4f089ed9ecb3986329ca/embed
- HelloGitHub 项目详情页：https://hellogithub.com/repository/6726c0923d8d4f089ed9ecb3986329ca

**Comment by yue1123** [comment]
感谢反馈，这个问题已经修复了
