### ISSUE TITLE
【工具自荐】比 rz / sz 好用的工具 trzsz ( trz / tsz )，新版本支持在跳板机使用 tmux （ 任意模式 ）的场景

### ISSUE THREAD

**Issue by lonnywong** [521xueweihan/HelloGitHub#2545]
## 推荐项目

- 项目地址： https://github.com/trzsz/trzsz-go

- 类别：Go

- 项目标题：比 rz / sz 好用的工具，支持原生终端，支持 tmux，支持……

- 项目描述：
  * ~Python 版 [trzsz](https://github.com/trzsz/trzsz ) 只有 `trz` 和 `tsz` 这两个命令，适合与 iTerm2 搭配使用。~
  * [Go 版 trzsz](https://github.com/trzsz/trzsz-go) 兼容 [Python 版 trzsz](https://github.com/trzsz/trzsz)，重点是多了 `trzsz` 这第三个命令。
  * 使用 `trzsz` 命令，可以让原生终端也支持类似 rz / sz 的文件传输方式，只要用 `trzsz ssh xxx` 登录即可。
  * [Go 版 1.1.0]() 支持在跳板机使用 `tmux` 的场景，用法：
      `[客户端]` `trzsz ssh xxx` 👉 `[跳板机]` `tmux` 👉 `trzsz -r ssh xxx` 👉 `[服务器]` `trz / tsz`

- 亮点：
  * 支持 tmux，包括 tmux 普通模式，以及与 iTerm2 集成的 tmux 命令模式。
  * 支持 传输目录，trz -d 命令上传目录，tsz -d xxx 命令下载 xxx 目录。
  * 支持 Windows，不仅可在 Windows 客户端使用，也可在 Windows ssh 服务器使用。
  * 支持 原生终端，不需要原生终端做支持，只要使用 trzsz ssh x.x.x.x 登录即可。
  * 支持 web 终端，通过 web 浏览器在本地与服务器之间传输目录和文件。
  * 支持 拖动上传，将文件和目录拖到终端窗口即可上传到远程服务器。
  * 支持 进度条，显示当前正在传输的文件名、进度、大小、速度和剩余时间等。
  * 更好的 交互体验，传输成功或出错时显示友好的结果，ctrl + c 优雅中止。

- 示例代码：（可选）

- 截图：（可选）gif/png/jpg
![](https://user-images.githubusercontent.com/20320324/209072962-73ab2660-9e13-4368-9864-8fd1cf52f8c1.gif)

- 后续更新计划：
   * 支持类似 rsync 的增量传输

**Comment by lonnywong** [comment]
### 差异：
Python 版本不支持原生终端，不支持在客户端或跳板机使用 `tmux` 普通模式的场景，Go 版的 `trzsz` 命令解决了这两个问题，且新版本用流水线实现的传输速度快了很多。

**Comment by 521xueweihan** [comment]
月刊不会重复推荐同一个项目的不同语言实现
