### ISSUE TITLE
【开源自荐】Pot 一个跨平台的划词翻译软件

### ISSUE THREAD

**Issue by Pylogmon** [521xueweihan/HelloGitHub#2546]
## 推荐项目

- 项目地址：https://github.com/pot-app/pot-desktop

- 类别：JavaScript/Rust

- 项目标题：基于Tauri的跨平台全局划词翻译软件，支持多接口选择。

- 项目描述：这款基于Tauri实现的跨平台划词翻译及OCR软件，不仅可以让用户在全平台享受一致的翻译体验，还提供了各大翻译平台的API配置，让用户自由选择接口。还可以通过其他软件插件调用，方便快捷地实现划词翻译功能。

- 亮点：
	1. 支持配置多个接口，一个软件集成各大翻译平台。
	2. 翻译交互方便，提供多种交互方式：快捷键翻译，输入翻译，插件调用翻译。
	3. 支持OpenAI接口，提供非常棒的翻译质量。
	4. 全局划词翻译，不仅仅在浏览器中使用。
	5. 跨平台，支持Windows，MacOS，Linux

- 截图：（可选）gif/png/jpg
	
	![header](https://github.com/521xueweihan/HelloGitHub/assets/59004461/abbf973f-6bf1-48a7-be95-0e1a4eec1045)

![eg1](https://github.com/521xueweihan/HelloGitHub/assets/59004461/57375b09-8eaf-4114-b179-05bb43d396f8)
![eg3](https://github.com/521xueweihan/HelloGitHub/assets/59004461/11ec9b14-920d-4ec3-a800-588cd65bcecc)
![eg4](https://github.com/521xueweihan/HelloGitHub/assets/59004461/45ff5d18-587b-425d-a540-5bd7d393a6aa)
![eg5](https://github.com/521xueweihan/HelloGitHub/assets/59004461/9d723964-823d-4b30-8756-68d61785d1cf)
![eg6](https://github.com/521xueweihan/HelloGitHub/assets/59004461/26dc3831-d78d-49c1-bf3c-7ff920628f37)

- 后续更新计划：
	1. 支持更多接口
	2. 优化界面
	3. 实现插件系统

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 88 期](https://hellogithub.com/periodical/volume/88)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

更多详情尽在：

最后，欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
