### ISSUE TITLE
【开源自荐】TTime - 一款简洁高效的输入、截图、划词翻译软件

### ISSUE THREAD

**Issue by ByLiangCheng** [521xueweihan/HelloGitHub#2555]
## 推荐项目

- 项目地址：https://github.com/InkTimeRecord/TTime

- 类别：JS

- 项目标题：一款简洁高效的输入、截图、划词翻译软件

- 项目描述：
  TTime是一款跨平台的翻译工具，一键安装全局使用，完美替代浏览器、IDEA插件
  我们的核心功能包括：通过简单的快捷键，可以轻松触发输入翻译、截图翻译、划词翻译等功能，无需额外的步骤或工具
  TTime的目标是提高工作效率，无论是在编写代码、浏览网页，还是阅读文件，都能提供即时、准确的翻译服务
  更重要的是，TTime支持17种翻译源，包括Google翻译、百度翻译、DeepL、OpenAI（ChatGPT）翻译等，并支持200多种语言的翻译

- 亮点：
1. 简单易用：TTime秉持"返璞归真"的设计理念，尽力打造用户友好的界面和使用体验
2. 全平台支持：PC软件一键安装，不受浏览器插件限制，具有跨平台特性
3. 多样化主题：支持明亮、暗黑模式，满足不同用户对界面皮肤的需求
4. 快捷键操作：支持快捷键一键调起输入翻译、截图翻译、划词翻译功能，流畅且高效
5. 多样翻译源：提供了17种翻译源任意选择，解决了用户单个翻译时，考虑结果准确性和需要比对多个翻译结果时，需要打开多个翻译窗口或应用的问题
6. 丰富OCR支持：自带离线OCR、在线OCR、第三方接入OCR，如：百度、火山等，满足OCR文字识别的各种场景需求
7. OpenAI（ChatGPT）功能：支持OpenAI（ChatGPT）翻译、文字润色、总结、分析、代码解析等功能，丰富你的语言使用体验

- 截图：（可选）gif/png/jpg

**明亮模式**

![translate](https://github.com/521xueweihan/HelloGitHub/assets/45414993/c1d5d6ea-b505-4ce1-a372-4493daf92641)
**暗黑模式**

![translate-dark](https://github.com/521xueweihan/HelloGitHub/assets/45414993/c70f4f39-d102-4097-b7a9-37097c9c0f2c)

**输入翻译（默认快捷键：Alt + Q）**

![input](https://github.com/521xueweihan/HelloGitHub/assets/45414993/6e8b0bc0-7b87-4c3b-bc94-e05e320f3b04)

**截图翻译（默认快捷键：Alt + W）**

![screenshot](https://github.com/521xueweihan/HelloGitHub/assets/45414993/854a73da-da06-44ae-af2e-559dd72ae265)

**划词翻译（默认快捷键：Alt + E）**

![choice](https://github.com/521xueweihan/HelloGitHub/assets/45414993/68278ecf-dc00-4cc9-973e-737e9b24e776)

**翻译源设置**

![14a9cb9a59804c480e08787b2b81b7e](https://github.com/521xueweihan/HelloGitHub/assets/45414993/4658da23-f4c3-4d4f-8889-884fd2c220ae)

- 后续更新计划：
1.增加翻译历史记录功能
2.增加更多翻译、OCR第三方源
3.增加划词，浮现小图标，点击翻译功能

**Comment by 0Afrikakorps1** [comment]
👍🏻
