### ISSUE TITLE
【自荐项目】Tushan: 五分钟构建一个后台管理平台

### ISSUE THREAD

**Issue by moonrailgun** [521xueweihan/HelloGitHub#2561]
## 推荐项目

- 项目地址：https://github.com/msgbyte/tushan

- 类别：JS

- 项目标题：Tushan: 五分钟构建一个后台管理平台

- 项目描述：

    `Tushan` 是一个自由度极高的，基于React的，开箱即用的后台管理应用前端框架。
    
    作为开发者, 你可以像是调用库一样快速创建一个可用的后台管理框架，包含了常见的增删改查等常规行为以及过滤、导出等常见需求。通过 Tushan, 你可以把精力更多的放在核心的业务上而不是后台管理上。

  [官方文档](https://tushan.msgbyte.com/)

- 亮点：

  相比于大量同类的admin项目来说，`Tushan` 给到用户的是一个可以快速启动的起点，一个低学习曲线的入口。如果说其他的admin项目是一个完整的项目，需要开发者去学习、去修改。那么`Tushan`就是一个开发库，跟随开发者一同快速构建自己的后台管理系统，加速开发者创造。

- 示例代码：

```tsx
import {
  createTextField,
  createEmailField,
  createUrlField,
  jsonServerProvider,
  ListTable,
  Resource,
  Tushan,
} from 'tushan';

const dataProvider = jsonServerProvider('https://jsonplaceholder.typicode.com');

function App() {
  return (
    <Tushan
      basename="/admin"
      dataProvider={dataProvider}
    >
      <Resource
        name="users"
        label="User"
        list={
          <ListTable
            fields={[
              createTextField('id', {
                label: 'ID',
              }),
              createTextField('name', {
                label: 'Name',
                list: {
                  sort: true,
                },
              }),
              createEmailField('email', {
                label: 'Email',
              }),
              createUrlField('website', {
                label: 'Website',
              }),
            ]}
            action={{ create: true, detail: true, edit: true, delete: true }}
          />
        }
      />
    </Tushan>
  );
}

export default App;
```

- 截图：

![image](https://github.com/521xueweihan/HelloGitHub/assets/6964737/29844b56-b3f0-49a8-a34c-10257a999633)

![image](https://github.com/521xueweihan/HelloGitHub/assets/6964737/c475b18e-77de-4996-bdc4-8945cf290576)

![image](https://github.com/521xueweihan/HelloGitHub/assets/6964737/f20b2721-cbaf-469d-b6bb-06d9e5287554)

![image](https://github.com/521xueweihan/HelloGitHub/assets/6964737/2a6db8fb-aed3-48dc-a0e6-8b05093a9935)

- 后续更新计划：
  - 增加一个仅需json配置就能构建完整后台的解决方案
  - 与faas平台进行集成

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
