### ISSUE TITLE
【开源自荐】goploy : Devops项目代码部署发布平台

### ISSUE THREAD

**Issue by zhenorzz** [521xueweihan/HelloGitHub#2575]
## 推荐项目

- 项目地址：https://github.com/zhenorzz/goploy

- 类别：Go

- 项目标题：web发布代码工具，支持各种代码发布、回滚，通过web来一键完成，完整的安装指引，上手无难度！

- 项目描述:
  - 构建项目
  - 发布项目到unix、windows
  - 支持git、svn、ftp、sftp
  - 基于角色的访问控制RBAC
  - 监控http、tcp、process
  - 服务器性能
  - 秒级定时任务
  - Xterm
  - Sftp
  - LDAP

- 亮点：
  -  [完备的文档](https://docs.goploy.icu/#/)
  - 可视化安装
  - 操作简便

- 截图：
   ![预览](https://raw.githubusercontent.com/zhenorzz/goploy/master/preview.gif)
   ![原理图](https://raw.githubusercontent.com/zhenorzz/goploy/master/goploy.png)

- 后续更新计划：
  - 支持导入钉钉飞书成员
  - 支持pipeline方式发布代码

**Comment by 521xueweihan** [comment]
@zhenorzz 不好意思，我来晚了。

你的持续更新和对开源的热爱，我看到了。项目已收录近期将会发布在 HelloGitHub 月刊～

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 94 期](https://hellogithub.com/periodical/volume/94)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
