### ISSUE TITLE
EasyPack - 也许是最方便的 webpack 构建工具

### ISSUE THREAD

**Issue by onvno** [521xueweihan/HelloGitHub#258]
## 项目推荐
- 项目名称：easy-pack

- 项目地址：https://github.com/onvno/easy-pack

- 项目语言：JavaScript

- 项目描述：webpack可视化构建配置

- 推荐理由：
项目中都会用到 webpack,但每个项目的重复配置太多，还经常会因为某个版本升级，导致原先的配置失效，重新花时间去整理。 很多 webpack 工具或者 CLI 都把配置包装起来，不利于二次开发，遂想把 webpack 配置模块化，简单化，可视化。
EasyPack 只专注在构建方面，目前基于 webpack3 构建开发
效率：避免重复配置的工作
交互便捷：实现可视化操作
人性化：直接暴露配置，方便修改
专注开发

- 示例代码：

- 截图：
![](http://ww1.sinaimg.cn/large/63885f75ly1frh6f0fpmfg20g80mqguf.gif)

**Comment by 521xueweihan** [comment]
您好，对比后已收录 #246 ，期待后续继续推荐项目
