### ISSUE TITLE
【开源自荐】MVM设计模式 for iOS, Android, H5; 大前端的POM设计模式

### ISSUE THREAD

**Issue by AblerSong** [521xueweihan/HelloGitHub#2581]
## 推荐项目

- 项目地址：https://github.com/AblerSong/MVMDemo

- 类别：JS、Kotlin、Swift

- 项目标题：MVM设计模式; iOS, Android, H5版本的POM设计模式

- 项目描述：本质上就是一个后端和UI的中间件, 向后端请求接口之后对数据解析, 输出一个UI需要的且可以直接使用的数据模型
       1. 大前端的UI Test一直比较费事, 尤其是iOS和Android, 通过这个设计模式, 可以通过 Unit Test 替代 UI Test;
       2. 增删功能十分方便, 复用性强; 有些公司开展相似业务线, 后端无需大改基本用的是一套代码, 使用MVM设计模式, 前端基本上只需要开发UI部分, 逻辑部分可以像后端一样复用
       3. UI 和 逻辑 可以完全拆分, 可以更容易的拆解业务, 复用代码, 提高开发效率; 

- 亮点：
           1. 相比MVC, MVVM, MVP, VIPER, MVI 等框架, 核心思想简单,易学
           2. 方便白盒自动化测试;
           3. 模式新颖, 当初写demo的时候iOS,Android,h5没看到这种设计模式, 发版后搜索了一下,发现了POM(Page Object Model):页面对象模型 is a design pattern in Selenium; 反正没在大前端看到类似文档

- 示例代码：（可选）

- 截图：（可选）gif/png/jpg

- 后续更新计划：
       增加自动化Unit Test 替换 UI Test 的demo

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
