### ISSUE TITLE
MVPArms 官方快速组件化方案

### ISSUE THREAD

**Issue by JessYanCoding** [521xueweihan/HelloGitHub#259]
## 项目推荐
- 项目名称：ArmsComponent

- 项目地址：https://github.com/JessYanCoding/ArmsComponent

- 项目语言：java

- 项目描述：ArmsComponent 是 MVPArms 官方快速组件化方案

- 推荐理由：自带近万字文档, 一键生成组件模板, 拥有成熟稳定的基础框架, 降低新手开始组件化的门槛, 让组件化走向平民化

- 截图：
  ![ArmsComponentArchitecture](https://raw.githubusercontent.com/JessYanCoding/ArmsComponent/master/arts/ArmsComponentArchitecture.jpeg)

**Comment by 521xueweihan** [comment]
@JessYanCoding 该项目咱不能收录到月刊中，已推荐过类似项目。

希望您能够继续推荐有意思、入门级项目，再次感谢。
