### ISSUE TITLE
【免费软件推荐】PDDON画图：一款日常学习工作必备画图神器

### ISSUE THREAD

**Issue by pddon** [521xueweihan/HelloGitHub#2590]
## 推荐项目

软件名称： PDDON
软件网址： https://pddon.com/
windows桌面版： https://github.com/pddon/pddon-win

它和drawio比较类似，但是和drawio有很大区别，这是一款提供了低代码和AI智能辅助画图的工具，支持在线绘图和桌面版绘图，而且对每种类型的绘图做了功能增强。
比较出色一点的功能有：
* 智能纠正绘图排版，一键美化绘图，一键切换风格等等
* 像drawio提供的一些基本绘图操作、文字排版等功能它都支持，而且支持多选后批量操作
* 支持同时打开多个绘图进行协同编辑
* 支持绘制草图风格且可调整杂乱度
* 支持数学公式
* 无限画布白板作图
* 可导出高清大图格式支持png、jpg、svg、pdf、webp等等
* 支持对象建模、数据库建模，生成代码，支持多种编程语言和SQL方言
* 画图设计稿可以导入导出且支持批量，桌面版可以双击设计稿文件直接打开实时编辑并存档
* 其他更多好用功能就不再赘述了，期待大家来使用发现哦

### 画图面板截图
![](https://meta-cdn1.appinn.com/uploads/default/optimized/3X/e/f/ef6b112fb5c302b803d22ce0be76397e55f60762_2_690x372.png)
### 页面截图
* 首页
  ![](https://meta-cdn1.appinn.com/uploads/default/optimized/3X/2/4/24959ff19a9e74cf77ceb4c6fcb54eb7ba8ce851_2_690x317.jpeg)
* 模板市场
  ![](https://meta-cdn1.appinn.com/uploads/default/optimized/3X/9/f/9fec5cce4d10677b93b9ddf9be8a17ff5a84ad9f_2_690x317.jpeg)
* 社区帮助
  ![](https://meta-cdn1.appinn.com/uploads/default/optimized/3X/2/8/28dfc594d134aadde7eb8abef39866cbe1409cb0_2_690x317.jpeg)
* 我的绘图
  ![](https://meta-cdn1.appinn.com/uploads/default/original/3X/d/1/d146d37ec7df2305e3a895778bad6c499e071bdc.jpeg)

### 其他资料

* 在线画图： https://pddon.com/
* 视频教程：[B站](https://space.bilibili.com/1293169179/video)
* 微信公众号：PDDON在线画图

**Comment by ZhangLe1993** [comment]
这不开源吗

**Comment by pddon** [comment]
> 暂时还没开源，这个项目涉及比较多的自研工具包，不可能整体开源，不过会把部分实用的工具包开源，已规划待开源的组件工具包比较多，目前没有那么多精力去搞，后续会把一些自研工具包开源出来的，目前重心还是在优化迭代，提供更优质的画图体验，让大家用起来更方便。
> 如果大家比较喜欢这个项目，可以多多支持，分享、点赞、提bug都可以，让我们感受到大家很期待这个项目，这样我们会加快加大对开源的投入，感谢大家!
