### ISSUE TITLE
【开源自荐】yft-design：基于Canvas的开源版"创客贴"

### ISSUE THREAD

**Issue by more-strive** [521xueweihan/HelloGitHub#2593]
## yft-design

- 项目地址：https://github.com/more-strive/yft-design

- 类别：Javascript

- 项目标题：基于Canvas的开源版"创客贴"

- 项目描述：使用 Vue3 + TypeScript + Fabric.js + Pinia + Element-Plus，在线设计，编辑名片，单页，海报，图片，支持印刷文件导出。

- 亮点：自定义丰富的背景（渐变，网格，底纹）

- 示例代码：（可选）

- 截图：（可选）gif/png/jpg
- 
![image](https://github.com/521xueweihan/HelloGitHub/assets/113762408/e43c11ee-2908-470f-aa8b-f4b263d999fc)
![image](https://github.com/521xueweihan/HelloGitHub/assets/113762408/a71cdd4c-759a-4864-bced-c44be19aa324)
![image](https://github.com/521xueweihan/HelloGitHub/assets/113762408/3088c182-c303-470c-a6d1-aa1858cfbd4d)

- 后续更新计划：
1，PDF导出
2，PSD导入
3，后台管理

**Comment by xsxz01** [comment]
？？？
他这个推自己产品啊，又不是开源，这样也能开源自荐？还是说他这个开源意思就是可以私有部署

**Comment by more-strive** [comment]
> ？？？ 他这个推自己产品啊，又不是开源，这样也能开源自荐？还是说他这个开源意思就是可以私有部署  
项目已经捐献给 [dromara](https://dromara.org/) 
https://github.com/dromara/yft-design  
欢迎关注star

**Comment by more-strive** [comment]
很遗憾未评选上月刊，可能是做的还不够😂

**Comment by xsxz01** [comment]
> > ？？？ 他这个推自己产品啊，又不是开源，这样也能开源自荐？还是说他这个开源意思就是可以私有部署
> > 项目已经捐献给 [dromara](https://dromara.org/)
> > https://github.com/dromara/yft-design
> > 体验地址： https://yft.design
> > 欢迎关注star

不好意思，捐赠的事那会我不了解，有事件麻烦写清楚，感谢分享

**Comment by more-strive** [comment]
是投稿之后捐赠的

**Comment by more-strive** [comment]
这个psd解析和pdf解析功能也是最近刚开发出来的
