### ISSUE TITLE
HybridPageKit

### ISSUE THREAD

**Issue by dequan1331** [521xueweihan/HelloGitHub#260]
## 项目推荐
- 项目名称：
HybridPageKit
- 项目地址：
https://github.com/dequan1331/HybridPageKit
- 项目语言：
Objective-C
- 项目描述：
HybridPageKit是一个针对新闻类App高性能、易扩展、组件化的通用内容页实现框架。
- 推荐理由：
集成简单，几十行代码完成新闻类App的内容展示页框架，满足绝大多数使用场景
- 示例代码：

- 截图：

### 编辑完推荐项目的信息，下述提示信息**请删除**
非常感谢推荐这么好的项目

如您推荐的项目收录到《HelloGitHub》月刊，您的GitHub帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/contributors.md)，**同时会在此 issues 中通知您**。

再次感谢您对《HelloGitHub》项目的支持！

HelloGitHub 网站：https://hellogithub.com

**Comment by 521xueweihan** [comment]
@dequan1331 请问作为新手这个项目可以带给他们那些收获？另外请根据提示删除提示信息。😊修改后可重开 issues。
