### ISSUE TITLE
【开源自荐】Awesome AIGC Tutorials

### ISSUE THREAD

**Issue by zht1130** [521xueweihan/HelloGitHub#2602]
项目地址：https://github.com/luban-agi/Awesome-AIGC-Tutorials

类别：资料收集

项目标题：Awesome AIGC Tutorials

项目描述：仓库收集了关于AIGC的各种精选教程和资源，既适合初学者也适合进阶AI爱好者。

亮点：全网最全的AIGC教程资料收集

截图：
![image](https://github.com/521xueweihan/HelloGitHub/assets/23211139/81711d18-5bf6-4aee-bad7-10fc15fc3788)
![image](https://github.com/521xueweihan/HelloGitHub/assets/23211139/14c47dc0-e9a6-4a6c-b1cf-ea63fd067109)

后续更新计划：完善中文版

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
