### ISSUE TITLE
【开源自荐】定制中秋贺卡 🌕 送祝福·庆团圆·寄相思

### ISSUE THREAD

**Issue by xiaoli1999** [521xueweihan/HelloGitHub#2610]
## 推荐——定制中秋贺卡

![预览](https://github.com/xiaoli1999/moon-card/raw/master/preview.png)

- 项目地址：https://github.com/xiaoli1999/moon-card

- 项目预览
[主站地址✈️](https://www.xiaoli.vip/moon-card) 
[github pages✈️](https://xiaoli1999.github.io/moon-card) 

- 类别：JS

- 项目标题：定制中秋贺卡小工具；用户可快速定制，得到属于自己的中秋贺卡。

- 项目描述：该项目是基于vue3、typescript、Element UI、fabric.js的一款定制中秋贺卡工具。预置祝福、团圆、思念三个贺卡主题，用户只需上传头像，修改文案，简单调整位置即可快速定制出中秋贺卡。支持中秋贺卡集功能，用户可观看他人定制的贺卡。支持保存、生成海报分享，将祝福传递给身边人！

- 项目初衷：露从今夜白，月是故乡明！中秋将至，团圆之时近。中秋将至，采黎为大家带来 **定制中秋贺卡**。值此佳节，让我们通过贺卡传递温馨祝福，庆祝团圆，寄托思念。

- 特点：使用最新的语言及工具，代码质量高，扩展性强，可玩度高；该工具轻量、灵活、自由，用户体验感较好。

- 兼容性：兼容PC移动（微信、qq内置浏览器）

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
