### ISSUE TITLE
【开源自荐】plus-pro-components ，vue 版本的 ProComponents，页面级别的前端组件。

### ISSUE THREAD

**Issue by l-x-f** [521xueweihan/HelloGitHub#2618]
## 推荐项目

- 项目地址：https://github.com/plus-pro-components/plus-pro-components

- 类别：JS

- 项目标题：vue 版本的 ProComponents，页面级别的前端组件。

- 项目描述：PlusProComponents 是基于 element-plus 而开发的模板组件，它提供了更高级别的抽象支持，开箱即用。可以显著的提升制作 CRUD 页面的效率，更加专注于页面。

- 亮点：功能强大、易于使用、高度可定制、兼容element-plus、丰富的组件库、使用
TypeScript 国际化 预设

- 示例代码：（可选）

- 截图：（可选）gif/png/jpg

![1](https://github.com/521xueweihan/HelloGitHub/assets/33000154/c1590d4a-f56a-4922-94f2-fec8e7f66e5b)
![2](https://github.com/521xueweihan/HelloGitHub/assets/33000154/0987ccff-898f-471e-9100-30835342f024)
![3](https://github.com/521xueweihan/HelloGitHub/assets/33000154/853c08e5-c83b-49c7-ab8e-8a657282b6fd)
![4](https://github.com/521xueweihan/HelloGitHub/assets/33000154/20fa8d45-86e5-4916-a018-86a014799cf6)
![5](https://github.com/521xueweihan/HelloGitHub/assets/33000154/9a802be5-ad7b-4f95-9c9d-f07e413ff9b5)
![6](https://github.com/521xueweihan/HelloGitHub/assets/33000154/0902221b-56c4-44b0-ad37-6d01a9682e20)

- 后续更新计划：周更

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
