### ISSUE TITLE
pqi: a terminal tools for Python

### ISSUE THREAD

**Issue by Fenghuapiao** [521xueweihan/HelloGitHub#262]
## 项目推荐
- 项目名称：PyQuickInstall

- 项目地址：https://github.com/Fenghuapiao/PyQuickInstall

- 项目语言：Python

- 项目描述：把国外PyPi源迅速切换化为国内源tuna(清华源)、douban、 aliyun、ustc(中科大源) 从而加快   python包的安装速度。

- 推荐理由：由于国内通过pip下载python包的速度真的很慢，而pqi可以把国外的PyPi源迅速切换为国内源tuna, douban, aliyun, ustc从而加快python包的安装速度，支持Py2、Py3、跨平台。

- 怎么使用：
#### 方法一（推荐）
```
>>> pip install pqi
```

#### 方法二
```
>>> git clone https://github.com/Fenghuapiao/PyQuickInstall.git
>>> python3 setup.py install
```

### 2. 命令行输入 `pqi` 回车
```
>>> pqi
Usage:
  pqi ls
  pqi use <name>
  pqi show
  pqi add <name> <url>
  pqi remove <name>
  pqi (-h | --help)
  pqi (-v | --version)
Options:
  -h --help        Show this screen.
  -v --version     Show version.
```
* 列举所有支持的PyPi源
```
>>> pqi ls
```

* 改变PyPi源
```
>>> pqi use <name>
```
例子，比如运行`pqi use tuna`即把当前PyPi源改为清华的PyPi源

* 显示当前PyPi源
```
>>> pqi show
```

* 添加新的pip源(如添加USTC源）
```
>>> pqi add ustc https://mirrors.ustc.edu.cn/pypi/web/simple
```

* 移除pip源（如官方PyPi源）
```
>>> pqi remove pypi
```

### 3. 升级到最新版`pqi`
```
>>> pip install --upgrade pqi
```

**Comment by 521xueweihan** [comment]
@Fenghuapiao 非常推荐这种动手写工具，并开源的精神。但该项目暂不能收录到月刊中。期待您后面的推荐。
