### ISSUE TITLE
【开源自荐】让移动端视图展示在桌面端的 PostCSS 插件

### ISSUE THREAD

**Issue by wswmsword** [521xueweihan/HelloGitHub#2620]
## postcss-mobile-forever

- 项目地址：https://github.com/wswmsword/postcss-mobile-forever

- 类别：JS、CSS

- 项目标题：让移动端视图展示在桌面端的 PostCSS 插件

- 项目描述：一款 PostCSS 插件，将固定尺寸的移动端视图转为具有最大宽度的可伸缩的移动端视图，让移动端视图处处可访问。相比 postcss-px-to-viewport，mobile-forever 能够限制最大宽度，从而使桌面端可访问；相比 rem + js，mobile-forever 不涉及 javascript，仅使用 CSS 完成限制移动端视图最大宽度的任务。

- 亮点：支持限制移动端视图的最大宽度、提供多种方式限制最大宽度、易用的 API

- 示例代码：

```javascript
import mobile from 'postcss-mobile-forever' // <---- 这里
import autoprefixer from 'autoprefixer'
// 省略……
{
	postcss: {
		plugins: [
			autoprefixer(),
			mobile({ // <---- 这里
				appSelector: '#app',
				viewportWidth: 375,
				maxDisplayWidth: 580,
			}),
		],
	},
}
// 省略……
```

- 截图：

<table>
	<tr>
		<td><img src="https://raw.githubusercontent.com/wswmsword/postcss-mobile-forever/main/images/portrait.png" alt="移动端的展示效果" /></td>
		<td><img src="https://raw.githubusercontent.com/wswmsword/postcss-mobile-forever/main/images/landscape.png" alt="移动端横屏的展示效果" /></td>
	</tr>
	<tr>
		<td colspan="2"><img src="https://raw.githubusercontent.com/wswmsword/postcss-mobile-forever/main/images/desktop.png" alt="桌面端的展示效果" /></td>
	</tr>
</table>

- 后续更新计划：持续更新

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
