### ISSUE TITLE
【开源自荐】谷歌网盘文件管理插件 DriveWorks 

### ISSUE THREAD

**Issue by ycui1984** [521xueweihan/HelloGitHub#2622]
## 推荐项目

- 项目地址：https://github.com/ycui1984/DriveWorks

- 类别：JS

- 项目标题：谷歌网盘管理插件

- 项目描述：管理谷歌网盘方便易用, 但是文件管理及其耗时易错. 比如我们想在上万个文件中删除所有title 为Untitled document的文件, 只能耗费大量的时间去手工操作. DriveWorks 覆盖了基本的用户文件管理场景, 比如删除, 重命名等, 同时提供了基于文件类型, 文件名等过滤器, 用户只需在UI上简单配置, 插件会完成剩下的枯燥工作, 同时任务结束会生成详细报表和邮件提醒.

- 亮点：没有同类型的项目. 

- 示例代码：（可选）

- 截图：（可选）gif/png/jpg

- 后续更新计划：基于用户反馈将持续添加新feature. 同时会提交Google marketplace供用户使用

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
