### ISSUE TITLE
【开源自荐】Pictode-最方便集成的绘图编辑器

### ISSUE THREAD

**Issue by JessYan0913** [521xueweihan/HelloGitHub#2625]
## 推荐项目

- 项目地址：https://github.com/JessYan0913/pictode

- 类别：JS

- 项目标题：Pictode-最方便集成的绘图编辑器

- 项目描述：
 
Pictode是一个基于Konva.js开发的绘图编辑器框架，具备流畅的交互体验，面向开发者提供友好的集成方式和可扩展特点。

也许你已经在网上看到许多技术大咖分享如何实现画板或图片编辑器的方法。他们或许详细解释了编辑器的原理和代码实现，有些甚至直接使用原生Canvas构建编辑器。但你是否和我有相同的感受？

我们既敬佩技术大咖，又感到自己阅读后除了感叹：“🐮🍺！”外收获很少。原因在于我们无法将他们的代码应用到项目中。虽然阅读、点赞和收藏了这些文章，但仍感头脑空空，实际收获有限。

**把图形编辑器嵌入自己的项目，有时真麻烦**。比如，编辑器用React构建，你的项目用Vue；或者编辑器不够灵活。

Pictode就是你的救星，像🚀一样，解决这些问题，让你事半功倍。

- 亮点：基于Konva.js库、方便集成、可自定义工具、可自定义插件、与UI框架无关

- 示例代码：

**Pictode** offers various plugins to cater to diverse needs.

[![Edit pictode](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/pictode-playground-7rm8zq?file=%2Fsrc%2FApp.vue%3A1%2C1)

### 🕒 History Plugin

1. Install the `@pictode/plugin-history` dependency.

```shell
npm install @pictode/plugin-selector
```

2. Instantiate the historyPlugin plugin.

```ts
import { HistoryPlugin } from '@pictode/plugin-history';

const historyPlugin = new HistoryPlugin();
```

3. Use the app.use(historyPlugin) method to load the plugin.

```ts
app.use(historyPlugin);
```

4. You can now implement undo and redo functionality with the app.undo() and app.redo() methods.

### ✅ Selector Plugin

1. Install the @pictode/plugin-selector dependency.

```shell
npm install @pictode/plugin-selector
```

2. Instantiate the selectorPlugin plugin.

```ts
import { SelectorPlugin } from '@pictode/plugin-selector';

const selectorPlugin = new SelectorPlugin();
```

3. Use the app.use(selectorPlugin) method to load the plugin.

```ts
app.use(selectorPlugin);
```

4. Implement selecting and deselecting shapes using mouse clicks or the app.select(...) and app.cancelSelect(...) methods. Hold down the Shift key to enable multi-selection and deselection.

### 🔄 Alignment Tools

1. Install the @pictode/plugin-alignment dependency.

```shell
npm install @pictode/plugin-selector
```

2. Instantiate the alignmentPlugin plugin.

```ts
import { AlignmentPlugin } from '@pictode/plugin-alignment';

const alignmentPlugin = new AlignmentPlugin();
```

3. Use the app.use(alignmentPlugin) method to load the plugin.

```ts
app.use(alignmentPlugin);
```

4. You can now perform alignment operations using a range of methods, including app.alignTop, app.alignRight, app.alignBottom, app.alignLeft, app.alignCenterX, app.alignCenterY, and more.

5. Additionally, use app.distributeX and app.distributeY methods to achieve horizontal and vertical distribution.

- 截图：

![效果图](https://github.com/JessYan0913/picx-images-hosting/raw/master/Kapture%202023-10-18%20at%2022.26.09.gif)

- 后续更新计划：

![v1.0.0](https://p9-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/62864bab4328465faa3cb80614aa4815~tplv-k3u1fbpfcp-jj-mark:3024:0:0:0:q75.awebp#?w=1166&h=2484&s=416468&e=png&b=141414)

![v2.0.0](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/49608c2d0aec4303a6647ad4428fa753~tplv-k3u1fbpfcp-jj-mark:3024:0:0:0:q75.awebp#?w=784&h=1144&s=99049&e=png&b=141414)

![v3.0.0](https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/3e6842ceddf14ac7933df758711d79af~tplv-k3u1fbpfcp-jj-mark:3024:0:0:0:q75.awebp#?w=716&h=504&s=50059&e=png&b=151515)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
