### ISSUE TITLE
【开源自荐】跨平台的截图、录屏、录音、录像软件 pear-rec 

### ISSUE THREAD

**Issue by 027xiguapi** [521xueweihan/HelloGitHub#2627]
- 项目地址：https://github.com/027xiguapi/pear-rec/
- 类别：JS
- 项目标题：跨平台的截图、录屏、录音、录像软件
- 项目描述：pear-rec(梨子 rec) 是一个跨平台的截图、录屏、录音、录像软件。
- 示例代码：[网页](https://pear-rec-xiguapi.vercel.app/)
- 截图：

首页：
![home](https://user-images.githubusercontent.com/31228055/275695109-7c7d44ee-0f00-4fd5-8037-968365189de4.jpg)

截图：
![ss](https://user-images.githubusercontent.com/31228055/275694837-a31f22f2-2b50-4596-9a95-c76abe8ec657.jpg)

录音：
![ra](https://user-images.githubusercontent.com/31228055/275694917-f8d24a17-6d45-4b4d-b019-f7e113381a75.jpg)

查看图片：
![vi](https://user-images.githubusercontent.com/31228055/275694957-2863b26a-d7e2-4abc-8795-17e9cd968e97.jpg)

播放视频
![vv](https://user-images.githubusercontent.com/31228055/275695037-96a4d90c-2b80-4778-b28c-c75c5c14cd96.jpg)

录屏：
![rs](https://user-images.githubusercontent.com/31228055/275695074-3b6ac264-2103-457f-b634-281ec3150dd5.jpg)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目，已推荐过类似项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
