### ISSUE TITLE
HTML 静态页面快速迭代工具

### ISSUE THREAD

**Issue by BingKui** [521xueweihan/HelloGitHub#263]
## 项目推荐
- 项目名称：static-html-template

- 项目地址：https://github.com/BingKui/static-html-template.git

- 项目语言：HTML,Less

- 项目描述：静态页面网站快速开发环境，支持自动刷新页面，less样式预处理。

- 推荐理由：在现在项目迭代快递的情况下，官网的修改速度也不断加快，此项目能够实现样式的预处理，页面自动刷新等功能，帮助开发者加速页面的开发、调试速度。项目发包支持资源的压缩、浏览器兼容性前缀和页面压缩等功能，能够大大减少页面在加载过程中所消耗的资源。

- 示例代码：

- 截图：

**Comment by JameJJ** [comment]
谢谢推荐，请问一下你这种方案有在公司中使用吗

**Comment by BingKui** [comment]
在公司使用过，在我前家公司使用过，因为存在多条产品线，官网比较多，并且修改不叫频繁，所以自己搭建了一套这样的模板，方便开发和修改。

**Comment by xuexb** [comment]
@BingKui 赞，你的项目里再有个可预览的示例就更帅了~

**Comment by 521xueweihan** [comment]
@BingKui 建议增加一个，[GitHub Page](https://pages.github.com/) 的在线 demo 展示。这样生成的静态页面的效果一目了然。
