### ISSUE TITLE
【开源自荐】焰火十二卷 - 基于 PyQt5 的调色板应用程序，为创建调和色彩而设计

### ISSUE THREAD

**Issue by eigenmiao** [521xueweihan/HelloGitHub#2634]
## 推荐项目

- 项目地址：https://github.com/eigenmiao/Rickrack
- 项目主页：https://eigenmiao.com/yanhuo
- 视频教程：https://space.bilibili.com/390426743

- 类别：Python

- 项目标题：焰火十二卷 - 基于 PyQt5 的调色板应用程序，为创建调和色彩而设计

- 项目描述：该项目打造了一款开源的调色板桌面应用，旨在帮助用户轻松实现色彩的协调与搭配。这款软件提供了多项强大的功能，让用户能够快速创建出和谐的色彩组合。值得一提的是，该软件高度尊重用户的隐私，不需要注册、会员资格或网络连接，也没有任何功能上的限制，所有的数据都安全地存储在用户自己的计算机上。这款应用适用于各类创意工作者，包括绘画爱好者和专业设计师，无论你是初学者还是专业用户，都能轻松实现色彩的协调搭配。

- 亮点：
1. 从色轮中选取一组符合特定调和规则的色彩。
2. 从图像中提取出一组搭配和谐的色彩。
3. 根据用户选择的色彩生成一个混合渐变的色板。
4. 保存、导出和转换色板，支持常见色板格式如 aco、ase、gpl、xml 等。
5. 导出的色板可导入至 Photoshop、Clip Studio Paint、GIMP、Krita 等图像编辑和数字绘画软件中。

- 截图：（可选）gif/png/jpg
1. 从色轮中选取一组符合特定调和规则的色彩。
![](https://raw.githubusercontent.com/eigenmiao/Rickrack/main/demo/00_usage/000.gif)

2. 从图像中提取出一组搭配和谐的色彩。
![](https://raw.githubusercontent.com/eigenmiao/Rickrack/main/demo/00_usage/109.gif)

3. 根据用户选择的色彩生成一个混合渐变的色板。
![](https://raw.githubusercontent.com/eigenmiao/Rickrack/main/demo/00_usage/202.gif)

4. 保存色板。
![](https://raw.githubusercontent.com/eigenmiao/Rickrack/main/demo/00_usage/300.gif)

- 后续更新计划：
我们将持续不断地改进软件的用户体验。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 92 期](https://hellogithub.com/periodical/volume/92)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

更多详情尽在：

最后，欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
