### ISSUE TITLE
SiteServer CMS 内容管理系统

### ISSUE THREAD

**Issue by starlying** [521xueweihan/HelloGitHub#264]
## 项目推荐
- 项目名称：SiteServer CMS 内容管理系统

- 项目地址：https://github.com/siteserver/cms/

- 项目语言：C#

- 项目描述：SiteServer CMS 基于.NET平台，能够以最低的成本、最少的人力投入在最短的时间内架设一个功能齐全、性能优异、规模庞大并易于维护的网站平台。

- 推荐理由：国内主流开源免费CMS系统

- 示例代码：

- 截图：![](https://camo.githubusercontent.com/64f5a081077ee02d4332e12851ca381a18c5fc9f/68747470733a2f2f7777772e736974657365727665722e636e2f6173736574732f6769746875622d62616e6e65722e706e67)

**Comment by 521xueweihan** [comment]
@starlying 您推荐的项目，已成功收录在 [HelloGitHub 第 27 期](https://hellogithub.com/periodical/volume/27/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
