### ISSUE TITLE
【开源自荐】PageSpy，远程调试Web项目，本地H5调试可以替代 vConsole

### ISSUE THREAD

**Issue by wqcstrong** [521xueweihan/HelloGitHub#2645]
## 推荐项目

- 项目地址：https://github.com/HuolalaTech/page-spy-web

- 类别：Javascript

## 开源背景

技术和测试、产品不在一个地方办公。H5 项目提测后出现问题，尽管测试人员会提供 vConsole 的截图，但在「确认问题」环节上会产生很多沟通成本，本质原因是测试人员不知道代码逻辑，同时技术人员只能在测试人员的帮助下了解故障。

## 设计目标

出现问题后：1）测试只需要跟技术简单描述问题；2）技术可以直接看到调试信息。

## 解决思路

PageSpy 组合SDK、server、调试端三者。客户端集成 SDK ，SDK 收集数据发到调试端，技术人员在调试端和故障信息直接面对面。开源后提供了 Docker 、NPM Package 等多种[一键部署](https://github.com/HuolalaTech/page-spy-web#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8)的方案，用户可以部署到内网，承诺不会收集任何数据。

### 主页
![image](https://github.com/521xueweihan/HelloGitHub/assets/23474513/b2d02f2e-38d8-490c-8a5b-d5281e2b229f)

### 待调试列表
![image](https://github.com/521xueweihan/HelloGitHub/assets/23474513/65a93c83-547b-4567-8efa-103b95574a40)

### 调试面板
![image](https://github.com/521xueweihan/HelloGitHub/assets/23474513/473ad7a5-dbda-4db4-8706-7e0bfce3209f)

## 其他
PageSpy 起初设计用于解决远程协同的问题，但最后发现同样可以用于在本地调试 H5。整体的调试体验也比 vConsole 更好，比如：
- 检测客户端使用的系统和浏览器
- 报错时支持定位到源码
- 支持查看 indexedDB
- 检测各个标准方法的兼容性
- ……

## 后续更新计划

长期更新

**Comment by 521xueweihan** [comment]
@wqcstrong 请按照 issues 模板修改项目项目描述

**Comment by wqcstrong** [comment]
> @wqcstrong 请按照 issues 模板修改项目项目描述

你好，已修改。麻烦再看一下

**Comment by wqcstrong** [comment]
> 您推荐的项目，**已成功发布**在 [HelloGitHub 第 92 期](https://hellogithub.com/periodical/volume/92)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
> 
> 更多详情尽在：
> 
> 最后，欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

🙏 感谢
