### ISSUE TITLE
【开源自荐】macOS系统状态监控桌面小组件，支持网络、CPU、内存监控

### ISSUE THREAD

**Issue by blabla-yy** [521xueweihan/HelloGitHub#2647]
## 推荐项目

- 项目地址：https://github.com/blabla-yy/monitor

- 类别：Swift

- 项目标题：macOS系统状态监控桌面小组件，支持网络、CPU、内存监控

- 项目描述：支持状态栏、桌面小组件的系统状态监控应用，可以在桌面实时展示系统状态。其中网络信息可以以多维度筛选，并可以在状态栏或应用中查看各个应用进程的网络使用情况。

- 亮点：支持macOS 14桌面小组件；各应用实时网络状态展示；支持状态栏

- 截图：
<img width="720" alt="snapshot" src="https://github.com/521xueweihan/HelloGitHub/assets/38376621/b547d776-ce5e-4ea1-a4ba-ca6d7cb85627">
<img width="424" alt="demo" src="https://github.com/521xueweihan/HelloGitHub/assets/38376621/266beb11-e4b8-4a7e-a0ca-95eaa7a01b9f">

- 后续更新计划：使用bpf捕获网络数据包，以获得更好的性能和更多的数据筛选方式

**Comment by 521xueweihan** [comment]
@blabla-yy 已推荐过类似的项目
