### ISSUE TITLE
wtool 是一个工具函数集合，同时一个练手的好轮子，感兴趣的同学请迅速上车哈

### ISSUE THREAD

**Issue by wangzianan** [521xueweihan/HelloGitHub#265]
## 项目推荐
- 项目名称：WTool 

- 项目地址：https://github.com/wangzianan/WTool

- 项目语言：javascript

- 项目描述：
wtool 是一个工具函数集合，它参照了 underscore.js 的 API 设计，但具体实现和 underscroe.js 是不一样的。这当然是一个练手的好轮子了，哈哈。
- 推荐理由：
期待和我一起同行的小伙伴，全方位参与其中，这个项目走下来不能让你变成大师，但是我敢肯定会让你的能力上一个台阶，赶快加入吧

- 示例代码：
```
<script src="../wtool.js"></script>

wtool.map([1, 2, 3], function(num){ return num * 3; })
wtool.reduce([1,2,3], function(memo, num){ return memo+num;})
```
- 截图：
![image](https://user-images.githubusercontent.com/13514472/40760075-9f5991b4-64c7-11e8-90e0-f88e2f3e35fe.png)

**Comment by JameJJ** [comment]
@wangzianan 你好，首先十分感谢关注hellogithub，我看了一下你的项目，目前应该处于萌芽状态。我觉得项目想法不错，但是确实项目成熟度还未到一定程度。我们的推荐的目的是想让更多的人去知道一些成熟的开源项目。在次谢谢你的关注，如果说对hellogithub有什么建议的话也可以提出来的😂
