### ISSUE TITLE
【开源自荐】Gmeek 超轻量级个人博客，All in Github

### ISSUE THREAD

**Issue by Meekdai** [521xueweihan/HelloGitHub#2651]
## 推荐项目

- 项目地址：https://github.com/Meekdai/Gmeek

- 类别：Python

- 项目标题：Gmeek 超轻量级个人博客，All in Github

- 项目描述：完全基于`Github Pages` 、 `Github Issues` 和 `Github Actions`。不需要本地部署，从搭建到写作，只需要18秒，2步搭建好博客，第3步就是写作。

- 亮点：只需要有github账号即可，搭建超级简单，完全免费，也可以自定义主题等。默认响应式主题，适配电脑和手机端浏览。

- 截图：
![image](https://github.com/521xueweihan/HelloGitHub/assets/11755104/12ae935f-536e-40a2-9de7-b4dd900ac3f9)

- 后续更新计划：
1. 添加更多的主题样式（欢迎前端大佬自定义）
2. 优化加载速度

**Comment by chaozh** [comment]
好像很多这种项目，优点是什么呢

**Comment by 521xueweihan** [comment]
@Meekdai 博客风格很清爽，搭建和发布流程很极客，此类项目很多，我之所以没有收录是因为 GitHub 的网络问题，你琢磨琢磨。

**Comment by Meekdai** [comment]
@521xueweihan GitHub 的网络问题？咋们这个HelloGitHub的项目不就是分享GitHub上的项目吗？如果是考虑到访问博客的用户不能访问，套一个国内的CDN就可以解决的。

另外`此类项目很多`，我了解到的很多都是比较古早的项目，搭建和使用起来都不是很方便的，所以我才有这个想法做了这个项目。

**Comment by 521xueweihan** [comment]
@Meekdai 你觉得我为什么要做 HelloGitHub.com 的站点，而且是托管在国内。咱们得考虑可续发展吧，月刊收录的项目也一样

月刊很少收录依赖海外服务的项目

**Comment by Meekdai** [comment]
@521xueweihan HelloGitHub我想是让更多的人了解到GitHub上的一些优秀的开源项目，并且参与进来。整个GitHub都是海外的服务，你却在这里纠结这个项目是否依赖海外服务。

所以我现在理解HelloGitHub并不是让更多人参与到开源项目中，而是利用国内不能稳定访问GitHub的网站，让更多人看到你的网站而已。

我的项目虽然不是什么高大上的项目，但是初心是让更多人参与开源，可以更好更方便而且免费的搭建自己的博客。如果需要国内访问，完全可以花钱买个阿里云服务器，直接用WordPress、Typecho等博客框架，完全没有必要来GitHub折腾。

**Comment by 521xueweihan** [comment]
@Meekdai 我本是好意提醒你这种项目做不大，你为什么不考虑一下之前类似项目为什么不做了？重点此类项目的目标用户也不应该是国内用户，你知道国内上线的网站内容是要加审核的吗？但是你这种恶意揣测的行为，我还是气不过。

HelloGitHub 百分之九十以上是国内读者，一般会魔法一半不会魔法，难道我不应该考虑收录项目，对于国内用户的使用场景吗？这点竟然也能被你吐槽，依赖服务和使用平台是两个不同的概念，你如果不懂那是因为你用的免费服务还不够多。

我维护 HelloGitHub 这个项目 7 年，GitHub 的内容一直是第一时间更新。制作网站的原因是：收录项目太多不好维护，考虑可持续不重复收录才开发的网站。而且，我为了方便挂代理的用户更好的访问源项目，还加机器做了海外代理。

[我和 HelloGitHub](https://mp.weixin.qq.com/s/xNpX3eCaWL_kNe8oZLxTWA)

以上种种，不一定能说服你，如果我不进行说明，看到这里人可能就会被你的言论所误导。

**Comment by Meekdai** [comment]
@521xueweihan 生气不值得了，我只是看到你说因为我的这个依赖了Github，所以感到非常诧异，吐槽一下。上面回的可能稍微有点情绪在里面，请你原谅。

我们正常讨论就行，我感觉开源一个项目第一位肯定是自己喜欢，自己愿意花时间在这个上面。如果有更多的人喜欢一起开发那就更好了，而至于需不需要做大我觉得无所谓。在你这边自荐推广，我也就是想让更多的人看到这个项目，觉得喜欢过来试用一下，如果觉得是因为GitHub Pages需要翻墙才能访问不合适，那就当个乐子看一看。既然不合适HelloGitHub也就算了。

也谢谢你给出的答复。
