### ISSUE TITLE
【开源自荐】一个类似看门狗功能的golang 库

### ISSUE THREAD

**Issue by OnlyPiglet** [521xueweihan/HelloGitHub#2653]
项目地址：https://github.com/OnlyPiglet/watchdog
类别：Golang
项目标题：看门狗功能的golang 库
项目描述：这是一个实现类似看门狗功能的库，可以自定义实现投喂功能，跑飞处理功能 ，大地减少了重复轮子代码。
亮点：
零学习成本，go mod引入之后，只需要实现Sheep接口即可；

功能全面，看门狗常见功能都有；

生产环境验证，该项目已在内部多个项目中使用。

示例代码：（可选）

```golang
require (
	github.com/OnlyPiglet/watchdog 073af6c2620f3995c3811b64df28a94e83aede93
)
```

```golang

dog := NewWatchDog()

sheep := MySheep{
	food: make(chan struct{}, 1),
	name: "my sheep",
}

err := dog.AddSheep(&sheep)
	if err != nil {
		panic(err)
	}

```

截图：

![image](https://github.com/521xueweihan/HelloGitHub/assets/46953658/9577949a-0d84-456e-9d1b-039fa636ffda)

![image](https://github.com/521xueweihan/HelloGitHub/assets/46953658/518daabc-c153-45f0-9f92-e75f58d13003)

后续更新计划：
目前watchdog 的功能已经相当完善，未来会根据用户提的Issue进行功能迭代。

**Comment by 521xueweihan** [comment]
@OnlyPiglet 月刊已收录过类似的项目，所以您的项目无法收录进月刊。

**Comment by OnlyPiglet** [comment]
> @OnlyPiglet 月刊已收录过类似的项目，所以您的项目无法收录进月刊。

好吧
