### ISSUE TITLE
class-site

### ISSUE THREAD

**Issue by ZZKdev** [521xueweihan/HelloGitHub#266]
## 项目推荐
- 项目名称：
class-site
- 项目地址：
https://github.com/ZZKdev/class-site
- 项目语言：
python
- 项目描述：
班级管理网站，使用django搭建。实现了文件下传下载，消息发布和管理，图片上传显示，分页管理。一个django的入门级项目，也是一个教程。
- 推荐理由：
里面包括了django的入门和写这个项目的教程，已经打包成pdf。通过这个教程可以快速地入门django，在这个项目里面，django的基本功能都有所涉及。
- 示例代码：
from django.shortcuts import render
from django.http import HttpResponse
from .models import News, Announcement, File_math, File_language, File_others
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
# Create your views here.
```
def index(request):
    news_list = News.objects.all().order_by('-time')
    paginator = Paginator(news_list, 1)

    page = request.GET.get('page')
    try:
        news = paginator.page(page)
    except PageNotAnInteger:
        news = paginator.page(1)
    except EmptyPage:   
        news = paginator.page(paginator.num_pages)
    First = Announcement.objects.last()
    return render(request, 'class_home_page.html', {'news' : news, 'First' : First})

def course_view(request):
    First = Announcement.objects.last()
    return render(request, 'course.html', {'First' : First})

def Announce_view(request):
    Announce_list = Announcement.objects.all().order_by('-time')

    First = Announcement.objects.last()

    return render(request, 'Announce.html', {'announce_list' : Announce_list, 'First' : First})
```
- 截图：
![教程目录](https://user-images.githubusercontent.com/33409623/40883202-25f0e9f6-672b-11e8-83cd-3932189cb553.png)
![](https://raw.githubusercontent.com/ZZKdev/class-site/master/projectshow/one.jpg)
![](https://raw.githubusercontent.com/ZZKdev/class-site/master/projectshow/two.jpg)
![](https://raw.githubusercontent.com/ZZKdev/class-site/master/projectshow/three.jpg)

**Comment by 521xueweihan** [comment]
@ZZKdev 建议参照 [HelloGitHub 推荐项目审核标准](https://gist.github.com/JameJJ/bbdf4f9fe5d9c69b4aba203dbe2cd873) 修改项目 Readme

再次感谢您对 HelloGitHub 的支持
