### ISSUE TITLE
【开源自荐】VersionFox: 一款轻量、通用、跨平台的SDK版本管理工具。

### ISSUE THREAD

**Issue by aooohan** [521xueweihan/HelloGitHub#2664]
## 推荐项目

- 项目地址：https://github.com/version-fox/vfox

- 类别：Go

- 项目标题：一款轻量、通用、跨平台的SDK版本管理工具。

- 项目描述：每种编程语言都有对应的版本管理工具，如nvm、fvm、gvm、sdkman等，它们的核心功能大同小异。但对于使用多种语言的开发者来说，这意味着需要学习和记忆各种不同的命令，增加了学习成本。如果你是全栈工程师,或者使用不止一种语言,使用VersionFox，你无需再学习这些繁杂的工具，从而降低学习成本，节省时间。

- 亮点：跨平台! 以插件的形式提供SDK, 有官方插件库. 另外可根据插件规范实现自定义插件. 可分享插件.

- 示例代码：（可选）

- 截图：（可选）gif/png/jpg
 
<img width="1334" alt="image" src="https://github.com/521xueweihan/HelloGitHub/assets/40265686/0572ab40-aed2-43a1-b358-bf894418bf93">

<img width="1335" alt="image" src="https://github.com/521xueweihan/HelloGitHub/assets/40265686/9e934561-6f49-4be9-ad9c-f21e09a0723e">

### 管理Dart
![v-dart](https://github.com/521xueweihan/HelloGitHub/assets/40265686/42926229-9ff1-466e-972a-10cdc1d094ca)
### 管理Flutter
![v-flutter](https://github.com/521xueweihan/HelloGitHub/assets/40265686/c46f77fb-29d7-4ab9-bf68-09127d5a3d59)

- 后续更新计划：
继续丰富插件仓库, 提供更多种语言的插件.

**Comment by 521xueweihan** [comment]
@aooohan 我还在看项目，正在找项目亮点你就给关了，等我再看看。
网站后台显示未收录，我是可以反悔的。我正好看到你这里也提交了，我看的有点慢😅

**Comment by aooohan** [comment]
@521xueweihan 感谢大佬, 头大 : | , 推广太难了.  
https://juejin.cn/post/7326542703222571034
这是昨天写的针对golang的帖子, 里面有操作演示. 应该比这个issue里的全点,  后面又更新了好多特性功能. 还是看这个文章吧哈哈哈

**Comment by BushBiden** [comment]
你们不睡觉了吗？

**Comment by 521xueweihan** [comment]
@aooohan 加我微信：xueweihan，我帮你推广。

**Comment by 521xueweihan** [comment]
@aooohan 您推荐的项目，**已成功发布**在 [HelloGitHub 第 94 期](https://hellogithub.com/periodical/volume/94)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
