### ISSUE TITLE
【开源自荐】🎉Vue TSX Admin, 中后台管理系统开发的新方向

### ISSUE THREAD

**Issue by manyuemeiquqi** [521xueweihan/HelloGitHub#2667]
## 推荐项目

- 项目地址：https://github.com/manyuemeiquqi/vue-tsx-admin

- 类别：Vue Admin

- 项目标题：vue-tsx-admin 是一个免费开源的中后台管理系统模块，帮助你快速搭建起一个中后台前端项目。

- 项目描述：它使用了最新的前端技术栈，完全采用 Vue3 + TSX 的模式进行开发，提供了开箱即用的中后台前端解决方案，内置了 i18n 国际化解决方案，可配置化布局，主题色修改，权限验证，提炼了典型的业务模型。

- 亮点：
   1. 完全使用 JSX 进行开发，适合喜爱 JSX 模式的开发者
   2. 提供了开箱即用的中后台前端解决方案
   3. 解决了中后台模板开发方式的痛点，比如 表格自定义列冗余、难以同一文件构建声明式弹窗、抽离组件需要同时关注 script 跟 模板的缺点
   4. 同类开发模式的开源后台管理模板鲜有

- 示例代码：（可选）
```js
    const handleError = () => {
      Modal.error({
        title: () => <div>error</div>,
        content: () => (
          <p>
            <span>Message can be error</span>
            <IconErro />
          </p>
        )
      })
    }
```

- 后续更新计划：
   - 进行 bug 修复，项目开箱即用即可，不累加过多功能

**Comment by wisdom661** [comment]
Hello

**Comment by 521xueweihan** [comment]
@manyuemeiquqi 此类项目月刊收录较多，所以你的项目暂不收录。

不是项目本身的问题，感谢理解。
