### ISSUE TITLE
【开源自荐】将 Github Copilot 请求转换为 ChatGPT 请求，免费使用 GPT-4 模型

### ISSUE THREAD

**Issue by aaamoon** [521xueweihan/HelloGitHub#2669]
## 推荐项目

- 项目地址：https://github.com/aaamoon/copilot-gpt4-service

- 类别：Go

- 项目标题：将 Github Copilot 转换为 ChatGPT

- 项目描述：通过抓包我们可以发现 Github Copilot Chat 其实底层是调用 OpenAI 的 ChatGPT 接口，那么我们就可以将 Github Copilot Chat 的请求转换为 ChatGPT 请求。

- 亮点：只要我们拥有 Github Copilot 账号，就能无限制使用 ChatGPT 的 GPT-4 模型。

1. 实现原理
![实现原理](https://raw.githubusercontent.com/aaamoon/copilot-gpt4-service/master/assets/principle.png)

2. 使用步骤
![步骤1](https://raw.githubusercontent.com/aaamoon/copilot-gpt4-service/master/assets/step1.png)

- 后续更新计划：长期更新

**Comment by 521xueweihan** [comment]
@aaamoon 我把你的项目放到本周的热点了，https://mp.weixin.qq.com/s/Ayr1fe436ZSrVnQkQk2FKA

本月的月刊再收录，坚持更新哈！

**Comment by aaamoon** [comment]
感谢

**Comment by 521xueweihan** [comment]
@aaamoon 有用户反馈获取 token Copilot 账号被封。
<img width="705" alt="image" src="https://github.com/521xueweihan/HelloGitHub/assets/8255800/3e414617-da8b-4b8e-ae8d-c52c821f42ac">

**Comment by aaamoon** [comment]
不推荐通过第三方获取token，项目里面有两种其他方法本地获取token

**Comment by aaamoon** [comment]
https://github.com/aaamoon/copilot-gpt4-service/blob/master/README_CN.md#%E8%8E%B7%E5%8F%96-copilot-token

**Comment by 521xueweihan** [comment]
@aaamoon 好的，已在月刊的描述中进行提醒。

**Comment by 521xueweihan** [comment]
@aaamoon 您推荐的项目，**已成功发布**在 [HelloGitHub 第 94 期](https://hellogithub.com/periodical/volume/94)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

**Comment by You0** [comment]
仓库被和谐了
