### ISSUE TITLE
【开源自荐】GPUPixel 跨平台实时美颜特效库 - 可达到商业级美颜效果

### ISSUE THREAD

**Issue by gezhaoyou** [521xueweihan/HelloGitHub#2675]
## 推荐项目

- 项目地址：https://github.com/pixpark/gpupixel

- 类别：C++ | Java | Objective-C

- 项目标题：
跨平台实时美颜滤镜库, 可达到商业级美颜效果

- 项目描述：
  1. GPUPixel是一个由C++11编写的高性能图像和视频处理库, 基于GPU, 内置美颜特效滤镜, 效果可以达到商业级别。
  2. 支持的平台包括iOS, Mac, Android, 未来还会支持Windows和鸿蒙。
  3. 支持的效果包括：**磨皮、美白、瘦脸、大眼、口红、腮红**等
  4. 便于为直播和WebRTC等音视频场景提供美颜滤镜能力，代码完全开源.

- 亮点：
  1. 跨平台，GPUImage仅支持苹果；
  2. 效果优秀，可以达到商用级别；
  3. 高性能，C++11编写
 
- 截图： 
 ## 效果预览
👉 **视频: <a href="https://youtu.be/9BY1Qx1NEPs" target="_blank">YouTube</a> | <a href="https://www.bilibili.com/video/BV1xQ4y1L7Fh/?share_source=copy_web&vd_source=46adcb1014fa989cfcbb4cc1e866831e" target="_blank">BiliBili</a>** 

  <img width="650" alt="Xnip2024-01-16_23-34-17" src="https://github.com/Wechat-ggGitHub/Awesome-GitHub-Repo/assets/15272757/9189120e-67e9-4d3a-825f-2fb0d998b7db">
  框架：
  <img width="650" alt="arch" src="https://github.com/ruanyf/weekly/assets/15272757/d08982fe-0c90-4b2f-b4e6-5d9d3763399d">

- 后续更新计划：
  1. 支持Windows端；
  2. 人脸关键点识别库替换为 VNN或MNN

**Comment by 521xueweihan** [comment]
@gezhaoyou 您推荐的项目，**已成功发布**在 [HelloGitHub 第 94 期](https://hellogithub.com/periodical/volume/94)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

更多详情尽在：

最后，欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

**Comment by gezhaoyou** [comment]
> @gezhaoyou 您推荐的项目，**已成功发布**在 [HelloGitHub 第 94 期](https://hellogithub.com/periodical/volume/94)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
> 
> 更多详情尽在：
> 
> 最后，欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

好的非常感谢~

**Comment by gezhaoyou** [comment]
目前项目已添加windows和linux系统支持，正在增加 python 和 webassembly 封装支持

**Comment by forrest-lam** [comment]
什么时候支持python啊
