### ISSUE TITLE
没有rss之类的订阅方式的吗？

### ISSUE THREAD

**Issue by NeverMoes** [521xueweihan/HelloGitHub#268]
为什么我翻了半天不知道在哪里可以邮件或者rss的方式订阅的呢。

**Comment by JameJJ** [comment]
你好，目前暂不支持RSS订阅，我们会尽快打通其他渠道以及RSS功能。十分感谢对HelloGithub项目的关注

**Comment by ListenLove** [comment]
虽然我也很想帮帮忙，但奈何编程能力还太菜，现在只能在一边摇旗呐喊，加油XD

**Comment by JameJJ** [comment]
@ListenLove 一起加油，一起加油😂

**Comment by 521xueweihan** [comment]
@ListenLove 好的，撸起袖子干！

**Comment by iShawnWang** [comment]
Hoping i can subscribe with email, i suggest service like `Mailchimp` ~

**Comment by 521xueweihan** [comment]
@NeverMoes 已支持 RSS 订阅功能：https://hellogithub.com/rss

**Comment by ali101110** [comment]
> Hoping i can subscribe with email, i suggest service like `Mailchimp` ~

its test

**Comment by ZhuPeng** [comment]
推荐一个订阅方式，扫描下方二维码，页面底部有订阅按钮，后续可以通过微信的服务通知订阅更新
![image](https://user-images.githubusercontent.com/4994339/57193503-64382e80-6f6e-11e9-99ef-2b4de3b06fd0.png)

小程序是开源的，有任何问题和意见可以直接提 Issue 反馈：[GitHub Trending Hub](https://github.com/ZhuPeng/mp-githubtrending)

**Comment by rea1shane** [comment]
RSS 体验不是很好，我用 Reeder 5 抓取不到详情与图片
