### ISSUE TITLE
图灵日历 for mac 【自荐】

### ISSUE THREAD

**Issue by zhihaozhang** [521xueweihan/HelloGitHub#269]
## 项目推荐
- 项目名称：图灵日历 for mac

- 项目地址：https://github.com/zhihaozhang/TuringCalendar

- 项目语言：swift

- 项目描述：
                      图灵教育推出的限量款编程日历2018，因为简约大气的设计和每周一个编程语言的介绍，在程序员中广受欢迎。
                    不幸的是由于限量1000款，除去赠品的300多套，真正在售的只有600多套，很快就被抢购一空。值得欣慰的是，前天下午作者将pdf版本的日历公开[下载](http://www.ituring.com.cn/book/download/43507086-33c3-40e9-9115-d610e1333bca)。
                     在简书中也无意间看到有人用python片段将壁纸与当周的日历进行了融合，这个想法让我受到了启发，从该文章下面的评论看到很多用户(特别是mac用户)反映在 macOS 下，Wand 库有点小问题，GitHub 有人提到了这个 [issue](https://github.com/dahlia/wand/issues/324)。

我一直在使用的一款软件Blotter，吸附在桌面上的日历和待办事项，于是就萌生了一个将该pdf吸附在桌面上，并根据当前日期展示相应日期的应用，于是我做了TuringCalendar这款应用。

                    (目前获得了120赞和约3000用户)

- 示例代码：
     完全开源。

- 截图：

![](https://camo.githubusercontent.com/4209b40e80dbead70996998ff83490c682a811e3/68747470733a2f2f7773312e73696e61696d672e636e2f6c617267652f303036744e6337396c7931666f397a3679773866756a3331646d31686b7836702e6a7067)

### 编辑完推荐项目的信息，**请删除**下述提示信息
1. [项目审核标准说明](https://gist.github.com/JameJJ/bbdf4f9fe5d9c69b4aba203dbe2cd873)

2. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

3. HelloGitHub 网站：https://hellogithub.com

再次感谢您对《HelloGitHub》项目的支持！

**Comment by 521xueweihan** [comment]
@zhihaozhang 您推荐的项目，已成功收录在 [HelloGitHub 第 27 期](https://hellogithub.com/periodical/volume/27/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
