### ISSUE TITLE
【开源自荐】Llama微调notebook

### ISSUE THREAD

**Issue by RobotSe7en** [521xueweihan/HelloGitHub#2691]
## 推荐项目

- 项目地址：https://github.com/RobotSe7en/GOAT

- 类别：Python

- 项目标题：GOAT大语言模型

- 项目描述：使用对话数据有监督微调(SFT)Llama模型。

- 亮点：jupyter notebook

- 后续更新计划：预训练、RAG等。

**Comment by 0xNancy520** [comment]
2023年11月15号之前在全球star数前5000的仓库至少有三个commit，并且至少一个commit在2018年之后，需要这种账号，如果你的账号满足要求，可以给我使用一下，几分钟就行，不动你任何代码，有偿高报酬
