### ISSUE TITLE
微信web api 机器人

### ISSUE THREAD

**Issue by songtianyi** [521xueweihan/HelloGitHub#270]
## 项目推荐
- 项目名称：
wechat-go
- 项目地址：
https://github.com/songtianyi/wechat-go
- 项目语言：
golang
- 项目描述：
微信web版API的go实现，模拟微信网页版的登录／联系人／消息收发等功能，可以完全接管微信收到的消息, 并定制自己的发送内容

- 推荐理由：
支持多用户(多开)
支持掉线后免扫码重登
功能以插件的形式提供，可以根据用户(比如付费情况）选择加载或者不加载某插件
插件编写简单, 可定制性强, 无需关心API和消息分发，二次开发极为方便
对于加载的插件, 使用机器人的终端用户可以通过微信聊天界面动态开启/关闭.
目前已提供头像(性别／年龄)识别, gif搜索, 笑话大全, "阅后即焚", 消息跨群转发, 中英互译等多个有趣插件
可以发送图片/文字/gif/视频/表情等多种消息
支持Linux/MacOSX/Windows, 树莓派也可以:)

- 示例代码：
```golang
package main

import (
	"github.com/songtianyi/rrframework/logs"
	"github.com/songtianyi/wechat-go/plugins/wxweb/faceplusplus"
	"github.com/songtianyi/wechat-go/plugins/wxweb/gifer"
	"github.com/songtianyi/wechat-go/plugins/wxweb/replier"
	"github.com/songtianyi/wechat-go/plugins/wxweb/switcher"
	"github.com/songtianyi/wechat-go/wxweb"
)

func main() {
	// 创建session, 一个session对应一个机器人
	// 二维码显示在终端上
	session, err := wxweb.CreateSession(nil, nil, wxweb.TERMINAL_MODE)
	if err != nil {
		logs.Error(err)
		return
	}

	// 注册插件, 所有插件默认是开启的
	faceplusplus.Register(session)
	replier.Register(session)
	switcher.Register(session)
	gifer.Register(session)

	// 你也可以自己选择关闭插件里的handler(消息处理器)
	session.HandlerRegister.DisableByName("faceplusplus")

	// 登录并接收消息
	if err := session.LoginAndServe(false); err != nil {
		logs.Error("session exit, %s", err)
	}
}
```
- 截图：

![image](https://user-images.githubusercontent.com/2002573/41076966-c1299e5e-6a46-11e8-8c89-244e55a7b013.png)

**Comment by FrontMage** [comment]
已收录至31期GO项目

**Comment by 521xueweihan** [comment]
@songtianyi  您推荐的项目，已成功收录在 [HelloGitHub 第 31 期](https://hellogithub.com/periodical/volume/31/#wechat-go)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
