### ISSUE TITLE
丑丑头像生成器

### ISSUE THREAD

**Issue by puzzle9** [521xueweihan/HelloGitHub#2714]
开源地址 https://github.com/txstc55/ugly-avatar
预览地址 https://txstc55.github.io/ugly-avatar/

抽象 还是抽象 还是手撮的

**Comment by 521xueweihan** [comment]
有够丑的

**Comment by vannvan** [comment]
真的好丑(蚌埠住了～)

**Comment by cllam1234548** [comment]
雀食丑哈哈
