### ISSUE TITLE
【开源自荐】 适合Archlinux的高度DIY的IoT安全仿真工具

### ISSUE THREAD

**Issue by N1nEmAn** [521xueweihan/HelloGitHub#2717]
## 推荐项目

- 项目地址：https://github.com/N1nEmAn/Sevnup

- 类别：shell，python

- 项目标题：Sevnup MIPSel 固件模拟脚本

- 项目描述：当前FirmAE和FAT等仿真工具非常方便，但是有时候一些新的固件需要更加高度的DIY仿真。本开源项目基于Archlinux,直接从qemu层面配置，启动即可进入文件系统，不需要自己手动操作，并且保留了高度的自定义空间。也欢迎各位贡献其他系统版本。IoTSec FoR FUN！

- 亮点：
    1. 高度的自定义性质，与使用人员相结合，能够适应更多的固件
    2. Archlinux发烧玩家狂喜！

- 截图：复现磊科路由器的漏洞
![image](https://github.com/GitHubDaily/GitHubDaily/assets/118088443/70b29624-d56b-459f-aa69-0d1b7a55aeb6)
![image](https://github.com/GitHubDaily/GitHubDaily/assets/118088443/dfc52097-8e94-48a2-834e-6eeedef28c34)
![image](https://github.com/GitHubDaily/GitHubDaily/assets/118088443/0cf45988-7840-4657-a531-a5dd74d3f71c)
![image](https://github.com/GitHubDaily/GitHubDaily/assets/118088443/affb3205-98ff-4952-96ab-1c719241c3f3)
![成功复现磊科路由器漏洞](https://github.com/GitHubDaily/GitHubDaily/assets/118088443/207b386f-86aa-4f46-b62e-184ee0515575)

- 后续更新计划：
    1. 继续更新脚本，使自动化程度进一步提高，但是不降低可DIY性。
    2. 更新支持Arm、risc-v等架构的版本。

**Comment by 521xueweihan** [comment]
@N1nEmAn 领域太小众了，不好意思。
