### ISSUE TITLE
wechat-autoreply

### ISSUE THREAD

**Issue by giscafer** [521xueweihan/HelloGitHub#272]
## 项目推荐
- 项目名称：wechat-autoreply

- 项目地址：https://github.com/giscafer/wechat-autoreply

- 项目语言：中文

- 项目描述：
web微信自动回复，（web微信！！！非微信公众号，不管是在微信群聊还是微信私聊中，触发关键词，都会出现自动回复）, 基于node.js

- 推荐理由：
自己冲着有趣写的

- 截图：

![](https://github.com/giscafer/wechat-autoreply/raw/master/screenshot/screenshot2.jpg)

**Comment by 521xueweihan** [comment]
@giscafer 该项目暂时不能收录，建议持续优化。 #271
