### ISSUE TITLE
404 not found 项目链接已经失效！

### ISSUE THREAD

**Issue by eleveyuan** [521xueweihan/HelloGitHub#2741]
最新一期（[第97期](https://github.com/521xueweihan/HelloGitHub/blob/master/content/HelloGitHub97.md#%E5%85%B6%E5%AE%83)）
<img width="1029" alt="image" src="https://github.com/521xueweihan/HelloGitHub/assets/85916131/2b4b2e8c-ecf2-43db-bc14-46414cd90c33">
点击进去链接都没了。。。
<img width="915" alt="image" src="https://github.com/521xueweihan/HelloGitHub/assets/85916131/bce741d1-0ce7-416e-9d22-5ed02c695a2d">

建议28号提交的时候项目是否需要最后再审查下。

**Comment by 521xueweihan** [comment]
@eleveyuan 该项目的作者正在整理其项目

<img width="584" alt="image" src="https://github.com/521xueweihan/HelloGitHub/assets/8255800/0a8b4eeb-4978-4f9b-b7f2-5390720ee2a0">
