### ISSUE TITLE
500lines：这个是一本书，用简短的code去实现一个个并不trivial的idea，很适合学习

### ISSUE THREAD

**Issue by franklingu** [521xueweihan/HelloGitHub#275]
## 项目推荐
- 项目名称：
500lines
- 项目地址：
https://github.com/aosabook/500lines
- 项目语言：
Python,lisp, JS etc
- 项目描述：
> This is the source for the book 500 Lines or Less, the fourth in the Architecture of Open Source Applications series.
- 推荐理由：
一些大牛们写的短小但是很有意思的application，适于学习内部实现
- 示例代码：

**Comment by 521xueweihan** [comment]
@franklingu 该项目已推荐过，[第10期](https://hellogithub.com/periodical/volume/10/)
