### ISSUE TITLE
推荐 containerfs

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [521xueweihan/HelloGitHub#276]
## 项目推荐
- 项目名称：
containerfs
- 项目地址：
https://github.com/tiglabs/containerfs
- 项目语言：
golang
- 项目描述：
多实例分布式文件系统
- 推荐理由：
我写的，在京东内部大规模应用
- 示例代码：
[guide](https://github.com/tiglabs/containerfs/blob/master/doc/guide.md)
- 截图：
![image](https://user-images.githubusercontent.com/10624990/41398562-5bd13856-6fea-11e8-9c2d-e9c0ca626078.png)
![image](https://user-images.githubusercontent.com/10624990/41398612-7936908a-6fea-11e8-8a6a-973bafbc42a2.png)

**Comment by 521xueweihan** [comment]
@zhengxiaochuan-3 非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
