### ISSUE TITLE
v-region 基于 Vue2 的简洁、易用的中国行政区划选择器

### ISSUE THREAD

**Issue by TerryZ** [521xueweihan/HelloGitHub#278]
## 项目推荐
- 项目名称：v-region

- 项目地址：[https://github.com/TerryZ/v-region](https://github.com/TerryZ/v-region)

- 项目语言：javascript / Vue2

- 项目描述：基于 **Vue2** 的简洁、易用的中国行政区划选择器，包含常规表单下拉列表模式和UI下拉选择器模式；支持 “省/直辖市” - “市” - “区/县” - “乡/镇/街道”4级行政级别

- 推荐理由：包含常规表单下拉列表模式和UI下拉选择器模式；支持 “省/直辖市” - “市” - “区/县” - “乡/镇/街道”4级行政级别

- 示例代码：

template

```vue
<template>
    <v-region @values="regionChange" class="form-control"></v-region>
</template>
```
script

```vue
export default {
    methods:{
        //receive selected region data
        regionChange(data){
            console.log(data);
        }
    }
};
```

- 截图：

*form element mode*

![base](https://terryz.gitee.io/image/v-region/v-region-base.png)

*dropdown selector mode*

![ui](https://terryz.gitee.io/image/v-region/v-region-ui.png)

**Comment by 521xueweihan** [comment]
@TerryZ   您推荐的项目，已成功收录在 [HelloGitHub 第 27 期](https://hellogithub.com/periodical/volume/27/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by TerryZ** [comment]
你好，我看了你们发布的 27 期的内容了，如果项目只能贴一张截图，能不能把 `v-region` 的截图换成贴子里的第二张啊，有劳了

**Comment by TerryZ** [comment]
而且显示代码的部分变成了

![image](https://user-images.githubusercontent.com/854406/41981067-a631b34c-7a5a-11e8-8464-2a6c391030f2.png)

**Comment by 521xueweihan** [comment]
@TerryZ 您好，图片已经修改。关于网站上的示例代码问题（github 项目中展示无此问题），修复后会在这里给出回复。

再次感谢您的支持。

**Comment by TerryZ** [comment]
感谢修改，谢谢

**Comment by TerryZ** [comment]
后续还会有更多个人原创插件来投稿

**Comment by 521xueweihan** [comment]
@TerryZ 完美

**Comment by 521xueweihan** [comment]
@TerryZ 示例代码展示已修复。
https://hellogithub.com/periodical/volume/27/#v-region

**Comment by TerryZ** [comment]
感谢处理，已经正常了，谢谢

**Comment by TerryZ** [comment]
@521xueweihan 请问申请的 Star 是否有数量限制，我新做的项目 Star 比较少，就不知道能不能申请上月报
