### ISSUE TITLE
推荐项目--ZeroNet

### ISSUE THREAD

**Issue by is1nn0n** [521xueweihan/HelloGitHub#28]
ZeroNet——[站点][1]：去中心化的网站  [DEMO 与 截图][2]

刚发现这个列表, 很喜欢
既然都有 XX-Net 了, 所以推荐下这个

[1]: https://github.com/HelloZeroNet/ZeroNet
[2]: https://github.com/HelloZeroNet/ZeroNet/blob/master/README-zh-cn.md

**Comment by erguotou520** [comment]
不是太懂这个，给讲讲他的实际用途？什么场景使用？解决什么问题？

**Comment by is1nn0n** [comment]
...  更自由地获取与发布内容

**Comment by 521xueweihan** [comment]
不好意思，请重新[创建 issues](https://github.com/521xueweihan/HelloGitHub/issues/new)，根据推荐项目的模版，规范推荐项目格式、完善信息。
