### ISSUE TITLE
完全遵循SemVer规范的全自动NPM包发布工具 Relix

### ISSUE THREAD

**Issue by PengJiyuan** [521xueweihan/HelloGitHub#281]
## 项目推荐
- 项目名称：relix

- 项目地址：https://github.com/PengJiyuan/relix

- 项目语言：Javascript / NodeJs

- 项目描述：全自动 npm 包发布工具。自动根据[NPM 官方使用的 Semver规范](https://semver.org/)来控制版本号 ,  即 **MAJOR.MINOR.PATCH-BETA**，发布流程全自动化。

- 推荐理由: **relix**全自动的解决了发布npm包的所有的繁琐的过程。relix 会自动根据[Semver规范](https://semver.org/)帮你生成版本号，然后更新package.json。而且会自动根据version修改的类型来生成Commit message。然后relix会自动帮你打tag，推tag到github。最后帮你把完全标准化的一个包推到NPM！ **这个流程是全自动化的！**

- 示例代码：

```bash
npm install relix -g
relix --patch
```

- 截图：

![2018-06-27 5 20 47](https://user-images.githubusercontent.com/19399269/41965165-88cfe1ce-7a2e-11e8-9978-a8f092e8f55a.png)

**Comment by PengJiyuan** [comment]
已更新中文文档。

**Comment by 521xueweihan** [comment]
@PengJiyuan 
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
