### ISSUE TITLE
通用的后台管理系统(权限 登录 作业管理) java项目

### ISSUE THREAD

**Issue by yalunwang** [521xueweihan/HelloGitHub#282]
## 项目推荐
- 项目名称：
commonAdmin
- 项目地址：
https://github.com/GodGrounp/commonAdmin
- 项目预览地址
http://book.yalunwang.com/SSM/
用户名 :yalunwang
密码 ： 123456
- 项目语言：
java
- 项目描述：
通用的后台管理系统(权限 登录 作业管理)
spring springmvc mybatis项目
spring 4.2
shiro
layui
- 推荐理由：
可以作为后台的通用权限管理,也可以作为初学者学习SSM框架的很好的例子。

- 示例代码：

- 截图：

![default](https://user-images.githubusercontent.com/13617882/42013903-042310f0-7ad2-11e8-831b-60e21f846a21.PNG)

**Comment by 521xueweihan** [comment]
@yalunwang 已推荐过类似项目，您推荐的项目暂不能收录到月刊中。

**Comment by yalunwang** [comment]
好的看到了，谢谢。楼主在博客园发布第二期的时候开始关注的，现在更新这么多期还在坚持，到现在很多人都在关注，再下非常佩服。证明只要坚持做一件事情迟早会有收获，向楼主学习，加油。 @521xueweihan

**Comment by 521xueweihan** [comment]
@yalunwang 谢谢您的肯定和支持，但到您的回复让我知道我的付出是有价值的！

这个项目能够一只走到现在，少不了大家的支持和鼓励！我们会持续做下去，让好玩的开源项目被更多人知道。🙏
