### ISSUE TITLE
2018 FIFA 世界杯 3D H5 页面

### ISSUE THREAD

**Issue by JackGit** [521xueweihan/HelloGitHub#283]
## 项目推荐
- 项目名称：2018 FIFA 世界杯 3D H5 页面

- 项目地址：https://github.com/JackGit/fifa

- 项目语言：Vue.js three.js

- 项目描述：2018 FIFA 世界杯 3D H5 页面

- 推荐理由：新颖有趣的 3D 互动阅读体验

- 示例代码：

- 截图：![](http://qiniu.jackyang.me/fifa/screenshot/fifa_screenshot_01.jpg)

**Comment by 521xueweihan** [comment]
@JackGit  该项目暂不能收录到月刊中。推荐标准请参考 #271 

希望您能够继续推荐有意思、入门级项目，再次感谢。
