### ISSUE TITLE
基于Laravel5.6+Vue2+elementUI2搭建的单页面个人博客系统，持续更新中。。

### ISSUE THREAD

**Issue by ouhaohan8023** [521xueweihan/HelloGitHub#284]
## 项目推荐
- 项目名称：个人博客系统

- 项目地址：https://github.com/ouhaohan8023/laravel

- 项目语言：PHP

- 项目描述：基于Laravel5.6+Vue2+elementUI2搭建的单页面个人博客系统，持续更新中。。

- 推荐理由：单页面博客系统，将前端最火框架Vue2.0和PHP最火框架Laravel进行了融合使用，适合新手创建博客，并开始前后端折磨之旅

- 示例代码：https://www.ohh.ink/#/

- 截图：![首页](http://pa6zwc1z4.bkt.clouddn.com/ohhink1.png)
![登陆](http://pa6zwc1z4.bkt.clouddn.com/ohhink2.png)

**Comment by 521xueweihan** [comment]
@ouhaohan8023  该项目暂不能收录到月刊中。推荐标准请参考 #271 

希望您能够继续推荐有意思、入门级项目，再次感谢。
