### ISSUE TITLE
【开源自荐】基于 eBPF 的网络问题排查命令行工具

### ISSUE THREAD

**Issue by hengyoush** [521xueweihan/HelloGitHub#2849]
## 推荐项目

- 项目地址：
https://github.com/hengyoush/kyanos

- 类别：C、Go

- 项目标题：Kyanos —— 一个基于eBPF的网络问题分析工具

- 项目描述：
Kyanos 是一个基于eBPF的网络问题分析工具，你可以用它来抓取业务请求，比如HTTP请求、Redis请求、MYSQL请求等，还可以帮你分析异常链路，快速排查业务故障，并且拥有良好的兼容性，大多数情况下无需任何依赖一行命令即可开始分析。

- 亮点：
  - 可根据进程id/容器id/pod名称抓包。
  - 内核耗时细节探测，可以知道请求数据从进程发送到网卡的耗时，也能知道响应从网卡读取到进程花费的耗时。
  - 可聚合分析，比如一行命令就可以找到最慢的HTTP请求到了哪些服务端，找到哪些请求的占用的带宽最大。
  - SSL 加密流量自动解密，目前支持 openssl 和 gotls。
  - 零依赖，无任何存储依赖，也无需安装其他分析软件如wireshark，就地分析。

- 截图：
一行命令找到最慢的 HTTP 请求：
![kyanos-demo](https://github.com/user-attachments/assets/650d694d-ebe8-4d94-aa53-da168fb97b1b)

内核耗时细节，可以看到请求和响应到达网卡的时间，甚至可以看到从容器网卡到宿主机网卡的耗时：
![timedetail](https://github.com/user-attachments/assets/fe606884-6006-4f6f-81c7-59bdde54b935)

- 后续更新计划：
  - 支持更多的应用层协议：HTTP2、GRPC、KAFKA、AMQP等。
  - 支持 K8s 复杂网络环境下的网络分析。
  - 增加内核的丢包、TCP重传、TCP传输Buffer等事件的采集。

**Comment by 521xueweihan** [comment]
@hengyoush 已收录，方便的话可以认领下，项目README将展示 HelloGitHub 推荐的徽章，并可以积累用户的评价。
