### ISSUE TITLE
無視簡繁日異體字的 regexp

### ISSUE THREAD

**Issue by bluelovers** [521xueweihan/HelloGitHub#285]
## 项目推荐
- 项目名称：regexp-cjk
- 项目地址：https://github.com/bluelovers/regexp-cjk
- 项目语言：javascript
- 项目描述：這是一個無視簡繁日異體字的 regexp
- 推荐理由：自肥
- 示例代码：https://github.com/bluelovers/regexp-cjk/blob/master/README.md
- 截图：

**Comment by 521xueweihan** [comment]
@bluelovers  非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
