### ISSUE TITLE
Gio.js: 一个基于 Three.js 的 Web3D 地球数据可视化库 [自荐]

### ISSUE THREAD

**Issue by syt123450** [521xueweihan/HelloGitHub#286]
## 项目推荐
- 项目名称：
Gio.js
- 项目地址：
https://github.com/syt123450/giojs
- 项目语言：
Javascript
- 项目描述：
Gio.js 是一个基于 Three.js 的 web 3D 地球数据可视化的开源组件库。使用 Gio.js 的网页应用开发者，可以快速地以申明的方式创建自定义的 Web3D 数据可视化模型，添加数据，并且将其作为一个组件整合到自己的应用中。支持静态dom，React和微信小程序。
- 推荐理由：
这个库的开发是受到 Google 2012 Info 大会上的项目世界武器贩卖可视化的启发，该项目开发者是 Google 员工 Michael Chang。使用 Gio.js 就可以快速构建这种炫酷的 3D 模型，并以此为基础进行深入地开发。Gio.js 具有以下的特点：
  * 易用性 -- 仅使用 4 行 Javascript 即可创建 3D 地球数据可视化模型
  * 定制化 -- 使用 Gio.js 提供的丰富的 API 来创建自定义样式的 3D 地球
  * 现代化 -- 基于 Gio.js 构建高交互、跨平台、自适应的现代化 3D 前端应用
- 示例代码：

在 HTML 页面中添加了 Threejs 和 Giojs 依赖:
```
<!DOCTYPE HTML>
<html>
<head>

  <!-- 引入 three.js -->
  <script src="three.min.js"></script>

  <!-- 引入 Gio.js -->
  <script src="gio.min.js"></script>

</head>
<body>

  <!-- 创建一个 div 作为 Gio 的绘制容器 -->
  <div id="globalArea"></div>

</body>
</html>
```
在页面中添加以下 Javascript 代码来初始化 Gio 地球：
```
<script>

    // 获得用来承载Gio地球的容器
    var container = document.getElementById( "globalArea" );

    // 创建 Gio 控制器
    var controller = new GIO.Controller( container );

    // 添加数据
    controller.addData( data );

    // 初始化并渲染地球模型
    controller.init();

</script>
```

- 截图：

  * gif效果图：
 <img src="https://raw.githack.com/syt123450/giojs/master/assets/readme/Gio.gif"/>

  * CodePen在线示例：[链接](https://codepen.io/collection/DkBobG/)

  * 官网首页截图：http://giojs.org

<img width="1248" alt="2018-07-01 9 16 15" src="https://user-images.githubusercontent.com/7977100/42134734-098dafba-7d74-11e8-90b0-baf7622790a8.png">

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 34 期](https://hellogithub.com/periodical/volume/34/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
