### ISSUE TITLE
[Android]一个页面切换动画库MTransition[自荐]

### ISSUE THREAD

**Issue by HJ-Money** [521xueweihan/HelloGitHub#288]
## 项目推荐
- 项目名称：MTransition

- 项目地址：https://github.com/HJ-Money/MTransition

- 项目语言：Java

- 项目描述：MTransition是一个Android上的Activity切换动画库，它可以让一些复杂的、自定义的Activity切换动画更加简单地实现出来，节省开发成本。

- 推荐理由：它能仅用少量实现一些十分复杂并且高度自定义的Activity过场动画，同时能支持跟手操作动画

- 示例代码：https://github.com/HJ-Money/MTransition/blob/master/README_cn.md

- 截图：https://github.com/HJ-Money/MTransition/blob/master/Introduction/1.gif
https://github.com/HJ-Money/MTransition/blob/master/Introduction/2.gif
https://github.com/HJ-Money/MTransition/blob/master/Introduction/3.gif

**Comment by 521xueweihan** [comment]
@HJ-Money  您推荐的项目，已成功收录在 [HelloGitHub 第 28 期](https://hellogithub.com/periodical/volume/28/#MTransition)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
