### ISSUE TITLE
桌面版脑图（百度脑图离线版，思维导图工具）开箱即用，跨平台支持 Windows/Linux/Mac OS

### ISSUE THREAD

**Issue by topcss** [521xueweihan/HelloGitHub#289]
## 项目推荐
- 项目名称：桌面版脑图 (DesktopNaotu)

- 项目地址：(https://github.com/NaoTu/DesktopNaotu)

- 项目语言：Javascript

- 项目描述：桌面版脑图是基于百度脑图的本地化版本，帮助你在没有互联网环境的情况下，依然可以使用脑图工具。

- 推荐理由：
  - **有用户加群的备注是这样填的：觉得你们很酷啊！**
  - 离线版，意味着没有隐私顾虑，也可以在内网运行。
  - 相比于在线版，很多人常常抱怨数据丢失，服务器上不去，本地如丝滑般流畅。

- 截图：
![kmimage](https://user-images.githubusercontent.com/2252451/42300568-ac1c13e4-8043-11e8-9585-5dcc4a4ba6f0.png)

**Comment by 521xueweihan** [comment]
@topcss   您推荐的项目，已成功收录在 [HelloGitHub 第 28 期](https://hellogithub.com/periodical/volume/28/#DesktopNaotu)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
