### ISSUE TITLE
cockroach 爬虫：又一个 java 爬虫实现[自荐]

### ISSUE THREAD

**Issue by zhangyingwei** [521xueweihan/HelloGitHub#290]
## 项目推荐
- 项目名称：cockroach 爬虫：又一个 java 爬虫实现

- 项目地址：https://github.com/zhangyingwei/cockroach

- 项目语言：Java

- 项目描述：一个小巧、灵活、健壮的爬虫框架

- 推荐理由：创建一个爬虫也可以这么简单

- 示例代码：
```java
@EnableAutoConfiguration
public class CockroachApplicationTest {
    public static void main(String[] args) throws Exception {
        TaskQueue queue = TaskQueue.of();
        queue.push(new Task("http://blog.zhangyingwei.com"));
        CockroachApplication.run(CockroachApplicationTest.class,queue);
    }
}
```

- 截图：
![](https://camo.githubusercontent.com/ad4d3fd7b37206f4f9d07cef84fed246aafbdbc1/687474703a2f2f7574696c2e7a68616e6779696e677765692e636f6d2f2f636f636b726f6163682f312f636172626f6e2e706e67)

**Comment by 521xueweihan** [comment]
@zhangyingwei 您好，该项目暂不能收录到月刊中。推荐标准请参考 #271 

希望您能够继续推荐有意思、入门级项目，再次感谢。
