### ISSUE TITLE
一周用c++/opengl做一个minecraft

### ISSUE THREAD

**Issue by fuyingdi** [521xueweihan/HelloGitHub#292]
## 项目推荐
- 项目名称：
MineCraft-One-Week-Challenge
- 项目地址：
https://github.com/Hopson97/MineCraft-One-Week-Challenge
- 项目语言：
c++
- 项目描述：
一周用c++/opengl做一个minecraft
- 推荐理由：
很好的学习opengl的资料，还可以到youtube上看作者的视频

**Comment by 521xueweihan** [comment]
@fuyingdi 您好，是否有兴趣翻译成中文？这样受众面可以更大。

**Comment by fuyingdi** [comment]
您说的翻译是指视频还是什么呢？

**Comment by 521xueweihan** [comment]
@fuyingdi 我觉得是否可以先从工作量最小的 ReadMe 开始？如果效果好，是否能够会有更多人加入字幕的翻译组？😁
