### ISSUE TITLE
Zero-UI 美观好用的PC端组件库[自荐]

### ISSUE THREAD

**Issue by AlphaGo88** [521xueweihan/HelloGitHub#295]
## 项目推荐
- 项目名称：Zero-UI

- 项目地址：https://github.com/AlphaGo88/Zero-UI

- 项目语言：javascript

- 项目描述：美观好用的PC端组件库

- 推荐理由：丰富美观的组件，易用性高，使用简单，文档完整

- 示例代码：

- 截图：

### 编辑完推荐项目的信息，**请删除**下述提示信息
1. [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271)

2. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

3. HelloGitHub 网站：https://hellogithub.com

再次感谢您对《HelloGitHub》项目的支持！

**Comment by JameJJ** [comment]
如果可以出基于react或者vue的组件库，应该会更好....😂

**Comment by AlphaGo88** [comment]
react的，正在开发中..

**Comment by 521xueweihan** [comment]
@AlphaGo88 非常感谢您推荐项目，期待持续完善该项目。

**该项目暂不能收录到本期的 HelloGitHub 月刊中**

再次感谢您对 HelloGitHub 的支持 🙏
