### ISSUE TITLE
超分辨率图像重建

### ISSUE THREAD

**Issue by zhitao654321** [521xueweihan/HelloGitHub#296]
## 项目推荐
- 项目名称：super-resolution-SRDPNs-tensorflow

- 项目地址：https://github.com/zhitao654321/super-resolution-SRDPNs-tensorflow

- 项目语言：python

- 项目描述：利用深度学习网络，对于单幅低分辨率的图像进行重建，获得对应的高分辨率图像。

- 推荐理由：

- 示例代码：

- 截图：

### 编辑完推荐项目的信息，**请删除**下述提示信息
1. [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271)

2. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

3. HelloGitHub 网站：https://hellogithub.com

再次感谢您对《HelloGitHub》项目的支持！

**Comment by 521xueweihan** [comment]
@zhitao654321  您好，该项目暂不能收录到月刊中。推荐标准请参考 #271 

希望您能够继续推荐有意思、入门级项目，再次感谢。
