### ISSUE TITLE
Chinese-number-gestures-recognition

### ISSUE THREAD

**Issue by tz28** [521xueweihan/HelloGitHub#297]
## 项目推荐
- 项目名称：Chinese-number-gestures-recognition

- 项目地址：https://github.com/tz28/Chinese-number-gestures-recognition

- 项目语言：java

- 项目描述：基于卷积神经网络的数字手势识别安卓APP，识别数字手势0-10（The number gestures recognition Android APP based on convolutional neural network(CNN), which can recognize the gestures corresponding number 0 to 10）

- 推荐理由：自荐

- 示例代码：
```java
inferenceInterface.feed(inputName, inputdata, 1, IMAGE_SIZE, IMAGE_SIZE, 3);
//运行模型,run的参数必须是String[]类型
String[] outputNames = new String[]{outputName,probabilityName,outlayerName};
inferenceInterface.run(outputNames);
//获取结果
int[] labels = new int[1];
inferenceInterface.fetch(outputName,labels);
int label = labels[0];
float[] prob = new float[11];
inferenceInterface.fetch(probabilityName, prob);
```

- 截图：
![演示](https://raw.githubusercontent.com/tz28/Chinese-number-gestures-recognition/master/img/nighttime.jpg)
![演示](https://raw.githubusercontent.com/tz28/Chinese-number-gestures-recognition/master/img/%E5%A4%8D%E6%9D%82%E5%9C%BA%E6%99%AF%E7%A2%B0%E8%BF%90%E6%B0%94.jpg) 

### 编辑完推荐项目的信息，**请删除**下述提示信息
1. [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271)

2. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

3. HelloGitHub 网站：https://hellogithub.com

再次感谢您对《HelloGitHub》项目的支持！

**Comment by 521xueweihan** [comment]
@tz28   您好，该项目暂不能收录到月刊中。推荐标准请参考 #271 

希望您能够继续推荐有意思、入门级项目，再次感谢。
