### ISSUE TITLE
TGmeetup 一个搜集与整合技术类社群的专案

### ISSUE THREAD

**Issue by sufuf3** [521xueweihan/HelloGitHub#300]
## 项目推荐
- **项目名称：** TGmeetup

- **项目地址：** 
   - 主专案：https://github.com/TGmeetup/TGmeetup
   - Web & npm : https://github.com/TGmeetup/tgmeetup.js

- **项目语言：** python, JavaScript

- **项目后续更新计划：** 
加入更多国家的社群资讯
支援 python 的 CLI lite 版（使用 GitHub API 取得活动资讯的 CLI 版）
Web 介面改善
...

- **项目描述：** 一个搜集与整合技术类社群的专案，TGmeetup 搜集所有有关于社群的资讯，并透过社群的 Meetup 连结（如：Meetup，KKTIX ...），透过API拿取最新的活动资讯。让使用者取得社群资讯以及社群的活动资讯的专案。目前可以透过 CLI，npm，Calendarm，RSS 等方式来使用。

- **推荐理由：** 太多社群活动，想知道最近有什么社群举办的活动，可以透过一个工具来查找。不论身处国内外，都可以透过一个工具即时知道近期的活动资讯。

- 示例代码：无 

- 截图：
![](https://raw.githubusercontent.com/TGmeetup/TGmeetup/master/imgs/output.gif)

**Comment by 521xueweihan** [comment]
@sufuf3  您推荐的项目，已成功收录在 [HelloGitHub 第 29 期](https://hellogithub.com/periodical/volume/29/#TGmeetup)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
