### ISSUE TITLE
better-onetab 一个更好的onetab扩展[自荐]

### ISSUE THREAD

**Issue by cnwangjie** [521xueweihan/HelloGitHub#303]
## 项目推荐
- 项目名称：better-onetab

- 项目地址：https://github.com/cnwangjie/better-onetab

- 项目后续更新计划：https://github.com/cnwangjie/better-onetab/projects/1

- 项目描述：一个更好的onetab扩展

- 推荐理由：拥有更多的功能和更美观的界面, 采用webpack构建, 支持firefox

- 截图：

![image](https://user-images.githubusercontent.com/7459652/43685925-3850a1cc-98ef-11e8-9a44-79bf8c2d6cb7.png)

**Comment by 521xueweihan** [comment]
@cnwangjie 您推荐的项目，**已成功发布**在 [HelloGitHub 第 33 期](https://hellogithub.com/periodical/volume/33/#better-onetab)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
