### ISSUE TITLE
【swift项目】AVHider for macOS

### ISSUE THREAD

**Issue by zhihaozhang** [521xueweihan/HelloGitHub#305]
## 项目推荐
- 项目名称：FileHider-for-mac

- 项目地址：https://github.com/zhihaozhang/FileHider-for-mac

- 项目后续更新计划：

- 项目描述：将mac系统文件一键隐藏，支持文件选择器和Drag&Drop.

- 推荐理由：将*敏感/机密/少儿不宜*的文件对有机会瞟到你屏幕的人设为不可见，无论是*周围同事*还是给其他人*做ppt演讲*，都很实用。

- 示例代码：

- 截图：![](https://ws1.sinaimg.cn/large/aa2320a8ly1fnhbezm45wg20hs0dc7q5)

![](https://ws1.sinaimg.cn/large/aa2320a8ly1fnpohtbv10g21ls1ukb1l)

**Comment by 521xueweihan** [comment]
@zhihaozhang 看到项目名称，没忍住来手动点个赞

**Comment by zhihaozhang** [comment]
haha，搞个大新闻。

**Comment by zhihaozhang** [comment]
已经通过apple 审核，上架mac app store。

**Comment by 521xueweihan** [comment]
@zhihaozhang  您推荐的项目，已成功收录在 [HelloGitHub 第 30 期](https://hellogithub.com/periodical/volume/30/#FileHider-for-mac)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
