### ISSUE TITLE
【nodejs 项目】idomain 

### ISSUE THREAD

**Issue by Jon-Millent** [521xueweihan/HelloGitHub#306]
## 项目推荐
- 项目名称：idomain

- 项目地址： https://github.com/cmdboys/idomain

- 项目后续更新计划： 计划添加显示域名价格

- 项目描述： 命令行批量域名查询工具

- 推荐理由： 很方便的在命令行查域名

- 示例代码：  

```cmd
  >> idmain
  >> taobao.com
  >> taobao
```

- 截图：
![20180807_101314.gif](https://i.loli.net/2018/08/07/5b690176d1d59.gif)

**Comment by 521xueweihan** [comment]
@Jon-Millent  非常感谢您推荐项目。该项目是个非常实用的脚本，建议可以做一个实用脚本集合项目，如果配套一套教程，相信会更受欢迎。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
