### ISSUE TITLE
【vue项目】可以生成假红包等功能的app

### ISSUE THREAD

**Issue by Jon-Millent** [521xueweihan/HelloGitHub#307]
## 项目推荐
- 项目名称：faker

- 项目地址：https://github.com/Jon-Millent/faker

- 项目后续更新计划：暂无

- 项目描述：在线制作微信/支付宝红包，聊天，转账，余额，花呗等截图

- 推荐理由：在线就可以生成，无需下载客户端

- 示例代码：

- 截图：

![TIM截图20180808163531.png](https://i.loli.net/2018/08/08/5b6aab66000d3.png)
- 在线预览：
![8744cd5535ab70821895433d074788b7.png](https://i.loli.net/2018/08/08/5b6aaba85546b.png)

**Comment by 521xueweihan** [comment]
@Jon-Millent 图谋不轨、炫富必备的项目

**Comment by 521xueweihan** [comment]
@Jon-Millent  非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
