### ISSUE TITLE
【js项目】小米移动商城

### ISSUE THREAD

**Issue by Jon-Millent** [521xueweihan/HelloGitHub#309]
## 项目推荐
- 项目名称：小米移动商城

- 项目地址：https://github.com/Jon-Millent/mi-shop

- 项目后续更新计划：暂无

- 项目描述：使用vue制作的高仿小米商城，用户体验比较好。

- 推荐理由：真的很高仿哦

- 示例代码：无

- 截图：
![TIM截图20180809090522.png](https://i.loli.net/2018/08/09/5b6b936767470.png)
- 预览：
![a2c10bafe3ec9ad7d6937e1d4ae9e7b9.png](https://i.loli.net/2018/08/09/5b6b93b3d5d6c.png)

**Comment by 521xueweihan** [comment]
@xiaoymin 非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
