### ISSUE TITLE
推荐项目 -- knowledge-map

### ISSUE THREAD

**Issue by xiedacon** [521xueweihan/HelloGitHub#31]
[knowledge-map](https://github.com/nikitavoloboev/knowledge-map) - Search Interactive Mind Maps to learn anything

**Comment by 521xueweihan** [comment]
不好意思请重新[创建 issues](https://github.com/521xueweihan/HelloGitHub/issues/new)，根据推荐项目的模版，规范推荐项目格式、完善信息。
