### ISSUE TITLE
vitess

### ISSUE THREAD

**Issue by mds1455975151** [521xueweihan/HelloGitHub#310]
## 项目推荐
- 项目名称：vitess

- 项目地址：https://github.com/vitessio/vitess

- 项目后续更新计划：

- 项目描述：Vitess is a database clustering system for horizontal scaling of MySQL

- 推荐理由：go语言，与K8s最佳搭配的数据库集群软件

- 示例代码：
无

- 截图：
![image](https://user-images.githubusercontent.com/12950929/43989346-b8c705b4-9d7a-11e8-9d88-12a03d68b241.png)

**Comment by 521xueweihan** [comment]
@mds1455975151 非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，再次感谢您对 HelloGitHub 的支持 🙏
