### ISSUE TITLE
【swagger-bootstrap-ui】基于Swagger的前端UI实现

### ISSUE THREAD

**Issue by xiaoymin** [521xueweihan/HelloGitHub#311]
## 项目推荐
- 项目名称：【swagger-bootstrap-ui】基于Swagger的前端UI实现

- 项目地址：https://github.com/xiaoymin/Swagger-Bootstrap-UI

- 项目后续更新计划：优化发送请求细节、UI细节调整

- 项目描述：swagger-bootstrap-ui是Swagger的前端UI实现,目的是替换Swagger默认的UI实现Swagger-UI,使文档更友好一点儿....

- 推荐理由：后端在使用Spring技术栈的时候，针对rest接口，总是避免不了文档对接，而文档成了开发者最大的难题，庆幸Java开发人员有Swagger，但是Swagger的官网UI，Swagger-ui界面不论是美观上，还是易用上都难达到要求，swagger-bootstrap-ui是一个基于Swagger的前端UI实现，目的是替换Swagger的默认UI库Swagger-UI,让开发者给出一份美观、易用的开发者文档.

- 示例代码：

预览地址：http://swagger-bootstrap-ui.xiaominfo.com/doc.html

- 截图：

![debug](https://user-images.githubusercontent.com/7894406/44011064-e7162606-9ee8-11e8-934d-096bd917e52a.png)
![des](https://user-images.githubusercontent.com/7894406/44011065-e7db007a-9ee8-11e8-8d4e-1dc954a8b79d.png)

**Comment by 521xueweihan** [comment]
@xiaoymin 非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
