### ISSUE TITLE
drone

### ISSUE THREAD

**Issue by mds1455975151** [521xueweihan/HelloGitHub#312]
## 项目推荐
- 项目名称：drone

- 项目地址：https://github.com/drone/drone

- 项目后续更新计划：

- 项目描述：Drone 是一个基于 Docker的持续集成平台，使用 Go 语言编写

- 推荐理由：go语言项目

- 截图：
![image](https://user-images.githubusercontent.com/12950929/44067077-363437ce-9fa6-11e8-9650-283aaf43fb80.png)

**Comment by appleboy** [comment]
這個不錯，我在台灣狂推廣 Drone CI/CD，並且錄製 [Udemy 影片](https://www.udemy.com/devops-oneday)，目前也是 Drone maintainer 之一。

**Comment by FrontMage** [comment]
@mds1455975151 @appleboy 尝试了一下用drone + gogs自动化构建nodejs项目，构建时容器内部无法访问外网，暂时没调通，所以暂时没有推荐

**Comment by 521xueweihan** [comment]
@FrontMage

**Comment by appleboy** [comment]
@FrontMage 昨天 drone 作者才 Release v1.0 的代碼了。如果 drone + gogs 不能用，你可以試試看 drone + gitea 喔。

**Comment by FrontMage** [comment]
@appleboy 我再试一下，问题应该不在gogs，我这问题是drone用来构建项目的docker镜像内部无法访问npm，导致npm install失败，应该是drone的docker配置问题

**Comment by appleboy** [comment]
@FrontMage 中國訪問 npm 要改成國內鏡像啊

**Comment by FrontMage** [comment]
@appleboy cnpm也不work，根据我的尝试，应该是直接没有网，因为ping百度ping不通，curl也不行，都显示DNS无法解析，直接ping ip也不行，显示unreachable

**Comment by appleboy** [comment]
@FrontMage 先看看本機網路有無通？基本上都是跟著機器網路才是

**Comment by FrontMage** [comment]
@appleboy 是通的，所以我说是它docker配置有问题，我再试试

**Comment by FrontMage** [comment]
@appleboy 1.0构建完美，收录drone至36期发布

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 36 期](https://hellogithub.com/periodical/volume/36/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
