### ISSUE TITLE
【javascript项目】Github Issue 博客订阅工具

### ISSUE THREAD

**Issue by xiaosongxiaosong** [521xueweihan/HelloGitHub#313]
## 项目自荐
- 项目名称：IssueReader

- 项目地址：
项目地址：https://issuereader.github.io
源码地址：https://github.com/IssueReader/issue-reader-dva

- 项目后续更新计划：
1. 订阅管理
2. 基于仓库维度的文章列表
3. 博主推荐
4. issue 讨论显示

- 项目描述：
Github Issue 博客订阅工具

- 推荐理由：
Github Issue 博客订阅工具，提升学习效率

- 示例代码：
无

- 截图：
1. 所有文章
![image](https://user-images.githubusercontent.com/2703455/44128004-ee52b746-a072-11e8-990c-fbec21f9fef3.png)
2. 文章详情
![image](https://user-images.githubusercontent.com/2703455/44128014-fa4bfc9c-a072-11e8-8215-198750186315.png)
3. 收藏列表
![image](https://user-images.githubusercontent.com/2703455/44128032-13398af8-a073-11e8-8378-e5af4e48c9ed.png)

### 编辑完推荐项目的信息，**请删除**下述提示信息
1. [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271)

2. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

3. HelloGitHub 网站：https://hellogithub.com

再次感谢您对《HelloGitHub》项目的支持！

**Comment by 521xueweihan** [comment]
@xiaosongxiaosong 非常感谢您推荐项目，这是个很有意思的项目，但是功能还需要完善更多。

所以**该项目暂不能收录到 HelloGitHub 月刊中**，期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
