### ISSUE TITLE
project-based-learning

### ISSUE THREAD

**Issue by maychair** [521xueweihan/HelloGitHub#315]
## 项目推荐
- 项目名称：面向项目学习

- 项目地址：https://github.com/tuvtran/project-based-learning

- 项目后续更新计划：

- 项目描述：使用一个一个的项目学习计算机科学；由项目驱动，学习编译原理、操作系统、计算机网络、web 等等；包含了多种语言；

- 推荐理由：面向项目学习，比面向书本学习可操作性更高，更容易获得正向反馈；

- 示例代码：

- 截图：

![image](https://user-images.githubusercontent.com/18720246/44144991-55b0c2e0-a0bc-11e8-9fa2-f29256b5d4d8.png)

**Comment by 521xueweihan** [comment]
@maychair 您推荐的项目，已成功收录在 [HelloGitHub 第 29 期](https://hellogithub.com/periodical/volume/29/#project-based-learning)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
