### ISSUE TITLE
RebateBot 返利机器人 基于golang+vue+android-xposed   

### ISSUE THREAD

**Issue by 546669204** [521xueweihan/HelloGitHub#316]
## 项目推荐
- 项目名称：RebateBot 返利机器人

- 项目地址：https://github.com/546669204/RebateBot

- 项目后续更新计划：增加京东购链，发送图片语音，优化逻辑代码

- 项目描述：返利机器人，基于微信建立机器人通道与用户通过聊天快速生成返利链接
利用闲置微信和极小的电脑性能开启24小时无人轮值返利机器人
购物只需要发送链接给机器人，机器人能马上给你回复优惠价格及链接

- 推荐理由：非常贴近用户，易于改造成自己的项目

- 示例代码：

- 截图：
https://github.com/546669204/RebateBot/raw/master/screenshots/demo.png

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
