### ISSUE TITLE
[Go项目] 微信支付SDK

### ISSUE THREAD

**Issue by objcoding** [521xueweihan/HelloGitHub#317]
## 项目推荐
- 项目名称：wxpay

- 项目地址：https://github.com/objcoding/wxpay

- 项目后续更新计划：1.完善代码质量 2.增加一些新功能，如企业付款到银行卡等

- 项目描述：这是一款为Go语言写的一个微信支付SDK

- 推荐理由：轻量、好用、易上手。

- 示例代码：
```
// 新建微信支付客户端
// 统一下单
params := make(wxpay.Params)
params.SetString("body", "test").
		SetString("out_trade_no", "436577857").
		SetInt64("total_fee", 1).
		SetString("spbill_create_ip", "127.0.0.1").
		SetString("notify_url", "http://notify.objcoding.com/notify").
		SetString("trade_type", "APP")
p, _ := client.UnifiedOrder(params)
```

**Comment by FrontMage** [comment]
已收录至31期GO项目

**Comment by 521xueweihan** [comment]
@objcoding 您推荐的项目，已成功收录在 [HelloGitHub 第 31 期](https://hellogithub.com/periodical/volume/31/#wxpay)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
