### ISSUE TITLE
网页正文抽取工具

### ISSUE THREAD

**Issue by chrislinan** [521xueweihan/HelloGitHub#318]
## 项目推荐
- 项目名称：
       cx-extractor-python
- 项目地址：
        https://github.com/chrislinan/cx-extractor-python
- 项目后续更新计划：
        添加多语言支持
- 项目描述：
         这是一个对网页正文进行抽取的工具，是cx-extractor算法的python版本，改进了原有算法，使其支持中英文，对新闻类网页正文抽取效果较好
- 推荐理由：
     不需要解析html，抽取网页正文速度快，准确度高
- 示例代码：
    ```
    from crawler.cx_extractor_Python import  cx_extractor_Python
    cx = cx_extractor_Python()
    # test_html = cx.readHtml("E:\\Documents\\123.html")
    test_html = cx.getHtml('http://news.163.com/16/0101/10/BC84MRHS00014AED.html')
    content = cx.filter_tags(test_html)
    s = cx.getText(content)
     print(s)
     ```
- 截图：
![raw](https://user-images.githubusercontent.com/12604912/44471432-7bdcba80-a65e-11e8-885f-c88be9e52338.png)
![text](https://user-images.githubusercontent.com/12604912/44471435-7d0de780-a65e-11e8-927d-4a8b9f4ea4fd.png)

**Comment by 521xueweihan** [comment]
@chrislinan 您推荐的项目，已成功收录在 [HelloGitHub 第 30 期](https://hellogithub.com/periodical/volume/30/#cx-extractor-python)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
