### ISSUE TITLE
推荐项目 MediaInfoLib

### ISSUE THREAD

**Issue by PeoLeser** [521xueweihan/HelloGitHub#32]
为几乎全部的音频视频容器和编码方式提供了一个对外统一的Tag读取接口, 优于TagLib
[MediaInfoLib](https://github.com/MediaArea/MediaInfoLib)

**Comment by 521xueweihan** [comment]
不好意思请重新[创建 issues](https://github.com/521xueweihan/HelloGitHub/issues/new)，根据推荐项目的模版，规范推荐项目格式、完善信息。
