### ISSUE TITLE
react-meme-generator 在线表情包制作器 [自荐]

### ISSUE THREAD

**Issue by lijinke666** [521xueweihan/HelloGitHub#321]
## 项目推荐
- 项目名称： react-meme-generator

- 项目地址：[https://github.com/lijinke666/react-meme-generator](https://github.com/lijinke666/react-meme-generator)

- 项目后续更新计划： 暂无

- 项目描述：
一个基于`React`, `Antd ` 在线的表情包制作器

- 推荐理由：
  - 支持摄像头捕捉, 没有图片素材的时候 用自己当素材也是没毛病的
  - 支持图片拖拽 和 截图粘贴
  - 灵活方便的制作
  - 支持图片旋转放大压缩

- 示例代码：

无

- 截图：
![image](https://user-images.githubusercontent.com/21015895/44730905-9c9c8880-ab14-11e8-9ae8-3bb9707b3f95.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
