### ISSUE TITLE
💅 Regex-Combat

### ISSUE THREAD

**Issue by tangweikun** [521xueweihan/HelloGitHub#322]
## 项目推荐
- 项目名称：Regex-Combat

- 项目地址：https://github.com/tangweikun/Regex-Combat

- 项目描述：通过实例练习学习正则表达式

- 推荐理由：正则表达式可以帮助你巧妙的解决很多难题

- 截图：
<img width="877" alt="7kyu" src="https://user-images.githubusercontent.com/13361639/44764017-32213200-ab80-11e8-8016-2e96cf370fbf.png">

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
