### ISSUE TITLE
Fast, lightweight Web framework based on Netty

### ISSUE THREAD

**Issue by crossoverJie** [521xueweihan/HelloGitHub#323]
## 项目推荐
- 项目名称：
`cicada`

- 项目地址：
https://github.com/TogetherOS/cicada

- 项目后续更新计划：
- [x] 代码简洁，没有过多依赖。
- [x] 一行代码即可启动 HTTP 服务。
- [x] 自定义拦截器。
- [x] 灵活的传参方式。
- [x] `json` 响应格式。
- [x] 自定义配置。
- [ ] 多种路由风格。
- [ ] `HTTPS` 支持。
- [ ] `Cookie` 支持。
- [ ] 文件上传。

- 项目描述：

基于 Netty4 实现的快速、轻量级 WEB 框架；没有过多的依赖，核心 jar 包仅 30KB。

- 推荐理由：

一行代码即可启动 HTTP 服务，支持灵活的传参方式。

- 示例代码：

```java
public class MainStart {

    public static void main(String[] args) throws InterruptedException {
        CicadaServer.start(MainStart.class,"/cicada-example") ;
    }
}
```

### 配置业务 Action

创建业务 Action 实现 `top.crossoverjie.cicada.server.action.WorkAction` 接口。

```java
@CicadaAction(value = "demoAction")
public class DemoAction implements WorkAction {


    private static final Logger LOGGER = LoggerBuilder.getLogger(DemoAction.class) ;

    private static AtomicLong index = new AtomicLong() ;

    @Override
    public WorkRes<DemoResVO> execute(Param paramMap) throws Exception {
        String name = paramMap.getString("name");
        Integer id = paramMap.getInteger("id");
        LOGGER.info("name=[{}],id=[{}]" , name,id);

        DemoResVO demoResVO = new DemoResVO() ;
        demoResVO.setIndex(index.incrementAndGet());
        WorkRes<DemoResVO> res = new WorkRes();
        res.setCode(StatusEnum.SUCCESS.getCode());
        res.setMessage(StatusEnum.SUCCESS.getMessage());
        res.setDataBody(demoResVO) ;
        return res;
    }

}
```

- 截图：

![](https://ws2.sinaimg.cn/large/006tNbRwgy1fuvohu1awsj31fs0ukjv8.jpg)

**Comment by 521xueweihan** [comment]
@crossoverJie  您推荐的项目，已成功收录在 [HelloGitHub 第 30 期](https://hellogithub.com/periodical/volume/30/#cicada)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
