### ISSUE TITLE
AndroidAutoSize

### ISSUE THREAD

**Issue by JessYanCoding** [521xueweihan/HelloGitHub#325]
## 项目推荐
- 项目名称：AndroidAutoSize

- 项目地址：https://github.com/JessYanCoding/AndroidAutoSize

- 项目后续更新计划：持续维护

- 项目描述：今日头条屏幕适配方案终极版，一个极低成本的 Android 屏幕适配方案

- 推荐理由：目前成本最低的  Android 屏幕适配方案，今日头条已经用到线上，开源不到一个月近 3k star

- 截图：![](https://raw.githubusercontent.com/JessYanCoding/AndroidAutoSize/master/art/1440x2880_width.png)

**Comment by 521xueweihan** [comment]
@JessYanCoding 建议
1. 简化README，把教程拆出去
2. README 加入采用该项目的APP或公司

加油持续维护下去！

**Comment by 521xueweihan** [comment]
@JessYanCoding  您推荐的项目，已成功收录在 [HelloGitHub 第 31 期](https://hellogithub.com/periodical/volume/31/#AndroidAutoSize)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by JessYanCoding** [comment]
感谢您的建议🙏
