### ISSUE TITLE
项目推荐-基于nuxt构建的高仿饿了么（2018版）

### ISSUE THREAD

**Issue by EasyTuan** [521xueweihan/HelloGitHub#326]
## 项目推荐
- 项目名称：
基于nuxt构建的高仿饿了么（2018版）
- 项目地址：
https://github.com/EasyTuan/nuxt-elm
- 项目后续更新计划：
完善下单流程、定位等功能
- 项目描述：
高仿饿了么，以nuxt作为vue的服务端渲染，适合刚接触或者准备上vue ssr的同学参考和学习
- 截图：
### 首页展示

<img src="/EasyTuan/nuxt-elm/raw/master/screenshots/1.png" width="375px" height="667px" /> <img src="/EasyTuan/nuxt-elm/raw/master/screenshots/1.gif" width="375px" height="667px" />
### 个人资料

<img src="/EasyTuan/nuxt-elm/raw/master/screenshots/1.png" width="375px" height="667px" /> <img src="/EasyTuan/nuxt-elm/raw/master/screenshots/2.gif" width="375px" height="667px" />
### 我的

<img src="/EasyTuan/nuxt-elm/raw/master/screenshots/3.png" width="375px" height="667px" /> <img src="/EasyTuan/nuxt-elm/raw/master/screenshots/3.gif" width="375px" height="667px" />
### 订餐

<img src="/EasyTuan/nuxt-elm/raw/master/screenshots/4.png" width="375px" height="667px" /> <img src="/EasyTuan/nuxt-elm/raw/master/screenshots/4.gif" width="375px" height="667px" />
### 商家评价
<img src="/EasyTuan/nuxt-elm/raw/master/screenshots/5.png" width="375px" height="667px" /> <img src="/EasyTuan/nuxt-elm/raw/master/screenshots/5.gif" width="375px" height="667px" />

**Comment by 521xueweihan** [comment]
@EasyTuan 您好，已推荐过类似项目，所以不能收录到月刊中
