### ISSUE TITLE
v-uploader - 基于 Vue2 简洁易用，可批量、拖拽的文件上传插件[自荐]

### ISSUE THREAD

**Issue by TerryZ** [521xueweihan/HelloGitHub#328]
## 项目推荐
- 项目名称：v-uploader

- 项目地址：
  - [HomePage](https://terryz.gitee.io/vue/#/upload)
  - [Github](https://github.com/TerryZ/v-uploader)

- 项目后续更新计划：自定义请求服务端数据结构

- 项目描述：基于 Vue2 简洁易用，可批量、拖拽的文件上传插件

- 推荐理由：

  - 单文件上传模式带图片预览框
  - 单文件上传模式预览框模式支持关闭、自定义尺寸、自定义默认展示图片等定制化功能
  - 批量上传模式支持图片预览、文件拖拽
  - 健全的上传文件限制，文件类型、文件尺寸、自定义校验等

- 示例代码：

```vue
<v-uploader></v-uploader>
```

- 截图：

单文件上传带图片预览模式
![v-uploader-single](https://user-images.githubusercontent.com/854406/45596320-e4fce700-b9ec-11e8-9545-be6d4f8551a5.png)

批量上传，支持拖拽模式
![v-uploader-multiple](https://user-images.githubusercontent.com/854406/45596331-11b0fe80-b9ed-11e8-93dd-5599c00826ed.png)

- 项目类型：基于 Vue2 的文件上传组件

**Comment by JameJJ** [comment]
感觉官网可以显示些demo，这样可以有一个不错的使用体验

**Comment by TerryZ** [comment]
官网的 Demo 有六七个了啊

**Comment by 521xueweihan** [comment]
@TerryZ  您推荐的项目，已成功收录在 [HelloGitHub 第 30 期](https://hellogithub.com/periodical/volume/30/#v-uploader)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by TerryZ** [comment]
@521xueweihan 感谢推荐，有时间再来自荐自己的项目 :)
