### ISSUE TITLE
iOS:每个APP都用的上的CategoryView【自荐】

### ISSUE THREAD

**Issue by pujiaxin33** [521xueweihan/HelloGitHub#329]
## 项目推荐
- 项目名称：JXCategoryView

- 项目地址：https://github.com/pujiaxin33/JXCategoryView

- 项目后续更新计划：保持对主流效果的及时更新。

- 项目描述：几乎实现了所有主流APP的分类切换控制效果，效果丰富，配置简单。而且通过协议控制，指示器效果可以完全自定义。cell的样式也可以完全自定义。

- 推荐理由：适合每个iOS开发，使用简单，功能强大。

- 示例代码：

//1、初始化JXCategoryTitleView
self.categoryView = [[JXCategoryTitleView alloc] initWithFrame:CGRectMake(0, 0, WindowsSize.width, categoryViewHeight)];
self.categoryView.delegate = self;

//2、添加并配置指示器
//lineView
JXCategoryIndicatorLineView *lineView = [[JXCategoryIndicatorLineView alloc] init];
lineView.indicatorLineViewColor = [UIColor redColor];
lineView.indicatorLineWidth = JXCategoryViewAutomaticDimension;
//backgroundView
JXCategoryIndicatorBackgroundView *backgroundView = [[JXCategoryIndicatorBackgroundView alloc] init];
backgroundView.backgroundViewColor = [UIColor redColor];
backgroundView.backgroundViewWidth = JXCategoryViewAutomaticDimension;
titleCategoryView.indicators = @[lineView, backgroundView];

//3、绑定contentScrollView。self.scrollView的初始化细节参考源码。
self.categoryView.contentScrollView = self.scrollView;
[self.view addSubview:self.categoryView];

- 截图：
![image](https://user-images.githubusercontent.com/12654640/45681489-384b7280-bb70-11e8-857a-b038e7d6c678.png)

**Comment by 521xueweihan** [comment]
@pujiaxin33 您推荐的项目，**已成功发布**在 [HelloGitHub 第 33 期](https://hellogithub.com/periodical/volume/33/#JXCategoryView)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
