### ISSUE TITLE
爬虫租房app

### ISSUE THREAD

**Issue by answershuto** [521xueweihan/HelloGitHub#33]
## 项目推荐
- 项目：[项目名称](项目地址)
Rental https://github.com/answershuto/Rental

- 项目描述：
一款租房app，基于node.js爬虫爬取58同城租房信息，并用地图进行可视化展示，方便用户获取周围租房信息。

- 推荐理由：
趣味项目

- 实例代码：
Rental https://github.com/answershuto/Rental

- 截图：

> ![img](https://ooo.0o0.ooo/2017/04/20/58f8946c5d617.png)

> ![img](https://ooo.0o0.ooo/2017/04/20/58f8946c8cb6b.png)

> ![img](https://ooo.0o0.ooo/2017/04/20/58f8946c8d8ea.png)

> ![img](https://ooo.0o0.ooo/2017/04/20/58f8946e0959b.png)

**Comment by 521xueweihan** [comment]
您好，Rental 项目已收录到 [14 期](https://github.com/521xueweihan/HelloGitHub/blob/master/14/HelloGitHub14.md)，再次感谢您的支持，希望以后推荐更多好的项目。
