### ISSUE TITLE
SpiderMan:Android崩溃日志手机端显示

### ISSUE THREAD

**Issue by simplepeng** [521xueweihan/HelloGitHub#330]
## 项目推荐
- 项目名称：
SpiderMan
- 项目地址：
https://github.com/simplepeng/SpiderMan
- 项目后续更新计划：
崩溃日志本地数据库存储
- 项目描述：
Android崩溃日志手机端显示 ，测试妹妹的最爱，开发哥哥的小棉袄
- 推荐理由：

Release环境不弹出难看的崩溃框！崩溃了也不闪退~
Debug环境可以在手机上显示崩溃信息！分享给相关开发人员~
再也不用担心测试妹妹给你重现怎么操作崩溃的啦！
再也不用担心产品相关人员给你说哪儿哪儿崩溃，但是又重现不了的尴尬啦！
再也不用担心某些Rom禁止异常输出啦！
再也不用担心开发工具log信息时灵时不灵啦

- 示例代码：
```java
       SpiderMan.init(this)
                //设置回调异常信息，友盟等第三方崩溃信息收集平台会用到,
                .setOnCrashListener(new SpiderMan.OnCrashListener() {
                    /**
                     *
                     * @param t
                     * @param ex
                     * @param model 崩溃信息记录，包含设备信息
                     */
                    @Override
                    public void onCrash(Thread t, Throwable ex, CrashModel model) {
                      
                    }
                });
```
- 截图：
![](https://raw.githubusercontent.com/simplepeng/SpiderMan/3f457c754a90baa8c9b73b6953b4cb9581bb9414/statics/debug.gif)

**Comment by 521xueweihan** [comment]
@simplepeng 这样岂不减少了和测试妹子的沟通频次，差评😂

**Comment by simplepeng** [comment]
> @simplepeng 这样岂不减少了和测试妹子的沟通频次，差评😂

好像是这个道理啊！！！😢😢😢

**Comment by 521xueweihan** [comment]
@simplepeng 您推荐的项目，**已成功发布**在 [HelloGitHub 第 32 期](https://hellogithub.com/periodical/volume/32/#SpiderMan)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
