### ISSUE TITLE
AndroidWM: 轻量级安卓水印框架，支持隐形数字水印

### ISSUE THREAD

**Issue by huangyz0918** [521xueweihan/HelloGitHub#331]
## 项目推荐
- 项目名称：AndroidWM

- 项目地址：https://github.com/huangyz0918/AndroidWM

- 项目后续更新计划：实现 LSB 混合频域水印，增强隐形数字水印的鲁棒性，优化计算速度和包大小。

- 项目描述：一个轻量级的开源 Android 图片水印框架，支持文字水印和图像水印，以及不同的水印样式、位置等。同时可以支持 LSB 空间域隐形数字水印的加载和频域数字水印的加载和检测，适合客户端图片水印添加，移动端图像处理等。

- 推荐理由：免费的盲水印本地制作框架，再也不需要客户端手写 Canvas 和算傅里叶变换了。同时在 Java 平台上实现了快速计算频域图像的功能，提供了灵活的接口。

- 示例代码：

在下载并且配置好 androidwm 之后，你可以创建一个 `WatermarkImage` 或者是 `WatermarkText` 的实例，并且使用内置的诸多`Set`方法为创建一个水印做好准备。

```java
    WatermarkText watermarkText = new WatermarkText(editText)
            .setPositionX(0.5)
            .setPositionY(0.5)
            .setTextColor(Color.WHITE)
            .setTextFont(R.font.champagne)
            .setTextShadow(0.1f, 5, 5, Color.BLUE)
            .setTextAlpha(150)
            .setRotation(30)
            .setTextSize(20);
```

当你的水印（文字或图片水印）已经准备就绪的时候，你需要一个 `WatermarkBuilder`来把水印画到你希望的背景图片上。 你可以通过 `create` 方法获取一个 `WatermarkBuilder` 的实例，注意，在创建这个实例的时候你需要先传入一个 `Bitmap` 或者是一个 `Drawable` 的资源 id 来获取背景图。

```java
    WatermarkBuilder
            .create(context, backgroundBitmap)
            .loadWatermarkText(watermarkText) // use .loadWatermarkImage(watermarkImage) to load an image.
            .getWatermark()
            .setToImageView(imageView);
```

![](https://i.loli.net/2018/09/01/5b8aa948a8935.png)

- 截图：

|  ![](https://i.loli.net/2018/09/06/5b90f8d80402b.gif)   | ![](https://i.loli.net/2018/09/06/5b90f8d7936f9.gif) | 
| :-------------: | :-------------: | 
|   隐形文字水印 (LSB)   |  隐形图像水印 (LSB)  |

**Comment by 521xueweihan** [comment]
@huangyz0918 您推荐的项目，**已成功发布**在 [HelloGitHub 第 33 期](https://hellogithub.com/periodical/volume/33/#AndroidWM)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
