### ISSUE TITLE
一个有趣的目录生成器

### ISSUE THREAD

**Issue by SHERlocked93** [521xueweihan/HelloGitHub#335]
## 项目推荐
- 项目名称：
  **progress-catalog**

- 项目地址：
  [SHERlocked93 - progress-catalog](https://github.com/SHERlocked93/progress-catalog)

- 项目后续更新计划：
  - [ ] 代码重构，CodeReview

- 项目描述：
  **progress-catalog** 是一个根据选定的目录内容中的 `h1, h2, h3, h4, h5, h6` 标签来自动生成目录插入到选定的目录容器中，并且提供一个漂亮的样式效果的目录自动生成器。如果你不喜欢炫酷的目录样式，也有普通的目录样式可选

- 推荐理由：
  一个有趣的JS目录生成器

- 示例代码：
  ```js
  // 引入
  import Catalog from 'ProgressCatalog'
  
  // 使用 
  new Catalog({
  	contentEl: 'loading-animation',
  	catalogEl: `catalog-content-wrapper`,
  	selector: ['h2', 'h3']
  })
  ```

  详细可见：[<一个骚气的文章目录自动生成器了解一下>](https://juejin.im/post/5b6c29dde51d4518f5445c03)

- 截图：
![](https://i.loli.net/2018/09/28/5bad890a0cdd7.gif)

**Comment by Seven-Steven** [comment]
骚

**Comment by ChungZH** [comment]
好玩

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
