### ISSUE TITLE
MaterialDesign Xamarin.Android Demo

### ISSUE THREAD

**Issue by code-jar** [521xueweihan/HelloGitHub#338]
## 项目推荐
- 项目名称：
MaterialDesign Demo
- 项目地址：
https://github.com/code-jar/MaterialDesignDemo
- 项目后续更新计划：

- 项目描述：
Material Design风格 Xamarin.Android Demo项目
- 推荐理由：
Xamarin.Android入门项目
- 示例代码：

- 截图：
![image](https://user-images.githubusercontent.com/22388512/46241492-48274a00-c3ed-11e8-8dbe-de188c8bc487.png)

**Comment by 521xueweihan** [comment]
@code-jar 您好，该项目暂不能收录到月刊中，请参考 #271 

感谢您的支持
