### ISSUE TITLE
微软小冰读心术命令行版[自荐]

### ISSUE THREAD

**Issue by imzeali** [521xueweihan/HelloGitHub#339]
## 项目推荐
- 项目名称：
读心术
- 项目地址：
https://github.com/imzeali/mind_reader
- 项目后续更新计划：

- 项目描述：
读心术是微软小冰AI技能，首先在你的心理默想1个名人，然后回答15问题，程序就能猜到你所想的那个人。
- 推荐理由：
封装了网页版的http接口api，可用于对接其他第三方程序。
- 示例代码：
![image](https://user-images.githubusercontent.com/13485293/46778848-0f219a80-cd48-11e8-9291-9e19bc50da0c.png)

- 截图：

![image](https://user-images.githubusercontent.com/13485293/46778763-bce07980-cd47-11e8-89f5-eb9e25c3d693.png)

**Comment by 521xueweihan** [comment]
@imzeali 您好，该项目暂不能收录到月刊中。推荐标准请参考 #271 

希望您能够继续推荐有意思、入门级项目，再次感谢。
