### ISSUE TITLE
Django 博客开发教程

### ISSUE THREAD

**Issue by zmrenwu** [521xueweihan/HelloGitHub#34]
## 项目推荐
- 项目：[Django 博客开发教程](https://github.com/zmrenwu/django-blog-tutorial)

- 项目描述：26 篇教程一步步带你使用 Django 从零开发一个个人博客系统，在实践的同时掌握 Django 的开发技巧。

- 推荐理由：免费、中文、零基础，完整的项目，基于最新版 Django 1.10 和 Python 3.5。带你从零开始一步步开发属于自己的博客网站，帮助你以最快的速度掌握 Django 开发的技巧。

- 实例代码：None

- 截图：None，在线预览：[Demo](http://demo.zmrenwu.com/)

**Comment by 521xueweihan** [comment]
您推荐的项目已收录到 [15 期](https://github.com/521xueweihan/HelloGitHub/blob/master/content/15/HelloGitHub15.md#python-项目)，同时您已加入到 [贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/contributors.md) 中。

期待老铁后面继续推荐给力的项目 💪
