### ISSUE TITLE
MyPerf4J 针对高并发、低延迟应用设计的高性能 Java 性能监控和统计工具 【自荐项目】

### ISSUE THREAD

**Issue by ThinkpadNC5** [521xueweihan/HelloGitHub#340]
# ## 项目推荐
- 项目名称：MyPerf4J

- 项目地址：https://github.com/ThinkpadNC5/MyPerf4J

- 项目描述：一个针对高并发、低延迟应用设计的高性能 Java 性能监控和统计工具

- 推荐理由：高性能、低消耗、无侵入、轻量

- 示例代码：
    - 打包
        * git clone git@github.com:ThinkpadNC5/MyPerf4J.git
        * mvn clean package
        * 把 MyPerf4J-ASM-${MyPerf4J-version}.jar 重命名为 MyPerf4J-ASM.jar
    - 配置
        在 JVM 启动参数里加上以下两个参数
        > -javaagent:/your/path/to/MyPerf4J-ASM.jar

        > -DMyPerf4JPropFile=/your/path/to/myPerf4J.properties

        其中，`MyPerf4JPropFile`的配置如下:

         ```
        #应用名称
        AppName=MyPerf4JTest
        
        #MetricsProcessor类型，0:以标准格式化结构输出到stdout.log 1:以标准格式化结构输出到磁盘  2:以InfluxDB LineProtocol格式输出到磁盘
        MetricsProcessorType=1
        
        #配置各个Metrics日志的文件路径，可不配置
        MethodMetricsFile=/data/logs/MyPerf4J/method_metrics.log
        #ClassMetricsFile=/data/logs/MyPerf4J/class_metrics.log
        #GCMetricsFile=/data/logs/MyPerf4J/gc_metrics.log
        #MemMetricsFile=/data/logs/MyPerf4J/memory_metrics.log
        #ThreadMetricsFile=/data/logs/MyPerf4J/thread_metrics.log
            
        #配置时间片，单位为ms，最小1s，最大600s
        MillTimeSlice=10000
            
        #需要监控的package，可配置多个，用英文';'分隔
        IncludePackages=cn.perf4j.demo
            
        #不需要监控的package，可配置多个，用英文';'分隔
        ExcludePackages=org.spring;
            
        #可配置多个方法名，用英文';'分隔
        ExcludeMethods=equals;hash
        ```
        
        > 想了解更多的配置？请看[这里](https://github.com/ThinkpadNC5/MyPerf4J/wiki/%E9%85%8D%E7%BD%AE)
    
- 截图：
    ![Markdown](https://raw.githubusercontent.com/ThinkpadNC5/Pictures/master/MyPerf4J-InfluxDB-Method_Show_Operation.gif)

**Comment by 521xueweihan** [comment]
@ThinkpadNC5   您推荐的项目，已成功收录在 [HelloGitHub 第 31 期](https://hellogithub.com/periodical/volume/31/#MyPerf4J)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by ThinkpadNC5** [comment]
好的，感谢 : )
