### ISSUE TITLE
项目推荐：LongestCocoa

### ISSUE THREAD

**Issue by NamelessAshone** [521xueweihan/HelloGitHub#341]
## 项目推荐
- 项目名称：
LongestCocoa
- 项目地址：
https://github.com/Quotation/LongestCocoa
- 项目后续更新计划：
无
- 项目描述：
Programmers who write Objective-C must REALLY love its descriptive and verbose naming style.
SoWhatAreTheLongestMethodOrConstantNamesInCocoaFramework? Here are some superb ones:
......
- 推荐理由：
Have fun:D
- 示例代码：
Run `python longest.py` to discover the first 10 longest names for each identifier type. Below is the output from `python longest.py iphoneos` and `python longest.py macosx`.
- 截图：
![haha](https://user-images.githubusercontent.com/26870409/46859742-2b553280-ce41-11e8-81d7-e7a5e14cd7d3.png)

**Comment by 521xueweihan** [comment]
@NamelessAshone 请提供中文描述和理由。再次感谢您对本月刊的支持
