### ISSUE TITLE
用go语言实现四则运算

### ISSUE THREAD

**Issue by RitterHou** [521xueweihan/HelloGitHub#345]
## 项目推荐
- 项目名称：Yui

- 项目地址：https://github.com/RitterHou/yui

- 项目后续更新计划：已完成，暂无更新计划

- 项目描述：使用golang实现四则运算，包含了编译器和虚拟机的实现

- 推荐理由：可以作为go语言的学习项目，也可以用于编译原理和虚拟机原理的学习

- 示例代码：

      define pi 3.14
      define radius 10

      {
          (radius * radius) * pi
      }
      {
          (1 + 2 + 88) * 100000 + 18722 / (-2) + 888 * (8848 - 19087) // 计算结果 -1593
      }

- 可以在此链接查看演示：<https://asciinema.org/a/K4deAJjyqxECZmpjJOR2rorEt>

**Comment by 521xueweihan** [comment]
@FrontMage

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
