### ISSUE TITLE
(持续更新, 目前含100+工具类) DevUtils 是一个 Android 工具库, 主要根据不同功能模块，封装快捷使用的工具类及 API 方法调用。 该项目尽可能的便于开发人员，快捷、快速开发安全可靠的项目。

### ISSUE THREAD

**Issue by afkT** [521xueweihan/HelloGitHub#346]
## 项目推荐
- 项目名称： DevUtils

- 项目地址： https://github.com/afkT/DevUtils

- 项目后续更新计划： 

（目前兼容至 Android P）

https://github.com/afkT/DevUtils/blob/master/DevLibUtils/README.md

持续更新，并且存在多个快捷开发关联库

- 项目描述：

DevUtils 是一个 Android 工具库, 主要根据不同功能模块，封装快捷使用的工具类及 API 方法调用。 该项目尽可能的便于开发人员，快捷、快速开发安全可靠的项目，以及内置部分常用的资源文件，如color.xml、(toast) layout.xml等

- 推荐理由：

注释规范、API文档清晰明了、工具类种类多，便于开发人员快捷开发出一个安全可靠的应用

- 示例代码：

https://github.com/afkT/DevUtils/blob/master/DevLibUtils/README.md

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 34 期](https://hellogithub.com/periodical/volume/34/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
