### ISSUE TITLE
具有2.5k star,成熟的Android MVP可配置化集成框架

### ISSUE THREAD

**Issue by JessYanCoding** [521xueweihan/HelloGitHub#35]
## 项目推荐
- 项目：[MVPArms](https://github.com/JessYanCoding/MVPArms)

- 项目描述：MVPArms是一个整合了大量主流开源项目的Android Mvp快速搭建框架,其中包含Dagger2,Retrofit,Rxjava以及RxLifecycle,RxCache等Rx系三方库,并且提供UI自适应方案,本框架将它们结合起来,并全部使用Dagger2管理并提供给开发者使用,使用本框架开发你的项目就意味着你已经拥有一个MVP+Dagger2+Retrofit+Rxjava项目

- 推荐理由：具有上万字的 [Wiki文档](https://github.com/JessYanCoding/MVPArms/wiki),2.5kStar,成熟稳定的 Android MVP解决方案

## Architectural
![Architecture](https://github.com/JessYanCoding/MVPArms/raw/master/image/Architecture.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功收录**在 [HelloGitHub 第 17 期](https://github.com/521xueweihan/HelloGitHub/blob/master/content/17/HelloGitHub17.md)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，如果方便可以 Star ⭐️ 本项目，让更多人看到本项目。

**Comment by JessYanCoding** [comment]
好的，已star

**Comment by 521xueweihan** [comment]
@JessYanCoding 老铁，稳！
