### ISSUE TITLE
FGDBTKD组织(Build for everyone, Create for everyone, Design for everyone, Code for everyone. If you want to join me, email me!)[自荐]

### ISSUE THREAD

**Issue by Eurus-Holmes** [521xueweihan/HelloGitHub#350]
## 项目推荐
- 项目名称：
**FGDBTKD Organization**
- 项目地址：
[**FGDBTKD**](https://github.com/FGDBTKD)
- 项目后续更新计划：
**希望能与[HelloGitHub](https://hellogithub.com/)合作，共同促进开源社区的发展**
- 项目描述：
**事实上这并不是一个项目，而是我建立的一个organization，建立的初衷与[HelloGitHub](https://hellogithub.com/)类似，每当看到我感兴趣的项目都会fork下来，目前大部分项目都与机器学习、深度学习、人工智能以及NLP方面相关，但还没有好好整理过。。。期待感兴趣的朋友们来和我共同维护～
我的邮箱地址是: chenfeiyang999@gmail.com**
- 推荐理由：
**Build for everyone, Create for everyone, Design for everyone, Code for everyone. 
If you want to join me, email me!**
- 示例代码：
# Tracking Progress in Natural Language Processing

### English

- [Automatic speech recognition](english/automatic_speech_recognition.md)
- [CCG supertagging](english/ccg_supertagging.md)
- [Chunking](english/chunking.md)
- [Common sense](english/common_sense.md)
- [Constituency parsing](english/constituency_parsing.md)
- [Coreference resolution](english/coreference_resolution.md)
- [Dependency parsing](english/dependency_parsing.md)
- [Dialogue](english/dialogue.md)
- [Domain adaptation](english/domain_adaptation.md)
- [Entity linking](english/entity_linking.md)
- [Grammatical error correction](english/grammatical_error_correction.md)
- [Information extraction](english/information_extraction.md)
- [Language modeling](english/language_modeling.md)
- [Lexical normalization](english/lexical_normalization.md)
- [Machine translation](english/machine_translation.md)
- [Multi-task learning](english/multi-task_learning.md)
- [Multi-modal](english/multimodal.md)
- [Named entity recognition](english/named_entity_recognition.md)
- [Natural language inference](english/natural_language_inference.md)
- [Part-of-speech tagging](english/part-of-speech_tagging.md)
- [Question answering](english/question_answering.md)
- [Relation prediction](english/relation_prediction.md)
- [Relationship extraction](english/relationship_extraction.md)
- [Semantic textual similarity](english/semantic_textual_similarity.md)
- [Semantic parsing](english/semantic_parsing.md)
- [Semantic role labeling](english/semantic_role_labeling.md)
- [Sentiment analysis](english/sentiment_analysis.md)
- [Stance detection](english/stance_detection.md)
- [Summarization](english/summarization.md)
- [Taxonomy learning](english/taxonomy_learning.md)
- [Temporal processing](english/temporal_processing.md)
- [Text classification](english/text_classification.md)
- [Word sense disambiguation](english/word_sense_disambiguation.md)

### Chinese

- [Entity linking](chinese/chinese.md#entity-linking)

### Hindi

- [Chunking](hindi/hindi.md#chunking)
- [Part-of-speech tagging](hindi/hindi.md#part-of-speech-tagging)
- [Machine Translation](hindi/hindi.md#machine-translation)

### Vietnamese

- [Dependency parsing](vietnamese/vietnamese.md#dependency-parsing)
- [Machine translation](vietnamese/vietnamese.md#machine-translation)
- [Named entity recognition](vietnamese/vietnamese.md#named-entity-recognition)
- [Part-of-speech tagging](vietnamese/vietnamese.md#part-of-speech-tagging)
- [Word segmentation](vietnamese/vietnamese.md#word-segmentation)

This document aims to track the progress in Natural Language Processing (NLP) and give an overview
of the state-of-the-art (SOTA) across the most common NLP tasks and their corresponding datasets.

It aims to cover both traditional and core NLP tasks such as dependency parsing and part-of-speech tagging
as well as more recent ones such as reading comprehension and natural language inference. The main objective
is to provide the reader with a quick overview of benchmark datasets and the state-of-the-art for their
task of interest, which serves as a stepping stone for further research. To this end, if there is a 
place where results for a task are already published and regularly maintained, such as a public leaderboard,
the reader will be pointed there.

If you want to find this document again in the future, just go to [`nlpprogress.com`](https://nlpprogress.com/)
or [`nlpsota.com`](http://nlpsota.com/) in your browser.
- 截图：
<img width="1440" alt="2018-11-16 10 51 05" src="https://user-images.githubusercontent.com/34226570/48594991-eb2c2700-e98d-11e8-8b3e-e2c2194b79dd.png">

**Comment by 521xueweihan** [comment]
@Eurus-Holmes 感谢对 HG 的支持，机器学习部分一只是我们的弱项，期待合作。

我先和我们的小伙伴商量下在给予您回复 🙏

**Comment by Eurus-Holmes** [comment]
@521xueweihan 嗯嗯回复了。
