### ISSUE TITLE
上班划水神器：一个可以在控制台玩斗地主项目！

### ISSUE THREAD

**Issue by xia-tong** [521xueweihan/HelloGitHub#351]
## 项目推荐
- 项目名称：在命令行里面斗地主

- 项目地址：https://github.com/ainilili/ratel

- 项目后续更新计划：

- 项目描述：这是Ratel，它可以在命令行内进行简单的斗地主游戏

- 推荐理由：Ratel分客户端和服务端，你可以在本地启动一个客户端让小伙伴们的客户端都连接你的服务器进行游戏，又或者可以直接连接作者公网服务器进行游戏

- 示例代码：

- 截图：
![demo](https://user-images.githubusercontent.com/18086995/48599303-0ef96800-e9a2-11e8-9fbd-d6394c446b4e.gif)

**Comment by 521xueweihan** [comment]
@xia-tong 您推荐的项目，**已成功发布**在 [HelloGitHub 第 x 期](https://hellogithub.com/periodical/volume/32/#ratel)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
