### ISSUE TITLE
【SimplifyDb】 中小Java项目快速操作数据库一款利器

### ISSUE THREAD

**Issue by jiangzeyin** [521xueweihan/HelloGitHub#352]
## 项目推荐
- 项目名称：

  SimplifyDb

- 项目地址：

   https://github.com/jiangzeyin/SimplifyDb

- 项目后续更新计划：
  
  长期维护，目前是支持mysql 后续支持更多的数据库

- 项目描述：

  SimplifyDb 是一个Java基于druid的一款Builder简化写sql语句操作的框架。本项目主要采用反射读写需要操作的实体和表，同时项目还是提供多种主键生成器和自定义主键生成器接口方便用户根据实际业务扩展主键生成器

- 推荐理由：

  java中小项目快速操作数据库一款利器

- 示例代码：

   https://github.com/jiangzeyin/SimplifyDb/blob/master/src/test/java/cn/simplifydb/README.md

**Comment by 521xueweihan** [comment]
@jiangzeyin 
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
