### ISSUE TITLE
项目推荐：Android-ViaBus-Architecture

### ISSUE THREAD

**Issue by KunMinX** [521xueweihan/HelloGitHub#353]
## 项目推荐
- 项目名称：
Android-ViaBus-Architecture

- 项目地址：
https://github.com/KunMinX/android-viabus-architecture

- 项目后续更新计划：
1. 持续集成依赖于依赖 viabus-core 的 common module，使能够快速开发和迭代新产品。
2. 编写简单和复杂的 demo，帮助使用者理解解耦、分离对软件工程的意义。

- 项目描述：
 ViaBus 是一款响应式架构，借助总线转发数据的请求和响应，实现ui、业务的完全解耦。

- 推荐理由：
一款符合设计模式 6 大原则、曾被用于“5 天内完成 60 个类的公司年度产品核心模块 的重构”的架构。它存在的使命是帮助使用者认识到，并愉悦的顺应工程学设计、工程开发原则。原先需要 1 个月才能完成的重构工作，现在耗费不到 5 天时间。原先 1 年经验重复使用 5 年，现在每天都可以专注深耕，不断发展变化。

- 示例代码：
https://github.com/KunMinX/android-viabus-architecture/wiki/1%E5%88%86%E9%92%9F%E6%8E%8C%E6%8F%A1-ViaBus-%E6%9E%B6%E6%9E%84%E7%9A%84%E4%BD%BF%E7%94%A8

- 截图：
![viabus flow](https://github.com/KunMinX/android-viabus-architecture/raw/master/images/viabus_flow_flow_detail.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 34 期](https://hellogithub.com/periodical/volume/34/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by KunMinX** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    收到 谢谢
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                kunminx
                            
                    
                        
                            
                                    kunminx@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2019年1月27日 23:50，削微寒<notifications@github.com> 写道： 


您推荐的项目，已成功发布在 HelloGitHub 第 34 期，并把您添加到了贡献者列表中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
