### ISSUE TITLE
基于spring boot的小清新个人博客系统

### ISSUE THREAD

**Issue by youyaa** [521xueweihan/HelloGitHub#354]
## 项目推荐
- 项目名称：听雨个人博客ListeningrainBLog

- 项目地址：https://github.com/youyaa/ListeningrainBlog

- 项目后续更新计划：界面优化，后台管理模块持续改进

- 项目描述：基于spring boot的小清新风个人博客，在线演示地址：https://blog.listeningrain.cn

- 推荐理由：标准的SSM项目的范例，在开发标准上参考我司的规范，可以让萌新提前了解企业开发规范。

- 示例代码：
https://github.com/youyaa/ListeningrainBlog/wiki

- 截图：
![listeningrainBlog1.png](https://i.loli.net/2018/11/20/5bf357af712f2.png)

**Comment by 521xueweihan** [comment]
@youyaa 非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
