### ISSUE TITLE
自荐Flask-Pluginkit: 基于Flask的插件式开发工具

### ISSUE THREAD

**Issue by staugur** [521xueweihan/HelloGitHub#356]
## 项目推荐
- 项目名称：Flask-PluginKit

- 项目地址：[https://github.com/staugur/Flask-PluginKit](https://github.com/staugur/Flask-PluginKit)

- 项目后续更新计划：[https://github.com/staugur/Flask-PluginKit#todo](https://github.com/staugur/Flask-PluginKit#todo)

- 项目描述：为Flask应用提供插件式结构开发

- 推荐理由：flask web扩展很多，但基于项目的通用或私有的快速开发插件却没什么好扩展，补缺。

- 示例代码：

```python
    from flask_pluginkit import PluginManager
    plugin = PluginManager()
    plugin.init_app(app)
```

- 截图：[https://flask-pluginkit.readthedocs.io/zh_CN/latest/#hello-world](https://flask-pluginkit.readthedocs.io/zh_CN/latest/#hello-world)

**Comment by 521xueweihan** [comment]
@staugur 非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
