### ISSUE TITLE
wtfpython 中文翻译文档

### ISSUE THREAD

**Issue by leisurelicht** [521xueweihan/HelloGitHub#357]
## 项目推荐
- 项目名称：What the f*ck Python 中文版

- 项目地址：https://github.com/leisurelicht/wtfpython-cn

- 项目后续更新计划：随原库更新

- 项目描述：一个收录 Python 语言中有趣且鲜为人知的各种大小坑的项目.

- 推荐理由：免费、中文、有趣、适合各种 python 开发者阅读，避免踩坑

- 示例代码：无

- 截图：
<img width="981" alt="default" src="https://user-images.githubusercontent.com/8042345/49137796-73181680-f328-11e8-8570-dfb72978a25f.png">

**Comment by 521xueweihan** [comment]
@leisurelicht 您好，感谢推荐和翻译这么有趣的项目，为开源社区贡献自己的一份力量。

由于之前的[第 25 期月刊](https://hellogithub.com/periodical/volume/25/#wtfpython)已经推荐过 wtfpython 项目，所以直接在该项目的介绍中增加了中文翻译版的链接。

再次感谢您对 HG 项目的支持！
