### ISSUE TITLE
lint-md 项目

### ISSUE THREAD

**Issue by ChungZH** [521xueweihan/HelloGitHub#358]
## 项目推荐
- 项目名称：
lint-md
- 项目地址：
https://github.com/hustcc/lint-md
- 项目后续更新计划：

- 项目描述：
这个工具是一个可以帮助你检测 Markdown 文档格式的工具，使用 Node.js 编写。检查规则来源于 https://github.com/sparanoid/chinese-copywriting-guidelines ，还方便集成在 CI 上，十分好用。
- 推荐理由：
实用
- 示例代码：

- 截图：
![](https://i.loli.net/2018/11/29/5bff6b10c6529.jpg)

**Comment by hustcc** [comment]
@521xueweihan 推荐你也在这个仓库中用来啊，我检查了一下，大概有 100 个错误！

**Comment by ChungZH** [comment]
~~太多了所以作者弃疗~~:smiley:

**Comment by 521xueweihan** [comment]
我会在挣扎一下的
