### ISSUE TITLE
一行代码即可监听 App 中所有网络链接的上传以及下载进度

### ISSUE THREAD

**Issue by JessYanCoding** [521xueweihan/HelloGitHub#36]
## 项目推荐
- 项目：[ProgressManager](https://github.com/JessYanCoding/ProgressManager)

- 项目描述：ProgressManager 一行代码即可监听 App 中所有网络链接的上传以及下载进度,包括 Glide 的图片加载进度,实现原理类似 EventBus,你可在 App 中的任何地方,将多个监听器,以 Url 地址作为标识符,注册到本框架,当此 Url 地址存在下载或者上传的动作时,框架会主动调用所有使用此 Url 地址注册过的监听器,达到多个模块的同步更新.

## Feature
* 使用简单,只需一行代码即可实现进度监听.
* 多平台支持,支持 **Okhttp** , **Retrofit** , **Glide** ,使用 **Okhttp** 原生 **Api** ,不存在兼容问题.
* 低耦合,实际请求端和进度接收端并不存在直接或间接的关联关系,即可以在 **App** 任何地方接收进度信息.
* 侵入性低,使用本框架你并不需要更改之前进行上传或下载的代码,即使用或不使用本框架并不会影响到原有的代码.
* 多端同步,同一个数据源的上传或下载进度可以指定多个不同的接收端,少去了使用 **EventBus** 实现多个端口同步更新进度.
* 自动管理监听器,少去了手动注销监听器的烦恼.
* 默认运行在主线层,少去了切换线程的烦恼.
* 轻量级框架,不包含任何三方库,体积极小.

## ScreenShot
![gif](https://raw.githubusercontent.com/JessYanCoding/ProgressManager/master/arts/progressManager.gif)

**Comment by jp1017** [comment]
:+1: 老大无所不在 :sob:

**Comment by JessYanCoding** [comment]
@jp1017 你也才是无所不在

**Comment by jp1017** [comment]
@JessYanCoding https://github.com/521xueweihan/HelloGitHub/blob/dev/Android.md 其实可以这里直接pr, @521xueweihan 没问题吧... :smile:

**Comment by 521xueweihan** [comment]
@JessYanCoding 老大好😁

**Comment by JessYanCoding** [comment]
@521xueweihan 😂

**Comment by 521xueweihan** [comment]
@JessYanCoding 蒋哥，你开心就好✌️

**Comment by 521xueweihan** [comment]
@JessYanCoding 您推荐的项目已收录到 [15 期](https://github.com/521xueweihan/HelloGitHub/blob/master/content/15/HelloGitHub15.md#java-项目)，同时您已加入到 [贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/contributors.md) 中。

期待老铁后面继续推荐给力的项目 💪
