### ISSUE TITLE
力荐 Omi

### ISSUE THREAD

**Issue by dntzhang** [521xueweihan/HelloGitHub#361]
### 项目名称

Omi

### 项目地址

https://github.com/Tencent/omi

### 项目描述

下一代 Web 框架

### 推荐理由：

* 设计精巧
* 腾讯微信支付团队和 AlloyTeam 合力打造
* 基于 Web Components 标准
* BAT 和 谷歌都在使用。

### 示例代码：

```js
import { render, WeElement, define } from 'omi'

define('my-counter', class extends WeElement {
    static observe = true
    
    data = {
      count: 1
    }

    sub = () => {
      this.data.count--
    }

    add = () => {
      this.data.count++
    }

    render() {
      return (
        <div>
          <button onClick={this.sub}>-</button>
          <span>{this.data.count}</span>
          <button onClick={this.add}>+</button>
        </div>
      )
    }
  })

render(<my-counter />, 'body')
```

### 截图
![qq 20181129143641](https://user-images.githubusercontent.com/7917954/49203707-36115a00-f3e4-11e8-9cc3-1466cba1f70d.png)

**Comment by ming995** [comment]
@dntzhang 感谢推荐，目前33期的JS项目已经有4个了，所有你推荐这个项目会放在34期月刊，还请谅解。再次感谢你对HG的关注，希望以后可以多多合作😬

**Comment by dntzhang** [comment]
没事，可以。多谢~~  @ming995

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 34 期](https://hellogithub.com/periodical/volume/34/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
