### ISSUE TITLE
自荐 Peach-Blog 基于 Flask 的简单博客

### ISSUE THREAD

**Issue by lt94** [521xueweihan/HelloGitHub#362]
## 项目推荐
- 项目名称：Peach-blog

- 项目地址：https://github.com/lt94/peach-blog.git

- 项目后续更新计划：
   1. RSS 功能
   2. 提醒功能
   3. 命令行批量导出功能
   4. 完善测试

- 项目描述：

    Peach Blog 是基于 Flask 的博客平台，目的是为了提供一种更加纯粹的内容写作与发布平台,通过几个简单命令,可以帮助用户无痛的从 Hexo 切换到 Peach Blog

- 推荐理由：

    熟悉 Flask 的整个开发流程,开发一个自己的博客, 帮助用户无痛的从 Hexo 切换到新的平台

- 示例代码：
   
```python
def create_app(config_name):
    app = Flask(__name__, static_folder='static', static_url_path='')

    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    misaka.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)
    hexo.init_app(app, db)
    admin.init_app(app, db)
    tools.init_app(app)
    login_manager.init_app(app)

    from .commands.hexo.cli import hexo_cli

    app.cli.add_command(hexo_cli)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    from .api_v1_0 import api as api_blueprint
    app.register_blueprint(api_blueprint, url_prefix='/api/v1')

    return app
```

- 截图：

![](http://ww1.sinaimg.cn/large/006wYWbGly1fxmgbfy4ynj311o0pamzu.jpg)

![](http://ww1.sinaimg.cn/large/006wYWbGly1fxmgahexh9j31jy1h7grc.jpg)

![](http://ww1.sinaimg.cn/large/006wYWbGly1fxpv6inei2j31lu17pn4w.jpg)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
