### ISSUE TITLE
自荐项目【mockj】 mock数据生成利器，mockjs 的 java 实现

### ISSUE THREAD

**Issue by kevin-wang001** [521xueweihan/HelloGitHub#363]
## 项目推荐
- 项目名称：mockj

- 项目地址：[https://github.com/kevin-wang001/mockj](https://github.com/kevin-wang001/mockj)
[https://gitee.com/kkk001/mockj](https://gitee.com/kkk001/mockj)

- 项目后续更新计划：后续扩展正则规则的支持

- 项目描述：mockj 是生成mock数据的利器，mockjs 的 java 实现。同时内置随机 random 一个对象的功能。让 java 开发者也能轻松使用上 mockjs 相同的功能。支持手写 mock 规则模板、随机 mock 模板 和 反射 mock 模板
效果可以参考 mockjs :[http://mockjs.com/examples.html]( http://mockjs.com/examples.html)

- 推荐理由：简单易用，容易上手。开发单元测试、挡板服务时特别能提高效率。目前以经在本人公司中使用

- 示例代码：
String template = "{" +
                  "\"name|1-10\": \"★\"," +
                  "\"flag\": \"$char\"," +
                  "\"age|1-100\": 100," +
                  "\"next|+1\": 100," +
                  "\"point|1-100.1-2\": 100," +
                  "\"boy|@random\": true," +
                  "\"startDate\": \"$date\"," +
                  "\"endDate\": \"$date(yyyy-MM-dd)\"," +
                  "\"courses|2\": [\"语文\",\"数学\",\"英语\"]," +
                  "\"courses2|1-2\": [\"语文\",\"数学\",\"英语\"]," +
                  "\"map|2-4\": {\"110000\": \"北京市\",\"120000\": \"天津市\",\"130000\": \"河北省\",\"140000\": \"山西省\"}" +
                  "}";
Foo foo = Mock.mock(template, Foo.class);
**产生的mock数据：**
{
    "age":33,
    "boy":false,
    "courses":[
        "英语",
        "英语"
    ],
    "courses2":[
        "语文"
    ],
    "endDate":1537459200000,
    "flag":"s",
    "map":{
        "130000":"河北省",
        "140000":"山西省"
    },
    "name":"★★★★★★★",
    "next":100,
    "point":67.76,
    "startDate":1537524864573
}

- 截图：

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目，月刊中已收录过类似的项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
