### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by ChungZH** [521xueweihan/HelloGitHub#364]
HelloGithub 可以建一个交流群吗？Slack 或者 qq 都行。方便大家贡献、交流 😺 ，谢谢！

**Comment by 521xueweihan** [comment]
@ChungZH 收到，我们会尽快讨论并给出结果。

**Comment by ChungZH** [comment]
@521xueweihan 关于这件事有进展了吗 :smile:

**Comment by 521xueweihan** [comment]
@ChungZH qq 我们都不用，微信的话很可能会维护成水群。

你有什么办法或者意见吗？

**Comment by feilongfl** [comment]
感觉 https://gitter.im/ 用的人挺多的

**Comment by ChungZH** [comment]
slack 或者楼上的 gitter 吧，都行~

**Comment by anson2416** [comment]
关注中 其实可以先建立一个非官方的 或者水群 主要看目的。

**Comment by 521xueweihan** [comment]
我期望交流群能够带来：
1. 能够让大家更方便的为 HG 项目做贡献、交流
2. 发现核心的贡献者和维护者
3. 找到一群热爱开源，志同道合的小伙伴
4. 帮助更多人的走进开源社区，为开源贡献力量。

人数不重要，以上是我所以希望的。

**Comment by 521xueweihan** [comment]
@ChungZH 感谢你提供的建议！
