### ISSUE TITLE
go-qrcode

### ISSUE THREAD

**Issue by yeqown** [521xueweihan/HelloGitHub#365]
## 项目推荐
- 项目名称：go-qrcode

- 项目地址：github.com/yeqown/go-qrcode

- 项目后续更新计划：暂无

- 项目描述：基于golang的二维码生成实现

- 推荐理由：对于熟悉二维码原理和生成过程有更深入的认知；也可以用于自行实现扫码登陆等功能；

- 示例代码：

```go
package main

import (
	"fmt"

	qrcode "github.com/yeqown/go-qrcode"
)

func main() {
	qrc, err := qrcode.New("https://github.com/yeqown/go-qrcode")
	if err != nil {
		fmt.Printf("could not generate QRCode: %v", err)
	}

	// save file
	if err := qrc.Save("../testdata/repo-qrcode.jpeg"); err != nil {
		fmt.Printf("could not save image: %v", err)
	}
}
```

- 截图：

<img src="https://github.com/yeqown/go-qrcode/raw/master/testdata/repo-qrcode.jpeg" width="100px"/>

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
