### ISSUE TITLE
自荐项目：Algorithm101

### ISSUE THREAD

**Issue by yichenluan** [521xueweihan/HelloGitHub#367]
## 项目推荐
- 项目名称：Algorithm101

- 项目地址：https://github.com/yichenluan/Algorithm101

- 项目后续更新计划：需要补充的有：

 1. 标准库 Sort 实现
 2. hash 表相关
 3. 二叉树
 4. 平衡二叉查找树
 5. 多路查找树
 6. 优先队列
 7. 搜索算法
 8. 查找算法
 9. 图
 10. 字符串
 11. DP

- 项目描述：

     Data Structure and Alogorithm in C++ / Go.
     重点关注标准库实现。

- 推荐理由：

1. 每一项数据结构或算法都有可运行代码及相应解释
2. 探索解析 C++/Go 标准库中的相应实现（如果有）

- 截图：

![2018-12-06 4 20 41](https://user-images.githubusercontent.com/5328290/49571011-15607b80-f973-11e8-90cb-a3ab5b0deb49.png)

**Comment by ChungZH** [comment]
说说本蒟蒻的个人看法。
就拿我会的快排来说吧，个人感觉对于概念的讲解不够多，可以举一些例子（更适合蒟蒻观看hh
还是一个很好的项目:+1:

**Comment by yichenluan** [comment]
> 说说本蒟蒻的个人看法。
> 就拿我会的快排来说吧，个人感觉对于概念的讲解不够多，可以举一些例子（更适合蒟蒻观看hh
> 还是一个很好的项目👍

大哥你真是小学五年级吗？

**Comment by ChungZH** [comment]
这是真的，不必怀疑hh

**Comment by yichenluan** [comment]
> 这是真的，不必怀疑hh

厉害厉害，想起我的小学。。。。加油

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
