### ISSUE TITLE
自荐项目 :  AntzOs

### ISSUE THREAD

**Issue by CasterWx** [521xueweihan/HelloGitHub#368]
## 项目推荐
- 项目名称：AntzOs操作系统

- 项目地址： https://github.com/CasterWx/AntzOS

- 项目后续更新计划：美化图像界面 , 为开发者提供更多可编程接口。

- 项目描述：一个简易的自制操作系统 , 通过实现RGB显存读写实现了图片显示 ,  在时钟中断中提供了可编程的接口 , 为其他开发者创造实现操作系统功能方法。

- 推荐理由：文档更新完善，可以帮助对操作系统开发有兴趣的同学理解操作系统底层的原理。

- 示例代码：
```c
	cli();
	if (fstatus(&key) + fstatus(&mouse) == 0) {
		stihlt();
	} else {
		if (fstatus(&key) != 0) {
			i = fget(&key);
			sti();
			sprintf(s, "%02X", i);
			key(binfo,s);
		} else if (fstatus(&mouse) != 0) {
			i = fget(&mouse);
			sti();
		}
      }
```

- 截图：
![img1](https://github.com/CasterWx/AntzOS/raw/master/screen/a.gif?raw=true)
![img2](https://raw.githubusercontent.com/CasterWx/AntzOS/master/screen/execute.gif)
![img3](https://github.com/CasterWx/AntzOS/raw/master/screen/antz_gif.gif?raw=true)

**Comment by CasterWx** [comment]
@521xueweihan  核心是c+汇编代码，但一直被定义成Objective-C .

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

已推荐过从零开发操作系统的教程。你这个是个很酷的项目，可以持续维护、开发。Readme 可以继续按照标准优化，加油～

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
