### ISSUE TITLE
一款使用Vim操作的文件管理器Ranger

### ISSUE THREAD

**Issue by itgoyo** [521xueweihan/HelloGitHub#369]
## 项目推荐
- 项目名称：Ranger

- 项目地址：https://github.com/ranger/ranger

- 项目后续更新计划：

- 项目描述：
Mac和Linux下面的类似Vim操作的文件管理器

- 推荐理由：
方便，快捷，不用鼠标或者触控板点开一层层的目录

[软件下载地址](https://ranger.github.io/download.html)

Unpack the archive, enter the directory and run ranger:
```
tar xvf ranger-stable.tar.gz
cd ranger-stable
./ranger.py
```

If you want to conventionally install it, for example for a multi-user system, you can run this command:
```
sudo make install
```

然后终端ranger,即可打开文件管理器

键盘右键`->`为打开的意思，浏览图片的时候可以使用改键，来预览图片

详细到底有多酷，可以自己点开此链接观看[youtube](https://www.youtube.com/watch?v=nlolvAVqn10)

<iframe width="560" height="315" src="https://www.youtube.com/embed/nlolvAVqn10" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>

配置ranger:

默认如果找不到配置文件,要先执行以下命令

```
ranger --copy-config=all
```
在/home/用户名/.config/ranger文件夹下有一系列配置文件。启用文件预览功能，需要先打开rc.conf文件

找到“set use_preview_script”一行，将其值设为“true”。本设置将启用scope.sh脚本，用于各种文件的预览；
 
找到“set preview_script”一行，将其值设为“~/.config/ranger/scope.sh”，为预览功能指定脚本文件；

找到“set preview_images”一行，将其值设为“true”，本设置启用对图片的预览功能；

找到“set preview_images_method”一行，将其值设为“w3m”，表明是用w3m作为图片预览的工具。

更多详细设置请参考:http://blog.sina.com.cn/s/blog_69e5d8400102wp2k.html

如果在使用`w3m`的过程中出现缺少`w3mimgdisplay`的时候可以使用一下命令行来安装

`sudo apt install w3m-img`

In Ranger, you can choose a program to open a file based on its extension. For example, to open a JPEG file with Feh image viewer, add this line at the top of rifle.conf:
`ext jpg = feh "$@"`
After the specific file associations, I like to have a rule to catch all the rest of the files and open them using xdg-open:
`has xdg-open, flag f = xdg-open "$1"`
### Mac相关的可以参考
https://github.com/johngodlee/ranger_rifle_conf_tut/blob/master/ranger_rifle_conf_mac.md

https://unix.stackexchange.com/questions/219765/open1-in-rifle-conf-for-ranger-on-os-x

https://unix.stackexchange.com/questions/381499/ranger-what-program-is-opening-file

---
之前推荐想这么写的，但是太多东西太多了，显得有点繁琐

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 34 期](https://hellogithub.com/periodical/volume/34/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
