### ISSUE TITLE
linux下的多home目錄切換tool

### ISSUE THREAD

**Issue by xnum** [521xueweihan/HelloGitHub#37]
## 项目推荐
- 项目：[ch](https://github.com/xnum/ch)

- 项目描述：類似virtualenv，可以在linux下建立虛擬的home目錄並切換，以管理不同工作或專案的檔案。與docker或其他虛擬化方案比較之優點在於，不必重新建立執行環境，且啟動臨時的開發用網頁伺服器更加方便。

- 推荐理由：因為日常開發需求而寫了這個工具，順道分享給大家看看是否實用。

- 实例代码：

- 截图：![](https://xnum.github.io/assets/ch.gif)

**Comment by 521xueweihan** [comment]
您推荐的项目已收录到 [15 期](https://github.com/521xueweihan/HelloGitHub/blob/master/content/15/HelloGitHub15.md#其它)，同时您已加入到 [贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/contributors.md) 中。

期待老铁后面继续推荐给力的项目 💪
