### ISSUE TITLE
Mac键盘映射软件Karabiner-Elements

### ISSUE THREAD

**Issue by itgoyo** [521xueweihan/HelloGitHub#371]
## 项目推荐
- 项目名称：Karabiner-Elements

- 项目地址：https://github.com/tekezo/Karabiner-Elements

- 项目描述：Mac上一款强大的键位修改软件

- 推荐理由：由于开发时候有的人会改键位，类似深度Vim和Emacs用户，为了适应各种开发人员编码习惯，所以重点推荐。

- 示例代码：

- 截图：

![](https://github.com/itgoyo/Mac-Shift/raw/master/mac_shift.gif)

**Comment by itgoyo** [comment]
@521xueweihan 好滴，下次会多写点东西。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 34 期](https://hellogithub.com/periodical/volume/34/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
