### ISSUE TITLE
keycastr在屏幕上显示当前按键

### ISSUE THREAD

**Issue by itgoyo** [521xueweihan/HelloGitHub#372]
## 项目推荐
- 项目名称：keycastr

- 项目地址：https://github.com/keycastr/keycastr

- 项目描述：在屏幕上实时显示当前键位

- 推荐理由：有时候录屏或者直播的时候为了方便观众知道自己的的按键是什么按键

- 截图：
![](https://github.com/keycastr/keycastr/raw/master/assets/reposition.gif)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 34 期](https://hellogithub.com/periodical/volume/34/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
