### ISSUE TITLE
js2img

### ISSUE THREAD

**Issue by ChungZH** [521xueweihan/HelloGitHub#373]
## 项目推荐
- 项目名称：
 js2image
- 项目地址：
https://github.com/xinyu198736/js2image
- 项目后续更新计划：

- 项目描述：
一个可以把 js 源代码压缩成一个 ascii 字符画的源代码的工具，压缩后的代码仍可运行
- 推荐理由：
好玩
- 示例代码：

- 截图：
![](https://cdn.ruguoapp.com/FrJ9jY9oLC8RUCvwA58CeL0WHDPE.png?imageMogr2/auto-orient/format/jpeg/thumbnail/400x2000%3E/quality/70/interlace/1)

**Comment by 521xueweihan** [comment]
@ChungZH 您推荐的项目，**已成功发布**在 [HelloGitHub 第 33 期](https://hellogithub.com/periodical/volume/33/#js2image)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
