### ISSUE TITLE
PTT 表特日報

### ISSUE THREAD

**Issue by Larry850806** [521xueweihan/HelloGitHub#374]
## 项目推荐
- 项目名称：PTT 表特日報

- 项目地址：[https://github.com/Larry850806/ptt-daily-beauty](https://github.com/Larry850806/ptt-daily-beauty)

- 项目后续更新计划：支援更多功能、美化網站、分析大家的喜好

- 项目描述：一個爬蟲專案，每天會爬取 PTT Beauty 版上的前三名，然後發送到大家的信箱

- 推荐理由：這個專案是用 Go 寫的，歡迎大家一同來參與，而且看美女有助身心健康

- 示例代码：無

- 截图：

![](https://i.imgur.com/yo4b7AB.png)

**Comment by FrontMage** [comment]
已收录至３３期

**Comment by 521xueweihan** [comment]
@Larry850806 您推荐的项目，**已成功发布**在 [HelloGitHub 第 33 期](https://hellogithub.com/periodical/volume/33/#ptt-daily-beauty)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by Larry850806** [comment]
謝謝你～我也會多跟朋友推廣 HelloGithub
