### ISSUE TITLE
MeEdu - 基于Laravel开发的在线教育系统，PHP项目

### ISSUE THREAD

**Issue by Qsnh** [521xueweihan/HelloGitHub#375]
## 项目推荐
- 项目名称：MeEdu

- 项目地址：https://github.com/Qsnh/meedu

- 项目后续更新计划：见readme.md

- 项目描述：基于Laravel开发的开源的，免费的在线教育系统。

- 推荐理由：随着知识付费领域的兴起，尤其是知识付费领域的龙头“得到”的成功，知识付费领域俨然成为了新的风口。经过这几年的发展，知识付费领域的基础建设有了很大的进步，市场上面很多知识付费的平台可以在短短几分钟之内搭建一套属于自己的知识付费应用。但是，这并不是我想要的！可能是处于程序员的角度出发，我更在乎的是这套应用是我自己可以完全控制的！所以 MeEdu 诞生了。MeEdu 寄托了我对当前知识付费领域的期望。我相信未来的每位身负技能的人都可以通过 MeEdu 来构建自己的知识付费应用，通过 MeEdu 将自己的知识进行变现。

- 示例代码：无

- 截图：

![meedu](https://user-images.githubusercontent.com/12671205/49639658-81f87a80-fa46-11e8-9545-e4e935c947c4.jpg)

**Comment by 521xueweihan** [comment]
@Qsnh 您推荐的项目，**已成功发布**在 [HelloGitHub 第 33 期](https://hellogithub.com/periodical/volume/33/#MeEdu)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
