### ISSUE TITLE
自荐项目-SimpleKernel

### ISSUE THREAD

**Issue by MRNIU** [521xueweihan/HelloGitHub#378]
## 项目推荐
- 项目名称：
SimpleKernel
- 项目地址：
https://github.com/MRNIU/SimpleKernel
- 项目后续更新计划：
还没有完成的：
设备管理
文件系统
进程管理
内存管理
POSIX API
libc
一些 shell命令
主要驱动程序
还有 持续修复 bug
- 项目描述：
用于学习操作系统内核的项目。
这里有实现一个内核过程中，各个阶段的源码，你可以从自己感兴趣的地方开始。
目前已经完成了启动、gdt、idt 的初始化，系统中断（isr）以及键盘输入。
- 推荐理由：
  - 成体系的内核实现
  - 涉及到的资料、知识比较完善
  - 源码注释清楚
- 示例代码：
生成内核映像的 makefile 规则
![2018-12-09 2 20 49](https://user-images.githubusercontent.com/12967882/49694061-a62a9780-fbbd-11e8-83c1-0dc5a84add77.png)

与 gdt 相关数据的宏定义
![2018-12-09 2 22 24](https://user-images.githubusercontent.com/12967882/49694072-de31da80-fbbd-11e8-9b38-5227f0a51ce1.png)

- 截图：
bochs 运行截图
![2018-12-09 2 16 37](https://user-images.githubusercontent.com/12967882/49694037-18e74300-fbbd-11e8-9f0a-18dccbdeaaa3.png)

- 补充说明：

这个项目刚开始是因为我有抄一个 linux0.1x 内核的计划，以此加深对操作系统的理解，不过 linux 越看越坑，最后很多东西还是没搞明白，参考资料有一大摞，真的是掉进坑里出不来了。

项目中需要了解的知识我会整理成文档放到一块，免去了到处找资料的麻烦，参考项目我也有列出，你可以对比不同内核的实现思路有什么不一样。

emmm就这些吧。

**Comment by 521xueweihan** [comment]
@MRNIU 
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
