### ISSUE TITLE
如何让 vim，tmux，zsh 成为我们的神器

### ISSUE THREAD

**Issue by FengShangWuQi** [521xueweihan/HelloGitHub#379]
## 项目推荐
- 项目名称：
如何让 vim，tmux，zsh 成为我们的神器

- 项目地址：
https://github.com/FengShangWuQi/to-vim-tmux-zsh

- 项目后续更新计划：
暂无

- 项目描述：
如何让 vim，tmux，zsh 成为我们的神器

- 推荐理由：
让喜欢终端的童鞋更喜欢终端。

- 示例代码：
无

- 截图：

vim
![image](https://user-images.githubusercontent.com/17982705/49985345-8a9d0380-ffa6-11e8-9390-a7cd999529d6.png)

tmux
![image](https://user-images.githubusercontent.com/17982705/49985413-d18af900-ffa6-11e8-9113-a74870aced6b.png)

zsh
![image](https://user-images.githubusercontent.com/17982705/49985423-da7bca80-ffa6-11e8-9f8f-89c954b2602c.png)

**Comment by 521xueweihan** [comment]
@FengShangWuQi 建议：
