### ISSUE TITLE
GankMM:（Material Design & MVP & Retrofit + OKHttp & RecyclerView ...）Gank.io Android客户端

### ISSUE THREAD

**Issue by maning0303** [521xueweihan/HelloGitHub#38]
## 项目推荐
- 项目：
[GankMM](https://github.com/maning0303/GankMM)

- 项目描述：
（Material Design & MVP & Retrofit + OKHttp & RecyclerView ...）Gank.io Android客户端：每天一张美女图片，一个视频短片，若干Android，iOS等程序干货，周一到周五每天更新，数据全部由 干货集中营 提供。

- 推荐理由：
（项目简单完整，已发布市场，涉及内容全面）
1.Retrofit和OKHttp的使用；
2.MVP模式的基本使用；
3.RecycleView控件的使用；
4.状态的的颜色的设置（Android 4.4 +）；
5.Android Material Design 风格控件的基本使用；
6.SQLite的基本使用；
7.WebView的使用,夜间模式；
8.Jsoup抓取网页数据；
9.Android 6.0权限适配
10.夜间模式的使用
11.三方开源库的使用
12.Android 7.0适配安装升级

- 实例代码：

[https://github.com/maning0303/GankMM](https://github.com/maning0303/GankMM)

- 截图：
![](https://github.com/maning0303/GankMM/raw/master/screenshots/gank_gif.gif)
![](https://github.com/maning0303/GankMM/raw/master/screenshots/gank_day_01.png)
![](https://github.com/maning0303/GankMM/raw/master/screenshots/gank_night_01.png)

**Comment by 521xueweihan** [comment]
@maning0303 Gif 动图太大了，不利于功能展示。 建议：
- 只录制主要功能，以缩短录制时间
- 压缩 GIF 图片：http://www.iloveimg.com/zh_cn/compress-image/compress-gif

**Comment by maning0303** [comment]
压缩了下，到了5M

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功收录**在 [HelloGitHub 第 17 期](https://github.com/521xueweihan/HelloGitHub/blob/master/content/17/HelloGitHub17.md)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，如果方便可以 Star ⭐️ 本项目，让更多人看到本项目。
