### ISSUE TITLE
自荐项目-使用zsh、oh-my-zsh、tmux、vim和docker打造随取随用的开发环境

### ISSUE THREAD

**Issue by noobcoderT** [521xueweihan/HelloGitHub#380]
## 项目推荐
- 项目名称：
使用zsh、oh-my-zsh、tmux、vim和docker打造随取随用的开发环境
- 项目地址：
https://github.com/noobcoderT/myvimrc
- 项目后续更新计划：
暂无
- 项目描述：
基于[amix的vim配置](https://github.com/amix/vimrc)，将vim、zsh、oh-my-zsh和tmux统一打包成docker镜像，构造一个随取随用的开发环境。
- 推荐理由：
  - 基于16k+ star的开源vim配置，有详细的文档说明和丰富的插件；
  - 提供zsh、oh-my-zsh及tmux的集成，方便易用；
  - 提供docker打包脚本，可自定义更改打包过程；
  - 提供打包好的镜像，docker命令一键拉取。
- 示例代码：
无
- 截图：
tmux+zsh+oh-my-zsh:
![image](https://user-images.githubusercontent.com/12445813/50064163-a7297d80-01ea-11e9-9f1f-6d4c0ee8a9c7.png)
vim:
![image](https://user-images.githubusercontent.com/12445813/50064136-852ffb00-01ea-11e9-8e9b-b8d9f3383fc6.png)
- 补充说明
详细介绍请见[个人博客](https://traceme.space/blog/page/6/zshoh-my-zshtmuxvimdocker/)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
