### ISSUE TITLE
PX->REM的IntelliJ Idea插件

### ISSUE THREAD

**Issue by sunqian1991** [521xueweihan/HelloGitHub#382]
## 项目推荐
- 项目名称：PX转REM的IntelliJ Idea插件

- 项目地址：[PX2REM](https://github.com/sunqian1991/WebStorm-PX2REM)

- 项目后续更新计划：

- 项目描述：在IntelliJ Idea和Webstorm中将CSS里面的px转为rem单位的插件

- 推荐理由：写前端样式时更加方便

- 示例代码：

- 截图：

![image](https://github.com/sunqian1991/WebStorm-PX2REM/raw/dev/resources/option.gif)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
