### ISSUE TITLE
Maka.js,一款基于前端微服务设计思想的React框架

### ISSUE THREAD

**Issue by ziaochina** [521xueweihan/HelloGitHub#384]
## 项目推荐
- 项目名称：maka.js

- 项目地址：https://github.com/makajs/maka

- 项目描述：一款基于前端微服务设计思想的React框架

- 推荐理由：更多设计和生态角度思考超复杂SPA程序的实现方式

- 示例代码：

```
import pkgJson from './package.json'
import { actionMixin } from 'maka'
import './style.less'

const name = pkgJson.name

const state = {
    data: {
        content: 'hello ',
        input: ''
    }
}

@actionMixin('base')
class action {
    constructor(option) {
        Object.assign(this, option.mixins)
    }

    onChange = (e) => {
        this.base.setState({ 'data.input': e.target.value })
        console.log(this.base.getState('data.input'))
    }
}

const view = {
    component: 'div',
    className: 'hello',
    children: [{
        component: 'div',
        children: '{{data.content + data.input}}'
    }, {
        component: 'input',
        placeholder: 'world',
        value: '{{data.input}}',
        onChange: '{{$onChange}}'
    },{
        component: 'AppLoader',
        appName: 'sub'
    }]
}

export {
    name,
    state,
    action,
    view
}
```

- 截图：

![framework](https://user-images.githubusercontent.com/4494312/50320846-27145800-0509-11e9-97fa-6a072863668f.png)
![dashboard](https://user-images.githubusercontent.com/4494312/50320851-309dc000-0509-11e9-8243-c7e563658996.png)
![person-list](https://user-images.githubusercontent.com/4494312/50320858-3398b080-0509-11e9-91e4-f0622110ccc7.png)
![bom](https://user-images.githubusercontent.com/4494312/50320859-3693a100-0509-11e9-8ced-194d10a10e0e.png)
![home](https://user-images.githubusercontent.com/4494312/50320863-3abfbe80-0509-11e9-8165-f9f97a75901c.png)
![rpt](https://user-images.githubusercontent.com/4494312/50320864-3dbaaf00-0509-11e9-9f7c-c8e1cd94f780.png)

**Comment by 521xueweihan** [comment]
您好，经过我们讨论，此项目**暂不能收录**到 HG 月刊中。
