### ISSUE TITLE
用动画的形式呈现解LeetCode题目

### ISSUE THREAD

**Issue by nivance** [521xueweihan/HelloGitHub#385]
## 项目推荐
- 项目名称：LeetCodeAnimation

- 项目地址：https://github.com/MisterBooo/LeetCodeAnimation

- 项目后续更新计划：作者会尽力将LeetCode上所有的题目都用动画的形式演示出来，计划用3到4年时间去完成它

- 项目描述：用动画的形式呈现解LeetCode题目的思路

- 推荐理由：目前为止最佳leetcode解题方式

- 示例代码：无

- 截图：
![1](https://user-images.githubusercontent.com/3291404/50322767-9e4dea00-0511-11e9-80fd-7b914d99e6d6.jpg)

**Comment by 521xueweihan** [comment]
@nivance 您推荐的项目，**已成功发布**在 [HelloGitHub 第 33 期](https://hellogithub.com/periodical/volume/33/#LeetCodeAnimation)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
