### ISSUE TITLE
轴动效果，快速实现github404效果

### ISSUE THREAD

**Issue by bestvist** [521xueweihan/HelloGitHub#386]
## 项目推荐
- 项目名称：
轴动效果 axial3d
- 项目地址：
https://github.com/bestvist/axial3d
- 项目后续更新计划：
暂无
- 项目描述：
轴动效果，快速实现github404效果
- 推荐理由：
高端、大气、上档次
- 示例代码：
```
<html>
<head>
    <title>Demo - Axial3d</title>
</head>
<body>
    <script src="https://unpkg.com/axial3d"></script>
    <div id="axial3d"></div>
    <script>
        (function () {
            var options = {
                selector: '#axial3d',
                imgs: [
                    {src: 'https://bestvist.github.io/axial3d/public/demo1/bg.png', left: '50px', top: '10px'},
                    {src: 'https://bestvist.github.io/axial3d/public/demo1/2.png', left: '150px', top: '10px'},
                    {src: 'https://bestvist.github.io/axial3d/public/demo1/3.png', left: '50px', top: '300px'},
                    {src: 'https://bestvist.github.io/axial3d/public/demo1/4.png', left: '300px', top: '300px'}
                ]
            }
            var effect = new Axial3d(options);
        })()
    </script>
</body>
</html>
```
- 截图：
![](https://camo.githubusercontent.com/cc335156a90a0c64485bb6187be99b6624545b6d/68747470733a2f2f62657374766973742e6769746875622e696f2f617869616c33642f7075626c69632f6769746875623430342e676966)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 34 期](https://hellogithub.com/periodical/volume/34/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
