### ISSUE TITLE
vue时钟组件

### ISSUE THREAD

**Issue by bestvist** [521xueweihan/HelloGitHub#387]
## 项目推荐
- 项目名称：
vue clock2
- 项目地址：
https://github.com/bestvist/vue-clock2
- 项目后续更新计划：
无
- 项目描述：
vue时钟组件，可自动更新实现或显示固定时间
- 推荐理由：
满足钟表类项目需求
- 示例代码：
```
<template>
  <clock :time="time"></clock>
</template>

<script>
  import Clock from 'vue-clock2';
  export default {
    components: { Clock },
    data () {
      return {
          time: '10:40:00'
      }
    }
  }
</script>
```
- 截图：
![](https://github.com/bestvist/vue-clock2/blob/master/clock-color.png)

**Comment by ming995** [comment]
@bestvist 感觉可以加个电子时钟样式显示😂

**Comment by bestvist** [comment]
> @bestvist 感觉可以加个电子时钟样式显示

哈哈，感觉可以

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
