### ISSUE TITLE
神奇的python应用合集

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#391]
## 项目推荐
- 项目名称：神奇的python应用

- 项目地址：https://github.com/mahmoud/awesome-python-applications.git

- 项目后续更新计划：

- 项目描述：介绍Python有趣神奇的开源项目，目前涵盖了15个领域，180+个项目

- 推荐理由：
Python已成为现在的主流语言，但是寻找好的项目资源，费时费力。点开此项目，省时省力。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 34 期](https://hellogithub.com/periodical/volume/34/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
