### ISSUE TITLE
DevHub

### ISSUE THREAD

**Issue by ChungZH** [521xueweihan/HelloGitHub#392]
## 项目推荐
- 项目名称：
DevHub
- 项目地址：
https://github.com/devhubapp/devhub
- 项目后续更新计划：

- 项目描述：
这个工具可以方便的帮你查看 GitHub 的消息、动态。
- 推荐理由：
使用，有趣
- 示例代码：

- 截图：
![](https://user-images.githubusercontent.com/619186/49800542-dfcee000-fd2e-11e8-8e08-ff95c5872513.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 35 期](https://hellogithub.com/periodical/volume/35/#devhub)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
