### ISSUE TITLE
动漫角色生成项目-通过自定义属性

### ISSUE THREAD

**Issue by zzugbb** [521xueweihan/HelloGitHub#394]
## 项目推荐
- 项目名称：
makegirlsmoe_web

- 项目地址：
https://github.com/makegirlsmoe/makegirlsmoe_web
项目网站：https://make.girls.moe/#/

- 项目后续更新计划：
新的项目—Crypko。在Crypko中，你可以从以太坊区块链上获取并交易AI生成的二次元角色

- 项目描述：
动漫角色图片生成，选择发色，发型，眼睛，皮肤，微笑，眼镜，风格，等等特征生成二次元图片

- 推荐理由：二次元头像定制，好玩

- 示例代码：
克隆时，使用 `git-lfs` 替换 `git`
    ```js
    git-lfs clone https://github.com/makegirlsmoe/makegirlsmoe_web.git 
    Modify src/Config.js and set var debug=true;
    npm install
    npm start
    ```
- 截图：
![image](https://user-images.githubusercontent.com/31366103/50389732-c1bea200-0768-11e9-89ca-71cf2bfdfda4.png)

![image](https://user-images.githubusercontent.com/31366103/50389738-e155ca80-0768-11e9-9814-ff983499b92b.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 36 期](https://hellogithub.com/periodical/volume/36/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
