### ISSUE TITLE
自荐项目-LaravelS 基于Swoole加速Laravel

### ISSUE THREAD

**Issue by hhxsv5** [521xueweihan/HelloGitHub#395]
## 项目推荐
- 项目名称：LaravelS

- 项目地址：https://github.com/hhxsv5/laravel-s

- 项目后续更新计划：
    1.Bug修复
    2.关注Swoole，添加更多特性
    3.关注Laravel/Lumen，确保兼容更多版本

- 项目描述：一个胶水项目，用于快速集成[Swoole](https://www.swoole.com/)到[Laravel](https://laravel.com/)，常驻内存提升性能，内置HTTP/WebSocket Server，支持TCP/UDP Server、自定义进程、异步的事件监听、异步任务队列、毫秒级定时任务、平滑Reload，与Nginx配合搭建高可用分布式服务器群，开箱即用。

- 推荐理由：
    - 集成LaravelS之后无需使用PHP FPM，直接基于Swoole开启Http Server
    - 代码常驻内存之中，性能提升非常明显
    - 可快速开发WebSocket/TCP/UDP服务
    - 支持异步任务队列、自定义进程、定时任务，支持更多的业务场景
    - 可直接使用Swoole的很多特性

- 示例代码：
    ```bash
    # 在Laravel/Lumen项目根目录执行
    composer require "hhxsv5/laravel-s:~3.3" -vvv
    php artisan laravels publish
    bin/laravels start
    ```

- 截图：
![image](https://user-images.githubusercontent.com/7278743/50393919-538fd480-0794-11e9-8e7e-df7876bd6f2a.png)
![image](https://user-images.githubusercontent.com/7278743/50394013-40313900-0795-11e9-8c20-bc1da8567baf.png)
![image](https://user-images.githubusercontent.com/7278743/50394019-4aebce00-0795-11e9-9cf2-89151eef2e21.png)

### 编辑完推荐项目的信息，**请删除**下述提示信息
1. [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271)

2. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

3. HelloGitHub 网站：https://hellogithub.com

再次感谢您对《HelloGitHub》项目的支持！

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 34 期](https://hellogithub.com/periodical/volume/34/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
