### ISSUE TITLE
开源运维平台

### ISSUE THREAD

**Issue by zyupo** [521xueweihan/HelloGitHub#399]
## 项目推荐
- 项目名称：
Spug开源运维平台
- 项目地址：
https://github.com/openspug/spug
- 项目后续更新计划：
后续支持发布支持审批，支持流程化发布，执行命令支持录像回放，发布回滚记录日志等。
- 项目描述：
开源运维平台基于Docker镜像发布部署，帮助中小型企业完成简单方便的自动化部署操作，支持运维常见管理功能主机管理、任务计划管理、发布部署、配置文件管理等
- 推荐理由：
使用Python+VUE实现的开源运维平台，基于Docker镜像发布部署，简化项目部署，项目前后端分离，方便二次开发。
- 截图：
[登录预览](https://github.com/openspug/spug/blob/master/docs/demo/login.gif)
[用户管理](https://github.com/openspug/spug/blob/master/docs/demo/user.gif)
[主机管理](https://github.com/openspug/spug/blob/master/docs/demo/host.gif)
[发布管理](https://github.com/openspug/spug/blob/master/docs/demo/publish.gif)
[任务管理](https://github.com/openspug/spug/blob/master/docs/demo/tasks.gif)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 35 期](https://hellogithub.com/periodical/volume/35/#spug)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
