### ISSUE TITLE
推荐语种识别工具langid

### ISSUE THREAD

**Issue by zhbzz2007** [521xueweihan/HelloGitHub#4]
项目名称：langid

项目地址：https://github.com/saffsd/langid.py

项目描述：用于识别输入文本数据所属的语种，目前支持97种语言识别；

项目依赖：numpy

Demo：

    import langid
    text1 = "I am a coder and love data mining"
    text2 = "请注明作者和出处并保留声明和联系方式"
    
    print langid.classify(text1)
    print langid.classify(text2)
    
    # ('en', 0.9999957874458753)
    # ('zh', 1.0)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。（推荐的项目、项目信息格式、内容简直完美！）

如您推荐的项目在《HelloGithub》月刊中推荐，则会同时*写明推荐人*。😜

再次感谢您对《HelloGithub》项目的支持！
