### ISSUE TITLE
自荐项目-veneno

### ISSUE THREAD

**Issue by zhuyingda** [521xueweihan/HelloGitHub#40]
## 项目推荐
- 项目：[veneno](https://github.com/zhuyingda/veneno)

- 项目描述：一个基于Node.js编写的web安全漏洞自动化扫描框架

- 推荐理由：同类fuzz、渗透工具在安全领域中不胜枚举，但多数是python、java写的，对于熟悉js的程序员并不友好，另外 Node.js的异步非阻塞特性其实很适合用于这个业务场景。

- 实例代码：直接在仓库里master分支看吧

- 截图：[详见文档](https://www.zhuyingda.com/docs/veneno.html)

**Comment by 521xueweihan** [comment]
您推荐的项目已收录到 [15 期](https://github.com/521xueweihan/HelloGitHub/blob/master/content/15/HelloGitHub15.md#javascript-项目)，同时您已加入到 [贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/contributors.md) 中。

期待老铁后面继续推荐给力的项目 💪
