### ISSUE TITLE
基于spark sql引擎的即席查询服务

### ISSUE THREAD

**Issue by teeyog** [521xueweihan/HelloGitHub#400]
## 项目推荐
- 项目名称：IQL

- 项目地址：https://github.com/teeyog/IQL

- 项目后续更新计划：

- 项目描述：An ad hoc query service based on the spark sql engine.(基于spark sql引擎的即席查询服务)

- 推荐理由：
  - 优雅的交互方式，支持多种datasource/sink，多数据源混算
  - spark常驻服务，基于zookeeper的引擎自动发现
  - 负载均衡，多个引擎随机执行
  - 多session模式实现并行查询
  - 采用spark的FAIR调度，避免资源被大任务独占
  - 基于spark的动态资源分配，在无任务的情况下不会占用executor资源
  - 支持Cluster和Client模式启动
  - 基于Structured Streaming实现SQL动态添加流
  - 类似SparkShell交互式数据分析功能
  - 高效的script管理，配合import/include语法完成各script的关联
  - 对数据源操作的权限验证
 
- 示例代码：
```
-- 加载MySQL数据
load jdbc.user
where driver="com.mysql.jdbc.Driver" 
      and url="jdbc:mysql://localhost/db?characterEncoding=utf8" 
      and user="root" 
      and password="***" 
as tb_mysql;

-- 加载HBase数据
load hbase.user_info
where `spark.table.schema`="userid:String,osversion:String,toolversion:String"
	   and `hbase.table.schema`=":rowkey,info:osversion,info:toolversion" 
	   and `hbase.zookeeper.quorum`="localhost:2181"
as tb_hbase; 

select * from tb_mysql join tb_hbase on tb_mysql.id=tb_hbase.userid 
as tb_join;

-- 保存为json文件
save tb_join as json.`/tmp/path` partitionBy date coalesce 2;
```

- 截图：![](https://upload-images.jianshu.io/upload_images/3597066-e19cdef507fd77a7.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 35 期](https://hellogithub.com/periodical/volume/35/#IQL)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
