### ISSUE TITLE
Ant Design

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#401]
## 项目推荐
- 项目名称：Ant Design

- 项目地址：https://github.com/ant-design

- 项目后续更新计划：

- 项目描述：一套企业级的 UI 设计语言和 React 实现。

- 推荐理由：

提炼自企业级中后台产品的交互语言和视觉风格。
开箱即用的高质量 React 组件。
使用 TypeScript 构建，提供完整的类型定义文件。
全链路开发和设计工具体系。
中英文对照，上手容易。

- 示例代码：
[官网](https://github.com/ant-design/ant-design/blob/master/README-zh_CN.md)

**Comment by 521xueweihan** [comment]
@daixiang0 
您好，该项目已经推荐过：第 01 期、JavaScript 项目

https://hellogithub.com/periodical/search/?q=https://github.com/ant-design#ant-design
