### ISSUE TITLE
自荐项目：针对于前端技术体系的每日分享

### ISSUE THREAD

**Issue by wubaiqing** [521xueweihan/HelloGitHub#403]
## 项目推荐
- 项目名称：zaobao

- 项目地址：https://github.com/wubaiqing/zaobao/

- 项目后续更新计划：每周至少三次分享

- 项目描述：每日时报，会以前端技术体系为主要分享课题。内容会以：文章、工具、新闻、视频几大板块作为主要分类。

- 推荐理由：
不知道大家有没有跟我一样的情况，总是需要了解一些前沿的技术；其目的可能是为了让技术精进，也有可能是害怕技术落后而掉队；总之需要从各类网站了解一些前沿信息。学习加整理这个过程是非常耗时的。所以我希望有一个像阮一峰老师的每周分享，或者蚂蚁金服陈成一样的微信群，来快速的学习有价值的东西。可能是这个信息源我还没有找到，所以我打算自己来做，于是才有了这个开源项目。

- 示例代码：

- 截图：
![效果](https://raw.githubusercontent.com/wubaiqing/zaobao/master/docs/assets/introduce_1.png)

**Comment by wubaiqing** [comment]
OK，我需要先想一下合作的方式。

**Comment by 521xueweihan** [comment]
@wubaiqing 有具体细节，我可以拉该项目负责人，你们可以进行直接的沟通。

**Comment by wubaiqing** [comment]
@521xueweihan 谢谢推荐，我已经联系 FAIRYEVER 了。

**Comment by 521xueweihan** [comment]
@wubaiqing 好的，祝你们合作愉快
