### ISSUE TITLE
Github开源项目自荐：web前端入门图文教程

### ISSUE THREAD

**Issue by qianguyihao** [521xueweihan/HelloGitHub#404]
## 项目推荐
- 项目名称：web前端入门图文教程

- 项目地址：https://github.com/qianguyihao/Web

- 项目后续更新计划：坚持平均每日更新一小时，不断完善项目。

- 项目描述：web前端入门的图文教程，包含从0到1入门的基础和进阶内容，非常详细和全面。

- 推荐理由：1、网上的大部分入门教程，都不太适合初学者，本项目争取照顾到每一位入门者的同理心。2、帮助入门web前端的人提供一个精品学习资源，提高学习效率，少走很多弯路。3、可以当做是前端字典，随时翻阅，查漏补缺。

- 示例代码：暂无。

- 截图：

![image](https://user-images.githubusercontent.com/8827896/51222283-fdb7e200-1977-11e9-97e3-abff4235cce1.png)

**Comment by 521xueweihan** [comment]
@qianguyihao

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 36 期](https://hellogithub.com/periodical/volume/36/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by qianguyihao** [comment]
> 您推荐的项目，**已成功发布**在 [HelloGitHub 第 36 期](https://hellogithub.com/periodical/volume/36/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
> 
> 欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

好，非常感谢您的推荐。已经将 <https://hellogithub.com> 告知我的小伙伴们。期待越办越好~

**Comment by 521xueweihan** [comment]
@qianguyihao 感谢支持，期待后续继续推荐如此有趣、有价值的项目。
