### ISSUE TITLE
利用动态二维码传输更多信息

### ISSUE THREAD

**Issue by wojs5** [521xueweihan/HelloGitHub#405]
## 项目推荐
- 项目名称：TXQR

- 项目地址：https://github.com/divan/txqr

- 项目后续更新计划：

- 项目描述：TXQR (Transfer via QR) is a protocol and set of tools and libs to transfer data via animated QR codes. It uses fountain codes for error correction.

- 推荐理由：动态二维码传输更多信息

- 示例代码：

- 截图：
![image](https://user-images.githubusercontent.com/20939996/50505940-3ec38180-0ab1-11e9-87ed-2a83aa1b26c7.png)

https://github.com/divan/txqr/blob/master/docs/demo.gif

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 34 期](https://hellogithub.com/periodical/volume/34/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
