### ISSUE TITLE
Open AI 深度强化学习资源

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#406]
## 项目推荐
- 项目名称：Open AI 深度强化学习资源

- 项目地址：
https://github.com/openai/spinningup

- 项目后续更新计划：

- 项目描述：
这是OpenAI制作的教育资源，可以更容易地学习深层强化学习（深度RL）。

- 推荐理由：
官方项目，质量保证，浅显易懂。
提供练手小程序，方便初学者或对深层强化学习好奇者入门。

- 示例代码：
[链接](https://spinningup.openai.com)

**Comment by xibinyue** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 34 期](https://hellogithub.com/periodical/volume/34/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
