### ISSUE TITLE
Quick Draw

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#407]
## 项目推荐
- 项目名称：Quick Draw

- 项目地址：https://github.com/1991viet/QuickDraw

- 项目描述：

[Quick Draw](https://quickdraw.withgoogle.com/) 是谷歌开发的一个流行的在线游戏，神经网络会猜测你在画什么。神经网络从每幅图画中学习，提高正确猜测涂鸦内容的能力。

- 推荐理由：

你现在可以基于这个仓库，用 Python 构建自己的 Quick Draw 游戏。有一个详细教程。使用这个代码，你可以运行一个应用程序，可以在计算机的摄像头前绘制，也可以在画布上绘制

- 截图：
https://github.com/1991viet/QuickDraw/blob/master/demo/quickdraw.gif"

**Comment by daixiang0** [comment]
@ming995 add "machine learn" label if possible could be better.

**Comment by ming995** [comment]
@daixiang0 Ok，I think is good
