### ISSUE TITLE
自荐项目：将Bing每日美图设置为GNOME锁屏

### ISSUE THREAD

**Issue by zhangzp9970** [521xueweihan/HelloGitHub#408]
## 项目推荐
- 项目名称：GnomeBingLockScreen

- 项目地址：https://github.com/zhangzp9970/GnomeBingLockScreen

- 项目后续更新计划：
1.增加新功能：删除超过一定时间的图片

- 项目描述：一个将必应美图设置为GNOME锁屏壁纸的小python脚本

- 推荐理由：
1.代码量少，结构清晰，适合新手学习
2. 改变了GNOME一成不变的锁屏壁纸，提升用户体验

- 截图：
![img](https://raw.githubusercontent.com/zhangzp9970/GnomeBingLockScreen/master/img/Screenshot.png)

**Comment by 521xueweihan** [comment]
@zhangzp9970 非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
