### ISSUE TITLE
[建议] 每周更新时 release，配合 GitHub 的 watch release only 方便订阅

### ISSUE THREAD

**Issue by Songkeys** [521xueweihan/HelloGitHub#409]
如题。

直接订阅的话，issues 太多会干扰信息获取；可以选择 release only 仅订阅每周的本体更新。

![image](https://user-images.githubusercontent.com/22665058/50512848-386ede80-0a8c-11e9-83f9-27f50c64c90f.png)

可以参考阮一峰的 [weekly](https://github.com/ruanyf/weekly/releases) 的做法。

最后感谢作者的好项目，辛苦了！

**Comment by 521xueweihan** [comment]
@Songkeys 好主意！

**Comment by pwwang** [comment]
Great suggestion. I will follow in this way to get away those annoying issue notifications.

**Comment by 521xueweihan** [comment]
@Songkeys 已新增：https://github.com/521xueweihan/HelloGitHub/releases
