### ISSUE TITLE
【推荐好文章】什么是真正的程序员

### ISSUE THREAD

**Issue by LanjianNUll** [521xueweihan/HelloGitHub#410]
推荐好文章：
-  [什么是真正的程序员(中文)](https://www.cnblogs.com/xueweihan/p/5220513.html)
-  [什么是真正的程序员(英文)](http://ferd.ca/the-little-printf.html)
-  [什么是真正的程序员(个人博客理解)](https://blog.csdn.net/sinat_23156865/article/details/85223941)

**Comment by 521xueweihan** [comment]
@LanjianNUll HelloGitHub 暂时不收录文章，感谢推荐。😄 那个中文版是我翻译的

**Comment by 521xueweihan** [comment]
@LanjianNUll 老铁可以推荐到，[阮一峰周刊](https://github.com/ruanyf/weekly) 👍

**Comment by LanjianNUll** [comment]
尴尬了，老铁

**Comment by 521xueweihan** [comment]
@LanjianNUll 哈哈哈，那个是我博客园的博客。

**Comment by LanjianNUll** [comment]
嗯，翻译的贼棒！

**Comment by LanjianNUll** [comment]
[【推荐github总结】互联网 Java 工程师进阶知识完全扫盲](https://github.com/doocs/advanced-java),不知道这种会不会收录，也推荐下

**Comment by 521xueweihan** [comment]
@LanjianNUll 感谢。该项目可以推荐，重新提交 issues
