### ISSUE TITLE
click

### ISSUE THREAD

**Issue by kaixinbaba** [521xueweihan/HelloGitHub#413]
## 项目推荐
- 项目名称：

- 项目地址：
https://github.com/pallets/click
- 项目后续更新计划：

- 项目描述：
python命令行的库
- 推荐理由：
通过装饰器装饰命令行接口，支持各种参数类型，子命令，命令行效果，我工作中的命令行工具都是用这个库编写的，目前看6.8k的star
- 示例代码：
import click

@click.command()
@click.option("--count", default=1, help="Number of greetings.")
@click.option("--name", prompt="Your name",
              help="The person to greet.")
def hello(count, name):
    """Simple program that greets NAME for a total of COUNT times."""
    for _ in range(count):
        click.echo("Hello, %s!" % name)

if __name__ == '__main__':
    hello()
- 截图：
![image](https://user-images.githubusercontent.com/22809336/50578939-35ecfa00-0e7b-11e9-9960-68f4a562a965.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 34 期](https://hellogithub.com/periodical/volume/34/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
