### ISSUE TITLE
【小程序项目】在线借书平台

### ISSUE THREAD

**Issue by imageslr** [521xueweihan/HelloGitHub#414]
## 项目推荐
- 项目名称：在线借书平台

- 项目地址：https://github.com/imageslr/weapp-library

- 项目后续更新计划：暂无

- 项目描述：该小程序项目提供在线借书功能，连接读者与图书馆，实现图书借阅线上化。界面风格良好，功能完整。具有注册登录、图书搜索、书单系统、订单管理等功能。

- 推荐理由：该项目开发流程规范，文档完善，适合初学者学习
  * 研究多种设计规范，精心打磨产品界面与交互，确保良好的用户体验
  * 利用 Swagger 编写详细的RESTful API 文档
  * 前后端分离开发
  * 小程序端经过多次重构，尽可能实现组件化

- 截图：
![image](https://user-images.githubusercontent.com/17822028/50583589-14a10380-0ea5-11e9-82e2-330898cb3678.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 34 期](https://hellogithub.com/periodical/volume/34/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
