### ISSUE TITLE
自荐项目：C++跨平台视频播放器

### ISSUE THREAD

**Issue by itisyang** [521xueweihan/HelloGitHub#417]
## 项目推荐
- 项目名称：playerdemo

- 项目地址：https://github.com/itisyang/playerdemo

- 项目后续更新计划：换肤功能，Mac平台支持

- 项目描述：一个跨平台视频播放器，开源版 potplayer。用于学习和交流音视频技术。

- 推荐理由：入门级视频播放器，拥有视频播放器基本功能，适合学习播放器技术

- 示例代码：

- 截图：
![运行画面](https://raw.githubusercontent.com/itisyang/MyImages/master/playerdemo/0.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 34 期](https://hellogithub.com/periodical/volume/34/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
