### ISSUE TITLE
📝 Hve Notes - 一个静态博客写作客户端

### ISSUE THREAD

**Issue by ChungZH** [521xueweihan/HelloGitHub#420]
## 项目推荐
- 项目名称：
 Hve Notes 

- 项目地址：
https://github.com/hve-notes/hve-notes
- 项目后续更新计划：

- 项目描述：
🌈 Hve Notes 一个静态博客写作客户端。你可以用它来记录你的生活、心情、知识、笔记、创意... ...
- 推荐理由：
简单好用
- 示例代码：

- 截图：
![](https://raw.githubusercontent.com/hve-notes/hve-notes/master/hve-notes-app.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 34 期](https://hellogithub.com/periodical/volume/34/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
