### ISSUE TITLE
万物皆可 RSS

### ISSUE THREAD

**Issue by adrianzhang** [521xueweihan/HelloGitHub#421]
## 项目推荐
- 项目名称：RSSHub

- 项目地址：https://github.com/DIYgod/RSSHub

- 项目后续更新计划：去问项目持有人。

- 项目描述：RSSHub 是一个轻量、易于扩展的 RSS 生成器，可以给任何奇奇怪怪的内容生成 RSS 订阅源

- 推荐理由：反爬虫使爬取内容很艰难，有了这个项目，将要爬取的页面做成一个rss，然后对rss订阅的内容再做处理，即可成为一个稳定的爬虫。

- 示例代码： https://rsshub.app/weibo/user/1195230310，便得到了微博用户何炅(id:1195230310)的最新一页微博。

- 截图：
![screenshot from 2019-01-14 13-39-07](https://user-images.githubusercontent.com/3865309/51097859-582f3200-1802-11e9-84aa-c2f3414870a8.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 34 期](https://hellogithub.com/periodical/volume/34/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
