### ISSUE TITLE
【自荐项目】轻量级室内导航方案

### ISSUE THREAD

**Issue by tower1229** [521xueweihan/HelloGitHub#422]
## 项目推荐
- 项目名称：
Tracesr(觅迹寻路)

- 项目地址：
移动端导航 https://github.com/tracesr/navigation
PC端编辑器 https://github.com/tracesr/map-editor

- 项目后续更新计划：
1. 消息系统
2. 主题功能
- 项目描述：
轻量级室内导航解决方案，主要应用于商超、景点、园区等区域内寻路场景，结合使用场景可以扩展全局消息、商家消息、和途径消息等多样化功能。
- 推荐理由：

- 示例代码：

- 截图：
![](https://tracesr.github.io/static/tracesr_os.png)

**Comment by 521xueweihan** [comment]
@tower1229 连接请更新成具体项目。

**Comment by tower1229** [comment]
@521xueweihan 已更新，这个项目包含移动端导航和PC端编辑器两部分

**Comment by 521xueweihan** [comment]
@tower1229 
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
