### ISSUE TITLE
项目推荐 GSYGithubAppFlutter

### ISSUE THREAD

**Issue by w4ctech** [521xueweihan/HelloGitHub#425]
## 项目推荐
- 项目名称：GSYGithubAppFlutter

- 项目地址：https://github.com/CarGuo/GSYGithubAppFlutter

- 项目后续更新计划：

- 项目描述：一款跨平台的开源Github客户端App，提供更丰富的功能，更好体验，旨在更好的日常管理和维护个人Github，提供更好更方便的驾车体验～～Σ(￣。￣ﾉ)ﾉ。项目涉及各种常用控件、网络、数据库、设计模式、主题切换、多语言、Redux等。在开发学习过程中，提供丰富的同款对比：
同款Weex版 （ https://github.com/CarGuo/GSYGithubAppWeex ）
同款ReactNative版 （ https://github.com/CarGuo/GSYGithubApp ）
同款Android Kotlin版本（ https://github.com/CarGuo/GSYGithubAppKotlin ）
基于Flutter开发，适配Android与IOS。目前初版，持续完善中。

``项目的目的是为方便个人日常维护和查阅Github，更好的沉浸于码友之间的互基，Github就是你的家。``

``项目同时适合Flutter的练手学习，覆盖了各种框架的使用，与原生的交互等。``

``随着项目的使用情况和反馈，将时不时根据更新并完善用户体验与功能优化吗，欢迎提出问题。``

- 推荐理由：超完整的Flutter项目，功能丰富，适合学习和日常使用。

- 截图：
![image](https://user-images.githubusercontent.com/33955669/51362610-5b326700-1b0f-11e9-9762-fdaa51fa963f.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目，项目的 README 排版和描述可以参照下面的审核标准修改后重新提交。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
