### ISSUE TITLE
项目推荐 Flutter-learning

### ISSUE THREAD

**Issue by w4ctech** [521xueweihan/HelloGitHub#426]
## 项目推荐
- 项目名称：Flutter-learning

- 项目地址：https://github.com/AweiLoveAndroid/Flutter-learning

- 项目后续更新计划：

- 项目描述：Flutter安装和配置，Flutter开发遇到的难题，Flutter示例代码和模板，Flutter项目实战，Dart语言学习示例代码。

- 推荐理由：这个库主要是一些Flutter学习资料，个人总结，项目示例代码。

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
