### ISSUE TITLE
自荐项目：基于three.js的3D场景编辑器

### ISSUE THREAD

**Issue by tengge1** [521xueweihan/HelloGitHub#428]
## 项目推荐
- 项目名称：ShadowEditor

- 项目地址：https://github.com/tengge1/ShadowEditor

- 项目后续更新计划： 物理引擎、地形编辑、更多材质特效、皮肤美化。

- 项目描述：基于three.js的在线3D场景编辑器，使用mongodb保存3D模型和场景数据。

- 推荐理由：简单易用，功能强大。

- 示例代码：无

- 截图：

![image](https://raw.githubusercontent.com/tengge1/ShadowEditor/master/images/scene20190111.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
