### ISSUE TITLE
自荐项目 - Python异步爬虫框架Ruia

### ISSUE THREAD

**Issue by howie6879** [521xueweihan/HelloGitHub#429]
## 项目推荐
- 项目名称：Ruia

- 项目地址：https://github.com/howie6879/ruia

- 项目后续更新计划：
    -  插件开发
    - 维护

- 项目描述：
Python轻量异步爬虫框架，An async web scraping micro-framework based on asyncio.

- 推荐理由：
    -  Easy: 上手简单，简明的语法
    -  Fast: 完全异步，速度快
    -  Extensible: 插件化，提供中间件以及插件支持比如JavaScript support

- 示例代码：
``` python
from ruia import TextField, Item, Spider

class HackerNewsItem(Item):
    target_item = TextField(css_select='tr.athing')
    title = TextField(css_select='a.storylink')


class HackerNewsSpider(Spider):
    start_urls = ['https://news.ycombinator.com/news?p=1']

    async def parse(self, response):
        async for item in HackerNewsItem.get_items(html=response.html):
            yield item

if __name__ == '__main__':
    HackerNewsSpider.start()
```
- 截图：
![image](https://user-images.githubusercontent.com/17047388/51813206-1917db00-22f0-11e9-978f-84dfb5b73cde.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 35 期](https://hellogithub.com/periodical/volume/35/#ruia)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
