### ISSUE TITLE
正则表达式生成器

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#430]
## 项目推荐
- 项目名称：verbalexpressions

- 项目地址：

https://github.com/VerbalExpressions/JSVerbalExpressions

- 项目后续更新计划：

- 项目描述：

通过代码自动生成对应的正则表达式，此项目为JS项目，另外也主持大多数主流编程语言。

- 推荐理由：

正则表达式在编程中不可谓不重要，但精通需要大量时间，通过此可以直接生成想要的表达式。同时，根据自身爱好，也可以学习相应的编程技巧。

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by SamenYan** [comment]
项目名称：Tools

项目地址：https://github.com/SamenYan/tools <https://github.com/howie6879/ruia>
项目后续更新计划：

前后端开发IED及常用高效插件使用
Java相关(coding、框架、环境部署等)
...
项目描述：【收集类项目】主要收集学习及工作开发中使用过的工具、类库、插件以及一些黑科技等等。目前收集的偏前端居多，后续update Java相关

推荐理由：web开发人员工具包, 记录便于查找使用。也适用于fork自我扩展。

示例代码：暂无

**Comment by SamenYan** [comment]
项目地址： https://github.com/SamenYan/tools <https://github.com/SamenYan/tools>


> 在 2019年1月28日，下午3:16，SamenYan <15895446649@163.com> 写道：
> 
> 项目名称：Tools
> 
> 项目地址：https://github.com/SamenYan/tools <https://github.com/howie6879/ruia>
> 项目后续更新计划：
> 
> 前后端开发IED及常用高效插件使用
> Java相关(coding、框架、环境部署等)
> ...
> 项目描述：【收集类项目】主要收集学习及工作开发中使用过的工具、类库、插件以及一些黑科技等等。目前收集的偏前端居多，后续update Java相关
> 
> 推荐理由：web开发人员工具包, 记录便于查找使用。也适用于fork自我扩展。
> 
> 示例代码：暂无
> 
>

**Comment by daixiang0** [comment]
@521xueweihan hi，这是一个repo合集，具体是不符合哪条标准呢？

**Comment by 521xueweihan** [comment]
@daixiang0 HG 只推荐 GitHub 上的项目，需要给出项目地址，不能只是个 GitHub page。

**Comment by daixiang0** [comment]
更新 https://github.com/VerbalExpressions/JSVerbalExpressions
