### ISSUE TITLE
自荐项目: 开源php加密扩展

### ISSUE THREAD

**Issue by del-xiong** [521xueweihan/HelloGitHub#431]
## 项目推荐
- 项目名称：php screw plus

- 项目地址：https://github.com/del-xiong/screw-plus

- 项目后续更新计划：考虑增加动态解密模块，提高安全性能

- 项目描述：一个简单易用的php加密运行模块，也可用来防范web漏洞

- 推荐理由：无需额外成本保护项目代码、多人协作保护核心代码不外泄

- 示例代码：none

- 截图：none

**Comment by 521xueweihan** [comment]
@del-xiong 你好，我发现该项目很长时间没有更新了。欢迎更新、修复 issues 后重新提交该项目。

所以，**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
