### ISSUE TITLE
neovim -  Vim-fork 专注于可扩展性和可用性 

### ISSUE THREAD

**Issue by ChungZH** [521xueweihan/HelloGitHub#432]
## 项目推荐
- 项目名称：
neovim
- 项目地址：
https://github.com/neovim/neovim
- 项目后续更新计划：

- 项目描述：
这是一个致力于改善 Vim 的可扩展性和可用性的编辑器。
- 推荐理由：
功能强大、开发活跃。
- 示例代码：

- 截图：
![](https://neovim.io/images/logo@2x.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 35 期](https://hellogithub.com/periodical/volume/35/#neovim)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
