### ISSUE TITLE
fx - 命令行工具和终端 JSON 查看器。

### ISSUE THREAD

**Issue by ChungZH** [521xueweihan/HelloGitHub#433]
## 项目推荐
- 项目名称：
fx
- 项目地址：
https://github.com/antonmedv/fx
- 项目后续更新计划：

- 项目描述：
命令行工具和终端 JSON 查看器。
- 推荐理由：
很酷、方便。
- 示例代码：

- 截图：
![](https://medv.io/assets/fx.gif)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
