### ISSUE TITLE
你不知道的JS

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#434]
## 项目推荐
- 项目名称：你不知道的JS

- 项目地址：https://github.com/getify/You-Dont-Know-JS

- 项目后续更新计划：

- 项目描述：

这是一系列深入探讨JavaScript语言核心机制的书籍。 该系列的第一版现已完成。

- 推荐理由：

如果想要深入学习JS，是不可多得的专业用书

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 35 期](https://hellogithub.com/periodical/volume/35/#You-Dont-Know-JS)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
