### ISSUE TITLE
自荐项目：Gitter for GitHub - 可能是目前颜值最高的GitHub小程序客户端

### ISSUE THREAD

**Issue by huangjianke** [521xueweihan/HelloGitHub#435]
## 项目推荐
- 项目名称：Gitter

- 项目地址：https://github.com/huangjianke/Gitter

- 项目后续更新计划：会持续更新维护

- 项目描述：GitHub小程序客户端

- 推荐理由：颜值高，实用性，开源

- 示例代码：可查看仓库地址 https://github.com/huangjianke/Gitter

- 截图：
![image](https://user-images.githubusercontent.com/8692455/53217043-95080780-3691-11e9-89dd-cd5d350d3eb4.png)
![image](https://user-images.githubusercontent.com/8692455/51885067-f0ade080-23c4-11e9-9d95-41bbc54af435.png)
![image](https://user-images.githubusercontent.com/8692455/51885072-f4d9fe00-23c4-11e9-903e-4c989196ab4c.png)
![image](https://user-images.githubusercontent.com/8692455/51885075-f99eb200-23c4-11e9-8da0-cc8ae791bac9.png)
![image](https://user-images.githubusercontent.com/8692455/51885080-fefbfc80-23c4-11e9-8f68-65fb94a7c00d.png)

**Comment by EryouHao** [comment]
很赞！

**Comment by huangjianke** [comment]
> 很赞！

感谢支持 @EryouHao

**Comment by ChungZH** [comment]
:joy: 以后可以考虑换个名字？Gitter 是一个协作平台来的 [gitter](https://gitter.im/)

**Comment by aen516954023** [comment]
真的很不错   我也要尝试着写一个这样的小程序

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 35 期](https://hellogithub.com/periodical/volume/35/#Gitter)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by huangjianke** [comment]
@521xueweihan 感谢支持
