### ISSUE TITLE
动手学深度学习

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#436]
## 项目推荐
- 项目名称： 动手学深度学习

- 项目地址：https://github.com/d2l-ai/d2l-zh

- 项目后续更新计划：

- 项目描述：
《动手学深度学习》，英文版即伯克利深度学习（STAT 157，2019春）教材。面向中文读者、能运行、可讨论。 

- 推荐理由：

伯克利深度学习（STAT 157，2019春）教材中文翻译版，面向中文读者的能运行、可讨论的深度学习教科书。适合初学者入门。

**Comment by xibinyue** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 35 期](https://hellogithub.com/periodical/volume/35/#d2l-zh)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
