### ISSUE TITLE
Project Based Learning

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#437]
## 项目推荐
- 项目名称：Project Based Learning

- 项目地址：
https://github.com/tuvtran/project-based-learning
- 项目后续更新计划：

- 项目描述：

通过具体的项目学习编程

- 推荐理由：

支持多种编程语言，通过具体项目，既可以从零学习编程，也可以快速学习新的编程语言。

**Comment by 521xueweihan** [comment]
基于月刊的篇幅考虑，将于 37 收录您推荐的项目。
