### ISSUE TITLE
自荐项目：tools

### ISSUE THREAD

**Issue by SamenYan** [521xueweihan/HelloGitHub#438]
## 项目推荐
- 项目名称：tools

- 项目地址：https://github.com/SamenYan/tools

- 项目后续更新计划：
前后端开发IED及常用高效插件使用
Java相关(coding、框架、环境部署等)
...

- 项目描述：【收集类项目】主要收集学习及工作开发中使用过的工具、类库、插件以及一些黑科技等等。目前收集的偏前端居多，后续update Java相关

- 推荐理由：web开发人员工具包, 记录便于查找使用。也适用于fork自我扩展。

- 示例代码：暂无

- 截图：暂无

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
