### ISSUE TITLE
开源项目：python 代码调试利器

### ISSUE THREAD

**Issue by dantangfan** [521xueweihan/HelloGitHub#439]
## 项目推荐
- 项目名称：pylane

- 项目地址：https://github.com/NtesEyes/pylane

- 项目后续更新计划：网易运维团队维护，持续更新

- 项目描述：Pylane 是一个基于gdb的python进程注入和调试工具, 通过gdb trace python进程，然后在该进程的python vm中动态地注入一段python代码， 从而对一个运行中的python进程执行一段任意的逻辑。

- 推荐理由：这是团队第一个开源项目，是从我们团队自研的python代码调试工具中剥离出来的一部分核心代码，该工具解决了不少线上问题，这里也有一篇我们的代码调试经验的总结性文章，希望对其他同学也有用 https://mp.weixin.qq.com/s/Mlhrp2E390EMD0ZfSaNFKw

- 示例代码：pylane shell <PID> 即可进入进程调试

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 36 期](https://hellogithub.com/periodical/volume/36/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
