### ISSUE TITLE
window下gif录制

### ISSUE THREAD

**Issue by jp1017** [521xueweihan/HelloGitHub#44]
## 项目推荐
- 项目：[ScreenToGif](https://github.com/NickeManarin/ScreenToGif)

- 项目语言：C#

- 项目描述：window下gif和video录制

- 推荐理由：写博客录制gif必备工具

- 截图：
<img src="https://github.com/NickeManarin/ScreenToGif-Website/raw/master/screenshots/Editor.gif" width="640"/>

**Comment by 521xueweihan** [comment]
已推荐过：https://github.com/521xueweihan/HelloGitHub/blob/master/content/12/HelloGitHub12.md#c-项目-1
