### ISSUE TITLE
gitsome - 实用又很酷的 GitHub 命令行工具

### ISSUE THREAD

**Issue by ChungZH** [521xueweihan/HelloGitHub#440]
## 项目推荐
- 项目名称：
gitsome
- 项目地址：
https://github.com/donnemartin/gitsome
- 项目后续更新计划：

- 项目描述：
GitHub 命令行工具。
- 推荐理由：
实用，方便。
- 示例代码：

- 截图：
![](http://i.imgur.com/0SXZ90y.gif)

**Comment by 521xueweihan** [comment]
@ChungZH 已推荐过类似工具，所以暂不能收录该项目
