### ISSUE TITLE
自荐项目：Bootstrap Table

### ISSUE THREAD

**Issue by wenzhixin** [521xueweihan/HelloGitHub#441]
## 项目推荐
- 项目名称：Bootstrap Table

- 项目地址：https://github.com/wenzhixin/bootstrap-table 

- 例子项目: https://github.com/wenzhixin/bootstrap-table-examples

- 项目后续更新计划：不断新增新功能和修复已有的bug（ https://bootstrap-table.com/news ）

- 项目描述：基于 Bootstrap 的 jQuery 表格插件，通过简单的设置，就可以拥有强大的单选、多选、排序、分页，以及编辑、导出、过滤（扩展）等等的功能。

- 推荐理由：基于 Bootstrap，完全支持 bootstrap v2，v3 和 v4。简单易用，文档：https://bootstrap-table.com 和例子 https://examples.bootstrap-table.com 齐全（v3 文档和例子：https://bootstrap-table-docs3.wenzhixin.net.cn/home ）。

- 示例代码：https://bootstrap-table.com/docs/getting-started/usage

```js
<table data-toggle="table">
  <thead>
    <tr>
      <th>Item ID</th>
      <th>Item Name</th>
      <th>Item Price</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>Item 1</td>
      <td>$1</td>
    </tr>
    <tr>
      <td>2</td>
      <td>Item 2</td>
      <td>$2</td>
    </tr>
  </tbody>
</table>
```

- 截图：

![image](https://user-images.githubusercontent.com/2117018/52416622-f9b95300-2b24-11e9-8532-bc762fb5fcee.png)

**Comment by wenzhixin** [comment]
最新版本增加了多个流行 CSS 框架的支持：Bootstrap, Semantic UI, Bulma, Material Design, Foundation) https://bootstrap-table.com/themes/

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 36 期](https://hellogithub.com/periodical/volume/36/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
