### ISSUE TITLE
git history

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#442]
## 项目推荐
- 项目名称：Git history

- 项目地址：https://github.com/pomber/git-history

- 项目后续更新计划：

- 项目描述：

快速浏览任何GitHub文件的历史记录

- 推荐理由：

生动形象看到任何github上文件的变化。
https://githistory.xyz/

- 截图：
[运行截图](https://user-images.githubusercontent.com/1911623/52460615-f3899d80-2b49-11e9-8c21-06af4097a527.gif)

**Comment by daixiang0** [comment]
@521xueweihan node.js架构

**Comment by 521xueweihan** [comment]
@daixiang0 现在实例网站无法打开

**Comment by daixiang0** [comment]
这是仓库的[问题](https://github.com/pomber/git-history/issues/110)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
