### ISSUE TITLE
learn-go-with-tests

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#443]
## 项目推荐
- 项目名称：通过测试驱动开发学习Go

- 项目地址：

https://github.com/quii/learn-go-with-tests

- 项目后续更新计划：

- 项目描述：

通过测试驱动开发学习Go

- 推荐理由：

Go是现在十分热门的语言，根据实例可以快速入门

**Comment by FrontMage** [comment]
下期36期收录

**Comment by daixiang0** [comment]
@FrontMage 似乎可以添加标签
