### ISSUE TITLE
基于react实现web桌面操作系统——react-desktop

### ISSUE THREAD

**Issue by jiajun00** [521xueweihan/HelloGitHub#444]
## 项目推荐
- 项目名称：
react-desktops
- 项目地址：
https://github.com/jiajun00/react-desktops
- 项目后续更新计划：
2019.3月份完善window系统中开始菜单功能
2019.6月份添加桌面背景图设置功能
2019.8月份完成消息推送功能
- 项目描述：
react-desktops是桌面操作系统前端UI，用了丰富的mac和win10桌面元素，包括桌面图标、窗口化子页面管理、开始菜单等组件，兼容主流现代浏览器。
- 推荐理由：
适合快速开发后台管理系统的前端界面、整合企业诸多应用、通过B/S架构集成系统、可作为企业级应用管理平台。
- 示例代码：

- 截图：
![mac-home](https://user-images.githubusercontent.com/14782540/52690311-360f0800-2f98-11e9-97f7-7f1c4ee2948f.png)
![win-home](https://user-images.githubusercontent.com/14782540/52690322-3c04e900-2f98-11e9-85e0-bd46f7e9c513.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
