### ISSUE TITLE
OI-Wiki  🌟 Wiki for OI / ICPC. （某大型游戏线上攻略，内含炫酷算术魔法）

### ISSUE THREAD

**Issue by ChungZH** [521xueweihan/HelloGitHub#445]
## 项目推荐
- 项目名称：
OI-Wiki
- 项目地址：
https://github.com/24OI/OI-WIKI
- 项目后续更新计划：
https://github.com/24OI/OI-wiki/issues/936
- 项目描述：
 🌟 Wiki for OI / ICPC. （某大型游戏线上攻略，内含炫酷算术魔法）
- 推荐理由：
内容详细、易懂。
- 示例代码：

- 截图：

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 35 期](https://hellogithub.com/periodical/volume/35/#OI-WIKI)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
