### ISSUE TITLE
CS-Notes

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#446]
## 项目推荐
- 项目名称：技术面试必备基础知识

- 项目地址：https://github.com/CyC2018/CS-Notes

- 项目后续更新计划：

- 项目描述：技术面试必备基础知识

- 推荐理由：

技术面试必备基础知识，省去了查找资料的时间，对于无需面试的也是一个很好的学习资料。

**Comment by 521xueweihan** [comment]
基于月刊的篇幅考虑，将于 37 收录您推荐的项目。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 37 期](https://hellogithub.com/periodical/volume/37/#CS-Notes)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
