### ISSUE TITLE
Motrix

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#447]
## 项目推荐
- 项目名称：Motrix

- 项目地址：https://github.com/agalwood/Motrix

- 项目描述：

Motirx 是一款全能的下载工具，支持下载 HTTP、FTP、BT、磁力链、百度网盘等资源。它的界面简洁易用，官[网](https://motrix.app/)

- 推荐理由：

Vue + VueX + Element的技术架构，适合作为桌面应用学习的的素材。对于下载想要有所了解的童鞋也能从中学到不少知识。

- 截图：
[运行截图](https://camo.githubusercontent.com/5e79b26360931e8096dd9d8054f87550b0e24a99/68747470733a2f2f63646e2e6e6c61726b2e636f6d2f79757175652f302f323031392f706e672f3132393134372f313534383235313038383137372d32313736326134312d333937352d343431372d626635342d3666363461656230663230642e706e67)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 35 期](https://hellogithub.com/periodical/volume/35/#Motrix)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
