### ISSUE TITLE
开源项目：前端工程师所应该具备的软技能以及面试技巧图文

### ISSUE THREAD

**Issue by bigbigDreamer** [521xueweihan/HelloGitHub#448]
## 项目推荐
- 项目名称：CommonProjectConfigurationFiles

- 项目地址：https://github.com/bigbigDreamer/CommonProjectConfigurationFiles

- 项目后续更新计划：持续更新前端工程师所具备的软技能以及前端面试所应该掌握的要点知识。

- 项目描述：这个仓库主要讲解了前端项目常用的一些文件配置以及使用教学，包括一个标准前端工程师的必备软技能。

- 推荐理由：相信我的项目应该能帮助更多的一些前端入门一段时间的小白或者是即将走进职场，进入面试的同胞们。

- 示例代码：单纯讲解经验，没有主观的实例代码。

- 截图：
[点击查看](https://github.com/bigbigDreamer/CommonProjectConfigurationFiles/blob/master/configExampleImgs/demo.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您好，经过我们的再次审核该项目暂时不能收录到月刊中。建议：
1. 丰富项目的内容
2. 参考修改项目 #271
