### ISSUE TITLE
开源编程图书合集

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#451]
## 项目推荐
- 项目名称：free-programming-books

- 类别：书籍

- 项目地址：https://github.com/EbookFoundation/free-programming-books

- 项目后续更新计划：

- 项目描述：收藏多类开源的编程相关的图书

- 推荐理由：内容庞大的图书合集，减少寻找时间。支持多种语言。

**Comment by daixiang0** [comment]
@521xueweihan 更新类别

**Comment by 521xueweihan** [comment]
全是英文的图书资源，对新手不友好。暂不推荐该项目。
