### ISSUE TITLE
开源P2P搜索引擎

### ISSUE THREAD

**Issue by tangdou1** [521xueweihan/HelloGitHub#452]
## 项目推荐
- 项目名称：Yacy

- 项目地址：https://github.com/yacy/yacy_search_server

- 项目后续更新计划：

- 项目描述：YaCy是一款采用了新的搜索方法的搜索引擎软件。 它不需要中央服务器。相反，它的搜索结果 来自独立的分布式网络。

- 推荐理由：https://github.com/yacy/yacy_search_server/wiki/%E4%B8%AD%E6%96%87%E4%BB%8B%E7%BB%8D

- 示例代码：JAVA开发

- 截图：

**Comment by CasualJi** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 36 期](https://hellogithub.com/periodical/volume/36/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
