### ISSUE TITLE
开源项目推荐 Skoruba.IdentityServer4.Admin

### ISSUE THREAD

**Issue by Seaear** [521xueweihan/HelloGitHub#454]
## 项目推荐
- 项目名称：Skoruba.IdentityServer4.Admin

- 项目地址：https://github.com/skoruba/IdentityServer4.Admin

- 项目后续更新计划：
> 1.1.0:
>    Add audit logs to track changes
>    Create a project template using dotnet CLI - dotnet new template
>    Second template: The administration of the IdentityServer4 (without Asp.Net Core Identity)
>    User registration / Password reset
>    Account linking
>    Manage profile
> 2.0.0:
>    Add API:
>    IdentityServer4
>    Asp.Net Core Identity
>    Add swagger support

- 项目描述：Skoruba.IdentityServer4.Admin 是一个 IdentityServer4 与 Asp.Net Core Identity 管理器

- 推荐理由：IdentityServer4 官方的管理器是收费的，Skoruba.IdentityServer4.Admin 很好的替代了官方管理器，可以方便的管理使用 IdentityServer4 所搭建的认证服务器

- 示例代码：C# 开发

- 截图：
![image](https://user-images.githubusercontent.com/1687087/53141083-c0272400-35c9-11e9-9466-b6f4573368a4.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 35 期](https://hellogithub.com/periodical/volume/35/#IdentityServer4.Admin)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
