### ISSUE TITLE
创建属于自己github门户

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#455]
## 项目推荐
- 项目名称：personal-website

- 类别：Ruby

- 项目地址：https://github.com/github/personal-website.git

- 项目后续更新计划：

- 项目描述：

GitHub官方提供的主页模板

- 推荐理由：

GitHub有一个神奇的网站，username.github.io，你只要稍加设置，就可以有一个专属的GitHub门户，快来试试吧。(username是GitHub账号的username)

- 示例代码：
[我的门户](https://daixiang0.github.io/)

**Comment by daixiang0** [comment]
@521xueweihan 应该是RUBY项目，使用的是jekyll框架

**Comment by daixiang0** [comment]
@521xueweihan 更新类别，ruby项目，使用的是jekyll框架

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
