### ISSUE TITLE
自荐项目： Xs编程语言

### ISSUE THREAD

**Issue by kulics** [521xueweihan/HelloGitHub#457]
## 项目推荐
- 项目名称：
Xs 编程语言
- 项目地址：
https://github.com/kulics/xs
- 项目后续更新计划：
探索编译实现，翻译到目标语言或者自执行。
- 项目描述：
Xs 是一个专注于简单的开源跨平台编程语言。  
这门语言的设计目标是改进阅读与编写效率，降低语法负担，让使用者能够把真正的注意力放在解决问题上。  
因此Xs舍弃繁杂的特性，保留最通用的功能，只需极少的语法，就能优雅地表达逻辑。 
- 推荐理由：
与众不同的语法思维。
- 示例代码：
```
# export namespace
\HelloWorld {
    System # import namespace
}
# package
program -> {
    # main function
    Main() -> () {
        # list
        greetings := {"Hello", "Hola", "Bonjour",
                    "Ciao", "こんにちは", "안녕하세요",
                    "Cześć", "Olá", "Здравствуйте",
                    "Chào bạn", "您好"}
        # for-each  
        @ item <- greetings {
            # switch
            ? item -> [ 0 <= 8 ] {
                prt(item) # call function
            } _ {
                # lambda
                prt( greetings.filter( {it -> it.len> 4} ) )
                <- @
            }
        }
    }
}
```

**Comment by 521xueweihan** [comment]
@kulics 请问该项目分类到 C# 是否合适？

**Comment by kulics** [comment]
@521xueweihan 可以的，目前也的确是个C#项目呢

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 36 期](https://hellogithub.com/periodical/volume/36/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
