### ISSUE TITLE
推荐：plotly dash

### ISSUE THREAD

**Issue by byronz** [521xueweihan/HelloGitHub#458]
## 项目推荐
- 项目名称：
dash
- 项目地址：
https://github.com/plotly/dash

- 项目后续更新计划：
dash R, dash bio, 和dash julia

- 项目描述：
dash是一款只用几百行Python就可以轻易实现数据分析可视化(data analytics visualization)的利器

- 推荐理由：
1. 8k github star, 120 issues
2. 是目前Python社区的数据可视化的主要两个工具之一，另一个是bokeh
3. dash的实现基于plotly.js (d3)，Reactjs和flask。 所有web页面的构件都是基于React JS Component，开源作者可以很容易基于dash提供的build工具来拓展已有的React component进入dash的生态圈。
4. 团队有20%的华人

- 示例代码：

live demo
https://dash-drug-explorer.plot.ly/
https://dash-bio.plotly.host/dash-speck/
https://dash-hello-world.herokuapp.com/
https://dash-gallery.plotly.host/dash-oil-and-gas/

```
import dash
from dash.dependencies import Input, Output
import dash_core_components as dcc
import dash_html_components as html

import flask
import pandas as pd
import time
import os

server = flask.Flask('app')
server.secret_key = os.environ.get('secret_key', 'secret')

df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/hello-world-stock.csv')

app = dash.Dash('app', server=server)

app.scripts.config.serve_locally = False
dcc._js_dist[0]['external_url'] = 'https://cdn.plot.ly/plotly-basic-latest.min.js'

app.layout = html.Div([
    html.H1('Stock Tickers'),
    dcc.Dropdown(
        id='my-dropdown',
        options=[
            {'label': 'Tesla', 'value': 'TSLA'},
            {'label': 'Apple', 'value': 'AAPL'},
            {'label': 'Coke', 'value': 'COKE'}
        ],
        value='TSLA'
    ),
    dcc.Graph(id='my-graph')
], className="container")

@app.callback(Output('my-graph', 'figure'),
              [Input('my-dropdown', 'value')])

def update_graph(selected_dropdown_value):
    dff = df[df['Stock'] == selected_dropdown_value]
    return {
        'data': [{
            'x': dff.Date,
            'y': dff.Close,
            'line': {
                'width': 3,
                'shape': 'spline'
            }
        }],
        'layout': {
            'margin': {
                'l': 30,
                'r': 20,
                'b': 30,
                't': 20
            }
        }
    }

if __name__ == '__main__':
    app.run_server()
```

- 截图：

![image](https://user-images.githubusercontent.com/1394467/53292920-a556da00-3798-11e9-8b5d-7d153010adcf.png)
![demo](https://cdn-images-1.medium.com/max/2600/1*6K8V_xTLvm9kt_-g4WFwQg.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 36 期](https://hellogithub.com/periodical/volume/36/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
