### ISSUE TITLE
gita 管理多个git repo的命令行工具

### ISSUE THREAD

**Issue by nosarthur** [521xueweihan/HelloGitHub#459]
## 项目推荐
- 项目名称：gita

- 项目地址：https://github.com/nosarthur/gita

- 项目描述：
  - 同时显示多个repo的状态信息， 包括本地branch与远程branch的关系，编辑状态等
  - 在任何目录下代理执行git指令

- 截图：

![gita screenshot](https://github.com/nosarthur/gita/raw/master/screenshot.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by nosarthur** [comment]
谢谢

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 36 期](https://hellogithub.com/periodical/volume/36/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
