### ISSUE TITLE
python脚本-在网易云音乐与qq音乐之间同步歌单

### ISSUE THREAD

**Issue by Denon** [521xueweihan/HelloGitHub#46]
## 项目推荐
- 项目：[syncPlaylist](https://github.com/Denon/syncPlaylist)

- 项目语言：python

- 项目描述：在网易云音乐与qq音乐之间同步歌单

- 推荐理由：python爬虫脚本, 代码比较简单。此项目使用到requests + beautifulsoup 以及 selenium+phantomjs 两种技术。

**Comment by 521xueweihan** [comment]
@Denon 我个人觉得使用这个脚本配置、安装有些复杂。

是否能够设计成，直接运行脚本通过交互式命令就可以完成同步？

安装可以只通过一个 `pip install -r requirements.txt` 命令完成？

纯属个人建议，欢迎讨论。

**Comment by Denon** [comment]
@521xueweihan 这个可以有。我准备把那几个驱动都下载进来。这样就可以做到一键安装了， 配置也省略了。

**Comment by jp1017** [comment]
@Denon 可否添加酷狗音乐同步? :+1:

**Comment by Denon** [comment]
@jp1017 可以有，你可以去项目里面提个issue好了。酷狗音乐印象中可以直接导入文件的。
