### ISSUE TITLE
中国科学技术大学计算机学院课程资源

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#460]
## 项目推荐
- 项目名称：中国科学技术大学计算机学院课程资源

- 项目地址：

https://github.com/mbinary/USTC-CS-Courses-Resource

- 项目后续更新计划：

- 项目描述：

收集 中国科学技术大学课程资源的（主要是计算机学院的,也有其他课程,公选课,自由选修等）的 repo, 包括课程电子版 书籍，参考书，slides(ppt), 考试试卷，学习心得，某些书的答案

- 推荐理由：

入门计算机课程的不二之选。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 35 期](https://hellogithub.com/periodical/volume/35/#USTC-CS-Courses-Resource)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by shuye02** [comment]
这个repo已经被删除了……

**Comment by 521xueweihan** [comment]
@shuye02 感谢反馈。该项目移动了到了组织下，新的地址：https://github.com/USTC-Resource/USTC-Course

**Comment by shuye02** [comment]
原来如此，谢谢XD
