### ISSUE TITLE
使用深度学习对视频和图片换脸工具

### ISSUE THREAD

**Issue by nivance** [521xueweihan/HelloGitHub#462]
## 项目推荐
- 项目名称：faceswap

- 项目地址：https://github.com/deepfakes/faceswap

- 项目后续更新计划：无

- 项目描述：通过这个工具可以对图片和视频进行换脸

- 推荐理由：可以很方便地处理图片和视频，搞些有意思的事情

- 示例代码：无

- 截图：图上传失败，看项目首页吧

**Comment by xibinyue** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 36 期](https://hellogithub.com/periodical/volume/36/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
