### ISSUE TITLE
自荐项目：PasteMe

### ISSUE THREAD

**Issue by LucienShui** [521xueweihan/HelloGitHub#463]
## 项目推荐
- 项目名称：PasteMe

- 项目地址：https://github.com/LucienShui/PasteMe

- 项目后续更新计划：

重构代码，优化逻辑，为 API 增加上传的功能，添加一些其它的 feature。

- 项目描述：

Ubuntu Pastebin 的本土化版，相较前者增加了加密、阅后即焚、代码一键复制、二维码分享等功能，并提供相应的 API，更美观、更便捷、（访问速度）更快，并可以在页面内直接与站长交流。

- 推荐理由：自己写的，想扩大一下影响。

- 示例代码：

对于现有 API 的调用：

```bash
api.pasteme.cn?token=<key>,<passwd>
```

其中 `key` 为索引，`passwd` 为索引的密码（如果有），中间以英文逗号分隔。

比如：

```bash
curl 'api.pasteme.cn?token=100'
curl 'api.pasteme.cn?token=101,123'
```

- 截图：

![homePage](https://github.com/LucienShui/gitcdn/blob/master/pasteme_home.png?raw=true)

![chat](https://github.com/LucienShui/gitcdn/blob/master/pasteme_chat.png?raw=true)

![effectiveOnce](https://github.com/LucienShui/gitcdn/blob/master/pasteme_read_once.png?raw=true)

![adminPage](https://github.com/LucienShui/gitcdn/blob/master/pasteme_admin.png?raw=true)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 36 期](https://hellogithub.com/periodical/volume/36/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by LucienShui** [comment]
非常感谢你们所提供的平台，辛苦啦～我会推荐给小伙伴并继续支持你们的～
