### ISSUE TITLE
推荐java 项目  generator-jhipster 

### ISSUE THREAD

**Issue by LYXmoonstars** [521xueweihan/HelloGitHub#464]
## 项目推荐
- 项目名称：generator-jhipster

- 项目地址：https://github.com/jhipster/generator-jhipster

- 项目描述：
用于在几秒钟内创建Spring Boot+Angular/React项目的开源应用程序生成器！

- 推荐理由：
JHipster可以自动化生成一个完整和现代的Web应用程序或微服务架构。

基于Spring Boot框架的服务端，具备高性能和高可用的Java技术栈；

基于Angular，React和Bootstrap的时尚，现代，移动优先的前端；

基于JHipster Registry，Netflix OSS，ELK堆栈和Docker的强大的微服务架构；

使用Yeoman，Webpack和Maven/Gradle构建应用程序的强大工作流程。

参考官网：https://www.jhipster.tech/

**Comment by liyuexing** [comment]
前端技术栈

Angular 5和React

Bootstrap响应式网页设计

HTML5 

国际化

CSS的Sass

WebSocket

使用Yarn安装新的JavaScript库

使用Webpack构建，优化和实时加载

使用Jest和Protractor进行测试

支持Thymeleaf模板引擎 

后端技术栈

Spring Boot 

Maven和Gradle

Spring Security 

Spring MVC REST + Jackson

Spring Websocket

Spring Data JPA 

Liquibase 

Elasticsearch

MongoDB和Couchbase

Cassandra

Kafka

微服务技术栈

使用Netflix Zuul或Traefik作为HTTP路由

使用Netflix Eureka或HashiCorp Consul作为服务发现

使用Spring Cloud Config作为统一配置

CI/CD支持

Jenkins

Travis CI

GitLab CI

Circle CI

部署环境支持

使用ELK堆栈进行应用指标监控

使用ehcache，hazelcast或Infinispan进行缓存

优化的静态资源（gzip过滤器，HTTP缓存头）

使用Logback进行日志管理，可在运行时进行配置

使用HikariCP连接池以获得最佳性能

构建标准WAR文件或可执行JAR文件

完整的Docker和Docker-Compse支持

支持所有主要云提供商：AWS，Cloud Foundry，Heroku，Kubernetes，OpenShift，Docker等
引用https://cloud.tencent.com/developer/article/1360193  https://www.jhipster.tech/tech-stack/

**Comment by CasualJi** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 38 期](https://hellogithub.com/periodical/volume/38/#generator-jhipster)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
