### ISSUE TITLE
ProMarkdown - 一款专业级Markdown编辑器React组件[开发者自荐]

### ISSUE THREAD

**Issue by reactma** [521xueweihan/HelloGitHub#467]
## 项目推荐
- 项目地址：

https://github.com/reactma/promarkdown

- 类别：请从中选择（C、C#、C++、CSS、Go、Java、JS、Kotlin、Objective-C、PHP、Python、Ruby、Swift、其它、书籍、机器学习）

其他 - Markdown / Javascript

- 项目后续更新计划：

增加键盘快捷方式

- 项目描述：
  - 必写：这是个什么项目、能用来干什么、有什么特点或解决了什么痛点
  - 可选：适用于什么场景、能够让初学者学到什么
  - 描述长度（不包含示例代码）: 10 - 256 个字符

ProMarkdown是一款为专业程序员和文档写作者开发专业级的Markdown编辑器，基于CodeMirror和React。

支持如下更加强大的Markdown编辑功能：

    Frontmatters, 支持YAML / TOML /JSON
    键盘布局, Vim / Sublime / Emacs, 和默认
    行编号
    块折叠
    预览 / 全屏 / 编辑和实时预览
    搜索与替换
    国际化，已内置zh-CN。 开发者可以针对不同语言提供菜单提示/ 搜索/替换的对应语言。
    工具栏/菜单: 提供默认的菜单，支持常见的Markdown格式
    可扩展 - 对开发者开放CodeMirror，允许提供自己的菜单，自己的预览组件和底层CodeMirror事件处理器。

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？

支持专业编辑模式和Frontmatter

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

![Default Mode](https://raw.githubusercontent.com/reactma/promarkdown/master/demo/demo-default.png)

![Bare editor](https://raw.githubusercontent.com/reactma/promarkdown/master/demo/demo-bare.png)

![Live edit and preview](https://raw.githubusercontent.com/reactma/promarkdown/master/demo/demo-splitpane.png)

### 编辑完推荐项目的信息，**请删除**下述提示信息
1. [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271)

2. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

3. HelloGitHub 网站：https://hellogithub.com

再次感谢您对《HelloGitHub》项目的支持！

**Comment by 521xueweihan** [comment]
请删除提示性文字，重新提交 issues
