### ISSUE TITLE
ProMarkdown - 一款专业级Markdown编辑器React组件[开发者自荐]

### ISSUE THREAD

**Issue by reactma** [521xueweihan/HelloGitHub#468]
## 项目推荐
- 项目地址：

https://github.com/reactma/promarkdown

- 类别：其他 - Markdown / Javascript

- 项目后续更新计划：
  - 增加键盘快捷方式

- 项目描述：ProMarkdown是一款为专业程序员和文档写作者开发专业级的Markdown编辑器React组件，基于CodeMirror。您可以用它为基础开发自己的Web Markdown编辑器
  
支持如下更加强大的Markdown编辑功能：

- Frontmatters, 支持YAML / TOML /JSON
- 键盘布局, Vim / Sublime / Emacs, 和默认
- 行编号
- 块折叠
- 预览 / 全屏 / 编辑和实时预览
- 搜索与替换
- 国际化，已内置zh-CN。 开发者可以针对不同语言提供菜单提示/ 搜索/替换的对应语言
- 工具栏/菜单: 提供默认的菜单，支持常见的Markdown格式
- 可扩展 - 对开发者开放CodeMirror，允许提供自己的菜单，自己的预览组件和底层CodeMirror事件处理器

- 推荐理由：支持专业编辑模式和Frontmatter

**默认配置**
![Default Mode](https://raw.githubusercontent.com/reactma/promarkdown/master/demo/demo-default.png)

**裸编辑器，无任何配置**
![Bare editor](https://raw.githubusercontent.com/reactma/promarkdown/master/demo/demo-bare.png)

**编辑和实时预览**
![Live edit and preview](https://raw.githubusercontent.com/reactma/promarkdown/master/demo/demo-splitpane.png)

**搜索/替换**
![Search and replace](https://raw.githubusercontent.com/reactma/promarkdown/master/demo/demo-search-replace.png)

**自定义菜单**
![Custom Menu](https://github.com/reactma/promarkdown/blob/master/demo/demo-custom-menu.png)

**Comment by 521xueweihan** [comment]
@reactma 您好，已推荐过类似的项目，该项目暂不能收录。

我刚才修改了下您的提交信息，提示语包含描述、类别等提示。欢迎后续分享更多有趣的项目。
