### ISSUE TITLE
大神整理的十几年“渗透攻击”经验

### ISSUE THREAD

**Issue by nivance** [521xueweihan/HelloGitHub#469]
## 项目推荐
- 项目地址：https://github.com/Micropoor/Micro8

- 类别：书籍

- 项目后续更新计划：近期一直在更新

- 项目描述：
  - 大神整理的十几年“渗透攻击”经验
  - 适用于初中级安全从业人员，乙方安全测试，甲方安全自检，网络安全爱好者等，企业安全防护与提高
  - 已经更新了100多节课

- 推荐理由：大神十几年“渗透攻击”经验，免费的安全课程，直接照着学就可以了

- 示例代码：无

- 截图：
![360 17891227111739](https://user-images.githubusercontent.com/3291404/53538349-47cfde00-3b48-11e9-8905-16535fe769dd.jpg)

**Comment by 521xueweihan** [comment]
@nivance 您好，该项目已经推荐过：https://hellogithub.com/periodical/volume/35/#Micro8
