### ISSUE TITLE
LovingHome-Real-Estate-Platform

### ISSUE THREAD

**Issue by 29DCH** [521xueweihan/HelloGitHub#470]
## 项目推荐
- 项目地址：https://github.com/29DCH/LovingHome-Real-Estate-Platform

- 类别：java

- 项目后续更新计划：
加springcloud微服务
- 项目描述：
JavaWeb项目

- 推荐理由：数据可视化

- 示例代码：（可选）长度：1-20 行
 public List<House> getHotHouse(Integer size) {
        House query = new House();
        List<Long> list = getHot();
        list = list.subList(0, Math.min(list.size(), size));
        if (list.isEmpty()) {
            return Lists.newArrayList();
        }
        query.setIds(list);
        final List<Long> order = list;
        List<House> houses = houseService.queryAndSetImg(query, PageParams.build(size, 1));
        Ordering<House> houseSort = Ordering.natural().onResultOf(hs -> {
            return order.indexOf(hs.getId());
        });
        return houseSort.sortedCopy(houses);
    }

- 截图：（可选）gif/png/jpg
![image](https://user-images.githubusercontent.com/28681519/53552534-7795da80-3b76-11e9-8896-b4d1e0c41744.png)
![image](https://user-images.githubusercontent.com/28681519/53552577-95fbd600-3b76-11e9-8240-7609a6374953.png)
![image](https://user-images.githubusercontent.com/28681519/53552604-a449f200-3b76-11e9-87dd-fe997d3b87ff.png)
![image](https://user-images.githubusercontent.com/28681519/53552617-aca22d00-3b76-11e9-80c5-d0a660902c43.png)

**Comment by CasualJi** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
