### ISSUE TITLE
f-admin——基于 Laravel 框架开发的基础权限后台系统

### ISSUE THREAD

**Issue by fangzesheng** [521xueweihan/HelloGitHub#471]
## 项目推荐
- 项目地址：https://github.com/fangzesheng/f-admin

- 类别：PHP

- 项目后续更新计划：将所用laravel框架更新到最新版本

- 项目描述：f-admin基础权限后台是一套基于Laravel框架开发的系统，不需要开发者重复不必要的工作，就可以实现后台功能的快速开发。

- 推荐理由：避免重复造轮子，严格的前后端验证

- 截图：![](https://github.com/fangzesheng/f-admin/raw/master/img/index.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
