### ISSUE TITLE
pprof

### ISSUE THREAD

**Issue by googege** [521xueweihan/HelloGitHub#472]
## 项目推荐
- 项目地址：https://github.com/google/pprof
- 类别：GO

- 项目后续更新计划：

- 项目描述：
  - 必写：pprof是用于可视化和分析性能分析数据的工具,将go中的测试数据进行多种可视化，有效的加快了速度的分析速度，以及可观性
  - 可选：适用于go程序的数据测试，压力测试，以及查看逃逸分析，内存的使用情况等调试环节。
  - 描述长度（不包含示例代码）:

- 推荐理由：结合go本身的pprof，让可视化的数据测试更上一层楼啊，它可以分析可以任意产生protocol buffer格式的数据的程序，不管程序是什么语言开发的，简直爽翻了

- 示例代码：

- 截图：

**Comment by FrontMage** [comment]
收录至36期发布

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 36 期](https://hellogithub.com/periodical/volume/36/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
