### ISSUE TITLE
代替endnote的zotero文献管理器

### ISSUE THREAD

**Issue by tangdou1** [521xueweihan/HelloGitHub#473]
## 项目推荐
- 项目地址：zotero /zotero

- 类别：js 请从中选择（C、C#、C++、CSS、Go、Java、JS、Kotlin、Objective-C、PHP、Python、Ruby、Swift、其它、书籍、机器学习）

- 项目后续更新计划：

- 项目描述：
  - 必写：文献管理器
  - 可选：学术研究，资源整理
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：极其好用

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

### 编辑完推荐项目的信息，**请删除**下述提示信息
1. [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271)

2. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

3. HelloGitHub 网站：https://hellogithub.com

再次感谢您对《HelloGitHub》项目的支持！

**Comment by 521xueweihan** [comment]
请按照提示填写推荐信息，并删除提示性信息。

**Comment by tangdou1** [comment]
> 
> 
> 请按照提示填写推荐信息，并删除提示性信息。

已修改
