### ISSUE TITLE
ncform，一种令人愉悦的表单配置开发方式

### ISSUE THREAD

**Issue by daniel-dx** [521xueweihan/HelloGitHub#474]
## 项目推荐
- 项目地址：https://github.com/ncform/ncform

- 类别：JS

- 项目描述：

  - ncform是什么？
   
     ncform，一种令人愉悦的表单开发方式，仅需配置即可生成表单UI及其交互行为。

  - 为什么要用它？

     后台管理系统中绝大部分的功能不是查询列表，就是录入表单。
表单的开发是一种无趣的，无营养的，高消耗的重复体力活，费时费力。
表单控件间的交互功能，表单项的校验规则，都极容易产生“八哥”。
SO，为了提高表单开发效率，减少失误，提高表单规范和健壮性，最重要，提高开发人员的开发幸福感，项目因此而生

  - 它有什么特性:

      - 配置生成：一个JSON数据结构完整描述一个表单的UI及其交互行为，表单的开发工作就完成了

      - 灵活互动：通过强大的dx表达式，表单控件可灵活与其它表单控件进行互动

      - 标准组件：ncform定义了一套标准的表单组件配置规范，未经扩展即可满足你90%以上的表单开发需求

      - 校验丰富：自带常用的十几种验证规则，满足你90%以上的表单验证需求

      - 扩展友好：表单的组件和校验规则都可灵活扩展，并且提供了工具简化扩展工作

- 推荐理由：高效的配置开发方式，开箱即用，经过多个实际投产项目的验证（唯品会第一个前端开源项目，目前移交ncform组织维护），可满足几乎你遇到的所有表单开发的场景，而不只是一个好看或好玩的玩具

- 示例代码：

请在 [Playground](https://ncform.github.io/ncform/ncform-show/playground/index.html?lang=cn) 领略ncform的魅力吧

- 截图：

![ncform preview](https://github.com/ncform/ncform/raw/master/docs/images/preview.png)

**Comment by ming995** [comment]
有react版本吗

**Comment by daniel-dx** [comment]
有计划，但暂时排期不上

**Comment by jaywcjlove** [comment]
@ming995 思路差不多的实现。 https://uiwjs.github.io/#/components/form 你可以copy出来搞个包

**Comment by daniel-dx** [comment]
我想思路应该不太一样哈，ncform不会再开发一套表单控件，而是能与优秀的ui开源项目像elementui和平共处，ncform就是个容器，具体可以看readme最后的设计思想哈

**Comment by jaywcjlove** [comment]
@daniel-dx [uiw](https://uiwjs.github.io/#/components/form) 中的 Form 组件，实现方式也是当做一个容器，如果独立出来一样能与 antd 等 React 组件库和平共处。

**Comment by daniel-dx** [comment]
厉害厉害，各有各自解决的问题，我就不作一一对比了哈

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 36 期](https://hellogithub.com/periodical/volume/36/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
