### ISSUE TITLE
自荐项目：rxweb

### ISSUE THREAD

**Issue by zhangjessey** [521xueweihan/HelloGitHub#475]
## 项目推荐
- 项目名称：rxweb

- 项目地址：https://github.com/zhangjessey/rxweb

- 类别：Java

- 项目后续更新计划：不断新增feature，详见README.md和修复已有的bug

- 项目描述：基于RxJava和RxNetty的web框架，已实现函数式路由以及注解式路由，类似于一个极简版的Spring WebFlux。适用于常规web项目，比如使用Spring MVC或者使用Spring WebFlux的场景。

- 推荐理由：响应式的Java web框架，基于Servlet的SpringMVC已经渐渐过时，响应式方兴未艾，从零开始造一个类似Spring WebFlux的轮子，对理解其本质原理有极大的好处，项目本身并不复杂，易于学习，代码规范，在阿里Java规约检测中无警告信息，注释清晰，便于扩展改造。

- 截图：
![annotated route](https://user-images.githubusercontent.com/25023163/53624821-6fa06e00-3c3c-11e9-8f52-bb0d6f91d1fc.png)

![functionalroute](https://user-images.githubusercontent.com/25023163/53625267-91e6bb80-3c3d-11e9-880d-fc6cd44d8a4e.png)

**Comment by CasualJi** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
