### ISSUE TITLE
ETCD

### ISSUE THREAD

**Issue by NineSunRD** [521xueweihan/HelloGitHub#476]
## 项目推荐
- 项目地址：https://github.com/etcd-io/etcd

- 类别：Go

- 项目后续更新计划：见该项目的官方网站

- 项目描述：
  - 必写：ETCD 是一个高可用的分布式键值数据库，可用于服务发现。ETCD 采用 raft 一致性算法，基于 Go 语言实现。
  - 可选：可以通过该项目了解raft与zk的一些差别，学习raft的实际应用。

- 推荐理由：采用raft协议，保证分布式的数据一致性和高可用性，与现有的zk可以对照学习。

**Comment by FrontMage** [comment]
收录至36期发布

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 36 期](https://hellogithub.com/periodical/volume/36/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
