### ISSUE TITLE
项目推荐

### ISSUE THREAD

**Issue by TrumanDu** [521xueweihan/HelloGitHub#477]
## 项目推荐
- 项目地址：
[https://github.com/xaecbd/RCT](https://github.com/xaecbd/RCT)
- 类别：java

- 项目后续更新计划：
目前开源的是2.0.0，后续会继续开源lite版，更轻量级，更容易使用。
- 项目描述：
  - 必写：RCT(Redis Computed Tomography)是一个通过解析rdb文件对redis内存结构分析的一站式平台。 支持对非集群/集群rdb文件分析、Slowlog查询与监控、ClientList查询与监控。
  - 可选：适用于redis运维管理人员需要了解redis中使用情况。
  - 描述长度（不包含示例代码）: 10 - 256 个字符
  
- 推荐理由：优雅高效的分析redis中的内存数据情况，支持多种报表可视化与邮件发送功能，让redis的内存使用不再是黑盒。

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

![rct](https://user-images.githubusercontent.com/16727775/53633870-9ae28780-3c53-11e9-9338-db2ebeef0c86.jpg)

**Comment by CasualJi** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
