### ISSUE TITLE
[Fira Code] [ 一个程序员专供的字体]

### ISSUE THREAD

**Issue by Aimiyoo** [521xueweihan/HelloGitHub#478]
## 项目推荐
- 项目地址：https://github.com/tonsky/FiraCode

- 类别：其它

- 项目后续更新计划： 见该项目的官方网站

- 项目描述：
  - 必写：高逼格的具有编程连字的等宽字体，最适合在编程编辑器和IDE中使用
  - 可选：支持多种终端和IDE

- 推荐理由：超酷的字体，可以增加写代码的欲望，程序员专供字体

- 截图：
![image](https://user-images.githubusercontent.com/8653546/53652819-b87c1500-3c84-11e9-8cd3-d69a1eee6287.png)
![image](https://user-images.githubusercontent.com/8653546/53653148-946d0380-3c85-11e9-8c23-bc1bb158e098.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
