### ISSUE TITLE
 项目推荐 LeetCode for VS Code

### ISSUE THREAD

**Issue by jdneo** [521xueweihan/HelloGitHub#479]
## 项目推荐
- 项目地址：https://github.com/jdneo/vscode-leetcode

- 类别：JS

- 项目后续更新计划：
  - 进一步完善使用体验

- 项目描述：
这是一个可以让用户在 VS Code 中，练习 LeetCode 的插件。可用于练习算法，助你在校招，社招中杀出重围，目前支持的功能有：
  - 切换中英文版 LeetCode
  - Session 管理
  - 测试，提交答案
  - 题目的分类，方便针对性训练

- 推荐理由：比较适合于那些，喜欢沉浸式编程体验的用户，在 VS Code 中练习算法题。同时也是上班摸鱼小神器。

- 截图：
![gif](https://raw.githubusercontent.com/jdneo/vscode-leetcode/master/docs/gifs/demo.gif)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 36 期](https://hellogithub.com/periodical/volume/36/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by jdneo** [comment]
Hi @521xueweihan, 

我在贡献者列表里并没有看到自己的Github ID

**Comment by 521xueweihan** [comment]
@jdneo 感谢反馈，是我这边编辑的时候出现的失误，现在已经修复了。

**Comment by jdneo** [comment]
@521xueweihan 谢谢，看到了。
