### ISSUE TITLE
分布式系统介绍

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#480]
## 项目推荐
- 项目地址：https://github.com/aphyr/distsys-class

- 类别：书籍

- 项目描述：
  详细介绍了分布式系统

- 推荐理由：

  随着云的普及，分布式这个关键词越来越受到追捧。本篇由浅入深得介绍了什么是分布式系统，为什么要分布式系统以及如何实现分布式系统，让人更容易理解分布式系统。

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
