### ISSUE TITLE
给女朋友发一封暖心邮件

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#481]
## 项目推荐
- 项目地址： https://github.com/Vincedream/NodeMail

- 类别：JS

- 项目描述：
  用Node写一个爬虫脚本每天定时给女朋友发一封暖心邮件

- 推荐理由：

作为一个程序员，还在愁女友说自己不浪漫吗？赶紧行动起来，每天给女友发发一封暖心邮件吧。

使用nodejs，框架简单，上手容易，方便二次开发定制。

**Comment by daixiang0** [comment]
@ming995 这个是什么原因关闭的？

**Comment by 521xueweihan** [comment]
@daixiang0 没有达到收录的标准
