### ISSUE TITLE
SS的前世今生

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#482]
## 项目推荐
- 项目地址：https://github.com/JadaGates/ShadowsocksBio.git

- 类别：书籍

- 项目描述：
  介绍了SS的前世今生以及简单使用方法。

- 推荐理由：

由于种种不可抗力，SS已成为国内码农不可或缺的生活必备品。为什么要SS？SS是谁写的？SS该怎么用？等等问题，都能在这里找到答案。

**Comment by 521xueweihan** [comment]
@daixiang0 本项目为了‘长治久安’ 暂不推荐此类项目
