### ISSUE TITLE
JAVA后端架构师技术图谱

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#483]
## 项目推荐
- 项目地址：https://github.com/xingshaocheng/architect-awesome

- 类别： Java、书籍

- 项目描述：
 基于Java语言，由浅入深得介绍了后端架构师的技术图谱。

- 推荐理由：

Java工程师可以以此图谱拓展自己的知识面，提高自己的专业水平，使用其他语言的工程师也能触类旁通，是不可多得的完整的技术图谱。

**Comment by 521xueweihan** [comment]
@daixiang0 此类集合、教程等隶属于 其它 分类，只有包含：Gitbook、详细的目录，章节、符合书籍的特征的项目才属于 书籍 分类

**Comment by daixiang0** [comment]
@521xueweihan Get it.

**Comment by CasualJi** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
@daixiang0 该项目已推荐过：https://hellogithub.com/periodical/search/?q=https://github.com/xingshaocheng/architect-awesome#architect-awesome
