### ISSUE TITLE
自荐项目 - Android多功能刷新控件 

### ISSUE THREAD

**Issue by dkzwm** [521xueweihan/HelloGitHub#485]
## 项目推荐
- 项目地址：https://github.com/dkzwm/SmoothRefreshLayout

- 类别：Java

- 项目后续更新计划：修复BUG，提高性能

- 项目描述：支持所有的视图、支持越界回弹、二级刷新（淘宝二楼、京东活动）、横向刷新、拉伸回弹、类QQ下拉回弹效果

- 推荐理由：单个控件可实现较为复杂的效果。

**Comment by CasualJi** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 39 期](https://hellogithub.com/periodical/volume/39/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

为了让开源项目的发起者不再孤单，我们决定牵线搭桥。可以加我微信：xueweihan（备注您发起的项目链接）
待时机成熟，你会发现你并不孤独！
