### ISSUE TITLE
微信小程序开发资源汇总

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#486]
## 项目推荐
- 项目地址：
https://github.com/justjavac/awesome-wechat-weapp

- 类别：JS、书籍

- 项目描述：
收集了微信小程序开发过程中会使用到的资料、问题以及第三方组件库

- 推荐理由：

随着微信的独霸市场，微信小程序的市场越来越大，很多公司也专门以制作小程序为业，不论对感兴趣的人还是想自己动手做小程序的人而言，这份合集省去了不少查询的时间。

**Comment by 521xueweihan** [comment]
基于月刊的篇幅考虑，将于 37 收录您推荐的项目。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 37 期](https://hellogithub.com/periodical/volume/37/#awesome-wechat-weapp)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
