### ISSUE TITLE
new-project-checklist

### ISSUE THREAD

**Issue by nivance** [521xueweihan/HelloGitHub#488]
## 项目推荐
- 项目地址：https://github.com/phodal/new-project-checklist

- 类别：其它

- 项目后续更新计划：未知

- 项目描述：新项目检查清单及其工具

- 推荐理由：可以依照这份清单来检查自己的项目

**Comment by 521xueweihan** [comment]
基于月刊的篇幅考虑，将于 37 收录您推荐的项目。

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
