### ISSUE TITLE
windows原生计算器

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#489]
## 项目推荐
- 项目地址：https://github.com/Microsoft/calculator

- 类别：C++

- 项目后续更新计划：

  - 添加用户将计算器固定在其他窗口之上的功能
  - 提供其他自定义选项

- 项目描述：
  是一个用C ++编写的现代Windows应用程序，预装在Windows内。
  该应用程序提供标准，科学和程序员计算器功能，以及各种度量单位和货币之间的一组转换器。

- 推荐理由：
 
  一向闭源的Windows终于开源啦！计算器的实现并不复杂，但如何做到简单高效安全，快来看看微软工程师是如何编写的吧！  

- 截图：

  [截图](https://github.com/Microsoft/calculator/blob/master/docs/Images/CalculatorScreenshot.png)

**Comment by ChungZH** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
