### ISSUE TITLE
FFLoadingView

### ISSUE THREAD

**Issue by FFFang** [521xueweihan/HelloGitHub#49]
## 项目推荐
- 项目：FFLoadingView https://github.com/FFFang/FFLoadingView
- 项目语言：
Objective-C
- 项目描述：
LoadingView with animation Edit
- 推荐理由：
简单易用的加载动画
- 示例代码：
`[self.loadingView startLoading];`
- 截图：
![FFLoadingView.gif](https://ooo.0o0.ooo/2017/06/13/593f81e7a8a97.gif)

**Comment by 521xueweihan** [comment]
@FFFang 您好，我个人认为该项目功能较为简单，不能收录到 HelloGitHub。

欢迎讨论 ❤️
