### ISSUE TITLE
JsonTemplate一个生成Json字符串的Java库

### ISSUE THREAD

**Issue by haihanyin** [521xueweihan/HelloGitHub#490]
## 项目推荐
- 项目地址：https://github.com/json-template/JsonTemplate

- 类别：Java

- 项目后续更新计划：
不断改进

- 项目描述：
  - 必写：用来生成Json字符串的Java库
  - 可选：用模板字符串来生成Json字符串，快速直接，无需借助创建模型类来序列化
  - 描述长度：
见推荐理由

- 推荐理由：
1. 在Java中编写Json字符串，智能识别，省去加入双引号(“\"”)的工作。
2. 无需借助serializer，直接用字符串，仍保持代码可读性。
3. 用“格式结构“来生成符合要求的字符串，无需考虑具体值。

- 示例代码：（可选）长度：1-20 行
```java
String template = "{" +
                  "  name : @s," +
                  "  age : @i(max=100)," +
                  "  role : @s[](min=1, max=3)," +
                  "  address : {" +
                  "    city : @s," +
                  "    street : @s," +
                  "    number : @i" +
                  "  }" +
                  "}";
String json = new JsonTemplate(template).prettyString(); 
```

- 截图：（可选）gif/png/jpg

**Comment by CasualJi** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
