### ISSUE TITLE
推荐一个免费的技术学习列表

### ISSUE THREAD

**Issue by qinchaofeng** [521xueweihan/HelloGitHub#491]
## 项目推荐
- 项目地址：https://github.com/EbookFoundation/free-programming-books

- 类别：书籍

- 项目后续更新计划：

- 项目描述：
  - 必写：免费编程书籍列表
  - 可选：各种IT学习书籍
  - 描述长度（不包含示例代码）: 这个列表最初是StackOverflow的clone版本，它是由Karan Bhangui和George Stocker提供的免费编程书籍列表

- 推荐理由：各种免费编程书籍列表

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
英文书籍，对于新手不是很友好，所以暂时决定不收录该项目。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
