### ISSUE TITLE
可扩展、可靠和高性能的大型系统背后的模式

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#492]
## 项目推荐
- 项目地址：https://github.com/binhnguyennus/awesome-scalability

- 类别：书籍

- 项目描述：
一个有组织的阅读列表，用于说明可扩展、可靠和高性能的大型系统背后的模式。案例研究来自为数百万至数十亿用户提供服务的经过实战检验的系统。

- 推荐理由：
基于真实案例，讲述了如何搭建一个可扩展的可靠的高性能的大型系统，对于所有工程师而言都是一个很好的知识学习，从高层次纵观软件开发，提升自己的视界。

**Comment by 521xueweihan** [comment]
基于月刊的篇幅考虑，将于 37 收录您推荐的项目。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 37 期](https://hellogithub.com/periodical/volume/37/#awesome-scalability)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
