### ISSUE TITLE
Hope-plus是一款nice的权限管理系统。基于Springboot2开发，整合使用mybatis+shiro+redis+thymeleaf+maven等实用技术。🏷

### ISSUE THREAD

**Issue by java-aodeng** [521xueweihan/HelloGitHub#493]
## 项目推荐
- 项目地址：
https://github.com/java-aodeng/hope-plus
- 类别：Java

- 项目后续更新计划：添加定时服务，数据权限分离

- 项目描述：
  - 必写：Hope-plus是一款nice的权限管理系统。基于Springboot2开发，整合使用mybatis+shiro+redis+thymeleaf+maven等实用技术。🏷

- 推荐理由：代码格式整洁，适合学习，或者二开

再次感谢《HelloGitHub》项目的支持！

**Comment by java-aodeng** [comment]
牛逼

**Comment by CasualJi** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
