### ISSUE TITLE
编译入门

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#495]
## 项目推荐
- 项目地址：

https://github.com/aalhour/awesome-compilers

- 类别：书籍

- 项目描述：
 关于编译器，解释器和运行时领域的源代码项目的精选列表。

- 推荐理由：

编程语言究竟是如何实现的？编译器和解释器又是什么鬼？对于想探索这一神秘领域的童鞋而言是一个不错的合集。

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
