### ISSUE TITLE
Go语言四十二章经

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#496]
## 项目推荐
- 项目地址： https://github.com/ffhelicopter/Go42

- 类别：Go、J书籍

- 项目后续更新计划：

本书会持续更新！为了更简单表述清楚，某些章节的内容我会根据情况随时更新；当然也会随Go语言版本的不断更新，不断修改完善相关章节的内容和代码。

- 项目描述：

这本书适合Go语言新手来细细阅读，对于有一定经验的开发人员，也可以根据自己的情况，选择一些章节来看。

- 推荐理由：

结合作者编程经历，将开发过程中碰到过的一些问题，踩到过的一些坑，融入在对这门语言的核心思维、清晰掌握语言的细节规范以及反复琢磨标准包代码设计模式的理解中，无论是新手还是开发人员，都有可学习的地方。

**Comment by FrontMage** [comment]
收录至36期发布

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 36 期](https://hellogithub.com/periodical/volume/36/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
