### ISSUE TITLE
最接近微信朋友圈的图片压缩算法

### ISSUE THREAD

**Issue by nivance** [521xueweihan/HelloGitHub#499]
## 项目推荐
- 项目地址：https://github.com/Curzibn/Luban

- 类别：Java

- 项目后续更新计划：未知

- 项目描述：
  - 必写：一个号称可能是最接近微信朋友圈的图片压缩算法

- 推荐理由：App上的图片压缩是刚需，解决微信的压缩算法必须支持 

- 示例代码：无

- 截图：
![](https://user-images.githubusercontent.com/3291404/54249925-d72fb500-457c-11e9-98da-4760333ca942.jpg)

**Comment by CasualJi** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 36 期](https://hellogithub.com/periodical/volume/36/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
