### ISSUE TITLE
[推荐]python版的聚合搜索引擎searx

### ISSUE THREAD

**Issue by BruceDone** [521xueweihan/HelloGitHub#5]
- git地址：
  https://github.com/asciimoo/searx
- 推荐理由
  1.分分钟打造一个聚合的搜索引擎，使用简单方便，docker镜像已经打包好，直接使用
  2.拓展方便，基于插件式的管理。
- 演示地址
  https://searx.me/

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

如您推荐的项目在《HelloGithub》月刊中推荐，则会同时写明推荐人。

再次感谢您对《HelloGithub》项目的支持！

**Comment by 521xueweihan** [comment]
您好，searx 项目已收录到 [13期](https://github.com/521xueweihan/HelloGitHub/blob/master/13/HelloGitHub13.md)，再次感谢您的支持，希望以后推荐更多好的项目。
