### ISSUE TITLE
Chrome插件英雄榜

### ISSUE THREAD

**Issue by nivance** [521xueweihan/HelloGitHub#500]
## 项目推荐
- 项目地址：https://github.com/zhaoolee/ChromeAppHeroes

- 类别：书籍

- 项目后续更新计划：未知

- 项目描述：
  - 必写：Chrome插件英雄榜, 为优秀的Chrome插件写一本中文说明书

- 推荐理由：Chrome实用插件

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 36 期](https://hellogithub.com/periodical/volume/36/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by zhaoolee** [comment]
项目后续更新计划: Chrome插件英雄榜, 每周会更新1到2篇~
