### ISSUE TITLE
2048 node版

### ISSUE THREAD

**Issue by bestvist** [521xueweihan/HelloGitHub#501]
## 项目推荐
- 项目地址：https://github.com/bestvist/2048.node

- 类别：Javascript
- 项目后续更新计划：
保存分数
增加排行榜

- 项目描述：
  2048游戏node版

- 推荐理由：
 2048游戏，cli即可开始。

- 示例代码：

```
npm install -g 2048.node

2048node
```

- 截图：

![demo](https://github.com/bestvist/2048.node/raw/master/demo.gif)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
