### ISSUE TITLE
The Way to Go

### ISSUE THREAD

**Issue by ChungZH** [521xueweihan/HelloGitHub#503]
## 项目推荐
- 项目地址：
https://github.com/Unknwon/the-way-to-go_ZH_CN
- 类别：Go

- 项目后续更新计划：

- 项目描述：

《The Way to Go》中文译本。一本优秀的 Go 语言入门书籍。

- 推荐理由：

简单、易懂。

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

**Comment by daixiang0** [comment]
duplicate 第 09 期、开源书籍
