### ISSUE TITLE
自学是门手艺

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#504]
## 项目推荐
- 项目地址：
https://github.com/selfteaching/the-craft-of-selfteaching
- 类别：书籍

- 项目后续更新计划：

- 项目描述：
 一个编程入门者的自学心得

- 推荐理由：
如今学习资源很多，对于初学者入门而言，最难的是如何自学，跟着作者的脚本打开编程自学大门吧。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 37 期](https://hellogithub.com/periodical/volume/37/#the-craft-of-selfteaching)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
