### ISSUE TITLE
从零构建属于自己的X

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#506]
## 项目推荐
- 项目地址：

https://github.com/danistefanovic/build-your-own-x

- 类别：其它

- 项目描述：
  从零构建属于自己的docker\git\database等。

- 推荐理由：

 docker\git\database等对于程序员而言再熟悉不过，但是他们是怎么设计的、怎么从零构建的呢？这个项目能给你解惑，并帮助你构建属于自己的docker\git\database等。

**Comment by 521xueweihan** [comment]
https://hellogithub.com/periodical/search/?q=https://github.com/danistefanovic/build-your-own-x

该项目已推荐过
