### ISSUE TITLE
自荐项目 ：AntzOS

### ISSUE THREAD

**Issue by CasterWx** [521xueweihan/HelloGitHub#507]
## 项目推荐

- 项目地址：https://github.com/CasterWx/AntzOS

- 类别：C

- 项目后续更新计划：完善任务调度与图形界面，添加其他的命令，长远目标是实现网络协议栈。

- 项目描述：AntzOS是一个在完成系统引导后便开始随心所欲设计的操作系统，在读完开发文档之后，你可以根据自己的理解自己来实现系统内功能，例如在任务调度方面，我没有采取Linux2.6之后的"完全公平调度算法"，而是一个为了设计方便直接在时钟中随机调度的算法。系统的显卡操作是作者在多媒体课上的灵光一现而直接使用的根据图片的RGB写显存，虽然目前终端是黑白色的，但依旧可以在其中显示彩色图片，支持24位色图像。系统可直接载入U盘，开机时U盘启动并使用AntzOS系统。

- 推荐理由： 你可以不用去在意学校OS课程学习的大部分理论，而是去根据自己对操作系统的理解来实现OS功能。

- 截图：

![1](https://github.com/CasterWx/AntzOS/raw/master/screen/runShow.gif)
 
![2](https://github.com/CasterWx/AntzOS/raw/master/screen/%E8%99%9A%E6%8B%9F%E6%9C%BA1.gif?raw=true)

**Comment by ChungZH** [comment]
非常感谢您推荐项目。

> 个人意见：该项目以前已经提过（ #368  ），因为 README 原因被拒。直到现在它的 README 还是不够完善 :joy: （不过我是挺喜欢这个项目的hhh

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
