### ISSUE TITLE
WormHole是一个简单易用的api管理平台，支持dubbo服务调用

### ISSUE THREAD

**Issue by deathearth** [521xueweihan/HelloGitHub#508]
## 项目推荐
- 项目地址：https://github.com/deathearth/wormhole

- 类别：Java

- 项目后续更新计划：

  在实际应用过程中，解决遇到的各种问题。不断提升整体的易用性。
- 项目描述：
  - 必写：API网关系统，支持dubbo服务的泛化调用，有简单的后台操作功能
  - 可选：统一api的管理和接入入口。可以学到签名、验签、组件化控制等知识
  - 描述长度（不包含示例代码）: 
WormHole是一个简单、易用的api管理平台。目的是为了降低后端服务开发与前端调用的耦合性。通过WormHole这一层使整个项目的开发协作更加完善。客户端开发人员从管理平台查找需要的接口信息进行调用，服务端开发人员定义好接口后同步到管理平台中，管理平台可以统一对接口的访问设置等。

- 推荐理由：有效降低了前后端人员的工作耦合度，不仅有效的管理API接口，且统一了调用入口

- 示例代码：（可选）长度：1-20 行
private Object routeService(Context context, GatewayApiDO apiInfo, String types[],
      Object values[]) {

    ReferenceConfig<GenericService> reference = new ReferenceConfig<GenericService>();
    Object result = null;
    GenericService genericService = null;
    try {
      // 1.初始化对象
      application.setName(runConfig.getApplicationName());
      registryConfig.setAddress(runConfig.getZookeeperAddress());
      registryConfig.setProtocol("zookeeper");

      reference.setApplication(this.application);
      reference.setRegistry(this.registryConfig);
      // 声明为泛化接口
      reference.setGeneric(true); 
      reference.setInterface(apiInfo.getServiceName());
      reference.setVersion(apiInfo.getServiceVersion());
      reference.setTimeout(apiInfo.getTimeOut());
      reference.setRetries(0);

      // 2.缓存处理
      genericService = ReferenceConfigCache.getCache().get(reference);
      if (genericService == null) {
        ReferenceConfigCache.getCache().destroy(reference);
        logger.error("dubbo server not founded ! apiInfo is {}", JSON.toJSONString(apiInfo));
        throw new GatewayException(ResultCode.SYSTEM_NOT_FOUNDED);
      }

      // 3.设置上下文对象
      setGWContext(context);

      // 4.调用服务
      result = genericService.$invoke(apiInfo.getServiceMethod(), types, values);
    } catch (Throwable e) {
      logger.error("eid={} context={} type={} param={}", e.hashCode(), JSON.toJSONString(context), JSON.toJSONString(types), JSON.toJSONString(values));
      throw e;
    }
    return result;
  }

- 截图：（可选）gif/png/jpg
![image](https://user-images.githubusercontent.com/17823587/54689717-0933af00-4b5b-11e9-92ec-d35892e21ef5.png)
![image](https://user-images.githubusercontent.com/17823587/54689900-4d26b400-4b5b-11e9-91e0-6456d428e759.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 40 期](https://hellogithub.com/periodical/volume/40/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
