### ISSUE TITLE
用Gloading深度解耦Android App中全局加载中、加载失败及空数据视图

### ISSUE THREAD

**Issue by luckybilly** [521xueweihan/HelloGitHub#509]
## 项目推荐
- 项目地址：https://github.com/luckybilly/Gloading

- 类别：Java

- 项目后续更新计划：

- 项目描述：
  - 深度解耦Android App中全局加载中、加载失败及空数据视图
  - 分离全局加载状态视图的实现和使用
  - 不需要在每个页面的布局文件中额外添加加载状态视图
  - 可用于Activity，也可用于为某个View显示加载状态，还可用于各种通过列表Item（ListView、RecyclerView等）

- 推荐理由：
  - 深度解耦，特别适用于页面在多个App中复用时加载视图风格不一的情况
  - 助力解决组件化改造过程中的解耦长征

- 示例代码：
```java
Gloading.initDefault(new GlobalAdapter());
Gloading.Holder holder = Gloading.getDefault().wrap(activity).withRetry(retryTask);
Gloading.Holder holder = Gloading.getDefault().wrap(view).withRetry(retryTask);

//显示加载中的UI状态
holder.showLoading() 

//显示加载成功的UI状态
holder.showLoadSuccess()

//显示加载失败的UI状态
holder.showFailed()

//显示加载成功，但数据未空的UI状态
holder.showEmpty()
```

- 截图：

为Activity添加全局加载状态

加载成功|加载失败<br>点击重试|加载成功<br>无数据|个别页面使用特殊的Loading视图
:---:|:---:|:---:|:---:
<img src="https://github.com/luckybilly/Gloading/raw/master/image/en_load_success.gif" width="200" />|<img src="https://github.com/luckybilly/Gloading/raw/master/image/en_load_failed.gif" width="200" />|<img src="https://github.com/luckybilly/Gloading/raw/master/image/en_load_empty_data.gif" width="200" />|<img src="https://github.com/luckybilly/Gloading/raw/master/image/en_load_special_loading.gif" width="200" />

为View添加全局加载状态

单个View|多个View|用于GridView|用于RecyclerView<br>并且不显示文字
:---:|:---:|:---:|:---:
<img src="https://github.com/luckybilly/Gloading/raw/master/image/en_wrap_single_view.gif" width="200" />|<img src="https://github.com/luckybilly/Gloading/raw/master/image/en_wrap_scroll_view.gif" width="200" />|<img src="https://github.com/luckybilly/Gloading/raw/master/image/en_wrap_grid_view.gif" width="200" />|<img src="https://github.com/luckybilly/Gloading/raw/master/image/en_wrap_recycler_view.gif" width="200" />

**Comment by CasualJi** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
@luckybilly 我可以理解这是个安卓的加载组件吗？

**Comment by luckybilly** [comment]
可以的

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 38 期](https://hellogithub.com/periodical/volume/38/#Gloading)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
