### ISSUE TITLE
SpaceVim - 一个模块化的 Vim 配置

### ISSUE THREAD

**Issue by wsdjeg** [521xueweihan/HelloGitHub#51]
## 项目推荐
- 项目：[SpaceVim](https://github.com/SpaceVim/SpaceVim)

- 项目语言：vim script

- 项目描述：SpaceVim 是一个社区驱动的模块化 vim/neovim 配置集合，其中包含了多种功能模块，并且针对 neovim 做了功能优化。spacevim 有多种功能模块可供选择，用户只需要选择需要的模块，就可以配置出一个适合自己的开发环境。

- 推荐理由：简单易上手，所有快捷键都有导航系统，支持多种语言开发

- 示例代码：

- 截图：

![2017-04-29-20 54 49](https://cloud.githubusercontent.com/assets/13142418/25555650/d7d2c07e-2d1e-11e7-975d-646a07b38a62.png)

**Comment by 521xueweihan** [comment]
您推荐的项目已收录到 [15 期](https://github.com/521xueweihan/HelloGitHub/blob/master/content/15/HelloGitHub15.md#其它)，同时您已加入到 [贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/contributors.md) 中。

期待老铁后面继续推荐给力的项目 💪

**Comment by wsdjeg** [comment]
@521xueweihan 谢谢，我是终端里面玩的比较多，后面可以推荐一些终端下比较有意思的程序。

**Comment by 521xueweihan** [comment]
@wsdjeg 好的，非常欢迎
