### ISSUE TITLE
Chrome插件英雄榜

### ISSUE THREAD

**Issue by zhaoolee** [521xueweihan/HelloGitHub#510]
## 项目推荐
- 项目地址：https://github.com/zhaoolee/ChromeAppHeroes

- 类别：书籍

- 项目后续更新计划：
每周更新1至2篇

- 项目描述：
  - 必写：Chrome插件英雄榜, 为优秀的Chrome插件写一本中文说明书, 让Chrome插件英雄们造福人类~

- 推荐理由：为优秀的Chrome插件写一本中文说明书, Chrome插件借助Chrome完成了跨平台, 而且大多开源, 相信经过谷歌的推广, Chrome插件会成为谷歌未来操作系统的重要组成部分, 但国内很多用户并不了解Chrome插件, 这里通过对每一个推荐的插件进行详细评测, 让Chrome插件英雄们造福人类~

**Comment by 521xueweihan** [comment]
您好，您推荐的项目已经收录到第 36 期，因为我上期操作错误。没有把您放到贡献者列表中，本期修复。

再次谢谢您对 HelloGitHub 的支持。
