### ISSUE TITLE
自荐 Python 项目 - ScrapydWeb，一个用于 Scrapyd 集群管理的全功能 web UI，支持 Scrapy 日志分析和可视化

### ISSUE THREAD

**Issue by my8100** [521xueweihan/HelloGitHub#511]
## 项目推荐
- 项目地址：https://github.com/my8100/scrapydweb

- 类别：Python

- 项目后续更新计划：完善数据可视化，添加 REST API，前后端分离及单页应用

- 项目描述：一个用于 Scrapyd 集群管理的全功能 web UI，支持 Scrapy 日志分析和可视化，自动打包，定时器任务和邮件通知等特色功能，详见[文档和预览](https://github.com/my8100/files/blob/master/scrapydweb/README_CN.md)。

- 推荐理由：Scrapyd 集群管理实现了一次操作，批量执行，彻底摆脱繁琐的命令行操作。独创性的 Scrapy 日志分析和可视化，实时掌控爬虫进度。

- 截图：
  - Scrapyd 集群管理
![servers](https://raw.githubusercontent.com/my8100/files/master/scrapydweb/screenshots/servers.png)
  - Scrapy 日志分析和可视化
![stats](https://raw.githubusercontent.com/my8100/files/master/scrapydweb/screenshots/stats.gif)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 36 期](https://hellogithub.com/periodical/volume/36/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
