### ISSUE TITLE
pyright

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#513]
## 项目推荐
- 项目地址：

https://github.com/Microsoft/pyright.git

- 类别：JS、Python

- 项目后续更新计划：

https://github.com/Microsoft/pyright#todo

- 项目描述：
  一个高速高效的Python代码检测工具

- 推荐理由：

 微软出品，质量保证，执行速度快，效率高，适合大型Python项目

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 37 期](https://hellogithub.com/periodical/volume/37/#pyright)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
