### ISSUE TITLE
高效搜索工具

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#514]
## 项目推荐
- 项目地址：

https://github.com/valeriansaliou/sonic.git

- 类别：其它

（Rust语言，现在无专栏）

- 项目描述：
  快速，轻量级和无架构的搜索后端。Elasticsearch的替代方案，可在几MB的RAM上运行。

- 推荐理由：

  超轻量级，相比与ES的沉重，更适合在微服务架构使用。

- 示例代码：

https://github.com/valeriansaliou/sonic#demo

**Comment by FrontMage** [comment]
@daixiang0 这个支持中文吗？

**Comment by daixiang0** [comment]
of course, refer to [doc](https://github.com/valeriansaliou/sonic#which-text-languages-are-supported)

**Comment by FrontMage** [comment]
这货居然没有rust的client，折腾了两周手写了一个。。。
