### ISSUE TITLE
Google开源的图片压缩器

### ISSUE THREAD

**Issue by nivance** [521xueweihan/HelloGitHub#515]
## 项目推荐
- 项目地址：https://github.com/GoogleChromeLabs/squoosh/

- 类别：JS

- 项目后续更新计划：无

- 项目描述：
  - 必写：在保证图片质量的情况下快速压缩图片。支持多种图片格式。

- 推荐理由：压缩后的图片质量很不错

- 示例代码：无

- 截图：无

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 37 期](https://hellogithub.com/periodical/volume/37/#squoosh)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
