### ISSUE TITLE
实时多人2D姿态检测库——openpose

### ISSUE THREAD

**Issue by nivance** [521xueweihan/HelloGitHub#516]
## 项目推荐
- 项目地址：https://github.com/CMU-Perceptual-Computing-Lab/openpose

- 类别：C++

- 项目后续更新计划：一直在不断优化

- 项目描述：
  - 必写：openpose是基于卷积神经网络和监督学习的开源库，可以实现人的面部、躯干和四肢甚至手指的跟踪，适用于多人，同时具有较好的鲁棒性。

- 推荐理由：支持多人标记，且标记准确准确

- 示例代码：无

**Comment by xibinyue** [comment]
您推荐的项目已收录到专栏，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 37 期](https://hellogithub.com/periodical/volume/37/#openpose)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
