### ISSUE TITLE
a problem 

### ISSUE THREAD

**Issue by StephenWu5** [521xueweihan/HelloGitHub#517]
a problem 

why i unwatch your repos and unfollow you ,you still show in my feeds ???

![image](https://user-images.githubusercontent.com/32475322/55127212-5959d500-514a-11e9-9521-d37d9a9658c2.png)
![image](https://user-images.githubusercontent.com/32475322/55127221-65459700-514a-11e9-80a1-459a29e7e7fe.png)
the words in low picture is not right?

**Comment by 521xueweihan** [comment]
Your should [contact github](https://github.com/contact). I can't help you any more.

**Comment by StephenWu5** [comment]
i follow you now
