### ISSUE TITLE
零耦合接入Android-BLE蓝牙库

### ISSUE THREAD

**Issue by AICareless** [521xueweihan/HelloGitHub#518]
## 项目推荐
- 项目地址：https://github.com/Alex-Jerry/Android-BLE

- 类别：Java

- 项目后续更新计划：一直会持续不断的更新维护，增加更多有用的接口

- 项目描述：
  - 必写：AndroidBLE蓝牙框架，包括扫描、连接、设置通知、发送数据、读取、接收数据和OTA升级以及各种直观的回调，近乎一行代码植入项目，可扩展配置蓝牙相关操作。
  - 可选：适用于Android-BLE4.0蓝牙，几行代码就可以轻松接入到已有项目中，零耦合

- 推荐理由：几行代码就可以轻松接入到已有项目中，零耦合，即便是BLE方面的小白也可以在短短几分钟内接入并运用到项目中。

- 示例代码：Ble.options()
                .setLogBleExceptions(true)//设置是否输出打印蓝牙日志（非正式打包请设置为true，以便于调试）
                .setThrowBleException(true)//设置是否抛出蓝牙异常
                .setAutoConnect(true)//设置是否自动连接
                .setConnectFailedRetryCount(3)
                .setConnectTimeout(10 * 1000)//设置连接超时时长（默认10*1000 ms）
                .setScanPeriod(12 * 1000)//设置扫描时长（默认10*1000 ms）
                .setUuid_service(UUID.fromString("0000fee9-0000-1000-8000-00805f9b34fb"))//主服务的uuid
                .setUuid_write_cha(UUID.fromString("d44bc439-abfd-45a2-b575-925416129600"))//可写特征的uuid
                .create(getApplicationContext());

- 截图：https://camo.githubusercontent.com/acabc2214ca9c086ad896e6da3eb296b02b7100c/687474703a2f2f75706c6f61642d696d616765732e6a69616e7368752e696f2f75706c6f61645f696d616765732f333838343131372d343966303830616434346236303934362e6769663f696d6167654d6f6772322f6175746f2d6f7269656e742f7374726970

**Comment by CasualJi** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 38 期]https://hellogithub.com/periodical/volume/38/#Android-BLE)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
