### ISSUE TITLE
code server

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#519]
## 项目推荐
- 项目地址： https://github.com/codercom/code-server.git

- 类别：JS

- 项目后续更新计划：https://github.com/codercom/code-server#future

- 项目描述：
  在线使用VS Code编程。

- 推荐理由：
  微软出品，支持在任意终端使用浏览器进行在线编程。
 
- 示例代码：

```
docker run -t -p 127.0.0.1:8443:8443 -v "${PWD}:/root/project" codercom/code-server code-server --allow-http --no-auth
```

- 截图：https://github.com/codercom/code-server/raw/master/doc/assets/ide.png

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您好，经过我们讨论，此项目**暂不能收录**到 HG 月刊中
