### ISSUE TITLE
GetSub - 一步下载视频字幕

### ISSUE THREAD

**Issue by gyh1621** [521xueweihan/HelloGitHub#52]
## 项目推荐
- 项目：[GetSub](https://github.com/gyh1621/GetSubtitles)

- 项目语言：python

- 项目描述：通过拖曳视频文件进终端，一步下载字幕到视频对应文件夹，并重命名字幕名称为视频名称，提供查询模式手动选择要下载的字幕包，不然自动选择最佳匹配字幕包下载。
也可以拖曳包含多个视频的文件夹，会识别文件夹中的视频文件一一下载字幕。

- 推荐理由：整合下载字幕繁琐步骤，简单易用

- 截图：![自动模式](https://github.com/gyh1621/GetSubtitles/raw/master/pic/single.gif)

**Comment by 521xueweihan** [comment]
兄弟建议做一下 python2 的兼容

**Comment by gyh1621** [comment]
好的，不过我这几天期末复习，可能要到七月初改

**Comment by 521xueweihan** [comment]
嗯，7.28 之前开发完成就行，7月的那期就可以推荐你的这个项目。

本来这期就打算推荐的，后来发现这个这支持 python3，受众相对小一些。所以，就等你七月开发完了，再推荐 😁

**Comment by gyh1621** [comment]
好，改完了我在这里回复 😁

**Comment by 521xueweihan** [comment]
@gyh1621 赞 👍

**Comment by gyh1621** [comment]
做好了，拖了这么久 :sweat_smile:

**Comment by CHWJ** [comment]
Potplayer可以在线查找字幕哟，而且可以设置字幕源的😁。不过，用项目练练手也不错呢。

**Comment by gyh1621** [comment]
potplayer的在线搜索只有对osdb才有自动下载字幕包并且加载，而osdb里面中文字幕不多，特别是新出的美剧一块。
如果设置了字幕源，在potplayer里面进行搜索是打开一个浏览器定位到那个字幕网站去的，与自己开网页搜索没什么区别，我就是觉得开网页搜索下载有点繁琐才写了这个，而且我平时ubuntu用得比较多，懒得切回windows看视频 😄

**Comment by 521xueweihan** [comment]
@gyh1621 Nice，时间刚好

**Comment by crazynet999** [comment]
不发布一个windows文件版本吗?

**Comment by zhlmnet** [comment]
好用,我加到右键菜单了,非常爽
