### ISSUE TITLE
浙江大学课程资源

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#520]
## 项目推荐
- 项目地址： https://github.com/QSCTech/zju-icicles.git

- 类别：书籍

- 项目描述：
  浙江大学课程资源，不仅仅包括计算机学院。

- 推荐理由：

  除了课程资源，还有作业、答案、复习资料、选课攻略等等，浙大在校生的必备资源，对于有考研想法的学生而言也是很好的资源。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 37 期](https://hellogithub.com/periodical/volume/37/#zju-icicles)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
