### ISSUE TITLE
Hope-plus是一款权限管理系统。整合Springboot2，mybatis+shiro+redis+thymeleaf+maven+swagger等实用技术。🏷

### ISSUE THREAD

**Issue by java-aodeng** [521xueweihan/HelloGitHub#522]
## 项目推荐
- 项目地址：https://github.com/java-aodeng/hope-plus

- 类别：（Java）

- 项目后续更新计划：
 - [x] 整合 **RESTful APIs 构建成前后端分离项目**
- [x] 整合 **Swagger接口管理**
- [ ] 整合 **sso单点登录**
- [ ] 整合 **数据权限分离**
- [ ] 整合 **支付模块**
- [ ] 整合 **定时服务**
- [ ] 整合 **授权登录**
- [ ] 整合 **J2Cache缓存**
- [ ] 整合 **国际化I18N**
- [ ] 重构 **前端暂定Vue**
- [ ] 重构 **项目使用微服务架构**
- 项目描述：
  - 必写：Hope-plus是一款权限管理系统。
  - 可选：Hope-plus是我学习过程中诞生的，算我学习的结晶吧。主语言[java]
  - 描述长度（不包含示例代码）: 项目地址： https://github.com/java-aodeng/hope-plus

- 推荐理由：令人眼前一亮的点是整洁的代码

- 截图：
![](https://i.loli.net/2018/12/31/5c29cfa636b7a.png)
![](https://i.loli.net/2018/12/31/5c29cfe24ef3c.png)
![](https://i.loli.net/2018/12/31/5c29d0f3e7f89.png)
![](https://i.loli.net/2018/12/31/5c29d08c40128.png)
![](https://i.loli.net/2018/12/31/5c29d08c4b71f.png)
![](https://i.loli.net/2018/12/31/5c29d188d68fe.png)
![](https://i.loli.net/2018/12/31/5c29d188daba1.png)
![](https://i.loli.net/2018/12/31/5c29d1ce428a5.png)
![](https://i.loli.net/2018/12/31/5c29d1ce60893.png)
![](https://i.loli.net/2018/12/31/5c29d1ce68318.png)
![](https://i.loli.net/2018/12/31/5c29d1ce66275.png)
![](https://i.loli.net/2018/12/31/5c29d1ce86b5e.png)
![](https://i.loli.net/2019/03/17/5c8e0bd37267a.png)

再次感谢《HelloGitHub》项目的支持！

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
