### ISSUE TITLE
emoji-mineswepper - emoji 扫雷

### ISSUE THREAD

**Issue by ChungZH** [521xueweihan/HelloGitHub#523]
## 项目推荐
- 项目地址：
https://github.com/muan/emoji-minesweeper
- ### 类别：JS

- 项目后续更新计划：

- 项目描述：
这个项目是一个网页的使用 Emoji 符号的扫雷，代码很简短，寥寥三百多行代码。可以给初学者学习。

- 推荐理由：有趣 简单

- 截图：
![](https://cloud.githubusercontent.com/assets/1153134/7797311/19c09214-031d-11e5-99c3-2a380ac7984e.gif)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 37 期](https://hellogithub.com/periodical/volume/37/#emoji-minesweeper)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
