### ISSUE TITLE
基于dive的docker镜像分析工具

### ISSUE THREAD

**Issue by vicanso** [521xueweihan/HelloGitHub#524]
## 自荐项目
- 项目地址：https://github.com/vicanso/diving

- 类别：go

- 项目后续更新计划：无

- 项目描述：
  - 基于[dive](https://github.com/wagoodman/dive)分析docker镜像，界面化展示了镜像每层的变动（增加、修改、删除等），镜像得分，用户层数据大小等信息。便捷获取镜像信息，每层镜像内容的文件树，对于需要优化镜像体积时非常方便。

- 推荐理由：提供便捷的方式确认docker镜像尺寸的精简思路，简单易用的镜像信息浏览

![Image](https://raw.githubusercontent.com/vicanso/diving/master/.data/demo.gif)

**Comment by FrontMage** [comment]
已收录至38期

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 38 期](https://hellogithub.com/periodical/volume/38/#diving)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
