### ISSUE TITLE
俄罗斯方块

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#526]
## 项目推荐
- 项目地址： https://github.com/taylorconor/tinytetris.git

- 类别：C++

- 项目描述：
用C++编写的终端版俄罗斯方块。

- 推荐理由：

提供了两个版本的源码，注释较多，易于理解。

- 截图：
![截图](https://github.com/taylorconor/tinytetris/blob/master/animation.gif)

**Comment by ChungZH** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 37 期](https://hellogithub.com/periodical/volume/37/#tinytetris)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
