### ISSUE TITLE
zhui - 一款带有中国风的React组件库

### ISSUE THREAD

**Issue by ChungZH** [521xueweihan/HelloGitHub#527]
## 项目推荐
- 项目地址：
https://github.com/zhui-team/zhui
- 类别：JS

- 项目后续更新计划：

- 项目描述：
一款带有中国风的React组件库

- 推荐理由：
中国风的组件库，非常独特。

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）
![](https://camo.githubusercontent.com/33d23e9b7019920e87e257f62dad80bb05f2defb/68747470733a2f2f73322e617831782e636f6d2f323031392f30322f31322f6b647a6271412e6d642e706e67)

**Comment by 521xueweihan** [comment]
@ChungZH 根据语言，增加labels

**Comment by ChungZH** [comment]
> @ChungZH 根据语言，增加labels

蛤？我似乎还不能加 label :joy:

**Comment by 521xueweihan** [comment]
> > @ChungZH 根据语言，增加labels
> 
> 蛤？我似乎还不能加 label 😂

https://github.com/521xueweihan/HelloGitHub/invitations

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 37 期](https://hellogithub.com/periodical/volume/37/#zhui)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
