### ISSUE TITLE
Markdown 简体中文与西文混排要点

### ISSUE THREAD

**Issue by ChungZH** [521xueweihan/HelloGitHub#528]
## 项目推荐
- 项目地址：
https://github.com/selfteaching/markdown-writing-with-mixed-cn-en
- 类别：书籍

- 项目后续更新计划：

- 项目描述：
Markdown 简体中文与西文混排要点

- 推荐理由：
写的很具体、全面且专业，值得学习。

- 示例代码：

- 截图：

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
