### ISSUE TITLE
JS开源书籍 - ECMAScript 6 入门

### ISSUE THREAD

**Issue by kelekexiao123** [521xueweihan/HelloGitHub#53]
## 项目推荐
- 项目：[项目名称](项目地址)  http://es6.ruanyifeng.com/

- 项目语言： JavaScript

- 项目描述：开源书籍推荐

- 推荐理由：阮一峰老师的开源精品，es6入门书籍

- 示例代码：https://github.com/ruanyf/es6tutorial

- `截图： 实在是非常懒，网页地址都给了，想学es6的话一定会喜欢的。

**Comment by 521xueweihan** [comment]
您推荐的项目已收录到 [15 期](https://github.com/521xueweihan/HelloGitHub/blob/master/content/15/HelloGitHub15.md#开源书籍)，同时您已加入到 [贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/contributors.md) 中。

期待老铁后面继续推荐给力的项目 💪
