### ISSUE TITLE
Windows 远程桌面管理工具

### ISSUE THREAD

**Issue by xunki** [521xueweihan/HelloGitHub#530]
## 项目推荐
- 项目地址：[https://github.com/xunki/RemoteDesktopManage](https://github.com/xunki/RemoteDesktopManage)

- 类别：C#

- 项目后续更新计划：
   - 增加自动更新逻辑 
      `不需要每次都来 github 下载最新版本`
   - 将存储库从 SQLite 调整为 LiteDB
      `版本更新时，可能会修改对象结构，还需要记录SQL升级表结构，通过 NoSQL 来实现就没这么多麻烦，很多新功能只需加默认值即可`
   - 通过 dotnet core 3.0 重构界面
      `希望借助 dotnet core 可以实现独立程序，不需要安装 nfx nfc 即可运行`

- 项目描述：基于 MSTSC 连接 Windows 远程桌面，并对其进行封装实现管理多个远程桌面配置的小工具

- 推荐理由：更方便的管理多个远程桌面，并同时远程，互相切换，相当于把多个 MSTSC 集合在一个软件里，并进行分组打标试

![主界面](https://raw.githubusercontent.com/xunki/RemoteDesktopManage/master/Images/%E6%95%88%E6%9E%9C-%E4%B8%BB%E7%95%8C%E9%9D%A2.png)

![进行远程](https://raw.githubusercontent.com/xunki/RemoteDesktopManage/master/Images/%E6%95%88%E6%9E%9C-%E6%89%93%E5%BC%80%E8%BF%9C%E7%A8%8B%E8%BF%9E%E6%8E%A5.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 37 期](https://hellogithub.com/periodical/volume/37/#RemoteDesktopManage)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
