### ISSUE TITLE
Emoji Mosaic

### ISSUE THREAD

**Issue by NeilKleistGao** [521xueweihan/HelloGitHub#531]
## 项目推荐
- 项目地址：https://github.com/ericandrewlewis/emoji-mosaic

- 类别： JS

- 项目描述：将图片转换为emoji拼接的马赛克图片

- 推荐理由：项目有趣，且相对简单

- 截图：
![微信截图_20190403202735](https://user-images.githubusercontent.com/25132828/55478732-f89d3180-564e-11e9-8cf8-05ffa53e908d.png)

**Comment by ming995** [comment]
密集恐惧症表示不想看到这个项目🤣

**Comment by 521xueweihan** [comment]
这个项目让没有密集恐惧症的我，都感觉到了恐惧。

**Comment by ming995** [comment]
@521xueweihan 老外时间是真的多🤣
