### ISSUE TITLE
蚂蚁金服开放的分布式事务解决方案

### ISSUE THREAD

**Issue by nivance** [521xueweihan/HelloGitHub#532]
## 项目推荐
- 项目地址：https://github.com/seata/seata

- 类别：Java

- 项目后续更新计划：
![640](https://user-images.githubusercontent.com/3291404/55599396-28048900-578a-11e9-9cd3-7756d23db8c0.jpg)

- 项目描述：
  - 必写：Simple Extensible Autonomous Transaction Architecture，一套一站式分布式事务解决方案。让分布式事务的使用像本地事务的使用一样，简单和高效，并逐步解决开发者们遇到的分布式事务方面的所有难题。

- 推荐理由：分布式事务提出了很多年，但是一直没有很好的解决方案，要不就收费很贵。蚂蚁金服开放的seata，将让分布式事务不在束之高阁，任何需要的人都可以使用它。

**Comment by CasualJi** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 37 期](https://hellogithub.com/periodical/volume/37/#seata)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
