### ISSUE TITLE
神经网络与深度学习

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#538]
## 项目推荐
- 项目地址： https://github.com/nndl/nndl.github.io.git

- 类别：机器学习

- 项目描述：
  神经网络与深度学习，446页内容。

- 推荐理由：有示例代码和课程练习，方便自学者入门。复旦大学教授编写，质量保证，从基础到研究前沿介绍了深度学习的核心概念与理论。

**Comment by Eurus-Holmes** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
该项目已经收录过：https://hellogithub.com/periodical/search/?q=https://github.com/nndl/nndl.github.io#nndl
