### ISSUE TITLE
从头学习Spring

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#539]
## 项目推荐
- 项目地址：https://github.com/wuyouzhuguli/SpringAll.git

- 类别：Java

- 项目描述：
  https://mrbird.cc中Spring系列源码，包含Spring Boot、Spring Boot & Shiro、Spring Cloud和Spring Boot & Spring Security

- 推荐理由：

Spring是JAVA目前生命力最强的框架之一，通过资料与源码的配合，容易上手，

**Comment by CasualJi** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by CasualJi** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by CasualJi** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 37 期](https://hellogithub.com/periodical/volume/37/#SpringAll)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
