### ISSUE TITLE
北京大学课程资料

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#540]
## 项目推荐
- 项目地址：https://github.com/lib-pku/libpku.git

- 类别：其它

- 项目描述：
  北京大学课程资料整理。

- 推荐理由：
  传说中的北大，教的课程究竟是什么内容呢？让我们一探究竟吧。

**Comment by 521xueweihan** [comment]
相同类型太多了，就不收录北大的课程资料了 ✌️
