### ISSUE TITLE
清华大学计算机系课程

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#541]
## 项目推荐
- 项目地址：https://github.com/PKUanonym/REKCARC-TSC-UHT.git

- 类别：其它

- 项目描述：
  清华大学计算机课程整理。

- 推荐理由：
  从大一到大四，内容丰富，跟着清华学子一起学习传说中高校的课程吧。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 37 期](https://hellogithub.com/periodical/volume/37/#REKCARC-TSC-UHT)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
