### ISSUE TITLE
Awesome love

### ISSUE THREAD

**Issue by glazec** [521xueweihan/HelloGitHub#542]
## 项目推荐
- 项目地址：https://github.com/glazec/awesome-love

- 类别：其它

- 项目后续更新计划：添加更多有意思的项目，并制作更新公告。

- 项目描述：
这是一个收录了与恋爱有关的程序，网站和故事的repo。在这程序员更加容易找到，符合他们口味的表达情感的工具。
 
这是一个文档类项目，有着清晰的贡献文档，并且支持多语言。贡献的门槛很低，储蓄者可以分享一个故事，也可以提交一个自己写的项目。由于与恋爱有关的项目不多，因此只要有一个好点子，就可以在这个竞争不激烈的领域写出一个好项目。难度并不大。

- 推荐理由：各种awesome项目都有，唯独没有awesome-love。这是一个文档类项目中，贡献难度最低的项目。初学者得到的反馈MAX。
![image](https://user-images.githubusercontent.com/22890026/55907560-f3c70900-5b8b-11e9-8cab-06e034415602.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
