### ISSUE TITLE
腾讯优图人脸检测算法DSFD

### ISSUE THREAD

**Issue by nivance** [521xueweihan/HelloGitHub#543]
## 项目推荐
- 项目地址：https://github.com/TencentYoutuResearch/FaceDetection-DSFD

- 类别：Python

- 项目后续更新计划：暂无

- 项目描述：
  - 必写：腾讯优图的双分支人脸检测器全新算法。优图此次提出的DSFD人脸检测算法，主要有3点创新：
    - 新的特征增强模块（FEM：Feature Enhance Module）
    - 分层锚点渐进式的代价函数监督（PLA：Progressive Anchor Loss）
    - 改进的锚点匹配策略（Improved Anchor Matching Strategy）

- 推荐理由：据悉，该算法已经被计算机视觉顶级会议CVPR 2019接收，刷新了两个权威的人脸检测数据集WIDER FACE和FDDB上的新纪录。

- 示例代码：无

- 截图：
![](https://github.com/TencentYoutuResearch/FaceDetection-DSFD/raw/master/imgs/DSFD_demo1.PNG)

**Comment by xibinyue** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 37 期](https://hellogithub.com/periodical/volume/37/#FaceDetection-DSFD)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
