### ISSUE TITLE
JavaScript 算法与数据结构

### ISSUE THREAD

**Issue by zzugbb** [521xueweihan/HelloGitHub#544]
## 项目推荐
- 项目地址：https://github.com/trekhleb/javascript-algorithms

- 类别：JS

- 项目描述：
   多种基于 JavaScript 的算法与数据结构, 包含相关说明和链接，以便进一步阅读 (还有 YouTube 视频， 有各种语言版本。学习基于 JavaScript 的算法与数据结构的材料。

- 推荐理由：学习 JavaScript 的算法与数据结构，包括数据结构，算法（数学，集合，字符串，搜索，排序，链表，树，图，加密等等），算法范式（贪心法，分治法，动态编程，回溯等）等模块。

**Comment by ming995** [comment]
@zzugbb 由于本期篇幅限制，项目收录到下期推荐，感谢关注HelloGithub

**Comment by 521xueweihan** [comment]
已推荐过：https://hellogithub.com/periodical/search/?q=https://github.com/trekhleb/javascript-algorithms
