### ISSUE TITLE
Jpom一款简而轻的低侵入式Java运维、监控软件

### ISSUE THREAD

**Issue by jiangzeyin** [521xueweihan/HelloGitHub#547]
## 项目推荐
- 项目地址：
https://github.com/jiangzeyin/Jpom

- 类别：Java

- 项目后续更新计划：

  1. 主要管理页面兼容移动端
   2. ssl 到期提醒、快捷续签
   3. 多机统一管理
   4. 程序宕机处理

- 项目描述：

#### 你为什么需要[Jpom](https://gitee.com/keepbx/Jpom)

> SpringBoot、Jboot等框架开发的项目通常是以Jar的方式在后台运行的，如果只有一两个项目，管理起来不是太麻烦，但是当项目多了以后，管理起来就不是那么方便了，当项目出现问题时，能够通过Jpom即时排查问题，问题解决后还可以直接上传修改后的Jar，项目的堆栈信息，服务器CPU、内存使用情况一目了然，不必再登录服务器管理。

> 当多个项目运行在同一台服务器时，运维人员通常也不只一个，如果每个人都登录服务器管理项目，难免会造成一些不必要的麻烦，甚至给服务器的安全性带来问题（服务器密码知道的人越多，越容易泄露），因为不需要登录服务器管理项目，维护人员不需要知道服务器的登录密码，只需要有Jpom的账号就行，Jpom本身可以通过权限管理，给不同用户不同的权限，这样也使得项目的稳定性得到提升。

> Jpom可以在Linux和Windows服务器上运行

### Jpom 目标

> 一款简而轻的低侵入式Java运维、监控软件

#### 项目主要功能及特点

1. 创建、修改、删除项目、Jar包管理
2. 实时查看控制台日志、备份日志、删除日志、导出日志
3. cpu、ram 监控、导出堆栈信息、查看项目进程端口、服务器状态监控
4. 多用户管理，用户项目权限独立(上传、删除权限可控制)
5. 系统路径白名单模式，杜绝用户误操作系统文件
6. 在线管理Nginx配置、ssl证书文件
7. Jpom完全不依赖数据库，随装随用
8. 阿里云 CodePipeline + Oss在线管理

- 推荐理由：
当多个项目运行在同一台服务器时，运维人员通常也不只一个，如果每个人都登录服务器管理项目，难免会造成一些不必要的麻烦，甚至给服务器的安全性带来问题（服务器密码知道的人越多，越容易泄露），因为不需要登录服务器管理项目，维护人员不需要知道服务器的登录密码，只需要有Jpom的账号就行，Jpom本身可以通过权限管理，给不同用户不同的权限，这样也使得项目的稳定性得到提升。

- 截图：http://s.keepbx.cn/jpom-demo-gif.gif

<img src="http://s.keepbx.cn/jpom-demo-gif.gif" ></img>

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
