### ISSUE TITLE
小程序首页展示授权

### ISSUE THREAD

**Issue by ZhuPeng** [521xueweihan/HelloGitHub#549]
开发了一个可以查看 GitHub Trending 的小程序 [https://github.com/ZhuPeng/mp-githubtrending](https://github.com/ZhuPeng/mp-githubtrending)

想在首页（轮播图）展示你更新的内容，希望获得你的授权，不知道是否可以？

**Comment by 521xueweihan** [comment]
@ZhuPeng 可以，感谢您的推荐和支持。

**Comment by ZhuPeng** [comment]
感谢，已经更新到小程序了，有空可以看看效果。

**Comment by 521xueweihan** [comment]
@ZhuPeng 好的，刚才已经看到了效果，没问题。轮播的封面图好像有些拉伸 ，如果需要我们提供指定规格的封面图，可以告知我尺寸。
