### ISSUE TITLE
系统设计入门

### ISSUE THREAD

**Issue by nivance** [521xueweihan/HelloGitHub#550]
## 项目推荐
- 项目地址：https://github.com/donnemartin/system-design-primer

- 类别：其它

- 项目后续更新计划：无

- 项目描述：
  - 必写：系统设计入门指南及系统设计的相关面试准备，还有Anki卡

- 推荐理由：系统设计方面的知识非常完善，学习系统设计不错的资料

- 示例代码：无

- 截图：
![](https://camo.githubusercontent.com/e45e39c36eebcc4c66e1aecd4e4145112d8e88e3/687474703a2f2f692e696d6775722e636f6d2f6a6a3341354e382e706e67)

**Comment by 521xueweihan** [comment]
@nivance 该项目已经推荐过：https://hellogithub.com/periodical/search/?q=https://github.com/donnemartin/system-design-primer#system-design-primer

可以通过：https://hellogithub.com/ 输入项目地址进行差重
