### ISSUE TITLE
了解Google工具栈

### ISSUE THREAD

**Issue by nivance** [521xueweihan/HelloGitHub#551]
## 项目推荐
- 项目地址：https://github.com/jhuangtw-dev/xg2xg

- 类别：其它

- 项目后续更新计划：未知

- 项目描述：
  - 必写：Google一名前员工分享的在 Google 工作时日常使用的工具列表，并详细列出了这些工具列表的外界对应的替代方案。

- 推荐理由：对了解google是一个不错的途径

- 示例代码：无

- 截图：无

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
