### ISSUE TITLE
阿里巴巴JAVA编码规范和相关IDE插件

### ISSUE THREAD

**Issue by nivance** [521xueweihan/HelloGitHub#554]
## 项目推荐
- 项目地址：https://github.com/alibaba/p3c

- 类别：书籍

- 项目后续更新计划：暂无

- 项目描述：
  - 必写：阿里巴巴JAVA编码规范和相关IDE插件

- 推荐理由：阿里巴巴JAVA编码规范差不多成了业界规范，最牛鼻的是将规范做了IDE插件

**Comment by 521xueweihan** [comment]
@nivance 该项目已经推荐过：https://hellogithub.com/periodical/search/?q=https://github.com/alibaba/p3c#p3c
