### ISSUE TITLE
计算机专业论文阅读笔记

### ISSUE THREAD

**Issue by nivance** [521xueweihan/HelloGitHub#556]
## 项目推荐
- 项目地址：https://github.com/dyweb/papers-notebook

- 类别：其它

- 项目后续更新计划：持续在更新

- 项目描述：
  - 必写：论文阅读笔记（分布式，虚拟化，容器，自动机器学习等）

- 推荐理由：可以作为学习计算机部分专业的论文入口

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 39 期](https://hellogithub.com/periodical/volume/39/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
