### ISSUE TITLE
智能画笔(语义图像合成)

### ISSUE THREAD

**Issue by nivance** [521xueweihan/HelloGitHub#557]
## 项目推荐
- 项目地址：https://github.com/NVlabs/SPADE

- 类别：Python

- 项目后续更新计划：未知

- 项目描述：
  - 必写：英伟达(NVIDIA)新开源的工具，利用生成对抗网络，根据几根简单的线条就能生成栩栩如生的图像

- 推荐理由：绘图从此会变得更加简单

- 截图：
![](https://camo.githubusercontent.com/a295a79daea9d1dd0cb16b48055607d0f17258b2/68747470733a2f2f6e766c6162732e6769746875622e696f2f53504144452f2f696d616765732f6f6365616e2e676966)

**Comment by xibinyue** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 37 期](https://hellogithub.com/periodical/volume/37/#SPADE)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
