### ISSUE TITLE
网络对战坦克小游戏

### ISSUE THREAD

**Issue by liuyj24** [521xueweihan/HelloGitHub#558]
## 项目推荐
- 项目地址：https://github.com/liuyj24/TankOnline

- 类别：Java

- 项目后续更新计划：客户端登陆时能够选择坦克名字, 会尝试制作聊天模块

- 项目描述：
- 本项目可用于巩固JavaSE基础知识, 学习面向对象思想, 封装, 继承, 多态等. 
- 能让初学者掌握简单的客户端与服务器通信模型, 自定义简单的应用层协议以供游戏中的数据交互.

<html>
    <img width="50%" src="https://www.cnblogs.com/images/cnblogs_com/tanshaoshenghao/1426602/o_tankFight.gif"/>
</html>

**Comment by CasualJi** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
