### ISSUE TITLE
HitUP - Find top things in New Tab

### ISSUE THREAD

**Issue by wonderbeyond** [521xueweihan/HelloGitHub#559]
[HitUP](https://chrome.google.com/webstore/detail/hitup/eiokaohkigpbonodjcbjpecbnccijkjb) 是一款 Chrome 浏览器扩展，利用 New Tab “空白页” 助您保持对流行技术趋势的跟进，附带其它福利。

HitUP 会替换掉浏览器默认的 New Tab “空白”页面，展示 GitHub 上近期最流行的项目 (Trending Repositories)，助您时刻跟踪热门趋势。欢迎安装体验！

- 下载地址：https://chrome.google.com/webstore/detail/hitup/eiokaohkigpbonodjcbjpecbnccijkjb
- 项目地址：https://github.com/wonderbeyond/HitUP

### 核心特性

- 提供 Grid/List 两种视图为您呈现 GitHub 趋势榜单
- 支持[黑夜主题](https://www.v2ex.com/t/556887)
- [随机展示我精心整理的一句话技巧](https://www.v2ex.com/t/550206)
- 同步用户偏好设置（语言、观察时间、视图、主题等）

### 项目后续更新计划

可能会提供展示全网 Top-n 资讯、最球 Top-n 网站的小部件。

### 截图

<p align="center">
  <img alt="HitUP" src="https://raw.githubusercontent.com/wonderbeyond/HitUP/master/screenshots/dark-theme-trending-repo-grid.png">
  <br><b>▲ Awesome! HitUP have Dark Theme now 🎉 🎉 🎉</b><br>
</p>

<p align="center">
  <img alt="HitUP" src="https://raw.githubusercontent.com/wonderbeyond/HitUP/master/screenshots/trending-repo-grid.png">
  <br><b>▲ Trending Repositories This Week – Grid View</b><br>
</p>

<p align="center">
  <img alt="HitUP" src="https://raw.githubusercontent.com/wonderbeyond/HitUP/master/screenshots/trending-repo-list.png">
  <br><b>▲ Trending Repositories This Week – List View</b><br>
</p>

<p align="center">
  <img alt="HitUP" src="https://raw.githubusercontent.com/wonderbeyond/HitUP/master/screenshots/filter-by-lang.png">
  <br><b>▲ Filter by Language</b><br>
</p>

**Comment by 521xueweihan** [comment]
@wonderbeyond 请按照推荐模版填写，重新提交。
