### ISSUE TITLE
Wlitsoft 框架 - 公共组件

### ISSUE THREAD

**Issue by Wlitsoft** [521xueweihan/HelloGitHub#56]
## 项目推荐
- 项目名称：Wlitsoft 框架 - 公共组件

- 项目地址：https://github.com/Wlitsoft/Common

- 项目语言：C#

- 项目描述：
   ​    该项目是一个开发中经常使用的功能类库，封装了对象序列化反序列化、网络请求、参数加密、日志、缓存接口、以及常用的字符串操作等。

**Comment by 521xueweihan** [comment]
@Wlitsoft 您好，该项目可能暂时无法推荐，期待扩展更多功能、优化文档后，再次推荐。
