### ISSUE TITLE
HitUP - 助您发现优质内容的 Chrome 扩展

### ISSUE THREAD

**Issue by wonderbeyond** [521xueweihan/HelloGitHub#560]
## 项目推荐
- 项目地址：
GitHub 仓库：[https://github.com/wonderbeyond/HitUP](https://github.com/wonderbeyond/HitUP?ref=GitHub.521xueweihan.HelloGitHub.iss560)
Chrome 扩展：[https://chrome.google.com/webstore/detail/hitup/eiokaohkigpbonodjcbjpecbnccijkjb](https://chrome.google.com/webstore/detail/hitup/eiokaohkigpbonodjcbjpecbnccijkjb?ref=GitHub.521xueweihan.HelloGitHub.iss560)
在线版地址：[https://hitup.wondertools.top](https://hitup.wondertools.top?ref=GitHub.521xueweihan.HelloGitHub.iss560)

- 类别：JavaScript, Chrome 扩展

- 项目后续更新计划：
    * GitHub 项目排行榜提供额外的维度，比如历史总榜
    * 围绕 “Find top things” 的主题，添加全网 Top-N 资讯/话题、Top-N 站点的小部件

- 项目描述：HitUP 是一款 Chrome 扩展，它会替换掉浏览器默认的 New Tab “空白”页面，助您保持对流行技术趋势的跟进，核心功能是展示 GitHub 上近期最流行的项目 (Trending Repositories)，并会围绕 “Find top things” 的主题谨慎添加新特性。
HitUP 适合 IT 业界人士（程序员、设计师、产品经理）拓展视野、发现精彩，欢迎安装体验！

- 推荐理由：不用刻意跟踪，绝不错过热门技术趋势，HitUP 利用夹缝时间带给你精彩

- 截图：
<p align="center">
  <img alt="HitUP" src="https://raw.githubusercontent.com/wonderbeyond/HitUP/master/screenshots/dark-theme-trending-repo-grid.png">
  <br><b>▲ Awesome! HitUP have Dark Theme now 🎉 🎉 🎉</b><br>
</p>

<p align="center">
  <img alt="HitUP" src="https://raw.githubusercontent.com/wonderbeyond/HitUP/master/screenshots/trending-repo-grid.png">
  <br><b>▲ Trending Repositories This Week – Grid View</b><br>
</p>

<p align="center">
  <img alt="HitUP" src="https://raw.githubusercontent.com/wonderbeyond/HitUP/master/screenshots/trending-repo-list.png">
  <br><b>▲ Trending Repositories This Week – List View</b><br>
</p>

<p align="center">
  <img alt="HitUP" src="https://raw.githubusercontent.com/wonderbeyond/HitUP/master/screenshots/filter-by-lang.png">
  <br><b>▲ Filter by Language</b><br>
</p>

**Comment by 521xueweihan** [comment]
@wonderbeyond 你好，请问和上游项目：https://github.com/kamranahmedse/githunt，有什么改进或者区别？

**Comment by wonderbeyond** [comment]
> @wonderbeyond 你好，请问和上游项目：https://github.com/kamranahmedse/githunt ，有什么改进或者区别？

很好的问题。

[HitUP](https://github.com/wonderbeyond/HitUP) 始于对 [kamranahmedse/githunt](https://github.com/kamranahmedse/githunt) 的 Fork, 我在项目 README 和 Chrome web store 页面都有提到。

我曾在官方的 [GitHub Trending](https://github.com/trending/) 栏目中多次发现让我感到惊艳（并可能受用终生）的项目，些许遗憾的是我并没有养成经常逛 Trending 的习惯。后来我发现了 [GitHunt](https://github.com/kamranahmedse/githunt) 这个项目，它提供一款 Chrome 扩展，宣称会把默认的 New Tab 页面替换成 “a list of trending repositories on github”，我觉得这正是我一直想要的，我终于能够时刻保持对流行技术趋势的跟进了！

我使用了很长一段时间的 GitHunt, 但遗憾的是我发现榜单中的项目总是很平凡，鲜有项目能引起我的兴趣。然后我把它和 [GitHub 官方的 Trending](https://github.com/trending/) 做了对比，才发现两者的数据筛选根本不是一个视角：

* GitHub Trending 能够提供所有项目中最近一天（周/月）的受关注度排行榜，可选择不同技术语言
* GitHunt 也提供 Daily/Weekly/Monthly 的筛选方式，单其含义实际是 “今天（本周/本月）新创建的项目的受手关注度排名”

以我的理解，GitHunt 这种筛选方式并不能算作 “Trending”，好的项目往往都不是最近创建的，我感觉单纯关注热门**新**项目意义不是特别大，或者说不是最重要的。

然后我开始探索是否能够在这个扩展中展示真正的 “Trending Repositories”, 后来发现不是很方便，因为 GitHub 并没有提供相关 API，你要么在前端抓取 HTML 页面解析，要么架后台提供三方 API. 后来我找到了已有的[三方 Trending API 项目](https://github.com/huchenme/github-trending-api)（后来我还陆续贡献了一些代码），准备开始改造这个扩展了。

**为什么不把改造反馈到上游的 GitHunt 而是新建一个 HitUP 项目？**

因为我觉得这种数据逻辑的改造已经改变了原项目的含义，而且引入了三方 API，同时也修改了大量源文件（可以参见我的历史提交）。可以认为上游项目最终发挥了脚手架的作用，还有基础样式的复用。

同时，我也萌生了很多其它有关 “Find top things” 的 ideas, 部分 idea 已经实现了，比如随机展示我精心整理的一句话技巧：
![image](https://user-images.githubusercontent.com/228361/56843291-3e0cf180-68d1-11e9-89e2-ae5c8728935a.png)

总之，由于核心数据逻辑变更、整体改动过多以及很多已经实现的和即将实现的个人规划的原因，我决定单独发展 HitUP 项目。

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 39 期](https://hellogithub.com/periodical/volume/39/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

为了让开源项目的发起者不再孤单，我们决定牵线搭桥。可以加我微信：xueweihan（备注您发起的项目链接）
待时机成熟，你会发现你并不孤独！
