### ISSUE TITLE
推荐Bento ML

### ISSUE THREAD

**Issue by yubozhao** [521xueweihan/HelloGitHub#561]
## 项目推荐
- 项目地址：github.com/bentoml/bentoml

- 类别 Python, 机器学习

- 项目描述：
  - 必写：BentoML是一个机器学习工具用来打包和发布模型
  - 描述长度: BentoML帮助数据科学家用不到5分钟把在ipython notebook里的模型发布到生产环境

**Comment by Eurus-Holmes** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 38 期](https://hellogithub.com/periodical/volume/38/#bentoml)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
