### ISSUE TITLE
快速实现pcm、wav、mp3音频的录制及音频可视化

### ISSUE THREAD

**Issue by zhaolewei** [521xueweihan/HelloGitHub#562]
## 项目推荐
- 项目地址：
https://github.com/zhaolewei/ZlwAudioRecorder
实现pcm、wav、mp3音频的录制
- 类别：Java
- 项目后续更新计划：
    将支持更多的音频格式
- 项目描述：
  1. 快速实现pcm、wav、mp3音频的录制
  2. 实现了录音音频的可视化
  
- 推荐理由：
  使录音工作更加简单、快速

- 截图：https://raw.githubusercontent.com/zhaolewei/ZlwAudioRecorder/master/doc/demo.jpg

**Comment by CasualJi** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
