### ISSUE TITLE
推荐《PHP面试问答》

### ISSUE THREAD

**Issue by colinlet** [521xueweihan/HelloGitHub#563]
## 项目推荐
- 项目地址：https://github.com/colinlet/PHP-Interview-QA

- 类别：PHP

- 项目后续更新计划：持续更新中

- 项目描述：
  - 必写：结合实际 PHP 面试，系统的汇总面试中的各种各样的问题，尝试提供简洁准确的答案
  - 可选：PHP 面试求职必备
  - 描述长度（不包含示例代码）: 包含网络协议、数据结构与算法、PHP、Web、MySQL、Redis、Linux、安全、设计模式、架构、自我介绍、离职原因、职业规划、准备问题等部分

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 38 期](https://hellogithub.com/periodical/volume/38/#PHP-Interview-QA)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
