### ISSUE TITLE
Learning to Paint

### ISSUE THREAD

**Issue by hzwer** [521xueweihan/HelloGitHub#564]
## 项目推荐
- 项目地址：https://github.com/hzwer/LearningToPaint

- 类别：机器学习

- 项目后续更新计划：结合风格迁移或生成模型，不仅仅局限于临摹

- 项目描述：
  - 必写：一个深度强化学习项目，研究如何让机器用画笔画画
  - 可选：体验，制作自己的绘画
  - 描述长度（不包含示例代码）:  可以根据一张图片生成一整个绘画过程

- 推荐理由：在线运行，看起来效果挺好

- 截图：https://github.com/hzwer/LearningToPaint/blob/master/demo/lisa.gif

**Comment by xibinyue** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by Eurus-Holmes** [comment]
@hzwer hhh我好像在知乎上看到过你～

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 37 期](https://hellogithub.com/periodical/volume/37/#LearningToPaint)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
