### ISSUE TITLE
自荐项目 - Practice

### ISSUE THREAD

**Issue by mintsweet** [521xueweihan/HelloGitHub#567]
## 项目推荐
- 项目地址：https://github.com/mintsweet/practice
- 文档地址：https://docs.mintsweet.cn/#/

- 类别：JavaScript

- 项目后续更新计划：

  * 完善基于React的PC管理版
  * 完善基于Vue的移动客户端
  * 完善文档内容

- 项目描述：
  - 必写：这是一个引用多种JS技术实现在不同终端上的论坛网站，包括(Node, Koa, Express, Pug, React, Vue, Antd, Vant 等等等等)
  - 可选：对于初学者是友好的完整项目流程，从前到后的完整开发体验

- 推荐理由：初学者开发的入门，从前端到后端的一整套流程

**Comment by ming995** [comment]
@mintsweet 由于本期篇幅限制，项目收录到下期推荐，感谢关注HelloGithub

**Comment by mintsweet** [comment]
@ming995 好的，谢谢～

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 38 期](https://hellogithub.com/periodical/volume/38/#practice)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
