### ISSUE TITLE
Wlitsoft - WebCast - 基于 Maven 构建的 Java 示例

### ISSUE THREAD

**Issue by Wlitsoft** [521xueweihan/HelloGitHub#57]
## 项目推荐
- 项目名称：Wlitsoft - WebCast - 基于 Maven 构建的 Java 示例

- 项目地址：https://github.com/Wlitsoft/WebCast-Maven-JavaDemo

- 项目语言：Java

- 项目描述：
   基于 Maven 构建的 Java 示例，从最基础的 Spring 依赖注入开始，到 Spring MVC、Spring AOP、Spring Task、MyBatis 等 正在持续构建中。

**Comment by 521xueweihan** [comment]
@Wlitsoft 已有类似项目推荐：#48
