### ISSUE TITLE
开源项目 - Vim Bootstrap : 简单易用的 .vimrc 配置生成器

### ISSUE THREAD

**Issue by NamelessAshone** [521xueweihan/HelloGitHub#570]
## 项目推荐
- 项目地址：https://github.com/avelino/vim-bootstrap

- 类别：工具

- 项目后续更新计划：持续更新中

- 项目描述：Vim Bootstrap 是一个简单易用的 .vimrc 配置文件生成网站, 支持vim, NeoVim, NeoVim-Qt, MacVim 和 GVim.
  网站地址 https://vim-bootstrap.com/

- 推荐理由：
    1.  轻量:  包含少且必要的插件(相比spf13, SpaceVim更加轻量)
    2.  易用:  适合在vim中成功存活的入门者. 
    2.  易于定制: 只需选择使用的语言,即可获得对应配置.
    3.  先进的插件管理器: 使用 Vim-Plug 管理插件, 简单易用, 速度超快, 业界流行.
    4.  支持多种编程语言.

- 截图：
![Screenshot from 2019-04-24 23-17-14](https://user-images.githubusercontent.com/26870409/56671410-2d008c80-66e7-11e9-8fa5-1d07defa0f99.png)
![Screenshot from 2019-04-24 23-15-29](https://user-images.githubusercontent.com/26870409/56671304-fb87c100-66e6-11e9-91f7-8e6c710d2c83.png)

**Comment by 521xueweihan** [comment]
@NamelessAshone 您好，首先您推荐的项目对于 vim 新手特别友好，而且推荐语通俗易懂，到位、突出特点。期待后续继续推荐项目。再次感谢

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 38 期](https://hellogithub.com/periodical/volume/38/#vim-bootstrap)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
