### ISSUE TITLE
开源项目 - Vim Awesome : 搜罗宇宙中牛逼的vim插件

### ISSUE THREAD

**Issue by NamelessAshone** [521xueweihan/HelloGitHub#571]
## 项目推荐
- 项目地址：https://github.com/vim-awesome/vim-awesome

- 类别：工具

- 项目后续更新计划：持续更新中

- 项目描述：
Vim Awesome希望成为一个全面，准确，最新的Vim插件目录。
最近的许多Vim插件都公布在Hacker News或专门的主板上, 而且愈发如此。但是新用户如何找到这些？我们希望用Vim Awesome解决这个问题和其他问题 - 这是一个用于发现新的和流行的Vim插件的开源社区资源。
网站地址 https://vimawesome.com/

- 推荐理由：
    1. vim版插件商店, 方便查找
    2. 支持所有目前流行的vim插件管理器

- 截图：
![Screenshot from 2019-04-25 00-21-30](https://user-images.githubusercontent.com/26870409/56676133-36dabd80-66f0-11e9-9c9d-6b55759f2500.png)
![Screenshot from 2019-04-25 00-22-08](https://user-images.githubusercontent.com/26870409/56676135-37735400-66f0-11e9-91bc-cade5b13f4be.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
