### ISSUE TITLE
伊索寓言小程序

### ISSUE THREAD

**Issue by plough** [521xueweihan/HelloGitHub#577]
## 项目推荐
- 项目地址：https://github.com/plough/yisuo

- 类别：JS

- 项目后续更新计划：1. 在现有基础上进行小迭代，优化细节的体验。2. 考虑抽出内容接口，以快速开发同类小程序（如成语故事、笑话大全、脑筋急转弯等）

- 项目描述：
  这是一个微信小程序，下拉刷新，随机展示一则伊索寓言。可以在碎片时间，看几则故事，领悟人生哲理。有助于初学者学习微信小程序的开发。

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？
代码非常简单，核心 JS 代码就 50 行左右，却实现了一个完整可用的小程序。可以在较短的时间内读懂，并用来开发自己的小程序。
我个人也挺喜欢用这个小程序。

- 示例代码：（可选）长度：1-20 行
```javascript
function getOneRandomFable() {
  var length = fableList.length;
  var index = parseInt(Math.random() * length)
  while (!isValidFable(fableList[index])) {
    index = parseInt(Math.random() * length)
  }
  return fableList[index];
}
```
- 截图：
![](https://raw.githubusercontent.com/plough/yisuo/master/images/yisuo.jpg)

微信扫码体验：
![](https://raw.githubusercontent.com/plough/yisuo/master/images/qrcode.png)

**Comment by 521xueweihan** [comment]
很有趣的 demo实践项目，但是不符合开源项目的规范，有敏感信息。暂不能收录到月刊中。建议：
1. 删除铭感信息
2. ReadMe 按照：推荐项目审核标准 #271 修改更新
