### ISSUE TITLE
项目推荐

### ISSUE THREAD

**Issue by xmyl** [521xueweihan/HelloGitHub#579]
## 项目推荐
- 项目地址：https://github.com/lizhenghn123/StudyBooks

- 类别：书籍

- 项目后续更新计划：

- 项目描述：
  - 必写：别人的学习资料，包括书籍和网址
  - 可选：编程方面的参考资料
  - 描述长度（不包含示例代码）: 都是资料，没细看

- 推荐理由：知识共享啦

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
