### ISSUE TITLE
vue2 eagles项目爬坑之路 —— 各种组件封装

### ISSUE THREAD

**Issue by silianpan** [521xueweihan/HelloGitHub#58]
## 项目推荐
- 项目名称：vue2 eagles项目爬坑之路 —— 各种组件封装

- 项目地址：https://github.com/silianpan/eagles
[在线演示](https://silianpan.github.io/eagles_dist/)

- 项目语言：javascript vue

- 项目描述：本项目采用vue+axios+elementui技术，集成了vuex状态管理，vue-awesome字体图标库，vue-i18n国际化，mockjs模拟api数据提交，支持sass样式编译。开发了非常适合项目的低耦合组件，如：树表、拓扑图、表格、图表等，还附加菜单管理、角色权限管理、用户管理等通用项目模块。

- 推荐理由：vue全家桶+axios+elementui技术实战经验

- 示例代码：
```javascript
<template>
	<el-row class="container">
    <v-head :collapsed="collapsed" @collapsedChange ="collapsedChange"></v-head >
		<el-col :span="24" class="main">
			<v-sidebar :collapsed="collapsed" :menuList = "menuList"></v-sidebar >
			<section class="content-container">
				<div class="grid-content bg-purple-light">
					<el-col :span="24" class="content-wrapper">
						<transition name="fade" mode="out-in">
							<router-view>
							</router-view>
						</transition>
					</el-col>
				</div>
			</section>
		</el-col>
	</el-row>
</template>
```

- 截图：https://github.com/silianpan/silianpan.github.io/blob/master/2017/05/13/vue2/topo.png

![topo](https://github.com/silianpan/silianpan.github.io/blob/master/2017/05/13/vue2/topo.png)

**Comment by 521xueweihan** [comment]
@silianpan 请问为什么，我在访问示例网站时，点击某些 tab（组件->富文本） 无法跳转到相应页面，然后会跳到登陆界面。

**Comment by silianpan** [comment]
@521xueweihan 还在完善中

**Comment by 521xueweihan** [comment]
@silianpan 期待完善完成的效果 😁
