### ISSUE TITLE
项目推荐：ieaseMusic

### ISSUE THREAD

**Issue by xmyl** [521xueweihan/HelloGitHub#580]
## 项目推荐
- 项目地址：https://github.com/trazyn/ieaseMusic

- 类别：其它

- 项目后续更新计划：

- 项目描述：
  - 必写：基于网易云API开发的音乐播放软件
  - 可选：好用的音乐软件，适用于linux和mac os

- 推荐理由：UI设计好看，音乐资源丰富

**Comment by 521xueweihan** [comment]
@xmyl 以后推荐项目可以在 issues 的 title 写上项目名称。

**Comment by xmyl** [comment]
好的，今天才看到你们的项目呢，以后会多关注的哦




------------------ 原始邮件 ------------------
发件人: "削微寒"<notifications@github.com>;
发送时间: 2019年4月29日(星期一) 下午3:08
收件人: "521xueweihan/HelloGitHub"<HelloGitHub@noreply.github.com>;
抄送: "夏木彦林"<xmylme@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [521xueweihan/HelloGitHub] 项目推荐：ieaseMusic (#580)




@xmyl 以后推荐项目可以在 issues 的 title 写上项目名称。

**Comment by 521xueweihan** [comment]
@xmyl 感谢支持和推荐，✌️

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 38 期](https://hellogithub.com/periodical/volume/38/#ieaseMusic)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
