### ISSUE TITLE
项目推荐：你用不惯 RxJava，只因缺了这把钥匙 🔑

### ISSUE THREAD

**Issue by KunMinX** [521xueweihan/HelloGitHub#581]
## 项目推荐
- 项目地址：https://github.com/KunMinX/RxJava2-Operators-Sample

- 类别：Java

- 项目后续更新计划：

目前已完成核心功能，后续持续更新 samples 案例和拓展功能。

- 推荐理由：你用不惯 RxJava，只因缺了这把钥匙

- 项目描述：

![](https://user-gold-cdn.xitu.io/2019/4/29/16a67c5328707335?w=1472&h=801&f=jpeg&s=238694)

很高兴和大家见面！

缘于 4 月中旬，我在掘金发表的 [《你用不惯 RxJava，只因缺了这把钥匙》](https://juejin.im/post/5cb82a42e51d456e62545ac6) （以下简称 “Rx钥匙” ）。

原本目标只是给大家一把钥匙，方便大家意会 RxJava 操作符的本质，想不到在后台收到 40 多条留言。

有的读者因为豁然开朗而喜出望外，不吝留下夸张的赞美；也有读者觉得意犹未尽，表达了对见证更多的愿望。

![](https://upload-images.jianshu.io/upload_images/57036-0c2e1cc89253dc22.png)

![](https://upload-images.jianshu.io/upload_images/57036-ed92fc17cc7284e6.png)

![](https://upload-images.jianshu.io/upload_images/57036-f960ade1565fa041.png)

从留言中，我看到了热心网友们对 Rx钥匙 的期待 和 各自内心世界的丰富多彩，这些期待甚至远远超出了 Rx钥匙 本身，期望它是一把能够解决无聊、带给自己更多的 魔法棒。

![](https://user-gold-cdn.xitu.io/2019/4/25/16a53611f80f218d?w=330&h=285&f=png&s=99624)

再加上，我自己也因为 **“拿 SQL 来隐喻操作符”** 的那番见解，而心生灵感：

不如做一件史上最无聊的事吧 —— **像设计师一样将每个像素都抠到极致，像工程师一样将工程设计模式和原则应用到每一个功能的编写，用无聊的方式来对抗无聊** —— 这是一款为无聊而生的面向 Android 开发者的操作符练习工具。

|                        Add Operators                         |                         Output Code                          |                      Clear Expressions                       |
| :----------------------------------------------------------: | :----------------------------------------------------------: | :----------------------------------------------------------: |
| ![](https://user-gold-cdn.xitu.io/2019/4/29/16a67c5327b2bae4?w=374&h=666&f=gif&s=1085552) | ![](https://user-gold-cdn.xitu.io/2019/4/29/16a67c53289e5af2?w=374&h=666&f=gif&s=477115) | ![](https://user-gold-cdn.xitu.io/2019/4/29/16a67c532882840a?w=374&h=666&f=gif&s=273763) |

除了提供 “解决无聊” 这一最核心功能之外，你还可以从这个开源项目获得的内容包括：

1. 整洁的代码风格和标准的资源命名规范。
2. 基于前沿的、遵循关注点分离的 JetPack MVVM 架构。
3. 使用 RxJava 和 lambda 表达式。
4. AndroidX 和 Material Design 2 的全面使用。
5. ConstraintLayout 约束布局的最佳实践。
6. 为提升手机桌面的逼格做贡献，让知识与美观并存，即使从不打开。
7. 绝不使用 Dagger，绝不使用奇技淫巧、编写艰深晦涩的代码。
8. 长期更新。

如你所见，Rx钥匙的界面效果大体已经出来了，我的目标是，将首页先打磨好，这样 Rx钥匙 的 Apk 最快可能下周就能正式和大家见面了。

鉴于目前在 RxJava 表达式的书写上存有一些 “字符联想” 上的小问题，如果你对此十分熟悉，请不吝参与进来，这个项目会因为你的参与而变得更好！

项目链接：
[https://github.com/KunMinX/RxJava2-Operators-Sample](https://github.com/KunMinX/RxJava2-Operators-Sample)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

不是您的项目不好，是我能力有限不了解这个东西是干啥的。
