### ISSUE TITLE
自荐项目：CovenantSQL

### ISSUE THREAD

**Issue by auxten** [521xueweihan/HelloGitHub#582]
## 自荐项目
- 项目地址：https://github.com/CovenantSQL/CovenantSQL

- 类别：Go

- 项目后续更新计划：提升分布式 Transaction 效率，完善 SDK，提升宕机自动恢复的能力

- 项目描述：
  - 必写：具有区块链特性的去中心化 SQL 关系型数据库
  - 可选：可以提供 DBaaS 服务，去中心化存储保证用户隐私
  - 文档：https://developers.covenantsql.io/docs/zh-CN/intro

- 推荐理由：
  - CovenantSQL(CQL) 是一个运行在公网上的 SQL 数据库，并具有 GDPR 合规与去中心化等特点。
    - **ServerLess 支持**: 为小程序、浏览器插件提供免部署维护，自动同步、高可用的数据库服务
    - **SQL 接口**: 支持 SQL-92 标准
    - **去中心化**: 基于共识算法 DH-RPC & Kayak 实现的去中心化
    - **不可篡改**: CQL 中的 Query 历史是不可篡改且可追溯的
    - **隐私**: 使用列级 ACL 和 SQL 白名单模式授予权限
    - **权限**：列级别的权限限制，可以设定 SQL 白名单
  - MacOS 客户端可以通过 `brew install cql` 直接安装

- 截图：
    - 架构图：
      ![架构图](https://cdn.jsdelivr.net/gh/CovenantSQL/docs@b7143254adb804dff0e3bc1f2f6ab11ad9cd44f5/website/static/img/2layers.svg)

    - 基于 CQL 构建的论坛：

![](https://github.com/CovenantSQL/CovenantForum/raw/master/screenshot-link.png)

**Comment by FrontMage** [comment]
已收录至38期

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 38 期](https://hellogithub.com/periodical/volume/38/#CovenantSQL)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
