### ISSUE TITLE
推荐项目：pprint（C++）

### ISSUE THREAD

**Issue by 521xueweihan** [521xueweihan/HelloGitHub#583]
## 项目推荐
- 项目地址：https://github.com/p-ranav/pprint

- 类别：C++

- 项目后续更新计划：无

- 项目描述：
让 print 的输出变得漂亮的 C++ 库。就像 python 的 pprint 库，输出字典和数组的时候有缩进和分行，才容易发现这个世界的美好。示例代码如下：
```c++
#include <pprint.hpp>
printer.print(std::map<std::string, std::set<int>>{
    {"foo", {1, 2, 3, 3, 2, 1}}, {"bar", {7, 6, 5, 4}}});
// 输出结果如下
{
  "bar" : {4, 5, 6, 7}, 
  "foo" : {1, 2, 3}
}
```

**Comment by ChungZH** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
