### ISSUE TITLE
自荐项目:MarkSentence 英语听力(托福)标记工具（C++）

### ISSUE THREAD

**Issue by Gltina** [521xueweihan/HelloGitHub#584]
## 项目推荐
- 项目地址：https://github.com/Gltina/MarkSencent

- 类别：C++ (QT 5.9)

- 项目后续更新计划： 希望和更多人探讨如何使得精听过程更高效的方法，对程序中的标记方式进行调整

- 项目描述：
  - 必写：这是一个在托福听力中标记句子的工具(即精听工具) ，可直接对听力音频中没听懂片段进行标记，并选择标记理由，在日后反复复习中可提高效率。
  - 可选：当前直接面向的是备考托福的人，因为目前仅提供了获取服务器上的托福听力资源，但是其基本功能，也就是对听力做标签的功能，可用于所有练习英语听力的学习者。
  - 描述长度（不包含示例代码）: 用于提高托福听力的复习效率

- 推荐理由：给听力音频做标签，下次高效复习！

- 截图：（可选）
在线获取听力文件
![在线获取听力文件](https://github.com/Gltina/MarkSencent/raw/master/samples/use_download.gif)
精听的过程
![精听的过程](https://github.com/Gltina/MarkSencent/raw/master/samples/use_listening_1.gif)

**Comment by ChungZH** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by ChungZH** [comment]
*个人意见：我觉得这个项目还是很好的哈，您可以按照我们的审核标准再完善一下项目，比如 *LICENSE*、文档 等这几个部分，再来提交。期待下一次看到更完美的项目。* :smile:
