### ISSUE TITLE
代替Toast/SnackBar新方式，使用WindowManager 无需申请权限

### ISSUE THREAD

**Issue by o0o0oo00** [521xueweihan/HelloGitHub#586]
## 项目推荐
- 项目地址：https://github.com/o0o0oo00/Pudding

- 类别：Kotlin
- 项目描述：
  - Pudding use WindowManager(don't need request permission) to pull down a view that are displayed on top their attached window 

- 推荐理由：代替Toast/SnackBar新方式，使用WindowManager 无需申请权限

- 示例代码：
```
Pudding.create(this) {
    setTitle("This is Title")
    setText("this is text")
}.show()
```

- 截图：![gif](https://raw.githubusercontent.com/o0o0oo00/Pudding/master/demogif/first3.gif)

# #

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
