### ISSUE TITLE
推荐项目：Python - 100天从新手到大师（本月star数上升最快的项目之一）

### ISSUE THREAD

**Issue by liyuexing** [521xueweihan/HelloGitHub#588]
## 项目推荐
- 项目地址：https://github.com/jackfrued/Python-100-Days

- 类别：Python
- 项目后续更新计划：持续更新
- 项目描述：
Python - 100天从新手到大师，Python学习的进阶路线。

- 推荐理由：
学习曲线低，非专业人士也能上手
开源系统，拥有强大的生态圈
解释型语言，完美的平台可移植性
支持面向对象和函数式编程
能够通过调用C/C++代码扩展功能
代码规范程度高，可读性强

- 示例代码：

![Python](https://user-images.githubusercontent.com/37652252/57191640-68f2e780-6f5a-11e9-9245-124cbf58ca98.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 38 期](https://hellogithub.com/periodical/volume/38/#Python-100-Days)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
