### ISSUE TITLE
终端gameboy

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#589]
## 项目推荐
- 项目地址：

https://github.com/HFO4/gameboy.live.git

- 类别：Go

- 项目后续更新计划：

https://github.com/HFO4/gameboy.live#features--todos

- 项目描述：

终端玩gameboy游戏

- 推荐理由：

gameboy是我们童年的回忆，你想过在终端运行吗？快来试试吧！

- 示例代码：
```
telnet gameboy.live 1989
```
- 截图：

![image](https://user-images.githubusercontent.com/26538619/57204135-3db6d980-6fe8-11e9-91fb-a500ab5fb092.png)

**Comment by FrontMage** [comment]
已收录至38期
