### ISSUE TITLE
ActionScript3.0 解释器

### ISSUE THREAD

**Issue by asheigithub** [521xueweihan/HelloGitHub#59]
## 项目推荐
- 项目名称：ActionScript3.0 解释器

- 项目地址：https://github.com/asheigithub/ASTool

- 项目语言：C# + VB.Net
- 项目描述：net2.0实现的AS3解释器

- 推荐理由：貌似应该是目前功能最全的纯C# ActionScript3.0解释器了吧（应该吧）

**Comment by 521xueweihan** [comment]
@asheigithub 您好，请问这个项目有什么实际作用？或者可以让 C# 的初学者学到那些知识呢？

因为我并不是很了解 AS3（第三代FLASH脚本） 这门语言，还望指教。

**Comment by asheigithub** [comment]
你好，这是一个解释器，从语法树分析开始一直到实际执行。差不多算是一个完整的脚本语言解释执行系统。至于你说有什么用，我目标是嵌入unity做热更用的

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功收录**在 [HelloGitHub 第 17 期](https://github.com/521xueweihan/HelloGitHub/blob/master/content/17/HelloGitHub17.md)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，如果方便可以 Star ⭐️ 本项目，让更多人看到本项目。
