### ISSUE TITLE
自荐项目：Redis TUI 基于命令行的 Redis 图形界面客户端

### ISSUE THREAD

**Issue by mylxsw** [521xueweihan/HelloGitHub#590]
## 项目推荐
- 项目地址：https://github.com/mylxsw/redis-tui

- 类别：Golang

- 项目描述：

    A Redis Text-based UI client in CLI.

- 推荐理由：Very cool

- 截图：

![](https://raw.githubusercontent.com/mylxsw/redis-tui/master/preview.gif)

**Comment by FrontMage** [comment]
已收录至38期
