### ISSUE TITLE
自荐项目：Wizard 开源文档管理系统

### ISSUE THREAD

**Issue by mylxsw** [521xueweihan/HelloGitHub#591]
## 项目推荐
- 项目地址：https://github.com/mylxsw/wizard

- 类别：PHP

- 项目后续更新计划：

    根据社区反馈优化，增加新的功能。

- 项目描述：
  
    Wizard 是一款开源文档管理系统，基于Laravel开发框架开发，目前已经在多家公司部署使用，主要支持Markdown，Swagger文档管理。

- 推荐理由：

    功能完备，不仅能够用来管理Markdown文档，还可以用来管理Swagger API文档，同时还可以接入到公司内部的统一身份认证系统（LDAP）。

- 截图：

    ![](https://ssl.aicode.cc/2019-05-06-15571233127682.jpg)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 38 期](https://hellogithub.com/periodical/volume/38/#wizardx)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
