### ISSUE TITLE
Windows 终端

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#592]
## 项目推荐
- 项目地址：

https://github.com/microsoft/Terminal

- 类别：C++

- 项目描述：

Windows Terminal 是一个面向命令行用户的全新，现代，功能丰富，高效的终端应用程序。它包括 Windows 命令行社区最常请求的许多功能，包括对选项卡，富文本，全球化，可配置性，主题和样式等的支持。终端还需要满足我们的目标和措施，以确保它保持快速，高效，并且不会消耗大量的内存或电力。

- 推荐理由：

一直以来 Windows 不被开发者青睐的原因就是终端不好用，该工具完美兼容所有你熟悉的终端，还可以使用颜色以及 emoji，快来试试吧！

**Comment by ChungZH** [comment]
您推荐的项目已收录到专栏，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
