### ISSUE TITLE
GO 性能调优手册

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#593]
## 项目推荐
- 项目地址： https://github.com/dgryski/go-perfbook.git

- 类别：Go

- 项目后续更新计划：

- 项目描述：
  
  本文档概述了编写高性能Go代码的最佳实践。

- 推荐理由：
  
  对于想提供性能的GO编写者而言是一个很好的参考。

**Comment by 521xueweihan** [comment]
已推荐过：https://hellogithub.com/periodical/search/?q=https://github.com/dgryski/go-perfbook#go-perfbook
