### ISSUE TITLE
项目推荐：真香警告：即使不用饿了么订餐，也请务必收藏好该库！

### ISSUE THREAD

**Issue by KunMinX** [521xueweihan/HelloGitHub#594]
## 项目推荐
- 项目地址：https://github.com/KunMinX/Linkage-RecyclerView

- 类别：Java

- 项目后续更新计划：
完善二级联动在各场景下的需求，如加载更多等。

- 项目描述：
  
### 由来

LinkageRecyclerView 是一款基于 MVP 架构开发的二级联动列表控件。它是因 “RxJava 魔法师” 这个项目的需求而存在。

在最初寻遍了 GitHub 也没有找到合适的开源库（高度解耦、可远程依赖）之后，我决心研究参考现有开源项目关于二级联动的逻辑，并自己动手编写一个 **高度解耦、轻松配置、可通过 maven 仓库远程依赖** 的真正的第三方库。

LinkageRecyclerView 的个性化配置十分简单，依托于 MVP 的 “配置解耦” 特性，使用者无需知道内部的实现细节，仅通过实现 Config 类即可完成功能的定制和扩展。

此外，在不设置自定义配置的情况下，LinkageRecyclerView 最少只需一行代码即可运行起来。

|                           RxMagic                            |                         Eleme Linear                         |                          Eleme Grid                          |
| :----------------------------------------------------------: | :----------------------------------------------------------: | :----------------------------------------------------------: |
| ![7.gif](https://upload-images.jianshu.io/upload_images/57036-b4d61e70b43a07bb.gif) | ![2.gif](https://upload-images.jianshu.io/upload_images/57036-04b42bddcdd6cf39.gif) | ![3.gif](https://upload-images.jianshu.io/upload_images/57036-5dc85c89ef486d57.gif) |

**Comment by CasualJi** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 39 期](https://hellogithub.com/periodical/volume/39/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

为了让开源项目的发起者不再孤单，我们决定牵线搭桥。可以加我微信：xueweihan（备注您发起的项目链接）
待时机成熟，你会发现你并不孤独！
