### ISSUE TITLE
自荐项目-中国人聊天表情包

### ISSUE THREAD

**Issue by zhaoolee** [521xueweihan/HelloGitHub#596]
## 项目推荐
- 项目地址：
https://github.com/zhaoolee/ChineseBQB

- 类别：书籍

- 项目后续更新计划：
每周一到两次

- 项目描述：
  - 必写：这是一个专门用于收录表情包的仓库, 所有收录的表情包均可在线查看! 所有图片索引数据由python程序自动生成, 程序为项目中的`build.py`

 - 描述长度（不包含示例代码）: 表情包是中国的, 也是世界的! 让中国表情包文化在github生根发芽

- 推荐理由：表情包是快乐之源!

```
Remember, when you pass an emoticon
记住，当你传递一张表情包的时候

You are not passing a green stalk
你不是在传递一张发绿的老梗

You passed
你传递的

It is the last torch of the classical Internet spirit!
是古典互联网精神最后的火炬！ 
```

![](https://user-images.githubusercontent.com/15868458/57589652-187e1a00-7558-11e9-9c96-2ee413f3b470.png)

**Comment by 521xueweihan** [comment]
非常有意思的项目，就是 Readme 写的有些乱。。。

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 39 期](https://hellogithub.com/periodical/volume/39/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

为了让开源项目的发起者不再孤单，我们决定牵线搭桥。可以加我微信：xueweihan（备注您发起的项目链接）
待时机成熟，你会发现你并不孤独！

**Comment by zhaoolee** [comment]
感谢您的收录, 希望项目越办越好!

削微寒 <notifications@github.com> 于2019年6月28日周五 上午9:22写道：
