### ISSUE TITLE
简易Logo制作工具

### ISSUE THREAD

**Issue by sherlonWang** [521xueweihan/HelloGitHub#597]
## 项目推荐
- 项目地址：https://github.com/sherlonWang/logodiy

- 类别：CSS

- 项目后续更新计划：更新特定主题的Logo风格，如youtube、pornhub等等。

- 项目描述：
  - 本项目是基于 HTML5 + JS + CSS 的静态网页，可以用来制作风格多样的简易logo图标并下载。

- 推荐理由：UI简洁直观，操作方便，可以生成风格多样的logo。

- 截图：![](https://i.loli.net/2019/05/12/5cd83dfb65dd0.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
