### ISSUE TITLE
iOS开源项目：PYPhotoBrowser 

### ISSUE THREAD

**Issue by iphone5solo** [521xueweihan/HelloGitHub#6]
PYPhotoBrowser —— https://github.com/iphone5solo/PYPhotoBrowser  高仿 QQ、微信效果的图片浏览器（支持原图和缩略图、多种手势、CocoaPods）

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。已加入到[07期](https://github.com/521xueweihan/HelloGitHub/blob/master/07/HelloGitHub07.md)
