### ISSUE TITLE
WeiboSpider

### ISSUE THREAD

**Issue by ResolveWang** [521xueweihan/HelloGitHub#60]
## 项目推荐
- 项目名称：WeiboSpider

- 项目地址：https://github.com/ResolveWang/WeiboSpider

- 项目语言：Python

- 项目描述：分布式微博爬虫，支持快速抓取和稳定抓取两种运行模式，凡是能想到的数据，几乎都做了抓取实现，项目模块逻辑清晰，注释丰富，非常便于定制化自己的需求。关于项目配置和使用具体信息可以查看[项目文档](https://github.com/ResolveWang/WeiboSpider/wiki)和[演示视频](https://pan.baidu.com/s/1eSy2qzw)（密码是: ypn5 ）

- 推荐理由：
  - 功能完备，抓取内容包括特定关键词搜索、用户具体信息抓取、微博评论抓取、微博转发信息抓取等  
  - 抓取信息完备，任务都是通过PC端进行抓取的，并且是登录状态下  
  - 易用，提供丰富的文档支持，对于小白用户，可以通过演示视频快速入门，也提供QQ群答疑  
  - 代码逻辑清晰，注释丰富，非常便于二次开发
  - 项目会长期更新，很多爬虫项目都在开源后一段时间就不会维护了，导致无法使用，但是该项目会一直更新，目前已经迭代一年了。

- 截图：

微博信息结果
![微博信息](https://user-images.githubusercontent.com/8018776/27718307-d140d9c8-5d7d-11e7-8946-10b482584998.png)

用户信息抓取结果
![用户信息](https://user-images.githubusercontent.com/8018776/27718379-316c6060-5d7e-11e7-9dd6-5072aabe9e81.png)

其它抓取信息鉴于篇幅，就不贴出了

**Comment by 521xueweihan** [comment]
@ResolveWang 赞，信息写的已经非常详尽了

**Comment by 521xueweihan** [comment]
@ResolveWang 不管是项目内容、类型、推荐项目描述，都非常适合。欢迎推荐更多优秀的项目。

**Comment by ResolveWang** [comment]
哈哈，这次是自荐试试水。以后会推荐更加优秀的项目的

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功收录**在 [HelloGitHub 第 17 期](https://github.com/521xueweihan/HelloGitHub/blob/master/content/17/HelloGitHub17.md)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，如果方便可以 Star ⭐️ 本项目，让更多人看到本项目。

**Comment by ResolveWang** [comment]
哈哈哈，早就star了哈

**Comment by 521xueweihan** [comment]
@ResolveWang 老铁，稳。
