### ISSUE TITLE
[自荐项目] MarkSentence （英语听力标记工具） ( C++)

### ISSUE THREAD

**Issue by Gltina** [521xueweihan/HelloGitHub#600]
## 项目推荐
- 项目地址：https://github.com/Gltina/marksencent

- 类别：C++, QT(5.5)

- 项目后续更新计划：做一些能提高学习效率的调整

- 项目描述：
  - 必写：这是一个在托福听力中标记句子的工具(即精听工具) 

  - 描述长度（不包含示例代码）: 在听力时可文本对照，并且对听力音频中没听懂片段进行标记，并选择标记理由，在日后反复复习中可提高效率。

- 推荐理由：也许有很多的软件都可以做到对音频的控制，你也可以在一段一段的听力中快进后退来练习听力，但是，你有没有想过，如果把你每次没听懂的地方标记下来，下次听的时候，是不是就可以首先听那些你第一次没听懂的？ 然后才考虑全部听一遍。

- 示例代码：如果你对本项目感兴趣，你可以查看我在开发时所遇到的[一些好玩的算法和问题](https://github.com/Gltina/marksencent/blob/master/log/sparkSpot.md)

- 截图：see more please [click](https://github.com/Gltina/marksencent)
![标记过程](https://github.com/Gltina/marksencent/raw/master/samples/marking.gif)
![复习过程](https://github.com/Gltina/marksencent/raw/master/samples/clickmark.gif)

**Comment by ChungZH** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 39 期](https://hellogithub.com/periodical/volume/39/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

为了让开源项目的发起者不再孤单，我们决定牵线搭桥。可以加我微信：xueweihan（备注您发起的项目链接）
待时机成熟，你会发现你并不孤独！
