### ISSUE TITLE
【自荐项目】Android 网络视频加载库推荐

### ISSUE THREAD

**Issue by Reone** [521xueweihan/HelloGitHub#601]
## 项目推荐
- 项目地址：https://github.com/Reone/Mrthumb

- 类别：Java

- 项目后续更新计划：
            1.  添加自定义配置缩略图缓存机制
            2. 自定义获取缩略图方案
            3. 更新代码结构，是整个项目代码更简洁易懂

- 项目描述：
  合理的顺滑的获取网络视频缩略图
              1.  使用MediaMetadataRetriever获取视频信息及缩略图
              2. 使用线程异步加载缩略图并缓存
              3. 支持两种不同的加载顺序选择：顺序、乱序
              4. 获取不到缩略图时取最近的缩略图
- 推荐理由：API简单，效果顺滑

- 示例代码：（可选）长度：1-20 行
1. 加载缩略图
```java
if (playState == NiceVideoPlayer.STATE_PREPARED) {
    //视频准备好后开始加载缩略图
    Mrthumb.obtain().buffer(videoUrl, videoDuration, Mrthumb.Default.COUNT);
    //更详细的可以调用如下方法
    //Mrthumb.obtain().buffer(videoUrl, null, videoDuration, Mrthumb.Default.RETRIEVER_TYPE, Mrthumb.Default.COUNT, Mrthumb.Default.THUMBNAIL_WIDTH, Mrthumb.Default.THUMBNAIL_HEIGHT);
}
```

2. 获取缩略图 
```java
float percentage = (float) seekBar.getProgress() / seekBar.getMax();
Bitmap bitmap = Mrthumb.obtain().getThumbnail(percentage);
```

3. 添加缓存进度回调
```java
Mrthumb.obtain().addProcessListener(new ProcessListener() {

    @Override
    public void onProcess(final int index, final int cacheCount, final int maxCount, final long time, final long duration) {
        if (delegate != null) {
            delegate.thumbProcessLog("cache " + time / 1000 + "s at " + index + " process:" + (cacheCount * 100 / maxCount) + "%");
        }
    }
});
```
- 截图：（可选）gif/png/jpg
![img](https://raw.githubusercontent.com/Reone/Mrthumb/master/simple/preview.gif)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
