### ISSUE TITLE
[自荐项目] 为前端开发者量身定制的pdf书籍(附: 码农长寿指南)

### ISSUE THREAD

**Issue by ddzy** [521xueweihan/HelloGitHub#602]
## 项目推荐
- 项目地址：https://github.com/ddzy/fe-necessary-book

- 类别：书籍

- 项目后续更新计划：不定期更新

- 项目描述：
  - 我相信, 知识永远没有国界!
  - 前端必读书籍, 量不再多, 而在于精
  - 项目主要是分享pdf书籍, 也会不定期共享一些开发者必备的`软件工具包`等等...  
  - 另外, 本项目还附属——**码农长寿指南**, 祝你的代码事业更上一层楼~

- 推荐理由：在优秀书籍的加持下, 继续努力吧.
![熊猫头_你写代码就像蔡徐坤](https://user-images.githubusercontent.com/33921398/57829366-4cb83b80-77e1-11e9-948f-ee5913fd5842.png)

**Comment by 521xueweihan** [comment]
竟然没有推进  https://hellogithub.com 网站，还想收录到月刊！你走开

**Comment by ddzy** [comment]
> 该项目中竟然没有推荐 https://hellogithub.com 网站和 HelloGitHub 项目的字样，还想收录到本月刊中！你妄想，你走开！

我是个有原则的人

**Comment by ddzy** [comment]
> 该项目中竟然没有推荐 https://hellogithub.com 网站和 HelloGitHub 项目的字样，还想收录到本月刊中！你妄想，你走开！

https://github.com/ddzy/fe-necessary-book#community

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
@ddzy 相亲相爱的小伙伴队伍中又多了一名新成员 ✌️

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 39 期](https://hellogithub.com/periodical/volume/39/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

为了让开源项目的发起者不再孤单，我们决定牵线搭桥。可以加我微信：xueweihan（备注您发起的项目链接）
待时机成熟，你会发现你并不孤独！
