### ISSUE TITLE
微软开源的分布式近似最近邻域搜索库

### ISSUE THREAD

**Issue by nivance** [521xueweihan/HelloGitHub#603]
## 项目推荐
- 项目地址：https://github.com/microsoft/SPTAG

- 类别：C++

- 项目后续更新计划：暂无

- 项目描述：
  - 必写：这个库的样本以向量表示，向量可以用L2距离或余弦距离进行比较。为查询向量返回的向量是与查询向量具有最小L2距离或余弦距离的向量。 SPTAG提供了两种方法:kd树相邻图(SPTAG- kdt)和平衡k均值树相邻图(SPTAG- bkt)。SPTAG-KDT在索引构建成本方面具有优势，SPTAG-BKT在高维数据的搜索精度方面具有优势。

- 推荐理由：SPTAG 允许用户利用深度学习模型在几毫秒内搜索数十亿条数据

相关信息：https://blogs.microsoft.com/ai/bing-vector-search/?utm_source=pre-amp&utm_campaign=81516

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
