### ISSUE TITLE
[自荐项目]nic: an elegant and easy-to-use HTTP request libs

### ISSUE THREAD

**Issue by EddieIvan01** [521xueweihan/HelloGitHub#604]
## 项目推荐
- 项目地址：https://github.com/EddieIvan01/nic

- 类别：Go, HTTP request

- 项目后续更新计划：根据issues添加新features

- 项目描述：
  - nic是一个易用的HTTP request包，它封装了Golang的HTTP标准库，提供了简洁优雅的API，可以更轻松的发送HTTP请求，解决了Golang标准库自定义HTTP请求（如headers、cookies）时繁琐的步骤。类似于Python-requests之于Python-urllib。

- 推荐理由：能让用户以类似于Python-requests的写法使用Golang发起HTTP请求，更简单优雅

- 示例代码：
  ```go
  resp, err := nic.Post("http://example.com", &nic.H {
      Headers: nic.KV {
          "X-Forwarded-For": "127.0.0.1",
      },
      Data: nic.KV {
          "nic": "nic",
      },
  })
  
  if err != nil {
      handle(err)
  }
  fmt.Println(resp.Text)
  resp.SetEncode("gbk")
  fmt.Println(resp.Text)
  ```
  ```go
  session := &nic.Session{}
  session.Post("http://example.com/login", &nic.H{
      Data: nic.KV {
          "uname": "nic",
          "passwd": "nic",
      },
  })
  resp, err := session.Get("http://example.com/userinfo", nil)
  
  if err == nil {
      fmt.Println(resp.Text)
  }
  ```

**Comment by FrontMage** [comment]
已收录至38期

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 38 期](https://hellogithub.com/periodical/volume/38/#nic)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
