### ISSUE TITLE
对程序员有用的定律和法则

### ISSUE THREAD

**Issue by nivance** [521xueweihan/HelloGitHub#605]
## 项目推荐
- 项目地址：https://github.com/dwmkerr/hacker-laws

- 类别：其它

- 项目后续更新计划：持续添加中

- 项目描述：
  - 必写：程序员工作中可能使用到的定律、原理、原则和模式库

- 推荐理由：程序员在工作中会讨论原则和模式以及他们的应用，这里有15大定律和7大原则供你学习和选择使用。

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 38 期](https://hellogithub.com/periodical/volume/38/#hacker-laws)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
