### ISSUE TITLE
[自荐项目]：PyMySQLPool

### ISSUE THREAD

**Issue by prprprus** [521xueweihan/HelloGitHub#606]
## 项目推荐
- 项目地址：https://github.com/prprprus/PyMySQLPool

- 类别：Python

- 项目后续更新计划：可视化管理后台

- 项目描述：
  - 必写：基于 PyMySQL 的数据库连接池；可设置最大连接数、动态增量添加连接、动态释放过剩的空闲链接
  - 可选：适用于需要数据库连接池的场景；能够让初学者学到多线程编程、连接池等概念
  - 描述长度（不包含示例代码）: PyMySQLPool 是一个基于 PyMySQL 客户端的数据库连接池，简单、轻量级

- 推荐理由：根据实际需要增量式添加连接、动态释放过剩的空闲连接、轻量级

- 示例代码：

```Python
from pymysqlpool.pool import Pool

pool = Pool(host=HOST, port=PORT, user=USER, password=PASSWORD, db=DB)
pool.init()

connection = pool.get_conn()
cur = connection.cursor()
cur.execute('SELECT * FROM `pet` WHERE `name`=%s', args=("Puffball", ))
print(cur.fetchone())

pool.release(connection)
```

**Comment by 521xueweihan** [comment]
@prprprus 你好，感觉 SQLAlchemy 的 pool 实现：https://github.com/zzzeek/sqlalchemy/blob/master/lib/sqlalchemy/pool/impl.py#L26 已经挺容易理解和学习的了

**Comment by prprprus** [comment]
@521xueweihan 👋

 好的，那我关掉这个 issue
