### ISSUE TITLE
Remix Icon  1500+图标的免费开源图标库

### ISSUE THREAD

**Issue by xiaochunjimmy** [521xueweihan/HelloGitHub#611]
## 项目推荐
- 项目地址：https://github.com/Remix-Design/RemixIcon

- 类别：CSS、前端、设计

- 项目后续更新计划：每2-3周更新一次，包括期间issue收到的request内容、官网的功能升级等。

- 项目描述：
这个项目可以让开发者和设计师在一个图标库中快速找到适合的图标，用于自己的网站或者APP开发。不同于混搭收集的图标库，RemixIcon每一枚图标都是由设计师精心设计而成，并且每一枚图标都包含填充和描边两种风格，便于切换使用。而传统的图标库，要么收费、要么图标较少、要么不够精美。

- 推荐理由：每一枚图标都是精心设计，完美像素且简洁易读。提供 fill 和 outline 两种风格。

- 预览图：
![preview](https://cdn.remixcdn.com/image/remixicon-1500.png)

**Comment by ming995** [comment]
Nice

**Comment by 521xueweihan** [comment]
简直不要太赞了！

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 39 期](https://hellogithub.com/periodical/volume/39/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

为了让开源项目的发起者不再孤单，我们决定牵线搭桥。可以加我微信：xueweihan（备注您发起的项目链接）
待时机成熟，你会发现你并不孤独！
