### ISSUE TITLE
【自荐项目】Zvm

### ISSUE THREAD

**Issue by 5A59** [521xueweihan/HelloGitHub#612]
## 项目推荐
- 项目地址：https://github.com/5A59/Zvm

- 类别：Python

- 项目后续更新计划：以 Zvm 为例讲解如何从零开始写 JVM

- 项目描述：
是一款用 python 实现的简易 jvm，实现功能如下：class 文件解析，类加载，运行时数据区，指令解释器，基本指令集 (总共 205 条，实现了估计 190 多条吧)，简易 gc，简易线程，简易 jdk 库，可以运行基本的 java class 文件。
代码量少，模块清晰，适合用来学习 jvm 的基本结构和实现。

- 推荐理由：
java 是如何运行起来的，jvm 是如何实现的，通过 Zvm 项目可简单入门，了解 jvm 的简易实现。

- 截图：
https://github.com/5A59/Zvm/blob/master/res/pic1.png

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 38 期](https://hellogithub.com/periodical/volume/38/#Zvm)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
