### ISSUE TITLE
自荐项目：城市脉络

### ISSUE THREAD

**Issue by 96486d9b** [521xueweihan/HelloGitHub#613]
## 项目推荐
- 项目地址：https://github.com/96486d9b/city-vein

- 类别：JS、Python

- 项目后续更新计划：暂无

- 项目描述：以公交路线数据，还原城市结构

- 推荐理由：通过可视化手段，借助公交路线，还原了30多个城市的城市结构

- 截图：
![hangzhou](https://user-images.githubusercontent.com/24759956/58336416-43c90900-7e76-11e9-9738-a6da357c0f80.gif)

**Comment by Eurus-Holmes** [comment]
Interesting!

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 38 期](https://hellogithub.com/periodical/volume/38/#city-vein)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
