### ISSUE TITLE
styled-components

### ISSUE THREAD

**Issue by ming995** [521xueweihan/HelloGitHub#618]
## 项目推荐
- 项目地址：https://github.com/styled-components/styled-components

- 类别：JS

- 项目后续更新计划：https://github.com/styled-components/styled-components/issues/1934

- 项目描述: 更爽的在React中写样式

- 推荐理由：从关注点分离到组件的隔离，样式和JS以及DOM结构在一个文件中，这个文件就是一个组件，styled-components就是更便捷的`css in js`。并且将样式进行组件化，避免了样式的冲突而且更优雅的解决了覆盖第三方组件的样式，并且支持css全部特性，也可以在里面写带有类名的样式，唯一不足好像是在vscode中没有代码提示

- 示例代码：

- 截图：
![image](https://user-images.githubusercontent.com/46031112/58448912-f4b3fa00-813b-11e9-9b0a-226812def5e8.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
