### ISSUE TITLE
美丽的Java开源博客系统MyBlog

### ISSUE THREAD

**Issue by ZHENFENG13** [521xueweihan/HelloGitHub#62]
## 项目推荐
- 项目名称：Docker+SpringBoot+Mybatis+thymeleaf的开源Java博客系统

- 项目地址：https://github.com/ZHENFENG13/My-Blog

- 项目语言：Java

- 项目描述：简洁美观的个人博客模板，采用Java语言编写，结合了Docker、SpringBoot、Mybatis、thymeleaf等技术框架，程序完全开源免费，面向所有用户。

- 推荐理由：功能完善，项目美观，不断完善中...

- 示例代码：

```
@MapperScan("com.my.blog.website.dao")
@SpringBootApplication
@EnableTransactionManagement
public class CoreApplication {
    @Bean(initMethod = "init", destroyMethod = "close")
    @ConfigurationProperties(prefix = "spring.datasource")
    public DataSource dataSource() {
        return new DruidDataSource();
    }

    @Bean
    public SqlSessionFactory sqlSessionFactoryBean() throws Exception {
        PathMatchingResourcePatternResolver resolver = new PathMatchingResourcePatternResolver();
        SqlSessionFactoryBean sqlSessionFactoryBean = new SqlSessionFactoryBean();
        sqlSessionFactoryBean.setDataSource(dataSource());
        sqlSessionFactoryBean.setMapperLocations(resolver.getResources("classpath*:/mapper/*Mapper.xml"));
        return sqlSessionFactoryBean.getObject();
    }

    @Bean
    public PlatformTransactionManager transactionManager() {
        return new DataSourceTransactionManager(dataSource());
    }


    public static void main(String[] args) {
        SpringApplication.run(CoreApplication.class, args);
    }
}

```
- 截图：
**首页：**
![首页](http://images2015.cnblogs.com/blog/859549/201705/859549-20170511122850691-373579903.png)
**文章详情页：**
![文章页](http://images2015.cnblogs.com/blog/859549/201705/859549-20170510225208988-1419050749.png)
**登录页：**
![登录页](http://images2015.cnblogs.com/blog/859549/201705/859549-20170511122916004-738411708.png)
**文章列表页：**
![文章列表页](http://images2015.cnblogs.com/blog/859549/201705/859549-20170510225259722-688622603.png)
**文章编辑页：**
![文章编辑页](http://images2015.cnblogs.com/blog/859549/201705/859549-20170510225330566-559394265.png)
**分类编辑：**
![分类编辑](http://images2015.cnblogs.com/blog/859549/201705/859549-20170510225357207-57945087.png)

**Comment by 521xueweihan** [comment]
@ZHENFENG13 你好，由于已经推荐过 java 的 blog 项目，所以为了月刊项目的丰富性，就不会再推荐 java blog 类项目。 不好意思。
