### ISSUE TITLE
百度网盘命令行客户端BaiduPCS-Go

### ISSUE THREAD

**Issue by xmyl** [521xueweihan/HelloGitHub#620]
## 项目推荐
- 项目地址：https://github.com/iikira/BaiduPCS-Go

- 类别：Go

- 项目后续更新计划：持续更新中

- 项目描述：
  - 必写：百度网盘客户端（go语言，虽然已发现收录，但不是同一个项目）

- 推荐理由：很好用，突破下载速度，安装很方便，网盘下载利器

**Comment by FrontMage** [comment]
虽然已发现收录，但不是同一个项目 
---
这好像就一个呀

**Comment by xmyl** [comment]
https://github.com/GangZhuo/BaiduPCS
一个是C，一个是改写的Go

**Comment by 521xueweihan** [comment]
@xmyl 专栏负责人决定收录：https://github.com/peterq/pan-light 这个项目了，所以您推荐的项目暂时不能收录。
