### ISSUE TITLE
you-get 基于命令行下载网页视频的程序

### ISSUE THREAD

**Issue by xmyl** [521xueweihan/HelloGitHub#621]
## 项目推荐
- 项目地址：https://github.com/soimort/you-get

- 类别：Python

- 项目后续更新计划：持续更新中

- 项目描述：
  - 必写：用于下载一些网页视频（可播放但禁止下载的网页视频）

- 推荐理由：部分网页视频禁止下载但可观看，可以用该程序下载你喜欢的网页视频

**Comment by 521xueweihan** [comment]
这个只能下载 youtube 上的视频，是不是不符合大部分的“网络情况”？

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
下次写介绍可以多写一些，这么强大项目。我差点给错过了

**Comment by xmyl** [comment]
好的，后续推荐的项目我尽量写得详细一些


------------------
走在变得更好的路上，遇见更好的人。


 




------------------ 原始邮件 ------------------
发件人: "削微寒"<notifications@github.com>;
发送时间: 2019年6月26日(星期三) 凌晨0:11
收件人: "521xueweihan/HelloGitHub"<HelloGitHub@noreply.github.com>;
抄送: "夏木彦林"<xmylme@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [521xueweihan/HelloGitHub] you-get 基于命令行下载网页视频的程序 (#621)




下次写介绍可以多写一些，这么强大项目。我差点给错过了

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 39 期](https://hellogithub.com/periodical/volume/39/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

**Comment by xmyl** [comment]
上个月贡献了一个项目，这次贡献了一个项目，应该是两次了哦------------------ 原始邮件 ------------------
发件人: "削微寒"<notifications@github.com>
发送时间: 2019年6月28日(星期五) 上午9:27
收件人: "521xueweihan/HelloGitHub"<HelloGitHub@noreply.github.com>;
抄送: "夏木彦林"<xmylme@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [521xueweihan/HelloGitHub] you-get 基于命令行下载网页视频的程序 (#621)



您推荐的项目，已成功发布在 HelloGitHub 第 39 期，并把您添加到了贡献者列表中。
 
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 
 
&mdash;

**Comment by 521xueweihan** [comment]
https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md
