### ISSUE TITLE
【自荐项目】vue-unit-test-with-jest

### ISSUE THREAD

**Issue by holylovelqq** [521xueweihan/HelloGitHub#622]
## 项目推荐
- 项目地址：https://github.com/holylovelqq/vue-unit-test-with-jest

- 类别：JS（Vue.js）

- 项目后续更新计划：在单独文件内mock axios和store，其他测试文件引入使用，完善其他细节

- 项目描述：
  - 必写：这是一个vue项目的单体测试教学项目，列出了vue开发时个人所能想到所有的需要测试的环节，并附有测试代码及说明文档
  - 可选：适用于vue项目单元测试，鉴于vue的普及度越来越高，相应的生态越来越完善，但是测试相关的技术文档却乏善可陈，正赶上自己项目中需要写单元测试，特此简单总结了写法思路，以供其他有需要的朋友交流学习。
  - 描述长度（不包含示例代码）: 鉴于vue的普及度越来越高，相应的生态越来越完善，但是测试相关的技术文档却乏善可陈，正赶上自己项目中需要写单元测试，特此简单总结了写法思路，以供其他有需要的朋友交流学习。

- 推荐理由：vue单元测试相关的技术文档很少，解决了vue开发者开始写单元测试无从下手的问题

- 示例代码：（可选）长度：1-20 行
```js
import { shallowMount, createLocalVue } from '@vue/test-utils'
import FilterTest from '@/components/FilterAddWatchTest.vue'

...

  // 测试内容：filter----filter不能通过wrapper或者vm获取，只能通过组件获取
  // filter需要测试函数的所有可能性
  it('filter test', () => {
    // console.log(FilterTest.filters)
    expect(FilterTest.filters.formatText('12345678')).toBe('12...78')
    expect(FilterTest.filters.formatText('12345')).toBe('12345')
    expect(FilterTest.filters.formatText()).toBe('')
  })

...

```

- 截图：（可选）gif/png/jpg

<img width="750" alt="スクリーンショット 2019-05-27 16 14 04" src="https://user-images.githubusercontent.com/34114975/58620147-5376a080-8301-11e9-89a3-b90d06d6f641.png">

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 40 期](https://hellogithub.com/periodical/volume/40/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
