### ISSUE TITLE
[自荐项目] - 成都房源分析

### ISSUE THREAD

**Issue by yhlben** [521xueweihan/HelloGitHub#624]
## 项目推荐

- 项目地址：https://github.com/yhlben/cdfang-spider
- 在线预览：https://cdfangyuan.cn

- 类别：TypeScript

- 项目后续更新计划：
  - 技术方面：完善 docker，k8s，微服务，serverless 等技术开源，真正做到一键发布。
  - 产品方面：增加除成都地区之外的房源分析，增加房价分析，以及根据反馈，进行其他功能支持。

- 项目描述：
  - 项目名称：成都房源统计，统计了成都开盘以来所有的房源信息，帮助想在成都买房的同学提供一些可视化的数据分析，比房协网官方的数据更直观，分析更透彻。
  - 学习价值：项目包含了一套完整的源代码，以及详细的[项目搭建文档](https://github.com/yhlben/cdfang-spider/blob/master/Introduction.md)，开发者可以根据搭建文档一步一步搭建这个项目。可以帮助开发者学习前端，后端，数据库端，单元测试，持续集成等全套知识。

- 推荐理由：不管你是想研究成都房源，还是想学习这一整套实战项目技术，都可以获得一定的收获。

- 截图：
![image](https://user-images.githubusercontent.com/13692434/58714204-d3326700-83f6-11e9-9ba2-a4feb96af469.png)

**Comment by ming995** [comment]
可以加一下在线预览地址

**Comment by yhlben** [comment]
已加， @ming995

**Comment by ming995** [comment]
@yhlben nice🤣

**Comment by hapiman** [comment]
可以弄个二手房

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
由于篇幅问题，您的项目将于下期推荐

**Comment by yhlben** [comment]
好的，谢谢！ @521xueweihan

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 40 期](https://hellogithub.com/periodical/volume/40/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
