### ISSUE TITLE
命令行的艺术（多语言版）

### ISSUE THREAD

**Issue by bsharkl** [521xueweihan/HelloGitHub#626]
## 项目推荐
- 项目地址：https://github.com/jlevy/the-art-of-command-line

- 类别：请从中选择（书籍）

- 项目后续更新计划：看原作者，不是本人的项目。

- 项目描述：
  - 必写：熟练使用命令行是一种常常被忽视，或被认为难以掌握的技能，但实际上，它会提高你作为工程师的灵活性以及生产力。本文是一份我在 Linux 上工作时，发现的一些命令行使用技巧的摘要。有些技巧非常基础，而另一些则相当复杂，甚至晦涩难懂。这篇文章并不长，但当你能够熟练掌握这里列出的所有技巧时，你就学会了很多关于命令行的东西了。
  - 可选：适这篇文章不仅能帮助刚接触命令行的新手，而且对具有经验的人也大有裨益。
  - 描述长度（不包含示例代码）: 涵盖范围：
本文致力于做到覆盖面广（涉及所有重要的内容），具体（给出具体的最常用的例子），以及简洁（避免冗余的内容，或是可以在其他地方轻松查到的细枝末节）。在特定应用场景下，本文的内容属于基本功或者能帮助您节约大量的时间。
本文主要为 Linux 所写，但在仅限 OS X 系统章节和仅限 Windows 系统章节中也包含有对应操作系统的内容。除去这两个章节外，其它的内容大部分均可在其他类 Unix 系统或 OS X，甚至 Cygwin 中得到应用。
本文主要关注于交互式 Bash，但也有很多技巧可以应用于其他 shell 和 Bash 脚本当中。
除去“标准的”Unix 命令，本文还包括了一些依赖于特定软件包的命令（前提是它们具有足够的价值）。
注意事项：适这篇文章不仅能帮助刚接触命令行的新手，而且对具有经验的人也大有裨益。

为了能在一页内展示尽量多的东西，一些具体的信息可以在引用的页面中找到。我们相信机智的你知道如何使用 Google 或者其他搜索引擎来查阅到更多的详细信息。文中部分命令需要您使用 apt-get，yum，dnf，pacman， pip 或 brew（以及其它合适的包管理器）来安装依赖的程序。
遇到问题的话，请尝试使用 Explainshell 去获取相关命令、参数、管道等内容的解释。

- 推荐理由：无意中看到这个项目，觉得很棒。不仅仅对于新手能学到很多，老司机也可读读看.

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

**Comment by 521xueweihan** [comment]
@bsharkl 您好，感谢您推荐项目，而且内容如此详细。

但是很遗憾，该项目在之前的月刊中已经推荐过：https://hellogithub.com/periodical/search/?q=https://github.com/jlevy/the-art-of-command-line#the-art-of-command-line

后面推荐项目的时候，可以先通过：https://hellogithub.com/ 首页的搜索功能搜索一下，推荐项目的地址是否已被推荐，从而减少重复推荐的情况发生。
