### ISSUE TITLE
一种能够展示应用程序拓扑结构的Docker＆Kubernetes监控工具

### ISSUE THREAD

**Issue by tony0705** [521xueweihan/HelloGitHub#627]
## 项目推荐
- 项目地址：https://github.com/weaveworks/scope

- 类别：Go

- 项目后续更新计划：当前最新版本1.11.1，6天前更新

- 项目描述：
  - 必写：Weave Scope能够自动生成应用程序的拓扑结构，使您能够直观地了解、监控和控制基于Docker＆Kubernetes的应用程序。
  - 可选：适用于什么场景、能够让初学者学到什么
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：清晰展示应用拓扑结构

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg
![](https://github.com/weaveworks/scope/blob/master/imgs/topology.png?raw=true)

**Comment by FrontMage** [comment]
收录至七月第二周

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 40 期](https://hellogithub.com/periodical/volume/40/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
