### ISSUE TITLE
zdog

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#628]
## 项目推荐
- 项目地址：

https://github.com/metafizzy/zdog.git

- 类别：JS

- 项目描述：

圆形，扁平，设计师友好的伪3D引擎

- 推荐理由：
js编写，入门简单，是少见的可编程式3D引擎。

- 示例代码：https://github.com/metafizzy/zdog#hello-world-demo

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
