### ISSUE TITLE
自托管RSS订阅系统（rsshub的完美伴侣)

### ISSUE THREAD

**Issue by bsharkl** [521xueweihan/HelloGitHub#629]
## 项目推荐
- 项目地址：https://github.com/FreshRSS/FreshRSS

- 类别：PHP

- 项目描述：
  - 必写：这是一个自托管的RSS阅读器，号称上万条订阅都不带卡顿。
  - 可选：与Rsshub搭配使用，完美解决RSS重度用户的痛点。
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：自托管你懂的，可分配多账户且支持第三方安卓/IOS客户端，支持FEVER API协议。对于RSS重度患者爱不释手。本人IOS平台使用的是Uread完美同步账户阅读流。

- 截图：http://tuchuang.bai-long.cn/bsharkl/20190607/P83v5lOfdbao.png

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 39 期](https://hellogithub.com/periodical/volume/39/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
