### ISSUE TITLE
安利一下我的h5 mock服务

### ISSUE THREAD

**Issue by chinesedfan** [521xueweihan/HelloGitHub#63]
## 项目推荐
- 项目名称：parrot-mocker-web

- 项目地址：https://github.com/chinesedfan/parrot-mocker-web

- 项目语言：Node.js

- 项目描述：小巧的mock服务器，配合Chrome插件可以轻松地拦截或mock页面上的xhr/jsonp/fetch请求。不需要侵入页面本身代码，让前端同学在后端接口没有ready或者难以模拟数据的时候，继续开心地开发玩耍。

- 推荐理由：
    - 项目提供的功能属于前端开发刚需，上手后可以解决日常开发痛点
    - 基于webpack2+koa+vue2实现，代码简单易懂，非常适合新手学习

- 截图：
<img src="https://github.com/chinesedfan/parrot-mocker-web/raw/master/pic/3.3.list.png" width="80%">

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功收录**在 [HelloGitHub 第 17 期](https://github.com/521xueweihan/HelloGitHub/blob/master/content/17/HelloGitHub17.md)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，如果方便可以 Star ⭐️ 本项目，让更多人看到本项目。
