### ISSUE TITLE
每天一句微信暖心话

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#630]
## 项目推荐
- 项目地址：

https://github.com/sfyc23/EverydayWechat

- 类别：Python

- 项目后续更新计划：

- 项目描述：
 定时通过wechat给对象发送每日天气、提醒、每日一句。

- 推荐理由：

程序员的浪漫你值得拥有，对于微信接口开发、爬虫开发有借鉴意义。

- 截图：

[运行截图](https://camo.githubusercontent.com/7b2d825d81abb69c08e949492163423bf8f907aa/687474703a2f2f766c6f672e7366796332332e78797a2f7765636861745f65766572796461792f32303139303331323031303632302e706e67)
[效果图](https://camo.githubusercontent.com/08006b9fa8655e9bc1661364c54baf19fc52ec2f/687474703a2f2f766c6f672e7366796332332e78797a2f7765636861745f65766572796461792f32303139303331323031303632312e706e67)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
