### ISSUE TITLE
C++实现的基于对象的高并发网络库——muduo

### ISSUE THREAD

**Issue by ZhimingYan** [521xueweihan/HelloGitHub#631]
## 项目推荐
- 项目地址：http://github.com/chenshuo/muduo

- 类别：C++

- 项目描述：
  - 这是一个由C++编写的，基于对象编程的非阻塞IO和事件驱动的C++网络库，实现了对底层系统调用的封，高性能异步日志的设计，Reactor多线程并发模式设计，以及简单的http协议的解析
  - muduo网络库适合开发Linux下的面向业务的多线程服务端应用程序，不仅如此，还适合C++语言、Linux网络编程等后台知识的学习

- 推荐理由：C++后台开发实战项目的源码学习

- 示例代码：

```cpp
#include "examples/simple/echo/echo.h"

#include "muduo/base/Logging.h"
#include "muduo/net/EventLoop.h"

#include <unistd.h>

// using namespace muduo;
// using namespace muduo::net;

int main()
{
  LOG_INFO << "pid = " << getpid();
  muduo::net::EventLoop loop;
  muduo::net::InetAddress listenAddr(2007);
  EchoServer server(&loop, listenAddr);
  server.start();
  loop.loop();
}
```

**Comment by 521xueweihan** [comment]
@ChungZH 这个项目看看，我觉得很好。能否收录到本期中？

**Comment by ChungZH** [comment]
> @ChungZH 这个项目看看，我觉得很好。能否收录到本期中？

我尽量。

**Comment by ChungZH** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 40 期](https://hellogithub.com/periodical/volume/40/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
