### ISSUE TITLE
JS文件上传库

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#634]
## 项目推荐
- 项目地址： https://github.com/pqina/filepond

- 类别：JS

- 项目描述：
  一个JavaScript库，可以上传您抛出的任何内容，优化图像以加快上传速度，并提供出色的，可访问的，如丝般顺畅的用户体验。

- 推荐理由：

压缩后仅21 KB.， 十分轻量，支持React, Vue, Angular 以及 jQuery。

- 截图：
![a.png](https://github.com/pqina/filepond-github-assets/blob/master/filepond-animation-01.gif?raw=true)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 39 期](https://hellogithub.com/periodical/volume/39/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
