### ISSUE TITLE
添加「恶意 issue 提交者黑名单」

### ISSUE THREAD

**Issue by ChungZH** [521xueweihan/HelloGitHub#638]
恶意 issue 越来越多了。。。是时候列一个清单出来了

**Comment by ChungZH** [comment]
@521xueweihan :joy:

**Comment by ming995** [comment]
@ChungZH 这个名单没啥意义啊，恶意的好像都是新注册的号

**Comment by ChungZH** [comment]
> @ChungZH 这个名单没啥意义啊，恶意的好像都是新注册的号

（我觉得还是可以考虑下吧

**Comment by 521xueweihan** [comment]
@ChungZH 提交恶意 issues 的用户都是新号，关闭 issues 就可以了。

当然也不排除有人误操作
