### ISSUE TITLE
【自荐项目】一个简洁而优雅的Android原生UI框架

### ISSUE THREAD

**Issue by xuexiangjys** [521xueweihan/HelloGitHub#640]
## 项目推荐
- 项目地址：
https://github.com/xuexiangjys/XUI

- 类别：Java-Android

- 项目后续更新计划：
完善组件使用

- 项目描述：
XUI是一个简洁而又优雅的Android原生UI框架，涵盖绝大部分的UI组件：TextView、Button、EditText、ImageView、Spinner、Picker、Dialog、PopupWindow、ProgressBar、LoadingView、StateLayout、FlowLayout、Switch、Actionbar、TabBar、Banner、GuideView、BadgeView、MarqueeView、WebView、SearchView等一系列的组件和丰富多彩的样式主题。
目的：让原生Android开发人员也能像web开发者一样，有自己的UI库，简便UI的实现。
适用于有过一年开发经验的Android开发者。

- 推荐理由：
拥有丰富的UI组件，完善的文档，能够满足日常开发的绝大多数需求，UI整体统一。

- 示例代码：
见主页

- 截图：（可选）gif/png/jpg
![在这里插入图片描述](https://img-blog.csdnimg.cn/20190116142606690.png) ![在这里插入图片描述](https://img-blog.csdnimg.cn/20190116142641122.png)  ![在这里插入图片描述](https://img-blog.csdnimg.cn/20190116142713201.png) ![在这里插入图片描述](https://img-blog.csdnimg.cn/20190116142816600.png) ![在这里插入图片描述](https://img-blog.csdnimg.cn/20190116142827869.png) ![在这里插入图片描述](https://img-blog.csdnimg.cn/2019011614283898.png) ![在这里插入图片描述](https://img-blog.csdnimg.cn/20190116142846941.png) ![在这里插入图片描述](https://img-blog.csdnimg.cn/20190116142854297.png) ![在这里插入图片描述](https://img-blog.csdnimg.cn/20190116142901928.png) ![在这里插入图片描述](https://img-blog.csdnimg.cn/20190116142910561.png) ![在这里插入图片描述](https://img-blog.csdnimg.cn/20190116142919551.png) ![在这里插入图片描述](https://img-blog.csdnimg.cn/20190116142928113.png) ![在这里插入图片描述](https://img-blog.csdnimg.cn/20190116142936464.png) ![在这里插入图片描述](https://img-blog.csdnimg.cn/20190116142943863.png) ![在这里插入图片描述](https://img-blog.csdnimg.cn/20190116142951126.png) ![在这里插入图片描述](https://img-blog.csdnimg.cn/20190116142958814.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 41 期](https://hellogithub.com/periodical/volume/41/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了《讲解开源项目》系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
