### ISSUE TITLE
C# 国产ORM当自强——FreeSql

### ISSUE THREAD

**Issue by 2881099** [521xueweihan/HelloGitHub#641]
## 项目推荐
- 项目地址：https://github.com/2881099/FreeSql

- 类别：C#

- 项目后续更新计划：实现类似 sharding 的功能

- 项目描述：

FreeSql 是一个功能强大的对象关系映射程序(O/RM)，支持 .NETCore 2.1+ 或 .NETFramework 4.5+
CodeFirst 开发模式下，开箱即用。

 1、支持 CodeFirst 迁移；
 2、支持 DbFirst 从数据库导入实体类，提供失血、贫血、充血三种生成模板；
 3、大量采用 ExpressionTree 技术提升性能；
 4、支持深入的类型映射，比如pgsql的数组类型，堪称匠心制作；
 5、支持丰富的表达式函数；
 6、支持导航属性查询，和延时加载；
 7、支持同步/异步数据库操作方法，链式查询方法；
 8、支持读写分离、分表分库，租户设计，过滤器，乐观锁；
 9、支持多种数据库，MySql/SqlServer/PostgreSQL/Oracle/Sqlite；

- 推荐理由：

扶摇直上，至强ORM只为自由编码；鹏程万里，至简Linq可使保留黑发；横批：FreeSql（诗人：Coder）

- 示例代码：

```csharp
var t0 = fsql.Select<Tag>()
    .Where(a => a.Parent.Parent.Name == "粤语")
    .IncludeMany(a => a.Tags, then => then.Where(sub => sub.Name == "xxx"))
    .ToList();

var t3 = fsql.Select<Xxx>()
    .Where(a => a.IsDelete == 0)
    .WhereIf(keyword != null, a => a.UserName.Contains(keyword))
    .WhereIf(role_id > 0, a => a.RoleId == role_id)
    .Where(a => a.Nodes.AsSelect().Any(t => t.Parent.Id == t.UserId))
    .Count(out var total)
    .Page(page, size)
    .OrderByDescending(a => a.Id)
    .ToList()
```

**Comment by iamoldli** [comment]
叶老板速度可以啊~

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 39 期](https://hellogithub.com/periodical/volume/39/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

为了让开源项目的发起者不再孤单，我们决定牵线搭桥。可以加我微信：xueweihan（备注您发起的项目链接）
待时机成熟，你会发现你并不孤独！
