### ISSUE TITLE
支持三框架的前端表格组件-GridManager

### ISSUE THREAD

**Issue by baukh789** [521xueweihan/HelloGitHub#643]
## 项目推荐
- 项目地址：https://github.com/baukh789/GridManager

- 类别：JS

- 项目后续更新计划：
     - select组件开发
     - 列内容相同项合并功能
     - 固定列功能
     - 树层结构表格
     - 将同类参数进行合并

- 项目描述：
这是一个原生表格组件，基础类库为[jTool](https://github.com/baukh789/jTool)。在原生组件基础上封装了[React](https://github.com/baukh789/GridManager-React), [Angular-1.x](https://github.com/baukh789/GridManager-Angular-1.x), [Vue](https://github.com/baukh789/GridManager-Vue)三个版本，从而可以在不同的框架中使用相同的方式进行开发。

- 功能描述
| 功能 | 描述 | 
| -: | :- | 
| 宽度调整 | 表格的列宽度可进行拖拽式调整 | 
| 位置更换 | 表格的列位置进行拖拽式调整 |
| 配置列 | 可通过配置对列进行显示隐藏转换 |
| 表头吸顶 | 在表存在可视区域的情况下,表头将一直存在于顶部 |
| 排序 | 表格单项排序或组合排序 |
| 分页 | 表格ajax分页,包含选择每页显示总条数和跳转至指定页功能 |
| 用户偏好记忆 | 记住用户行为,含用户调整的列宽、列顺序、列可视状态及每页显示条数 |
| 序号 | 自动生成序号列 |
| 全选 | 自动生成全选列 |
| 导出 | 当前页数据下载,和仅针对已选中的表格下载 |
| 右键菜单 | 常用功能在菜单中可进行快捷操作 |
| 过滤 | 通过对列进行过滤达到快速搜索效果 |

- 推荐理由：快速、灵活的对Table标签进行实例化，让Table标签充满活力。

- 示例代码：
```html
<table></table>
```
```javascript
document.querySelector('table').GM({
    gridManagerName: 'demo-baseCode',
    ajax_url: 'https://www.lovejavascript.com/learnLinkManager/getLearnLinkList',
    ajax_type: 'POST',
    query: {pluginId: 1},
    columnData: [
        {
            key: 'name',
            text: '名称'
        },{
            key: 'info',
            text: '使用说明'
        },{
            key: 'url',
            text: 'url'
        }
    ]
});
```

- 截图：
![image](https://s2.ax1x.com/2019/04/16/AxA4xK.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
