### ISSUE TITLE
自荐项目 - ImageMiniLab 

### ISSUE THREAD

**Issue by itisyang** [521xueweihan/HelloGitHub#644]
## 项目推荐
- 项目地址：https://github.com/itisyang/ImageMiniLab

- 类别：Python

- 项目后续更新计划：完善各种cv图像算法，用qt演示。

- 项目描述：图像迷你实验室，可进行图像实验，图像处理，图像分析。  

- 推荐理由：使用 PyQt5 结合 opencv-python，代码简洁，适合cv入门学习，快速演示图像算法效果。

- 截图：
![logo](https://raw.githubusercontent.com/itisyang/ImageMiniLab/master/ImageMiniLab.png)

**Comment by Eurus-Holmes** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by itisyang** [comment]
谢谢

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 39 期](https://hellogithub.com/periodical/volume/39/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

为了让开源项目的发起者不再孤单，我们决定牵线搭桥。可以加我微信：xueweihan（备注您发起的项目链接）
待时机成熟，你会发现你并不孤独！
