### ISSUE TITLE
【自荐项目】自由钢琴 AutoPiano - 优雅的在线钢琴应用

### ISSUE THREAD

**Issue by WarpPrism** [521xueweihan/HelloGitHub#645]
## 项目推荐
- 项目地址：https://github.com/WarpPrism/AutoPiano
- Demo地址： http://www.autopiano.cn

- 类别：JavaScript、CSS、Vue

- 项目后续更新计划：
1、实现midi解析，并映射为钢琴键位 
2、推出钢琴入门教程  
3、增加多种音色
4、提升应用趣味性

- 项目描述：

> 自由钢琴（AutoPiano）是利用HTML5技术开发的在线钢琴应用，致力于为钢琴爱好者、音乐爱好者以及其他所有的创造者提供一个优雅、简洁的平台，在学习工作之余可以享受钢琴、音乐的美好。就类似于多年前Flash开发的钢琴游戏，自由钢琴只是换了H5的技术，同时支持了钢琴曲的自动播放功能。
> AutoPiano支持键盘按键和鼠标点击播放，同时琴键上会有按键和音名提示。另外，AutoPiano还有教学的功能，一种方式是快速入门，通过简易的谱子按键进行演奏，另一种是演奏示例，通过钢琴曲的自动播放来达到演示的目的。
> AutoPiano的亮点是实现对musicxml或midi的解析，实现钢琴曲自动播放。

- 示例代码：

~~~js
export default [
  {
    name: `祝你生日快乐`,
    content: `oopo sa<br> oopo ds <br> oo h f s a p<br> gg f s d s<br>
              oopo sa<br> oopo ds <br> oo h f s a p<br> gg f s d fs`,
    degree: 1,
    lyrics: `Happy Birthday to You <br>
            Happy Birthday to You<br>
            Happy Birthday to You <br>
            Happy Birthday to You <br>`,
    author: '棱镜jh',
    authorLink: 'https://github.com/WarpPrism/AutoPiano'
  }
]
~~~

- 截图：

![autopiano.png](https://i.loli.net/2019/05/24/5ce7c48ce8c1093923.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 39 期](https://hellogithub.com/periodical/volume/39/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
