### ISSUE TITLE
GithubMonitor 项目推荐

### ISSUE THREAD

**Issue by Macr0phag3** [521xueweihan/HelloGitHub#646]
## 项目推荐
- 项目地址：https://github.com/Macr0phag3/GithubMonitor

- 类别：Python/信息安全
- 项目后续更新计划：无

- 项目描述：根据关键字与 hosts 生成的关键词，利用 github 提供的 api，监控 git 泄漏。

- 推荐理由：简单却完善

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
