### ISSUE TITLE
自荐项目：BackgroundLibrary Android UI框架

### ISSUE THREAD

**Issue by JavaNoober** [521xueweihan/HelloGitHub#648]
## 项目推荐
- 项目地址：
[https://github.com/JavaNoober/BackgroundLibrary](https://github.com/JavaNoober/BackgroundLibrary).
- 类别：JAVA
- star：1700+ 
- 项目后续更新计划：
除了原生属性的支持外，提供更多支持属性
- 项目描述：
  完全与Android原生ui控件相结合的shape、selector添加方式，无须任何代码直接依赖使用即可，可以省去原生的大量shape、selector的xml文件

- 推荐理由：
原生Android设置ui背景需要写很多重复相似的xml文件，而该框架依赖之后完全无须代码，直接可以添加属性生成背景，不同于自定义View更加的方便简单。

- 示例代码：
使用效果完全和原生shape 
selector一样，但是只需要直接在xml中加入属性即可，例如

        <TextView
            android:id="@+id/ttt"
            android:layout_width="130dp"
            android:layout_height="36dp"
            android:layout_marginTop="5dp"
            android:gravity="center"
            android:text="TextView"
            android:textColor="#8c6822"
            android:textSize="20sp"
            app:bl_corners_radius="4dp"
            app:bl_solid_color="#E3B666"
            app:bl_stroke_color="#8c6822"
            app:bl_stroke_dashGap="5dp"
            app:bl_stroke_dashWidth="10dp"
            app:bl_stroke_width="2dp" />

- 截图：
![](https://raw.githubusercontent.com/JavaNoober/BackgroundLibrary/master/test/show.gif)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
