### ISSUE TITLE
Intellij摸鱼插件

### ISSUE THREAD

**Issue by MUedsa** [521xueweihan/HelloGitHub#649]
## 项目推荐
- 项目地址：[https://github.com/MUedsa/TextReaderSiderTool](https://github.com/MUedsa/TextReaderSiderTool)

- 类别：Java

- 项目后续更新计划：完善功能

- 项目描述： 在Intellij系列IDE中添加一个查看文本的工具窗口，可以按前后缀字符分割章节，改变字体大小等。

- 推荐理由：一时摸鱼一时爽，一直摸鱼炒鱿鱼

- 截图：
![](https://github.com/MUedsa/TextReaderSiderTool/blob/master/temp.gif?raw=true)

**Comment by CasualJi** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
