### ISSUE TITLE
程序员工作中常见的英语词汇

### ISSUE THREAD

**Issue by ChungZH** [521xueweihan/HelloGitHub#650]
## 项目推荐
- 项目地址：
https://github.com/Wei-Xia/most-frequent-technology-english-words
- 类别：其它

- 项目后续更新计划：

- 项目描述：本列表中的单词是英语类计算机书籍、文档、文章中高频常见的技术词汇，最终目的是希望程序员集合自身的英语基础，在掌握列表中的词汇后，可以无障碍阅读英语技术文章和文档。

- 推荐理由：帮助新手程序员更好地入坑。

- 示例代码：

- 截图：由于本人太懒，所以没有。。

**Comment by XiangWx** [comment]
发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Haoshen Zhong <notifications@github.com>
发送时间: 2019年6月21日 13:34
收件人: 521xueweihan/HelloGitHub <HelloGitHub@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[521xueweihan/HelloGitHub] 程序员工作中常见的英语词汇 (#650)




项目推荐


项目地址：
https://github.com/Wei-Xia/most-frequent-technology-english-words



类别：其它



项目后续更新计划：



项目描述：本列表中的单词是英语类计算机书籍、文档、文章中高频常见的技术词汇，最终目的是希望程序员集合自身的英语基础，在掌握列表中的词汇后，可以无障碍阅读英语技术文章和文档。



推荐理由：帮助新手程序员更好地入坑。



示例代码：



截图：由于本人太懒，所以没有。。

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 39 期](https://hellogithub.com/periodical/volume/39/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
