### ISSUE TITLE
数学动画生成引擎

### ISSUE THREAD

**Issue by xiaoxiaopingzi** [521xueweihan/HelloGitHub#652]
## 项目推荐
- 项目地址：https://github.com/3b1b/manim

- 类别：Python

- 项目后续更新计划：项目一直在更新中

- 项目描述：manim是一个生成数学教学视频的动画引擎。 它用编程的方式创建精美的数学动画，如3Blue1Brown的视频中所展示的。

- 推荐理由：可以生成酷炫的数学动画

- 截图：
![image](https://user-images.githubusercontent.com/20459496/59962855-81748c80-951d-11e9-8723-6e29f4889b29.png)

**Comment by 521xueweihan** [comment]
感觉入门门槛有点高，但决定收录。师父领进门，修行靠个人。

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 39 期](https://hellogithub.com/periodical/volume/39/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
