### ISSUE TITLE
简洁的 Mac 图床客户端 uPic

### ISSUE THREAD

**Issue by gee1k** [521xueweihan/HelloGitHub#653]
## 项目推荐
- 项目地址：[https://github.com/gee1k/uPic](https://github.com/gee1k/uPic)

- 类别：Swift

- 项目后续更新计划：支持更多图床服务，带来更好的使用体验

- 项目描述：
  - 必写：按照自定义规则上传图片、文件到云储存服务器、图床，并自动将最终访问URL复制到剪切板
  - 可选：适用于什么场景、能够让初学者学到什么
  - 描述长度（不包含示例代码）: 能让你再写文章、写博客、论坛闲聊时快速的上传图片到图床并将 URL 自动复制到剪切板，让你贴图不在复杂

- 推荐理由：能让你再写文章、写博客、论坛闲聊时快速的上传图片到图床并将 URL 自动复制到剪切板，让你贴图不在复杂。并支持直接输出 HTML 标签， Markdown 标签

- 截图：

![selectFile](https://s2.svend.cc/projects/uPic/upload/selectFile.gif)
![paste](https://s2.svend.cc/projects/uPic/upload/paste.gif)
![drag](https://s2.svend.cc/projects/uPic/upload/drag.gif)
![screenshot](https://s2.svend.cc/projects/uPic/upload/screenshot.gif)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 40 期](https://hellogithub.com/periodical/volume/40/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
