### ISSUE TITLE
A linux terminal online dictionary based on Cambridge online

### ISSUE THREAD

**Issue by xueyuanl** [521xueweihan/HelloGitHub#654]
## A linux terminal online dictionary based on Cambridge online
- 项目地址：https://github.com/xueyuanl/cambrinary

- 类别：Python

- 项目后续更新计划：不断完善；开发牛津版

- 项目描述：
  - 终端版在线剑桥词典
  - linuxer
  - 喜欢剑桥原汁原味的解释内容
  - 厌倦金山有道的有损翻译。

- 推荐理由：linuxer必备

![hello](https://user-images.githubusercontent.com/15186846/59993022-26f44100-9681-11e9-9da3-477ed23fbf61.PNG)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
