### ISSUE TITLE
开源项目：前端面试每日3+1

### ISSUE THREAD

**Issue by haizhilin2013** [521xueweihan/HelloGitHub#657]
## 项目推荐
- 项目地址：https://github.com/haizlin/fe-interview

- 类别：JS

- 项目后续更新计划：
每天早上4点半-5点之间纯手工更新（365天无节假日，目前已坚持更新第71天）

- 项目描述：
  - 必写：这是一个前端的开源项目，每天出4个基础题目，坚持每天花20分钟来学习与思考！
  - 可选：适用于所有前端开发人员提升自我！在这里能学到独立思考，充实自己，积累知识。
  - 描述：不积跬步，无以至千里；不积小流，无以成江海。

- 推荐理由：以面试题来驱动学习，提倡每日学习与思考，日积月累，每天进步一点！相信坚持的力量！让努力成为一种习惯，让奋斗成为一种享受！

- 示例代码：
  - 今天的面试题 (2019.06.26) —— 第71天
    - [html] [怎么在IE8及以下实现HTML5的兼容？](https://github.com/haizlin/fe-interview/issues/502)  
    - [css] [你对响应式设计的理解是什么？知道它基本的原理是吗？要想兼容低版本的IE怎么做呢？](https://github.com/haizlin/fe-interview/issues/503)  
    - [js] [说说你对深浅拷贝的理解？并实现一个对数组和对象深拷贝的方法](https://github.com/haizlin/fe-interview/issues/504)  
    - [软技能] [做了这么多年开发，说说你最大的感悟是什么？](https://github.com/haizlin/fe-interview/issues/505)  

- 截图：

![image](https://user-images.githubusercontent.com/5070345/60137097-8ca71100-97d8-11e9-99b1-2d31366d5282.png)
![image](https://user-images.githubusercontent.com/5070345/60137134-a21c3b00-97d8-11e9-93cd-517b7ca47d92.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 39 期](https://hellogithub.com/periodical/volume/39/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

为了让开源项目的发起者不再孤单，我们决定牵线搭桥。可以加我微信：xueweihan（备注您发起的项目链接）
待时机成熟，你会发现你并不孤独！
