### ISSUE TITLE
RedisCX 最智能的跨平台Redis桌面工具

### ISSUE THREAD

**Issue by Sidfate** [521xueweihan/HelloGitHub#658]
## 项目推荐
- 项目地址：https://github.com/Sidfate/RedisCX

- 类别：JS

- 项目后续更新计划：
  - 支持集群连接
  - 支持多窗口界面
  - 支持自带shell操作

- 项目描述：
  - 必写：Redis的跨平台桌面软件
  - 可选：操作大数据量db，频繁使用redis

- 推荐理由：
  - 解决了几乎所有其他同类软件的一个通病：大数据量的db打开速度慢的问题。通过一个人性化的操作，让用户可选择的查询解决了这个问题。
  - 更加简明亲民的ui。
  - 绝对的最智能，包括可以自定义db的标签，快速置顶，快速搜索。

- 示例代码：

- 截图：

![](https://camo.githubusercontent.com/beedef503e959deaac1a4ed6f6e7964584781fcd/68747470733a2f2f692e6c6f6c692e6e65742f323031382f30382f32392f356238363461323037613738622e706e67)

![](https://camo.githubusercontent.com/a7608cbeccc2850aea2c5ca68b87d719d89954f6/68747470733a2f2f692e6c6f6c692e6e65742f323031382f31302f31362f356263353465393964643330362e706e67)

![](https://camo.githubusercontent.com/a38166720286408faddbfaa4c17cb210b80cea60/68747470733a2f2f692e6c6f6c692e6e65742f323031382f30382f32392f356238363461323037633730642e706e67)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
