### ISSUE TITLE
一个提供开发中常用数据的一个稳定聚合Api接口源，运行于独立服务器，免费，且长期维护，会持续添加新的接口！ 

### ISSUE THREAD

**Issue by MZCretin** [521xueweihan/HelloGitHub#659]
## 项目推荐
- 项目地址：https://github.com/MZCretin/RollToolsApi

- 类别：Java

- 项目后续更新计划：持续添加新的好用接口

- 项目描述：
  - 必写：一个提供开发中常用数据的一个稳定聚合Api接口源，免费，稳定，支持https请求
  - 可选：无论是Android，iOS，小程序都可直接调用接口使用，且不收费
  - 描述长度（不包含示例代码）: 一个提供开发中常用数据的一个稳定聚合Api接口源，运行于独立服务器，免费，且长期维护，会持续添加新的接口！ 

- 推荐理由：聚合接口，免费，稳定，独立服务器，交流群

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
