### ISSUE TITLE
GithubMonitor: 监控 GitHub 的信息泄露

### ISSUE THREAD

**Issue by Macr0phag3** [521xueweihan/HelloGitHub#661]
项目推荐

项目地址：https://github.com/Macr0phag3/GithubMonitor

类别：Python/信息安全

项目后续更新计划：无

项目描述：由于很多猪队友的存在，公司敏感信息通过 GitHub 泄露出去是很常见的。这个项目主要根据关键字与 hosts 生成的关键词，利用 github 提供的 api，监控 git 泄漏，并在检测到信息泄露的时候发送邮件通知。

推荐理由：
- 对于泄露有对应的泄漏定级，可作为严重性的参考
- 简单却完善：利用 api 获取 GitHub 的搜索结果是最简单高效的方式，加上关键词的限定，保证不超过 GitHub 的 api 限制
- 注释比较详细，可以很快地进行定制
- 自动组合关键字

**Comment by 521xueweihan** [comment]
@Macr0phag3 原来是修改了 Readme 和推荐描述，赞👍

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 39 期](https://hellogithub.com/periodical/volume/39/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

为了让开源项目的发起者不再孤单，我们决定牵线搭桥。可以加我微信：xueweihan（备注您发起的项目链接）
待时机成熟，你会发现你并不孤独！
