### ISSUE TITLE
webtorrent基于js的流媒体torrent种子客户端，无需下载可直接播放

### ISSUE THREAD

**Issue by xmyl** [521xueweihan/HelloGitHub#663]
## 项目推荐
- 项目地址：https://github.com/webtorrent/webtorrent

- 类别：JS

- 项目描述：
  - 必写：一个基于JS的流媒体种子客户端，不需要等待种子中的内容下载完毕，就可以马上播放种子中的内容。
  - 可选：不需要等待内容下载完成，就可以播放种子内容，目前Windows、Mac和Linux都支持

- 推荐理由：很实用、支持多个不同的操作系统

没有截图，可以进入项目地址看看相关的介绍，挺实用的。

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 41 期](https://hellogithub.com/periodical/volume/41/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
