### ISSUE TITLE
C# .NETCore斗地主服务端 + HTML5前端——FightLandlord

### ISSUE THREAD

**Issue by 2881099** [521xueweihan/HelloGitHub#665]
## 项目推荐
- 项目地址：https://github.com/2881099/FightLandlord

- 类别：请从中选择（C#）

- 项目后续更新计划：完成机器智能出牌

- 项目描述：
  - 必写：项目采用.NETCore跨平台技术，实现斗地主服务端规则玩法，后期更有可能完成机器人打牌的功能。
  - 描述长度（不包含示例代码）: 项目最终目标为AI斗地主，机器人最优方案对打。项目谥在学习，任何用于违法用途的行为与作者无关。目前尚处于研阶段，为了方便测试，HTML5做成了单机方式运行，但这不影响后期部署成多端游戏。已实现功能有，洗牌、发牌、抢地主、斗地主、（游戏环节）、提示出牌、游戏结束。

- 推荐理由：.NETCore 作为新型跨平台技术，缺少像斗地主这类游戏的开源库。

- 截图：

![image](https://user-images.githubusercontent.com/16286519/60312193-f36d2b80-998c-11e9-8859-309a42a45248.png)

**Comment by 521xueweihan** [comment]
老哥，你抗起了我们的 C# 专栏

**Comment by 2881099** [comment]
> 老哥，你抗起了我们的 C# 专栏

我的仓库还有点存货，估计还有再申请几期 =_=

**Comment by 521xueweihan** [comment]
> > 老哥，你抗起了我们的 C# 专栏
> 
> 我的仓库还有点存货，估计还有再申请几期 =_=

强 👍👍

**Comment by ddzy** [comment]
这个牛逼

**Comment by crazygreenapple** [comment]
这个好玩

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 40 期](https://hellogithub.com/periodical/volume/40/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
