### ISSUE TITLE
gecko

### ISSUE THREAD

**Issue by bbaobelief** [521xueweihan/HelloGitHub#666]
## 项目推荐
- 项目地址：https://github.com/bbaobelief/gecko

- 类别：Python

- 项目后续更新计划：

- 项目描述：
  - 必写：python爬虫集合，收录喜欢的壁纸，电影
  - 描述长度（不包含示例代码）: 收录喜欢的壁纸，deepin下自动换壁纸。

- 推荐理由：

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

### 编辑完推荐项目的信息，**请删除**下述提示信息
1. [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271)

2. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

3. HelloGitHub 网站：https://hellogithub.com

再次感谢您对《HelloGitHub》项目的支持！

**Comment by bbaobelief** [comment]
update

**Comment by smart2pet** [comment]
@521xueweihan This isn't a bad issue. Please review here. Thanks.
