### ISSUE TITLE
gecko

### ISSUE THREAD

**Issue by bbaobelief** [521xueweihan/HelloGitHub#667]
## 项目推荐
- 项目地址：https://github.com/bbaobelief/gecko

- 类别：Python

- 项目后续更新计划：有喜欢的资源就会更新。

- 项目描述：
  - 必写：python爬虫集合，收录喜欢的壁纸，电影
  - 描述长度（不包含示例代码）: 收录喜欢的壁纸，deepin下自动换壁纸。

- 推荐理由：资源爬虫

- 示例代码：cd 项目 && python run.py

- 截图：无

**Comment by 521xueweihan** [comment]
嗯，我看了下您的项目。现在暂时不能推荐，可以丰富内容后再次推荐。
