### ISSUE TITLE
[bug]39期，Arrow项目代码块不建议指定语言类型

### ISSUE THREAD

**Issue by buppter** [521xueweihan/HelloGitHub#669]
这儿指定代码块语言为python会有点问题，可以不写语言，或者语言改为shell
![微信截图_20190628171502](https://user-images.githubusercontent.com/43202996/60332080-9db67480-99c8-11e9-9a5a-fce3d4dc3c6d.png)

**Comment by 521xueweihan** [comment]
@buppter 收到，感谢反馈。立马修复

**Comment by 521xueweihan** [comment]
@buppter 已修复
