### ISSUE TITLE
Golang访问控制开源库Casbin

### ISSUE THREAD

**Issue by hsluoyz** [521xueweihan/HelloGitHub#67]
## 项目推荐
- 项目名称：Casbin

- 项目地址：https://github.com/casbin/casbin

- 项目语言：Go

- 项目描述：访问控制开源库，支持ACL/RBAC/ABAC等访问控制模型，支持MySQL/NoSQL等策略存储方式。

- 推荐理由：目前做到了Go访问控制领域的第一名

- 示例代码：
```go
e := casbin.NewEnforcer("path/to/model.conf", "path/to/policy.csv")

sub := "alice" // the user that wants to access a resource.
obj := "data1" // the resource that is going to be accessed.
act := "read" // the operation that the user performs on the resource.

if e.Enforce(sub, obj, act) == true {
    // permit alice to read data1
} else {
    // deny the request, show an error
}
```
- 截图：

![casbin-logo](https://user-images.githubusercontent.com/3787410/28065221-4a351642-666a-11e7-9af2-73dabb2a5c82.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功收录**在 [HelloGitHub 第 17 期](https://github.com/521xueweihan/HelloGitHub/blob/master/content/17/HelloGitHub17.md)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，如果方便可以 Star ⭐️ 本项目，让更多人看到本项目。
