### ISSUE TITLE
Valine - 一款快速、简洁且高效的无后端评论系统

### ISSUE THREAD

**Issue by buppter** [521xueweihan/HelloGitHub#670]
## 项目推荐
- 项目地址：
https://github.com/xCss/Valine

- 类别：JavaScript 

- 项目后续更新计划：
目前仍在更新状态中

- 项目描述：
Valine，是一款使用 LeanCloud 存储数据的快速、简洁且高效的无后端评论系统。

- 推荐理由：
对于使用 Hexo、Hugo 等静态网页博客的人来说，Valine 简直就是福音。它美观、简洁，实现了评论的功能。它还支持 **Markdown 和 Emoji**！

- 示例代码：
无

- 截图：
![微信截图_20190628194752](https://user-images.githubusercontent.com/43202996/60340296-b5e4be80-99dd-11e9-86cb-199ce63a54ca.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 41 期](https://hellogithub.com/periodical/volume/41/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了《讲解开源项目》系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
