### ISSUE TITLE
Nps 一款轻量级、功能强大的内网穿透代理服务器

### ISSUE THREAD

**Issue by bsharkl** [521xueweihan/HelloGitHub#671]
## 项目推荐
- 项目地址：https://github.com/cnlh/nps

- 类别：Go

- 项目后续更新计划：

- 项目描述：
  - 必写：一款轻量级、功能强大的内网穿透代理服务器。支持tcp、udp流量转发，支持内网http代理、内网socks5代理，同时支持snappy压缩、站点保护、加密传输、多路复用、header修改等。支持web图形化管理，集成多用户模式。

- 推荐理由：frp之外另一个不错的内网穿透解决方案，且图形化，交互友好。

- 截图：
![image](https://user-images.githubusercontent.com/17378745/60356299-38cc4000-9a03-11e9-8f85-30cab2387db7.png)

**Comment by FrontMage** [comment]
收录至七月第二周

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 40 期](https://hellogithub.com/periodical/volume/40/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
