### ISSUE TITLE
Python 工匠

### ISSUE THREAD

**Issue by leaicc** [521xueweihan/HelloGitHub#672]
## 项目推荐
- 项目地址：https://github.com/piglei/one-python-craftsman

- 类别：Python

- 项目后续更新计划：持续更新

- 项目描述：
  - 真正优秀的代码，正是由无数优秀的细节造就的。这个 repo 就是着眼于 Python 那些『小』的细节，比如何时使用异常（Exceptions）、或怎么给变量起名、怎么编写条件分支等等，以小见大，简单的也是最难的。

- 推荐理由：我一直觉得编程某种意义上是一门『手艺』，因为优雅而高效的代码，就如同完美的手工艺品一样让人赏心悦目。所以如果你想写出『优雅』的代码，那就从那些小的细节开始吧。

- 截图：![](https://i.loli.net/2019/07/01/5d197159983f039342.jpg)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 40 期](https://hellogithub.com/periodical/volume/40/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
