### ISSUE TITLE
基于 react hooks 实现的极简全局状态管理库

### ISSUE THREAD

**Issue by masx200** [521xueweihan/HelloGitHub#677]
## 项目推荐
- 项目地址：
https://github.com/masx200/react-simple-global-state-store-hook
- 类别：

javascript

- 项目后续更新计划：

- 项目描述：
基于 react hooks 实现的极简全局状态管理库，可以跨组件共享全局状态
仅仅使用 44 行代码写成的极简 react 全局状态管理库!

- 推荐理由：
跟 redux 对比,极为简洁!抛弃 redux！
redux主要由store,action,reducer等等组成,过于庞大负杂,繁琐

react-simple-global-state-store-hook只管理状态仓库,修改全局状态的方法返回给组件内部调用,就跟使用useState一样简单!
- 示例代码：

```javascript
import useGlobalstate from "react-simple-global-state-store-hook";
function Htest() {
  const {
    number: [number, setnumber]
  } = useGlobalstate({ number: 78546 });

  //全局状态 number 生成 ,初始值为 78546

  return (
    <div>
      <p>
        number:
        {number}
      </p>
      <button
        onClick={() => {
          setnumber(number * 3);
          /*修改全局状态number,其他使用了全局状态number的组件也会刷新数据*/
        }}
      >
        修改number
      </button>
    </div>
  );
}
```

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
