### ISSUE TITLE
Pull - 自动化更新 Github fork

### ISSUE THREAD

**Issue by wei** [521xueweihan/HelloGitHub#678]
## 项目推荐
- 项目地址：https://github.com/wei/pull

- 类别：其他

- 项目后续更新计划：图形化配置、自动配置文件

- 项目描述：
  - 必写：Github App 自动化实现同步集成 Fork 
  - 描述长度（不包含示例代码）: 很多童鞋开源工作时会fork项目，但无法取得原项目的最新更新。此 Github App 自动化实现 Fork 同步集成。截至目前已有 30k+ 仓库使用，截至目前已经自动生成了近70万个 PR。注意：如果 master 有更改需要备份后使用，具体见[文档](https://github.com/wei/pull#readme)。

- 推荐理由：
很多童鞋开源工作时会fork项目，但无法取得原项目的最新更新。此 Github App 解决这个痛点。
截至目前已有 28k 仓库使用，截至目前已经自动生成了 600k+ 个 PR。

- 截图：

![](https://user-images.githubusercontent.com/5880908/40864471-046ffcd2-65c2-11e8-83cb-706e24bde80d.png)

![](https://user-images.githubusercontent.com/5880908/40864529-32647474-65c2-11e8-9cdd-d325f2d7a6e4.png)

![image](https://user-images.githubusercontent.com/5880908/60558161-39701980-9d16-11e9-9438-a817a603951d.png)

**Comment by 521xueweihan** [comment]
@wei 项目描述修改后内容如下：
 
一个 GitHub App 可以让 fork 的仓库自动同步，保持和原仓库同步的神器。很多同学参与开源时会 fork 项目，但无法取得原项目的最新更新。此 Github App 可以很好的解决这个问题，截至目前已有 28k+ 仓库使用，截至目前已经自动生成了 600k+ 个 PR。注意：如果 master 有更改需要备份后使用，具体见[英文文档](https://github.com/wei/pull#readme)

如有问题，欢迎回复反馈。

**Comment by wei** [comment]
截至目前已有 30k+ 仓库使用，截至目前已经自动生成了近 70 万个 PR。

感谢！

**Comment by 521xueweihan** [comment]
好的

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 42 期](https://hellogithub.com/periodical/volume/42/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了《讲解开源项目》系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
