### ISSUE TITLE
Eyepetizer-in-Kotlin:一款简约的小视频app

### ISSUE THREAD

**Issue by LRH1993** [521xueweihan/HelloGitHub#68]
## 项目推荐
- 项目名称：Eyepetizer-in-Kotlin

- 项目地址：https://github.com/LRH1993/Eyepetizer-in-Kotlin

- 项目语言：Kotlin

- 项目描述：

1.数据来源

Eyepetizer-in-Kotlin的所有数据来源自开眼视频，不涉及任何商业用途，有如侵权，立即删除。

具体api接口可以参考项目中的Api类。

2.功能

 含有开眼视频每日推荐、热门及分类小视频
 支持视频播放，包含全屏播放等特性
 支持关键词搜索，想看什么看什么
 记录历史观看，以及缓存视频，本地播放等功能

3.特点

作为学习kotlin的一款app，在撸代码的过程中学习kotlin的语法及特性。

Eyepetizer-in-Kotlin适合初学者作为学习kotlin语言的一个项目，可以在做项目的同时体验到kotlin语言的优点。

- 推荐理由：

风格简约，项目结构清晰，应用MVP模式。使用Retrofit、RxJava、Glide等框架开发。

使用kotlin语言开发，使用了kotlin的多种特性，是接触与学习kotlin的一个入门级项目。

- 示例代码：

**通过以下代码展示kotlin特性**

(1) 和findViewById说再见

我们可以直接使用xml中对应的id，并且import对应的文件，不在需要findViewById
```
import kotlinx.android.synthetic.main.activity_watch.*
.........
tv_hint.visibility = View.VISIBLE
tv_hint.text = "告别findViewById"
```
(2) 延迟加载

延迟加载有几个好处。首先由于加载时机推迟到了变量被访问时，因此它可以提高应用的启动速度。其次，这样的延迟加载也有更高的内存效率。
```
val mModel: FindDetailModel by lazy {
        FindDetailModel()
    }
```
当第一次使用mModle的时候进行初始化
```
lateinit var mAdapter: DownloadAdapter
```
在任何想进行初始化的位置进行初始化

(3) Lambdas 表达式

Lambdas 表达式在减少源文件中代码的总行数的同时，也支持函数式编程。

使用 lambdas 表示式时，onClickListener 的用法如下：
```
holder?.itemView?.setOnClickListener {
            var keyWord = list?.get(position)
            var intent : Intent = Intent(context,ResultActivity::class.java)
            intent.putExtra("keyWord",keyWord)
            context?.startActivity(intent)
            mDialogListener?.onDismiss()
        }
```

(4) 数据类

数据类简化了类的定义，自动为类添加equals()，hashCode()，copy() 和toString() 方法。它明确定义了 model 类的意图，以及应该包含什么内容，同时将纯数据与业务逻辑分离开来。
```
data class VideoBean(var feed:String?,var title:String?,var description:String?,
                     var duration: Long?,var playUrl: String?,var category: String?,
                     var blurred : String?,var collect:Int?,var share:Int?,var reply:Int?,var time:Long) : Parcelable,Serializable {}
```
就是如此简单，对比以前动辄几百行的数据类，简洁了太多。如果想实现序列化Parcelable，可以下载支持kotlin序列化的插件，一键实现，非常方便。

(5) 集合过滤

通过使用 Kotlin 的集合过滤功能，我们可以使代码变得更清晰简洁。
```
bean.issueList!!
                .flatMap { it.itemList!! }
                .filter { it.type.equals("video") }
                .forEach { mList.add(it) }
```
通过以上过滤，便可以得到我们想要的内容。

(6) 扩展

扩展的好处在于它允许我们为一个类添加功能同时无需继承它。例如，你是否曾经希望 Context 有某些方法，比如 showToast()？使用扩展，你可以很容易实现这个功能：
```
fun Context.showToast(message: String) : Toast {
    var toast : Toast = Toast.makeText(this,message,Toast.LENGTH_SHORT)
    toast.setGravity(Gravity.CENTER,0,0)
    toast.show()
    return toast
}
```
(7) 其他特性

**字符串**

Kotlin在字符串之中可以使用变量，相对与在Java中的字符串拼接，更让人感觉到舒服。
```
holder?.tv_detail?.text = "发布于 $category / $realMinute:$realSecond"
```
**when**

Kotlin中when的出现替代了switch，但其功能更加强大。
```
 override fun onClick(v: View?) {
        when(v?.id){
            R.id.tv_watch ->{
                var intent = Intent(activity,WatchActivity::class.java)
                startActivity(intent)
            }
            R.id.tv_advise ->{
                var intent = Intent(activity,AdviseActivity::class.java)
                startActivity(intent)
            }
            R.id.tv_save ->{
                var intent = Intent(activity,CacheActivity::class.java)
                startActivity(intent)
            }
        }
    }
```

- 截图：

 1.启动界面
![](https://user-gold-cdn.xitu.io/2017/7/12/38b6637df618a15c4cba46c7b0168ca3)
2.主界面
![](https://user-gold-cdn.xitu.io/2017/7/12/e785698f73626e048ae0e69bc9e2cd27)
![](https://user-gold-cdn.xitu.io/2017/7/12/d137df56bd0d8a4b2a92f0978901665f)
3.视频界面
![](https://user-gold-cdn.xitu.io/2017/7/12/7418abac3c599ac32b76f811e0f33c61)
4.搜索界面
![](https://user-gold-cdn.xitu.io/2017/7/12/e9b7d9ac3edf78ca9be3daa3970b5b1c)
5.缓存界面
![](https://user-gold-cdn.xitu.io/2017/7/12/2b87d4affb11efc3b78924c1ca337087)

**Comment by 521xueweihan** [comment]
@LRH1993 看来是时候加入 `Kotlin` 语言的分类了

**Comment by LRH1993** [comment]
@521xueweihan 是的，我看还没有Kotlin呢

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功收录**在 [HelloGitHub 第 17 期](https://github.com/521xueweihan/HelloGitHub/blob/master/content/17/HelloGitHub17.md)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，如果方便可以 Star ⭐️ 本项目，让更多人看到本项目。
