### ISSUE TITLE
go 实现的简单数据库

### ISSUE THREAD

**Issue by exfly** [521xueweihan/HelloGitHub#680]
## 项目推荐
- 项目地址：https://github.com/anydemo/newdb/

- 类别：Go

- 项目后续更新计划：
     https://github.com/anydemo/newdb/projects/1

- 项目描述：
  - 必写：使用Go实现兼容Mysql的关系型数据库
  - 描述长度（不包含示例代码）:  使用Go实现一个兼容mysql通讯协议简单的关系型数据库，主要包括Tuple的序列化与反序列化，Iterator操作，简单数据的get和set，类似select的操作以及简单比较操作的实现，暂时支持手写执行计划，未来会加入更加丰富的sql操作，以及mysql通讯协议的支持。

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？

学习数据库设计与实现，自己亲手写一个数据库。对于新手来说可以更好的从简单小巧的项目中获得最直观的数据库运行感受。

**Comment by FrontMage** [comment]
你好，请认真填写推荐理由。。。

**Comment by exfly** [comment]
@521xueweihan @FrontMage 重新修改了一下描述～

**Comment by FrontMage** [comment]
收录至41期

**Comment by 521xueweihan** [comment]
@exfly 您好，项目的介绍太少。
1. 数据库的实验性项目，本身就有一定门槛。项目的文档和目录结构需要有详细的描述，初学者才能参与和学习
2. test 和 代码放在一个目录我觉得欠妥
3. 数据的持久化方式是、架构图，这些都会让你的项目更好

请修改后再次提交，本次不能收录到月刊中
