### ISSUE TITLE
最早最全最持久的Spring Cloud免费教程

### ISSUE THREAD

**Issue by dyc87112** [521xueweihan/HelloGitHub#683]
## 项目推荐
- 项目地址：https://github.com/dyc87112/SpringCloud-Learning

- 类别：Java

- 项目后续更新计划：Spring Cloud Alibaba基础教程连载

-  #项目描述：
  - 必写：全网最早并一直在连载的Spring Cloud免费教程
  - 可选：适合想要体系化入门学习Spring Cloud的童鞋
  - 描述长度（不包含示例代码）: 国内最早的Spring Cloud系列教程，从B版开始一直在连载更新内容。在Netflix套件处于维护状态之后，开始继续连载最新的Alibaba套件，更多内容还在持续连载中。

- 推荐理由：最早最全最持久的Spring Cloud教程

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
