### ISSUE TITLE
全网最早连载的Spring Boot免费教程与案例

### ISSUE THREAD

**Issue by dyc87112** [521xueweihan/HelloGitHub#684]
## 项目推荐
- 项目地址：https://github.com/dyc87112/SpringBoot-Learning

- 类别：Java

- 项目后续更新计划：Spring Boot 2.x基础教程

- 项目描述：
  - 必写：免费的Spring Boot入门教材与案例
  - 可选：适合要学习Spring Boot的初学者与应用者
  - 描述长度（不包含示例代码）: 全网最早连载的Spring Boot免费教材，非常适合初学者阅读学习。

- 推荐理由：全网（Github + Gitee）累计Star最多的Spring Boot教程。

**Comment by 521xueweihan** [comment]
该项目已经推荐过：https://hellogithub.com/periodical/search/?q=https://github.com/dyc87112/SpringBoot-Learning
