### ISSUE TITLE
my-awesome-tools

### ISSUE THREAD

**Issue by bihell** [521xueweihan/HelloGitHub#685]
## 项目推荐
- 项目地址：https://github.com/bihell/my-awesome-tools

- 类别：

其它

- 项目后续更新计划： 

有新的工具等会持续更新。

- 项目描述：

汇集了我使用的工具：软件、硬件、数码等。

- 推荐理由：不仅仅是软件，还有硬件，还配了视频哟。

**Comment by 521xueweihan** [comment]
您好，已推荐过类似的项目。暂不能收录您的项目，谢谢
