### ISSUE TITLE
全能安卓播放器

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#686]
## 项目推荐
- 项目地址： https://github.com/CarGuo/GSYVideoPlayer

- 类别：Java

- 项目描述：
强大的移动端视频播放器（借鉴IJKplayer、ExoPlayer、MediaPlayer），支持HTTPS，支持弹幕，支持滤镜、水印、gif截图，片头广告、中间广告，多个同时播放，支持基本的拖动，声音、亮度调节，支持边播边缓存，支持视频自带rotation的旋转（90,270之类），重力旋转与手动旋转的同步支持，支持列表播放 ，列表全屏动画，视频加载速度，列表小窗口支持拖动，动画效果，调整比例，多分辨率切换，支持切换播放器，进度条小窗口预览，列表切换详情页面无缝播放，rtsp、concat、mpeg。

- 推荐理由：

移动端开源的播放器，基本囊括各种功能，使用简单，文档详细，社区活跃，如果你想在移动端嵌入一个播放器，为什么不选择这个呢？

- 示例：
https://github.com/CarGuo/GSYVideoPlayer#%E5%9B%9B%E8%BF%90%E8%A1%8C%E6%95%88%E6%9E%9C
（原仓库展示的很全，直接放链接了）

**Comment by CasualJi** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
之前的月刊，已推荐过：https://hellogithub.com/periodical/search/?q=https://github.com/CarGuo/GSYVideoPlayer
