### ISSUE TITLE
Python模块集合库

### ISSUE THREAD

**Issue by jtyoui** [521xueweihan/HelloGitHub#688]
## 项目推荐
- 项目地址：https://github.com/jtyoui/Jtyoui

- 类别：Python

- 项目后续更新计划：每周至少更新三次以上

- 项目描述：
搜狗词库下载、新词发现算法、 照片和PDF相互转化,、微信自动聊天机器人、中国农历与阳历的转换关系、简体字与繁体字的转换、坦克小游戏、分形模式、邮箱、地图、正则、装饰器,、数学统计、数据处理、nlp算法、进制转换、验证码识别、数据下载、分形模型、小游戏、语言处理、邮箱应用、网页处理、微信、异常、地图、计算统计、贝叶斯算法、常见的工具类、c模块、百度应用、日语单词翻译、天气预报、汉语纠错、字符串时间解析等等。

- 推荐理由：
一个Python模块集合、集合的大量的常用方法和数学函数。而且每一个类的使用都有对应的测试用例，非常简单易使用。

- 示例代码：
其中之一
from jtyoui.tools import StringTime
print('-----------------切换日期------------------')
st = StringTime('下周星期一下午2点半开会', '2019-4-17 00:00:00')
print(st.find_times()) # ['2019-04-22 14:30:00']
print('----------------多个时间-------------------')
st = StringTime('今天下午3点开会到4点整到12楼大会议室开会。')
print(st.find_times()) # ['2019-07-02 15:00:00', '2019-07-02 16:00:00']
print('---------------跳断日期--------------------')
st = StringTime('下周星期一下午2点半到4点开会')
print(st.find_times()) # ['2019-07-08 14:30:00', '2019-07-08 16:00:00']
print('---------------非常间断日期--------------------')
st = StringTime('明天下午2点半一直到下周星期五下午4点开会')
print(st.find_times()) # ['2019-07-03 14:30:00', '2019-07-12 16:00:00']
print('--------------几月底--------------')
st = StringTime('明年的2月底之前必须交报告,本月底吃饭')
print(st.find_times()) # ['2019-02-28', '2019-07-31']

- 截图：
其中之一
![image](https://user-images.githubusercontent.com/28988355/60768016-aeff2f80-a0f2-11e9-9b5e-87e0230bc791.png)

**Comment by jtyoui** [comment]
# Python项目

**Comment by 521xueweihan** [comment]
@jtyoui 项目描述不要罗列功能，用简短的语言进行描述。突出亮点

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 41 期](https://hellogithub.com/periodical/volume/41/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了《讲解开源项目》系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
