### ISSUE TITLE
sqli-labs

### ISSUE THREAD

**Issue by ming995** [521xueweihan/HelloGitHub#689]
## 项目推荐
- 项目地址：https://github.com/Audi-1/sqli-labs

- 类别：教程，主要实现语言是PHP

- 项目后续更新计划：

- 项目描述：这是SQL注入详细教程

- 推荐理由：非常详细的SQL注入教程值得入门安全行业的同学阅读，阅读语言需要英文

**Comment by No-Github** [comment]
纠正一下，把这个项目归类为教程不太合理的，分类为靶场或靶机比较合适

**Comment by 521xueweihan** [comment]
@No-Github 我们暂时不支持这么多分类，归结为其它把
