### ISSUE TITLE
Material Design 指南中文翻译项目

### ISSUE THREAD

**Issue by zdhxiong** [521xueweihan/HelloGitHub#69]
## 项目推荐

- 项目名称：Material Design 指南中文翻译

- 项目地址：https://github.com/zdhxiong/Material-Design-Chinese

- 项目描述：这是对 Material Design 官方文档的中文翻译，保留了原版网站的样式，并保持和官方文档同步更新。

- 推荐理由：这是非常完整的翻译版本。

- 在线阅读地址：https://www.mdui.org/design/

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功收录**在 [HelloGitHub 第 17 期](https://github.com/521xueweihan/HelloGitHub/blob/master/content/17/HelloGitHub17.md)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，如果方便可以 Star ⭐️ 本项目，让更多人看到本项目。
