### ISSUE TITLE
社团 GO 前后端

### ISSUE THREAD

**Issue by jin-hao-chen** [521xueweihan/HelloGitHub#690]
## 项目推荐
- 项目地址：
    + [前端地址](https://github.com/jin-hao-chen/team_go_frontend)
    + [后端地址](https://github.com/jin-hao-chen/team_go_backend)
- 类别：JavaScript, Python

- 项目后续更新计划：
    + 继续完善界面和后端服务, 后续将项目效果图上传到 github 上

- 项目描述：
  - 必写：大学社团纳新的 App, 大一新生无需直接到百团大战地点一个一个地去看杂乱无常的社团, 此 App 提供了线上的社团信息服务, 申请社团服务等, 方便学生足不出户就达到目标, 使用此 App 之后, 你需要做的就是等待社团管理员的面试通知即可, 你的个人信息在你提交申请的时候已经对管理员可见了。
  - 可选：此项目使用的 Vue + MUI, 在写的过程中遇到了 MUI 中的许多 BUG, 通过自己采坑, 修改 MUI 框架的源代码解决了问题, 希望可以帮助以后也采用 Vue + MUI 开发的人少走一些歪路
  - 描述长度（不包含示例代码）: 大学社团纳新的 App, 大一新生无需直接到百团大战地点一个一个地去看杂乱无常的社团, 此 App 提供了线上的社团信息服务, 申请社团服务等, 方便学生足不出户就达到目标, 使用此 App 之后, 你需要做的就是等待社团管理员的面试通知即可, 你的个人信息在你提交申请的时候已经对管理员可见了, 此段与项目描述其实是一样的:)

- 推荐理由：让大一新生足不出户就可以访问各个社团的信息, 同时进行申请, 之后只需等待管理的通知

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

项目地址错误
