### ISSUE TITLE
X-BUILD

### ISSUE THREAD

**Issue by codexu** [521xueweihan/HelloGitHub#692]
## 项目推荐
- 项目地址：https://github.com/codexu/x-build

- 类别：JS

- 项目后续更新计划：增加通过指令安装插件功能

- 项目描述：X-BUILD 是面向小型项目的脚手架工具，通过终端命令最快在几秒钟初始化项目目录，解决开发中的自动化、性能、模块化、规范、自适应布局等问题，辅助你生成更优质的代码。

- 推荐理由：可以帮助新手更快的上手体验现代化的前端工程。

- 截图：http://ww2.sinaimg.cn/large/006tNc79ly1g3yij4uah1g30rs0hzdnt.gif

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 40 期](https://hellogithub.com/periodical/volume/40/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
