### ISSUE TITLE
星聚弃疗榜

### ISSUE THREAD

**Issue by zhaoolee** [521xueweihan/HelloGitHub#695]
## 项目推荐

- 项目地址：https://github.com/zhaoolee/StarsAndClown

- 类别：书籍

- 项目后续更新计划：每周更新1-2个创意项目

- 项目描述：
  - 必写：在 Github 开了一个收纳创意项目的清单, 里面也包含了很多有趣的资源, Github星聚弃疗榜, 让吃瓜群众也能享受Github带来的乐趣~

- 推荐理由：Github有哪些沙雕库? 有哪些吃瓜群众也能玩的嗨的库? 在这里,你将找到满意的答案[手动滑稽]

![](https://user-images.githubusercontent.com/15868458/61105812-9b1a4b80-a4ad-11e9-8cd8-f4037f103a33.png)

![](https://user-images.githubusercontent.com/15868458/61105852-ba18dd80-a4ad-11e9-9867-95e5375798fe.png)

![](https://user-images.githubusercontent.com/15868458/61105863-c6049f80-a4ad-11e9-8f33-feafce028e0e.png)

![](https://user-images.githubusercontent.com/15868458/61105878-d3218e80-a4ad-11e9-89d9-76d8e3697a06.png)

![](https://user-images.githubusercontent.com/15868458/61105899-e2084100-a4ad-11e9-9f3b-455fea73e458.png)

![](https://user-images.githubusercontent.com/15868458/61105919-ee8c9980-a4ad-11e9-8b70-b28ce687bee4.png)
![](https://user-images.githubusercontent.com/15868458/61105927-fe0be280-a4ad-11e9-8fa6-14000a0c8e8c.png)

![](https://user-images.githubusercontent.com/15868458/61105935-0cf29500-a4ae-11e9-90c5-7a3838a5c277.png)

![](https://user-images.githubusercontent.com/15868458/61105952-1976ed80-a4ae-11e9-8ebc-68e6738983f1.png)

**Comment by 521xueweihan** [comment]
暂时不推荐这个项目了，已经推荐过 Github星聚弃疗榜，比这个有意思。哈哈哈

**Comment by zhaoolee** [comment]
推荐过 Github星聚弃疗榜 了么? 我这个项目曝光量好像还蛮少的[手动滑稽]
