### ISSUE TITLE
前端面试宝典 - 图解前端

### ISSUE THREAD

**Issue by azl397985856** [521xueweihan/HelloGitHub#697]
## 项目推荐
- 项目地址：https://github.com/azl397985856/fe-interview

- 类别：JS

- 项目后续更新计划：完善TODO，增加主题

- 项目描述：
  这是一份自己总结的关于准备前端面试的一个复习汇总项目，项目不定时更新。

  这不仅仅是一份用于求职面试的攻略，也是一份前端er用来检视自己，实现突破的宝典。 希望通过这个指南，大家可以打通自己的任督二脉，在前端的路上更进一步。

- 推荐理由：本仓库大量采用图的形式来传达知识，所谓一图胜千言，希望通过这种图文并茂的表达方式 让你更容易记住一些抽象，难以理解的概念，《图解前端》是我给它的副标题。

- 截图：

![logo](https://user-images.githubusercontent.com/12479470/61168590-1dc10a80-a583-11e9-9b1b-d08b0ddeec4d.jpg)
![SmartSelect_20190713-142136](https://user-images.githubusercontent.com/12479470/61168591-1dc10a80-a583-11e9-947e-3c9e4c71231a.jpg)
![SmartSelect_20190713-142204](https://user-images.githubusercontent.com/12479470/61168592-1e59a100-a583-11e9-99a7-deeb6f55aef5.jpg)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
