### ISSUE TITLE
英伟达: 淘宝照片试衣镜+用作深度学习训练图像

### ISSUE THREAD

**Issue by layumi** [521xueweihan/HelloGitHub#698]
## 项目推荐
- 项目地址：https://github.com/NVlabs/DG-Net

- 类别：Python

- 项目后续更新计划：每周更新

- 项目描述：
深度学习模型训练时往往需要大量的标注数据,但收集和标注大量的数据往往比较困难。作者在行人重识别这个任务上探索了 利用生成数据来辅助训练的方法。通过生成高质量的行人图像(行人两两换衣)，将其与行人重识别模型融合，同时提升行人生成的质量和行人重识别的精度。

- 推荐理由：

1. 不需要额外标注（如姿态pose，属性attribute，关键点keypoints等），就能生成高质量行人图像。通过交换提取出的特征，来实现两张行人图像的外表互换。这些外表都是训练集中真实存在的变化，而不是随机噪声。 
2. 不需要部件匹配来提升行人重识别的结果。仅仅是让模型看更多训练样本就可以提升模型的效果。给定N张图像，我们首先生成了NxN的训练图像，用这些图像来训练行人重识别模型。(下图第一行和第一列为真实图像输入，其余都为生成图像)
3. 训练中存在一个循环： 生成图像喂给行人重识别模型来学习好的行人特征，而行人重识别模型提取出来的特征也会再喂给生成模型来提升生成图像的质量。

- 示例代码：

Start training
```bash
python train.py --config configs/latest.yaml
```
Or training with low precision float (float16)
```bash
python train.py --config configs/latest-fp16.yaml
```
Intermediate image outputs and model binary files are stored in `outputs/latest`.
Check the loss log
```bash
 tensorboard --logdir logs/latest
```
- 截图：
![https://github.com/layumi/DGNet/blob/master/NxN.jpg?raw=true](https://github.com/layumi/DGNet/blob/master/NxN.jpg?raw=true)

**Comment by xibinyue** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 40 期](https://hellogithub.com/periodical/volume/40/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
