### ISSUE TITLE
java

### ISSUE THREAD

**Issue by ZQYnn** [521xueweihan/HelloGitHub#699]
## 项目推荐
- 项目地址：

- 类别：请从中选择（C、C#、C++、CSS、Go、Java、JS、Kotlin、Objective-C、PHP、Python、Ruby、Swift、其它、书籍、机器学习）

- 项目后续更新计划：

- 项目描述：
  - 必写：这是个什么项目、能用来干什么、有什么特点或解决了什么痛点
  - 可选：适用于什么场景、能够让初学者学到什么
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

**Comment by 521xueweihan** [comment]
bot
