### ISSUE TITLE
iOS开源项目：PYSearch 

### ISSUE THREAD

**Issue by iphone5solo** [521xueweihan/HelloGitHub#7]
PYSearch  GitHub地址：https://github.com/iphone5solo/PYSearch  一款综合（QQ 音乐、微信、美团、优酷、虎牙直播等多款 app）风格的搜索控制器

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

如您推荐的项目在《HelloGithub》月刊中推荐，则会同时写明推荐人。

再次感谢您对《HelloGithub》项目的支持！

**Comment by 521xueweihan** [comment]
您好，PYSearch 项目已收录到 [13期](https://github.com/521xueweihan/HelloGitHub/blob/master/13/HelloGitHub13.md)，再次感谢您的支持，希望以后推荐更多好的项目。
