### ISSUE TITLE
一个用Go语言模拟的简单计算机

### ISSUE THREAD

**Issue by RobiNexy** [521xueweihan/HelloGitHub#700]
## 项目推荐
- 项目地址：https://github.com/djhworld/simple-computer

- 类别：其它，Go语言，计算机组成原理

- 项目后续更新计划：将尝试模拟支持X86/ARM/RISC-V指令集的CPU

- 项目描述：
  - 必写：一个用Go语言模拟的简单计算机。只是模拟CPU电路的逻辑和通信，从与非门直到一台能做加减运算和显示的迷你虚拟计算机。没有硬件的模块，只有Go语言的函数。
  - 可选：原作者为了弄清楚计算机运行的原理，便自己动手写代码模拟了一个小电脑。

- 推荐理由：有关计算机最基础的东西，虽然不是用硬件打造而是使用Go语言模拟，但是，计算机的基本结构，运行的基本原理都显示的非常清楚，对于新手，既能了解CPU原理，也会发现编程语言除了能写软件之外的其他有趣用处。

- 截图：
<img width="113" alt="brush1" src="https://user-images.githubusercontent.com/44633884/61184751-ee45f700-a683-11e9-8cf4-72552fc1a92b.png">
<img width="113" alt="ascii1" src="https://user-images.githubusercontent.com/44633884/61184730-c787c080-a683-11e9-94c0-58fa44223531.png">
<img width="113" alt="text-writer1" src="https://user-images.githubusercontent.com/44633884/61184736-d1112880-a683-11e9-9666-40378fc99f1e.png">

-原文链接：掘金·机器之心 https://juejin.im/post/5ce608376fb9a07f08706e17

**Comment by FrontMage** [comment]
收录至41期

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 41 期](https://hellogithub.com/periodical/volume/41/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
