### ISSUE TITLE
巨石论坛

### ISSUE THREAD

**Issue by guowenzhuang** [521xueweihan/HelloGitHub#701]
## 项目推荐
- 项目地址：https://github.com/guowenzhuang/jushi

- 类别：Java

- 项目后续更新计划：后台管理 帖子审核

- 项目描述：
  - 必写：一个微服务论坛,可以用做学习,或者快速改造成一个自己的论坛
  - 可选：学习java 微服务 webflux的人
  - 描述长度（一个可以闲聊和讨论技术的论坛 才有微服务和webflux handler模式开发

- 推荐理由：采用了函数式 响应式的编程

**Comment by guowenzhuang** [comment]
这是个采用webflux 纯函数式编程的java项目

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
