### ISSUE TITLE
利用 Python 伪造电子邮件发件人以及制造电子邮件炸弹

### ISSUE THREAD

**Issue by Macr0phag3** [521xueweihan/HelloGitHub#702]
## 项目推荐
- 项目地址：https://github.com/Macr0phag3/email_hack

- 类别：Python/信息安全

- 项目后续更新计划：暂无

- 项目描述：
  - 利用 SMTP 协议的缺陷，使用 Python 伪造电子邮件发件人以及制造电子邮件炸弹。
  - 能够轻松地伪造邮件，让初学者了解检查邮件安全的必要性，也能了解协议分析相关的知识。

- 推荐理由：有较详细的原理说明、使用的友好度以及效果还算不错。

- 截图：
![image](https://user-images.githubusercontent.com/20874963/61196608-64893e80-a702-11e9-9a9b-6a989e6ef62f.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by 521xueweihan** [comment]
我们暂时没有安全这么细分的分类。是我们的问题。
