### ISSUE TITLE
推荐一款强大的android侧滑处理框架：SmartSwipe，内置百叶窗、侧滑返回等十几种侧滑效果

### ISSUE THREAD

**Issue by luckybilly** [521xueweihan/HelloGitHub#703]
## 项目推荐
- 项目地址：https://github.com/luckybilly/SmartSwipe

- 类别：Java

- 项目后续更新计划：

- 项目描述：
  - SmartSwipe是一个侧滑处理框架，而不是具体某种侧滑的实现
  - 内部封装十几种侧滑效果，包括侧滑返回、侧滑删除、百叶窗、开门等效果，总有那么几款能让你眼前一亮
  - 仿照内置的侧滑效果能很轻松地自定义出自己的侧滑展示逻辑
  - 

- 推荐理由：
  - 使用内置的侧滑效果轻易地就能让你的app用户体验提升一个台阶
  - 无需透明主题，无需继承某个Activity，不需要侵入xml布局文件，也不需要侵入BaseActivity，全局只需一行代码即可搞定所有Activity侧滑返回
  - 一行代码即可为任意view添加下拉刷新功能，并支持横向使用

- 示例代码：
```java
//为控件添加仿MIUI的弹性拉伸效果：
//	当纵向不能滚动（或滚动到顶/底）时，若继续拖动，则UI呈现弹性拉伸效果，释放后平滑恢复
SmartSwipe.wrap(view)
	.addConsumer(new StretchConsumer())
	.enableVertical();

SmartSwipe.wrap(view)
	.addConsumer(new StretchConsumer())
	.enableVertical() 	//仿MIUI拉伸效果的方向为：上下2个方向
	.addConsumer(new SpaceConsumer())
	.enableHorizontal()  //仿iOS弹性留白效果的方向为：左右2个方向
	;

SmartSwipeBack.activityBezierBack(application, null);	//仿小米MIUI系统的贝塞尔曲线返回效果
SmartSwipeBack.activityStayBack(application, null);		//仿手机QQ的手势滑动返回
SmartSwipeBack.activitySlidingBack(application, null);	//仿微信带联动效果的透明侧滑返回
SmartSwipeBack.activityDoorBack(application, null);		//侧滑开门样式关闭activity
SmartSwipeBack.activityShuttersBack(application, null);	//侧滑百叶窗样式关闭activity

//xxxMode第二个参数为false，表示工作方向为纵向：下拉刷新&上拉加载更多
//如果第二个参数设置为true，则表示工作方向为横向：右拉刷新&左拉加载更多
SmartSwipeRefresh.drawerMode(view, false).setDataLoader(loader);
SmartSwipeRefresh.behindMode(view, false).setDataLoader(loader);
SmartSwipeRefresh.scaleMode(view, false).setDataLoader(loader);
SmartSwipeRefresh.translateMode(view, false).setDataLoader(loader);
```
- 截图:

Stretch<br/>[StretchConsumer][StretchConsumer]|Space<br/>[SpaceConsumer][SpaceConsumer]|Translucent Sliding<br/>[TranslucentSlidingConsumer][TranslucentSlidingConsumer]
:---:|:---:|:---:
<img width="200" src="https://github.com/luckybilly/SmartSwipe/raw/master/images/stretchConsumer.gif">|<img width="200" src="https://github.com/luckybilly/SmartSwipe/raw/master/images/spaceConsumer.gif">|<img width="200" src="https://github.com/luckybilly/SmartSwipe/raw/master/images/translucentSlidingConsumer.gif">
Drawer above<br/>[DrawerConsumer][DrawerConsumer]|Drawer behind<br/>(factor is settable)<br/>[SlidingConsumer][SlidingConsumer]|
<img width="200" src="https://github.com/luckybilly/SmartSwipe/raw/master/images/drawerConsumer.gif">|<img width="200" src="https://github.com/luckybilly/SmartSwipe/raw/master/images/slidingConsumer.gif">|
Doors Open<br/>[DoorConsumer][DoorConsumer]|Shutters Open<br/>[ShuttersConsumer][ShuttersConsumer]|
<img width="200" src="https://github.com/luckybilly/SmartSwipe/raw/master/images/doorConsumer.gif">|<img width="200" src="https://github.com/luckybilly/SmartSwipe/raw/master/images/shuttersConsumer.gif">|

<img src="https://luckybilly.github.io/SmartSwipe-tutorial/images/covers.gif">

[ActivityDoorBackConsumer]: https://luckybilly.github.io/SmartSwipe-tutorial/pages/consumers/ActivityDoorBackConsumer.html
[ActivityShuttersBackConsumer]: https://luckybilly.github.io/SmartSwipe-tutorial/pages/consumers/ActivityShuttersBackConsumer.html
[ActivitySlidingBackConsumer]: https://luckybilly.github.io/SmartSwipe-tutorial/pages/consumers/ActivitySlidingBackConsumer.html
[BezierBackConsumer]: https://luckybilly.github.io/SmartSwipe-tutorial/pages/consumers/BezierBackConsumer.html
[DoorConsumer]: https://luckybilly.github.io/SmartSwipe-tutorial/pages/consumers/DoorConsumer.html
[DrawerConsumer]: https://luckybilly.github.io/SmartSwipe-tutorial/pages/consumers/DrawerConsumer.html
[ShuttersConsumer]: https://luckybilly.github.io/SmartSwipe-tutorial/pages/consumers/ShuttersConsumer.html
[SlidingConsumer]: https://luckybilly.github.io/SmartSwipe-tutorial/pages/consumers/SlidingConsumer.html
[SpaceConsumer]: https://luckybilly.github.io/SmartSwipe-tutorial/pages/consumers/SpaceConsumer.html
[StayConsumer]: https://luckybilly.github.io/SmartSwipe-tutorial/pages/consumers/StayConsumer.html
[StretchConsumer]: https://luckybilly.github.io/SmartSwipe-tutorial/pages/consumers/StretchConsumer.html
[TranslucentSlidingConsumer]: https://luckybilly.github.io/SmartSwipe-tutorial/pages/consumers/TranslucentSlidingConsumer.html

**Comment by 521xueweihan** [comment]
@luckybilly 看你的邮箱，或者垃圾箱有没有我的邮件！！！

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 41 期](https://hellogithub.com/periodical/volume/41/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了《讲解开源项目》系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
