### ISSUE TITLE
杀手级AI补代码工具问世，支持23种语言及5种主流编辑器

### ISSUE THREAD

**Issue by TrustTheBoy** [521xueweihan/HelloGitHub#704]
## 项目推荐
- 项目地址：https://github.com/zxqfl/TabNine

- 类别：机器学习、工具

- 项目后续更新计划：未知

- 项目描述：
  - 一个来自OpenAI的逆天语言模型，现在能用来补全代码了
  - 代码补全工具支持23种编程语言、5种编辑器，使用简单，效果惊艳
  - 详细描述: [点击这里快速了解](https://mp.weixin.qq.com/s/y7MZijv44mVqEWtTzHg4nw)

- 推荐理由：TabNine支持VS Code、Sublime Text、Atom、Emacs、Vim五种代码编辑器。
[点击这里快速了解](https://mp.weixin.qq.com/s/y7MZijv44mVqEWtTzHg4nw)

**Comment by xibinyue** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 40 期](https://hellogithub.com/periodical/volume/40/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
