### ISSUE TITLE
项目自荐 GHDropMenu 简单使用 无入侵 对原项目无污染

### ISSUE THREAD

**Issue by shabake** [521xueweihan/HelloGitHub#706]
## 项目推荐
- 项目地址：https://github.com/shabake/GHDropMenuDemo

- 类别：Objective-C

- 项目后续更新计划：不定时更新

- 项目描述：
  GHDropMenu 是一个通用的筛选菜单,方便集成,快速选择出筛选项,对原有项目无污染

- 推荐理由：整理了市面常见的筛选菜单样式,复制代码调用即可

#### 使用方法:

![12.png](https://upload-images.jianshu.io/upload_images/1419035-46b3260c4c3c49a4.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

#### 实现数据源方法:

![2.png](https://upload-images.jianshu.io/upload_images/1419035-8bef7e6a81c99d5c.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

- 截图：

![Untitled.gif](https://upload-images.jianshu.io/upload_images/1419035-55dd0f6eafb19fd7.gif?imageMogr2/auto-orient/strip)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 40 期](https://hellogithub.com/periodical/volume/40/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
