### ISSUE TITLE
自荐项目：python3 多语言帮助

### ISSUE THREAD

**Issue by star2000** [521xueweihan/HelloGitHub#707]
## 项目推荐
- 项目地址：https://github.com/star2000/i18n-python

- 类别：Python

- 项目后续更新计划：不定期更新

- 项目描述：
    写代码时，能看到中文帮助。能够让英语不好的初学者快速掌握编程。

- 推荐理由：为学习python降低门槛

- 截图：
<img width="676" alt="批注 2019-07-17 222128" src="https://user-images.githubusercontent.com/42126168/61383450-504f6800-a8e1-11e9-8cf0-bb3f56e41155.png">

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
