### ISSUE TITLE
Licia：实用 JavaScript 工具库

### ISSUE THREAD

**Issue by surunzi** [521xueweihan/HelloGitHub#708]
## 项目推荐
- 项目地址：https://github.com/liriliri/licia

- 类别：JS

- 项目后续更新计划：不断增加实用工具函数。

- 项目描述：Licia 是一套在开发中实践积累起来的实用 JavaScript 工具库。该库目前拥有超过 300 个模块，同时支持浏览器、node 及小程序运行环境，提供了包括日期格式化、md5、颜色转换等实用模块，可以极大地提高开发效率。

- 推荐理由：可以用来替代大部分 npm 小包，只安装一个就行了。

- 示例代码：

```javascript
const uuid = require("licia/uuid");
const dateFormat = require("licia/dateFormat");
const now = require("licia/now");
const randomBytes = require("licia/randomBytes");

console.log(randomBytes(5));
console.log(uuid());
console.log(dateFormat(now(), "yyyy-mm-dd"));
```

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 40 期](https://hellogithub.com/periodical/volume/40/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
