### ISSUE TITLE
基于Vue和ElementUI的后台管理系统

### ISSUE THREAD

**Issue by sailengsi** [521xueweihan/HelloGitHub#71]
## 项目推荐
- 项目名称：基于Vue和ElementUI的后台管理系统

- 项目地址：https://github.com/sailengsi/sls-admin

- 项目语言：JavaScript

- 项目描述：基于这个模式，可以拓展更为强大的功能，诸如类似其他后台模板里面的那些功能等，都可以用组件化形式开发，注入到此项目。

- 推荐理由：易于协作开发，方便拓展与维护，结构清晰明了，灵活，可自定义配置

- 示例代码：

- 截图：

**Comment by 521xueweihan** [comment]
@sailengsi 你好，建议完善 README，可以通过简短的介绍了解本项目。同时，知晓本项目的特点与优势。
