### ISSUE TITLE
自荐项目：Lite 编程语言

### ISSUE THREAD

**Issue by kulics** [521xueweihan/HelloGitHub#711]
## 项目推荐
- 项目地址：
https://github.com/kulics/lite

- 类别：C#、Go

- 项目后续更新计划：
语法设计已经稳定（1.0-alpha），后续主要精力将放在编译器实现改进迭代，扩展到更多场景。

- 项目描述：
    Lite 是一个专注于工程化的开源通用编程语言。

    这门语言的设计目标是简单性、可读性、可理解性。

    通过去除关键字，减少语法特性，统一表达规范，这门语言可以有效降低读写负担，让使用者能够把真正的注意力放在解决问题上。

    目前支持输出到 C#/Go/TypeScript，借助它们的资源，已经可以在非常广泛的场景下使用这门语言。

- 推荐理由：精心设计的语法，易于编写和阅读。可能是目前世界上语法最精简的静态编程语言。

- 示例代码：

<img width="381" alt="readme" src="https://user-images.githubusercontent.com/8154330/61680762-61630380-ad3d-11e9-9cc8-f81ed8d239b0.png">

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by 521xueweihan** [comment]
我们暂时不推荐单纯的编程语言类项目
