### ISSUE TITLE
 PC端百度网盘视频倍速播放谷歌浏览器插件

### ISSUE THREAD

**Issue by chxcode** [521xueweihan/HelloGitHub#717]
## 项目推荐
- 项目地址：
[https://github.com/chxcode/speeded_video_for_Baidu_Netdisk](https://github.com/chxcode/speeded_video_for_Baidu_Netdisk)
- 类别：请从中选择（C、C#、C++、CSS、Go、Java、JS、Kotlin、Objective-C、PHP、Python、Ruby、Swift、其它、书籍、机器学习）
JS
- 项目后续更新计划：
主要提高用户体验
- 项目描述：
  - 必写：这是个什么项目、能用来干什么、有什么特点或解决了什么痛点
  - 可选：适用于什么场景、能够让初学者学到什么
  - 描述长度（不包含示例代码）: 10 - 256 个字符
一款可以调整PC端百度网盘在线视频播放速度的谷歌浏览器插件，简单易操作，解决了用户不能通过自己调整百度网盘在线视频播放的问题。
- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？
百度网盘视频可在线倍速播放啊！
- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
