### ISSUE TITLE
NumPy 中文文档（入门、进阶教程）

### ISSUE THREAD

**Issue by leaicc** [521xueweihan/HelloGitHub#718]
## 项目推荐
- 项目地址：https://github.com/teadocs/numpy-cn

- 类别：Python

- 项目后续更新计划：已完结

- 项目描述：
这是 NumPy 的入门和进阶教程，非常完整、系统，适合任何想了解学习 NumPy 的人，还可以当作手册查阅
如果你是新手朋友，推荐阅读基础文章中的：理解 Numpy、NumPy 简单入门教程、创建 Numpy 数组的不同方式。
如果你想徒手实现神经网络可以参看 NumPy 与 神经网络、 NumPy 实现 DNC、RNN 和 LSTM 神经网络算法。

- 推荐理由：如果你想系统的学习 NumPy，有了这个文档，你可能不需要购买任何的书籍就可以学会，而且参考文章里会不定期更新国内外优秀的 Numpy 相关的内容

**Comment by Eurus-Holmes** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 41 期](https://hellogithub.com/periodical/volume/41/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
