### ISSUE TITLE
提问的智慧 - How To Ask Questions The Smart Way

### ISSUE THREAD

**Issue by ChungZH** [521xueweihan/HelloGitHub#719]
## 项目推荐
- 项目地址：https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way

- 类别：其它

- 项目后续更新计划：

- 项目描述：在程序员的世界里，你所提技术问题的解答很大程度上取决于你提问的方式与解决此问题的难度，本文将教你如何提问才更有可能得到满意的答复。最后，下面通过举例来演示提问的智慧。同样的问题两种提法，一种愚蠢，另一种明智。

  - 愚蠢：我在哪能找到关于 Foonly Flurbamatic 设备的东西？
    明智： 我用谷歌搜索过“Foonly Flurbamatic 2600”，但没有找到什么有用的，有谁知道在哪能找到这种设备的编程信息？

  - 愚蠢： 我不能编译某项目的源代码，它为什么这么破？
    明智： 某项目的源代码不能在某 Linux 6.2 版下编译。我读了常见问题文档，但其中没有与某 Linux 相关的内容。这是编译时的记录，我做错了什么吗？

  - 愚蠢： 我的主板有问题，谁能帮我？
    明智： 我在 S2464 主板上试过 X、Y 和 Z，当它们都失败后，又试了 A、B 和 C。注意我试 C 时的奇怪症状，显然某某东西正在做某某事情，这不是期望的行为。通常在 Athlon MP 主板上导致某某事情的原因是什么？有谁知道我还能再试点什么以确定问题？

- 推荐理由：提问前必看！

- 示例代码：

- 截图：

**Comment by 521xueweihan** [comment]
收录过类似的项目了：https://hellogithub.com/periodical/search/?q=How-To-Ask-Questions-The-Smart-Way
