### ISSUE TITLE
CRMEB商城系统

### ISSUE THREAD

**Issue by sugar1569** [521xueweihan/HelloGitHub#721]
## 项目推荐
- 项目地址：https://github.com/crmeb/CRMEB

- 类别：PHP

- 项目后续更新计划：

持续升级优化，目前是2.6版，下个月发布3.0版

- 项目描述：
 
1.商品: 能够对商品的状态分类管理 (出售中、待上架、库存中、已售馨、库存警戒、回收站)、添加产品、添加商品分类等功能

2.会员:站内会员的管理 (发放优惠劵、发通知、发图文消息、增加余额、会员行为详情)、站内通知 、微信端用户管理 (微信用 户的管理、分组、行为观察、添加标签) 等功能

3.营销:能够管理优惠的发放和制作、用户积分的统计使用情况、秒杀产品的管理等

4.财务:能够对用户的消费、充值、返佣的记录

5.订单:能够完成用户的订单管理(发货、订单详情、修改订单、订单备注、订单记录、订单退款) 、售后服务 (评论的回复与删除)

6.分销:后台有分销统计管理，分销可以设置人人分销和指定人分销，也可以自己稍微开发一下修改规 7.数据统计图表统计分析(财务统计、产品统计、会员统计、营销统计、分销统计、交易统计等)

8.设置:能够完成管理员对网站的商品资料（添加大类、添加小类、商品添加、属性快速生成、商品审查）、商品交易（外理订单、发货查询）、会员管理（会员审查）、操作管理（管理员添加、管理员审查、管理员退出）、系统配置、后台通知等功能

9.内容:管理文章分类 (添加分类、删除分类、修改分类) 、 管理文章

10.维护:查看系统日志、文件变动效验、刷新网站缓存、在线更新系统、清除数据、文件管理等功能

11.权限管理：可以创建不同身份，不同管理员，同一个管理员可以拥有多重身份，权限可以控制到每一个控制器函数，例如：张三 1.可以控制他可以查看产品，但不能编辑产品； 2.可以添加产品，但不能删除产品； 3.可以查看用户但不能给用户发信息、加积分、开通分销等等； 。。。灵活应用，权限想怎么配就怎么配

**技术亮点**
    1.后台应用form-builder PHP快速生成现代化表单；
    2.前端以Vue + RequireJS模块化开发；
    3.PHPExcel数据导出,导出表格更加美观,可视；
    4.EasyWeChat部署微信开发,微信接入更加快捷,简单；
    5.后台应用ECharts实现完善的数据统计和分析；
    6.内部预留事件钩子,方面用户二次开发；
    7.后台多任务窗口化操作界面；
    8.内置强大灵活的权限管理；
    9.内置组合数据,系统配置,管理碎片化数据；
    10.客户端完善的交互效果和动画；
    11.对接公众号和小程序,并且数据同步；
    12.内置客服系统；
    13.高频数据缓存；
    14.数据备份和恢复
    15.一键安装；

- 推荐理由：开源微信公众号商城 小程序商城系统，带分销、拼团、秒杀、砍价、优惠券、积分等功能，前后端全部开源，更是一套方便二次开发的框架，表单直接生成无需写表单页面

- 示例代码：
无需模版页面，直接创建生成表单
~~~
public function create($cid = 0)
    {
        $field = [];
        $field[] = Form::input('menu_name','按钮名称')->required('按钮名称必填');
        $field[] = Form::select('pid','父级id',$cid)->setOptions(function(){
            $list = (Util::sortListTier(MenusModel::all(function($m){
                $m->order('sort DESC,id ASC');
            })->toArray(),'顶级','pid','menu_name'));
            $menus = [['value'=>0,'label'=>'顶级按钮']];
            foreach ($list as $menu){
                $menus[] = ['value'=>$menu['id'],'label'=>$menu['html'].$menu['menu_name']];
            }
            return $menus;
        })->filterable(1);
        $field[] = Form::select('module','模块名')->options([['label'=>'总后台','value'=>'admin']]);
        if($cid)$controller = MenusModel::where('id',$cid)->value('controller')?:'';
        else $controller = '';
        $field[] = Form::input('controller','控制器名',$controller);
        if (!empty($controller))
        {
            $controller = preg_replace_callback('/([.]+([a-z]{1}))/i', function ($matches) {
                return '\\' . strtoupper($matches[2]);
            }, $controller);
            if(class_exists('\app\admin\controller\\' . $controller))
            {
                $list = get_this_class_methods('\app\admin\controller\\' . $controller);

                $field[] = Form::select('action','方法名')->setOptions(function()use($list){
                    $menus = [['value'=>0,'label'=>'默认函数']];
                    foreach ($list as $menu){
                        $menus[] = ['value'=>$menu,'label'=>$menu];
                    }
                    return $menus;
                })->filterable(1);
            }else{
                $field[] = Form::input('action','方法名');
            }
        }
        $field[] = Form::input('params','参数')->placeholder('举例:a/123/b/234');
        $field[] = Form::frameInputOne('icon','图标',Url::build('admin/widget.widgets/icon',array('fodder'=>'icon')))->icon('ionic');
        $field[] = Form::number('sort','排序',0);
        $field[] = Form::radio('is_show','是否菜单',0)->options([['value'=>0,'label'=>'隐藏'],['value'=>1,'label'=>'显示(菜单只显示三级)']]);
        $form = Form::make_post_form('添加权限',$field,Url::build('save'),3);
        $this->assign(compact('form'));
        return $this->fetch('public/form-builder');
    }
~~~

- 截图：
后台部分页面
![WX20190725-091206](https://user-images.githubusercontent.com/14051877/61838731-3ef7f400-aebd-11e9-9da6-43b25a46f646.png)
![WX20190725-092022](https://user-images.githubusercontent.com/14051877/61838762-75ce0a00-aebd-11e9-9a98-5d57cb9ea3e1.png)
手机端部分页面
![1](https://user-images.githubusercontent.com/14051877/61838780-8aaa9d80-aebd-11e9-8df9-cd46eb70cea1.jpg)
![2](https://user-images.githubusercontent.com/14051877/61838781-8aaa9d80-aebd-11e9-9758-e7edd86e6820.jpg)
![3](https://user-images.githubusercontent.com/14051877/61838782-8b433400-aebd-11e9-8fd1-c324a48f2222.jpg)
![4](https://user-images.githubusercontent.com/14051877/61838783-8b433400-aebd-11e9-9039-f1225d4b3b3c.jpg)
![5](https://user-images.githubusercontent.com/14051877/61838784-8b433400-aebd-11e9-85a7-571fd4358e32.jpg)
![6](https://user-images.githubusercontent.com/14051877/61838786-8bdbca80-aebd-11e9-908f-5353a72078ce.jpg)
![7](https://user-images.githubusercontent.com/14051877/61838787-8bdbca80-aebd-11e9-9948-783e7f54b399.jpg)
![8](https://user-images.githubusercontent.com/14051877/61838789-8bdbca80-aebd-11e9-913d-741f528e82a3.jpg)
后台演示地址：
http://demo.crmeb.net  帐号：demo 密码：crmeb.com
前台演示
![二维码](https://user-images.githubusercontent.com/14051877/61838871-e37a3600-aebd-11e9-935d-553171cdaa60.jpg)

谢谢！

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 40 期](https://hellogithub.com/periodical/volume/40/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
