### ISSUE TITLE
awesome-captcha

### ISSUE THREAD

**Issue by Lase75** [521xueweihan/HelloGitHub#722]
## 项目推荐
- 项目地址：
https://github.com/ZYSzys/awesome-captcha
- 类别：请从中选择（C、C#、C++、CSS、Go、Java、JS、Kotlin、Objective-C、PHP、Python、Ruby、Swift、其它、书籍、机器学习）
Python
- 项目后续更新计划：

- 项目描述：
  - 必写：验证码破解相关合集
  - 可选：机器学习相关
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：captcha破解

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

**Comment by 521xueweihan** [comment]
@Lase75 请删除无用信息，增加描述。
