### ISSUE TITLE
Python 之旅（explore-python）

### ISSUE THREAD

**Issue by leaicc** [521xueweihan/HelloGitHub#723]
## 项目推荐
- 项目地址：https://github.com/ethan-funny/explore-python

- 类别：Python

- 项目后续更新计划：已完结

- 项目描述：
  这是作者在学习 Python 的过程中所做的笔记，进行加工和完善之后，集结成册，深入浅出，条理清晰。你完全可以把它当成手册，需要时拿来查阅，每篇篇幅不长，却能直击要点。

- 推荐理由：由于我也有做笔记的习惯，所以读起来就像查阅自己写的东西一样，详实，实用。

- 截图：![](https://i.loli.net/2019/07/26/5d3a73c0de91096513.png)

**Comment by 521xueweihan** [comment]
@leaicc 已推荐过。https://hellogithub.com/periodical/search/?q=https://github.com/ethan-funny/explore-python
