### ISSUE TITLE
开源项目自荐:  wewe: 将微信, slack 等群聊消息公开到互联网

### ISSUE THREAD

**Issue by timqian** [521xueweihan/HelloGitHub#724]
## 项目推荐
- 项目地址：https://github.com/t9tio/wewe
- 网址: https://wewe.t9t.io

- 类别：JS

- 项目后续更新计划：会持续更新

- 项目描述：
  解决群聊天信息没办法沉淀的问题, 主要功能有
  - 在一个地方记录了群聊里的信息, 群外人也可以看到
  - 可以被搜索引擎搜到
  - 话题抽取,便于浏览和搜索
  - 聊天内容的分析(unfinished)
  - 支持各种群聊工具(目前支持微信群和 slack 群, 并且计划支持 telegram/gitter 等主流群聊工具)

- 截图：
![](https://raw.githubusercontent.com/timqian/images/master/20190729165545.png)
![](https://raw.githubusercontent.com/timqian/images/master/20190729120702.png)
![](https://raw.githubusercontent.com/timqian/images/master/20190729165537.png)
![](https://raw.githubusercontent.com/timqian/images/master/20190729165541.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
