### ISSUE TITLE
C# redis 客户端SDK —— CSRedis

### ISSUE THREAD

**Issue by 2881099** [521xueweihan/HelloGitHub#725]
## 项目推荐
- 项目地址：https://github.com/2881099/csredis

- 类别：C#

- 项目后续更新计划：持续更新新命令，如 redis 5.0 stream 类型

- 项目描述：
  - 必写：解决了使用其他库的易用和稳定问题；
  - 可选：CSRedis 所有方法名与 redis-cli 保持一致；
  - 描述长度：支持 redis 2.8-5.0 所有功能和命令、哨兵、集群。

- 推荐理由：CSRedis 是 redis.io 官方推荐的 c# 客户端驱动，于2016年开始持续迭代更新，实现了低门槛、高性能，和分区高级玩法。

- 示例代码：
```csharp
var csredis = new CSRedis.CSRedisClient("127.0.0.1:6379,password=123");
RedisHelper.Initialization(csredis);

RedisHelper.Set("test1", "123123", 60);
RedisHelper.Get("test1");
//...函数名与 redis-cli 的命令相同

//普通订阅
RedisHelper.Subscribe(
  ("chan1", msg => Console.WriteLine(msg.Body)),
  ("chan2", msg => Console.WriteLine(msg.Body)));

//管道操作
RedisHelper.StartPipe().Set("a", "1").Get("a").EndPipe();
```

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 41 期](https://hellogithub.com/periodical/volume/41/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了《讲解开源项目》系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
