### ISSUE TITLE
looter-轻量级的Python爬虫框架

### ISSUE THREAD

**Issue by alphardex** [521xueweihan/HelloGitHub#726]
## 项目推荐
- 项目地址：https://github.com/alphardex/looter

- 类别：Python

- 项目后续更新计划：暂无

- 项目描述：
一个轻量级的爬虫框架，使得爬虫开发变得更加简单高效。

- 推荐理由：
1. 极容易上手
2. 工作流很简单：爬虫模板与命令行调试
3. 有大量的[例子](https://github.com/alphardex/looter/tree/master/examples)
4. 源码简单易懂，方便进一步的定制

- 示例代码：

3行代码实现图片链接爬虫

``` sh
$ looter shell https://konachan.com/post
```

``` python
>>> imgs = tree.css('a.directlink::attr(href)').extract()
>>> Path('konachan.txt').write_text('\n'.join(imgs))
```

**Comment by 521xueweihan** [comment]
@alphardex 该项目暂时不能收录到月刊中，建议：
1. 增加架构、原理图
2. 项目目录说明和讲解，有助于帮助想提交 PR 的开发者快速了解
3. API 可以设计的更加优雅，便于当作模块引用部分功能或者 tools
