### ISSUE TITLE
overcommit配置git hook 进行静态代码质量检查

### ISSUE THREAD

**Issue by JohnnyTing** [521xueweihan/HelloGitHub#727]
## 项目推荐
- 项目地址：https://github.com/sds/overcommit

- 类别：Ruby

- 项目后续更新计划：暂无

- 项目描述：
  -  一个可配置的git hook管理工具，通常集成各个语言的代码质量检查工具，来保证代码质量
  - 对于团队需要遵守语言代码规范的，很有必要

- 推荐理由：
1. 文档完善，易上手
2. git hook配置灵活
3. 支持多种语言的代码质量lint
4. 有很多例子，可直接拿来用

- 截图：
![image](https://camo.githubusercontent.com/570845b00471b22e484e01c65fa43c2cae8de4b0/68747470733a2f2f7364732e6769746875622e696f2f6f766572636f6d6d69742f6f766572636f6d6d69742e676966)

**Comment by daixiang0** [comment]
您推荐的项目已收录到专栏，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 pray

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 41 期](https://hellogithub.com/periodical/volume/41/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了《讲解开源项目》系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
