### ISSUE TITLE
Antmove，小程序跨平台开发统一解决方案

### ISSUE THREAD

**Issue by xiaofuzi** [521xueweihan/HelloGitHub#729]
## 项目推荐
- 项目名称：蚂蚁搬家工具
- 项目地址：https://github.com/ant-move/antmove

- 类别：JS

- 项目后续更新计划：
  - 支付宝转百度能力支持
  - 支付宝转微信能力支持
  - 支付宝转头条能力支持
  - 页面/组件维度转换能力支持

- 项目描述：

> 一键实现微信小程序项目到支付宝小程序的迁徙，不再为重复开发而烦恼。

antmove 的初衷是提供一种小程序跨平台开发的解决方案，帮助开发者底层本实现小程序的跨平台开发（微信小程序、支付宝小程序、百度智能小程序、头条小程序），做到一套代码开发、多小程序平台运行的目的。

目前 antmove 已经帮助了多款微信小程序到支付宝小程序的迁徙，代码转换率高达 90%+，极大的降低了小程序开发企业的人力成本。工具不仅能做到运行时 diff 的抹平，也能部分做到一个 API 从无到有的过程以及缺失组件的支持。

### 特性

* 简单易使用，无学习成本，直接上手
* 转换覆盖率全面，及时跟进各小程序平台更新情况
* 配套详细的编译时日志/运行时日志工具
* 编译生成代码可读性强，可二次编程
* 二次编译支持

- 推荐理由：蚂蚁搬家工具，让小程序跨平台开发变得简单。

![antmove](https://img.alicdn.com/tfs/TB13u6Cb4z1gK0jSZSgXXavwpXa-3852-936.png)

**Comment by 521xueweihan** [comment]
@xiaofuzi 您好，已推荐过类似项目，您的项目暂不能收录到月刊中。
