### ISSUE TITLE
mica-auto 注解自动生成 Spring boot starter  配置 Spring boot starter 开发利器

### ISSUE THREAD

**Issue by ChunMengLu** [521xueweihan/HelloGitHub#731]
## 项目推荐
- 项目地址：https://github.com/lets-mica/mica-auto

- 类别：Java

- 项目后续更新计划：工具型项目，目前相对完善，后续有需求时会再添加。

- 项目描述：
  - 必写：利用注解自动生成 Spring boot starter  配置
  - 可选：Spring boot starter 开发利器，避免手写配置，避免改了代码忘记改配置导致服务启动失败，规避Spring包扫描问题。

- 推荐理由：编译器自动完成，高效、可靠

### 编辑完推荐项目的信息，**请删除**下述提示信息

再次感谢您对《HelloGitHub》项目的支持！

**Comment by smart2pet** [comment]
@521xueweihan This isn't a spam/bad issue. Please come and review it. Thanks.
