### ISSUE TITLE
【自薦項目】Bullet : 漂亮的 Command Line Tool 選單函式庫

### ISSUE THREAD

**Issue by Mckinsey666** [521xueweihan/HelloGitHub#734]
## 项目推荐
- 项目地址：https://github.com/Mckinsey666/bullet

- 类别：Python

- 项目后续更新计划：
  - 支援Windows平台
- 项目描述：這是一個終端機上，充滿設計感的使用者輸入 / 選單函式庫。在 config 一個專案時常需要使用者從列表中選擇，或者 prompt 使用者輸入。此函式庫提供了一個完整，顏色格式皆可客製化的 Wrapper，讓開發者無痛創造出漂亮的使用者輸入介面。

- 推荐理由：使用者可以「在Terminal上」使用方向鍵使用工具列選單（單選 / 複選），同時也能讓使用者輕鬆的客製化使用者輸入格式與顏色。目前支援的使用者輸入有：

  - 單選（用方向鍵控制）
  - 複選（用方向鍵控制）
  - 滑桿
  - 一般文字輸入
  - 密碼輸入
  - 是否輸入
  - 數字輸入

重點是，這全都是在終端機上實做出來的！

- 示例代码：
```python
# 單選輸入用法
from bullet import Bullet

cli = Bullet(
        prompt = "\nPlease choose a fruit: ",
        choices = ["apple", "banana", "orange", "watermelon", "strawberry"], 
        indent = 0,
        align = 5, 
        margin = 2,
        shift = 0,
        bullet = "",
        pad_right = 5
    )

result = cli.launch()
print("You chose:", result)
```

- 截图：

![demo](https://user-images.githubusercontent.com/32431810/62419009-85153a80-b6a9-11e9-9aa2-b8dfb34db8ce.gif)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 41 期](https://hellogithub.com/periodical/volume/41/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了《讲解开源项目》系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
