### ISSUE TITLE
PC版微信机器人

### ISSUE THREAD

**Issue by TonyChen56** [521xueweihan/HelloGitHub#737]
## 项目推荐
- 项目地址：https://github.com/TonyChen56/WeChatRobot

- 类别：C++

- 项目后续更新计划：无更新计划

- 项目描述：
用C++实现的PC版微信机器人。实现功能：接收和发送所有类型消息 获取联系人和群 自动聊天 自动收款 自动同意好友请求 防撤回 无限多开 解密数据库等等等等~

- 推荐理由：是目前实现功能最多的PC版本的微信机器人

**Comment by ChungZH** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
