### ISSUE TITLE
黑客工具集HackTools

### ISSUE THREAD

**Issue by TonyChen56** [521xueweihan/HelloGitHub#738]
## 项目推荐
- 项目地址：https://github.com/TonyChen56/HackerTools

- 类别：C++

- 项目后续更新计划：无更新计划

- 项目描述：
这是一个将所有黑客技术都收纳进一个程序的工具，能够帮助网络安全行业的入门人员了解和学习黑客技术，入门信息安全行业。 目前已有的技术有：注入技术 启动技术 自启动技术 提权技术 加密技术 压缩技术 桌面截屏 U盘小偷 文件监控 按键记录等等

**Comment by 521xueweihan** [comment]
@TonyChen56 你好我看了你的两个项目。

**Comment by ChungZH** [comment]
> @TonyChen56 你好我看了你的两个项目。

啊，干啥，前几天你叫我看了，然后呢？

**Comment by ChungZH** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
