### ISSUE TITLE
自荐项目：巡云轻论坛系统

### ISSUE THREAD

**Issue by diyhi** [521xueweihan/HelloGitHub#739]
## 项目推荐
- 项目地址：https://github.com/diyhi/bbs

- 类别：Java

- 项目后续更新计划：会员权限，会员权益等功能已在开发中

- 项目描述：
巡云轻论坛系统采用JAVA+MYSQL架构，自适应手机端和电脑端，界面简洁，性能高效。数据库表结构设计使用分表方案,提高系统的负载能力。后台数据库备份/还原、全站指定目录打包、一键自动升级等功能使维护简单方便。系统拥有强大的模板管理功能，布局版块支持设置输出条件，让前端页面展示方便快捷。

- 推荐理由：界面好看，功能强大

- 截图：
![1](https://user-images.githubusercontent.com/37889044/62755495-c9884800-baa6-11e9-95cb-808ec5dbea68.jpg)

![3](https://user-images.githubusercontent.com/37889044/62755504-d9a02780-baa6-11e9-97e1-490e6df73263.jpg)

![5](https://user-images.githubusercontent.com/37889044/62755521-eb81ca80-baa6-11e9-997a-67d00f136d38.jpg)

![m1](https://user-images.githubusercontent.com/37889044/62755548-0d7b4d00-baa7-11e9-8c15-e83eaf511ac7.jpg)

![m3](https://user-images.githubusercontent.com/37889044/62755564-18ce7880-baa7-11e9-8f15-76e2a6b7470c.jpg)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
