### ISSUE TITLE
鸿蒙 OS

### ISSUE THREAD

**Issue by ChungZH** [521xueweihan/HelloGitHub#740]
## 项目推荐
- 项目地址：
https://github.com/Awesome-HarmonyOS/HarmonyOS
- 类别：C

- 项目后续更新计划：

- 项目描述：鸿蒙系统是基于微内核的全场景分布式 OS，可按需扩展，实现更广泛的系统安全，主要用于物联网，特点是低时延，甚至可到毫秒级乃至亚毫秒级。鸿蒙 OS 实现模块化耦合，对应不同设备可弹性部署，鸿蒙 OS 有三层架构，第一层是内核，第二层是基础服务，第三层是程序框架 。可用于大屏、PC、汽车等各种不同的设备上。还可以随时用在手机上，但暂时华为手机端依然优先使用安卓。鸿蒙 OS 底层由鸿蒙微内核、Linux 内核、Lite OS 组成，未来将发展为完全的鸿蒙微内核架构。

- 推荐理由：分布式架构，实现跨终端无缝协同体验；通过统一 IDE 支撑一次开发，多端部署，实现跨终端生态共享。

- 示例代码：

- 截图：

**Comment by idongliming** [comment]
这个不是官方的，只是记录新闻，等官方开源吧。

---原始邮件---
发件人: "Haoshen Zhong"<notifications@github.com>
发送时间: 2019年8月10日(星期六) 晚上6:07
收件人: "521xueweihan/HelloGitHub"<HelloGitHub@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [521xueweihan/HelloGitHub] 鸿蒙 OS (#740)



项目推荐
  
 
项目地址：
 https://github.com/Awesome-HarmonyOS/HarmonyOS
 
 
类别：C
 
 
项目后续更新计划：
 
 
项目描述：鸿蒙系统是基于微内核的全场景分布式 OS，可按需扩展，实现更广泛的系统安全，主要用于物联网，特点是低时延，甚至可到毫秒级乃至亚毫秒级。鸿蒙 OS 实现模块化耦合，对应不同设备可弹性部署，鸿蒙 OS 有三层架构，第一层是内核，第&#x4E8C;层是基础&#x670D;务，第三层是程序框架 。可用于大屏、PC、汽车等各种不同的设备上。还可以随时用在手机上，但暂时华为手机端依然优先使用安卓。鸿蒙 OS 底层由鸿蒙微内核、Linux 内核、Lite OS 组成，未来将发展为完全的鸿蒙微内核架构。
 
 
推荐理由：分布式架构，实现跨终端无缝协同体验；通过统一 IDE 支撑一次开发，多端部署，实现跨终端生态共享。
 
 
示例代码：
 
 
截图：
  
&mdash;

**Comment by ChungZH** [comment]
无法确定是否官方发布，先 close。
