### ISSUE TITLE
PyPyTorch

### ISSUE THREAD

**Issue by dark-ai** [521xueweihan/HelloGitHub#741]
## 项目推荐
- 项目地址：https://github.com/dark-ai/pypytorch.git

- 类别：Python, Deep Learning

- 项目后续更新计划：Make framework more powerful

- 项目描述：
  - 必写：PyPyTorch is a simple deep learning framework implemented by Python3, 代码简洁明了(因为是用 Python3 实现的, 代码相对 C/C++ 实现的框架简洁明了),  参考 README.md 下载数据集放置到执行的区域, 可以跑通 README.md 中 gif 的代码
  - 描述长度（不包含示例代码）: PyPyTorch 的出发地是学习为主, 通过 PyPyTorch 让初学者了解框架运行原理

- 推荐理由：基于 Python3 实现的深度学习框架, 基于动态图, 为了方便学习, 接口基本与 PyTorch 一致, 代码简洁, 方便学习

- 截图：（可选）gif/png/jpg

**Comment by Eurus-Holmes** [comment]
Interesting! 期待后续更新:)

**Comment by Eurus-Holmes** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
