### ISSUE TITLE
Android 人脸美妆项目

### ISSUE THREAD

**Issue by DingProg** [521xueweihan/HelloGitHub#748]
## 项目推荐
- 项目地址：https://github.com/DingProg/Makeup

- 类别：Android/Java

- 项目后续更新计划：
暂无更新计划

- 项目描述：
  - 这是一个人脸美妆的项目
  - 使用Canvas来给人脸画妆
  - 唇彩，美瞳，粉底，眼影，腮红，眼线，双眼皮，眉毛等，能画的妆，都画了

- 推荐理由：如果你正在研究图形处理，人脸美妆，Android/Java  Canvas基础API这个项目适合你

- 截图：

- ![](https://camo.githubusercontent.com/969d58bf36cfc6ae2b812e75db434edfbd46aa5f/68747470733a2f2f757365722d676f6c642d63646e2e786974752e696f2f323031392f382f392f313663373433626231336639373162393f773d34353626683d34393426663d706e6726733d323932353035)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
@DingProg 你好，有几个修改建议：
1. Readme 最重要的是说明这是个什么项目、是 APP 还是库、安装步骤、快速开始后续更新计划等，能让人对你的项目是做什么的一目了然，而不是要去你的“文章”中找上述的信息。
2. 详细的原理讲解可以放到 文档文件中，Readme 中引用就好。
