### ISSUE TITLE
项目打开没法build成功，求作者帮忙解答一下，应该是安装kotlin插件的问题

### ISSUE THREAD

**Issue by zj593743143** [521xueweihan/HelloGitHub#75]
## 项目推荐
- 项目名称：

- 项目地址：

- 项目语言：

- 项目描述：

- 推荐理由：

- 示例代码：

- 截图：

### 编辑完推荐项目的信息，下述提示信息**请删除**
非常感谢推荐这么好的项目

如您推荐的项目收录到《HelloGitHub》月刊，您的GitHub帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/contributors.md)，**同时会在此 issues 中通知您**。

再次感谢您对《HelloGitHub》项目的支持！

HelloGitHub 网站：https://hellogithub.com

**Comment by 521xueweihan** [comment]
@zj593743143 请尽可能详细的描述问题，根据你现在提供的信息我无法帮助你。

提问也是门技术，不是
