### ISSUE TITLE
Flutter 画中画的效果

### ISSUE THREAD

**Issue by DingProg** [521xueweihan/HelloGitHub#752]
## 项目推荐
- 项目地址：https://github.com/DingProg/FlutterPIP

- 类别：Flutter/Dart

- 项目后续更新计划：后续Flutter处理图片的一些更牛的效果

- 项目描述：
  - Flutter跨平台图片处理
  - 学习到跨平台上怎么使用Canvas来绘图，搞出漂亮的效果

- 推荐理由：看一看截图效果，个人觉得挺不错的

![](https://github.com/DingProg/FlutterPIP/blob/master/screen/main.png)

![](https://github.com/DingProg/FlutterPIP/blob/master/screen/pip_cd.png)
![](https://github.com/DingProg/FlutterPIP/blob/master/screen/pip_pao.png)
![](https://github.com/DingProg/FlutterPIP/blob/master/screen/pip_movie.png)
![](https://github.com/DingProg/FlutterPIP/blob/master/screen/pip_gloass.png)
![](https://github.com/DingProg/FlutterPIP/blob/master/screen/pip_photo.png)
![](https://github.com/DingProg/FlutterPIP/blob/master/screen/pip_draw.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目，本月刊暂时不支持此类项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
