### ISSUE TITLE
[自荐项目]：softest

### ISSUE THREAD

**Issue by prprprus** [521xueweihan/HelloGitHub#754]
## 项目推荐
- 项目地址：https://github.com/prprprus/softest

- 类别：JS

- 项目后续更新计划：添加局部截图功能；添加对测试结果的分析等

- 项目描述：
  - softest 是一款端对端的测试工具，用于录制用户跟浏览器之间的交互，并生成测试脚本，简单而且实用。

- 推荐理由：让你不用写一行代码就可以得到测试脚本。

- 截图：[![Watch the video](https://raw.githubusercontent.com/prprprus/picture/master/softest2.png)](https://www.bilibili.com/video/av64092242/)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
