### ISSUE TITLE
一个开源的跨平台服务器框架及一个ARPG应用例子

### ISSUE THREAD

**Issue by ylmbtm** [521xueweihan/HelloGitHub#755]
## 项目推荐
- 项目地址：https://github.com/ylmbtm/GameProject3

- 类别：C、C#、C++

- 项目后续更新计划：项目会持续开发

- 项目描述：
  - 必写：这是一个跨平台的游戏服务器框架，网络有三种实现方式可选Boost, Libuv及socketapi实现，以及使用这个框架实现的一个arpg游戏。
  - 可选：初选者可以学习如何使用boost asio， libuv , socket api实现高性能的服务器框架
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：高性能跨平台的游戏服务器框架， 以及一个资源丰定的arpg游戏demo

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

## 提示
> 点击上方 “Preview” 更方便地阅读以下内容，

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
@ylmbtm 抱歉，加群获取源码的项目，本月刊暂不支持收录。

**Comment by ylmbtm** [comment]
源码全部在github上，只是客户端的资源太大了，之前免费的空间有限，不让上传而己，服务器的所有代码都是在github上。

在 2019-08-25 18:47:32，"削微寒" <notifications@github.com> 写道：


@ylmbtm 抱歉，加群获取源码的项目，本月刊暂不支持收录。
