### ISSUE TITLE
【项目自荐】: rc-leaflet 基于Leaflet.js的React地图组件库，支持TypeScript

### ISSUE THREAD

**Issue by Coder-JJ** [521xueweihan/HelloGitHub#756]
## 项目推荐
- 项目地址：
[rc-leaflet](https://github.com/Coder-JJ/rc-leaflet)

- 类别：
JS

- 项目后续更新计划：
  - LayerGourp组件
  - FeatureGroup组件
  - ImageOverlay组件
  - SvgOverlay组件
  - 周边插件（聚合点位，热力图，绘制工具，路径规划）

- 项目描述：
  - 基于Leaflet.js引擎的React地图组件库，支持TypeScript
  - 利用React组件的生命周期，对Leaflet.js API进行抽象封装，用数据驱动视图

- 推荐理由：
  - 支持TypeScript
  - 弹出层，提示框，点位支持JSX内容
  - 支持海量点位组件
  - 支持聚合点位组件
  - 支持主题定制
  - 支持按需加载

- 示例代码：
```jsx
import { RCMap, TileLayer, DivIcon, Point, Polyline } from 'rc-leaflet'

<RCMap>
  <TileLayer.AMap />
  <Point position />
  <Point position >
    <DivIcon className />
    <Point.Content className>this is content.</Point.Content>
  </Point>
  <Polyline  points />
</RCMap>
```

- 截图：

![image](https://user-images.githubusercontent.com/34091965/63311506-d58aca00-c330-11e9-8243-d7d5f4a07a16.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
