### ISSUE TITLE
[开源项目自荐]: chart.xkcd - xkcd 风格(手绘风格)的图表库

### ISSUE THREAD

**Issue by timqian** [521xueweihan/HelloGitHub#757]
## 项目推荐
- 项目地址： https://github.com/timqian/chart.xkcd

- 类别：JS

- 项目后续更新计划：持续更新

- 项目描述：xkcd 风格(手绘风格)的图表库

- 截图：
![](https://raw.githubusercontent.com/timqian/images/master/20190819131226.gif)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 41 期](https://hellogithub.com/periodical/volume/41/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了《讲解开源项目》系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
