### ISSUE TITLE
一个纯静态工具站

### ISSUE THREAD

**Issue by yimogit** [521xueweihan/HelloGitHub#76]
## 项目推荐
- 项目名称：meTools

- 项目地址：https://github.com/yimogit/metools

- 项目语言：Javascript

- 项目描述：使用vue.js+layui构建的纯静态个人工具站点。

- 推荐理由：需要【加密/解密】【编码/解码】【生成二维码】【在线翻译】的时候不用再去百度一下~ fork之后绑定pages即可食用

- 示例代码： 添加组件后配置到`metools/static/data/initData.js`即可

- 截图：

![图片](https://dn-coding-net-production-pp.qbox.me/d723e53d-8a72-4e2e-9445-94a831117cdb.png)

![图片](https://dn-coding-net-production-pp.qbox.me/964d58e5-da1e-4792-aec7-e029305ef168.png)

![图片](https://dn-coding-net-production-pp.qbox.me/038a28e0-e563-4664-b67c-86b93ea392a8.png)

**Comment by 521xueweihan** [comment]
@yimogit 我个人认为，此类工具脚本可以做一个脚本集合，而不是做成 web app 的方式。

1. 新手可以在学习完一种编程语言，可以通过此类脚本练手
2. 使用方面
3. 如果做成 model 形式，方便引用与扩展
