### ISSUE TITLE
macOS AppearancesSwitcher

### ISSUE THREAD

**Issue by GMWorkStudio** [521xueweihan/HelloGitHub#762]
## 项目推荐
- 项目地址：
https://github.com/GMWorkStudio/AppearancesSwitcher
- 类别：Swift
- 项目后续更新计划：
* 增加自动切换主题功能
- 项目描述：
  - 功能： macOS 切换“亮/暗”主题的工具
  - 介绍：根据喜好切换 macOS “亮/暗”主题，免去到"偏好设置"中选择
- 推荐理由：
可以在 “ macOS 通知中心”中快速切换“亮 /暗”主题。
- 截图：
![image](https://raw.githubusercontent.com/GMWorkStudio/AppearancesSwitcher/master/screenshot/preview.png)

再次感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 41 期](https://hellogithub.com/periodical/volume/41/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
