### ISSUE TITLE
AoE：一种快速集成AI的终端运行环境SDK

### ISSUE THREAD

**Issue by Kuloud** [521xueweihan/HelloGitHub#764]
## 项目推荐
- 项目地址：
https://github.com/didi/AoE

- 类别：
机器学习

- 项目后续更新计划：
https://github.com/didi/AoE/blob/master/ROADMAP.md

- 项目描述：
AoE (AI on Edge) 是一个滴滴开源的终端侧AI集成运行时环境(IRE)。以 “稳定性、易用性、安全性” 为设计原则，帮助开发者将不同框架的深度学习算法轻松部署到终端高效执行。

- 推荐理由：
终端侧AI集成运行时环境(IRE)，简化终端AI模型部署落地

![image](https://user-images.githubusercontent.com/2024271/63564774-01a88400-c599-11e9-9630-ea68a1caea0e.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
