### ISSUE TITLE
javascript在线学习答题系统

### ISSUE THREAD

**Issue by Zo3i** [521xueweihan/HelloGitHub#769]
## 项目推荐
- 项目地址：
后端: https://github.com/Zo3i/CodeJsSystem
前端: https://github.com/Zo3i/CodeJsFront

- **演示地址：** http://xcoding.me
- 类别：Js

- 项目后续更新计划：
    新增题目分类，答题讨论
- 项目描述：
  可以在线进行Js答题，学习Js编程，管理员可自定义题库。可以在答题之后查看别人的答案。学习别人的编程思路。

- 推荐理由：适用于刚刚开始学习Js语言的小伙伴

- 截图：
![](https://i.bmp.ovh/imgs/2019/08/9daf4bfd05275bc8.png)
![](https://i.bmp.ovh/imgs/2019/08/d5d2baa8e279ef28.png)
![](https://i.bmp.ovh/imgs/2019/08/ebc14d1cb24437bb.png)
![](https://i.bmp.ovh/imgs/2019/08/b9b0d526757e1bcf.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
