### ISSUE TITLE
Markdown Nice 最好用的markdown微信排版工具

### ISSUE THREAD

**Issue by guanpengchn** [521xueweihan/HelloGitHub#770]
## 项目推荐

- 项目地址：https://github.com/zhning12/markdown-nice

- 类别：JavaScript

- 项目后续更新计划：浏览器插件，Markdown 中文指北纠正器

- 项目描述：
  - 必写：支持自定义样式的 Markdown 编辑器，支持微信公众号排版，支持知乎、稀土掘金、博客园和CSDN等一系列平台，内容和自定义样式浏览器中实时保存，支持上传图片、脚注、公式
  - 可选：Markdown排版
  - 描述长度（不包含示例代码）: 支持自定义样式的 Markdown 编辑器，支持微信公众号排版，支持知乎、稀土掘金、博客园和CSDN等一系列平台，内容和自定义样式浏览器中实时保存，支持上传图片、脚注、公式

- 推荐理由：解决微信公众号排版，和其他平台排版问题，提供大量定制主题，并且提供自定义主题功能

- 截图：

![20190826115509](https://user-images.githubusercontent.com/13995641/63664248-60b80400-c7f8-11e9-9c93-0747a643581f.jpg)

**Comment by 521xueweihan** [comment]
我最近就在用你的工具，比我之前用的那个方便、美观。

感谢开源如此好用的工具，诚挚的邀请您加入我们的[《讲解开源系列》](https://github.com/HelloGitHub-Team/Article)，您的文章我们会全平台单推，这样带来的曝光会更多，让您的项目被更多人所发现和使用。

**Comment by guanpengchn** [comment]
@521xueweihan 感谢支持，受宠若惊，我去看一下

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 42 期](https://hellogithub.com/periodical/volume/42/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
