### ISSUE TITLE
Notable

### ISSUE THREAD

**Issue by ChungZH** [521xueweihan/HelloGitHub#771]
## 项目推荐
- 项目地址：https://github.com/notable/notable

- 类别：JS

- 项目后续更新计划：

- 项目描述：这是一个使用 TypeScript 开发的 Markdown 编辑器，支持 Windows、Mac OS 以及 Linux。它是用 GFM(GitHub-Flavored Markdown) 编写和渲染的，不是 WYSIWYG（What You See Is What You Get，所见即所得）。没有专有格式，简洁漂亮，可以导入 Evernote 笔记。

- 推荐理由：漂亮，好用

- 示例代码：（可选）长度：1-20 行

- 截图：![](https://github.com/notable/notable/raw/master/resources/demo/main.png)

## 提示
> 点击上方 “Preview” 更方便地阅读以下内容，

**意见和反馈 BUG 请移步，[反馈意见收集贴](https://github.com/521xueweihan/HelloGitHub/issues/673)。新建 issues 只接受项目推荐，如不是则会被 bot 关闭。**

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
已推荐过类似的项目，该项目暂不能收录到月刊中。
