### ISSUE TITLE
Android 人脸美妆项目

### ISSUE THREAD

**Issue by DingProg** [521xueweihan/HelloGitHub#772]
## 项目推荐
- 项目地址：https://github.com/DingProg/Makeup

- 类别：Android/Java

- 项目后续更新计划：
更多美妆演示效果的更新，后续计划加入AI部分

- 项目描述：
  - 这是一个人脸美妆的项目
  - 使用Canvas来给人脸画妆
  - 唇彩，美瞳，粉底，眼影，腮红，眼线，双眼皮，眉毛等，能画的妆，都画了
  -  利用图形局部变形算法进行 大眼，瘦脸，丰胸，大长腿等

- 推荐理由：如果你正在研究图形处理，人脸美妆,图形局部变形，Android/Java  Canvas基础API这个项目适合你

- 截图：
美妆  
![image](https://user-images.githubusercontent.com/15081256/63691106-ecee1980-c840-11e9-834a-aec2da8a40f1.png)
![image](https://user-images.githubusercontent.com/15081256/63691110-f2e3fa80-c840-11e9-9a6a-1a431caaeab0.png)

![image](https://user-images.githubusercontent.com/15081256/63691133-02634380-c841-11e9-83a3-94dda8c19657.png)

- 备注：已更新README部分

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by 521xueweihan** [comment]
效果图看的我有点害怕。。。
