### ISSUE TITLE
Marktext

### ISSUE THREAD

**Issue by ChungZH** [521xueweihan/HelloGitHub#774]
## 项目推荐
- 项目地址：https://github.com/marktext/marktext

- 类别：JS

- 项目后续更新计划：

- 项目描述：这是一个**下一代**的 Markdown 编辑器，它简洁、优雅，专注于速度和可用性。它所见即所得，让您获得无干扰的写作体验。支持 CommonMark Spec、GFM、数学表达式（KaTeX）、front matter 和 emoji。你可以把它当作一个更强并且开源的 Typora。

- 截图：![](https://github.com/marktext/marktext/raw/develop/docs/marktext.png?raw=true)

**Comment by 521xueweihan** [comment]
@ChungZH 项目推荐语修改为：

一个简单且优雅的开源 Markdown 编辑器，支持 Linux、macOS 和 Windows [下载地址](https://github.com/marktext/marktext#download-and-install)。功能：
- 实时预览（所见即所得）和简洁明了的界面
- Markdown 扩展，例如数学表达式和 emoji 表情
- 输出 HTML 和 PDF 文件
- 各种编辑模式：源代码模式、打字机模式、专注模式
- 等等

如有疑问，欢迎留言反馈。
