### ISSUE TITLE
Python 项目推荐： Kivy，Python的跨平台应用开发框架

### ISSUE THREAD

**Issue by JackTheMico** [521xueweihan/HelloGitHub#775]
## 项目推荐
- 项目地址：https://github.com/kivy/kivy

- 类别：Python

- 项目后续更新计划：

- 项目描述：
Kivy是一个用来开发支持多点触控应用的开源跨平台Python框架，支持Windows, macOS, Linux, Android, iOS 五个平台的应用开发。特点是使用kv文件来对python代码中的对象进行配置，可以通过修改kv文件达到快速修改前端显示的效果。Kivy理论上可以实现一次编码，将应用发布到五个平台的效果。

**Comment by 521xueweihan** [comment]
@JackTheMico 我没看懂这个项目是干什么的。解决了什么痛点。示例效果。。。

**Comment by jaywcjlove** [comment]
@521xueweihan 用 Python 开发跨平台桌面应用程序的 ui 框架。
