### ISSUE TITLE
C ++ | 分布式图数据库

### ISSUE THREAD

**Issue by QingZ11** [521xueweihan/HelloGitHub#776]
- 项目地址：https://github.com/vesoft-inc/nebula

- 项目描述：

    Nebula Graph 的目标是为超大规模图数据提供高并发，低延时的读、写及计算服务。Nebula Graph 是世界上唯一能够容纳千亿个顶点和万亿条边，并提供毫秒级查询延时的图数据库解决方案。

    Nebula Graph 的主要特点：
    - 全对称分布式架构
    - 可扩展
    - 高可用
    - 数据强一致
    - 类 SQL 查询语言

- 项目截图：

![Nebula Graph 架构图](https://user-images.githubusercontent.com/38887077/63827768-effb1e00-c996-11e9-9af8-48e0849657a3.png)

![KV Store](https://user-images.githubusercontent.com/38887077/63827792-01442a80-c997-11e9-95c2-aeb19f136190.png)

![Meta Service](https://user-images.githubusercontent.com/38887077/63827811-0ef9b000-c997-11e9-9ee7-74730dc8a754.png)

![Query Engine & Query Language(nGQL)](https://user-images.githubusercontent.com/38887077/63827834-26d13400-c997-11e9-8236-802fc28c839a.png)

**Comment by 521xueweihan** [comment]
@FrontMage 雷神，试试这个图数据库

**Comment by ChungZH** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by ChungZH** [comment]
- 项目地址：https://github.com/vesoft-inc/nebula

- 项目描述：
    Nebula Graph 的目标是为超大规模的图数据提供高并发、低延时的读、写及计算服务。Nebula Graph 是世界上唯一能够容纳千亿个顶点和万亿条边、并提供毫秒级查询延时的图数据库解决方案。

    Nebula Graph 的主要特点：
    - 全对称分布式架构
    - 可扩展
    - 高可用
    - 数据强一致
    - 类 SQL 查询语言

- 项目截图：

![Nebula Graph 架构图](https://user-images.githubusercontent.com/38887077/63827768-effb1e00-c996-11e9-9af8-48e0849657a3.png)

![KV Store](https://user-images.githubusercontent.com/38887077/63827792-01442a80-c997-11e9-95c2-aeb19f136190.png)

![Meta Service](https://user-images.githubusercontent.com/38887077/63827811-0ef9b000-c997-11e9-9ee7-74730dc8a754.png)

![Query Engine & Query Language(nGQL)](https://user-images.githubusercontent.com/38887077/63827834-26d13400-c997-11e9-8236-802fc28c839a.png)

**Comment by ChungZH** [comment]
哈哈哈清蒸写的推荐真好，基本上没什么问题！

**Comment by QingZ11** [comment]
😆 卤蛋大佬 Demo 做得好

Haoshen Zhong <notifications@github.com> 于2019年9月20日周五 下午2:05写道：

**Comment by 521xueweihan** [comment]
推荐语修改细节：

Nebula Graph 是一款开源图数据库，目标是为超大规模的图数据提供高并发、低延时的读、写及计算服务。目前是世界上唯一能够容纳千亿个顶点和万亿条边、并提供毫秒级查询延时的图数据库解决方案。特点：
- 全对称分布式架构
- 可扩展
- 高可用
- 数据强一致
- 类 SQL 查询语言

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 42 期](https://hellogithub.com/periodical/volume/42/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了《讲解开源项目》系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
