### ISSUE TITLE
使用bullet检测N+1查询和未使用的预加载

### ISSUE THREAD

**Issue by JohnnyTing** [521xueweihan/HelloGitHub#777]
- 项目地址：https://github.com/flyerhzm/bullet

- 类别：Ruby

- 项目后续更新计划：暂无

- 项目描述：
  - 在rails项目中，关联查询是常见的，新手使用不当就会出现N+1查询的情况，拖慢查询速度，bullet是用来检测代码出现N+1查询的问题，也可以检测到未使用的预加载
  - 对系统性能有要求，提升查询速度

- 推荐理由：提升系统性能，配置简单，现成的例子

- 日志提示：
2009-08-25 20:40:17[INFO] N+1 Query: PATH_INFO: /posts;    model: Post => associations: [comments]·
Add to your finder: :include => [:comments]
2009-08-25 20:40:17[INFO] N+1 Query: method call stack:·
/Users/richard/Downloads/test/app/views/posts/index.html.erb:11:in `_run_erb_app47views47posts47index46html46erb'
/Users/richard/Downloads/test/app/views/posts/index.html.erb:8:in `each'
/Users/richard/Downloads/test/app/views/posts/index.html.erb:8:in `_run_erb_app47views47posts47index46html46erb'
/Users/richard/Downloads/test/app/controllers/posts_controller.rb:7:in `index'

**Comment by daixiang0** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
