### ISSUE TITLE
将汉字转换成拼音(支持多音字)

### ISSUE THREAD

**Issue by JohnnyTing** [521xueweihan/HelloGitHub#778]
- 项目地址：https://github.com/janx/ruby-pinyin

- 类别：Ruby

- 项目后续更新计划：暂无

- 项目描述：
  - 可以把汉字转化为对应的拼音，并能够较好的处理多音字的情况。

- 推荐理由：简单好用，直接照着实例代码就能写

- 示例代码：
    PinYin.of_string('节操') 
    return ['jie', 'cao']

    PinYin.of_string('节操', true)    
    return ['jie2', 'cao1']

    PinYin.of_string('节操', :unicode)   
    return ["jié", "cāo"]

    正确处理多音字:
    PinYin.of_string('南京市长江大桥', :unicode)
    return ["nán", "jīng", "shì", "cháng", "jiāng", "dà", "qiáo"]
    
    PinYin.abbr('感谢party感谢guo jia')  
    return 'gxpartygxguojia'

**Comment by daixiang0** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 42 期](https://hellogithub.com/periodical/volume/42/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
