### ISSUE TITLE
Teradata covalent,Material Design 二次封装的UI框架

### ISSUE THREAD

**Issue by sunjiaheng7825** [521xueweihan/HelloGitHub#779]
## 项目推荐
- 项目地址：https://github.com/Teradata/covalent

- 类别：JavaScript

- 项目后续更新计划：

- 项目描述：
  - Covalent is a reusable UI platform from Teradata for building web applications with common standards and tooling. It is based on Angular and Material Design。
  - 二次封装了step,input等组件
  - 追加了Code Editor,MarkDown等组件

- 推荐理由：追加了部分Material Design没有的组件
- 示例代码：
```
import { CovalentLayoutModule } from '@covalent/core/layout';
import { CovalentStepsModule  } from '@covalent/core/steps';
/* any other core modules */
// (optional) Additional Covalent Modules imports
import { CovalentHttpModule } from '@covalent/http';
import { CovalentHighlightModule } from '@covalent/highlight';
import { CovalentMarkdownModule } from '@covalent/markdown';
import { CovalentDynamicFormsModule } from '@covalent/dynamic-forms';
import { CovalentBaseEchartsModule } from '@covalent/echarts/base';
// other imports 
@NgModule({
  imports: [
    CovalentLayoutModule,
    CovalentStepsModule,
    // (optional) Additional Covalent Modules imports
    CovalentHttpModule.forRoot(),
    CovalentHighlightModule,
    CovalentMarkdownModule,
    CovalentDynamicFormsModule,
    CovalentBaseEchartsModule,
  ],
  ...
})
export class AppModule { }
```

- 截图：（可选）gif/png/jpg

## 提示
> 点击上方 “Preview” 更方便地阅读以下内容，

**意见和反馈 BUG 请移步，[反馈意见收集贴](https://github.com/521xueweihan/HelloGitHub/issues/673)。新建 issues 只接受项目推荐，如不是则会被 bot 关闭。**

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
