### ISSUE TITLE
Go ultimate study guide

### ISSUE THREAD

**Issue by Yanwenjiepy** [521xueweihan/HelloGitHub#781]
## 项目推荐
- 项目地址：https://github.com/hoanhan101/ultimate-go

- 类别：Go

- 项目后续更新计划：持续更新中

- 项目描述：
  - 必写：这是作者学习Go 过程中，对Go源码以及涉及到的相关的计算机基础知识的心得与总结。
  - 可选：适合Go学习者阅读与学习，和作者一起深入了解Go源码，了解背后的计算机理论和Go的设计思想。
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：这对任何具有一些其他编程语言经验并希望学习Go的中级开发人员来说都很重要。我们相信这些课程非常适合那些想要学习Go或者想要更全面地理解语言及其内部结构的人。
- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

## 提示
> 点击上方 “Preview” 更方便地阅读以下内容，

**意见和反馈 BUG 请移步，[反馈意见收集贴](https://github.com/521xueweihan/HelloGitHub/issues/673)。新建 issues 只接受项目推荐，如不是则会被 bot 关闭。**

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
@Yanwenjiepy 项目描述修改为：

该项目是作者在学习 Go 过程中，对 Go 源码以及涉及到的相关的计算机基础知识的心得与总结。适合 Go 学习者阅读与学习，和作者一起深入了解 Go 源码，了解背后的计算机理论和 Go 的设计思想

如果疑问欢迎留言反馈

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 42 期](https://hellogithub.com/periodical/volume/42/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
