### ISSUE TITLE
面向C语言的Linq

### ISSUE THREAD

**Issue by haifenghuang** [521xueweihan/HelloGitHub#782]
## 项目推荐
- 项目地址：https://github.com/haifenghuang/linq4c

- 类别：C

- 项目后续更新计划：
该项目已经能够运行大部分的Linq方法，现在还在不断完善中，希望能够有更多的参与者来共同维护。

- 项目描述：
  - 必写：使用C语言来实现大部分的Linq方法。
  - 描述长度:
一直羡慕C#的Linq， 于是做了一个C语言版的，实现了LInq的大部分方法(60+)，希望能够对自己和别人有所帮助。

- 推荐理由：实现了C# Linq的大部分的方法，同时支持链式操作。

- 示例代码：

```c
    bool WhereCallback(void *item) {
        char *str= (char *)item;
        return str[0] == 'h';
    }

    void *SelectCallback(void *item) {
        return newStr("%s_1", (char *)item);
    }

    char *str1 = "huang", *str2 = "hai", *str3 = "feng";

    ArrayList array = arrlist_new();
    arrlist_append(array, str1);
    arrlist_append(array, str2);
    arrlist_append(array, str3);

    Linq *lq = From(array);
    ArrayList result = 
        lq
        ->Where(lq, WhereCallback)
        ->Select(lq, SelectCallback)
        ->ToArray(lq);

    for(int i = 0; i < arrlist_size(result); i++) {
        printf("%s\n", arrlist_get(result, i));
    }
```

- 截图：https://github.com/haifenghuang/linq4c/blob/master/img/Linq4c_1.png

## 提示
> 点击上方 “Preview” 更方便地阅读以下内容，

**意见和反馈 BUG 请移步，[反馈意见收集贴](https://github.com/521xueweihan/HelloGitHub/issues/673)。新建 issues 只接受项目推荐，如不是则会被 bot 关闭。**

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！

**Comment by ChungZH** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by ChungZH** [comment]
- 项目地址：https://github.com/haifenghuang/linq4c
- 项目描述：如果你想在 C 中使用隔壁 C# 的 linq 方法，那么不妨来使用这个项目！这是它的 C 语言版。实现了 linq 的大部分方法（60+）。现在它还在不断完善中，希望能够有更多的参与者来共同维护。
- 推荐理由：实现了 C# linq 的大部分的方法，同时支持链式操作。
- 示例代码：
```cpp
   bool WhereCallback(void *item) {
        char *str= (char *)item;
        return str[0] == 'h';
    }

    void *SelectCallback(void *item) {
        return newStr("%s_1", (char *)item);
    }

    char *str1 = "huang", *str2 = "hai", *str3 = "feng";

    ArrayList array = arrlist_new();
    arrlist_append(array, str1);
    arrlist_append(array, str2);
    arrlist_append(array, str3);

    Linq *lq = From(array);
    ArrayList result = 
        lq
        ->Where(lq, WhereCallback)
        ->Select(lq, SelectCallback)
        ->ToArray(lq);

    for(int i = 0; i < arrlist_size(result); i++) {
        printf("%s\n", arrlist_get(result, i));
    }
```
- 截图：![](https://github.com/haifenghuang/linq4c/blob/master/img/Linq4c_1.png)

**Comment by ChungZH** [comment]
@haifenghuang  
**提示**：如果要插入图片，请用 `![](图片地址)` 的 Markdown 语法。而且你这里给出的这个 `https://github.com/haifenghuang/linq4c/blob/master/img/Linq4c_1.png` 图片链接是错误的，这实际上是一个网页。应为 `https://raw.githubusercontent.com/haifenghuang/linq4c/master/img/Linq4c_1.png`

**Comment by haifenghuang** [comment]
多谢提醒，已更改。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 42 期](https://hellogithub.com/periodical/volume/42/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了《讲解开源项目》系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
