### ISSUE TITLE
为 Rails 应用添加新功能介绍以及用户指引

### ISSUE THREAD

**Issue by jinhucheung** [521xueweihan/HelloGitHub#787]
## 项目推荐
- 项目地址：https://github.com/jinhucheung/intro

- 类别：Ruby

- 项目后续更新计划： 持续更新 [shepherd](https://github.com/shipshapecode/shepherd)

- 项目描述：
  - Intro 作为一个 Rails Engine， 为 Rails 应用添加了功能介绍以及用户指引功能
  - Intro 支持 Rails 3 以上的应用

- 推荐理由：Intro 通过一个后台，统一处理了功能介绍及用户指引的需要，更方便为 Rails 应用添加相关指引，并在生产环境中通过实践

- 示例代码：[intro-demo](https://github.com/jinhucheung/intro-demo)

- 示例应用：https://intro-demo.herokuapp.com/

- 截图：![](https://user-images.githubusercontent.com/19590194/64253419-dbe38d80-cf4f-11e9-9aab-b1e6058990ab.png)

## 提示
> 点击上方 “Preview” 更方便地阅读以下内容，

**意见和反馈 BUG 请移步，[反馈意见收集贴](https://github.com/521xueweihan/HelloGitHub/issues/673)。新建 issues 只接受项目推荐，如不是则会被 bot 关闭。**

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！

**Comment by daixiang0** [comment]
此项目需要一定的Rails基础，不符合HG标准，故close。

非常感谢您推荐项目。

该项目暂不能收录到 HelloGitHub 月刊中，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 pray

**Comment by jinhucheung** [comment]
@daixiang0 感谢审查，thanks
