### ISSUE TITLE
自然语言处理HanLP

### ISSUE THREAD

**Issue by hellowHuaairen** [521xueweihan/HelloGitHub#790]
## 项目推荐
- 项目地址：https://github.com/hankcs/HanLP

- 类别：Java

- 项目描述：
HanLP是一系列模型与算法组成的NLP工具包，由大快搜索主导并完全开源，目标是普及自然语言处理在生产环境中的应用。HanLP具备功能完善、性能高效、架构清晰、语料时新、可自定义的特点。

- 推荐理由：HanLP功能特别丰富。包括中文分词，词性标注，命名实体识别，关键词提取，自动摘要，短语提取，拼音转换，简繁转换，文本推荐，依存句法分析，文本分类，文本聚类，word2vec，语料库工具。

- 示例代码：
日本人名识别
```java
String[] testCase = new String[]{
        "北川景子参演了林诣彬导演的《速度与激情3》",
        "林志玲亮相网友:确定不是波多野结衣？",
};
Segment segment = HanLP.newSegment().enableJapaneseNameRecognize(true);
for (String sentence : testCase)
{
    List<Term> termList = segment.seg(sentence);
    System.out.println(termList);
}
```
网站地址：http://hanlp.com/
分词效果：
![](https://ae01.alicdn.com/kf/H68076c2e56d64a869dcf56c6db44a35aa.png)

**Comment by 521xueweihan** [comment]
https://hellogithub.com/periodical/search/?q=https://github.com/hankcs/HanLP

该项目已推荐过，但是当时文案写的不好。采用了最新的文案
