### ISSUE TITLE
一键部署高可用 Elasticsearch 集群的工具

### ISSUE THREAD

**Issue by bluecll** [521xueweihan/HelloGitHub#791]
## 项目推荐
- 项目地址：https://github.com/bluecll/es-easy-setup

- 类别：Python

- 项目后续更新计划：会加入新版 es 部署的支持、安全模块支持以及 elk 全套部署功能

- 项目描述：

es-easy-setup 是一套简化 es 集群部署的工具，支持多种模式部署（测试集群模式、线上集群模式、多机房模式等），可快速部署生产级别可用的集群。
 
一个命令就可以完成全部部署工作，并支持多套集群混合部署，提高机器利用率。

项目采用 ansible 开发，不需要在服务器上预先安装客户端，只需要有 ssh 连接权限即可。

已在大厂经过长时期验证。欢迎大家使用。

- 推荐理由：es-easy-setup 基于 Ansible 开发，支持快速部署生产环境可用 es 集群。

- 示例代码：`ansible-playbook -i example.cfg setup.yml -v`

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
