### ISSUE TITLE
Python数据可视化框架Bokeh

### ISSUE THREAD

**Issue by hellowHuaairen** [521xueweihan/HelloGitHub#792]
## 项目推荐
- 项目地址：https://github.com/bokeh/bokeh

- 类别：Python

- 项目描述：Bokeh是一个用于Python的交互式可视化库，可在现代Web浏览器中实现美观且有意义的数据可视化呈现。使用Bokeh，您可以快速轻松地创建交互式图表，仪表板和数据应用程序。

- 推荐理由：大型或流式数据集提供高性能交互。

- 截图：
![](https://ae01.alicdn.com/kf/H54b08e37da234d93a06c5b230cb46781v.png)

**Comment by 521xueweihan** [comment]
项目描述修改为：

一个交互式的数据可视化 Python 库，专注于在 Web 浏览器中实现美观、直接的数据可视化功能。使用它可以让你快速和轻松地创建交互式图表、仪表板和数据可视化程序。流式数据集的可视化效果如下图：
![](https://bokeh.org/img/streaming.gif)
