### ISSUE TITLE
cherry - 无需机器学习背景的文本分类器

### ISSUE THREAD

**Issue by Windsooon** [521xueweihan/HelloGitHub#793]
## 自荐项目
- 项目地址：https://github.com/Windsooon/cherry/

- 类别：Python, 机器学习

- 项目后续更新计划：持续更新，希望用户反馈要求。

- 项目描述：
  - 必写：简单易用的文本分类器
  - 可选：适用多种语言，包含两个预训练模型，无需机器学习知识，定制简单
  - 描述长度: cherry 自带两个预训练模型，使用预训练模型进行分类只需一行代码。使用自己的数据集进行定制训练也只需要十行代码。轻松达到高精确率，召回率。同时 cherry 支持自定义分词算法，分类算法以及 stop words 词库。

- 推荐理由：简单易用，适合没有机器学习背景的用户快速入门

- 示例代码：使用预训练模型进行文本分类：

        >>> res = cherry.classify(model='harmful', text=['她们对计算机很有热情，也希望学习到数据分析，网络爬虫，人工智能等方面的知识，从而运用在她们工作上'])
        >>> res.word_list
        [(2, '她们'), (1, '网络'), (1, '热情'), (1, '方面'), (1, '数据分析'), (1, '希望'), (1, '工作'), (1, '学习'), (1, '从而')]
        >>> res.probability
        # 返回结果分别对应 赌博，正常，政治，色情 4个 类别的概率
        array([[4.43336608e-03, 9.95215198e-01, 3.51419231e-04, 1.68657851e-08]])

- 截图：（可选）gif/png/jpg

         https://news.ycombinator.com/item?id=20914738

## 提示
> 点击上方 “Preview” 更方便地阅读以下内容，

**意见和反馈 BUG 请移步，[反馈意见收集贴](https://github.com/521xueweihan/HelloGitHub/issues/673)。新建 issues 只接受项目推荐，如不是则会被 bot 关闭。**

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 42 期](https://hellogithub.com/periodical/volume/42/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了《讲解开源项目》系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
