### ISSUE TITLE
BaseShell

### ISSUE THREAD

**Issue by chen-shang** [521xueweihan/HelloGitHub#796]
## 项目推荐
- 项目地址：https://github.com/chen-shang/BaseShell

- 类别：其它

- 项目后续更新计划：

- 项目描述： BaseShell类似于Java语言的SDK是为Shell脚本语言提供的一套工具库,涵盖多种类Java工具的实现
>1. 并发工具【Concurrent】
>2. 锁【Concurrent】
>3. Object工具【Lang】
>4. 数学工具【Lang】
>5. 常量【Constant】
>6. 字符串工具【Lang】
>7. SSH【Ssh】
>8. Starter包【Starter】
>9. 工具包【Utils】
>10. 单元测试【Utils】
>11. 日期工具【localdate、localdatetime、localtime、timeunit、week】
>12. 日志工具【log】
......

等等,目前还在完善当中。旨在简化shell脚本的编写、提高shell脚本的健壮性。丰富的类库可以大大减少shell脚本编写的难度，其类Java的实现方式可以使得面向对象范式的程序员很快的理解并使用。与之相配套的我会出一篇《Shell编程规约》,以期规范Shell脚本程序员的书写习惯。

- 推荐理由：旨在简化shell脚本的编写、提高shell脚本的健壮性。丰富的类库可以大大减少shell脚本编写的难度，其类Java的实现方式可以使得面向对象范式的程序员很快的理解并使用

- 示例代码：（可选）长度：1-20 行

- 截图:

![](https://github.com/chen-shang/Picture/blob/master/init.gif)

## 提示
> 点击上方 “Preview” 更方便地阅读以下内容，

**意见和反馈 BUG 请移步，[反馈意见收集贴](https://github.com/521xueweihan/HelloGitHub/issues/673)。新建 issues 只接受项目推荐，如不是则会被 bot 关闭。**

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
感谢您的推荐，欢迎提高项目的完成度后，重新提交推荐。
