### ISSUE TITLE
[推荐]Go语言实现的类cURL工具-Bat

### ISSUE THREAD

**Issue by TomShine** [521xueweihan/HelloGitHub#8]
+ Github地址: <https://github.com/astaxie/bat>

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

如您推荐的项目在《HelloGithub》月刊中推荐，则会同时写明推荐人。

再次感谢您对《HelloGithub》项目的支持！

**Comment by 521xueweihan** [comment]
不好意思，请重新[创建 issues](https://github.com/521xueweihan/HelloGitHub/issues/new)，根据推荐项目的模版，规范推荐项目格式、完善信息。
