### ISSUE TITLE
PowerToys

### ISSUE THREAD

**Issue by ChungZH** [521xueweihan/HelloGitHub#800]
## 项目推荐
- 项目地址：https://github.com/microsoft/PowerToys

- 类别：C++

- 项目后续更新计划：

- 项目描述：PowerToys 是一套效率工具，帮助高级用户高级用户调整和简化 Windows 体验，以提高工作效率。此项目在 Windows 95 时代已经开始，可是后来被终止了。目前，PowerToys 只有 FancyZones 和 Windows key shortcut guide 这两个功能。

- 推荐理由：高效、有前途。

- 示例代码：（可选）长度：1-20 行

- 截图：![](https://github.com/microsoft/PowerToys/raw/master/doc/images/Logo.jpg)

**Comment by 521xueweihan** [comment]
@ChungZH 需要在描述中解释：FancyZones 和 Windows key shortcut guide
