### ISSUE TITLE
【自荐项目】XUpdate 一个全套的Android原生全量版本更新解决方案

### ISSUE THREAD

**Issue by xuexiangjys** [521xueweihan/HelloGitHub#802]
## 项目推荐
- 项目地址：https://github.com/xuexiangjys/XUpdate

- 类别：java

- 项目后续更新计划：

不断完善项目本身

- 项目描述：

XUpdate是一套基于Android的全量版本更新整体解决方案。他除了提供了Android SDK外，还附带了Spring Boot搭建的后台服务以及Vue.js编写的后台管理界面。主要解决中小企业Android版本管理混乱的问题,提供可定制化的解决方案.

## 特点

* 使用简单，只需一行代码即可完成版本更新功能。
* 功能强大，兼容Android6.0、7.0、8.0和9.0，支持静默更新和自动更新，支持国际化。
* 扩展性强，可自定义请求API接口、提示弹窗、下载服务、文件加密方式等。
* 搭建简单，只需提供json内容即可支持版本更新。
* 配套齐全，默认提供了后台服务和管理界面。

## 推荐理由

不同于其他Android全量版本更新对API和行为有严格的约束,该框架提供了完全可插拔的版本更新,同时为了让使用者使用方便,还同时提供了后台服务和管理界面,使用的都是现下最流行的技术,完全做到灵活、方便和高可用性.同时,也提供了大量丰富的[文档](https://github.com/xuexiangjys/XUpdate/wiki)供大家参阅.

## 示例代码:

* 默认版本更新
```
XUpdate.newBuild(getActivity())
        .updateUrl(mUpdateUrl)
        .update();
```
* 自动版本更新
```
XUpdate.newBuild(getActivity())
        .updateUrl(mUpdateUrl)
        .isAutoMode(true) //如果需要完全无人干预，自动更新，需要root权限【静默安装需要】
        .update();
```
* 自定义版本更新解析器
```
XUpdate.newBuild(getActivity())
        .updateUrl(mUpdateUrl3)
        .updateParser(new CustomUpdateParser()) //设置自定义的版本更新解析器
        .update();
```

### Android版本更新界面
![在这里插入图片描述](https://img-blog.csdnimg.cn/20190427221252848.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly94dWV4aWFuZ2p5cy5ibG9nLmNzZG4ubmV0,size_16,color_FFFFFF,t_70)               ![在这里插入图片描述](https://img-blog.csdnimg.cn/2019042722130818.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly94dWV4aWFuZ2p5cy5ibG9nLmNzZG4ubmV0,size_16,color_FFFFFF,t_70)
### 后台管理界面
![在这里插入图片描述](https://img-blog.csdnimg.cn/20190427221406435.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly94dWV4aWFuZ2p5cy5ibG9nLmNzZG4ubmV0,size_16,color_FFFFFF,t_70)
![在这里插入图片描述](https://img-blog.csdnimg.cn/20190427221446926.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly94dWV4aWFuZ2p5cy5ibG9nLmNzZG4ubmV0,size_16,color_FFFFFF,t_70)
![在这里插入图片描述](https://img-blog.csdnimg.cn/20190427221421466.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly94dWV4aWFuZ2p5cy5ibG9nLmNzZG4ubmV0,size_16,color_FFFFFF,t_70)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 42 期](https://hellogithub.com/periodical/volume/42/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了《讲解开源项目》系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
