### ISSUE TITLE
Python基础课程

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#803]
## 项目推荐
- 项目地址： https://github.com/microsoft/c9-python-getting-started

- 类别：其它

- 项目描述：
按章节教学，包含以下内容：

- Python基础
- Python项目基础
- 简单语法
- Python包管理

- 推荐理由：

内容浅显易懂，适合入门。
微软出品，质量保证，并提供了视频资料。

**Comment by 521xueweihan** [comment]
项目描述修改为：

微软出品的零基础 Python 入门教程，内容浅显易懂。项目内包含示例代码、演示的 PPT。[Youtube 视频地址](https://www.youtube.com/playlist?list=PLlrxD0HtieHhS8VzuMCfQD4uJ9yne1mE6)

如有疑问欢迎留言回复
