### ISSUE TITLE
【自荐项目】taro-music - 基于taro + taro-ui + redux + typescript 开发的网易云音乐小程序

### ISSUE THREAD

**Issue by lsqy** [521xueweihan/HelloGitHub#804]
## 项目推荐

- 项目地址：https://github.com/lsqy/taro-music

- 类别：JS

- 项目后续更新计划：持续进行功能完善迭代，计划支持H5以及其他端的适配

- 项目描述：
 基于Taro与网易云音乐api开发，技术栈主要是：`typescript+taro+taro-ui+redux`,目前主要是着重小程序端的展示，可以借此项目强化下上述几个技术栈的使用，通过这个项目也可以帮助你进行参考，快速使用Taro开发一个属于你自己的小程序，目前已实现的主要功能点如下：
- [x] 用户登陆
- [x] 退出登陆
- [x] 我的关注列表
- [x] 我的粉丝列表
- [x] 最近播放列表
- [x] 推荐歌单
- [x] 我创建的歌单列表
- [x] 我收藏的歌单列表
- [x] 共用的歌单详情列表
- [x] 歌曲播放页面
- [x] 歌词滚动
- [x] 歌曲切换播放模式（随机播放/单曲循环/顺序播放）
- [x] 切换上一首/下一首
- [x] 喜欢/取消喜欢某首歌曲
- [x] 评论列表
- [x] 视频播放
- [x] 热搜列表
- [x] 搜索（包含单曲/歌单/视频/歌手/专辑/电台/用户）
- [x] 统一的播放组件，方便进行切换页面后可以随时进入到播放页面
- [x] 搜索功能
- [x] 视频播放
- [x] mv播放
- [x] 视频与mv中的评论列表

## 推荐理由：

使用的框架Taro 立足于微信小程序开发，众所周知小程序的开发体验并不是非常友好，比如小程序中无法使用 npm 来进行第三方库的管理，无法使用一些比较新的 ES 规范等等，针对小程序端的开发弊端，本项目集成了redux进行状态管理，项目目录合理的组织方式，以及选用typescript进行实现，可以让你能够快速将上述的这些技术点以及规范进行综合运用起来。

## 示例代码：

```
启动后端接口服务

git clone https://github.com/Binaryify/NeteaseCloudMusicApi.git

cd NeteaseCloudMusicApi

npm i

npm run start

接下来启动前端项目

git clone https://github.com/lsqy/taro-music.git

cd taro-music

npm i

npm run dev:weapp

```

## 截图：

![](https://oscimg.oschina.net/oscnet/498fdfc98cc89d72196dded4f54afa29ed4.jpg)

![](https://oscimg.oschina.net/oscnet/f52f4448ce3475f5ecd002958ae1413a3dd.jpg)

![](https://oscimg.oschina.net/oscnet/446008d8690a962a105f839c46d7638b89b.jpg)

![](https://oscimg.oschina.net/oscnet/38e5dcac4baaca87195e95a115132cb7958.jpg)

**Comment by 521xueweihan** [comment]
@lsqy 项目描述修改为：
基于 Taro 与网易云音乐 API 开发的网易云音乐小程序。技术栈为 typescript+taro+taro-ui+redux 目前主要是着重小程序端的展示，可以通过项目学习上述几个技术栈的使用和实战，从而能够快速使用 Taro 开发一个属于你自己的小程序，目前已实现的主要功能点如下：
- 用户登陆
- 我的关注列表
- 最近播放列表
- 歌曲播放页面
- 等等

如有问题，欢迎留言反馈。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 42 期](https://hellogithub.com/periodical/volume/42/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了《讲解开源项目》系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
