### ISSUE TITLE
自荐项目 - 一份在线 Node.js 技术栈学习指南

### ISSUE THREAD

**Issue by Q-Angelo** [521xueweihan/HelloGitHub#807]
## 项目推荐
- 项目地址：https://github.com/Q-Angelo/Nodejs-Roadmap

- 类别：Node.js、JS、书籍

- 项目后续更新计划：会持续更新

- 项目描述：致力于为大家分享最具有价值的 Node.js 相关技术干货，包含 Node.js 基础知识（JavaScript、ES6/ES7/ES8...、TypeScript）、Node.js 核心模块、主流框架实践、缓存、数据库、消息中间件、DevOps、HTTP 协议以及 Node.js 在微服务、分布式领域下的应用分享等

- 截图：

![image](https://user-images.githubusercontent.com/17956058/65474588-fa81d800-deae-11e9-81ba-0b7f1d5da619.png)

**Comment by 521xueweihan** [comment]
不好意思，推荐项目的地址一定要是 github 项目地址。我已经修改了，为您带来的不便，下次要注意😯

**Comment by Q-Angelo** [comment]
@521xueweihan 好的 也可以的 谢谢！

**Comment by 521xueweihan** [comment]
项目分类修改到“教程”，描述修改为：
Node.js 技术栈学习指南。内容侧重于 Node.js 服务端，包含：Node.js 基础知识、Node.js 核心模块、主流框架实践、缓存、数据库、消息中间件、DevOps、HTTP 协议以及 Node.js 在微服务等，[在线阅读](https://www.nodejs.red/)

如果有疑问欢迎留言反馈

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 42 期](https://hellogithub.com/periodical/volume/42/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
