### ISSUE TITLE
navi

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#808]
## 项目推荐
- 项目地址： https://github.com/denisidoro/navi.git

- 类别：其它

- 项目后续更新计划：

- 项目描述：

用于命令行的交互式备忘单工具
- 推荐理由：

终端的历史有限，经常会有找不到历史忘记命令的尴尬时刻。有了navi，再也不用担心命令历史没有了。

- 运行效果：

![Demo](https://user-images.githubusercontent.com/3226564/65389667-0181dc80-dd2f-11e9-9fac-c875ed7c7b53.gif)

**Comment by daixiang0** [comment]
准确的分类是shell，但目前没有。

**Comment by 521xueweihan** [comment]
@daixiang0 是的，shell 只能是就分类到其它吧。
