### ISSUE TITLE
小乐数学zzllrr Mather，一款集自学教学、科研科普功能的数学轻量级利器（可离线运行的网页APP）

### ISSUE THREAD

**Issue by zzllrr** [521xueweihan/HelloGitHub#809]
## 项目推荐
- 项目地址：
https://github.com/zzllrr/mather
- 在线演示地址：
https://zzllrr.github.io/mather
- 类别：JS

- 项目后续更新计划：
扩充数学知识库、函数库、工具库、课件库等。
长期愿景是推动更多的数学、科学、教育、技术、工程、人文、互联网、物联网工作者，加入全球开源工具项目：Mather（暂译为数学客），更专业化地普及、研究、发展数学。

- 项目描述：
  - 必写：小乐数学zzllrr Mather，是小乐原创开源实现的一款跨平台可离线运行并满足多用户背景、多场景需要的数学软件Web APP，让数学更易学易练，易教易研，易赏易玩，易见易得，易传易及。
  - 可选：适用于数学自学、教学、研究、科普等场景、能够让初学者轻松解题（提供解题步骤）并能探索结构化体系的数学内容。

  - 描述长度（不包含示例代码）: 项目背景，详见 https://raw.githubusercontent.com/zzllrr/mather/master/RESEARCH.md

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？
目前已实现数学公式编辑器，初等代数、线性代数、离散数学等学科的典型题目的离线解题，PPT演示，作图工具，语音合成播放（使用的第三方API，需联网），AR，VR工具箱等。

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

**Comment by 521xueweihan** [comment]
@zzllrr   您好，该项目暂不能收录到月刊中。推荐标准请参考 #271

希望您能够继续推荐有意思、入门级项目，再次感谢。
