### ISSUE TITLE
自荐项目：多画面播放器

### ISSUE THREAD

**Issue by ithewei** [521xueweihan/HelloGitHub#810]
## 项目推荐
- 项目地址：https://github.com/ithewei/hplayer.git

- 类别：C++

- 项目后续更新计划：
添加人脸检测与识别功能；
添加美颜功能；
添加图片与文字叠加功能；
添加多画面合成功能；
添加推流功能；
添加桌面录制功能；

- 项目描述：
一个类似VLC的播放器，能播放本地媒体文件、捕获设备、网络流；

- 推荐理由：
多画面监控网格界面，可自由切换多画面风格;
使用Qt实现界面；
使用FFmpeg获取帧，编解码，转码；
使用OpenCV处理图片；
使用OpenGL渲染视频帧；

- 项目博客
https://hewei.blog.csdn.net/article/category/9275796

- 截图
[https://github.com/ithewei/hplayer/blob/master/hplayer_test.png](url)

**Comment by ChungZH** [comment]
@ithewei  您好，该项目暂不能收录到月刊中。推荐标准请参考 #271

希望您能够继续推荐有意思、入门级项目，再次感谢。
