### ISSUE TITLE
mall-learning

### ISSUE THREAD

**Issue by hellowHuaairen** [521xueweihan/HelloGitHub#813]
## 项目推荐
- 项目地址：https://github.com/macrozheng/mall-learning

- 类别：Java

- 项目描述：
mall学习教程，架构、业务、技术要点全方位解析。mall项目（20k+star）是一套电商系统，使用现阶段主流技术实现。 涵盖了SpringBoot2.1.3、MyBatis3.4.6、Elasticsearch6.2.2、RabbitMQ3.7.15、Redis3.2、Mongodb3.2、Mysql5.7等技术，采用Docker容器化部署

- 推荐理由：开源前后端分离的项目，是个很好的学习教程。

- 截图：

![image](https://user-images.githubusercontent.com/19610305/65660584-b7b43180-e061-11e9-8eae-d1d010153c55.png)

**Comment by 521xueweihan** [comment]
已推荐过：https://hellogithub.com/periodical/volume/40/#mall
