### ISSUE TITLE
[magic_get]非侵入式为Struct提供编译期反射能力

### ISSUE THREAD

**Issue by westfly** [521xueweihan/HelloGitHub#815]
## 项目推荐
- 项目地址：https://github.com/apolukhin/magic_get 

- 类别： C++

- 项目后续更新计划：
   进入C++标准库
- 项目描述：
  - 基于C++14 的新特性，为用户自定义的struct 类型（POD）提供与std::tuple接口类似的函数操作，具有无侵入代码、编译期反射等特点。（ This C++14 library is meant for accessing structure elements by index and providing other std::tuple like methods for user defined types without any macro or boilerplate code）

- 推荐理由：使用模版元技巧实现对POD类型的编译期反射

- 示例代码：
```cpp
// requires: C++14
#include <iostream>
#include <string>
#include "boost/pfr/precise.hpp"

struct some_person {
    std::string name;
    unsigned birth_year;
};

int main() {
    some_person val{"Edgar Allan Poe", 1809};

    std::cout << boost::pfr::get<0>(val)                // No macro!
        << " was born in " << boost::pfr::get<1>(val);  // Works with any aggregate initializables!
}
```

**Comment by 521xueweihan** [comment]
此类语法特性的项目，月刊中暂不收录
