### ISSUE TITLE
[dbg-macro]提供更友好的debug宏

### ISSUE THREAD

**Issue by westfly** [521xueweihan/HelloGitHub#817]
## 项目推荐
- 项目地址：https://github.com/sharkdp/dbg-macro

- 类别： C++

- 项目后续更新计划：
   暂未知
- 项目描述：
   打日志是C++开发中必不可少的一种debug方式，[dbg-macro](https://github.com/sharkdp/dbg-macro) 受 [rust-lang](https://www.rust-lang.org) 中 的[dbg](https://doc.rust-lang.org/std/macro.dbg.html) 启发，提供较 printf& std::cout 更好宏函数dbg(...)，主要有如下特点
   - 兼容C++11 并且是 header-only
   - 支持基础类型和STL容器类型的输出
   - 除了基本信息外，还输出变量名和类型，human-friendly
   - 启用 DBG_MACRO_DISABLE 生成 release版 

- 推荐理由：小功能有大作用

- 示例代码：
```cpp
#include <vector>
#include <dbg.h>

// You can use "dbg(..)" in expressions:
int factorial(int n) {
  if (dbg(n <= 1)) {
    return dbg(1);
  } else {
    return dbg(n * factorial(n - 1));
  }
}

int main() {
  std::string message = "hello";
  dbg(message);  // [example.cpp:15 (main)] message = "hello" (std::string)
  const int a = 2;
  const int b = dbg(3 * a) + 1;  // [example.cpp:18 (main)] 3 * a = 6 (int)
  std::vector<int> numbers{b, 13, 42};
  dbg(numbers);  // [example.cpp:21 (main)] numbers = {7, 13, 42} (size: 3) (std::vector<int>)
  dbg("this line is executed");  // [example.cpp:23 (main)] this line is executed
  factorial(4);
  return 0;
}
```
- 截图： ![官方输出](https://user-images.githubusercontent.com/1453169/65680681-0a094880-e08a-11e9-84d9-08ef1ca35337.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
感谢，此类项目正式我们需要的 👍

**Comment by ChungZH** [comment]
## 项目推荐
- 项目地址：https://github.com/sharkdp/dbg-macro

- 类别： C++

- 项目后续更新计划：
   
- 项目描述：
   打日志是 C++ 开发中必不可少的一种 debug 方式，[dbg-macro](https://github.com/sharkdp/dbg-macro) 受 [rust-lang](https://www.rust-lang.org) 中 的 [dbg](https://doc.rust-lang.org/std/macro.dbg.html) 启发，提供比 printf 和 std::cout 更好的宏函数 dbg(...)，主要有如下特点
   - 美观的彩色输出（当输出不是交互式终端时，颜色将自动禁用） 
   - 兼容 C++11，并且是 header-only
   - 支持基础类型和 STL 容器类型的输出
   - 除了基本信息外，还输出变量名和类型，human-friendly
   - 启用 DBG_MACRO_DISABLE 生成 release 版 

- 推荐理由：小功能有大作用

- 示例代码：
```cpp
#include <vector>
#include <dbg.h>

// You can use "dbg(..)" in expressions:
int factorial(int n) {
  if (dbg(n <= 1)) {
    return dbg(1);
  } else {
    return dbg(n * factorial(n - 1));
  }
}

int main() {
  std::string message = "hello";
  dbg(message);  // [example.cpp:15 (main)] message = "hello" (std::string)
  const int a = 2;
  const int b = dbg(3 * a) + 1;  // [example.cpp:18 (main)] 3 * a = 6 (int)
  std::vector<int> numbers{b, 13, 42};
  dbg(numbers);  // [example.cpp:21 (main)] numbers = {7, 13, 42} (size: 3) (std::vector<int>)
  dbg("this line is executed");  // [example.cpp:23 (main)] this line is executed
  factorial(4);
  return 0;
}
```
- 截图： ![官方输出](https://user-images.githubusercontent.com/1453169/65680681-0a094880-e08a-11e9-84d9-08ef1ca35337.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 43 期](https://hellogithub.com/periodical/volume/43/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
