### ISSUE TITLE
项目自荐 - goribot- 一个基于闭包函数的Scrapy风格的Go爬虫框架（请多多指教

### ISSUE THREAD

**Issue by zhshch2002** [521xueweihan/HelloGitHub#818]
## 项目推荐
- 项目地址：[https://github.com/zhshch2002/goribot](https://github.com/zhshch2002/goribot)

- 类别：Go

- 项目后续更新计划：emm，刚刚起步，边学边完善吧。

- 项目描述：
  - 一个基于闭包函数的Scrapy风格的Go爬虫框架。
  - 类似Scrapy的request->hander的处理逻辑。
  - 用闭包函数表达处理逻辑，不像Scrapy那么冗长。

- 推荐理由：在Go的高并发下，优雅的描述爬虫逻辑

- 示例代码：
```Go
package main

import (
    "encoding/json"
    "fmt"
    "github.com/zhshch2002/goribot"
)

func main() {
    s := goribot.NewSpider()
    _ = s.Get(nil, "https://httpbin.org/get?Goribot%20test=hello%20world", func(r *goribot.Response) {
        m := make(map[string]interface{})
        err := json.Unmarshal([]byte(r.Text), &m)
        if err != nil {
            fmt.Println(err)
        }
        fmt.Println(m)
    })
    s.Run()
}
```

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
