### ISSUE TITLE
Bulma

### ISSUE THREAD

**Issue by JameJJ** [521xueweihan/HelloGitHub#82]
## 项目推荐
- 项目名称：Bulma(CSS项目)

- 项目地址：https://github.com/jgthms/bulma

- 项目语言：CSS

- 项目描述：样式UI框架

- 推荐理由：样式比Bootstrap更加扁平化，源码文件结构清晰，通过源码可以学到UI框架架构。项目提供的只是样式，可以和Vue或者React进行结合，形成组件。

- 示例代码：
> 以下是组件/菜单栏的源代码
```css
$menu-size: $size-normal !default

$menu-item: $text !default
$menu-item-radius: $radius-small !default
$menu-item-hover: $text-strong !default
$menu-item-hover-background: $background !default
$menu-item-active: $link-invert !default
$menu-item-active-background: $link !default

$menu-list-border: $border !default

$menu-label: $text-light !default

.menu
  font-size: $menu-size

.menu-list
  line-height: 1.25
  a
    border-radius: $menu-item-radius
    color: $menu-item
    display: block
    padding: 0.5em 0.75em
    &:hover
      background-color: $menu-item-hover-background
      color: $menu-item-hover
    // Modifiers
    &.is-active
      background-color: $menu-item-active-background
      color: $menu-item-active
  li
    ul
      border-left: 1px solid $menu-list-border
      margin: 0.75em
      padding-left: 0.75em

.menu-label
  color: $menu-label
  font-size: 0.8em
  letter-spacing: 0.1em
  text-transform: uppercase
  &:not(:first-child)
    margin-top: 1em
  &:not(:last-child)
    margin-bottom: 1em
Contact GitHub API Training Shop Blog About
```

- 截图：
> 官网地址 http://bulma.io/

官网首页
![image](https://user-images.githubusercontent.com/12341577/28678142-2b40ff34-7322-11e7-89e0-fbef92cd1f79.png)

卡片组件
![image](https://user-images.githubusercontent.com/12341577/28678443-03acc9ca-7323-11e7-8736-12e80430dc6a.png)

**Comment by 521xueweihan** [comment]
@JameJJ 必须手动赞一下！

**Comment by JameJJ** [comment]
@521xueweihan 😂哈哈哈

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功收录**在 [HelloGitHub 第 17 期](https://github.com/521xueweihan/HelloGitHub/blob/master/content/17/HelloGitHub17.md)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，如果方便可以 Star ⭐️ 本项目，让更多人看到本项目。
