### ISSUE TITLE
【自荐项目】Just proxy 一个好用的 chrome 代理插件

### ISSUE THREAD

**Issue by 0jinxing** [521xueweihan/HelloGitHub#820]
## 项目推荐
- 项目地址：<https://github.com/0jinxing/just-proxy>

- 类别：JS

- 项目后续更新计划：不断完善项目本身

- 项目描述：
  - 便捷快速的切换 chrome 代理设置，解决 shadowsocks 自定义 user-rule 不便的痛点。
  - 采用 react，项目代码结构清晰，适合初学者学习 react、webpack、ts 的入门项目。

- 推荐理由：随心所欲的设置 chrome 代理。[已上架](https://chrome.google.com/webstore/detail/just-proxy/ooinoebmmhbmhkocojcoahbkefikddch)

- 截图：
  ![](https://raw.githubusercontent.com/0jinxing/just-proxy/master/docs/demo.gif)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
