### ISSUE TITLE
反向面试

### ISSUE THREAD

**Issue by QingZ11** [521xueweihan/HelloGitHub#821]
## 项目推荐
- 项目地址：https://github.com/yifeikong/reverse-interview-zh

- 类别：其他

- 项目后续更新计划：

- 项目描述：
  - 必写：这个是一个反向提问的项目，面试是应聘者和招聘方的双向面试，当面试官问你：你有什么想问我的？不用担心会脑子一片空白懵逼走出面试场。
  - 可选：适用于面试场景
  - 描述长度（不包含示例代码）: 列表里的问题对于参加技术面试的人来说可能有些用。列表里的问题并不一定适用于某个特定的职位或者工作类型，也没有排序。最开始的时候这只是项目维护者自己的问题列表，但是慢慢地他添加了一些觉得可能让他对这家公司亮红牌的问题。 当然作为一个面试官，项目维护者我也注意到被他面试的人提问他的问题太少了，感觉他们挺浪费机会的。

- 推荐理由：再也不用担心反问不出来有亮点的问题

![image](https://user-images.githubusercontent.com/38887077/65817626-4381b580-e23c-11e9-9f11-82b291c6c3d8.png)

![image](https://user-images.githubusercontent.com/38887077/65817627-4aa8c380-e23c-11e9-8eb8-51488d78342b.png)

![image](https://user-images.githubusercontent.com/38887077/65817633-56948580-e23c-11e9-802c-8a490da4f5f0.png)

![image](https://user-images.githubusercontent.com/38887077/65817635-5e542a00-e23c-11e9-821b-a533f0bb4fb3.png)

**Comment by 521xueweihan** [comment]
@QingZ11 您好，该项目已推荐过：https://hellogithub.com/periodical/volume/42/#reverse-interview
