### ISSUE TITLE
[fiora]一个有趣的Web聊天室, 界面友好, 功能丰富

### ISSUE THREAD

**Issue by yinxin630** [521xueweihan/HelloGitHub#822]
## 项目推荐
- 项目地址：https://github.com/yinxin630/fiora

- 类别：JavaScript, TypeScript

- 项目后续更新计划：[查看 issue 列表](https://github.com/yinxin630/fiora/issues)

- 项目描述：
  - 这是一个在线聊天室, 支持PC端、H5端、APP端(部分功能)
  - 功能丰富, [查看功能列表](https://github.com/yinxin630/fiora/blob/master/doc/README.ZH.md#%E5%8A%9F%E8%83%BD)
  - 最新基于 TypeScript + React 16.9 做了重构, 代码逻辑清晰, 注释较为完善, 适合用来学习 node.js / TypeScript / React + Hooks

- 推荐理由：
  - 界面小清新, 并且支持自定义
  - 消息朗读很好玩
  - 高可用性

- 截图：
![image](https://user-images.githubusercontent.com/6939365/65843675-7ecbd380-e365-11e9-87ee-e7acf30806bd.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 43 期](https://hellogithub.com/periodical/volume/43/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
