### ISSUE TITLE
[Charset Normalizer] 维护有关编码和语言检测的库。 🔎像Chardet | Solve declareless encoding madness.

### ISSUE THREAD

**Issue by Ousret** [521xueweihan/HelloGitHub#825]
## 项目推荐
- 项目地址：[Charset Normalizer](https://github.com/ousret/charset_normalizer)

- 类别：请从中选择（Python :tada: ）

- 项目后续更新计划：[查看 issue 列表](https://github.com/Ousret/charset_normalizer/issues)

- 项目描述：

维护有关编码和语言检测的库。 🔎像Chardet

帮助您从未知字符集编码中读取文本的库。
由chardet推动的项目，我正在尝试通过另一种方法来解决该问题。

没有更多的编码问题。 猜测任何内容的编码。

```python
from charset_normalizer import detect

my_byte_str = '我没有埋怨，磋砣的只是一些时间。'.encode('gb18030')
print(detect(my_byte_str))
```

![CLI](https://repository-images.githubusercontent.com/200259335/d3da9600-dedc-11e9-83e8-081f597505df)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
