### ISSUE TITLE
各种经典降维算法的资料整理与实现

### ISSUE THREAD

**Issue by heucoder** [521xueweihan/HelloGitHub#826]
## 项目推荐
- 项目地址：https://github.com/heucoder/dimensionality_reduction_alo_codes

- 类别：机器学习

- 项目后续更新计划：暂无

- 项目描述：
项目使用python实现了11种经典的数据抽取(数据降维)算法，同时附有相关资料，适用于机器学习初学者，刚刚入坑数据挖掘的初学者。
 
- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？
针对网上降维算法**资料参差不齐**以及**绝大部分资料不提供算法源码**的问题，汇总整理了一些优异的资源，同时提供了全部算法的源代码。为后来者提供方便。
- 示例代码：（可选）长度：
```
def cal_pairwise_dist(x):

    '''计算pairwise 距离, x是matrix
    (a-b)^2 = a^2 + b^2 - 2*a*b
    '''
    sum_x = np.sum(np.square(x), 1)
    dist = np.add(np.add(-2 * np.dot(x, x.T), sum_x).T, sum_x)
    #返回任意两个点之间距离的平方
    return dist
```
- 截图：
![LE算法](https://raw.githubusercontent.com/heucoder/dimensionality_reduction_alo_codes/master/codes/LE/LE_1.png)

**Comment by 521xueweihan** [comment]
@heucoder 您好，请问有后续更新计划吗？

**Comment by heucoder** [comment]
> @heucoder 您好，请问有后续更新计划吗？

数据降维系列不会再添加新的算法，后续应该会添加一些特征选择系列的算法，两者都是数据预处理中不同的特征提取算法

**Comment by 521xueweihan** [comment]
> > @heucoder 您好，请问有后续更新计划吗？
> 
> 数据降维系列不会再添加新的算法，后续应该会添加一些特征选择系列的算法，两者都是数据预处理中不同的特征提取算法

Readme 格式修改建议：

| 算法名 | 资料链接 | 代码 | 展示 |
| ------- | ----- | ----- | ------ |
| PCA | [资料1](xxx)、[资料2](xxx) | 示例代码链接 | 效果图|

**Comment by heucoder** [comment]
> > > @heucoder 您好，请问有后续更新计划吗？
> > 
> > 
> > 数据降维系列不会再添加新的算法，后续应该会添加一些特征选择系列的算法，两者都是数据预处理中不同的特征提取算法
> 
> 好的，知道了。
> 
> Readme 格式修改建议：
> 算法名 	资料链接 	代码 	展示
> PCA 	[资料1](xxx)、[资料2](xxx) 	示例代码链接 	效果图
> 
>     1. 资料链接处可修改的更加简洁
> 
>     2. 示例代码链接出来便于查找
> 
>     3. 效果图的展示非常好
> 
> 
> tips：markdown 语法可参考[这里](https://github.com/younghz/Markdown)

已修改，修改完之后确实看起来简洁了很多。
