### ISSUE TITLE
简单的C++网络库

### ISSUE THREAD

**Issue by caozhiyi** [521xueweihan/HelloGitHub#829]
## 项目推荐
- 项目地址：https://github.com/caozhiyi/CppNet

- 类别：C++

- 项目后续更新计划：
    1. 修复发现的问题，提高健壮性。
    2. 丰富操作系统类型支持。

- 项目描述：
    CppNet是一个高效简洁的C++网络库，对客户端而言仅引进了一个新的对象类型，使用起来完全类似原生socket接口。使用了最新的操作系统特性来提高效率，淌过了一个又一个OS接口的坑。代码简洁明了，最大的代码文件不超过500行，好学易懂，注释清晰。
    通过CppNet，你可以学习到从操作系统到应用层的所有网络细节。

- 推荐理由：简洁，高效，明了

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
@caozhiyi 标题中去掉了“最”。

既然是简单、面向学习者的。那么介绍也可以描述的更加通俗易通，站在初学者的角度，突出这个项目可以让初学者学习到的知识和项目特点。

**Comment by caozhiyi** [comment]
非常感谢收录！
我修改下介绍：

CppNet是一个封装在Tcp协议上的Proactor模式multi-thread网络库，包含OS接口调用，回调处理，定时器，数据缓存，任务队列……，这里有从操作系统到应用层的所有网络细节！
简单：CppNet对外只导出了少量的调用接口，所有的网络IO都封装为异步回调的形式，且接口声明都尽可能的像是调用系统socket API，对客户端而言，只多了一个新增的buffer对象类型。
快速：分别采用epoll和IOCP做底层事件驱动，其中epoll多线程惊群通过端口复用交由Linux内核处理。参照SGI STL和Nginx实现了内存池，每个建立连接的socket都独享一个内存池对象，所有从内存池中申请的内存都由智能指针管理。
明了：CppNet结构上分为三层：事件驱动层，会话管理层，接口层，各层之间通过回调向上通知。各个模块之间职责分工明确，上帝的事儿归上帝管，凯撒的事儿归凯撒管。最大的类不超过500行代码。

再次感谢收录，望采纳。

**Comment by ChungZH** [comment]
> 非常感谢收录！
> 我修改下介绍：
> 
> CppNet是一个封装在Tcp协议上的Proactor模式multi-thread网络库，包含OS接口调用，回调处理，定时器，数据缓存，任务队列……，这里有从操作系统到应用层的所有网络细节！
> 简单：CppNet对外只导出了少量的调用接口，所有的网络IO都封装为异步回调的形式，且接口声明都尽可能的像是调用系统socket API，对客户端而言，只多了一个新增的buffer对象类型。
> 快速：分别采用epoll和IOCP做底层事件驱动，其中epoll多线程惊群通过端口复用交由Linux内核处理。参照SGI STL和Nginx实现了内存池，每个建立连接的socket都独享一个内存池对象，所有从内存池中申请的内存都由智能指针管理。
> 明了：CppNet结构上分为三层：事件驱动层，会话管理层，接口层，各层之间通过回调向上通知。各个模块之间职责分工明确，上帝的事儿归上帝管，凯撒的事儿归凯撒管。最大的类不超过500行代码。
> 
> 再次感谢收录，望采纳。

太长了......精简一下吧 :joy:

**Comment by caozhiyi** [comment]
好，我再精简下：

CppNet是一个封装在Tcp协议上的Proactor模式multi-thread网络库，包含OS接口调用，回调处理，定时器，缓存管理，任务队列……，这里有从操作系统到应用层的所有网络细节！
简单：只导出了最少量的接口，其声明都类似系统socket API，对客户端而言，只新增了一个buffer类型。
快速：采用性能最优的epoll和IOCP做事件驱动，惊群处理交由内核。每个连接都独享一个内存池，从内存池中申请的内存都由智能指针管理。
明了：结构上分为事件驱动，会话管理，接口三层，通过回调向上通知。模块之间职责分工明确。最大的类不超过500行代码。

这次简练了蛮多。。

**Comment by ChungZH** [comment]
CppNet 是一个封装在 Tcp 协议上的 Proactor 模式 multi-thread 网络库，包含 OS 接口调用，回调处理，定时器，缓存管理，任务队列……，这里有从操作系统到应用层的所有网络细节！
- 简单：只导出了最少量的接口，其声明都类似系统 socket API，对客户端而言，只新增了一个 buffer 类型。
- 快速：采用性能最优的 epoll 和 IOCP 做事件驱动，惊群处理交由内核。每个连接都独享一个内存池，从内存池中申请的内存都由智能指针管理。
- 清晰：结构上分为事件驱动，会话管理，接口三层，通过回调向上通知。模块之间职责分工明确。最大的类不超过 500 行代码。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 43 期](https://hellogithub.com/periodical/volume/43/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
