### ISSUE TITLE
大数据入门指南

### ISSUE THREAD

**Issue by heibaiying** [521xueweihan/HelloGitHub#831]
## 项目推荐

- 项目地址：https://github.com/heibaiying/BigData-Notes

- 类别：教程

- 项目后续更新计划：
继续增加更多技术栈的讲解，并完善进阶方面的内容

- 项目描述：
详细介绍了大数据常用技术栈的基本知识，循序渐进地讲解了 Hadoop，Spark，Storm，HBase ，Hive，ZooKeeper，Kafka 等常用技术栈的核心知识点。

- 推荐理由：每篇文章都有很用心地去撰写，在保证简明扼要的基础上力求覆盖大多数的核心知识点。同时文章采用了大量的配图来讲解那些晦涩的内容，并提供了完整的示例代码和实验数据集。

- 截图：
![大数据技术栈思维导图](https://user-images.githubusercontent.com/31504331/66487675-59666480-eadf-11e9-9fd9-e392f30f9327.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 43 期](https://hellogithub.com/periodical/volume/43/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
