### ISSUE TITLE
SandDance：微软开源的这个可视化库

### ISSUE THREAD

**Issue by QingZ11** [521xueweihan/HelloGitHub#836]
## 项目推荐
- 项目地址：https://github.com/microsoft/SandDance

- 类别：TypeScript

- 项目描述：
  - 必写：微软开源的这个可视化库
  - 可选：数据可视化
  - 描述长度：SandDance 使用单元可视化，将数据库中的行一对一映射到屏幕中，在进行数据交互时，视图可无缝平滑过渡

- 推荐理由：可视化的效果有些 cool

- 截图：

![1](https://user-images.githubusercontent.com/38887077/66730798-650eae00-ee86-11e9-98fa-bac5c0aba1e9.gif)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 43 期](https://hellogithub.com/periodical/volume/43/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。
