### ISSUE TITLE
操作github的命令行工具

### ISSUE THREAD

**Issue by JohnnyTing** [521xueweihan/HelloGitHub#837]
## 项目推荐
- 项目地址：https://github.com/github/hub

- 类别：其它
- 项目后续更新计划：暂无

- 项目描述：
  -  通过命令行的方式来操作github
  -  包含操作github的大多数方式，比如创建远程仓库、删除远程仓库、提交PR、issue等。

- 推荐理由：不通过浏览器快速操作github，看起来更方便、更炫酷。

- 示例代码：
  创建远程仓库: hub create github-repository
  删除远程仓库: hub delete github-repository
  fork当前仓库到github: hub fork

- 截图：
![image](https://user-images.githubusercontent.com/46625434/66731945-72c73200-ee8c-11e9-9193-4394798661bf.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 43 期](https://hellogithub.com/periodical/volume/43/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
