### ISSUE TITLE
推荐nice-hooks，一个提供一些Nice的自定义Hooks，使得 React Hooks 更易于使用

### ISSUE THREAD

**Issue by daniel-dx** [521xueweihan/HelloGitHub#839]
## 项目推荐

- 项目地址：https://github.com/daniel-dx/nice-hooks

- 类别：JS

- 项目后续更新计划：

根据社区反馈，来不断增加好用的自定义Hooks

- 项目描述：

这是一个自定义 React Hooks 的项目，提供一些 Nice 的 Hooks，使得 React Hooks 更易于使用。

- 推荐理由：

当前官方 React Hooks 的功能还不是很好用，比如 useState 失去了 this.setState 的 callback 功能，比如没有专门对应的生命周期方法，比如没有专门用于声明实例变量的 hook 等

- 示例代码：

```
import React from 'react';

import { useStateCB } from 'nice-hooks';

const App = () => {
  const [count, setCount] = useStateCB(0);

  // Note: must use count state with method arguments instead of directly using the value of count state defined above
  function doSomeActions(count) {
    document.title = `Count: ${count}`
  }

  return (
    <div>
      {count}

      <button type="button" onClick={() => setCount(count + 1, doSomeActions)}>
        Increase
      </button>
    </div>
  );
};
```

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
