### ISSUE TITLE
QRCodeJS——可添加图片的二维码

### ISSUE THREAD

**Issue by JianmingXia** [521xueweihan/HelloGitHub#84]
## 项目推荐
- 项目名称：QRCodeJS

- 项目地址：https://github.com/JianmingXia/QRCodeJS

- 项目语言：JavaScript

- 项目描述：使用JS生成二维码，可选择在二维码中间添加Logo

- 推荐理由：之前找了很久能够给二维码添加Logo的代码，或者是贴的代码都是经过混淆的。原有QRCodeJS作者已很久没有维护，所以将项目Fork至我的项目中，并进行修改。希望更多的人使用。

- 示例代码：
```
var qrcode = new QRCode(document.getElementById("qrcode"), {
	text: "https://github.com/JianmingXia/QRCodeJS",
	width: 128,
	height: 128,
	colorDark : "#000000",
	colorLight : "#ffffff",
	correctLevel : QRCode.CorrectLevel.H,
	img_src: "img/user.jpg",
	img_width: 50
});
```

- 截图：
![image](https://user-images.githubusercontent.com/9691577/28708135-acd30552-73ad-11e7-89e4-77d0a1cfec67.png)

**Comment by 521xueweihan** [comment]
@JianmingXia 您好，已经推荐过类似的项目：https://github.com/sylnsfar/qrcode

**Comment by JianmingXia** [comment]
我觉得并不冲突，已推荐的是用python写的，前端生成二维码的需求还是很多的。
