### ISSUE TITLE
Android App在线自动更新

### ISSUE THREAD

**Issue by MZCretin** [521xueweihan/HelloGitHub#844]
## 项目推荐
- 项目地址：https://github.com/MZCretin/AutoUpdateProject

- 类别：Java-Android

- 项目后续更新计划：
   1、添加Apk文件加密

- 项目描述：
    Android内实现App在线更新功能，提供很多套备选UI，支持Android 9，可自定义UI，多中设置数据的方式！
    Android App 内容自更新方案，文件处理，通知栏操作，Apk安装等等

- 推荐理由： 
    + 最大亮点，提供12种更新的样式，总有一个是你喜欢的类型！
    + 支持三种设置更新信息的方式，您可以直接传model，传json数据，或者直接配置请求链接，sdk会自主请求并发起app的更新，满足多方需求！
    + 文件下载支持断点续传，下载错误拥有重试机制；相同版本的apk只会下载一次，防止重复下载！
    + 使用接口方式获取数据时支持设置请求头，支持POST和GET请求方式，更灵活，使用HttpUrlConnection，不集成其他复杂第三方网络框架。
    + 调用者可以自定义UI实现更新功能。
    + 已适配Android 6.0，Android 7.0，Android 8.0，Android 9.0。
    + 提供强制更新，不更新则无法使用APP，同时可以根据后台返回受影响的版本号，可控制多个版本同时被强制更新。
    + 通知栏图片自定义
    + 少配置，多功能，接入简单
    + 少其他三方库依赖，接入成本低

- 示例代码：
```
        //更新库配置
        UpdateConfig updateConfig = new UpdateConfig()
                .setDebug(true)//是否是Debug模式
                .setBaseUrl("http://www.cretinzp.com/system/versioninfo")//当dataSourceType为DATA_SOURCE_TYPE_URL时，配置此接口用于获取更新信息
                .setMethodType(TypeConfig.METHOD_GET)//当dataSourceType为DATA_SOURCE_TYPE_URL时，设置请求的方法
                .setDataSourceType(TypeConfig.DATA_SOURCE_TYPE_URL)//设置获取更新信息的方式
                .setShowNotification(true)//配置更新的过程中是否在通知栏显示进度
                .setNotificationIconRes(R.mipmap.download_icon)//配置通知栏显示的图标
                .setUiThemeType(TypeConfig.UI_THEME_AUTO)//配置UI的样式，一种有12种样式可供选择
                .setRequestHeaders(null)//当dataSourceType为DATA_SOURCE_TYPE_URL时，设置请求的请求头
                .setRequestParams(null)//当dataSourceType为DATA_SOURCE_TYPE_URL时，设置请求的请求参数
                .setCustomActivityClass(CustomActivity.class)//如果你选择的UI样式为TypeConfig.UI_THEME_CUSTOM，那么你需要自定义一个Activity继承自RootActivity，并参照demo实现功能，在此处填写自定义Activity的class
                .setModelClass(new UpdateModel());
        AppUpdateUtils.init(this, updateConfig);
```

- 截图：
  当前有12中样式可以选择
  ![样式.png](https://upload-images.jianshu.io/upload_images/2356659-52128746db514090.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by 521xueweihan** [comment]
@MZCretin 您好，能否简述下和：https://github.com/xuexiangjys/XUpdate 这个项目的区别和优势。

**Comment by MZCretin** [comment]
您好，相比之下，可定制化的东西没有这个这么多，不过就易用性和接入成本来说，我觉得我这个简单点！我这边支持了常用的定制，减少了冗余的定制！
1、对于更新信息的设置，我这边提供两种方式，可定制化分的没有那么细，不过我觉得我这个使用更加简单，只需要配置请求链接和返回的数据对象类型即可！而且不对更新接口返回的数据有任何的限制！
2、有12套可直接使用的样式供选择
3、请求接口提供了请求头的设置
4、demo依赖了太多其他第三方库，使用成本变高
5、本身不支持网络请求，需要外部提供，我这边使用原生HttpUrlConnection提供支持
。。。

**Comment by 521xueweihan** [comment]
@MZCretin 您好，**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

修改建议：
1. 能否把描述中的 12 种更新的样式合并到一张图，这样会更加直观和美观。
2. 请参考 #271 修改 Readme，简洁的项目首页有助于大家快速获取关键信息，产生兴趣。

**Comment by MZCretin** [comment]
@521xueweihan 已修改

**Comment by 521xueweihan** [comment]
@MZCretin 收到，👍

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 43 期](https://hellogithub.com/periodical/volume/43/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
