### ISSUE TITLE
鲁班H5：开源版本的H5制作平台，可以简单理解为开源版本的 mini 易企秀

### ISSUE THREAD

**Issue by ly525** [521xueweihan/HelloGitHub#846]
# 自荐项目： 鲁班H5 开源版本的H5制作平台

## 项目自荐
- 项目地址：
  - GitHub 地址：[https://github.com/ly525/luban-h5](https://github.com/ly525/luban-h5)
  - 在线访问地址：[https://api.luban-h5.wxjcart.com/](https://api.luban-h5.wxjcart.com/) （后续可能会更新，建议从上面仓库地址进入）

- 类别：JavaScript
- 项目后续更新计划：支持模板模块，完善动画系统，支持用户模块
- 项目描述：
  - 必写：鲁班H5是基于Vue2.0开发的，通过拖拽的形式，生成页面的工具，类似易企秀、百度 H5 等工具

- 推荐理由：
    1. 类似易企秀，采用拖拽的形式，可以快速支持H5页面，减轻前端工程师的负担。
    2. 支持
       1.  表单单数据收集和统计 
       1. 模板系统
       1. 支持动画模块
       1. 前后端均具备，功能相对比较完备
       1. 更多功能请查看：Features [https://ly525.github.io/luban-h5/zh/getting-started/features.html](https://ly525.github.io/luban-h5/zh/getting-started/features.html)
    3. 对开发者友好且完善的中英文文档，文档地址：[https://ly525.github.io/luban-h5/zh/](https://ly525.github.io/luban-h5/zh/)
    4. 前后端均开源

- 截图：

<img src="https://s2.ax1x.com/2019/10/11/u7WzUx.gif" style="margin: 10px;" width="60%" /><br />

备注：
最近一周曾两次登上 GitHub Trending
![image](https://user-images.githubusercontent.com/12668546/67143817-ed83b900-f2a1-11e9-9104-23e095a2fe56.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
