### ISSUE TITLE
svrx - 一个渐进且易于使用的、插件化的前端开发工作台

### ISSUE THREAD

**Issue by int64ago** [521xueweihan/HelloGitHub#848]
## 项目推荐
- 项目地址：https://github.com/svrxjs/svrx

- 类别：JS

- 项目后续更新计划：svrx-ui 支持可视化配置

- 项目描述：
  - 必写：一个渐进且易于使用的、插件化的前端开发工作台
  - 可选：适用于前端开发，把折腾开发环境的时间省下来做更有意义的事
  - 描述长度（不包含示例代码）: 作为前端开发，在不同的开发需求下，一般来说我们会有一套或者多套固定的开发环境。 它可能包括本地服务器以及各种用于调试工程的小工具。 维护这样的开发环境是很麻烦的：你不仅需要单独安装每一个工具，还需要对每一个工具进行设置。 svrx 做的，就是利用插件机制来整合各种前端开发服务， 让前端开发者可以自由挑选所需的功能，如静态伺服、代理、远程调试等，且无需关心这些功能插件的安装过程。 有了svrx这样一个前端开发工作台，我们可以轻松做到一份配置对应一套开发环境，实现真正的一键启动开发服务。

- 推荐理由：一款全新的前端开发工具，它能给你的前端开发带来看起来和现在一样但其实又不那么一样的体验

- 示例代码：

```bash
npm install -g @svrx/cli
mkdir example && cd example
echo '<html><body>Hello svrx!</body></html>' > index.html
svrx
```

- 截图：

![](https://svrx.io/assets/demo.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
@int64ago 您好由于篇幅问题，您的项目将于下期推荐。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 44 期](https://hellogithub.com/periodical/volume/44/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了《讲解开源项目》系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
