### ISSUE TITLE
【自薦項目】chart-race-react: 完全客製化的長條圖賽跑動畫 React 組件

### ISSUE THREAD

**Issue by Mckinsey666** [521xueweihan/HelloGitHub#849]
## 项目推荐
- 项目地址：https://github.com/Mckinsey666/chart-race-react

- 类别：Javascript

- 项目后续更新计划：
  - 新增時間軸
  - 資料內差補齊

- 项目描述：2019 年是 Bar Chart Race 爆炸的一年。到處都可以看到各種隨時間變化的長條圖賽跑，有GDP, 人口, 公司市值等等。此套件基於 React 開發，讓使用者輕易將 Bar Chart Race 融入自己的網頁中，可以自定義資料集，同時可以完全客製化視覺設計，如顏色，長條圖風格，動畫延遲時間等等。是一個資料視覺化（data visualization）以及前端開發的好用套件。

- 推荐理由：動畫完全 encapsulated ，讓使用者不用擔心動畫的設計，只需要定義好靜態的風格，套件會完全幫你做出流暢的長條圖賽跑動畫。客製化 React 組件也讓前端設計師更輕易做出自己想到的風格。

- 示例代码：
```javascript
import ReactDOM from 'react-dom';
import BarChart from 'chart-race-react';

ReactDOM.render(<BarChart />, document.getElementById('root'));
```
- 截图：

![demo](https://raw.githubusercontent.com/Mckinsey666/chart-race-react/master/assets/demo.gif)

||||
|---|---|---|
|![color1](https://raw.githubusercontent.com/Mckinsey666/chart-race-react/master/assets/color1.gif)|![color2](https://raw.githubusercontent.com/Mckinsey666/chart-race-react/master/assets/color2.gif)|![color3](https://raw.githubusercontent.com/Mckinsey666/chart-race-react/master/assets/color3.gif)|
|![border1](https://raw.githubusercontent.com/Mckinsey666/chart-race-react/master/assets/border1.gif)|![border2](https://raw.githubusercontent.com/Mckinsey666/chart-race-react/master/assets/border2.gif)|![border3](https://raw.githubusercontent.com/Mckinsey666/chart-race-react/master/assets/border3.gif)|
|![speed3](https://raw.githubusercontent.com/Mckinsey666/chart-race-react/master/assets/speed3.gif)|![speed1](https://raw.githubusercontent.com/Mckinsey666/chart-race-react/master/assets/speed1.gif)|![speed2](https://raw.githubusercontent.com/Mckinsey666/chart-race-react/master/assets/speed2.gif)|
||||

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 43 期](https://hellogithub.com/periodical/volume/43/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
