### ISSUE TITLE
Sweetalert

### ISSUE THREAD

**Issue by JameJJ** [521xueweihan/HelloGitHub#85]
## 项目推荐
- 项目名称：Sweetalert

- 项目地址：https://github.com/t4t5/sweetalert

- 项目语言：JavaScript

- 项目描述：很漂亮的alert

- 推荐理由：纯JS写成的alert组件，很多公司项目采用了的项目。源代码使用了ES6进行了重构，项目结构更加清晰，通过学习他的项目结构可以知道一个JS组件的文件结构。通过对源码分析可以学习原生JS的DOM复杂操作的技巧

- 示例代码：
判断class，添加class，删除class
![image](https://user-images.githubusercontent.com/12341577/28722390-2c9160ee-73e6-11e7-8986-3c4d4a46bd4f.png)

- 截图：
> 官网地址：http://t4t5.github.io/sweetalert/

带有图标的alert
![image](https://user-images.githubusercontent.com/12341577/28722462-6a0c1a54-73e6-11e7-8f95-e8b541d11180.png)

带有交互的alert
![image](https://user-images.githubusercontent.com/12341577/28722490-82365216-73e6-11e7-8692-f8cce4c41014.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功收录**在 [HelloGitHub 第 17 期](https://github.com/521xueweihan/HelloGitHub/blob/master/content/17/HelloGitHub17.md)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，如果方便可以 Star ⭐️ 本项目，让更多人看到本项目。
