### ISSUE TITLE
【自荐项目】Android X2J，让你的 XML 布局直接变成 Java 来运行 

### ISSUE THREAD

**Issue by 7hens** [521xueweihan/HelloGitHub#850]
## 项目推荐

- 项目地址：https://github.com/7hens/android-x2j

- 类别：Java/Kotlin/Android

- 项目后续更新计划：暂无

- 项目描述：Android X2J（XML to Java）是一个 Gradle 插件，它可以在 APK 编译期间 自动 将你的 XML 布局翻译成 Java 代码，并 自动 注入到 Activity 和自定义布局中。

- 推荐理由：传统的布局加载方案都是在运行时解析 XML（通过 LayoutInflater），而 Android X2J 则可以将 XML 的解析提前到编译时，从而可以让布局加载速度提升 200%

- 示例代码：无，只需参照 README 导入该插件即可

- 截图：无

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
