### ISSUE TITLE
贪吃蛇

### ISSUE THREAD

**Issue by z-rx** [521xueweihan/HelloGitHub#851]
## 项目推荐
- 项目地址https://github.com/z-rx/Snake-practice

- 类别：请从中选择C++

- 项目后续更新计划：使用更简洁的方式写出来，或者优化界面

- 项目描述：
  - 必写：一个看起来还好的贪吃蛇(多线程)
  - 可选：可以使初学者了解一些东西
  - 描述长度（不包含示例代码）: 10 - 256 个字符

- 推荐理由：使用多线程，好看的命令行界面

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
