### ISSUE TITLE
一款轻量且精致的、基于React的H5播放器组件

### ISSUE THREAD

**Issue by vortesnail** [521xueweihan/HelloGitHub#853]
## 项目推荐
- 项目地址：https://github.com/vortesnail/qier-player

- 类别：JS、React

- 项目后续更新计划：增加找不到播放源的错误提示、全屏状态下鼠标悬停3秒之后鼠标消失，控制栏隐藏、增加主题色更改等

- 项目描述：
  - 必写：适配PC端、基于React的播放器组件，可用于在你的项目中轻松添加播放器组件用于播放视频，如果你嫌原生video功能太少，操作太傻，界面太简单，那这个播放器就是你的菜。
  - 可选：适用于自己的项目中需要用到视频播放器的情况下，你可通过阅读源码了解到关于生命周期执行顺序、父子组件传值的方式、以及如何利用定时器进行一些实时的状态更新。

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？ 简约、功能充足、轻量且精致的 h5 播放器组件

安装
```bash
npm install --save qier-player
```
使用
```js
import React from 'react';
import ReactDOM from 'react-dom';
import QierPlayer from 'qier-player';


ReactDOM.render(<QierPlayer srcOrigin="你的视频地址"/>, document.getElementById('root'));
```
- 截图：
![整体样式](https://i0.hdslb.com/bfs/album/dc46482ec425ebf78f8501fb44f05f8b01cbda4b.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 44 期](https://hellogithub.com/periodical/volume/44/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了《讲解开源项目》系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
