### ISSUE TITLE
eladmin

### ISSUE THREAD

**Issue by hellowHuaairen** [521xueweihan/HelloGitHub#856]
## 项目推荐
- 项目地址：https://github.com/elunez/eladmin

- 类别：Java

- 项目描述：
eladmin基于 Spring Boot 2.1.0 、 Jpa、 Spring Security、redis、Vue的前后端分离的后台管理系统， 权限控制的方式为RBAC，项目支持数据字典与数据权限管理，支持一键生成前后端代码，支持前端菜单动态路由。

- 推荐理由：基于Spring Boot2.1.0框架，使用的工具有非关系数据库redis,接口测试工具swagger,数据库使用的druid数据源驱动，邮件依赖（javax.mail），七牛云存储sdk，支付宝sdk,页面模板引擎使用的是freemarker。超级丰富的内容，值得学习。

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg
![image](https://user-images.githubusercontent.com/19610305/67615037-99c12480-f7f9-11e9-9442-67e0c5169f42.png)

![image](https://user-images.githubusercontent.com/19610305/67615039-a2b1f600-f7f9-11e9-85b5-1b2592393f05.png)
![image](https://user-images.githubusercontent.com/19610305/67615065-00464280-f7fa-11e9-9a3d-360a9b9a0861.png)

![image](https://user-images.githubusercontent.com/19610305/67615064-f91f3480-f7f9-11e9-9e42-837d0564d94c.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
