### ISSUE TITLE
LeetCode题记记录

### ISSUE THREAD

**Issue by tangweikun** [521xueweihan/HelloGitHub#858]
## 项目推荐
- 项目地址：https://github.com/tangweikun/leetcode

- 类别：JS

- 项目后续更新计划：持续更新中

- 项目描述：
  - 必写：LeetCode的JavaScript解题记录

- 推荐理由：提供多种解题思路，涵盖了300多提LeetCode题解

**Comment by 521xueweihan** [comment]
@tangweikun 请勿重复提价：https://github.com/521xueweihan/HelloGitHub/issues/184
