### ISSUE TITLE
历史地图

### ISSUE THREAD

**Issue by faithxie** [521xueweihan/HelloGitHub#859]
## 项目推荐
- 项目地址：https://sdmtai.github.io

- 类别：js

- 项目描述：
  - 必写：中国疆土历史地图，快速翻页有疆土变化特效哟

- 截图：
![image](https://user-images.githubusercontent.com/19542104/67616764-5ec9eb80-f80f-11e9-83fd-6c4a56855aae.png)

**Comment by 521xueweihan** [comment]
@faithxie 要有项目地址

**Comment by faithxie** [comment]
加上了
