### ISSUE TITLE
jeecg-boot

### ISSUE THREAD

**Issue by hellowHuaairen** [521xueweihan/HelloGitHub#861]
## 项目推荐
- 项目地址：https://github.com/zhangdaiscott/jeecg-boot

- 类别：Java

- 项目描述：一款基于代码生成器的JAVA快速开发平台！采用最新技术，前后端分离架构：SpringBoot 2.x，Ant Design&Vue，Mybatis-plus，Shiro，JWT。强大的代码生成器让前后端代码一键生成，无需写任何代码，绝对是全栈开发福音！！JeecgBoot提高UI能力的同时,降低前后分离的开发成本，JeecgBoot还独创在线开发模式，No代码概念，一系列在线智能开发：在线配置表单、在线配置报表、在线设计流程等等。

- 推荐理由：丰富的文档教程，视频教程，在线演示环境，还有交流群，是学习不错的选择。

- 截图：
![image](https://user-images.githubusercontent.com/19610305/67652188-d10d0e00-f97e-11e9-878a-ab7a30317192.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。
**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。
再次感谢您对 HelloGitHub 的支持 🙏
