### ISSUE TITLE
le5le-topology，类Visio的绘图工具

### ISSUE THREAD

**Issue by Alsmile** [521xueweihan/HelloGitHub#863]
## 项目推荐 Le5le-Topology
- 项目地址：https://github.com/le5le-com

- 类别：JS

- 项目后续更新计划：持续内核升级、响应式事件。

- 项目描述：
  -Topology是乐吾乐公司自主设计、研发的开源web绘图工具，拥有为电力能源、水利、物联网、工业互联网、智慧城市、智慧医疗、智慧农业、IT运维等提供解决方案的可视化平台。

- 推荐理由：Topology具有跨平台、高效、可扩展、实时监控、动态交互、支持自动算法等特点。最大程度减少研发和运维的成本，并致力于普通业务人员0代码开发实现web组态、SCADA等场景。

- 示例代码：
import { Topology } from '@topology/core';
import { register as registerFlow } from '@topology/flow-diagram';
import { register as registerActivity } from '@topology/activity-diagram';
import { register as registerClass } from '@topology/class-diagram';
import { register as registerSequence } from '@topology/sequence-diagram';
import { register as registerChart } from '@topology/chart-diagram';
registerFlow();
registerActivity();
registerClass();
registerSequence();
registerChart();
var canvas = new Topology('topo-canvas', {});
const json = {pens:[xxxx]};
canvas.open(json);

- 截图：
![1](https://user-images.githubusercontent.com/77136284/110762299-9a8e1580-828b-11eb-8a0e-687aa602e959.gif)
![3958a5790ef59106ff91bea7369c616](https://user-images.githubusercontent.com/77136284/110762366-ad084f00-828b-11eb-9d75-30eb203d7886.png)
![微信图片_20210112143915](https://user-images.githubusercontent.com/77136284/110762447-c1e4e280-828b-11eb-8516-0a9c09c60c09.png)

**Comment by 521xueweihan** [comment]
@Alsmile 您好，图挂了。修复后可已重新 @我

**Comment by Alsmile** [comment]
@521xueweihan 已修复。

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
