### ISSUE TITLE
EH Forwarder Bot：一个可扩展的聊天隧道框架。

### ISSUE THREAD

**Issue by blueset** [521xueweihan/HelloGitHub#864]
## 项目推荐
- 项目地址：
  - https://github.com/blueset/ehForwarderBot
  - https://github.com/blueset/efb-telegram-master
  - https://github.com/blueset/efb-wechat-slave
  - https://github.com/blueset/efb-fb-messenger-slave
  - https://github.com/milkice/efb-qq-slave
  - 等等

- 类别：Python

- 项目描述：
开发代号 EH Forwarder Bot (EFB) 是一个可扩展的聊天隧道框架，允许用户联系其他聊天平台的用户，并远程控制他们在其他平台上的账户。目前框架主维护者（我）以及社区提供的 Telegram、微信、QQ 以及 Facebook Messenger 的隧道通讯支持。组件库中也提供了各种功能的中间件以供使用。

- 项目后续更新计划：
  - 完成框架以及我所维护的组件的单元测试
  - 进一步支持更多的即时通讯平台
  - 开发专属的主端以及消息转发主端

- 推荐理由：
  通过一个统一的 API 来管理各种即时通讯平台，能够通过一种用户体验较好的方式来使用那些体验 
 较差的平台。能够将所有信息统一汇总在一处、并方便进行自动化处理。

- 示例代码：

```shell
$ # 安装 EH Forwarder Bot 框架
$ pip3 install ehforwarderbot
$ # 安装通讯平台组件（略）
$ # 启动设置向导
$ efb-wizard
$ # 启动主程序
$ ehforwarderbot
```

- 截图：

| ![image](https://user-images.githubusercontent.com/553831/67655274-07508a80-f98b-11e9-9d39-70380542899a.png) |
| :-: |
| 项目 Banner |
| ![image](https://miro.medium.com/max/4538/0*MMO8ZyD71zP_fAzt.jpg) |
| 启用了微信和 Telegram 组件的使用例（截图来自[日向](https://medium.com/cnhinata/%E7%94%A8-telegram-%E6%94%B6%E5%8F%91%E5%BE%AE%E4%BF%A1%E6%B6%88%E6%81%AF-906517d10cd1)） |
| ![image](https://user-images.githubusercontent.com/553831/67655576-0ff59080-f98c-11e9-83ee-23ed68eb4fb0.png) |
| 启用了微信和 Telegram 组件的使用例（截图来自[Armin Li](https://arminli.com/blog/177)） |

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。我又重新看了下项目，决定月刊中暂不收录该项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
