### ISSUE TITLE
KubeOperator - K8s 集群规划、部署及管理平台

### ISSUE THREAD

**Issue by KubeOperator** [521xueweihan/HelloGitHub#866]
## 项目推荐
- 项目地址：

https://github.com/KubeOperator/KubeOperator

- 类别：请从中选择（C、C#、C++、CSS、Go、Java、JS、Kotlin、Objective-C、PHP、Python、Ruby、Swift、其它、书籍、机器学习）

Python

- 项目后续更新计划：

KubeOperator 2.2 计划在 11月30日发布，2.3 计划在 12.31 发布。3.0 计划在 2020.06.30 发布。 

- 项目描述：
  - 必写：这是个什么项目、能用来干什么、有什么特点或解决了什么痛点
  - 可选：适用于什么场景、能够让初学者学到什么
  - 描述长度（不包含示例代码）: 10 - 256 个字符

KubeOperator 是一个开源项目，在离线网络环境下，通过可视化 Web UI 在 VMware、Openstack 或者物理机上规划、部署和管理生产级别的 Kubernetes 集群。

Kubernetes 是新一代云原生应用的基础设施，KubeOperator 可以帮助初学者快速部署 K8s 集群，开启他们的 Kubernetes 之旅。

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？

KubeOperator 提供简介的 Web UI，使用 Terraform 在 IaaS 平台上自动创建主机（用户也可以自行准备主机，比如物理机或者虚机），通过 Ansible 完成自动化部署和变更操作，支持 Kubernetes 集群 从 Day 0 规划，到 Day 1 部署，到 Day 2 运维及变更的全生命周期管理。

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

![image](https://user-images.githubusercontent.com/52770786/67767534-b7a5b800-fa8b-11e9-8fac-253cba7e882a.png)

## 提示（提交时请删除以下内容）
> 点击上方 “Preview” 更方便地阅读以下内容，

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
@KubeOperator 请按照要求填写，删除提示语等信息。更新完内容欢迎 @ 我
