### ISSUE TITLE
新蜂商城：基于 Spring Boot 2 及相关技术栈开发的 Java 开源商城项目

### ISSUE THREAD

**Issue by newbee-mall** [521xueweihan/HelloGitHub#867]
## 项目推荐

- 项目地址：https://github.com/newbee-ltd/newbee-mall

- 类别：Java

- 项目后续更新计划：继续完善功能，并对项目进行性能优化。

- 项目描述：

![newbee-mall](https://camo.githubusercontent.com/8d311a7c9e32fcd3d88035bf5520382fc8a1044f/68747470733a2f2f6e65776265652d6d616c6c2e6f73732d636e2d6265696a696e672e616c6979756e63732e636f6d2f706f737465722f70726f647563742f6e65776265652d6c6f676f2e706e673f782d6f73732d70726f636573733d696d6167652f726573697a652c685f3234302c775f343830)
newbee-mall 项目是一套电商系统，包括 newbee-mall 商城系统及 newbee-mall-admin 商城后台管理系统，基于 Spring Boot 2.X 及相关技术栈开发。 前台商城系统包含首页门户、商品分类、新品上线、首页轮播、商品推荐、商品搜索、商品展示、购物车、订单结算、订单流程、个人订单管理、会员中心、帮助中心等模块。 后台管理系统包含数据面板、轮播图管理、商品管理、订单管理、会员管理、分类管理、设置等模块

- 推荐理由：

1. newbee-mall 对新手开发者十分友好，无需复杂的操作步骤，仅需 2 秒就可以启动这个完整的商城项目；
 2. newbee-mall 也是一个企业级别的 Spring Boot 大型项目，对于各个阶段的 Java 开发者都是极佳的选择；
 3. 你可以把它作为 Spring Boot 技术栈的综合实践项目，newbee-mall 足够符合要求，且代码开源、功能完备、流程完整、页面交互美观；
 4. 技术栈新颖且知识点丰富，学习后可以提升大家对于知识的理解和掌握，可以进一步提升你的市场竞争力；
 5. 对于部分求职中的 Java 开发者，你也可以将该项目放入求职简历中以丰富你的工作履历；

- 截图：

#### 商城页面预览

- 商城首页 1

	![index](https://newbee-mall.oss-cn-beijing.aliyuncs.com/poster/product/index-01.png)

- 商城首页 2

	![index](https://newbee-mall.oss-cn-beijing.aliyuncs.com/poster/product/index-02.png)

- 商品搜索

	![search](https://newbee-mall.oss-cn-beijing.aliyuncs.com/poster/product/search.png)

- 购物车

	![cart](https://newbee-mall.oss-cn-beijing.aliyuncs.com/poster/product/cart.png)
	
- 订单结算

	![settle](https://newbee-mall.oss-cn-beijing.aliyuncs.com/poster/product/settle.png)
			
- 订单列表

	![orders](https://newbee-mall.oss-cn-beijing.aliyuncs.com/poster/product/orders.png)	
	
- 支付页面

	![settle](https://newbee-mall.oss-cn-beijing.aliyuncs.com/poster/product/wx-pay.png)

### 后台管理页面

- 登录页

	![login](https://newbee-mall.oss-cn-beijing.aliyuncs.com/poster/product/manage-login.png)

- 轮播图管理

	![carousel](https://newbee-mall.oss-cn-beijing.aliyuncs.com/poster/product/manage-carousel.png)
	
- 新品上线

    ![config](https://newbee-mall.oss-cn-beijing.aliyuncs.com/poster/product/manage-index-config.png)

- 分类管理

	![category](https://newbee-mall.oss-cn-beijing.aliyuncs.com/poster/product/manage-category.png)

- 商品管理

	![goods](https://newbee-mall.oss-cn-beijing.aliyuncs.com/poster/product/manage-goods.png)

- 商品编辑

	![edit](https://newbee-mall.oss-cn-beijing.aliyuncs.com/poster/product/manage-goods-edit.png)

- 订单管理

	![order](https://newbee-mall.oss-cn-beijing.aliyuncs.com/poster/product/manage-order.png)

**Comment by 521xueweihan** [comment]
辛苦 @hellowHuaairen  审核该项目能否收录

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 44 期](https://hellogithub.com/periodical/volume/44/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了《讲解开源项目》系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）

**Comment by newbee-mall** [comment]
谢谢你的推荐❤



---原始邮件---
发件人: "削微寒"<notifications@github.com&gt;
发送时间: 2019年11月27日(星期三) 下午5:45
收件人: "521xueweihan/HelloGitHub"<HelloGitHub@noreply.github.com&gt;;
抄送: "十三"<zhenfengshisan@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [521xueweihan/HelloGitHub] 新蜂商城：基于 Spring Boot 2 及相关技术栈开发的 Java 开源商城项目 (#867)



您推荐的项目，已成功发布在 HelloGitHub 第 44 期，并把您添加到了贡献者列表中。
 
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
 
HG 发起了《讲解开源项目》系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
