### ISSUE TITLE
gka

### ISSUE THREAD

**Issue by joeyguo** [521xueweihan/HelloGitHub#87]
## 项目推荐
- 项目名称：gka

- 项目地址：https://github.com/gkajs/gka

- 项目语言：JavaScript

- 项目描述：简单的、高效的帧动画生成工具

- 推荐理由：只需一行命令，快速图片优化、生成动画文件，支持效果预览。支持相同帧图片复用✓，图片空白裁剪✓，合图模式✓，图片压缩✓，图片重命名✓，内置多种文件输出模板，支持自定义模板

- 示例代码：

```bash
npm i gka -g

gka E:\img 
```

- 截图：
![](https://user-images.githubusercontent.com/10385585/28651130-77b0bc80-72b2-11e7-9c42-7aad9e5774a7.jpg)
![preview](https://cloud.githubusercontent.com/assets/10385585/24502038/ac4bd9f2-157e-11e7-87e0-a9a44aaffafa.gif)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功收录**在 [HelloGitHub 第 17 期](https://github.com/521xueweihan/HelloGitHub/blob/master/content/17/HelloGitHub17.md)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，如果方便可以 Star ⭐️ 本项目，让更多人看到本项目。
