### ISSUE TITLE
KubeOperator - K8s 集群规划、部署及管理平台

### ISSUE THREAD

**Issue by KubeOperator** [521xueweihan/HelloGitHub#870]
## 项目推荐
- 项目地址：https://github.com/KubeOperator/KubeOperator
- 类别：Python
- 项目后续更新计划：KubeOperator 2.2 计划在 11 月 30 日发布，2.3 计划在 12 月 31 日发布，3.0 计划在 2020 年 06 月 30 日 发布。 
- 项目描述：
  - 必写：KubeOperator 是一个开源项目，在离线网络环境下，通过可视化 Web UI 在 VMware、Openstack 或者物理机上规划、部署和管理生产级别的 Kubernetes 集群。
  - 可选：Kubernetes 是新一代云原生应用的基础设施，KubeOperator 可以帮助初学者快速部署 K8s 集群，开启他们的 Kubernetes 之旅。
- 推荐理由：KubeOperator 提供简介的 Web UI，使用 Terraform 在 IaaS 平台上自动创建主机（用户也可以自行准备主机，比如物理机或者虚机），通过 Ansible 完成自动化部署和变更操作，支持 Kubernetes 集群 从 Day 0 规划，到 Day 1 部署，到 Day 2 运维及变更的全生命周期管理。
- 截图：
![image](https://user-images.githubusercontent.com/52770786/67767534-b7a5b800-fa8b-11e9-8fac-253cba7e882a.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 44 期](https://hellogithub.com/periodical/volume/44/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了《讲解开源项目》系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
