### ISSUE TITLE
网站的插图都裂了

### ISSUE THREAD

**Issue by Thchoonlophon** [521xueweihan/HelloGitHub#871]
![mark](http://lynchow.com/upload_picture/20191030/TogJmDMqVcgE.png?imageslim)
插图全都加载失败，网站和GitHub上面都是图片都加载不出来。

**Comment by 521xueweihan** [comment]
@Thchoonlophon @Azzy97 感谢反馈，已修复。https://hellogithub.com/periodical/volume/43/
