### ISSUE TITLE
Mohism cli-wrapper 更简单的开发你的命令行工具，  然后以插件的方式共享给你的朋友。

### ISSUE THREAD

**Issue by captainblue2013** [521xueweihan/HelloGitHub#874]
## 项目推荐
- 项目地址：https://github.com/mohism-framework/cli-wrapper

- 类别：JS

- 项目后续更新计划：
   - 集成更多常用组件
   - 加强 code gen 方面的内容 

- 项目描述：
  - 必写：更简单的开发你的命令行工具，  然后以插件的方式共享给你的朋友。
  - 可选：适用于开发自动化工具，或者其他有趣的读写

- 推荐理由：
   在我们的研发流程里，尤其是结合到devops的环节，需要开发大量的自动化工具。
   为了弥补shell编程能力的不足，选择了node作为命令行开发语言。
   而市面上的解决方案五花八门，经常有大量的重复工作，所以开发了这个可以支持插件化命令
   的项目。

- 示例代码： 详情看项目地址  README

- 截图：

**Comment by 521xueweihan** [comment]
我是这么理解这个项目的：node 实现命令，以解决 shell 编写脚本的局限性，提高自动化的幸福度。

如果有误，欢迎指正

**Comment by captainblue2013** [comment]
> 我是这么理解这个项目的：node 实现命令，以解决 shell 编写脚本的局限性，提高自动化的幸福度。
> 
> 如果有误，欢迎指正

还有更多。
使用一门更丰富编程语言是第一步，
整合命令行开发的通用内容，让开发者专注具体细节功能，是第二步，
依托npm模块管理，实现命令共享，是第三补。

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。
**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。
再次感谢您对 HelloGitHub 的支持 🙏
