### ISSUE TITLE
LLDebugTool - 一款便捷的iOS调试工具

### ISSUE THREAD

**Issue by HDB-Li** [521xueweihan/HelloGitHub#876]
## 项目推荐
- 项目地址：https://github.com/HDB-Li/LLDebugTool

- 类别：Objective-C

- 项目描述：
LLDebugTool是一款针对开发者和测试者的调试工具，它可以帮助你在非Xcode的情况下，进行数据分析和操作

1. 检查网络请求或者查看某些事件的日志信息，而不必非在XCode运行下运行。这在解决测试人员的问题上很有用。

2. 更轻松的筛选有用的信息。

3. 更轻松的处理偶发的问题。

4. 更轻松的分析崩溃原因。

5. 更轻松的分享、预览或删除沙盒文件，这在开发阶段非常有用。

6. 更轻松的观察App的CPU，内存，FPS等信息。

7. 截屏、标注并分享。

8. 更直观的查看视图结构，并修改具体属性值。

9. 更准确地确定App里的UI元素和颜色。

10. 便捷的获取和对比位置信息。

11. 便捷的查看元素边框及位置。

12. 快速的Html容器入口。

- 推荐理由：脱离XCode，动态的Debug你的App。

- 截图：
![preview](https://raw.githubusercontent.com/HDB-Li/HDBImageRepository/master/LLDebugTool/screenGif.gif)
![preview](https://raw.githubusercontent.com/HDB-Li/HDBImageRepository/master/LLDebugTool/screenGif2.gif)

![preview](https://github.com/HDB-Li/HDBImageRepository/blob/master/LLDebugTool/ScreenShot-1-small.png)

**Comment by 521xueweihan** [comment]
您好，月刊中已推荐过类似的项目，所以您的项目暂时不能收录到月刊中，谢谢您的支持和理解～

**Comment by HDB-Li** [comment]
但是我的项目和Doraemonkit还不太一样，我的项目有监控网络请求的功能。

**Comment by 521xueweihan** [comment]
@HDB-Li 您好，能否横向对比下这个库：https://hellogithub.com/periodical/category/Swift%20%E9%A1%B9%E7%9B%AE/#CocoaDebug
