### ISSUE TITLE
项目自荐: 暗网中文网监控爬虫

### ISSUE THREAD

**Issue by aoii103** [521xueweihan/HelloGitHub#878]
## 项目推荐
- 项目地址：https://github.com/aoii103/DarkNet_ChineseTrading

- 类别：```Python```

- 项目后续更新计划：持续跟进暗网站点动向

- 项目描述：
  🚇这是一个针对全球最大的中文暗网交易市场 **(DEEPMIX)** 的实时情报监控爬虫。可自动注册用户并登陆爬取，并可在第一时间将信息整理成图文发至相关telegram频道。

  ✨包含以下特点:
  - Tor节点切换
  - 自动注册(中文式账户)
  - 自动登录
  - 防封禁
  - ORM交互
  - 事件详情/样本信息录入
  - 事件提醒（`telegram`）[图文]
  - 分类爬取
  - 裸体图片过滤(保存但不发送)
  - 残留EXIF-GPS信息提取

- 截图：
![mosaic](https://user-images.githubusercontent.com/22721729/68106281-1059d280-ff1c-11e9-91bd-d5c731048007.jpg)

**Comment by 521xueweihan** [comment]
@aoii103 坦白的说，我早就想把这个项目收录到 HG 月刊中。但认真考虑的下，为了本项目的“长治久安”，不能收录。真的不是因为您项目质量的原因，还望您能理解。
