### ISSUE TITLE
spring-data-jpa-datatables

### ISSUE THREAD

**Issue by eastseven** [521xueweihan/HelloGitHub#88]
## 项目推荐
- 项目名称：
spring-data-jpa-datatables
- 项目地址：
https://github.com/darrachequesne/spring-data-jpa-datatables
- 项目语言：
java
- 项目描述：
spring-data-jpa 和 jquery [datatables](https://www.datatables.net/) 集成工具
- 推荐理由：
极大简化基于 datatables 数据表格的开发
- 示例代码：
```javascript
$(document).ready(function() {
	var table = $('table#sample').DataTable({
		'ajax': {
			'contentType': 'application/json',
			'url': '/data/users',
			'type': 'POST',
			'data': function(d) {
				return JSON.stringify(d);
			}
		},
		...
```

```java
// and server-side becomes
@JsonView(DataTablesOutput.View.class)
@RequestMapping(value = "/data/users", method = RequestMethod.POST)
public DataTablesOutput<User> getUsers(@Valid @RequestBody DataTablesInput input) {
	return userRepository.findAll(input);
}
```

- 截图：
![image](https://user-images.githubusercontent.com/912902/28905770-5f21eda4-7845-11e7-9d46-adf355617715.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，已成功收录在 [HelloGitHub 第 18 期](https://hellogithub.com/volume/18/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，如果方便可以 Star ⭐️ 本项目，让更多人看到本项目。

**项目非常好用，项目描述详细，手动赞一下。**
