### ISSUE TITLE
PureMusic - 是 难得一见 的 Jetpack MVVM 最佳实践！

### ISSUE THREAD

**Issue by KunMinX** [521xueweihan/HelloGitHub#881]
## 项目推荐
- 项目地址：
https://github.com/KunMinX/Jetpack-MVVM-Best-Practice

- 类别：Java，Android

- 项目描述：
  
是 难得一见 的 Jetpack MVVM 最佳实践！在 蕴繁于简 的代码中，对 视图控制器 乃至 标准化开发模式 形成正确、深入的理解！

&nbsp;

此外，你还可以 从这个开源项目中 获得的内容 包括：

1. 整洁的代码风格 和 标准的资源命名规范。
2. 对 视图控制器 知识点的 深入理解 和 正确使用。
3. AndroidX 和 Material Design 2 的全面使用。
4. ConstraintLayout 约束布局的最佳实践。
5. **优秀的 用户体验 和 交互设计**。
6. 绝不使用 Dagger，绝不使用奇技淫巧、编写艰深晦涩的代码。
7. One more thing.

- 推荐理由：

本人拥有 3 年的 移动端架构 践行和设计经验，领导团队重构的 中大型项目 多达十数个，对 Jetpack MVVM 架构在 确立规范化、标准化 开发模式 以 **减少不可预期的错误** 所作的努力，有着深入的理解。

在这个案例中，我将为你展示，Jetpack MVVM 是如何 **蕴繁于简** 地 将原本十分容易出错、一出错就会耽搁半天时间的开发工作，通过 寥寥的几行代码 轻而易举地完成。😉

|                  是让人 爱不释手 的 交互设计！                   |                     是 连贯 的 用户体验                      |                    唯一可信源 的 统一分发                    |
| :----------------------------------------------------------: | :----------------------------------------------------------: | :----------------------------------------------------------: |
| ![1231111323.gif](https://upload-images.jianshu.io/upload_images/57036-0a5cdc68f003211a.gif) | ![222.gif](https://upload-images.jianshu.io/upload_images/57036-2b21db531e51ff03.gif) | ![333.gif](https://upload-images.jianshu.io/upload_images/57036-9a541148ce5bed2e.gif) |

**Comment by 521xueweihan** [comment]
@KunMinX 您好，请按照要求填写，修改后 @我

**Comment by KunMinX** [comment]
@521xueweihan

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
