### ISSUE TITLE
GSYVideoPlayer

### ISSUE THREAD

**Issue by hellowHuaairen** [521xueweihan/HelloGitHub#883]
## 项目推荐
- 项目地址：https://github.com/CarGuo/GSYVideoPlayer

- 类别：Java

- 项目描述：
视频播放器（IJKplayer、ExoPlayer、MediaPlayer），HTTPS，支持弹幕，支持滤镜、水印、gif截图，片头广告、中间广告，多个同时播放，支持基本的拖动，声音、亮度调节，支持边播边缓存，支持视频自带rotation的旋转（90,270之类），重力旋转与手动旋转的同步支持，支持列表播放 ，列表全屏动画，视频加载速度，列表小窗口支持拖动，动画效果，调整比例，多分辨率切换，支持切换播放器，进度条小窗口预览，列表切换详情页面无缝播放，rtsp、concat、mpeg。

- 推荐理由：功能强大，使用文档很详细。
1、打开一个播放(旋转、镜像、填充)
2、列表/详情模式(动画、旋转、小窗体)
3、弹幕
4、滤镜和GL动画
6、背景铺满模糊播放
7、进度条小窗口预览

**Comment by 521xueweihan** [comment]
该项目以推荐过
