### ISSUE TITLE
Dapps - 是一个跨平台的应用商店，包含众多软件

### ISSUE THREAD

**Issue by wallace5303** [521xueweihan/HelloGitHub#884]
## 项目推荐
- 项目地址：https://github.com/wallace5303/dapps

- 类别：JS

- 项目描述：
它是一个应用程序商店，包含丰富的软件，因为基于docker，使你本机电脑有云开发的效果。 一键安装程序；多版本共存，完善的使用说明，且不影响本机环境。 前端、服务端、运维、站长可以直接使用，效率提高非常多。普通用户亦可使用其中部分软件。

- 推荐理由：
1. 一键安装程序；多版本共存
2. 支持系统版本：Linux、MacOs、Windows
3. 开源中国最有价值项目

- 部分软件：
AriaNg高速下载器、wordpress、mysql、redis、PHP、nginx、百度网盘web版、等......

- 截图：
    ![](https://camo.githubusercontent.com/d37001d51fa291a40a0edf5ba41471305cc8b10a/68747470733a2f2f692e6c6f6c692e6e65742f323031392f31302f32362f664c6d71746550624148466e6b736c2e706e67)
    ![](https://camo.githubusercontent.com/e87b20076dc04ddbaaaffc2e79b5e2e09edf0c1f/68747470733a2f2f692e6c6f6c692e6e65742f323031392f31302f32362f6a536354703444434b524d666f626b2e706e67)
    ![](https://camo.githubusercontent.com/7ac1ffeddac7637fb5b5051210cccd94b03f650d/68747470733a2f2f692e6c6f6c692e6e65742f323031392f31302f31312f795743493854515265414d736470422e706e67)
    ![](https://camo.githubusercontent.com/607bc578e62aae54116bd4b49f814aac6d65a7de/68747470733a2f2f692e6c6f6c692e6e65742f323031392f31312f30342f526f784f434e6e5745646148464c772e706e67)

## 开始使用

```
# 下载
git clone https://gitee.com/wallace5303/dapps.git

# 安装
cd dapps
npm install --registry=https://registry.npm.taobao.org

# 启动
npm run start
```

**Comment by 521xueweihan** [comment]
给我点时间，我需要理解和使用一下哈～

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
