### ISSUE TITLE
推荐pycorrector

### ISSUE THREAD

**Issue by shibing624** [521xueweihan/HelloGitHub#885]
## 项目推荐
- 项目地址：https://github.com/shibing624/pycorrector

- 类别：请从中选择Python

- 项目后续更新计划：
1.优化识别效果和速度
2.深度学习模型的gpu支持。

- 项目描述：
  - 必写：中文纠错项目
  

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？
1. 首次支持中文纠错的工具。
2.传统方法和深度方法相结合，作者是百度高T。nlp算法知识点应用多。

**Comment by 521xueweihan** [comment]
您好，可以多写一些项目描述，帮助读者和审核者更快的了解您的项目

**Comment by 521xueweihan** [comment]
24 小时后，如还未回复本 issues 将被关闭
