### ISSUE TITLE
SpringCloud脚手架

### ISSUE THREAD

**Issue by hellowHuaairen** [521xueweihan/HelloGitHub#886]
## 项目推荐
- 项目地址：https://github.com/zhoutaoo/SpringCloud

- 类别：Java

- 项目描述：基于SpringCloud2.1的微服务开发脚手架，整合了spring-security-oauth2、nacos、feign、sentinel、springcloud-gateway等。服务治理方面引入elasticsearch、skywalking、springboot-admin、zipkin等

- 推荐理由：快速搭建环境，专注进入业务开发，而不需过多时间花费在架构搭建上。并且项目持续更新中。

- 截图：
用户管理
![image](https://user-images.githubusercontent.com/19610305/68300525-e7cb0780-00d8-11ea-9741-d097c4e06ce2.png)
API文档
![image](https://user-images.githubusercontent.com/19610305/68300569-029d7c00-00d9-11ea-89b1-48c17ef5ab5a.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏
