### ISSUE TITLE
现代 JavaScript 教程，以最新 JavaScript 标准为基准的权威教程，React 官方文档推荐

### ISSUE THREAD

**Issue by leviding** [521xueweihan/HelloGitHub#889]
## 项目推荐

- 项目地址：https://github.com/javascript-tutorial/zh.javascript.info

- 类别：JavaScript、书籍

- 项目后续更新计划：以最新的 JavaScript 标准为基准，实时更新教程内容，保证它是最现代的 JavaScript 教程。

- 项目描述：
  - 必写：以最新的 JavaScript 标准为基准。通过简单但足够详细的内容，讲解从基础到高阶的 JavaScript 相关知识，旨在帮助初中级前端提升 JavaScript 等前端技术水平。现存唯一一个现代的 JavaScript 教程。
  - 可选：适用于初中级前端开发工程师和相要学习前端的人，以最新的 JavaScript 标准为基准。通过简单但足够详细的内容，为你讲解从基础到高阶的 JavaScript 相关知识。
  - 描述长度（不包含示例代码）: 《现代 JavaScript 教程》是 [React 官方文档推荐，与 MDN 并列](https://zh-hans.reactjs.org/docs/getting-started.html#javascript-resources)的 JavaScript 学习教程，以最新的 JavaScript 标准为基准。通过简单但足够详细的内容，为你讲解从基础到高阶的 JavaScript 相关知识。旨在帮助初中级前端提升 JavaScript 等前端技术水平。

- 推荐理由：《现代 JavaScript 教程》是 [React 官方文档推荐，与 MDN 并列](https://zh-hans.reactjs.org/docs/getting-started.html#javascript-resources)的 JavaScript 学习教程，旨在帮助初中级前端提升 JavaScript 等前端技术水平。此外，[阮一峰](https://github.com/ruanyf/free-books#web-%E5%BC%80%E5%8F%91)和 [justjavac](https://github.com/justjavac/free-programming-books-zh_CN#javascript) 等前端大佬也在 GitHub 上推荐了本教程。

- 截图：

![](https://user-images.githubusercontent.com/26959437/68352167-8c346480-0140-11ea-9827-92a00e2bf7fa.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by leviding** [comment]
谢谢 👍

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 44 期](https://hellogithub.com/periodical/volume/44/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

**Comment by leviding** [comment]
谢谢你们，我会持续关注项目，并推荐给小伙伴儿的~
