### ISSUE TITLE
python爬虫代理IP池

### ISSUE THREAD

**Issue by jhao104** [521xueweihan/HelloGitHub#89]
## 项目推荐
- 项目名称：
  爬虫代理IP池
- 项目地址：
  https://github.com/jhao104/proxy_pool
- 项目语言：
  Python
- 项目描述：
  基于Python的自建代理IP池服务，通过网络爬虫不断抓取互联网上免费的代理IP，本地实时校验剔除失效的代理IP。保证每个代理高可用，从而实现一个时时有代理IP可用的池。最后通过Flask以API的形式对外部提供代理IP服务，包括代理池刷新、无效代理删除、代理获取等接口。从而实现爬虫模块和代理模块分离，更好的为爬虫程序服务。
- 推荐理由：
  功能上: 时时提供免费代理IP，为爬虫工程师解决反爬这一大难题；
  代码上: 设计文档详细，模块结构简明易懂，同时也是爬虫初学者的的练手项目。
- 示例代码：
```
import requests

def get_proxy():
    return requests.get("http://127.0.0.1:5000/get/").content

def delete_proxy(proxy):
    requests.get("http://127.0.0.1:5000/delete/?proxy={}".format(proxy))

# your spider code

def spider():
    # ....
    requests.get('https://www.example.com', proxies={"http": "http://{}".format(get_proxy())})
    # ....
```
- 截图：
![](https://camo.githubusercontent.com/583fcc7cd62289814f86f52a0152835b11802979/68747470733a2f2f706963322e7a68696d672e636f6d2f76322d66323735366461323938366161386138636162316639353632613131356235355f622e706e67)

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功收录**在 [HelloGitHub 第 17 期](https://github.com/521xueweihan/HelloGitHub/blob/master/content/17/HelloGitHub17.md)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，如果方便可以 Star ⭐️ 本项目，让更多人看到本项目。
