### ISSUE TITLE
【自荐】pytest 官方文档的翻译和拓展

### ISSUE THREAD

**Issue by luizyao** [521xueweihan/HelloGitHub#890]
## 项目推荐
- 项目地址：https://github.com/luizyao/pytest-chinese-doc

- 类别：其它

- 项目后续更新计划：项目分支名对应`pytest`版本，目前版本为`5.1.3`

- 项目描述：
  `pytest`自动化测试框架的[官方文档（5.1.3版本）](https://docs.pytest.org/en/5.1.3/contents.html)的中文翻译，但不仅仅是简单的翻译：
    - 更多的示例，所有的示例代码都在`docs/`目录下，以章节划分，尽量覆盖每个知识点；
    - 更多的拓展阅读，添加了学习时所查阅的资料、阅读的源码等，也是作者学习和思考的历程；
  

- 推荐理由：
    - 知识点覆盖广，可以作为工具书来使用；
    - 使用`pipenv`虚拟环境，方便练习；
    - 对英文不好的同学是一个新的学习途径；

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by luizyao** [comment]
谢谢

**Comment by luizyao** [comment]
是忘了吗？⊙﹏⊙

**Comment by 521xueweihan** [comment]
咳咳咳。。。是我忘记标标签了，导致漏了。我的问题，对不起只能下期发布了😅

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 45 期](https://hellogithub.com/periodical/volume/45/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
