### ISSUE TITLE
BigData-Notes

### ISSUE THREAD

**Issue by hellowHuaairen** [521xueweihan/HelloGitHub#895]
## 项目推荐
- 项目地址：https://github.com/heibaiying/BigData-Notes

- 类别：Java

- 项目后续更新计划：作者持续更新中。

- 项目描述：数据学习笔记。

- 推荐理由：作者整理和很详细的大数据的学习笔记，并且都是实战项目。要学习大数据的你不用错过。

- 截图：
大数据处理流
![image](https://user-images.githubusercontent.com/19610305/68484726-cb65d100-0278-11ea-942a-30c9e8798cbb.png)

作者满满的笔记。

![image](https://user-images.githubusercontent.com/19610305/68485030-6d85b900-0279-11ea-8578-6a307140ee8b.png)

**Comment by 521xueweihan** [comment]
https://github.com/heibaiying/BigData-Notes

该项目已收录过
