### ISSUE TITLE
现代 C++ 教程 - 高速上手 C++ 11/14/17/20

### ISSUE THREAD

**Issue by ChungZH** [521xueweihan/HelloGitHub#896]
## 项目推荐
- 项目地址：https://github.com/changkun/modern-cpp-tutorial

- 类别：书籍

- 项目后续更新计划：

- 项目描述：如果你是熟悉传统 C++，渴望在短时间内迅速了解现代 C++ 特性的人，或是想要学习现代 C++ **黑魔法**的人，那么你非常适合阅读此书。本书号称『高速上手』，从内容上对二十一世纪二十年代之前产生 C++ 的相关特性做了非常相对全面的介绍。同时，本书在介绍这些特性的过程中，尽可能简单明了的介绍了这些特性产生的历史背景和技术需求，这为理解、运用这些特性提供了很大的帮助。

- 推荐理由：可以高速上手现代 C++！

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

**Comment by 521xueweihan** [comment]
该项目已推荐过
