### ISSUE TITLE
[自荐] Selenium IDE 相关的资料

### ISSUE THREAD

**Issue by wangding** [521xueweihan/HelloGitHub#9]
Selenium IDE 录制的自动化测试脚本仓库：https://github.com/wangding/seIDE
Selenium IDE 官方文档资料的翻译：https://github.com/wangding/SeleniumIDEDoc

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

如您推荐的项目在《HelloGithub》月刊中推荐，则会同时写明推荐人。

再次感谢您对《HelloGithub》项目的支持！

**Comment by 521xueweihan** [comment]
不好意思，请重新[创建 issues](https://github.com/521xueweihan/HelloGitHub/issues/new)，根据推荐项目的模版，规范推荐项目格式、完善信息。
