### ISSUE TITLE
MQTTX -- 一款跨平台的 MQTT 桌面客户端

### ISSUE THREAD

**Issue by ysfscream** [521xueweihan/HelloGitHub#906]
## 项目推荐
- 项目地址：[https://github.com/emqx/MQTTX](https://github.com/emqx/MQTTX)

- 类别：JS

- 项目描述：
  - MQTTX 是 EMQ 开源的一款跨平台 MQTT 桌面客户端，它支持 macOS, Linux, Windows。采用了聊天界面形式，简化了页面操作逻辑，方便用户快速测试 MQTT/MQTTS 连接，及 MQTT 消息的发布与订阅。
  - 适用于正在搭建自己的 MQTT 的消息服务器的用户测试连接，或者是正在开发或研究 MQTT broker 的用户，对于刚了解或接触学习 MQTT 的用户，可以快速理解该协议知识。项目采用 Vue + TypeScript + Electron，也可用作前端项目的学习和讨论。

- 项目后续更新计划：
后续还将支持 Websocket 的单双向连接，继续添加和优化一些新的交互逻辑，可以对 MQTT Broker 进行简单的监控反馈。

- 推荐理由：
  1. 现已支持多种 MQTT broker 的连接测试
  2. 连接，消息的订阅发布采用聊天界面，交互流程简单易懂
  2. 由 [EMQ](https://github.com/emqx/emqx) 开源社区开发和维护

- 截图：
![image](https://user-images.githubusercontent.com/21299158/69301110-1e179380-0c50-11ea-808b-351576bf5842.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
