### ISSUE TITLE
Sourcetrail

### ISSUE THREAD

**Issue by ListenLove** [521xueweihan/HelloGitHub#907]
## 项目推荐
- 项目地址：[https://github.com/CoatiSoftware/Sourcetrail](https://github.com/CoatiSoftware/Sourcetrail)  

- 类别：C++

- 项目描述：
  - 必写：
    Sourcetrail是一个：
    - 免费且开源、跨平台的可视化源码探索项目。 
    - **能够十分高效的帮助它使用者探索和熟悉陌生的代码**。
    - 支持离线运行，支持**C**, **C++**, **Python**和**Java**。
    - 同时提供了相关SDK用于编写拓展来支持其他语言，相信在未来会提供更多语言的支持。
    - 提供了链接至IDEA、CLion、Sublime Text 3等IDE或编辑器的功能，能够在点击之后快速跳转至相关代码处进行修改。
    - 项目地址官网提供了相关平台的安装包进行下载安装，安装过程十分简单！
  - 可选：用于浏览和探索陌生源码，程序员在它的帮助下可以快速熟悉陌生项目、学习开源项目、框架等。
  - 推荐理由：Sourcetrail在帮助我熟悉陌生项目方面十分高效，以后睡前抱着我的小本本，鼠标点一点，像看网页内容一样看Linux内核的梦想可能就要成真了😂。

- 示例代码：
 无
- 截图：
![image](https://user-images.githubusercontent.com/35055116/69334213-3958c200-0c95-11ea-9f22-dbbcfe6cb68b.png)

**Comment by ListenLove** [comment]
格式折腾了好久，整的还是不好看，不过项目是好项目的！我今天用了一下，美观大方、流畅顺滑、真心好用！

**Comment by 521xueweihan** [comment]
@ListenLove 辛苦您了，写的已经非常好了。

**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 44 期](https://hellogithub.com/periodical/volume/44/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
