### ISSUE TITLE
一个基于wxpython和opencv的视觉算法演示程序

### ISSUE THREAD

**Issue by Laser0v0** [521xueweihan/HelloGitHub#910]
## 项目推荐
- 项目地址：
[picView](https://github.com/Laser0v0/picView)
- 类别：Python

- 项目后续更新计划：
增加更多的机器视觉算法实时显示接口以及一些必要的注释

- 项目描述：
  - 必写：

基于wxpython和opencv的视觉算法演示框架，包括文件（图片、视频）、摄像头和训练（后续提供）三种模式，提供视觉算法验证接口。

- 能够让初学者学到:
   > 闭包与回调函数的概念
   >opencv摄像头捕获、一些基本的图像算法
   >wxpython中的线程通信、文件读取与保存、一些基本控件

- 推荐理由：
可以直观地表现出图像处理算法的效果。

- 示例代码：（可选）长度：1-20 行
```
#叠加模式下的函数复合
def comDef(defList):
    if len(defList)>2:
        return comDef([defList[0]]+comDef(defList[1:]))
    elif len(defList) == 1:
        return defList
    else:
        return [lambda x : defList[0](defList[1](x))]
```
- 截图:

![卷积模式](https://raw.githubusercontent.com/Laser0v0/picView/master/img/test1.PNG)
![验证拉普拉斯算子](https://raw.githubusercontent.com/Laser0v0/picView/master/img/test2.PNG)
![拉普拉斯算子加人脸识别](https://raw.githubusercontent.com/Laser0v0/picView/master/img/test3.PNG "拉普拉斯算子加人脸识别")

**Comment by 521xueweihan** [comment]
您好，项目我看过了。很好的实践项目，但是项目的结构不符合优秀开源项目的标准。
1. 项目的依赖（requirements.txt）
2. 运行步骤、项目介绍、功能介绍

项目开源出来是要让大家参与、使用、反馈。你如果只是这样把项目开源出来，大家是没法体验你的项目的精彩之处的。

欢迎修改、优化以上几点后重新提交～
