### ISSUE TITLE
自荐一个新项目：印象笔记网页版插件

### ISSUE THREAD

**Issue by topcss** [521xueweihan/HelloGitHub#912]
## 项目推荐
- 项目地址：https://github.com/topcss/EvernoteExtension
- 类别：Javascript

- 项目后续更新计划：
已经很好用了，会持续更新。

- 项目描述：
将印象笔记网页版的编辑功能提高了不只一个 level。
印象笔记用户群友反馈说： **这些搞前端的太凶残了。**

### 目前解决了哪些问题（新功能）：
1. 温饱问题
撤销、重做、清除格式、格式刷、设置标题等

2. 小康问题
字数统计、导出图片、预览文档、突出显示等

3. 幸福问题
支持微信QQ截图了，直接粘贴。对，不需要把图片当附件上传了。

**Comment by 521xueweihan** [comment]
有意思的项目，是为了解决痛点而开发的项目。👍👍👍赞

但是这个项目我看过后，发现只是一个使用说明。没有代码，可以考虑把代码开源出来、或者做成 chrome 插件之类的。便于大家一起维护和共享～

嗯，HelloGitHub 月刊暂时就不收录 EvernoteExtension 这个项目了。

**Comment by topcss** [comment]
有源代码，请看 gh-pages 分支。参照 github 的推荐用法。
