### ISSUE TITLE
uform推荐

### ISSUE THREAD

**Issue by janryWang** [521xueweihan/HelloGitHub#914]
## 项目推荐
- 项目地址：
github.com/alibaba/uform
- 类别：
  - JS
- 项目后续更新计划：
  - 建立表单生态，开发者工具，可视化表单构建工具，智能表单生成器
- 项目描述：
  - 一款面向企业级复杂场景的高性能表单解决方案

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？
  - 阿里巴巴集团标准表单解决方案
  - 高性能表单，动态Schema渲染
 
- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

## 提示（提交时请删除以下内容）
> 点击上方 “Preview” 更方便地阅读以下内容，

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！

**Comment by 521xueweihan** [comment]
@janryWang 您好，请按照要求提交项目。

注：项目地址要完整，否则会被认为是恶意提交

**Comment by 521xueweihan** [comment]
@janryWang 完整的地址是要带 https://
