### ISSUE TITLE
短网址应用设计原理 + 源码 + Demo

### ISSUE THREAD

**Issue by Youthink** [521xueweihan/HelloGitHub#918]
## 项目推荐
- 项目地址：https://github.com/Youthink/short_url

- 类别：其它/ Elixir

- 项目后续更新计划：代码优化

- 项目描述：
  - 是 Elixir 语言开发的支持自定义短码的短链接服务。
  - 长网址转换成短链接。新手可以参考源码和[原理解析](https://hufangyun.com/2017/short-url/)实现一个短链接服务或者学习 elixir 开发一个 web 服务。

- 推荐理由：
  - Elixir 语言实现的短链接服务。
  - 代码开源、附带实现过程 [短网址(short URL)系统的原理及其实现](https://hufangyun.com/2017/short-url/) ，可以参照本文的原理介绍，很容易实现一个其他编程语言的短链接服务。

- [预览地址](https://fearless-trustworthy-aidi.gigalixirapp.com/)

- 截图：

![image](https://user-images.githubusercontent.com/9588284/69772132-187afa00-11ca-11ea-9a5f-4aee0963da7e.png)

**Comment by 521xueweihan** [comment]
@Youthink 您好，由于 HG 月刊的分类还不支持那么多语言，所以只能把您的项目归于 其它分类了，望您理解。

增加分类的时候我会推进的。

**Comment by Youthink** [comment]
@521xueweihan 好的，好的。

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 45 期](https://hellogithub.com/periodical/volume/45/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
