### ISSUE TITLE
推荐项目申请：xmake - 一个基于Lua的轻量级跨平台自动构建工具

### ISSUE THREAD

**Issue by waruqi** [521xueweihan/HelloGitHub#919]
## 项目推荐
- 项目地址：https://github.com/xmake-io/xmake

- 类别：c

- 项目后续更新计划：

  * 远程编译支持
  * 分布式编译支持

- 项目描述：

xmake是一个基于Lua的轻量级跨平台自动构建工具，支持在各种主流平台上构建项目，主要用于解决C/C++项目的跨平台构建，同时支持与其他语言的混合编译支持。

工程配置语法简单易读，对初学者友好，快速上手。

- 推荐理由：

  * 远程依赖包管理支持，内建自有仓库以及分布式私有仓库支持，解决c/c++依赖管理问题
  * 操作方便易上手，工程描述简单易读，提升开发者维护构建项目的效率
  * 构建，打包，安装，运行流程操作一体化
  * 丰富的插件扩展
  * 灵活的脚本定制化
  * 与vscode/idea/clion/sublime/vs等IDE和编辑器的高度集成
  * 多语言、多平台支持
  * 完善的中英文文档：https://xmake.io/

- 示例代码：

```lua
add_requires("libuv master", "ffmpeg", "zlib 1.20.*", "tbox >1.6.1")
target("test")
    set_kind("shared")
    add_files("src/*.c")
    add_packages("libuv", "ffmpeg", "tbox", "zlib")
```

- 截图：

![](https://camo.githubusercontent.com/f2450894d57dd7e419e41e7e855ee11de02616fe/68747470733a2f2f786d616b652e696f2f6173736574732f696d672f696e6465782f7061636b6167655f6d616e6167652e706e67)

![](https://camo.githubusercontent.com/36d51f121c7688de9b59c64328c819882849efbb/68747470733a2f2f786d616b652e696f2f6173736574732f696d672f696e6465782f7061636b6167655f617263682e706e67)

**Comment by 521xueweihan** [comment]
@waruqi 您好：请把提示性文字删除后 @我

**Comment by waruqi** [comment]
@521xueweihan 删了

**Comment by 521xueweihan** [comment]
@waruqi 收到～

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by waruqi** [comment]
谢谢

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 45 期](https://hellogithub.com/periodical/volume/45/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）

**Comment by waruqi** [comment]
谢谢，已加申请
