### ISSUE TITLE
远程 Headless Chrome 控制库

### ISSUE THREAD

**Issue by xcyf008** [521xueweihan/HelloGitHub#93]
## 项目推荐
- 项目名称：
puppeteer

- 项目地址：
https://github.com/GoogleChrome/puppeteer

- 项目语言：
JavaScript

- 项目描述：
Puppeteer 是 Google Chrome 团队开源的面向 Node.js 的，基于 DevTools 协议的远程 Headless Chrome 控制库，它可以生成网页截图、PDF、抓取单页应用与网页内容、进行自动化表单提交、界面测试与模拟键盘输入等功能

- 推荐理由：
可以用于自动化测试

- 示例代码：
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({path: 'example.png'});

  browser.close();
})();

- 截图：

### 编辑完推荐项目的信息，下述提示信息**请删除**
非常感谢推荐这么好的项目

如您推荐的项目收录到《HelloGitHub》月刊，您的GitHub帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/contributors.md)，**同时会在此 issues 中通知您**。

再次感谢您对《HelloGitHub》项目的支持！

HelloGitHub 网站：https://hellogithub.com

**Comment by 521xueweihan** [comment]
您推荐的项目，已成功收录在 [HelloGitHub 第 18 期](https://hellogithub.com/volume/18/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，如果方便可以 Star ⭐️ 本项目，让更多人看到本项目。

**Comment by xcyf008** [comment]
开心，哈哈
从这个期刊里已经发现不少有意思的项目了
