### ISSUE TITLE
openwebflow

### ISSUE THREAD

**Issue by hellowHuaairen** [521xueweihan/HelloGitHub#931]
## 项目推荐
- 项目地址：https://github.com/bluejoe2008/openwebflow

- 类别：Java

- 项目描述：基于Activiti的工作流引擎扩展，接管了Activiti对活动权限以及用户表的管理，并提供了催办、代办、加签（包括前加签/后加签）、自由跳转、分裂节点等功能

- 推荐理由：彻底满足“中国特色”，并提供了安全的（同时也是优雅的）催办、代办、加签（包括前加签/后加签）、自由跳转（包括前进/后）、分裂节点等功能

- 截图：

![image](https://user-images.githubusercontent.com/19610305/69871580-232eaf80-12ee-11ea-896d-9f2190134b80.png)

**Comment by 521xueweihan** [comment]
@hellowHuaairen 描述改成通俗易懂的描述，
