### ISSUE TITLE
GF(Go Frame)

### ISSUE THREAD

**Issue by mingzaily** [521xueweihan/HelloGitHub#938]
## 项目推荐
- 项目地址：https://github.com/gogf/gf

- 类别：Go

- 项目后续更新计划：~

- 项目描述：
  - 必写：
    -  GF(Go Frame)是一款模块化高性能、生产级Go应用开发框架
    - 提供了常用的核心开发组件，如：缓存、日志、文件、时间、队列、数组、集合、字符串、定时器、命令行、文件锁、内存锁、对象池、连接池、资源管理、数据校验、数据编码、文件监控、定时任务、数据库ORM、TCP/UDP组件、进程管理/通信、 并发安全容器等等。
    - 模块化、松耦合设计；模块丰富，开箱即用；作者是国人，本地化支持，封装狂魔
  - 适用于快速web开发
  - 描述长度（不包含示例代码）: 蛮方便的一款框架，相比常用的gin有更多的组件

- 推荐理由：
  - 方便快捷
  - issue活跃
  - 不错的框架

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 45 期](https://hellogithub.com/periodical/volume/45/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
