### ISSUE TITLE
redis管理平台Repoll

### ISSUE THREAD

**Issue by NaNShaner** [521xueweihan/HelloGitHub#939]
## 项目推荐
- 项目地址：https://github.com/NaNShaner/repoll

- 类别：python

- 项目后续更新计划：
- [x] 支持哨兵模式和集群模式
- [ ] 监控独立展示，包括qps、内存使用率、客户端链接以及慢查询等
- [ ] 支持web console
- [ ] 提供新建、下线、实例列表查询等API接口

- 项目描述：
  - 必写：该项目主要用于集中管理公司内部的redis集群，是一个redis的运维门户平台，包括标准化申请流程、统一redis配置及版本、统一监控并提供API接口用于打通公司内部的cmdb或现有告警上报功能等
  - 可选：项目用django2.0编写，一方面可以了解django的项目开发，另一方可以帮助了解redis的运维管理

- 推荐理由：redis运维管理门户，解放运维人员的痛苦，赋能开发

- 截图：
![image](https://github.com/NaNShaner/repoll/blob/master/images/login.png?raw=true)

**Comment by 523144419** [comment]
和cachecloud很像啊？django版本？啥时候release？

**Comment by NaNShaner** [comment]
差不多，会一些api接口帮助对接公司内部的上下游运维系统。现在还在码功能，release还要一段时间

**Comment by 521xueweihan** [comment]
@NaNShaner 感谢推荐项目，建议出了 release 版本再推荐。该项目暂不收录到月刊中，谢谢您的支持。
