### ISSUE TITLE
golang gorm 数据库映射工具 

### ISSUE THREAD

**Issue by xxjwxc** [521xueweihan/HelloGitHub#940]
## 项目推荐
- 项目地址：https://github.com/xxjwxc/gormt

- 类别：Go

- 项目后续更新计划：加入相关快捷函数(OrmFunc)

- 项目描述：
  - 必写：mysql数据库转 struct 工具,可以将mysql数据库自动生成golang sturct结构，带大驼峰命名规则，带json标签，支持外键，注释导出
  - 可选：数据库映射工具

- 推荐理由：gorm 需要手动写orm映射对象。通过此工具可以自动从数据库中捞取

- 示例代码：
// UserAccountTbl 用户账号
type UserAccountTbl struct {
	ID            int    `gorm:"primary_key"`
	Account       string `gorm:"unique"`
	Password      string
	AccountType   int         // 帐号类型:0手机号，1邮件
	AppKey        string      // authbucket_oauth2_client表的id
	UserInfoTblID int         `gorm:"index"`
	UserInfoTbl   UserInfoTbl `gorm:"association_foreignkey:user_info_tbl_id;foreignkey:id"` // 用户信息
	RegTime       time.Time
	RegIP         string
	BundleID      string
	Describ       string
}

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by xxjwxc** [comment]
有什么问题需要改进的吗？

**Comment by 1011875777** [comment]
@xxjwxc 刚学习go，你这个项目和gorm有什么不同之处吗？

**Comment by xxjwxc** [comment]
> @xxjwxc 刚学习 go，你这个项目和 gorm 有什么不同之处吗？

这个是gorm的辅助工具，用于自动生成mysql 数据库到 gorm 结构体的映射工具。

**Comment by 521xueweihan** [comment]
> 有什么问题需要改进的吗？

本期优秀的 go 项目过多，经过慎重思考。您的这个项目被刷下来了，望理解。

**Comment by xxjwxc** [comment]
那等下期我再提交吧。正好我也在更新快捷函数这一块。

**Comment by xxjwxc** [comment]
thx

**Comment by 521xueweihan** [comment]
我有个建议，这个工具是否能够提 pr 合并到 gorm 项目中？

**Comment by xxjwxc** [comment]
> 我有个建议，这个工具是否能够提 pr 合并到 gorm 项目中？

好建议,这个项目已经被收录到gorm社区了。
