### ISSUE TITLE
Holer端口映射软件

### ISSUE THREAD

**Issue by Dom-Wang** [521xueweihan/HelloGitHub#943]
## 项目推荐
- 项目地址：https://github.com/wisdom-projects/holer

- 类别：Go、Java

- 项目后续更新计划：
Holer 1.3版本更新如下特性：
1. 支持UDP协议
2. 支持数据压缩
3. 提升用户体验

- 项目描述：
  - 必写：
Holer是一个将局域网中的应用映射到公网访问的端口映射软件，支持转发基于TCP协议的报文。
解决公网无法访问局域网内的TCP应用。

  - 可选：
用户使用holer实现从公网访问本地TCP应用，也可以学习到GO和Java Netty实现将本地TCP端口映射到公网访问的原理。

  - 描述长度（不包含示例代码）: 10 - 256 个字符

在没有公网IP的NAT网络里的主机上，TCP应用是无法从公网Internet访问到，Holer是一个将局域网中的应用映射到公网访问的端口映射软件，支持转发基于TCP协议的报文。
用到的技术如下：
1. Holer 服务端采用Springboot和Netty实现
2. Holer 客户端采用Java Netty和GO语言实现

- 推荐理由：
Holer可以将局域网中的TCP应用映射到公网Internet上访问。
常用的使用案例如下：
(1). 从公网HTTP/HTTPS访问本地web服务器
(2). 从公网访问本地数据库
(3). 从公网远程桌面到局域网Windows系统
(4). 从公网ssh登录局域网Linux系统

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg
![Holer](http://blog.wdom.net/upload/2019/11/v3sonj7kuogp1orspp1ek7t4jt.png)
![Holer Server](http://blog.wdom.net/upload/2019/04/pnlmngj08sh4eqv8fdb97oto0p.png)
![Holer Client](http://blog.wdom.net/upload/2019/04/1he44jumd2g9no95c6f8fsa5re.png)
![Holer Report](http://blog.wdom.net/upload/2019/04/5atk5j8ii2gl1rqfl3l6672sdq.png)

![Wisdom](http://blog.wdom.net/upload/2019/09/6pb9liclg4jbercad2d4hhnj3j.gif)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by Dom-Wang** [comment]
感谢收录！🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 45 期](https://hellogithub.com/periodical/volume/45/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
