### ISSUE TITLE
gods-pen 高扩展网页制作平台

### ISSUE THREAD

**Issue by jy03078959** [521xueweihan/HelloGitHub#945]
## 项目推荐
- 项目地址：https://github.com/ymm-tech/gods-pen

- 类别：JS

- 项目后续更新计划：

- 项目描述：
    码良是一个`在线生成h5页面并提供页面管理和页面编辑的平台`，用于快速制作H5页面。用户无需掌握复杂的编程技术，通过简单拖拽、少量配置即可制作精美的页面，可用于营销场景下的页面制作。同时，也为开发者提供了`完备的编程接入能力`，通过脚本和组件的形式获得强大的组件行为和交互控制能力。码良的初心是创建一个开源免费的平台,支持公司内部搭建使用

- 推荐理由：功能强大，支持组件，组合组件，脚本，动画等，对开发和营销活动具有非常高扩展性。开源免费，适合搭建内部营销系统，整合到自己的营销流程中。

- 截图：（可选）gif/png/jpg

![](https://ymm-maliang.oss-cn-hangzhou.aliyuncs.com/ymm-maliang/resource/ymm_1570591673129.png)

![](https://ymm-maliang.oss-cn-hangzhou.aliyuncs.com/ymm-maliang/access/ymm_1539761082989.gif)

![](https://ymm-maliang.oss-cn-hangzhou.aliyuncs.com/ymm-maliang/access/ymm_1539760521686.gif)

![](https://ymm-maliang.oss-cn-hangzhou.aliyuncs.com/ymm-maliang/access/ymm_1539760696547.gif)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
月刊篇幅问题，本期暂不发布，望理解。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 46 期](https://hellogithub.com/periodical/volume/46/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。
