### ISSUE TITLE
项目辅助工具-用于失败的http请求重新提交

### ISSUE THREAD

**Issue by jiashaokun** [521xueweihan/HelloGitHub#946]
## 项目推荐
- 项目地址：https://github.com/jiashaokun/go-hreq

- 类别：请从中选择（Go）

- 项目后续更新计划：

- 项目描述：
  - 必写：http请求重新提交，在很多业务项目中遇到请求失败的情况，该工具可将失败的请求重新提交，直到提交次数等于规定次数或者返回结果与规定返回结果匹配才会停止，请求后的数据会被删除，不会产生垃圾数据。
  - 可选：适用于什么场景、能够让初学者学到什么
  - 描述 http请求重新提交，在很多业务项目中遇到请求失败的情况，该工具可将失败的请求重新提交，直到提交次数等于规定次数或者返回结果与规定返回结果匹配才会停止，请求后的数据会被删除，不会产生垃圾数据

- 推荐理由：解决业务中失败请求需要重复提交而重复造轮子的问题

- 示例代码：（可选）长度：1-20 行
//每分钟执行一次
c.AddFunc("*/60 * * * * ?", service.Repre)

for _, v := range fdVal {
	req := pkg.Req{
		Id: v["id"].(string),
		Url: v["url"].(string),
		Info: v["info"].(string),
		Method: v["method"].(string),
		Num: v["num"].(int32),
		Resp: v["resp"].(string),
		ReqNum: v["req_num"].(int32),
	}

	wg.Add(1)
	go func(req *pkg.Req, cn *library.MongoLib) {
		defer wg.Done()
		idx, _ := req.Request()
		req.Do(connect, idx)
	}(&req, connect)
}
wg.Wait()

req := fasthttp.AcquireRequest()
defer fasthttp.ReleaseRequest(req)

- 截图：（可选）gif/png/jpg
![image](https://user-images.githubusercontent.com/9696062/70294379-3544ac80-181e-11ea-94bd-e10515f9cdbe.png)

**Comment by 521xueweihan** [comment]
您好，很有意思的项目。但还有优化和提高的空间，建议持续迭代项目。
1. 实现的方法和逻辑（要让人一目了然，图）
2. 支持多种方式使用（不依赖外部服务）
3. 能够试用更多场景（具有推广性）
