### ISSUE TITLE
Amazing Apps

### ISSUE THREAD

**Issue by Rictusempra** [521xueweihan/HelloGitHub#95]
- 项目地址：
http://amazingapps.org/
- 项目语言：
markdown 文档
- 项目描述：
awesome lists
- 推荐理由：
人工审核的应用列表

**Comment by 521xueweihan** [comment]
@EMLVIRUS 
Awesome project! 关于推荐有一下几点建议。
1. 经过浏览我发现后面会有不同的系列，所以先会推荐 `Amazing-Windows-Apps` 系列，后面其他系列完成，欢迎告知。

2. 因为本项目是 HelloGitHub，所以只推荐 GitHub 上的项目。所以我找到 `Amazing-Windows-Apps` 项目的 GitHub 地址：https://github.com/AmazingApps/Amazing-Windows-Apps ，望以后推荐时请附上 GitHub 的项目地址。

3.  项目描述可以丰富一些。

😄

**Comment by EMLVIRUS** [comment]
@521xueweihan https://github.com/AmazingApps/Organization-Wiki
我的锅，忘了贴wiki了

**Comment by EMLVIRUS** [comment]
忘了说了，之前是一直是有README的，也就是在gitbook阅读时的首页。
后来分离语言，就只有LANG.md了，而且该文件内多余内容会被gitbook无视，也就成了现在的样子

**Comment by 521xueweihan** [comment]
@EMLVIRUS 嗯，我是看到了 gitbook 的介绍。我的出发点可能是从 github 项目出发，github 项目也是可以带来很多的阅读量。如果一个项目没有描述，虽然我可能可以根据 project name 猜出它是干什么的，但是我可能并不会 进一步的去了解该项目。

以上是出于希望更多人可以发现你的项目，提出的个人建议。

PS：关于项目描述，github 给出两种方案：README、wiki

- [Documenting your projects on GitHub](https://guides.github.com/features/wikis/)

**Comment by Rictusempra** [comment]
@521xueweihan Username 因某些防GANK原因更改，麻烦删除 @ 内容，感谢

**Comment by 521xueweihan** [comment]
您推荐的项目，已成功收录在 [HelloGitHub 第 19 期](https://hellogithub.com/volume/19/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，如果方便可以 Star ⭐️ 本项目，让更多人看到本项目。
