### ISSUE TITLE
[自荐项目]A React-based Loading animation component library

### ISSUE THREAD

**Issue by sixiaodong123** [521xueweihan/HelloGitHub#951]
## 项目推荐
- 项目地址：https://github.com/sixiaodong123/react-loading
- 类别：JS

- 项目后续更新计划： 1. 对react-loading组件库中的组件进行分类  2.不断丰富组件库
  

- 项目描述：
 这是一个基于React的Loading动画组件库,可以用于异步请求时的Loading动画。react-loadingg这个动画组件库支持丰富的api以及按需加载。 

- 推荐理由：react-loadingg这个动画组件库光滑轻量并且默认完全居中开箱即用,支持丰富的api以及按需加载。 

- 示例代码：
```  
       import React from 'react';
       import { DisappearedLoading } from 'react-loadingg';
       const Container = () => <DisappearedLoading />;
       export default Container;  
```

- 截图：
![react-loading](https://user-images.githubusercontent.com/30104912/70386027-e1c59080-19ce-11ea-9c75-db6a01ee8c28.gif)

**Comment by sixiaodong123** [comment]
![home](https://user-images.githubusercontent.com/30104912/70866346-7158d980-1fa3-11ea-8d2d-1c7f920e4605.gif)

**Comment by 521xueweihan** [comment]
好看！

**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by sixiaodong123** [comment]
谢谢大佬~.我会不断完善该项目的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"削微寒"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月18日(星期三) 下午5:52
收件人:&nbsp;"521xueweihan/HelloGitHub"<HelloGitHub@noreply.github.com&gt;;
抄送:&nbsp;"天天吃肉长不胖"<3450236968@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [521xueweihan/HelloGitHub] [自荐项目]A React-based Loading animation component library (#951)




好看！
 
您推荐的项目已收录到专栏，后续有最新进展会在此 Issues 进行通知。
 欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 45 期](https://hellogithub.com/periodical/volume/45/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
