### ISSUE TITLE
自荐项目「gortal」一个使用 Go 语言开发的，超级轻量的堡垒机（跳板机）服务

### ISSUE THREAD

**Issue by elfgzp** [521xueweihan/HelloGitHub#952]
## 项目推荐
- 项目地址：https://github.com/TNK-Studio/gortal
- 类别：Go
- 项目后续更新计划：
    - 增加文件中专站功能，通过跳板机传输文件
    - 菜单中文
    - UI 优化

- 项目描述：
  - 首先说说为什么想做这个东西，一开始是几个好基友有很多闲置的服务器，都是 1 核 2G 之类的超小配置服务器。然后基友之间想共享出来用，但是要配置公钥私钥啥的，而且部分服务器也不是所有人可见的。
于是乎想到公司在用 jumpserver，是一个开源的堡垒机（跳板机）项目，于是乎想拿来用。
谁知道它的配置要求是 2 核 4 G ... ??? 于是就有了这个项目。
gortal 是使用 Go 语言开发的超轻量跳板机，目前版本的镜像只有 23M，很适合个人和小组织使用。该项目只花了一周多时间开发，可能会有 BUG，不过也欢迎大家来尝试和提 issuse。
- 推荐理由：超级轻量堡垒机（跳板机），docker 镜像只有 20 + M
- 截图：![gortal](https://github.com/TNK-Studio/gortal/raw/master/doc/gortal.gif)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
