### ISSUE TITLE
[自荐] Arya - 在线 Markdown 编辑器

### ISSUE THREAD

**Issue by nicejade** [521xueweihan/HelloGitHub#954]
## 项目推荐
- 项目地址：[nicejade/markdown-online-editor](https://github.com/nicejade/markdown-online-editor)
	- 在线体验：[Arya - 在线 Markdown 编辑器](https://markdown.lovejade.cn)

- 类别：JavaScript, CSS

- 项目后续更新计划：
	- 新增侧边栏文件树；
	- 增加 PPT 预览导出 HTML；
	- 新增“所见即所得”编辑模式；
	- ......

- 项目描述：
	[Arya](https://markdown.lovejade.cn/)，是一款基于 `Vue`、`Vditor`，为未来而构建的在线 Markdown 编辑器；轻量且强大：内置粘贴 HTML 自动转换为 Markdown，支持流程图、甘特图、时序图、任务列表，可导出携带样式的图片、PDF 等。

	通过此项目，初学者可以学习采用 Vue、Webpack 开发（优化） Web 应用（[PWA](https://github.com/nicejade/nice-front-end-tutorial/blob/master/tutorial/pwa-tutorial.md)），以及采取“预渲染”方案来解决 SPA 首屏渲染、SEO 问题等。

- 推荐理由：市面上不乏很多功能强大、体验良好的 Markdown 神器；但或多或少都会存在一些问题，如：功能不全、使用不便、体验不佳，或高级功能收费等；而 Arya 就取了一个折中，功能丰富（可支持多种功能，并且使用方便），同时免费又安全（数据只会在本地进行保存）。了解更多可参见文章：[Arya - 在线 Markdown 编辑器](https://www.jeffjade.com/2019/05/31/155-arya-markdown-online-editor/)。

	- [x] 🎉 通常 `Markdown` 解析器自带的基本功能；
	- [x] 🍀 支持**流程图**、**甘特图**、**时序图**、**任务列表**；
	- [x] 🏁 支持粘贴 HTML 自动转换为 Markdown；
	- [x] 💃🏻 支持插入原生 Emoji、设置常用表情列表；
	- [x] 🚑 支持编辑内容保存**本地存储**，防止意外丢失；
	- [x] 📝 支持**实时预览**，主窗口大小拖拽，字符计数；
	- [x] 🛠 支持常用快捷键(**Tab**)，及代码块添加复制
	- [x] ✨ 支持**导出**携带样式的 PDF、PNG、JPEG 等；
	- [x] ✨ 升级 Vditor，新增对 `echarts` 图表的支持；
	- [x] 👏 支持检查并格式化 Markdown 语法，使其专业；
	- [x] 🦑 支持五线谱、及[部分站点、视频、音频解析](https://github.com/b3log/vditor/issues/117?utm_source=hacpai.com#issuecomment-526986052)；
	- [ ] 🚧 增加对**所见即所得**编辑模式的支持(开发中)；

- 应用截图：

![image](https://user-images.githubusercontent.com/15773463/70392731-0eed5f80-1a1e-11ea-923b-a564a4e8e252.png)

**Comment by 521xueweihan** [comment]
您好，月刊往期已收录过类似的项目，您推荐的项目暂不能收录到月刊中。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
