### ISSUE TITLE
【自荐项目】Vue滑动验证码插件

### ISSUE THREAD

**Issue by monoplasty** [521xueweihan/HelloGitHub#959]
## 项目推荐
- 项目地址：https://github.com/monoplasty/vue-monoplasty-slide-verify

- 类别：JS

- 项目后续更新计划：兼容性更新

- 项目描述：
  - 基于Vue2.0+的验证码插件，移动端适配
  - 用于网页注册或者登录
  - 基于滑动式的验证码，免于字母验证码的繁琐输入
 
- 推荐理由：基于滑动式的验证码，免于字母验证码的繁琐输入

- 示例代码：
 ```javascript
  import Vue from 'vue';
  import SlideVerify from 'vue-monoplasty-slide-verify';

  Vue.use(SlideVerify);

  export default {
        name: 'App',
        data(){
            return {
                msg: '',
            }
        },
        methods: {
            onSuccess(){
                this.msg = 'login success'
            },
            onFail(){
                this.msg = ''
            },
            onRefresh(){
                this.msg = ''
            }
        }
    }
  ```

- 截图：[在线查看demo](https://monoplasty.github.io/vue-monoplasty-slide-verify/)

![预览图](https://img-blog.csdnimg.cn/20181215161401935.png)

**Comment by 521xueweihan** [comment]
JS 项目展示就是方便，可以用 GitHub Pages 预览效果，一目了然～

**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏

**Comment by 521xueweihan** [comment]
月刊篇幅问题，本期暂不发布，望理解。

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 46 期](https://hellogithub.com/periodical/volume/46/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。
