### ISSUE TITLE
基于pytorch的SSD目标检测模型(全中文注释,结构简洁明了,支持多GPU训练)

### ISSUE THREAD

**Issue by yatengLG** [521xueweihan/HelloGitHub#963]
## 项目推荐
- 项目地址：https://github.com/yatengLG/SSD-Pytorch

- 类别：Python

- 项目后续更新计划：后续会支持更多的特征提取网络，完善更多的网络配置。

- 项目描述：
     项目是SSD目标检测模型的pytorch实现版本。适宜新手入门，目标检测任务参考或重用，甚至直接基于本项目实现目标检测任务。
     1.项目在实现时，将数据处理，模型结构，训练、测试、检测流程等单独部分实现，具有非常清晰的结构，也便于代码的重复利于。
     2.项目采用全中文注释，降低了入门难度，便于理解。有较好的readme说明。
     3.训练过程支持多GPU，并多GPU训练环境与单GPU环境训练代码进行了统一，只需一行代码，数个字符的修改即可指定需要使用的设备，且不会对训练结果产生影响。
     4.由于深度学习训练过程较为漫长，项目采用visdom来可视化训练过程，浏览器实时的显示训练过程。
     5. 项目完整性极高，包含了训练，验证，单图检测，视频检测等完整的流程，且配置了完整的一套训练参数。上手及用。

- 推荐理由:
     完整的目标检测项目，结构简洁明了，全中文注释。适宜新手入门，目标检测任务参考或重用，甚至直接基于本项目实现目标检测任务。

- 示例代码：
 **训练过程(只需下列几行代码即可实现)**
```python
   
    # 实例化模型. 模型的具体各种参数在Config文件中进行配置
    net = SSD(cfg)
    # 将模型移动到gpu上,cfg.DEVICE.MAINDEVICE定义了模型所使用的主GPU
    # 模型的参数更新会在主GPU上进行.
    net.to(cfg.DEVICE.MAINDEVICE)

    # 初始化训练器,训练器参数已通过cfg进行配置;也可传入参数进行配置,但不建议
    trainer = Trainer(cfg, max_iter=None, batch_size=None, 
                      train_devices=None, model_save_step=None, 
                      model_save_root=None, vis = None, vis_step=None)
    # 训练器开始在 数据集上训练模型
    trainer(net, train_dataset)
```
- 截图：
![](https://github.com/yatengLG/SSD-Pytorch/blob/master/Images/000531_det.jpg)

**Comment by 521xueweihan** [comment]
有心做的项目值得被更多人知道和发现，希望能够持续更新和维护。加油！

**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 45 期](https://hellogithub.com/periodical/volume/45/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
