### ISSUE TITLE
仿京东 Android 客户端样式的级联地址选择器

### ISSUE THREAD

**Issue by sunshinewei** [521xueweihan/HelloGitHub#97]
## 项目推荐
- 项目名称：JDAddressSelector

- 项目地址：https://github.com/chihane/JDAddressSelector

- 项目语言：java

- 项目描述：仿京东 Android 客户端样式的级联地址选择器

- 推荐理由：可以添加自定义数据源。

- 示例代码：
`dependencies {
    ...
    compile 'com.github.chihane:JDAddressSelector:1.1.4'
}`

- 截图：

### 编辑完推荐项目的信息，下述提示信息**请删除**
非常感谢推荐这么好的项目

如您推荐的项目收录到《HelloGitHub》月刊，您的GitHub帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/contributors.md)，**同时会在此 issues 中通知您**。

再次感谢您对《HelloGitHub》项目的支持！

HelloGitHub 网站：https://hellogithub.com

**Comment by vpjacob** [comment]
能不能帮助我一下，我初学，问题可能出在哪一步。

**Comment by 521xueweihan** [comment]
推荐理由：站在初学者的角度，能够学到写什么？
