### ISSUE TITLE
ASP.NetCore 入门教程

### ISSUE THREAD

**Issue by anjoy8** [521xueweihan/HelloGitHub#970]
## 项目推荐
- 项目地址：https://github.com/anjoy8/Blog.Core

- 类别：C#

- 项目后续更新计划：消息队列、缓存中间件、多库、导出、数据权限、支付等

- 项目描述：
  - ASP.NET Core 2.2/3.1 教程，前后端分离的后端接口，vue教程的姊妹篇，不仅有丰富文档，群社区，更有部分视频讲解，快速搭建前后端分离项目。
  - 适用于任何api项目，跨平台，依赖注入，中间件，AOP，权限管理等

- 推荐理由：本项目从ASP.NET Core基础讲起，涵盖平时日常开发中的基本常见技能，配合vue后台，快速搭建前后端分离项目，同时内置授权管理，可以精确到按钮基本授权控制。
对初学者或者有一定基础但不想造轮子的小伙伴，有很高的利用价值。

- 示例代码：

```
  services.AddMemoryCacheSetup();
  services.AddSqlsugarSetup();
  services.AddDbSetup();
  services.AddAutoMapperSetup();
  services.AddCorsSetup();
  services.AddMiniProfilerSetup();
  services.AddSwaggerSetup();
  services.AddJobSetup();
  services.AddHttpContextSetup();
  services.AddAuthorizationSetup();

  services.AddSignalR().AddNewtonsoftJsonProtocol();

  services.AddScoped<UseServiceDIAttribute>();

```

- 在线Demo：[地址](http://apk.neters.club/index.html)

**Comment by 521xueweihan** [comment]
@anjoy8 项目地址麻烦修改正确，然后 @我

**Comment by anjoy8** [comment]
@521xueweihan 已经修改了，抱歉之前没看清。

**Comment by anjoy8** [comment]
@521xueweihan 您好，还需要其他修改的么

**Comment by 521xueweihan** [comment]
您好，不好意思回复晚了。没有别的问题了，您的项目将出现在下期月刊中。明天处理完成
(づ ●─● )づ

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 45 期](https://hellogithub.com/periodical/volume/45/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
