### ISSUE TITLE
【自荐项目】一款手绘风格组件库

### ISSUE THREAD

**Issue by 5A59** [521xueweihan/HelloGitHub#971]
## 项目推荐
- 项目地址：
https://github.com/m-zylab/SketchyComponent

- 类别：
Kotlin

- 项目后续更新计划：
会不断扩充组件类型。

- 项目描述：
SketchyComponent 是一款 Android 上的手绘风格组件库。也是 Android 平台上第一款手绘风格库（据我所知～）。
SketchyComponent 提供了一些基础图形和 Icon，以及快捷的自定义能力，使用 SketchyComponent 可以轻松的创建手绘风格 APP。  

- 推荐理由：
SketchyComponent 是 Android 平台上第一款（伪）手绘风格的组件库。接入简单，使用方便。

- 示例代码：
1. 添加 jcenter 仓库（AS 创建的项目默认已经添加）
``` gradle
repositories {
    jcenter()
}
```
2. 添加 sketchy 依赖
``` gradle
implementation 'com.zylab:sketchy:0.1.3'
```
3. 使用
``` kotlin
// 1. 创建 Sketchy 图形
val skSquareDrawable = SkSquareDrawable().apply {
    // 2. 设置属性
    fillColor = resources.getColor(android.R.color.holo_orange_dark)
}
// 3. 给 View 设置背景
text.background = skSquareDrawable
```
- 截图： 
![demo](https://github.com/m-zylab/SketchyComponent/blob/master/pics/demo.png)
![demo](https://github.com/m-zylab/SketchyComponent/blob/master/pics/demo1.png)
![demo](https://github.com/m-zylab/SketchyComponent/blob/master/pics/demo2.png)
![demo](https://github.com/m-zylab/SketchyComponent/blob/master/pics/demo3.png)

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 45 期](https://hellogithub.com/periodical/volume/45/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
