### ISSUE TITLE
命令行版音乐下载器SoMusic

### ISSUE THREAD

**Issue by jaydenwen123** [521xueweihan/HelloGitHub#972]
## 项目推荐
- 项目地址：
https://github.com/jaydenwen123/Somusic.git
- 类别：请从中选择（C、C#、C++、CSS、Go、Java、JS、Kotlin、Objective-C、PHP、Python、Ruby、Swift、其它、书籍、机器学习）
**Go**
- 项目后续更新计划：
项目已完成几乎所有的功能，剩下自动播放音乐功能
- 项目描述：
  - 必写：这是个什么项目、能用来干什么、有什么特点或解决了什么痛点
**这是一个Golang开发的结合爬虫技术、命令行版的音乐下载器，支持搜索、并发下载酷狗官网提供的付费歌曲。**
  - 可选：适用于什么场景、能够让初学者学到什么
**对于想熟悉爬虫、学习golang、掌握自己动手开发一款自己的命令行版编辑器非常有学习意义**
  - 描述长度（不包含示例代码）: 10 - 256 个字符
**该项目文档齐全、clone后即可在本地编译运行**

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？
如果你对一直使用的命令行工具比较陌生，它内部的原理是什么？不妨你值得一试
如果你对爬虫比较陌生，不妨你值得一试，本项目所采用的是是kugou的在线地址，通过分析后台接口实现的一个命令行版爬虫音乐下载器

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg
![image](https://user-images.githubusercontent.com/38454179/70964598-6a2aec00-20c7-11ea-9550-4de97a7b8276.png)
![image](https://user-images.githubusercontent.com/38454179/70964290-45824480-20c6-11ea-8d25-085a76ee8a3f.png)
![image](https://user-images.githubusercontent.com/38454179/70964314-5468f700-20c6-11ea-9d24-7e8716c2afe7.png)
![image](https://user-images.githubusercontent.com/38454179/70964583-5a130c80-20c7-11ea-937c-229b5fc605ef.png)

**Comment by 521xueweihan** [comment]
此类项目之前收录过，而且容易收到版权的问题停止维护。所以您的项目**暂时不收录到月刊中了**，望您理解。
