### ISSUE TITLE
【自荐项目】Concent

### ISSUE THREAD

**Issue by fantasticsoul** [521xueweihan/HelloGitHub#973]
## 项目推荐
- 项目地址：
https://github.com/concentjs/concent

- 文档地址：
https://concentjs.github.io/concent-doc/

- 类别：JS

- 项目后续更新计划：
核心功能和api已近稳定，后续注重于concli的开发，让用户可以快速生成concent的js & ts应用标准骨架项目

- 项目描述：
一个可预测、0入侵、渐进式、高性能的react增强型状态管理方案，基于依赖标记、引用收集和状态分发原理工作，让状态管理遁于无形，内置computed、watch、setup等高级特性，且对类组件和函数组件暴露100%一致的调用方式，抹平两者之间生命周期函数写法差异，这意味着不仅组件的逻辑复用更优雅，组件的表现形式也更将自由。

- 推荐理由：可预测、0入侵、渐进式、高性能、增强react组件能力、对ts友好、支持中间件和插件、兼容redux生态。

- 示例代码：
```js
import React, { Component, Fragment } from "react";
import { register, run, useConcent } from "concent";

run({
  counter: {// 定义counter模块
    state: {// 【必需】，定义state
      count: 0
    },
    reducer: {// 【可选】定义reducer，书写修改模块状态逻辑
      inc(payload = 1, moduleState) {
        return { count: moduleState.count + payload };
      }
    }
  }
});

class Counter extends Component {
  //setState 能够将数据将同步到store，广播到其他实例
  inc = () => {
    this.setState({ count: this.state.count + 1 });
  };
  //调用dispatch, 同样的能够将数据将同步到store，广播到其他属于counter模块或者连接到counter模块的实例
  incD = () => {
    this.ctx.dispatch("inc"); // or this.ctx.moduleReducer.inc()
  };
  render() {
    //concent注入counter模块的数据到state
    const { count } = this.state;
    return (
      <div style={{ padding: "12px", margin: "6px" }}>
        <div>count: {count}</div>
        <button onClick={this.inc}>inc by setState</button>
        <button onClick={this.incD}>inc by dispatch</button>
      </div>
    );
  }
}
//将Counter类注册为CcClazzCounter，属于counter模块
const CcClazzCounter = register("counter")(Counter);

// 抽到setup，setup函数只会在组件初次渲染前被调用一次！！！
const setup = ctx => {
  ctx.on('someEvent', (p1, p2)=>console.log(p1, p2));

  ctx.effect(() => {
    fetchProducts();
  }, ["type", "sex", "addr", "keyword"]);//这里只需要传key名称就可以了
   /** 对应useEffect, componentDidUpdate */

  ctx.effect(() => {
    return () => {
      // 返回一个清理函数
      // 等价于useEffect, componentWillUnmout, 这里搞清理事情
    };
  }, []);

  inc = () => ctx.setState({ count: this.state.count + 1 });
  incD = () => ctx.dispatch("inc");
  //incD = () => ctx.moduleReducer.inc(); // 这样写更优雅
  return { inc, incD }; //返回结果收集到settings里
};

// 装配到类组件
const SetupCounter = register({ module: "counter", setup })(
  class extends Component {
    render() {
      const { count } = this.state;
      const { inc, incD } = this.ctx.settings;
      // 绑定 count  inc incD 到视图, return ui
    }
  }
);

// 装配到函数组件
const SetupCounterFn = React.memo(function() {
  const {
    state,
    settings: { inc, incD }; //api 只需要定义一次，不存在每次渲染都创建临时闭包函数了
  } = useConcent({ module: "counter", setup });
  // 绑定 count  inc incD 到视图, return ui
});

```
- 截图：
![hello-concent](https://raw.githubusercontent.com/fantasticsoul/assets/master/img/cc/hello.gif)

**Comment by 521xueweihan** [comment]
项目介绍很详细，如果可以用更加简单、通俗易懂的文字说明。
“这个项目是用来干嘛的，那就更完美了～”

一个可预测、0入侵、渐进式、高性能的react增强型状态管理方案。可以优化下这句话

**Comment by fantasticsoul** [comment]
> 项目介绍很详细，如果可以用更加简单、通俗易懂的文字说明。
> “这个项目是用来干嘛的，那就更完美了～”
> 
> 一个可预测、0入侵、渐进式、高性能的react增强型状态管理方案。可以优化下这句话

感谢反馈：

一个可预测、0入侵、渐进式、高性能的react增强型状态管理方案，基于依赖标记、引用收集和状态分发原理工作，让状态管理遁于无形，内置computed、watch、setup等高级特性，且对类组件和函数组件暴露100%一致的调用方式，抹平两者之间生命周期函数写法差异，这意味着不仅组件的逻辑复用更优雅，组件的表现形式也更将自由。

-------------修改为

 concent是一个兼容redux生态的渐进式&高性能状态管理方案，基于依赖标记、引用收集和状态分发原理工作，通过独有的实例上下文机制增强组件能力，抹平类组件和函数组件的生命周期函数写法差异，内置computed、watch、setup、event等高级特性，让逻辑复用更优雅、组件表现形式更丰富、应用架构更稳健。

__
你看看这样好些了吗

**Comment by fantasticsoul** [comment]
## 在线示例
- js version:
<p>
<a href="https://codesandbox.io/s/concent-guide-xvcej" rel="nofollow">
<img src="https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667" alt="Edit" data-canonical-src="https://codesandbox.io/static/img/play-codesandbox.svg" style="max-width:100%;"></a></p>

- ts version:
<p>
<a href="https://codesandbox.io/s/concent-guide-ts-zrxd5" rel="nofollow">
<img src="https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667" alt="Edit" data-canonical-src="https://codesandbox.io/static/img/play-codesandbox.svg" style="max-width:100%;"></a></p>
ts版本的代码仓库：https://github.com/fantasticsoul/concent-guid-ts

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
篇幅问题，本期暂不发布

**Comment by fantasticsoul** [comment]
> 月刊篇幅问题，本期暂不发布，望理解。

好的，了解了😀

**Comment by fantasticsoul** [comment]
> 月刊篇幅问题，本期暂不发布，望理解。

你好呀，看到很久都没有动静，不会忘了吧┭┮﹏┭┮

**Comment by 521xueweihan** [comment]
> > 月刊篇幅问题，本期暂不发布，望理解。
> 
> 你好呀，看到很久都没有动静，不会忘了吧┭┮﹏┭┮

我们的月刊每月 28 号发布，发布后会有通知和回复，清静候佳音。

**Comment by fantasticsoul** [comment]
好的

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 46 期](https://hellogithub.com/periodical/volume/46/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏
HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
