### ISSUE TITLE
网红生成器

### ISSUE THREAD

**Issue by daixiang0** [521xueweihan/HelloGitHub#974]
## 项目推荐
- 项目地址：https://github.com/a312863063/seeprettyface-generator-wanghong

- 类别：机器学习

- 项目后续更新计划：

- 项目描述：
基于StyleGAN的图片生成器

- 推荐理由：

网红的增多，让我们越来越脸盲。网红都有哪些特征？除了整容，还可以通过代码生成。以实际场景代入学习，适合初学者入门。

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
