### ISSUE TITLE
Golang爬虫项目集合，包括leetcode、酷狗、快手、掘金文章、精美壁纸等实例

### ISSUE THREAD

**Issue by jaydenwen123** [521xueweihan/HelloGitHub#977]
## 项目推荐
- 项目地址：
https://github.com/jaydenwen123/GolangSpider.git
- 类别：请从中选择（C、C#、C++、CSS、Go、Java、JS、Kotlin、Objective-C、PHP、Python、Ruby、Swift、其它、书籍、机器学习）
**Go**
- 项目后续更新计划：

- 项目描述：
  - 必写：这是个什么项目、能用来干什么、有什么特点或解决了什么痛点
这个一个完全用golang开发的爬虫项目，整个项目包含了近十个案例如爬虫爬取快手视频、酷狗音乐、电影票房、古诗文、图片、爬取leetcode题库等等。对于想学习爬虫的同学，绝对是一个极佳的项目，每个实例都有完整的readme文档，教读者如何分析网站接口，如何并发爬取数据
  - 可选：适用于什么场景、能够让初学者学到什么
1.能对爬虫感兴趣的同学，起到快速入门
2.对想学习golang的同学，快速熟悉golang的基本库以及并发、数据库、序列化等知识
  - 描述长度（不包含示例代码）: 10 - 256 个字符
本项目对互联网上比较典型的网站数据做了爬取，可以用来熟悉技术、但禁止用于商业化
- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？
爬虫是一项很有意思的活，可以利用技术做一些非常有趣的事情，希望这个项目可以给爬虫爱好者们一个入门以及抛砖引玉的作用

- 截图：（可选）gif/png/jpg
**leetcode**
![image](https://user-images.githubusercontent.com/38454179/71056145-230a2d00-2193-11ea-9232-aea989d2aec1.png)
![image](https://user-images.githubusercontent.com/38454179/71056155-2c939500-2193-11ea-856d-05c8de01511e.png)
![image](https://user-images.githubusercontent.com/38454179/71056165-36b59380-2193-11ea-95d7-3cd66f514179.png)
![image](https://user-images.githubusercontent.com/38454179/71056173-3ddca180-2193-11ea-8ef5-116899d1bf19.png)
![image](https://user-images.githubusercontent.com/38454179/71056187-48973680-2193-11ea-9dce-7cebdc7966b7.png)

**快手视频**
![image](https://user-images.githubusercontent.com/38454179/71056205-5b117000-2193-11ea-850f-2eaae43516c4.png)
![image](https://user-images.githubusercontent.com/38454179/71056228-6ebcd680-2193-11ea-8307-316bd2bff569.png)

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
