### ISSUE TITLE
基于Angular4实现的自动生成笔记的应用

### ISSUE THREAD

**Issue by linguowei** [521xueweihan/HelloGitHub#98]
## 项目推荐
- 项目名称：micro-note(微记)

- 项目地址：https://github.com/linguowei/micro-note/tree/master

- 项目语言：TypeScript

- 项目描述：一个用Angular实现的可以输入文章链接生成笔记的一个管理应用程序

- 推荐理由：国内目前Angular4的开源项目较少，该项目并不复杂但基本涉及了Angular4的基本特性和技术点，适合初学者学习

- 示例代码：

- 截图：![](http://ouo33aiyh.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202017-08-29%2009.41.31.png)

**Comment by 521xueweihan** [comment]
您推荐的项目，已成功收录在 [HelloGitHub 第 19 期](https://hellogithub.com/volume/19/)

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

最后，如果方便可以 Star ⭐️ 本项目，让更多人看到本项目。
