### ISSUE TITLE
golang worker pool

### ISSUE THREAD

**Issue by xxjwxc** [521xueweihan/HelloGitHub#980]
## 项目推荐
- 项目地址：https://github.com/xxjwxc/gowp

- 类别：Go

- 项目后续更新计划：

- 项目描述：
  -  golang 高性能异步并发线程池
  - 并发限制goroutine池。
  - 限制任务执行的并发性，而不是排队的任务数。
  - 无论排队多少任务，都不会阻止提交任务。
  - 用于控制并发访问，及并发执行

- 推荐理由：并发限制goroutine池,不会阻止提交任务，支持错误返回

- 示例代码：

```
package main

import (
	"fmt"
	"time"

	"github.com/xxjwxc/gowp/workpool"
)

func main() {
	wp := workpool.New(10)             //设置最大线程数
	for i := 0; i < 20; i++ { //开启20个请求
		ii := i
		wp.Do(func() error {
			for j := 0; j < 10; j++ { //每次打印0-10的值
				time.Sleep(1 * time.Second)
			}
			return nil
		})
	}

	wp.Wait()
	fmt.Println("down")
}
```

**Comment by 521xueweihan** [comment]
@xxjwxc 您好，月刊之前收录过这个项目：https://hellogithub.com/periodical/search/?q=https://github.com/aosen/gopool#gopool

能否简述下您的库和这个库的区别、优势之类的～

**Comment by xxjwxc** [comment]
区别：
gopool：是分布式连接池(做数据连接池的)
gowp：是异步线程池(非分布式，主要应用在并发性计算及访问方面，工具库类)

优势：业务场景不太一样，不好评论优势。自己看下来几个优点
1，非阻塞形式
2，接口定义简单
3，性能卓越。(比 https://github.com/gammazero/workerpool 高很多，且调用友好很多)
4，支持异常退出。异步及同步等待

**Comment by 521xueweihan** [comment]
**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 45 期](https://hellogithub.com/periodical/volume/45/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了《讲解开源项目》系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 45 期](https://hellogithub.com/periodical/volume/45/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了[《讲解开源项目》](https://github.com/HelloGitHub-Team/Article)系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
