### ISSUE TITLE
推荐一个自己的GitHub模板仓库

### ISSUE THREAD

**Issue by BruceMaa** [521xueweihan/HelloGitHub#988]
## 项目推荐
- 项目地址：
https://github.com/GithubTemplate/github-repository-template
- 类别：请从中选择（C、C#、C++、CSS、Go、Java、JS、Kotlin、Objective-C、PHP、Python、Ruby、Swift、其它、书籍、机器学习）
GitHub仓库模板
- 项目后续更新计划：
Spring Boot 仓库模板，Spring Cloud仓库模板还在完善中，后续计划推出Python、Golang和Rust等各个框架的仓库模板
- 项目描述：
  - 必写：GitHub Template，通过点击[<kbd>use this template</kbd>](https://github.com/GithubTemplate/github-repository-template/generate)按钮，可以快速的创建一个配置齐全的Repo，省却了规范`README.md`，`CHANGELOG.md`，`CONTRIBUTING.md`，`COMMIT_CONVENTION.md`，添加`PULL_REQUEST_TEMPLATE.md`，`ISSUE_TEMPLATE.md`和`Github Actions`等繁琐工作的时间。

- 推荐理由：一键生成一个配置齐全的Github Repo

- 示例代码：（可选）长度：1-20 行

- 截图：（可选）gif/png/jpg

<p align="right">谢谢</p>

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
