### ISSUE TITLE
Redis命令行可视化工具

### ISSUE THREAD

**Issue by kyai** [521xueweihan/HelloGitHub#989]
## 项目推荐
- 项目地址：

https://github.com/kyai/redis-cui

- 类别：

Go

- 项目后续更新计划：

增加日志
优化体验

- 项目描述：

一款简单、可视化的Redis命令行工具。

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？

以一种直观、易于阅读的形式，在终端查看Redis数据。

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
