### ISSUE TITLE
【开源项目推荐】doocs/md：一款高度简洁的在线微信 Markdown 编辑器

### ISSUE THREAD

**Issue by yanglbme** [521xueweihan/HelloGitHub#990]
## 项目推荐
- 项目地址：https://github.com/doocs/md

- 类别：JS

- 项目后续更新计划：
对项目进行重构，使用 Vue-cli 脚手架进行开发。

- 项目描述：
[![github](https://badgen.net/badge/⭐/GitHub/cyan)](https://github.com/doocs/md) [![gitee](https://badgen.net/badge/⭐/Gitee/cyan)](https://gitee.com/doocs/md) [![PRs Welcome](https://badgen.net/badge/PRs/welcome/green)](http://makeapullrequest.com) [![license](https://badgen.net/github/license/doocs/md)](https://github.com/doocs/md/blob/master/LICENSE) [![release](https://img.shields.io/github/v/release/doocs/md.svg)](https://github.com/doocs/md/releases)
这是一款高度简洁的微信 Markdown 编辑器，可以将 Markdown 文档自动实时渲染为微信图文，让你不再为微信文章排版而发愁！只要你会基本的 Markdown 语法，就能做出一篇样式简洁而又美观大方的微信图文。

- 推荐理由（亮点）：
 支持色盘取色，并一键替换颜色；
 支持自定义 CSS 样式并实时渲染；
 支持多图上传并将 URL 插入编辑器光标定位处。

- 截图：
![select-and-change-color-theme](https://raw.githubusercontent.com/doocs/md/master/assets/images/doocs-md-select-and-change-color-theme.gif)
![copy-and-paste](https://raw.githubusercontent.com/doocs/md/master/assets/images/doocs-md-copy-and-paste.gif)
![custom](https://raw.githubusercontent.com/doocs/md/master/assets/images/doocs-md-custom-css.gif)
![doocs-md-upload-image](https://raw.githubusercontent.com/doocs/md/master/assets/images/doocs-md-upload-image.gif)

**Comment by 521xueweihan** [comment]
类似项目推荐过很多个了，该项目暂不能收录到月刊中。
