### ISSUE TITLE
让性能飞起来——Redis开发最佳实践

### ISSUE THREAD

**Issue by ITcathyh** [521xueweihan/HelloGitHub#992]
## 项目推荐
- 项目地址：https://github.com/ITcathyh/redis-best-practice

- 类别：Java、C、C#、C++、Go、PHP、Python、Ruby、Swift、其它

- 项目后续更新计划：持续跟版本更新

- 项目描述：
  - 项目说明：Redis开发最佳实践，紧跟Redis版本发布更新。帮助规范Redis的使用，让系统能够通过更好地运用缓存组件来多方位提升获得性能的提高。
  - 适用场景：适用于任何使用到Redis的场景，让他人能了解到Redis怎么用能够更好地帮助自己提升系统性能，并避免产生线上问题
  - 描述长度（不包含示例代码）: 1684字

- 推荐理由：
1.紧跟版本更新，非陈年旧识
2.列出各类注意问题，帮助避免出现线上事故
3.帮助大幅提升系统性能

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
