### ISSUE TITLE
一个安全高效的Golang并发执行工具库

### ISSUE THREAD

**Issue by ITcathyh** [521xueweihan/HelloGitHub#993]
## 项目推荐
- 项目地址：https://github.com/ITcathyh/conexec

- 类别：Go

- 项目后续更新计划：拓展更多方式的多任务并发执行，如拓扑图、执行打点等

- 项目描述：
[![Build Status](https://travis-ci.org/ITcathyh/conexec.svg?branch=master)](https://travis-ci.org/ITcathyh/conexec)[![codecov](https://codecov.io/gh/ITcathyh/conexec/branch/master/graph/badge.svg)](https://codecov.io/gh/ITcathyh/conexec)[![Go Report Card](https://goreportcard.com/badge/github.com/ITcathyh/conexec)](https://goreportcard.com/report/github.com/ITcathyh/conexec)[![GoDoc](https://godoc.org/github.com/ITcathyh/conexec?status.svg)](https://godoc.org/github.com/ITcathyh/conexec)

conexec是一个用于并发执行多任务的工具库。它简单而高效，支持设置全局的超时时间，以及对异常情况进行快速响应

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？
使用简单方便
执行高效
对异常情况处理完善
支持超时设置

- 示例代码：
```
	c := NewActuator()
	c.WithTimeOut(time.Second) // set time out
	err := c.Exec(
		func() error {
			fmt.Println(1)
			time.Sleep(time.Second * 2)
			return nil
		},
		func() error {
			fmt.Println(2)
			return nil
		},
		func() error {
			time.Sleep(time.Second * 1)
			fmt.Println(3)
			return nil
		},
	)
	
	if err != nil {
		// ...do sth
	}
```

**Comment by 521xueweihan** [comment]
非常感谢您推荐项目。

**该项目暂不能收录到 HelloGitHub 月刊中**，HelloGitHub 推荐项目审核标准 #271。
期待持续完善该项目，后续推荐更多的项目。

再次感谢您对 HelloGitHub 的支持 🙏
