### ISSUE TITLE
 LuckyFrameWeb

### ISSUE THREAD

**Issue by hellowHuaairen** [521xueweihan/HelloGitHub#996]
## 项目推荐
- 项目地址：https://gitee.com/seagull1985/LuckyFrameWeb

- 类别：Java

- 项目描述：LuckyFrame测试平台是一款免费开源的测试平台，最大的特点是全纬度覆盖了接口自动化、WEB UI自动化、APP自动化，并且支持分布式测试。

- 推荐理由：测试关键字驱动也很大程度上解决了测试同学代码基础弱的问题。同时也集成了质量管理相关的一些功能，解决QA的日常工作中，项目过程数据的收集问题，并能展示一些简单质量报表。

- 截图：（可选）gif/png/jpg
![image](https://user-images.githubusercontent.com/19610305/71417926-01cda300-26a3-11ea-9264-0505a9d98bdb.png)
![image](https://user-images.githubusercontent.com/19610305/71417934-0db96500-26a3-11ea-91b5-7f79e89abbc2.png)
![image](https://user-images.githubusercontent.com/19610305/71417937-127e1900-26a3-11ea-886b-2f78dbfd7724.png)
![image](https://user-images.githubusercontent.com/19610305/71417944-190c9080-26a3-11ea-9690-193b4e369dca.png)

**Comment by 521xueweihan** [comment]
@hellowHuaairen 暂不接受非 github 平台的项目

**Comment by hellowHuaairen** [comment]
好的
