### ISSUE TITLE
号称世界上最简洁的人脸识别库

### ISSUE THREAD

**Issue by GatesMa** [521xueweihan/HelloGitHub#999]
## 项目推荐
- 项目地址：https://github.com/ageitgey/face_recognition

- 类别：机器学习

- 项目后续更新计划：本项目的人脸识别是基于业内领先的C++开源库 dlib中的深度学习模型，用Labeled Faces in the Wild人脸数据集进行测试，有非常高的准确率。但对小孩和亚洲人脸的识别准确率尚待提升。

- 项目描述：
  本项目**号称世界上最简单的人脸识别库**，可使用 Python 和命令行进行调用。该库使用 dlib 顶尖的深度学习人脸识别技术构建，在户外脸部检测数据库基准（Labeled Faces in the Wild benchmark）上的准确率高达 **99.38%**，该项目提供了一个简单的面部识别命令行工具，允许您对来自命令行的图像文件夹进行面部识别。对于初学者，可以通过这个项目感受人脸识别或机器学习带来的乐趣。

- 推荐理由：使用世界上最简单的面部识别库从Python或命令行识别和操作面部。项目是一个强大、简单、易上手的人脸识别开源项目，并且**配备了完整的开发文档和应用案例**，特别是兼容树莓派系统。

- 示例代码：
```
# 定位图片中的所有人脸：
import face_recognition
image = face_recognition.load_image_file("your_file.jpg")
face_locations = face_recognition.face_locations(image)

# 识别人脸关键点，包括眼睛、鼻子、嘴和下巴
import face_recognition
image = face_recognition.load_image_file("your_file.jpg")
face_landmarks_list = face_recognition.face_landmarks(image)
```

- 截图：

![image](https://user-images.githubusercontent.com/42234931/71430433-bc42c180-2706-11ea-8eae-e69901b778bd.png)
![image](https://user-images.githubusercontent.com/42234931/71430445-d086be80-2706-11ea-9cce-d11625eda7d9.png)

**Comment by 521xueweihan** [comment]
非常详尽、通俗易通的介绍和项目描述，项目也很适合新手学习和使用。欢迎持续推荐，成为我们的核心贡献者（成功收录 10 项目）

**您推荐的项目已收录到专栏**，后续有最新进展会在此 Issues 进行通知。
欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中。谢谢 🙏

**Comment by 521xueweihan** [comment]
您推荐的项目，**已成功发布**在 [HelloGitHub 第 45 期](https://hellogithub.com/periodical/volume/45/)，并把您添加到了[贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)中。

欢迎继续推荐如此优秀的项目、告诉其他小伙伴加入到 HelloGitHub 项目中，没有 star 本项目的请 star 一下。谢谢 🙏

HG 发起了《讲解开源项目》系列，欢迎项目作者参与（全平台免费单推您的项目）。有兴趣可以加我微信：xueweihan（备注您发起的项目名称）
